### ISSUE TITLE
Steam won't show battery life in-game overlay.

### ISSUE THREAD

**Issue by TheBatman** [ValveSoftware/steam-for-linux#3956] opened 2015-08-08 23:46 UTC
Hello i have been using Linux for my laptop (Ubuntu 14.04LTS) and theres a missing feature, steam is not showing the battery bar while on windows it shows it and advises me when my battery is low.

i'm not sure if this is a missing feature or is an error im a newbie btw.

PC specs:
OS:Ubuntu 14.04LTS 64bit
RAM:8GB of ram
Video Ram: 1GB
Graphic card: AMD radeon R5 with 1gb of vram
Processor:AMD A8-6410 APU x4

**Comment by kisak-valve** [comment] 2018-11-30 14:04
Closing as a duplicate of #3033.

**Closed by kisak-valve** 2018-11-30 14:05 UTC
Labels: overlay, reviewed
