### ISSUE TITLE
In-game GUI doesn't use same keyboard layout as Steam client

### ISSUE THREAD

**Issue by garciabruno** [ValveSoftware/steam-for-linux#3676] opened 2015-01-18 21:16 UTC
If you are in-game and SHIFT + TAB to open the graphical layout, any input (such as Chat window) won't use the same keyboard layout as the OS.

My keyboard layout happens to be in Spanish and I can't type things like: á é í ñ ç...etc.

**Comment by mrluisiko99** [comment] 2016-01-31 00:58
+1. I also occurs within games. It is impossible to assign a key to a function in the game, so some actions are not working. PS: Sorry for my bad English

**Comment by mrluisiko99** [comment] 2016-01-31 01:02
#4267

**Comment by steffenWi** [comment] 2016-11-01 18:56
This is still an issue. For me it's äöüß that aren't working.

**Comment by steffenWi** [comment] 2016-11-09 19:19
This is ridicoulus. When I open the Friends list from Steam itself, I can type @,ö,ä,ü and ß just fine in it's search box and a chat window. If I open the friends list from the Steam Overlay inside any game I can't type any of those letters.

**Comment by MartinPL** [comment] 2017-01-20 11:00
Can't type Polish characters only in overlay
Steam info 
> Wersja systemu operacyjnego:
>     Linux (64-bitowy)
>     Nazwa kernela: Linux
>     Wersja kernela: 4.8.13-1-ARCH
>     Dostawca serwera X: The X.Org Foundation
>     Wydanie serwera X: 11901000
>     Menedżer okien X: GNOME Shell
>     Wersja biblioteki Steam: steam-runtime-beta-release_2016-12-05
>     
>     
> Dodatki:
>     Język interfejsu: Polski
>     JĘZYK: **pl_PL.UTF-8**

**Comment by MartinPL** [comment] 2017-03-27 17:06
It would be nice if this error was fixed

**Comment by kisak-valve** [comment] 2017-04-18 18:00
Closing as a duplicate of #2122.

**Closed by kisak-valve** 2017-04-18 18:00 UTC
Labels: overlay, reviewed
