### ISSUE TITLE
Download buttons have no apparent effect in Steam client

### ISSUE THREAD

**Issue by codingthat** [ValveSoftware/steam-for-linux#6943] opened 2020-03-02 22:36 UTC
#### Your system information

* Steam client version (build number or date): Feb 11 2020 (latest, according to trying to update)
* Distribution (e.g. Ubuntu): Linux Mint 19
* Opted into Steam client beta?: [Yes/No]  No
* Have you checked for system updates?: [Yes/No]  Yes

#### Please describe your issue in as much detail as possible:

I've always been able to click Download to download games via the Steam client.

Today, after hitting #6942 , which seems unrelated, I was no longer able to.

#### Steps for reproducing this issue:

0. Open the Steam client.
1. On the Store page, search for Interrogation: You will be deceived.
2. On the page for that game, click the Download button next to "Free Demo".
3. The button springs with every click, but nothing happens, no matter how many times I click it.  The game is not added to my library and no download for it is listed in the Downloads screen.

Restarting Steam did not help.  Cold-booting my computer did not help either.

Running the equivalent steam:// install link in the terminal does work, but I've never had to do that before.

**Comment by codingthat** [comment] 2020-03-03 11:36
Opting into the Steam beta program solved this particular issue.  Clicking the link in the Steam client now opens a download window.  (I do find it odd that such core functionality was broken in a normal release though.  When will the current beta become standard, so I can opt out again?  I had intentionally stayed out of beta because I prefer a more stable experience to having the latest features.)

**Comment by arrowgent** [comment] 2020-03-04 23:14
it has broken several times, and been fixed

so... not sure why it isnt mentioned in the update logs

**Comment by byte1024** [comment] 2020-03-05 13:13
Another alternative, you can also open the store page in a regular browser, click the download button, and then allow it work with Steam application.

**Comment by codingthat** [comment] 2020-03-05 13:40
@arrowgent thanks for the confirmation.  @byte1024 actually if you see the referenced issue in the OP, that's exactly what I was trying to do the first time I encountered this error, and it didn't work.

**Comment by inguin** [comment] 2020-03-06 19:23
Same here. I noticed it a few times recently after purchasing a new title. I didn't give it much thought because installing from the library screen worked fine.

Today I tried to download a demo for a game, no success so far.

**Comment by codingthat** [comment] 2020-03-08 10:34
Update: I opted back _out_ of Steam Beta, which reinstalled the Feb 11 2020 non-Beta Steam client, and this issue is gone.  I was able to click the download button on https://store.steampowered.com/app/907000/The_Navigator/ within the Steam client, and it popped up a dialogue with a literal `%game%` in the title, followed almost immediately by the download/install options dialogue, which then worked fine.

**Comment by TTimo** [comment] 2020-03-09 22:58
This could just be the web code served by the Steam store. It's the same whether you are looking at the page in the Steam client or the store via a browser, and it'll update on it's own cycle independent from the Steam client.

Unless someone currently has this issue still reproductible, we will close.

**Comment by inguin** [comment] 2020-03-09 23:41
> Unless someone currently has this issue still reproductible, we will close.

I still see the issue. I click the "Download Demo" button on the [Factorio store page](https://store.steampowered.com/app/427520/Factorio/) and nothing happens.

**Comment by codingthat** [comment] 2020-03-10 10:00
I'm still seeing it too, as I said.  100% reproducible here both on beta and on non-beta.

Interesting point you bring up @TTimo though about web code—and actually I can confirm it's not related to that, because I can, with no Steam web sites open in my browser, open a new tab, type [steam://install/452280](steam://install/452280) in the address bar, hit Enter, and get the same result: my Steam client reverts to the main store page (or opens to it, if it wasn't already running.)

**Comment by TTimo** [comment] 2020-03-10 22:56
I see a workaround described, by going to the browser and using steam:// links. @codingthat had some problem in #6942 with the steam URL setup on his system that is now fixed.

Now everyone should be seeing the download button working in the steam beta client (even looks like you can go back to stable client afterwards?). If that's correct, then I think we can close.

(also, I do not know the schedule of beta client -> stable promotion .. "soon").

**Comment by codingthat** [comment] 2020-03-11 07:30
Sorry @TTimo  my last message was in error, I was conflating with issue #6942.  What I said in [the message before that](https://github.com/ValveSoftware/steam-for-linux/issues/6943#issuecomment-596190268) is correct though: opting into beta fixed it, and it stayed fixed when I opted out.

That said, I'm not sure @inguin of your status.  Did you try opting into Steam client beta?

**Comment by inguin** [comment] 2020-03-11 07:39
I can confirm that changing to beta fixes the issue. Going back to stable makes it return, though.

**Comment by TTimo** [comment] 2020-03-11 11:55
Fixed in beta.

**Closed by TTimo** 2020-03-11 11:55 UTC
Labels: Steam client
