### ISSUE TITLE
Steam mobile : Failed to connect to server [Android], latest steam version

### ISSUE THREAD

**Issue by Nu-Illasera** [ValveSoftware/steam-for-linux#10780] opened 2024-04-13 14:45 UTC
As the title says, i wish i could add more info but i can't.

> Tap "steam chat" app on mobile.
> Insert correct username
> Insert correct password

>> Sign in button tap

Error : "Failed to connect to steam".

This issue doesn't belong here and i don't care, i am spamming it anywhere i can since i can't get a hold of any steam tech support nor issues to open.

Please forward it to whoever it is that is responsible.

**Comment by kisak-valve** [comment] 2024-04-13 14:54
Hello @Nu-Illasera, your choice to repeatedly spam issue reports has resulted in a 1 day timeout.

Closing as a duplicate of https://github.com/ValveSoftware/steam-audio/issues/345.

**Closed by kisak-valve** 2024-04-13 14:54 UTC
