### ISSUE TITLE
Steam crashes when WPA3 is used

### ISSUE THREAD

**Issue by jrtberlin** [ValveSoftware/steam-for-linux#7832] opened 2021-06-05 08:10 UTC
* Steam client version (build number or date): 1622844577
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam crashes on startup with `libnm:ERROR:libnm-core/nm-setting-wireless-security.c:837:need_secrets: code should not be reached` when a WPA3 Wi-Fi network is configured.
This happened to me on more than one machine (Arch with KDE Plasma and Pop OS with GNOME).

I use an Intel Wi-Fi 6 AX200.

#### Steps for reproducing this issue:

1. Have a WPA3 network configured in Network manager
2. Try to start Steam
3. Observe `libnm:ERROR:libnm-core/nm-setting-wireless-security.c:837:need_secrets: code should not be reached`

#### Workaround

I got steam starting again by manually changing all Wi-Fi networks back to WPA2. This worked also on Pop OS.

**Comment by CJ1169** [comment] 2021-06-08 08:26
When on wired, disabling WiFi worked to get steam open. Had the same error code as you, but also the error codes displayed in https://github.com/ValveSoftware/steam-for-linux/issues/7842 and https://github.com/ValveSoftware/steam-for-linux/issues/7813. Perhaps this workaround will help those two issues?

**Comment by GerritDamen** [comment] 2021-06-08 11:00
Same here, changing the WiFi back to WPA2 is a workaround. Up until today, Steam worked fine with WPA3.

`steam -console
Running Steam on ubuntu 21.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/ssd2/Steam/ubuntu12_32/steam -console
[2021-06-08 12:47:17] Startup - updater built Jun  7 2021 19:27:32
Installing breakpad exception handler for appid(steam)/version(1623096420)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2021-06-08 12:47:18] Loading cached metrics from disk (/ssd2/Steam/package/steam_client_metrics.bin)
[2021-06-08 12:47:18] Using the following download hosts for Public, Realm steamglobal
[2021-06-08 12:47:18] 1. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-06-08 12:47:18] 2. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-06-08 12:47:18] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1623096420)
[2021-06-08 12:47:18] Checking for update on startup
[2021-06-08 12:47:18] Suche nach verfügbaren Updates...
[2021-06-08 12:47:18] Downloading manifest: https://cdn.cloudflare.steamstatic.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1623096420)
[2021-06-08 12:47:18] Download skipped: /client/steam_client_ubuntu12 version 1623096420, installed version 1623096420, existing pending version 0
[2021-06-08 12:47:18] Nothing to do
[2021-06-08 12:47:18] Installation wird überprüft...
[2021-06-08 12:47:18] Performing checksum verification of executable files
[2021-06-08 12:47:18] Verification complete
Loaded SDL version 2.0.15-6501165
Gtk-Message: 12:47:19.035: Failed to load module "gail"
Gtk-Message: 12:47:19.035: Failed to load module "atk-bridge"

(steam:5657): Gtk-WARNING **: 12:47:19.048: Im Modulpfad »adwaita« konnte keine Themen-Engine gefunden werden,
/home/xxxxxx/.themes/Orchis/gtk-2.0/main.rc:790: error: unexpected identifier 'direction', expected character '}'

(steam:5657): Gtk-WARNING **: 12:47:19.049: Im Modulpfad »adwaita« konnte keine Themen-Engine gefunden werden,
/home/xxxxxx/.themes/Orchis/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  12
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  13
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  14
xerror_handler: X failed, continuing
Installing breakpad exception handler for appid(steam)/version(1623096420)
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
Could not connect to X session manager: None of the authentication protocols specified are supported
[0608/124719.635957:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: browser
Installing breakpad exception handler for appid(steam)/version(1623096420)
Installing breakpad exception handler for appid(steam)/version(1623096420)
Installing breakpad exception handler for appid(steam)/version(1623096420)
Installing breakpad exception handler for appid(steam)/version(1623096420)
Installing breakpad exception handler for appid(steam)/version(1623096420)
Installing breakpad exception handler for appid(steam)/version(1623096420)
[0608/124719.669717:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0608/124719.669807:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1623094080
[0608/124719.669816:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0608/124719.669824:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
Installing breakpad exception handler for appid(steam)/version(1623096420)
Installing breakpad exception handler for appid(steam)/version(1623096420)
Installing breakpad exception handler for appid(steam)/version(1623096420)
Installing breakpad exception handler for appid(steam)/version(1623096420)
/usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so: undefined symbol: g_log_structured_standard
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Installing breakpad exception handler for appid(steam)/version(1623096420)
Installing breakpad exception handler for appid(steam)/version(1623096420)
[0608/124719.714197:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0608/124719.714237:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1623094080
[0608/124719.714243:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0608/124719.714245:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
[0608/124719.714626:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: gpu-process
CAppInfoCacheReadFromDiskThread took 95 milliseconds to initialize
[0608/124720.294469:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0608/124720.294508:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1623094080
[0608/124720.294514:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0608/124720.294518:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
[0608/124720.294886:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: utility
CApplicationManagerPopulateThread took 716 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Installing breakpad exception handler for appid(steam)/version(1623096420)
Installing breakpad exception handler for appid(steam)/version(1623096420)
Proceed to auto login
**
libnm:ERROR:libnm-core/nm-setting-wireless-security.c:837:need_secrets: code should not be reached
Bail out! libnm:ERROR:libnm-core/nm-setting-wireless-security.c:837:need_secrets: code should not be reached
Installing breakpad exception handler for appid(steam)/version(1623096420)
assert_20210608124717_1.dmp[5724]: Uploading dump (out-of-process)
/tmp/dumps/assert_20210608124717_1.dmp
/ssd2/Steam/steam.sh: Zeile 772:  5657 Abgebrochen             (Speicherabzug geschrieben) $STEAM_DEBUGGER $DEBUGGER_ARGS "$STEAMROOT/$STEAMEXEPATH" "$@"

assert_20210608124717_1.dmp[5724]: Finished uploading minidump (out-of-process): success = yes
assert_20210608124717_1.dmp[5724]: response: CrashID=bp-9a84fec3-71de-40b8-9558-d41b72210608
assert_20210608124717_1.dmp[5724]: file ''/tmp/dumps/assert_20210608124717_1.dmp'', upload yes: ''CrashID=bp-9a84fec3-71de-40b8-9558-d41b72210608''
`

**Comment by chewi** [comment] 2021-06-08 18:38
To be honest, I find it quite disturbing that WPA2 vs WPA3 makes any kind of difference to Steam. How you connect to the network is really none of its business.

**Comment by jrtberlin** [comment] 2021-06-08 19:07
@chewi maybe it has something to do with in-home streaming and device discovery.

**Comment by skyline75489** [comment] 2021-06-09 04:38
I'm seeing the exact issue after update yesterday.

**Comment by 3qu1tu5** [comment] 2021-06-09 05:13
I'm seeing the same thing on two of my PopOs systems, everything else in the house steam is fine, and yes both systems have WIFI6 cards. Everything was fine until today. Hopefully they push out a rollback until they figure out what part of the update caused this. I see the exact same error above when I run steam in terminal.

**Comment by slanderous-mambo** [comment] 2021-06-10 07:51
Since yesterday, I have the same issue on Fedora 34 with an Intel AX200 Wifi 6 card. This is on the non-beta release. Like for everyone else, switching to WPA2 makes Steam launch normally again.

[System information and log](https://gist.github.com/slanderous-mambo/76ecb253f3447c1b7c137f99e08c9a37)

**Comment by smcv** [comment] 2021-06-10 12:33
Is this crash happening with or without a 32-bit `libnm.so.0` on the host system?

If an up-to-date 32-bit `libnm.so.0` is available on your host system (for example `libnm0:i386` on Ubuntu or `lib32-nm` on Arch) but not currently installed, then you might find that installing it works around this issue. Please could someone try that and report back?

(I suspect this might be an incompatibility between the older `libnm.so.0` client library in the Steam Runtime, which didn't know about WPA3, and the newer NetworkManager service on the host system, which does.)

**Comment by smcv** [comment] 2021-06-10 12:39
> To be honest, I find it quite disturbing that WPA2 vs WPA3 makes any kind of difference to Steam. How you connect to the network is really none of its business.

I think it's keeping track of this information because when it runs in SteamOS mode as an "appliance"-style UI (`steam -bigpicture -steamos`), Steam is the component that is responsible for providing the UI for configuring wifi - the equivalent of what would be done by `gnome-shell` or `nm-applet` or equivalent on a typical desktop.

One way to avoid issues like this would be to avoid entering that code path when not in SteamOS mode, but I think the same code is currently used to determine whether you have network connectivity at all, so that it can go into offline mode if you don't. Ideally it would be using netlink (`GNetworkMonitor` or equivalent) for connectivity monitoring, and only talking to NM directly when actually in SteamOS mode.

**Comment by chewi** [comment] 2021-06-10 12:47
Thanks, Simon, I had similar thoughts myself after posting that and I like your suggestion.

I was aware that it interfaced with NetworkManager before and I always assumed that was just to check whether you were online or not. It's not effective on my system as I don't use NetworkManager but I still have it installed to satisfy the dependency.

I haven't hit this issue myself but a root password prompt from PolicyKit regarding NetworkManager has started appearing on my daughter's OpenSUSE system. I've worked around it for now but I should file an issue here. It may be related to this issue.

**Comment by smcv** [comment] 2021-06-10 13:06
For people who are experiencing this crash, another piece of information that would be useful is: if you look at the WPA3 network's configuration in `/etc/NetworkManager/system-connections/` (you'll need to do this as root), in the `[wifi-security]` section, what is the `key-mgmt` field?

For WPA2 it's typically `key-mgmt=wpa-psk`, but for your WPA3 network, I suspect it might be `sae` for WPA3 Personal (or maybe even `wpa-eap-suite-b-192` for WPA Enterprise, or `owe`). If someone can confirm that it is, that would help to make sure we're on the right track for avoiding the crash.

**Comment by jrtberlin** [comment] 2021-06-10 13:07
> Is this crash happening with or without a 32-bit `libnm.so.0` on the host system?
> 
> If an up-to-date 32-bit `libnm.so.0` is available on your host system (for example `libnm0:i386` on Ubuntu or `lib32-libnm` on Arch) but not currently installed, then you might find that installing it works around this issue. Please could someone try that and report back?
> 
> (I suspect this might be an incompatibility between the older `libnm.so.0` client library in the Steam Runtime, which didn't know about WPA3, and the newer NetworkManager service on the host system, which does.)

Installing `lib32-libnm` fixes the issue for me.

**Comment by smcv** [comment] 2021-06-10 13:09
> Installing `lib32-libnm` fixes the issue for me.

Thanks, that's consistent with what I thought the root cause might be. It looks like the older `libnm.so.0` client library in the Steam Runtime is not 100% compatible with newer NetworkManager services. I'll try to patch this for the next Steam Runtime update.

**Comment by jrtberlin** [comment] 2021-06-10 13:09
@smcv Thanks!

**Comment by smcv** [comment] 2021-06-10 17:02
The underlying libnm bug is fixed in https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/merge_requests/887, and a backport into the Steam Runtime is in progress.

**Comment by TTimo** [comment] 2021-06-11 21:17
Steam beta client has been updated with the fix and should no longer be crashing (June 11th). Please retest.

**Comment by jrtberlin** [comment] 2021-06-11 21:42
@TTimo  I can confirm that without `lib32-libnm` and WPA3 configured steam is starting again on build `1623445000` from June 11th.

**Comment by cybereality** [comment] 2021-06-19 11:48
I just upgraded my system to Wifi 6 and encountered this problem. I'm on Ubuntu 21.04 and using an Intel AX210 wifi card.

I can confirm that the following command has fixed my issue, Steam now opens and I can play games no problem:
~~~
sudo apt install libnm0:i386
~~~
I can also confirm that the WPA3 is in use:
~~~
key-mgmt=sae
~~~
I am not using the beta, so I'm not sure if this is fixed already, but I thought I would post just in case. Thanks.

**Comment by tnbp** [comment] 2021-06-27 18:50
Just opted in to the beta, which works for me when the regular version required me to delete my ~/.steam folder every time.

**Comment by smcv** [comment] 2021-06-27 23:51
Thanks, but if you don't have new information, we don't need "me too" reports. The current situation is:

* In the general availability (non-beta) branch, WPA3 will cause Steam to crash.
    * Workaround: have a 32-bit libnm installed (`libnm0:i386` on Debian/Ubuntu, `lib32-libnm` on Arch) which should prevent the crash.
* In the beta branch, WPA3 shouldn't be a problem any more.

A future update to the general availability branch should pick up the same fix that's in the beta.

> the regular version required me to delete my ~/.steam folder every time

That sounds like a different bug, probably #7813 (which is also present in the general availability branch but fixed in the beta branch, and is *not* avoided by installing a 32-bit libnm). If that is the bug you are experiencing, a less destructive workaround for the general availability branch is to configure Steam to stop remembering your password (https://github.com/ValveSoftware/steam-for-linux/issues/7813#issuecomment-861475454).

**Comment by tnbp** [comment] 2021-06-28 04:45
The bug still has the "Need Retest" label, so I confirmed the bug is gone in the beta.
Also no, it's not a different bug. The nug has to do with retrieving stored credentials (apparently) and does not occur when there are no stored credentials. Please don't patronize.

**Comment by bedawi** [comment] 2021-07-03 07:10
If you like to apply the workaround on **Fedora 34**, you need to install the "NetworkManager-libnm.i686" package.

```
sudo dnf install NetworkManager-libnm.i686
```

**Comment by blshkv** [comment] 2021-07-03 09:40
No, we don't need workaround. That's why we are here, not at fedora's bugzilla

**Comment by kisak-valve** [comment] 2021-07-20 18:37
Per "Fixed crashes when on a WPA3 wireless network" in the [2021-07-13](https://store.steampowered.com/oldnews/86266) Steam client update, closing as fixed.

**Closed by kisak-valve** 2021-07-20 18:37 UTC
Labels: Need Retest
