### ISSUE TITLE
Proton: Installation of Assassin's Creed Brotherhood and AC:II

### ISSUE THREAD

**Issue by Mushoz** [ValveSoftware/steam-for-linux#5649] opened 2018-08-23 07:41 UTC
#### Your system information

* Steam client version (build number or date): Steam Beta, latest as of 23rd of August 2018
* Distribution (e.g. Ubuntu): Antergos (Arch)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
This issue was originally opened on the Proton issue tracker, but on second thought this seems to be an issue with Steam for Linux instead, since Wine/Proton doesn't even get to start, since the installation doesn't complete successfully. Orginal issue: https://github.com/ValveSoftware/Proton/issues/68

I am trying out different games from my Steam library. Installing Assassin's Creed 1 works fine and plays correctly. However, when I try to install Assassin's Creed Brotherhood or Assassin's Creed: II a Window that says "Creating Local Game Files" pops up. This screen never completes.

In the background I do see the game being downloaded with progress going from 0% to 100%, however, said screen remains. I can only click "cancel" or the cross in the rightmost corner of the popup, but both will uninstall the game immediately.

FYI, Assassin's Creed Brotherhood runs fine when I run the Window's version of Steam through regular Wine. One thing I noticed is that this version uses Ubisoft Uplay Launcher to launch the game. Perhaps this is resulting in installation conflicts with Steam Play.

**Comment by Mushoz** [comment] 2018-08-23 07:47
Killing the steam client gets rid of the perpetual "Creating Local Game Files" screen as a workaround. However, clicking play now results in a "Failed to request product key from Steam, please try again in a few minutes." popup.

**Comment by unlimitedbacon** [comment] 2018-08-26 19:37
I had the same issue when I installed the game, and I am also getting the "Failed to request product key" message when I try to play it. I also have the game installed on my Windows box. Is there a way to copy the product key from there and enter it manually?

**Comment by veikk0** [comment] 2018-08-28 21:56
> Is there a way to copy the product key from there and enter it manually?

There is a "CD Key" entry in the links section when you select the game in Steam's library view. However, clicking it brings up that same Steam error pop-up that says "Failed to request product key from Steam, please try again in a few minutes." So it would seem this is a problem with retrieving the key at all, even manually, via the Steam Linux client.

**Comment by d4rkf4b** [comment] 2018-08-29 12:14
Have the same issue with "Driver: San Francisco"
Another drop of Ubisoft

**Comment by brandonrisell** [comment] 2018-11-10 05:13
I'm seeing this with Assassins Creed II. Installs, but the "Creating local game files" popup stays up. I kill steam and reopen. When trying to launch the game, "Failed to request product key from Steam".

**Comment by jvetulani** [comment] 2018-12-31 17:33
I'm getting the same with Assassin's Creed: Revelations

**Comment by Darklink999999** [comment] 2019-03-03 08:30
I also have the same problem with AC II.

**Comment by Mushoz** [comment] 2019-03-03 10:19
Still an issue for me as well. The game playes perfectly when I run the Windows version of steam itself in Wine, so it should definitely be playable. Would be a very happy man when I can ditch the Windows client completely and stuck with the native Linux steam client :)

**Comment by jomarocas** [comment] 2019-07-13 23:59
any progress for this, this i am think is possible for fix, but nothing to progress for fix various games

**Comment by mohkale** [comment] 2020-06-01 01:40
still definitely an issue.

**Comment by hsantos92** [comment] 2020-08-11 05:35
totally still an issue!!

**Comment by cverstege** [comment] 2020-11-12 09:34
I've tried some stuff but with no positive results. Maybe this helps the one at Valve trying to fix this issue. See https://github.com/ValveSoftware/steam-for-linux/issues/212#issuecomment-725009666

**Comment by cverstege** [comment] 2020-11-14 10:27
I think I found the cause of this Problem.

When installing Assassin's Creed 2 (https://steamdb.info/app/33230/) on Windows, it will only install the Windows CD Key DLC (https://steamdb.info/app/33361/), but not the Mac CD Key DLC (https://steamdb.info/app/33362/). It isn't even shown as an available DLC on the Windows Steam client.

In contrast, when installing the game on Linux, both CD Key DLCs are installed as well, but the Steam client can only fetch the Windows Key, but also wants to get the Mac key, as `ShowCDKeyOnLaunch` is set to true for both DLCs (see SteamDB links).

When launching the game on Windows, the Steam client will thus only try to get the Windows DLC Key, but the Linux client is trying to obtain the Windows and the Mac key on launch, which fails.

On Linux requesting the Windows Key with `steam steam://cdkeys/33361` works just fine. Requestig the Mac key with `steam steam://cdkeys/33362` will fail. Requesting the Mac Key on Windows will fail as well.
This is all expected behaviour I guess, as SteamPlay will only work with Windows titles.

So the problem here is that the steam Linux client wants to request all DLC keys when doing `steam steam://cdkeys/33230` but would only need the Windows DLC keys, as SteamPlay/Proton does only support running Windows Titles.
This is probably a problem with the steam Play configuration, as the Linux client will install the Mac only DLC with the Mac Key but then fails to get the key on startup.

@Plagman I hope you can work with all this information :)

**Comment by belgianGeek** [comment] 2020-11-19 09:19
> I think I found the cause of this Problem.
> 
> When installing Assassin's Creed 2 (https://steamdb.info/app/33230/) on Windows, it will only install the Windows CD Key DLC (https://steamdb.info/app/33361/), but not the Mac CD Key DLC (https://steamdb.info/app/33362/). It isn't even shown as an available DLC on the Windows Steam client.
> 
> In contrast, when installing the game on Linux, both CD Key DLCs are installed as well, but the Steam client can only fetch the Windows Key, but also wants to get the Mac key, as `ShowCDKeyOnLaunch` is set to true for both DLCs (see SteamDB links).
> 
> When launching the game on Windows, the Steam client will thus only try to get the Windows DLC Key, but the Linux client is trying to obtain the Windows and the Mac key on launch, which fails.
> 
> On Linux requesting the Windows Key with `steam steam://cdkeys/33361` works just fine. Requestig the Mac key with `steam steam://cdkeys/33362` will fail. Requesting the Mac Key on Windows will fail as well.
> This is all expected behaviour I guess, as SteamPlay will only work with Windows titles.
> 
> So the problem here is that the steam Linux client wants to request all DLC keys when doing `steam steam://cdkeys/33230` but would only need the Windows DLC keys, as SteamPlay/Proton does only support running Windows Titles.
> This is probably a problem with the steam Play configuration, as the Linux client will install the Mac only DLC with the Mac Key but then fails to get the key on startup.
> 
> @Plagman I hope you can work with all this information :)

Now I understand why the game won't launch, thank you ! Is there any way we can bypass this issue ?

**Comment by cverstege** [comment] 2020-11-19 11:23
> Now I understand why the game won't launch, thank you ! Is there any way we can bypass this issue ?

I don't think so. There apparently was a workaround by editing `~/.steam/steam/appcache/appinfo.vdf` and altering the registry parts to prevent steam from going for the key. But an update earlier this year broke this workaround as the steam client is checking the integrity of this file at every launch.
Starting steam in offline mode doesn't help either as it only displayed Games from the Orange Box for me, after I've altered `~/.steam/steam/appcache/appinfo.vdf`.

You can take a look at https://github.com/ValveSoftware/steam-for-linux/issues/212#issuecomment-725009666 and the following comments for things I've already tried. If you come up with another idea I will gladly try it.
I've posted my findings to all related issues for steam-for-linux and proton.

**Comment by mberndt123** [comment] 2021-04-30 00:09
I'm having this problem too with Assassin's Creed II. And running the `steam steam://cdkeys/33361` command from the console will retrieve the CD key just fine, only when I try to launch the actual game it will fail to retrieve the CD Key.

**Comment by thaewrapt** [comment] 2021-04-30 06:34
> steam steam://cdkeys/33361

Yeah, this command also works for me, I guess Steam just can't figure out that it needs this particular key to use when it's on Linux. The same happens for another affected Ubisoft title, Tom Clancy's Splinter Cell: Conviction, `steam steam://cdkeys/33370` shows the key while other two methods ("Manage CD keys" by menu or starting the game from Steam) fail with the error mentioned above.

**Comment by pdfrod** [comment] 2021-05-02 11:20
@mberndt123 have you tried the workaround I suggested [here](https://github.com/ValveSoftware/Proton/issues/190#issuecomment-735877518)?

**Comment by mberndt123** [comment] 2021-05-03 00:21
@pdfrod,
I've used [Steam-Metadata-Editor](https://github.com/tralph3/Steam-Metadata-Editor) to fix the Steam metadata and now things seem to work.
And honestly, this Ubisoft Connect nonsense is a good reason to never buy from Ubisoft again.

**Comment by NathanaelA** [comment] 2021-07-13 20:13
I want to comment on @mberndt123 solution, the https://github.com/tralph3/Steam-Metadata-Editor works great as long as you know where to put the `showcdkeyonlaunch` key...  

So for me making the `showcdkeyonlaunch: 0` does work at least for Assassins Creed Unity, however, a couple notes to expand:
1. You need to apply it to any DLC you have -- as several of the DLC's for AC: Unity also has this flag set to 1 and they will cause it to continue to fail.   
2. For both the game and EACH DLC, The section you want to add it to is:   "<STEAM_ID>" -> "modified" -> "appinfo" -> "extended" ----> "showcdkeyonlaunch: 0"

So the AC: Unity looks like (with all non-relevant sections stripped out):
```
{
  "289650": {
    "modified": {
       "appinfo": {
           "extended: {
              "showcdkeyonlaunch": 0
            }
        }
     }
  }
}
```

I just basically exported every single DLC and the game, and manually added the showcdkeyonlaunch: 0 to every one of the dlc's.   In addition on keys that seemed questionable, I made changes...   I'm not 100% if they are needed (but for completeness I'll list them here in case someone else finds that `showcdkeyonlaunch: 0` alone doesn't solve AC: Unity)

```
          "legacykeyregistrationmethod": "registry",      <--- Deleted
          "legacykeyregistrationmethod": "api",             <--- Deleted
          "supportscdkeycopytoclipboard": 1,                <--- Changed to 0
          "legacykeylinkedexternally": 1                         <--- Changed to 0
          "legacykeyproofofpurchaseticket": 1,              <--- Changed to 0
          "proofofpurchaseticketrevision": 1                   <--- Changed to 0
```

Just a warning: I've played the game on windows before, so my steam account is linked to my ubisoft account, however those keys might still be needed if you have never played the game before....

**Comment by smintman** [comment] 2021-11-19 15:29
Please please Valve can you resolve this we shouldn't need to hacking the files to get this to work, just correct the client incorrectly trying to request the Mac DLC!?!?

**Comment by smintman** [comment] 2022-02-14 11:27
@Plagman can you confirm if this planned to be resolved on for the upcoming steamdeck steam client?, I think it will result in uwanted steam deck compatibilty failures for games that otherwise work fine!

**Comment by smintman** [comment] 2022-03-31 20:15
The issue might be fixed, I updated my client (I'm on beta channel) and deleted the prefix and deleted the appcache.vdf (to clear any previous fixes) and I managed to start, update and play assassins creed 2 deluxe and brotherhood!
Also can request CD key without error!

Can others try to check the issue is resolved for them!!

**Comment by KnightOfCups** [comment] 2022-03-31 20:18
Confirmed on #212

**Comment by kisak-valve** [comment] 2022-05-13 23:21
Closing as fixed in the [2022-05-12](https://store.steampowered.com/oldnews/138198) Steam client update (uncredited).

**Closed by kisak-valve** 2022-05-13 23:21 UTC
Labels: Steam client, Need Retest, Proton
