### ISSUE TITLE
Context menus closing unexpectedly (like #320) with compiz

### ISSUE THREAD

**Issue by undeference** [ValveSoftware/steam-for-linux#4639] opened 2016-09-30 00:50 UTC
#### Your system information
- Steam client version: 

Steam client application
Built: Sep 20 2016, at 18:21:08
Steam API: v017
Steam package versions: 1474415843
- Distribution (e.g. Ubuntu): Fedora release 24 (Twenty Four) on x86-64 running MATE 1.15.1 with Compiz 0.8.12.3
- Opted into Steam client beta?: [Yes/No] No
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Context menus close after submenus disappear. Like #320.
#### Steps for reproducing this issue:
1. Right click on e.g., a friend's icon
2. Try to move mouse cursor to "Join Game"
3. Context menu closes when the cursor moves past "Invite to Group" (hovering "Invite to Group" properly opens the submenu, but when moving the mouse away, the entire context menu disappears)

**Comment by gdrewb-valve** [comment] 2016-09-30 00:54
Do you have focus-follows-mouse set or any other special focus options?

**Comment by undeference** [comment] 2016-09-30 02:08
No

**Comment by undeference** [comment] 2016-09-30 05:24
Apparently this only happens with compiz. Doesn't happen with marco

**Comment by undeference** [comment] 2016-10-23 18:46
With the build from "October 13 2016, at 00:48:25", if a tooltip is shown, the context menu also disappears. It makes viewing game info or inviting to game from the _friends who also play this game_ thing very difficult.

**Comment by undeference** [comment] 2016-12-04 05:22
This no longer happens

**Comment by undeference** [comment] 2016-12-04 05:22
Scratch that; it just no longer happens reliably

**Comment by kisak-valve** [comment] 2017-03-28 14:53
Closing as a duplicate of #3295.

**Closed by kisak-valve** 2017-03-28 14:53 UTC
Labels: Distro Family: Fedora, reviewed
