### ISSUE TITLE
Steam unable to launch games after upgrading to Mesa 22.3.0 from kisak-mesa

### ISSUE THREAD

**Issue by grimshins** [ValveSoftware/steam-for-linux#8967] opened 2022-12-03 02:46 UTC
#### Your system information

* Steam client version (build number or date): Dec 1 2022, at 22:40:28
* Distribution (e.g. Ubuntu): Ubuntu 22.04.1 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Unable to launch any applications following upgrade to Mesa 22.3.0 from the kisak-mesa PPA. Both native and Proton applications are affected.

#### Steps for reproducing this issue:

1. Open Steam
2. Launch any application

**Comment by kisak-valve** [comment] 2022-12-03 02:55
Hello @grimshins, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, if you completely close Steam, then run `steam` from a terminal, are there any hints in the terminal spew to go along with trying to run a game?

**Comment by kisak-valve** [comment] 2022-12-03 03:14
Nevermind, I see the issue here.

**Comment by grimshins** [comment] 2022-12-03 03:16
> Hello @grimshins, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, if you completely close Steam, then run `steam` from a terminal, are there any hints in the terminal spew to go along with trying to run a game?

https://gist.github.com/grimshins/3f60ba04aa76585891eba2e14f541e0d

When attempting to run Splitgate (native application), I get this:

`[2022.12.03-03.13.38:709][  0]LogCore: === Critical error: ===
Unhandled Exception: SIGSEGV: invalid attempt to read memory at address 0x000000000000031f

[2022.12.03-03.13.38:709][  0]LogCore: Fatal error!

0x00007f09178d924d ld-linux-x86-64.so.2!UnknownFunction(0x324d)
0x00007f0916d4cc28 libc.so.6!_dl_catch_exception(+0x87)
0x00007f0916d4ccf3 libc.so.6!_dl_catch_error(+0x32)
0x00007f0916c681ae libc.so.6!UnknownFunction(0x901ad)
0x00007f0916c67ed8 libc.so.6!dlclose(+0x27)
0x00007f086a2796c0 libvulkan_dzn.so!UnknownFunction(0x5e6bf)
0x00007f086a27a33b libvulkan_dzn.so!UnknownFunction(0x5f33a)
0x00007f086b636a29 libvulkan.so.1!UnknownFunction(0x36a28)
0x00007f0912195007 libVkLayer_MESA_device_select.so!UnknownFunction(0x3006)
0x00007f0894179e88 libVkLayer_steam_fossilize.so!UnknownFunction(0x42e87)
0x00007f088ff9463c steamoverlayvulkanlayer.so!vkCreateInstance(+0x5b)
0x00007f086b63ae28 libvulkan.so.1!UnknownFunction(0x3ae27)
0x00007f086b64229b libvulkan.so.1!vkCreateInstance(+0x56a)
0x0000000004fc5c9f PortalWars-Linux-Shipping!UnknownFunction(0x4dc5c9e)
0x0000000004fc4d89 PortalWars-Linux-Shipping!UnknownFunction(0x4dc4d88)
0x0000000004fc4abe PortalWars-Linux-Shipping!UnknownFunction(0x4dc4abd)
0x00000000050579d4 PortalWars-Linux-Shipping!UnknownFunction(0x4e579d3)
0x00000000029b7cd3 PortalWars-Linux-Shipping!UnknownFunction(0x27b7cd2)
0x00000000029b3ff1 PortalWars-Linux-Shipping!UnknownFunction(0x27b3ff0)
0x00000000062b75d8 PortalWars-Linux-Shipping!UnknownFunction(0x60b75d7)
0x00007f0916c01d90 libc.so.6!UnknownFunction(0x29d8f)
0x00007f0916c01e40 libc.so.6!__libc_start_main(+0x7f)
0x00000000029b0b49 PortalWars-Linux-Shipping!UnknownFunction(0x27b0b48)
`

**Comment by kisak-valve** [comment] 2022-12-03 03:41
So, the issue is a regression somewhere in mesa/dozen which causes it to interfere with 64 bit mesa/radv. In the short term, you can temporarily disable this driver with something like `sudo mv /usr/share/vulkan/icd.d/dzn_icd.x86_64.json /usr/share/vulkan/icd.d/dzn_icd.x86_64.json.disabled` or run steam with `VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json steam` from a terminal to avoid the driver as well.

This is clearly a mesa issue and needs to be pondered by a mesa dev. Please report it to mesa's gitlab issue tracker. I'll get a revised mesa build sent off to the build farm shortly.

Closing as not a Steam client issue.

**Closed by kisak-valve** 2022-12-03 03:41 UTC
Labels: Distro Family: Ubuntu
