### ISSUE TITLE
Clicking or double-clicking the tray icon does nothing (all distros)

### ISSUE THREAD

**Issue by arcooke** [ValveSoftware/steam-for-linux#4819] opened 2017-01-20 00:18 UTC
#### Your system information

* Steam client version: Jan 19 2017 Beta, 1484790260
* Distribution: KDE Neon 5.8.5
* Opted into Steam client beta?: Yes (same behavior on stable)
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Double-clicking the tray icon does nothing. It should open the library.  

Since you are updating the tray behavior right now, I thought I would mention this.  I've asked others using the newest update, and everyone has the same issue.  

This has never worked on any distro I've used.  Would appreciate if this could be looked into.  Thanks

**Comment by kisak-valve** [comment] 2017-01-20 00:23
Closing as a duplicate of #3519.

**Closed by kisak-valve** 2017-01-20 00:23 UTC
