### ISSUE TITLE
Ibus support for Linux (Steam does not detect input with Ibus).

### ISSUE THREAD

**Issue by jatin-cbs** [ValveSoftware/steam-for-linux#6473] opened 2019-08-29 02:28 UTC
I know this issue is a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/781
But it was written in 2013 and no steam devs are helping out so I just wanted to rise this up, Is there no way for us linux users to type in japanese ? Ibus is default for most gnome users and we have no support for that in steam. No IME works with steam on linux for japanese (my requirement) but other languages too. Ibus has all languages support for example Mozc for japanese but Valve doesnt gave any answer since 6 years now. Please Dont close this or else we know valve devs ignoring all issues now.

**Comment by kisak-valve** [comment] 2019-08-29 13:18
Hello @jatin-cbs, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #781.

**Closed by kisak-valve** 2019-08-29 13:18 UTC
