### ISSUE TITLE
Steam is ~~trying to redownload~~ UNINSTALLS certain games since proton-4.2.3

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#6236] opened 2019-04-22 23:31 UTC
This happens on ubuntu_18.04 and manjaro too.
Sometimes, when I validate the game files the issue gets resolved for certain games.

**Comment by trialism** [comment] 2019-04-22 23:34
Correction: steam DELETED those games completely!

**Comment by kisak-valve** [comment] 2019-04-22 23:37
Hello @trialism, can you check if this is a duplicate of #5745.

**Comment by trialism** [comment] 2019-04-23 00:11
@kisak-valve I had proton enabled globally.

**Comment by A-UNDERSCORE-D** [comment] 2021-01-14 02:35
Had this (or the other comment I made in #6543 ) happen to me today, this is the second time its occurred within a few months.

**Comment by kisak-valve** [comment] 2021-09-10 13:55
Hello @A-UNDERSCORE-D, have you seen this issue since https://github.com/ValveSoftware/steam-for-linux/issues/6543#issuecomment-795367480?

**Comment by A-UNDERSCORE-D** [comment] 2021-09-10 14:03
I have not but Ive also reinstalled my entire system since then so it may be that whatever circumstances are required no longer exist for me

**Comment by kisak-valve** [comment] 2021-09-10 14:18
Thanks for the feedback @A-UNDERSCORE-D. Because the reporting user has turned into a ghost, I'm closing this issue report.

**Closed by kisak-valve** 2021-09-10 14:18 UTC
Labels: Steam client, Need Retest, Proton
