### ISSUE TITLE
Client crashes on "Help > System Information"

### ISSUE THREAD

**Issue by matthew-cline** [ValveSoftware/steam-for-linux#4856] opened 2017-02-10 04:04 UTC
* System information gist: https://gist.github.com/matthew-cline/05ffc86d27205be2068cf121d177dd5a
* Steam client version (build number or date): Jan 19 2017, at 01:23:20
* Distribution (e.g. Ubuntu): Fedora  25
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

When, in the Steam client, I try to get system information from "Help > System Information", a window pops up with the information, stays there for about a second, and then the Steam client crashes.  The problem goes away if I start steam with `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0`.  When the crash happens, the following lines are output by the steam client:

    dbus[7899]: arguments to dbus_connection_ref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2686.
    This is normally a bug in some application using the D-Bus library.

This might be another manifestation of issue #4795, since:
1. I have the same issue.
1. That issue also goes away with `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0`
1. That issue also has something to do with d-bus.

**Comment by matthew-cline** [comment] 2017-02-12 04:24
[Here's the output of dbus-monitor](https://gist.github.com/matthew-cline/a26b9bbe0e0e40e6307c822b9c815d51) related to the problem. From after the system window opens to before the crash is the first part of the gist, before the line of "#"s. From the point that the client crashes is after the line of "#"s.

**Comment by matthew-cline** [comment] 2017-02-14 11:09
Oops, don't know how I missed this the first time: after the client's message about dbus, there's also this message:

    Bad thread local../common/steamservice.cpp (56) : Assertion Failed: m_hServiceLib == NULL
    Assert( Assertion Failed: m_hServiceLib == NULL ):../common/steamservice.cpp:56

**Comment by Vash63** [comment] 2017-04-06 09:30
I'm able to reproduce this in Arch Linux with the latest Steam beta client.  My system info:

https://gist.github.com/Vash63/1b230516d6d2ea5bfd253

**Comment by poppingtonic** [comment] 2017-04-26 08:52
I can't even file a report within Steam, because it crashes as soon as I click the (required) check box. I concur with @Vash63 , and here's my gdb output: https://gist.github.com/poppingtonic/b019b191aa713818cb198ec11879c4f3

**Comment by afettouhi** [comment] 2017-05-12 07:20
I can confirm this also on arch linux. Tried it with both the stable client og beta client.

**Comment by Majora320** [comment] 2017-05-27 00:28
Confirmed again on Arch Linux

**Comment by Vash63** [comment] 2017-05-28 08:28
I can no longer reproduce this on my Arch system. I run the Steam beta if you haven't tried that @Majora320

**Comment by afettouhi** [comment] 2017-05-28 08:31
I am still having this issue and I am running Steam beta (latest update).

**Comment by Majora320** [comment] 2017-05-28 16:37
Yeah, opting into the steam beta fixed it for me.

**Comment by OlliC** [comment] 2017-06-07 22:35
Can confirm this issue on Steam stable client. 

https://gist.github.com/OlliC/4cfd76dfa291bb19f55f

```
process 25522: arguments to dbus_connection_ref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file dbus-connection.c line 2686.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace

```

**Comment by TruboXL** [comment] 2017-06-28 11:40
This bug is still exist on Fedora 26, stable Steam
```
dbus[12715]: arguments to dbus_connection_ref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2686.
This is normally a bug in some application using the D-Bus library.

Bad thread local

../common/pipes.cpp (765) : CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected
steamclient.cpp (714) : Assertion Failed: bufRet.TellPut() == sizeof(uint8)
../common/processpipe_posix.cpp (492) : Assertion Failed: CCrossProcessPipe::BWrite: 32 (Broken pipe)
```

`STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` does fix it somewhat

**Comment by MKN-dev-LINUX** [comment] 2017-08-06 06:30
I am no longer experiencing this bug on Arch Linux with beta enabled.

**Comment by kisak-valve** [comment] 2017-08-23 15:04
Is anyone still seeing this issue with the current steam beta?

**Comment by ewe2** [comment] 2017-08-31 02:12
Yes I'm getting:
```
process 1491: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2794.
This is normally a bug in some application using the D-Bus library.
```
both with and without STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 on the beta update today. Steam is unresponsive and crashes soon afterwards.

**Comment by matthew-cline** [comment] 2017-08-31 06:15
The steam beta fixes the problem for me on Fedora 25.

**Comment by master-andreas** [comment] 2017-09-03 12:23
i am still expieriencing this steam beta on manjaro unstable (same with arch stable)

**Comment by vityafx** [comment] 2017-10-04 11:27
I also have it on the latest arch linux stable.

**Comment by Spanguole** [comment] 2017-10-05 16:06
Still crashes on latest steam client beta for me. I'm on funtoo.

**Comment by pouya-barzegar** [comment] 2017-10-29 20:15
i faced the same problem.
on arch linux
Linux parch 4.13.9-1-ARCH #1 SMP PREEMPT Sun Oct 22 09:07:32 CEST 2017 x86_64 GNU/Linux

**Comment by kisak-valve** [comment] 2019-11-29 14:41
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by afettouhi** [comment] 2019-11-29 15:10
No, this works on my steam beta client.

**Comment by kisak-valve** [comment] 2020-01-03 14:39
Thanks for retesting @afettouhi, closing.

**Closed by kisak-valve** 2020-01-03 14:39 UTC
Labels: Need Retest, Steam client
