### ISSUE TITLE
Steamwebhelper still active after closing Steam

### ISSUE THREAD

**Issue by k4os77** [ValveSoftware/steam-for-linux#4972] opened 2017-05-13 18:55 UTC
* Steam client version May 12 2017
* Distribution (e.g. Ubuntu): Debian 9 (64bit) [XFCE]
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

When I close Steam, Steamwebhelper keeps running. To stop it, I have to kill the process through the System Monitor.

Steps to reproduce:

1. Run Steam for Linux;
2. Close Steam;
3. Open your System Monitor application;
4. Enjoy 1 main Steamwebhelper process with 3 sub-processes.

NOTE: **Only the beta seems affected**

**Comment by kisak-valve** [comment] 2017-05-13 18:59
Also seen on Gentoo Linux since the 2017-05-08 beta client update.

**Comment by sysms** [comment] 2017-05-17 19:52
Confirmed on Debian Linux 8.

**Comment by k4os77** [comment] 2017-05-19 18:31
With Steam client version **May 19 2017**, the issue has been fixed.

**Comment by sysms** [comment] 2017-05-19 19:03
Indeed, but it introduces a very more serious bug for me: #4980

**Comment by kisak-valve** [comment] 2017-05-19 19:09
The missing SDL symbol issue is being tracked at #4951.

Thanks for retesting, closing.

**Closed by kisak-valve** 2017-05-19 19:09 UTC
Labels: Steam client

**Comment by LuciusofLegend** [comment] 2023-07-09 12:01
I'm actually having this same issue on Steam (Native) 1.0.0.75-3

**Comment by aljohnston112** [comment] 2025-10-24 03:29
This is still happening on Fedora 42
