### ISSUE TITLE
Steam Client has become very unresponsive

### ISSUE THREAD

**Issue by alosarjos** [ValveSoftware/steam-for-linux#10459] opened 2024-02-03 11:00 UTC
#### Your system information

* Steam client version (build number or date): 1706914901
* Distribution (e.g. Ubuntu): ArchLinux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Desktop: Gnome + Wayland
* Steam Logs: Getting an error?

```sh
tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs
tar: Removing leading `/' from member names
tar (child): /home/alosarjos/Desktop/steam-logs.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
/home/alosarjos/.steam/steam/logs/
/home/alosarjos/.steam/steam/logs/systemperfmanager.txt
tar: /home/alosarjos/Desktop/steam-logs.tar.gz: Cannot write: Broken pipe
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

* GPU: AMD

Steam Client has become very unresponsive, specially when opening new popup windows and such.

As you can see in the video, game library is kinda frozen, I'm running a game and the UI is not showing it as running, I'm trying clicking on the games, but it's not working and even the cursor is not changing to the "hand" to show is a clickable element. When going to the community tab, on the top side, there is like part of the library stuck. I think this started happening with a recent update that included the base chromium upgrade, but not sure at 100%

https://github.com/ValveSoftware/steam-for-linux/assets/29999427/54d1c8d8-f155-42ff-90e1-488bcadcb7a9

**Comment by KibaGasteiz** [comment] 2024-02-03 11:56
This is also happening to me, and sometimes steam runtime goes to "not responding" state when launching a Proton game then the full client resets and then the game launches, can't reproduce anymore but i think it only happens when i launch a recently installed game, the thing is that the client became very unresponsive lately.
The library goes unresponsive when i've been a lot of time not touching it, for example i'm just browsing on firefox and when i return to Steam it needs like 5 seconds to "wake up".

**Comment by Saeuissimus** [comment] 2024-02-04 14:18
I'm seeing something similar to #9880 and the same workaround described there works for me. Could you try it out to see if the problem is related?

**Comment by alosarjos** [comment] 2024-02-04 14:40
Looks like it, switching desktops and going back reproduces the error and resizing the window fixes it too.

**Comment by alosarjos** [comment] 2024-02-04 14:51
But also, changing my "online status" on the windows friends, freezes the UI temporary

**Comment by TTimo** [comment] 2024-02-05 20:04
Are you all using gnome+wayland, on an AMD GPU?

**Comment by alosarjos** [comment] 2024-02-05 20:05
> Are you all using gnome+wayland, on an AMD GPU?

Yes

**Comment by alosarjos** [comment] 2024-02-05 20:50
In case it helps, another demo...

https://github.com/ValveSoftware/steam-for-linux/assets/29999427/30850a88-c119-429a-b286-241063281280

**Comment by wescode** [comment] 2024-02-05 23:35
Same issue, resizing the window fixes the problem. Specs below:

- Fedora 39 kernel 6.7.3
- 7900xt Mesa 23.3.4
- Gnome 45.3 on Wayland

**Comment by Saeuissimus** [comment] 2024-02-06 02:44
>Are you all using gnome+wayland, on an AMD GPU?
I'm using i3+xorg server on an AMD GPU.

**Comment by SpiritWinD86** [comment] 2024-02-06 13:44
I'm experiencing the same issue with steam library window. (resizing steam window helps until minimizing\closing window in tray).
Nobara39 (gnome+wayland+AMD gpu).

**Comment by BetaVersionBY** [comment] 2024-02-06 14:33
Same issue with library window after minimizing Steam to tray. Workaround with resizing Steam window works.
Debian, LXQt, X11, RX7600/Mesa3D

**Comment by alosarjos** [comment] 2024-02-06 15:00
@TTimo Yeah, I can use the rest of the desktop and apps perfectly fine. Using escape doesn't seem to do anything.

**Comment by saffroy** [comment] 2024-02-07 10:39
> Are you all using gnome+wayland, on an AMD GPU?

No. Same issue here on XFCE+Xorg, AMD GPU.

Not sure if related, but it reminds me of #9598 in that it seems that certain windowing events are somehow blocked or lost until a certain kind of event makes things right again.

BTW, switching virtual desktops also triggers the issue, also "fixed" by resizing the window.

**Comment by hifron** [comment] 2024-02-07 14:17
Steam uses Chrome under the hood and it is not ready for GPU acceleration. For me it freezes Steam when I use GPU accel, but as I read another forum threads on this topic it differs with users but as I know Chrome is not ready for GPU acceleration with some drivers and if it worked and now not, it is problem. But maybe Chrome based and therefore also in Steam.

**Comment by BetaVersionBY** [comment] 2024-02-07 14:24
> Steam uses Chrome under the hood and it is not ready for GPU acceleration.

Yes, disabling GPU rendering for web pages fixed that problem for me.

**Comment by eris667** [comment] 2024-02-07 14:32
I'm experiencing the same issue with steam library window. (testing disabling hardware decoding, so far it appears to have resolved the symptoms).
Nobara39 (KDE+wayland+AMD gpu).

**Comment by Leopard1907** [comment] 2024-02-07 21:10
Same issue here as well. Arch Linux, radeonsi and Kde Wayland.

App tries to resize itself but fails when gpu accel for web view client option is enabled. Problem goes away when it is turned off.

It is a regression as i kept that on all the time, first time seeing it cause this issue.

**Comment by CypherDragon** [comment] 2024-02-08 11:52
Also the same issue, Arch Linux, KDE x11, AMD GPU/amdgpu driver

Library UI freezes after minimizing/closing Steam UI

Disabling gpu accel for web view resolves issue, along with other workarounds, eg resizing the window

+1 on a regression, haven't seen this issue before

**Comment by tgurr** [comment] 2024-02-08 12:15
> Also the same issue, Arch Linux, KDE x11, AMD GPU/amdgpu driver

Hesitated to add a +1 as I didn't see anyone else before reporting on this issue using KDE Plasma & X11. So same here, Exherbo Linux also on KDE Plasma **X11** session with amdgpu (kernel 6.7.4 / mesa 24.0.0 / linux-firmware 20240115).

**Comment by ojsl1** [comment] 2024-02-09 04:08
+1 for regression on the current steam beta (1707265912), cant repro it after switching to steam stable (1705108172).
Fwiw I tried both mesa-git:24.1.0 and mesa:23.3.5 on the steam beta but that didn't seem to have any effect on the freezing.

Manjaro, KDE x11, amdgpu, kernel 6.1.77

**Comment by ApatheticVaporeon** [comment] 2024-02-10 20:45
Having this issue as well. 

Fedora 39 KDE (Wayland)
Steam RPM (reproduced on flatpak as well)
7900xtx

**Comment by outfrost** [comment] 2024-02-10 21:27
Library in current client beta freezes every time I close the window. When I open it back up (right click Steam tray -> Library), the library portion of the window is frozen, and the close button (X) is highlighted in red, until I resize the window or restart Steam. Disabling GPU acceleration in web views does indeed work around the problem.

* Steam client version: 1707518866
* Distribution: Manjaro stable
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Desktop: KDE Plasma 5.27.10 on X11
* GPU: AMD RX 5700 XT (mesa 23.3.3, amdgpu 23.0.0, linux 6.6.10)

**Comment by deathxxx123** [comment] 2024-02-12 18:04
For me, steam client has great lag just like 30sec after start,
I fix this when remove all non-valve protons.
I just found that few days before.

**Comment by dtantono** [comment] 2024-02-13 08:12
I am using Intel igpu with Kubuntu and I got same problem which is Steam cause my computer very slow unless I close the app.

**Comment by alosarjos** [comment] 2024-02-14 06:12
Looks like it's fixed with todays beta update. I would encourage people to give it a try, and if no one complains today, I'll close the issue

**Comment by SpiritWinD86** [comment] 2024-02-14 10:09
> Looks like it's fixed with todays beta update. I would encourage people to give it a try, and if no one complains today, I'll close the issue

Can confirm, it is fixed with the latest steam beta update (Steam Version: 1707871101).

**Comment by TTimo** [comment] 2024-02-14 14:54
Thank you for testing. The primary AMD+mesa issue is fixed in Steam beta client, closing. Since this became a bit of a catch all, if you are still having issue please open a separate report.

**Closed by TTimo** 2024-02-14 14:54 UTC
Labels: Steam client, Need Retest, Distro Family: Arch, Web Component

**Comment by SpiritWinD86** [comment] 2024-03-09 16:59
It's happening again.
(Steam Beta Branch:  Steam Beta Update
Steam Version:  1709920887
Steam Client Build Date:  Thu, Mar 7 10:29 PM UTC -08:00
Steam Web Build Date:  Fri, Mar 8 4:12 AM UTC -08:00
Steam API Version:  SteamClient021)
(Operating System Version:
"Nobara Linux 39 (GNOME Edition)" (64 bit)
Kernel Name: Linux
Kernel Version: 6.7.6-201.fsync.fc39.x86_64
X Server Vendor: The X.Org Foundation
X Server Release: 12101099
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20240304.79797)

**Comment by ojsl1** [comment] 2024-03-09 17:16
I was about to comment on how I cant repro on 1709757778 beta, but after running the client again and updating to the newest 1709920887 beta it's now happening to me too.

Manjaro, KDE Plasma 6.0.1, Wayland, kernel 6.8.0rc7

**Comment by alosarjos** [comment] 2024-03-09 17:20
The issue seems to be simply the GPU acceleration on the client. I ended up disabling it some time ago. Even when the unresponsiveness was fixed, the client still freezes a lot when interacting with other client windows (Like the friends like).

Chrome and HW acceleration on Linux has never been stable at all for me. Not sure this is something on Valves side...
