### ISSUE TITLE
Big picture does not redraw when switching TTY

### ISSUE THREAD

**Issue by haikarainen** [ValveSoftware/steam-for-linux#3630] opened 2014-12-13 06:07 UTC
# Some needed context

I have set up steam so that when I login on a certain account it will open steam in big picture mode automatically. I have given steam it's own account (for security, as steam will not work with 0600 file/0700 dir permissions in home directories), and I switch between sessions (TTYs) to switch between my gaming session in steam big picture and regular-usage session.
# The problem

When I do the TTY/session switching, big picture will not redraw. It's stuck on a black screen, although I can hear that it's actively responding to input and whatnot. Alt+tabbing out and in will change the black screen with whatever was in the screens buffer (wallpaper etc), but it will still not redraw.
# Possible solution

Force screen redraws when window gains focus.
# Technical details

Lenovo Flex 2 14"
_Intel Core i7 4510U_
_Integrated Intel HD 4400 (Not used)_
_NVIDIA GT840M 4GB_

Running KDE5 with SDDM under ArchLinux x64. Have proprietary nvidia drivers installed, with the integrated chipset disabled (Get bad performance with optirun/primusrun)

**Comment by aldrik** [comment] 2015-01-02 22:25
I also have this issue, it is not limited to big-picture mode. The issue is not visible if/while there is a desktop compositor running. And it's Nvidia only, no such issue if I switch to intel drivers/hardware.

**Comment by haikarainen** [comment] 2015-06-11 15:42
>11 June	- New Steam Client Beta - June 10th
>
>...
>
>Linux 
>Fixed Steam Big Picture freezing and graphics corruption when switching sessions

Is this a fix for this issue?

**Comment by aldrik** [comment] 2016-07-26 22:46
> Is this a fix for this issue?

I can't reproduce this issue any more.

**Comment by kisak-valve** [comment] 2018-05-04 14:55
Hello @haikarainen, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment] 2018-06-08 12:18
Closing assumed a driver issue. In general, nVidia's proprietary driver has long standing issues related to use of VTs.

**Closed by kisak-valve** 2018-06-08 12:18 UTC
Labels: Big Picture, NVIDIA drivers, Need Retest, reviewed

**Comment by haikarainen** [comment] 2018-06-08 13:04
Oh sorry I have missed your question. I haven't been on an Nvidia/Linux system in years, so I haven't and can not test it.
