### ISSUE TITLE
{Steam Controller API } -- Can't change controller template from official [HL, HL2] 

### ISSUE THREAD

**Issue by CEOofUnhandledExceptions** [ValveSoftware/steam-for-linux#11334] opened 2024-10-09 23:29 UTC
Sys; 
- Steam Deck (OLED), SteamOS (Stable)
Affected Games;
- Half-Life, Half-Life 2
 
Summary;
Simply attempting to change the layout from official to anything else is not possible; any deviation is immediately reset upon launching the affected titles. This issue is not yet present in other Source/GoldSrc titles.
I believe the issue is caused by whatever special version(s) of the Steam Controller API which have been assigned to HL / HL2.

#### Steps for reproducing this issue:

1.  Change or modify the official controller template for Half-Life 1/2 to literally anything else
2.  Immediately have your template overridden back to official
2.5. Your own template is now labelled as 'incompatible' (despite still working fine with every other Source/GoldSrc title)
3.  Realize you have no choice but to to press Y to reload
4.  Permanently quit playing the affected game(s)

**Comment by kisak-valve** [comment] 2024-10-09 23:36
Hello @CEOofUnhandledExceptions, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #10966.

**Closed by kisak-valve** 2024-10-09 23:36 UTC
