### ISSUE TITLE
Chat window displays Hebrew letters in reversed order.

### ISSUE THREAD

**Issue by Okoyl** [ValveSoftware/steam-for-linux#240] opened 2012-12-21 20:12 UTC
when Chatting with my friends in Hebrew, the letter order is displayed reversed, for example:
instead of seeing אני מסכים איתך
you see: ךתיא םיכסמ ינא

the only problem is the display, when typing it sends correctly.
My friends who tried Steam Linux confirmed it.

**Comment by shytzedaka** [comment] 2016-10-28 13:37
and yet again 4 years later steam Has not fixed this issue.

**Comment by Jelomite** [comment] 2016-11-15 17:45
Does anyone have a solution for this? Even if it's a temporary one.

**Comment by XtratoS** [comment] 2018-06-10 18:04
6 years and still no clue

**Comment by merithes** [comment] 2018-11-23 09:06
There is no 'fix' people, the thing is that there is a special character that signals the text renderer to display the text from right to left ([https://en.wikipedia.org/wiki/Right-to-left_mark](url)), and the steam text renderer just doesn't interpret it.

The only way for this to be fixed is if Valve decides to support it, or to run a homebrew version of steam. It's not a bug, it's not fixable by fiddling with settings. It's just that supporting localizations is a huge mess, and the best way to handle localization is to not support it

 That's why your text is displayed the wrong way, because it would require a lot of efforts for a minority. It's sad, but the rewards isn't worth the hassle

**Comment by ahmed12345678910111213141516** [comment] 2023-05-17 06:07
steam render arabic messages the right way to me but only if i opened the chat window
the issue is still there for pop up

**Comment by shytzedaka** [comment] 2023-05-23 04:40
I have done a retest with Hebrew both in chat and in notifications, it appears to be working correctly.
(I used Arch Linux With Gnome 44.1 X11 **Steam on Flatpak, Steam Version:  1684535786**)
_Though it is important to mention i have used this on Ubuntu with the .Deb version of steam and it worked perfectly there as well_

Notification: 
![Screenshot from 2023-05-23 07-32-44](https://github.com/ValveSoftware/steam-for-linux/assets/20986867/eb4bb8bd-f089-4c76-b1bf-0b57b3d4197d)
Chat box:
![Screenshot from 2023-05-23 07-32-05](https://github.com/ValveSoftware/steam-for-linux/assets/20986867/08e2caaa-5865-463b-84c4-a1c68c557675)

**Comment by kisak-valve** [comment] 2023-07-07 23:56
Closing per the last comment.

**Closed by kisak-valve** 2023-07-07 23:56 UTC
Labels: reviewed, Steam client, localization, Need Retest
