### ISSUE TITLE
Feature Request: Add target monitor on big picture mode Linux client

### ISSUE THREAD

**Issue by lben** [ValveSoftware/steam-for-linux#4733] opened 2016-12-02 22:46 UTC
#### Your system information

* Steam client version: 1480467111
* Distribution (e.g. Ubuntu): Ubuntu 16.04
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I expect to be able to play my games using my TV through the hdmi port. I know in windows there is a target monitor option inside the display option in big picture mode (see here: [http://s29.postimg.org/vw7tz89w7/Untitled.jpg](url)) but that option is not present in the linux client. 

#### Steps for reproducing this issue:

1. Open Big Picture Mode
2. Go to Settings
3. In the display section there is not any option to send Big Picture Mode to another monitor.

**Comment by Alan-James** [comment] 2016-12-12 23:48
Even if you get big picture mode running on the correct screen you may find games wanting to open on either the primary or leftmost display. Here's my script to launch big picture mode. You may find it useful.


[tv_steam.sh.txt](https://github.com/ValveSoftware/steam-for-linux/files/647558/tv_steam.sh.txt)

**Comment by lben** [comment] 2016-12-13 00:02
Thank you for your script! I will test it later, in the meantime could you elaborate what this script does please? For instance how do I do to go back when I want to use my primary display? Thanks

**Comment by Alan-James** [comment] 2016-12-13 00:28
First I must turn on the TV, then run the script.

It disables my screensaver, then enables the tv output and makes it the primary and leftmost screen. 
Then because all my windows have now moved to the left by 1920 pixels, it moves all windows 1920 pixels to the right. It sets a few SDL environment variables that probably fixed some game I don't play anymore, and then runs Steam in big picture mode.

In BP mode each time I have to manually set the audio output to the HDMI because even though it's playing through it, it'll tell games the wrong output unless BP mode's audio screen shows the right output.
It seems to forget which device I'm using as a mic too.

When Steam exits, windows are moved left again and the tv output disabled.

You may need to modify the xrandr commands as your screen outputs may be named differently. Run arandr to get the names you need.

So while it's running you can still go back to your desk and use your pc as normal, your tv is just another screen attached to the left.

**Comment by Managor** [comment] 2017-10-31 19:51
It's been a year Valve. Time to bump this as on multimonitor setups the screen doesn't focus on either of the screens
![20171031_214900](https://user-images.githubusercontent.com/8741769/32245824-b207c044-be85-11e7-8ed3-7faf9fb98727.jpg)

**Comment by kisak-valve** [comment] 2019-10-11 15:23
Closing as a duplicate of #921.

**Closed by kisak-valve** 2019-10-11 15:23 UTC
Labels: Big Picture, Feature Request, reviewed
