### ISSUE TITLE
Feature Request: add an advanced option for downloading/running windows games

### ISSUE THREAD

**Issue by AncientLich** [ValveSoftware/steam-for-linux#3890] opened 2015-06-19 04:26 UTC
There are games that are not officially ported under linux, but however can be runned on Linux through PlayOnLinux or directly through wine.

An example is Castle Crashers (tested for a brief time on Steam Client for windows under Ubuntu 14.04 LTS with wine / winetricks).

It should be nice if steam client could allow user to ignore game supported platform in order to download / run a windows native game (obliouvsly.... the user should be know what is doing and the feature could not grant that the game could run), expecting that user manually properly modifies game content directory (for example... renaming the .exe file and placing a bash script that properly runs the game, comunicating between client and game itself).

I don't know if this feature is possible to add or not, but it could be a nice thing... in this way you could limit wine usage and windows dependencies only by game itself (avoiding to be forced to run also the windows client that requires more "emulation").

**Comment by MrSchism** [comment] 2015-06-19 04:46
Valve is trying to avoid supporting Wine/PoL due to several additional levels of complexity regarding support.  Having this feature added may add confusion unless it was well documented directly in the settings (and even then, brings user support questions on properly using it).

Think from a support stance (read through closed tickets here and in Dota2 if you need help) and imagine a tick box that says "Ignore game platform for downloads."

What is worth mentioning to developers is that --while not ideal-- it is possible to use a wine wrapper for a linux port (it's been done before).  Of course, you could run the Steam client via Wine and download the games that way if the game you want has inactive developers.

**Comment by AncientLich** [comment] 2015-06-19 09:59
Nice Points, MrSchism.
Thank for sharing your opinion... after reading it I should say that I agree with you completely.

:)

**Comment by Tele42** [comment] 2015-06-19 12:51
Duplicate of #74.

**Comment by MrSchism** [comment] 2015-06-20 05:25
@Tele42 This is a subtle difference.  74 requests wine integration.  This simply requests bypassing the "only download for current platform" functionality of the Steam client.  It would mean that you could download Windows versions and back them up in an archive on a linux system (among other things).  It's just insanely complex from a support angle.

**Comment by Tele42** [comment] 2015-06-20 14:46
The download only perspective was considered a duplicate by @gdrewb-valve on #3714. Despite the wording, this is all the same core feature request - make non-native games more accessible.

**Comment by MrSchism** [comment] 2015-06-21 06:48
I will close it as a dupe of #3714 (which it almost exactly is.  Forgot about that one).

**Closed by MrSchism** 2015-06-21 06:48 UTC
Labels: Feature Request, reviewed
