### ISSUE TITLE
plasmashell: Xlib: sequence lost warning ou /var/log/messages from Steam

### ISSUE THREAD

**Issue by Patola** [ValveSoftware/steam-for-linux#9086] opened 2023-01-10 22:03 UTC
#### Your system information

* Steam client version (build number or date): Build: Dec 15 2022, at 21:27:25 / package version: 1671236931
* Distribution (e.g. Ubuntu): ArchLinux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

After upgrading lib32-libx11 to 1.8.3-1 from 1.8.2-2, there's a whole lot of messages in /var/log/messages from the steam client which makes it really slow.

#### Steps for reproducing this issue:

1. upgrade library `lib32-libx11` to `1.8.3-1`
2. start steam
3. monitor `/var/log/messages` (or /var/log/messages.log) for new messages, possibly via `tail -f`. There will be a flood of messages like:
```
Jan 10 22:21:18 risadinha plasmashell[2796]: Xlib: sequence lost (0x25f0000 > 0x25e233c) in reply type 0xc!
Jan 10 22:21:18 risadinha plasmashell[2796]: Xlib: sequence lost (0x25f0000 > 0x25e2341) in reply type 0xc!
Jan 10 22:21:18 risadinha plasmashell[2796]: Xlib: sequence lost (0x25f0000 > 0x25e234a) in reply type 0xc!
Jan 10 22:21:18 risadinha plasmashell[2796]: Xlib: sequence lost (0x25f0000 > 0x25e234f) in reply type 0xc!
Jan 10 22:21:18 risadinha plasmashell[2796]: Xlib: sequence lost (0x25f0000 > 0x25e2358) in reply type 0xc!
Jan 10 22:21:18 risadinha plasmashell[2796]: Xlib: sequence lost (0x25f0000 > 0x25e235d) in reply type 0xc!
Jan 10 22:21:18 risadinha plasmashell[2796]: Xlib: sequence lost (0x25f0000 > 0x25e2366) in reply type 0xc!
Jan 10 22:21:18 risadinha plasmashell[2796]: Xlib: sequence lost (0x25f0000 > 0x25e236b) in reply type 0xc!
```

Note 1: not sure if this is a bug in the library itself, in plasmashell (most likely) or Steam.

Note 2: this bug is also described in this reddit post -- https://www.reddit.com/r/linux_gaming/comments/10459tz/steam_on_terminal_is_spamming_this_type_of_message/

Note 3: confirmed with 2 other friends which also use Arch Linux with KDE.

Note 4: downgrading back to 1.8.2-2 solves the issue.

**Comment by Patola** [comment] 2023-01-10 22:09
Bug report #9086 occurs in Gnome, so it seems it is not in plasmashell

**Comment by kisak-valve** [comment] 2023-01-10 23:27
Hello @Patola, this is an upstream regression in libX11 and needs to be resolved upstream.

Closing as a duplicate of #9083.

**Closed by kisak-valve** 2023-01-10 23:27 UTC
