### ISSUE TITLE
Steam overlay breaks with XCOM 2

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#4297] opened 2016-02-05 11:49 UTC
See this screenshot, XCOM 2 totally breaks the Steam Overlay causing white boxes.
http://imgur.com/ZWBWJSq
It also happens to the in-game FPS counter.

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3f
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3500 Mhz
    16 logical processors
    8 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.0-27-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 980 Ti/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 355.11
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x17c8
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  3840 x 2160
Desktop Resolution: 3840 x 2160
Primary Display Size: 24.45" x 13.43"  (27.87" diag)
                                        62.1cm x 34.1cm  (70.8cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 6144 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC1150

Memory:
    RAM:  15947 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  1877664 Mb
    Largest Free Hard Disk Block:  1686512 Mb

Installed software:

Recent Failure Reports:

**Comment by Plagman** [comment] 2016-02-19 01:14
Can you still reproduce this issue? I haven't seen any other reports.

**Comment by MiroslavR** [comment] 2016-02-20 17:08
> Can you still reproduce this issue? I haven't seen any other reports.

I can reproduce this as well, although the FPS counter is drawn properly.

**Comment by NaughtySquid** [comment] 2016-02-20 17:12
@MiroslavR system info?

**Comment by MiroslavR** [comment] 2016-02-20 17:12
@NaughtySquid Updated my post.

**Comment by Plagman** [comment] 2016-02-20 20:06
Thanks for the information about it being random; we'll try again to replicate it here.

**Comment by MiroslavR** [comment] 2016-02-23 20:39
These visual glitches only seem to occur when the game is run with FPS counter enabled. I can work around the issue by running the game with FPS counter disabled and enabling it in-game.

**Comment by LiamDawe** [comment] 2016-03-22 11:32
I still have the issues FYI. Ubuntu 16.04, Nvidia 358 driver series.

**Comment by NoXPhasma** [comment] 2017-08-26 08:41
This is still an issue. I just bought XCOM 2 and facing the same bug. It does not happen every time but is bound to the running Steam session. When I'm lucky I start Steam and the overlay works fine and this for the whole Steam session, no matter how often I restart XCOM2, when I restart Steam it happens again. This happens most of the time but some times it does not.

I looked into the Steam log but couldn't find any errors or warnings which would point to this issue.

System Info:
```Computerinformationen:
    Hersteller: Unknown
    Modell: Unknown
    Formfaktor: Desktop
    Keine Touch-Eingabe erkannt

Prozessor:
    CPU-Hersteller: AuthenticAMD
    CPU-Marke: AMD Ryzen 7 1700 Eight-Core Processor          
    CPU-Familie: 0x17
    CPU-Modell: 0x1
    CPU-Stepping: 0x1
    CPU-Typ: 0x0
    Geschwindigkeit: 3800 MHz
    16 logische Prozessoren
    8 technische Prozessoren
    HyperThreading:  Unterstützt
    FCMOV:  Unterstützt
    SSE2:  Unterstützt
    SSE3:  Unterstützt
    SSSE3:  Unterstützt
    SSE4a:  Unterstützt
    SSE41:  Unterstützt
    SSE42:  Unterstützt
    AES: Unterstützt
    AVX: Unterstützt
    CMPXCHG16B: Unterstützt
    LAHF/SAHF: Unterstützt
    PrefetchW: Nicht unterstützt

Betriebssystem:
    Linux Mint 18.2 Sonya (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 4.12.8-041208-generic
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11804000
    X-Fenstermanager: Mutter (Muffin)
    Steam-Runtime-Version: steam-runtime-beta-release_2016-12-05

Grafikkarte:
    Treiber: NVIDIA Corporation GeForce GTX 970/PCIe/SSE2
    Treiberversion: 4.5.0 NVIDIA 384.69
    OpenGL-Version: 4.5
    Desktopfarbtiefe: 24 Bit per Pixel
    Monitor-Aktualisierungsrate: 60 Hz
    Anbieterkennung: 0x10de
    Gerätekennung: 0x13c2
    Revision nicht gefunden
    Anzahl der Monitore: 2
    Anzahl der logischen Grafikkarten: 1
    Prim. Anzeigeauflösung: 1920 x 1080
    Desktopauflösung: 3840 x 1080
    Prim. Anzeigegröße: 20,91" x 11,77" (23,98" diag)
 53,1cm x 29,9cm (60,9cm diag)
    Primärer Bus: PCI Express 16x
    Primärer VRAM: 4096 MB
    Unterstützte MSAA-Modi: 2x 4x 8x 16x 

Soundkarte:
    Audiogerät: Nvidia GPU 71 HDMI/DP

Speicher:
    RAM: 32168 MB

Weitere Daten:
    UI-Sprache: Deutsch (Deutsch)
    SPRACHE: de_DE.UTF-8
    Verfügbarer Festplattenspeicher insgesamt: 275163 MB
    Größter freier Festplattenspeicherblock: 57459 MB
    VR-Headset: Keines gefunden
```

**Comment by kisak-valve** [comment] 2019-03-15 12:57
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by NoXPhasma** [comment] 2019-03-15 13:28
Because of the randomness of this issue I restarted Steam several times and run the game also several times each session. Couldn't reproduce that issue on my current system and Steam Beta client.

Systeminfo: https://gist.github.com/NoXPhasma/7a37f6d53519be8bc0061cca8e733ad8

**Comment by kisak-valve** [comment] 2019-04-26 13:16
Thanks for retesting @NoXPhasma, closing presumed fixed.

**Closed by kisak-valve** 2019-04-26 13:16 UTC
Labels: Need Retest, overlay, reviewed
