### ISSUE TITLE
Steamcommunity.com website is unresponsive.

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3717] opened 2015-02-14 22:51 UTC
While I have mentioned to the Valve Support representatives that the issue persists in the browser, they told me to lodge an issue here.

The issue also exists here: https://support.steampowered.com/view.php?ticketref=9197-WTDH-0136
The issue text there is as follows:

> For a few months now, the steamcommunity.com website has been giving me problems where elements that do work on the steampowered.com website do not work on the steamcommunity.com website.
> The dropdown menus don't function, forum- and comment-threads do not allow me to switch pages, just about every element that requires some scripted functionality fails.
> Now, I am aware of adblockers, scriptblockers, and the like, and I have turned each and every single one off to try and see if that is the issue, but it is not.
> I am using a fully HTML5 capable web browser, but the steamcommunity.com website still does not wish to work properly.
> Are you discriminating browsers on useragent strings? If so, there is no visible clue of that. (It is also a bad practice.) Is it because I am running Linux? Again, there is no visible clue that hints at my OS not being supported if that were the case.
> I am honestly at a loss what could cause this inability for the steamcommunity.com site to function, while the steampowered.com website functions perfectly. 

The steampowered.com website is running perfectly fine. Once I get redirected to the steamcommunity.com website, active content stops working, making the site completely useless.
I don't believe the support representative knows a thing about Linux and simply forwarded me to get rid of me.

**Comment by gdrewb-valve** [comment] 2015-02-15 20:12
Is this only inside of the Steam client or in a separate Linux browser?  If so which browsers have you tried?  Have you tried any Windows browsers to see if this is a problem in Linux only or it it's a problem with the community site itself?

**Comment by Makitk** [comment] 2015-02-15 20:34
The issue is not in the Steam client. It does happen in the Pale-Moon-for-Linux browser which is fully HTML5 capable and a fork of the Mozilla Firefox browser. The only thing I can think of is that the Steam site checks for UserID and does not accept the Pale Moon UserID string and therefore turns off active content, although I could not imagine a reasoning behind such.
I have no idea how to do a check on whether what does what it's supposed to do, and am not able to install a different browser on my Linux machine for a variety of reasons.

**Comment by gdrewb-valve** [comment] 2015-02-15 20:42
OK, I'll pass this on to the team that handles the websites (the Linux team is not directly involved in that).

**Comment by gdrewb-valve** [comment] 2015-02-23 20:43
The web team tried it with real Firefox and didn't have issues so they're no sure what's going on (the Pale Moon installer didn't work so they weren't able to try that).  They suggested it might be a proxy issue but as they haven't seen the problem it's just a guess.

**Comment by Makitk** [comment] 2015-02-23 23:49
The installer here should work for installing pale moon on linux; http://sourceforge.net/projects/pm4linux/
I am not running any proxies. I connect directly to the internet.
I ran pale moon without any plugins and ran into the issue.
I don't know how to give you more information that would help find the cause of this.

**Comment by Makitk** [comment] 2015-02-23 23:53
I dropped this issue on the pale moon for linux support forum as well, I'll see if someone there may know what's up. Will update here in case they come up with something.

**Comment by kisak-valve** [comment] 2018-06-15 12:32
Closing as the user has turned into a ghost. If this issue is still around on an up to date system, it would need to be investigated from scratch.

**Closed by kisak-valve** 2018-06-15 12:32 UTC
Labels: reviewed
