### ISSUE TITLE
LD_LIBRARY_PATH unbound

### ISSUE THREAD

**Issue by blueish4** [ValveSoftware/steam-for-linux#3697] opened 2015-01-31 13:58 UTC
With STEAM_RUNTIME disabled I now get an error on launch 
`/home/michael/.local/share/Steam/steam.sh: line 713: LD_LIBRARY_PATH: unbound variable`
Using Arch Linux with the open source AMD drivers.

**Comment by hexid** [comment] 2015-01-31 18:05
I also received this error message:

    Running Steam on arch rolling 64-bit
    STEAM_RUNTIME is disabled by the user
    /home/hexid/Steam/steam.sh: line 713: LD_LIBRARY_PATH: unbound variable

To get steam to start, I just had to run the following:

    $ LD_LIBRARY_PATH="/usr/lib" steam

---

Steam is trying to append to the `LD_LIBRARY_PATH` env variable even if it doesn't exist.

This can be fixed by changing line 713 from:

    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib32"

to:

    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+LD_LIBRARY_PATH:}/usr/lib32"

**Comment by Oxalin** [comment] 2015-02-02 03:57
From what I understand from http://wiki.bash-hackers.org/syntax/pe#use_a_default_value, I think it could be simplified a bit more to:
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH-}:/usr/lib32"

**Comment by artemjackson** [comment] 2015-02-19 18:51
**hexid** works for me.

**Comment by Shished** [comment] 2015-03-02 14:44
For me it shows more errors:

```
STEAM_RUNTIME=0 steam
/home/yuri/.local/share/Steam/steam.sh: line 145: DISTRIB_ID: unbound variable
/home/yuri/.local/share/Steam/steam.sh: line 159: DISTRIB_RELEASE: unbound variable
/home/yuri/.local/share/Steam/steam.sh: line 145: DISTRIB_ID: unbound variable
/home/yuri/.local/share/Steam/steam.sh: line 159: DISTRIB_RELEASE: unbound variable
Running Steam on   64-bit
STEAM_RUNTIME is disabled by the user
/home/yuri/.local/share/Steam/steam.sh: line 712: LD_LIBRARY_PATH: unbound variable
```
On openSUSE 13.2 x86_64

**Comment by Shished** [comment] 2015-03-02 14:54
It seems that steam restores original launcher during startup. Tested with STEAM_RUNTIME enabled and disabled.

**Comment by Oxalin** [comment] 2015-03-02 17:17
Indeed, once steam.sh is modified, it will check its integrity on the next startup and restore itself.

Shished, it seems openSUSE doesn't use DISTRIB_ID and DISTRIB_RELEASE. To my knowledge, this doesn't create any problem for Steam, but if you have seen something wrong related to these missing variables, I would suggest to open a different bug. To help you with this bug and a way to determine the missing variables, you could check if the following exists and what it contains: /etc/lsb-release

**Comment by Shished** [comment] 2015-03-02 18:41
```
$ cat /etc/lsb-release
LSB_VERSION="core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64"
```
Commenting the "if" string and changing first "elseif" into "if" fixes this problem.

**Comment by Oxalin** [comment] 2015-03-02 22:33
As I said, I would open a different bug for these specific missing variables with the information you provided.

**Comment by Oxalin** [comment] 2015-03-02 23:34
Shished, I would follow issue 3694 if I was you about the DISTRIB_ID and DISTRIB_RELEASE, it seems to be the same.

**Comment by Shished** [comment] 2015-03-03 08:11
Also about Line 712 problem. On openSUSE default folder for 32bit libs is /usr/lib instead of /usr/lib32. So there's should be additional checks.

**Comment by Oxalin** [comment] 2015-03-03 18:55
Shished, you are right about this, but I feel this should also be treated as a different bug, nevertheless related to the current one. We are drifting away from the original bug which is that steam.sh fails to start when LD_LIBRARY_PATH is undefined.

If you want to add some info about this other bug, feel free to copy what follows.
As stated in section 4.1 Runtime support of chapter 4 of OpenSUSE, 32bit libraries are under /lib and /usr/lib, while 64bit libraries are under /lib64 and /usr/lib64: https://doc.opensuse.org/documentation/html/openSUSE_121/opensuse-reference/cha.64bit.html OpenSUSE calks itself to the FHS 2.3 specification on the matter: http://refspecs.linuxfoundation.org/FHS_2.3/fhs-2.3.html#LIB64

That said, many distributions seems to use symlinks to do pretty much the same. For example, Ubuntu uses /usr/lib/"arch" with some symlinks. At the opposite, ArchLinux is not following the FHS at all, where 64bit libraries are located in /lib and /usr/lib, and the 32bit are in /lib32 and /usr/lib32.

A workaround for the user is to manually set the LD_LIBRARY_PATH, but then it goes againts the idea of keeping things as simple as possible for any user.

Since whatever system and architecture we are using, there should always be a /usr/lib, the easy and dumb way would be to change line 712 to include both possible paths. At worst, one will fail without any consequence if the other one is found. So line 712 could be:
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH-}:/usr/lib32:/usr/lib"

The best way would be to determine the 32bit library folder and then to append it to LD_LIBRARY_PATH. We could look for a specific library identified as a dependency with a "find" command, then analyze the returned paths with a "file" command and filter looking for an ELF 32-bit answer.

**Comment by nexfwall** [comment] 2015-03-22 18:13
Confirmed on openSUSE Tumbleweed 20150318 and still exists.

**Comment by arzeth** [comment] 2015-03-28 21:46
In December 2014 I hadn't this error. Today I have it.

**Comment by DoctorJellyface** [comment] 2015-03-31 13:44
I'm having this error too for a while. Arch 64 bit.

**Comment by RunasSudo** [comment] 2015-04-12 09:07
Error presented itself after I updated Steam for the first time in a while today.
```
$ STEAM_RUNTIME=0 steam
Running Steam on arch rolling 64-bit
STEAM_RUNTIME is disabled by the user
/home/runassudo/.local/share/Steam/steam.sh: line 712: LD_LIBRARY_PATH: unbound variable
```
Steam works properly when `STEAM_RUNTIME` is enabled. Problem is fixed by first exporting `LD_LIBRARY_PATH="/usr/lib32"`

**Comment by Oxalin** [comment] 2015-04-12 15:23
RunasSudo, LD_LIBRARY_PATH just has to be exported first, even with an empty value like this:
export LD_LIBRARY_PATH=""

As explained previously, the problem comes from the fact that Steam.sh looks for this variable in the STEAM_RUNTIME=0 path to add a new path to it (which is /usr/lib32/ by the way), but fails to handle the situation properly when LD_LIBRARY_PATH has not been defined already.

**Comment by Shished** [comment] 2015-04-12 15:34
For me steam always crashes when STEAM_RUNTIME env variable is set to 0. Changing LD_LIBRARY_PATH does not fixes the problem.

**Comment by Oxalin** [comment] 2015-04-12 21:06
Shished, you are experiencing a different bug then. Please, dig a bit more and either find the appropriate bug or open a new one. I would be tempted to ask you to have a look here first to help you identify missing libs or conflicting ones: https://wiki.archlinux.org/index.php/Steam#Steam_runtime_issues

**Comment by Oxalin** [comment] 2015-04-12 21:44
By the way, if you need help, you can contact me by email. Look at my profile and you'll have my email address.

**Comment by HarlemSquirrel** [comment] 2015-05-03 16:05
[code]$ LD_LIBRARY_PATH="/usr/lib" steam[/code]

This helped me after not being able to launch steam after installing my own build of llvm

**Comment by laptander** [comment] 2015-05-24 23:58
Steam do not allows me to edit steam.sh file.
Trying to launch steam with `$ STEAM_RUNTIME=0 steam`, but get error `/home/user/.local/share/Steam/steam.sh: line 710: LD_LIBRARY_PATH: unbound variable`

Changed that line in steam.sh file, but steam checks file size and downloads it again if it detects changes. Here is what I saw at output:
```
Startup - updater built May 14 2015 17:40:14
Checking installation...
BVerifyInstalledFiles: steam.sh is 22608 bytes, expected 22526
Verification complete
Downloading update...
```
And after that it restarts with recovered original file.

**Comment by Oxalin** [comment] 2015-05-25 04:18
@laptander: normal and expected. This won't be fixed as long as:
- Steam doesn't modify the script on their side with one of the already proposed minor modification;
- you add an empty LD_LIBRARY_PATH in your environment.

For that last option, you could add LD_LIBRARY_PATH="${LD_LIBRARY_PATH-}" to your environment file (/etc/environment) or in your personal variables as an example.

**Comment by laptander** [comment] 2015-05-25 04:41
@Oxalin Thanks for reply.
I added LD_LIBRARY_PATH="${LD_LIBRARY_PATH-}" to /etc/environment, logged out and in again, checked value of variable with ``echo $LD_LIBRARY_PATH`` and it is ``${LD_LIBRARY_PATH-}"``

But still cannot launch steam with ``STEAM_RUNTIME=0 steam``. Here is output (sorry for long output):
```
Running Steam on arch rolling 64-bit
STEAM_RUNTIME is disabled by the user
Installing breakpad exception handler for appid(steam)/version(1431729692)
Installing breakpad exception handler for appid(steam)/version(1431729692)
Gtk-Message: Failed to load module "canberra-gtk-module"
Installing breakpad exception handler for appid(steam)/version(1431729692)
/home/user/.local/share/Steam/ubuntu12_32/steamwebhelper: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/../vgui_surfacelib/FontManager.cpp (276) : Assertion Failed: descs.Count() >= 1
Assert( Assertion Failed: descs.Count() >= 1 ):/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/../vgui_surfacelib/FontManager.cpp:276

Installing breakpad exception handler for appid(steam)/version(1431729692)
crash_20150525073230_5.dmp[23311]: Uploading dump (out-of-process)
/tmp/dumps/crash_20150525073230_5.dmp
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/../vgui_surfacelib/FontManager.cpp (276) : Assertion Failed: descs.Count() >= 1
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/../vgui_surfacelib/FontManager.cpp (276) : Assertion Failed: descs.Count() >= 1
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/../vgui_surfacelib/FontManager.cpp (276) : Assertion Failed: descs.Count() >= 1
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/steamUI/../common/steam/client_api.cpp (320) : Assertion Failed: ClientAPI_InitGlobalInstance: InternalAPI_Init_Internal failed, most likely because you are missing a 32-bit dependency of steamclient.so (the Steam client is a 32-bit app).

/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/steamUI/SteamStartup.cpp (751) : Assertion Failed: ! "There was a problem with your Steam installation.\n" "Please reinstall steam.\n"
[2015-05-25 07:32:30] Startup - updater built May 14 2015 17:40:14
[2015-05-25 07:32:30] Проверка установки...
[2015-05-25 07:32:30] Verification complete
[2015-05-25 07:32:32] Shutdown
crash_20150525073230_5.dmp[23311]: Finished uploading minidump (out-of-process): success = no
crash_20150525073230_5.dmp[23311]: error: HTTP response code said error
crash_20150525073230_5.dmp[23311]: file ''/tmp/dumps/crash_20150525073230_5.dmp'', upload no: ''HTTP response code said error''
```
Have you any suggestions what is the problem now?

**Comment by Oxalin** [comment] 2015-05-25 05:23
@laptander , LD_LIBRARY_PATH should be empty, my error I didn't copy the good thing. You should read LD_LIBRARY_PATH="" if you put it in /etc/environment. However, it shouldn't matter in our case.

That being said, your new error comes from somewhere else: missing or conflicting librairies. Could you send me an email so we can solve this error without flooding the current bug? Look at my profile for my email.

**Comment by abbradar** [comment] 2015-06-11 13:24
I have the same bug as @laptander while trying to run Steam without runtime:
```
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/../vgui_surfacelib/FontManager.cpp (276) : Assertion Failed: descs.Count() >= 1
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/../vgui_surfacelib/FontManager.cpp (276) : Assertion Failed: descs.Count() >= 1
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/../vgui_surfacelib/FontManager.cpp (276) : Assertion Failed: descs.Count() >= 1
```
I should note that I'm trying to make this work on an unsupported distribution (NixOS), so I don't expect Valve to fix this -- but if there is some information on what libraries cause this, it would be very nice to know.

**Comment by laptander** [comment] 2015-06-11 13:37
@abbradar I just installed packages, that are listed in alucryd's repo in Arch linux and it helped me. Maybe you can try to find out if there are the same packages in NixOS.

**Comment by abbradar** [comment] 2015-06-11 13:43
@laptander Thanks, looking at libraries list right now.

**Comment by johnv-valve** [comment] 2015-07-17 22:17
I believe this is fixed

**Closed by johnv-valve** 2015-07-17 22:17 UTC
Labels: reviewed

**Comment by tomtomme** [comment] 2015-07-23 09:43
thanks. I can confirm that steam does now start with runtime disabled on opensuse tumbleweed

**Comment by samkostka** [comment] 2016-05-11 18:20
I think I just got this bug on Arch.  I fixed it by adding export LD_LIBRARY_PATH="${LD_LIBRARY_PATH-}" to /bin/steam.

**Comment by Tele42** [comment] 2016-05-11 19:13
The current regression is being tracked on #4447, this issue report is retired.
