### ISSUE TITLE
User confusion with scrolling behavior on Steam Deck when viewing a library title.

### ISSUE THREAD

**Issue by psymin** [ValveSoftware/steam-for-linux#8723] opened 2022-08-05 22:03 UTC
#### Your system information

* Steam client version (build number or date): Built: Jul 30 2022, at 04:09:05 Steam package versions: 1659369000
* Distribution (e.g. Ubuntu): SteamOS Holo (64 bit)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

The default behavior of touch scrolling on a title in a library on the Steam Deck seems to confuse and/or frustrate some users.

When scrolling, it will "spring" back to the top.

This behavior changes to a more expected behavior if any of the buttons "Activity", "Your Stuff", "Community",  or "Game Info" are touched.  Then scrolling doesn't spring back.

https://user-images.githubusercontent.com/326578/183217203-08b30e4c-0998-4d6b-b3a4-22bcc6062816.mp4

#### Steps for reproducing this issue:

1. Click on a title in the library.
2. Touch the screen and flick upwards, to scroll.
3. The screen will return to the default state after a brief moment.

**Comment by ZereoX** [comment] 2024-07-15 13:36
Hi @psymin,

I have been unable to reproduce the issue you reported above on the latest Stable SteamOS release (3.5.19). In all instances the the Game Details Page remained at the correct position when scrolled and never "sprung" back up.

Would you be able to confirm if this is still an issue that is affecting you?

Thanks.

**Comment by kisak-valve** [comment] 2024-08-16 20:35
Closing pending feedback.

**Closed by kisak-valve** 2024-08-16 20:35 UTC
Labels: Steam client, Need Retest, Distro Family: SteamOS
