### ISSUE TITLE
Steam don't run in Ubuntu 16.10

### ISSUE THREAD

**Issue by 903124** [ValveSoftware/steam-for-linux#4665] opened 2016-10-14 14:53 UTC
#### Your system information
- Steam client version:
- Distribution (e.g. Ubuntu):  1476379980
- Opted into Steam client beta?: [Yes/No]  No
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

Steam just can't launch after installation

```
Running Steam on ubuntu 16.10 64-bit
STEAM_RUNTIME is enabled automatically
[2016-10-14 22:50:54] Startup - updater built Oct 13 2016 00:47:16
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2016-10-14 22:50:54] Checking for update on startup
[2016-10-14 22:50:54] Checking for available updates...
[2016-10-14 22:50:54] Download skipped: /client/steam_client_ubuntu12 version 1476379980, installed version 1476379980
[2016-10-14 22:50:54] Nothing to do
[2016-10-14 22:50:54] Verifying installation...
[2016-10-14 22:50:54] Performing checksum verification of executable files
[2016-10-14 22:50:55] Verification complete
```
#### Steps for reproducing this issue:
1. Download the newest release https://launchpad.net/ubuntu/yakkety/i386/steam/1:1.0.0.52-5ubuntu1
2. install steam

**Comment by TheOpenDevProject** [comment] 2016-10-16 09:24
Ah so I am not the only one that is having issues.

**Comment by boltronics** [comment] 2016-10-16 22:11
I just used the one in the Ubuntu repo, and that worked fine. The one in the repo has a Bash wrapper script `/usr/share/games` that takes care of removing certain problematic libraries that are part of the 12.04 environment that Steam downloads. Perhaps the one from the launchpad repo doesn't include it?

**Comment by 903124** [comment] 2016-10-17 02:34
@boltronics I can't see the script in the directory

**Comment by boltronics** [comment] 2016-10-17 02:56
@903124 I'm not in front of a Ubuntu install right now, but I'm referring to the one in the multiverse repository, as opposed to one installed from a PPA or otherwise. You should be able to determine the one you are using by running `apt-cache policy steam`.

**Comment by boltronics** [comment] 2016-10-17 02:57
Oh... I probably meant `/usr/games/steam`. Sorry!

**Comment by 903124** [comment] 2016-10-18 06:28
@boltronics It is still the same. The script does run but can't help. 

The version is also correct


`steam:i386:
  Installed: 1:1.0.0.52-5ubuntu1
  Candidate: 1:1.0.0.52-5ubuntu1
`

**Comment by ekaris** [comment] 2016-10-18 16:20
The steam on the ubuntu repos also worked for me:
sudo apt install steam

**Comment by 903124** [comment] 2016-10-20 08:20
@ekaris It's not working even for a fresh installation. Any idea?

**Comment by q3452** [comment] 2016-10-20 11:08
This is also the precise error I'm experiencing.

```
$ steam
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
[2016-10-20 19:02:00] Startup - updater built Oct 13 2016 00:47:16
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2016-10-20 19:02:01] Checking for update on startup
[2016-10-20 19:02:01] Checking for available updates...
[2016-10-20 19:02:03] Download skipped: /client/steam_client_ubuntu12 version 1476379980, installed version 1476379980
[2016-10-20 19:02:03] Nothing to do
[2016-10-20 19:02:03] Verifying installation...
[2016-10-20 19:02:03] Performing checksum verification of executable files
[2016-10-20 19:02:04] Verification complete
$ 
```
After "Verification complete", it shuts down.
I installed from the repositories on 16.04.1 after enabling canonical partners.
```
$ aptitude search steam
v   steam                                         -                                                         
i   steam:i386                                    - Valve's Steam digital software delivery system          
v   steamcmd                                      -                                                         
p   steamcmd:i386                                 - Command-line interface for Valve's Steam

$ aptitude show steam:i386
Package: steam:i386                      
State: installed
Automatically installed: no
Multi-Arch: foreign
Version: 1:1.0.0.48-1ubuntu3
Priority: extra
Section: multiverse/games
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: i386
Uncompressed Size: 2,662 k
Depends: debconf:i386 (>= 0.5) | debconf-2.0:i386, libc6:i386 (>= 2.15), libstdc++6:i386 (>= 4.3),
         libx11-6:i386, xz-utils:i386, libudev1:i386, libxinerama1:i386, libtxc-dxtn0:i386,
         libgl1-mesa-dri:i386, libgl1-mesa-glx:i386, xterm:i386 | x-terminal-emulator:i386
PreDepends: debconf:i386, multiarch-support:i386
Recommends: zenity:i386, fonts-liberation:i386
Provides: steam (= 1:1.0.0.48-1ubuntu3)
```

**Comment by q3452** [comment] 2016-10-20 12:10
Found this in syslog when replicating the error.
```
Oct 20 20:06:30 localhost kernel: [27577.226259] steam[16472]: segfault at 57dd7238 ip 0000000057dd7238 sp 00000000ffc2a23c error 15
```

**Comment by ekaris** [comment] 2016-10-20 13:57
@903124 I don't know how to help in this case, this is a problem that valve should resolve.. I used Ubuntu gnome 16.10 64 bits btw

**Comment by q3452** [comment] 2016-10-22 12:12
Is there anyway to call Valve for help with this issue?

**Comment by TheOpenDevProject** [comment] 2016-10-23 06:47
I actually found out how to resolve the issue I was having. Mine was with radeonsi and I used the old fix.

**Comment by q3452** [comment] 2016-10-23 08:31
@TheOpenDevProject Were you getting the same error message as us?
`segfault at 57dd7238` in syslog?  Or was it a different error?

**Comment by TheOpenDevProject** [comment] 2016-10-24 10:28
@q3452 Different so if the theme of this bug-track is the segfault I redact my statement :smile:

**Comment by q3452** [comment] 2016-10-24 12:54
Well, the segfault is how the error appears in **my** syslog, I can't speak for OP.  I only know that  @903124  had the client die silently in the same way I did.  I don't know what was appearing in their syslog.

**Comment by q3452** [comment] 2016-10-26 00:35
I can confirm that the same error occurs in LinuxMint18 with both NVidia 370 and 367 drivers.

**Comment by q3452** [comment] 2016-10-26 02:14
I can confirm that the same error exists under LinuxMint18 and with both 370 and 367 proprietary nvidia drivers on a gtx1070.

**Comment by q3452** [comment] 2016-11-15 02:04
@903124 Could you try these steps and report the results?   I appear to have had the same issue as you and fixed it using this technique.

`ls /usr/share/X11/locale/`echo $LANG``
In my case, I was using a locale of English that wasn't supported by X11 (there are quite a lot) and Steam failed to fall back to En_US and subsequently silently crashed with a segfault.

If the above line returns something like `ls: cannot access '/usr/share/X11/locale/en_HK.UTF-8': No such file or directory` then the solution is using this to start Steam:
`LANG=en_US.utf8 steam`

Possibly adapted to include whatever other exports you include to get Steam to ignore it's own out-dated libraries or find your LibGL or proprietary video drivers.

**Comment by nothingface0** [comment] 2017-02-25 23:35
Hi and sorry if this is considered an old/closed thread.

I have the exact same problem as the OP and the same output at the terminal.

However, my locale **is** en_US.UTF-8. Even by executing
`$ LANG=en_US.utf8 steam`
I get the same behavior. Did anyone happen to come across any other solution?

Note that Steam runs as intended when the system is freshly booted but, after I've closed Steam and used my computer for other stuff and then try to re-launch Steam, the problem arises. Unfortunately I haven't been able to reproduce the steps that lead to that.

I've read all the threads I could find on the subject but nothing helped.

PS: I'm using Crunchbang++ (debian).

**Comment by WoutLin** [comment] 2018-02-25 18:35
Hi, how can this be considered closed when I do not see a solution?  I have spent the last week trying to solve this same problem.  When I use windows xp 32-bit the steam client works as expected.  It starts to the store and I can play games no problem.  I also use Linux Mint 18 64-bit on the same computer.  I installed the steam client and it wouldn't work.  I updated to Linux Mint 18.3 64-bit-not work, tried every suggestion I could find-not work.  I tried Linux Lite 3.8 32-bit, Linux Lite 3.8 64-bit, Peppermint 8 64-bit-not work.  
I moved the hard drive which had Linux Lite 3.8 32-bit to another computer and it worked, although the store was unavailable because 32-bit not  supported.  
Now the first computer (steam on linux won't work)  is single core Athlon 64 3200+, 2Gb ddr ram, radeon hd 4670 agp graphics.  The second computer that the steam client starts (although I have yet to try a game) is dual core Pentium D 805/2.66 GHz 64-bit, 1Gb ddr2 ram, ATI Radeon Xpress 200 integrated graphics.
It was the same hard drive with no changes except I changed the amd cpu microcode driver to intel cpu microcode from driver manager of Linux Lite.
Is the first computer, which is capable of running steam client in windows xp 32-bit, too old or missing something that is required to run the same in Linux? 
This is what happens when I use terminal: steam

Running Steam on linuxmint 18.3 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
[2018-02-25 13:23:00] Startup - updater built Dec 15 2017 11:47:44
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2018-02-25 13:23:00] Checking for update on startup
[2018-02-25 13:23:00] Checking for available updates...
[2018-02-25 13:23:01] Download skipped: /client/steam_client_ubuntu12 version 1513371133, installed version 1513371133
[2018-02-25 13:23:01] Nothing to do
[2018-02-25 13:23:01] Verifying installation...
[2018-02-25 13:23:01] Performing checksum verification of executable files
[2018-02-25 13:23:01] Verification complete

Then the login window pops up.  I fill in user and pw.  It disappears.  A small window appears, "updating user configuration".  Then the terminal is ready for a new command.  Steam just stops.
I am continuing my research but if someone knows the solution, it would be greatly appreciated.

**Comment by WoutLin** [comment] 2018-02-26 16:04
This is a update trying to get to the bottom of why the steam client won't launch. 

Now I have newly installed and updated Linux Lite 3.8 64-bit, Peppermint 8 64-bit, Linux Mint 18.3 64-bit. I have installed steam from the software manager provided by each OS.  The machine contains single core cpu Athlon64 3200+.  Run steam from terminal and you get: Linux Lite=the r600_dri.so error, and it hangs; Peppermint8 and Linux Mint 18.3 both let you login, then "updating user configuration" box appears and disappears, then the command prompt returns in the terminal.  Steam has apparently shut itself off.  The last line before the command prompt: Verification complete.

The hard drive has been removed from this computer and put into one that has dual core cpu Pentium D 805/2.66 GHz 64-bit.  Nothing has been changed.  All the OS's work as expected.  Steam is run from the terminal.  On all 3 OS's the steam client seems to work perfect.  I installed a game and it worked. Go to the store.  Browse games, watch videos.  It all works. 

So is the first computer's processor the reason why the steam client doesn't work with linux.  It does work with windows xp.  It is the usual way that I have used steam for years.

If one of the experts from valve/steam could verify then please let us know and change the system requirements if warranted.  	
From "install steam now" page:

System Requirements

Windows XP, Vista, or 7
512 MB RAM
1 Ghz or faster processor

Intel Mac, OS X version 10.7 (Lion), or later.
Two-button mouse strongly recommended

1GB HD space (recommended)
Internet connection (broadband recommended)

Thank you.

**Comment by mateusfccp** [comment] 2018-06-20 11:39
I'm having this same problem on Elementary OS 0.4.1 Loki.
Built on Ubuntu 16.04.3 LTS, Kernel 4.13.0-45-generic.
Nvidia drivers (396).

 Steam was working with no problems about one week ago. One day I entered Big Picture mode, and after I closed big picture mode the client crashed. Since then, I can't open it again. I get the same messages as the others above:

```
mateusfccp@Pintobook:~$ steam
Running Steam on elementary 0.4.1 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
[2018-06-20 08:36:44] Startup - updater built Jun  8 2018 22:22:23
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2018-06-20 08:36:44] Checking for update on startup
[2018-06-20 08:36:44] Checking for available updates...
[2018-06-20 08:36:45] Download skipped: /client/steam_client_ubuntu12 version 1528497815, installed version 1528497815
[2018-06-20 08:36:45] Nothing to do
[2018-06-20 08:36:45] Verifying installation...
[2018-06-20 08:36:45] Performing checksum verification of executable files
[2018-06-20 08:36:45] Verification complete
```

I tried completely purging Steam package and reinstalling it (even cleared cache so it would redownload), deleting ~/.steam folder, but nothing worked. @q3452 solution also didn't work for me.

Please, help me!

**Comment by mateusfccp** [comment] 2018-06-20 11:52
After searching a lot, this one answer fixed my problem: https://askubuntu.com/a/903488/169212

**Comment by kisak-valve** [comment] 2019-09-13 16:44
Hello, @903124, are you still experiencing an issue on an up to date system?

@WoutLin, Steam-for-linux currently needs a SSE3-capable processor due to #5164.

**Comment by WoutLin** [comment] 2019-09-14 00:10
Hello, @kisak-valve 
I have since upgraded my system. Now it includes i7 8700 processor and this problem is a forgotten memory now.  Thanks for the update, it may help someone else.

**Comment by kisak-valve** [comment] 2019-10-18 13:27
Closing pending feedback.

**Closed by kisak-valve** 2019-10-18 13:27 UTC
Labels: Need Retest, reviewed
