### ISSUE TITLE
Clicking on offer a trade opens a new window and anything steam cant be touched anymore

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#4671] opened 2016-10-18 16:31 UTC
#### Your system information

* Steam client version: Latest as of today
* Distribution (e.g. Ubuntu):  Ubuntu gnome 16.10
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
In a friends profile if I click on offer a trade, a new window appears (as it should) but
after that any other window from steam isn't possible to use until the trade window
is closed, not even the chat works.

#### Steps for reproducing this issue:
1. Go to a friends profile
2. Click offer a trade
3. It should be possible to interactively use the other windows with the new one, but it isn't.

**Comment by Tele42** [comment] 2016-10-18 19:07
Duplicate of #4659.

**Comment by gdrewb-valve** [comment] 2016-10-18 19:54
Closing duplicate.

**Closed by gdrewb-valve** 2016-10-18 19:54 UTC

**Comment by ekaris** [comment] 2016-10-19 06:41
Please re add this feature, now one can't go to the market in other steam window to check the prices of the items.. what a fail
