### ISSUE TITLE
Click on the middle button of the mouse (wheel) block steam Linux

### ISSUE THREAD

**Issue by martindupont** [ValveSoftware/steam-for-linux#3886] opened 2015-06-17 06:54 UTC
Hi !
When I click in the Steam Linux client with the central mouse button (the wheel), that's block + I can't use the icons of applications in the Ubuntu left bar.
To borrow "the hand" I have to right click and select an option.

**Comment by gdrewb-valve** [comment] 2015-06-17 18:32
Duplicate of #2424.

**Closed by gdrewb-valve** 2015-06-17 18:32 UTC
Labels: duplicate, reviewed
