### ISSUE TITLE
Falling of models under textures (Bug Counter-Strike)

### ISSUE THREAD

**Issue by UniverseTech** [ValveSoftware/steam-for-linux#2252] opened 2013-04-01 04:03 UTC
![1](https://f.cloud.github.com/assets/4023437/322862/213ede30-9a81-11e2-9ed9-90430c8084f2.png)
![2](https://f.cloud.github.com/assets/4023437/322864/3b539478-9a81-11e2-8ea7-caf7686de870.png)

**Comment by kisak-valve** [comment] 2017-04-25 18:47
Closing as a duplicate of https://github.com/ValveSoftware/halflife/issues/76 / https://github.com/ValveSoftware/halflife/issues/907.

**Closed by kisak-valve** 2017-04-25 18:47 UTC
Labels: MOVED: Counter‐Strike, reviewed
