### ISSUE TITLE
Case sensitve steamapps directory on case insensitive filesystems can cause problems with old installs

### ISSUE THREAD

**Issue by ipat500** [ValveSoftware/steam-for-linux#3710] opened 2015-02-09 10:11 UTC
Old steam installs used to use the directory $ROOTOFSTEAM/SteamApps to store data.
New installs use $ROOTOFSTEAM/steamapps

Since I have I am using a very old data directory mine had the former by default.

Somehow, not sure how, I managed to not have any problems with this until the most recent update (9th of Febuary 2015 ish).

After the update the client had forgotten about that directory (it wasn't my primary directory, it was showing up as an added library folder). And then when I tried to re-add it through the menu (Steam library folders) it failed with the error message "Steam library folder must be on a filesystem mounted with execute permissions", which wasn't helpful at all, because that drive does have excecute bits set (it is ntfs btw).

So the problem at it's heart is that steam must be trying to make the lower case version of the directory (which is probably somehow grouped in with the code it uses to test for excecute bit), which fails, because ntfs is derp and case-insensitive. And then  still only the directory with the wrong case exists.

Anyway, the way I see it there is 2 options:
1) Make the error message more helpful (seems like a given)
2) Set up some way to detect and correct the case in old installs automatically (seems dangerous but might possible)

Also as a side note. I assume that this has happended because something recently changed in the way the client deals with this stuff. So you probably just screwed up a whole load of people who like me somehow managed to last this long with the wrong case.

Btw, obviously this isn't a problem for me, since I found the problem and manually corrected it. But this is a backwards compatability issue which I figured you should probably be aware of.

**Comment by eydee** [comment] 2015-02-09 23:47
Renaming the directory works, the issue is actually old. Probably Steam should just look for both  versions and use whatever it finds.

**Comment by ipat500** [comment] 2015-02-10 00:08
Yeah I got the feeling this was an old issue (I found the fix on a forum from like a year ago).

I imagine that adding new library folders through the menu has been the way it is for ages. But perhaps up until yesteray existing installs were fine, which is why I never had a problem. I'm not really sure.

My original install had that directory symlinked to the other drive from ~/.steam

At some point the client automatically changed this to the new method with the library folders, but iirc the symlink was still there.

The point is, this situation would probably only happen to people who originally had a symlink. So they would probably be technically minded enough to fix it manually. A more helpful error message is probably sufficient to solve this (it was really confusing).

**Comment by eydee** [comment] 2015-02-10 10:30
For me no symlinks were involved. I just keep a library on a separate parition which I add to new installs from time to time. At a certain point it refused to add it with the notorious error message. It took a while to find out what the real issue was, but once it happened, I renamed the directory and it worked and it keeps working ever since.

Changing the error message is not the best solution. If you're adding a library and Steam displays an error message "please rename SteamApps to steamapps" everyone will think Steam developers are retarded. Steam should just rename it automatically or accept both.

**Comment by Peter200lx** [comment] 2015-03-14 06:35
This looks like it is a dupe of #3649 
(Not trying to ask for this bug to be closed or anything, just referencing it so that there will be a link back)

**Comment by Nemoder** [comment] 2017-11-05 09:16
I just wanted to add that on my old Ubuntu machine where Steam was working fine and some games were working fine but all the games using unity3d were instantly crashing with:  
"Player data archive not found"  
It turned out to be because it had both a steamapps and SteamApps directory.   
Removing the SteamApps directory solved the issue.

**Comment by kisak-valve** [comment] 2018-04-07 00:32
Hello @ipat500, per "Fixed a bug where trying to re-add old Steam Library folders to the client would fail with an error about the filesystem not being mounted with execute permissions" in the [2018-04-06](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1657763209739490075) Steam beta client, please opt into the beta client and retest this issue.

**Comment by kisak-valve** [comment] 2018-05-18 13:30
Closing as fixed.

**Closed by kisak-valve** 2018-05-18 13:30 UTC
Labels: Need Retest, Steam client, reviewed
