### ISSUE TITLE
Dialog windows do not have the _NET_WM_WINDOW_TYPE_DIALOG window type

### ISSUE THREAD

**Issue by scummos** [ValveSoftware/steam-for-linux#4457] opened 2016-05-22 12:40 UTC
Steam's dialogs (e.g the startup dialog, login dialog, settings dialog, download dialog) do not have _NET_WM_WINDOW_TYPE set to _NET_WM_WINDOW_TYPE_DIALOG, as dialogs should have (you can easily check with xprop, and compare to dialogs opened by almost any other application). See also here: https://specifications.freedesktop.org/wm-spec/latest/ar01s05.html under _NET_WM_WINDOW_TYPE.

As a result, window managers which apply rules to dialog windows specifically will not correctly handle the steam dialogs; for example, a tiling window manager might not want to tile dialog windows but set them to floating instead, especially when they are additionally not resizable like the steam ones.

**Comment by gdrewb-valve** [comment] 2016-05-22 16:15
Basically the same thing as #2104.

**Comment by kisak-valve** [comment] 2021-03-20 17:45
Closing as a duplicate of #597.

**Closed by kisak-valve** 2021-03-20 17:45 UTC
Labels: reviewed
