### ISSUE TITLE
Steam vulkan layer prevents compression on Intel GPUs

### ISSUE THREAD

**Issue by vsyrjala2** [ValveSoftware/steam-for-linux#8899] opened 2022-11-07 19:12 UTC
The steam vulkan layer forces VK_IMAGE_USAGE_STORAGE_BIT for swapchain images, which has the unfortunate side effect of preventing Intel GPUs from using compression.

Fortunately one can use DISABLE_VK_LAYER_VALVE_steam_overlay_1=1 avoid this, but would be nice if worked out of the box.

Any chance of removing the forced VK_IMAGE_USAGE_STORAGE_BIT?

**Comment by Plagman** [comment] 2022-11-07 23:33
Are you seeing applied to all games, or only certain games that can present from compute?

**Comment by danginsburg** [comment] 2022-11-07 23:43
@vsyrjala2 That was actually added at Intel's request :)  The problem is if an application presents from the compute queue we need to be able to write to it from a compute shader in order to render the overlay.  We don't know ahead of time if an app is going to present from compute, so we conservatively set the bit during vkCreateSwapchainKHR if the app has done vkGetDeviceQueue on a compute queue that supports present.  If you can think of another way we could detect this case, we could change it.

**Comment by danginsburg** [comment] 2022-11-08 16:21
> How does that check work?

If the application has done a vkGetDeviceQueue on a queue that supports VK_QUEUE_COMPUTE_BIT and vkGetPhysicalDeviceSurfaceSupportKHR reports that present is supported for the VkSwapchainCreateInfoKHR->surface on that queue family we enable VK_IMAGE_USAGE_STORAGE_BIT during vkCreateSwapchainKHR.  Perhaps instead we could relax it to supports VK_QUEUE_COMPUTE_BIT and does *NOT* support VK_QUEUE_GRAPHICS_BIT since if it supports graphics we will be able to render to it with non-compute.

**Comment by vsyrjala** [comment] 2022-11-08 17:57
Slight side note: I also tried to hack off STORAGE_BIT from supportedUsageFlags, but that made no difference to the layer's behaviour. Should it perhaps check that stuff and at least complain a bit if the reported caps don't have what it needs?

**Comment by danginsburg** [comment] 2022-11-08 21:20
I've checked in a fix so that the overlay will only do this for a compute queue that does not support graphics (and does support present).  Fix will be in the next Steam Beta client update.

**Closed as completed by danginsburg** 2022-11-08 21:20 UTC
Labels: overlay
