### ISSUE TITLE
Steam fails to use new or existing Steam library folder with kernel update 3.13.0-59

### ISSUE THREAD

**Issue by tdryer** [ValveSoftware/steam-for-linux#3936] opened 2015-07-27 23:46 UTC
Steam lost access to my library folder and refuses to re-add it or create a new one. None of my installed game are accessible in Steam, nor can they be re-installed.

Trying to re-add my library or create a new one through `Settings>Downloads>Steam Library Folders` or the prompt when installing a game gives the error `New Steam library must be on a filesystem mounted with execute permissions`. Running a game manually from its executable in my non-working Steam library allows it to run (but without the Steam overlay). 

Steps to reproduce:
1. Open Steam.
2. Try to install a game.
3. Select `Create new Steam library on drive ...` since no libraries are recognized.
4. Select any directory when prompted (eg. `$HOME/Steam`).
5. See dialog box: `New Steam library must be on a filesystem mounted with execute permissions`.

System Information:
```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3001 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Linux 3.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-59-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  i3
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 650 Ti/PCIe/SSE2

    Driver Version:  4.4.0 NVIDIA 331.113
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x11c6
    Number of Monitors:  2
    Number of Video Cards Not Detected
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 18.78" x 10.55"  (21.54" diag)
                                            47.7cm x 26.8cm  (54.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Intel Haswell HDMI
    
Memory:
    RAM:  15928 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  936559 Mb
    Largest Free Hard Disk Block:  535819 Mb
    
Installed software:
    
Recent Failure Reports:
    Mon Jul 27 19:20:34 2015 GMT: file ''/tmp/dumps/assert_20150727122029_7.dmp'', upload no: ''HTTP response code said error''
    Mon Jul 27 19:31:16 2015 GMT: file ''/tmp/dumps/assert_20150727123111_7.dmp'', upload no: ''HTTP response code said error''
    Mon Jul 27 19:39:21 2015 GMT: file ''/tmp/dumps/assert_20150727123913_7.dmp'', upload yes: ''CrashID=bp-700f7019-f5cc-464e-a3fd-c15042150727''
    Mon Jul 27 19:46:30 2015 GMT: file ''/tmp/dumps/assert_20150727124621_7.dmp'', upload yes: ''CrashID=bp-fd5ba1eb-937e-4df8-892e-59dd12150727''
    Mon Jul 27 19:49:28 2015 GMT: file ''/tmp/dumps/assert_20150727124924_7.dmp'', upload no: ''HTTP response code said error''
    Mon Jul 27 19:53:11 2015 GMT: file ''/tmp/dumps/assert_20150727125303_7.dmp'', upload yes: ''CrashID=bp-5db81b70-2086-46f5-a9b0-b2a2d2150727''
    Mon Jul 27 19:56:00 2015 GMT: file ''/tmp/dumps/assert_20150727125549_7.dmp'', upload yes: ''CrashID=bp-ff781032-8b44-4a09-a594-44abe2150727''
    Mon Jul 27 22:58:14 2015 GMT: file ''/tmp/dumps/assert_20150727155805_7.dmp'', upload yes: ''CrashID=bp-467aa822-0b30-4ece-b8d5-df7292150727''
    Mon Jul 27 23:00:12 2015 GMT: file ''/tmp/dumps/assert_20150727160004_7.dmp'', upload yes: ''CrashID=bp-b8b0616a-ae57-4117-a741-2f85d2150727''
    Mon Jul 27 23:09:52 2015 GMT: file ''/tmp/dumps/assert_20150727160944_7.dmp'', upload yes: ''CrashID=bp-12477206-581e-4665-b166-990352150727''
    Mon Jul 27 23:11:25 2015 GMT: file ''/tmp/dumps/crash_20150727161114_7.dmp'', upload yes: ''CrashID=bp-45b56a02-c2d5-4f79-b1e3-8fb1a2150727''
    Mon Jul 27 23:11:42 2015 GMT: file ''/tmp/dumps/crash_20150727161131_15.dmp'', upload yes: ''CrashID=bp-fa1b5b57-b1c6-47e8-b800-a783e2150727''
    Mon Jul 27 23:16:49 2015 GMT: file ''/tmp/dumps/crash_20150727161643_27.dmp'', upload no: ''HTTP response code said error''
```

**Comment by Captainthrills** [comment] 2015-07-28 02:29
Can confirm also happening to me also. A full wipe of steam simply produced the same results, and the exec mount error.

**Comment by dlanileonardo** [comment] 2015-07-28 03:56
Hey! I Have the same problem, steam cannot read my Hard Drive.

**Comment by qubitsu** [comment] 2015-07-28 08:21
Same problem here. I tried `steam --reset` and a fresh install, but all my games are still uninstalled and will not install. When I try to install a game in my library, the "Disk space Available" says 0 MB, though `df -h` reports 83G available, and Steam's System Information interface shows otherwise.

Here's my system information:
```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3400 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Linux 3.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-59-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 750 Ti/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 352.21
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1380
    Number of Monitors:  1
    Number of Video Cards Not Detected
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 1680 x 1050
    Primary Display Size: 18.62" x 11.65"  (21.93" diag)
                                            47.3cm x 29.6cm  (55.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC892
    
Memory:
    RAM:  7930 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  104540 Mb
    Largest Free Hard Disk Block:  84267 Mb
    
Installed software:
    
Recent Failure Reports:
    Tue Jul 28 07:45:50 2015 GMT: file ''/tmp/dumps/crash_20150728004546_7.dmp'', upload yes: ''CrashID=bp-01c7f7be-b715-46b1-84ed-36ce72150728''
    Tue Jul 28 07:46:06 2015 GMT: file ''/tmp/dumps/crash_20150728004604_15.dmp'', upload yes: ''CrashID=bp-78c62e19-883b-4508-ba07-6a1c02150728''
    Tue Jul 28 07:50:19 2015 GMT: file ''/tmp/dumps/assert_20150728005016_7.dmp'', upload yes: ''CrashID=bp-02ed6a9c-ce72-4520-8960-b72e62150728''
    Tue Jul 28 07:51:08 2015 GMT: file ''/tmp/dumps/assert_20150728005107_7.dmp'', upload yes: ''CrashID=bp-2d36b252-b266-4726-9a71-3c7732150728''
    Tue Jul 28 07:57:52 2015 GMT: file ''/tmp/dumps/crash_20150728005746_7.dmp'', upload yes: ''CrashID=bp-44215a36-e9bd-4fef-a2a0-1ce9a2150728''
    Tue Jul 28 07:58:18 2015 GMT: file ''/tmp/dumps/crash_20150728005805_15.dmp'', upload yes: ''CrashID=bp-20a81c48-6f42-4839-8560-3b2f82150728''
```

**Comment by who-me** [comment] 2015-07-28 10:09
Hi,

I can confirm the issue as well. Additionally the steam browser does not load the store page. It shows a black window and the spinner icon.

steam --reset did not fix the problem

dmesg is being spammed with this:
 
```
[ 2001.201704] sh[5599]: segfault at 3d2e32d0 ip 000000003d2e32d0 sp 00000000a940db10 error 14 in ld-2.19.so[7f1b3d2e2000+23000]
[ 2011.300353] sh[5604]: segfault at 882ef2d0 ip 00000000882ef2d0 sp 000000004e075d70 error 14 in ld-2.19.so[7ff7882ee000+23000]
[ 2021.491601] sh[5609]: segfault at 15f922d0 ip 0000000015f922d0 sp 0000000038f017f0 error 14 in ld-2.19.so[7fd415f91000+23000]
[ 2031.583681] sh[5614]: segfault at 31a6f2d0 ip 0000000031a6f2d0 sp 000000009b964400 error 14 in ld-2.19.so[7f9f31a6e000+23000]
[ 2041.677211] sh[5619]: segfault at a56812d0 ip 00000000a56812d0 sp 00000000081a60c0 error 14 in ld-2.19.so[7fd9a5680000+23000]
[ 2051.866351] sh[5624]: segfault at 505632d0 ip 00000000505632d0 sp 000000002e8c2b90 error 14 in ld-2.19.so[7f0e50562000+23000]
[ 2061.969499] sh[5629]: segfault at 8730e2d0 ip 000000008730e2d0 sp 00000000aa0611f0 error 14 in ld-2.19.so[7f958730d000+23000]
[ 2072.067331] sh[5634]: segfault at 438482d0 ip 00000000438482d0 sp 0000000094227310 error 14 in ld-2.19.so[7f5c43847000+23000]
```

 
System info:
```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3700 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Linux 3.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-59-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 660/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 352.21
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x11c0
    Number of Monitors:  1
    Number of Video Cards Not Detected
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 16,06" x 10,04"  (18,94" diag)
                                            40,8cm x 25,5cm  (48,1cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC892
    
Memory:
    RAM:  7966 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  112546 Mb
    Largest Free Hard Disk Block:  48049 Mb
    
Installed software:
    
Recent Failure Reports:
    Tue Jul 28 09:34:05 2015 GMT: file ''/tmp/dumps/assert_20150728123359_7.dmp'', upload yes: ''CrashID=bp-79308412-4f45-4dbf-9c66-80fa82150728''
    Tue Jul 28 09:38:16 2015 GMT: file ''/tmp/dumps/assert_20150728123816_6.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
    Tue Jul 28 09:40:41 2015 GMT: file ''/tmp/dumps/assert_20150728124041_5.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
    Tue Jul 28 09:57:54 2015 GMT: file ''/tmp/dumps/assert_20150728125754_5.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
    Tue Jul 28 10:02:21 2015 GMT: file ''/tmp/dumps/assert_20150728130217_7.dmp'', upload yes: ''CrashID=bp-e43c5e16-cd9b-4ed5-9428-73ca82150728'' 

```

**Comment by lyubomirv** [comment] 2015-07-28 11:31
Same problem. Using XUbuntu 14.04.02 LTS x86-64 with kernel 3.13.0-59-generic

Complete wipe and reinstall does not help.

**Comment by Jahsis** [comment] 2015-07-28 12:10
Have same issue with 3.13.0-59-generic kernel. Booting in 3.13.0-58-generic fixes problem for me too.

**Comment by Mecha-Weasel** [comment] 2015-07-28 16:22
Same for me 14.04.02 LTS ("Lamenting To Steam") x86-64, yaddah, yaddah, yaddah.

**Comment by Mecha-Weasel** [comment] 2015-07-28 17:10
PS: I noticed there is also a LaunchPad bug-tracker case open with Ubuntu: [url=https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1478989]LaunchPad Bug #1478989[/url]

**Comment by Mecha-Weasel** [comment] 2015-07-28 17:12
PPS: Looks like there is also another LaunchPad bug-tracker case open as well:
"Odd behaviour in some applications"
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1478873

**Comment by jellehermsen** [comment] 2015-07-28 17:29
Same issue here, also on 3.13.0-59 and Ubuntu 14.04. Booting in -58 works, I could set up the library directories perfectly, but after booting back into -59 they were gone.

**Comment by who-me** [comment] 2015-07-28 17:58
Well, keep using -58 then as -59 is clearly b0rked.

**Comment by who-me** [comment] 2015-07-28 21:05
The bug is also being investigated here:
 
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1479093

**Comment by fcastilloec** [comment] 2015-07-28 22:45
Same issue here, I'm going back to -58 until further notice, but the launchpad bug suggest that a -59 lts kernel might not suffer from this bug. I'm just not sure what they mean by it.

**Comment by Mecha-Weasel** [comment] 2015-07-28 23:07
I think what they are getting-at in those LaunchPad bug reports, is that there is another kernel update in the pipeline (3.16.something, instead of 3.13.something) that fixes things - but just isn't released yet for LTS.

**Comment by DigiAngel** [comment] 2015-07-28 23:57
Ok good...glad to know I'm not the only one:

Jul 28 17:43:44 kernel: [  178.985396] sh[3839]: segfault at 12ace2d0 ip 0000000012ace2d0 sp 0000000021eb61e0 error 14 in ld-2.19.so[7fa112acd000+23000]

**Comment by brosander** [comment] 2015-07-29 02:57
having the same problem here with linux mint kde, booting to 58 seems to be a decent workaround for now

**Comment by Mecha-Weasel** [comment] 2015-07-29 16:17
According to the bug case on the Ubuntu side (https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1479093), additional affected applications (besides Steam and WINE) have been identified, and they have changed to priority to fixing this now from "medium" to "high".

I also saw a note in there that a fix is in the works and releasing an updated kernel should be forthcoming shortly.
[quote]
[...] wrote 3 hours ago:	#16
A fix for this is building right now and, if all goes well, should be released in 8 to 12 hours.
[/quote]

**Comment by CreamyCookie** [comment] 2015-07-29 17:46
@Plagman @gdrewb-valve
I have the exact same problem. I don't know if this has anything to do with this, but I suddenly seem to have two Steam folders:

* `~/.local/share/Steam`
* `~/.steam/steam`

Which one is the correct one and which one can I delete?

**Comment by Mecha-Weasel** [comment] 2015-07-29 18:21
FYI: The Ubuntu bug-tracker case (https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1479093) has now has its status updated to "Fix Committed".

**Comment by Mecha-Weasel** [comment] 2015-07-30 01:11
According to Ubuntu side, this should be fixed now with the kernel update they released today (kernel version 3.13.0-61.100):
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1479093, more specifically https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1479093/comments/23

**Comment by tdryer** [comment] 2015-07-30 03:28
Fixed after upgrading from kernel `3.13.0-59-generic` to `3.13.0-61-generic`.

**Comment by johnv-valve** [comment] 2015-07-30 17:39
Nothing we can do in Steam to work around this, you will need the updated kernel from Ubuntu.

**Closed by johnv-valve** 2015-07-30 17:39 UTC
Labels: reviewed

**Comment by fdoerrer** [comment] 2018-02-18 02:53
I'm having this issue on Kernel version 4.12.12, I'm assuming it's because I don't have a specific module enabled. can anyone identify that module?
