### ISSUE TITLE
Dropdown menus disappear with Firefox 58.0.1

### ISSUE THREAD

**Issue by psydex** [ValveSoftware/steam-for-linux#5375] opened 2018-02-07 14:24 UTC
#### Your system information
* Firefox on Windows 10
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

Same as [this thread](https://github.com/ValveSoftware/steam-for-linux/issues/4029)

#### Steps for reproducing this issue:
![35905056-501ec34e-0bee-11e8-94ff-268e8ee7ee2c](https://user-images.githubusercontent.com/5594251/35921481-61d46212-0c23-11e8-9d1b-a3ef8704930e.gif)

**Comment by kisak-valve** [comment] 2018-02-13 00:41
Hello @psydex, are you able to reproduce this issue?

As a side note, this issue tracker is generally intended for issues that only affect the steam client on linux. [Steam Support](https://help.steampowered.com/en/) is available for Windows users.

**Comment by psydex** [comment] 2018-02-13 07:00
It's been fixed.

**Comment by kisak-valve** [comment] 2018-02-13 13:28
Thanks for retesting, closing.

**Closed by kisak-valve** 2018-02-13 13:28 UTC
Labels: Need Retest, Web
