### ISSUE TITLE
Steam client (June 16th) fails to start the new UI

### ISSUE THREAD

**Issue by odysei** [ValveSoftware/steam-for-linux#9650] opened 2023-06-17 10:30 UTC
#### Your system information

* Steam client version (build number or date): Jun 16, 2023
* Distribution (e.g. Ubuntu): Kubuntu 23.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11778608/steam-logs.tar.gz)
* GPU: NVIDIA GeForce RTX 4070/PCIe/SSE2

#### Please describe your issue in as much detail as possible:
Steam client with a new UI loops with repeated lines:
"""
(steam:28377): GLib-CRITICAL **: 13:34:13.502: g_main_context_push_thread_default: assertion 'acquired_context' failed

(steam:28377): GLib-CRITICAL **: 13:34:13.502: g_main_context_pop_thread_default: assertion 'g_queue_peek_head (stack) == context' failed
BuildCompleteAppOverviewChange: 434 apps
RegisterForAppOverview 1: 8ms
RegisterForAppOverview 2: 8ms
"""
The tray icon loads, possible to shutdown via the tray.

Interestingly, after a PC restart it starts the new UI once, and then the next time fails again, i.e., goes into the loop if started the second++ time.

Seems to load with an old interface just fine "-vgui".

#### Steps for reproducing this issue:

1. Run the new steam
2. Exit Steam
3. Run the new steam

**Comment by mmbossoni** [comment] 2023-06-17 11:20
In my testing, if you just start steam and let it be it will, eventually, open.
Sometimes it takes more than one minute to show the interface, but it show up.

**Comment by kisak-valve** [comment] 2023-06-17 13:43
Hello @odysei, what video driver version are you using? This reads like a duplicate of #9634.

**Comment by Big-Brick** [comment] 2023-06-17 16:37
I have same issue with amd card with mesa drivers. I disabling gpu acelerated rendering didn't help. I managed to start new UI by using "Launch using Integrated Graphics Card"(I have laptop Radeon 6800m and AMD Ryzen 9 5980HX)

**Comment by kisak-valve** [comment] 2023-06-17 16:45
Hello @Big-Brick, you've described the issue being tracked at #9383.

**Comment by odysei** [comment] 2023-06-18 19:26
> Hello @odysei, what video driver version are you using? This reads like a duplicate of #9634.

Indeed, I am on the latest 535.54.03, so it might be related, but I don't see anything related to opcode as in https://github.com/ValveSoftware/steam-for-linux/issues/9634.

**Comment by kisak-valve** [comment] 2023-06-18 19:38
Thanks, let's continue tracking this on #9634. Feel free to add your findings to that issue report.

Closing in favor of the older issue report.

**Closed by kisak-valve** 2023-06-18 19:38 UTC
Labels: duplicate, NVIDIA drivers, Web Component
