### ISSUE TITLE
Fedora 27 - Couldn't launch Portal 2 game

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/steam-for-linux#5259] opened 2017-11-26 18:21 UTC
#### Your system information

* Steam client version (build number or date): Nov 22 2017, at 13:33:37
* Distribution (e.g. Ubuntu): Fedora 27
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam client installed from RPMFusion repo:  https://rpmfusion.org/Configuration
```
[mikhail@localhost Portal 2]$ ./portal2_linux 
./portal2_linux: error while loading shared libraries: libtcmalloc_minimal.so.4: cannot open shared object file: No such file or directory

# whereis libtcmalloc_minimal.so.4
libtcmalloc_minimal.so: /usr/lib64/libtcmalloc_minimal.so.4
```

#### Steps for reproducing this issue:

1. Just launch game
```
GameAction [AppID 620, ActionID 8] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 620, ActionID 8] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 620, ActionID 8] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 620, ActionID 8] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 620, ActionID 8] : LaunchApp continues with user response "CreatingProcess"
Opted-in Controller Mask: 0
Game update: AppID 620 "", ProcID 7576, IP 0.0.0.0:0
>>> Adding process 7576 for game ID 620
GameAction [AppID 620, ActionID 8] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/mikhail/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/mikhail/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 7578 != 7577, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/mikhail/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 620, ActionID 8] : LaunchApp changed task to Completed with ""
>>> Adding process 7577 for game ID 620
ERROR: ld.so: object '/home/mikhail/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 7579 for game ID 620
>>> Adding process 7580 for game ID 620
SDL video target is 'x11'

SDL failed to create GL compatibility profile (whichProfile=0!

Installing breakpad exception handler for appid(gameoverlayui)/version(20171122133326)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Using breakpad crash handler
Game update: AppID 620 "", ProcID 7580, IP 0.0.0.0:0
Setting breakpad minidump AppID = 620
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198082472541 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198082472541
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
tcmalloc: large alloc 4288602112 bytes == (nil) @ 
tcmalloc: large alloc 4288602112 bytes == (nil) @ 
Game removed: AppID 620 "", ProcID 7580 
No cached sticky mapping in ActivateActionSet.
```

**Comment by kisak-valve** [comment] 2017-11-26 20:06
Hello @NTMan, please read through https://github.com/ValveSoftware/portal2/issues/204 and see if it applies to you.

**Comment by NTMan** [comment] 2017-11-26 20:25
I made fix32 file as described in article but got OUT OF MEMORY error.
And yes my filesystem is XFS.
```
$ LD_LIBRARY_PATH="./bin" fix32 ./portal2_linux -game portal2
ERROR: ld.so: object '/usr/local/lib/inode64.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
SDL video target is 'x11'
SDL video target is 'x11'

SDL failed to create GL compatibility profile (whichProfile=0!
SDL failed to create GL compatibility profile (whichProfile=0!

This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system DOES NOT support the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system supports the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system supports the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
Using breakpad crash handler
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
tcmalloc: large alloc 4293468160 bytes == (nil) @ 
tcmalloc: large alloc 4293468160 bytes == (nil) @ 
***** OUT OF MEMORY! attempted allocation size: 4293460361 ****
```

**Comment by NTMan** [comment] 2017-11-27 16:00
Yes, I am able launch the game.
But after splash screen game is crashed.
My filesystem is XFS.
```
[mikhail@localhost ~]$ cd /home/mikhail/.local/share/Steam/steamapps/common/Portal\ 2/
[mikhail@localhost Portal 2]$ LD_LIBRARY_PATH="./bin" fix32 ./portal2_linux -game portal2
SDL video target is 'x11'
SDL video target is 'x11'

SDL failed to create GL compatibility profile (whichProfile=0!
SDL failed to create GL compatibility profile (whichProfile=0!

This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system DOES NOT support the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system supports the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system supports the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
Using breakpad crash handler
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
Did not detect any valid joysticks.
Did not detect any valid joysticks.

[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
CSoundEmitterSystemBase::BaseInit:  Manifest 'scripts/game_sounds_manifest.txt' with bogus file type 'new_sound_scripts_must_go_below_here', expecting 'declare_file' or 'precache_file'
CSoundEmitterSystemBase::BaseInit:  Manifest 'scripts/game_sounds_manifest.txt' with bogus file type 'new_sound_scripts_must_go_below_here', expecting 'declare_file' or 'precache_file'

Convar r_flashlightscissor has conflicting FCVAR_CHEAT flags (child: no FCVAR_CHEAT, parent: has FCVAR_CHEAT, parent wins)
Convar r_flashlightscissor has conflicting FCVAR_CHEAT flags (child: no FCVAR_CHEAT, parent: has FCVAR_CHEAT, parent wins)


 ##### swap interval = 1     swap limit = 1 #####
Did not detect any valid joysticks.
Did not detect any valid joysticks.

Could not load program cache file glshaders.cfg
Could not load program cache file glshaders.cfg

Could not find user GL shader cache file
Could not find user GL shader cache file

[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
CClientSteamContext logged on = 0
CClientSteamContext logged on = 0

Convar building_cubemaps has conflicting FCVAR_CHEAT flags (child: has FCVAR_CHEAT, parent: no FCVAR_CHEAT, parent wins)
Convar building_cubemaps has conflicting FCVAR_CHEAT flags (child: has FCVAR_CHEAT, parent: no FCVAR_CHEAT, parent wins)

Game.dll loaded for "Half-Life 2"
Game.dll loaded for "Half-Life 2"

[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
Segmentation fault (core dumped)
```

**Comment by NTMan** [comment] 2018-01-27 12:20
I am retryed attempt with running steam client and it helps launch the game without crashing.

Thanks for solution, but I think better solution would be provide 64 bit binary or recompiling 32 bit with _FILE_OFFSET_BITS=64 flag.

**Comment by kisak-valve** [comment] 2020-04-10 14:12
Closing as a duplicate of https://github.com/ValveSoftware/portal2/issues/204.

**Closed by kisak-valve** 2020-04-10 14:12 UTC
Labels: Distro Family: Fedora, MOVED: Portal2

**Comment by ScremCat** [comment] 2022-07-30 04:00
Doesnt this seem to be just because there does seem to be any steam instance in the program files x86 folder
