### ISSUE TITLE
Expand the number of compatible terminals for the steam-launcher package

### ISSUE THREAD

**Issue by Artem13327** [ValveSoftware/steam-for-linux#10361] opened 2024-01-07 12:47 UTC
Hello! I have Steam installed for Debian, and I have the steam-launcher package installed, so it has some terminals in its dependencies, please expand the number of terminals compatible with it, otherwise a lot of desktop environments have their own excellent terminals, but you have to install another one -because you need the steam-launcher package. I wrote through a translator, and also sorry for the mistakes

**Comment by kisak-valve** [comment] 2024-01-07 14:35
Hello @Artem13327, this issue is already being tracked in various issue reports like #665 #1476 #3980 #9265. Fragmenting the discussion of this topic on another non-specific issue report is not worthwhile.

Closing as a duplicate of #665.

**Closed by kisak-valve** 2024-01-07 14:35 UTC
