### ISSUE TITLE
Steam self-update ignores download scheduling rules

### ISSUE THREAD

**Issue by DeHackEd** [ValveSoftware/steam-for-linux#4633] opened 2016-09-24 04:08 UTC
#### Your system information
- Steam client version: Built Aug 23 2016, at 18:25:43, api v016m package versions 1471977975
- Distribution (e.g. Ubuntu): Ubuntu 14.04 container (under LXC)
- Opted into Steam client beta?: No
- Have you checked for system updates?: (Cause of issue)
#### Please describe your issue in as much detail as possible:

I've set Steam to download updates for games between 3 and 6 am and not to download while playing. This works fine for games, but steam itself will take updates any time it feels like even during games. The lag is real. Confirmed timezone is set correctly.
#### Steps for reproducing this issue:
1. Set a tiny time window for updates to be allowed to download
2. Wait for an update
3. Note the time Steam downloads the update. It will typically be outside this window.

**Comment by kisak-valve** [comment] 2017-04-12 19:52
Closing as a duplicate of #2003.

**Closed by kisak-valve** 2017-04-12 19:52 UTC
Labels: reviewed
