### ISSUE TITLE
Auth Ticket Canceled

### ISSUE THREAD

**Issue by earth2016** [ValveSoftware/steam-for-linux#5594] opened 2018-07-27 10:57 UTC
Hi,

When i am playing to Rust, the game freezes and server side shows me this error message:

kicked: Steam: AuthTicketCanceled

I think is an issue with Steam. I have checked Rust doesn't crash with segmentation fault or some library issue, moreover i have checked the files integration and all are ok.

Any clue to solve this issue?

Thanks!

**Comment by kisak-valve** [comment] 2018-07-27 13:04
Hello @earth2016, this issue should also be brought to the attention of the game's dev(s).

**Comment by earth2016** [comment] 2018-07-27 20:37
Your are right. Finally i saw errors in syslog.
```
Jul 27 22:14:54 mymachine steam.desktop[15749]: Native stacktrace:
Jul 27 22:14:54 mymachine steam.desktop[15749]: /mnt/interno/almacen/moving/home/user-name/local/steam/steamapps/common/Rust/rust_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so(+0xd406d) [0x7f9a333fd06d]
Jul 27 22:14:54 mymachine steam.desktop[15749]: /lib/x86_64-linux-gnu/libpthread.so.0(+0xf88f) [0x7f9a3d51c88f]
Jul 27 22:14:54 mymachine steam.desktop[15749]: /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37) [0x7f9a3c76a067]
Jul 27 22:14:54 mymachine steam.desktop[15749]: /lib/x86_64-linux-gnu/libc.so.6(abort+0x147) [0x7f9a3c76b447]
Jul 27 22:14:54 mymachine steam.desktop[15749]: /mnt/interno/almacen/moving/home/user-name/local/steam/steamapps/common/Rust/rust() [0x9ed12b]
Jul 27 22:14:54 mymachine steam.desktop[15749]: /mnt/interno/almacen/moving/home/user-name/local/steam/steamapps/common/Rust/rust_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so(+0x14d451) [0x7f9a33476451]
Jul 27 22:14:54 mymachine steam.desktop[15749]: /mnt/interno/almacen/moving/home/user-name/local/steam/steamapps/common/Rust/rust_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so(+0x5ace0) [0x7f9a33383ce0]
Jul 27 22:14:54 mymachine steam.desktop[15749]: /lib/x86_64-linux-gnu/libpthread.so.0(+0xf88f) [0x7f9a3d51c88f]
Jul 27 22:14:54 mymachine steam.desktop[15749]: /mnt/interno/almacen/moving/home/user-name/local/steam/steamapps/common/Rust/rust() [0x59db26]
Jul 27 22:14:54 mymachine steam.desktop[15749]: /mnt/interno/almacen/moving/home/user-name/local/steam/steamapps/common/Rust/rust() [0x55414a]
Jul 27 22:14:54 mymachine steam.desktop[15749]: /mnt/interno/almacen/moving/home/user-name/local/steam/steamapps/common/Rust/rust() [0x7874af]
Jul 27 22:14:54 mymachine steam.desktop[15749]: /mnt/interno/almacen/moving/home/user-name/local/steam/steamapps/common/Rust/rust() [0x7880d4]
Jul 27 22:14:54 mymachine steam.desktop[15749]: /mnt/interno/almacen/moving/home/user-name/local/steam/steamapps/common/Rust/rust() [0x78826a]
Jul 27 22:14:54 mymachine steam.desktop[15749]: /mnt/interno/almacen/moving/home/user-name/local/steam/steamapps/common/Rust/rust() [0x8e1398]
Jul 27 22:14:54 mymachine steam.desktop[15749]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x8063) [0x7f9a3d515063]
Jul 27 22:14:54 mymachine steam.desktop[15749]: /lib/x86_64-linux-gnu/libc.so.6(clone+0x6c) [0x7f9a3c81d62c]
Jul 27 22:14:54 mymachine steam.desktop[15749]: Debug info from gdb:
Jul 27 22:14:54 mymachine steam.desktop[15749]: mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb
Jul 27 22:14:54 mymachine steam.desktop[15749]: Assert( Assertion Failed: !m_ThreadClient.IsAlive() ):socket.cpp:423
Jul 27 22:14:54 mymachine steam.desktop[15749]: Uploading dump (in-process) [proxy '']
Jul 27 22:14:54 mymachine steam.desktop[15749]: /tmp/dumps/assert_20180727221454_3.dmp
Jul 27 22:14:59 mymachine gnome-session[1805]: Gjs-Message: JS LOG: pushModal: invocation of begin_modal failed
Jul 27 22:15:05 mymachine steam.desktop[15749]: success = yes
Jul 27 22:15:05 mymachine steam.desktop[15749]: response:  Discarded=1
Jul 27 22:15:05 mymachine rust: [22:15:05] [EAC InGame] [Warning] [E700h] [~cBackgroundWorker] Thread 0x7f998f81d700 being terminated by its destructor! It is highly recommended to explicitly call Terminate inste
ad.
Jul 27 22:15:05 mymachine steam.desktop[15749]: Killed
Jul 27 22:15:05 mymachine steam.desktop[15749]: Game removed: AppID 252490 "", ProcID 16262

```

**Comment by mixa37region** [comment] 2019-09-09 20:24
Several server admins Rust.   Often kick players from the server (random players and randomly kick) with such messages in the console...
Kicked: Steam: AuthTicketCanceled
Kicked: Steam: Unresponsive 
And server hosting is different. Can you tell me what the problem is?

**Comment by earth2016** [comment] 2019-09-09 21:57
mixa37region told us:
> Several server admins Rust. Often kick players from the server (random players and randomly kick) with such messages in the console...
> Kicked: Steam: AuthTicketCanceled
> Kicked: Steam: Unresponsive
> And server hosting is different. Can you tell me what the problem is?



Maybe you have some connection problems with the server, a high ping on it, so you could change the server to closer to you, a local server could be ok. You could connect 2 users with rust client to same server and one is the admin, kick off the another guy with a message (using the command server: kick <steam64 or playername> reason), you should see the same symptoms. Try to use a little map, because Rust is going to use 16G RAM and 6GB NVRAM. You also need to know your hardware specifications and check if they match with Rust Client system requirement.

**Comment by kisak-valve** [comment] 2020-10-23 14:05
Hello @earth2016, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment] 2020-11-27 14:54
Closing as outdated.

**Closed by kisak-valve** 2020-11-27 14:54 UTC
Labels: 3rd party game, Need Retest

**Comment by nghialele** [comment] 2024-10-28 16:20
This still happening as of today.

**Comment by FrZ-BR** [comment] 2025-01-05 18:38
Not solved.
