### ISSUE TITLE
[KDE] Panel doesn't disappear when using Big Picture

### ISSUE THREAD

**Issue by DrDoctor13** [ValveSoftware/steam-for-linux#4835] opened 2017-01-28 17:17 UTC
#### Your system information

* Steam client version: 1.0.0.54-2
* Distribution (e.g. Ubuntu): Manjaro 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Expected: After running a game in Big Picture and closing it, Big Picture should appear at the front and cover everything.

Reality: After running a game in Big Picture and closing it, Big Picture reappears, but my panel appears above it until I minimize and restore the Big Picture window, such as by alt-tabbing to another application then back.

#### Steps for reproducing this issue:

1. Open Big Picture in KDE Plasma
2. Run any game (I used A Bird Story in full screen for this)
3. Close it
4. Big Picture will reappear behind the Plasma panel
5. Alt-tab to another program
6. Alt-tab back in
7. The panel will now be gone.

**Comment by kisak-valve** [comment] 2017-01-28 18:15
Hello @DrDoctor13, this looks like a duplicate of #4611 and possibly #4313 which needs to be resolved before evaluating these symptoms. Closing in favor of #4611.

**Closed by kisak-valve** 2017-01-28 18:15 UTC
Labels: Big Picture
