### ISSUE TITLE
Steam does not preserve its workspace across application states

### ISSUE THREAD

**Issue by Mblackwell1024** [ValveSoftware/steam-for-linux#2462] opened 2013-05-12 10:59 UTC
Using GNOME Shell 3.8 (but this happens on previous versions of GNOME Shell), Steam can be started on a new workspace, but its current workspace will not be preserved between:

Updating Steam
Starting Steam
Main Steam Application

This results in (on my part) needing to wait for Steam to start completely and then moving windows around, and in the meantime windows popping up into focus on my current workspace.

**Comment by ramma** [comment] 2015-09-03 00:58
Similar situation on Ubuntu 14.04.1 LTS. Certain windows when first opened after start will open on the first workspace / virtual desktop no matter which workspace the Steam client is on. Most notably this happens with the friend list, which also periodically gets closed when idle.

**Comment by kisak-valve** [comment] 2017-05-05 00:26
Closing as a duplicate of #353

**Closed by kisak-valve** 2017-05-05 00:26 UTC
Labels: Feature Request, reviewed, Steam client
