### ISSUE TITLE
Steam Play (Proton) games fail to stream correctly

### ISSUE THREAD

**Issue by howels** [ValveSoftware/steam-for-linux#6360] opened 2019-07-04 11:29 UTC
#### Your system information

* Steam client version (build number or date): 1562035212
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Proton-based games should stream as Native games do. 

When streaming a native game (Dying Light) the performance is flawless and streaming works perfectly.

When streaming a proton game (Shadow of the Tomb Raider, Assassin's Creed Unity, Heretic: Shadow of the Serpent Riders) only the first frame will be captured and shown on the client. 

The client sees only the first frame of the stream and controls are not passed to the host. The stream will also stop when the game loads an interstitial window prior to going full-screen, the window will be zoomed in on the client but when the server changes to fullscreen the stream will stop.

#### Steps for reproducing this issue:

1. Stream most proton games from Linux to Linux, Linux to Android or Linux to Steam Link
2. Stream will start, often showing the desktop
3. If game goes fullscreen immediately then the first frame is shown and stream halts. If game shows interstitial desktop window before going fullscreen then that window is shown and then the stream stops or closes when switching to fullscreen.

**Comment by kisak-valve** [comment] 2019-07-04 12:43
Hello @howels, this reads like a duplicate of #5831. Closing in favor of the existing issue report.

**Closed by kisak-valve** 2019-07-04 12:43 UTC
