### ISSUE TITLE
Game re-runs after restarting Steam for update

### ISSUE THREAD

**Issue by ali1234** [ValveSoftware/steam-for-linux#3478] opened 2014-09-09 12:05 UTC
To reproduce:
1. Quit Steam if it is running.
2. Click on a launcher for a game. Steam loads up, then the game loads up.
3. Quit the game.
4. Wait for a Steam update.
5. Restart Steam to install update.

Result: Steam exits, downloads the update, automatically re-opens, and then the game you originally ran also loads up.

Expected: The game should not automatically load up when Steam restarts.

**Comment by kisak-valve** [comment] 2017-04-04 17:08
Closing as a duplicate of #1414.

**Closed by kisak-valve** 2017-04-04 17:08 UTC
Labels: reviewed
