### ISSUE TITLE
No connection error on window manager switching with auto-start enabled

### ISSUE THREAD

**Issue by mattyy1hp** [ValveSoftware/steam-for-linux#1321] opened 2013-02-06 16:44 UTC
There is an issue if the "run steam when computer starts" is enabled and window manager switching.

Steps to reproduce:

1/ Enable "run Steam when my computer starts"
2/ Reboot
- system will start
- Steam will start
- everything is OK

3/ Log out from your system
4/ On a login screen choose another window manager
5/ Log in to your system
6/ Nothing happens

---
- Actually, Steam will start, but won't open any window. If I look in to the System Monitor, I can see Steam process with ~160MB in memory and waiting channel "futex_wait_queue_me".
- If I try to start Steam, I get this message:
  mattyy1hp@mattyy1hp-laptop ~ $ steam
  Running Steam on linuxmint 13 64-bit
  STEAM_RUNTIME is enabled automatically
  mattyy1hp@mattyy1hp-laptop ~ $ 
- I have to kill the Steam process. But if I do it and try to start it again, Steam says "could not connect to the Steam network".

Btw. of course, my internet connection is enabled all the time, I has also verified it by "ping" command.

---

My system specs:

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 1400 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 13 Maya (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.6.5-030605-generic
    X Server vendor:  The X.Org Foundation
    X Server release:  11103000

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6520G

```
Driver Version:  4.2.12002 Compatibility Profile Context 9.012
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x6760
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.54" x 7.60"  (15.51" diag)
                                        34.4cm x 19.3cm  (39.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  3418 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  581188 Mb
    Largest Free Hard Disk Block:  153309 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment] 2017-04-03 15:41
Hello @mattyy1hp, are you still experiencing this issue with an up to date system?

After following the reproduction steps on my Arch test box, I could not reproduce this issue, first using KDE5, then Cinnamon.

**Comment by kisak-valve** [comment] 2017-05-08 18:03
Closing pending feedback.

**Closed by kisak-valve** 2017-05-08 18:03 UTC
Labels: Need Retest, reviewed, Steam client
