### ISSUE TITLE
Ubuntu indicator menu empty since Jan 19 version

### ISSUE THREAD

**Issue by jcassee** [ValveSoftware/steam-for-linux#4821] opened 2017-01-20 21:35 UTC
#### Your system information

* Steam client version: 1.0.0.48-1ubuntu / Jan 19 2017
* Distribution (e.g. Ubuntu): 16.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The indicator menu is empty.

(I wanted to make a screenshot, but could not get Ubuntu to make one with the Steam indicator menu open.)

#### Steps for reproducing this issue:

Click the Steam indicator icon. The menu is empty.

**Comment by kisak-valve** [comment] 2017-01-20 22:15
Closing as a duplicate of #4795.

**Closed by kisak-valve** 2017-01-20 22:15 UTC

**Comment by jcassee** [comment] 2017-01-20 22:25
Thanks, @kisak-valve, for pointing me in the right direction. Works again after `apt-get install libdbusmenu-gtk4:i386`.
