### ISSUE TITLE
Manjaro Linux - Steam is not starting (Steam runtime disabled): Line 712: LD_LIBRARY_PATH not set

### ISSUE THREAD

**Issue by vincent-t** [ValveSoftware/steam-for-linux#3729] opened 2015-02-22 09:09 UTC
Since some time steam is not starting anymore on my system.
**When running in terminal i get this output:**
```
Running Steam on manjarolinux 0.8.12 64-bit
STEAM_RUNTIME is disabled by the user
/home/vincent/.local/share/Steam/steam.sh: Zeile 712: LD_LIBRARY_PATH ist nicht gesetzt.
```
**After adding:**
```
export LD_LIBRARY_PATH="/usr/lib"
[vincent@Arbeits-PC ~]$ steam
Running Steam on manjarolinux 0.8.12 64-bit
STEAM_RUNTIME is disabled by the user
Installing breakpad exception handler for appid(steam)/version(1424305157)
```
steam is running again (only in terminal)
To fix this issue permanently i need to edit `~/.local/share/Steam/steam.sh` and replace `export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib32"` with `export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+LD_LIBRARY_PATH:}/usr/lib32"`.
Could you please release an updated version of `steam.sh` which contains this fix.

**Comment by Oxalin** [comment] 2015-02-24 06:05
Duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/3697

**Comment by jyapujuju** [comment] 2015-03-07 16:04
line no 712  in my case

**Comment by johnv-valve** [comment] 2015-07-17 22:16
I believe this is fixed

**Closed by johnv-valve** 2015-07-17 22:16 UTC
Labels: reviewed

**Comment by yanickrochon** [comment] 2017-11-20 04:10
Got same issue. I migrated from Debian to Manjaro, and I get this error. The suggested fix does not longer apply.

**Comment by yusi-09** [comment] 2020-10-20 14:10
Broken for me.
