### ISSUE TITLE
Tray icon does not work on KDE 5.8

### ISSUE THREAD

**Issue by WindohsCrasher** [ValveSoftware/steam-for-linux#4833] opened 2017-01-27 19:18 UTC
#### Your system information

* Steam client version: 1484790260 (19th January)
* Distribution (e.g. Ubuntu): Linux Mint 18.1 KDE x64 (based on Ubuntu 16.04)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
On KDE 5, I can minimize Steam to tray by clicking the "X" in the upper right corner. The window disappears and the tray icon remains. However, the tray icon is completely unresponsive - right clicking, left clicking or double clicking does absolutely nothing. To bring up the Steam window again, I have to click the Steam icon from my app starter menu. Please note that this is not a duplicate of #3519 .

This might be related to KDE 5's limited appindicator functionality, but I don't know exactly.

#### Steps for reproducing this issue:

1. Open Steam in KDE 5.8
2. Click the X in the upper right corner to minimize Steam to tray
3. Left or right click the tray icon - it does nothing

**Comment by kisak-valve** [comment] 2017-01-27 19:45
Closing as a duplicate of #4795. Please see https://github.com/ValveSoftware/steam-for-linux/issues/4795#issuecomment-271268063.

**Closed by kisak-valve** 2017-01-27 19:45 UTC
