### ISSUE TITLE
ubuntu 17.10 desktop shortcuts created but no icons

### ISSUE THREAD

**Issue by charlesalloum** [ValveSoftware/steam-for-linux#5464] opened 2018-04-25 15:50 UTC
#### Your system information

* Steam client version (build number or date): apr 2 2018 API v018 
* Distribution (e.g. Ubuntu): ubuntu 17.10
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No] yes

after upgrading from 16.04 to 17.10 all steam shortcuts are created but without icons...
i tried to to point to the icons but without succeeding...
i format my laptop and proceeded with a fresh installation of ubuntu 17.10 but once i create a shorcut.. same issue re appeared... shortcuts are there but no icons..

#### Steps for reproducing this issue:

1. in library , right click on game, create shortcut

**Comment by kisak-valve** [comment] 2018-04-25 16:51
Hello @charlesalloum, can you give some examples of which games you are creating shortcuts for that were working with 16.04 and not 17.10? Does the shortcut have a generic DE icon or Steam's icon?

Possible duplicate of #989, #4000.

**Comment by charlesalloum** [comment] 2018-04-25 17:05
hello @kisak-valve thanks for your reply.
well im a new user to steam and i only have 4 games: cs go, dota 4, star conflict, team fortres 2,war thunder.... 
these are the games i installed first to try them... i was on 16.04 LTS , but when i upgraded apparently all the shortcuts created from steam client have no icons. they have the generic blank white icon as no icon was assigned.. if you go to the config i can see that the icon line is configured though : icon=steam_icon_730
and this icon is the .steam folder , i even tried to assign the full path but no result

**Comment by charlesalloum** [comment] 2018-04-30 16:12
update: ubuntu 18.04 lts is released, i tested this issue on that too.. same problems.
desktop shortcuts are created but without icons

**Comment by Plagman** [comment] 2018-06-05 01:16
See https://github.com/ValveSoftware/steam-for-linux/issues/989 and report any issues there when the next Beta hits.

**Closed by Plagman** 2018-06-05 01:16 UTC
Labels: Distro Family: Ubuntu, Steam client, Window manager
