### ISSUE TITLE
Relaunching an instance of Steam opened by opening game through automatically created shortcuts launches the game too.

### ISSUE THREAD

**Issue by MarkSill** [ValveSoftware/steam-for-linux#4907] opened 2017-03-23 06:06 UTC
#### Your system information

* Steam client version (build number or date): Mar 22 2017, at 23:45:04
* Distribution (e.g. Ubuntu): Linux Mint 18.1
* Opted into Steam client beta?: No
* Have you checked for system updates?: Just updated.

#### Please describe your issue in as much detail as possible:

Earlier today, I opened a game on Steam through its shortcut, which opened Steam. Later, Steam updated and when it finished, it also relaunched the game. This also works when coming in and out of offline mode.

#### Steps for reproducing this issue:

1. Close Steam if running.
2. Open a game through its shortcut.
3. Exit the game.
4. Relaunch Steam by updating or entering/exiting offline mode.
5. The game opens again.

**Comment by kisak-valve** [comment] 2020-01-03 14:54
Closing as a duplicate of #1414.

**Closed by kisak-valve** 2020-01-03 14:54 UTC
