### ISSUE TITLE
Steam is now giving the "Buffer I/O error on dev sr0, logical block 7, async page read" upon launch since the October Update.

### ISSUE THREAD

**Issue by Redbatman89** [ValveSoftware/steam-for-linux#8133] opened 2021-10-08 15:02 UTC
Since the steam update on October 6th I'm getting the "Buffer I/O error on dev sr0, logical block 7, async page read" flooding my gnome logs. It used to only happen when I would open a game with proton, but now it happens when I launch steam or when I resume my PC from sleep/suspend (steam is still on when I suspend). Please look to fix this.

**Comment by kisak-valve** [comment] 2021-10-08 15:23
Duplicate of #8002.

**Closed by kisak-valve** 2021-10-08 15:23 UTC
