### ISSUE TITLE
Accessing a network share for backup/restore is a pain

### ISSUE THREAD

**Issue by mmeyran** [ValveSoftware/steam-for-linux#6203] opened 2019-04-08 07:46 UTC
#### Your system information

* Steam client version (build number or date): latest
* Distribution (e.g. Ubuntu): 08.04.2 LTS
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
The file browser included in Steam for backup and restore is extremely basic : Gnome-mounted file shares have to be looked for under /run/user/<UID>/gvfs in a very unfriendly UI (small, no shortcuts to devices or current mount point).
Please use the desktop environment's default file browser instead.

#### Steps for reproducing this issue:

1. start to backup or restore a game located on a remote network share
2. use the custom Steam file browser to locate said network share
3. use the custom Steam file browser to browse the network share once you eventually locate it.

**Comment by kisak-valve** [comment] 2019-04-08 12:34
Hello @mmeyran, this is functionally a duplicate of #4003. Closing in favor of the existing feature request.

**Closed by kisak-valve** 2019-04-08 12:34 UTC
