### ISSUE TITLE
BPM minimized or hidden after quitting game

### ISSUE THREAD

**Issue by vampyrex13** [ValveSoftware/steam-for-linux#4769] opened 2016-12-20 16:16 UTC
#### Your system information

* Steam client version: 1481318740
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Whenever I start a game from BPM and then close it, BPM is minimized or not accessible unless I run the shortcut for steam again. In OpenBox, I am left with just a black screen and mouse. In the normal desktop, BPM is completely minimized. This is causing a headache because I launch Steam from within Kodi and it keeps losing focus due to minimizing every time I quit a game.

#### Steps for reproducing this issue:

1. Open Steam either in OpenBox or normal Ubuntu Desktop in BPM.
2. Start any In-Home Streaming game from a PC.
3. Quit game.

**Comment by vampyrex13** [comment] 2016-12-22 13:55
Tried using the beta version as well. Same problem exists. I know of another user also experiencing the same issue, so I know it's not just me.

**Comment by prcastro** [comment] 2017-01-10 11:18
I can also confirm this issue

**Your system information**

- Steam client version: 1482202200
- Distribution: Arch Linux
- Opted into Steam client beta:  No
- Have you checked for system updates?: Yes

**Comment by chrisaq** [comment] 2017-02-04 20:36
Same problem here.

- Steam client version: 1486166473
- Distribution: Arch Linux
- Opted into Steam client beta: Yes
- Have you checked for system updates?: Yes

**Comment by silverhammermba** [comment] 2017-07-23 03:27
Same issue with Steam 1500335472 and latest Arch Linux. Pretty annoying because my streaming box has no keyboard so I had to set up a pretty hacky script to unmiminize Steam after I quit the game.

**Comment by Plagman** [comment] 2017-07-23 05:15
Does restarting Steam with this environment variable set help?

export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0

**Comment by silverhammermba** [comment] 2017-07-23 13:55
That seems to have worked!

**Comment by hchapman** [comment] 2017-09-04 06:14
I have a little HTPC that chugs with Big Picture on the lowest settings. In-home streaming (HW accelerated, normally very crisp and responsive) takes a huge hit with that environment variable enabled (drops frames, unresponsive controls) for me.

**Comment by moonwolf-github** [comment] 2017-10-27 22:12
It works for me (on Fedora) and i haven't noticed any performance issues either directly or through Steam Link.

**Comment by yaomtc** [comment] 2018-10-01 04:04
So, it's been a year... how's it goin dudes. It's still happening to me, but that environment variable works. Don't have a Steam Link so I can't test if in-home streaming is affected.

**Comment by kisak-valve** [comment] 2019-11-01 15:37
Closing in as a duplicate of #4611.

**Closed by kisak-valve** 2019-11-01 15:37 UTC
Labels: Big Picture, reviewed
