### ISSUE TITLE
[Steam Controller] Experimental rumble doesn't work

### ISSUE THREAD

**Issue by YevPo** [ValveSoftware/steam-for-linux#4338] opened 2016-02-27 19:46 UTC
System info: http://pastebin.com/GUZPB2J0

I updated my Steam Client to the latest beta version (24 Feb) and updated controller firmware (19 Feb). After that I tried few games with rumble support but there were no rumble.

Games I tried: Dust: An Elysian Tale, Dirt Showdown and Fez. For all those games I selected standard 'Gamepad' template and enabled 'Experimental rumble emulation' in steam controller options.

It should be noted that rumble works just fine in all those games with Xbox 360 wireless gamepad.

**Comment by Kryuko** [comment] 2016-03-14 19:32
+1, same problem here.
Ubuntu 15.10 64bit, GTX970 i7-3770

**Comment by Nibodhika** [comment] 2016-10-08 13:54
Can confirm, I stumbled across this while writing a simple SDL program that made controllers rumble to identify them, every other controller I tried rumbles fine, but not the Steam Controller. SDL complains about not finding a haptic device.

Tried it on 3 different hardwares all running Arch Linux  64 bits (4.7.6-1).

**Comment by BernardoGO** [comment] 2016-10-16 21:34
Same problem, is there a solution?

**Comment by pppKin** [comment] 2017-05-26 05:18
It's been a year now and still no rumble feedback. Tested in Saint Row IV which rumbles fine with XBox One controller but not with Steam Controller. We badly need it and it would be nice to have it enabled on linux. Thank you Valve.

**Comment by oolongbrothers** [comment] 2017-06-12 19:05
I can confirm this on the Alienware Steam Machine ASM100.

**Comment by Aerol** [comment] 2017-10-02 18:52
Just so it's here and hopefully easier to find than it was for me; rumble emulation works under linux if you use sc-controller.

I don't have the time to dig into why this is, but maybe it'll help somebody figure it out.

**Comment by fosspill** [comment] 2018-05-12 17:32
Same issue on the newest beta firmware. Ubuntu 18.04

**Comment by AlexeyProkhin** [comment] 2018-08-26 07:38
With the introduction of the new steamplay/proton, it is now more important than ever for rumble to be fixed. 
Is there any progress?

**Comment by AlexeyProkhin** [comment] 2018-08-26 08:25
Unfortunately the rumble does not work for me with steam's driver at least in GtaV. Although it works great with sc-controller.

**Comment by dubigrasu** [comment] 2018-08-26 08:31
Yes, like I said, it works for some. I'd say out of 10 games I tried, 7 had rumble working. 
But what I mean is, the basic functionality is there, as opposed with Linux native games where is none whatsoever.

**Comment by AlexeyProkhin** [comment] 2018-09-23 18:46
Since there was not any word on ETA on the issue I decided to look into it myself. I have discovered that rumble definitely works for games that use Steam Controller API (@dubigrasu, thanks for pointing me to Red Faction, by the way).
However, most games does not use SCAPI but rather a gamepad emulated by steam which, as it seems, does not support any haptic effects. Or at least does not properly declare to the games that it can.

Once I confirmed the rumble can be triggered  I knew that somehow the rumble can be fixed without any help from steam developers. So the project [sc-rumble-hack](https://gitlab.com/Prokhin/sc-rumble-hack/tags) was born. It is an alternative implementation of SDL2's haptic subsystem that uses SCAPI to send rumble to a steam controller (or any other gamepad if steam has created an emulated gamepad for it).

To get it activated set game launch options:
```
LD_PRELOAD="/path/to/libsc_rumble_hack.so:$LD_PRELOAD" %command%
```
This is **not** an universal fix. This will work only for games that use SDL2, fortunately, this includes any game running via proton.

Also be aware the project has not been extensively tested. I have quickly tried only three games so far: GTAV, Witcher 3, *native* Rise of The Tomb Raider. The rumble works! (Although, RotTR, for some reason, requires putting LD_PRELOAD into RiseOfTheTomRaider.sh)

**Comment by corvusd** [comment] 2018-11-21 19:47
Is really annoying that valve not give totally support to own gamepad. For me, how temporal and not ideal solution, I use Kozec SC Controller. This give rumble support, very basic but have rumble in games.

**Comment by kisak-valve** [comment] 2019-05-22 23:32
Hello, per "Added support for rumble pass-through for virtual controllers. This fixes missing rumble support for any controllers opted into Steam Input, and rumble emulation support for the Steam controller." in the [2019-05-22](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1612764629382440848) Steam client beta update, please opt into Steam's beta client and retest this issue.

**Comment by LiamDawe** [comment] 2019-05-23 09:02
Tested today across DiRT 4, Bastion, Rocket League and BallisticNG with rumble emulation forced on with the Steam Controller and nothing.

System info: https://pastebin.com/GKQfLcsv

**Comment by Myrddin-Wyllt** [comment] 2019-05-26 19:07
Nope. Not fixed for BlazeRush, Serious Sam Fusion, Victor Vran, or BallisticNG whether forced on or using global input configurations. sc-controller works but sounds like a blender with gravel.

**Comment by Vthyarilops** [comment] 2019-06-16 20:46
@kisak-valve Does this only work with Steam controllers? I have a Dualshock 3 and experience the same lack of rumble, I don't see any Pass through option in Steam Beta client and the rumble still doesn't function.

**Comment by Myrddin-Wyllt** [comment] 2019-07-27 23:17
During the past month, rumble started working for me with Steam Controllers on some games. Rumble with local multiplayer was tested and is working properly for some titles, but absent or improper for others. I'll maintain a list of games here to help development & track progress. More games will be added as time allows.

Fully functional titles include:
+ Victor Vran (Native Linux)
+ Grip: Combat Racing (Proton 4.2-9)

Rumble is Absent:
+ Serious Sam Fusion (Native Linux)

Rumble is Improper:
+ BlazeRush (Proton 4.2-9) intermittent, random rumble

**Comment by aqxa1** [comment] 2020-03-13 07:20
F12019 and MGXP (both Proton 5.0-4) have improper rumble as well (seems to be delayed events).

**Comment by KiralyCraft** [comment] 2021-01-08 22:52
Tested with a DS3 controller wrapped through Steam Input. Running kernel 5.10.2, Proton 5.13-4. Using Steam Build from 5th Jan 2021, 1609891938. Tried to play GTA IV. Controls work fine but no rumble. Not using xboxdrv or any special wrappers other than Steam Input. I have the controller connected via bluetooth. Works fine with ROTR (Native, no Steam Input). Doesn't rumble when I click "Identify" (Which only appears if I enable handling of Playstation controllers) in the general controller settings of Steam

**Comment by kisak-valve** [comment] 2022-10-28 13:02
Hello, is anyone still experiencing this issue on an up to date system? At this point, it would be better to track any follow up issues separately.

**Comment by Blockguy24** [comment] 2022-10-28 14:44
Yes, I have this problem. Should I create a new issue?

**Closed** 2022-12-09 19:43 UTC
Labels: reviewed, Need Retest, Steam controller
