### ISSUE TITLE
Steam icon in tray/on launcher doesn't blink on group message

### ISSUE THREAD

**Issue by TheVekter** [ValveSoftware/steam-for-linux#4006] opened 2015-09-07 01:42 UTC
Exactly what it says on the tin. I know I could turn on sound for each message, but that gets annoying fast when you're in more than one group. I'd rather just have it where either the tray or launcher icon shakes/blinks on incoming message. Is there any way to make this happen?

**Comment by kisak-valve** [comment] 2018-12-14 17:05
Closing as a duplicate of #3835.

**Closed by kisak-valve** 2018-12-14 17:05 UTC
Labels: Feature Request, reviewed
