### ISSUE TITLE
quakelive not showing up in my library

### ISSUE THREAD

**Issue by JJAYL** [ValveSoftware/steam-for-linux#4128] opened 2015-11-11 00:29 UTC
It is not found in my library despite having it before. I talked to quakelive support and they gave me a steam code. I used it, but the game is still nowhere to be found in my library. I looked in the hidden category as well as the games category (where there is no steamOS filter), On the Steam store is says it is in my library.

```
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0xa
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  3200 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.5-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11704000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD BARTS (DRM 2.43.0, LLVM 3.7.0)

    Driver Version:  3.0 Mesa 11.0.4
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x6738
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1600 x 900
    Desktop Resolution: 3520 x 1080
    Primary Display Size: 17.44" x 9.80"  (20.00" diag)
                                            44.3cm x 24.9cm  (50.8cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  3949 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  145962 Mb
    Largest Free Hard Disk Block:  26332 Mb

Installed software:

Recent Failure Reports:
```

**Comment by Tele42** [comment] 2015-11-11 00:52
This sounds like the intended behavior. Go to your library, select "Steamos + Linux" on the search bar, and change it to "Games" to see all games on your account, including games do not support your OS.

**Comment by Tele42** [comment] 2015-11-11 00:55
If you have added Quake Live to your hidden category, you need to change to the games category to show games you own but not supported by your OS, then scroll to the hidden category on the larger list.

**Comment by JJAYL** [comment] 2015-11-11 01:37
Quakelive is in neither my games list nor my hidden list. I am fairly sure my hidden list is unfiltered and that I did not put quakelive in my hidden list.

**Comment by HeWhoWatches** [comment] 2015-11-14 07:25
According to this article, Quake Live is no longer free and no longer available for Linux (which I assume also includes SteamOS): http://linux.softpedia.com/blog/former-free-to-play-quake-live-now-9-99-on-steam-linux-support-dropped-495924.shtml

**Comment by JJAYL** [comment] 2015-11-14 08:29
That is what I originally suspected. I contacted quakelive support first and they gave me a steam key but the game still didn't show up in my library. The steam store and steamDB says I own it. It just isn't showing up in my library.

**Comment by kisak-valve** [comment] 2019-02-01 14:51
Closing as resolved back in 2015.

Related: https://github.com/ValveSoftware/Proton/issues/112

**Closed by kisak-valve** 2019-02-01 14:51 UTC
Labels: reviewed
