### ISSUE TITLE
No smooth scrolling

### ISSUE THREAD

**Issue by KotoWhiskas** [ValveSoftware/steam-for-linux#7839] opened 2021-06-07 11:48 UTC
#### Your system information

* Steam client version (build number or date): May 19 2021 at 01:54:04
* Distribution (e.g. Ubuntu): Pop os 20.04 (based on Ubutnu 20.04 LTS)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Smooth scrolling doesn't work even when "Enable smooth scrolling in web views" and "Enable gpu acceleration" options are enabled, although on the same hardware it works on windows. These options in settings are simply ignored. The features are supported in chromium on linux.

#### Steps for reproducing this issue:

1. Open Steam
2. Scroll

**Comment by kisak-valve** [comment] 2021-06-07 14:30
Hello @KotoWhiskas, these options should work in general, and Steam hands off the `--disable-smooth-scrolling`, `--disable-gpu-compositing`, and `--disable-gpu` CLI options to steamwebhelper when they are disabled, but libcef may be disabling something for its own reasons.

While it's not considered a normal way to troubleshoot, you should be able to completely close Steam, then run `steam -console` in a terminal, login and go to the console tab, and type `open about:gpu` to get the same graphics diagnostics information as upstream chromium. Please click the `Copy Report to Clipboard` button and share it in a [gist](https://gist.github.com). Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a gist, then include links to the gists in this issue report.

**Comment by KotoWhiskas** [comment] 2021-06-07 19:30
Hello, thanks for the reply

Info from about:gpu page - https://gist.github.com/KotoWhiskas/0a6a02c234fbaf9e53326c158f7297da
System info - https://gist.github.com/KotoWhiskas/d79568a5c89b5005a5b616dd0e3a27b7
Output from "steam -console" command - https://gist.github.com/KotoWhiskas/07a5c7984aaf8387255b3fe0fcc33713

**Comment by KotoWhiskas** [comment] 2021-06-07 19:30
@kisak-valve

**Comment by kisak-valve** [comment] 2021-06-07 19:46
Thanks, I think that's telling us that GPU accelerated web views is working as intended. Let's use this issue report to focus on the Steam client's smooth scrolling behavior.

**Comment by KotoWhiskas** [comment] 2021-06-07 20:11
@kisak-valve, In Windows, on the same hardware, scrolling is smoother (when i pull scroll bar), because hardware accelerated rasterization is off on linux, so it's hardware accelerated, but partially. Here's gist with about:gpu from windows - https://gist.github.com/KotoWhiskas/a10f5b5a5dab20c47bdd718a3f379862

**Comment by 20PercentRendered** [comment] 2021-08-02 22:47
I don't think smooth scrolling on linux works with any hardware/software configuration.

**Comment by urbenlegend** [comment] 2021-09-17 16:41
I've been seeing this issue as well on my Gnome Arch install. Smooth scrolling works fine in every other application, including Chromium-based browsers. Only Steam seems to not have smooth scrolling in all views.

**Comment by KotoWhiskas** [comment] 2021-09-17 21:34
By the way, smooth scroll works if I use keyboard arrows, but scroll is laggy compared to windows because on linux it has no gpu rasterization enabled

**Comment by 20PercentRendered** [comment] 2021-09-17 21:38
I feel like this should be fairly high priority considering more and more of the client is being refactored as webpages.

**Comment by 20PercentRendered** [comment] 2021-10-10 10:11
I think the problem lies within the version of cef being so old ANGLE is not supported.
Info from a freshly built cef: https://gist.github.com/20PercentRendered/6bb6323b035dab801c5bdde4942d1465
Info from steam's about:gpu: https://gist.github.com/20PercentRendered/31f6bde0f7153a8904b96a3e1d5aff6b

**Comment by litLizard69** [comment] 2022-07-16 11:46
> I feel like this should be fairly high priority considering more and more of the client is being refactored as webpages.

Definitely. Smooth-Scrolling makes using the client much better.

**Comment by 20PercentRendered** [comment] 2022-07-16 12:31
Would it be possible to open-source steamwebhelper so the community can fix related issues?

**Comment by litLizard69** [comment] 2022-07-16 13:13
> Would it be possible to open-source steamwebhelper so the community can fix related issues?

That would be a good idea because Valve doesn't seem to have this issue at a high priority right now.

**Comment by litLizard69** [comment] 2022-08-01 20:44
**This problem is still present and needs fixing!**

**Comment by litLizard69** [comment] 2022-08-18 16:03
This issue is still present on the newest version of the Steam-Client for Linux and should receive a fix.

**Comment by KotoWhiskas** [comment] 2022-08-19 09:12
> This issue is still present on the newest version of the Steam-Client for Linux and should receive a fix.

I don’t think spamming will help. They’ll end up just locking the issue. There were a 10 year old issues with hundreds of “thumb up” reactions and only some of them they actually fixed recently.

**Comment by litLizard69** [comment] 2022-08-19 09:32
> > This issue is still present on the newest version of the Steam-Client for Linux and should receive a fix.
> 
> I don’t think spamming will help. They’ll end up just locking the issue. There were a 10 year old issues with hundreds of “thumb up” reactions and only some of them they actually fixed recently.

Oh, I'm sorry. I'll stop spamming then.
Weird that their Steam Client for Linux is not made with the care like on Windows even though they think Linux gaming is the future etc.

**Comment by 20PercentRendered** [comment] 2022-08-21 18:16
If you have CEF debugging turned on in Steam, you can open Chrome's `about:inspect` and click on the steam library. Scrolling the library from Chrome's preview window scrolls smoothly, the movement even being mirrored in the Steam client itself. Steamwebhelper seems to have some sort of input issues. Is steamwebhelper calculating scrolling wrong?

And way back when the Steam Deck Recovery image was first posted, I tested the desktop steam client with the steampal branch and `-steamdeck` launch arg. Smooth scrolling worked. This could have been because of the forced scale factor with `-steamdeck`.

**Comment by litLizard69** [comment] 2022-08-21 18:40
> If you have CEF debugging turned on in Steam, you can open Chrome's `about:inspect` and click on the steam library. Scrolling the library from Chrome's preview window scrolls smoothly, the movement even being mirrored in the Steam client itself. Steamwebhelper seems to have some sort of input issues. Is steamwebhelper calculating scrolling wrong?
> 
> And way back when the Steam Deck Recovery image was first posted, I tested the desktop steam client with the steampal branch and `-steamdeck` launch arg. Smooth scrolling worked. This could have been because of the forced scale factor with `-steamdeck`.

How do you enable CEF debugging in Steam (Flatpak)?

**Comment by 20PercentRendered** [comment] 2022-08-21 19:41
To enable remote debugging:
`touch /home/$(whoami)/.var/app/com.valvesoftware.Steam/.local/share/Steam/.cef-enable-remote-debugging`
To disable remote debugging:
`rm /home/$(whoami)/.var/app/com.valvesoftware.Steam/.local/share/Steam/.cef-enable-remote-debugging`
After you're done debugging make sure to disable the debug feature. 
Then, in chrome/chromium you go to `about:inspect` and add `127.0.0.1:8080` into target discovery. And now you can click open any of the pages.

**Comment by litLizard69** [comment] 2022-08-21 20:48
> To enable remote debugging: `touch /home/$(whoami)/.var/app/com.valvesoftware.Steam/.local/share/Steam/.cef-enable-remote-debugging` To disable remote debugging: `rm /home/$(whoami)/.var/app/com.valvesoftware.Steam/.local/share/Steam/.cef-enable-remote-debugging` After you're done debugging make sure to disable the debug feature. Then, in chrome/chromium you go to `about:inspect` and add `127.0.0.1:8080` into target discovery. And now you can click open any of the pages.

Ah, got it. Yeah when scrolling through the chrome tab it is smoother, though not the smooth scrolling from windows. Hopefully Valve will fix that.

**Comment by 20PercentRendered** [comment] 2022-11-13 11:36
Scrolling in gamepadui is smooth.

**Comment by kisak-valve** [comment] 2023-02-19 21:56
Per the feedback on #9219, please retest this issue.

**Comment by 20PercentRendered** [comment] 2023-02-19 22:00
Works in library and friends ui. Does not work in store or other website webviews, like manually opening a page from the console with `open https://google.com`. Works in webhelper popups like properties window's compatibility tool list. Haven't tested the overlay.

**Comment by Bill5122** [comment] 2023-02-19 22:32
Works in library and friends list, but not in the community tab, store tab, or profile tab for me. Everywhere except the library and friends list appears to have the old non-smooth scrolling.  I can confirm that the ingame overlay also has non smooth scrolling everywhere, including the friends list and browser page.

**Comment by KotoWhiskas** [comment] 2023-03-12 15:17
> Works in library and friends list, but not in the community tab, store tab, or profile tab for me. Everywhere except the library and friends list appears to have the old non-smooth scrolling. I can confirm that the ingame overlay also has non smooth scrolling everywhere, including the friends list and browser page.

Can confirm, also those areas that now have smooth mouse scrolling also receive proper touchpad scrolling events, so on touchpad scrolling became smooth

**Comment by KotoWhiskas** [comment] 2023-03-18 14:04
And after the latest beta update it's gone again

**Comment by Bill5122** [comment] 2023-04-28 00:03
As of the latest steam beta, version 1682634349, smooth scrolling is now working everywhere in the regular steam client, as far as I can tell!  However, smooth scrolling is not working in the in-game overlay still.

**Comment by purplebar0** [comment] 2023-04-28 07:06
> As of the latest steam beta, version 1682634349, smooth scrolling is now working everywhere in the regular steam client, as far as I can tell! However, smooth scrolling is not working in the in-game overlay still.

It does, but it is slow due to Chromium 85 (scrolling speed fixed in 109). The current workaround is to use [IMWheel](https://wiki.archlinux.org/title/IMWheel) and configure it as such:

```
# ~/imwheelrc

# Speed up scrolling for pre-109 CEF
"^(Steam|Friends List.*)$"
    None, Up,   Button4, 2
    None, Down, Button5, 2

# Default (or else Ctrl+Scroll and such won't work in any application)
".*"
    Control_L, Up,   Control_L|Button4
    Control_L, Down, Control_L|Button5
    Control_R, Up,   Control_R|Button4
    Control_R, Down, Control_R|Button5
    Shift_L,   Up,   Shift_L|Button4
    Shift_L,   Down, Shift_L|Button5
```

...but considering this is a very dirty hack, I would much, MUCH prefer if something was done to fix it before 2024, when new Chromium versions will be pushed.

**Comment by KotoWhiskas** [comment] 2023-04-29 09:50
> As of the latest steam beta, version 1682634349, smooth scrolling is now working everywhere in the regular steam client, as far as I can tell! However, smooth scrolling is not working in the in-game overlay still.

Last time I checked, smooth scroll didn't work in overlay in windows 10 either

**Comment by kisak-valve** [comment] 2023-06-09 23:29
Closing as implemented.

Hello @Bill5122, feel free to open a new issue report to track your follow up issue.

**Closed by kisak-valve** 2023-06-09 23:29 UTC
Labels: Need Retest, Web Component
