### ISSUE TITLE
Steam will only work preloading libstdc++.so.6 on AMD graphics hardware

### ISSUE THREAD

**Issue by fredddii** [ValveSoftware/steam-for-linux#4725] opened 2016-11-26 19:31 UTC
This issue does not occur on my desktop with NVIDIA or on my notebook with Intel graphics.

I am using the latest Linux Mint. Steam will only work if I launch it as following from a terminal:

> **LD_PRELOAD='/usr/$LIB/libstdc++.so.6' steam**

The default AMDGPU driver is being used (flgrx is deprecated and not available for recent hardware). The card in use is a Sapphire Radeon R9 FURY.

The output of trying to run Steam normally:

> steam
> Running Steam on linuxmint 18 64-bit
> STEAM_RUNTIME is enabled automatically
> [2016-11-26 20:31:41] Startup - updater built Oct 13 2016 00:47:16
> SteamUpdateUI: An X Error occurred
> X Error of failed request:  BadValue (integer parameter out of range for operation)

Took a screenshot of my basic system information and included it as an attachment.

![screenshot from 2016-11-26 20-29-41](https://cloud.githubusercontent.com/assets/15217150/20642733/1d39ba4a-b417-11e6-967e-32f7a891d806.png)

**Comment by Tele42** [comment] 2016-11-26 20:26
Duplicate of https://github.com/ValveSoftware/steam-runtime/issues/34 and many other open steam runtime issue reports (search this repository for libstdc++).

**Comment by gdrewb-valve** [comment] 2016-11-27 16:37
Closing duplicate.

**Closed by gdrewb-valve** 2016-11-27 16:37 UTC
