### ISSUE TITLE
New client update completely breaks the UI for focus-follows-mouse users

### ISSUE THREAD

**Issue by toranmallow** [ValveSoftware/steam-for-linux#9583] opened 2023-06-14 23:53 UTC
#### Your system information

* Steam client version (build number or date): 1686779606
* Distribution (e.g. Ubuntu): Ubuntu 20.04 LTS
* Opted into Steam client beta?: [Yes/No] Probably not, but the Beta Participation section is no longer listed under Settings > Account, so who knows?
* Have you checked for system updates?: [Yes/No] Yes, entire system freshly updated

#### Please describe your issue in as much detail as possible:

Clicking on the Properties selection for a game should always bring up the game's Property screen.  For users with focus-follows-mouse, it no longer does so in the latest Steam client update.  The bug outlined here (https://github.com/ValveSoftware/steam-for-linux/issues/9273) has crept into other parts of the Steam client UI.  There are other non-responsive controls throughout the new UI, leaving the client basically useless.

#### Steps for reproducing this issue:

1.  Start Steam
2.  Find a game in your library
3.  Select Properties for the game
4.  Nothing happens...

#### Work Around

The same work around for this bug (https://github.com/ValveSoftware/steam-for-linux/issues/9273) works in this case, but Big Picture mode sucks for keyboard and mouse PC users.  Going into "Small Mode" can fix some of the issues, but the Proton Version drop down is still busted.

PLEASE FIX.  I have spent way too much money with you all to tolerate this.  Or for god's sake, let us revert back to the old UI.

Signed,
A long time Steam user

**Comment by kisak-valve** [comment] 2023-06-14 23:56
Hello @toranmallow, there's no value in fragmenting the discussion of this issue across multiple issue reports. Closing as a duplicate of #9273.

**Closed by kisak-valve** 2023-06-14 23:56 UTC

**Comment by toranmallow** [comment] 2023-06-14 23:59
It is not a duplicate.  That bug covers one drop down.  This affects different parts of the UI than just the proton version drop down.  You all have a completely broken client now for some people.

**Comment by kisak-valve** [comment] 2023-06-15 00:24
Thanks for the clarification. Re-reading this, #9273 and the older #6 issue reports cover the discussion of the topic and it's better to discuss the issue on the existing issue reports. Feel free to list all the spots where you're having trouble on #6.
