### ISSUE TITLE
Steam UI becomes unusable after resizing or locking screen

### ISSUE THREAD

**Issue by copywrong** [ValveSoftware/steam-for-linux#3528] opened 2014-10-07 19:49 UTC
Steam UI becomes unusable after changing screen resolution or locking screen. It might be related with steamwebhelper (what is that?). Only tray icon is usable, and I can play games and use Steam overlay.

Arch Linux + Xfce + xfwm4 + nvidia

**Comment by eiglow** [comment] 2019-12-06 13:31
I was unable to reproduce this issue. I'm on Fedora KDE with AMD graphics.

**Comment by kisak-valve** [comment] 2020-01-10 23:29
Closing per the last comment.

**Closed by kisak-valve** 2020-01-10 23:29 UTC
Labels: Need Retest, Steam client, reviewed
