### ISSUE TITLE
Missing CEG support in Steam for Linux

### ISSUE THREAD

**Issue by jqadev** [ValveSoftware/steam-for-linux#7035] opened 2020-04-16 07:45 UTC
Dear Team,

an issue with missing CEG support in Steam for Linux is known since Proton has been released, i.e. August 2018.
Multiple Windows games use it and they are listed here: https://github.com/ValveSoftware/Proton/issues/753

Proton Collaborator Andrew Eikum @aeikum wrote [here](https://github.com/ValveSoftware/Proton/issues/753#issuecomment-597610267): 
> Won't help. We need support from the Steam client, but they don't ship CEG support in Steam for Linux. I'll update this bug if there's progress here.

Since Steam for Windows has implemented CEG support, can you use this implementation and add it to Steam for Linux?

@kisak-valve  the issue https://github.com/ValveSoftware/Proton/issues/753 should be transferred from Proton to this repo as it is an issue with Steam for Linux, not with Proton.

**Comment by jqadev** [comment] 2020-04-16 21:03
@kisak-valve, why did you add `duplicate` label? I haven't found another ticket regarding missing CEG support in this repo.
What are you going to do with this issue? There are so many people waiting for the solution.
@Plagman, do you know about this issue?

**Comment by kisak-valve** [comment] 2020-04-16 21:09
Hello @jqadev, as you've clearly indicated, this issue is already being tracked at https://github.com/ValveSoftware/Proton/issues/753 and the value of fragmenting the discussion across multiple issue trackers is tentative at best, which is why this is marked as a duplicate.

**Comment by jqadev** [comment] 2020-04-16 21:13
@kisak-valve, can't you transfer this issue from Proton repo here?

**Comment by jqadev** [comment] 2020-04-16 21:15
@kisak-valve, I don't know if you are a developer but could you please assign this issue to appropriate developer?

**Comment by jqadev** [comment] 2020-04-20 10:42
@kisak-valve, what are you going to do with this issue? Could you please answer my question?

**Comment by kisak-valve** [comment] 2020-04-20 17:35
Friendly reminder that I'm a moderator for Valve's issue trackers on Github and not a Valve dev myself. I don't have special insight to give on this topic. We already know that the developers that are interested in this issue are already aware of it and will let us know on https://github.com/ValveSoftware/Proton/issues/753 if there's something new to test.

You've made it clear that the point of this issue report is to demand that the long-standing issue report be moved needlessly and force a response on the topic. This is wholly unproductive and not going to result in that issue being resolved quicker.

Please stop calling me out to answer questions I can't respond to. Closing as a duplicate of https://github.com/ValveSoftware/Proton/issues/753.

**Closed by kisak-valve** 2020-04-20 17:35 UTC
Labels: Proton, duplicate
