### ISSUE TITLE
[STREAMING] Certain Games will not Recognize Controller

### ISSUE THREAD

**Issue by Joechim94** [ValveSoftware/steam-for-linux#5815] opened 2018-10-06 05:43 UTC
#### Your system information

* Steam client version (build number or date): Sep 8 2018
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Some games will recognize the controller when streaming from **Linux-to-Linux**, but _not_ when streaming from **Windows-to-Linux**.

Client (Controller): Arch Linux
Host (Game): Windows 8.1
Controller: Xbox One S-Controller OR PS3 DualShock 3

#### Steps for reproducing this issue:

1.  Ensure that the controller works for the game in Windows (set it as the active input in options)
2.  Stream a specific game such as _Hyperdimension Neptunia Re;Birth1_ or 2 from Windows **to** Linux
3. Attempt to play the game on Linux by streaming it from Windows
4. Game will not recognize the controller while streaming (no longer appears in options)

When streaming the game from Linux, this issue does not occur.

**Comment by kisak-valve** [comment] 2018-10-06 14:11
Closing as a duplicate of #5554.

**Closed by kisak-valve** 2018-10-06 14:11 UTC
