### ISSUE TITLE
Steam redownloads whole game new after validating content

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/steam-for-linux#5123] opened 2017-08-08 15:34 UTC
#### Your system information

* Steam client version (build number or date):  Built: Jul 17 2017, at 23:10:56
* Distribution (e.g. Ubuntu): Ubuntu 17.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I had very strong network lags in Rocket League, just on my machine under Ubuntu, and not on my brother's machine on Windows. Because of this I thought I should validate the game files, so if some file were wrong and creating this issue, it would be downloaded again and replaced with a working version.
Steam then deleted the whole game and started to download it completely new. Neither my home folder, nor my steam library (which is on an external NTFS partition) are encrypted

#### Steps for reproducing this issue:

1. open steam
2. go into library folder
3. pick some game, click "VERIFY INTEGRITY OF GAME FILES..." in preferences-LOCAL FILES
4. see the game files checked and steam saying it found a whole bunch (it was ~7000 when I tried this on Endless Sky) of wrong files and it starts to download the whole game

**Comment by Zamundaaa** [comment] 2017-08-08 15:52
When the download seemed to be finished I tried to start the game. It then seems to have deleted the game contents anew and started the download again. This happens with all games I tried!

**Comment by Zamundaaa** [comment] 2017-08-08 15:56
![steam_error](https://user-images.githubusercontent.com/20477130/29081458-ed486c40-7c62-11e7-86d1-d01cf0bef8a7.png)
This is what it displayed after the second try

**Comment by Zamundaaa** [comment] 2017-08-08 16:24
More system information: https://gist.github.com/Zamundaaa/8b64dd4af1608559850bee93fe271d3d

**Comment by Zamundaaa** [comment] 2017-08-08 16:58
The game files seem to be in the downloading folder in my steam library. When I copied them into the gamefolder and started steam, I could start the game again. Still trying to verify the integrity of the game folder does result in a new download

**Comment by kisak-valve** [comment] 2017-08-14 13:17
Hello @Zamundaaa, it sounds like you are encountering #4800. Does the workaround at https://github.com/ValveSoftware/steam-for-linux/issues/4800#issuecomment-271763278 avoid the issue?

**Comment by Zamundaaa** [comment] 2017-08-22 13:30
Yes it does. Thanks

**Comment by kisak-valve** [comment] 2017-08-22 13:49
Thanks for testing. Closing as a duplicate of #4800.

**Closed by kisak-valve** 2017-08-22 13:49 UTC
Labels: duplicate, Steam client
