### ISSUE TITLE
Weird issue with KDE

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#5972] opened 2018-12-21 19:37 UTC
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* DE: KDE on Xorg
* Compositor: KWin

Sometimes, strange invisible window overlaps with some desktop icons.
I don't know, how to reproduce that, but i got some info from xorg:
`xwininfo:`
```
xwininfo: Window id: 0x4000037 (has no name)

  Absolute upper-left X:  0
  Absolute upper-left Y:  50
  Relative upper-left X:  0
  Relative upper-left Y:  50
  Width: 446
  Height: 553
  Depth: 24
  Visual: 0x89
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x4000036 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: yes
  Map State: IsViewable
  Override Redirect State: yes
  Corners:  +0+50  -3394+50  -3394-481  +0-481
  -geometry 446x553+0+50
```
`xprop:`
```
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: True
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_MENU, _KDE_NET_WM_WINDOW_TYPE_OVERRIDE
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
WM_CLASS(STRING) = "Steam", "Steam"
```

**Comment by nightsky30** [comment] 2018-12-28 14:31
I run XFCE, but I think we might have the same issue.  Please tell me if I'm wrong.

I don't know if it is the View menu or the Library menu.  I'm leaning towards the Library menu.  But, sometimes if I open one of them it seems like it causes some invisible aspect of the menu to get stuck open.  The Steam menu closes and disappears, but something else gets stuck in the process and it causes a strange floating invisible rectangle the size and shape of the closed menu that shows my background when other windows are on top of it.

It was hard to get a screenshot because most times when I take the screenshot the invisible "window" or what I believe to be the menu in my case disappears in the taken screenshot!  But I caught it this time!

C'est ici!  The incredible invisible floating menu!

![invisible_steam_menu](https://user-images.githubusercontent.com/6024315/50518367-ea9daa80-0a7a-11e9-9ca2-47469c745427.png)

I don't know how to reproduce it either.  I say that I believe it gets stuck because somehow I got it unstuck yesterday after taking the screenshots and it disappeared.  I think I clicked around in the Steam client and that fixed it.

**Comment by nightsky30** [comment] 2019-01-30 02:41
I think this might be fixed with today's beta client update :D

**Comment by kisak-valve** [comment] 2019-03-01 14:44
Thanks for the feedback @nightsky30, closing.

**Closed by kisak-valve** 2019-03-01 14:44 UTC
Labels: Need Retest, Steam client
