### ISSUE TITLE
one steamwebhelper process used >1GB GPU memory

### ISSUE THREAD

**Issue by WhiteSp1rit** [ValveSoftware/steam-for-linux#6962] opened 2020-03-15 13:14 UTC
#### Your system information

* Steam client version, build date: Feb 11 2020, at 19:27:00
* Distribution: Manjaro KDE
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
A single steamwebhelper process consumed 1200 MB video memory, 
nvidia-smi showed:
`0      2941      G   ...logs/cef_log.txt --product-version=Valv  1230MiB`

#### Steps for reproducing this issue:
- open Steam
- browse some pages in the store
- check process video memory consumption with nvidia-smi

Attached cef_log.txt files.
[cef_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/4334239/cef_log.txt)
[cef_log.previous.txt](https://github.com/ValveSoftware/steam-for-linux/files/4334238/cef_log.previous.txt)

**Comment by WhiteSp1rit** [comment] 2020-03-15 14:15
Update: this might be identical to https://github.com/ValveSoftware/steam-for-linux/issues/6715,
each timne I resize Steam window the steamwebhelper grows by about 500MB memory use, does not free up used memory.

I successfully increased steamwebhelper's size past 5GB, and it seems it can be increased indefinitely.

**Comment by kisak-valve** [comment] 2020-03-15 14:18
Hello @WhiteSp1rit, there's no point in tracking this issue in multiple issue reports. Closing as a duplicate of #6715.

**Closed by kisak-valve** 2020-03-15 14:18 UTC
Labels: Web Component
