### ISSUE TITLE
Keyboard stops working if Steam overlay is used a few times

### ISSUE THREAD

**Issue by headlesscyborg** [ValveSoftware/steam-for-linux#5471] opened 2018-04-30 12:31 UTC
#### Your system information

* Steam client version (build number or date): Up to date (30th April 2018), stable release
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* System info: https://gist.github.com/thedarkfighter413/b48b5f94a26ffc625ad076873085a3d4

#### Please describe your issue in as much detail as possible:
In the last weeks I've been experiencing a weird issue - keyboard input stops working in specific games if I use the Steam overlay a few times. An example - I start a game, create a lobby and invite some friends using the Steam overlay. Then they join, I can use in-game lobby chat to say "hello". Then I invite a few more people using the Steam overlay and suddenly the game doesn't recognize any keyboard input, I can't type into in-game chat anymore, I can't use my keyboard to control in-game menu although keyboard still works perfectly in Steam overlay. Then I can't move using WASD.
An interesting thing is that my XBOX 360 Wireless controller still works. Also, mouse still works.

This only happens in these games:
- Dawn of War 3
- Tomb Raider (2013)
- Left 4 Dead 2
- XCOM 2 WOTC

Tomb Raider is basically a certainty - it happens everytime. We (a few people) play every Saturday and I (as a lobby creator) have to play with my Xbox controller because keyboard stops working sooner or later as I use Steam overlay to send/reveive messages. The only workaround is restarting the game, then I can play with mouse and keyboard as long as I don't use the Steam overlay.

#### Steps for reproducing this issue:

1. Launch one of the games I mentioned above (for example Tomb Raider)
2. Create a private lobby
3. Invite friends using the Steam overlay
4. Use Steam overlay a few times

#### What I've tried:
- Disabling Steam overlay = it happened anyway when I minimized the game (TR 2013) using "alt+tab" to invite my friends
- Launching the game in windowed mode = didn't help
- Disconnecting my Xbox 360 USB receiver = didn't help

#### Terminal output:
- Terminal output: https://gist.github.com/thedarkfighter413/a54b3d4a288ed283855711cd0681003b

**Comment by thedarkfighter413** [comment] 2018-04-30 14:07
@kisak-valve Hello, sure. Here is the file.
[gameoverlayrenderer.log](https://github.com/ValveSoftware/steam-for-linux/files/1960866/gameoverlayrenderer.log)

**Comment by thedarkfighter413** [comment] 2018-05-22 18:07
It happens to me now everytime in Left 4 Dead 2, Medieval 2: Total War, Total War: Shogun 2 + the games I mentioned above. Any workaround? I lost 2 hours of progress in a Total War game because someone sent me a message, I replied and then and I was unable to save the game without keyboard. Also, people kick me from L4D2 with and call me a "f****** console noob" because I have to play with a controller.

**Comment by omaskery** [comment] 2018-09-02 08:07
Hello, I've also experienced this issue and am able to provide `gameoverlayrenderer.log` files - although in my case it seemed to generate many files with PIDs in the filename - I've attached them all. It also emitted `gameoverlayui.log`, would those also be useful?

[gameoverlayrenderer.16451.log](https://github.com/ValveSoftware/steam-for-linux/files/2343068/gameoverlayrenderer.16451.log)
[gameoverlayrenderer.16489.log](https://github.com/ValveSoftware/steam-for-linux/files/2343069/gameoverlayrenderer.16489.log)
[gameoverlayrenderer.16493.log](https://github.com/ValveSoftware/steam-for-linux/files/2343070/gameoverlayrenderer.16493.log)
[gameoverlayrenderer.16514.log](https://github.com/ValveSoftware/steam-for-linux/files/2343071/gameoverlayrenderer.16514.log)
[gameoverlayrenderer.16517.log](https://github.com/ValveSoftware/steam-for-linux/files/2343072/gameoverlayrenderer.16517.log)

I'm trying to play Two Point Hospital, and I believe I'm on Ubuntu 18.04. I'm not sure of the exact steps to reproduce, but my actions are broadly:

- Be playing the game
- Be in conversation with a steam friend
- Open steam-overlay occasionally to answer received messages from steam friend
- Suddenly find that, in steam-overlay, I am unable to type into the steam chat window anymore
- Close the steam-overlay
- At this point I believe the game will no longer accept keyboard input, but the mouse is fine
- Re-open steam-overlay, which now allows steam's chat window to allow keyboard input
- At this point the game definitely is no longer accepting keyboard input

Please let me know if I can provide any more information or answer any questions that could help lead to a solution :)

**Comment by headlesscyborg** [comment] 2018-10-14 10:11
I am still experiencing this issue. Do you need anything from me to fix it?

**Comment by kisak-valve** [comment] 2020-07-03 13:25
Hello @headlesscyborg, @omaskery, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment] 2020-08-14 13:08
Closing pending feedback.

**Closed by kisak-valve** 2020-08-14 13:08 UTC
Labels: 3rd party game, Need Retest, overlay
