### ISSUE TITLE
[Bug] STEAM client freezes when mousing over "More discussions"

### ISSUE THREAD

**Issue by BloodyIron** [ValveSoftware/steam-for-linux#6784] opened 2019-12-22 17:51 UTC
When I'm reading a discussion thread, on the right side the "More discussions" section, when I mouse over that and it pops up a preview of each thread, it often locks up my STEAM client. This has been happening for well over a year now, and on multiple computers of different hardware, so I'm confident this is a software bug.

I have to wait for the STEAM client to eventually unfreeze itself.

**Comment by BloodyIron** [comment] 2019-12-22 17:51
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 5 2600 Six-Core Processor            
    CPU Family:  0x17
    CPU Model:  0x8
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3400 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 19.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.3.0-24-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12005000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20191210.1

Video Card:
    Driver:  X.Org Radeon RX 580 Series (POLARIS10, DRM 3.33.0, 5.3.0-24-generic, LLVM 9.0.0)
    Driver Version:  4.5 (Compatibility Profile) Mesa 19.2.1
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 119 Hz
    VendorID:  0x1002
    DeviceID:  0x67df
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 20.51" x 11.54" (23.50" diag)
                                            52.1cm x 29.3cm (59.7cm diag)
    Primary VRAM: 8192 MB

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  32110 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Total Hard Disk Space Available:  468426 Mb
    Largest Free Hard Disk Block:  67883 Mb
    VR Headset: None detected

The runtime information tool is preparing a report, please wait...

**Comment by kisak-valve** [comment] 2019-12-22 18:18
Hello @BloodyIron, are you using the xf86-video-amdgpu DDX or xf86-video-modesetting DDX? Please check if you can equally reproduce the issue between them (hint from https://github.com/ValveSoftware/steam-for-linux/issues/4357#issuecomment-198327377).

Possible duplicate of #3994.

**Comment by BloodyIron** [comment] 2019-12-22 21:01
I'm using AMDGPU, however I observed the issue on a GTX 960 on my previous gaming rig with the nvidia proprietary blobs too, which was about a year ago-onward.

**Comment by Wes-Kuegler** [comment] 2020-07-22 23:34
I'm having this exact issue.
<details>
<summary>System Information</summary>
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    CPU Family:  0x6
    CPU Model:  0x9e
    CPU Stepping:  0xa
    CPU Type:  0x0
    Speed:  4300 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Pop!_OS 20.04 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.4.0-7634-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12008000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20200604.0

Video Card:
    Driver:  NVIDIA Corporation GeForce RTX 2060/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 440.100
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 144 Hz
    VendorID:  0x10de
    DeviceID:  0x1f08
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 20.91" x 11.77" (23.98" diag)
                                            53.1cm x 29.9cm (60.9cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 6144 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  7881 Mb

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  933837 Mb
    Largest Free Hard Disk Block:  792108 Mb

Steam Linux Runtime Information:
{
  "can-write-uinput" : true,
  "steam-installation" : {
    "path" : "/home/wes/.steam/debian-installation",
    "data_path" : "/home/wes/.steam/debian-installation",
    "issues" : [
      "steamscript-not-in-environment"
    ]
  },
  "runtime" : {
    "path" : "/home/wes/.steam/debian-installation/ubuntu12_32/steam-runtime",
    "version" : "0.20200604.0",
    "issues" : [
    ],
    "pinned_libs_32" : {
      "list" : [
        " 25828230      4 drwxrwxr-x   2 wes      wes          4096 Jul 14 21:54 pinned_libs_32",
        " 25829442      4 -rw-rw-r--   1 wes      wes            80 Jul 14 21:54 pinned_libs_32/system_libvulkan.so.1",
        " 25829441      4 lrwxrwxrwx   1 wes      wes           106 Jul 14 21:54 pinned_libs_32/libvulkan.so.1 -> /home/wes/.steam/debian-installation/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libvulkan.so.1.2.135",
        " 25829443      0 -rw-rw-r--   1 wes      wes             0 Jul 14 21:54 pinned_libs_32/has_pins"
      ]
    },
    "pinned_libs_64" : {
      "list" : [
        " 25828231      4 drwxrwxr-x   2 wes      wes          4096 Jul 14 21:54 pinned_libs_64",
        " 25828270      4 lrwxrwxrwx   1 wes      wes           113 Jul 14 21:54 pinned_libs_64/libdbusmenu-gtk.so.4 -> /home/wes/.steam/debian-installation/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libdbusmenu-gtk.so.4.0.13",
        " 25829255      4 -rw-rw-r--   1 wes      wes            78 Jul 14 21:54 pinned_libs_64/system_libcurl.so.4",
        " 25829440      4 -rw-rw-r--   1 wes      wes            97 Jul 14 21:54 pinned_libs_64/system_libdbusmenu-glib.so.4",
        " 25829190      4 lrwxrwxrwx   1 wes      wes           104 Jul 14 21:54 pinned_libs_64/libcurl.so.4 -> /home/wes/.steam/debian-installation/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libcurl.so.4.2.0",
        " 25829295      4 -rw-rw-r--   1 wes      wes            84 Jul 14 21:54 pinned_libs_64/system_libvulkan.so.1",
        " 25829438      4 -rw-rw-r--   1 wes      wes            76 Jul 14 21:54 pinned_libs_64/system_libGLU.so.1",
        " 25829256      4 lrwxrwxrwx   1 wes      wes           108 Jul 14 21:54 pinned_libs_64/libvulkan.so.1 -> /home/wes/.steam/debian-installation/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libvulkan.so.1.2.135",
        " 25829296      4 lrwxrwxrwx   1 wes      wes           107 Jul 14 21:54 pinned_libs_64/libGLU.so.1 -> /home/wes/.steam/debian-installation/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libGLU.so.1.3.08004",
        " 25829439      4 lrwxrwxrwx   1 wes      wes           114 Jul 14 21:54 pinned_libs_64/libdbusmenu-glib.so.4 -> /home/wes/.steam/debian-installation/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libdbusmenu-glib.so.4.0.13",
        " 25829444      0 lrwxrwxrwx   1 wes      wes            12 Jul 14 21:54 pinned_libs_64/libcurl.so.3 -> libcurl.so.4",
        " 25829189      0 -rw-rw-r--   1 wes      wes             0 Jul 14 21:54 pinned_libs_64/has_pins",
        " 25828271      4 -rw-rw-r--   1 wes      wes            95 Jul 14 21:54 pinned_libs_64/system_libdbusmenu-gtk.so.4"
      ]
    }
  },
  "os-release" : {
    "id" : "pop",
    "id_like" : [
      "ubuntu",
      "debian"
    ],
    "name" : "Pop!_OS",
    "pretty_name" : "Pop!_OS 20.04 LTS",
    "version_id" : "20.04",
    "version_codename" : "focal"
  },
  "container" : {
    "type" : "none"
  },
  "driver_environment" : [
  ],
  "architectures" : {
    "i386-linux-gnu" : {
      "can-run" : true,
      "library-issues-summary" : [
      ],
      "graphics-details" : {
        "x11/vulkan" : {
          "messages" : "ERROR: [Loader Message] Code 0 : /usr/lib/x86_64-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS64\nERROR: [Loader Message] Code 0 : /usr/lib/x86_64-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS64\nERROR: [Loader Message] Code 0 : /home/wes/.steam/debian-installation/ubuntu12_64/steamoverlayvulkanlayer.so: wrong ELF class: ELFCLASS64\n",
          "renderer" : "GeForce RTX 2060",
          "version" : "1.1.119 (device 10de:1f08) (driver 440.400.0)"
        },
        "glx/gl" : {
          "renderer" : "GeForce RTX 2060/PCIe/SSE2",
          "version" : "4.6.0 NVIDIA 440.100",
          "library-vendor" : "glvnd"
        },
        "egl_x11/gl" : {
          "messages" : "Waffle error: 0x1 WAFFLE_ERROR_FATAL: dlopen(\"libEGL.so.1\") failed: libEGL.so.1: wrong ELF class: ELFCLASS64\n",
          "renderer" : null,
          "version" : null,
          "library-vendor" : "unknown",
          "issues" : [
            "cannot-load"
          ],
          "exit-status" : 1
        },
        "egl_x11/glesv2" : {
          "messages" : "Waffle error: 0x1 WAFFLE_ERROR_FATAL: dlopen(\"libEGL.so.1\") failed: libEGL.so.1: wrong ELF class: ELFCLASS64\n",
          "renderer" : null,
          "version" : null,
          "library-vendor" : "unknown",
          "issues" : [
            "cannot-load"
          ],
          "exit-status" : 1
        }
      },
      "dri_drivers" : [
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/i915_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/i965_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/iris_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/kms_swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/nouveau_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/nouveau_vieux_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/r200_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/r300_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/r600_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/radeon_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/radeonsi_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/virtio_gpu_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/vmwgfx_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/zink_dri.so"
        }
      ],
      "va-api_drivers" : [
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/i965_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/iHD_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/nouveau_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/r600_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/radeonsi_drv_video.so"
        },
        {
          "library_path" : "/home/wes/.steam/debian-installation/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/dri/dummy_drv_video.so"
        }
      ],
      "vdpau_drivers" : [
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_nouveau.so",
          "library_link" : "libvdpau_nouveau.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_nouveau.so.1",
          "library_link" : "libvdpau_nouveau.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_nvidia.so",
          "library_link" : "libvdpau_nvidia.so.440.100"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_nvidia.so.1",
          "library_link" : "libvdpau_nvidia.so.440.100"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_r300.so",
          "library_link" : "libvdpau_r300.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_r300.so.1",
          "library_link" : "libvdpau_r300.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_r600.so",
          "library_link" : "libvdpau_r600.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_r600.so.1",
          "library_link" : "libvdpau_r600.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_radeonsi.so",
          "library_link" : "libvdpau_radeonsi.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_radeonsi.so.1",
          "library_link" : "libvdpau_radeonsi.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_trace.so.1",
          "library_link" : "libvdpau_trace.so.1.0.0"
        }
      ],
      "glx_drivers" : [
        {
          "library_soname" : "libGLX_indirect.so.0",
          "library_path" : "/usr/lib/i386-linux-gnu/libGLX_mesa.so.0.0.0"
        },
        {
          "library_soname" : "libGLX_mesa.so.0",
          "library_path" : "/usr/lib/i386-linux-gnu/libGLX_mesa.so.0.0.0"
        },
        {
          "library_soname" : "libGLX_nvidia.so.0",
          "library_path" : "/usr/lib/i386-linux-gnu/libGLX_nvidia.so.440.100"
        }
      ]
    },
    "x86_64-linux-gnu" : {
      "can-run" : true,
      "library-issues-summary" : [
      ],
      "graphics-details" : {
        "x11/vulkan" : {
          "messages" : "ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS32\nERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32\nERROR: [Loader Message] Code 0 : /home/wes/.steam/debian-installation/ubuntu12_32/steamoverlayvulkanlayer.so: wrong ELF class: ELFCLASS32\n",
          "renderer" : "GeForce RTX 2060",
          "version" : "1.1.119 (device 10de:1f08) (driver 440.400.0)"
        },
        "glx/gl" : {
          "renderer" : "GeForce RTX 2060/PCIe/SSE2",
          "version" : "4.6.0 NVIDIA 440.100",
          "library-vendor" : "glvnd"
        },
        "egl_x11/gl" : {
          "renderer" : "GeForce RTX 2060/PCIe/SSE2",
          "version" : "4.6.0 NVIDIA 440.100",
          "library-vendor" : "glvnd"
        },
        "egl_x11/glesv2" : {
          "renderer" : "GeForce RTX 2060/PCIe/SSE2",
          "version" : "OpenGL ES 3.2 NVIDIA 440.100",
          "library-vendor" : "glvnd"
        }
      },
      "dri_drivers" : [
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/i915_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/i965_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/iris_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/kms_swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/nouveau_vieux_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/r200_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/r300_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/r600_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/radeon_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/virtio_gpu_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/zink_dri.so"
        }
      ],
      "va-api_drivers" : [
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/nouveau_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/r600_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so"
        },
        {
          "library_path" : "/home/wes/.steam/debian-installation/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/dri/dummy_drv_video.so"
        }
      ],
      "vdpau_drivers" : [
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_nouveau.so",
          "library_link" : "libvdpau_nouveau.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_nouveau.so.1",
          "library_link" : "libvdpau_nouveau.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_nvidia.so",
          "library_link" : "libvdpau_nvidia.so.440.100"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_nvidia.so.1",
          "library_link" : "libvdpau_nvidia.so.440.100"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_r300.so",
          "library_link" : "libvdpau_r300.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_r300.so.1",
          "library_link" : "libvdpau_r300.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_r600.so",
          "library_link" : "libvdpau_r600.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_r600.so.1",
          "library_link" : "libvdpau_r600.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_radeonsi.so",
          "library_link" : "libvdpau_radeonsi.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_radeonsi.so.1",
          "library_link" : "libvdpau_radeonsi.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_trace.so.1",
          "library_link" : "libvdpau_trace.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_va_gl.so",
          "library_link" : "libvdpau_va_gl.so.1"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_va_gl.so.1"
        }
      ],
      "glx_drivers" : [
        {
          "library_soname" : "libGLX_indirect.so.0",
          "library_path" : "/usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0"
        },
        {
          "library_soname" : "libGLX_mesa.so.0",
          "library_path" : "/usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0"
        },
        {
          "library_soname" : "libGLX_nvidia.so.0",
          "library_path" : "/usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.440.100"
        }
      ]
    }
  },
  "locale-issues" : [
  ],
  "locales" : {
    "<default>" : {
      "resulting-name" : "en_US.UTF-8",
      "charset" : "UTF-8",
      "is_utf8" : true
    },
    "C" : {
      "resulting-name" : "C",
      "charset" : "ANSI_X3.4-1968",
      "is_utf8" : false
    },
    "C.UTF-8" : {
      "resulting-name" : "C.UTF-8",
      "charset" : "UTF-8",
      "is_utf8" : true
    },
    "en_US.UTF-8" : {
      "resulting-name" : "en_US.UTF-8",
      "charset" : "UTF-8",
      "is_utf8" : true
    }
  },
  "egl" : {
    "icds" : [
      {
        "json_path" : "/usr/share/glvnd/egl_vendor.d/10_nvidia.json",
        "library_path" : "libEGL_nvidia.so.0"
      },
      {
        "json_path" : "/usr/share/glvnd/egl_vendor.d/50_mesa.json",
        "library_path" : "libEGL_mesa.so.0"
      }
    ]
  },
  "vulkan" : {
    "icds" : [
      {
        "json_path" : "/usr/share/vulkan/icd.d/radeon_icd.i686.json",
        "library_path" : "/usr/lib/i386-linux-gnu/libvulkan_radeon.so",
        "api_version" : "1.2.128"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/radeon_icd.x86_64.json",
        "library_path" : "/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so",
        "api_version" : "1.2.128"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/intel_icd.x86_64.json",
        "library_path" : "/usr/lib/x86_64-linux-gnu/libvulkan_intel.so",
        "api_version" : "1.2.131"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/nvidia_icd.json",
        "library_path" : "libGLX_nvidia.so.0",
        "api_version" : "1.1.119"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/intel_icd.i686.json",
        "library_path" : "/usr/lib/i386-linux-gnu/libvulkan_intel.so",
        "api_version" : "1.2.131"
      }
    ]
  },
  "desktop-entries" : [
    {
      "id" : "steam.desktop",
      "commandline" : "/usr/games/steam %U",
      "filename" : "/usr/share/applications/steam.desktop",
      "default_steam_uri_handler" : true,
      "steam_uri_handler" : true
    }
  ],
  "cpu-features" : {
    "x86-64" : true,
    "sse3" : true,
    "cmpxchg16b" : true
  }
}

The Steam Linux Runtime container tool is not installed.

</details

**Comment by BloodyIron** [comment] 2020-07-23 02:45
I still have this issue here and there.

**Comment by Marty651** [comment] 2021-03-10 21:54
Is there any chance that this bug gets some attention? I have this since a long time now. When reading discussions in the forum I have always to be careful not to hover accidentally over the "More discussions" field because then everything freezes and I have to wait 20 seconds or so until it unfreezes again. This is very annoying.
My system: Ubuntu 20.04. GeForce GTX 1060, NVIDIA driver.

**Comment by Houtworm** [comment] 2021-05-09 14:09
Same issue here on Arch with a I7-6800K and a GTX1080, Been having it for a very long time

**Comment by arrowgent** [comment] 2021-05-09 14:16
tooltip/hover issue
here is an example

!(https://i.imgur.com/Xq5qvmP.png)

yes this is a longtime bug that supposedly was fixed

**Comment by Redbatman89** [comment] 2021-08-17 23:04
Happening to me as well

**Comment by kisak-valve** [comment] 2022-04-23 01:05
Closing in favor of #3994.

**Closed by kisak-valve** 2022-04-23 01:05 UTC
Labels: duplicate, Distro Family: Ubuntu, Web Component

**Comment by BloodyIron** [comment] 2022-04-25 14:40
Good work @kisak-valve ! Didn't know about that one ;)
