### ISSUE TITLE
Steam doesn't launch - SteamUpdateUI: An X Error occurred

### ISSUE THREAD

**Issue by Tameiki** [ValveSoftware/steam-for-linux#4909] opened 2017-03-24 00:36 UTC
#### Your system information

* Steam client version (build number or date): Mar 13 2017
* Distribution (e.g. Ubuntu): Ubuntu 16.04, 64bits
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Hello,
Since last update (Mar 13 2017), Steam doesn't launch. In the terminal, there is what I found:

~$ steam
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
[2017-03-24 01:29:27] Startup - updater built Mar 13 2017 20:55:20
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)

I already tried, like other people, to remove (or rename with .bak) the two files
~/.steam/steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6
~/.steam/steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6

If you need more information, just ask :)
Thank's

**Comment by kisak-valve** [comment] 2017-03-24 00:54
Hello @Tameiki, I was just discussing a near identical scenario with someone on irc. Can you run `apt install mesa-utils:i386` and use glxinfo and glxgears to confirm your 32 bit opengl driver is sane?

**Comment by Tameiki** [comment] 2017-03-24 00:59
mesa-utils was already installed, here the reply of both command:

~$ glxinfo 
name of display: :0
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  90
  Current serial number in output stream:  91

~$ glxgears 
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  29
  Current serial number in output stream:  30

**Comment by kisak-valve** [comment] 2017-03-24 01:01
right, so steam is just the victim here, if a reboot does not help, then you need to fix your opengl driver.

**Comment by Tameiki** [comment] 2017-03-24 01:02
Ok, I reboot.

**Comment by Tameiki** [comment] 2017-03-24 01:06
Ok, sorry for the disruption, problem solved after reboot.

**Comment by kisak-valve** [comment] 2017-03-24 01:09
Closing as there is nothing actionable.

**Closed by kisak-valve** 2017-03-24 01:09 UTC
Labels: Distro Family: Ubuntu

**Comment by xahon** [comment] 2018-06-05 05:32
Why this issue is closed? I'm compiling now and can't reboot at the moment and can't open steam too. For me reboot helps each time but I think it's not a good fix for the issue

**Comment by elliotf** [comment] 2019-03-09 17:37
@xahon @kielbarry the root cause of the problem (for me, at least) was that I'd done an upgrade of libraries/drivers but had not yet done a reboot to have the new drivers take effect. It's likely some sort of incompatibility between drivers/libraries that are installed and older drivers that are running.

So maybe if you have something that you'll want to have your machine up for and also play games, do a reboot before you start, or avoid doing an upgrade until you're done.

**Comment by alwayslivid** [comment] 2019-03-09 21:59
> @xahon @kielbarry the root cause of the problem (for me, at least) was that I'd done an upgrade of libraries/drivers but had not yet done a reboot to have the new drivers take effect. It's likely some sort of incompatibility between drivers/libraries that are installed and older drivers that are running.
> 
> So maybe if you have something that you'll want to have your machine up for and also play games, do a reboot before you start, or avoid doing an upgrade until you're done.

Personally, although I've seen other people saying that simple reboots worked out for them too, that solution didn't do the job for me. 

I tried to reboot multiple different occasions and ensured that all my drivers (proprietary Nvidia drivers), as well as my Xorg configurations were in order, and they all pretty much appeared normal from my perspective. I'm not an expert.

**Comment by kielbarry** [comment] 2019-03-10 08:52
Likewise. While I don't have access to the computer I was using, it wasn't
a reboot issue and plagued me for quite some time without a solution.

**Comment by rkahani** [comment] 2020-04-28 14:54
Probably missing 32-bit Nvidia driver:
Try this:

`sudo apt-get install libnvidia-gl-390:i386`

ref: 
https://steamcommunity.com/discussions/forum/0/3140616601474785172/

**Comment by glubsy** [comment] 2020-06-05 15:58
For Arch Linux users who installed [nvidia-vulkan](https://aur.archlinux.org/packages/nvidia-vulkan/) driver and landed here, remember to also install the 32bits version of libgl as well like [lib32-nvidia-vulkan-utils](https://aur.archlinux.org/packages/lib32-nvidia-vulkan-utils/).

**Comment by WHK102** [comment] 2020-06-26 19:47
For ubuntu 20.04 and nvidia privative drivers, install `mesa-utils` and reboot.

**Comment by mdesantis** [comment] 2020-06-29 08:11
> For ubuntu 20.04 and nvidia privative drivers, install `mesa-utils` and reboot.

This worked for me. Thanks!

**Comment by JeffreyRodriguez** [comment] 2020-09-26 22:57
> Probably missing 32-bit Nvidia driver:
> Try this:
> 
> `sudo apt-get install libnvidia-gl-390:i386`
> 
> ref:
> https://steamcommunity.com/discussions/forum/0/3140616601474785172/

Fixed it for me after Mint 19 -> 20 upgrade.

**Comment by dp1140a** [comment] 2021-02-12 23:05
This is happening to me as well.  Im on Ubuntu 20.04 .  Steam was working just fine and then it wasnt.

> steam
Running Steam on pop 20.10 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/dave/.local/share/Steam/ubuntu12_32/steam -nominidumps -nobreakpad
[2021-02-12 15:02:57] Startup - updater built Feb  8 2021 05:16:36
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)

**Comment by philippludwig** [comment] 2021-03-23 15:12
This can also happen if your user does not have sufficient permissions; for example, on Gentoo your user must be in the `video` group.

**Comment by chaim1221** [comment] 2021-04-10 01:46
Can also confirm regression on 20.10.

**Comment by anythinga** [comment] 2021-05-06 12:16
> For ubuntu 20.04 and nvidia privative drivers, install o reinstall `mesa-utils` and reboot.

Fixed it for me on pop!_os 20.10 after an apt upgrade, running nvidia proprietary drivers.

**Comment by LevitatingBusinessMan** [comment] 2021-05-06 13:58
As an ArchLinux user I had to install `lib32-nvidia-utils`

**Comment by davad** [comment] 2021-06-24 16:11
> This is happening to me as well. Im on Ubuntu 20.04 . Steam was working just fine and then it wasnt.
> 
> > steam
> > Running Steam on pop 20.10 64-bit
> > STEAM_RUNTIME is enabled automatically
> > Pins up-to-date!
> > Steam client's requirements are satisfied
> > /home/dave/.local/share/Steam/ubuntu12_32/steam -nominidumps -nobreakpad
> > [2021-02-12 15:02:57] Startup - updater built Feb  8 2021 05:16:36
> > SteamUpdateUI: An X Error occurred
> > X Error of failed request:  BadValue (integer parameter out of range for operation)

Same issue here on Ubuntu 20.10 64-bit. The packages `mesa-utils` and `libnvidia-gl-460:i386` are already installed. I think the nvidia driver was upgraded to 460 when it stopped working.

**Comment by shantanubedajna009** [comment] 2021-10-29 21:00
> Probably missing 32-bit Nvidia driver: Try this:
> 
> `sudo apt-get install libnvidia-gl-390:i386`
> 
> ref: https://steamcommunity.com/discussions/forum/0/3140616601474785172/

Thanks , this fixed it i was suspecting something like this simple, cause mine is a fresh install of ubuntu 20.04 without much tweaks

**Comment by Deleetdk** [comment] 2021-11-18 23:21
> For ubuntu 20.04 and nvidia privative drivers, install o reinstall `mesa-utils` and reboot.

Dangerous advice! I decided to do this in two steps, first remove, then install. The problem is that cinnamon depends on this package, so this actually uninstalls the desktop environment! Leads to this issue: https://forums.linuxmint.com/viewtopic.php?t=273579

Using `apt install reinstall mesa-uitls` is alright though.

**Comment by zorkpatrol** [comment] 2022-05-21 04:57
> ArchLinux

Make sure that you're using the right Nvidia driver. I had to install **lib32-nvidia-390xx-utils** from the AUR.

**Comment by yhojann-cl** [comment] 2022-05-21 06:40
> > ArchLinux
> 
> Make sure that you're using the right Nvidia driver. I had to install **lib32-nvidia-390xx-utils** from the AUR.

The recomendes driver for now is nvidia-520.

**Comment by glubsy** [comment] 2022-05-21 10:10
> > > ArchLinux
> > 
> > 
> > Make sure that you're using the right Nvidia driver. I had to install **lib32-nvidia-390xx-utils** from the AUR.
> 
> The recomendes driver for now is nvidia-520.

If your GPU is not supported by the latest driver version, you have to use older versions.

**Comment by elliotf** [comment] 2022-05-21 15:50
I also get this when I perform an upgrade and I have not yet rebooted.

**Comment by PedrocaMarmota** [comment] 2022-06-03 19:22
I have a GTX 1070, and I am using Arch Linux with I3 and after a `sudo pacman -Syy` steam stopped working and started showing this error output, after trying every possible solution above and failing I figured that it could be an Nvidia driver not properly suited for my video card

What fixed it for me was going to the [Nvidia drivers](https://www.nvidia.com.br/Download/index.aspx?lang=br) official website selecting my video card, linux-64 bits and downloading the drivers from there.

After this it was just a matter of turning the .run file into an executable, exiting I3 and logging in as root and running the .run file.

**Comment by aanno** [comment] 2022-08-06 11:51
I had the same error on fedora 36. I'm using the official nvidia driver for a Geforce RTX 2060. The problem in my case was that I forgot to install the 32-bit driver. You can do that with:

sudo dnf install nvidia-driver-libs.i686

More tipps on nvidia on linux could be found on [https://negativo17.org/nvidia-driver/](https://steamcommunity.com/linkfilter/?url=https://negativo17.org/nvidia-driver/)

**Comment by jyn514** [comment] 2024-12-07 17:14
note that this can also happen if you disable your gpu in software at runtime (e.g. with `nvidia-smi drain -p 0000:01:00.0 -m 0`)
