### ISSUE TITLE
Suggestion to errors in control

### ISSUE THREAD

**Issue by dinhokusanagi** [ValveSoftware/steam-for-linux#9085] opened 2023-01-10 05:34 UTC
Here are numerous control -related errors, wouldn't it be viable in Steam to map the control and then generate a file save to PC and Steam read this file?Something like antimicrox does.

**Comment by kisak-valve** [comment] 2023-01-10 13:22
Hello @dinhokusanagi, sorry, but this isn't coherent. Please clarify exactly what errors you are encountering.

**Comment by dinhokusanagi** [comment] 2023-01-10 13:24
> Olá @dinhokusanagi, desculpe, mas isso não é coerente. Por favor, esclareça exatamente quais erros você está encontrando.

https://github.com/ValveSoftware/steam-for-linux/issues/9071#event-8163140532

**Comment by kisak-valve** [comment] 2023-01-10 13:55
Please do not intentionally open duplicate issue reports. Closing as a duplicate of #9049.

**Closed by kisak-valve** 2023-01-10 13:55 UTC
Labels: Need More Information

**Comment by dinhokusanagi** [comment] 2023-01-10 14:04
If you notice the text is a suggestion and not a problem report, it is very explicit.
What you should do are not doing is solving the problem, I need to play the games I paid and you are not having the responsibility to solve.

**Comment by dinhokusanagi** [comment] 2023-01-10 14:04
> Por favor, não abra intencionalmente relatórios de problemas duplicados. Fechando como uma duplicata de [ #9049 ](https://github.com/ValveSoftware/steam-for-linux/issues/9049) .

If you notice the text is a suggestion and not a problem report, it is very explicit.
What you should do are not doing is solving the problem, I need to play the games I paid and you are not having the responsibility to solve.
