### ISSUE TITLE
Add DOSBox to Steam Runtime for use with DOS games [Feature]

### ISSUE THREAD

**Issue by MartynHare** [ValveSoftware/steam-for-linux#5779] opened 2018-09-23 17:26 UTC
# Feature Request
Add DOSBox to Steam Runtime for use with DOS games

## Description
Extend Steam Runtime to use native Linux DOSBox for DOS-based games.  

## Business Case
Add this and all the DOSBox games for Windows will start "just working" as legitimate Linux-native games, relative to how DOSBox games are referred to as Windows-native on the storefront.  This will improve sales of games, benefitting both the game developers and Valve through their cut from sales.  A subset of the Linux gaming market purchases Linux-supported games on principle, additionally many of these games are sold as Linux-native on a rival storefront (GOG) already, indicating a market.  

Additionally, this will increase the library of SteamOS games, giving OEMs more of an incentive to manufacture Steam Machines in the future.

## Risks
No brainer, the work is minimal and the rewards on paper look reasonable.

**Comment by kisak-valve** [comment] 2018-09-23 17:34
Closing as a duplicate of https://github.com/ValveSoftware/Proton/issues/1566.

**Closed by kisak-valve** 2018-09-23 17:34 UTC
