### ISSUE TITLE
Steam not launching

### ISSUE THREAD

**Issue by duckster** [ValveSoftware/steam-for-linux#7596] opened 2021-01-09 20:59 UTC
#### Your system information

* Steam client version (build number or date): Installed today via flatpak (9th Jan 2021)
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?:No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
 127 ❯ flatpak run com.valvesoftware.Steam
https://github.com/flathub/com.valvesoftware.Steam/wiki
Overriding TZ to Europe/Vienna
Running Steam on org.freedesktop.platform 20.08.3 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/sekular/.local/share/Steam/ubuntu12_32/steam --version
[2021-01-09 21:56:36] Startup - updater built Dec 20 2020 23:07:02
Installing breakpad exception handler for appid(steam)/version(1608507519)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
SteamUpdateUI: An X Error occurred
X Error of failed request:  GLXBadContext
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  45
xerror_handler: X failed, continuing
Major opcode of failed request:  151 (GLX)
Minor opcode of failed request:  6 (X_GLXIsDirect)
Serial number of failed request:  46
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2021-01-09 21:56:36] Loading cached metrics from disk (/home/sekular/.local/share/Steam/package/steam_client_metrics.bin)
[2021-01-09 21:56:36] Using the following download hosts for Public, Realm steamglobal
[2021-01-09 21:56:36] 1. http://media4.steampowered.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
Installing breakpad exception handler for appid(steam)/version(1608507519)
[2021-01-09 21:56:36] Checking for update on startup
[2021-01-09 21:56:36] Checking for available updates...
[2021-01-09 21:56:36] Downloading manifest: http://media4.steampowered.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1608507519)
[2021-01-09 21:56:37] Download skipped: /client/steam_client_ubuntu12 version 1608507519, installed version 1608507519, downloaded version 0
[2021-01-09 21:56:37] Nothing to do
[2021-01-09 21:56:37] Verifying installation...
[2021-01-09 21:56:37] Performing checksum verification of executable files
[2021-01-09 21:56:37] Verification complete
Loaded SDL version 2.0.14-6278618
Gtk-Message: 21:56:37.495: Failed to load module "gail"
Gtk-Message: 21:56:37.496: Failed to load module "atk-bridge"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  151
Serial number of failed request:  51
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151
Value in failed request:  0x0
Serial number of failed request:  50
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  151
Serial number of failed request:  52
xerror_handler: X failed, continuing
crash_20210109215636_1.dmp[217]: Uploading dump (out-of-process)
/tmp/dumps/crash_20210109215636_1.dmp
/home/sekular/.local/share/Steam/steam.sh: line 759:   139 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

nvidia driver: 455.23.05
CUDA version: 11.1 (uninstalling CUDA is not an option for me, as i need this for my deep learning projects)

#### Steps for reproducing this issue:

1. Installed with flatpak instructions
2. Launched via command line

**Comment by kisak-valve** [comment] 2021-01-09 21:13
Hello @duckster, swrast is mesa's slower software renderer and the fact that Steam is trying to use it tells us that you're using the nVidia proprietary driver, but don't have 32 bit userspace driver support installed. The nVidia proprietary driver requires that the running kernel module, 32 bit userspace, and 64 bit userspace versions have the same version to work properly.

nVidia's CUDA driver PPA is known not to provide 32 bit userspace support and that issue is being tracked at #5778. You might be able to to workaround the issue by installing a newer nVidia driver than what is bundled with the CUDA packages from https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa/ and install all the CUDA components you need you need without the meta-package(s) that explicitly ask for the version bundled with CUDA.

After that, then Flatpak has a chance to match up to the more widely used driver version inside their container system.

Closing as a duplicate of #5778.

**Closed by kisak-valve** 2021-01-09 21:13 UTC
