### ISSUE TITLE
Num key pad not working in game or Steam overlay. Or responding as directional pad.

### ISSUE THREAD

**Issue by Lance321** [ValveSoftware/steam-for-linux#4592] opened 2016-08-13 23:58 UTC
#### Your system information
- Steam client version: V017 (Updated July 8th, 2016)
- Distribution (e.g. Ubuntu): Ubuntu 16.04
- Opted into Steam client beta?: [Yes/No] No
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

Num pad is not functioning correctly in Steam browser. Only the number "5" is resonding, other numbers jump the cursor around the page as directional buttons (4=left, 8=up, 6=right, 2=down.  9=Home key, 3 = End key.  1= Beginning of line, 7= end of a line). 

Is this by design? I believe that the ten-key pad (num pad) should work as a number pad by default instead of directional pad within steam. 

Note: This is also not functioning as a number pad in game. In game console where you type comands its not responsive.

**Comment by kisak-valve** [comment] 2019-07-19 14:43
Closing as a duplicate of #4170.

**Closed by kisak-valve** 2019-07-19 14:43 UTC
Labels: overlay, reviewed
