### ISSUE TITLE
Encrypted /home folder causes Steam to go crazy

### ISSUE THREAD

**Issue by amarildojr** [ValveSoftware/steam-for-linux#2515] opened 2013-05-23 22:39 UTC
Basically if I have a encrypted folder I can download any source game (from what I could see) and after verifiyng the game's cache Steam starts the download again.

More: https://github.com/ValveSoftware/Source-1-Games/issues/706#issuecomment-18354354, https://github.com/ValveSoftware/Source-1-Games/issues/584, https://github.com/ValveSoftware/Source-1-Games/issues/717#issuecomment-18089731

-----------------------------------------------------------------------------------------------------------------

Update: Added a video showing what happened after downloading Counter Strike Source. I copied the folder before verifiying the cache so I don't have to download it again. The game works fine tho.

http://www.youtube.com/watch?v=mhPqBIx39Ms

Ubuntu 12.04.2 64bit
AMD Athlon II X2 250 @3.6GHz
NVIDIA 9800GT - driver version 310-Experimental

**Comment by robertfoss** [comment] 2015-08-02 19:08
I'm experiencing this bug too.

**Comment by jtrees** [comment] 2015-11-14 16:43
I am also experiencing this issue. If Valve doesn't intend to fix it I wish they would just tell us.

**Comment by riccardobl** [comment] 2015-12-29 02:27
I have this problem with steam installed on an encrypted partition and the library on an unionfs mount.

**Comment by amarildojr** [comment] 2015-12-30 21:38
Seriously? VALVe still haven't fixed this?

**Comment by Plagman** [comment] 2016-01-09 00:25
Hi,

Can you try this scenario with today's Beta client?

**Comment by Spice-King** [comment] 2016-01-09 02:05
Looks good to me. Made a new user on my Ubuntu 15.10 laptop with ``sudo adduser --encrypted-home test-steam``, logged in, opted into the beta and downloaded a few small games. So encryptfs on top of Ext4. Both ``VVVVVV`` and ``Papers, Please`` pass the cache verification just fine, even after restarting the Steam client and a full reboot of the laptop.

![screenshot from 2016-01-08 19-38-23](https://cloud.githubusercontent.com/assets/590498/12213574/74526c58-b640-11e5-9138-fdbcaf4ec506.png)

Would love to hear what is happening with other filesystems people are using.

**Comment by xplt** [comment] 2016-01-09 02:12
Unfortunately, it still doesn't work with ReiserFS and completely re-downloads the files

**Comment by Plagman** [comment] 2016-01-09 02:30
Are you sure you are running the Beta branch and got tonight's update? If so, next step would be to capture an strace log of the issue and try to identify where the problem is.

**Comment by xplt** [comment] 2016-01-09 02:34
Yes, sorry. I jumped to conclusion too early: I thought I had the latest version of Steam, though, I hadn't. Fixed for me as well. Thank you, VALVe!

**Comment by Plagman** [comment] 2016-01-09 02:35
Thanks for double-checking. Going to close this now, feel free to file another issue if running into more problems.

**Closed by Plagman** 2016-01-09 02:35 UTC
Labels: reviewed, Steam client

**Comment by amarildojr** [comment] 2016-01-09 16:32
Nicely done. It only took 2 years to solve it hehehe.
