### ISSUE TITLE
[Feat. Req.] Sync categories between machines/OSs

### ISSUE THREAD

**Issue by ozone89** [ValveSoftware/steam-for-linux#3346] opened 2014-06-05 21:21 UTC
As title says.
For me it would mean create a Linux category while on said OS, so that I could avoid installing its compatible titles when switching to Windows

**Comment by kisak-valve** [comment] 2017-03-28 15:54
Closing as a duplicate of #121.

**Closed by kisak-valve** 2017-03-28 15:54 UTC
Labels: Feature Request, reviewed
