### ISSUE TITLE
[Manjaro Linux; Steam Client] Can't save images from community content. Open button appears in file explorer instead of save button

### ISSUE THREAD

**Issue by bsumner2** [ValveSoftware/steam-for-linux#8543] opened 2022-04-20 05:48 UTC
#### Your system information

* Steam client version (build number or date): Mar 14, 2022, at 19:49:17
* Distribution (e.g. Ubuntu): Manjaro x86_64 5.15.32-1-MANJARO 
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Saving images from "Community Content" pages when viewing games from steam library not working properly. Expected: Steam's built-in file explorer pops up, has, "Save," button, so that I can actually save the image. 
What_Actually_Happened: Steam's built-in file explorer pops up, has, "Open," button, so I can't actually save anything because the file explorer is expecting user to open, not save, a file. 

#### Steps for reproducing this issue:

1. From Games Library, click on any game, and scroll down to the community content underneath the play game button. 
2. Click on any image post in community content section.
3. Right click image and select, "Save screenshot as," and then you will see the file explorer only has open button - no save button.
![image](https://user-images.githubusercontent.com/88171547/164158251-f0802cbf-eb38-47a6-8d45-82cb0229ed6f.png)
![image](https://user-images.githubusercontent.com/88171547/164158369-482b51f6-0fbd-4b79-86f2-85ec07550d10.png)

##### I understand this is already an issue being investigated at #6698, and, as such, my submission will be obligatorily closed. I get it; however please, hear me out as I like saving photos from other users without having to use print screen.  I understand duplicates from as recent as Dec 2021 have been closed and redirected to #6698. I just worry that #6698 has been buried under new issues/areas in need of improvement - especially now that the Steam Deck is out. 

I just ask that you hear out my plea because I respect the work y'all do. The UI seems a lot more responsive than it does for Windows, and overall with this issue notwithstanding, my experience with the native Linux client has been positive. I understand if the issue doesn't take priority, nevertheless, as I'd imagine, understandably so, that there are bigger fish to tackle. Thanks again, have a good day.

**Comment by kisak-valve** [comment] 2022-04-20 12:33
Hello @bsumner2, fragmented the discussion of an issue over multiple reports isn't productive. Closing as a duplicate of #6698.

**Closed by kisak-valve** 2022-04-20 12:33 UTC
