### ISSUE TITLE
Missing Big Picture Overlay with desktop mode setting

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4825] opened 2017-01-22 15:41 UTC
* Steam client version: 1484790260 (Jan 19 2017)
* Distribution (e.g. Ubuntu): Ubuntu 16.04
* Opted into Steam client beta?: No (checked missing in beta too)
* Have you checked for system updates?: Yes

I wanted to try using Big Picture overlay instead of the standard Desktop overlay (on the Desktop). And I found out Linux client is missing 2 options in Settings > In-Game. I see no reason to exclude first missing option - Big Picture overlay on Desktop. Second missing option is related to SteamVR and that is understandable (until SteamVR comes to Linux).

Image is showing Windows on the left and Linux on the right.
![steam-missing-feature](https://cloud.githubusercontent.com/assets/17696117/22183447/c32f24d4-e0be-11e6-9b73-992b90b10be8.png)

**Comment by kisak-valve** [comment] 2017-01-22 18:18
Hello @predr, let's track the Big Picture Overlay with desktop mode here, and separately track the SteamVR setting after the prerequisite support is implemented on linux.

**Comment by predr** [comment] 2017-01-22 19:24
Hi @kisak-valve. Ok, good idea. Please let me know when this becomes available in beta so I can test it also.

**Comment by parkerlreed** [comment] 2018-08-24 02:38
Any update on this?

**Comment by LiquidPL** [comment] 2019-01-07 00:42
I can confirm that as of January 2019, this option is missing on both the stable, and beta clients. Any further progress on this?

**Comment by PSebs** [comment] 2019-05-15 05:18
I am wondering if there's any progress to this. I would like to know if when it becomes an available option.

**Comment by webodan** [comment] 2019-07-15 02:27
Count me up on this one. It's annoying to have to open up Big Picture and then the game itself to have the Big Picture overlay when all you want is to have the In game overlay of Big Picture instead of the entire client running that way hogging resources.

**Comment by PSebs** [comment] 2019-09-17 23:04
After the new library update. The big picture overlay now seems to be up, but it seems that an invisible Big Picture background process is hogging all the controller input. It makes an unplayable experience with the games I tried with the steam controller or other steam input device.

**Comment by kisak-valve** [comment] 2019-09-17 23:10
Hello @PSebs, you're most likely looking for #6495 for the follow up issue.

**Comment by kisak-valve** [comment] 2019-11-08 15:35
Closing as implemented in the [2019-10-30](https://store.steampowered.com/news/55600/) Steam client update.

**Closed by kisak-valve** 2019-11-08 15:35 UTC
Labels: Big Picture, Steam client
