### ISSUE TITLE
Steam is not able to express why it failed to initialize

### ISSUE THREAD

**Issue by WHK102** [ValveSoftware/steam-for-linux#7225] opened 2020-06-26 17:51 UTC
Today, when I tried to start steam it did not work, no error window or any message appeared, when trying to run it from the terminal I could see the following message:

```bash
$ steam
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/.../.steam/debian-installation/ubuntu12_32/steam -nominidumps -nobreakpad
```

At first glance there is no problem but the graphical interface is not visible and in the list of processes if it appeared to me that Steam was running, so I looked for how to see the problem in more detail: https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Debugging_Steam

```bash
$ DEBUGGER=gdb steam
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
gdb -x whk.steam.gdb.Lmrs --args /home/.../.steam/debian-installation/ubuntu12_32/steam -nominidumps -nobreakpad
GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/.../.steam/debian-installation/ubuntu12_32/steam...
(No debugging symbols found in /home/.../.steam/debian-installation/ubuntu12_32/steam)
(gdb) run
Starting program: /home/.../.steam/debian-installation/ubuntu12_32/steam -nominidumps -nobreakpad
[Depuración de hilo usando libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[2020-06-26 13:36:49] Startup - updater built Jun  4 2020 05:50:42
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
```

At this point I was able to check that if there is an unsatisfied dependency which are probably the nvidia 32-bit drivers mentioned here: https://github.com/ValveSoftware/steam-for-linux/issues/4909

The main problem is not the dependency error itself, but:

- There was no user-level message detailing the problem (for example, a popup or window).
- Execution by terminal indicated that there were no unsatisfied dependency problems, even though it also indicates that `STEAM_RUNTIME` is enabled (with the use of proton), but if there was a dependency problem.

The problem is that Steam is not able to detail the end user when the problem occurred, it simply remained running in the background without showing absolutely anything and to end steam, the process had to be stopped directly. I had to go to advanced tools to be able to detect the problem. Not all users are advanced and it would be a good idea to create an initial preloader that runs steam and detects any errors and this is reported to the end user in a more visual or accessible way.

The same happens for example when a game is not 100% compatible with proton, for example, War Robots is left with the process running without it raising the game itself when you use proton 5, but with proton 4 it works perfectly, the problem is that it does not it is possible to know why it does not work, it is simply not seen and that's it.

**Comment by bigmb** [comment] 2020-06-26 19:23
@WHK102 did you solve it?

**Comment by WHK102** [comment] 2020-06-26 19:46
Yes, try install mesa-utils and reboot. This issue is for display messages from Steam UI. If you need help, use the https://github.com/ValveSoftware/steam-for-linux/issues/4909 issue.

**Comment by kisak-valve** [comment] 2020-07-01 19:24
Closing as a duplicate of #5366.

**Closed by kisak-valve** 2020-07-01 19:24 UTC
Labels: Steam client
