### ISSUE TITLE
steam linux deb package returning 403

### ISSUE THREAD

**Issue by equivalent** [ValveSoftware/steam-for-linux#4729] opened 2016-11-28 23:31 UTC
Given I'm on Steam website 
And I'm running Ubuntu 16.04 linux
When I click Install steam button
Then I see "Forbidden You don't have permission to access /steam/archive/precise/steam_latest.deb on this server."

http://repo.steampowered.com/steam/archive/precise/steam_latest.deb is returning 403

**Comment by Tele42** [comment] 2016-11-28 23:35
Duplicate of #4719.

**Comment by gdrewb-valve** [comment] 2016-11-29 05:01
Closing duplicate.

**Closed by gdrewb-valve** 2016-11-29 05:01 UTC
