### ISSUE TITLE
Big Picture Mode top of window corrupted after minimizing and restoring BPM

### ISSUE THREAD

**Issue by noammor** [ValveSoftware/steam-for-linux#5225] opened 2017-10-29 14:22 UTC
#### Your system information

* Steam client version (build number or date): Oct 27, 2017
* Distribution (e.g. Ubuntu): Ubuntu 17.10
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

After updating to Ubuntu 17.10 - which uses Gnome 3 - I tried Steam Big Picture Mode. I minimized it, which worked. Then I restored it by clicking the icon on the Dock. 

The result is a BPM screen that works normally, but has a corrupted bar at the top of the window. It seems to overlap exactly the bar at the top of the Gnome 3 UI.

#### Steps for reproducing this issue:

1. Start BPM
2. Minimize BPM
3. Click the Steam icon in the Ubuntu Dock.

**Comment by Parduk** [comment] 2017-10-29 14:31
https://bugs.launchpad.net/mutter/+bug/1725649
https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/1725821
fix committed, but not released yet for artful
https://github.com/ValveSoftware/steam-for-linux/issues/5221

**Comment by kisak-valve** [comment] 2017-10-29 16:04
Closing as a duplicate of #5221.

**Closed by kisak-valve** 2017-10-29 16:04 UTC
