### ISSUE TITLE
Login window flickering and no text is displayed

### ISSUE THREAD

**Issue by tapwag** [ValveSoftware/steam-for-linux#6489] opened 2019-09-14 07:12 UTC
#### Your system information

* Steam client version (build number or date): Updated on 14 September 2019
* Distribution (e.g. Ubuntu): openSUSE Tumbleweed
* Opted into Steam client beta?: [Yes/No] Apparently, yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam login window should be displayed okay.
![Bildschirmfoto_2019-09-14_09-11-58](https://user-images.githubusercontent.com/7955030/64904819-bbde6780-d6cf-11e9-84cd-e2e10495d9d1.png)

#### Steps for reproducing this issue:

1. Run steam from the command line

[SteamConsoleOutput.txt](https://github.com/ValveSoftware/steam-for-linux/files/3612407/SteamConsoleOutput.txt)

**Comment by byte1024** [comment] 2019-09-14 12:19
```
(steam:1971): Gtk-WARNING **: 09:05:52.518: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Adwaita/gtk-2.0/main.rc:733: error: unexpected identifier 'direction', expected character '}'

(steam:1971): Gtk-WARNING **: 09:05:52.524: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Adwaita/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
```
This may actually be a system or adwaita theme problem instead of Steam. For instance,
https://askubuntu.com/questions/774664/gtk-warning-unable-to-locate-theme-engine-in-module-path-adwaita-error-o

**Comment by byte1024** [comment] 2019-09-14 13:28
So I really see nothing in the log that is actually the cause of a flicker besides using gtk and adwaita (which is today a part of gtk).

gtk has had flickering problem potential up until this year (still marking duplicates) for a long time now https://bugs.eclipse.org/bugs/show_bug.cgi?id=517671 so you can see if that solution is also cause of the issue here.

**Comment by kisak-valve** [comment] 2022-01-07 20:14
Hello @tapwag, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment] 2022-02-11 20:03
Closing pending feedback.

**Closed by kisak-valve** 2022-02-11 20:03 UTC
Labels: Intel drivers, Steam client, Need Retest, Distro Family: openSUSE
