### ISSUE TITLE
steam client creates too many files in home folder: .steam .steampath .steampid

### ISSUE THREAD

**Issue by Jimbolino** [ValveSoftware/steam-for-linux#6308] opened 2019-06-07 16:05 UTC
#### Your system information

* Steam client version (build number or date): 1556574584
* Distribution (e.g. Ubuntu): Ubuntu 19.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Issue:

Steam creates too many files in the home folder of the user.
I suspect this is probably legacy, because one of them is a broken symlink.
There are currently 3 files/folders in the user's home directory:
```
.steam
.steampath -> /home/username/.steam/sdk32/steam (broken symlink)
.steampid -> /home/username/.steam/steam.pid
```

i suggest moving these folders, or the content of these folders to the appropriate location:
`/home/username/.local/share/Steam`

Or if that's not possible, at least move the .steampath + .steampid inside the .steam folder.

#### Steps for reproducing this issue:

1. Install Steam
2. Run Steam
3. open a console and type `ls -al`

**Comment by kisak-valve** [comment] 2019-06-07 16:24
Hello @Jimbolino, this is a duplicate of the feature request at #1890 and also the legacy Steamworks hacks being tracked at #5245. My understanding is that it's not trivial to move these without breaking some games.

Closing in favor of the existing issue reports.

**Closed by kisak-valve** 2019-06-07 16:24 UTC
