### ISSUE TITLE
Artifact does not star: Unable to query size of supported swapchain formats

### ISSUE THREAD

**Issue by synasius** [ValveSoftware/steam-for-linux#5943] opened 2018-12-08 06:28 UTC
#### Your system information

* Steam client version (build number or date): 1544235369
* Distribution (e.g. Ubuntu): Ubuntu 18.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Graphics Driver: NVIDIA Driver 410

#### Please describe your issue in as much detail as possible:
When I try to start the game I get this error: 
CreateSwapChain(): Unable to query size of supported swapchain formats.

![screenshot from 2018-12-08 07-27-25](https://user-images.githubusercontent.com/217898/49682813-e8b77b80-faba-11e8-9cd7-ea2686279d7c.png)

**Comment by kisak-valve** [comment] 2018-12-08 17:32
Hello @synasius, does any vulkan application work like `vulkaninfo` from `vulkan-tools`?

**Comment by synasius** [comment] 2018-12-09 06:38
Hi @kisak-valve, 
when I try to run `vulkaninfo` I get this error:
``` 
vulkaninfo: /build/vulkan-tools-1.1.92.0~rc3/vulkaninfo/vulkaninfo.c:1309: AppDumpSurfaceFormats: Assertion `!err' failed
```

I must also say that I have `lunarg-vulkan-sdk` installed

This is the complete output from vulkainfo:

```
==========
VULKANINFO
==========

Vulkan Instance Version: 1.1.92



Instance Extensions:
====================
Instance Extensions	count = 16
	VK_EXT_acquire_xlib_display         : extension revision  1
	VK_EXT_debug_report                 : extension revision  9
	VK_EXT_debug_utils                  : extension revision  1
	VK_EXT_direct_mode_display          : extension revision  1
	VK_EXT_display_surface_counter      : extension revision  1
	VK_KHR_device_group_creation        : extension revision  1
	VK_KHR_display                      : extension revision 21
	VK_KHR_external_fence_capabilities  : extension revision  1
	VK_KHR_external_memory_capabilities : extension revision  1
	VK_KHR_external_semaphore_capabilities: extension revision  1
	VK_KHR_get_display_properties2      : extension revision  1
	VK_KHR_get_physical_device_properties2: extension revision  1
	VK_KHR_get_surface_capabilities2    : extension revision  1
	VK_KHR_surface                      : extension revision 25
	VK_KHR_xcb_surface                  : extension revision  6
	VK_KHR_xlib_surface                 : extension revision  6
Layers: count = 16
=======
VK_LAYER_GOOGLE_threading (Google Validation Layer) Vulkan version 1.1.92, layer version 1
	Layer Extensions	count = 1
		VK_EXT_debug_report                 : extension revision  6
	Devices 	count = 1
		GPU id       : 0 (GeForce GTX 1050 Ti)
		Layer-Device Extensions	count = 0

VK_LAYER_GOOGLE_unique_objects (Google Validation Layer) Vulkan version 1.1.92, layer version 1
	Layer Extensions	count = 0
	Devices 	count = 1
		GPU id       : 0 (GeForce GTX 1050 Ti)
		Layer-Device Extensions	count = 0

VK_LAYER_LUNARG_api_dump (LunarG debug layer) Vulkan version 1.1.92, layer version 2
	Layer Extensions	count = 0
	Devices 	count = 1
		GPU id       : 0 (GeForce GTX 1050 Ti)
		Layer-Device Extensions	count = 0

VK_LAYER_LUNARG_assistant_layer (LunarG Validation Layer Factory Layer) Vulkan version 1.1.92, layer version 1
	Layer Extensions	count = 1
		VK_EXT_debug_report                 : extension revision  6
	Devices 	count = 1
		GPU id       : 0 (GeForce GTX 1050 Ti)
		Layer-Device Extensions	count = 1
			VK_EXT_debug_marker                 : extension revision  4

VK_LAYER_LUNARG_core_validation (LunarG Validation Layer) Vulkan version 1.1.92, layer version 1
	Layer Extensions	count = 1
		VK_EXT_debug_report                 : extension revision  6
	Devices 	count = 1
		GPU id       : 0 (GeForce GTX 1050 Ti)
		Layer-Device Extensions	count = 2
			VK_EXT_debug_marker                 : extension revision  4
			VK_EXT_validation_cache             : extension revision  1

VK_LAYER_LUNARG_demo_layer (LunarG Validation Layer Factory Layer) Vulkan version 1.1.92, layer version 1
	Layer Extensions	count = 1
		VK_EXT_debug_report                 : extension revision  6
	Devices 	count = 1
		GPU id       : 0 (GeForce GTX 1050 Ti)
		Layer-Device Extensions	count = 1
			VK_EXT_debug_marker                 : extension revision  4

VK_LAYER_LUNARG_device_simulation (LunarG device simulation layer) Vulkan version 1.1.92, layer version 1
	Layer Extensions	count = 0
	Devices 	count = 1
		GPU id       : 0 (GeForce GTX 1050 Ti)
		Layer-Device Extensions	count = 0

VK_LAYER_LUNARG_monitor (Execution Monitoring Layer) Vulkan version 1.1.92, layer version 1
	Layer Extensions	count = 0
	Devices 	count = 1
		GPU id       : 0 (GeForce GTX 1050 Ti)
		Layer-Device Extensions	count = 0

VK_LAYER_LUNARG_object_tracker (LunarG Validation Layer) Vulkan version 1.1.92, layer version 1
	Layer Extensions	count = 1
		VK_EXT_debug_report                 : extension revision  6
	Devices 	count = 1
		GPU id       : 0 (GeForce GTX 1050 Ti)
		Layer-Device Extensions	count = 1
			VK_EXT_debug_marker                 : extension revision  4

VK_LAYER_LUNARG_parameter_validation (LunarG Validation Layer) Vulkan version 1.1.92, layer version 1
	Layer Extensions	count = 1
		VK_EXT_debug_report                 : extension revision  6
	Devices 	count = 1
		GPU id       : 0 (GeForce GTX 1050 Ti)
		Layer-Device Extensions	count = 1
			VK_EXT_debug_marker                 : extension revision  4

VK_LAYER_LUNARG_screenshot (LunarG image capture layer) Vulkan version 1.1.92, layer version 1
	Layer Extensions	count = 0
	Devices 	count = 1
		GPU id       : 0 (GeForce GTX 1050 Ti)
		Layer-Device Extensions	count = 0

VK_LAYER_LUNARG_standard_validation (LunarG Standard Validation) Vulkan version 1.1.92, layer version 1
	Layer Extensions	count = 1
		VK_EXT_debug_report                 : extension revision  6
	Devices 	count = 1
		GPU id       : 0 (GeForce GTX 1050 Ti)
		Layer-Device Extensions	count = 2
			VK_EXT_debug_marker                 : extension revision  4
			VK_EXT_validation_cache             : extension revision  1

VK_LAYER_LUNARG_starter_layer (LunarG Validation Layer Factory Layer) Vulkan version 1.1.92, layer version 1
	Layer Extensions	count = 1
		VK_EXT_debug_report                 : extension revision  6
	Devices 	count = 1
		GPU id       : 0 (GeForce GTX 1050 Ti)
		Layer-Device Extensions	count = 1
			VK_EXT_debug_marker                 : extension revision  4

VK_LAYER_LUNARG_vktrace (Vktrace tracing library) Vulkan version 1.1.92, layer version 1
	Layer Extensions	count = 0
	Devices 	count = 1
		GPU id       : 0 (GeForce GTX 1050 Ti)
		Layer-Device Extensions	count = 0

VK_LAYER_VALVE_steam_overlay_32 (Steam Overlay Layer) Vulkan version 1.1.73, layer version 1
	Layer Extensions	count = 0
	Devices 	count = 1
		GPU id       : 0 (GeForce GTX 1050 Ti)
		Layer-Device Extensions	count = 0

VK_LAYER_VALVE_steam_overlay_64 (Steam Overlay Layer) Vulkan version 1.1.73, layer version 1
	Layer Extensions	count = 0
	Devices 	count = 1
		GPU id       : 0 (GeForce GTX 1050 Ti)
		Layer-Device Extensions	count = 0

vulkaninfo: /build/vulkan-tools-1.1.92.0~rc3/vulkaninfo/vulkaninfo.c:1309: AppDumpSurfaceFormats: Assertion `!err' failed.
```

**Comment by kisak-valve** [comment] 2018-12-09 13:41
That effectively tells you the vulkan driver stack is broken. I'm going to guess you've hit this packaging snafu: https://www.linuxuprising.com/2018/11/fix-nvidia-graphics-drivers-ppa.html

**Comment by synasius** [comment] 2018-12-09 20:33
Your guess is correct! I'll try one of the suggested fixes or at least I will downgrade to 396.xx
Thanks for your support @kisak-valve

**Comment by synasius** [comment] 2018-12-09 20:59
Your guess is correct! I'll try one of the suggested fixes or at least I will downgrade to 396.xx
Thanks for your support @kisak-valve

**Comment by Lz-Gustavo** [comment] 2019-07-28 23:50
I just faced this same issue on Jul 2019, and fixed it by running `sudo vulkaninfo` first too.

It's just a blind guess, but isn't this caused by the initial configuration of "Use my monitor's default resolution" under Config -> Video -> Resolution? I believe that running the game with a pre-defined resolution would eliminate the needs of `sudo vulkaninfo`, but I'm definitely not sure.

**Comment by kisak-valve** [comment] 2021-05-07 13:31
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by ThunderMikey** [comment] 2021-05-07 21:30
I'm running Manjaro now, so not being able to re-test. But I don't recall I have ever met the same problem again since then.

**Comment by kisak-valve** [comment] 2021-06-11 15:10
Thanks for the feedback @ThunderMikey, closing.

**Closed by kisak-valve** 2021-06-11 15:10 UTC
Labels: Distro Family: Ubuntu, Need Retest

**Comment by SunWukongsCommand** [comment] 2021-12-26 03:46
@kisak-valve I'm currently facing this issue with Dota 2 on Pop!_OS 21.10.


    **Steam client version (build number or date):** Dec 16 2021
    **Distribution (e.g. Ubuntu)**: Pop!_OS 21.10 based on Ubuntu 21.10
    **Opted into Steam client beta?:** [Yes/No] No
    **Have you checked for system updates?:** [Yes/No] Yes

**Please describe your issue in as much detail as possible:**

Attempting to run the game with Vulkan using the Ryzen 7 5800H's iGPU gives me the **Unable to query size of supported swapchain formats** error. Running the game with OpenGL, or running the game with the discrete GPU both work fine.

This is the output from `vulkaninfo`:
```
vulkaninfo
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_lvp.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
ERROR at /build/vulkan-tools-A4vpMj/vulkan-tools-1.2.162.0+dfsg1/vulkaninfo/vulkaninfo.h:248:vkGetPhysicalDeviceSurfacePresentModesKHR failed with ERROR_UNKNOWN
```
