### ISSUE TITLE
Steam does not start with 64bit nvidia-460 driver

### ISSUE THREAD

**Issue by tmvkrpxl0** [ValveSoftware/steam-for-linux#7668] opened 2021-02-22 20:04 UTC
#### Your system information

* Steam client version (build number or date): 1:1.0.0.68
* Distribution (e.g. Ubuntu): Linux mint
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
It should launch without problem
Log: https://pastebin.com/nmd3PU2G

#### Steps for reproducing this issue:

1. Download nvidia-driver-460:amd64 package
2. Download Latest steam
3. Doesn't work because "failed to load driver: swrast"

Note that gpu driver is installed properly, i see it on driver manager and nvidia-smi works, i even played third-party games using vulkan api, and it worked fine and i see gpu usage rising on nvidia-smi. WebGL example works, etc..
This was fine until i installed nvidia-driver-460:amd64 to replace nvidia-driver-460:i386, in other words, i updated my driver from 32bit to 64bit and i encountered this issue

**Comment by kisak-valve** [comment] 2021-02-22 20:14
Hello @tmvkrpxl0, it sounds like 32 bit OpenGL is broken in general on your system and this isn't a Steam-specific issue. Please install the `libnvidia-gl-460:i386` system package. This should provide the missing 32 bit userspace support to go along with the rest of the nVidia driver install.

**Comment by tmvkrpxl0** [comment] 2021-02-22 20:24
> Hello @tmvkrpxl0, it sounds like 32 bit OpenGL is broken in general on your system and this isn't a Steam-specific issue. Please install the `libnvidia-gl-460:i386` system package. This should provide the missing 32 bit userspace support to go along with the rest of the nVidia driver install.

I can't, installing it would break my cuda installation, which requires libnvidia-gl-460:amd64

**Comment by kisak-valve** [comment] 2021-02-22 20:31
The lack of 32 bit userspace support in nVidia's CUDA PPA is a known issue on their side and is being tracked at #5778. That needs to be addressed by nVidia's PPA package maintainers, not by a Valve developer. Please see that issue report for some methods to workaround your issue.

Closing as a duplicate of #5778.

**Closed by kisak-valve** 2021-02-22 20:31 UTC
Labels: Distro Family: Ubuntu, NVIDIA drivers
