### ISSUE TITLE
Regression: Overlay not working.

### ISSUE THREAD

**Issue by nstgc** [ValveSoftware/steam-for-linux#5714] opened 2018-08-31 21:26 UTC
#### Your system information

* Steam client version (build number or date): Aug 30 2018
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
When I try raising the overlay, either via shift+tab or the Steam button on my Steam Controller, nothing happens. This effects both Proton-games and normal Linux games, both launched from BPM and desktop-mode.

#### Work Around

Restarting the client does fix this, but this is still new (at least for me).

#### Steps for reproducing this issue:

0. I was a bit too quick to make this issue. I'm not entirely sure what caused the client to start misbehaving, but once it had, every game seemed to be effected.
1. Launch a game (I tested Dragon Age:Origin UE, The Incredible Adventures of van Helsing, Divinity: Original Sin EE, and Warlock: Master of the Arcane)
2. Trying bring up the overlay with either shift+tab or the Steam button on a Steam Controller.

**Comment by nightsky30** [comment] 2018-09-07 02:01
I've seen this with CSGO within the past day.  I was using desktop mode at the time.

**Comment by gatlinnewhouse** [comment] 2019-12-31 12:03
I have also had this issue. 

At first I thought it might be because I have HIDPI mode on my monitor, because before switching configs to HIDPI the overlay worked in CS:GO for example, but now I only get a grey background from the overlay which appears in the top right quarter of my screen if I shift+tab or when I first start playing CS:GO. 

I do not know what to debug for this, but the issue is not resolved for me :(

**Comment by TTimo** [comment] 2020-01-06 23:16
The initial report was the overlay not working. @gatlinnewhouse your problem seems like incorrect rendering. This is likely specific to your system or configuration, if overlay was broken across the board I think we'd have seen more reports by now. Can you provide the output of Help > System Information?

**Comment by TTimo** [comment] 2020-01-06 23:59
Nevermind, you provided that on the other issue.

**Comment by kisak-valve** [comment] 2020-12-25 22:23
Hello @nstgc, @nightsky30, are either of you still experiencing this issue on an up to date system?

**Comment by nightsky30** [comment] 2020-12-26 00:33
@kisak-valve I have not seen it happen recently, no.

**Comment by nstgc** [comment] 2020-12-26 16:30
> Hello @nstgc, @nightsky30, are either of you still experiencing this issue on an up to date system?

I haven't have this issue in a while.

**Comment by kisak-valve** [comment] 2020-12-26 16:32
Thanks for the feedback, closing.

**Closed by kisak-valve** 2020-12-26 16:32 UTC
Labels: Distro Family: Arch, Need Retest, overlay
