### ISSUE TITLE
No High-DPI Mode

### ISSUE THREAD

**Issue by Swiftpaw** [ValveSoftware/steam-for-linux#3785] opened 2015-04-06 07:56 UTC
Is it coming?  4K monitors are going to become a lot more common this year.

**Comment by UltraFly** [comment] 2017-02-20 21:47
This is a duplicate of bug #3492 User interface almost illegible on HiDPI (“retina”) display

**Comment by kisak-valve** [comment] 2017-02-20 21:52
Thanks @UltraFly, closing in favor of #3492.

**Closed by kisak-valve** 2017-02-20 21:52 UTC
Labels: reviewed
