### ISSUE TITLE
Big Picture launches on wrong monitors

### ISSUE THREAD

**Issue by Disk1of5** [ValveSoftware/steam-for-linux#3520] opened 2014-10-02 16:44 UTC
Hello, I am running a dual screen setup on Mint 17.
Graphics card: Nvidia GTX 770
Windows Manager: Cinnamon 
My primary monitor is DP-1 (Center)
My secondary Monitor is HDMI-1 (Right of)

I have Verified my primary monitor (DP-1) is set correctly in the Nvidia Settings Tool as well as it is also the Primary Display in the Display settings for my Windows Manage AND also with xrandr.
SDL games launch using the correct Display when full screened, but Big Picture still has been using HDMI-1

Thanks!

**Comment by nlfog** [comment] 2017-10-20 16:00
Having the same issue as the above.  Big Picture Mode does not launch on my primary monitor, but my second (middle) monitor, but games open on the primary monitor minimizing BPM on the second monitor.

Ubuntu 17.10
Gnome 3.26.1
Nvidia GTX 950  (Driver Version: 4.5.0 NVIDIA 384.90)
Steam package version: 1508465769 (Build Oct 19 2017 at 18:48:24)

Xrandr output:
HDMI-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 598mm x 336mm
DVI-I-1 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 598mm x 336mm
DP-0 connected 1920x1080+3840+0 (normal left inverted right x axis y axis) 598mm x 336mm

~/.config/monitors.xml output:

> <monitors version="2">
>   <configuration>
>     <migrated/>
>     <logicalmonitor>
>       <x>0</x>
>       <y>0</y>
>       <primary>yes</primary>
>       <monitor>
>         <monitorspec>
>           <connector>HDMI-0</connector>
>           <vendor>BNQ</vendor>
>           <product>0x78ca</product>
>           <serial>0x00005445</serial>
>         </monitorspec>
>         <mode>
>           <width>1920</width>
>           <height>1080</height>
>           <rate>60</rate>
>         </mode>
>       </monitor>
>     </logicalmonitor>
>     <logicalmonitor>
>       <x>1920</x>
>       <y>0</y>
>       <monitor>
>         <monitorspec>
>           <connector>DVI-I-1</connector>
>           <vendor>BNQ</vendor>
>           <product>0x78c3</product>
>           <serial>0x00005445</serial>
>         </monitorspec>
>         <mode>
>           <width>1920</width>
>           <height>1080</height>
>           <rate>60</rate>
>         </mode>
>       </monitor>
>     </logicalmonitor>
>     <logicalmonitor>
>       <x>3840</x>
>       <y>0</y>
>       <monitor>
>         <monitorspec>
>           <connector>DP-0</connector>
>           <vendor>DEL</vendor>
>           <product>0x40f6</product>
>           <serial>0x42514442</serial>
>         </monitorspec>
>         <mode>
>           <width>1920</width>
>           <height>1080</height>
>           <rate>60</rate>
>         </mode>
>       </monitor>
>     </logicalmonitor>
>   </configuration>
>   <configuration>
>     <logicalmonitor>
>       <x>0</x>
>       <y>0</y>
>       <scale>1</scale>
>       <primary>yes</primary>
>       <monitor>
>         <monitorspec>
>           <connector>HDMI-1</connector>
>           <vendor>BNQ</vendor>
>           <product>BenQ GW2760HS</product>
>           <serial>52F01038SL0</serial>
>         </monitorspec>
>         <mode>
>           <width>1920</width>
>           <height>1080</height>
>           <rate>60</rate>
>         </mode>
>       </monitor>
>     </logicalmonitor>
>     <logicalmonitor>
>       <x>1920</x>
>       <y>0</y>
>       <scale>1</scale>
>       <monitor>
>         <monitorspec>
>           <connector>DVI-I-1</connector>
>           <vendor>BNQ</vendor>
>           <product>BenQ GW2750H</product>
>           <serial>6BC00124SL0</serial>
>         </monitorspec>
>         <mode>
>           <width>1920</width>
>           <height>1080</height>
>           <rate>60</rate>
>         </mode>
>       </monitor>
>     </logicalmonitor>
>     <logicalmonitor>
>       <x>3840</x>
>       <y>0</y>
>       <scale>1</scale>
>       <monitor>
>         <monitorspec>
>           <connector>DP-1</connector>
>           <vendor>DEL</vendor>
>           <product>DELL P2717H</product>
>           <serial>YKNFG78MBQDB</serial>
>         </monitorspec>
>         <mode>
>           <width>1920</width>
>           <height>1080</height>
>           <rate>60</rate>
>         </mode>
>       </monitor>
>     </logicalmonitor>
>   </configuration>
>   <configuration>
>     <logicalmonitor>
>       <x>0</x>
>       <y>0</y>
>       <scale>1</scale>
>       <primary>yes</primary>
>       <monitor>
>         <monitorspec>
>           <connector>HDMI-0</connector>
>           <vendor>BNQ</vendor>
>           <product>BenQ GW2760HS</product>
>           <serial>52F01038SL0</serial>
>         </monitorspec>
>         <mode>
>           <width>1920</width>
>           <height>1080</height>
>           <rate>60</rate>
>         </mode>
>       </monitor>
>     </logicalmonitor>
>     <logicalmonitor>
>       <x>1920</x>
>       <y>0</y>
>       <scale>1</scale>
>       <monitor>
>         <monitorspec>
>           <connector>DVI-I-1</connector>
>           <vendor>BNQ</vendor>
>           <product>BenQ GW2750H</product>
>           <serial>6BC00124SL0</serial>
>         </monitorspec>
>         <mode>
>           <width>1920</width>
>           <height>1080</height>
>           <rate>60</rate>
>         </mode>
>       </monitor>
>     </logicalmonitor>
>     <logicalmonitor>
>       <x>3840</x>
>       <y>0</y>
>       <scale>1</scale>
>       <monitor>
>         <monitorspec>
>           <connector>DP-0</connector>
>           <vendor>DEL</vendor>
>           <product>DELL P2717H</product>
>           <serial>YKNFG78MBQDB</serial>
>         </monitorspec>
>         <mode>
>           <width>1920</width>
>           <height>1080</height>
>           <rate>60</rate>
>         </mode>
>       </monitor>
>     </logicalmonitor>
>   </configuration>
> </monitors>

**Comment by fwsGonzo** [comment] 2019-01-14 18:45
I am having this exact issue. I thought it was due to fullscreen not using "virtual monitors", so I tried changing the physical cables around to switch the order. The result is the same, it opens it in my right monitor regardless of where Steam is.

**Comment by Managor** [comment] 2020-02-09 15:34
Has there been any progress on this? I managed to notice that the problem is with focus. BPM opens up on the screen that has the current focus https://youtu.be/D8mBPFUfK_U

I'm on Arch with KDE.

**Comment by Managor** [comment] 2024-04-20 04:33
@kisak-valve I believe this can be closed. It relates to the old BPM and I haven't noticed it happening with the new one.

**Comment by kisak-valve** [comment] 2024-06-08 00:58
Closing per the last comment.

**Closed by kisak-valve** 2024-06-08 00:58 UTC
Labels: Big Picture, reviewed, Need Retest
