### ISSUE TITLE
Issue with Xbox-One-Controller via Steam-Remote-Play

### ISSUE THREAD

**Issue by LoveSpock** [ValveSoftware/steam-for-linux#7052] opened 2020-04-20 09:05 UTC
#### Your system information

* Steam client version (build number or date):  newest (Sorry, Computer is offline)
* Distribution (e.g. Ubuntu): Manjaro 
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

Dear Community,

There is a Problem with my Xbox One Controller. I added the file 99-Steam-Controller-Permes.rules so Steam recognizes my controller now. I am able to configure it or even to play games in my own library. 

But it is not working via Steam-Remote-Play. My Boyfriend has a computer with Windows 10 and hosted the games. We tried to play stuff like Overcooked 1, Mount your friends or humans fall flat. On the other side my keyboard works fine, while he is able to play with both, keyboard and controller. When he tried to play with people using Windows as well, using a controller was possible, so my computer is the only one refusing.
I hope for your help!

Best wishes

Jay

**Comment by ArtificialNebulae** [comment] 2020-04-22 14:15
I think this might be a duplicate of #6951 (which I need to provide updates to; I've tried every beta since the start of the new beta cycle except for the April 2 update that was quickly rescinded, and they have all exhibited the same issue).

**Comment by Hetti** [comment] 2020-04-22 22:04
A friend of mine encounters the same issue. 
Keyboard and Mouse works streamed, but Controller not working as a Client running Manjaro (Arch Linux)

**Comment by blastermaster77** [comment] 2020-05-07 02:54
I have the same problem, I play on Ubuntu 20.04 LTS  and my brothers in Windows 10, whit remote play their keyboard is detected but not their controllers, the use an xbox one controller and a dual shock 4, I tried with navitive games and proton games and same thing, this bug is driving me nutz. please fix. cant enjoy playing with them since we are in lockdown here in Puetor Rico due to corona. sad!  😭

**Comment by Zorrototo** [comment] 2021-03-20 02:56
Currently having the same issue, Host Windows 10 and Client Manjaro Linux, the client can not control with the xbox360 controller (host has a xbox one controller), but the controller is kinda detected as when the host plays with its settings he can trigger controller vibration.

**Comment by slouken** [comment] 2021-09-23 15:14
Duplicate of #7715

**Closed by slouken** 2021-09-23 15:14 UTC
Labels: Streaming, Distro Family: Arch, General controller / Steam Input
