### ISSUE TITLE
there is no sign of proton being enabled in new library

### ISSUE THREAD

**Issue by barfin** [ValveSoftware/steam-for-linux#6494] opened 2019-09-17 17:58 UTC
#### Your system information

* Steam client version (build number or date): Seb 17 2019, at 01:04:36
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
there is no sign of proton being enabled in new library

#### Steps for reproducing this issue:

1. go to library
2. no sign of proton on games

**Comment by dpanter** [comment] 2019-09-17 18:55
It also does not give any indication to which version it will install; native or Proton.

**Comment by Nonecaster** [comment] 2019-09-20 14:23
It also doesn't show which version of Proton is used by which game anymore.

**Comment by barfin** [comment] 2019-10-31 11:00
new steam library is now in stable branch and i don't see this issue fixed ?

**Comment by thunder1410** [comment] 2019-10-31 23:29
I am not a big fan of the new library but I could get use to it. 
But it is just annoying that I don't see if I am starting the game with proton or not. You don't even get the pop-up that your are playing a not supported title through proton.

**Comment by Newbie13XD** [comment] 2019-11-07 18:48
> But it is just annoying that I don't see if I am starting the game with proton or not. You don't even get the pop-up that your are playing a not supported title through proton.

Yes you still do. It only appears the first time you start a game via Proton though, as it always has been.

**Comment by thunder1410** [comment] 2019-11-07 21:19
@Newbie13XD You are right about the first time. But on the old UI there was next to the play button some text telling you you are using x.x.x version of proton to run this game.

**Comment by Managor** [comment] 2019-11-08 15:14
Plz fix

**Comment by Leopard1907** [comment] 2019-11-08 16:43
I can't understand how such a regression is still exists. Amazing

**Comment by LiamDawe** [comment] 2019-11-09 20:28
It is there now. On a game's page, click the I to pull out the extra info.

**Comment by barfin** [comment] 2019-11-10 01:38
> It is there now. On a game's page, click the I to pull out the extra info.

ok but i wish it was somewhere here, previous library was much more clean
![Screenshot from 2019-11-10 05-01-08](https://user-images.githubusercontent.com/37030489/68537396-131f5200-0378-11ea-8110-38fa75b8534f.png)

**Comment by g2p** [comment] 2020-02-19 12:33
Could (I) be made a shortcut/hotkey?
It's a bit tedious to check with the mouse.

**Comment by kisak-valve** [comment] 2021-01-23 13:32
Closing because the issue in the opening post is resolved and #7618 was opened for the follow up feature request.

**Closed by kisak-valve** 2021-01-23 13:32 UTC
Labels: Proton, Steam client
