### ISSUE TITLE
Sometimes steam goes nuts and everywhere you click opens in a new window

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4450] opened 2016-05-17 17:43 UTC
Sometimes steam goes nuts and everywhere you click opens in a new window

**Comment by Cynerd** [comment] 2016-05-20 22:37
This cause by #3451 most probably.

**Comment by ekaris** [comment] 2016-05-21 14:08
Yup, I clicked on shift and problem solved

**Comment by glubsy** [comment] 2016-07-18 12:57
I confirm this. It happens on XFCE, sometimes in KDE but it seems to be less often (my XFCE machine is much less powerful though).

Pressing shift fixes it temporarily, until it happens again.
Really annoying.

**Comment by kisak-valve** [comment] 2019-05-10 17:29
Closing as a duplicate of #3451.

**Closed by kisak-valve** 2019-05-10 17:29 UTC
Labels: reviewed
