### ISSUE TITLE
[linux] web overlay does not work

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#3984] opened 2015-08-26 23:56 UTC
I get the following errors:
ERROR: ld.so: object '/opt/steam/i686/home/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/opt/steam/i686/home/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

**Comment by gdrewb-valve** [comment] 2015-08-27 01:14
What about it doesn't work?  It doesn't come up at all?  The LD_PRELOAD messages are ignorable.

**Comment by sylware** [comment] 2015-08-27 09:47
On Wed, Aug 26, 2015 at 06:14:20PM -0700, Drew Bliss wrote:
> What about it doesn't work?  It doesn't come up at all?  The LD_PRELOAD messages are ignorable.

The weird thing with LD_PRELOAD: it's both overlays, 32 bits and 64 bits.

The "web" overlay does not come up at all: I tried many key shortcuts, none did
work (32 bits games and 64 bits games).
The "bigpicture" overlay does work.

BTW, the "bigpicture" overlay is blinking in dota2 reborn (with all the other
games I did test it, it was displayed fine, but I think they were all 32 bits
games).
I use an amd tahiti xt gpu with a recent mesa stack.

**Comment by sylware** [comment] 2015-08-27 17:42
On Thu, Aug 27, 2015 at 09:46:29AM +0000, sylvain.bertrand@gmail.com wrote:
> ... I think they were all 32 bits games)....

Tested with skyforce anniversary which is 64 bits. Same pb:
"bigpicture" overlay works fine, "web" overlay does not work (but it seems to
load as I get no ELFCLASS64 errors, only ELFCLASS32).

**Comment by gdrewb-valve** [comment] 2015-08-27 18:00
You can get both bitness of errors when games have launchers or launch scripts.  For example a game with a launch script will likely run a 64-bit shell to run the script so the 32-bit overlay will not be compatible.  Then if the game itself is 32-bit the 64-bit overlay will not be compatible and you'll get both messages, so having them both doesn't mean that's the cause of the overlay not working.

**Comment by sylware** [comment] 2015-08-28 10:30
Ok, then the overlay is loaded (was about to check the process maps), but the
"web" version does not work whereas the "bigpicture" version does work-ish
(blinking in dota 2 reborn).
I noticed I don't even get the first notification ("to access the steam
community") from the "web" overlay.

**Comment by sylware** [comment] 2015-08-29 02:59
I installed a linux 4.2.0-rc8, I get:
<6>gameoverlayui[409]: segfault at 204 ip 00000000f774eace sp 00000000ffee9580 error 4 in ld-2.21.so[f773a000+20000]

**Comment by sylware** [comment] 2015-08-29 16:50
Actually, the web overlay segfaults with any linux kernel and glibc 2.21 on my systems.
I switch to bigpicture.

**Comment by kisak-valve** [comment] 2018-12-07 14:31
Hello @sylware, for better or worse, this appears to have been a one-off issue with your personal flavor of linux. If you're still experiencing this issue on an up to date system, it'll need a new investigation. Closing.

**Closed by kisak-valve** 2018-12-07 14:31 UTC
Labels: reviewed

**Comment by sylware** [comment] 2018-12-07 17:43
On Fri, Dec 07, 2018 at 06:31:49AM -0800, kisak-valve wrote:
> Hello @sylware, for better or worse, this appears to have been a one-off
> issue with your personal flavor of linux. If you're still experiencing this
> issue on an up to date system, it'll need a new investigation. Closing.

Was gone a long time ago. Forgot about it.
