### ISSUE TITLE
steam overlay is unusable in some games

### ISSUE THREAD

**Issue by barfin** [ValveSoftware/steam-for-linux#6506] opened 2019-09-18 11:03 UTC
#### Your system information

* Steam client version (build number or date): Sep 17 2019
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
input is so bad you have to click on things 3-4 times so it can perform an action
it wasn't always like this
in previous updates it became like this

#### Steps for reproducing this issue:

1. launch dota2 or dota underlords (a user reported that rocket league has the same issue)
2. shit+tab to go to steam overlay
3. unresponsive overlay (including settings, web browsers, steam chat ,...)

**Comment by Myrddin-Wyllt** [comment] 2019-09-18 15:21
Are you referring to the Big Picture overlay?

I just tested the regular (NON-big picture) overlay & everything worked flawlessly (i.e., the web browser, music player, friends list). I'm using Manjaro, so I doubt this is a distribution issue with Arch. Perhaps it is graphics driver related? 

I've tested L4D2, Shovel Knight, & Torchlight II. All worked with the overlay with all links/buttons functioning.

**Comment by barfin** [comment] 2019-09-18 18:24
no i mean the regular overlay
and i just tested these games

- Dota2 Opengl
- Dota2 Vulkan
- Dota Underlords
- Counter-Strike: global offensive
- Left 4 dead 2
- Rocket league
- Deus Ex the fall (through proton 4.11-5)

and only dota2 (both opengl and vulkan) and dota underlords had this issue so I guess the issue is only in source 2 games

**Comment by Newbie13XD** [comment] 2019-09-18 19:22
>     * Deus Ex the fall

Which D3D/DirectX version does this use? Sounds like the issue might be Vulkan related.

**Comment by Myrddin-Wyllt** [comment] 2019-09-20 14:25
@barfin Change the title to include Source 2 since that seems to be the cause. I don't own any Source 2 games, so I can't help to verify this. Hopefully someone else with the game can corroborate.

**Comment by Newbie13XD** [comment] 2019-09-20 16:21
> @barfin I don't have any Source 2 games installed. Hopefully someone else with the game can corroborate.

Try Dota 2 — it's free! I face the same issue in Dota 2. It's not entirely unresponsive, but it certainly starts working weirdly if I interact with it and isn't really usable. 

Distribution: Fedora 30, video: NVIDIA.

**Comment by sylware** [comment] 2019-09-20 17:53
tried dota2 vulkan/GL on x11 native/state of the art AMD driver stack: the mouse events are going thru the overlay making it hard to use.

**Comment by barfin** [comment] 2019-09-20 18:02
> tried dota2 vulkan/GL on x11 native/state of the art AMD driver stack: the mouse events are going thru the overlay making it hard to use.
> Tested with "distance" (GL), the overlay is fine.

well yeah keyboard is fine
but mouse is really really a pain in the butt

**Comment by piv0tal** [comment] 2019-09-21 03:14
was told to come here from Steam support. Have the same issue on Ubuntu 18 - only Dota2 and Dota Underlords to my knowledge are producing this issue. I made this video to explain it https://streamable.com/elx15

**Comment by Newbie13XD** [comment] 2019-09-21 08:40
> was told to come here from Steam support. Have the same issue on Ubuntu 18 - only Dota2 and Dota Underlords to my knowledge are producing this issue. I made this video to explain it. It may have something to do with primary / secondary monitors, or it could be the games themselves.. https://streamable.com/elx15

Looks like you are using GNOME, just like me. How about @barfin, what WM are you using? Could this be a GNOME-related issue?

**Comment by Raigor2** [comment] 2019-09-21 13:02
I can confirm I have the same issue, since an update around July 2019.  I can reproduce exactly what is presented on the video attached above.

I'm running my client on Manjaro kernel 4.19.59_rt23-1, a GTX 1070 with driver 430.40 in gnome.

**Comment by sylware** [comment] 2019-09-21 13:45
It is not gnome wm related as I use a lean fvwm and have the same issue (a pain
to pay dota2 stuff from the overlay). Anybody with wayland and xwayland?

**Comment by Raigor2** [comment] 2019-09-21 16:41
Moreover I can confirm it is an Dota related issue, I do run other games via Proton on Steam and the overlay works just fine.  Artifact/Dota 2 are the ones producing the problem on me, maybe Source Engine related? It happens on OpenGL and Vulkan

**Comment by barfin** [comment] 2019-09-22 17:21
> Moreover I can confirm it is an Dota related issue, I do run other games via Proton on Steam and the overlay works just fine. Dota 2 is the ones producing the problem, maybe Source Engine related? It happens on OpenGL and Vulkan

more accurately source 2
dota underlords has the same issue i don't have artifact to see if it has that issue too

**Comment by LiamDawe** [comment] 2019-09-26 21:13
This is not only Valve games.

I cannot properly interact with it in Rocket League now either. Most of it is unresponsive.

**Comment by Myrddin-Wyllt** [comment] 2019-09-27 02:21
@LiamDawe When you say Rocket League is broken, do you refer to the Big Picture Overlay in Steam's desktop mode (i.e., Not big picture)?

I believe this Source 2 overlay issue is separate from https://github.com/ValveSoftware/steam-for-linux/issues/6495 as it is entirely broken whether using the desktop overlay or big picture. 

Am I right in thinking your issue is related to Big Picture Overlay in Desktop Mode? Is Rocket League's overlay broken when launched from Big Picture (and how about disabling Big Picture Overlay in Desktop Mode & test the Desktop Overlay)?

**Comment by LiamDawe** [comment] 2019-09-27 09:29
No I'm talking normal desktop overlay, what the original bug report here is for.

Big Picture Mode already has a bug report open by me: https://github.com/ValveSoftware/steam-for-linux/issues/6495

**Comment by dpanter** [comment] 2019-09-28 10:29
Sounds like this could be related.

Doom 2016 has heavy stutter, even microfreezes when moving the mouse with Steam overlay enabled.
When standing still, moving around with keyboard only or playing with gamepad - it runs correctly.
Problem exists regardless of in-game graphics options, different versions of Proton, using Vulkan or OpenGL. Disabling Steam overlay fixes the problem completely. AFAIK, the overlay worked correctly in the Steam beta client versions prior to the new Library design.

OS: Siduction (Debian sid)
KERNEL: 5.2.17-towo.2-siduction-amd64
CPU: Intel Core i7-8700K @ 3.70GHz
GPU: AMD Radeon VII
GPU DRIVER: 4.5 Mesa 19.2.0-rc4
RAM: 32 GB

**Comment by 1heghost** [comment] 2019-09-28 20:46
Confirmed for Ubuntu 19.04 with Dota 2 on Vulkan. Completely borked, in beta too.
Factorio is working fine.

**Comment by TTimo** [comment] 2019-10-01 19:44
Thank you for the reports!

The problem appeared in SDL2 2.0.10, we are still tracking it down.

A workaround for now is to revert to 2.0.9 - which can go a few different ways depending on your situation.

For titles that bundle their own SDL2 (such as Dota 2 which bundles an affected 2.0.10), you can replace directly in the title installation files.

In other cases you can replace the SDL2 libraries in your steam runtime:
```
/home/timo/.steam/steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libSDL2-2.0.so.0
/home/timo/.steam/steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
```

Finally, on distributions that have already upgraded to 2.0.10 (Arch and derivatives) you may need to downgrade or uninstall SDL2, or force the pinning of the steam runtime version.

I've extracted the libraries from the relevant packages on http://repo.steampowered.com/steamrt/pool/main/libs/libsdl2/?C=N;O=D at http://repo.steampowered.com/download/steam-runtime-issue-6506/

**Comment by Raigor2** [comment] 2019-10-01 23:02
thank you! I used the workaround, Dota is Fixed!! Is Working!

**Comment by Myrddin-Wyllt** [comment] 2019-10-01 23:49
To downgrade SDL2 with pacman:
`sudo pacman -U https://archive.archlinux.org/packages/l/lib32-sdl2/lib32-sdl2-2.0.9-1-x86_64.pkg.tar.xz https://archive.archlinux.org/packages/s/sdl2/sdl2-2.0.9-1-x86_64.pkg.tar.xz`

Then [ignore updates for sdl2 and lib32-sdl2](https://wiki.archlinux.org/index.php/Pacman#Skip_package_from_being_upgraded) until this issue can be sorted out.

**Comment by TTimo** [comment] 2019-10-07 17:12
The next Steam beta update (> Sep 30) will include a fix to make the in-game overlay code compatible with latest SDL2.

**Comment by sylware** [comment] 2019-10-08 11:15
Have it.

Move hovering is still going thru the overlay (tested in dota2)

Incomplete fix?

**Comment by TTimo** [comment] 2019-10-08 13:38
> Move hovering is still going thru the overlay (tested in dota2)

Can you be more specific, I'm not observing this here.

**Comment by barfin** [comment] 2019-10-08 15:22
> Have it. Move hovering is still going thru the overlay (tested in dota2) Incomplete fix?

after this update 
https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1591384490870888376
 it's working good for me in dota 2

**Comment by sylware** [comment] 2019-10-08 15:42
Display the overlay on top of dota2 dashboard.

When the mouse cursor is hovering over some dota2 subpanels you can see them
being pre-activated. For instance the feed text edit box will pre-activate when
hovering over it. The visual cues are obvious.

**Comment by Newbie13XD** [comment] 2019-10-08 20:42
> Display the overlay on top of dota2 dashboard. When the mouse cursor is hovering over some dota2 subpanels you can see them being pre-activated. For instance the feed text edit box will pre-activate when hovering over it. The visual cues are obvious.

This occurs in Witcher 3 too, especially when doing alt + tab while running around as it often causes the quick menu thing to open, which does make sounds as different selections are hovered over when the Steam Overlay is open.

**Comment by barfin** [comment] 2019-10-20 23:34
> The next Steam beta update (> Sep 30) will include a fix to make the in-game overlay code compatible with latest SDL2.

when will you put this in stable branch?

**Comment by gatlinnewhouse** [comment] 2019-12-31 12:05
I am also having this issue in the current Steam stable branch with CSGO #5714

**Comment by TTimo** [comment] 2020-02-13 04:17
Next Steam beta (> Feb 12) will have further fixes for this problem.

**Comment by guihkx** [comment] 2020-02-14 01:35
I just did some quick testing with some games:

**Terraria**: The issue is completely gone in both native and Proton versions! The only difference (a nitpick, actually) is that in the Proton version, when the overlay is open and you do some left clicks in random positions, the game will register the cursor positions (but not the clicks). But after you close the overlay, it successfully restores the cursor position to its original state, so that's fine I guess.

**CS:GO (native)**: The issue I mentioned in #6856 is gone as well!

**Skyrim: Special Edition (Proton)**: This one I hadn't tested before, but unfortunately the game suffers from the exact same problem I was having in #6856, so this update made no difference here.

**GTA: SA (Proton)**: No improvements either. Well, now you don't see the in-game cursor moving while the Steam overlay is open, but the game still registers all clicks.

**Comment by sylware** [comment] 2020-02-20 23:40
Briefly tested with dota2 vulkan/x11(native), could not go thru the overlay.

**Comment by jaskor** [comment] 2020-03-12 08:38
Tested with warframe via proton and it's still not working even after downgrading SDL2

**Comment by cfebs** [comment] 2020-04-28 13:15
Tested in dota2 + CSGO with latest beta and issue described here: https://github.com/ValveSoftware/steam-for-linux/issues/6856 does not occur, i cannot click through to the game!

Was testing with Proton (Grim Dawn) and click-through behavior is still present. In addition, sometimes (haven't found a pattern seems like a race condition or something) in friends window input boxes (direct messages and groups) the Enter key will just produce a newline and not send the message.

**Comment by Newbytee** [comment] 2020-04-28 14:17
> Tested in dota2 + CSGO with latest beta and issue described here: #6856 does not occur, i cannot click through to the game!
> 
> Was testing with Proton (Grim Dawn) and click-through behavior is still present. In addition, sometimes (haven't found a pattern seems like a race condition or something) in friends window input boxes (direct messages and groups) the Enter key will just produce a newline and not send the message.

I believe this could be https://github.com/ValveSoftware/steam-for-linux/issues/3451

**Comment by sylware** [comment] 2020-04-29 13:05
On my system the overlay (GL+vulkan) stopped working at all for all games. I
had to open a new issue.

**Comment by kisak-valve** [comment] 2022-01-21 21:58
Closing because the issue in the opening post has been resolved. Follow up issues should be tracked separately.

**Closed by kisak-valve** 2022-01-21 21:58 UTC
Labels: overlay
