### ISSUE TITLE
[L4D2] joypad axis didn't work

### ISSUE THREAD

**Issue by s3rg3** [ValveSoftware/steam-for-linux#2386] opened 2013-05-04 13:36 UTC
When joypad is enabled you can't move with joypad and also with keybord,wasd doesn't work,when joypad is disabled wasd work fine.

**Comment by kisak-valve** [comment] 2017-04-28 15:27
Hello, is anyone still experiencing this issue?

**Comment by magoid** [comment] 2017-04-28 18:10
This problem was fixed a long time ago. To make sure, I just checked up the files consistency, fired up the game, tested it with a Xbox 360 and Steam controllers, everything is fine.

If you are interested in fixing other problems with this game (witch I play almost daily), there are problems with the sound. The first one is that the game do not remember the output you choose (# of channels or headphones), and 5.1 channels is messed up, the rear channels do not work as they should, works as it is only 2.0 channels. And this was tested with different soundcards and different versions of Ubuntu.

**Comment by kisak-valve** [comment] 2017-04-28 18:29
Thanks for the feedback @magoid.

The issue with L4D2 having trouble saving audio settings is being tracked at https://github.com/ValveSoftware/Source-1-Games/issues/1881, I personally can't reproduce that issue, it would be great if someone could figure out the difference between a working and affected system.

On my primary desktop which has a rather funky audio pipe, I can visually see that surround sound is working fine, but it is distinctly biased to the front left and front right speakers. This may be a side effect of your first issue. Feel free to open an issue report on the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games), but I can make no promises if or when a Valve dev will get around to looking into it.

Closing.

**Closed by kisak-valve** 2017-04-28 18:29 UTC
Labels: Need Retest, reviewed
