### ISSUE TITLE
[L4D2] Only able to turn 90 degrees

### ISSUE THREAD

**Issue by eggman314** [ValveSoftware/steam-for-linux#2398] opened 2013-05-05 12:14 UTC
Usually when I start a game I am only able to turn 90 degrees. Pressing Esc twice to go to main menu and back has fixed it every time so far. I use mouse and keyboard.

Processor Information:
    Vendor:  GenuineIntel
    Speed: 3501 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.7.0-7-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11302902
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 560 Ti/PCIe/SSE2

```
Driver Version:  4.3.0 NVIDIA 313.30
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x1200
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1200
Desktop Resolution: 1920 x 1200
Primary Display Size: 20,39" x 12,76"  (24,02" diag)
                                        51,8cm x 32,4cm  (61,0cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  16005 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  938898 Mb
    Largest Free Hard Disk Block:  849462 Mb

Installed software:

Recent Failure Reports:
    Sun May  5 06:55:28 2013 GMT: file ''/tmp/dumps/assert_20130505085527_1.dmp'', upload no: ''HTTP response code said error''
    Sun May  5 07:38:23 2013 GMT: file ''/tmp/dumps/assert_20130505093616_2.dmp'', upload no: ''Couldn't connect to server''

**Comment by kisak-valve** [comment] 2017-04-28 15:35
Closing as a duplicate of #2385.

**Closed by kisak-valve** 2017-04-28 15:35 UTC
Labels: reviewed
