### ISSUE TITLE
Performance problems with Remote Play, Vulkan

### ISSUE THREAD

**Issue by fallenguru** [ValveSoftware/steam-for-linux#6738] opened 2019-12-05 00:02 UTC
#### Your system information

* Steam client version (build number or date): 2019-11-28
* Distribution (e.g. Ubuntu): Ubuntu 18.04.3
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

linux 5.3.0-24-generic [hwe-edge], mesa 19.3.0+aco+git1575452833-3409c06e26d-1bionic1, xorg hwe.
AMD 3900X + Radeon VII, 32 GB RAM.

#### Please describe your issue in as much detail as possible:
I use Remote Play a lot, to stream from my desktop to a HTPC connected to a projector. Recently, this hasn't been working so well.
E.g., Ori and the Blind Forest: Definitive Edition (387290) [won't stream with Proton 4.11 at all, of course, variation of #6516], has FPS drops / microstutter on Proton default, 4.2 and 4.19-GE-1. *Locally* it's buttery smooth with any of these Proton builds [including 4.11]. Interestingly, Ori takes kindly to running with PROTON_USE_WINED3D11=1 instead of DXVK, that gives me flawless performance even streamed.
Thing is, the symptoms remind me of #6623 -- the same pattern of 60 FPS, sheer drop, back up to 30 FPS, stable there for a moment, back up to ~60 FPS, rinse, repeat; and Life is Strange: Before the Storm (554620) is native Vulkan ...
I've tried a few other games and so far the hypothesis "currently trying to stream a Vulkan game that is at all FPS-sensitive, be it native or via Proton/DXVK results in abominable performance" as described, holds.

(And no, it's not shader compilation stutter, it's too short and doesn't get better.)

**Comment by kisak-valve** [comment] 2019-12-05 00:08
Possible duplicate of #5591.

**Comment by fallenguru** [comment] 2019-12-05 13:57
> Possible duplicate of #5591.

That bug's from July 2018, meanwhile I've had flawless streaming performance in July and the beginning of August of this year (2019), and I did a lot of testing/benchmarking/playing back then, to see if a Linux gaming PC is viable at all. If the symptoms, or at least the underlying cause, are the same, it's a regression.

I'd rather you didn't close the bug outright, but if merging them is an option, I'm all for it.

**Comment by pr-delta** [comment] 2020-01-18 04:16
Does this still present a problem @fallenguru ?

**Comment by fallenguru** [comment] 2020-01-27 00:26
@pr-delta: Thank you for reminding me to re-test, as it looks like there've been quite a few changes. Everything default (no Proton version override, no launch options, most recent Steam beta):

* At a glance, Ori works ok now. TBH, I've seen better looking display curves on the graph with much heavier games, but it's perfectly playable.
* The Witcher 3 has been getting hours of "testing" here lately, and it's baby's bottom smooth 60 FPS at max settings.

**Comment by kisak-valve** [comment] 2020-01-27 00:30
Hello @fallenguru, glad to hear it's behaving better. Closing per the last comment.

**Closed by kisak-valve** 2020-01-27 00:30 UTC
Labels: Streaming

**Comment by fallenguru** [comment] 2020-01-27 00:43
> Closing per the last comment.

You *are* quick ... Sorry for not closing it myself, I just wanted to double-check the settings before doing so (they check out).

**Comment by pr-delta** [comment] 2020-02-24 21:36
Im still having this problem, especially with The Witcher 3. CPU is only at 45% max at any time but i get a 20fps penalty.
