### ISSUE TITLE
Steam client UI won't start anymore

### ISSUE THREAD

**Issue by chtenb** [ValveSoftware/steam-for-linux#9954] opened 2023-08-05 11:42 UTC
#### Your system information

* Steam client version: installed latest .deb today
* Distribution Ubuntu 22.04 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* GPU: Nvidia
* logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12266951/steam-logs.tar.gz)

#### Please describe your issue in as much detail as possible:
1. Run steam in the terminal.
2. System tray appears, but is not functional. Nothing else happens.
3. Yesterday everything still worked. I'm suspecting it has something to do with a steam update? I re-installed the latest .deb today, but still no luck.

Here is the process stdout
```
Unable to determine whether the expected Nvidia drivers are available.
The Steam client may have limited functionality.
steam.sh[31024]: Running Steam on ubuntu 22.04 64-bit
steam.sh[31024]: STEAM_RUNTIME is enabled automatically
setup.sh[31142]: Steam runtime environment up-to-date!
steam.sh[31024]: Steam client's requirements are satisfied
[2023-08-05 13:34:52] Startup - updater built Jul 28 2023 18:44:09
[2023-08-05 13:34:52] Startup - Steam Client launched with: '/home/chiel/.local/share/Steam/ubuntu12_32/steam' '-no-browser'
08/05 13:34:52 Init: Installing breakpad exception handler for appid(steam)/version(1690583737)/tid(31218)
[2023-08-05 13:34:52] Loading cached metrics from disk (/home/chiel/.local/share/Steam/package/steam_client_metrics.bin)
[2023-08-05 13:34:52] Using the following download hosts for Public, Realm steamglobal
[2023-08-05 13:34:52] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-08-05 13:34:52] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-08-05 13:34:52] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-08-05 13:34:52] Verifying installation...
[2023-08-05 13:34:52] Verification complete
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf6417370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf6415cc0
/usr/share/themes/Yaru-dark/gtk-2.0/main.rc:775: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Yaru-dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
GetWin32Stats: display was not open yet, good
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[31280]: Runtime for steamwebhelper: defaulting to /home/chiel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[31280]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
CAppInfoCacheReadFromDiskThread took 85 milliseconds to initialize
BRefreshApplicationsInLibrary 1: 1ms
[2023-08-05 13:36:53] Background update loop checking for update. . .
[2023-08-05 13:36:53] Checking for available updates...
[2023-08-05 13:36:53] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12?t=628120537
[2023-08-05 13:36:53] Manifest download: send request
[2023-08-05 13:36:53] Manifest download: waiting for download to finish
[2023-08-05 13:36:54] Manifest download: finished
[2023-08-05 13:36:54] Download skipped: /steam_client_ubuntu12?t=628120537 version 1690583737, installed version 1690583737, existing pending version 0
[2023-08-05 13:36:54] Nothing to do
```

**Comment by chtenb** [comment] 2023-08-06 09:47
I did a full fresh reinstall of my ubuntu system, and now steam seems to start again. However, other people seem to have this problem as well, so it may well be that something unspecific to my system broke steam, either a steam update or some package upgrade.

**Comment by PerplexativeKhat** [comment] 2023-08-08 17:41
I was having a very similar crash after an update to my Arch system, but it was solved when I went through one of the solutions on issue #9508, which appears to be a crash caused by newer versions of `libgudev` installed on your system.

**Comment by smcv** [comment] 2023-08-15 12:46
This matches the symptoms of an issue I saw with the NVIDIA driver on an Ubuntu 22.04 test system.

During an upgrade, the package manager installed a different kernel (in my case it was the `lowlatency` kernel variant) and made it the default, but did not install the corresponding kernel headers that were necessary to compile the proprietary NVIDIA kernel module, resulting in that kernel having no hardware-accelerated 3D graphics.

The GNOME desktop environment worked surprisingly well with the `llvmpipe` software renderer, but the Steam user interface variously either did not appear, or crashed, or was drawn as a transparent/invisible window. If I understand correctly, this is a known issue in the `steamwebhelper` (it does not appear correctly when using `llvmpipe`).

Very old or un-demanding games might have run acceptably with `llvmpipe` and a fast enough CPU, but if I had been able to start a demanding modern game then it would have also been very slow, as a result of not using my GPU.

If other people get a similar symptom on an Ubuntu system that is using the NVIDIA proprietary graphics driver, I would recommend checking that the graphics driver is installed and working correctly. In particular, `lsmod | grep nvidia` should list modules like `nvidia` and `nvidia_modeset`, and if it does not list an `nvidia` module then the proprietary NVIDIA driver is not working as intended.

**Comment by kisak-valve** [comment] 2023-09-16 00:21
Closing as a video driver issue per the last couple comments.

The issue with rendering the Steam client with llvmpipe is being tracked at #9752.

**Closed by kisak-valve** 2023-09-16 00:21 UTC
Labels: Steam client, Need Retest, Distro Family: Ubuntu

**Comment by gazhay** [comment] 2023-12-21 17:04
Can confirm this still happens with properly installed nvidia drivers

` bash -x steam
+ export STEAMSCRIPT=steam
+ STEAMSCRIPT=steam
+ export STEAMSCRIPT_VERSION=1.0.0.74-1ubuntu2/Ubuntu
+ STEAMSCRIPT_VERSION=1.0.0.74-1ubuntu2/Ubuntu
+ STEAMCONFIG=/home/gaz/.steam
+ : /home/gaz/.local/share
+ '[' -L /home/gaz/.steam/steam ']'
+ '[' -e /home/gaz/.steam/steam ']'
+ '[' -L /home/gaz/.steam/root ']'
+ '[' -e /home/gaz/.steam/root ']'
+ '[' -L /home/gaz/.steam/steam ']'
++ readlink -e -q /home/gaz/.steam/steam
+ STEAMDIR=/home/gaz/.steam/debian-installation
+ ubuntu32=/home/gaz/.steam/debian-installation/ubuntu12_32
+ steam=/home/gaz/.steam/debian-installation/ubuntu12_32/steam
+ runtime=/home/gaz/.steam/debian-installation/ubuntu12_32/steam-runtime
+ real=/usr/lib/games/steam/steam
+ test -n en_GB.UTF-8
+ nosse2='WARNING:
The hardware on this system lacks support for the sse2 instruction set.
The browser within the steam client will not work. For more information,
see: https://support.steampowered.com/kb_article.php?ref=4090-RTKZ-4347'
+ grep -q sse2 /proc/cpuinfo
+ test '!' -d /home/gaz/.steam
+ true
+ test '!' -d /home/gaz/.steam/debian-installation
+ true
+ '[' -d /home/gaz/.steam/steam ']'
+ '[' -d /home/gaz/.steam/root ']'
+ test '!' -x /home/gaz/.steam/debian-installation/steam.sh
+ true
+ test '!' -d /home/gaz/.steam/debian-installation/ubuntu12_32
+ true
+ test '!' -x /home/gaz/.steam/debian-installation/ubuntu12_32/steam
+ true
+ test '!' -e /home/gaz/.steam/debian-installation/ubuntu12_32/steam-runtime.tar.xz
+ true
+ test '!' -d /home/gaz/.steam/debian-installation/ubuntu12_32/steam-runtime
+ rm -f 'steam-runtime.tar.xz*'
+ rm -f /home/gaz/.steam/debian-installation/error.log
+ test -x /home/gaz/.steam/debian-installation/steam.sh
+ exec /home/gaz/.steam/debian-installation/steam.sh -nominidumps -nobreakpad
steam.sh[3070154]: Running Steam on ubuntu 22.04 64-bit
steam.sh[3070154]: STEAM_RUNTIME is enabled automatically
setup.sh[3070281]: Updating Steam runtime environment...
--<<hangs here forever>>-- ^C
 lsmod | grep nvidia
nvidia_uvm           1363968  0
nvidia_drm             69632  7
nvidia_modeset       1241088  8 nvidia_drm
nvidia              56365056  394 nvidia_uvm,nvidia_modeset
drm_kms_helper        311296  1 nvidia_drm
drm                   622592  11 drm_kms_helper,nvidia,nvidia_drm


`
