### ISSUE TITLE
0 bytes updates with proton steam play titles - again!

### ISSUE THREAD

**Issue by HughTebby** [ValveSoftware/steam-for-linux#6064] opened 2019-01-30 20:55 UTC
#### Your system information

* Steam client version: - jan 29 2019
* Distribution: Ubuntu
* Opted into Steam client beta?:  Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The issue detailed here seems to be back: https://github.com/ValveSoftware/steam-for-linux/issues/5644
I do not know whether the issue was solved or not on my system by the previous jan 16 update, but it certainly is there right now.

Also a couple of game also have a Disk Write Error (for the 0 byte download), making it impossible to launch them. I can however delete et re-download the games without an issue.

**Comment by kisak-valve** [comment] 2019-01-30 20:58
Hello @HughTebby, is this a one-time update per game?

**Comment by HughTebby** [comment] 2019-01-30 21:23
Hi!

I updated them yesterday I think, they came back today. Just restarted Steam and only the two games with the Disk Write Error are to be updated. And just to be clear, there is no issue with disk space, and I even tried to change the download drive, still same error. All my drives are ext4, if that can help...

**Comment by byte1024** [comment] 2019-01-31 20:34
It wasn't actually completely resolved - if at all - as far as I'm aware. After the beta update that tried to fix it, it may have improved, but the next beta update showed 0 updates again.

Disabling shader pre-cache may have fixed it for me as I haven't seen it since then but that shouldn't be necessary.

**Comment by ewe2** [comment] 2019-01-31 20:42
It's still happening on the Jan 4 stable client every time it gets started.

**Comment by byte1024** [comment] 2019-02-01 04:57
> It's still happening on the Jan 4 stable client every time it gets started.

Did they have a fix for the non-beta version? I haven't noticed one previously. In any case, the latest beta version fix (this week or last) didn't really work either.

**Comment by lucifertdark** [comment] 2019-02-01 07:31
I haven't had a single 0byte update since the Jan 4 update, I'm using the beta version.

**Comment by DerSandmann-Badcode** [comment] 2019-02-06 02:11
I'm getting 0 byte updates still. 
![image](https://user-images.githubusercontent.com/8218786/52316691-8844ac00-2a21-11e9-9017-19f13125ad3f.png)

**Comment by HughTebby** [comment] 2019-02-06 20:43
I still have them, but it's not systematic (except when I don't update the games). They just seem to come back randomly... And the DISK WRITE ERROR on some 0 byte updates stops me from launching those games.

![image](https://user-images.githubusercontent.com/461824/52372284-1176d580-2a58-11e9-84f7-2b1abe78ee8b.png)

**Comment by XakepSDK** [comment] 2019-02-11 02:40
I'm getting these 0 bytes updates when i'm installing / removing any proton game.

**Comment by MeGA-ct** [comment] 2019-02-18 23:38
![captura de pantalla de 2019-02-19 00-37-34](https://user-images.githubusercontent.com/3133372/52981227-94941600-33de-11e9-9c07-ef38228ae39c.png)
I have noticed the same.
I'm using last beta build.

**Comment by kisak-valve** [comment] 2019-03-06 23:55
Hello, per "Fixed more instances of 0-byte downloads and missing Proton or data files for Steam Play titles" in the [2019-03-06](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1798531141142819058) Steam beta client update, please opt into Steam's beta client and retest this issue.

**Comment by MeGA-ct** [comment] 2019-03-08 21:53
I can say that it's not sowing the 0 bite downloads now, at least in my case.

**Comment by XakepSDK** [comment] 2019-03-08 23:55
Got one. Less and less with every fix!
https://puu.sh/CXbsJ/6b8af30afc.png

**Comment by HughTebby** [comment] 2019-03-18 16:11
Haven't had any for several days, seems to be solved!

**Comment by XakepSDK** [comment] 2019-03-21 04:37
More 0 bytes updates!
https://puu.sh/D355e/34958b1029.png

p.s. saints row iv native, not proton.
Built: Mar 20 2019, at 18:38:53

**Comment by kisak-valve** [comment] 2021-02-26 21:36
Hello, is anybody still experiencing this issue on an up to date system?

**Comment by omicron-b** [comment] 2021-02-27 04:19
@kisak-valve nope, the issue is solved for me
Ubuntu 20.04, 20.10 and Debian Testing

**Comment by kisak-valve** [comment] 2021-04-02 16:30
Thanks for retesting @omicron-b, closing.

**Closed by kisak-valve** 2021-04-02 16:30 UTC
Labels: Need Retest, Proton
