### ISSUE TITLE
Brief pauses on controller button press/mouse move with in-home streaming 

### ISSUE THREAD

**Issue by thigger** [ValveSoftware/steam-for-linux#4764] opened 2016-12-18 20:36 UTC
#### Your system information

* Steam client version: 1481318740
* Distribution (e.g. Ubuntu):  Ubuntu 16.04.1 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Steam streaming (from a fairly powerful Win10 host system)
Using VDPAU or VAAPI
Video stream runs fine, but any controller input causes pauses in streaming. Button presses or keyboard presses cause brief pauses, analog input or mouse movement causes long pauses (several seconds if the mouse is wiggled a bit). During the pause, the performance information also pauses, and when it unpauses (the host game has obviously continued to run in the background) the graph moves on and there is a straight line to the next data point. CPU usage does not increase during the pauses (remains at 60-70% when all other software is killed, mostly due to the streaming client).

Tested with USB Playstation 2 controllers, Wireless Xbox controller with USB receiver, USB keyboard, USB mouse.

System is fairly low powered - T2400 CPU, GTX220, 3Gb RAM (but plays 1080p h264 video fine via vdpau). Link to host machine is wired gigabit ethernet.

Session is extremely lightweight - Xorg server, Mythfrontend (though I've tried without it running), xfwm4 window manager

Some discussion at: https://steamcommunity.com/app/221410/discussions/0/154644045353074952/

NB the same system works absolutely fine for playing local games.

#### Steps for reproducing this issue:

1. Use my system
2. Launch any streaming game from the host PC
3. (for worst results) - wiggle the mouse for a second, to produce a multi-second pause. Otherwise press any controller button for a briefer pause (host system responds to control as expected though).

**Comment by thigger** [comment] 2016-12-18 20:49
[streaming_client.log.txt](https://github.com/ValveSoftware/steam-for-linux/files/659654/streaming_client.log.txt)
[error.log.txt](https://github.com/ValveSoftware/steam-for-linux/files/659653/error.log.txt)

Error and streaming log
nb these are from the latest attempt; in debugging attempts had been making Steam use my system libva libraries, and had temporarily disabled VAAPI to force it to use VDPAU - I'll switch everything back to standard for future attempts - but it behaves the same either way.

**Comment by thigger** [comment] 2016-12-18 21:22
Found in a host file:

[2016-12-18 20:11:45] "SessionStats"
{
	"GameNameID"		"LUFTRAUSERS"
	"TimeSubmitted"		"1482091905"
	"ResolutionX"		"1920"
	"ResolutionY"		"1080"
	"CaptureDescriptionID"		"Game Delayed OpenGL NV12 + NVENC H264"
	"DecoderDescriptionID"		"VDPAU hardware decoding"
	"BandwidthLimit"		"10000"
	"FramerateLimit"		"0"
	"SlowGamePercent"		"0"
	"SlowCapturePercent"		"0"
	"SlowConvertPercent"		"0"
	"SlowEncodePercent"		"0"
	"SlowNetworkPercent"		"0"
	"SlowDecodePercent"		"0"
	"SlowDisplayPercent"		"0"
	"AvgClientBitrate"		"23.274158477783203"
	"StdDevClientBitrate"		"103.75316619873047"
	"AvgServerBitrate"		"593.4583740234375"
	"StdDevServerBitrate"		"4037.760498046875"
	"AvgLinkBandwidth"		"104725.1328125"
	"AvgPingMS"		"0.049730077385902405"
	"StdDevPingMS"		"0.19999277591705322"
	"AvgCaptureMS"		"0.70406848192214966"
	"StdDevCaptureMS"		"0.28197303414344788"
	"AvgConvertMS"		"0.0057493583299219608"
	"StdDevConvertMS"		"0.19825835525989532"
	"AvgEncodeMS"		"5.2645769119262695"
	"StdDevEncodeMS"		"0.33966076374053955"
	"AvgNetworkMS"		"0.18032373487949371"
	"StdDevNetworkMS"		"0.66254687309265137"
	"AvgDecodeMS"		"0.82001650333404541"
	"StdDevDecodeMS"		"4.0133614540100098"
	"AvgDisplayMS"		"0.54997366666793823"
	"StdDevDisplayMS"		"0.64449268579483032"
	"AvgFrameMS"		"19.537008285522461"
	"StdDevFrameMS"		"8.2164726257324219"
	"AvgFPS"		"32.831375122070313"
	"StdDevFPS"		"11.148100852966309"
	"BigPicture"		"0"
	"KeyboardMouseInput"		"1"
	"GameControllerInput"		"0"
	"SteamControllerInput"		"0"
}

**Comment by thigger** [comment] 2016-12-20 22:56
I think this may be a duplicate of #4444

**Comment by kisak-valve** [comment] 2016-12-20 23:24
Hello @thigger, does the workaround in #4444 resolve the issue?

**Comment by thigger** [comment] 2016-12-21 09:31
I think so (though I've not done exactly the same) - I was having a play last night after noticing the dbus errors in the log, and changed quite a lot of things including: installing the "dbus-user-session" package, removing the dbus and gpg-error libraries from the steam runtime, removing the libSDL2 library from the steam runtime (though I think Steam put it straight back), a few random package upgrades (just Ubuntu updates), removing pulseaudio, and a couple of reboots.
Something in there (and I assume it's most likely to be the dbus stuff, given #4444) has fixed the problem entirely so it seems likely that the workaround would have done it (though it needs tweaking for those of us on 32-bit).
Now streaming 1080p at 20%CPU, even when "Big Picture" is selected. Just need to fix the audio (which I think may be the host) and stop MythTV jumping to the foreground, and I'm golden!

**Comment by kisak-valve** [comment] 2016-12-21 13:42
Thanks for retesting. Closing as a duplicate of #4444.

**Closed by kisak-valve** 2016-12-21 13:42 UTC
Labels: Streaming
