### ISSUE TITLE
Steam segfault at 0 error 4 in libc-2.31.so

### ISSUE THREAD

**Issue by CreationTribe** [ValveSoftware/steam-for-linux#7502] opened 2020-12-02 19:29 UTC
#### Your system information

* Steam client version (date): 2020.12.02 
* Distribution (e.g. Ubuntu): Kubuntu 20.04 x64
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Expected that Steam would start as per usual. But it did not.

After I click the icon, the "updating steam" (or whatever it says) window appears, loads, and then it vanishes.

I updated all of my packages including Steam to see if that would fix it, but it did not.

here's what dmesg spat out. I'll include multiple attempts of trying to start Steam:

```
[Dec 2 10:56] steam[80366]: segfault at 0 ip 00000000f7985065 sp 00000000ffd9a37c error 4 in libc-2.31.so[f78fd000+15b000]
[  +0.000008] Code: 40 38 ca 0f 84 4d 01 00 00 80 f9 00 0f 84 71 01 00 00 40 4f 75 14 8a 08 38 ca 0f 84 36 01 00 00 80 f9 00 0f 84 5a 01 00 00 40 <8b> 08 bd ff fe fe fe bf ff fe fe fe 01 cd 31 cd 01 cf 8d 40 04 0f

[Dec 2 10:58] steam[80883]: segfault at 0 ip 00000000f796d065 sp 00000000ffad924c error 4 in libc-2.31.so[f78e5000+15b000]
[  +0.000007] Code: 40 38 ca 0f 84 4d 01 00 00 80 f9 00 0f 84 71 01 00 00 40 4f 75 14 8a 08 38 ca 0f 84 36 01 00 00 80 f9 00 0f 84 5a 01 00 00 40 <8b> 08 bd ff fe fe fe bf ff fe fe fe 01 cd 31 cd 01 cf 8d 40 04 0f

[Dec 2 11:46] steam[93501]: segfault at 0 ip 00000000f7925065 sp 00000000ffcaa45c error 4 in libc-2.31.so[f789d000+15b000]
[  +0.000007] Code: 40 38 ca 0f 84 4d 01 00 00 80 f9 00 0f 84 71 01 00 00 40 4f 75 14 8a 08 38 ca 0f 84 36 01 00 00 80 f9 00 0f 84 5a 01 00 00 40 <8b> 08 bd ff fe fe fe bf ff fe fe fe 01 cd 31 cd 01 cf 8d 40 04 0f

[Dec 2 11:50] steam[94281]: segfault at 0 ip 00000000f79a5065 sp 00000000ffe0e24c error 4 in libc-2.31.so[f791d000+15b000]
[  +0.000006] Code: 40 38 ca 0f 84 4d 01 00 00 80 f9 00 0f 84 71 01 00 00 40 4f 75 14 8a 08 38 ca 0f 84 36 01 00 00 80 f9 00 0f 84 5a 01 00 00 40 <8b> 08 bd ff fe fe fe bf ff fe fe fe 01 cd 31 cd 01 cf 8d 40 04 0f
```

And here's what steam gives me cli (I've cut out everything that's not significant):

```
Steam client's requirements are satisfied
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
SteamUpdateUI: An X Error occurred
X Error of failed request:  GLXBadContext
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  45
xerror_handler: X failed, continuing
Major opcode of failed request:  151 (GLX)
Minor opcode of failed request:  6 (X_GLXIsDirect)
Serial number of failed request:  46
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  151
Serial number of failed request:  51
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151
Value in failed request:  0x0
Serial number of failed request:  50
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  151
Serial number of failed request:  52
xerror_handler: X failed, continuing
assert_20201202120955_1.dmp[96103]: Uploading dump (out-of-process)
/tmp/dumps/assert_20201202120955_1.dmp
```
Then it automatically uploaded the dump.

#### Steps for reproducing this issue:
I honestly can't say ...

**Comment by kisak-valve** [comment] 2020-12-02 19:34
Hello @CreationTribe, swrast is mesa's slower cpu opengl renderer and the fact Steam is trying to use it and failing hints that you're using the nVidia proprietary driver, but don't have nVidia's 32 bit userspace installed.

Can you check what driver series you have installed, then check if the 32 bit userspace is installed with something like `apt policy libnvidia-gl-455:i386`? (Change 455 to match the version that is installed.) If it's not installed, you can run something like `sudo apt install libnvidia-gl-455:i386` to add it to your system.

**Comment by CreationTribe** [comment] 2020-12-02 19:52
Oh no  - that didn't work :( 
It uninstalled my cuda drivers, which I use for development.

Is there another work around?

**Comment by kisak-valve** [comment] 2020-12-02 20:38
The packages from nVidia's cuda PPA does not provide 32 bit userspace support. This is a known issue which is being tracked at #5778, but needs to be fixed by the PPA maintainer(s).

My understanding is that you should be able to use a slightly newer nVidia driver than cuda was bundled with from https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa or the distro repos now that Ubuntu is pulling in new nVidia drivers more often and install all the cuda packages you need except the top meta package which explicitly wants the incomplete driver from the cuda PPA.

Closing as a duplicate of #5778.

**Closed by kisak-valve** 2020-12-02 20:38 UTC
Labels: Distro Family: Ubuntu, NVIDIA drivers
