### ISSUE TITLE
Any game start change time 2 hours back

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [ValveSoftware/steam-for-linux#6395] opened 2019-07-16 20:18 UTC
#### Your system information

* Steam client version (build number or date): jenkins-steam-runtime-beta-release_0.20190320.2
* Distribution (e.g. Ubuntu): Ubuntu 19.04 (64 бит)
* Opted into Steam client beta?: [Yes/No]No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I expect that steam not touch time. 
If i start any game from my library time change 2 hours back.
In moment when i exit from game time return to normal.

Issue illustrated in video

[2019-07-16 22-15-35.flv.gz](https://github.com/ValveSoftware/steam-for-linux/files/3398965/2019-07-16.22-15-35.flv.gz)

#### Steps for reproducing this issue:

1. Install Steam
2. Start game

**Comment by kisak-valve** [comment] 2019-07-16 20:31
Hello @jpVm5jYYRE1VIKL, I don't believe that Steam is changing the system's time, rather, I think that you're encountering a KDE compositor issue that's showing an old rendering of the system tray. Can you check if running `kwin --replace` while in the quirk state has an effect? (from https://github.com/ValveSoftware/steam-for-linux/issues/5334#issuecomment-357393182)

Most likely a duplicate of #5334.

**Comment by jpVm5jYYRE1VIKL** [comment] 2019-07-17 06:44
No no it is not influense on system time only representatiom. I checked system time in another windows and it is not changed. It influence only on Window manager time widget . Do i need to report it to kde or it is Steam issue ?

**Comment by kisak-valve** [comment] 2019-07-17 12:15
Thanks for confirming, feel free to add your experience to #5334. Closing in favor of the existing issue report.

**Closed by kisak-valve** 2019-07-17 12:15 UTC
Labels: Distro Family: Ubuntu, Window manager
