### ISSUE TITLE
Steam video player still cannot stretch content in fullscreen mode

### ISSUE THREAD

**Issue by ViBE-HU** [ValveSoftware/steam-for-linux#4580] opened 2016-08-08 10:47 UTC
#### Your system information
- Steam client version: 1469850758
- Distribution (e.g. Ubuntu): Ubuntu 16.04, 64 bit
- Opted into Steam client beta?: [Yes] 
- Have you checked for system updates?: [Yes]
#### Please describe your issue in as much detail as possible:

As far as I remember this issue was fixed but now it's back (or I'm wrong and it has been never fixed)

![steamfullscreen](https://cloud.githubusercontent.com/assets/640109/17477515/fc513356-5d65-11e6-910c-b531bb00f50d.jpg)
#### Steps for reproducing this issue:
1. Go to the Store and select a game
2. Start a trailer
3. Switch to fullscreen

**Comment by predr** [comment] 2016-08-10 13:07
Restarted Steam, tried to open video and it didn't stretch. Loads correctly on second try. Running beta 1469850758 on Ubuntu 16.04.

![video-fullscreen](https://cloud.githubusercontent.com/assets/17696117/17554076/7665fd3a-5f09-11e6-87d8-e3b1a1873326.png)

**Comment by Tele42** [comment] 2016-08-16 12:59
Duplicate of #3699.

**Comment by ViBE-HU** [comment] 2016-08-17 12:57
@Tele42 Cool. I remebered that it has been fixed. Finding that thread was also hard by title. A permanent fix would be good...

**Comment by Plagman** [comment] 2016-11-26 03:27
As @Tele42 said, tracked in #3669

**Closed by Plagman** 2016-11-26 03:27 UTC
Labels: reviewed
