### ISSUE TITLE
No stdout logging

### ISSUE THREAD

**Issue by GoTeamAnt** [ValveSoftware/steam-for-linux#7114] opened 2020-05-16 10:13 UTC
#### Your system information

Version:
* steam_1.0.0.62
* Archlinux

#### Please describe your issue in as much detail as possible:

Steam stopped logging stdout to /tmp/dumps/$USER_stdout.log

**Comment by kisak-valve** [comment] 2020-05-16 11:55
Hello @GoTeamAnt, this is an intentional change in the 1.0.0.62 steam packaging related to #6901.

My understanding was that there wasn't interest in unconditionally logging stdout anymore. You can create an equivalent log by completely closing Steam, then running `steam 2>&1 | tee /path/to/logfile` from a terminal (or creating a shortcut).

**Comment by kisak-valve** [comment] 2022-11-04 15:46
Closing because this is the intended behavior.

**Closed by kisak-valve** 2022-11-04 15:46 UTC
Labels: Valve-provided steam package
