### ISSUE TITLE
Please create 64 bit native Steam Linux client!

### ISSUE THREAD

**Issue by roadapathy** [ValveSoftware/steam-for-linux#3833] opened 2015-05-04 16:27 UTC
Why on earth are we still using a 32bit Steam client for Linux? I can't even imagine it. This is BREAKING my system with all of these old 32bit libs. Please fix this.

**Comment by LollenJumplan** [comment] 2015-05-04 16:31
+1 my poor debian is also flooded by 32 bit deps. :/

**Comment by gdrewb-valve** [comment] 2015-05-04 19:04
Duplicate of #179.

**Closed by gdrewb-valve** 2015-05-04 19:04 UTC
Labels: duplicate, reviewed
