### ISSUE TITLE
Steam for Linux .deb download - where?

### ISSUE THREAD

**Issue by WillemMali** [ValveSoftware/steam-for-linux#4728] opened 2016-11-28 09:49 UTC
#### Your system information

* Steam client version: (no client, this is the problem)
* Distribution (e.g. Ubuntu): Debian Stretch (intending to use the newest possible Ubuntu builds)
* Opted into Steam client beta?: N/A
* Have you checked for system updates?: N/A

#### Please describe your issue in as much detail as possible:
I want to install Steam on Debian Testing (Stretch, best matching Ubuntu Xenial), but I can't find a [steam.deb](https://github.com/ValveSoftware/steam-for-linux) or [steam_latest.deb](http://jorisvr.nl/article/steam-firejail-debian). Both result in dead or inaccessible links. Is there any place where I can find the latest Steam builds for Ubuntu, or if they exist, (unofficial) Debian releases?

The links I found are this one (via the "Install Steam" button on the Steam homepage, linked to by JorisVR):
````
http://repo.steampowered.com/steam/archive/precise/steam_latest.deb
````
And this one (from `README.md`), but it redirects to the link above:
````
http://media.steampowered.com/client/installer/steam.deb
````

#### Steps for reproducing this issue:

1. Try to find a download for Steam
    link on this page: https://github.com/ValveSoftware/steam-for-linux
    or on this page: http://store.steampowered.com/about/
2. Find instructions and the download link from it
3. Link returns 403 status code with this message:

```
Forbidden

You don't have permission to access /steam/archive/precise/steam_latest.deb on this server.

Apache/2.2.22 (Ubuntu) Server at repo.steamstatic.com Port 80
```

**Comment by Tele42** [comment] 2016-11-28 13:25
Duplicate of #4719.

**Comment by gdrewb-valve** [comment] 2016-11-28 18:59
Closing duplicate.

**Closed by gdrewb-valve** 2016-11-28 18:59 UTC
