### ISSUE TITLE
Steam input does not passthrough rumble to Xbox controllers.

### ISSUE THREAD

**Issue by Bitwolfies** [ValveSoftware/steam-for-linux#8590] opened 2022-05-17 01:13 UTC
#### Your system information

* Steam client version (build number or date): May 14th
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:
When using Steam input on non Steam input native games with a Xbox controller, rumble is not transmitted.
#### Steps for reproducing this issue:

1. Play a game that does not support steam input natively.
2. Using an xbox controller, force it on.
3. Notice how any rumble actions no longer work.

**Comment by man-stein** [comment] 2022-06-04 07:36
Same here on Kubuntu 22.04 with xpadneo 9.3.
Xbox Series Controller connected with Bluetooth.

**Comment by deathxxx123** [comment] 2022-06-20 20:25
Just reinstall xnadneo. This is happen when you get kernel update.
And reconnect again.

**Comment by man-stein** [comment] 2022-06-21 16:06
> Just reinstall xnadneo. This is happen when you get kernel update. And reconnect again.

Rumble is working with native linux games (without Steam), fftest and with Steam games, but without Steam Input.
So it is not a driver or kernel issue.

**Comment by deathxxx123** [comment] 2022-06-21 17:15
Rumble on BT connection is working only with xpadneo driver.

**Comment by man-stein** [comment] 2022-06-21 17:23
> Rumble on BT connection is working only with xpadneo driver.

Yes, I'm aware of it. As I wrote, I'm using it.

**Comment by Bitwolfies** [comment] 2022-07-15 19:01
Should be noted this issue is even starting to extend to the Deck, with digital foundry complaining that rumble failed when using an external controller, I really feel like its in your best interest to pay attention to this issue. https://youtu.be/UZKBSf3aLf4?t=810

**Comment by EwokExile** [comment] 2022-07-22 17:28
Yeah, right now the only "solution" to this is to disable steam input, but I've run into quite a few games recently that don't detect a controller at all if steam input is disabled (God of War, Horizon Zero Dawn, Tales of Arise). So it's not really a great solution. To reproduce you have to install Xone (dongle) or Xpadneo (Bluetooth) for wireless controller support, then launch one of the aforementioned games. Easy to compare with something that does work with steam input disabled also, like Stray most recently

**Comment by Bitwolfies** [comment] 2022-07-22 17:52
Stray actually worked fine for me with steam input (it’s even required to be enabled to get PlayStation icons for some unholy reason)

Can’t remember if rumble worked however, regardless it’s still an issue with steam input.

**Comment by EwokExile** [comment] 2022-07-22 17:59
My experience with Stray (using Xbox 1914 controller with latest firmware and Xpadneo) is that steam input did work, mappings were fine and all that, but no rumble. Disabling steam input everything worked as expected, including rumble.

**Comment by ruineka** [comment] 2022-09-13 13:35
I think this should be a priority at this point with so many devices relying on steam input these days. I hope it gets addressed sooner rather than later.

**Comment by Bitwolfies** [comment] 2022-09-14 04:31
I still wonder how this wasn't fixed yet (assuming this is happening for everyone, even on Windows like it did for me) as i've now confirmed it effects Steam input NATIVE games too. Spiderman's pc port has a steam input mode and a proper fallback to another api, with it defaulting on. This is fine until you realize there's no rumble, despite it being true native steam input. Turning it off restores rumble, albeit with steam deck icons as the fall back.

So, was this not caught after all that somehow, or is it only effecting SOME controllers?

**Comment by ruineka** [comment] 2022-09-14 05:31
> I still wonder how this wasn't fixed yet (assuming this is happening for everyone, even on Windows like it did for me) as i've now confirmed it effects Steam input NATIVE games too. Spiderman's pc port has a steam input mode and a proper fallback to another api, with it defaulting on. This is fine until you realize there's no rumble, despite it being true native steam input. Turning it off restores rumble, albeit with steam deck icons as the fall back.
> 
> So, was this not caught after all that somehow, or is it only effecting SOME controllers? 
> 
> Maybe we can narrow it down a bit, im using an Xbox One S controller. Not an orignal Xb1 controller, nor an elite or series X. This issue happens when both using wired, and the wireless dongle with the xone drivers.

It's all devices except for the Steam Deck that don't have working rumble using Steam Input. It's been a known issue for a while.

**Comment by Bitwolfies** [comment] 2022-09-14 06:00
> > I still wonder how this wasn't fixed yet (assuming this is happening for everyone, even on Windows like it did for me) as i've now confirmed it effects Steam input NATIVE games too. Spiderman's pc port has a steam input mode and a proper fallback to another api, with it defaulting on. This is fine until you realize there's no rumble, despite it being true native steam input. Turning it off restores rumble, albeit with steam deck icons as the fall back.
> > So, was this not caught after all that somehow, or is it only effecting SOME controllers?
> > Maybe we can narrow it down a bit, im using an Xbox One S controller. Not an orignal Xb1 controller, nor an elite or series X. This issue happens when both using wired, and the wireless dongle with the xone drivers.
> 
> It's all devices except for the Steam Deck that don't have working rumble using Steam Input. It's been a known issue for a while.

Well, I sure hope its been known for awhile since I reported the issue! Jokes aside, I meant this doesn't seem to be a 100% issue, it *only* effects xbox controllers (Neither my PS4 or PS5 controller have this issue) and surely more people would be complaining about this, and clearly its begun to spread to Steam input native, despite this, I don't see a single thread in Spider-Man complaining about broken Xbox rumble, so there has to be more to this.

**Comment by Bitwolfies** [comment] 2022-09-14 06:11
Wanna complicate things further? I own a steam deck, I connected my Xbox controller wirelessly to my deck and played spiderman with steam input on, and yknow what?

Rumble worked.

**Comment by ruineka** [comment] 2022-09-14 13:56
> Wanna complicate things further? I own a steam deck, I connected my Xbox controller wirelessly to my deck and played spiderman with steam input on, and yknow what?
> 
> Rumble worked. This isn't a one size fits all issue, Ill keep digging.

Wow really?? Thats...weird. I'll have to try with my steam deck.

**Comment by Bitwolfies** [comment] 2022-09-14 23:55
Unfortunantly my testing has turned up mostly empty, here's what I know.

My distro is Arch Linux with the KDE DE, just like the Steam Deck, my controller is the Xbox One S controller. This issue has happened to me on Windows as well.

-Connected via dongle via Xone driver: No rumble using Steam input translator or Spider-Man (Steam input native)
-Connected via usb via Xone driver:  No rumble using Steam input translator or Spider-Man (Steam input native)
-Connected via usb with Xpad driver:  No rumble using Steam input translator or Spider-Man (Steam input native) (xone was uninstalled)
-Connected via Bluetooth directly: Untested, doesn't hold a connection for me.
-Connected via Bluetooth to Steam Deck: Rumble using Steam input translator or Spider-Man (Steam input native) worked as intended.

So clearly, whatever Valve has done to the Deck has made it immune to this issue, now the Decks firmware is still shockingly old (possible regression?) sadly, and I have not verified what driver it uses, but I assume it to be Xpad.

Reminder, this clearly does not effect every user, Spider-Man was the first native game to actually have rumble fail, and I've heard zero word of others complaining about Xbox rumble in Spider-Man.

I tried both native and runtime, no dice. I tried enabling the proper configs in big picture mode, nadda. I am truly at a loss as to why this is happening.

**Comment by Bitwolfies** [comment] 2022-09-15 00:04
The only lead I have is from the [xpadneo](https://github.com/atar-axis/xpadneo) page, which lists this "As of SDL 2.0.12, SDL introduced a new HIDAPI which can read HID devices in raw mode, bypassing the drivers. Due to the way SDL works, and because xpadneo exposes hidraw devices as user-readable, SDL may see wrong button mappings because it may make wrong assumptions about the protocol mode of Xbox and compatible controllers. If you see wrong button mappings / missing buttons in SDL applications, or rumble does not work, you may need to turn off this behavior by setting an environment variable in your profile: SDL_JOYSTICK_HIDAPI=0

Observed problems:

    Wrong mappings when using newer SDL2 versions, should be fixed by latest xpadneo
    Rumble doesn't work at all, needs to be fixed by SDL2"

However sadly adding that env did not fix the issue.

**Comment by Bitwolfies** [comment] 2022-09-28 23:49
> The only lead I have is from the [xpadneo](https://github.com/atar-axis/xpadneo) page, which lists this:
> 
> "As of SDL 2.0.12, SDL introduced a new HIDAPI which can read HID devices in raw mode, bypassing the drivers. Due to the way SDL works, and because xpadneo exposes hidraw devices as user-readable, SDL may see wrong button mappings because it may make wrong assumptions about the protocol mode of Xbox and compatible controllers. If you see wrong button mappings / missing buttons in SDL applications, or rumble does not work, you may need to turn off this behavior by setting an environment variable in your profile: SDL_JOYSTICK_HIDAPI=0
> 
> Observed problems:
> 
> ```
> Wrong mappings when using newer SDL2 versions, should be fixed by latest xpadneo
> Rumble doesn't work at all, needs to be fixed by SDL2"
> ```
> 
> However sadly adding that env did not fix the issue.

So springboarding off of this, I might have found the issue cause, may not have, just gonna throw out a theory.

Steam Input uses SDL, for SDL to create rumble, it uses HIDAPI, which contacts the HIDRAW file of the Xbox one controller.

Problem, the Xbox One controller does not create an HIDRAW device, on my pc, but it DOES on my steam deck, where rumble works. 

This may be the fix, not yet sure.

**Comment by man-stein** [comment] 2022-09-29 18:09
I got the hidraw devices when connecting the Xbox Series Controller with xpadneo and bluetooth:
[  174.318753] hid-generic 0005:045E:0B13.0009: input,hidraw8: BLUETOOTH HID v5.13 Gamepad [Xbox Wireless Controller] on 3c:7c:3f:98:f7:6e
[  174.417494] xpadneo 0005:045E:0B13.0009: input,hidraw8: BLUETOOTH HID v11.30 Gamepad [Xbox Wireless Controller] on 3c:7c:3f:98:f7:6e
[  175.696181] xpadneo 0005:045E:0B13.0009: input,hidraw8: BLUETOOTH HID v11.30 Gamepad [Xbox Wireless Controller] on 3c:7c:3f:98:f7:6e

But rumble isn't working when Steam Input is active.

**Comment by pvizc** [comment] 2022-09-30 12:57
I've got the same exact issue. No rumble when using Steam Input with my Xbox Wireless Controller. Not using Steam Input is not an option in some games since those games completely ignore the controller.

I have tried all drivers (xpadneo, xone, xpad) connecting by cable, bluetooth and the dongle. Nothing works.

**Comment by pvizc** [comment] 2022-10-01 08:57
So after much testing, I noticed that in my machine there were 3 joysticks being detected (/dev/input/js0 js1 and js3) which seemed odd. Then I realized that time ago I installed the old xboxdrv driver and there was a systemd service running in the background causing these "extra" devices to appear.

In my case I stopped the systemd service and uninstalled the package and boom, many games were able again to work with Steam Input disabled, which means rumble worked again!!

**Comment by man-stein** [comment] 2022-10-01 10:52
Do you mean "with Steam input **enabled**, rumble is working again"?

**Comment by pvizc** [comment] 2022-10-02 09:01
> Do you mean "with Steam input **enabled**, rumble is working again"? It was already working if Steam Input was disabled.

Yes, I was just replying just in case someone else run into that problem. Steam Input has no rumble neither in my machine unfortunately.

**Comment by MastaG** [comment] 2022-10-19 10:03
Same here on Fedora 37 using xpad-noone and my 8Bitdo Pro2 controller (wired).
Rumble works fine in RPCS3, so it must be a Steam thing...

**Comment by Bitwolfies** [comment] 2022-10-22 05:44
New beta update to steam converts the input ui one to that seen on the deck (even got the battery low icon in the overlay as a bug) but still, go figure, rumble still DOES NOT WORK.

**Comment by andrebrait** [comment] 2022-10-24 13:33
Rumble works for me on my Xbox Series X controller over Bluetooth on the Steam Deck. Problem is, it works too much (see #8107).

On the DualShock 4 and DualSense controllers, everything works just fine (also tested via Bluetooth).

**Comment by Bitwolfies** [comment] 2022-10-27 22:14
Its fixed, as of today's beta, its fixed.

**Comment by Bitwolfies** [comment] 2022-10-28 03:39
I tested with a few games, Crash Bandicoot N Sane, Sackboy, and Mekazoo, all three had working rumble.

**Comment by man-stein** [comment] 2022-10-28 07:56
I can confirm it. It is working again with the current Steam beta (tested with ETS2).

**Comment by kakra** [comment] 2022-11-17 20:52
The xpadneo author here... There may be some issues that come into play when using the Xbox controllers over Bluetooth:

1. Rumble data may not be sent faster than 50ms per interval, see https://github.com/libsdl-org/SDL/issues/6435, without this fix, rumble either lags behind or crashes the rumble loop of the firmware, resulting in continuous rumble or no rumble at all, sometimes breaking the whole Bluetooth connection
2. There may be a race condition with haptic detection in SDL which then prevents games to actually see rumble support, see https://github.com/libsdl-org/SDL/issues/6253, xpadneo actually provokes the bug by playing a rumble effect before opening up the force feedback API, this timing gap can be closed by disabling the rumble notification but it won't fully prevent the race condition from ever happening

When using xpadneo (that means, not using the controllers via SDL hidraw mode), xpadneo prevents (1) from happening. When using SDL in hidraw mode, there's no point in using xpadneo at all because everything bypasses the driver anyways. To prevent using hidraw mode, it's essential that your system doesn't apply read/write permissions to the hidraw file in `/dev`. This fixes most if not all of the problems.

When using the controllers via USB or dongle, there won't be a hidraw device anyways because only in Bluetooth mode the controllers act as HID devices.

When SDL is updated to latest versions (via your system or Steam Linux runtime), point (1) should also be fixed because all latest games and Steam Input itself should be able to load newer SDL versions even when compiled for older versions.

**Comment by man-stein** [comment] 2022-11-25 20:05
I think, the issue can be closed because rumble is working again with Steam Input (Beta and Stable client).

**Closed** 2022-11-25 20:44 UTC
Labels: Need Retest, General controller / Steam Input

**Comment by marco-calautti** [comment] 2023-05-31 10:03
Rumble is not working for me on a DS4 controller. I did some experiments, and it seems that Steam input is perfectly able to map the controller to an XBOX 360  controller. Indeed, If i open the wine control panel of any game configured to run with proton inside steam, I can see an x360 controller. The problem is that, this x360 controller, as seen by wine has the rumble checkbox disabled by default. However, if I check the checkbox in the gamepad configuration window inside the wine control panel, rumble work. Unfortunately, it seems that the change does not save (i.e., If I close the control panel window, and reopen it, rumble is disabled again).

So, the conclusion is that Steam Input is really prefectly capable of passing through rumble information between proton/wine and linux, but the wine side has rumble for the virtual controller disabled by default.

**Comment by kakra** [comment] 2023-05-31 13:15
> but the wine side has rumble for the virtual controller disabled by default.

This is an interesting observation and actually makes sense. Yes, Steam Input creates a virtual device in wine - xpadneo actually uses the same device ID (but on bus 5 = BT instead of bus 3 = USB) and presents compatible HID reports. The bus ID seems to be ignored within wine, so it matches there, but SDL doesn't ignore it which is important so SDL does not intercept our xpadneo input reports.

**Comment by marco-calautti** [comment] 2023-05-31 14:11
> > but the wine side has rumble for the virtual controller disabled by default.
> 
> This is an interesting observation and actually makes sense. Yes, Steam Input creates a virtual device in wine - xpadneo actually uses the same device ID (but on bus 5 = BT instead of bus 3 = USB) and presents compatible HID reports. The bus ID seems to be ignored within wine, so it matches there, but SDL doesn't ignore it which is important so SDL does not intercept our xpadneo input reports.

Sorry, but this is not super clear to me. What does this imply? That Steam Input is doing something wrong here?

**Comment by kakra** [comment] 2023-06-01 22:23
> Sorry, but this is not super clear to me. What does this imply? That Steam Input is doing something wrong here?

Yes and no... It's actually SDL which does not read the HID descriptor and rather relies on controllerdb.

> Further, using Lutris, vanilla Wine is able to automatically map my DS4 controller to an Xinput device and rumble works also there.

Latest wine can handle HID descriptors properly, so it works unless Steam Input is present which uses SDL to map the controls.

> I wonder why Steam has to make things so complicated, when wine already does the mapping automatically.

Older Proton and wine versions won't work correctly so Steam Input is still needed there. But I'm guessing that Steam Input may shift over to a similar solution and use HID directly.

**Comment by SlimeProgenitor** [comment] 2023-06-06 18:53
This is still an issue on every version of steam I've tested as of today. (windows, steam deck, proton)
DS4 controller, Steam Controller, and Switch Pro Controller all have zero rumble when Steam Input is enabled in the controller menu. Steam Controller does still have haptics, but no rumble from games.
Turning off Steam Input support for DS4 and Switch Pro controller is enough to get them rumbling in games.
the DualSense and DualSense Edge controllers are the only controllers I'm able to test that still have rumble when using Steam Input, which implies that the Steam Input team has figured out how to fix this, they just haven't patched it for other controllers
