### ISSUE TITLE
Grabbing and dragging items in shop dota 2 Linux Debian buster/bullseye Mate, Ubuntu mate 20.04 lts

### ISSUE THREAD

**Issue by koreanfan** [ValveSoftware/steam-for-linux#7141] opened 2020-05-28 12:03 UTC
#### Your system information
Debian buster/bullseye Mate, Ubuntu mate 20.04 lts, rx560, 8GB ram
* Steam client version (build number or date): steam:i386 1.0.0.62-2
* Distribution (e.g. Ubuntu): Debian buster/bullseye Mate, Ubuntu mate 20.04 lts
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
After match starting i open shop and try to grab and drag item from shop to my stash. When you grab and dragging very very slow grabbing dragging works improperly (10 grab and drag/ success 8, fail 2), but when you grab and dragg very fast its work completely improperly (10 grab and drag / success 1,fail 9). What does it mean fail? Fail - when you start grabbing and dragging items from shop to stash, left mouse click may dont work or shop may closed or when you dragging item(who consist of 2 or more parts) you can got in stash only one part of dragging item. First i think my left button dont work, or dota files damaged. I change mouse, veryfy dota 2 files, delete dota+steam,reinstall, same effect. Delete linux,make clean isntall, but again same result. So i install second OS Debian buster XFCE and try test dota and all works without any issues, then i install Debian bullseye XFCE and all works without any issues. Seems steam work improperly with mate desktop environment. Maybe its steam bug or maybe its Mate DE bug or maybe ist Debian bug. Btw, when you try grab and dragging window (caja ot pluma etc) it has partly same issue, cuz you cant grab window and dragging him if you doing fast left click and mouse movement. But weird is that you fail only dragging with vertical movements, if you do it with horizontal movements all works without any issue.
#### Steps for reproducing this issue:

1. Install debian buster/bullseye with Mate DE, Ubuntu mate 20.04 lts
2. Install steam and dota 2
3. Launch dota 2 and try grabbing and dragging

**Comment by kisak-valve** [comment] 2020-05-28 12:53
Closing as a duplicate of https://github.com/ValveSoftware/Dota-2/issues/1764.

**Closed by kisak-valve** 2020-05-28 12:53 UTC
