### ISSUE TITLE
[steam client]Asian steam users need good language support, IME is the biggest issue.

### ISSUE THREAD

**Issue by alexanderhou** [ValveSoftware/steam-for-linux#3105] opened 2014-01-16 05:23 UTC
[steam client]Asian steam users need good language support, IME is the biggest issue.

steam linux client does not support modern Asian language IME(input method editor/enhancer), Chinese, Japanese, Korean, they all need IME to input under linux.

but steam for linux does not support IME on linux, e.g. on ubuntu, there are ibus IME family. lots of IME software.
## 

thank you . this is a feature request.

i know it is not easy. really. not a easy joke. ton of work needs to be made for this.

thank you again. but i think Asian does not want this issue to be a "good to know" issue, and "no one care" issue.

**Comment by kisak-valve** [comment] 2017-10-27 15:05
Closing as a duplicate of #781.

**Closed by kisak-valve** 2017-10-27 15:05 UTC
Labels: Feature Request, reviewed, Steam client
