### ISSUE TITLE
Add toggles for offloading Nvidia and AMD in steam/game settings

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#9308] opened 2023-03-30 12:58 UTC
#### Your system information

* Steam client version (build number or date): Mar 24 2023 at 17:20:43
* Distribution (e.g. Ubuntu): Fedora Workstation 37
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

So i would like to suggest this to the Steam Linux because it's annoying to type in prime-run or the offloading thing for every game (especially when the user has an big library). It would be nice if there would be a toggle in the Steam settings or Game settings for enabling prime offloading. It would also be nice to add an gamemode toggle when gamemode is detected on the system.

**Comment by kisak-valve** [comment] 2023-03-30 13:10
Hello @Njezi, this is functionally a duplicate of #3453. Closing in favor of the older feature request.

**Closed as not planned by kisak-valve** 2023-03-30 13:10 UTC
