### ISSUE TITLE
[CS16] Spectator list fails in ubuntu

### ISSUE THREAD

**Issue by Jonuz** [ValveSoftware/steam-for-linux#2633] opened 2013-07-02 12:32 UTC
Hey, when you are dead, and you press ctrl to select player you wanna watch you can't close that list.

OS: Ubuntu 12.04

**Comment by kisak-valve** [comment] 2017-05-26 14:23
Closing as a duplicate of https://github.com/ValveSoftware/halflife/issues/177.

**Closed by kisak-valve** 2017-05-26 14:23 UTC
Labels: MOVED: Counter‐Strike, reviewed
