### ISSUE TITLE
Xbox One not working in-game

### ISSUE THREAD

**Issue by alfonsoler** [ValveSoftware/steam-for-linux#5911] opened 2018-11-20 23:49 UTC
#### Your system information

* Steam client version (build number or date): 1542672201
* Distribution (e.g. Ubuntu): Ubuntu 18.10
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Xbox Controller connected via Bluetooth to Steam Link Hardware. No title responds to the gamepads anymore,  games just seem to recognize the mouse and keyboard of my PC OR the gamepads, if they are connected directly to my PC and not to SteamLink.
The menus work: If I press the HOME button on the gamepad, the menu of Steam Link opens itself. All menu interactions inside Steam Link and Big Picture work perfectly. Just not in-game input.
I tried all solutions I found in forums. I also reinstalled Ubuntu, firmware in SteamLink, changed drivers both in SL and PC, tried an update in Windows (which did not work),...

#### Steps for reproducing this issue:

1. Run Steam Link Hardware and connect with the PC
2. Start a game using the gamepad in the menus
3. Failure appears direct. Only HOME button works.
[streaming_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/2602021/streaming_log.txt)
[steamlink_debug.txt](https://github.com/ValveSoftware/steam-for-linux/files/2602022/steamlink_debug.txt)
[streaming_log.previous.txt](https://github.com/ValveSoftware/steam-for-linux/files/2602023/streaming_log.previous.txt)

**Comment by alfonsoler** [comment] 2018-11-21 00:39
From now after trying with Steam Link for Android (also not working):
[streaming_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/2602115/streaming_log.txt)

**Comment by alfonsoler** [comment] 2018-11-21 18:40
I think I had some outdated TXT. Here from today's try, after changing into Beta in the SteamLink Hardware and trying to play wired (into the SL):
[streaming_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/2605395/streaming_log.txt)
[steamlink_debug.txt](https://github.com/ValveSoftware/steam-for-linux/files/2605396/steamlink_debug.txt)

**Comment by alfonsoler** [comment] 2018-11-22 08:43
No problem under Windows with a laptop. So it is deffinetly a Problem with the Host.

**Comment by vitaminace33** [comment] 2018-11-25 20:14
#### Host system information
* Steam client version: 1541819448 (Nov 10 2018)
* Distribution: Ubuntu 18.04.1
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Steam Link system information
* Steam Link version: 1541819448 (Nov 10 2018)
* Opted into beta compilation?: No
* Have you checked for system updates?: Yes

#### Issue description
Gamepad (Logitech Wireless Gamepad F710) works flawlessly on Steam Link system and, when streaming, on Big Picture Mode. Gamepad is not recognized by any game. However, if Logitech (home) button is pressed, then the Big Picture Mode layer appears and, as said, gamepad inputs are followed.

In summary, gamepad works in-menu but not in-game.

#### Steps for reproducing this issue:
1. Start the Steam client on the host computer.
2. Plug the usb receiver into Steam Link and switch it on.
3. Use the gamepad on the Steam Link system to start the host's streaming.
4. Navigate through Big Picture Mode using the gamepad to start any game.
5. The game fails to respond to the gamepad inputs.

#### Workaround
After step 3 above, unplug the usb receiver from the Steam Link and plug it into the host computer. (It defies the purpose of the Steam Link if the device and the computer are in separate rooms.)

#### Extras
I have tried to "switch to modern Xbox controller driver" from Steam Link system menu with no success.

#### Attachments
steamlink_debug.txt not found
[streaming_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/2613459/streaming_log.txt)

**Comment by alfonsoler** [comment] 2018-11-25 20:29
The problem is a Host problem, so I do not know if the SteamLink label would help. Here the answer of Steams Support:

Hello again,

Thanks for clarifying that for me. Now, i understand that this issue is only prevalent when using the Steam Link, but because the issue is specific on connection to the Linux Host, rather then on the Steam Link Menus, your best bet is to share your experience on the GitHub. 

I apologize for the inconvenience, and I am sorry that I do not have a more immediate solution for you. 

Thanks for using Steam,
Cole

**Comment by vitaminace33** [comment] 2018-11-25 22:29
Out of curiosity, I have tried a keyboard and mouse (Logitech Wireless). They both worked perfectly, so it seems it is restricted to gamepads. Since the Logitech Wiresless Gamepad F710 is an Xbox-like controller, I wonder if this happens also with PlayStation controllers. It would be of interest if someone could test this or even other controllers.

**Comment by vitaminace33** [comment] 2018-11-25 22:33
@alfonsoler, it is not clear to me what do you mean by "host". Just to be specific: Since this happens only on Steam Linux + Steam Link + Gamepads and since the gamepad works on the Big Picture Mode menus, which are part of the Steam Client, I guess the problem is that the Steam Client fails to transmit the gamepad inputs to the game.

Also, you are on Gentoo and I am on Ubuntu, so it doesn't seem to be distro specific.

That said, little off-topic, are you Spanish?

**Comment by alfonsoler** [comment] 2018-11-25 23:00
Gentoo? No no, Ubuntu 18.10 (I thought it was maybe a problem with the upgrade but I see you have 18.04 so...).
And were the mouse and keyboard connected to the Link?
Y sí, se me ha visto el plumero ;)

**Comment by vitaminace33** [comment] 2018-11-25 23:58
> Gentoo? No no, Ubuntu 18.10 (I thought it was maybe a problem with the upgrade but I see you have 18.04 so...).

True, not Gentoo. My bad, I confused it with another thread. I will try on Arch Linux.

> And were the mouse and keyboard connected to the Link?

Yes.

> Y sí, se me ha visto el plumero ;)

Pozí, el apellido te ha delatao.

**Comment by alfonsoler** [comment] 2018-11-26 12:02
From today's try with Amazon FireStick TV 4k (also not working with the Gamepad connected to the Stick via bluetooth. Only working if connected directly to the PC):
[streaming_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/2615382/streaming_log.txt)

**Comment by alfonsoler** [comment] 2018-11-27 08:53
That worked right now with the Fire Stick! Thank you. I will test it further later on.

**Comment by vitaminace33** [comment] 2018-11-27 11:03
;-) GL

**Comment by alfonsoler** [comment] 2018-11-28 23:01
Just one problem: RT and LT are inverted (?)

**Comment by vitaminace33** [comment] 2018-11-29 01:09
For me, all ok. Check it on the Link system, before connecting to the client (i.e. streaming). You can reset the button biding map and check if the default one is correct. If you then still have problems, it must be some controller configuration in the client or the game. Remember to activate "Xbox support" to have per-game settings.

Happy to hear that it works.

**Comment by vitaminace33** [comment] 2018-12-07 02:36
@alfonsoler, mark the thread as "solved".

**Comment by kisak-valve** [comment] 2018-12-07 03:17
This isn't a forum, resolved issue reports get closed, not tagged. Closing per the recent discussion.

**Closed by kisak-valve** 2018-12-07 03:17 UTC
Labels: General controller / Steam Input, Streaming
