### ISSUE TITLE
Steam client crashes when attempting to create online session in Monster Hunter World

### ISSUE THREAD

**Issue by thelyric27** [ValveSoftware/steam-for-linux#11613] opened 2024-12-29 02:49 UTC
#### Your system information

* Steam client version (build number or date): 1734743608 | Fri, Dec 20 7:01 PM UTC -06:00
* Distribution (e.g. Ubuntu): Linux Mint 21.1 "Vera"
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/user-attachments/files/18268246/steam-logs.tar.gz)
* GPU: AMD Radeon 6600 XT 8gb

#### Please describe your issue in as much detail as possible:
When trying to load a save in the game Monster Hunter World, it forces you to either join or create an online session to play. When I do this, it freezes on this screen immediately after pressing the button, stays for a few moments, then both the game AND the Steam client crash. It's believed that the game could be played offline because throughout the tutorial the game ran flawlessly, but once I was eligible to join other online players it put me into a session and crashed. The method to play the game offline however requires running Steam in offline mode, and I mostly got this game to play with friends. After searching on Google and ProtonDB, it doesn't seem like there have been other cases of this happening, so I'd like to know what about my setup could cause this.
![image](https://github.com/user-attachments/assets/866e7ec9-fe8c-4409-916b-b017ef59ad07)

#### Steps for reproducing this issue:

1. Use a system running Linux Mint 21.1, AMD processor and GPU,
2. Launch Monster Hunter World with Steam Play (Proton Experimental)
3. Progress to the end of the tutorial or load a save to attempt to enter online play. 
4. The game and Steam client will crash. It's unclear if the game or Steam crashes first, as if Steam closes, so will any game it's running.

**Comment by kisak-valve** [comment] 2024-12-29 03:08
Hello @thelyric27, does opting out of Steam's client beta have an effect? There's a decent chance this is the same issue as #11592.

**Comment by thelyric27** [comment] 2024-12-29 04:47
> Hello @thelyric27, does opting out of Steam's client beta have an effect? There's a decent chance this is the same issue as #11592.

That does the trick, yep. I also just found a post on Reddit describing the same problem posted yesterday that I hadn't seen before, and opting out of the beta was mentioned in the comments.

**Comment by Nekkowe** [comment] 2024-12-29 07:37
Same here! Opting out of the beta fixed it for me too.

**Comment by kisak-valve** [comment] 2024-12-29 13:41
Thanks for testing, let's treat this as a duplicate of #11592 until there's evidence otherwise.

Closing in favor of the older issue report.

**Closed by kisak-valve** 2024-12-29 13:41 UTC
Labels: Steam client, Proton
