### ISSUE TITLE
Borderlands 2 stuck in validation loop after forcing the use of Proton 4.2-2

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-for-linux#6201] opened 2019-04-07 13:46 UTC
#### Your system information

* Steam client version (build number or date): Feb 18 2019, at 22:09:18
* Distribution (e.g. Ubuntu): Fedora 29 Workstation
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

After realising that the new Borderlands 2 update broke cross-play between Windows and macOS/Linux, I thought I'd try installing the Windows version and run it via Proton instead, so I went into Borderlands 2's properties and enabled "Force the use of a specific Steam Play compatibility tool", after which a download was triggered. 

The download completed and validated as expected, but after that kept validating over and over. Ultimately I decided to uninstall Boderlands 2 and reinstall it, after which the game installed and launched just fine (with the appropriate tweaks for running it in Proton, of course). 

Side note: A friend of mine had the exact same issue with Borderlands: The Pre-Sequel on an Arch Linux install.

#### Steps for reproducing this issue:

1. Install the native Linux Borderlands 2 game.
2. Run it and exit out (I'm not sure whether this is required).
3. Force the use of Proton 4.2-2 (probably not related to a specific version, but I thought I'd add it).
4. Observe Borderlands 2 validate seemingly forever after the download has finished.

**Comment by kisak-valve** [comment] 2019-04-07 14:01
Possible duplicate of #6044.

**Comment by LingMan** [comment] 2019-05-17 13:00
Exact same issue for me.

#### System information

* Steam client version (build number or date): Apr 29 2019, at 20:58:26
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

**Comment by TheDaftRick** [comment] 2019-06-05 04:29
Having the same issue

Your system information

    Steam client version (build number or date): May 22 2019, at 21:55:41
    Distribution (e.g. Ubuntu): Ubuntu 19.04
    Opted into Steam client beta?: Yes
    Have you checked for system updates?: Yes

**Comment by Kolloom** [comment] 2019-06-12 04:55
I have ran into something similar. 
Switching from Native Linux to Proton causes a 3.9GB download. 
Something about not able to update the ``Config/BaseBuildInfo.ini`` file.  
If reverting back to Linux version, another 3.9GB download is forced. 

    Steam client version (build number or date): Apr 29, 2019 20:58:26
    Distribution (e.g. Ubuntu): Ubuntu 19.04
    Opted into Steam client beta?: No
    Have you checked for system updates?: Yes

```
[2019-06-11 19:35:17] AppID 49520 update changed : Running,
[2019-06-11 19:35:17] AppID 49520 update changed : Running,Committing,
[2019-06-11 19:35:17] AppID 49520 file commit : 11773 updated, 2194 moved, 1248 deleted
[2019-06-11 19:35:21] AppID 49520 update canceled : File commit failed: failed to move unchanged file "/home/thompson/.steam/steam/steamapps/common/Borderlands 2/Engine/Config/BaseBuildInfo.ini" (Disk write failure) "/home/thompson/.steam/steam/steamapps/common/Borderlands 2/Engine/Config/BaseBuildInfo.ini"
[2019-06-11 19:35:21] AppID 49520 update changed : Running,Committing,Stopping,
[2019-06-11 19:35:21] AppID 49520 update changed : Running,Stopping,
[2019-06-11 19:35:21] AppID 49520 update changed : None
[2019-06-11 19:35:21] AppID 49520 state changed : Update Required,Fully Installed,Update Queued,Update Optional,Update Started, (Disk write failure)
[2019-06-11 19:35:21] AppID 49520 state changed : Update Required,Fully Installed,Update Optional,Update Paused,Update Started,
[2019-06-11 19:35:21] AppID 49520 scheduler finished : removed from schedule
[2019-06-11 19:35:36] Current download rate: 0.000 Mbps
[2019-06-11 19:36:16] HTTP (SteamCache,90) - cache6-okc1.steamcontent.com (155.133.254.21:80 / 155.133.254.21:80, host: cache6-okc1.steamcontent.com): Closing connection
[2019-06-11 19:36:16] HTTP (CDN,64) - edge.steam-dns-2.top.comcast.net (69.241.121.226:443 / 69.241.121.226:443, host: edge.steam-dns-2.top.comcast.net): Closing connection
[2019-06-11 19:36:16] HTTP (CDN,64) - edge.steam-dns-2.top.comcast.net (69.241.121.226:443 / 69.241.121.226:443, host: edge.steam-dns-2.top.comcast.net): Closing connection
[2019-06-11 19:36:17] HTTP (CDN,64) - edge.steam-dns.top.comcast.net (69.241.80.106:443 / 69.241.80.106:443, host: edge.steam-dns.top.comcast.net): Closing connection
[2019-06-11 19:36:17] HTTP (SteamCache,103) - cache3-okc1.steamcontent.com (155.133.254.4:80 / 155.133.254.4:80, host: cache3-okc1.steamcontent.com): Closing connection
[2019-06-11 19:36:17] HTTP (SteamCache,134) - cache16-lax1.steamcontent.com (162.254.195.27:80 / 162.254.195.27:80, host: cache16-lax1.steamcontent.com): Closing connection
[2019-06-11 19:39:03] AppID 49520 scheduler update : Priority First, legacy=no, restore="", timeSinceLastPlayed=2680, appDisableSecondsRemaining=0
[2019-06-11 19:39:03] AppID 49520 state changed : Update Required,Fully Installed,Update Queued,Update Optional,Update Started,
[2019-06-11 19:39:03] AppID 49520 state changed : Update Required,Fully Installed,Update Queued,Update Optional,Update Running,Update Started,
[2019-06-11 19:39:03] AppID 49520 update changed : Running,
[2019-06-11 19:39:03] AppID 49520 update changed : Running,Reconfiguring,
[2019-06-11 19:39:03] AppID 49520 update changed : Running,
[2019-06-11 19:39:03] AppID 49520 update started : download 4179292304/4179292304, store 0/0, reuse 0/0, delta 0/0, stage 4814811651/4814811651 
[2019-06-11 19:39:04] AppID 49520 update changed : Running,Committing,
[2019-06-11 19:39:04] AppID 49520 file commit : 11773 updated, 2194 moved, 1248 deleted
[2019-06-11 19:39:08] AppID 49520 update canceled : File commit failed: failed to move unchanged file "/home/thompson/.steam/steam/steamapps/common/Borderlands 2/Engine/Config/BaseBuildInfo.ini" (Disk write failure) "/home/thompson/.steam/steam/steamapps/common/Borderlands 2/Engine/Config/BaseBuildInfo.ini"
[2019-06-11 19:39:08] AppID 49520 update changed : Running,Committing,Stopping,
[2019-06-11 19:39:08] AppID 49520 update changed : Running,Stopping,
[2019-06-11 19:39:08] AppID 49520 update changed : None
[2019-06-11 19:39:08] AppID 49520 state changed : Update Required,Fully Installed,Update Queued,Update Optional,Update Started, (Disk write failure)
[2019-06-11 19:39:08] AppID 49520 state changed : Update Required,Fully Installed,Update Optional,Update Paused,Update Started,
[2019-06-11 19:39:08] AppID 49520 scheduler finished : removed from schedule

**Comment by kisak-valve** [comment] 2021-08-20 14:18
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by LingMan** [comment] 2021-08-20 19:31
Can't reproduce anymore. Deleted the game, reinstalled native Linux version, and then switched to Proton 6.3-5.

**Comment by kisak-valve** [comment] 2021-09-24 18:34
Thanks fore retesting @LingMan, closing.

**Closed by kisak-valve** 2021-09-24 18:34 UTC
Labels: Steam client, Need Retest, Proton

**Comment by ambushxd** [comment] 2024-03-19 17:48
i realise this is a closed issue, but this is still happening on both steam proton and proton-ge, everytime i log in to steam, it validates, and then downloads the same update for me, its 1.3gb and then a further 800 - 900 MB.
i am using steam proton experimental and also ge-proton 9.1

**Comment by kisak-valve** [comment] 2024-03-19 17:56
Hello @ambushxd, you're looking for #10285 instead of this issue report.

**Comment by ambushxd** [comment] 2024-03-19 18:07
ah, ok, thankyou for pointing that out, i will keep an eye on that issue report.
