### ISSUE TITLE
Big Picture Mode: "Japanese (Rōmaji)" Keyboard Layout causes crash

### ISSUE THREAD

**Issue by hogehoge61** [ValveSoftware/steam-for-linux#10427] opened 2024-01-24 03:48 UTC
#### Your system information
* Steam client version (build number or date): 1705108172
* Distribution (e.g. Ubuntu): Arch Linux (2024-01-24 updated)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14032204/steam-logs.tar.gz)
* GPU: AMD Radeon RX 580 (probably not relevant)

#### Steps for reproducing this issue:

1. Launch the Steam client in Big Picture mode
2. Enable and Select "Japanese (Rōmaji)" from "Settings" -> "Select Active Keyboards Layouts""
3. Open OSK by focusing the search window on the top menu
4. The window will freeze for a while and Big Picture mode will restart.

![1-zop](https://github.com/ValveSoftware/steam-for-linux/assets/46648494/33f2fa20-c54f-446a-a860-d41a34739eac)

In addition to "Japanese (Rōmaji)", "Korean" also causes OSK to crash.

I have confirmed this issue on Arch Linux, occurring in both Beta channel (1705720677) and Stable channel (1705108172).

This problem also occurs with the SteamOS / current Steam Deck Beta client (1705720677), but strangely enough, when I switch back to the Steam Deck Stable client (1705108172) from desktop mode, OSK works fine. (Are there different builds even with the same version number? I don't know)

**Comment by smcv** [comment] 2024-02-12 11:16
We've found the cause for this crash, it should be fixed in a future beta.

**Comment by smcv** [comment] 2024-02-12 11:21
Workaround: **in the stable channel only**, install [ibus-anthy](https://archlinux.org/packages/extra/x86_64/ibus-anthy/) for the Japanese (Rōmaji) OSK, or [ibus-hangul](https://archlinux.org/packages/extra/x86_64/ibus-hangul/) for the Korean OSK. (Those package names are valid for at least Arch and Debian, other distros might vary.) If you want to type in Japanese or Korean, you'll probably need those packages installed anyway.

This workaround will not work in the beta channel. A proper fix for that is in progress.

> when I switch back to the Steam Deck Stable client (1705108172) from desktop mode, OSK works fine

I suspect that the Steam Deck already has ibus-anthy and/or ibus-hangul installed as part of SteamOS. If that's the case, then its situation is equivalent to the workaround I described.

**Comment by TTimo** [comment] 2024-02-14 14:56
This should be fixed in latest Steam beta client on Steam Deck.

**Comment by kisak-valve** [comment] 2024-03-22 22:16
Closing per the last comment.

**Closed by kisak-valve** 2024-03-22 22:16 UTC
Labels: Big Picture, Need Retest, Distro Family: Arch
