### ISSUE TITLE
estrength error message overlay in new Big Picture mode with bridged networking

### ISSUE THREAD

**Issue by NoXPhasma** [ValveSoftware/steam-for-linux#9122] opened 2023-01-20 07:50 UTC
#### Your system information

* Steam client version (build number or date): Fr., 20. January 2023
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?:  Yes

#### Please describe your issue in as much detail as possible:
I get this error message overlay about `estrength` in the new big picture mode. It is always visible, on each page.  Apparently it has something to do with the Wifi, but I have no Wifi and Wifi option is disabled in the settings.

I've already tried to reset Steam and switched between steam stable and beta, no success.

![grafik](https://user-images.githubusercontent.com/7719590/213643400-14008f50-aa37-46ec-96fd-3040f16cf07d.png)

**Comment by RedstoneLP2** [comment] 2023-02-08 00:55
Doing some tests after facing the issue myself, it appears to be (at least on my end) related to bridged network connections being used to connect to the internet. Disabling them and connecting to the network directly made it disappear for me.
In case further info about my setup is needed feel free to reach out

**Comment by NoXPhasma** [comment] 2023-02-08 06:28
@RedstoneLP2 Interesting find, I do have a bridged network as well. Switching to the main internet connection lets the text disappear.

**Comment by hasechris** [comment] 2023-02-14 20:23
just to add my two cents here. Same happened to me just now. I also use a bridged networking, so my windows virtual machine also can use a "native" connection with a individual ip address.

**Comment by ignisf** [comment] 2023-04-04 20:47
I can confirm, same for a vlan interface

**Comment by palves** [comment] 2023-06-03 23:28
Same here, using bridged networking as well.

**Comment by ignisf** [comment] 2023-06-04 23:49
I'd just like to say that I'd have opened a PR for that if the UI source code was available here under whatever license*

**Comment by maplehobo** [comment] 2023-06-17 00:26
Same here. Also bridged network for vm. This was driving me crazy.

**Comment by erpadmin** [comment] 2023-07-04 00:39
can confirm, bridge networking in use on my end

**Comment by RedstoneLP2** [comment] 2023-07-04 01:07
I'm gonna take a stab in the dark: The Steam client is looking for an icon for the specific network type, which doesn't exist. 
If this is the case, the easiest solution would be putting a "generic" network icon as a sort of "catch all" for connection types which don't have their own icon (yet)

Again, this is pure speculation on my part

**Comment by GreatKitsune** [comment] 2023-08-09 22:20
I am having the same issue would like a fix as I likey bridged connection.

**Comment by A-UNDERSCORE-D** [comment] 2023-08-13 20:08
Confirmed here. Wireguard VPN added though steam deck desktop mode

**Comment by crash83k** [comment] 2023-09-10 05:36
I'm having this issue with a bonded network.

**Comment by billpayne4x4** [comment] 2023-11-04 02:36
I have the same issue with a bridged network

**Comment by alex-blueguardianco** [comment] 2023-11-18 09:30
I'm also seeing this with both bridge and VLAN networking.
I agree that it should just use the generic globe network icon as a default.

**Comment by erpadmin** [comment] 2023-11-18 19:52
@kisak-valve is there anyway to know if this issue is at least on the radar somewhere?  i dont see that it is assigned to anyone.  many of use can help reproduce if that is needed

**Comment by JJRcop** [comment] 2023-12-15 18:17
I can reproduce this as well, using a bridged network on NetworkManager

![Screenshot_20231215_201201](https://github.com/ValveSoftware/steam-for-linux/assets/5211576/dae41bec-8a59-45e2-aec4-b5c0c3a466cd)

**Comment by JJRcop** [comment] 2023-12-15 18:20
> @kisak-valve is there anyway to know if this issue is at least on the radar somewhere?

@erpadmin Looks like @kisak-valve has already made comments on other issues referring to this one [here](https://github.com/ValveSoftware/steam-for-linux/issues/9787#issuecomment-1619294836) and [here](https://github.com/ValveSoftware/SteamVR-for-Linux/issues/621#issuecomment-1747196079). I'm sure that's confirmation that it is at least known, but you might want to know if it is on any roadmap to actually get fixed or not.

**Comment by lastedge** [comment] 2023-12-25 11:07
Also experiencing this issue. I'm not using a bridge or a bonded connection but Bluetooth tethering from my phone. The error message itself is also an issue as it is obtrusive and obscures UI elements, and can't be dismissed or hidden.

**Comment by terroreek** [comment] 2023-12-28 15:42
I am getting the same thing with a bridged network connection.

**Comment by alex-blueguardianco** [comment] 2024-01-16 01:36
@lostgoat - can you please take a look at this issue?

**Comment by lostgoat** [comment] 2024-01-16 21:24
I added a speculative fix for this since I didn't have a repro. It will come out with the next steam client beta.

Once that is out let me know if it fixes this issue.

**Comment by A-UNDERSCORE-D** [comment] 2024-01-16 21:25
Awesome! Will be sure to give feedback

**Comment by NoXPhasma** [comment] 2024-01-19 12:34
I can confirm as well, the error message is gone with latest beta.

**Comment by lostgoat** [comment] 2024-01-19 14:26
Great! Thanks for the issue report.

**Closed by lostgoat** 2024-01-19 14:26 UTC
Labels: Big Picture, Need Retest
