### ISSUE TITLE
games dont grab (input)focus properly on launch

### ISSUE THREAD

**Issue by cjwijtmans** [ValveSoftware/steam-for-linux#4899] opened 2017-03-18 14:31 UTC
#### Your system information
* Steam client version (build number or date): 1489791860
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I am playing on my steamlink but this issue is not isolated to BPM/streaming.
Some games on launch fail to grab focus from steam/BPM.
Terraria: no visual focus but input focus.(game is windowed though)
Rocketleague: visual focus but no input focus (and desktop cursor is visible)
Binding of isaac: visual focus but no input focus
Portal2: visual focus AND input focus.
Etc.

Focus grabbing prevention turned OFF on KDE.
With physical access to desktop i can grab focus to the game.

Very annoying bug and discouraging to play games via my desktop...

**Comment by kisak-valve** [comment] 2017-03-18 14:48
Possibly SDL related, assigning to the SDL dev. Some of these games bundle SDL, so the individual game devs may need to contacted after this is figured out.

**Comment by cjwijtmans** [comment] 2017-03-18 14:53
Would like to add that i dont have SDL installed on my system.

**Comment by cjwijtmans** [comment] 2017-03-18 15:04
Also when i press i press the steam button on the controller i see the steam overlay in the game and i have input focus but when i close the menu again no input focus in the game.

**Comment by Uramekus** [comment] 2018-08-23 04:06
@cjwijtmans can you still reproduce that? cant reproduce on my i3wm setup, its surely WM dependent

**Comment by cjwijtmans** [comment] 2018-08-24 09:48
Dont have a desktop gentoo box atm so afraid not.

**Comment by kisak-valve** [comment] 2018-08-24 13:34
Closing per the last comment.

**Closed by kisak-valve** 2018-08-24 13:34 UTC
Labels: 3rd party game, Distro Family: Gentoo, MOVED: Portal2, Need Retest
