### ISSUE TITLE
Remote Play for Proton games no longer works on Linux client.

### ISSUE THREAD

**Issue by laichiaheng** [ValveSoftware/steam-for-linux#6971] opened 2020-03-21 07:49 UTC
#### Your system information

* Steam client version (build number or date): Mar 20 2020
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Every game returns black screen on my client, but I can still hear the sound.

#### Steps for reproducing this issue:

1. Streaming the Proton game via Remote Play on my Linux client PC.
2. Black screen.

**Comment by kisak-valve** [comment] 2020-03-21 12:22
Hello @laichiaheng, without any finer details, this issue is a duplicate of #6716. Feel free to add your experience to the existing issue report.

**Closed by kisak-valve** 2020-03-21 12:22 UTC

**Comment by laichiaheng** [comment] 2020-03-21 12:25
@kisak-valve I had found out that it was an hardware decoding issue.

**Comment by tuxtergames** [comment] 2020-06-24 22:43
anoyone have success with remote play, here I can share my game, but  both  just can control player one me with my joystick and keyboard and he only with keyboard, in big picture configs we can see two controlers but just the host can use controller.

**Comment by ZerataX** [comment] 2020-07-22 23:32
sorry to keep going offtopic, but @tuxtergames what happens when you use the option under *controller options* in big picture mode to rearrange controllers and switch yours and your friend's controller order?

**Comment by tuxtergames** [comment] 2020-07-23 01:42
> sorry to keep going offtopic, but @tuxtergames what happens when you use the option under _controller options_ in big picture mode to rearrange controllers and switch yours and your friend's controller order?

Tks for reply, I just can see the two controllers, and set a share configs, but nothing happens, my friends just assume my keyboard always with player one and both os us always control the same player, I try with a several games, Teken 7, dragon ball fighterz, even a native game horizon chase, nothing works with all games we have tried, I'll try to gerate a new logs to upload here.

**Comment by ZerataX** [comment] 2020-07-23 01:51
hmm I mean this option 

![image](https://user-images.githubusercontent.com/5024958/88245470-9dee7580-cc97-11ea-98a5-6fbffe4d26d2.png)

For me swapping slot 1 & 2, suddenly allowed my remote friend to control with their controller

**Comment by tuxtergames** [comment] 2020-07-23 02:01
> hmm I mean this option
> 
> ![image](https://user-images.githubusercontent.com/5024958/88245470-9dee7580-cc97-11ea-98a5-6fbffe4d26d2.png)
> 
> For me swapping slot 1 & 2, suddenly allowed my remote friend to control with their controller

sorry, we try to to change this options but nothing happen, controller of the person was invited never work, when we change the player 2 for first player, even my controller stop to work, I was reading on steam to allow /dev/uinput ou /dev/input/uinput to read and write but even doing this not working.

**Comment by ZerataX** [comment] 2020-07-23 02:03
huh only your controller stops? completely or does it still work in the steam overlay?
it does stop my controller from working (tho using 2 controllers on my side fixed that), but yeah remote controller suddenly worked like my controller used to.

**Comment by tuxtergames** [comment] 2020-07-23 02:09
> huh only your controller stops? completely or does it still work in the steam overlay?
> it does stop my controller from working in game, not overlay iirc (tho using 2 controllers on my side fixed that), but yeah remote controller suddenly worked like my controller used to.

only stops to working with  games, on overlay still works, I never tried to plug 2 controllers on the same time, I'll try that to see what happen

**Comment by tuxtergames** [comment] 2020-07-23 11:38
> huh only your controller stops? completely or does it still work in the steam overlay?
> it does stop my controller from working in game, not overlay iirc (tho using 2 controllers on my side fixed that), but yeah remote controller suddenly worked like my controller used to.

Hi @ZerataX!!! trting again here with your tip and nothing works again, when I change my friend controller all controllers doesn't work on game, but in steam overlay works nice, really I don't know what to do anymore, only works two keyboards controlling player one

file:///home/tuxter/image20.png
