### ISSUE TITLE
Segmentation Fault on startup

### ISSUE THREAD

**Issue by tonyblatt** [ValveSoftware/steam-for-linux#3248] opened 2014-04-12 02:46 UTC
On a new installation of the steam client (ubuntu 13.10), steam immediately crashed due to a segmentation fault. Output from terminal:

Running Steam on ubuntu 13.10 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0_client)
/home/tony/.local/share/Steam/steam.sh: line 755: 21860 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
mv: cannot stat ‘/home/tony/.steam/registry.vdf’: No such file or directory
Installing bootstrap /home/tony/.local/share/Steam/bootstrap.tar.xz
Reset complete!
Restarting Steam by request...
Running Steam on ubuntu 13.10 64-bit
STEAM_RUNTIME has been set by the user to: /home/tony/.local/share/Steam/ubuntu12_32/steam-runtime
Installing breakpad exception handler for appid(steam)/version(0_client)
/home/tony/.local/share/Steam/steam.sh: line 755: 21988 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"

I was unable to locate the core dump

**Comment by JarrodHenry** [comment] 2015-01-03 20:08
Need to bump this, as I'm seeing it on Fedora 21 with an Nvidia Geforce GTX 660

**Comment by Esras** [comment] 2015-01-04 00:43
With the Nvidia 343 driver (installed through the downloadable installer) on Fedora 21 with dual GTX970s, I am getting the following, as well:
```
$ steam
Running Steam on fedora 21 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0_client)
/home/USER/.local/share/Steam/steam.sh: line 730:  5127 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
mv: cannot stat ‘/home/USER/.steam/registry.vdf’: No such file or directory
Installing bootstrap /home/USER/.local/share/Steam/bootstrap.tar.xz
Reset complete!
Restarting Steam by request...
Running Steam on fedora 21 64-bit
STEAM_RUNTIME has been set by the user to: /home/USER/.local/share/Steam/ubuntu12_32/steam-runtime
Installing breakpad exception handler for appid(steam)/version(0_client)
/home/USER/.local/share/Steam/steam.sh: line 730:  5216 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
```

I might not be able to do anything with Steam with Nouveau, because that produces a "Something went wrong" message on the Gnome login screen and won't let me get past it to a GUI, so I'm betting steam won't start if it can't find X.

**Comment by richardramirez** [comment] 2015-01-04 18:52
I am just trying to install Steam on fresh F21 install with nvidia 340.65 drivers:
```
$ steam 
Running Steam on fedora 21 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0_client)
/home/ysy/.local/share/Steam/steam.sh: linia 730:  3760 Naruszenie ochrony pamięci   (zrzut pamięci) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
mv: nie można wykonać stat na „/home/ysy/.steam/registry.vdf”: Nie ma takiego pliku ani katalogu
Installing bootstrap /home/ysy/.local/share/Steam/bootstrap.tar.xz
Reset complete!
Restarting Steam by request...
Running Steam on fedora 21 64-bit
STEAM_RUNTIME has been set by the user to: /home/ysy/.local/share/Steam/ubuntu12_32/steam-runtime
Installing breakpad exception handler for appid(steam)/version(0_client)
/home/ysy/.local/share/Steam/steam.sh: linia 730:  3849 Naruszenie ochrony pamięci   (zrzut pamięci) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

```
i tried both http://negativo17.org/steam/ and RPMFusion

**Comment by JarrodHenry** [comment] 2015-01-04 19:01
Okay, there is a workaround for this (for fedora users.)  You're going to need to remove your nvidia drivers and jump back to nouveau.   Get back into X running nouveau (by removing the nvidia driver _AND_ the nvidia X Server) , and removing the blacklist of the module from /etc/modprobe.d (Just comment it out.)  You MAY also have it blacklisted in /etc/sysconfig/grub, check there too.  

Once you're back in nouveau, give steam a start up.  All you need to do is login to it.  Then, reverse the process, put the nvidia drivers back in, and you should be good to go.

Obviously though this is steam bug or an nvidia driver bug, but this will get you moving.

**Comment by richardramirez** [comment] 2015-01-04 20:44
> remove your nvidia drivers and jump back to nouveau
I can confirm this walkaround - steam updated itself on nouveau, now its running ok on nvidia drivers

**Comment by richardramirez** [comment] 2015-01-07 16:54
Not sure how this could be ATI users problem? All users in this thread have nvidia cards and use nvidia binary drivers.

**Comment by eddie-dunn** [comment] 2015-01-08 12:34
@richardramirez read the second post in this thread. Also, I encountered this problem with my AMD card, and a friend of mine did as well. Curiously, none of my systems with nVidia cards had this issue.

**Comment by Esras** [comment] 2015-01-12 01:02
An update:

With F21 now running the latest kernel update (from 1/11/2015 - 3.17.8-300.fc21.x86_64), Steam was able to start just fine and run its update process.  Note that I did have to reinstall the NVidia driver (343.36) for the new kernel as I had originally installed it from their downloaded package.

**Comment by wolterh** [comment] 2015-01-22 17:39
I am following the average advise on the workaround for nvidia: 1) purge nvidia prop. binary drivers, 2) install and select nouveau drivers, 3) reboot, 4) purge steam, reinstall and let update, 5) install nvidia prop. binary drivers and select, 6) reboot, 7) try steam; (I'm on step 4 now.) However, I wonder if its really necessary to uninstall nvidia prop. drivers or moreover purge them; would it not work to just boot into X using nouveau and perform steps 4 and beyond?

**Comment by ZedCode** [comment] 2015-02-26 00:58
I ran into this issue on Fedora 21 and I had installed the nvidia drivers for my GTX 970m via the script from the nvidia site. This resulted in the same core dumping seen here. I resolved this issue by following the instructions here: http://rpmfusion.org/Howto/nVidia#Uninstall_the_nvidia_driver and ran `yum install akmod-nvidia "kernel-devel-uname-r == $(uname -r)"`.

Once I did this, I rebooted, launched Steam, signed in, then dropped back to the shell and re-ran the script from nvidia. That seemed to work without having to uninstall the nvidia drivers. I couldn't actually launch anything in steam because I only had the 64-bit drivers, but once I re-installed the nvidia drivers it all worked as expected.

**Comment by wlejon** [comment] 2015-03-02 02:33
I ran strace on the steam executable (according to the steam.sh script parameters) and found the crash happened in the libnvidia-glcore.so.

Updating to the latest nvidia driver (346.47) solved this problem for me.

**Comment by kalyanac** [comment] 2015-03-28 23:48
I am experiencing this with AMD GPUs
Using fglrx 14.501 (catalyst 14.12 omega driver). 

OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: AMD Radeon HD 7560D
OpenGL version string: 4.4.13283 Compatibility Profile Context 14.501.1003


DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.10
DISTRIB_CODENAME=utopic
DISTRIB_DESCRIPTION="Ubuntu 14.10"

3.16.0-33-generic #44-Ubuntu SMP Thu Mar 12 12:19:35 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by voidstarr** [comment] 2015-06-11 08:10
I am running nvidia gtx660 on ubuntu 14.04 with the driver version 346.47 and I am experiencing this issue.

**Comment by jairuncaloth** [comment] 2015-06-12 23:24
I'm on Fedora 22 and was using official NVIDIA 349.16 driver and was experiencing this issue.
Upgrading to NVIDIA 346.72 resolved this issue for me.

**Comment by djtm** [comment] 2015-06-14 16:34
A similar error happens when you restore a backup and symlinks were not properly transfered.

**Comment by Demiu** [comment] 2015-06-17 08:50
Using Manjaro Linux. Sadly, this bug has reappeared and steam reinstall, log in and update on noveau drivers now doesn't fix the issue when switching back to propetiary.

**Comment by wilken** [comment] 2015-06-17 20:32
This happens for me as well, on an XPS 13 2015 DE edition.
I get 

/home/morten/.local/share/Steam/steam.sh: line 756:  3011 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

When i try to run the installer.

My graphics card is:

00:02.0 VGA compatible controller: Intel Corporation Broadwell-U Integrated Graphics (rev 09) (prog-if 00 [VGA controller])
	Subsystem: Dell Device 0665
	Flags: bus master, fast devsel, latency 0, IRQ 47
	Memory at f6000000 (64-bit, non-prefetchable) [size=16M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at f000 [size=64]
	Expansion ROM at <unassigned> [disabled]
	Capabilities: <access denied>
	Kernel driver in use: i915

But unfortunately I have no idea what the drivers are, how to uninstall them and how to apply any of th tips in this thread.
Has anyone written a step-by-step guide?

**Comment by triffid** [comment] 2015-06-18 17:56
I just got hit with this one too, using nvidia-drivers-349.16 and kernel 4.0.5

Can confirm that temporarily switching to another driver, starting steam, then re-enabling nvidia-driver allows me to access my games via steam.

**Comment by rohit-n** [comment] 2015-06-23 00:05
Can confirm this issue on Manjaro Linux with proprietary NVIDIA drivers. Switching to nouveau and back does not work - I must stay on nouveau to use Steam.

**Comment by triffid** [comment] 2015-06-23 01:00
@rohit-n the procedure that worked for me is this:

1) switch to nouveau
2) start steam
3) switch to nvidia binary driver (keeping steam open)
4) run your favourite games

**Comment by fritz-net** [comment] 2015-07-24 23:55
same issue with AMD R9 290 and linux mint 17 3.19.0-22-generic
OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: AMD Radeon R9 200 Series 
OpenGL version string: 4.4.13374 Compatibility Profile Context 13.35.1005

**Comment by kyng** [comment] 2015-10-12 12:43
Had the same problem:
steam.sh: line 756: 15357 Bus error               (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
Error: Couldn't find bootstrap, it's not safe to reset Steam. Please contact technical support.
(Nvidia GT 720 nvidia-drivers 346-96)

Solution @triffid + restart worked for me.

**Comment by jimmyleith** [comment] 2015-10-21 06:53
Is there any actual solution to this other than some dodgy workaround?
Getting this issues on Nvidia Prop Drivers on a 970 after updating my steam.

**Comment by rijnswand** [comment] 2015-10-21 08:26
Is there a real solution to this? I've been running Steam without a problem until yesterday it suddenly decided to stop working.

**Comment by deathlire** [comment] 2015-10-21 08:31
You are suffering from the new linux beta bug unfortunately..and I want to warn anyone who removes that beta dir to get steam working again.. It deleted all of my games and had to re-download, of course i haven't looked to see yet if they in fact still will be there when beta works again. But just a heads up. If they want us to have SSE3 or whatever, i'll just go buy the games off the devs.

**Comment by rijnswand** [comment] 2015-10-21 09:29
Thanks, deathlire!
No need to erase the whole package dir, only the file called beta and steam.sh, see the reply here by eriixblaike: http://steamcommunity.com/groups/steamuniverse/discussions/1/490123727975571656/?tscn=1445401628

**Comment by jimmyleith** [comment] 2015-10-21 09:46
My issue was with the beta client as well. Looked very similar to this issue. If only I read your comment earlier I wouldn't be redownloading all my games .

**Comment by benletib** [comment] 2015-10-21 21:55
It's the first time I have pb with the beta client, same pb for me.
Thank you guys.

My error msg (in french) :
```
Running Steam on ubuntu 12.04 64-bit
STEAM_RUNTIME is enabled automatically
/home/benletib/.local/share/Steam/steam.sh : ligne 756 :  3801 Instruction non permise (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
```

**Comment by iacopodeenosee** [comment] 2015-10-30 18:03
similar here (ati/amd card with open source driver):
```
iacopodeenosee@ArchBox ~$ steam
/media/Dati/Steam/steam.sh: riga 161: VERSION_ID: variabile non assegnata
/media/Dati/Steam/steam.sh: riga 161: VERSION_ID: variabile non assegnata
Running Steam on arch  64-bit
/media/Dati/Steam/steam.sh: riga 161: VERSION_ID: variabile non assegnata
STEAM_RUNTIME is enabled automatically
/media/Dati/Steam/steam.sh: riga 756: 30681 Istruzione non consentita (core dump creato) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
```

**Comment by alexhultman** [comment] 2015-11-11 22:36
I get this when I start Steam on Fedora 22:

[alexhultman@localhost ~]$ steam
Running Steam on fedora 22 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
/home/alexhultman/.local/share/Steam/steam.sh: line 756:  2139 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

**Comment by ptimatth** [comment] 2015-11-23 21:11
Hi!
I have found the solution on fedora 23 !
I have the NVIDIA official(private) driver
you need to execute :
sudo dnf install xorg-x11-drv-nvidia
reboot and reinstall the NVIDIA official(private) driver
4.2.6-300.fc23.x86_64
GNU/Linux
Geforce GTX 760.

**Comment by acornesque** [comment] 2015-11-26 20:51
@ptimatth Thanks. I have the same specifications (4.2.6-300.fc23, GTX760). After installing xorg-x11-drv-nvidia and restarting, I was able to launch Steam. 

I have the latest proprietary NVIDIA drivers, was receiving a similar error as previously reported, and while stracing found it to be failing on libnvidia-glcore.so also.

**Comment by ZorkMyst** [comment] 2015-12-21 18:56
Hi, maybe this will be usefully for someone. It's enough to compile official drivers with 32-bit support.

**Comment by nycjv321** [comment] 2016-01-15 01:34
The segmentation fault is at a different location but are they related?

    [user ~]$ steam 
    Running Steam on fedora 23 64-bit
    STEAM_RUNTIME is enabled automatically
    Installing breakpad exception handler for appid(steam)/version(0)
    /$HOME/.local/share/Steam/steam.sh: line 756: 26680 Segmentation fault      (core dumped)
    $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

My nvidia version is:

    [user ~]$ nvidia-xconfig --version
    nvidia-xconfig:  version 352.63  (buildmeister@swio-display-x64-rhel04-11)  Sat Nov  7 22:00:19 PST 2015


My system information is:

    [user ~]$ uname -a
    Linux my_box 4.2.8-300.fc23.x86_64 #1 SMP Tue Dec 15 16:49:06 UTC 2015
     x86_64 x86_64 x86_64 GNU/Linux

**Comment by showcheap** [comment] 2016-02-20 13:39
@ptimatth : Thanks, it's work for me. 

Fedora 23
NVIDIA Corporation GF116 [GeForce GTX 550 Ti]
Linux fedora-pc 4.2.3-300.fc23.x86_64 #1 SMP Mon Oct 5 15:42:54 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pcreech** [comment] 2016-03-26 16:39
For what it's worth, I ran into this myself, and just resolved it on Fedora 23.

Fedora 23 x86_64
installed nvidia drivers following http://www.if-not-true-then-false.com/2015/fedora-nvidia-guide/
installed steam from http://negativo17.org/steam/

It appears the 32bit nvidia driver isn't installed properly first time around on a new install (due to 32bit libraries not being installed)

All I did, was reinstall the nvidia driver follwing the install guide sections 2.7 - 2.9, and it worked.

**Comment by Nodebuck** [comment] 2016-04-18 00:10
@pcreech Thank you! This worked for me.

**Comment by stedotmartin** [comment] 2016-04-20 21:30
@pcreech Yep worked for me too! thanks. I did notice the first time that the 32bit libs failed but though nothing of it.

**Comment by sjm324** [comment] 2016-05-16 23:20
Did any of you have trouble connecting to the steam servers?  I can connect the first time when it downloads, but then (e.g. if I try and install the beta or just straight restart it) I cannot ever connect.  Running Fedora 23 x64, steam launches offline with nvidia drivers installed no problem.  Running it from the console I get a large amount of bad `ELF` descriptors, mix `ELF32` and `ELF64`.  I'm trying to decide whether this install should be considered successful and there is a firewall issue of sorts (or router, or many others), or if the installation itself is faulty.

**Comment by boltronics** [comment] 2016-06-13 04:29
Woah, I can't believe that actually worked! Just uninstalled fglrx on 14.04, re-installed Steam (in firejail) which worked, re-installed fglrx again... and now Steam starts. Thanks for the tip! Hope Valve can get this bug sorted. Seems to have been around long enough.

**Comment by boltronics** [comment] 2016-06-13 05:02
Woah, I can't believe that actually worked! Just uninstalled fglrx on 14.04, re-installed Steam (in firejail) which worked, re-installed fglrx again... and now Steam starts. Thanks for the tip! Hope Valve can get this bug sorted. Seems to have been around long enough.

**Comment by RustyRaptor** [comment] 2017-04-21 06:14
This is a really silly issue. It's really a hassle after completely installing the driver from the website to have to go back to nouveau and then do the process all over again. Please fix this it's an embarrassment especially when the nouveau drivers will cause some desktops to lag entirely. GeForce GTX 1060 6GB here with this issue.

**Comment by svenevs** [comment] 2017-04-21 07:09
@RustyRaptor the reverting back to open source drivers is only for the installation of Steam, you should be able to reinstall the NVIDIA drivers afterward.

On fedora specifically, as @pcreech said, try using the Negativo rpm's.  Negativo is amazing, the number of things they've packaged that just work is fantastic, and the easiest solution.  The following may help if you cannot get those to work, good luck!

If you're having trouble starting your Desktop because you need the proprietary drivers to launch, advise using simple graphics to perform the installation.  You do this by editing the boot parameters one time.  For example, if you had to install nvidia drivers, then you likely ended up adding `rd.driver.blacklist=nouveau` in order to make sure it is not used.  When you boot, the `vmlinuz` line should be edited (hit the `E` key when `grub` starts up on the kernel version you want to edit for this boot only), the boot parameter you want to add is `nomodeset` to use "simple" graphics (in addition to getting rid of the blacklist).  This should be all you need to bypass your Desktop Manager not booting, which should let you install Steam.

E.g. on Fedora the steps would roughly be

1. Uninstall nvidia driver.
2. Make sure you have `nouveau` installed still (if-not-true-then-false is great, they tell you to uninstall it for a reason, but you may need it back first!)
3. Reboot and edit boot parameters to boot into simple graphics mode.
4. Install steam.
5. Reboot / switch to run level 3 and reinstall the Nvidia drivers.
6. Reboot again and my understanding of the discussion above is that you now have Steam and nvidia drivers playing well with one another.

The above should be successful in minimal work necessary, you shouldn't need to recompile `initramfs` or use `dracut` or anything like that.  Just make sure you temporarily install `nouveau`, un blacklist the open source driver and boot with simple graphics, install, reinstall, done.  Then the blacklist of `nouveau` should still be there the next time you boot.

There's [some nice pictures](https://wiki.ubuntu.com/Kernel/KernelBootParameters) that show what the menu you're looking for to edit boot parameters will mostly look like.

Fixing it is unlikely simple, though.  Unlike DirectX for Windows, or OpenGL for OSX, there are significantly fewer standards / common practices with OpenGL and Linux.  It basically amounts to instead of one company controlling the standards, you now have the open source community, AMD, and NVIDIA.  They all generally do the same thing (OpenGL specification is controlled by another party that all of these entities collaborate with / help shape it), but they are inconsistent enough that bugs like this one can be challenging to root out.  If they threw enough engineers at it they could, but Linux isn't nearly as profitable :/

**Comment by lostinblue** [comment] 2017-05-03 01:24
Profitability can not be the only thing to measure by, that path is suicide. I'm having this issue as well.

**Comment by kisak-valve** [comment] 2017-11-24 16:13
I'm going to go ahead and close this issue because there's nothing specifically actionable here.

The general idea is that Steam is a 32 bit opengl application and it needs a sane, working opengl implementation in order to run. It's up to the package maintainers of individual distros to ensure that something usable is provided. A 32 bit build of glxinfo should be sufficient to check opengl.

Some 64 bit distros do not install the 32 bit variants of needed opengl libraries by default. Reach out to your distro's community if you need help checking.

Specific to nvidia, the running nvidia kernel module must match the 32 bit userspace version, so a reboot is often needed to start steam after updating the nvidia proprietary driver. If libglvnd is being used by the distro, this may hide that the 32 bit nvidia library package is not installed.

New mesa users may also need to use something similar to `LD_PRELOAD=libstdc++.so.6 LIBGL_DRI3_DISABLE=1 steam` in a terminal for the first run because there are some libraries in the bootstrapper runtime that are incompatible with newer mesa (this is being tracked at #4816). This specific workaround should only be needed on the first run of Steam.

***

If you have a sane 32 bit opengl implementation and support opengl 2, then the issue should be investigated on a per-distro and video driver vendor basis.

**Closed by kisak-valve** 2017-11-24 16:13 UTC
Labels: NVIDIA drivers, reviewed
