### ISSUE TITLE
Steam keeps losing connection to its servers

### ISSUE THREAD

**Issue by therealfarfetchd** [ValveSoftware/steam-for-linux#5200] opened 2017-10-08 17:21 UTC
Recently, Steam has been losing the connection to it's servers. Only way to fix it is to restart it, which makes it disconnect again later (usually something like 30 min - 2 hours, I think).

 The effects of this include:
 - Getting logged out from the community page, trying to log back in fails with "There was an error communicating with the Steam servers. Please try again later."
 - Getting kicked from online games (TF2, specifically) because "A connection to the VAC service couldn't be made" or something along those lines
 - Appearing as offline for friends, but no indication of that on my side, it just keeps whatever friends were online at the time of disconnecting
 - Sending messages to friends does nothing

What I've done so far to try to work around it:
 - Switch from DHCP to static connection.
 - Reinstall OS
 - Reinstall Steam
 - Switch to Steam Beta

The error persists, though.
Using Arch Linux x64.

**Comment by kisak-valve** [comment] 2017-10-08 19:52
Possible duplicate of #5133 / #5163.

**Comment by Fretlon** [comment] 2017-10-16 19:01
This started happening to me several weeks ago as well. I can get through 1 to 2 matches of CSGO then I get kicked with a message saying VAC can't verify my computer. Fresh installs of Linux, CSGO files verified, etc. No change. It was working great until the last few weeks.

**Comment by koniiiik** [comment] 2017-12-08 19:27
I can also confirm that this is an issue. I don't usually play CSGO, but I still keep experiencing the issues with losing the authenticated session, and having to restart Steam in order to access the community, or create a party in Rocket League.

I have what appears to be an almost 100% successful way to reproduce this – make Steam lose its connection to the server. It can be by suspending/resuming the computer, or just disconnecting and reconnecting to the wifi.

I'm running Gentoo on amd64, by the way.

**Comment by aazaya** [comment] 2017-12-11 11:01
![steam](https://user-images.githubusercontent.com/13797637/33828056-6a4179ce-de62-11e7-9d58-e3e98630471f.png)

this happens everytime i dc or suspend my computer. I get dc everytime

**Comment by dnaod** [comment] 2017-12-25 22:05
I've had this issue for months.  Ubuntu Gnome 17.10 (and 17.04).  After idling for variable amounts of time, the above screenshot is displayed for any action involving your account.  The client must be closed and reopened.

**Comment by Ruedii** [comment] 2018-04-28 17:57
I tend not to get issues midgame, but I get issues after suspend cycles or extremely long periods of inactivity.

If a game is running it doesn't log out on me.

The desired behavior should be for the client to switch to away unless another computer login is detected.  (Mobile logins should not count, obviously).

If there is a session timeout Steam should attempt 3 times to ping/syn the Steam servers, and connect if it can contact them, otherwise it should sleep it's connect for a specified wait period (5 minutes is good) then try again.  

Steam should check for network events from standard desktop environments and attempt to reconnect after network changes.

Other desktop events Steam should attempt the standard methods to check are the screen saver function which should trigger away mode.

**Comment by therealfarfetchd** [comment] 2018-05-18 12:37
I haven't encountered this in a while.

**Comment by nightsky30** [comment] 2018-05-24 23:58
I recently started playing Borderlands 2 and am getting disconnected from the 4 player matches after short periods of time.  It takes me back to the main menu in game.  If I try and locate available games through the matchmaking functionality after the disconnect, matches will not appear again unless I minimize the game and do something to poke my Steam connection back to life...Such as go to the store page in the steam client.  If I do that, then maximize the game again, it will suddenly be able to find matches.

There is no need to restart the game or the Steam client.  I just have to force the Steam connection to reestablish by making some traffic from within the client.  I also noticed that the Borderlands 2 Network Option had switched from Public to LAN.  This was probably automatically done due to the Steam connection going dormant/stale.

I am using the latest Steam Client Beta.  Are there network logs I could provide to show when the connection decides to sleep?

**Comment by DevPre24** [comment] 2018-05-26 00:55
I noticed that it seems to disconnect more often when the window is minimized in the system tray. Keeping the window open reduces the rate at which it randomly disconnects.
(Arch Linux KDE + Steam Runtime Beta)

**Comment by therealfarfetchd** [comment] 2018-06-06 13:48
Welp, it just happened again. Nevermind me saying it was fixed

**Comment by DevPre24** [comment] 2018-06-10 11:05
Unplayable, every time that the client loses connection to its servers it disconnects me from the rust server i'm currently playing on.

**Comment by nightsky30** [comment] 2018-06-28 01:49
I'm finding that even if the steam client window is kept open, if the system is left alone for an hour or so (and the system won't sleep now because of another steam issue), the steam session / connection is terminated.  There is no indication that it has died.  It just has.  And if you try and view your own *private* profile, it prevents you from viewing your own profile because your session is dead and it fails to recognize you.  You have to view the Store's Featured page to reestablish the session / connection to view your own profile again.

**Comment by tunanachos** [comment] 2018-07-19 11:03
Any update on this? 

This has been happening for over a **year** and frankly it's a little insulting Steam haven't got to the bottom of this.... 
They don't make games anymore, they hardly make content... How about fixing your buggy, broken Steam client / servers before anything else guys??

**Comment by higuita** [comment] 2018-08-06 22:43
@tunanachos do not be rude, that kind of aggressive wording do not really help and only make companies fear supporting linux (specially after the witcher2 stupid drama)

You may be annoyed with this, but remember that steam IS supporting linux and if this was a easy bug, it would be already solved. Most people do not have any problem and this is probably releated with "not supported" distros and some other issue (bad config? missing or bad lib? security feature triggering something in steam?) 

I do have 3 linux machines (slackware, debian and ubuntu) and only one (slackware) have this... and even that, only recently (since june, somewhere since the new chat was released... but probably just coincidence)

If you do want to have this fixed faster, probably create a VM image with steam where you can replicate this (test also in other ISP connections and host machine) and attach the download URL here, so someone from steam can replicate it and understand what is happening

do not get me wrong, i too want this fixed, but being nice and helpful is more productive than being rude. :)

**Comment by tunanachos** [comment] 2018-08-06 23:13
I'm sorry but what part of my message did you deem rude exactly? It is buggy, it's never really been stable. My opinion, for what it's worth is that you should make sure the tyres are safe before you screw on the breaks..

Putting it differently, I feel Steam should try and get their client sorted before pushing a bunch of stuff people haven't asked for (new chat as of the last few weeks, still a buggy client - case in point).

I wholeheartedly agree with you, you catch more flies with honey than vinegar, however it's a frustrating issue and should be address in a timely manner.

I will look into your suggestion when I'm back home. Honestly I've never used GitHub and find it a little confusing at fist glance (I'm not sure of its purpose) but this is going off topic :)

All the best and thanks for your suggestions, will update if I get around to it.

**Comment by nightsky30** [comment] 2018-08-07 00:44
@higuita I'm running Ubuntu 18.04 and am experiencing the issue sporadically.  Though it did not happen with 17.10, it did also happen with 16.04.  I'd say the cause is pretty random.  Some weeks are ok.  Other weeks it seems like it happens almost daily, and this is on a distro that should be well supported considering its Debian heritage (not saying Ubuntu doesn't have its quirks).

**Comment by higuita** [comment] 2018-08-07 02:50
i just found that using "steam -tcp" makes the login work fine, but after steam started i'm required to login (or simply fails) to try to add to whishlist, view profile, etc

Can you guys check the Steam/logs/connection_log.txt during startup and login and compare it to when it fails, to see if you get anything strange
a `tail -F ~/Steam/logs/connection_log.txt` in a terminal should work. Also start steam from a terminal and check any output message during the problems

@tunanachos your complete last line is rude (even if you didn't intend to be) and could be simply replaced with "please fix this or help us debug the issue, we want to use steam" for a lot better and friendly text :)

**Comment by DevPre24** [comment] 2018-08-07 13:14
@higuita This bug has been out there for months and it's not a small bug, it prevents you from playing most multiplayer games because when steam auth fails it kicks you out of the server game and completely ruins the user experience. @tunanachos  's frustration is comprehensible, steam gets a share of every sale (30% if i remember correctly), we are not asking for the moon, just to be able to play the games which we paid for without getting kicked every ten minutes and having to restart the steam client every time.

**Comment by higuita** [comment] 2018-08-07 22:08
@DevPre24 i never said this is a small bug, i said it is not a easy bug... million of people use steam without any problem... as i said, my own 3 setups, only one have problems. Yes, this is very frustating bug, but it is also hard to reproduce and understand why it's failing

**Comment by higuita** [comment] 2018-08-10 01:56
Can some of you guy with arch try this scripts/commands to see if it helps in this problem?

https://github.com/airvzxf/archLinux-installer-and-setup/blob/master/src/laptop_MSI_GT73EVR_7R_Titan_Pro/05-knowledge/99e-steam-info-errors.sh

**Comment by higuita** [comment] 2018-08-10 02:11
also check this post:

https://steamcommunity.com/app/221410/discussions/0/1474221865193053915/

For slackware, running /usr/sbin/update-ca-certificates fixed my login problems, i had no /etc/ssl/certs/ca-certificates.crt file and running that recreated the file

**Comment by kisak-valve** [comment] 2018-08-13 23:58
Per "Fixed some cases users would not auto-login to Steam web pages inside the Steam Client" in the [2018-08-13](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1706188320728546746) Steam client beta update, please retest this issue.

**Comment by kisak-valve** [comment] 2018-09-14 19:46
Seen when opening inventory from the notification drop down.

**Comment by tunanachos** [comment] 2018-09-15 10:45
@DevPre24 Thank-you for being sympathetic to my irritation.  

This issue has been going on for +1 years and as you said stops you from playing most _(if not all)_ Source MP games..

and to @higuita I don't think pointing out that they don't make games and do a shoddy job of maintaining their client is _'rude'_ as you put it, it's fact. 
I'm sorry if you feel offended or upset by this, but it upsets me too.

Maybe instead of lessons on how to conduct ourselves online can be left until after this +1 years **major** issue is fixed? I've already said sorry, I'm not much sure what else you'd want.

**Comment by ephracis** [comment] 2018-09-29 16:44
I am seeing this as well.

Whenever the computer goes to sleep, Steam will lose its connection and all games I try will fail to connect to their servers. Other apps on the computer can connect fine. Steam (and the games) will start to work again if I logout of Steam and then back in again. But this is really a PITA since I have a 50 character password and use Steam Guard, and my computer goes to sleep between almost EVERY gaming session.

Please let me know if there are any useful logs and other debugging stuff I can do to help narrow down the bug. The issue is very easy for me to replicate.

OS: Fedora 28
Steam API: v018
Steam package versions: 1536436120
Steam built: Sep 8 2018, at 19:21:25

PS: You should really make the text in the about window selectable so it can easily be copy-pasted.

**Comment by nightsky30** [comment] 2018-09-30 13:48
> OS: Fedora 28
> Steam API: v018
> Steam package versions: 1536436120
> Steam built: Sep 8 2018, at 19:21:25
> 
> PS: You should really make the text in the about window selectable so it can easily be copy-pasted.

That about window is very aggravating.  It would be nice to have the same copy/paste functionality that is available with the system information window.  Or better yet, include the steam client info with the system information.

**Comment by Architector4** [comment] 2018-10-03 19:00
Did (my first) fresh install of Ubuntu 18.04 on my laptop about 4 weeks ago. This exact issue began to appear from the first day.
It only happens when my whole computer loses connection(either by suspending or turning off WiFi), but by itself Steam never loses connection.

Here's the Help>System Information text:
https://pastebin.com/DLgncXdi

Here's the Help>About text:
Steam client application
Built: Sep 8 2018, at 19:21:25
Steam API: v018
Steam package versions: 1536436120

(P.S. I actually like having to manually type out things like these :D)

**Comment by krash84** [comment] 2018-11-05 10:35
+1

**Comment by StarterX4** [comment] 2018-11-28 15:01
+1

**Comment by StarterX4** [comment] 2018-12-29 17:53
Fix this f*cking annoying bug! Second time i've got Low Priority in Dota 2 because of this sh*t!

**Comment by wifihero** [comment] 2019-01-04 23:53
So I might have sort of a fix. 

I installed ubuntu a week ago or so and experieced the exact same issue as the OP. Every ~30min or so steam would lose connection leading to a no steam logon  ingame. Really annoying! 

So yesterday I tried installing steam via flatpak, played all evening and zero disconnects. Yay!

**Comment by aldafu** [comment] 2019-01-25 14:01
One more observation, if I got "Activity" or "Market" Steam will try to re-login. Sometimes it will work and sometimes it will fail and a Steam restart is the only way out. 

As others have said, this is really annoying especially since you get kicked from e.g. CS:GO competitive matches and the like.

**Comment by krash84** [comment] 2019-01-25 14:12
On Linux I have a workaround for this: shutdown steam app before launching the game.

**Comment by f3ck4r** [comment] 2019-04-10 05:57
I just got disconnected 12 times playing dota.
at least i could go back to the match!

wtf is going on?

OS: ArchLinux - Current Release: 2019.04.01
Steam API: v018
Steam package versions: 1554351903
Steam built: Apr 4 2019, at 03:18:17

**Comment by h1z1** [comment] 2019-04-10 10:44
This may have to do with IP changes on some of Valve/Steam's servers (api.steampowered.com for example).  At least I've noticed that sessions will not always persist across akamai especially when you end up getting different datacenters.

**Comment by Ketchup901** [comment] 2019-04-16 08:01
Getting this. Arch Linux.

**Comment by pqueiroga** [comment] 2019-05-26 03:51
Getting this on ubuntu 18.

**Comment by pjf-valve** [comment] 2019-05-27 20:14
@pqueiroga (and others): Any chance you can test this with the current beta client if you're not already on it? There are some fixes in that for #474, and while I think this is a separate issue, we may have also gotten lucky.

**Comment by tunanachos** [comment] 2019-05-27 21:05
Hi I'm not sure if this will be useful but it can't hurt to mention.

Just the other day I attempted to play Gmod and was met with this issue again (the client losing connection to the Steam servers) and I'm sure resetting Steam does fix the issue but this issue was arising everytime I attempted to join a community server.

Is the solution really just to reset Steam? Or has there been a recent update on the past few days? 

Kind regards

**Comment by pjf-valve** [comment] 2019-05-27 21:18
@tunanachos : The current beta (which shipped a week or two ago) contains a linux-specific networking fix for when Steam could take an reasonably long time to realise that a network connection had died.

That fix wasn't specifically targeting this issue, and so I don't *think* it will help, but if we're seeing disconnects because Steam is holding onto an old connection, then it potentially could.

**Comment by pqueiroga** [comment] 2019-05-28 14:41
@pjf-valve : I was not opting in to beta, but I opted yesterday.

Since then, I've been noticing a lot more disconnects. But it reconnects alone, and, excluding the first time, it does it quite quickly. I don't need to restart steam anymore.

**Comment by tunanachos** [comment] 2019-05-30 18:31
While I've only been able to test this for a few minutes today I was not met with a black community server list after previously playing on a server - this in itself is already a massive improvement.

**Comment by kisak-valve** [comment] 2019-07-05 19:28
Closing as fixed in the [2019-06-13](https://store.steampowered.com/news/51761/) Steam client update.

**Closed by kisak-valve** 2019-07-05 19:28 UTC
Labels: Need Retest, Steam client

**Comment by callec** [comment] 2019-07-17 14:21
I keep getting 'Disconnected by VAC: You cannot play on secure servers' while playing TF2 or Counter Strike Source. Using 4.19.52-gentoo and steam beta, not sure if this issue is the problem though. Is there any log where I could see what's causing this?

**Comment by kisak-valve** [comment] 2019-07-17 14:24
Hello @callec, you're using a kernel affected by #6326. Please retest with 4.19.55 or newer.
