### ISSUE TITLE
Steam Runtime Soldier breaks Steering wheel support

### ISSUE THREAD

**Issue by yacinbm** [ValveSoftware/steam-for-linux#9333] opened 2023-04-09 12:57 UTC
#### Your system information

* Steam client version (build number or date): Mar 24 2023, at 17:20:43
* Distribution (e.g. Ubuntu): Steam OS 3.4.6 (Steam Deck)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I recently bought Assetto Corsa (ID 244210) and a T300RS steering wheel to play on my Steam Deck. After installing the T300RS Linux drivers ([hid-tmff2](https://github.com/Kimplul/hid-tmff2)) and verifying that the wheel works properly using `evtest` and `oversteer`, I tried configuring my game to work with it.

Unfortunately, I could only get the game to see the wheel, but no inputs (steering, pedals or buttons) were recognized. During my testing, I did the following:
1. Created a udev rule to make sure the all users have r/w access to the device (confirmed working with the following)
```
$ ls -al /dev/hidraw4
   crw-rw-rw-+ 1 root root 240, 4 Apr  9 08:14 /dev/hidraw4
```
2. Launched `path/to/my/Proton/files/bin/wine control joy.cpl` which shows all the input devices available to wine. Under the _Test Joystick_ tab, notice the inputs from the wheel are correctly recognized as expected. 
3. Launched `protontricks -c "wine control joy.cpl" 244210`, and noticed that the applet did not register inputs anymore (Proton tricks uses the SteamRuntime and the proton prefix for the specified game ID)
4. Set the `PROTON_DUMP_DEBUG_COMMANDS=1` launch argument for my game in Steam to generate the `/tmp/proton_deck` folder structure, which allows the game to be launched without the SteamRuntime Soldier.
5. Launched the game using `/tmp/proton_deck/run` and noticed that **the steering wheel works as intended**. 
6. Launched the game using `path/to/my/steam/steamapps/SteamLinuxRuntime_soldier/run /tmp/proton_deck/run` in order to launch the game with Steam Runtime, and noticed that **the game did not recognize the wheel anymore**. 

This seems to lead to SteamRuntime Soldier modifying something that leads to the wheel not being recognized anymore. 

#### Steps for reproducing this issue:

1. Install a game (Assetto Corsa in this case) using Proton > 5.13 (the issue was not present for some reason in older versions of Proton).
2. Launch the game and try to assign key bindings to your wheel.
3. Notice that any input to the wheel is not recognized.

Let me know if you need me to post some more logs, do some more tests. 
Cheers!

**Comment by kisak-valve** [comment] 2023-04-09 13:09
Hello @yacinbm, this is now the third issue report for the same issue. Fragmenting the discussion across multiple issue tracker is not productive. If you think an issue report should be transferred to a different issue tracker, then please give me a ping asking for that and explain why it should be done.

Please do not intentionally open duplicate issue reports.

Closing as a duplicate of https://github.com/ValveSoftware/Proton/issues/6674.

**Closed by kisak-valve** 2023-04-09 13:09 UTC

**Comment by yacinbm** [comment] 2023-04-09 13:11
Sorry about that, I did not realize these were the same Projects. I actually tried to delete the issue after seeing your answer on my other post. Won't happen again.
