### ISSUE TITLE
Steam is restarting network interfaces without user consent

### ISSUE THREAD

**Issue by arfett** [ValveSoftware/steam-for-linux#3424] opened 2014-08-10 18:44 UTC
I have Wi-Fi disabled on my laptop when I am home as I use an ethernet connection. When the Steam client is started it enables Wi-Fi which is undesirable behavior in my network.

The Steam client should not be enabling/disabling network interfaces automatically at any time without user consent; it is a digital game distribution service... not Network Manager.

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x10
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2300 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 17 Qiana (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-32-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release_2014-07-22

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 7660G

```
Driver Version:  4.3.12798 Compatibility Profile Context 13.35.1005
OpenGL Version: 4.3
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x6840
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.54" x 7.60"  (15.51" diag)
                                        34.4cm x 19.3cm  (39.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  5363 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  121925 Mb
    Largest Free Hard Disk Block:  89801 Mb

Installed software:

Recent Failure Reports:

**Comment by Suros** [comment] 2015-01-12 10:58
I'm starting to wonder if Valve even cares about this issue. It's been going on for at least 4 months and I haven't seen any form of acknowledgement of it. This wasn't even an issue when I started using the Linux client last summer.

**Comment by Captain-Chaos** [comment] 2015-01-12 11:04
Well there is someone saying "ok we'll take a look!" a few comments above. I guess that counts as some sort of "acknowledgement", but you're right, it's disappointingly meagre. I had expected better from Valve, both a quicker reaction, and a clear confirmation that this is indeed incorrect behaviour.

**Comment by chelmertz** [comment] 2015-01-16 17:28
Still a problem for steam-1.0.0.49-3.fc20.i686 on Fedora 20 (plug in cable, turn off wifi, start steam, wifi immidiately turned on).

**Comment by isntall** [comment] 2015-01-28 03:41
I'm also having this issue on ArchLinux and GNOME shell.

**Comment by AnAkIn1** [comment] 2015-02-15 22:46
Anything new Scott? Have you been able to find what the issue is?

**Comment by RayfenWindspear** [comment] 2015-02-25 22:15
For those interested, here is a simple fix.
http://github.com/RayfenWindspear/steam-for-linux_wifi-startup-fix

**Comment by AnAkIn1** [comment] 2015-02-26 10:33
Here's another fix I've made by just adding a polkit rule in /etc/polkit-1/rules.d
```
polkit.addRule(function(action, subject) {
  if (action.id.indexOf("org.freedesktop.NetworkManager.") == 0) {
        var filepath = polkit.spawn(["cat", "/proc/"+subject.pid+"/cmdline"]);

        if(polkit.spawn(["basename", filepath]) == "steam\n") {
                return polkit.Result.NO;
        }
 }
});
```

**Comment by RayfenWindspear** [comment] 2015-02-26 13:58
@AnAkIn1 If I understand correctly, that rule disallows Steam to modify the network status at all. That solution is a LOT more elegant than mine! My solution was merely off the top of my head after I recently did the same thing to keep my wifi (and bluetooth) from turning on after waking from sleep.

**Comment by AnAkIn1** [comment] 2015-02-26 14:02
Indeed, it prevents Steam from modifying anything network related :)

**Comment by RayfenWindspear** [comment] 2015-02-26 14:11
I have referred to your solution on my repo in the form of a link so people know there is a better solution. I am not familiar enough with GitHub's social tools to know if that is the best way or not.

**Comment by g0hww** [comment] 2015-02-26 19:57
@AnAkIn1  I've never noticed polkit before and decided to have a go with your solution, but I'm unable to produce any effect at all by placing your code in the file 
 /etc/polkit-1/rules.d/50-org.freedesktop.NetworkManager.rules
on my Ubuntu 14.04 box and running steam.  I've added some polkit.log() calls but have never seen anything related appear in /var/log/auth.log which is where other polkit stuff appears.  I've read a bit about polkit but so far I am stumped as to why it isn't having any effect.  I've tried making the rule file executable in case that helped, but no luck there. I've also tried moving the file to
 /usr/share/polkit-1/rules.d/
but that also had no effect.   I wonder if you can offer this idiot some clues.  Cheers.

**Comment by AnAkIn1** [comment] 2015-02-26 19:59
Did that file already exist? You need to create a different file, not use an already existing one. I've called mine 99-networkmanager-steam.rules, IIRC files starting by the highest numbers are parsed first.

**Comment by g0hww** [comment] 2015-02-26 20:08
Nope, actually, the /etc/polkit-1/rules.d directory didn't even exist, so that was created and the file was created with your content.  Perhaps the fact that the /et/polkit-1/rules.d dir didn't exist is some kind of clue.  The only pre-existing file in a polkit-1/rules.d dir is this one:
/usr/share/polkit-1/rules.d/unity-control-center.rules
but as I've said, I've tried moving the new rules file into that dir already, and it still has no discernible effect.

**Comment by AnAkIn1** [comment] 2015-02-26 20:13
It didn't exist? Well that's weird, maybe the directory is different on Ubuntu, I have no idea which one it would be. I'm on ArchLinux.

**Comment by g0hww** [comment] 2015-02-26 20:17
There was other polkit stuff in /etc, just not a rules.d dir.  Here's what that tree looks like now with the new file added:

/etc/polkit-1/
├── localauthority
│   ├── 10-vendor.d
│   ├── 20-org.d
│   ├── 30-site.d
│   ├── 50-local.d
│   └── 90-mandatory.d
├── localauthority.conf.d
│   ├── 50-localauthority.conf
│   └── 51-ubuntu-admin.conf
├── nullbackend.conf.d
│   └── 50-nullbackend.conf
└── rules.d
    └── 50-org.freedesktop.NetworkManager.rules

**Comment by AnAkIn1** [comment] 2015-02-26 20:19
According to that tree 50-org.freedesktop.NetworkManager.rules is not inside rules.d, it should be.
Anyway I guess you could try putting it into localauthority.conf.d or localauthority instead as this is what Ubuntu seems to use.

**Comment by g0hww** [comment] 2015-02-26 20:33
@AnAkIn1 Still no joy with the getting the polkit rule to work for me, I'm going to give up for now.  I like the idea though, thanks for sharing. If anyone does figure it out on Ubuntu 14.04 please give further clues.

**Comment by Mihara** [comment] 2015-02-26 20:40
Confirming that I've had success on Ubuntu 14.04 by placing the said snippet into `/usr/share/polkit-1/rules.d/steam.rules` -- much thanks, @AnAkIn1, you've saved me more than a few hairs.

`/etc/polkit-1/rules.d` does not normally exist in Ubuntu and placing a script there does not work.

**Comment by RayfenWindspear** [comment] 2015-02-27 00:54
The issue is this, though it looks correct to me.
Could not open policy file: /etc/polkit-1/rules.d/steam.rules: sun.securty.provider.PolicyParser$ParsingException: line 1: expected [;], found [polkit.addRule]

Looks like you can test the .rules file by running <code>policytool</code> and opening the file from the file menu.

**Comment by RayfenWindspear** [comment] 2015-02-27 00:56
I get the same error trying out any of the example scripts located here: http://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html

**Comment by RayfenWindspear** [comment] 2015-02-27 01:13
I am a little confused here. Ubuntu 14.04 doesn't seem to have polkitd at all. A search through installed packages listed these relating to polkit.

policykit-1
policykit-1-gnome
policykit-desktop-privileges
libpolkit-agent-1-0:amd64
libpolkit-backend-1-0:amd64
libpolkit-gobject-1-0:amd64

There is however a polkit-kde-1 package that is not installed. I am guessing that installing it would purge the gnome version.

**Comment by RayfenWindspear** [comment] 2015-02-27 01:33
Wow, I am on one today. So pretty much ignore all my comments above. <code>pkexec</code> doesn't do what I thought it did. And <code>ps</code> confirms <code>polkitd</code> is running.

**Comment by 88weighed** [comment] 2015-02-27 08:37
Tried to go for AnAkin1's solution with Mihara's file location, but I'm afraid that's no solution on Kubuntu 14.04.

**Comment by hobarrera** [comment] 2015-02-27 23:17
I've the same rule, only that it ocurrs on my desktop and all the access points are test networks, so wireless is networks don't even have internet connection. Steam seems to not-work if I disable it.

It's an awful behaviour to disconfigure a network in these sort os scenarios. If users configured their computer one way, there's probably a reason for it.

I already have to reconfigure my PC to proxy through a tunnel, since Steam doesn't do IPv6 by itself, now it won't even work because it demans wifi access. Doubly unusable.

**Comment by boltronics** [comment] 2015-02-28 04:11
I'm running Steam on Debian Wheezy (amd64), and I was unable to get the work-around @AnAkIn1 posted working. Like other people running Ubuntu, I did not have a pre-existing /etc/polkit-1/rules.d directory, but I do have a /usr/share/polkit-1/rules.d/. Unfortunately the code didn't work from either of these locations.

In the end, I crated a solution based on the idea posted by @RayfenWindspear - the main difference being that I backgrounded steam execution (```steam &```), and added a sleep of 5 seconds before the rfkill command. That way, I can still use my Ethernet connection for copying files over my LAN when Steam is running.

I can't believe Steam is too serious about GNU/Linux when it takes this long for them to provide what should be a simple fix.

**Comment by RayfenWindspear** [comment] 2015-02-28 17:00
That was my original solution, but I wanted to add the extra effort to have it check to see if wifi was already on and leave it if it was. Originally I wrote it so that I could fork and submit a pull request, until I realized that there isn't any code here. It is just a hub for issues :(

**Comment by boltronics** [comment] 2015-03-01 00:00
@RayfenWindspear I left the check in place too. There are rare occasions I might actually want or need to be on Wifi, so don't want it to disconnect in those situations.

**Comment by chrylis** [comment] 2015-03-01 15:31
The polkit rule works great for me on Arch. Thanks to @AnAkIn1; Lennartix is getting so convoluted I'm often not sure where to start looking to troubleshoot.

**Comment by RayfenWindspear** [comment] 2015-03-03 19:27
A brief heads up for anyone using my fix. Switching Steam from offline to online mode doesn't invoke the script <code>/usr/bin/steam</code> so it will switch on your wifi. It seems that going from online to offline doesn't have a problem, even though it also doesn't run the script again.

@scottlu Switching from online to offline might be where devs will want to look to see an example of it NOT enabling wifi on startup. The PID for <code>/usr/bin/steam</code> doesn't change, so I assume it isn't being run again during the switch.

**Comment by xhsdf** [comment] 2015-04-03 09:11
This was finally fixed in yesterday's Steam Beta update!

**Comment by g0hww** [comment] 2015-04-03 09:14
No it wasn't.  It's still firing up my wlano interface!

**Comment by xhsdf** [comment] 2015-04-03 09:15
That's strange...
Works for me now (Arch).

**Comment by g0hww** [comment] 2015-04-03 09:22
Odd indeed. I'm on Ubuntu 14.04 x86_64.  I suppose neither of us are using an officially  supported distro, but still, wtf are Valve playing at with this.

**Comment by g2p** [comment] 2015-04-04 00:50
Works for me, that's great.

**[Announcement](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/230022562793283749)**
> Fixed bug that would enable all WiFi interfaces whenever the desktop Steam Client was re-launched

**Tsouki™**
> how the fuck did that happened in the first place
> seriously
> why

**henryg [VALVᴱ]**
> Tsouki™ - this was intentional behavior for SteamOS mode, where it has additional networking configuration options in Big Picture mode to control your WiFi connections. It was mistakenly enabled for all Linux builds instead of only SteamOS.

**Comment by hobarrera** [comment] 2015-04-09 17:45
Fixed for me. I think it's safe to close this issue.

**Comment by g0hww** [comment] 2015-04-09 18:32
Oh. Nobody said that the fix was in a beta version 6 days ago.  it isn't fixed while the fix is stilll in beta! I guess I'll wait for the fix to make it into the main branch.

**Comment by xhsdf** [comment] 2015-04-09 18:34
"Oh. Nobody said that the fix was in a beta version"
Well, except for me...

**Comment by g0hww** [comment] 2015-04-09 18:58
D'oh!

**Comment by bjwest** [comment] 2015-04-09 20:50
Just got the latest client update (Apr 9, 2015) and WiFi remains off like it should for me.

**Comment by mdmower** [comment] 2015-04-09 20:59
I concur. Just requested a client update from _Steam > Check for Steam Client Updates..._ (not beta), and after a closing and restarting the client, Wi-Fi remained off.  Ubuntu 14.10 64bit.

**Comment by RayfenWindspear** [comment] 2015-04-10 17:22
Mine seems to be fine as well.

**Comment by boltronics** [comment] 2015-04-11 13:52
Fixed here (Debian Wheezy amd64, Steam main branch).

**Comment by ikselven** [comment] 2015-04-13 18:05
Fixed for me, too (Arch x86_64). Though I had to manually trigger the search for new updates from within Steam.

**Comment by 88weighed** [comment] 2015-04-14 07:44
Fixed. Kubuntu 14.04.2

**Comment by buxit** [comment] 2015-07-02 06:56
@scottlu don't you want to close this bug. it was obviously fixed.

**Comment by not83** [comment] 2016-01-09 02:07
Could someone please close this gub report. Many people have been reporting that it works.

**Closed** 2017-02-13 07:44 UTC
Labels: reviewed, Steam client
