### ISSUE TITLE
Dota2 Reborn doesn't start

### ISSUE THREAD

**Issue by Shelvak** [ValveSoftware/steam-for-linux#3906] opened 2015-06-25 02:43 UTC
I try to start Dota2 reborn from Arch linux and never start, i have black-screen and then the desktop is back

Here the info: 
- [Steam console log with font-error](https://gist.github.com/Shelvak/1890764774c0e71f0e42)
- [Steam console.log with font-fix -delete multiple line and install Bitstream font](https://gist.github.com/Shelvak/6c079d95c40b3039fe21)
- [Steam full console.log - from start and finish steam- ](https://gist.github.com/Shelvak/b8e1985e61f233c05cca)
- [Steam system info](https://gist.github.com/Shelvak/5956976f36d6c414047a)

I try reinstalling steam, reinstalling a few libs (gtk, fonts, a few libs but nothing) i'm using catalyst-total from aur.

Anything that you need, ask :+1:

**Comment by gdrewb-valve** [comment] 2015-06-25 03:18
Please report Reborn issues in the Dota-2-Reborn repo.  In this particular case it's a duplicate of item 10, your CPU doesn't support SSSE3 and Reborn uses it.  An update will fix this soon.

**Closed by gdrewb-valve** 2015-06-25 03:18 UTC
Labels: duplicate, reviewed

**Comment by Shelvak** [comment] 2015-06-25 14:07
Ok, thank you so much man! I want the fix :)
