### ISSUE TITLE
Big Picture Overlay freezes when configuring SteamController in Game

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#5273] opened 2017-12-05 19:41 UTC
#### Your system information

* Steam client version (build number or date): Dec 1 2017
* Distribution (e.g. Ubuntu): Solus 3.26.2
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

Steam system information: https://gist.github.com/ph0ec/b04f73c8b491deeca9a547a9992cff67

#### Please describe your issue in as much detail as possible:

When I'm configuring my steamcontroller in Big Picture Overlay mid game (tested with Mad Max, Hitman, Torchlight2, Shadow of Mordor), after a couple of tries the overlay freezes in the configuration screen, sometimes immediately, sometimes later. I can go back to the game and play without problems. I also can go back to overlay, but this brings back the frozen configuration screen. If i try to navigate, i can hear the menu soundeffects, but the screen doesn't react. After I close the game, steam isn't reacting.
(had the same issue on Ubuntu Budgie 17.10 and also on Solus without Beta Opt-in)

file in /tmp/dumps/
https://gist.github.com/ph0ec/d06aa9e3045d34b689375ddc9bb11b06

#### Steps for reproducing this issue:

1. open Big Picture Mode
2. start a game
3. open overlay
4. change configuration of steam controller
5. try the configuration
6. repeat 3-5 until freeze

**Comment by kisak-valve** [comment] 2017-12-05 20:01
Hello @ph0ec, this sounds like a Big Picture overlay variant of #4933.

You should at least be able to unfreeze the game by sending SIGSTOP and SIGCONT to it when it's frozen, and it's likely the overlay is unusable after that workaround.

**Comment by ph0ec** [comment] 2017-12-05 20:12
Hello, 
yes, sound familiar, but the game runs fine, even after the freeze, it's just the overlay. Or did you mean i should stop and restart the steam process?

**Comment by ph0ec** [comment] 2017-12-05 21:00
So, i reproduced the issue and tried to SIGSTOP and SIGCONT the game, nothing changed, but then i tried the same with Steam and after that Big Picture was working again.

**Comment by ajnieminen** [comment] 2018-02-24 10:37
Is there even a temporary fix? this is quite annoying.

**Comment by kisak-valve** [comment] 2020-04-17 13:24
Closing because the reporting user has turning into a ghost and this appears to have been resolved some time ago (https://github.com/ValveSoftware/steam-for-linux/issues/4933#issuecomment-394346435).

**Closed by kisak-valve** 2020-04-17 13:24 UTC
Labels: Big Picture, overlay
