### ISSUE TITLE
Mouse buttons don't work as PTT keys, always transmits voice.

### ISSUE THREAD

**Issue by yash1610** [ValveSoftware/steam-for-linux#4847] opened 2017-02-05 15:38 UTC
#### Your system information

* Steam client version (build number or date): Jan 19 2017, at 1:23:20
* Distribution (e.g. Ubuntu): Arch Linux x86_64
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

Using the side mouse buttons(Mouse button 4 and 5, also doesn't work with Left mouse and right mouse buttons) as the Push-to-Talk key for steam voice chat continuously transmits voice even when the button is not held, basically it works as though if I wasn't using PTT at all and had set the settings so that my voice be transmitted all the time.

Although if I use any key(Caps Lock, A, 1. etc etc) on my  keyboard push-to-talk works properly. Mouse buttons(4 and 5 also Left and Right) for PTT works as intended in-game(Dota2 and CS:GO), also works properly in other apps like discord and mumble.

Using libinput 0.23 as the default driver for Razer DeathAdder Chroma with steam runtime disabled

#### Steps for reproducing this issue:

1. Steam Options > Settings > Voice > Set PTT key as any mouse button
2. Voice chat with a friend using steam voice chat and speak without pressing the PTT mouse button, the person on the other side will still be able to hear it.
3.  Even the MIC symbol indicates that your voice is transmitting even when no PTT mouse button held

**Comment by kisak-valve** [comment] 2017-02-05 17:24
Closing as a duplicate of #3900.

**Closed by kisak-valve** 2017-02-05 17:24 UTC
