### ISSUE TITLE
Anomaly Warzone Earth doesn't start 

### ISSUE THREAD

**Issue by damianatorrpm** [ValveSoftware/steam-for-linux#7300] opened 2020-08-02 12:54 UTC
It just goes from "play" to "cancel" to "play"
I tried it as well on a recent system as well on the supported 
by the publisher Ubuntu 12.04, as well as with steam beta and without steam beta
Steam client it's whats latest today.

This issue seems related to a steam runtime update,
either fix or refund it if the game is not working for the platform it has been purchased for.

**Comment by kisak-valve** [comment] 2020-08-02 13:07
Hello @damianatorrpm, you've encountered a long standing game engine bug which is being tracked at #1553.

There's a workaround you can try at https://github.com/ValveSoftware/steam-for-linux/issues/1553#issuecomment-526992224, but beyond that the issue should be reported to the game's dev(s) and it's up to them to fix this issue.

Closing as a duplicate of #1553.

**Closed by kisak-valve** 2020-08-02 13:07 UTC
