### ISSUE TITLE
Steam client: "YOUR WEB BROWSER DOES NOT SUPPORT THE MINIMUM SET OF FEATURES REQUIRED TO WATCH THIS BROADCAST"

### ISSUE THREAD

**Issue by codingthat** [ValveSoftware/steam-for-linux#7066] opened 2020-04-25 06:40 UTC
#### Your system information

* Steam client version (build number or date): Apr 4 (latest, when I check for updates)
* Distribution (e.g. Ubuntu): Linux Mint 19.3
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:

For the LudoNarraCon weekend (still currently on), developer interviews were supposed to be taking place on the Steam store pages of a few dozen games.  When I go to one of them in the Steam client, there's the layout for the dev interview broadcast, but the message "YOUR WEB BROWSER DOES NOT SUPPORT THE MINIMUM SET OF FEATURES REQUIRED TO WATCH THIS BROADCAST":

![image](https://user-images.githubusercontent.com/26723818/80273145-1d3bcf80-86d0-11ea-9589-6bfbafc94e07.png)

Works fine in Firefox though: https://store.steampowered.com/app/992310/Backbone_Prologue/

#### Steps for reproducing this issue:

1. Open Steam client
2. Go to Backbone: Prologue store page (via search, via library, etc.)

**Comment by codingthat** [comment] 2020-04-25 06:47
(If it makes any difference, the Steam client does view the broadcast on the main LudoNarraCon event page OK, although the chat was glitchy and even on very low res the video tended to cut out.  But it loaded, at least.)

**Comment by lucifertdark** [comment] 2020-04-25 07:06
The broadcast is running as intended on the newest Beta client released April23rd with Ubuntu 20.04 & the 440.64 Nvidia drivers.

**Comment by kisak-valve** [comment] 2020-04-25 11:58
Hello @codingthat, please go to `Steam` -> `Settings` -> `Interface` and check that `Enable hardware video decoding, if supported` is enabled. Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Possible duplicate of #6780.

**Comment by codingthat** [comment] 2020-04-27 13:09
Hi @kisak-valve, thanks, I enabled that option and restarted.  It worked!  Thanks!

Sorry for the duplicate.  I did search for the exact phrase of the error beforehand, but #6780 hadn't come up as a result, and I'm not sure why.

Requested gist: https://gist.github.com/codingthat/31103e29a69035533b5dd33015213b52

**Comment by kisak-valve** [comment] 2020-04-27 13:17
Glad to hear you got it working, let's track this issue on the older issue report.

**Closed by kisak-valve** 2020-04-27 13:17 UTC
Labels: Steam client, Web Component
