### ISSUE TITLE
every other pressed key is ignored in overlay of Proton games when ibus is installed

### ISSUE THREAD

**Issue by Rodancoci** [ValveSoftware/steam-for-linux#9325] opened 2023-04-05 02:40 UTC
#### Your system information

* Steam client built Mar 24 2023. Package version 1.0.0.76-1.
* Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam overlay opens and closes without issue for all games I've tried but it's extremely inconvenient to use on games running with Proton, especially to chat, as every other keypress is ignored. This means that, for example, in order to type "1234567890", a key (that will be ignored) will have to be pressed in between inputting each individual character. Otherwise, by naively typing all digits in sequence, only "13579" is actually typed into the chat box.

This only happens when running games with Proton. For example, the issue is not present when running the native Linux version of Celeste. But after forcing the use of the Proton compatibility tool the issue arises. This is seemingly not related to any particular Proton version.

#### Steps for reproducing this issue:

1. Launch a game running with Proton
2. Open a chat window
3. Type a message in the chat box. Notice every other keypress is ignored.

**Edit:**
One thing I forgot to mention in my original comment is that the backspace key does not exhibit the same behavior. It deletes a character every time it's pressed.

**Comment by kisak-valve** [comment] 2023-04-05 12:40
Hello @Rodancoci, it might be interesting to test if setting Celeste's launch options to `FNA3D_FORCE_DRIVER=OpenGL %command%` or `FNA3D_FORCE_DRIVER=Vulkan %command%` has any influence on the Steam overlay's behavior.

**Comment by DonKatsu** [comment] 2023-04-06 00:46
I've been experiencing this for a while now as well on Fedora 37 KDE.  [System Information](https://gist.github.com/DonKatsu/304831d5257e6cc67b57ec515f5e72dd).
Native Project Zomboid's overlay works as expected. Anything running through Proton ignores every other key press.
I tried native Zomboid with either `FNA3D_FORCE_DRIVER=` variable but neither caused the issue.

**Comment by kisak-valve** [comment] 2023-04-06 00:50
For clarity, the intent of the question was to test if a Proton game (or maybe the same with a native Linux game) using OpenGL and Vulkan have differing behavior. `FNA3D_FORCE_DRIVER` is a game engine specific suggestion, not a general setting which any game would listen to.

**Comment by Rodancoci** [comment] 2023-04-09 05:26
https://github.com/ValveSoftware/steam-for-linux/issues/9325#issuecomment-1497421126
Hi, I tried both values for the `FNA3D_FORCE_DRIVER` variable and neither produced any difference.

One thing I forgot to mention in my original comment is that the backspace key does not exhibit the same behavior. It deletes a character every time it's pressed.

**Comment by Alexander-Wilms** [comment] 2023-04-29 17:17
I've experienced this issue for months.

[system_information.txt](https://gist.github.com/Alexander-Wilms/e783d580bbe6976801b900e8b912e364)

I'll test if I encounter it with native games as well.

**Comment by Milliw** [comment] 2023-05-18 13:44
Same issue for me.

**Comment by neckcen** [comment] 2023-06-04 21:53
I believe this is the same issue as https://github.com/ValveSoftware/Proton/issues/6280 (which is filled against proton).

I am still experiencing this bug on Fedora 38 as of today. Beta client or not, any proton version >=6 (including experimental).

**Comment by iodream** [comment] 2023-06-04 21:55
Fixed for me as well, on the beta client. Fedora 38 Kde

**Comment by Milliw** [comment] 2023-06-05 15:29
Still have this issue on regular client. Even with GPU vendor change from Nvidia to AMD meanwhile.
Though tried not on chat window but on the browser/a steam user profile guestbook.

**Comment by TheAnnoyingFruit** [comment] 2023-06-17 00:32
Yep issue is persisting with the latest steam update on fedora 38 with the steam flatpak and rpm.

**Comment by TheAnnoyingFruit** [comment] 2023-08-29 16:02
> I think this issue is only present when using Wayland. Am I wrong?

I’m on wayland

**Comment by nomadfh** [comment] 2023-08-29 17:14
> > I think this issue is only present when using Wayland. Am I wrong?
> 
> I’m on wayland

I can more or less confirm this issue isn't present on xorg and is always present when using Wayland.

**Comment by rconcenia** [comment] 2023-09-06 01:07
> I think this issue is only present when using Wayland. Am I wrong?

I am experiencing the issue on xorg myself

**Comment by Rodancoci** [comment] 2023-09-06 01:08
> I think this issue is only present when using Wayland. Am I wrong?

I'm experiencing the issue on xorg myself

**Comment by TTimo** [comment] 2023-09-22 16:04
This should be fixed in latest beta update.

**Comment by neckcen** [comment] 2023-09-22 20:48
> This should be fixed in latest beta update.

I can confirm that I no longer have the bug when using the latest beta, even after reactivating ibus. Thanks!

**Comment by Willdrick** [comment] 2023-09-26 12:26
+1 confirming that the issue is solved

That being said, accent characters are not working, I don't know if it's a related issue:
for example to produce " á " I'd press the "  ´  " key and then the " a " key, on Steam, the accent key is completely ignored.

**Comment by TTimo** [comment] 2023-09-28 14:41
> That being said, accent characters are not working, I don't know if it's a related issue:
for example to produce " á " I'd press the " ´ " key and then the " a " key, on Steam, the accent key is completely ignored.

This is https://github.com/ValveSoftware/steam-for-linux/issues/2122 - it's not really related. The Steam overlay doesn't support IME.

**Closed by TTimo** 2023-09-28 14:41 UTC
Labels: overlay, Need Retest
