### ISSUE TITLE
New games arriving on Linux don't show up on new releases

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4489] opened 2016-06-11 12:38 UTC
New games arriving on Linux & SteamOS that previously had a Windows/Mac version don’t appear in the new releases list.

**Comment by mastercoms** [comment] 2016-06-11 15:24
I agree that this is a problem, but how will Windows users be affected by this change?

**Comment by k4os77** [comment] 2016-06-11 21:49
Here is the issue, I think:

- With the Linux client, under "Popular New Releases" "Top Sellers" "Upcoming" "Specials", the tag SteamOS + Linux is off, while Windows and Mac OS X are ON.

Steam Devs should just fix the code about this.

**Comment by k4os77** [comment] 2016-06-11 21:56
Here is the issue, I think:

- With the Linux client, under "Popular New Releases" "Top Sellers" "Upcoming" "Specials", the tag SteamOS + Linux is off, while Windows and Mac OS X are ON. 
The code that manages "Narrow by OS" is just inverted.

Steam Devs should just fix the code about this.

**Comment by stqn1** [comment] 2016-06-30 12:33
Yep, it’s been an issue forever. Steam should store separate release dates for each platform and use the good one depending on the OS it is running on.

**Comment by Swiftpaw** [comment] 2016-08-12 16:40
> With the Linux client, under "Popular New Releases" "Top Sellers" "Upcoming" "Specials", the tag SteamOS + Linux is OFF, while Windows and Mac OS X are ON. The code that manages "Narrow by OS" is just inverted.

Yeah this makes the tabbed section at the bottom mostly useless.  Devs, please fix!

**Comment by Swiftpaw** [comment] 2016-08-12 16:44
> Yep, it’s been an issue forever. Steam should store separate release dates for each platform and use the good one depending on the OS it is running on.

Exactly, they just need to add additional release date fields for games so that if it's new on a particular platform, it can show up in the new games sections for that platform.

**Comment by kisak-valve** [comment] 2019-05-24 14:52
Closing as a duplicate of #389.

**Closed by kisak-valve** 2019-05-24 14:52 UTC
Labels: reviewed
