### ISSUE TITLE
Steam client crashes on Wayland because of notifications

### ISSUE THREAD

**Issue by SpidFightFR** [ValveSoftware/steam-for-linux#8693] opened 2022-07-18 18:55 UTC
#### Your system information

* Steam client version (build number or date): 1657838689 (the latest beta update)
* Distribution (e.g. Ubuntu): Archlinux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The steam clients freezes completely on Wayland after a notification pops up on screen.
At first i thought it was because of my controller, but when i disabled the notifications that shows that my controller is connected (on steam), it stopped freezing.
Now the freezes happen when i finish downloading a game for instance, a new notification appears to say that the game has finished downloading, which freezes Steam, so i have to kill the steam processes and start it again.

#### Steps for reproducing this issue:

1. make a notification appear (download, or controller, etc.)
2. the client Freezes completely (only on Wayland)

**Comment by SpidFightFR** [comment] 2022-07-18 19:27
Hello, thanks for your response, here's my [config](https://gist.github.com/SpidFightFR/9074021dac888f3bc910e1f270c65b90).

**Comment by SpidFightFR** [comment] 2022-07-18 19:54
Damn... welp thanks for the help anyways. Should i keep the issue opened ?

**Comment by helldoggo** [comment] 2022-09-25 20:10
select 'System Settings' > 'Display and Monitor' > 'Compositor' click on 'Re-enable OpenGL detection' deselect 'Enable compositor on startup' click 'Apply'

This fixed it for me. My steam quit freezing after startup/notifications

**Comment by SpidFightFR** [comment] 2022-09-25 20:30
Only solution i found that prevented crashes is to click on steam notifications as soon as we see them.

It requires to be fast, but if we click fast enough, it avoids crashes.

**Comment by helldoggo** [comment] 2022-09-25 20:41
This is my first time using the Wayland compositor. Just installed Nobara, was a Pop!OS guy for the longest. So first time using fedora and Wayland, fun times. 😀

**Comment by 20PercentRendered** [comment] 2022-11-20 22:45
For me, after freezing like this, my cursor sometimes turns into a "resize" cursor and if I focus the friends list, it sometimes allows me to "stop" resizing the steam window, which unfreezes the client.

**Comment by Hitsounds** [comment] 2022-12-30 18:35
I have been able to reliably reproduce this on KDE wayland. The download complete notification if not clicked on causes the entire client to freeze.

I have also found the following skin can fix the freezing, which leads me to believe this issue has something to do with the notification animation.
[StopAnimations.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/10325876/StopAnimations.tar.gz)

The relevant files in the skin are 
resource/styles/gameoverlay.styles
```
gameoverlay.styles
{
    include "../../resource/styles/gameoverlay.styles"
}
```
resource/styles/steam.styles
```
steam.styles
{
    include "../../resource/styles/steam.styles"

    colors {
        Notifications.SlideDirection "None"
        Notifications.FadeInTime "0.0"
        Notifications.FadeOutTime "0.0"
    }
}

```

**Comment by SpidFightFR** [comment] 2022-12-30 21:28
@Hitsounds hey, i tried the skin, and it works wonders ! Thanks a lot ! It will do the trick until we have an official solution.

**Comment by kisak-valve** [comment] 2023-01-06 21:47
Steam Client hang on Nvidia KDE Plasma WAYLAND

Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/9075.
@kodatarule posted on 2023-01-06T21:32:22:

#### Your system information
Operating System: EndeavourOS
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.7
Kernel Version: 6.1.2-273-tkg-pds (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5800X3D 8-Core Processor
Memory: 31,3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3070/PCIe/SSE2

* Steam client version (build number or date): latest beta 06.01.2023
* Distribution (e.g. Ubuntu):  EndeavourOS
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
To provide as much details as possible, whenever a notification is triggered(usually bottom right) it would make the client itself to hang(unresponsive completely frozen, clicking anywhere nothing happens). This issue is observed specifically on KDE Plasma under WAYLAND(as it is not present on Gnome Wayland) and NVIDIA gpu, it started since Plasma 5.25(5.24.6 didn't have this issue) and it is still present on Plasma 5.26.5. 
I did open a bug report which indicated that it is either an Nvidia driver issue or that steam github could help out on this.
Original bug report: https://bugs.kde.org/show_bug.cgi?id=462027
Nvidia forums bug report: https://forums.developer.nvidia.com/t/steam-notification-causes-the-client-to-freeze-hang-completely-kde-wayland/236138

Ways to workaround this is to disable notifications or to use big picture(new gamepadui)

#### Steps for reproducing this issue:

1.  Simple notification to show up while the client is running

```Note: it is interesting that while I see the client being frozen in terminal it doesn't indicate any problems or that something went wrong```

**Comment by kodatarule** [comment] 2023-01-07 07:43
> I have been able to reliably reproduce this on KDE wayland. The download complete notification if not clicked on causes the entire client to freeze.
> 
> I have also found the following skin can fix the freezing, which leads me to believe this issue has something to do with the notification animation. [StopAnimations.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/10325876/StopAnimations.tar.gz)
> 
> The relevant files in the skin are resource/styles/gameoverlay.styles
> 
> ```
> gameoverlay.styles
> {
>     include "../../resource/styles/gameoverlay.styles"
> }
> ```
> 
> resource/styles/steam.styles
> 
> ```
> steam.styles
> {
>     include "../../resource/styles/steam.styles"
> 
>     colors {
>         Notifications.SlideDirection "None"
>         Notifications.FadeInTime "0.0"
>         Notifications.FadeOutTime "0.0"
>     }
> }
> ```

I tried this fix, however unfortunately it didn't work for me.

**Comment by RyzenDew** [comment] 2023-01-16 22:45
> Thanks, at this point using Wayland with the NVIDIA proprietary driver doesn't have an established history of being reliable when used together and there's a good chance you're seeing a video driver or Kwin issue.

Correction using kde and nvidia and wayland has proven to be unreliable but gnome is very stable and works very well.

**Comment by kodatarule** [comment] 2023-01-18 19:30
> > Thanks, at this point using Wayland with the NVIDIA proprietary driver doesn't have an established history of being reliable when used together and there's a good chance you're seeing a video driver or Kwin issue.
> 
> Correction using kde and nvidia and wayland has proven to be unreliable but gnome is very stable and works very well.

That is very weird, I tried gnome + nvidia + wayland a few months ago and compared to KDE it was utterly horrible experience, while KDE has been mostly flawless outside of small issues like this one here.
At this point I think the nvidia+wayland experiences vary a lot.

**Comment by ex1tium** [comment] 2023-01-20 19:09
> For me, after freezing like this, my cursor sometimes turns into a "resize" cursor and if I focus the friends list, it sometimes allows me to "stop" resizing the steam window, which unfreezes the client.

I'm having this same issue. Nobara 37, Wayland, KDE.

**Comment by Kangie** [comment] 2023-01-22 01:01
I've been experiencing this on KDE Wayland for months. Why doesn't the steam client just use system notifications at this point anyway?

**System Info**
**Kernel**: `Linux monolith 6.1.2-gentoo--bouncy-mouse #1 SMP PREEMPT_DYNAMIC Thu Jan  5 11:15:04 AEDT 2023 x86_64 AMD Ryzen 9 5950X 16-Core Processor AuthenticAMD GNU/Linux`
**Steam Client**:` Jan 20 2023, 01:38:08`, **API** `v020`
**NVIDIA Info**: `x11-drivers/nvidia-drivers-525.85.05:0/525::gentoo` - using 'Kernel Open'

I note that the steam client is the only application I have that demonstrates this behaviour; no other apps lock up like this on Wayland at **all**.

**Comment by kodatarule** [comment] 2023-01-28 20:02
I did some additional testing, no idea what is happening, however on Gnome,Sway as well as Hyprland such hang does NOT occur. The issue is something specifically with how KDE plasma wayland implementation displays the notification it seems.

**Comment by SimplyCorbett** [comment] 2023-02-04 19:30
I'm having the same issue. Can't provide a gist because on kde wayland it wont let me copy the information from steam.

Running kernel 6.1.9, nvidia driver 525.85.05.

Plasma 5.26.5, frameworks 5.102.0, qt 5.15.8. Latest steam (non-beta) version.

**Comment by thndgonz** [comment] 2023-02-18 09:21
Really hurts to think its been going since july with no resolution near :disappointed: I'm experiencing the same as well. All latest updates. It is a bit maddening that I have ot keep closing my client and re-opening several times a day just to play a title.

**Comment by 20PercentRendered** [comment] 2023-02-18 10:01
I believe [Valve is working on completely reworking the client to not use vgui anymore](https://steamcommunity.com/groups/SteamClientBeta/discussions/3/3710433479207750727/). I'm pretty sure new big picture doesn't use vgui and uses something else instead (using steamwebhelper directly for the windows or maybe panorama). This issue will most likely be fixed if/when that rework comes out. Until then, you can use the new big picture in windowed mode as it doesn't freeze at all.

**Comment by Hasshu** [comment] 2023-03-11 21:50
For what it's worth, [Adwaita-for-Steam](/tkashkin/Adwaita-for-Steam) has fixed the freezing for me.

**Comment by thndgonz** [comment] 2023-03-12 05:00
> For what it's worth, [Adwaita-for-Steam](/tkashkin/Adwaita-for-Steam) has fixed the freezing for me.

Thank you so much this serriously fixed the issue for me on Arch Linux KDE+Waylandc

**Comment by C0rn3j** [comment] 2023-04-24 10:35
The Adwaita theme fixed the notification crash however the UI is still capable of freezing partially based on some other condition, but it is infinitely more rare now.

Am on Arch Linux + Plasma + Nvidia + Wayland + Flatpak.

**Comment by kodatarule** [comment] 2023-05-16 06:37
Just wanted to update, with the latest beta update and the new UI - there are no crashes anymore it seems resolved, at least I cannot reproduce a crash now.

**Comment by kisak-valve** [comment] 2023-07-01 00:00
Closing per the last comment.

**Closed by kisak-valve** 2023-07-01 00:00 UTC
Labels: NVIDIA drivers, Steam client, Window manager, Need Retest, Distro Family: Arch

**Comment by SDD701** [comment] 2024-08-01 06:04
I have exact same issue on qtile wayland now (client is freezing until I kill steamwebhelper process).

**Comment by JohnDoe02** [comment] 2024-09-20 14:29
Another qtile user here, can confirm this issue with up-to-date steam + qtile on arch linux on wayland.
