### ISSUE TITLE
DualSense controller input not going to game

### ISSUE THREAD

**Issue by doublez13** [ValveSoftware/steam-for-linux#7495] opened 2020-11-29 00:58 UTC
#### Your system information

* Steam client version (build number or date):  Nov 26, 2020 (1606355690)
* Distribution (e.g. Ubuntu):  Arch Linux
* Opted into Steam client beta?: [Yes/No]  Yes
* Have you checked for system updates?: [Yes/No]  Yes

#### Please describe your issue in as much detail as possible:

(I've tested this with GTA V and RDR2 using Proton 5.13-2)
The DualSense Controller works great wired and wirelessly in Big Picture Mode, but doesn't get passed into the game. When launching the game, the on screen instructions switch to buttons, so that would imply to me that the game sees the controller, but none of the controls do anything. The game works perfectly with the DualShock 4 controller.

#### Steps for reproducing this issue:

1. Launch Big Picture Mode and verify the DualSense controller is detected
2. Launch GTA V or RDR2 (I would assume other games experience this as well)
3. No controller input.

**Comment by NikoBellicRU** [comment] 2020-11-29 17:22
Same problem here, it works over Bluetooth no problem but wired it's constantly disconnecting and when i enter any game it just doesn't work at all and the light's stay off also, soon as i quit the game it turns right on again. 

At first i thought it was just defective but then it worked wired/wireless with PCSX2 and i played for quite some hours so controller's fine i guess. Not sure if it's the SDL2 stuff that has been implemented / needs to be. . .

https://gist.github.com/NikoBellicRU/5935b61d616c0d1a55fcbb3b4bf7c6c0

**Comment by Settyness** [comment] 2020-11-29 20:48
Since you're running Proton, it sounds like the issue is related to this post? https://github.com/ValveSoftware/steam-for-linux/issues/7473#issuecomment-734518898

I am, however, having a similar problem on the Linux-native game Retro City Rampage. The DualSense works fine over Proton, but because the game has glaring sound issues over Proton, I insist on play native. The game refuses to recognize controller inputs past the first screen, regardless of Steam Input Per-Game Setting. I'm uncertain if this is something on the game's end or if this should be working at this point.

**Comment by NikoBellicRU** [comment] 2020-11-30 12:59
> Since you're running Proton, it sounds like the issue is related to this post? [#7473 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/7473#issuecomment-734518898)
> 
> I am, however, having a similar problem on the Linux-native game Retro City Rampage. The DualSense works fine over Proton, but because the game has glaring sound issues over Proton, I insist on play native. The game refuses to recognize controller inputs past the first screen, regardless of Steam Input Per-Game Setting. I'm uncertain if this is something on the game's end or if this should be working at this point.

I also tried left 4 dead 2 wich is native the steam for linux container it did work for a bit but then just turned off like the ones on proton, i been playing them with bluetooth and been working fine, the problem is just wired and i noticed that it also keeps disconnecting / turning off when i'm watching videos on youtube in bpm and when i exit it turns on again.

**Comment by doublez13** [comment] 2020-12-03 21:09
This is working perfectly now in the December 3rd beta. Thank you guys so muuuuuuuuch!!!

**Comment by NikoBellicRU** [comment] 2020-12-04 18:01
Ok so now it even turns off in big picture and it's also freezing steam some times when i plug the usb, i uploaded a video sorry kinda dark :/

https://www.youtube.com/watch?v=QQEzUTcfJuQ&feature=youtu.be

Also everything is in the beta

**Comment by doublez13** [comment] 2020-12-04 18:10
What do your systems logs look like as the controller is reconnecting? 
I assume you're running with the updated udev rules?

**Comment by NikoBellicRU** [comment] 2020-12-04 18:23
> What do your systems logs look like as the controller is reconnecting?
> I assume you're running with the updated udev rules?
I'm not really into that, what logs?
When i open steam with terminal after disconecting just says this " Controller device closed after hid_read failure "

**Comment by doublez13** [comment] 2020-12-04 18:31
Exit steam
Open a terminal and run `sudo journalctl -f`
Plug your controller in
Open steam

**Comment by NikoBellicRU** [comment] 2020-12-04 18:58
I'm trying on pop os now and i get the same as manjaro, with that command i get that
![Screenshot from 2020-12-04 18-56-17](https://user-images.githubusercontent.com/50124155/101203482-a2259900-3662-11eb-8482-5ca917e6f52d.png)

**Comment by NikoBellicRU** [comment] 2020-12-05 17:35
Ok so today just to be sure i went to get a replacement controller cause it still had warranty and the problem persisted but i found out that aparently my psu was like at the limit and couldn't even keep the controller on for long. . .
I noticed this cause it would turn off on a high loads, anyway new psu and the problem is solved and even the mic is working now.

Thank's for the help  :+1:

**Comment by ncoder-1** [comment] 2020-12-08 21:14
I'm running the latest Steam (build Dec 7 2020, API v020, package version 1607372145) on Arch and ironically, with the  "Support for PS5 Controller" update, it actually has stopped all native Linux games from getting controller input.

For example, Dead Cells was working fine prior to the update with the DualSense controller in "Generic Gamepad" mode and now, ever since Steam sees the controller as a PS5 Controller, with "Playstation Configuration Support" enabled or not, no input makes it to the game.  Same with Vector and Jupiter Hell.  That said, games that use Proton, such as Hades or The Witcher 3, work properly...

**Comment by kisak-valve** [comment] 2021-01-15 15:14
Closing because it appears the issue in the opening post has been resolved.

Hello @ncoder-1, please open a new issue report for your follow up issue.

**Closed by kisak-valve** 2021-01-15 15:14 UTC
Labels: General controller / Steam Input, Need Retest, runtime
