### ISSUE TITLE
Stuck at "Loading user data" (on OpenSUSE TW with X11) when running `.desktop` file; works from terminal.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ValveSoftware/steam-for-linux#10072] opened 2023-09-18 15:54 UTC
#### Your system information

<table><tr>
	<th>Steam client version</th>
	<td><div class="tg-wrap"><table><tbody><tr><td><b>Build number</b></td><td>1694466342</td></tr></tbody></table></div></td>
</tr><tr>
	<th>Distribution</th>
	<td><a href="https://download.opensuse.org/tumbleweed/iso/openSUSE-Tumbleweed-NET-x86_64-Snapshot20230915-Media.iso">https://download.opensuse.org/tumbleweed/iso/openSUSE-Tumbleweed-NET-x86_64-Snapshot20230915-Media.iso</a></td>
</tr><tr>
	<th>Opted into Steam client beta?</th>
	<td>No</td>
</tr><tr>
	<th>Have you checked for system updates?</th>
	<td>Yes, on +2023-09-18T01+01:00</td>
</tr></table>

#### Steam logs

<blockQuote>

```log
RokeJulianLockhart@rp69se:~> steam
steam.sh[19023]: Running Steam on opensuse-tumbleweed 20230915 64-bit
steam.sh[19023]: STEAM_RUNTIME is enabled automatically
setup.sh[19096]: Steam runtime environment up-to-date!
steam.sh[19023]: Steam client's requirements are satisfied
[2023-09-18 16:50:58] Startup - updater built Sep 11 2023 20:48:54
[2023-09-18 16:50:58] Startup - Steam Client launched with: '/home/RokeJulianLockhart/.local/share/Steam/ubuntu12_32/steam'
09/18 16:50:58 Init: Installing breakpad exception handler for appid(steam)/version(1694466342)/tid(19156)
[2023-09-18 16:50:58] Loading cached metrics from disk (/home/RokeJulianLockhart/.local/share/Steam/package/steam_client_metrics.bin)
[2023-09-18 16:50:58] Using the following download hosts for Public, Realm steamglobal
[2023-09-18 16:50:58] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-09-18 16:50:58] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-09-18 16:50:58] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-09-18 16:50:58] Verifying installation...
[2023-09-18 16:50:58] Verification complete

Steam logging initialized: directory: /home/RokeJulianLockhart/.local/share/Steam/logs

/usr/share/themes/Breeze/gtk-2.0/widgets/entry:70: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Breeze/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", expected valid string constant
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xec07af50
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xec0795f0
steamwebhelper.sh[19189]: Runtime for steamwebhelper: defaulting to /home/RokeJulianLockhart/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[19189]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
CAppInfoCacheReadFromDiskThread took 77 milliseconds to initialize
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 19348
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
BRefreshApplicationsInLibrary 1: 1ms
BuildCompleteAppOverviewChange: 262 apps
RegisterForAppOverview 1: 18ms
RegisterForAppOverview 2: 19ms
[2023-09-18 16:52:59] Background update loop checking for update. . .
[2023-09-18 16:52:59] Checking for available updates...
[2023-09-18 16:52:59] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12?t=1129403633
[2023-09-18 16:52:59] Manifest download: send request
[2023-09-18 16:52:59] Manifest download: waiting for download to finish
[2023-09-18 16:53:00] Manifest download: finished
[2023-09-18 16:53:00] Download skipped: /steam_client_ubuntu12?t=1129403633 version 1694466342, installed version 1694466342, existing pending version 0
[2023-09-18 16:53:00] Nothing to do
```

</blockQuote>

<table><tr>
	<th>GPU</th>
	<td>NVIDIA</td>
</tr></table>

#### Please describe your issue in as much detail as possible:

New OS installation. Installed Steam. Steam never launches after authenticating the account, because it never loads user data.

#### Steps for reproducing this issue:

1.	```
	sudo zypper install -y steam
	```

1.	```
	xdg-open '/usr/share/applications/steam.desktop'
	```

	does not work, whereas

	```sh
	steam
	```

	works.

**Comment by kisak-valve** [comment] 2023-09-18 16:06
Hello @rokejulianlockhart, this reads like a duplicate of #9383. Please test if changing `PrefersNonDefaultGPU` to false (or removing it) works around the issue you're seeing.

**Comment by RokeJulianLockhart** [comment] 2023-09-27 15:39
@kisak-valve,

![Screenshot_20230927_163704](https://github.com/ValveSoftware/steam-for-linux/assets/42837531/038bf070-9cd8-426b-aba5-4319cd63f5bb)

**`/usr/share/applications/steam.desktop`**

<blockQuote>

```.desktop
[Desktop Entry]
Name=Steam
Comment=Application for managing and playing games on Steam
Exec=/usr/bin/steam %U
Icon=steam
Terminal=false
Type=Application
Categories=Network;FileTransfer;Game;
MimeType=x-scheme-handler/steam;x-scheme-handler/steamlink;
Actions=Store;Community;Library;Servers;Screenshots;News;Settings;BigPicture;Friends;
PrefersNonDefaultGPU=true
X-KDE-RunOnDiscreteGpu=true

[Desktop Action Store]
Name=Store
Exec=steam steam://store

[Desktop Action Community]
Name=Community
Exec=steam steam://url/SteamIDControlPage

[Desktop Action Library]
Name=Library
Exec=steam steam://open/games

[Desktop Action Servers]
Name=Servers
Exec=steam steam://open/servers

[Desktop Action Screenshots]
Name=Screenshots
Exec=steam steam://open/screenshots

[Desktop Action News]
Name=News
Exec=steam steam://open/news

[Desktop Action Settings]
Name=Settings
Exec=steam steam://open/settings

[Desktop Action BigPicture]
Name=Big Picture
Exec=steam steam://open/bigpicture

[Desktop Action Friends]
Name=Friends
Exec=steam steam://open/friends
```

**Comment by kisak-valve** [comment] 2023-09-27 15:42
Focus on the last two lines of the `[Desktop Entry]` section.

**Comment by RokeJulianLockhart** [comment] 2023-09-27 15:57
Ha, I missed that. Apologies.

**Comment by RokeJulianLockhart** [comment] 2024-05-11 16:02
> https://github.com/ValveSoftware/steam-for-linux/issues/10072#event-12776752285

The machine which I was testing this on I rarely utilize. I'll reopen this if I ever bother to reinstall the OS and this reappears.

**Closed** 2024-05-11 16:01 UTC
Labels: Distro Family: openSUSE
