### ISSUE TITLE
Insurgency runnning but steam status no game loaded "online"

### ISSUE THREAD

**Issue by charliebrownau** [ValveSoftware/steam-for-linux#5154] opened 2017-09-02 14:21 UTC
#### Your system information

* Steam client version (build number or date): 28/Aug/2017 
![screenshot at 2017-09-03 00-19-04](https://user-images.githubusercontent.com/31475201/29996210-bf888aa8-903d-11e7-8891-e50428a7dbca.png)

* Distribution (e.g. Ubuntu): Ubuntu Mate 17.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam not counting game as "running" 
Friends cant join on me when I host or join server
I launch from steam menu
same thing with and WITHOUT command line options
Worked fine in windows steam in win7

#### Steps for reproducing this issue:

1. Load Insurgency
2. Ubuntu Mate 17.04
3. Window or fullscreen + R9 380

**Comment by kisak-valve** [comment] 2017-09-02 15:14
Hello @charliebrownau, did you install steam with the distro-provided package or the valve-provided package? Is this the only game affected or are there other games with a similar issue?

Please run the game, then copy the contents of `~/.steam/error.log` to a [gist](https://gist.github.com/) and include a link in this issue report.

**Comment by OlliC** [comment] 2017-09-06 11:08
This is a known problem. 
See http://steamcommunity.com/app/222880/discussions/1/348292787753155302/

insurgency_linux spawns a crash_handler process in the initialisation process that steam thinks is the game. There is also a workaround in this discussion.

**Comment by kisak-valve** [comment] 2017-09-06 12:53
Thanks for linking that discussion, since the issue is with the game-provided crash handler, this will most likely need to be fixed by the game devs.

**Comment by OlliC** [comment] 2017-09-07 10:04
Yes it seems like that. Also because the issue was introduced by an Insurgency update and did not happen before that update. On the other hand it could also be a problem within Steam, because it confuses processes spawned by the main game process (insurgency_linux) as the game itself and removes the running status although the game is still running.

**Comment by OlliC** [comment] 2019-01-17 17:12
This was fixed with in new Steam Beta Client.

**Comment by kisak-valve** [comment] 2019-01-17 17:17
Hello @charliebrownau, is this fixed for you as well?

**Comment by kisak-valve** [comment] 2019-02-22 14:16
Thanks @OlliC, closing fixed.

**Closed by kisak-valve** 2019-02-22 14:16 UTC
Labels: 3rd party game, Need Retest
