### ISSUE TITLE
Feature Request: User control of game list displayed on Home

### ISSUE THREAD

**Issue by Gallocon** [ValveSoftware/steam-for-linux#11618] opened 2024-12-31 20:38 UTC
**Currently:** home displays the _Recent Games_ list. This can be fine for most, but the list is overwhelming. If you buy new games on a sale, or activate codes (e.g. from a Humble Bundle) they are then dropped right at the beginning of the list. If you don't intend on playing those right away, it adds friction to get to the game you were playing. 

**How to improve:** Steam allows for custom list creation. There's a default _Favorites_, but it's easy to make your own list of games. There could be a setting added to Settings >> Home to allow the selection of the list to present. 

**Why this is an improvement:** we all know of the Steam Backlog joke. I've got tons of games that I likely will never get to play. But hiding them from the UI hides them _everywhere_. That's impractical.

I also have ADHD. Looking at a list of games I'm not actively playing is overwhelming. So much so, that there are times where I don't play anything and put my Deck to sleep. It's a kin to "Netflix Paralysis". Too many options, and people may endlessly scroll. 

While digging, I've looked for workarounds (like CSS loader in Decky). The customization provided does not give you the control for the custom lists or specific games. 

---

As an end user, ISBAT manually select the games or game list on my Steam Deck Home Screen.

**Comment by kisak-valve** [comment] 2024-12-31 21:43
Hello @Gallocon, this is a feature request for the Steam client, not SteamOS as a platform. Looking around a bit, this looks like a duplicate of #10463. Closing in favor of the older feature request.

**Closed by kisak-valve** 2024-12-31 21:43 UTC
Labels: Feature Request, Steam client, Distro Family: SteamOS
