### ISSUE TITLE
Steam client segfaults at startup

### ISSUE THREAD

**Issue by bluenote10** [ValveSoftware/steam-for-linux#6753] opened 2019-12-08 18:25 UTC
#### Your system information

* Steam client version (build number or date): 1.0.0.61
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I'm starting `steam`, which briefly shows that "Verifying Steam" window and then crashes with a segfault:

```
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/fabian/.local/share/Steam/ubuntu12_32/steam
Installing breakpad exception handler for appid(steam)/version(1575604565)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Installing breakpad exception handler for appid(steam)/version(1575604565)
Installing breakpad exception handler for appid(steam)/version(1575604565)
Gtk-Message: 19:19:11.358: Failed to load module "gail"
Gtk-Message: 19:19:11.358: Failed to load module "atk-bridge"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  154
Serial number of failed request:  50
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  154
Value in failed request:  0x0
Serial number of failed request:  49
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  154
Serial number of failed request:  51
xerror_handler: X failed, continuing
assert_20191208191909_1.dmp[5477]: Uploading dump (out-of-process)
/tmp/dumps/assert_20191208191909_1.dmp
/home/fabian/.local/share/Steam/steam.sh: line 722:  5462 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20191208191909_1.dmp[5477]: Finished uploading minidump (out-of-process): success = yes
assert_20191208191909_1.dmp[5477]: response: CrashID=bp-8a3e3f9b-f282-4729-a41f-a88f52191208
assert_20191208191909_1.dmp[5477]: file ''/tmp/dumps/assert_20191208191909_1.dmp'', upload yes: ''CrashID=bp-8a3e3f9b-f282-4729-a41f-a88f52191208''
```

There are lots of segfault reports like this, but it is hard to extract clear instructions what to do in such a case (spend 2 hours on this already). In most cases it seemed to be related to NVidia drives, and some people could solve it with an update. In my case I was on driver version 418 originally. Now I've updated to 440, but that did not solve the issue.

Full output of `nvidia-smi`:

```
Sun Dec  8 19:23:52 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980     On   | 00000000:01:00.0  On |                  N/A |
|  0%   55C    P0    48W / 185W |    297MiB /  4042MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1346      G   /usr/lib/xorg/Xorg                            16MiB |
|    0      1401      G   /usr/bin/gnome-shell                          48MiB |
|    0      1753      G   /usr/lib/xorg/Xorg                            91MiB |
|    0      1889      G   /usr/bin/gnome-shell                         127MiB |
|    0      2927      G   ./insync                                       3MiB |
|    0      5231      G   gnome-control-center                           1MiB |
+-----------------------------------------------------------------------------+
```

Note: I need Cuda 10 for work, which had revealed issue #5778, but it looks like I have yet a different problem, because I don't see that `glXChooseVisual` error.

Any ideas how this problem can be solved?

#### Steps for reproducing this issue:

1. Start `steam`

**Comment by kisak-valve** [comment] 2019-12-08 19:16
Hello @bluenote10, swrast is mesa's slower cpu renderer and the fact Steam is trying to use it means that the system is trying to use mesa's libGL.so with the nvidia proprietary driver, which is incompatible. nVidia's .deb packaging of their cuda driver is known to not provide 32 bit userspace support, which is the problem you've encountered and is being tracked at #5778.

As noted in that issue report, your best bet is to install the 64 bit and 32 bit userspace components from the [Proprietary GPU Drivers PPA](https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa), then install the individual cuda components you need without using cuda's metapackaging in a similar process as https://github.com/ValveSoftware/steam-for-linux/issues/5778#issuecomment-517509736.

Closing as a duplicate of #5778.

**Closed by kisak-valve** 2019-12-08 19:16 UTC
