### ISSUE TITLE
Black or white blank windows instead of friends windows appear every 5 seconds

### ISSUE THREAD

**Issue by echaskaris** [ValveSoftware/steam-for-linux#7450] opened 2020-11-05 07:08 UTC
The white windows are titled as "about:blank?createflags=188 ..."

Latest beta steam
Appeared with latest steam update
Ubuntu 20.04

**Comment by laumiulun** [comment] 2020-11-05 07:28
Same. Major issues. I opted out of the beta program for now, and it seem to be fixed for now.

**Comment by Kandarihu** [comment] 2020-11-05 12:30
On my computer, the windows are blank, but this might simply be a matter of system theme difference. Nonetheless, I have this problem on Mint as well. I hope that this gets fixed soon.

**Comment by LiamDawe** [comment] 2020-11-05 12:32
A similar issue happens on Arch. Trying to open a Steam Chat from a Steam Group resulted in it spawning multiple windows with nothing in them, all blank with the Steam background colour. Also had to opt out as it made Steam quite unusable.

**Comment by parkerlreed** [comment] 2020-11-05 20:17
Same on Arch with KDE. Black windows that keeps spawning new.

**Comment by parkerlreed** [comment] 2020-11-05 20:18
Here's what is printed on the console every time it spawns

```
[1105/151734.095422:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.
[1105/151734.106131:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.
[1105/151734.804863:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[1105/151736.132293:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.
[1105/151736.166775:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.
[1105/151737.017940:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[1105/151738.349787:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.
[1105/151738.376543:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.
[1105/151738.627601:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[1105/151740.010726:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.
[1105/151740.038404:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.
[1105/151740.273521:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
```

**Comment by parkerlreed** [comment] 2020-11-05 20:30
If you disable GPU rendering for web views and GPU video decode in Steam settings then it has the same crashing behavior and it's white instead of black

And the log goes to only the crash reports

```
[1105/152856.462262:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[1105/152858.870972:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[1105/152901.131731:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[1105/152903.862634:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[1105/152906.171041:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
```

**Comment by echaskaris** [comment] 2020-11-06 14:17
The blank windows stop appearing after a bit, but the friends tab and features don't work at all!

**Comment by TTimo** [comment] 2020-11-06 15:23
If you are experiencing this, please post the full runtime info report from Help > System Information (while running the beta if at all possible).

**Comment by echaskaris** [comment] 2020-11-06 15:49
https://gist.github.com/echaskaris/089b506a2946cedaebb3e1b315d22667

**Comment by parkerlreed** [comment] 2020-11-06 19:09
https://gist.github.com/parkerlreed/24bc72112a4fe7ffb157b29060cd4348

**Comment by DraconYale** [comment] 2020-11-06 20:01
https://gist.github.com/DraconYale/d717142b5f2b00f1595f280f1317926f

**Comment by TTimo** [comment] 2020-11-06 20:15
Thanks .. we've had some success reproducing.

**Comment by echaskaris** [comment] 2020-11-08 15:42
Tried in X11 instead off wayland, still occurs.

**Comment by JacobSvenningsen** [comment] 2020-11-08 15:46
Also seems to affect the in-game overlay. Seems like the chat also sometimes recover after a while

**Comment by Shyrak** [comment] 2020-11-09 13:55
Also happening with Nvidia GPU
https://gist.github.com/Shyrak/a9948eee8984735804c26c0ffdf060c8

**Comment by TTimo** [comment] 2020-11-09 21:11
Assuming you have a recent SDL2 library on your host, can you try the following workaround:

- move `~/.steam/root/ubuntu12_64/libSDL2-2.0.so.0` out of the way (renaming it to `libSDL2-2.0.so.0.off` for instance)

This will make `steamwebhelper` fall back to your host's SDL library - which is not a good thing to do in general, but if the blank windows problem goes away that'll confirm it's in our patched SDL code.

**Comment by r3pek** [comment] 2020-11-09 21:56
@TTimo confirmed working on Fedora 32

**Comment by parkerlreed** [comment] 2020-11-09 23:09
Doesn't seem to work on Arch.

steam runtime and native, file appears to get recreated and problem persists (Both GPU accel on and off.

sdl2 2.0.12-3

**Comment by arielnmz** [comment] 2020-11-10 04:09
I've been experiencing the same issue in the steam client on fedora 31
steam-1.0.0.66-2.fc31
Fedora release 31 (Thirty One)
kernel 5.8.18-100.fc31.x86_64

**Comment by echaskaris** [comment] 2020-11-10 12:09
For me the file is recreated and the problem persists.
Ubuntu 20.04

**Comment by echaskaris** [comment] 2020-11-12 18:54
Umm can you please update steam with the patched sdl thanks

**Comment by JacobSvenningsen** [comment] 2020-11-12 18:55
One annoying thing about this issue, has been that it seemed to occur somewhat randomly.
I've found a reliable way to reproduce this issue, at least on my end. Every single time I try pasting an image from my clipboard into any chat window, this issue appears. Also looks like the image has to be sufficiently large.

To reproduce the issue, try the following:
1. Go to https://wcrates.files.wordpress.com/2015/03/cute-animal-photos.jpg
2. right-click the image, and select "Copy Image"
3. Open any chat with a friend
4. Press CTRL+V

**Comment by echaskaris** [comment] 2020-11-12 18:58
For me the windows don't open at all!

**Comment by TTimo** [comment] 2020-11-12 19:00
Next Steam beta update (> Nov 4) will fix this. I expect it might take a day or two to roll out (the fix is indeed via an SDL update).

**Comment by echaskaris** [comment] 2020-11-13 13:56
Fixed with Nov 13 build.

**Comment by JacobSvenningsen** [comment] 2020-11-13 17:50
What I posted here yesterday no longer reproduces this. Haven't been able to find another way to make the bug re-appear.
Nov. 13 build very likely fixed it indeed, as advertised

**Comment by parkerlreed** [comment] 2020-11-14 21:14
Working here as well.

**Closed** 2020-11-14 21:46 UTC
Labels: Need Retest, Web Component

**Comment by rohezal** [comment] 2021-03-20 20:49
Got the bug for Valheim. Running Ubuntu 18.04 in an lxd / lxc container.

Found path: /home/ubuntu/.local/share/Steam/steamapps/common/Valheim/valheim.x86_64
>>> Adding process 1201 for game ID 892970
[...]
[0320/200641.995263:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.
Game update: AppID 892970 "", ProcID 1201, IP 0.0.0.0:0
RecordSteamInterfaceCreation (PID 1201): SteamUtils009 / 
[...]
RecordSteamInterfaceCreation (PID 1201): SteamNetworkingSockets008 / 
Installing breakpad exception handler for appid(steam)/version(1613176728)
RecordSteamInterfaceCreation (PID 1201): SteamUtils009 / 
[...]
Installing breakpad exception handler for appid(steam)/version(1613176728)
[2021-03-20 20:17:10] Background update loop checking for update. . .
[2021-03-20 20:17:10] Checking for available updates...
[2021-03-20 20:17:10] Downloading manifest: https://cdn.cloudflare.steamstatic.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1613176728)
[...]
Error: websocket: close 1006 (abnormal closure): unexpected EOF
