### ISSUE TITLE
Steam entry blinks in application panel

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#6523] opened 2019-09-21 16:31 UTC
#### Your system information

* Steam client version (build number or date): Sep 20 2019, at 00:06:06
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam highlights itself in application panel sometimes

#### Steps for reproducing this issue:

1. Open steam
2. Open game settings
3. Click close
4. Steam will be highlighted in task panel
  
---(markdown parser is broken and creates single numbered list)---  
  
1. Open steam
2. Press help -> about stream
3. Click on any other application window
4. Click on 'About steam' window [optional, if window is under another window]
5. Click close
  
![image](https://user-images.githubusercontent.com/4938483/65376217-f6767000-dc8c-11e9-9bcf-8c4fd4b80ba4.png)

**Comment by zebh** [comment] 2019-09-23 12:38
Can confirm. This occurs in Plasma, and from OP's screenshot it seems that is the case there as well.

**Your system information**

    Steam client version (build number or date): Sep 20 2019, at 00:06:06
    Steam package versions: 1568941497
    Distribution (e.g. Ubuntu): OpenSuse Tumbleweed (snapshot: 20190921)
    Opted into Steam client beta?: [Yes/No] Yes
    Have you checked for system updates?: [Yes/No] Yes

    KWin (X11): 5.16.5
    KDE Plasma Version: 5.16.5
    KDE Frameworks Version: 5.61.0
    Qt Version: 5.13.1

**Comment by kisak-valve** [comment] 2022-01-21 22:31
Hello @XakepSDK, @zebh, are either of you still experiencing this issue on an up to date system?

**Comment by zebh** [comment] 2022-01-23 06:20
> Hello @XakepSDK, @zebh, are either of you still experiencing this issue on an up to date system?

No longer present here. Working as intended. :+1: 

```
Steam client version (build number or date): Jan 16 2022, at 17:34:49
Steam package versions: 1642451672
Distribution (e.g. Ubuntu): Ubuntu 21.10
Opted into Steam client beta?: [Yes/No] Yes
Have you checked for system updates?: [Yes/No] Yes

KWin (Wayland): 5.23.5
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
```

**Comment by XakepSDK** [comment] 2022-01-23 06:23
I think it's fixed.

**Comment by kisak-valve** [comment] 2022-01-23 12:39
Thanks for retesting, closing.

**Closed by kisak-valve** 2022-01-23 12:39 UTC
Labels: Steam client, Need Retest
