### ISSUE TITLE
Cannot move games to another drive. 

### ISSUE THREAD

**Issue by Evernow** [ValveSoftware/steam-for-linux#6095] opened 2019-02-16 19:45 UTC
Hello there! Apologies if this has been discussed before but I was unable to find any solutions.

For some background, I was downloading and installing my games on a 256GB M.2 SSD in the start, because I was inpatient and didn't wanna wait for my 2TB SSD to arrive, right now I have Frostpunk and The Witcher(first one) installed on Steam with Proton. And I cannot move those two games to the new drive. I made sure the new drive's partition is set to Ext4, and I can move non-proton games like Rimworld and Kerbal Space Programw without issues.

When I try to move Frostpunk or The Witcher, I get "Failed to move all files to new library folder (I/O Operation Failed). 

Any ideas?

**Comment by kisak-valve** [comment] 2019-02-16 19:52
Hello @Evernow, moving games is handled by Steam, not Proton, so I've transferred this issue to the steam-for-linux issue tracker.

Please run `find /path/to/game -type f -size +2G` and check if it lists any files. If it does, then you've encountered #4851.

**Comment by Evernow** [comment] 2019-02-16 21:58
I think it does list files. This is the output of the terminal 

[daniel@daniel-pc ~]$ find /home/daniel/.local/share/Steam/steamapps/common/Frostpunk/ -type f -size +2G

/home/daniel/.local/share/Steam/steamapps/common/Frostpunk/textures-s3.dat

**Comment by Evernow** [comment] 2019-02-16 22:08
Oh ok! If I move that file to somewhere else, then move the game to the other drive, it works! I was able to transfer both games using this! Thank you!

**Comment by kisak-valve** [comment] 2019-02-16 22:10
Thanks for testing, closing as a duplicate of #4851.

**Closed by kisak-valve** 2019-02-16 22:10 UTC
Labels: Proton
