### ISSUE TITLE
Steam crash during BLE firmware upgrade

### ISSUE THREAD

**Issue by Despruk** [ValveSoftware/steam-for-linux#5482] opened 2018-05-12 14:28 UTC
#### Your system information

* Steam client version (build number or date): May 11 2018, at 16:38:38
* Distribution (e.g. Ubuntu): Arch linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Steam client crashes during Steam controller BLE upgrade.
I've followed instructions from https://support.steampowered.com/kb_article.php?ref=7728-QESJ-4420#how

The firmware upgrade window appears.
The progress bar never moves.
After a minute or so, Steam client crashes.

Steam client output from the crash:
https://gist.github.com/Despruk/c5f50a7757ad53d931513834ad277108

I've attempted it twice, once from desktop and second time from Big picture mode with same result.
After crash the controller is not working.
Attempting to start Steam client right after the crash causes steam to get stuck at the initial "Connecting steam account" window, and it's not possible to kill the process anymore.
Steam output from that:
https://gist.github.com/Despruk/2d5203b379b63ad51cd052cb9ec79694

After system reset Steam client and the controller seems to be working fine again.

#### Steps for reproducing this issue:

1. Opt-in steam beta
2. Plug in Steam controller with usb
3. Start BLE firmware upgrade

#### System information
```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4200 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.15.15-1-vfio
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2017-10-05

Video Card:
    Driver:  X.Org Radeon RX 560 Series (POLARIS11 / DRM 3.23.0 / 4.15.15-1-vfio, LLVM 6.0.0)
    Driver Version:  3.0 Mesa 18.0.2
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1b80
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  2
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 5120 x 1440
    Primary Display Size: 23.50" x 13.23" (26.97" diag)
                                            59.7cm x 33.6cm (68.5cm diag)
    Primary VRAM: 3686 MB

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  32172 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Total Hard Disk Space Available:  438874 Mb
    Largest Free Hard Disk Block:  144455 Mb
    VR Headset: None detected

Recent Failure Reports:
```

**Comment by ananace** [comment] 2018-05-15 17:33
Ran into the same issue, seems like Steam manages to cause an oops in the usbhid driver on my system when trying to flash the firmware, requiring a reboot.

Entries from the log
```
kernel: BUG: unable to handle kernel paging request at 000055ac0ebe9008
kernel: IP: usbhid_raw_request+0xcf/0x150
kernel: PGD 0 P4D 0 
kernel: Oops: 0000 [#1] SMP PTI
kernel: Modules linked in: ipt_MASQUERADE nf_nat_masquerade_ipv4 nf_conntrack_netlink xfrm_user xfrm_algo xt_addrtype devlink ipt_REJECT nf_reject_ipv4 ip6t_rpfilter xt_tcpudp ip6t_REJECT nf_reject_ipv6 br_netfilter xt_connt>
kernel:  joydev snd_usbmidi_lib snd_rawmidi media snd_seq_device intel_rapl x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm crct10dif_pclmul crc32_pclmul crc32c_intel ghash_clmulni_intel pcbc efi_pstore aesni_in>
kernel:  udp_tunnel macvlan vmxnet3 virtio_net virtio_ring virtio tg3 sky2 r8169 pcnet32 mii igb dca e1000 atl1c fuse overlay xfs nfs lockd grace sunrpc jfs reiserfs ext4 jbd2 fscrypto ext2 mbcache firewire_core sl811_hcd xh>
kernel: CPU: 1 PID: 19952 Comm: Controller Work Tainted: G           O     4.16.0-sabayon #1
kernel: Hardware name: System manufacturer System Product Name/PRIME Z270-A, BIOS 0906 03/22/2017
kernel: RIP: 0010:usbhid_raw_request+0xcf/0x150
kernel: RSP: 0018:ffffc90005e0fea0 EFLAGS: 00210246
kernel: RAX: ffff88089566d800 RBX: 0000000000000000 RCX: 0000000000000041
kernel: RDX: ffff8808354ee8a0 RSI: 0000000000000000 RDI: 000055ac0ebe9000
kernel: RBP: ffff8808354ee8a0 R08: 0000000000000002 R09: ffff88089566d898
kernel: R10: ffff8807b4dbd738 R11: 0000000000000000 R12: 000000009fc7aa68
kernel: R13: 0000000000000041 R14: ffff880896386000 R15: 000000009fc7aa68
kernel: FS:  0000000000000000(0000) GS:ffff8808bec40000(0063) knlGS:00000000e5650b40
kernel: CS:  0010 DS: 002b ES: 002b CR0: 0000000080050033
kernel: CR2: 000055ac0ebe9008 CR3: 00000007d9e9a006 CR4: 00000000003606e0
kernel: DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
kernel: DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
kernel: Call Trace:
kernel:  hidraw_ioctl+0x28c/0x350
kernel:  compat_SyS_ioctl+0x435/0x1150
kernel:  do_fast_syscall_32+0xa0/0x210
kernel:  entry_SYSENTER_compat+0x7f/0x8e
kernel: Code: fb ff ff ff 5b c3 48 8b 87 d0 18 00 00 48 8b bf 10 1d 00 00 31 db 40 84 f6 45 0f b6 c0 4c 8b 08 48 8b 7f 08 49 8d 81 68 ff ff ff <48> 8b 7f 08 40 88 32 75 0d 48 83 c2 01 48 83 e9 01 bb 01 00 00 
kernel: RIP: usbhid_raw_request+0xcf/0x150 RSP: ffffc90005e0fea0
kernel: CR2: 000055ac0ebe9008
kernel: ---[ end trace 1473c39255f4da86 ]---
```

The client output a massive block of ioctl no such device errors just before this happens, so I haven't yet been able to get any useful lines of output from there.

**Comment by Despruk** [comment] 2018-05-17 19:52
I tried BLE firmware upgrade again and today it worked.

This was before Steam client updated, so I suppose something else changed on my system.
The only big change was switch to kernel 4.16, though I did some other updates so who knows.

**Comment by tpruzina** [comment] 2018-05-28 22:11
I had this crash on me when I tried updating it via steamlink, when I connected it to my linux box the update finished just fine (perhaps worth separate bug?).

In spite of that, I was unable wirelessly connect/pair to PC via dongle or steamlink afterwards (X+Start).
On my linux box I could attempt to add SC, but after 4 button code came up I was unable to enter it.
On steamlink X+Start wouldn't work at all. I tried downgrading/upgrading firmware via cable and none of that helped, but once I unplugged mouse & Xbox controller from my steamlink (prompting default connect controller screen), pairing worked just fine and afterwards I was able to pair with my PC as well.

Probably should create separate bug for this, but I don't think I'm gonna be able to reproduce it.

**Comment by kisak-valve** [comment] 2020-07-10 13:14
Hello @Despruk, have you seen this issue since the initial report?

**Comment by Despruk** [comment] 2020-07-10 13:34
> Hello @Despruk, have you seen this issue since the initial report?

No sorry, I haven't used the steam controller much since my original report. As I mentioned, the problem eventually went away.

**Comment by kisak-valve** [comment] 2020-08-14 13:10
Thanks for the follow up. Closing.

**Closed by kisak-valve** 2020-08-14 13:10 UTC
Labels: Need Retest, Steam client, Steam controller
