### ISSUE TITLE
Steam long commandline.

### ISSUE THREAD

**Issue by fbt** [ValveSoftware/steam-for-linux#5753] opened 2018-09-13 14:42 UTC
#### Your system information

* Steam client version (build number or date): Sep  8 2018, at 19:21:25
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam stops reacting to external commands (ex. `steam -shutdown`) if you feed it a long enough commandline. Weirdly, it seems to vary, but a thousand chars does this reliably.

#### Steps for reproducing this issue:

1. Launch Steam
2. Feed it a commandline of over about a thousand chars, example: `steam -applaunch 107410 -world=empty -noSplash -skipIntro -cpuCount=4 -maxMem=24576 -maxVRAM=11263 -exThreads=7 -noLogs -mod=mods-available/da8fc\;mods-available/7efc6\;mods-available/a9849\;mods-available/fb94f\;mods-available/7ef7c\;mods-available/76f92\;mods-available/7c479\;mods-available/69e77\;mods-available/bd6e9\;mods-available/42b88\;mods-available/665dc\;mods-available/b40a6\;mods-available/1e4ca\;mods-available/5528c\;mods-available/1878d\;mods-available/36b72\;mods-available/f4fb6\;mods-available/d79f8\;mods-available/2a801\;mods-available/fe52a\;mods-available/b0dd8\;mods-available/40496\;mods-available/4a200\;mods-available/c19a7\;mods-available/da7a1\;mods-available/3ecc8\;mods-available/74396\;mods-available/dc1d1\;mods-available/2fe45\;mods-available/ea285\;mods-available/be4b9\;mods-available/58582\;mods-available/c23ee\;mods-available/525f2\;mods-available/d36d8\;mods-available/d8b51\;mods-available/4cfbf\;mods-available/f235e\;mods-available/07c56\;mods-available/d24f0\;mods-available/07256\;mods-available/c92e1\;mods-available/d7dfb\;mods-available/68f61\;mods-available/fb083\;`
3. Steam stops reacting to any and all external commands.

It won't spew anything out into the console when this happens.
Not sure how to debug this further.
Happens in both the stable and the beta Steam versions.

Probably a DBus issue?

**Comment by fbt** [comment] 2018-09-13 14:52
This isn't a huge problem, I've already worked around it by making the commandline much shorter, but I think Steam should either allow longer commandlines or explicitly bark at you if you go over the limit.
This was a bit frustrating to pinpoint.

**Comment by bastimeyer** [comment] 2022-04-09 23:58
Could this issue please get some attention?

I'm the author of a launcher script for DayZ which needs to pass a long `-mod=...` argument to `steam -applaunch 221100`, similar to what has been described in the OP in regards to Arma 3.

In order to work around this issue, I had to update my launcher script so that it doesn't name mod directory links like `$ID-$NAME` and it now converts the decimal mod ID into a string of ASCII chars and base64 encodes it, to ensure a minimal length of mod directory names that get included in the game's `-mod` launch argument. This unfortunately makes mods unrecognizable in the game directory.

**Comment by DanielCeregatti** [comment] 2022-07-02 23:57
I didn't find issue this when I originally [reported my issue](#8484). I too was hopping to launch DayZ on Linux using a `steam://` URL, but this issue prevents it for servers with many mods. I will close mine and flag it as a duplicate of this one.

To be clear, the _ONLY_ way at the moment to join a DayZ server with a long `-mods` string from the Linux Steam client is to craft a `%command% -nolauncher -server=1.2.3.4 -mod=...` string and to use that in the launch options. Luckily @bastimeyer's script mentioned above helps with that.

Currently it's a lot of hoop-jumping just to play DayZ on Linux. Fixing this issue would go a long way to making that process easier.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2022-08-24 21:53
This limit should definitely be removed. I do not believe that mere notification of the problem to the user would remediate anything. Additionally, I am certain that the limit truly should become unlimited rather than the limit merely be configured to be greater, because that merely delays the problem until somebody else attempts something more unique and impressive.

**Comment by vitorhnn** [comment] 2023-12-26 02:20
From some very quick testing, this seems to have been quietly fixed by Valve at some point between October and now, or at least the size of the buffer Steam uses has been greatly expanded. `steam://` URLs of over 19000 bytes now are properly executed.

If anyone else can verify this it'd be greatly appreciated!

**Comment by kisak-valve** [comment] 2024-01-27 00:50
Closing per the last comment.

**Closed by kisak-valve** 2024-01-27 00:50 UTC
Labels: Steam client, Need Retest
