### ISSUE TITLE
Rollback from Steam Client Beta to Steam Client forces Steam Play games to full re-downloads.

### ISSUE THREAD

**Issue by ewe2** [ValveSoftware/steam-for-linux#6035] opened 2019-01-19 04:50 UTC
#### 
OS Linux Debian Buster/Sid (testing)
CPU I5
GPU Nvidia 1050ti
RAM 16GB
Steam Play Proton version 3.16-6 Beta

* Steam client version (build number or date): Jan 4 2019
* Distribution (e.g. Ubuntu): Debian Buster
* Opted into Steam client beta?: Yes, previously
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Similar problem was seen in a note in issue #6028, similar problems with 0-sized downloads for Steam Play games and inability to reach content servers. Debian enables IPv6 by default in kernel however my ISP does not support IPv6 (Carrier NAT), so that fix is impossible.

Rolling back to the stable version (as above) causes most Steam Play games to require full re-downloads, but it also forces updates for several native games.

#### Steps for reproducing this issue:

1.  Roll back from Jan 16/17 Steam Client Beta to current Linux Steam Client.
2. 
3.

**Comment by DPTJKKVH** [comment] 2019-01-19 08:41
I can confirm this. I have experienced this jus yesterday while debugging another issue.

**Comment by XakepSDK** [comment] 2019-01-19 15:02
Temp fix:
1. Start steam
2. Check for updates
3. Do not click "restart steam"
4. Press steam -> offline mode
5. Press "restart"
5. Go to settings and check 'use proton for all titles"
6. Press "restart"
7. Press "go online"

**Comment by kisak-valve** [comment] 2019-01-19 15:33
That makes this sound related to #5901.

**Comment by oblitum** [comment] 2019-01-19 19:37
DAMMIT! Whatever it did it's now going to redownload all the games.............. Such nightmare. Thanks Valve.

**Comment by ewe2** [comment] 2019-01-19 19:38
> DAMMIT! Whatever it did it's now going to redownload all the games.............. Such nightmare. Thanks Valve.

Try that fix mentioned above and let us know if it works for you.

**Comment by oblitum** [comment] 2019-01-19 19:39
@ewe2 I tried, it didn't.

**Comment by oblitum** [comment] 2019-01-19 19:42
@ewe2 to be exact, I didn't know of that at first. The games were running fine, but then I happened to hit the steam play tab and noticed the checkbox for running all games on proton wasn't checked anymore (it was before), then I checked it and on restart it started to download all the damn games, and then it looks like there was no way back. I tried the procedure above but didn't help, I tried to uncheck the checkbox (since the games were running before), but now they don't run anymore with it unchecked, looks like I have to download terabytes of data for nothing.

**Comment by DPTJKKVH** [comment] 2019-01-19 19:53
It didn't work for me either. I think you must pull it off the first time.

If you run into this issue unprepared (like most will) you are doomed. I already downloaded Valkyria Chronicles (18GB) at least three times since yesterday becuase I helped debugging the IPv4/6 issue with content servers.

I think Valve must inplement a whole new logic into the system  so it is able to deal with two builds of the same game simultaneously.

**Comment by oblitum** [comment] 2019-01-19 21:45
Yeah, from disk avail size increase, all games simply ended up deleted.

**Comment by Uradamus** [comment] 2019-01-22 09:01
The mentioned fix doesn't help anything for me either. After allowing a beta client update earlier, all my Proton games got queued to redownload, which is totally unacceptable. I've got like ~60 games I installed to test Proton over the past few months, I'm leaving this trash on pause until this is sorted, otherwise I'm just uninstalling them all as I'm not going to blow through all that bandwidth in a day or two and face throttling over this nonsense.

**Comment by oblitum** [comment] 2019-01-22 14:04
@Uradamus if you're just waiting for confirmation it got fixed and you're safe to download it all again, then fine, but if you're expecting the client will magically not have to re-download all the games anymore where they simply got deleted already, not a chance.

**Comment by Uradamus** [comment] 2019-01-22 19:47
Blah, so it did delete them all. What the shit, Valve, get your act together. I only noticed that it was starting to redownload stuff shortly before I went to bed last night, didn't even think to check what was going on in the Steam dir. When I saw all those games queued up and a dozen or so smaller ones already pushed through I paused it and came here looking for answers before shutting things down in disgust. I guess I'll have to go through and remove the ones I don't care about and let the rest run an hour or two a day until things are mostly restored...

**Comment by ewe2** [comment] 2019-01-24 20:09
Yeah best to stay on the stable client until all this is sorted. I am a most unwilling guinea pig for galaxy brain updates.

**Comment by oblitum** [comment] 2019-01-25 14:31
Yeah, seriously, I confirm, I didn't follow the advice and was re-downloading Batman 17GB that just finished (the client got updated once meanwhile). Then just after the download ends, only then, the client instead of finishing just put it as "paused canceled", I click download to it finishes the thing and it starts downloading it from scratch all over, WTF!!!!! Just wait for this issue to close.

**Comment by Johnanater** [comment] 2019-01-27 17:39
Verifying the games will stop them from re-downloading.

**Comment by oblitum** [comment] 2019-01-27 17:56
Won't work when they simply get erased.

**Comment by Johnanater** [comment] 2019-01-27 19:44
They only got erased when they started to download, which was one at a time. For me at least.

**Comment by DPTJKKVH** [comment] 2019-02-04 13:45
@kisak-valve This is fixed in Steam-Beta.

If you tell me that the latest stable release had a patch included for this issue I can test it for you.

**Comment by kisak-valve** [comment] 2019-02-04 17:51
The [2019-02-01](https://store.steampowered.com/news/48091/) Steam update has brought the stable client in line with the previous beta, so this issue should no longer be reproducible. Closing as resolved.

**Closed by kisak-valve** 2019-02-04 17:51 UTC
Labels: Proton, Steam client
