### ISSUE TITLE
Fullscreen is not working on 21:9 monitors

### ISSUE THREAD

**Issue by FabianGoettl** [ValveSoftware/steam-for-linux#4878] opened 2017-03-01 19:42 UTC
Full  screen video playback is neither in the correct dimensions, nor is it in full screen. Part of the screen is black. Please see attached screenshot.
![screenshot from 2017-03-01 01-53-13](https://cloud.githubusercontent.com/assets/24296280/23477814/83ad788c-febf-11e6-8179-11b632d4fe7c.png)

#### System information

* Ubuntu 16.04
* Nvidia Drivers

#### Steps for reproducing this issue:

1. Get a 21:9 monitor with resolution 3440x1440 (or 2560x1080)
2. Open full screen on any video in Steam store

**Comment by kisak-valve** [comment] 2017-03-01 19:48
Closing as a duplicate of #3699.

**Closed by kisak-valve** 2017-03-01 19:48 UTC
