### ISSUE TITLE
Feature request: Add ability to run Windows games in WINE for games without a Linux version

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#74] opened 2012-12-20 06:41 UTC
Although this would be a feature for more advanced users, it might be an interesting idea to allow running the Windows versions of games in WINE through the Linux client if a native version is not available and the game in question does not explicitly require a Windows license (i.e. it doesn't use XNA or some similar technology).

Although some games are ported to Linux, many are not, and having the option to run games through this method even in an unsupported fashion would be quite an interesting and useful feature to have. Definitely not expecting it any time soon, but it may be something to consider down the line, if it's even possible.

**Comment by WhosAsking** [comment] 2015-12-16 09:31
I can understand both sides of the argument, but I also note this. If Valve wants more people to switch to Linux and use the Steam Machines and such, they need a better gaming lineup, and while convincing developers to release Linux-native versions is of course best, there is still the massive back catalog of titles that are at end-of-life. The developer has either dropped it or (in some cases) no longer exists. These games are basically abandoned and therefore won't see a new version anywhere, let alone for Linux. It's for the back catalog that we should encourage WINE support, but as noted, it can get finicky, so do it like how DOSBox is used for Doom: on a game-by-game basis (And if they're willing to use DOSBox to run a legacy game, why not WINE?). It may be somewhat space-inefficient, but it also means the wrapper can be tuned for each game, reducing compatibility issues. It also improves the KISS factor which will be critical for drawing not-so-tech-savvy gamers.

Whether this is done by Valve or the developers (if any) is up to them, but Steam on Linux really needs some initiative to start bringing the Windows back catalog into the Linux catalog to improve its standing. Put it this way. It's the current mostly-Windows-only Steam library that keeps me from moving away from Windows, much as I want to given the whole Windows 10 thing. Improve the back catalog support and you'll likely find a convert, and I'm probably not the only one.

**Comment by Seegras** [comment] 2015-12-17 14:05
I don't see any use for this. If I want to run a windows game, I can run Steam for windows on wine. That way I also don't have a mess, and everything is nicely separated.

**Comment by boombatower** [comment] 2015-12-17 14:34
The reason is to avoid having to relog to play a windows game and having two copies of steam for no good reason.

**Comment by sdaugherty** [comment] 2015-12-17 16:11
Mark it as an experimental, no support offered feature, implement it with a
"stub" steam client that proxies all the APIs to the Linux client, and the
launch requests to the "stub", and call it a day.

We know the experience will be less than perfect. However, an imperfect
experience is less hell on your users than having to be logged in to one or
the other, having to dual boot, or having to abandon SteamOS entirely.

Make this happen already, make it optional for developers, and let users
turn it on anyway in some deeply buried " unsupported settings" menu.

**Comment by oelmekki** [comment] 2017-05-31 17:13
> If Valve wants more people to switch to Linux and use the Steam Machines and such, they need a better gaming lineup, and while convincing developers to release Linux-native versions is of course best, there is still the massive back catalog of titles that are at end-of-life.

This. We can run steam/windows through wine and it's good for us, but I imagine what it must look like for a kid who bought a steam machine with no prior experience of linux, only to discover they can't play most games ... on steam.

Indeed, pushing for native support is the way to go forward. But gamers don't care about our technical debates. They bought a (pricey) steam console, they expect to play steam games. Actually, I think that not only steam should use wine, but they should even be a sponsor for it, like often big companies back up open source projects, and take responsibility to write scripts akin PlayOnLinux for steam. They have an unique opportunity, here : they can port games to their playing console without even needing help from game developers. This is unheard of.

So yeah, native support is the best. For all (most) the other things, there's wine, we should not ignore the opportunity.

**Comment by oelmekki** [comment] 2017-06-01 08:27
By the way (sorry for double post), I gave a second thought to the argument : "if we support wine, game producers won't be incentive to release native version".

There are many ways to incentive people, and wine could play a part in it. Imagine Valve made a script to run a game through wine. This won't be the perfect experience from native game. We often say "oh yeah, this game works on wine, perfs are even better than on windows! There's just this little thing, <slow connection | texture missing | messed up main menu | whatever>, but really, I don't care that much!". This is something that can be used.

Imagine there's a banner on the page for that game that run through wine : "Warning! This game has no stable release for steam machine yet, experience may be slightly deteriorated". Now, gamers will be able to play the game, they'll know about shortcomings before buying, and they'll ask game developers : "when are you releasing the stable version for steam?".

**Comment by coollorenzo** [comment] 2018-03-03 16:33
It would be awesome to have something like playonlinux built into steam!

**Comment by regeya** [comment] 2018-03-03 18:08
Is there some way someone could close this?  It never seems to gain any traction and the thread is six years old at this point.  There's an unofficial way to do it called SteamFootBridge,  No idea if it'll earn you a VAC ban or not, but it can be done.

**Comment by oelmekki** [comment] 2018-03-04 09:43
@regeya

Thanks for mentioning SteamFootBridge, it's the first  time I hear about it. Although, the possibility it could get us banned and locked out of our expansive game collection is quite an issue :D 

Could we have any official statement on this? If there is a recommended way to use steam windows games in steam on linux, that's fine by me, disregarding if it's a builtin feature or not.

**Comment by Plagman** [comment] 2018-08-22 08:18
Going to call this one closed now. Specific issues with the new Steam Play compatibility feature can be filed here or in the Proton repository, depending on where the problem is.

**Closed by Plagman** 2018-08-22 08:18 UTC
Labels: Feature Request, reviewed

**Comment by pwaller** [comment] 2018-08-22 08:19
For anyone who missed it, @Plagman is referring to [this announcement](https://steamcommunity.com/games/221410/announcements/detail/1696055855739350561).
