### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by Root-Plasma** [ValveSoftware/steam-for-linux#7143] opened 2020-05-28 23:01 UTC
Your system information

* Steam client version (build number or date): 15 May 2020
* Distribution (e.g. Ubuntu): Debian 10.4
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

![Screenshot_20200528_195709](https://user-images.githubusercontent.com/62955221/83202205-7e1a5580-a11d-11ea-8b4b-d1fc685f792c.png)
![Screenshot_20200528_195747](https://user-images.githubusercontent.com/62955221/83202222-85416380-a11d-11ea-95dc-3cfd5aaecf63.png)

the first time I installed steam on debian it had also appeared that the browser within steam is not supported

Keyboard accents do not work within steam and only in steam, per example:

**All apps except steam**

ã é í ó ú

**Steam**
a e i o u

#### Steps for reproducing this issue:

1 install steam from official steam site 
2 switch to the keyboard that has accents
3. nothing works with the accent keyboard inside steam

![Screenshot_20200528_200049](https://user-images.githubusercontent.com/62955221/83202440-f97c0700-a11d-11ea-93a6-b4e683ae5d59.png)

**Comment by kisak-valve** [comment] 2020-05-28 23:17
Hello @Root-Plasma, what does running `locale -a` in a terminal give you? In particular, I'm interested if the output includes `en_US.utf8` or possibly `C.utf8`.

If it is missing, please add the locale to your system with something similar to https://github.com/ValveSoftware/steam-for-linux/issues/5586#issuecomment-408108428.

**Comment by Root-Plasma** [comment] 2020-05-29 01:55
@kisak-valve 
![Screenshot_20200528_225504](https://user-images.githubusercontent.com/62955221/83212555-508dd600-a136-11ea-9c70-9fe41b8dd14d.png)

**Comment by kisak-valve** [comment] 2020-05-29 02:06
Thanks, as described in #5589, please add `en_US.UTF-8 UTF-8` to `/etc/locale.gen` and run `sudo locale-gen`, then retest.

**Comment by Root-Plasma** [comment] 2020-05-29 22:24
![Screenshot_20200529_192407](https://user-images.githubusercontent.com/62955221/83310331-09f5b580-a1e2-11ea-9054-e3350f0647d6.png)

**Comment by Root-Plasma** [comment] 2020-05-29 22:25
and now my debian is only in english, im pt-br

**Comment by kisak-valve** [comment] 2020-05-29 22:40
Adding another locale to the system shouldn't remove the existing locale like that. You should be able to change the config back to what it was before and re-run `sudo locale-gen` to get back to where you were before. Just to double check, did you add `en_US.UTF-8 UTF-8` on a separate line from `pt_BR.UTF-8 UTF-8`? Can you attach the config file to this issue report?

**Comment by Root-Plasma** [comment] 2020-05-29 23:37
to .gen to .txt
[locale.txt](https://github.com/ValveSoftware/steam-for-linux/files/4704764/locale.txt)

**Comment by Root-Plasma** [comment] 2020-05-29 23:38
i fixed the linguage

**Comment by kisak-valve** [comment] 2020-05-29 23:50
I would try uncommenting lines 163, 381, and 382 like [locale.gen.txt](https://github.com/ValveSoftware/steam-for-linux/files/4704780/locale.gen.txt) and see if `sudo locale-gen` generates both locales.

There's a bit of a language barrier happening here, and I don't want to go around in circles, so if that doesn't work as expected, then you may have some luck asking around your distro's community on how to add locales to your system.

**Comment by Root-Plasma** [comment] 2020-05-30 01:12
Well @kisak-valve thanks for your help, **good job** ;)
we can be friends :P?

**Comment by kisak-valve** [comment] 2020-05-30 01:20
Just to confirm, is the original text entry issue resolved by that config adjustment? If it is, then we can close this as a duplicate of #5589.

**Comment by Root-Plasma** [comment] 2020-05-30 06:11
NEIN, not fixed :(

**Comment by Root-Plasma** [comment] 2020-05-30 06:11
Danke...

**Comment by Root-Plasma** [comment] 2020-05-30 06:54
EDIT: IT WORKS!!!!!!!!!!!! thanks @kisak-valve

**Comment by Root-Plasma** [comment] 2020-05-30 06:57
![Screenshot_20200530_035659](https://user-images.githubusercontent.com/62955221/83321903-a2fbef00-a229-11ea-81bf-e90c55e149a0.png)

**Closed** 2020-05-30 11:54 UTC
Labels: Distro Family: Debian, Steam client, localization
