### ISSUE TITLE
Steam segfaults on startup Ubuntu 20.04

### ISSUE THREAD

**Issue by ryandgoldenberg1** [ValveSoftware/steam-for-linux#7556] opened 2020-12-19 14:11 UTC
#### Your system information

* Steam client version (build number or date): 1:1.0.0.67 i386
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

Using cuda version 11.2

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I expected that after installing Steam, the `steam` command would launch the Steam app.
Instead it crashed with a Segmentation fault, see output below.

#### Steps for reproducing this issue:

1. Download "steam_latest.deb" from https://store.steampowered.com/about/
2. Install via `sudo apt-get install ./steam_latest.deb`
3. Run `steam`

#### Output

```bash
ryan@drogon:~$ steam
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/ryan/.local/share/Steam/ubuntu12_32/steam
[2020-12-19 09:06:33] Startup - updater built Dec  7 2020 18:04:23
Installing breakpad exception handler for appid(steam)/version(1607372145)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
SteamUpdateUI: An X Error occurred
X Error of failed request:  GLXBadContext
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  45
xerror_handler: X failed, continuing
Major opcode of failed request:  151 (GLX)
Minor opcode of failed request:  6 (X_GLXIsDirect)
Serial number of failed request:  46
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2020-12-19 09:06:33] Loading cached metrics from disk (/home/ryan/.local/share/Steam/package/steam_client_metrics.bin)
[2020-12-19 09:06:33] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2020-12-19 09:06:33] Using the following download hosts for Public, Realm steamglobal
[2020-12-19 09:06:33] 1. http://client-download.steampowered.com, /client/, Realm 'steamglobal', weight was 100, source = 'baked in'
[2020-12-19 09:06:33] 2. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1607372145)
[2020-12-19 09:06:33] Checking for update on startup
[2020-12-19 09:06:33] Checking for available updates...
[2020-12-19 09:06:33] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1607372145)
[2020-12-19 09:06:33] Download skipped: /client/steam_client_ubuntu12 version 1607372145, installed version 1607372145, downloaded version 0
[2020-12-19 09:06:33] Nothing to do
[2020-12-19 09:06:33] Verifying installation...
[2020-12-19 09:06:33] Performing checksum verification of executable files
[2020-12-19 09:06:34] Verification complete
Loaded SDL version 2.0.13-6246010
Gtk-Message: 09:06:34.346: Failed to load module "gail"
Gtk-Message: 09:06:34.346: Failed to load module "atk-bridge"

(steam:55215): Gtk-WARNING **: 09:06:34.351: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru/gtk-2.0/main.rc:775: error: unexpected identifier 'direction', expected character '}'

(steam:55215): Gtk-WARNING **: 09:06:34.352: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  151
Serial number of failed request:  51
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151
Value in failed request:  0x0
Serial number of failed request:  50
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  151
Serial number of failed request:  52
xerror_handler: X failed, continuing
assert_20201219090633_1.dmp[55287]: Uploading dump (out-of-process)
/tmp/dumps/assert_20201219090633_1.dmp
/home/ryan/.local/share/Steam/steam.sh: line 750: 55215 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
ryan@drogon:~$ assert_20201219090633_1.dmp[55287]: Finished uploading minidump (out-of-process): success = yes
assert_20201219090633_1.dmp[55287]: response: CrashID=bp-e99634dd-42da-4233-94e9-1867c2201219
assert_20201219090633_1.dmp[55287]: file ''/tmp/dumps/assert_20201219090633_1.dmp'', upload yes: ''CrashID=bp-e99634dd-42da-4233-94e9-1867c2201219''
```

**Comment by kisak-valve** [comment] 2020-12-19 14:21
Hello @ryandgoldenberg1, swrast is mesa's slower cpu opengl renderer and the fact Steam is trying to use it and failing hints that you're using the nVidia proprietary driver, but don't have nVidia's 32 bit userspace installed.

nVidia's CUDA PPA does not provide 32 bit userspace support for OpenGL  and Vulkan. This needs to be resolved by the nVidia PPA maintainers and is being tracked at #5778. If the CUDA PPA wasn't involved, I would have suggested you find what driver series you're using, then install `libnvidia-gl-455:i386` after adjusting 455 to the driver series you have installed.

Closing as a duplicate of #5778.

**Closed by kisak-valve** 2020-12-19 14:21 UTC
