### ISSUE TITLE
Slow download games only on linux client

### ISSUE THREAD

**Issue by fabry92** [ValveSoftware/steam-for-linux#4518] opened 2016-06-26 11:29 UTC
#### Your sistem information

* Steam client version: 1466649529
* Distribution (e.g. Ubuntu):  Ubuntu 16.04 gnome
* Opted into Steam client beta?: [Yes/No]  Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

I download slower only on steam linux client than windows version. The problem is described here: http://steamcommunity.com/app/221410/discussions/2/616189106498372437/

**Comment by Tele42** [comment] 2016-06-26 11:51
Duplicate of #2573 / #2645.

This is a known issue most likely related to the large amount of DNS queries that is hidden on Windows by a system caching mechanism, but flood the DNS server with the Mac and Linux client.

**Comment by gdrewb-valve** [comment] 2016-06-26 17:38
Closing duplicate.

**Closed by gdrewb-valve** 2016-06-26 17:38 UTC

**Comment by fabry92** [comment] 2016-06-26 18:04
lol instead close fix it XD there is this bug from 3 years! wtf ahah
