### ISSUE TITLE
All steam games freeze on black screen with mouse cursor.

### ISSUE THREAD

**Issue by roboman2444** [ValveSoftware/steam-for-linux#3091] opened 2014-01-12 01:59 UTC
After steam client updated itself...
When launching any steam game (tried serious sam 3, source based games, natural section 2, metro last light, etc) the entire screen goes black, and only a movable mouse cursor is left. In order to get out of this, one must go down a runlevel, and send signal 9 (with killall -9) to the game process. Big picture mode also does the same.
Before the update this hasn't happened to me.

I am running a Nvidia 770gtx 4gb on a AMD fx8320 with 24 gb of ram. 64 bit Debian testing. Kernel 3.11.2-amd64. Graphics drivers have been re-installed and updated, and it hasn't fixed it.

I am reasonably sure that this has nothing to do with my graphics drivers, as it has only started happening after steam client update. Also, 32 bit games and 64 bit games work just as usual on my system, even ones that require or use OpenGL 4. Heck, even wine works just fine.
I have looked in the console output for steam, but i haven't noticed anything strange.

**Comment by kisak-valve** [comment] 2017-10-27 14:34
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by Kixu** [comment] 2017-10-31 10:42
I hadn't encountered it since this thread, I don't use big picture mode normally so I just tried it and got the black screen and had to terminate steams process. However after I relaunched steam and went back into big picture mode it worked fine.

**Comment by kisak-valve** [comment] 2017-12-08 14:39
Thanks for the feedback @Kixu. Closing as the original issue does not seem to appear in the wild anymore.

If you can find some way to reliably reproduce the black screen with big picture mode, please open a new issue report.

**Closed by kisak-valve** 2017-12-08 14:39 UTC
Labels: Need Retest, reviewed
