### ISSUE TITLE
[L4D2] Unable to import custom spray

### ISSUE THREAD

**Issue by eggman314** [ValveSoftware/steam-for-linux#2401] opened 2013-05-05 16:32 UTC
Tried to import the same spray I use in L4D2 for windows, and also in TF2 for Linux, got the below error message. Restarting Steam as suggested did not help.

![2013-05-05_00001](https://f.cloud.github.com/assets/3087751/463794/3a399b5e-b59e-11e2-8880-2c029f39ba7e.jpg)

Processor Information:
    Vendor:  GenuineIntel
    Speed: 3501 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.7.0-7-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11302902
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 560 Ti/PCIe/SSE2

```
Driver Version:  4.3.0 NVIDIA 313.30
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x1200
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1200
Desktop Resolution: 1920 x 1200
Primary Display Size: 20,39" x 12,76"  (24,02" diag)
                                        51,8cm x 32,4cm  (61,0cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  16005 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  938898 Mb
    Largest Free Hard Disk Block:  848233 Mb

Installed software:

Recent Failure Reports:
    Sun May  5 16:02:02 2013 GMT: file ''/tmp/dumps/assert_20130505180202_1.dmp'', upload no: ''Failure when receiving data from the peer''
    Sun May  5 16:28:39 2013 GMT: file ''/tmp/dumps/crash_20130505182829_1.dmp'', upload yes: ''CrashID=bp-f0fba706-615d-461f-9344-5a4752130505
    ''

**Comment by kisak-valve** [comment] 2016-12-22 23:54
Closing as a duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/705.

**Closed by kisak-valve** 2016-12-22 23:54 UTC
Labels: reviewed
