### ISSUE TITLE
Disappear buttons in globalmenu

### ISSUE THREAD

**Issue by kirill85** [ValveSoftware/steam-for-linux#2399] opened 2013-05-05 14:12 UTC
While running Steam, the rest of the windows of the global menu buttons disappear when you move the mouse over them.  This is manifested for the windows wide open on the screen.

My distro - Ubuntu 12.04.2 64 bit.

Version Steam: 1.0.38
Version kernel: 3.5.0-28.
Nvidia drivers 310.14

**Comment by kisak-valve** [comment] 2017-04-30 00:42
Closing due to insufficient information to make an assessment. Most likely a duplicate of #663.

**Closed by kisak-valve** 2017-04-30 00:42 UTC
Labels: reviewed, Steam client
