### ISSUE TITLE
Invalid SSL Certificate for steamcommunity.com

### ISSUE THREAD

**Issue by minj** [ValveSoftware/steam-for-linux#3735] opened 2015-02-23 19:55 UTC
```
Invalid SSL Certificate

The SSL certificate for https://steamcommunity.com/market/eligibilitycheck/?goto=%2Fid%2Flinux-MJ%2Finventory%2F is invalid and the page will not be loaded.
```

I am seeing this screen when accessing inventory in the steam client with STEAM_RUNTIME=0

```
Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.18.7-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  Openbox
    Steam Runtime Version:  <runtime disabled>
    LANG:  lt_LT.UTF-8
    lib32-libgcrypt15 1.5.3-2
    lib32-nss 3.17.3-1
    lib32-libsoup 2.48.0-1
    lib32-libnl 3.2.25-1.1
    lib32-networkmanager 0.9.8.10
    lib32-tcp_wrappers 7.6-17
    lib32-libcurl-gnutls 7.40.0-0
```

**Comment by vincent-t** [comment] 2015-02-23 19:57
Same issue here, also using manjaro.

**Comment by Oxalin** [comment] 2015-02-24 06:01
Also confirmed on Arch linux (obviously). Happens when trying to access inventory or gifts.

**Comment by alexandruianu** [comment] 2015-02-25 20:25
It seems to be an issue running when without the steam runtime only.

**Comment by minj** [comment] 2015-02-25 20:26
That's why it was mentioned in the original report.

**Comment by jeifour** [comment] 2015-05-01 11:58
Can confirm having the same issue when using Steam with Manjaro x64 and native libraries instead of Valve's libraries. Any ideas what is going wrong here? I mean I don't see why SSL cert of steamcommunity.com should be treated as invalid, seems to be signed by DigiCert.

**Comment by Oxalin** [comment] 2015-05-01 16:21
@jeifour I might have a clue: I'm using the alucryd repository with Arch and installing the steam-libs package help me and I don't have this problem anymore.

I was suspecting the problem to come from libgcrypt, so I installed (and created packages on AUR) with a different version of libgcrypt. You'll need lib32-libgcrypt15-git and libgcrypt15-git if you want to use the latest 1.5 branch, or simply the not-git version (remove the "-git" at the end). From what I know, the API version has changed since the 1.5 branch, but Steam seems to rely on the 1.5 branch API (version 11). You could give it a try.

**Comment by kisak-valve** [comment] 2017-05-19 14:37
Hello, is anyone still experiencing this issue with an up to date system?

**Comment by Oxalin** [comment] 2017-05-21 22:07
Well, on Arch Linux, the steam-native-runtime package still has libgcrypt as a dependency. I could remove this "empty" package with libgcrypt to test it if you want.

**Comment by Oxalin** [comment] 2017-05-22 18:56
After removing steam-native-runtime and libgcrypt15 and restarting Steam, it seems to work correctly. If it has to do with a different dependency, then I'm not aware of it.

**Comment by kisak-valve** [comment] 2017-05-22 19:20
Thanks for retesting @Oxalin. Closing.

**Closed by kisak-valve** 2017-05-22 19:20 UTC
Labels: Distro Family: Arch, Need Retest, reviewed

**Comment by nghtstr** [comment] 2018-08-08 21:05
I am also on Manjaro (Arch) trying to run Windows Steam through Wine. I am continually getting the invalid certificate error, as well as seeing the dreaded Red X through the lock. I am able to download games that I have, but games that are not in my Library I cannot get access to.
