### ISSUE TITLE
Please allow steam to be resized horizontally at 960 pixels or less. 

### ISSUE THREAD

**Issue by codedcosmos** [ValveSoftware/steam-for-linux#5606] opened 2018-08-05 01:28 UTC
#### Your system information

Steam version:
Built: Aug 1 2018, at 22:27:11
Steam API v018
Package versions 1533163808

Linux distro:
Arch linux, 4.17.11 using gnome desktop

Opted into Steam client beta?:
Used to but not currently.

Have you checked for system updates?:
No, but it usually auto updates

#### Please describe your issue in as much detail as possible:
The main window (Not the friends tab, rather the one with the store, library, community etc tabs) cannot resize below 1010 pixels horizontally (I got that number from screenshotting just the steam window itself and seeing the size of the window, though I already knew it was larger then 960). This is slightly problematic as I prefer to split two windows on my side monitor giving them 960 pixels each (on a 1080p display and since the width is 1920, 960 is half of that).

#### Steps for reproducing this issue:

Attempt to resize the window as much as possible to the left. (shrink horizontally)

**Comment by Managor** [comment] 2019-11-08 13:48
Please add this. It's a giant pain in the ass to not have Steam be able to split itself in half on a resolution that according to Steam hardware survey accounts for 64.58% of the userbase.
There's also some oddity with this behavior as I've sometimes been able to split it and sometimes not but I haven't been able to find the root cause of that. I don't want to use small mode either.

**Comment by Managor** [comment] 2020-02-09 19:43
This might partly be fixed or it's my DE allowing for this behavior. https://youtu.be/ianAIyPb1HI
I would still like for steam to allow 960 pixel horizontal resize.

**Comment by codedcosmos** [comment] 2020-02-09 23:54
@Managor I believe you are tiling your windows left and right, but they are not half the size of your window. You can tell if you put your cursor in the middle of your window and see that they always overlap that point. That is the current behavior of most desktop enviroments.

**Comment by Managor** [comment] 2023-06-18 12:37
This has been fixed for me. The steam window can be resized to 288px wide if I tile the window to the side in KDE. Without tiling the minimum window width is 1010px.

**Comment by zjeffer** [comment] 2023-07-07 15:21
The new steam UI pretty much fixed this issue for me. The steam window can be resized as small as I want, although when resizing smaller than about 650px in width, the minimize/maximize/close buttons in the top right start to disappear:

https://github.com/ValveSoftware/steam-for-linux/assets/4633209/d3fcc700-fb19-4a55-8b02-db0feb378463

But I don't think that's a big problem.

**Comment by Managor** [comment] 2024-04-20 04:34
@kisak-valve This can be closed. It has been confirmed fixed long ago.

**Comment by kisak-valve** [comment] 2024-06-01 01:04
Closing per the last couple comments.

**Closed by kisak-valve** 2024-06-01 01:04 UTC
Labels: Feature Request, Steam client, Need Retest
