### ISSUE TITLE
Streaming from linux to SteamOS or Steam Link with Dualshock 4 crashes host

### ISSUE THREAD

**Issue by GrayBoltWolf** [ValveSoftware/steam-for-linux#5983] opened 2018-12-24 15:26 UTC
#### Your system information

Operating System Version:
    Debian GNU/Linux buster/sid (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.18.0-3-amd64

Processor Information:
    CPU Brand:  Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

Memory:
    RAM:  31681 Mb

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1070 
    Driver Version:  4.6.0 NVIDIA 390.87
    OpenGL Version: 4.6

* Steam client version (build number or date): Nov 26th 2018
* Distribution (e.g. Ubuntu): Debian 9.6
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Streaming any game from Debian host to SteamOS or SteamLink with a Dualshock 4 controller connected to the client crashes Steam on the host as soon as the game is launched. Controller and streaming work fine if the controller is connected to the host. Steam does not log any errors during the crash.

Tested with Battleblock Theater, Portal 2, and DIRT Rally.

Controller works fine navigating Big Picture Mode menus on the SteamOS or Steam Link client.

###### Steps for reproducing this issue:

1. Pair or connect Dualshock 4 controller to SteamOS or Steam Link.
2. Launch a game stream from the Debian host PC.

##### Bootstrap log:
[2018-12-24 10:15:02] Startup - updater built Nov 26 2018 20:15:21
[2018-12-24 10:15:02] Checking for update on startup
[2018-12-24 10:15:02] Checking for available updates...
[2018-12-24 10:15:02] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
[2018-12-24 10:15:03] Download skipped: /client/steam_client_ubuntu12 version 1543346820, installed version 1543346820
[2018-12-24 10:15:03] Nothing to do
[2018-12-24 10:15:03] Verifying installation...
[2018-12-24 10:15:03] Performing checksum verification of executable files
[2018-12-24 10:15:03] Verification complete
[2018-12-24 10:16:53] Shutdown

##### Streaming log:
[2018-12-24 10:15:00] Streaming started to steamos at 10.1.255.247:37500, audio channels = 2, MTU = 1468
[2018-12-24 10:15:00] Streaming quality: k_EStreamQualityBalanced
[2018-12-24 10:15:00] Streaming bitrate: Automatic
[2018-12-24 10:15:00] Maximum capture: 1920x1080 59.75 FPS
[2018-12-24 10:15:00] Video Streaming: enabled
[2018-12-24 10:15:00] Audio Streaming: enabled
[2018-12-24 10:15:00] Input Streaming: enabled
[2018-12-24 10:15:00] =====================================================================
[2018-12-24 10:15:00] Game: Portal 2 (620)
[2018-12-24 10:15:00] Setting target bitrate to 15000 Kbit/s, burst bitrate is 75000 Kbit/s
[2018-12-24 10:15:00] Recording system audio
[2018-12-24 10:15:00] Streamed game has created a window
[2018-12-24 10:15:00] Bringing streamed game to foreground - failed
[2018-12-24 10:15:00] Audio mix: start=30413070071, returned=0
[2018-12-24 10:15:00] Audio source [System Pulse]: init=0, through=0, last_start=0, mixed=0, drop_before=0, drop_after=0
[2018-12-24 10:15:00] Changing record window: 0x520000b
[2018-12-24 10:15:01] >>> Switching video stream from NONE to Desktop_MovieStream
[2018-12-24 10:15:01] Detected 8 logical processors, using 4 threads
[2018-12-24 10:15:01] >>> Capture method set to Desktop OpenGL NV12 + libx264 main (4 threads)
[2018-12-24 10:15:01] >>> Capture resolution set to 1920x1080
[2018-12-24 10:15:01] >>> Client video decoder set to VAAPI hardware decoding
[2018-12-24 10:15:01] Detected 8 logical processors, using 4 threads

##### Controller log:
[2018-12-24 10:11:06] No cached sticky mapping in ActivateActionSet.
[2018-12-24 10:12:29] No cached sticky mapping in ActivateActionSet.
[2018-12-24 10:14:59] Opted-in Controller Mask for AppId 620: 0
[2018-12-24 10:15:01] Remote Device Found
  type: 054c 09cc
  path: /dev/hidraw7
  serial_number: f4:93:9f:c3:32:38 - 0

[2018-12-24 10:15:01]   Manufacturer: Sony Interactive Entertainment
[2018-12-24 10:15:01]   Product:      Wireless Controller
[2018-12-24 10:15:01]   Release:      100
[2018-12-24 10:15:01]   Interface:    3
[2018-12-24 10:15:01] !! Steam controller device opened for index 0.
[2018-12-24 10:15:02] Controller 0 mapping uses xinput : false
[2018-12-24 10:15:05] Opted-in Controller Mask for AppId 0: 0
[2018-12-24 10:16:52] Exiting workitem thread
[2018-12-24 10:16:56] Opted-in Controller Mask for AppId 0: 0

**Comment by graycrofford** [comment] 2018-12-24 19:10
Just tested with the Android Steam Link app, same issue. With the DS4 connected to my Android phone, I can navigate the menus but as soon as I start streaming, Steam on the host crashes.

**Comment by graycrofford** [comment] 2018-12-24 19:14
Interesting, if I enable "Playstation Configuration Support" on the host, Steam immediately crashes. (no streaming involved)

**Comment by graycrofford** [comment] 2018-12-24 19:18
#4891 

I believe this is related to this issue.

**Comment by evgG** [comment] 2019-02-08 22:30
Hi,
I had almost same issue and problem was on pulseaudio.
Please look at #4753.
I've resolved my problem when changed /etc/pulse/default.pa:
```
#set-default-sink output
#set-default-source input
set-card-profile 1 output:analog-stereo
set-default-sink 1
```

**Comment by kisak-valve** [comment] 2019-07-19 14:22
Hello @GrayBoltWolf, @evgG, can you check if you're still experiencing this issue on an up to date system?

"Fix crash caused by audio cards with no active port set" in the [2019-07-16](https://store.steampowered.com/news/52467/) Steam client update may have had an effect for Dualshock 4 users.

**Comment by kisak-valve** [comment] 2019-08-23 15:26
Closing pending feedback.

**Closed by kisak-valve** 2019-08-23 15:26 UTC
Labels: 3rd party game, Distro Family: Debian, General controller / Steam Input, Need Retest, Steam client, Streaming

**Comment by GrayBoltWolf** [comment] 2019-09-21 01:30
> Closing pending feedback.

Apologies, yes it has been resolved.

Thanks!
