### ISSUE TITLE
Can't start Steam since yesterday: "Fatal Error: Failed to load steamui.so"

### ISSUE THREAD

**Issue by Johnnii360** [ValveSoftware/steam-for-linux#8760] opened 2022-08-25 11:57 UTC
#### Your system information

* Steam client version (build number or date): Dunno, I think the latest (can't get version info)
* Distribution (e.g. Ubuntu): Ubuntu 22.04.1 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam doesn't start anymore since yesterday. When I start Steam I always get this error:

![Bildschirmfoto vom 2022-08-25 10-22-11](https://user-images.githubusercontent.com/15824634/186657078-1c053038-6e5d-414f-8852-567ed84aa7dd.png)

Here the log when I start Steam from terminal: https://gist.github.com/Johnnii360/b15175938ff5e595f554eb482c170368
My sysinfo: https://gist.github.com/Johnnii360/f676617af3126bd98d55204c8937e731

#### Steps for reproducing this issue:

1. Rename `~.steam ` and `~.local/share/Steam` to ...-old
2. Start Steam and let update run
3. Error occures

I also purged Steam and tried to reinstall it over Ubuntu repo and your .deb file. But nothing worked. I did yesterday a `apt autoremove` but I have no idea if this caused the issue?

**Comment by kisak-valve** [comment] 2022-08-25 12:24
Hello @Johnnii360, `Failed to load steamui.so - dlerror(): /home/johannes/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libva-x11.so.2: undefined symbol: va_fool_postp` in your log is the key detail and makes this issue a duplicate of #8673.

There's a good chance that `sudo apt install libva-x11-2:i386` will workaround this issue.

Closing as a duplicate.

**Closed by kisak-valve** 2022-08-25 12:24 UTC

**Comment by Johnnii360** [comment] 2022-08-25 12:36
Awesome! Thanks @kisak-valve , you're my hero today! :)
