### ISSUE TITLE
Link can't stream Big Picture or desktop in Ubuntu 17.10

### ISSUE THREAD

**Issue by coaxial** [ValveSoftware/steam-for-linux#5269] opened 2017-12-02 17:55 UTC
#### Your system information

* Steam client version (build number or date): Oct 30 2017, at 19:09:46
* Distribution (e.g. Ubuntu): Ubuntu 17.10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Connect the Steam link to my TV, launch Steam client, start streaming. It starts Big Picture mode on the computer, but the display on the TV is black while playing the computer's sound (the computer is playing the sound as well, it isn't muted). I can see the cursor moving around but I won't get any image on the TV until a game is launched. It is streaming because I can see the cursor on the TV, but it has a black background (i.e. no desktop or big picture showing). I tried with wired and ac WiFi.

#### Steps for reproducing this issue:

1. Start Link
2. Connect to host via Link
3. Big Picture starts on host, moving cursor + black background on Link

#### Steam system information:

https://gist.github.com/coaxial/9b897833d5c2e619031111724b16b92a

**Comment by kisak-valve** [comment] 2017-12-02 18:37
Hello @coaxial, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. In particular, it would be good to know what video driver version is being used by the host system.

On the host system, if you go to Settings -> In-Home Streaming -> Advanced Host Options and disable hardware encoding, does that make a difference?

**Comment by coaxial** [comment] 2017-12-02 23:22
I updated the original comment with my system information. If I disable hardware encoding, it makes no difference re the display issue.

**Comment by xplt** [comment] 2017-12-31 18:39
I think I have the same issue: I use Ubuntu 17.10 on host system and also the only thing I see on Steam link is a black screen with moving cursor (I use Steam Controller, attached to Steam Link).
On host system it looks like this:
![steam-link-streaming-start](https://user-images.githubusercontent.com/6225402/34463601-13d5b90e-ee72-11e7-8d76-377b969cdecd.png)
Glowing border around Library and other animations still work, though I can't move focus to any other element neither by Steam Controller on Steam Link, nor with keyboard/mouse on my PC.
Sometimes, host PC gets stuck (Gnome3 offers to forcefully close unresponsive Steam client) and after a while it shows this message:
![steam-link-streaming-end](https://user-images.githubusercontent.com/6225402/34463611-69e1f092-ee72-11e7-8570-1ee85f5852c9.png)

My system:
https://gist.github.com/xplt/b46632fb762e349545be69fc056a3510

**Comment by kisak-valve** [comment] 2017-12-31 18:43
Hello @xplt, can you check if you're user session is a Gnome/Wayland or a Gnome/X session? If it's Gnome/Wayland, then please test if Gnome/X is also affected.

**Comment by xplt** [comment] 2017-12-31 18:49
According to GNOME Display Manager, this is "Gnome on Xorg".

**Comment by kisak-valve** [comment] 2018-01-13 02:20
From #5336, does it make a difference if there is no controller attached to the Steam Link?

**Comment by xplt** [comment] 2018-01-13 04:35
With replica of wired Xbox360 controller, I don't see any differences...

**Comment by xplt** [comment] 2018-01-15 04:58
The same happens on SteamOS (Beta / Desktop mode): https://gist.github.com/xplt/00ad5370d73b1b69c24c688591201bcf If you want, I can shoot a video of what's going on.

**Comment by kisak-valve** [comment] 2020-04-17 13:16
Hello @coaxial, @xplt, are either of you still experiencing this issue on an up to date system?

**Comment by xplt** [comment] 2020-04-17 13:26
I'll try it on the weekend. I still have SteamOS, plus now I have Fedora 31. To be honest, I thought that VALVe stopped supporting Link after it's deprecation...

**Comment by kisak-valve** [comment] 2020-05-22 13:32
Closing pending feedback.

**Closed by kisak-valve** 2020-05-22 13:32 UTC
Labels: Big Picture, Need Retest, Streaming

**Comment by coaxial** [comment] 2020-05-22 13:57
Sorry I can't test it, I returned my steamlink to the store because I couldn't get it to work with Linux.

**Comment by benefacto** [comment] 2020-12-20 00:51
> Closing pending feedback.

Hi @kisak-valve , I am experiencing this same issue as well on a Gnome Wayland desktop environment running Debian 10 buster. [Here is a gist](https://gist.github.com/benefacto/bf8da1c8474e8f93346b59b2cd222cec) of my system info. I was referred here by Steam Help Request HT-KW28-WTPB-YJQ8. 

I have unsuccessfully attempted the following to resolve the issue:
- Toggling of Hardware Encoding
- Opt in to Steam Client Beta
- Confirm system is up to date
- Confirm no controller is attached to the Steam Link
- Search the Steam Community and GitHub for workarounds or alternatives

I would appreciate any help you would be able to offer.

**Comment by kisak-valve** [comment] 2020-12-20 01:07
Hello @benefacto, looks like #6148 describes your issue and using a GNOME/X session may workaround the issue.

**Comment by benefacto** [comment] 2020-12-20 21:13
> 
> 
> Hello @benefacto, looks like #6148 describes a similar scenario as your issue and using a GNOME/X session may workaround the issue.

Thanks! I can confirm that following [these steps](https://www.youtube.com/watch?v=4LwldvmNBVE) to switch from Wayland to Xorg resolved my issue.

**Comment by Compizfox** [comment] 2021-07-27 22:30
Also having the same issue with Plasma Wayland.

Switching back to X11 is a workaround at best, not a solution. Steam should use xdg-desktop-portal to capture the screen on Wayland.
