### ISSUE TITLE
Dota 2 CM Portrait Bug

### ISSUE THREAD

**Issue by dbass81** [ValveSoftware/steam-for-linux#3386] opened 2014-06-29 17:21 UTC
![screenshot from 2014-06-29 11 13 34](https://cloud.githubusercontent.com/assets/5233000/3423908/bcf3421c-ffb1-11e3-8026-481349745df3.png)

Crystal Maiden's portrait goes bald after respawning.  It only occurs wearing a certain headset called "Yulsaria's Glacier".

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0xf
    CPU Model:  0x6b
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2100 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Debian GNU/Linux testing (jessie) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.14-1-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Openbox
    Steam Runtime Version:  steam-runtime-release_2014-04-15

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD TURKS

```
Driver Version:  3.0 Mesa 10.1.4
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x6758
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1600 x 900
Desktop Resolution: 1600 x 900
Primary Display Size: 17.01" x 9.45"  (19.45" diag)
                                        43.2cm x 24.0cm  (49.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC889A

Memory:
    RAM:  3962 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  107942 Mb
    Largest Free Hard Disk Block:  70760 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment] 2018-02-23 14:57
Hello @dbass81, @Storm-Engineer, if either of you are able to reproduce this issue with an up to date system, please open a new issue report in the [Dota-2](https://github.com/ValveSoftware/Dota-2/) issue tracker.

Closing as there's been too much churn in Dota 2 since this issue report and if this is still occurring, then it will need a new investigation.

**Closed by kisak-valve** 2018-02-23 14:57 UTC
Labels: reviewed
