### ISSUE TITLE
Restore button won't change to Maximize while there is updating window.

### ISSUE THREAD

**Issue by ccxex29** [ValveSoftware/steam-for-linux#6089] opened 2019-02-13 07:56 UTC
#### Your system information

* Steam client version (build number or date): Feb 8 2019, at 22:05:22 (1549672548)
* Distribution (e.g. Ubuntu):  Manjaro Linux 64-bit
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Desktop Environment/Window Manager: KDE Plasma 5.14.5

#### Please describe your issue in as much detail as possible:
I can't maximize after restoring the steam window while there is a window for waiting to be updated game.
If needed, here's the screen capture: [https://youtu.be/eY_-Yh5Oktg](https://youtu.be/eY_-Yh5Oktg)

#### Steps for reproducing this issue:

1. Maximize Steam with maximize button
2. Restore steam with restore button 
3. Maximize steam with maximize button. (in my case, the button is still restore thus can no longer maximize it except using window manager options.)

**Comment by kisak-valve** [comment] 2019-02-13 12:54
Hello @ccxex29, what DE are you using? Please check if this issue report is a duplicate of #3792.

**Comment by ccxex29** [comment] 2019-02-13 14:13
@kisak-valve I'm using KDE Plasma. 
I don't think it is a duplicate. While I can't resize steam window either, I can maximize using window manager's snap top to maximize and restore by dragging the window while being maximized. Furthermore, I no longer think updating is a part of the problem.

**Comment by McMarius11** [comment] 2019-04-15 16:46
i have the same problem with #3792.
running Kubuntu 18.04 LTS

**Comment by McMarius11** [comment] 2019-06-12 15:33
I think KDE Plasma 5.16 or the new Steam Beta fixed it! :) <3

now it works flawless

**Comment by kisak-valve** [comment] 2019-07-12 15:02
Closing per the last comment.

**Closed by kisak-valve** 2019-07-12 15:02 UTC
Labels: Need Retest, Steam client, Window manager
