### ISSUE TITLE
Steam wont start after latest beta update - libpipewire-0.3.so.0 missing

### ISSUE THREAD

**Issue by echaskaris** [ValveSoftware/steam-for-linux#7807] opened 2021-05-24 19:09 UTC
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: [Yes/No] y
* Have you checked for system updates?: [Yes/No] y

You are missing the following 32-bit libraries, and Steam may not run:
libpipewire-0.3.so.0

And then: Failed to load steamui.so

**Comment by tgurr** [comment] 2021-05-24 19:31
Short workaround to switch back to stable without resetting steam, just delete the file `.steam/steam/package/beta` and run steam, it will download and run the stable version of the client and you'll need to join the beta program again if desired.

On topic, steam didn't have a dependency on pulseaudio 32bit before, at least on my system it worked perfectly fine without it, it would be a real bummer if pipewire 32bit libs would be indeed needed on the host in the future, so I really hope this is just a bug that slipped in the beta.

**Comment by 414n** [comment] 2021-05-24 19:36
Have it too on a Slackware64 14.2 system. Before updating to latest client beta there was no hard requirement for it.
I tried building latest 0.3 version of pipewire to make the client happy, but came across some issues.

 - Steam client version (build number or date): 
 - Distribution: Slackware64 14.2
 - Opted into Steam client beta? Yes
 - Have you checked for system updates? n

**Comment by KeepBotting** [comment] 2021-05-24 19:46
Getting this too on Ubuntu 20.10, installing 32-bit Pipewire packages from Debian satisfies the dependency and Steam is able to launch just fine.

Excited to see Pipewire support in the works! Glad to be a beta tester!

**Comment by xanscale** [comment] 2021-05-24 19:54
https://packages.ubuntu.com/search?keywords=pipewire

I think the problem is that ubuntu doesn't really have 32bit pipewire overall

**Comment by Bednar87** [comment] 2021-05-24 20:03
> https://packages.ubuntu.com/search?keywords=pipewire
> 
> I think the problem is that ubuntu doesn't provide 32bit pipewire overall

Arch doesn't either, at least not in official repos. You can build the library via a package in AUR though.

**Comment by MurdoMaclachlan** [comment] 2021-05-24 20:07
I also have this on Slackware Current, which like Slackware 14.2, Ubuntu and Arch, doesn't have 32bit package in official repos, nor in any repos I could find.

**Comment by Nisc3d** [comment] 2021-05-24 20:09
lib32-pipewire is available in the AUR: https://aur.archlinux.org/pkgbase/lib32-pipewire/
After installing it on Arch it worked for me again.

**Comment by TTimo** [comment] 2021-05-24 20:15
beta shipped with an outdated runtime, will be fixed in next iteration. still, it's a good idea to install `lib32-pipewire` on your host also.

**Comment by MurdoMaclachlan** [comment] 2021-05-24 20:38
What of distros that don't have a `lib32-pipewire` package available? Will there be any major loss of functionality for us?

**Comment by TTimo** [comment] 2021-05-24 20:41
You should be just fine using the steam runtime's libpipewire.

**Comment by vchernin** [comment] 2021-05-24 20:41
As a workaround [Steam beta in Flatpak](https://flathub.org/apps/details/com.valvesoftware.Steam) works for me on Fedora 34 Silverblue. I do not have `lib32-pipewire` installed on my host system.

**Comment by barredijkstra** [comment] 2021-05-24 20:45
> beta shipped with an outdated runtime, will be fixed in next iteration. still, it's a good idea to install `lib32-pipewire` on your host also.

Just for completeness sake: beta steam on ubuntu 21.04 running into the same issue.
And thanks for looking forward to it. Can we expect a depedency on libpipewire i386? Ubuntu does not provide a 32-bit version in their repositories and while a good number of the linux users probably know how to checkout/compile shared objects for their distro i suspect an even greater number of people might be running into issues there.

**Comment by TTimo** [comment] 2021-05-24 20:55
the steam runtime satisfies that dependency. having a 32 bit pipewire 0.3 client library on the host is entirely optional.

**Comment by JSchrtke** [comment] 2021-05-24 21:18
Seems this is now fixed already, just got another update to the runtime. Runs fine now on Ubuntu 20.04.1

**Comment by 414n** [comment] 2021-05-24 22:01
Yup, fixed for me too :+1: 
Thanks!

**Comment by MurdoMaclachlan** [comment] 2021-05-24 22:03
Fixed here as well! :D

**Closed** 2021-05-24 22:52 UTC
Labels: Need Retest, Steam client, runtime

**Comment by Termuellinator** [comment] 2021-05-28 07:47
> the steam runtime satisfies that dependency. having a 32 bit pipewire 0.3 client library on the host is entirely optional.

Some games don't work properly without STEAM_RUNTIME=0 though (Metro Exodus in my case), so it would be a REAL bummer if 32bit pipewire would be needed to run the native libs...

**Comment by zeparu** [comment] 2021-06-07 18:11
latest stable update for linux manjaro includes lib32-pipewire libraries now, however client is stuck on login-window trying to run it with native libraries. with included runtime, it still runs without problems. [here is the pastebin of the the entire terminal output trying to run steam with native libraries](https://pastebin.com/sizJk3Hm)

**Comment by kisak-valve** [comment] 2021-06-07 18:25
Hello @zeparu, running Steam with the Steam runtime disabled is not supported. Report the issue to the package maintainers that helped you disable it.

**Comment by zeparu** [comment] 2021-06-07 18:48
@kisak-valve i wrote a similar report on the manjaro forums, but i thought maybe somebody here might be able to see what exactly the issue is right now, looking at the pastebin

**Comment by luzfcb** [comment] 2021-06-09 13:41
I had this problem on Ubuntu 20.04. I opened a ticket in Ubuntu to handle the missing i386 version of libpipewire-0.3.

https://bugs.launchpad.net/ubuntu/+source/pipewire/+bug/1931312

**Comment by smcv** [comment] 2021-06-09 17:00
@Termuellinator writes:
> Some games don't work properly without STEAM_RUNTIME=0 though

That is never meant to be required: all native Linux games on Steam are meant to use the Steam Runtime environment. Please report this problem to the affected game's developer.

It might also be helpful to open an issue on https://github.com/ValveSoftware/steam-runtime with all the information that's requested in the issue template there. There might be an improvement we can make to the Steam Runtime to fix this game, or we might be able to help the game's developer understand what is wrong, or if neither of those is possible, we can at least have it listed as a known issue.

**Comment by smcv** [comment] 2021-06-09 17:05
@luzfcb writes:
> I had this problem on Ubuntu 20.04 [more recently than the fix for this issue landing in the beta]

Please open a separate issue with full details, including the version number of Steam and anything it shows when run from a terminal (gnome-terminal or xterm or similar). https://github.com/ValveSoftware/steam-for-linux/issues/7813#issuecomment-857851359 has some more information about Steam crashing on startup, and how you can provide the information that developers will need to be able to solve things like this.

In general, after an issue is closed, it is better to open a new issue rather than replying to the closed issue, even if your symptoms look similar. There are lots of reasons why Steam might crash!

**Comment by smcv** [comment] 2021-06-09 17:05
@zeparu writes:
> i thought maybe somebody here might be able to see what exactly the issue is [with using an unsupported "native" library stack]

Please don't request support here for unsupported configurations, particularly not on someone else's issue report. The more you distract Steam developers, the longer it will take for issues to be fixed.

**Comment by JooJooBee666** [comment] 2021-06-14 22:29
I'm stuck in a loop here with this problem.  I was on beta, but I don't have the .steam/steam/package/beta file.  I don't even have the package folder so I'm stuck...The only thing I could do was uninstall and reinstall the package from apt (the installer from the website won't work either) but after doing that, same problem.  How do I get this fixed?

**Comment by luzfcb** [comment] 2021-06-14 22:37
@JooJooBee666 Assuming it's the same problem I had

Run `steam --reset` and keep unchecked the option to save the password. If you check the option to save the password, the error will occur the next time you open steam.

Another way to solve the same problem is:
https://github.com/ValveSoftware/steam-for-linux/issues/7847#issuecomment-858328101

**Comment by JooJooBee666** [comment] 2021-06-14 23:05
That's no help.  I've already tried all that but it still fails to load.  If I do STEAM_RUNTIME=0 steam I get the following error: Running Steam on ubuntu 21.04 64-bit
STEAM_RUNTIME is disabled by the user
Error: You are missing the following 32-bit libraries, and Steam may not run:
libpipewire-0.3.so.0
Can't find 'steam-runtime-check-requirements', continuing anyway

After that, Failed to load steamui.so - dlerror(): libpipewire-0.3.so.0: cannot open shared object file: No such file or directory
I can't install that here on Ubuntu 21.04 so I have no Steam now.

**Comment by luzfcb** [comment] 2021-06-14 23:25
@JooJooBee666 per https://github.com/ValveSoftware/steam-for-linux/issues/7849#issuecomment-857930518 you must not use `steam` with `STEAM_RUNTIME=0`

**Comment by JooJooBee666** [comment] 2021-06-15 01:37
@luzfcb Ha! you're right.  It's working now if I don't save the password.  Thanks.  Hopefully they get this fixed.  I know I'm going to accidentally check that again and forcing me to do a reset. :+1:

**Comment by smcv** [comment] 2021-06-15 09:10
Crashing on login if you *do* save the password is a separate issue (#7813) and is being worked on. Workaround: don't let Steam save the password, or have fewer virtual network interfaces (Docker, libvirtd and the `ip6_gre` module seem to be common triggers for that crash).

**Comment by newbie78** [comment] 2021-06-21 16:26
> Crashing on login if you _do_ save the password is a separate issue (#7813) and is being worked on. Workaround: don't let Steam save the password, or have fewer virtual network interfaces (Docker, libvirtd and the `ip6_gre` module seem to be common triggers for that crash).

yes! you right.
when i'm stopped all docker stuff, error with libpipewire-0.3.so.0 is gone!
