### ISSUE TITLE
Steam Big Picture blank screen lock up on launch

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4396] opened 2016-04-10 17:12 UTC
Running Debian Jessie with nouveau / mesa 11.1

Desktop mode works fine, but upon launching Big Picture mode I hear the startup sound but the screen is blank, and I cannot close it, and there are no interaction sounds.  I have to do a hard reset.

**Comment by kisak-valve** [comment] 2019-04-26 15:54
Closing because the reporting user has turned into a ghost and general video driver quality of nouveau in 2016 is no longer relevant. If anyone can reproduce this issue on an up to date system, please open a new issue report with hardware and driver information and also let the video driver vendor know.

**Closed by kisak-valve** 2019-04-26 15:54 UTC
Labels: reviewed
