### ISSUE TITLE
Paid for Creativerse but can't have access to it

### ISSUE THREAD

**Issue by jbruni** [ValveSoftware/steam-for-linux#3869] opened 2015-06-03 22:58 UTC
I've just made a purchase while using Steam for Linux.
A birthday gift for my son.
Paid successfully using Paypal (I received confirmation from Steam and PayPal).
But nothing has been delivered to my son's email account.
Opened a support ticket there - 5011-ETIH-6050
But there is no answer. I'm afraid they may answer only after the birthday party, which is this Friday.
Please, help.
Thank you.

**Comment by MrSchism** [comment] 2015-06-04 22:17
This is more for technical issues than for account management.  Developers here, unfortunately, are not able to handle that issue.

I hope the email gets delivered and, barring that, support gets back to you.  Occasionally, emails can take a while to come through.  It may be worth checking again and ensuring that the email account it was sent to was, in fact, his.  This information should be on the Steam confirmation email.

Again, this is not the place to resolve this issue.  I'm sorry, but I have to close this ticket here.

**Closed by MrSchism** 2015-06-04 22:17 UTC

**Comment by Tele42** [comment] 2015-06-04 23:54
As a side note, Creativerse's store says it supports Windows and Mac, but does not list linux. If you click on Library, then select Games from the drop down, you should be able to see all games linked to the steam account, including games that do not have support for your current OS.

The game dev reported on a community thread that a linux native version was not planned: http://steamcommunity.com/app/280790/discussions/0/613936039473550355/ . That being said, some users have reported this game works in wine, but that is beyond the scope of this issue tracker.
Good luck getting a refund.

**Comment by jbruni** [comment] 2015-06-09 15:05
Thanks for the kind words. I tried contact through every channel possible: support, twitter, facebook, and so on. I was able to get an access key through Playful (who makes Creativerse). So, I was able to give the surprise gift to my son at his birthday party, last Friday. It was very nice.

From Steam, not even a single word. The support ticket remains untouched, unanswered. All my begging at their social network channels was solemnly ignored. Of course, I will never give a penny to this company anymore.

I recommended Playful to change their distribution channel to a better one. I bought Minecraft accounts for the whole family, and never had a single issue, minor or major. I told them Steam may be blocking more interested users/gamers/consumers as us to reach their product.

@Tele42 - The game was purchased as a gift. The recipient (my son) uses Windows. I only did the gift purchase using Lubuntu.

It is a shame - you developers doing a hard work at Steam for Linux, and bad practices from the company at sales and support leading the reputation to the ground (or below). Unfair.

Thanks again for the nice replies.

**Comment by MrSchism** [comment] 2015-06-09 16:26
Valve's support department is separated from their developers and from their social media group; those methods very, *very* rarely are able to close an account support ticket of that nature.

That being said, did the email ever go through?

I've never once experienced Steam not delivering a game, given that the email is correct.  Did your son check his spam folders?  If it's GMail, it may have gone to the "Promotions" tab.

In my eyes, having the game doesn't resolve the underlying issue and that's what I want to get to the bottom of.

**Comment by MrSchism** [comment] 2015-06-09 18:04
I'm interested in trying to get to the bottom of this.  I've just sent my friend a gift (from the Linux client) via email.

I do feel it's worth mentioning, however, that the Developers, Customer Support, and Social Media teams are usually pretty segregated in most organizations.  That's why customer support wouldn't get back to you from your issue here or from social media.

I just sent a friend a game via email and he received it.  It may be worth double-checking your son's Spam folder, trash, and (if Gmail) promotions tab.  I'm waiting on the email receipt on my end to see if it says what email address it was sent to.

I do know that it *does not* tell them in the client if they were emailed a game.

I do want to clarify: I am not a Valve developer, so I cannot access anything of theirs.  I am, however, a long time user of Steam and a huge fan of Valve.  I have never had an issue with gifting, so from my perspective, this is a very rare case.  It's unfortunate that you feel slighted and I'd like to assure you that support will look into the issue as soon as they can.  Part of the issue is that Valve just changed their return policies, so I'm sure that Support is getting higher than average support requests.

**Comment by jbruni** [comment] 2015-06-09 21:39
Spoiler: the email was there, unnoticed, at the "Promotions" tab (it is Gmail).

I do have access to my son's email - and immediately after sending the gift through Steam for Linux, as well as after re-sending through the store website, I entered his Gmail account to check for its delivery. I myself do not use a personal Gmail account. I use Yahoo and my own self-hosted Postfix + Roundcube webmail server. I do use computers since childhood and I am a developer myself... I have checked other folders, including "spam" and "social media"... but I didn't check this "promotions" tab. Maybe because it was meaningless to me? So out of my mental model of relating with emails?

I only did it now because of the comment here.

So, I can't tell if the gift email was already delivered at that time or not. Even if it was, as I've reported in the support ticket but not here, I entered the web store for another attempt of sending the gift, and the response message was like "*this gift has already been redeemed*". How could that be? I had just made the purchase, and checked the email (and found nothing). I thought someone else had somehow used the access code which was meant to be used by my son.

It worths mentioning nor me nor my son had an Steam account - everything was absolutely new and first-time for me.

**Comment by MrSchism** [comment] 2015-06-09 21:57
It was probably in the Promotions tab because your son didn't have a Steam account registered to that email address, so Gmail didn't have a history on which to set a baseline.  

As for why the gift was marked as redeemed, I can't answer that.  

When you said they gave you a key... was it a Steam key or a general use key on the developer's site?

By following the link in the email, it could get added to a steam account still.  Alternatively, you could request a refund.  I'd suggest adding it to a Steam account, as Steam has many benefits that can be thoroughly enjoyed... like having the entirety of your steam library available from one location (the library) as opposed to having to track down different installers from different locations.

**Comment by jbruni** [comment] 2015-06-17 11:43
You from community are great. Playful staff was the real "life-saviour", instantly resolved the issue with no-questions-asked.

Now, my bad impression over Steam only grows.

I had started a dispute at PayPal. I just closed it. I already realized the effort for a refund does not worth the refund. And considering my son actually can play the game (gifted by Playful), and also that it was me which didn't see the e-mail at the promotions tab, let them have themoney. It is as if I really bought the game.

Now, it was surprising to see a big red alert at Steam software announcing the PayPal dispute, telling me to close it, and blocking access to the game - due to the dispute! Can you believe it? This is so horrible I do not have words. This company reputation for me now is deep underground. They can have wonderful software and community. But policies and lack of support destroy all this wonderful value.

Meanwhile, support said:

```
Ask the sender to log in to their Steam account and navigate to the "Games" menu and select "Manage Gifts & Guest Passes".

From their Steam Inventory he/she should see the gift. Have the sender select it and click on "Re-send gift". Make sure he/she tries either sending it to a different e-mail address if your first one did not work or directly through Steam.

Once the sender re-sends the gift you should see a notification at the top of your Steam client and via e-mail that you have received a new gift.
```

So... they take a lot of time to reply... and the only thing they can say is "re-send the gift" - which I told them in the very first message I already tried, and it says the gift has been redeemed.

And if I again try now, it says:

```
An error was encountered while processing your request:
Sending and receiving gifts has been disabled for your account.
```

Possibly due to the Paypal dispute (not even a "claim", merely a "dispute").

From my son's side, if I click the gift link (now that we've found the email), after login it says the same: the gift has been redeemed.

Answering your question: the key given to me by Playful gave acces to the game through the Steam software. So, I believe it is a "Steam key".

**Comment by MrSchism** [comment] 2015-06-17 18:47
Steam's customer support page has been crazy lately due to their new policies.  It will likely require you clarifying in the ticket that you opened a PayPal dispute and closed it.  Explain why you opened it.

The reason they have to stop when you open a PayPal dispute is to help prevent fraud.  There have been several systems used to scam both Valve and its customers out of tons of cash over the years.   This system is inconvenient, but necessary to help keep Steam customers secure.
