### ISSUE TITLE
CS2 texture bug on AMD GPU

### ISSUE THREAD

**Issue by marshallovski** [ValveSoftware/steam-for-linux#11383] opened 2024-10-24 17:49 UTC
#### Your system information

* Steam client version (build number or date): 1726604483
* Distribution (e.g. Ubuntu): Debian GNU/Linux 12 (bookworm) (64 біт)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [logs.zip](https://github.com/user-attachments/files/17510825/logs.zip)
* Wayland session with KDE
* GPU: AMD Radeon RX 580 8GB
(polaris10, LLVM 15.0.6, DRM 3.49, 6.1.0-26-amd64)
Версія драйвера: 4.6 (Compatibility Profile) Mesa 22.3.6

Версія ядра: Linux 6.1.0-26-amd64
Виробник X-сервера: The X.Org Foundation
Версія X-сервера: 12201009
Менеджер вікон X Window System: KWin
Версія середовища виконання Steam: steam-runtime_0.20240806.97925
Версія OpenGL: 4.6

#### Please describe your issue in as much detail as possible:
This texture bug happens on all maps. It's especially annoying on Dust 2 on long corridor (near A bomb site)
![730_screenshots_20241019130151_1](https://github.com/user-attachments/assets/065601f8-155d-4085-be1e-9b41ce7032e2)

#### Steps for reproducing this issue:

1. Open CS2
2. Start any game
3. Open Dust 2, or any map

**Comment by kisak-valve** [comment] 2024-10-24 17:52
Hello @marshallovski, this is a video driver bug that's been fixed for a fairly long time.

Closing as a duplicate of https://github.com/ValveSoftware/csgo-osx-linux/issues/3857.

**Closed by kisak-valve** 2024-10-24 17:52 UTC
