### ISSUE TITLE
Steam deletes files from steamlibrary if you share it with windows steamlibrary

### ISSUE THREAD

**Issue by Libco** [ValveSoftware/steam-for-linux#2812] opened 2013-08-29 11:26 UTC
Steam always have to download about 60Mb of HL2 when you start Steam for linux after Steam for windows and vice versa.
For instance L4D2 is fine, but Steam for linux is completely deleting Torchlight II.
Also the 0b updates (L4D2 for example) appear in downloads.

**Comment by enkore** [comment] 2015-02-19 17:22
Seen this too, two times. Wiped the entire "Tomb Raider" folder in SteamApps/common, except for the (then empty) "movies" and "redist" folders. These two folders survived it both times, which seems a bit odd.

**Comment by meowy** [comment] 2015-04-20 12:25
This is still an issue, and I'm affected. In the case of PAYDAY 2, Steam deletes all Steam-managed files in the "assets" folder which contains practically all resources of the game.

Dual-boot configurations are common and this issue is disastrous for people with slow internet connections.

**Comment by licaon-kter** [comment] 2015-04-20 14:10
@meowy: In the mean time the Steam options changed a bit so now one must set Update to "Only when launched" and that will take care of it. If you get updates in the download window though just be careful to only update the ones that are actually for your running platform. ;)

**Comment by kisak-valve** [comment] 2018-11-06 16:14
Closing as a duplicate of #546.

**Closed by kisak-valve** 2018-11-06 16:14 UTC
Labels: Steam client, reviewed
