### ISSUE TITLE
For non-Steam games: %command% in the launch options is not interpreted

### ISSUE THREAD

**Issue by popsUlfr** [ValveSoftware/steam-for-linux#6046] opened 2019-01-20 16:31 UTC
#### Your system information

* Steam client version (build number or date): **1547865289 (Jan 19 2019, at 02:01:59)**
* Distribution (e.g. Ubuntu): **Arch Linux**
* Opted into Steam client beta?: **Yes**
* Have you checked for system updates?: **Yes**

#### Please describe your issue in as much detail as possible:

So non-Steam windows games can be added via `.exe` file and launched through proton directly in the client now. However the `%command%` macro that works in the launch options for the other Steam games does not seem to be interpreted for those non-Steam launchers.
So setting something like : 
```
DXVK_HUD=1 PROTON_DUMP_DEBUG_COMMANDS=1 %command%
```
Will just append them as parameters to the launched executable.

#### Steps for reproducing this issue:

1. Add a non-Steam windows game via its `.exe`  (Add a Non-Steam Game... > Browse > File type: All Files > Open a .exe)
2. In its properties select "Set launch options..."
3. Set for instance `DXVK_HUD=1 PROTON_DUMP_DEBUG_COMMANDS=1 %command%`
4. They will just be supplied as parameters to the launched executable

**Comment by jarrard** [comment] 2019-01-25 19:32
Does normal arguments like -devmode etc work? is it just the %command% para trick not working?

**Comment by b4ssrp** [comment] 2019-01-28 23:33
As a temporal workaround you could just start steam with specific env var, eg
```DXVK_HUD=1 steam```

**Comment by popsUlfr** [comment] 2019-01-31 17:57
> As a temporal workaround you could just start steam with specific env var, eg
> `DXVK_HUD=1 steam`

The better way to do it is renaming `user_settings.sample.py` to `user_settings.py` in proton and setting the variable there for now. But it would make more sense and be more practical to have that macro work for non-steam shortcuts.

**Comment by BobbyWibowo** [comment] 2019-02-02 18:17
Would love to see this "fixed". I mainly need this feature to be able to launch the game with `optirun %command%`.

**Comment by ThatAnnoyedGuy** [comment] 2019-02-03 17:35
Also having the same problem. Looking forward to a fix

**Comment by TheDaftRick** [comment] 2019-03-09 05:56
I have this issue also

**Comment by dreamer** [comment] 2019-05-21 09:14
Just hit this issue as well (commenting to keep track of the status of this bug). "Set launch options" does not behave consistently between Steam and non-Steam games.

**Comment by jarrard** [comment] 2019-05-21 09:21
Yeah its still a issue, I forgot this still existed until I started messing with skyrimse and used a whole heap of arguments etc to configure things on launch.

**Comment by felixactually** [comment] 2019-08-03 09:50
Commenting to say that this issue still occurs, I have the non-Steam version of GTA V and cannot use _WINEDLLOVERRIDES=winedbg.exe=d %command%_ so instead have to use strace every time to get into GTA Online without crashing.

**Comment by ThatAnnoyedGuy** [comment] 2019-08-09 02:41
Is this going to be fixed? It has been almost 7 months now since this issue was opened.

**Comment by jarrard** [comment] 2019-08-09 02:51
I'll haft to test this again to see if its the case.

**Comment by ThatAnnoyedGuy** [comment] 2019-08-09 02:55
> I'll haft to test this again to see if its the case.

Just tested myself. Still doesn't work

**Comment by felixactually** [comment] 2019-09-16 20:47
Issue still occurs with Proton 4.11-4.

**Comment by dreamer** [comment] 2019-09-16 22:16
This issue is not related to Proton.

**Comment by jarrard** [comment] 2019-09-17 00:09
Correct the issue is related to steam, there is a steam valve general github you can place the issue on I think?

**Comment by felixactually** [comment] 2019-09-22 08:43
I'm aware that this issue isn't related to Proton @dreamer, I wasn't saying that it is. Just that with the release of the latest Proton, the issue still occurs.

**Comment by mijofa** [comment] 2019-10-05 02:06
I ran into this issue and after an hour or so of looking through the Proton Python scripts I found that the environment variables are being set correctly *before* proton runs, and the code causing issues was only running when "VR_CONFIG_PATH" is in the environment.
So my hacky temporary solution is to just include VR_CONFIG_PATH= with any other variables I'm setting before %command%.

The error is being triggered when Proton runs "[...]/wine winepath -w /home/USERNAME/.steam/steam/config" but I can't understand why winepath would fall apart in these circumstances because winepath shouldn't even be using the command line at all anyway. But is seems, to me, like an issue in Proton rather than the Steam client, because Proton is getting the correct environment variables and command line.

**Comment by mercuriete** [comment] 2019-10-14 00:17
Have this same issue.
Workaround launching steam with that env var works.

DXVK_HUD=1 steam

**Comment by mijofa** [comment] 2019-10-14 03:11
Problem with that is that some games work a lot better without DXVK_HUD=1, so it's not really suitable as a longterm solution, which is why I went through the code to find the VR_CONFIG_PATH= workaround, presumably it won't work for VR games launched via proton because they won't find their CONFIG_PATH, but that's less games than the EVERYTHING that's affected by setting the steam environment on launch

**Comment by mercuriete** [comment] 2019-10-14 08:34
Sorry I miss typed my workaround
What I needed was activate D9VK on a non steam windows game (guild wars 3)

so my workaround was:
```PROTON_USE_D9VK=1 steam```

Another use case but same problem

**Comment by Klairm** [comment] 2019-11-03 16:03
> Commenting to say that this issue still occurs, I have the non-Steam version of GTA V and cannot use _WINEDLLOVERRIDES=winedbg.exe=d %command%_ so instead have to use strace every time to get into GTA Online without crashing.

did you managed to solve that?

**Comment by hevanaa** [comment] 2019-12-15 22:15
Just bumped into the same issue. Launch option are just added as parameters to the executable. The VR_CONFIG_PATH= workaround suggested above doesn't work. 

In my case I need launch option PROTON_OLD_GL_STRING=1 %command%. 

From command line the application starts fine:

STEAM_COMPAT_DATA_PATH=~/Steam/SteamApps/compatdata/3645010168/ PROTON_OLD_GL_STRING=1 ~/Steam/SteamApps/common/Proton\ 4.11/proton waitforexitandrun "my_executable.exe"

But when trying to launch through steam the application hangs and when checking running processes in terminal, you can see that the application is started with "my_executable.exe PROTON_OLD_GL_STRING=1 %command%"

**Comment by jarrard** [comment] 2019-12-16 04:45
D9VK should be enabled by default at this stage, surprised its not.

**Comment by mijofa** [comment] 2019-12-17 00:58
On Sun, Dec 15, 2019 at 02:15:54PM -0800, Johan Heikkilä wrote:
> Just bumped into the same issue. Launch option are just added as parameters to the executable. The VR_CONFIG_PATH= workaround suggested above doesn't work. 
> 
> In my case I need launch option PROTON_OLD_GL_STRING=1 %command%. 
> 
> From command line the application starts fine:
> 
> STEAM_COMPAT_DATA_PATH=~/Steam/SteamApps/compatdata/3645010168/ PROTON_OLD_GL_STRING=1 ~/Steam/SteamApps/common/Proton\ 4.11/proton waitforexitandrun "my_executable.exe"
> 
> But when trying to launch through steam the application hangs and when checking running processes in terminal, you can see that the application is started with "my_executable.exe PROTON_OLD_GL_STRING=1 %command%"

I suspect that's a different issue. I've seen that happen recently-ish
with a native Linux game where it didn't correctly translate %command%
into the original comment and added it as an argument to the end
instead. In my cause it was caused by trying to add arguments both
before *and* after the %command%, which is supposed to work but I never
figured out why it didn't.

-- 
Mike Abrahall

**Comment by mijofa** [comment] 2020-01-16 07:29
It's been a while since I've touched it, but I'm running back into either this, or a similar issue now. My previous workaround doesn't work anymore, and I think it's actually not Proton related anymore.
Any further on other workarounds or anything?

**Comment by hevanaa** [comment] 2020-01-16 10:22
> 
> 
> @mijofa
> As I said on previous comments,
> you can workaround the problem putting environmental variables before launch steam
> example:
> `PROTON_USE_D9VK=1 steam`

This is not a good workaround for all use cases. In my example, there is only one game that needs PROTON_OLD_GL_STRING=1.  I don't want all games to get this environment variable, because there is only one game that needs string length limited in this way. 

For now I run the game from command line without involving steam at all (as shown in previous post above). For non-steam games (which this bug is about), the real benefit from steam is the proton environment, which in my case enables me to run the game at all (standard wine or wine staging don't work). The second benefit from steam is usability; it is easier for the user to configure and launch the game through the Steam GUI (instead of command line) and get benefits from proton environment.

**Comment by mijofa** [comment] 2020-01-16 10:41
That's not a viable solution for me because different games need different (often conflicting) variables to be set. Restarting Steam with different variables for every single game makes using Big Picture Mode from my couch very cumbersome.

Attached is a [user_settings.py](https://github.com/ValveSoftware/steam-for-linux/files/4070653/user_settings.py.txt) I've written just now that works around this issue by reverse engineering the %command% logic at a later step. It's kind of ugly, but it works.
The one caveat (that I know of) is that it won't work for things like optirun and similar linux applications that are intended to wrap Proton. This is because it's being handled after Proton has been called, so it can't really move the arguments back that far. It works for environment variables though, and that's the main thing that matters to me (if not most people)

**Comment by Syntist** [comment] 2020-01-18 07:38
@mijofa 
I am trying your Script, but doesn't seem to get it working,  
So, I just have to copy your script and use Envirnment Variable in steam launch option? It should work than right? but It ain't working for me. 

I still have that command in Process after the name, which mean it didn't detect it.
I tried it with dxvk_hud didn't work. 
I would like some help, it's annoying changing, user_settings.py for every game 
Or Re-opening Steam just for some game again and again

**Comment by mijofa** [comment] 2020-01-19 02:45
> @mijofa
> I am trying your Script, but doesn't seem to get it working,
> So, I just have to copy your script and use Envirnment Variable in steam launch option? It should work than right? but It ain't working for me.
> 
> I still have that command in Process after the name, which mean it didn't detect it.
> I tried it with dxvk_hud didn't work.
> I would like some help, it's annoying changing, user_settings.py for every game
> Or Re-opening Steam just for some game again and again

Can you see anything popping up in the bottom of ~/.steam/error.log when you launch the game that might indicate the issue?
I'm not really sure why it's not working, are you sure it's loading the user_settings.py at all? (note you'll need to remove the .txt extension)

**Comment by ltsdw** [comment] 2020-02-23 01:00
@mijofa Yep, also I've tested your user_settings.py (with extension .txt excluded, I've even gave execute permission), using DXVK_HUD = 1 %command% for test purpose and can confirm that isn't working with non-steam games.

**Comment by mijofa** [comment] 2020-02-23 03:17
Can you see anything popping up in the bottom of ~/.steam/error.log when you launch the game that might indicate the issue?
I've confirmed it's still working for me today right now, so I've no idea why it's failing without some extra info

**Comment by ltsdw** [comment] 2020-02-23 16:42
@mijofa I don't have any error.log on this directory... maybe it is on another place?

**Comment by IDeathByte** [comment] 2020-12-15 05:57
tryed to launch GOG version cyberpunk with gamescope, and pre-launch arguments currently not work

also as i see, new options interface uses only with steam games, and for non-steam we has old interface
![Screenshot_20201215_105412](https://user-images.githubusercontent.com/41571062/102176734-e1a27f80-3ec3-11eb-85fd-72ca738c441f.png)

**Comment by class101** [comment] 2021-01-11 16:40
Yes I suggest for this to keep the current  Launch Options without the need of translating %command%.

On the newer second "Compatibility" tab, where we enable Proton, we need launch options there that will correctly translate %command% as a normal Steam game.

Launch options 1 = Program parameters
Launch options 2 = Proton parameters

**Comment by kunver400** [comment] 2021-04-30 14:11
please fix this.

**Comment by wunderbar78** [comment] 2021-06-03 12:54
trying to use gamemoderun with a non-steam game and facing this issue.
please fix.

**Comment by YellowOnion** [comment] 2021-07-01 11:19
Anyone know of a work around for libstrangle? I want a framerate limiter for GTAV.

**Comment by class101** [comment] 2021-07-01 11:39
@YellowOnion 

Not sure what is the problem but I know MangoHUD has an `fps_limit` option for this.

@mijofa 

Thank you for sharing your idea, I have extrapolated this idea with a newer one

Basically it

- sets launch options for Steam and non-Steam games
- sets global launch options
- sets small overrides per games

https://gist.github.com/class101/65f3133b64ba278537ee19fbb3fbb782

For a use case you can see it in my Proton guide for installing the Vortex Mod Manager as a non-Steam game [here](https://steamcommunity.com/sharedfiles/filedetails/?id=2386287653)

**Comment by jarrard** [comment] 2021-07-01 13:47
dxvk 1.9 has fps limiter in built.

**Comment by Semperverus** [comment] 2021-07-04 00:42
I am currently experiencing this issue as well. Trying to launch Guild Wars 2 with DXVK_HUD or MangoHud fails. No other commands work with %command% either. This used to not be the case on older versions of Proton.

**Comment by jarrard** [comment] 2021-07-04 03:18
yeah seems to be some basic syntax pass-to-proton issue.  I wish someone at valve would just fix this because sometimes its used for Steam games also but where you wish to launch via a different method (Mod Manager or custom config Launcher etc)

**Comment by mercuriete** [comment] 2021-07-04 13:22
> I am currently experiencing this issue as well. Trying to launch Guild Wars 2 with DXVK_HUD or MangoHud fails. No other commands work with %command% either. This used to not be the case on older versions of Proton.

I am a guild wars 2 player like you and I have exactly the same problem.
I just launch Steam with the variable like:
```
DXVK_HUD=full steam
```
I know that is a bad workaround but It works for me.

**Comment by SingerJonathan** [comment] 2021-08-18 21:35
The following is the only workaround I've been able to figure out that works with any launch options including Linux applications (like optirun) and GameMode as well as environment variables.

### Running Non-Steam Proton Games with Full Launch Options Support
- Run your game through Steam, as you're probably doing already, by adding the .exe as a non-Steam game and selecting a version of Proton from the compatibility tab in the game's properties. This will generate the required compatdata directory containing the Proton prefix.
- Create a .desktop file to use as the target in Steam. You can use this one as a template.
```
[Desktop Entry]
Name='Guild Wars 2'
Path='/home/username/Games/Guild Wars 2'
Exec=env STEAM_COMPAT_DATA_PATH=/home/username/.local/share/Steam/steamapps/compatdata/2464934368 STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/username/.local/share/Steam/compatibilitytools.d/Proton-6.14-GE-2 mangohud '/home/username/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/username/.local/share/Steam/compatibilitytools.d/Proton-6.14-GE-2'/proton waitforexitandrun "/home/username/Games/Guild Wars 2/Gw2-64.exe" --autologin
```
- Replace `2464934368` in the template with your game's AppID.
- Replace the paths and Proton versions in the template with what's correct for your system and game.
- Place your pre-`%command%` launch options just before the SteamLinuxRuntime section. (Where `mangohud` is in the example)
- Place your post-`%command%` launch options after the .exe section. (Where `--autologin` is in the example)
- In Steam, edit your game's properties. Set `TARGET` to your .desktop file. Leave `LAUNCH OPTIONS` empty here.
- Uncheck `Force the use of a specific Steam Play compatibility tool`.
![Non-Steam_Proton_Launch_Options_Shortcut](https://user-images.githubusercontent.com/17101191/129971539-99b6fef1-a3d5-4358-bd87-38d55aad0212.jpg)
![Non-Steam_Proton_Launch_Options_Compatibility](https://user-images.githubusercontent.com/17101191/129971555-173b9201-05df-412b-9f46-ba0ac9961ad2.jpg)

### Notes & Tips
- The Exec section in the .desktop is essentially what steam calls when you run a non-Steam game with Proton, minus the environment variables. If you try to run this command without the variables, it will just ask for them and not run.
- To find your game's AppID, as @class101 pointed out in his guide:
  > The simplest way to find this value is to navigate to the ${X}/steamapps/compatdata folder and find the last directory created, its name consisting of 10 digits is the STEAMAPPID variable.
- GameMode works the same as it does with other Proton games. `LD_PRELOAD="$LD_PRELOAD:/usr/lib/libgamemodeauto.so.0"` works for me on Arch Linux.

**Comment by jarrard** [comment] 2021-08-19 01:19
I had no problems with the global user settings py method. Seemed easier and can back it up easily. No need to mess with steam.

**Comment by mijofa** [comment] 2021-08-19 01:25
Of note, further updates to Proton do require installing the user_settings.py again as it's installed in the specific Proton version. However I haven't needed that custom patch in a long while now, I forgot to install it after a particular update some time ago (no idea which one) and everything has continued working, so I've just kinda forgotten about it to be honest.

**Comment by SingerJonathan** [comment] 2021-08-19 01:51
With user_settings.py, I couldn't get LD_PRELOAD to work for GameMode. As far as I can tell, you can also only use environment variables that way. So, no optirun, nvidia-xrun, etc. The method I outlined allows you to use those options and it works on a per-game basis. It's also easy to back up a folder of .desktop files. Seems to be working well, I just wish we didn't have to resort to workarounds anymore!

**Comment by jarrard** [comment] 2021-08-19 07:47
Yeah I noticed I couldn't get VK_ICD_FILENAMES to work with it. Very weird.

**Comment by jextrevor** [comment] 2021-09-25 21:52
Having the same problem here. This has been open for two and a half years, will this ever be fixed?

**Comment by jarrard** [comment] 2021-09-26 02:42
You'd think it be something they want to fix before steam-deck comes out since their advertising 3rd vendor non-steam game support. But with these syntax issues for launching games, lots of people are going to be completely stumped why their added in game doesn't launch...

**Comment by Sterophonick** [comment] 2021-09-29 04:23
> You'd think it be something they want to fix before steam-deck comes out since their advertising 3rd vendor non-steam game support. But with these syntax issues for launching games, lots of people are going to be completely stumped why their added in game doesn't launch...

I know man, this is a thing I've been trying to make people aware of but Valve just ain't fixing this for whatever reason!

**Comment by jarrard** [comment] 2021-10-18 23:42
in the meanwhile you can use steamtinkerlauncher  _stl addnonsteamgame_

**Comment by YellowOnion** [comment] 2021-10-21 01:12
Has anyone tried `VAR=BLAH app.exe +flags -params` in the Target box like you would with a windows shortcut?

**Comment by jarrard** [comment] 2021-11-05 11:09
Any fix for this yet? been wanting to test gamescope out with a non-steam game and it seems its impossible because this issue taps on to other methods of bypassing the problem. (such as steamtinkerlauncher).

**Comment by Faalagorn** [comment] 2021-11-07 20:24
Would be nice to have it solved, I just tested that with Escape from Tarkov which isn't on Steam yet (doesn't work yet, but at least starts with newest proton-experimental), but for mangohud to work with it I had to start whole Steam with it ._.

**Comment by jarrard** [comment] 2021-11-07 21:42
I generally use steamtinkerlauncher in the meanwhile (often needs force custom exec option ticked, and you select custom proton version). 

At least steam generates the correct exe path and all when adding non steam games, we just need it to obey %command% line stuff.

**Comment by Ranguna** [comment] 2022-01-02 13:17
Same issue on my side, got Control on the epic store for free and wanted to get gamepad input working (which only works if I launch the game from big picture). I can't open Control with the required flags to enable Ray tracing and DLSS.

I do "understand" the ulterior motives here, but it would be nice to skip that kind of mentality and just go straight to playing games please.

Until this is fixed, the workaround of launching steam with the required env vars worked for me.

**Comment by Semperverus** [comment] 2022-01-03 05:35
Why is everyone suggesting there is an ulterior motive here? Why attribute to malace what can be attributed to incompetence (or in this case just huge time constraints) instead? I program for a living, there are a trillion and one things I have to keep track of in my day to day. I can tell you that real human beings are working on this, and when people start attacking you over something like that, it tends to go to the bottom of the priority list. Not only that, but Valve has been very pro-competition from the very beginning, and actively support their competitors in very odd ways, so long as it still makes some kind of business sense.

I want this fixed as much as you guys, but let's keep the insinuations out of the conversation.

**Comment by jarrard** [comment] 2022-01-03 07:01
> Why is everyone suggesting there

**Please keep on this topic**

**Comment by YellowOnion** [comment] 2022-01-05 00:23
> Has anyone tried `VAR=BLAH app.exe +flags -params` in the Target box like you would with a windows shortcut?

@jarrard 
@Ranguna 

We could also try wrapping the game in a script (bash for Linux games, and batch for proton?).

I'm not able to test it atm because I'm having hardware issues.

**Comment by Ranguna** [comment] 2022-01-05 08:16
> > Has anyone tried `VAR=BLAH app.exe +flags -params` in the Target box like you would with a windows shortcut?
> 
> @jarrard 
> @Ranguna 
> 
> We could also try wrapping the game in a script (bash for Linux games, and batch for proton?).
> 
> I'm not able to test it atm because I'm having hardware issues.

You mean copy all the things steam uses to launch Windows games and write all that ourselves in a bash script?

Should work, but that's a lot of trouble vs just launching steam with the correct env vars. Also, you'd have to constantly update your script whenever steam decides to add more stuff to the launch commands.

**Comment by mijofa** [comment] 2022-01-05 08:19
> We could also try wrapping the game in a script (bash for Linux games, and batch for proton?).

This is pretty much the same as the custom user_settings.py approach that was posted above

**Comment by jarrard** [comment] 2022-01-06 01:56
It be nice if added in non-steam games allow you to select a game profile upon adding. So say you added Doom Eternal from GOG or something; upon adding it, it have a gamesearchbox you just start typing and select use proton game profile Doom Eternal for this non-steam game. 

They can also just have a DEFAULT profile selected automatically that installs the bare minimal resources that ALL proton games need.

**Comment by Sultech** [comment] 2022-03-23 04:18
I have seen a video of someone using %command% with epic games added as a non steam game and it seems to work. They are using a steam deck, does the steam deck have an updated client with this fixed?

https://www.youtube.com/watch?v=UiUvAOatu9s

**Comment by Blisto91** [comment] 2022-04-01 17:32
Yes this seems to work with the steam beta client now.

**Comment by Plagman** [comment] 2022-04-01 23:22
Thanks for confirming!

**Closed** 2022-04-01 23:22 UTC
Labels: Steam client, Need Retest

**Comment by Sterophonick** [comment] 2022-04-02 00:36
WOOOOOOO
