### ISSUE TITLE
libGL error: unable to load driver

### ISSUE THREAD

**Issue by linuxcbon** [ValveSoftware/steam-for-linux#4081] opened 2015-10-21 15:03 UTC
Hi,
when runing steam client in linux, I always have this error messages : 
"libGL error: unable to load driver"
"libGL error: driver pointer missing"

solution found : remove 2 files /.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6*

thanks for your help

**Comment by gdrewb-valve** [comment] 2015-10-21 18:58
Duplicate of #3273.

**Closed by gdrewb-valve** 2015-10-21 18:58 UTC
Labels: reviewed
