### ISSUE TITLE
Steam filled my /tmp 

### ISSUE THREAD

**Issue by Kattus** [ValveSoftware/steam-for-linux#6901] opened 2020-02-15 16:11 UTC
#### Your system information

* Steam client version (build number or date): steam-runtime_0.20200204.0
* Distribution: Arch Linux 64-bit
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:
I was using my computer like normal when I found a few of my scripts wasn't working, and a kernel update failed (that was fun), I found out that `/tmp/dumps/katt_stdout.txt` was 7.9G and filling my entire tmpfs and effectively broke my entire system.
I moved the file elsewhere for closer inspection later, and found that (at least) the last 10000 lines were just "type unknown not a basic type"

I had been playing sone Divinity: Original Sin 2 with a friend, and while it used to work fine, this seems to no longer be the case, I don't know if it's proton, nvidia drivers, my kernel or mesa. It crashed a lot either way with different proton versions, older kernel and older mesa.

*Either way please don't let the steam log grow forever.*
[katt_stdout.txt.zip](https://github.com/ValveSoftware/steam-for-linux/files/4208714/katt_stdout.txt.zip)

#### Steps for reproducing this issue:

1. Start steam
2. Play Divinity: Original Sin 2
3. Crash a few times due to Proton/nvidia drivers being wonky (who knows!)
4. Find your entire computer broken

**Comment by kisak-valve** [comment] 2020-02-15 16:22
"type unknown not a basic type" appears to be dbus related. Reference: https://lists.freedesktop.org/archives/dbus/2008-September/010485.html

**Comment by kisak-valve** [comment] 2020-02-15 16:33
Some lines of interest from the log:
`steamuibetacontroller.cpp (732) : Assertion Failed: pfnGetClientActualLauncherType`
`process 1036: Array or variant type requires that type signature be written, but string was written.`
`The overall signature expected here was 'l^C^A^A' and we are on byte 26 of that signature.`
`type unknown not a basic type`

**Comment by develop7** [comment] 2020-02-19 09:27
Affected me as well; not sure how to reproduce, recent beta update seem to resolve it for now

**Comment by Kattus** [comment] 2020-02-19 10:37
I suppose I should add I've found why I was crashing so much, seems my RAM decided to go all kinds of unstable recently, I've downclocked them and no more crashes.

This of course doesn't change the fact that the log should never grow to this size, and a limit should be put in place.

**Comment by Tiedemanns** [comment] 2020-02-28 21:53
Had the same problem playing X4 (Beta) but the beta of the Steam client (1582328676) doesn't seem to do it.
It filled up with a lot of file not found errors but the game seemed to work fine with the mod files it complained about. Filled up 8GB after a few hours.

**Comment by TTimo** [comment] 2020-03-11 22:52
Workaround for now: edit `/usr/bin/steam` (`which steam`) and remove the teeing setup block at the very end of the script with just the execution: `exec "$LAUNCHSTEAMDIR/$STEAMBOOTSTRAP" "$@"`

**Comment by dsalt** [comment] 2020-03-14 16:13
Occasionally happening here too. From a little searching elsewhere, **it looks like it's something dbus-related.**

* Steam client version: 1583800998
* Distribution: Devuan beowulf
* Opted into Steam client beta?:Yes
* Have you checked for system updates?:Yes

```
Running Steam on debian 3 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/ds/.local/share/Steam/ubuntu12_32/steam -console %@
Installing breakpad exception handler for appid(steam)/version(1583800998)
ATTENTION: default value of option vblank_mode overridden by environment.
Installing breakpad exception handler for appid(steam)/version(1583800998)
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
Installing breakpad exception handler for appid(steam)/version(1583800998)
ATTENTION: default value of option vblank_mode overridden by environment.
Installing breakpad exception handler for appid(steam)/version(1583800998)
Installing breakpad exception handler for appid(steam)/version(1583800998)
Installing breakpad exception handler for appid(steam)/version(1583800998)
Installing breakpad exception handler for appid(steam)/version(1583800998)
Installing breakpad exception handler for appid(steam)/version(1583800998)
Installing breakpad exception handler for appid(steam)/version(1583800998)
Installing breakpad exception handler for appid(steam)/version(1583800998)
Installing breakpad exception handler for appid(steam)/version(1583800998)
Installing breakpad exception handler for appid(steam)/version(1583800998)
Installing breakpad exception handler for appid(steam)/version(1583800998)
process 31482: Array or variant type requires that type signature be written, but string was written.
The overall signature expected here was 'l^C^A^A' and we are on byte 34 of that signature.
type unknown not a basic type
type unknown not a basic type
type unknown not a basic type
type unknown not a basic type
type unknown not a basic type
type unknown not a basic type
```

After that point, while the normal log messages do appear (so far as I can tell), it's almost entirely that “type unknown”.

**Comment by JJRcop** [comment] 2020-03-20 01:48
My workaround is to symlink `/dev/null` to the offending file path. Hope this can be fixed. It was error.log for me.

**Comment by MasterCATZ** [comment] 2020-03-21 14:41
Steam package version 1584730869
Ubuntu 19.10 kernel 5.5.11-050511-generic

I have not played steam for a few months 
just installed doom eternal enabled proton 5 

then steam just crashed my pc by leaving 0 bytes free space 
when it hogged 2.9tb creating a error.log file containing 


rm: cannot remove '/home/aio/.steam/steam': Is a directory
rm: cannot remove '/home/aio/.steam/bin': Is a directory
ype
type unknown not a basic type
type unknown not a basic type
type unknown not a basic type

... infinite loop

**Comment by TTimo** [comment] 2020-03-22 15:51
@MasterCATZ see https://github.com/ValveSoftware/steam-for-linux/issues/6901#issuecomment-597919421 for workaround

**Comment by Yowlen** [comment] 2020-03-28 22:15
Already have the workaround in place, but just wanted to add that it happened to me for Starbound just now on Xubuntu 19.10. Luckily, my `/home` directory, where Steam is located, is on a separate partition, so it didn't crash the entire system. In fact, I only noticed when screenshots stopped saving.

Still, finding a 64GB error log that had accumulated over just a few hours was not a fun discovery. I hope the fix gets pushed to stable soon because I can't imagine how many other people it affects that aren't as tech-savvy as those of us here.

**Comment by TTimo** [comment] 2020-03-30 14:22
Update on this:

- The steam installer is now in beta for Debian derivatives: https://repo.steampowered.com/steam/archive/precise/steam-launcher_latest-beta_all.deb - this version no longer configures the steam client to log it's stdout/stderr to a file.

- We have made progress tracking the root cause of the spam. The fix will be in a future Steam client beta update.

**Comment by TriMoon** [comment] 2020-03-30 14:37
When will the current steam client auto-update to this fix?

**Comment by fagnerln** [comment] 2020-04-02 02:08
This bug broke my distro, I've lost some configuration (KDE and Steam) because the system got out of memory. With some research (and with help of ncdu ) i've found that ~/.steam/error.log have 331,8GB, yep 33% of my 1TB HDD. This is a very harmful bug.

I'm not a dev, and I can't (of course) open the 300GB log, but as someone referenced about this bug on a "ThreadHighPriority" dbus message, maybe Feral's Gamemode have something to do with this bug?

There's no way to steam control the size of the log? I mean, if a log increases the size exponentially in a few time (like a GB), Steam needs to stop the log.

**Comment by dsalt** [comment] 2020-04-02 03:34
_If_ GameMode has anything to do with this then it's not the only potential trigger. I don't have it installed here due to its dependency on systemd.

**Comment by TTimo** [comment] 2020-04-03 15:24
Please test this again with Steam beta client Apr. 1st or newer.

**Comment by fagnerln** [comment] 2020-04-05 18:57
Looks ok here, a nice 45KB log. I'll watch it for some days, if something strange happens, I will report...

**Comment by Saroumane** [comment] 2020-04-08 21:26
Happened to me on the 4th of April, after last Steam client update. 46GB of steam error.log.
Ubuntu 19.10.

**Comment by divergentdave** [comment] 2020-04-11 17:51
I had a similar issue today, but in my case with different log files in `/var/log/user.log`, `/var/log/syslog`, and/or `/var/log/messages`, IIRC. I must have a newer version of Steam than prior reports, because `/usr/bin/steam` does not write to `~/.steam/error.log`, rather, it tees to `/tmp/dumps/${USER}_stdout.txt`. I did notice while my disk was filling up that systemd-journald was pegging one core, and rsyslogd was pegging three other cores, so presumably the stdout of /usr/bin/steam was being captured by systemd and written into those `/var/log/` files.

While my disk was filling up, I ran `sudo journalctl`, scrolled to the end of the log, and noted many `type unknown not a basic type` lines. I took the PID from those lines, checked the process, and found that it was `gnome-shell`.

I don't recall how I had started Steam before this happened, but it was either from the application launcher or a `steam://` URI.

**Comment by Yowlen** [comment] 2020-04-11 19:34
Can confirm that the `type unknown not a basic type` spam exists as of the latest stable release. (Build date: April 4th, 2020, at 00:37:27 according to the `Help` -> `About Steam` dialog)

For me, on Xubuntu 19.10, it manifested in the `~/.xsession-errors` log fike which had the same effect as the previous issue, filling up my `/home` partition and causing all sorts of issues across different apps due to being unable to write config files and stuff. It'd obviously cause far worse problems on other systems that don't have the `/home` partition separated from the `/` partition.

**Comment by koreanfan** [comment] 2020-04-12 11:33
Hello. I use debian bullseye with latest updates and error log file size is 64 GB. Can you fix it pls?

**Comment by Kopetan4egX** [comment] 2020-04-12 15:35
Just got a message about "low amount of space at home folder". Found this error.log having size of 61.1Gb. Lost some app settings due to no-memory problem (Firefox, Deluge as i see now, maybe something else will be found later)

**Comment by Yowlen** [comment] 2020-04-13 17:56
Tested with the latest beta client (April 8th) and while the `type unknown not a basic type` error spam isn't present, I am getting the following spam in `~/.xsession-errors`:
`RecordSteamInterfaceCreation (PID 5978): SteamController007 / Controller
RecordSteamInterfaceCreation (PID 5978): SteamInput001 / Controller`

**Comment by ScottNAtlanta** [comment] 2020-04-15 18:23
This happened to me today April 15th.  The Error.log file was 370GB.  I deleted it.  Luckily my Home is on a separate partition or this would have hosed me big time.  It doesn't seem to be happening since I deleted the file and the new error.log file is 9KB.
I only play Cities Skylines and MiniMetro on Steam.

**Comment by Kopetan4egX** [comment] 2020-04-16 15:30
This morning it happened again. 
Error.log is 60.5Gb
Steam version the same
![Снимок экрана в 2020-04-16 18-27-55](https://user-images.githubusercontent.com/18350912/79475416-4db8a500-8010-11ea-981a-4131e90010f5.png)

**Comment by MegWATTT** [comment] 2020-04-16 18:05
Hello,

Same issue today. I have a 23GB stdout file in tmp/dumps filled with "type unknown not a basic type". Also had to kill steam with "kill -9"

**Comment by TTimo** [comment] 2020-04-16 20:39
Version 1.0.0.62 of the official steam client installer has been released for general use after a beta testing period. You can download it from https://repo.steampowered.com/steam/archive/precise/steam_latest.deb

This version of the steam client installer updates the `steam` launch script (normally installed to `/usr/bin/steam`) so it does not create logs in `/tmp/dumps` anymore, which addresses the initial problem reported here.

If you are running Debian or an Ubuntu derivative, please install this package right away.
Otherwise, get in touch with your upstream distribution so they update their version of the steam installer.

You can also apply this workaround until a solution is available in your favorite distribution: https://github.com/ValveSoftware/steam-for-linux/issues/6901#issuecomment-597919421

Finally, if you are experiencing the "type unknown is not a basic type" spam problem, which exarcerbates the logging and disk space issue at hand here, you should switch to the latest Steam Beta client, and report further issues to https://github.com/ValveSoftware/steam-for-linux/issues/6911 if the problem still happens for you.

**Closed by TTimo** 2020-04-16 20:39 UTC
Labels: Need Retest, Steam client
