### ISSUE TITLE
[Feature Request] Add option for the close button to completely exit steam

### ISSUE THREAD

**Issue by alemansec** [ValveSoftware/steam-for-linux#4772] opened 2016-12-21 20:27 UTC
#### Your system information

* Steam client version:1482214037
* Distribution (e.g. Ubuntu): Debian GNU/Linux Jessie x86_64 up-to-date
* Opted into Steam client beta?: [Yes/No] Yes & No (both afected)
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
hitting the window close button (within steam client custom titlebar) **DOES NOT CLOSE** the steam client application, but **MINIMIZES IT** INSTEAD

#### Steps for reproducing this issue:

1. start the steam client
2. let it start
3. hit the close button (the valve custom "X" button on steam client custom titlebar)

#### expected behaviour
Application clean exit

#### obtained behaviour
Application MINIMIZES instead of CLOSING

**Comment by kisak-valve** [comment] 2016-12-21 21:08
Hello @alemansec,
Per https://github.com/ValveSoftware/steam-for-linux/issues/1025#issuecomment-12858338, this is the current intended behavior. If you want the window to close, set the ```STEAM_FRAME_FORCE_CLOSE=1``` environment variable.

Closing as a duplicate.

**Comment by alemansec** [comment] 2016-12-21 21:23
**STEAM_FRAME_FORCE_CLOSE=1** env var does not fix it :

$ env|grep STEAM
STEAM_FRAME_FORCE_CLOSE=1

$ steam

wait for it ...
click the close (x) icon

wait ...
keep waiting ...

steam still running minimized...
(stdout|stderr did not even notice the click event or at least shows nothing)


hitting the close button does nothing but minimize the steam client.

**Comment by nmschulte** [comment] 2016-12-21 21:36
> expected behaviour
> 
> Application clean exit

Note, this is not the expected behavior of the workaround you note.  The workaround simply forces the **Window** to close, not the application.  The window should not be minimized in a window/task/process panel, but closed entirely.  From there, whether or not the application exits (closes) should be determined by your Steam preference to "close to tray" or not.

**Comment by nmschulte** [comment] 2016-12-21 22:02
I just updated Steam to the latest version, and the environment variable to workaround issue #1025 (where the close button works like minimize, in Linux releases) is still working just fine.

I cannot find a "close to tray?" preference, though, so it seems impossible to make the close button exit Steam, in the Linux release.  That issue is what this bug is for.

**Comment by alemansec** [comment] 2016-12-21 22:14
note that the windows build also behaves incorrectly regarding the close button : hit the close button and application will just minimize....

i'm not speaking of any minimize to tray "problem" .. it always worked correctly for me although application lacks quite a few options regarding focus, placement, minimize behaviour and also - because you're using close icon to minimize - close button behaviour.

Give us those options (via environment variables if you don't want those to be "visible" to all of your users).
If you still want to use standard icons like close button to act as non-standard, all-rules-and-standards-breaking, custom weird widgets, at least give us options to make them work as expected :)

[letting window manager actually manage windows, making close icons actually CLOSE the window then application if MainWindow was closed ... in a few words .. proper application, not a winblow$ copy&paste thing ...]

**Comment by nmschulte** [comment] 2016-12-21 22:24
@kisak-valve; please change the request to be "minimize to tray" instead of "close to tray".  Or, add options for both.

**Comment by nmschulte** [comment] 2016-12-21 22:25
@kisak-valve, I think the community believes it makes more sense for what's being requested to be the default behavior, and that the option to _not close_ be the option.

**Comment by kisak-valve** [comment] 2016-12-21 22:30
@nmschulte, are your asking for #1025, not this issue report?

**Comment by nmschulte** [comment] 2016-12-21 22:52
The two are basically the same, @kisak-valve; this one asks for close to exit the application, and the other one asks for close to close the window (keep the app up in the tray).  Personally, I feel like there should simply be a "close to tray" and/or perhaps "minimze to tray" preference, and clicking the X ("closing" Steam) should exit the app if "close to tray" is not selected, and otherwise it should simply close the window and keep Steam running ("in the tray").  Similarly for minimize.  That would resolve all of these issues.

Presumably #1025 will never be fix, and so forth neither will this one, or all of the mess that #1025 creates.  So, at this point, I go silent and check back in four years.

**Comment by Plagman** [comment] 2016-12-22 05:33
We have no plans to change that behavior, as it matches the behavior of the client on other platforms.

**Closed by Plagman** 2016-12-22 05:33 UTC
Labels: Feature Request, Steam client

**Comment by nmschulte** [comment] 2016-12-22 15:59
:wow:
