### ISSUE TITLE
[beta] Steam loading but only displaying a black screen within the frame

### ISSUE THREAD

**Issue by MurdoMaclachlan** [ValveSoftware/steam-for-linux#8036] opened 2021-09-02 19:14 UTC
#### Your system information

* Steam client version: Built on Aug 31 2021, at 20:28:17
* Distribution: Slackware Current
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam should display pages such as library, profile, store, etc. inside its frame, but only displays a black screen.
![image](https://user-images.githubusercontent.com/47920497/131902521-334751ed-ccd0-4bfc-bb33-c3306df9b261.png)
Log [here](https://gist.github.com/MurdoMaclachlan/f27beaee5c88e10259bad565e42f2523)

Big picture mode works as normal.

#### Steps for reproducing this issue:

1. Load Steam

**Comment by kisak-valve** [comment] 2021-09-02 19:20
Hello @MurdoMaclachlan, this reads like https://github.com/ValveSoftware/steam-runtime/issues/458. Closing as a duplicate.

**Closed by kisak-valve** 2021-09-02 19:20 UTC

**Comment by smcv** [comment] 2021-09-02 19:33
Workaround: install `zenity`.

**Comment by JPcode05** [comment] 2021-09-05 18:09
Try downgrading from Freetype 2.11 to 2.10: https://github.com/ValveSoftware/steam-for-linux/issues/7935#issuecomment-886026139

**Comment by Johnanater** [comment] 2021-09-06 23:29
> Workaround: install `zenity`.

I'm having this issue as well, `zenity` is already installed on my system :(

**Comment by pacmanmati** [comment] 2021-09-07 15:44
downgrading freetype2 (2.11.0-3 => 2.10.1-2) solved the issue for me on archlinux.

**Comment by smcv** [comment] 2021-09-07 16:47
The web UI not loading (resulting in this black screen) is a symptom, not a root cause. Just because you have this symptom, that does not necessarily mean the root cause is the same as for other people who have commented on this issue.

There are two known root causes for this symptom at the moment.

1. If you are using the **General Availability (non-beta) version of Steam**, and your distribution is very new (such as Arch Linux derivatives), you might have a version of `libfreetype` that requires a similarly new version of `harfbuzz`. When you run `steam` from a terminal (gnome-terminal, konsole, xterm or similar), there will be an error message similar to the one in [#7935](https://github.com/ValveSoftware/steam-for-linux/issues/7935), involving `libfreetype`. This is [#7935](https://github.com/ValveSoftware/steam-for-linux/issues/7935), and is fixed in the beta branch. Workaround: [use the beta version of Steam](https://developer.valvesoftware.com/wiki/Category:Beta_Releases) until the General Availability branch is fixed, and make sure `zenity` is installed.

2. If you are using the **Steam beta**, and you do not have `zenity` installed, then you might get errors like `echo: broken pipe at line 77` in `~/.steam/steam/logs/steamwebhelper.log`. This is [steam-runtime#458](https://github.com/ValveSoftware/steam-runtime/issues/458), and a fix is in progress. Workaround: make sure `zenity` is installed, and opt out from the beta if you are not intentionally using the beta.

3. If you think you are experiencing a different issue that is not the same as either of those, please [open a separate issue with full details](https://github.com/ValveSoftware/steam-for-linux/issues/new).

Commenting on a closed issue with "I also see this symptom" will not get it solved any quicker.
