### ISSUE TITLE
Can't open URL - /usr/bin/xdg-open: not found

### ISSUE THREAD

**Issue by urbinek** [ValveSoftware/steam-for-linux#4540] opened 2016-07-09 18:11 UTC
#### Your system information

* Steam client version: steam-launcher 1.0.0.52, package version 1468023329
* Distribution (e.g. Ubuntu): Debian GNU/Linux 8.5 (jessie)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I've just noticed that Steam is not opening links in chat window, there is no reaction in GUI.

If launched from terminal i can see that steam is returning error:

> sh: 1: STEAM_RUNTIME=0 LD_LIBRARY_PATH="$SYSTEM_LD_LIBRARY_PATH" PATH="$SYSTEM_PATH" /usr/bin/xdg-open: not found

Which is weird, because this application exist and is configured properly:
> urbinek@haruko:~$ which xdg-open
> /usr/bin/xdg-open

If invoked manually, works flawlessly
> urbinek@haruko:~$ xdg-open http://google.pl

(browser windows is opening)

#### Steps for reproducing this issue:

1. Get link in chat window
2. Click on link in chat windows
3. Nothing happens

**Comment by Tele42** [comment] 2016-07-09 19:27
Duplicate of #4528 / #4536.

**Comment by gdrewb-valve** [comment] 2016-07-09 19:54
Closing duplicate.

**Closed by gdrewb-valve** 2016-07-09 19:54 UTC
