### ISSUE TITLE
some games couldn't launch under steam client but works if they launched directly

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/steam-for-linux#4840] opened 2017-01-30 19:47 UTC
#### Your system information

* Steam client version: Jan 26 2017, at 19:05:32
* Distribution (e.g. Ubuntu): Fedora 25 x86_64
* Opted into Steam client beta?: [Yes/No]  Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Some games couldn't launch under steam client but works if they launched directly

#### Steps for reproducing this issue:

1. Launch Game from steam client:
```
>>> Adding process 31372 for game ID 560000
Traceback (most recent call last):
  File "/home/mikhail/.local/share/Steam/steamapps/common/Ladykiller in a Bind/Ladykiller in a Bind.py", line 196, in <module>
    main()
  File "/home/mikhail/.local/share/Steam/steamapps/common/Ladykiller in a Bind/Ladykiller in a Bind.py", line 193, in main
    renpy.bootstrap.bootstrap(renpy_base)
  File "/home/mikhail/.local/share/Steam/steamapps/common/Ladykiller in a Bind/renpy/bootstrap.py", line 213, in bootstrap
    import renpy.display.presplash #@Reimport
  File "/home/mikhail/.local/share/Steam/steamapps/common/Ladykiller in a Bind/renpy/display/presplash.py", line 27, in <module>
    import pygame_sdl2
ImportError: No module named pygame_sdl2
Game removed: AppID 560000 "Ladykiller in a Bind", ProcID 31366 
```

2. Launch Game directly:
```
$ .local/share/Steam/steamapps/common/Ladykiller\ in\ a\ Bind/Ladykiller\ in\ a\ Bind.sh 
[S_API FAIL] SteamAPI_Init() failed; no appID found.
Either launch the game from Steam, or put the file steam_appid.txt containing the correct appID in your game folder.
```

And Game works fine.

**Comment by kisak-valve** [comment] 2017-01-30 21:26
Closing as a duplicate of https://github.com/ValveSoftware/steam-runtime/issues/68.

**Closed by kisak-valve** 2017-01-30 21:26 UTC
