### ISSUE TITLE
Dropdown menus disappear with Firefox when moving cursor on the menu

### ISSUE THREAD

**Issue by strycore** [ValveSoftware/steam-for-linux#4029] opened 2015-09-23 00:22 UTC
Not an issue with the Steam client but I couldn't find anywhere to report issues with steampowered.com on the Steam Support website or on Valve Software's github. 

On Firefox, the dropdown menus from the blue toolbar (Games, Software, Hardware, …) will disappear when moving the cursor down from the toolbar to the menu itself. I've reproduced this bug on several machines and several systems. With Chrome, the menus act normally. I would assume this is an issue with a recent update to the website's stylesheets.

I've been experiencing this bug for about a month.

**Comment by Tele42** [comment] 2015-09-23 15:40
fwiw, if you're on a slow system and you can get the mouse outside the button when the menu starts to fade it, the menu is briefly usable.

**Comment by mark7** [comment] 2015-10-09 05:22
I could reproduce this with Iceweasel 38.2.1 on Debian stretch, no add-ons.

Checking Archive.org's snapshot of store.steampowered.com, the problem was introduced between the last snapshot on September 8 ( https://web.archive.org/web/20150908194136/http://store.steampowered.com/ ) and the first snapshot on September 9 ( https://web.archive.org/web/20150909032714/http://store.steampowered.com )

**Comment by Tele42** [comment] 2015-10-09 12:40
The corresponding Mozilla bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1205244

**Comment by alokhan** [comment] 2015-10-31 11:02
Same here with firefox 41.0.2 on ubuntu 15.04

**Comment by Blazko381** [comment] 2015-11-05 19:40
This bug is on all operations systems. My bug report:
https://bugzilla.mozilla.org/show_bug.cgi?id=1205027
-1st problem is scroll down and FF not load recommendations, sometimes load one recommendations list
-2nd problem is the drop-down lists for Games, Software, Hardware, and For You disappear when you try to click one of the items

**Comment by hallvors** [comment] 2015-11-08 11:02
Hi, 
the menu problem is caused by some JavaScript code relying on a non-standard IE-originated DOM extension - it uses event.toElement instead of event.relatedTarget.  I'll copy from a comment a Firefox developer makes in https://bugzilla.mozilla.org/show_bug.cgi?id=1205244 :

The JS file in question is:
 http://store.akamai.steamstatic.com/public/shared/javascript/shared_global.js

That file *does* actually have some usages of "relatedTarget", but it uses
non-standard "toElement" in the crucial place for these menus to work, which is
this chunk of "BindAutoFlyoutEvents()":

       $J(document).on('mouseleave.Flyout', '.flyout_tab', function(e) {
       [...]
               if ( !$Content.length || $Content.data('flyout-event-running') || bResponsiveSlidedownMenu ||
                       $Content.is( e.toElement ) || $J.contains( $Content[0], e.toElement ) )
                       return;

Using event.relatedTarget instead should work.

**Comment by miketaylr** [comment] 2015-11-08 14:57
Same bug reported at https://github.com/webcompat/web-bugs/issues/1886#issuecomment-153962858.

**Comment by Blazko381** [comment] 2015-11-10 17:11
Problem is resolved with menus disappear, when you install Greasemonkey and this script:
https://greasyfork.org/pl/scripts/13121-fix-drop-down-menus-on-steam-store
Not help with not loaded recommendations on Steam Store in Firefox.
Maybe little userscript to fix this problems? PLS

**Comment by miketaylr** [comment] 2015-11-10 19:30
Userscripts are cool for power users, but ideally someone at Valve can fix this for everyone.

**Comment by dholbert** [comment] 2015-11-11 21:35
Valve has fixed this internally, and it should be fixed on public sites sometime next week, per https://bugzilla.mozilla.org/show_bug.cgi?id=1205244#c19

**Comment by Nephyrin** [comment] 2015-11-19 00:48
The weak nexus to Steam-for-Linux aside, this has been fixed.

**Closed by Nephyrin** 2015-11-19 00:48 UTC
Labels: reviewed

**Comment by psydex** [comment] 2018-02-07 08:04
It's happening again!
![batch](https://user-images.githubusercontent.com/5594251/35905056-501ec34e-0bee-11e8-94ff-268e8ee7ee2c.gif)
Firefox 58.0.1

**Comment by kisak-valve** [comment] 2018-02-07 12:20
Hello @psydex, the issue in this report was triaged back in 2015. Please open a new issue report for the recent regression.
