### ISSUE TITLE
Steam takes very long to start, failed to connect to websocket

### ISSUE THREAD

**Issue by peacememories** [ValveSoftware/steam-for-linux#10879] opened 2024-05-11 15:48 UTC
#### Your system information

* Steam client version (build number or date): 1714854927
* Distribution (e.g. Ubuntu): Ubuntu 24.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: not available right now, I can post them when I next start steam, but the extract below should be the relevant information
* GPU: AMD Radeon 7900 XTX

#### Please describe your issue in as much detail as possible:
Recently when starting Steam, the tray icon appears immediately, but using any of the menu items does not work, and the Steam client does not appear.

Sometimes the client *does* appear after waiting for several minutes. I am not sure If this is always the case and I just was not patient enough most of the time.

When launching from the console it outputs this after hanging:

```
src/steamUI/webuitransportcontroller.cpp (206) : Failed to connect to websocket
```

This seems to me like something tries to connect to a websocket and the interface only continues initializing after the connection timeouts.

After appearing the interface does seem to work normally, so I am not sure what kind of websocket connection is failing.

This might be connected to #9658, but the problem started very recently for me and the mentioned issue seems to be a lot older.

#### Steps for reproducing this issue:

1. Start steam
2. The interface does not appear
3. Try to click on the tray icon and select "Library
4. The interface still does not appear
5. Wait for several minutes
6. The interface appears

**Comment by kisak-valve** [comment] 2024-05-11 17:02
Hello @peacememories, can you check if this is the same issue as discussed on #9383?

**Comment by usersteamdebian** [comment] 2024-05-12 17:52
I have the same problem,  since the last update it doesn't work well.
I tried uninstalling and purging ~/.steam/ ~/.steampath ~/.steampid but the problem persists
Your system information

    Steam client version (build number or date): 1714854927
    Distribution (e.g. Ubuntu): Debian GNU/Linux 12 (bookworm) (64 bit)
    Opted into Steam client beta?: No
    Have you checked for system updates?: Yes
    Steam Logs: [logs.zip](https://github.com/ValveSoftware/steam-for-linux/files/15287173/logs.zip)
    GPU: Radeon Vega 6

**Comment by YoinkerBoinker** [comment] 2024-05-13 10:54
Same issue. I also reported another issue which seems pretty much the same thing. See https://github.com/ValveSoftware/steam-for-linux/issues/10853 I think the issue with the start might be related to that small popup that sometimes shows up when starting steam to inform you about new offers/releases. 

I checkt he issue kisak-valve shows but i don't have a igpu since this is on 5700x3d / Rx7700 XT

**Comment by UrsusLvovich** [comment] 2024-05-13 12:45
I had a similar issue, started last tuesday for me. I guess when Steam had their last maintenance. When trying to open with the icon, the steam logo would show up in the task tray. But the main window wouldn't show up. I was able to still launch games by clicking the icon in the task tray though.
I then tried to run steam with sudo from the terminal. It did some update and the steam store actually came up this time. I thought I had resolved the issue, but trying to launch steam normally still resulted in the same behavior as before

**Comment by wwmm** [comment] 2024-05-16 17:36
I faced the same issue today. Steam's tray icon and the corresponding menu is in the system tray. But the window does not open. A curious workaround is disabling the internet connection before launching Steam. The window opens as usual this way without delay.

**Comment by wwmm** [comment] 2024-05-17 02:41
> I faced the same issue today. Steam's tray icon and the corresponding menu is in the system tray. But the window does not open. A curious workaround is disabling the internet connection before launching Steam. The window opens as usual this way without delay.

I think that the issue on my side may not be related to internet services. Having my xbox joystick plugged is what is actually making Steam's window to not be shown. Weird...

**Comment by fmorgner** [comment] 2024-05-17 22:50
I am seeing a similar problem (on Arch). Checking the logs, I see the following in `webhelper.txt`:

```
[2024-05-18 00:47:06] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: websocket connect retry: limit exceeeded, bailing - steamUI
[2024-05-18 00:47:06] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: failed to re-connect to websocket after close
[2024-05-18 00:47:06] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: OnWebsocketReconnect: Failed to reconnect to steam client
[2024-05-18 00:47:06] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: websocket connect retry: limit exceeeded, bailing - clientdll
[2024-05-18 00:47:06] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: failed to re-connect to websocket after close
[2024-05-18 00:47:06] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: OnWebsocketReconnect: Failed to reconnect to steam client
[2024-05-18 00:47:07] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: failed to reach open state
[2024-05-18 00:47:07] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: connect attempt failed: 2 - failed to reach open state
[2024-05-18 00:47:07] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: failed to reach open state
[2024-05-18 00:47:07] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: connect attempt failed: 2 - failed to reach open state
[2024-05-18 00:47:09] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: failed to reach open state
[2024-05-18 00:47:09] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: connect attempt failed: 2 - failed to reach open state
[2024-05-18 00:47:09] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: failed to reach open state
[2024-05-18 00:47:09] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: connect attempt failed: 2 - failed to reach open state
```

The following part keeps repeating every couple of seconds:

```
[2024-05-18 00:47:09] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: failed to reach open state
[2024-05-18 00:47:09] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: connect attempt failed: 2 - failed to reach open state
```

**Comment by peacememories** [comment] 2024-05-23 14:11
> Hello @peacememories, can you check if this is the same issue as discussed on #9383?

`DRI_PRIME` is not set on my machine, which makes sense since it's a desktop with only one, dedicated, GPU (the 5800x3d does not even have an IGP)

**Comment by RisaI** [comment] 2024-05-27 17:29
This happens to me too, also tested with the flatpak version and steam-runtime. 

Steam client version (build number or date): 1716584667
Distribution (e.g. Ubuntu): Arch Linux
Opted into Steam client beta?: No
Have you checked for system updates?: Yes
Steam Logs: -
GPU: AMD Radeon 7900 XTX

**Comment by RisaI** [comment] 2024-06-07 11:00
@OdinVex Interestingly enough, Steam works just fine on my laptop with an almost identical Arch installation. I wasn't able to isolate anything yet though.

**Comment by oliverlynch** [comment] 2024-06-10 14:39
Also experiencing this issue on EndevourOS, Steam takes over a minute to launch, CS2 is unplayable with massive frame rate drops every few seconds. I collected logs based on [this request](https://github.com/ValveSoftware/steam-for-linux/issues/10504#issuecomment-2145784328), which seems to be relevant to this issue.

Logs & System information: [Gist](https://gist.github.com/oliverlynch/9736e04560480d85a2add5a9a4912ff1)

It looks like steam generated a dump file at launch, if that is useful I can upload it.

**Comment by RisaI** [comment] 2024-06-15 16:23
After spending some minutes staring at `lsof` output, I realized Steam was somehow using my work-related loopback hostnames I had defined in `/etc/hosts`. After I removed those, the issue went away as well as other Big Picture issues including the startup intro being transparent and the escape menu not working.

**Comment by RisaI** [comment] 2024-06-16 07:53
I've further narrowed it down to Steam having problems with loopback hostnames containing hyphens. By appending `/etc/hosts` with:

```
127.0.0.1 te-st
```

I've been able to reproduce the issue on previously unaffected machines. Replacing `te-st` with `test` make Steam work well again.

@OdinVex try to run `lsof -c steam` while steam is running and watch out for similar lines:

```
steam     359053 USER  42u     IPv4            2732420       0t0      TCP te-st:57343 (LISTEN)
```

**Comment by cpmiller** [comment] 2024-06-19 16:44
Arch Linux, up-to-date.

Adding a +1 to Steam not handling hyphenated hostnames.  I've been experiencing the same startup patten described her.  My hostfile looked exactly like this (EAC Workaround provided by https://github.com/starcitizen-lug/lug-helper for Star Citizen)

```
# Static table lookup for hostnames.
# See hosts(5) for details.

127.0.0.1 modules-cdn.eac-prod.on.epicgames.com #Star Citizen EAC workaround
```

Added a `#` to comment out the EAC line and Steam starts right away.

**Comment by fmorgner** [comment] 2024-06-23 22:27
I'm not running systemd-resolved on any of my systems but my laptop (same OS as my main machine) does not exhibit the slow startup/reaction time of steam. I experimented with the NSS config of my main machine, and going from `mdns` to `mdns_minimal` seems to have resolved the slow down on that specific machine.

**Comment by DiegoGiovany** [comment] 2024-06-24 22:28
same erros using crossover 24 on macos, tried wineskin, whisky and vanilla wine, everything with same results....

**Comment by mattaw** [comment] 2024-07-12 02:01
I want to add that after switching hosts in `/etc/nsswitch.conf` from `mdns` to `mdns_minimal` steam starts right up. Before then I had a large delay, and the websocket warnings.

**Comment by another-username2** [comment] 2024-07-13 15:25
> I have the same issue with extremely stupidly long startup times (15 ****ing minutes on [16C32T@4.5GHz](mailto:16C32T@4.5GHz) 64GB DDR4 4x2TB NVMe RAID0, so it's NOT my ****). I've resorted to starting steam in a shell and spamming Ctrl+C sporadically terminating crap in the background it attempts to launch, it can speed up my startup times. Do it enough and you'll notice patterns around that plagueware of Chromium underneath and the entire websocket garbage. Edit: I despise this new UI so much. I miss the old Steam UI, functional and fast (aside from DPI issues and rasterized images). My frustration with this stems from a year of this expecting better but getting the same no-dpi-slider crap.
> 
> Steam Version: 1715635533 Distro: Manjaro KDE (64 bit) Wayland GPU: RX 5700 XT x 2

I agree. JS on the desktop is inappropriate and a technically uninformed decision.

Though, I do admire Valve for being so... determined... as to make a thoroughly bad idea work as it does and ignore all the bright-red, illuminated flags.

> I wonder if Steam developers are assuming something about mDNS or DNS caching?
Apparently, assumptions abound. It seems nobody thought enough about checking return values, either.

> I may try moving `files` up in the NSS stack and put an entry in there for `steamloopback.host`, maybe that would work too. Don't get me wrong, I'm not arguing that this would be an acceptable solution to this problem, but neither is having to fall back onto `mdns_minimal`
When working knowledge disappears, workarounds become the 'fix'. It's pathetic and scary how commercial software is produced.

> Interesting. I disabled systemd-resolved and switched to minimal, working.
If you have to reconfigure your system and network because of someone else's ignorant oversight, something has gone very wrong with both software development AND troubleshooting.

**Comment by Not-Zero-Blank** [comment] 2024-07-22 16:42
> > I've further narrowed it down to Steam having problems with loopback hostnames containing hyphens. By appending `/etc/hosts` with:
> > ```
> > 127.0.0.1 te-st
> > ```
> 
> Valid host names are `a-z9-0` and `-`. If CEF/Steam has an issue with that then Steam is the problem. I use IPv6, so there's no way I can remove the IPv6 loopbacks. I'm not going to, either. CEF needs to go. Steam should just use something cross-platform like Qt.

Im speechless thats just unprofessional

**Comment by akrychowski** [comment] 2024-07-23 12:37
On fedora 40 affected by this problem, removing the 127.0.0.1 view-localhost in hosts helped.

**Comment by royborgen** [comment] 2024-07-24 08:30
I can confirm the same issue on Ubuntu 24.04. Here is console log: 

```
steam.sh[60447]: Running Steam on ubuntu 24.04 64-bit
steam.sh[60447]: STEAM_RUNTIME is enabled automatically
setup.sh[60564]: Steam runtime environment up-to-date!
steam.sh[60447]: Steam client's requirements are satisfied
[2024-07-24 10:26:18] Startup - updater built Jul 16 2024 23:21:18
[2024-07-24 10:26:18] Startup - Steam Client launched with: '/home/user/.local/share/Steam/ubuntu12_32/steam' '-srt-logger-opened'
07/24 10:26:18 minidumps folder is set to /tmp/dumps
07/24 10:26:18 Init: Installing breakpad exception handler for appid(steam)/version(1721173382)/tid(60633)
[2024-07-24 10:26:18] Loading cached metrics from disk (/home/user/.local/share/Steam/package/steam_client_metrics.bin)
[2024-07-24 10:26:18] Using the following download hosts for Public, Realm steamglobal
[2024-07-24 10:26:18] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2024-07-24 10:26:18] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2024-07-24 10:26:18] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2024-07-24 10:26:18] Verifying installation...
[2024-07-24 10:26:18] Verification complete
UpdateUI: skip show logo
Steam logging initialized: directory: /home/user/.local/share/Steam/logs

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xe7993860
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xe7991fc0
/usr/share/themes/Yaru-blue-dark/gtk-2.0/main.rc:775: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Yaru-blue-dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
CAppInfoCacheReadFromDiskThread took 61 milliseconds to initialize
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 60754
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
BRefreshApplicationsInLibrary 1: 0ms
src/steamUI/webuitransportcontroller.cpp (206) : Failed to connect to websocket
src/steamUI/webuitransportcontroller.cpp (206) : Failed to connect to websocket
07/24 10:27:03 Init: Installing breakpad exception handler for appid(steam)/version(1721173382)/tid(60633)
assert_20240724102703_36.dmp[61589]: Uploading dump (out-of-process)
/tmp/dumps/assert_20240724102703_36.dmp
BuildCompleteAppOverviewChange: 236 apps
RegisterForAppOverview 1: 8ms
RegisterForAppOverview 2: 8ms
assert_20240724102703_36.dmp[61589]: Finished uploading minidump (out-of-process): success = yes
assert_20240724102703_36.dmp[61589]: response: CrashID=bp-c8bfd9f4-938e-4996-b10b-6909b2240724
assert_20240724102703_36.dmp[61589]: file ''/tmp/dumps/assert_20240724102703_36.dmp'', upload yes: ''CrashID=bp-c8bfd9f4-938e-4996-b10b-6909b2240724''
```

**Comment by royborgen** [comment] 2024-07-24 08:57
> On fedora 40 affected by this problem, removing the 127.0.0.1 view-localhost in hosts helped.

I can confirm this is also the case in Ubuntu 24.04. However after testing I found that changing the order of the entries in /etc hosts and putting localhost before view-localhost worked

**Comment by colinmarc** [comment] 2024-08-05 21:46
Confirmed this bug on a Manjaro machine with multiple hyphens in the hostname. I'm flabbergasted that this is a real thing.

**Comment by Acithium** [comment] 2024-08-19 02:16
> > On fedora 40 affected by this problem, removing the 127.0.0.1 view-localhost in hosts helped.
> 
> I can confirm this is also the case in Ubuntu 24.04. However after testing I found that changing the order of the entries in `/etc/hosts` and putting localhost before view-localhost fixed the issue

Running Fedora 40 and this fixed the issue fore me as well.

**Comment by PorcelainMouse** [comment] 2024-08-21 08:12
> > > On fedora 40 affected by this problem, removing the 127.0.0.1 view-localhost in hosts helped.
> > 
> > 
> > I can confirm this is also the case in Ubuntu 24.04. However after testing I found that changing the order of the entries in `/etc/hosts` and putting localhost before view-localhost fixed the issue
> 
> Running Fedora 40 and this fixed the issue fore me as well.

Me too.  This fixed a problem I've had for a short while.  I'm almost certain this is caused by VMWare Horizon Client RPM.  The RPM postinst script must be plopping this line at the top of /etc/hosts without any care whatsoever.  Outrageous behavior by VMWare; completely inexcusable.

**Comment by DollarStoreCPU** [comment] 2024-08-22 17:47
Bumping because I am also running into this issue. Switched the order of the first to lines in my /etc/hosts file and Steam fired right up. Found this issue because of a [steam client beta community discussion](https://steamcommunity.com/groups/SteamClientBeta/discussions/3/4433317658011281841/) that linked me here. Hope this gets fixed soon. That was annoying to google-fu.

**Comment by PorcelainMouse** [comment] 2024-09-07 09:07
> > Replying to [#10879 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/10879#issuecomment-2301430084)
> 
> No, VMware is fine to do that, it's 100% valid behavior. Dashes/hyphens are valid characters, follows RFC specifications.

No, that's not what I'm talking about. It's not a problem with hostname chars.

All aliases need to be on the same line in `/etc/hosts`.  man page says "For each host a single line should be present ...".  RFC 952 is referenced, but that's doesn't describe Linux's format requirements for the hosts table.  I'm pointing out the fact that you can't just jam text at the top of the file and supersede ever other definition in the file; that's undefined behavior, and therefore, illegal. Also, they're trying to change the loopback alias, which is very special and treated specially by the network stack, and they *know* that if /etc/hosts has any lines in it, one is guaranteed to be for 172.0.0.1.  So, you have to scan for that line and take extra care if you are going to modify it.  Besides, what was wrong with using `localhost`???  You can just use that and be (nearly?) guaranteed that is what you want. That's what that name standard is there for in the first pace! Or, better yet, if you want to hard code something, just f-ing use the IP addr and skip name resolution all-together.

Fine, it's probably weird for either Steam or VMware Client to use loopback for whatever the hell they are doing that could be more sensibly done with other IPC methods.  But, VMware broke not just rules, but common decency.  Post-Inst scripts for client software?  Give me a break.

**Comment by PorcelainMouse** [comment] 2024-09-08 09:56
Okay, but, I'm still confident you are wrong about `/etc/hosts`.  Perhaps I didn't quote you the best line from the man page, but it begins:  "This manual page describes the format of the /etc/hosts file. This file is a simple text file that associates IP addresses with hostnames, one line per IP address."  The man page is _not_ ambiguous on this point.  I understand the distinction between addrs, hosts, and host names.

The man page even suggests using 127.0.**1**.1 for the FQDN of local _host_, which is yet another valid option that VMware chose to ignore.

Now, I'm not saying what VMWare did breaks *everything*, but it breaks the rules and it broke some actual functionality in other programs.

Yes, I transposed digits in the first octet.  That's correct.

We don't really need adjudicate this, but I still don't understand 1) what's up with CEF--I know nothing about that, happily--and what that has to do with name resolution, and 2) why VMware can't follow the GD rules and just put their pet alias on the line with all the other aliases for localhost.

But, hey, I don't mean to defend Steam devs.  I'm sure what you say about Steam is also valid criticism.

**Comment by PorcelainMouse** [comment] 2024-09-11 05:03
I'm blaming VMware because they added an invalid line to `/etc/hosts`, and that broke things.  There may very well be a separate, additional issue.

I don't understand your problem with loopback.  That method of IPC has been around, like, for 40 years at least?  It's hardly unusual to talk to yourself over loopback.  What's "moronic" is requiring a private alias to tell you what is the loopback addr. 

Besides, I brought up the loopback space only because you brought it up.  The `hosts` rules could have been respected if VMWare had just chosen a unique addr; then they could have added the line--TO THE END OF THE FILE, NOT THE BEGINNING!--and everything would have worked out.  And wouldn't that have been better for routing, too? It's a whole Class A go work with!  Why not make you own "localhost subnet"?  I still don't see what this has to do with mdns or resolution.  I mean, IP routing happens at the IP layer; there are no names in routing.  But, as I say, CEF is new to me.  (Although, there is a Cisco networking technology called CEF that I thought you were talking about, at first, which only makes things more confusing.)

Hmm, I guess I would have been even more mad if VMWare client had altered the routing table.

**Comment by PorcelainMouse** [comment] 2024-09-14 07:33
Interesting.  I'm certainly on your side about having a web-server and client as your "app". No arguments there; that is pretty stupid.  On the other hand, it's nice to have a hard separation between UI and functionality.  I wouldn't want a whole HTTP server + client between the two, but if you have the separation, you can put anything in between you like, I guess.  But, yeah, CEF sounds lame.  I'm guessing that it has something to do with the whole thing where everything has to be "mobile", and we need to trash all the desktop apps until they suck.  This is why we can't have nice things.   Cheers, mate.

**Comment by lostgoat** [comment] 2024-09-30 18:39
Hey, thanks everyone for all the info.

First, a small clarification. The `steamloopback.host` hostname is unrelated to the websocket connection error. It gets printed as a prefix to each message in the log file because that is where the `js` file was loaded from. But it shouldn't be involved at all in the websocket connection.

The websocket connection is initiated by the `steamwebhelper` process, and it tries to connect to `localhost`. From what I've read in the reports above, it seems like there is a problem in resolving `localhost` in some systems. We can probably make this more reliably on the steam side by trying `127.0.0.1` if connecting to `localhost` fails.

I would like to confirm that this is the case though. For anyone experiencing the issue, could you collect the following info:
- `ping -4 -c 1 localhost`
- `ping -6 -c 1 localhost`
- `pstree` when steam is running
- Steam logs: `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`. In particular, the relevant files are `webhelper.txt` and `transport_steamui.txt` if you'd prefer to share just those two.

For users where this issue can be triggered by changing your hosts file, it would be good to know if the above `ping` commands yield any different results with the good/bad hosts configurations.

**Comment by royborgen** [comment] 2024-09-30 19:46
> For users where this issue can be triggered by changing your hosts file, it would be good to know if the above `ping` commands yield any different results with the good/bad hosts configurations.

Testet den above ping commands with `127.0.0.1 localhost` added to top of hosts-file and as the second entry. 

With localhost being the top entry in hosts: 
```
~$ ping -4 -c 1 localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.019 ms

--- localhost ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.019/0.019/0.019/0.000 ms
```

With localhost being the second entry from top: 
```
~$ ping -4 -c 1 localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from view-localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.030 ms

--- localhost ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.030/0.030/0.030/0.000 ms

```
As you can see there an increased delay. 

The other command `ping -6 -c 1 localhost` produce the same result for both settings:  
```
~$ ping -6 -c 1 localhost
ping: localhost: Address family for hostname not supported
```
I guess this is because I don't use IPv6

**Comment by lostgoat** [comment] 2024-09-30 20:54
@OdinVex My understanding is that this issue is about the client taking a long time start due to the websocket connection between `steamwebhelper` and `steam` fails to be established.

If you have concerns about `steamloopback.host`, can I trouble you to put them in a separate issue?

**Comment by lostgoat** [comment] 2024-09-30 21:23
@royborgen thanks again for the info. I can reproduce the problem locally based on the data you provided.

**Comment by lostgoat** [comment] 2024-09-30 22:01
Thanks everyone, a fix is queued up. I will update this issue once it makes it to a public build.

**Comment by lostgoat** [comment] 2024-10-03 04:18
@royborgen the fix should be available in the latest beta. Can you confirm it also works on your side?

**Comment by royborgen** [comment] 2024-10-03 12:05
> @royborgen the fix should be available in the latest beta. Can you confirm it also works on your side?

That seems to have fixed it :) 
Thanks a lot <3

**Comment by lostgoat** [comment] 2024-10-04 03:07
Thanks for checking. Closing this issue for now as the other user reports with logs had the same symptoms in them.

**Closed** 2024-10-04 03:07 UTC
Labels: Steam client, Need Retest
