### ISSUE TITLE
Steamwebhelper not responding

### ISSUE THREAD

**Issue by VidmoVDZ** [ValveSoftware/steam-for-linux#11087] opened 2024-07-13 11:22 UTC
#### Your system information

* Steam client version (build number or date): 1.0.0.79-6
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] NO
* Have you checked for system updates?: [Yes/No] YES
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

So, after launching steam, there appeared dialog with "Webhelper not responding". When sometimes I can reach steam there is error `cannot read properties of undefined (reading 'GetPlayer')` inside steam.

#### Steps for reproducing this issue:

1. Tried to run without GPU Accelerate, nothing changed
2. Tried to disable sandboxing, nothing changed
3. Tried clicking canel, sometimes it gave me steam but with error
4. Tried restarting steam
5. Tried restarting webhelper

`
//////////////////////////////////////////
//// logs/webhelper-linux.txt ////
/////////////////////////////////////////

steamwebhelper.sh[1797]: === wto, 9 lip 2024, 15:32:41 CEST ===
steamwebhelper.sh[1797]: Unable to find 0/amd64/usr/bin/steam-runtime-supervisor, falling back
steamwebhelper.sh[1797]: Starting steamwebhelper under bootstrap sniper steam runtime via /home/vidmo/.local/share/Steam/ubuntu12_64/steam-runtime-sniper.sh
steamwebhelper.sh[1797]: Using CEF sandbox \(try with -no-cef-sandbox if this fails\)
steamwebhelper.sh[1797]: Starting steamwebhelper with Sniper steam runtime at /home/vidmo/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/_v2-entry-point
exec ./steamwebhelper -lang=en_US -cachedir=/home/vidmo/.local/share/Steam/config/htmlcache -steampid=1394 -buildid=1718904662 -steamid=0 -logdir=/home/vidmo/.local/share/Steam/logs -uimode=7 -startcount=1 -userdatadir=/home/vidmo/.local/share/Steam/config/cefdata -steamuniverse=Public -realm=Global -clientui=/home/vidmo/.local/share/Steam/clientui -steampath=/home/vidmo/.local/share/Steam/ubuntu12_32/steam -launcher=0 -no-restart-on-ui-mode-change --valve-enable-site-isolation --enable-smooth-scrolling --password-store=basic --log-file=/home/vidmo/.local/share/Steam/logs/cef_log.txt --disable-quick-menu --disable-features=SpareRendererForSitePerProcess,DcheckIsFatal
[0709/153409.984598:ERROR:context.cc(100)] The browser_subprocess_path directory (./steamwebhelper) is not an absolute path. Defaulting to empty.
[0709/153413.745127:WARNING:crash_reporting.cc(278)] Failed to set crash key: UserID with value: 0
[0709/153413.745470:WARNING:crash_reporting.cc(278)] Failed to set crash key: BuildID with value: 1718903461
[0709/153413.745505:WARNING:crash_reporting.cc(278)] Failed to set crash key: SteamUniverse with value: Public
[0709/153413.745538:WARNING:crash_reporting.cc(278)] Failed to set crash key: Vendor with value: Valve
[0709/153413.745572:WARNING:crash_reporting.cc(278)] Failed to set crash key: Platform with value: Linux
[0709/153413.768415:INFO:crash_reporting.cc(239)] Crash reporting enabled for process: browser
[0709/153414.983383:WARNING:task_impl.cc(32)] No task runner for threadId 0
[0709/153415.511239:WARNING:task_impl.cc(32)] No task runner for threadId 0
[0709/153420.022187:WARNING:crash_reporting.cc(278)] Failed to set crash key: UserID with value: 0
[0709/153420.026764:WARNING:crash_reporting.cc(278)] Failed to set crash key: BuildID with value: 1718904662
[0709/153420.026794:WARNING:crash_reporting.cc(278)] Failed to set crash key: SteamUniverse with value: Public
[0709/153420.026819:WARNING:crash_reporting.cc(278)] Failed to set crash key: Vendor with value: Valve
[0709/153420.026843:WARNING:crash_reporting.cc(278)] Failed to set crash key: Platform with value: Linux
[0709/153420.211858:WARNING:crash_reporting.cc(278)] Failed to set crash key: UserID with value: 0
[0709/153420.212610:WARNING:crash_reporting.cc(278)] Failed to set crash key: BuildID with value: 1718904662
[0709/153420.212638:WARNING:crash_reporting.cc(278)] Failed to set crash key: SteamUniverse with value: Public
[0709/153420.212663:WARNING:crash_reporting.cc(278)] Failed to set crash key: Vendor with value: Valve
[0709/153420.212687:WARNING:crash_reporting.cc(278)] Failed to set crash key: Platform with value: Linux
srt-logger[2926]: Log opened 2024-07-09 15:39:04+0200
steamwebhelper.sh[2921]: Using supervisor /home/vidmo/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-supervisor
steamwebhelper.sh[2921]: Starting steamwebhelper under bootstrap sniper steam runtime via /home/vidmo/.local/share/Steam/ubuntu12_64/steam-runtime-sniper.sh
steamwebhelper.sh[2921]: Using CEF sandbox \(try with -no-cef-sandbox if this fails\)
steamwebhelper.sh[2921]: Starting steamwebhelper with Sniper steam runtime at /home/vidmo/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/_v2-entry-point
exec ./steamwebhelper -lang=en_US -cachedir=/home/vidmo/.local/share/Steam/config/htmlcache -steampid=2888 -buildid=1718904662 -steamid=0 -logdir=/home/vidmo/.local/share/Steam/logs -uimode=7 -startcount=0 -userdatadir=/home/vidmo/.local/share/Steam/config/cefdata -steamuniverse=Public -realm=Global -clientui=/home/vidmo/.local/share/Steam/clientui -steampath=/home/vidmo/.local/share/Steam/ubuntu12_32/steam -launcher=0 -no-restart-on-ui-mode-change --valve-enable-site-isolation --enable-smooth-scrolling --password-store=basic --log-file=/home/vidmo/.local/share/Steam/logs/cef_log.txt --disable-quick-menu --disable-features=SpareRendererForSitePerProcess,DcheckIsFatal
[0709/153946.432596:ERROR:context.cc(100)] The browser_subprocess_path directory (./steamwebhelper) is not an absolute path. Defaulting to empty.
[0709/153947.513718:WARNING:crash_reporting.cc(278)] Failed to set crash key: UserID with value: 0
[0709/153947.514656:WARNING:crash_reporting.cc(278)] Failed to set crash key: BuildID with value: 1718903461
[0709/153947.514681:WARNING:crash_reporting.cc(278)] Failed to set crash key: SteamUniverse with value: Public
[0709/153947.514704:WARNING:crash_reporting.cc(278)] Failed to set crash key: Vendor with value: Valve
[0709/153947.514726:WARNING:crash_reporting.cc(278)] Failed to set crash key: Platform with value: Linux
[0709/153947.517412:INFO:crash_reporting.cc(239)] Crash reporting enabled for process: browser
[0709/153947.768750:WARNING:task_impl.cc(32)] No task runner for threadId 0
[0709/153947.774174:WARNING:task_impl.cc(32)] No task runner for threadId 0
[0709/153948.031631:WARNING:crash_reporting.cc(278)] Failed to set crash key: UserID with value: 0
[0709/153948.033435:WARNING:crash_reporting.cc(278)] Failed to set crash key: BuildID with value: 1718904662
[0709/153948.033602:WARNING:crash_reporting.cc(278)] Failed to set crash key: SteamUniverse with value: Public
[0709/153948.033681:WARNING:crash_reporting.cc(278)] Failed to set crash key: Vendor with value: Valve
[0709/153948.033755:WARNING:crash_reporting.cc(278)] Failed to set crash key: Platform with value: Linux
[0709/153948.038928:WARNING:crash_reporting.cc(278)] Failed to set crash key: UserID with value: 0
[0709/153948.039328:WARNING:crash_reporting.cc(278)] Failed to set crash key: BuildID with value: 1718904662
[0709/153948.039385:WARNING:crash_reporting.cc(278)] Failed to set crash key: SteamUniverse with value: Public
[0709/153948.039408:WARNING:crash_reporting.cc(278)] Failed to set crash key: Vendor with value: Valve
[0709/153948.039428:WARNING:crash_reporting.cc(278)] Failed to set crash key: Platform with value: Linux
Gtk-Message: 15:41:17.163: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:41:17.647: Failed to load module "colorreload-gtk-module"
[0709/154118.576060:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: Brak interfejsu „org.freedesktop.portal.FileChooser”
[0709/154118.613545:INFO:crash_reporting.cc(262)] Crash reporting enabled for process: gpu-process
[0709/154118.664892:WARNING:property.cc(144)] version: GetAndBlock: failed.
[0709/154118.668060:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
[0709/154122.309136:WARNING:sandbox_linux.cc(385)] InitializeSandbox() called with multiple threads in process gpu-process.
[0709/154123.965469:WARNING:crash_reporting.cc(278)] Failed to set crash key: UserID with value: 0
[0709/154123.974676:WARNING:crash_reporting.cc(278)] Failed to set crash key: BuildID with value: 1718904662
[0709/154123.974762:WARNING:crash_reporting.cc(278)] Failed to set crash key: SteamUniverse with value: Public
[0709/154123.974844:WARNING:crash_reporting.cc(278)] Failed to set crash key: Vendor with value: Valve
[0709/154123.974923:WARNING:crash_reporting.cc(278)] Failed to set crash key: Platform with value: Linux
[0709/154124.007266:INFO:crash_reporting.cc(239)] Crash reporting enabled for process: utility
[0709/154622.532585:ERROR:network_service_instance_impl.cc(539)] Network service crashed, restarting service.
[0709/154622.837112:WARNING:crashpad_client_linux.cc(417)] prctl: Invalid argument (22)
[0709/154622.841744:ERROR:zygote_communication_linux.cc(291)] Failed to send GetTerminationStatus message to zygote
[0709/154622.841944:WARNING:zygote_communication_linux.cc(303)] Socket closed prematurely.
[0709/154622.854052:ERROR:gpu_process_host.cc(985)] GPU process launch failed: error_code=1002
[0709/154622.854283:WARNING:gpu_process_host.cc(1338)] The GPU process has crashed 1 time(s)
[0709/154622.961243:ERROR:gpu_process_host.cc(985)] GPU process launch failed: error_code=1002
[0709/154622.961490:WARNING:gpu_process_host.cc(1338)] The GPU process has crashed 2 time(s)
[0709/154622.965763:ERROR:gpu_process_host.cc(985)] GPU process launch failed: error_code=1002
[0709/154622.965885:WARNING:gpu_process_host.cc(1338)] The GPU process has crashed 3 time(s)
[0709/154623.196798:ERROR:gpu_process_host.cc(985)] GPU process launch failed: error_code=1002
[0709/154623.196928:WARNING:gpu_process_host.cc(1338)] The GPU process has crashed 4 time(s)
[0709/154623.202557:ERROR:gpu_process_host.cc(985)] GPU process launch failed: error_code=1002
[0709/154623.202725:WARNING:gpu_process_host.cc(1338)] The GPU process has crashed 5 time(s)
[0709/154623.206082:ERROR:gpu_process_host.cc(985)] GPU process launch failed: error_code=1002
[0709/154623.206172:WARNING:gpu_process_host.cc(1338)] The GPU process has crashed 6 time(s)
[0709/154623.251514:ERROR:gpu_process_host.cc(985)] GPU process launch failed: error_code=1002
[0709/154623.251680:WARNING:gpu_process_host.cc(1338)] The GPU process has crashed 7 time(s)
[0709/154623.255088:ERROR:gpu_process_host.cc(985)] GPU process launch failed: error_code=1002
[0709/154623.255266:WARNING:gpu_process_host.cc(1338)] The GPU process has crashed 8 time(s)
[0709/154623.258490:ERROR:gpu_process_host.cc(985)] GPU process launch failed: error_code=1002
[0709/154623.258647:WARNING:gpu_process_host.cc(1338)] The GPU process has crashed 9 time(s)
[0709/154623.258764:FATAL:gpu_data_manager_impl_private.cc(440)] GPU process isn't usable. Goodbye.
[0709/154625.576297:WARNING:crash_reporting.cc(278)] Failed to set crash key: UserID with value: 0
[0709/154625.622082:WARNING:crash_reporting.cc(278)] Failed to set crash key: BuildID with value: 1718904662
[0709/154625.622116:WARNING:crash_reporting.cc(278)] Failed to set crash key: SteamUniverse with value: Public
[0709/154625.622142:WARNING:crash_reporting.cc(278)] Failed to set crash key: Vendor with value: Valve
[0709/154625.622167:WARNING:crash_reporting.cc(278)] Failed to set crash key: Platform with value: Linux
[0709/154625.787534:WARNING:crashpad_client_linux.cc(362)] prctl: Invalid argument (22)
[0709/154625.793448:INFO:crash_reporting.cc(239)] Crash reporting enabled for process: utility
srt-logger[4223]: Log opened 2024-07-09 15:47:49+0200
steamwebhelper.sh[4218]: Using supervisor /home/vidmo/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-supervisor
steamwebhelper.sh[4218]: Starting steamwebhelper under bootstrap sniper steam runtime via /home/vidmo/.local/share/Steam/ubuntu12_64/steam-runtime-sniper.sh
steamwebhelper.sh[4218]: Using CEF sandbox \(try with -no-cef-sandbox if this fails\)
steamwebhelper.sh[4218]: Starting steamwebhelper with Sniper steam runtime at /home/vidmo/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/_v2-entry-point
exec ./steamwebhelper -lang=en_US -cachedir=/home/vidmo/.local/share/Steam/config/htmlcache -steampid=4187 -buildid=1718904662 -steamid=0 -logdir=/home/vidmo/.local/share/Steam/logs -uimode=7 -startcount=0 -userdatadir=/home/vidmo/.local/share/Steam/config/cefdata -steamuniverse=Public -realm=Global -clientui=/home/vidmo/.local/share/Steam/clientui -steampath=/home/vidmo/.local/share/Steam/ubuntu12_32/steam -launcher=0 -no-restart-on-ui-mode-change --valve-enable-site-isolation --enable-smooth-scrolling --password-store=basic --log-file=/home/vidmo/.local/share/Steam/logs/cef_log.txt --disable-quick-menu --disable-features=SpareRendererForSitePerProcess,DcheckIsFatal
[0709/154823.885552:ERROR:context.cc(100)] The browser_subprocess_path directory (./steamwebhelper) is not an absolute path. Defaulting to empty.
[0709/154824.161631:WARNING:crash_reporting.cc(278)] Failed to set crash key: UserID with value: 0
[0709/154824.162045:WARNING:crash_reporting.cc(278)] Failed to set crash key: BuildID with value: 1718903461
[0709/154824.162120:WARNING:crash_reporting.cc(278)] Failed to set crash key: SteamUniverse with value: Public
[0709/154824.162193:WARNING:crash_reporting.cc(278)] Failed to set crash key: Vendor with value: Valve
[0709/154824.162264:WARNING:crash_reporting.cc(278)] Failed to set crash key: Platform with value: Linux
[0709/154824.164600:INFO:crash_reporting.cc(239)] Crash reporting enabled for process: browser
[0709/154824.250144:WARNING:task_impl.cc(32)] No task runner for threadId 0
[0709/154824.255927:WARNING:task_impl.cc(32)] No task runner for threadId 0
[0709/154824.487561:WARNING:crash_reporting.cc(278)] Failed to set crash key: UserID with value: 0
[0709/154824.488093:WARNING:crash_reporting.cc(278)] Failed to set crash key: BuildID with value: 1718904662
[0709/154824.488171:WARNING:crash_reporting.cc(278)] Failed to set crash key: SteamUniverse with value: Public
[0709/154824.488565:WARNING:crash_reporting.cc(278)] Failed to set crash key: Vendor with value: Valve
[0709/154824.488644:WARNING:crash_reporting.cc(278)] Failed to set crash key: Platform with value: Linux
[0709/154824.495755:WARNING:crash_reporting.cc(278)] Failed to set crash key: UserID with value: 0
[0709/154824.496190:WARNING:crash_reporting.cc(278)] Failed to set crash key: BuildID with value: 1718904662
[0709/154824.496217:WARNING:crash_reporting.cc(278)] Failed to set crash key: SteamUniverse with value: Public
[0709/154824.496239:WARNING:crash_reporting.cc(278)] Failed to set crash key: Vendor with value: Valve
[0709/154824.496260:WARNING:crash_reporting.cc(278)] Failed to set crash key: Platform with value: Linux
Gtk-Message: 15:49:52.996: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:49:53.626: Failed to load module "colorreload-gtk-module"
[0709/154954.459120:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: Brak interfejsu „org.freedesktop.portal.FileChooser”
[0709/154954.620625:WARNING:property.cc(144)] version: GetAndBlock: failed.
[0709/154954.625459:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
[0709/154954.913232:INFO:crash_reporting.cc(262)] Crash reporting enabled for process: gpu-process
[0709/154958.395975:WARNING:sandbox_linux.cc(385)] InitializeSandbox() called with multiple threads in process gpu-process.
[0709/155000.095625:WARNING:crash_reporting.cc(278)] Failed to set crash key: UserID with value: 0
[0709/155000.105267:WARNING:crash_reporting.cc(278)] Failed to set crash key: BuildID with value: 1718904662
[0709/155000.105307:WARNING:crash_reporting.cc(278)] Failed to set crash key: SteamUniverse with value: Public
[0709/155000.105329:WARNING:crash_reporting.cc(278)] Failed to set crash key: Vendor with value: Valve
[0709/155000.105401:WARNING:crash_reporting.cc(278)] Failed to set crash key: Platform with value: Linux
[0709/155000.138095:INFO:crash_reporting.cc(239)] Crash reporting enabled for process: utility`

![2024-07-09_14-15](https://github.com/user-attachments/assets/42e4aaad-b775-44fb-a8a8-28c8b1d6ac08)

**Comment by another-username2** [comment] 2024-07-13 12:12
Your system information

    Steam client version (build number or date): 1718904662

    Distribution (e.g. Ubuntu): Ubuntu (5.15.0-107-generic #117~20.04.1-Ubuntu SMP Tue Apr 30 10:35:57 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux)

    Opted into Steam client beta?: [Yes/No] NO

    Have you checked for system updates?: [Yes/No] YES

    GPU: NVIDIA TU117 [GeForce GTX 1650] driver: nvidia v: 535.183.01


Bump.  I am also having this issue. Been having it for a few weeks, now.

I usually retry and wait for a Steam client update to arrive, but it's happened quite a few times over the past week or so, now and no updates have fixed it so here I am.

I found the log files (Maybe a crash reporter could provide necessary bug-reporting info links via a secondary application?  idk,)

I found the log files, tail'd them and re-launched... It displays fine, BUT the error STILL happened...
Logs:

`==> shader_log.txt <==
[2024-07-13 12:56:11] [AppID 312660] Target manifest 3371316184086377223 of size 20039564 key SteamSwarm / G7:VulkanPipelinesV6_904f69d2b1b44b65.
[2024-07-13 12:56:11] [AppID 312660] Source manifest 7898544230290636171 of size 19332439.

==> sitelicense_log.txt <==


[2024-07-13 12:56:11] Client version: 1718904662
[2024-07-13 12:56:11] Content cache info request: no local site servers

==> webhelper.txt <==
[2024-07-13 12:56:11] SP Desktop_uid0-'Steam': WasHidden 0: (0, 0) 1010x600
[2024-07-13 12:56:11] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: wayland: skipping init because GAMESCOPE_WAYLAND_DISPLAY is not set
[2024-07-13 12:56:11] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: Warning: wayland init failed, some functionality may be unavailable
[2024-07-13 12:56:11] SP Shared JS Context-'SharedJSCo': WARNING: https://steamloopback.host/library.js:2: wayland: skipping init because GAMESCOPE_WAYLAND_DISPLAY is not set
**[2024-07-13 12:56:11] SP Shared JS Context-'SharedJSCo': ERROR: https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=c6062d7de50e0588cde1:1: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'GetPlayer')**

==> webhelper-linux.txt <==
**[0713/125612.029093:INFO:CONSOLE(1)] "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'GetPlayer')", source: https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=c6062d7de50e0588cde1 (1)**

==> text_filter_log.txt <==


[2024-07-13 12:56:12] Client version: 1718904662
[2024-07-13 12:56:12] Requesting https://steamcommunity.com/textfilter/gettextfilterdictionary?type=profanity&language=english
[2024-07-13 12:56:12] Requesting https://steamcommunity.com/textfilter/gettextfilterdictionary?type=banned&language=eng`

Looks like a variable type error lol Is someone forgetting to check their return values before using them?

The 'Refresh' link in the error window doesn't work, either.

![Steam broken - Screenshot_2024-07-13_12-49-44](https://github.com/user-attachments/assets/bb6d2d65-0338-482d-a919-0138e354ddde)

[I am rather disappointed that it is written in JS. Using JS on the desktop is like using a fork to spread butter... Possible but not the best idea.]

**Comment by kisak-valve** [comment] 2024-07-13 12:47
Hello @VidmoVDZ, this issue is already being tracked at #11079. Closing as a duplicate.

**Closed by kisak-valve** 2024-07-13 12:47 UTC

**Comment by another-username2** [comment] 2024-07-13 14:38
> Hello @VidmoVDZ, this issue is already being tracked at #11079. Closing as a duplicate.

Different platforms... Same root cause?
