### ISSUE TITLE
Steam Tray Menu Items All Missing

### ISSUE THREAD

**Issue by glajchs** [ValveSoftware/steam-for-linux#4797] opened 2017-01-07 18:40 UTC
#### Your system information

* Steam client version: From "About Steam":
    Built: Jan 5 2017, at 18:41:06
    Steam API: v017
    Steam package versions: 1483649853
* Distribution (e.g. Ubuntu): Linux Mint 17 Qiana using XFCE (which is based off of Ubuntu 14.04.3 LTS trusty)
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
The system tray icon for Steam exists, but when I click on it, instead of getting a menu, I get a tiny menu with 0 items in it.  Since my "favorite" steam window, the window that opens upon startup, was friends, I couldn't get to my library to launch games.  I finally figured out that from friends I could get to settings and change my startup window to Library.

I have tried opting out of the beta steam client, and this fixes the issue.  When I opt back in, the issue is still present.

When launched via the command line, the beta client throws this message, but the normal client does not:
(steam:8498): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.40.2/./gobject/gsignal.c:2462: signal 'child-added' is invalid for instance '0xf829b088' of type 'GtkMenu'

![steam_tray_icon_clicked_no_menu_items](https://cloud.githubusercontent.com/assets/2104019/21744165/b464cfb2-d4de-11e6-8f2a-cd579d17644d.png)

#### Steps for reproducing this issue:

1. Use steam beta client
2. Open steam
3. Click on steam tray icon, menu is blank

**Comment by kisak-valve** [comment] 2017-01-07 19:16
Hello @glajchs, there's a good chance you have a partial system set of libappindicator, libindicator, and libdbusmenu. Either resolve these dependencies so steam only uses the system variant or start steam with the `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0` environment variable.

Closing as a duplicate of #4795.

**Closed by kisak-valve** 2017-01-07 19:16 UTC

**Comment by glajchs** [comment] 2017-01-10 01:00
Doing either "STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0" or installing i386 of libdbusmenu "sudo apt install libdbusmenu-gtk4:i386" (taken from the other bug) worked for me.  Thanks!

**Comment by 4ndyD** [comment] 2017-04-01 20:43
Using current Steam client on LM18.1 64bit XFCE, I have this problem even though I have all those dependencies and I have tried adding that variable to my launcher, although I'm not sure if I did that last part right.

Packages already installed, found by searching for those suggested:
```
Gir1.2-appindicator3-0.1
Libappindicator0.1-cil
Libappindicator1
Libappindicator3-1
Pythonappindicator
Libindicator3-7
Libindicator7
Gir1.2-dbusmenu-glib-0.4
Libdbusmenu-glib4
Libdbusmenu-gtk3-4
Libdbusmenu-gtk4
Libdbusmenu-qt2
Libdbusmenu-qt5
```

Launcher command:
`sh -c 'STEAM_FRAME_FORCE_CLOSE=1 STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam' %U`

**Comment by kisak-valve** [comment] 2017-04-01 23:23
Hello @4ndyD, Steam should need the 32 bit variants: Libappindicator1:i386, Libdbusmenu-glib4:i386, and Libdbusmenu-gtk4:i386, if those libraries are the 64 bit variants, then they would not be used by steam.

**Comment by 4ndyD** [comment] 2017-04-17 19:29
@kisak-valve that's weird, because I was using Steam on an i386 system before, til recently the browser stopped being supported for 32-bit versions of Linux, but at least the panel icon worked there.

Are you seriously telling me now that on an AMD64 system I would need to install 32-bit libraries? Those aren't included in the software manager, and I also checked, going and fetching those packages off launchpad and installing them requires the existing libraries to be uninstalled, along with a few other programs that already have them as dependencies.

I can't win here can I?

**Comment by kisak-valve** [comment] 2017-04-17 20:34
Steam itself is 32 bit, but the web component (libcef) is 64 bit because upstream support for the 32 bit build of the library was removed (http://www.omgubuntu.co.uk/2016/01/google-chrome-linux-32-bit-discontinued). I'm guessing you're trying to use mintinstall to install these libraries and it's giving you a simplified list of packages. You should be able to use apt to install those libraries.

**Comment by 4ndyD** [comment] 2017-04-17 21:08
Yes I mean they are not in mintinstall, but I get the same result whether I use apt to install them or fetch a deb file, it requires removing the 64-bit versions, which are dependencies for other things, so I guess a small sacrifice needs to be made either way for now, unless you know a way to hold both kinds of redundant libraries at once. Thanks anyway.

**Comment by kisak-valve** [comment] 2017-04-17 21:33
I'm not particularly experienced with Linux Mint, but that sounds like the equivilent of Debian's multiarch is not enabled. I'm guessing something along the lines of `dpkg --add-architecture i386` followed by `apt update` (based on https://wiki.debian.org/Multiarch/HOWTO).
