### ISSUE TITLE
Steam for Linux pointlessly downloads workshop content for non-Linux games.

### ISSUE THREAD

**Issue by aaronfranke** [ValveSoftware/steam-for-linux#4916] opened 2017-04-01 07:23 UTC
#### Your system information

* Steam client version (build number or date): Steam package version 1490228413 built on Mar 22 2017 at 23:45:04
* Distribution (e.g. Ubuntu): Xubuntu 16.04 64-bit
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. 

What I expected: Steam won't do anything with games that aren't installed or aren't available

What did happened: Steam downloads workshop content for a non-Linux game on Linux.

#### Steps for reproducing this issue:

1. Have Steam for Linux and a non-Linux game. 
2. Be subscribed to workshop content for that game.
3. When that content updates, Steam downloads the updates but there's no point at all since the game isn't installable anyway.

Image showing this issue: http://i.imgur.com/2zg6ptr.png

**Comment by kisak-valve** [comment] 2017-04-01 17:58
Closing as a duplicate of #2895.

**Closed by kisak-valve** 2017-04-01 17:58 UTC
Labels: Steam client
