### ISSUE TITLE
64bit games won't start on Debian unstable

### ISSUE THREAD

**Issue by DerBunman** [ValveSoftware/steam-for-linux#4319] opened 2016-02-15 16:59 UTC
When I start a 64 bit game in on Debian unstable I get invalid pointer errors since the last update. However, some games seem to run, when started from the terminal (eg Shovel Knight and Transistor).

**For example:**
Cities Skylines:
`*** Error in `/home/ichi/.steam/SteamApps/common/Cities_Skylines/Cities.x64': free(): invalid pointer: 0x00000000028e6d78 ***`

Shovel Knight:
`*** Error in `/home/ichi/.steam/SteamApps/common/Shovel Knight/64/ShovelKnight': free(): invalid pointer: 0x0000000001ed57a0 ***`

Transistor:
`*** Error in `./Transistor.bin.x86_64': free(): invalid pointer: 0x00007f7234000078 ***`

**My System:**

```
System:    Host: localhorst Kernel: 4.3.0-1-amd64 x86_64 (64 bit) Desktop: i3 4.11
           Distro: Debian GNU/Linux stretch/sid
Machine:   System: ASUS product: All Series
           Mobo: ASUSTeK model: Z87-K v: Rev X.0x Bios: American Megatrends v: 1402 date: 11/05/2014
CPU:       Quad core Intel Core i5-4570 (-MCP-) cache: 6144 KB 
           clock speeds: max: 3600 MHz 1: 3206 MHz 2: 3283 MHz 3: 3243 MHz 4: 3230 MHz
Graphics:  Card: NVIDIA GM204 [GeForce GTX 980]
           Display Server: X.Org 1.18.0 driver: nvidia Resolution: 1920x1080@60.00hz
           GLX Renderer: GeForce GTX 980/PCIe/SSE2 GLX Version: 4.5.0 NVIDIA 358.16
Audio:     Card-1 Intel 8 Series/C220 Series High Definition Audio Controller driver: snd_hda_intel
           Card-2 NVIDIA GM204 High Definition Audio Controller driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.3.0-1-amd64
Network:   Card: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller driver: r8169
           IF: eth0 state: up speed: 1000 Mbps duplex: full mac: ac:22:0b:82:2e:67
Drives:    HDD Total Size: 13292.2GB (56.3% used) ID-1: /dev/sda model: M4 size: 512.1GB
           ID-2: /dev/sdd model: WDC_WD40EFRX size: 4000.8GB ID-3: /dev/sdc model: WDC_WD40EFRX size: 4000.8GB
           ID-4: /dev/sdb model: Samsung_SSD_840 size: 250.1GB ID-5: /dev/sdf model: WDC_WD40EFRX size: 4000.8GB
           ID-6: /dev/sde model: M4 size: 512.1GB ID-7: USB /dev/sdg model: Rainbow_Line size: 15.5GB
Partition: ID-1: / size: 460G used: 283G (65%) fs: ext4 dev: /dev/sda1
           ID-2: swap-1 size: 10.74GB used: 0.00GB (0%) fs: swap dev: /dev/sda2
RAID:      Device-1: /dev/md0 - active raid: 5 components: online: 3/3 - sdc1 sdd1 sdf1
Sensors:   System Temperatures: cpu: 29.8C mobo: 27.8C gpu: 30C
           Fan Speeds (in rpm): cpu: 0
Info:      Processes: 242 Uptime: 6:27 Memory: 2536.4/15991.3MB Client: Shell (zsh) inxi: 2.2.28 
```

**Packages that where in the upgrade that broke 64 bit games:**

```
    Start-Date: 2016-02-15  11:17:46
    Commandline: apt upgrade
    Requested-By: ichi (1000)
    Install: 
        liblept5:amd64 (1.73-1+b1 automatic),
        libsnappy1v5:i386 (1.1.3-2 automatic),
        libsuitesparseconfig4.4.6:amd64 (4.4.6-1 automatic),
        php-phpseclib:amd64 (2.0.1-1 automatic),
        dbconfig-mysql:amd64 (2.0.2 automatic),
        libx265-79:i386 (1.9-dmo1 automatic),
        libilmbase12:amd64 (2.2.0-8 automatic),
        libopenexr22:amd64 (2.2.0-9 automatic)

    Upgrade:
        libkvazaar3:amd64 (0.8.3-dmo1, 0.8.3-dmo2),
        libkvazaar3:i386 (0.8.3-dmo1, 0.8.3-dmo2),
        lib32ubsan0:amd64 (5.3.1-7, 5.3.1-8),
        manpages:amd64 (4.04-0.1, 4.04-1),
        perl-base:amd64 (5.22.1-4, 5.22.1-7),
        libquadmath0-dbg:amd64 (5.3.1-7, 5.3.1-8),
        libmpx0:amd64 (5.3.1-7, 5.3.1-8),
        libgcj16:amd64 (5.3.1-7, 5.3.1-8),
        libdc1394-22:amd64 (2.2.3-1, 2.2.4-1),
        libdevmapper1.02.1:amd64 (1.02.115-1, 1.02.115-2),
        libltdl-dev:amd64 (2.4.2-1.11, 2.4.6-0.1),
        iso-codes:amd64 (3.64-1, 3.65-1),
        acpid:amd64 (2.0.25-1, 2.0.26-1),
        dmsetup:amd64 (1.02.115-1, 1.02.115-2),
        libnl-route-3-200:amd64 (3.2.26-1, 3.2.27-1),
        libavformat56:amd64 (2.8.5-dmo2, 2.8.6-dmo2),
        lib32mpx0:amd64 (5.3.1-7, 5.3.1-8),
        libgcc-5-dev:amd64 (5.3.1-7, 5.3.1-8),
        libisofs6:amd64 (1.4.2-1, 1.4.2-2),
        python-psutil:amd64 (3.4.1-1, 3.4.2-1),
        libaspectj-java:amd64 (1.8.5-1, 1.8.8-1),
        libavfilter5:amd64 (2.8.5-dmo2, 2.8.6-dmo2),
        libpackagekit-glib2-18:amd64 (1.0.11-1, 1.0.11-2),
        python-xapian:amd64 (1.2.22-1, 1.2.22-2),
        libvte-2.91-0:amd64 (0.42.1-2+b1, 0.42.3-1),
        handbrake:amd64 (0.10.3-dmo2, 0.10.3-dmo3),
        libchromaprint0:amd64 (1.2-dmo3, 1.3-dmo1),
        libgroupsock8:amd64 (2016.01.20-dmo1, 2016.01.29-dmo1),
        publicsuffix:amd64 (20160115-1, 20160130-1),
        netpbm:amd64 (10.0-15.2, 10.0-15.3),
        gir1.2-gtk-3.0:amd64 (3.18.6-1, 3.18.7-1),
        libx32itm1:amd64 (5.3.1-7, 5.3.1-8),
        ffmpeg:amd64 (2.8.5-dmo2, 2.8.6-dmo2),
        os-prober:amd64 (1.70, 1.71),
        linux-libc-dev:amd64 (4.3.3-7, 4.3.5-1),
        linux-libc-dev:i386 (4.3.3-7, 4.3.5-1),
        libatomic1-dbg:amd64 (5.3.1-7, 5.3.1-8),
        libapt-inst2.0:amd64 (1.2.1, 1.2.3),
        appstream:amd64 (0.9.0-3, 0.9.1-1),
        lib32stdc++-5-dev:amd64 (5.3.1-7, 5.3.1-8),
        libtool-bin:amd64 (2.4.2-1.11, 2.4.6-0.1),
        libgegl-0.3-0:amd64 (0.3.4-dmo1, 0.3.4-dmo2),
        imagemagick:amd64 (6.8.9.9-7, 6.8.9.9-7+b1),
        libgnutls-openssl27:amd64 (3.4.8-2, 3.4.9-2),
        lib32stdc++6:amd64 (5.3.1-7, 5.3.1-8),
        libswresample1:amd64 (2.8.5-dmo2, 2.8.6-dmo2),
        libswresample1:i386 (2.8.5-dmo2, 2.8.6-dmo2),
        g++-5-multilib:amd64 (5.3.1-7, 5.3.1-8),
        libopencv-imgproc2.4v5:amd64 (2.4.9.1+dfsg-1.2, 2.4.9.1+dfsg-1.3),
        libnl-genl-3-200:amd64 (3.2.26-1, 3.2.27-1),
        libopencv-objdetect2.4v5:amd64 (2.4.9.1+dfsg-1.2, 2.4.9.1+dfsg-1.3),
        p7zip:amd64 (9.20.1~dfsg.1-4.2, 9.20.1~dfsg.1-5),
        libsystemd0:amd64 (228-4+b1, 228-6),
        libsystemd0:i386 (228-4+b1, 228-6),
        libgtk-3-common:amd64 (3.18.6-1, 3.18.7-1),
        acl:amd64 (2.2.52-2, 2.2.52-3),
        libx32quadmath0:amd64 (5.3.1-7, 5.3.1-8),
        grub-common:amd64 (2.02~beta2-35, 2.02~beta2-36),
        transfig:amd64 (3.2.5.e-4, 3.2.5.e-5),
        aspectj:amd64 (1.8.5-1, 1.8.8-1),
        apt:amd64 (1.2.1, 1.2.3),
        libgtk-3-0:amd64 (3.18.6-1, 3.18.7-1),
        libacl1:amd64 (2.2.52-2, 2.2.52-3),
        python-cssutils:amd64 (1.0-4, 1.0-4.1),
        libjcommander-java:amd64 (1.35-1, 1.48-1),
        libobjc4:amd64 (5.3.1-7, 5.3.1-8),
        cpp-5:amd64 (5.3.1-7, 5.3.1-8),
        libcglib-java:amd64 (2.2.2+dfsg2-2, 3.2.0-2),
        libasound2-data:amd64 (1.0.29-1, 1.1.0-1),
        libgcc1-dbg:amd64 (5.3.1-7, 5.3.1-8),
        libtsan0-dbg:amd64 (5.3.1-7, 5.3.1-8),
        binutils:amd64 (2.26-2, 2.26-3),
        libmagickwand-6.q16-2:amd64 (6.8.9.9-7, 6.8.9.9-7+b1),
        libopencv-video2.4v5:amd64 (2.4.9.1+dfsg-1.2, 2.4.9.1+dfsg-1.3),
        libumfpack5.7.1:amd64 (4.4.5-2, 4.4.6-1),
        handbrake-cli:amd64 (0.10.3-dmo2, 0.10.3-dmo3),
        libitm1:amd64 (5.3.1-7, 5.3.1-8),
        libcamd2.4.1:amd64 (4.4.5-2, 4.4.6-1),
        libccolamd2.9.1:amd64 (4.4.5-2, 4.4.6-1),
        vlc-nox:amd64 (2.2.1-dmo14, 2.2.2-dmo1),
        perl-modules-5.22:amd64 (5.22.1-4, 5.22.1-7),
        lib32itm1:amd64 (5.3.1-7, 5.3.1-8),
        lib32asan2:amd64 (5.3.1-7, 5.3.1-8),
        nodejs:amd64 (4.2.6~dfsg-1, 4.3.0~dfsg-2),
        console-setup-linux:amd64 (1.134, 1.136),
        fop:amd64 (2.0+dfsg-5, 2.1-1),
        libx32gcc1:amd64 (5.3.1-7, 5.3.1-8),
        insserv:amd64 (1.14.0-5.1, 1.14.0-5.2),
        lib32gcc1-dbg:amd64 (5.3.1-7, 5.3.1-8),
        libthai-data:amd64 (0.1.24-1, 0.1.24-2),
        vlc-plugin-notify:amd64 (2.2.1-dmo14, 2.2.2-dmo1),
        libvlc5:amd64 (2.2.1-dmo14, 2.2.2-dmo1),
        grub2-common:amd64 (2.02~beta2-35, 2.02~beta2-36),
        gnutls-bin:amd64 (3.4.8-2, 3.4.9-2),
        udev:amd64 (228-4+b1, 228-6),
        libcilkrts5:amd64 (5.3.1-7, 5.3.1-8),
        console-setup:amd64 (1.134, 1.136),
        handbrake-gtk:amd64 (0.10.3-dmo2, 0.10.3-dmo3),
        rhythmbox-plugins:amd64 (3.2.1-1+b1, 3.3-1),
        alsa-utils:amd64 (1.0.29-1+b1, 1.1.0-2),
        libasan2:amd64 (5.3.1-7, 5.3.1-8),
        lib32gcc-5-dev:amd64 (5.3.1-7, 5.3.1-8),
        libquadmath0:amd64 (5.3.1-7, 5.3.1-8),
        libxmlgraphics-commons-java:amd64 (2.0.1-2, 2.1-1),
        libapt-pkg5.0:amd64 (1.2.1, 1.2.3),
        packagekit-tools:amd64 (1.0.11-1, 1.0.11-2),
        libpq5:amd64 (9.5.0-2, 9.5.0-3),
        libpq5:i386 (9.5.0-2, 9.5.0-3),
        ruby-unf-ext:amd64 (0.0.7.1-1+b3, 0.0.7.2-1),
        libx32gcc1-dbg:amd64 (5.3.1-7, 5.3.1-8),
        grub-pc:amd64 (2.02~beta2-35, 2.02~beta2-36),
        libcilkrts5-dbg:amd64 (5.3.1-7, 5.3.1-8),
        linux-headers-4.3.0-1-amd64:amd64 (4.3.3-7, 4.3.5-1),
        libpostproc53:amd64 (2.8.5-dmo2, 2.8.6-dmo2),
        libvlccore8:amd64 (2.2.1-dmo14, 2.2.2-dmo1),
        libudev1:amd64 (228-4+b1, 228-6),
        libudev1:i386 (228-4+b1, 228-6),
        libgomp1-dbg:amd64 (5.3.1-7, 5.3.1-8),
        libopencv-flann2.4v5:amd64 (2.4.9.1+dfsg-1.2, 2.4.9.1+dfsg-1.3),
        python-distutils-extra:amd64 (2.38-1, 2.39-1),
        libopencv-contrib2.4v5:amd64 (2.4.9.1+dfsg-1.2, 2.4.9.1+dfsg-1.3),
        phpmyadmin:amd64 (4.5.3.1-1, 4.5.4.1-2),
        lib32cilkrts5:amd64 (5.3.1-7, 5.3.1-8),
        libio-socket-ssl-perl:amd64 (2.022-1, 2.024-1),
        libltdl7:amd64 (2.4.2-1.11, 2.4.6-0.1),
        libltdl7:i386 (2.4.2-1.11, 2.4.6-0.1),
        installation-report:amd64 (2.61, 2.62),
        gcc-5-multilib:amd64 (5.3.1-7, 5.3.1-8),
        libopencv-highgui2.4v5:amd64 (2.4.9.1+dfsg-1.2, 2.4.9.1+dfsg-1.3),
        libcolamd2.9.1:amd64 (4.4.5-2, 4.4.6-1),
        libgcc1:amd64 (5.3.1-7, 5.3.1-8),
        libgcc1:i386 (5.3.1-7, 5.3.1-8),
        kodi:amd64 (15.2-dmo7, 15.2-dmo8),
        gir1.2-rb-3.0:amd64 (3.2.1-1+b1, 3.3-1),
        libperl5.22:amd64 (5.22.1-4, 5.22.1-7),
        python-cryptography:amd64 (1.2.1-1, 1.2.2-2),
        grub-pc-bin:amd64 (2.02~beta2-35, 2.02~beta2-36),
        gcc-5-base:amd64 (5.3.1-7, 5.3.1-8),
        gcc-5-base:i386 (5.3.1-7, 5.3.1-8),
        rhythmbox-data:amd64 (3.2.1-1, 3.3-1),
        lib32gcc1:amd64 (5.3.1-7, 5.3.1-8),
        gcj-5-jre-lib:amd64 (5.3.1-7, 5.3.1-8),
        libappstream-glib8:amd64 (0.5.5-1, 0.5.8-1),
        gnome-calculator:amd64 (3.18.2-1, 3.18.3-1),
        imagemagick-6.q16:amd64 (6.8.9.9-7, 6.8.9.9-7+b1),
        libnfs8:amd64 (1.9.8-dmo1, 1.10.0-dmo1),
        libstdc++-5-dev:amd64 (5.3.1-7, 5.3.1-8),
        libx32cilkrts5:amd64 (5.3.1-7, 5.3.1-8),
        nautilus:amd64 (3.18.4-1, 3.18.5-1),
        libnautilus-extension1a:amd64 (3.18.4-1, 3.18.5-1),
        libtsan0:amd64 (5.3.1-7, 5.3.1-8),
        libmagickcore-6.q16-2-extra:amd64 (6.8.9.9-7, 6.8.9.9-7+b1),
        gir1.2-wnck-3.0:amd64 (3.14.0-2, 3.14.1-1),
        kodi-skin-confluence:amd64 (15.2-dmo7, 15.2-dmo8),
        libgtk-3-bin:amd64 (3.18.6-1, 3.18.7-1),
        libnss-mdns:amd64 (0.10-6, 0.10-7),
        p7zip-full:amd64 (9.20.1~dfsg.1-4.2, 9.20.1~dfsg.1-5),
        libubsan0:amd64 (5.3.1-7, 5.3.1-8),
        libdatetime-timezone-perl:amd64 (1.94-1+2015g, 1.95-1+2016a),
        iceweasel:amd64 (43.0.4-1, 44.0-1),
        g++-5:amd64 (5.3.1-7, 5.3.1-8),
        gir1.2-vte-2.91:amd64 (0.42.1-2+b1, 0.42.3-1),
        steam:i386 (1.0.0.50-6, 1.0.0.51-1),
        libx32asan2:amd64 (5.3.1-7, 5.3.1-8),
        libnss-myhostname:amd64 (228-4+b1, 228-6),
        libgfortran3:amd64 (5.3.1-7, 5.3.1-8),
        libneon27-gnutls:amd64 (0.30.1-2+b2, 0.30.1-3),
        pinentry-gtk2:amd64 (0.9.7-1, 0.9.7-3),
        systemd-sysv:amd64 (228-4+b1, 228-6),
        lib32gomp1:amd64 (5.3.1-7, 5.3.1-8),
        libamd2.4.1:amd64 (4.4.5-2, 4.4.6-1),
        libnl-3-200:amd64 (3.2.26-1, 3.2.27-1),
        gcc-5:amd64 (5.3.1-7, 5.3.1-8),
        libbasicusageenvironment1:amd64 (2016.01.20-dmo1, 2016.01.29-dmo1),
        libavcodec56:amd64 (2.8.5-dmo2, 2.8.6-dmo2),
        libavcodec56:i386 (2.8.5-dmo2, 2.8.6-dmo2),
        tesseract-ocr:amd64 (3.04.00-5+b1, 3.04.00-5+b2),
        libprotobuf-c1:amd64 (1.1.1-1, 1.2.1-1),
        libburn4:amd64 (1.4.2-1, 1.4.2.pl01-1),
        libsdl2-image-2.0-0:amd64 (2.0.0+dfsg-3+b4, 2.0.1+dfsg-2),
        libsdl2-image-2.0-0:i386 (2.0.0+dfsg-3+b4, 2.0.1+dfsg-2),
        python-nose:amd64 (1.3.6-1, 1.3.7-1),
        vlc:amd64 (2.2.1-dmo14, 2.2.2-dmo1),
        libpam-systemd:amd64 (228-4+b1, 228-6),
        libgail-3-0:amd64 (3.18.6-1, 3.18.7-1),
        libavutil54:amd64 (2.8.5-dmo2, 2.8.6-dmo2),
        libavutil54:i386 (2.8.5-dmo2, 2.8.6-dmo2),
        vlc-data:amd64 (2.2.1-dmo14, 2.2.2-dmo1),
        libtheora0:amd64 (1.1.1+dfsg.1-7.1, 1.1.1+dfsg.1-8),
        libtheora0:i386 (1.1.1+dfsg.1-7.1, 1.1.1+dfsg.1-8),
        libopencv-calib3d2.4v5:amd64 (2.4.9.1+dfsg-1.2, 2.4.9.1+dfsg-1.3),
        packagekit:amd64 (1.0.11-1, 1.0.11-2),
        liblsan0:amd64 (5.3.1-7, 5.3.1-8),
        systemd:amd64 (228-4+b1, 228-6),
        libgomp1:amd64 (5.3.1-7, 5.3.1-8),
        libgomp1:i386 (5.3.1-7, 5.3.1-8),
        libavdevice56:amd64 (2.8.5-dmo2, 2.8.6-dmo2),
        xca:amd64 (1.0.0-2.1, 1.3.2-1),
        libopencv-legacy2.4v5:amd64 (2.4.9.1+dfsg-1.2, 2.4.9.1+dfsg-1.3),
        lib32quadmath0:amd64 (5.3.1-7, 5.3.1-8),
        gimp-gmic:amd64 (1.6.8-3, 1.6.8-3+b1),
        wine32:i386 (1.8-6, 1.8.1-1),
        libthai0:amd64 (0.1.24-1, 0.1.24-2),
        libthai0:i386 (0.1.24-1, 0.1.24-2),
        wine64:amd64 (1.8-6, 1.8.1-1),
        libhogweed4:amd64 (3.1.1-4, 3.2-1),
        libhogweed4:i386 (3.1.1-4, 3.2-1),
        libwnck-3-0:amd64 (3.14.0-2, 3.14.1-1),
        libubsan0-dbg:amd64 (5.3.1-7, 5.3.1-8),
        apt-utils:amd64 (1.2.1, 1.2.3),
        libswscale3:amd64 (2.8.5-dmo2, 2.8.6-dmo2),
        smartmontools:amd64 (6.4+svn4109-1, 6.4+svn4214-1),
        libmagickcore-6.q16-2:amd64 (6.8.9.9-7, 6.8.9.9-7+b1),
        manpages-dev:amd64 (4.04-0.1, 4.04-1),
        libx32ubsan0:amd64 (5.3.1-7, 5.3.1-8),
        keyboard-configuration:amd64 (1.134, 1.136),
        gnome-shell-extensions:amd64 (3.18.3-1, 3.18.3-2),
        libasound2:amd64 (1.0.29-1, 1.1.0-1),
        libasound2:i386 (1.0.29-1, 1.1.0-1),
        libasound2-dev:i386 (1.0.29-1, 1.1.0-1),
        libasound2-plugins:amd64 (1.0.29-dmo1, 1.1.0-dmo1),
        libasound2-plugins:i386 (1.0.29-dmo1, 1.1.0-dmo1),
        libx32stdc++-5-dev:amd64 (5.3.1-7, 5.3.1-8),
        fonts-wine:amd64 (1.8-6, 1.8.1-1),
        nodejs-dev:amd64 (4.2.6~dfsg-1, 4.3.0~dfsg-2),
        libnettle6:amd64 (3.1.1-4, 3.2-1),
        libnettle6:i386 (3.1.1-4, 3.2-1),
        libopencv-core2.4v5:amd64 (2.4.9.1+dfsg-1.2, 2.4.9.1+dfsg-1.3),
        busybox:amd64 (1.22.0-17, 1.22.0-18),
        findutils:amd64 (4.6.0-2, 4.6.0+git+20160126-2),
        libvte-2.91-common:amd64 (0.42.1-2, 0.42.3-1),
        gir1.2-packagekitglib-1.0:amd64 (1.0.11-1, 1.0.11-2),
        liblsan0-dbg:amd64 (5.3.1-7, 5.3.1-8),
        libgnutls30:amd64 (3.4.8-2, 3.4.9-2),
        libgnutls30:i386 (3.4.8-2, 3.4.9-2),
        libsoftware-license-perl:amd64 (0.103011-1, 0.103011-2),
        libwnck-3-common:amd64 (3.14.0-2, 3.14.1-1),
        debtags:amd64 (2.0.1, 2.0.2),
        perl:amd64 (5.22.1-4, 5.22.1-7),
        liblivemedia50:amd64 (2016.01.20-dmo1, 2016.01.29-dmo1),
        libmagick++-6.q16-5v5:amd64 (6.8.9.9-7, 6.8.9.9-7+b1),
        libbs2b0:amd64 (3.1.0+dfsg-2.1, 3.1.0+dfsg-2.2),
        nautilus-data:amd64 (3.18.4-1, 3.18.5-1),
        libopencv-ml2.4v5:amd64 (2.4.9.1+dfsg-1.2, 2.4.9.1+dfsg-1.3),
        apt-transport-https:amd64 (1.2.1, 1.2.3),
        libappstream3:amd64 (0.9.0-3, 0.9.1-1),
        libitm1-dbg:amd64 (5.3.1-7, 5.3.1-8),
        gparted:amd64 (0.19.0-3+b2, 0.25.0-1),
        libnetpbm10:amd64 (10.0-15.2, 10.0-15.3),
        libatomic1:amd64 (5.3.1-7, 5.3.1-8),
        linux-image-4.3.0-1-amd64:amd64 (4.3.3-7, 4.3.5-1),
        libcc1-0:amd64 (5.3.1-7, 5.3.1-8),
        libx32gcc-5-dev:amd64 (5.3.1-7, 5.3.1-8),
        wine:amd64 (1.8-6, 1.8.1-1),
        libx32gomp1:amd64 (5.3.1-7, 5.3.1-8),
        kodi-bin:amd64 (15.2-dmo7, 15.2-dmo8),
        linux-headers-4.3.0-1-common:amd64 (4.3.3-7, 4.3.5-1),
        libopencv-features2d2.4v5:amd64 (2.4.9.1+dfsg-1.2, 2.4.9.1+dfsg-1.3),
        kodi-data:amd64 (15.2-dmo7, 15.2-dmo8),
        linux-compiler-gcc-5-x86:amd64 (4.3.3-7, 4.3.5-1),
        pinentry-gnome3:amd64 (0.9.7-1, 0.9.7-3),
        libtesseract3:amd64 (3.04.00-5+b1, 3.04.00-5+b2),
        libstdc++6:amd64 (5.3.1-7, 5.3.1-8),
        libstdc++6:i386 (5.3.1-7, 5.3.1-8),
        lib32atomic1:amd64 (5.3.1-7, 5.3.1-8),
        libsdl2-ttf-2.0-0:amd64 (2.0.12+dfsg1-2, 2.0.14+dfsg1-1),
        libjpeg62-turbo:amd64 (1.4.1-2, 1.4.2-2),
        libjpeg62-turbo:i386 (1.4.1-2, 1.4.2-2),
        libx32atomic1:amd64 (5.3.1-7, 5.3.1-8),
        libfop-java:amd64 (2.0+dfsg-5, 2.1-1),
        libavresample2:amd64 (2.8.5-dmo2, 2.8.6-dmo2),
        libavresample2:i386 (2.8.5-dmo2, 2.8.6-dmo2),
        libusageenvironment3:amd64 (2016.01.20-dmo1, 2016.01.29-dmo1),
        libdebconfclient0:amd64 (0.201, 0.204),
        libjcommander-java-doc:amd64 (1.35-1, 1.48-1),
        libtool:amd64 (2.4.2-1.11, 2.4.6-0.1),
        libtokyocabinet9:amd64 (1.4.48-3, 1.4.48-7),
        rhythmbox:amd64 (3.2.1-1+b1, 3.3-1),
        diffstat:amd64 (1.60-1, 1.61-1),
        libwine:amd64 (1.8-6, 1.8.1-1),
        libwine:i386 (1.8-6, 1.8.1-1),
        libmodule-build-perl:amd64 (0.421400-3, 0.421600-1),
        rhythmbox-plugin-cdrecorder:amd64 (3.2.1-1+b1, 3.3-1),
        libdatrie1:amd64 (0.2.10-1, 0.2.10-2),
        libdatrie1:i386 (0.2.10-1, 0.2.10-2),
        libneon27:amd64 (0.30.1-2+b2, 0.30.1-3),
        librhythmbox-core9:amd64 (3.2.1-1+b1, 3.3-1),
        libx32stdc++6:amd64 (5.3.1-7, 5.3.1-8),
        libcholmod3.0.6:amd64 (4.4.5-2, 4.4.6-1)
    End-Date: 2016-02-15  11:24:41
```

**Comment by gdrewb-valve** [comment] 2016-02-15 17:56
Can you try disabling the Steam overlay to see if it's the cause?

**Comment by DerBunman** [comment] 2016-02-15 18:20
I tried that and it didn't change the behavior. 

Also I am sure that it is not a Steam update, but one of the packages I upgraded which causes an incompatibility with the steam runtime, because I luckily made a system backup before doing the "apt upgrade" and after reverting to the state before the upgrade the 64 bit Steam games run fine again.

**Comment by eriktorbjorn** [comment] 2016-02-17 21:08
Nice detective work! I don't have either of these games myself, but a number of other games stopped working for me recently. It turns out that I can get at least *some* (unfortunately not all) of them to work again if I downgrade the ALSA libraries (libasound2 etc.) to 1.0.29-1.

I've seen other reports of problems with ALSA 1.1.0 and Steam, but they were all about missing sound, not game crashes.

**Comment by AConsolePeasant** [comment] 2016-02-18 13:28
My games wouldn't load normally, running steam with

> LD_PRELOAD='/usr/$LIB/libasound.so.2 '${LD_PRELOAD} steam

 Fixes plague inc and torchlight 2 for me. Not sure why, just found it on the arch wiki.

**Comment by emikulic** [comment] 2016-02-27 08:02
Can confirm: this makes Cities:Skylines not crash on start on Debian testing (stretch):

`LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libasound.so.2 steam`

**Comment by kisak-valve** [comment] 2019-03-29 13:12
Hello, since this issue was last commented on Steam's handling of the Steam runtime has changed to prefer host libraries by default. Is anyone still experiencing this issue on an up to date system?

**Comment by emikulic** [comment] 2019-04-02 13:07
I can confirm that Cities:Skylines starts up fine without the `LD_PRELOAD` now. Thanks!

**Comment by kisak-valve** [comment] 2019-05-03 13:16
Thanks for retesting @emikulic, closing.

**Closed by kisak-valve** 2019-05-03 13:16 UTC
Labels: Need Retest, reviewed
