### ISSUE TITLE
fps cap setting

### ISSUE THREAD

**Issue by biji** [ValveSoftware/steam-for-linux#6515] opened 2019-09-19 13:18 UTC
#### Your system information

* Steam client version (build number or date): 
Latest beta

* Distribution (e.g. Ubuntu): 
Fedora 30

* Opted into Steam client beta?: [Yes/No]
Yes

* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Im using low end laptop with discrete gpu. Everything work great except i don't want to fry my laptop because temperature is above 90c. I hope there is FPS cap setting per game in Steam client, which implement similiar to libstrangle

Tq

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by dubigrasu** [comment] 2019-09-19 13:28
https://github.com/ValveSoftware/steam-for-linux/issues/6117

**Comment by kisak-valve** [comment] 2019-09-19 13:35
Hello @biji, as @dubigrasu pointed out, this is functionally a duplicate of #6117. Closing in favor of the existing feature request.

**Closed by kisak-valve** 2019-09-19 13:35 UTC
