### ISSUE TITLE
Long black screen, even after providing -novid flag in launch options

### ISSUE THREAD

**Issue by slookm** [ValveSoftware/steam-for-linux#8408] opened 2022-02-13 09:45 UTC
#### Your system information

* Steam client version (build number or date): 1644454953
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Launch the game using Steam client. Black screen comes and doesn't goes.

#### Steps for reproducing this issue:

1.  Launch the game using Steam client. Black screen comes and doesn't goes.

**Comment by kisak-valve** [comment] 2022-02-13 13:45
Hello @slookm, this isn't coherent feedback for the Steam for Linux client. I'm going to guess this issue report is a duplicate of https://github.com/ValveSoftware/csgo-osx-linux/issues/608.

**Closed by kisak-valve** 2022-02-13 13:45 UTC
