### ISSUE TITLE
Opening Beta Steam Overlay Crashes Hunt Showdown

### ISSUE THREAD

**Issue by LukeDearden** [ValveSoftware/steam-for-linux#9426] opened 2023-04-30 06:11 UTC
#### Your system information

* Steam client version (build number or date): 1682723851
* Distribution (e.g. Ubuntu): Fedora 38 GNOME 44 (same in x11 and Wayland)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

![image](https://user-images.githubusercontent.com/6813601/235338477-2ffff2f0-bc6c-4a09-b941-a979470532c7.png)

#### Please describe your issue in as much detail as possible:

Opening the overlay even when in the main menu crashes Hunt Showdown. The same action in the stable version of Steam works fine.

```
Wine C++ Runtime Library
(X
Assertion failed!
^ *
Program: Z:\home\luke\STEAM\SteamLibrary
\steamapps\common\Hunt Showdown bin
(win_x64\HuntGame.exe
File: ../src-wine/dls/winevulkan/loader_thunks.c
Line: 5275
Expression: "Istatus"
Press OK to exit the program, or Cancel to start
the Wine debugger.
```

![Screenshot from 2023-04-28 11-31-23](https://user-images.githubusercontent.com/6813601/235338530-70d311f2-0e67-4525-831e-96abbc621271.png)

#### Steps for reproducing this issue:

1.  Launch Hunt Showdown
2.  Open the Overlay

Also I tried to provide the runtime output report from Steam/Help/System info. But that now crashes my gnome session

**Comment by kisak-valve** [comment] 2023-04-30 12:17
Hello @LukeDearden, in general, we're tracking issues with games run with Proton in the Proton issue tracker. https://github.com/ValveSoftware/Proton/issues/3898 is the right place to ponder what's happening with this game.

Closing as a duplicate of https://github.com/ValveSoftware/Proton/issues/3898#issuecomment-1528944491.

**Closed by kisak-valve** 2023-04-30 12:17 UTC
