### ISSUE TITLE
[TF2 x64][Linux] TF2 "updates" every time the game starts

### ISSUE THREAD

**Issue by echaskaris** [ValveSoftware/steam-for-linux#10918] opened 2024-05-23 18:45 UTC
Meaning an update appears on steam and is applied when TF2 closes. While steam is open it shows disk write error.
Maybe some file verification?
Updated as of 23-5-2024 (no update recently)

Ubuntu 22.04 on X11

**Comment by kisak-valve** [comment] 2024-05-23 18:50
Possible duplicate of #10906.

**Comment by kisak-valve** [comment] 2024-05-23 20:02
Closing in favor of the older issue report.

**Closed by kisak-valve** 2024-05-23 20:02 UTC
Labels: Steam client, Distro Family: Ubuntu
