### ISSUE TITLE
steam view becomes corrupted when resizing in a tiling window manager

### ISSUE THREAD

**Issue by dindybutts** [ValveSoftware/steam-for-linux#6593] opened 2019-10-17 16:40 UTC
#### Your system information

* Steam client version (build number or date):  Oct 5 2019, at 18:19:51
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When resizing the steam window with hardware acceleration on in a tiling window manager via opening the friend list (or any other window) the window becomes corrupted, see below for an example of this happening

![Peek 2019-10-17 17-37](https://user-images.githubusercontent.com/18424612/67029298-eecbaf00-f104-11e9-8ebe-871a6c1c21f8.gif)

#### Steps for reproducing this issue:

1. Launch steam in a tiling window manager
2. Enable hardware acceleration
3. Resize steam window

System Information
https://gist.github.com/dindybutts/8b1b9c793a4c59059c8e52f30241b825

**Comment by kisak-valve** [comment] 2019-10-17 18:28
Hello @dindybutts, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by dindybutts** [comment] 2019-10-17 19:55
sorry @kisak-valve, i must've missed that, i'll post it here and in the original post

https://gist.github.com/dindybutts/8b1b9c793a4c59059c8e52f30241b825

**Comment by XakepSDK** [comment] 2019-10-18 18:16
Same on arch linux, kde kwin, hw accel enabled

**Comment by arutemii** [comment] 2019-10-20 07:38
Same issue.  amdgpu driver. 

System info: https://gist.github.com/arutemii/0b7d9055fde85e3d2748ae6d6c1bd84c

**Comment by NoXPhasma** [comment] 2019-10-21 20:44
Same happens to me now with the latest beta (1571675610) when HW Acceleration is enabled, and also introduced a huge VRAM memory leak. I'm currently at 2861MiB usage for one steamwebhelper process.

https://gist.github.com/NoXPhasma/73ea701d945c09ed10dfdd2072d07985

**Comment by Bumbadawg** [comment] 2019-10-23 11:01
Same happens on Manjaro/Ubuntu with KDE Kwin HW accel, it's when the library window size gets below a certain width. Not even needing to tile to see this occur.

**Comment by dindybutts** [comment] 2019-10-24 00:56
Ah, It's good to see it's not just a tiling window manager problem, I doubt valve would fix a bug in steam just for the few who use TWMs

**Comment by Bumbadawg** [comment] 2019-10-24 16:14
But since it's not related to TWMs but actual window rendering, they will.

**Comment by mpnordland** [comment] 2019-10-25 05:18
Reproduced on Arch Linux with Awesome WM.
![2019-10-25-011358_1890x2075_scrot](https://user-images.githubusercontent.com/2294814/67544833-0090f180-f6c5-11e9-9abf-3c609beb755c.png)
[System info](https://gist.github.com/mpnordland/6625146fb6003301b25fd84e799fc0f1)

**Comment by NoXPhasma** [comment] 2019-10-26 05:57
Latest beta (1572045180) update fixed the corruption for me and by that also the VRAM memory leak.

**Comment by arutemii** [comment] 2019-10-26 07:20
Latest beta update fixed the corruption, but the VRAM memory leak when resizing window is still present.

**Comment by Leopard1907** [comment] 2019-10-31 09:22
VRAM memory leak is also happening on my end too. Latest beta client.

**Comment by kisak-valve** [comment] 2019-11-24 14:59
Closing because the issue reported in the opening post is fixed and the vram leak is now being tracked at #6715.

**Closed by kisak-valve** 2019-11-24 14:59 UTC
Labels: Web Component
