### ISSUE TITLE
There are over 2,000 open issues.

### ISSUE THREAD

**Issue by piousminion** [ValveSoftware/steam-for-linux#4919] opened 2017-04-02 04:20 UTC
#### Your system information

* Steam client version (build number or date): **Irrelevant**
* Distribution (e.g. Ubuntu): **Irrelevant**
* Opted into Steam client beta?: [Yes/No] **No**
* Have you checked for system updates?: [Yes/No] **Yes**

#### Please describe your issue in as much detail as possible:
I visited the Steam github expecting some issues. What I found instead was **over 2 fucking thousand open issues**. There are over 2,000 open issues.  **Get your shit together Valve.**

#### Steps for reproducing this issue:

1. Visit the steam-for-linux github page.
2. Behold the cluster fuck of issues before you.
3. ???
4. Profit.

**Comment by psy-q** [comment] 2017-04-02 06:59
"Steam" is a non-sentient (I hope) piece of software, so addressing it in a sentence and telling it to get its shit together probably won't have the effect you hope for. You could address Valve, for example, that's slightly better because it's at least an organization and might be able to do something about these issues that bother you.

But then that would be pointless as well, because Valve is already being addressed in the 2,000 issues that made you open yet another issue for them to work on. Maybe a more helpful approach would be to go into each one of those 2,000 issues that might affect you, try to reproduce it and help solve it.

Not everyone is seeing all of these 2,000 issues simultaneously. Me, I'm seeing 0 (zero) of them. Some issues affect Steam, some only the Steam controller, some only appear with an unlikely combination of Turkish language when located in Thailand and using a pair of Chinese Dual Shock 3 rip-offs with broken firmware. Okay, I made that up.

It's a big and ambitious project, it's still early days for Steam on Linux compared to the 13 years it's been on Windows. Issues are to be expected. Me, I'm glad someoe's working on solving them and that there's an official, public issue tracker. This is more than most proprietary software makers give you.

**Comment by piousminion** [comment] 2017-04-02 07:08
@psy-q ""Steam" is a non-sentient"  I'm now addressing "Valve". Good point.
"But then that would be pointless as well" I may not be pointless if international attention is brought to it.
"Not everyone is seeing all of these 2,000 issues simultaneously." I have no idea what you're referring to.
"It's a big and ambitious project and it's still early days for Steam on Linux". No it isn't, on either account.
"I'm glad someoe's working on solving them" It most certainly does not look that way.

This "client" is a simple GUI that, given some info, the community would GLADLY do the work for them.  It is an absolute joke that a company like Valve can't get something so simple working. Game-specific issues I can see, but this is just a gui launcher. That's all.

**Comment by psy-q** [comment] 2017-04-02 07:26
The probability of all issues affecting you at the same time is very low, that's what I meant. Someone who knows math could probably even calculate it to some degree. I have personally seen maybe two or three of these issues (since beta), so it is possible to not be affected by any of them. 

If you look at some of the issues at random, you'll see that a good part of them only appear with a certain combination of distro, hardware and desktop environment configuration.

  * [This one](https://github.com/ValveSoftware/steam-for-linux/issues/4661) is caused by a missing package and affects only people who didn't install it
  * [This one](https://github.com/ValveSoftware/steam-for-linux/issues/4883) suggests missing libraries on the user's side and affects only people who forgot to install Nvidia's 32-bit libraries
  * [This one](https://github.com/ValveSoftware/steam-for-linux/issues/4575) is about tray icon appearance and affects only people with light desktop themes

So an "average" Ubuntu 16.04 user with a dark theme will not encounter any of them. They are still there and need to be fixed in some way, I do grant you that. But just having 2,000 issues in the issue tracker doesn't mean everyone experiences all of them.

But if you believe that Steam is just a GUI launcher, you're forgetting:

  * Steam Controller configuration
  * Big Picture mode
  * Stable Steam Runtime for developers to work against
  * DRM and cryptography
  * The content delivery network support (including ability to choose which region to download from)
  * Sync and Steam Cloud (if we'd have a fully FOSS Steam like you suggest, we could steal this from Mirall like ownCloud did)
  * Pre-loading of games
  * Backup and restore
  * Streaming, including hardware encoding
  * Family sharing
  * Music player
  * Video player
  * Screenshot manager with Steam Cloud integration
  * Trading cards and community marketplace
  * Survey tool
  * Updater

I'm sure I forgot a few things.

**Comment by kisak-valve** [comment] 2017-04-02 12:00
Hello @piousminion, I will be evaluating the open issues in this issue tracker. A fair bit of the open issues are individual users in need of help getting things setup. There also are some issues with several duplicates that artificially inflate the open issue count. Additionally, this issue tracker has historically been a dumping ground for anything remotely related to steam.

If an actionable fix can be identified, that improves the chance that a Valve dev can take action on any given issue. There simply are too many combinations of hardware and flavors of linux to cover with the manpower available and support from the various communities is appreciated.

For the issues that you personally are experiencing, you can add a thumbs up emoticon on the top post of that issue as a form of voting.

Note: I am a moderator for the Valve issue trackers, and not a dev.

Closing as this isn't a specific, actionable issue.

**Closed by kisak-valve** 2017-04-02 12:00 UTC

**Comment by piousminion** [comment] 2017-04-02 14:38
@kisak-valve "I will be evaluating the open issues in this issue tracker." You mean starting from right now?  ..because I haven't seen anything thus far.

"There simply are too many combinations of hardware and flavors of linux to cover with the manpower available"  Wrong. Try again.  It's a simple GUI launcher of which no updates have been released in quite some time.  If you code the application correctly, different distributions would be of no concern. You think Firefox,etc,etc has this much trouble? lol

"support from the various communities is appreciated"  You and I both know Valve would never allow that.

"For the issues that you personally are experiencing, you can add a thumbs up emoticon on the top post of that issue as a form of voting."  I tried that.  2.5 years later and I'm still waiting for a fix to something even a mentally challenged, one legged, Ugandan child could fix if only he had the source code.

**Comment by carbohydratesn** [comment] 2017-04-02 17:25
"Note: I am a moderator for the Valve issue trackers, and not a dev."

And there's the problem.

Valve developers don't read this stuff, ever.  Steam Support directs people to the 'Steam Community Forum' for games - basically their trash bin.

And then they direct people to this issues tracker.  Which is just *another* trash bin they keep around.

Valve's Linux support in general is abysmal, I hope they do something about this soon.

**Comment by Plagman** [comment] 2017-04-02 21:09
This tracker is monitored daily to identify important issues and evaluate the experience of the userbase at large. Just the count of issues and enhancement requests open here is not a particularly useful metric for that. We are always working with a finite set of resources (everyone, not just Linux developers), and have to constantly prioritize between bringing new features and functionality to Linux (SteamVR, internal efforts, etc), working with publishers on porting games, improving Mesa drivers, Linux tools, etc. As such, we're not always making visible progress on client issues, and there's no expectation that we'll get to them all. That being said, having the data captured here is still very useful and kisak is correct that posting detailed information and reproduction steps makes the task of addressing an issue much easier in the event that it needs to get fixed.

Please keep future reports on-topic, thanks!
