### ISSUE TITLE
[temp solved] One or more games go missing from library

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#7014] opened 2020-04-06 21:52 UTC
#### Your system information
https://gist.github.com/byte1024

* Steam client version (build number or date): Apr 4 2020
* Distribution (e.g. Ubuntu): Fedora 31
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Open Steam, one or more games are missing from game library.

Going to the game in the store shows the game(s) for purchase (not owned)

Going to discussions shows the game(s) are still owned.

Small mode also shows the game missing so it would seem to be not a UX problem? Or maybe they share the same views, code for it.

Not hidden or removed or otherwise.

Happened to me just now and only one time in many many years of using Steam.

#### Steps for reproducing this issue:

1. Start Steam
2. Look at game library.
3. Can't find one or more game(s) that should be owned and in the library

**Comment by nolddor** [comment] 2020-05-02 23:47
I suffered this issue few hours ago until my relative share their library with me using Family sharing feature.

Restarted the steam client solved the problem

**Comment by byte1024** [comment] 2020-05-25 01:56
Interesting, I have family sharing in use as well but its with my older accounts that are not being used.

In any case, just had it happen a second time now. Seems to be a new bug that shows up here and there. I imagine more people have it happen but since its fixed by a restart of Steam then many may not notice it at least until they notice it.

**Comment by byte1024** [comment] 2020-06-25 19:39
Happens after making a store purchase. Valve could do test purchases possibly to reproduce it.

I don't think it was missing anything before the store purchase but could have been and I wouldn't have known. Didn't think about it until a restart of steam fixed it.

**Comment by kisak-valve** [comment] 2022-08-26 20:07
Hello @nolddor, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment] 2022-09-30 18:34
Closing because the reporting user has turned into a ghost.

**Closed by kisak-valve** 2022-09-30 18:34 UTC
Labels: Steam client, Need Retest
