### ISSUE TITLE
Cannot save screenshots from Library browser

### ISSUE THREAD

**Issue by sebleblanc** [ValveSoftware/steam-for-linux#6698] opened 2019-11-17 15:45 UTC
#### Your system information

* Steam client version (build number or date): Nov 14 2019, at 18:30:46
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

I was browsing images for a game, under the Library tab, and attempted to download an image. The context menu says "Save screenshot as..." (even though it is not technically a screenshot).

Then a window appears but that window remains blank (glitched) until you actually interact with, that is, move your mouse over.

This dialog then opens in the Steam folder (~/.steam/debian-installation) (issue #6613) and shows a slew of hidden files. It lets you type a file name, but clicking OK does nothing.

If you select an existing file, it will overwrite that file with the screenshot you were downloading.

Cancelling the file chooser sends you back to the Library screen, but controls are unresponsive. It is impossible to scroll, click on [Close] or the [X] in the top right, or attempt to download the image again, until you move to another tab or hit Back in the browser.

#### What I expected

* The file manager should open in ~/Documents, failing that, in ~;
* The file chooser should let me type any file name and save the screenshot under that name;
* The file chooser should warn me about overwriting files before doing so;
* The browser should remain responsive after cancelling the save.

**Comment by arrowgent** [comment] 2019-11-28 11:46
the work around is to click "manage my screenshots" under the screenshots

this brings up the OLD menu which works fine.

**Comment by DanMan** [comment] 2020-04-04 22:39
It seems like it's not a "save file" but an "open" dialog, which makes no sense, of course.

**Comment by SirBubbles** [comment] 2022-02-01 06:30
Anyone addressing this issue? Still very much an issue for me on 1st of Feb 2022 under latest Steam Beta, up to date Manjaro Gnome, radeon 6700xt GPU, Ryzen 5 5600x.

**Comment by MkThUnderwd** [comment] 2022-10-26 01:55
I'm having the same issue.

To reproduce on Steam for Linux:
1) Click on a game in Library tab.
2) scroll down to Community Content
3) click on an image so it pops out into it's own window.
4) right click on the image in window.
5) choose the only option: "Save Screenshot as ..."
A file selection window should pop up, but instead of having an OK button it will have an OPEN button.

**Comment by SirBubbles** [comment] 2022-12-03 13:00
> I'm having the same issue.
> 
> To reproduce on Steam for Linux:
> 
>     1. Click on a game in Library tab.
> 
>     2. scroll down to Community Content
> 
>     3. click on an image so it pops out into it's own window.
> 
>     4. right click on the image in window.
> 
>     5. choose the only option: "Save Screenshot as ..."
>        A file selection window should pop up, but instead of having an OK button it will have an OPEN button.
> 
> 
> EDIT: the image can be saved, but the file must be created outside of Steam: 6) file creation from terminal: $ touch ~/Desktop/NameOfImage.jpg 7) select file from step-6 in the "Save Screenshot as ..." dialog with OPEN.

Just "bumping" this so that this issue stays visible. As weird as it seems, the "solution" described in this post does allow one to overwrite an existing image and thus save it, but this isn't acceptable. A simple task like this shouldn't be outright impossible unless you resort to extraordinary measures, and I can't see why it would be a big deal to get this sorted out.
I do respect what the Valve team does, but simple issues like this _have_ to be addressed.

**Comment by Fooshts** [comment] 2023-03-12 02:11
Still a problem 3/11/23

**Comment by BalderdashPoppycock** [comment] 2023-03-20 06:33
Can confirm that this is still a problem

**Comment by shytzedaka** [comment] 2023-05-08 11:09
Tested this with the Latest steam beta client: 
![image](https://user-images.githubusercontent.com/20986867/236807902-1b1e38a7-6faa-45ca-ab7e-cc55dffbee97.png)
It appears that the 'save as screenshot' button doesn't exist anymore. instead we get this:

If you right click a screenshot/artwork from the preview of it (Steam Community hub> Any artwork)
![image](https://user-images.githubusercontent.com/20986867/236808493-01ebb013-40f3-42bf-8ff1-f8b84c766765.png)
if you open up any artwork/screenshot beyond the preview you still get the same options.

Artworks have a 'Download' Button:
![image](https://user-images.githubusercontent.com/20986867/236808821-ad9626c6-4259-47c9-8cb4-37146faeb5b3.png)

When Pressing Download it leads you to a browser page with a full sized image of the artwork. (kinda like how you would open a png file in a web browser) 

Then your options are these: 
![image](https://user-images.githubusercontent.com/20986867/236809029-369bbc49-15a1-46aa-8bbc-d119c4eb0ad5.png)

**Comment by Terandox-The-Pineapple** [comment] 2023-11-15 06:39
Same problem on my end... how is this still not fixed???
And i thought the devs of drupal would be lazy...

**Comment by shytzedaka** [comment] 2023-11-15 07:13
Actually its much worse now:
right clicking a preview of an artwork looks like this at the moment:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/20986867/76d4001d-c0c8-41c2-b026-bd3a393d1473)

after clicking the image, steam for some reason opens up a "Steam web helper"
![image](https://github.com/ValveSoftware/steam-for-linux/assets/20986867/8f9f58d4-5a0e-4989-b2b8-79b73283d859)
You cannot interact at all with this "web helper" which opens up as a separate window, there are no context menu options.
**Note: this web helper program often crashes steam when trying to interact with it**



if you click the URL above the post it also opens up a separate window(Web Helper) instead of loading the page in steam.
![image](https://github.com/ValveSoftware/steam-for-linux/assets/20986867/11c87585-87f3-4c7d-b10d-92eb993a3632)
Once again you cannot right click anything (No context menu shows up)
Pressing the 'Download' Button in the artwork page loads up the picture but you cannot interact with it or save it.






The only button that **does** work correctly is:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/20986867/8e768fc5-1356-4b79-ac2e-345f904c7f1f)
which then loads up the artwork page in Steam and not in a separate window.
*When the artwork page is loaded in steam. you can right click(Context menu) in the artwork page (Unlike the web helper):
![image](https://github.com/ValveSoftware/steam-for-linux/assets/20986867/49215604-6182-41dd-8d96-d7ecfbe65dd7)

After pressing 'Download' in the artwork page:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/20986867/08910212-9803-4fdd-b892-bab1bc373ad4)
Still no option to save the artwork... 


I'll say that steam has crashed around 6 times when trying to take the screenshots of the current behavior
Steam version:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/20986867/5a0c9f21-691d-40b2-8919-a122973863e0)

I used Ubuntu 23.10 with the X11 windowing system. 
@kisak-valve  is there any additional information you might need?

**Comment by fabiscafe** [comment] 2023-12-19 08:39
Steam Version: 1702079146


Since #9057 is marked as a dup. If you try to save this years SteamYearInReview picture, it will spawn the file selector:
![grafik](https://github.com/ValveSoftware/steam-for-linux/assets/18744080/cae42c49-8d1a-4664-8348-078462e08424)

You cant actually create/place a new file with this. But since we still do not have a "share to fediverse" button i need to download it.

**Comment by Solitary** [comment] 2023-12-19 09:32
Indeed, just noticed this in the Steam Year In Review page where you can save screenshot of the statistics, but the dialog is wrongly a **file selector** instead of **file saving** dialog, which means the dialog can't specify the name of saved file and can't create new directories, you can only browse and select PNG files, and only way to save the screenshot is to select an existing PNG file, which then will be overwritten by the one we want to save.

**Comment by MkThUnderwd** [comment] 2024-01-11 07:31
> Indeed, just noticed this in the Steam Year In Review page where you can save screenshot of the statistics, but the dialog is wrongly a **file selector** instead of **file saving** dialog, which means the dialog can't specify the name of saved file and can't create new directories, you can only browse and select PNG files, and only way to save the screenshot is to select an existing PNG file, which then will be overwritten by the one we want to save.

A temporary fix may be to create an empty file with the right extension (jpg?) and find it in the selector dialog. Open that file you made and it could no longer be empty. It has worked for me before.

**Comment by ikaikahub** [comment] 2024-02-26 23:35
Silly issue

**Comment by matthewelmer** [comment] 2024-03-04 07:39
LOL steam devs out here making the simplest of issues stick around since 2019 (5 years ago!!!)

If I have spare time later I might put in a PR, there's no way this isn't more than a 10 minute fix lmao

**Comment by matthewelmer** [comment] 2024-03-04 07:44
ahahaha I can't even help out because they've hidden their javascript spaghetti code somewhere else!

I actually don't blame them for being ashamed of this absolute steaming pile lol.

**Comment by Managor** [comment] 2024-03-20 08:25
Reallly wish this could get fixed. A simple issue.

**Comment by Managor** [comment] 2024-07-31 13:25
This has been fixed, probably during the new Recordings and Screenshots overhaul.

**Comment by 414n** [comment] 2024-08-03 11:46
Just tested on Steam beta `1722380543` and I can finally save a screenshot from a game "Community content" section with no issues.

**Comment by Managor** [comment] 2024-08-09 03:06
I found a small issue. When selecting custom artwork for a game, the filter type gets set to `JPEG Image (*.jpg)` instead of `PNG Image (*.png)` that is the standard for steam custom artwork or simply `All files (*)`. I might make a separate report later.

**Comment by kisak-valve** [comment] 2024-09-28 14:40
Closing as fixed in the [2024-09-11](https://store.steampowered.com/news/app/593110/view/4599952112537386540) Steam client update.

**Closed by kisak-valve** 2024-09-28 14:40 UTC
Labels: Steam client, Need Retest

**Comment by ikaikahub** [comment] 2024-10-15 23:48
beautiful
