### ISSUE TITLE
CSGO not working

### ISSUE THREAD

**Issue by alexschwalb** [ValveSoftware/steam-for-linux#4961] opened 2017-05-10 18:53 UTC
#### Your system information
OS: Linux Mint 18.1 Cinnamon 64-bit
Processor: Intel Core i7 920 @2.6 GHz
Graphics Card: EVGA GTX 1060 6gb
Memory: 6gb ddr3
Storage: 5.5TB

* Steam client version (build number or date): Apr 25, 2017
* Distribution (e.g. Ubuntu): Linux Mint Cinnamon
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible: I've had csgo for quite a while, and before this, it worked fine, but a couple days ago, it said it needed an update. I downloaded it, it gave an error, I try downloading it again and it gave the same error, I try deleting it and all the files stored for it, try downloading it again, it gives the same error, the error is involving a corrupt update file. It says the corrupt file is located at /Steam/steamapps/downloading/730/bin/convertdmx.lua. I contacted steam support for this and they told me to go here. Any questions, just ask.
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. download counter-strike global offensive
2. 
3.

**Comment by kisak-valve** [comment] 2017-05-10 19:47
Most likely a duplicate of #4800. @alexschwalb, what filesystem is CS:GO installed on?

**Comment by alexschwalb** [comment] 2017-05-10 20:27
its ntfs, so yep that looks like its most likely the case. I got a smaller drive thats not ntfs that I guess I can transfer it to

**Comment by kisak-valve** [comment] 2017-05-11 19:24
Closing in favor of #4800.

**Closed by kisak-valve** 2017-05-11 19:24 UTC
Labels: duplicate, Steam client
