### ISSUE TITLE
Ability to remove older versions of proton, which are forcefully used by steam

### ISSUE THREAD

**Issue by MartinX3** [ValveSoftware/steam-for-linux#6894] opened 2020-02-13 19:16 UTC
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
I would like to have a manual override to use a specific version of proton on every game, instead only on these not officially supported ones.
At the moment I can't uninstall Proton 3.7, 3.16, 4.2, & 4.11 because some officially proton supported Steam games forcefully want to use it.
I would like to test them with as example now Proton 5.0 instead.
At the moment the old versions are consuming ~7GB on my limited storage.

**Comment by kisak-valve** [comment] 2020-02-13 19:35
Hello @MartinX3, I've transferred this feature request to the steam-for-linux issue tracker because it's referring to Steam's management of Proton versions, not Proton itself.

I believe the current logic of per game override > whitelisted Proton version > global Proton override is correct and setting the whitelisted games to use another version of Proton should unblock that version of Proton from being removed.

**Comment by MartinX3** [comment] 2020-02-13 19:43
Aye, thank you very much
I sadly oversee this repo :D

**Comment by Matombo** [comment] 2020-02-14 11:56
As a workaround: You can deactivate steam play in the settings menu, uninstalled the unwanted proton version and reactivate steam play again. It will stay uninstalled until you use it again.

**Comment by kisak-valve** [comment] 2020-02-14 13:05
In case it wasn't clear, in the per game properties, you can check the box beside `Force the use of a specific Steam Play compatibility tool` and select the Proton version you want to use.

This will override the Proton version selected by the whitelist and Steam should allow you to uninstall the Proton version after no games are set to use that version.

**Comment by MartinX3** [comment] 2020-02-14 14:08
@Matombo 
Thank you for the workaround

@kisak-valve 
Ahhh sorry, I thought you mean the general settings.
I overread the "per game".
Sadly I have no clue what game exactly wants the old version.
The only result is an "unknown error cause".

**Comment by kisak-valve** [comment] 2020-02-14 14:16
You can find out if a game is using Proton, what version, and why by selecting the game in the library, and clicking the ⓘ symbol on the right side.

**Comment by arrowgent** [comment] 2020-02-17 08:44
yes you have to manually find the exact game which is using that version of proton, unselect that version of proton THEN you can remove that proton version.
or uninstall that game.
the other ways will only bring back that version of proton again later

**Comment by supertin** [comment] 2020-03-02 07:21
It would be super helpful if we had an additional tab in the properties for the Proton versions listed in the library that scanned for games currently set up to use that version - whether by whitelisting, manual setting per game, or as the global default. I mean something like how DLC is shown on it's own tab in each game's properties.

In the old Steam interface, you could just down-arrow through the library looking at the "will open with Proton x.y" note. The new pretty interface still has this, and in fact is easier to read... But the info panel doesn't stay open as you scroll through games... For smaller libraries, fixing the info section so it stays own would be a quick workaround. But would still be impractical for people with hundreds of games.

**Comment by TriMoon** [comment] 2020-03-02 08:35
@supertin :+1:  for the `this version is used by` listing functionality...

**Comment by lucifertdark** [comment] 2020-03-02 09:02
I'll add my support to supertin's suggestion, it would be very useful to have this.

**Comment by wantija** [comment] 2020-03-25 19:27
This is also a problem if you uninstall a game that was using a custom Proton version or can't remember a game that was using it. You don't know what version it was using so you have to do Properties > Force specific Steam Play tool for every game to see what was using the version you want to remove.

**Comment by 3vi1** [comment] 2020-04-21 16:22
I have > 500 games installed (1000+ in library).  I prefer not to uninstall them if I may ever play them again, but this has led to having five different versions of Proton installed, and it's only going to get worse as time progresses.  Finding all the individual games, and even changing them manually is very cumbersome.  My preference would be:

> When you uninstall a Proton version:
>   - Warning!  Games A, B,... Z are using this version.  [Cancel, or Override These Games To Use Version X?]
> 
> When you uninstall a Game:
>   - Attention!  This is your last game that depends upon Proton version X.xx.  Uninstall that Proton version too?  [No, Okay]
> 
> When you start an officially supported Game not using the default recommended Proton version:
>   - Attention!  This game is only officially supported with Proton Y.yy, you are using X.xx.

This would allow us to more easily roll with just a few specific versions of Proton that work for our collection, save a heck of a lot of space for our games, and help identify Proton regressions with officially supported games.

**Comment by Termuellinator** [comment] 2020-05-11 13:54
i would second 3vi1's proposal...came here to suggest the listing of games using it when uninstalling proton version, but love all 3 suggestions :D

**Comment by tuxayo** [comment] 2020-07-04 23:09
### workaround
- start steam by the command line.
- try to remove the proton version
- cryptic message "unknown error"
- in the terminal you can for example:

```
GameAction [AppID 1113280, ActionID 3] : UninstallApps waiting for user response to ConfirmUninstall "1113280"
GameAction [AppID 1113280, ActionID 3] : UninstallApps continues with user response "ConfirmUninstall"
GameAction [AppID 1113280, ActionID 3] : UninstallApps changed task to StartNextApp with ""
GameAction [AppID 1113280, ActionID 3] : UninstallApps changed task to InstallScript with ""
GameAction [AppID 1113280, ActionID 3] : UninstallApps changed task to RemoveFromOS with ""
GameAction [AppID 1113280, ActionID 3] : UninstallApps changed task to WaitRunning with ""
App ID 13240 depends on compatibility tool 1113280, cannot uninstall!GameAction [AppID 1113280, ActionID 3] : UninstallApps failed with AppError_17 with ""
```

a search on the web ("steam app 13240") tells me that it's Unreal Tournament: GOTY.

### suggestion
The error message on uninstall should display the name of the blocking app. And suggest to go in the properties of the app to force use of another compat tool.

**Comment by tuxayo** [comment] 2020-07-05 02:33
Another suggestion for whitelisted games for which one wants to use the most recent proton version: the per game tool forcing could have in the list "latest proton version"

That way, it would be possible to always use the latest proton version for every game without having trouble deleting the old ones.

**Comment by kisak-valve** [comment] 2020-10-16 12:55
Closing because the per-game Steam Play override has been implemented for a fair while.

**Closed by kisak-valve** 2020-10-16 12:55 UTC
Labels: Feature Request, Proton, Steam client

**Comment by Termuellinator** [comment] 2020-10-16 12:59
> Closing because the per-game Steam Play override has been implemented for a fair while.

i don't think that is really enough - the big issue is the non-descriptive error together with the new library not showing the proton-version used without opening the properties for every single game individually.
So i guess it's about getting proper information from the error-message preventing the de-installation of an older proton version now ^^

**Comment by kisak-valve** [comment] 2020-10-16 13:03
RIght, #7407 was recently opened which directly presents that follow up issue instead of it being hidden in the discussion here.
