### ISSUE TITLE
[CS 1.6] Favorites "Add Current Server" does not work

### ISSUE THREAD

**Issue by healthycs16** [ValveSoftware/steam-for-linux#2350] opened 2013-04-28 22:27 UTC
Join a server; open Favorites tab in Servers window; click Add Current Server and click Refresh... The new favorite server is not added to the list.

**Comment by kisak-valve** [comment] 2017-04-27 14:34
Closing as a duplicate of https://github.com/ValveSoftware/halflife/issues/508.

**Closed by kisak-valve** 2017-04-27 14:34 UTC
Labels: MOVED: Counter‐Strike, reviewed
