### ISSUE TITLE
[Arch Linux] Updating Games Causes Lockup

### ISSUE THREAD

**Issue by scoronado12** [ValveSoftware/steam-for-linux#7385] opened 2020-10-03 16:17 UTC
#### Your system information

* Steam client version (build number or date): 
![image](https://user-images.githubusercontent.com/9601750/94996317-f4b6dc00-0571-11eb-88cc-58d47e5b5a34.png)

* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?:No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I play World of Warships occasionally (a fine game that runs well under Proton). It updates a lot despite me not playing every single day. When it auto-updates behind the scenes, I have to deal with my Window Manager/Desktop Environment (KDE Plasma) and even X11 locking up due to the heavy IO that is occurring on my desktop and laptop.

What makes little to no sense is that I have a fairly beefy CPU and RAM, and it occurs even on SSD.

#### Steps for reproducing this issue:

1.  Install World of Warships
2.  Accept an update
3.  Watch that everything else gets real slow and occasionally locks up

**Comment by kisak-valve** [comment] 2020-10-03 16:34
Hello @scoronado12, this issue is already being tracked in various issue reports already. Closing as a duplicate of #4978 / #5404 / #3450 / #6776.

**Closed by kisak-valve** 2020-10-03 16:34 UTC

**Comment by scoronado12** [comment] 2020-10-04 20:59
Thanks @kisak-valve , glad that this is already in the tracker.
