### ISSUE TITLE
Non-Steam games do not receive controller input

### ISSUE THREAD

**Issue by Goggo66** [ValveSoftware/steam-for-linux#8886] opened 2022-11-03 20:04 UTC
#### Your system information

* Steam client version (build number or date): 1667429911
* Distribution (e.g. Ubuntu): Kubuntu 22.04
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Testing the new beta client with "-gamepadui" option. Any non-Steam game started via the new gamepad user interface does not receive any controller input. Keyboard/mouse input is recognized in some games, in others not.
When starting the same game using the "old" user interface, it can be played with a controller.

It does not matter whether the game needs proton, or is a Linux-native game.

#### Steps for reproducing this issue:

1. Start Steam with "-gamepadui" option
2. Connect a controller, e.g. the Steam controller.
3. Verify that the controller is detected; navigate through the UI using the controller
4. Start a non-Steam game, e.g. the Linux-native build of "A Short Hike", added to the library as a non-Steam game.
5. Observe that controller input is not recognized.
6. Shut down Steam.
7. Restart Steam without the "-gamepadui" option.
8. Start the same non-Steam game.
9. Observe that controller input is recognized.

**Comment by TTimo** [comment] 2022-11-07 19:12
Thank you this will be addressed in an upcoming update.

**Comment by Goggo66** [comment] 2022-11-08 19:06
The latest beta client (version 1667871444) has fixed the issue. Thanks.

**Closed** 2022-11-08 19:27 UTC
Labels: Need Retest, General controller / Steam Input

**Comment by slynobody** [comment] 2022-12-13 15:34
The issue is reappearing in the last two beta client-versions minimum.
Also there are loads of seemingly completly identical controller-layouts to chose from ('steam input')

btw: desktop-mice are invisible / nonexistent too, this seems to be something contributing to the unavailability of mouse-look on controllers when using -gamepadui.
