### ISSUE TITLE
Steam beta unable to "Browse local files"  from within the client

### ISSUE THREAD

**Issue by dubigrasu** [ValveSoftware/steam-for-linux#4528] opened 2016-07-02 09:31 UTC
* Steam client version: 1467408261 (built Jul 1 2016)
* SteamOS Brewmaster update 2.83 (autologin disabled and logged in Gnome desktop mode as user steam).
* Have you checked for system updates?: Yes

Steam beta client is no longer able to open local folders from (any) game's "Properties" > "Local files" tab > "Browse local files".
The same with "View screenshot library" > "Show on disk".

Same functions are still working from with the stable Steam client.

**Comment by Tele42** [comment] 2016-07-02 12:34
Also seen on Gentoo Linux.

**Comment by dubigrasu** [comment] 2016-07-02 13:08
Some extra info:
Checked on another machine where the Steam client (also beta) was not updated.
The client version was 1466216159 (built Jun 18 2016) and the issue was not present.

**Comment by vincent-t** [comment] 2016-07-08 16:09
Also on Ubuntu 16.04.

**Comment by dubigrasu** [comment] 2016-07-16 11:58
The issue seems to be resolved for me in the 1468520696 client version ((built Jul 12 2016).

**Comment by vincent-t** [comment] 2016-07-19 08:12
@dubigrasu Is this the beta version? Because for me it is still not working...

**Comment by dubigrasu** [comment] 2016-07-19 08:32
Yes, is the beta client. (The stable client had no issues for me.)

**Comment by tatokis** [comment] 2016-07-19 08:35
The bug was actually pushed to the stable version before a fix was 
released in the beta client.
I can confirm the bug is fixed for me in the beta as well.

**Comment by vincent-t** [comment] 2016-07-19 09:19
@dubigrasu Strange... For me it is not working on stable client.

**Comment by dubigrasu** [comment] 2016-07-19 09:47
> @dubigrasu Strange... For me it is not working on stable client.
Ah, @tatokis above is right; (at the time I made the report the stable client was bug free), but now the bug was pushed to the stable branch as well.
However, the beta branch seems to be fixed, have you tried the beta client?

**Comment by vincent-t** [comment] 2016-07-19 09:57
@dubigrasu Beta client has fixed the issue.

**Closed** 2016-09-04 09:44 UTC
Labels: reviewed

**Comment by Inotamira** [comment] 2019-10-01 09:51
Issue not resolved, having problems with this
