### ISSUE TITLE
Use Feral Interactive Game Mode on all games

### ISSUE THREAD

**Issue by felipecrs** [ValveSoftware/steam-for-linux#7684] opened 2021-02-28 18:23 UTC
Steam for Linux should have an option and probably be turned on by default on the settings to launch the games using [Feral Interactive's Game Mode](https://github.com/FeralInteractive/gamemode). It comes preinstalled in Ubuntu since 20.04 LTS. If it's not present in the system, the option could be either hidden or ineffective and be called: _Launch all titles with Game Mode if present_. A plus would be to be able to specify this setting in each game, in case someone wants to disable it for a certain game.

Currently, users have to do this on a game per game basis, by editing the launch options and adding `gamemoderun %command%` to them. However, this is something that probably users would like to do in all games in Linux, and having a global setting would come in handy.

This is already supported by Lutris.

**Comment by kisak-valve** [comment] 2021-02-28 18:26
Hello @felipecrs, this is the exact same request as #7126 with the same response to be given.

Closing as a duplicate of #3453.

**Closed by kisak-valve** 2021-02-28 18:26 UTC

**Comment by felipecrs** [comment] 2021-02-28 18:31
Hi @kisak-valve, I searched it and I couldn't find it, probably because I searched for _Feral Interactive_.

However, this is not the exact same feature request: this is about adding a new option in the global settings so users could enable it if they want, and not silently adding `gamemoderun` to all games.

As I said in the beginning, it could probably be turned on by default, but if there are concerns about it, it could be off.

**Comment by frostworx** [comment] 2021-03-03 10:21
Hi,  @felipecrs,
you might want to try my tool [steamtinkerlaunch](https://github.com/frostworx/steamtinkerlaunch)
which should cover your needs. Have fun!
