### ISSUE TITLE
Workspace switch causes Library view freeze (includes possible workaround)

### ISSUE THREAD

**Issue by Saeuissimus** [ValveSoftware/steam-for-linux#9880] opened 2023-07-20 03:30 UTC
#### Your system information

* Steam client version (build number or date): 1689814451
* Distribution (e.g. Ubuntu): ArchLinux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12101765/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:

Additional context: I am using the i3 window manager.

When switching to another workspace and coming back to the workspace, the steam client window is partially frozen. In particular, I am able to interact with the small mode upper menus like "Store", "Community", "Profile". I can navigate the store and discussion forums without problems in this state.

However, when the view is set to "Library" the image is completely frozen and I'm not able to interact with any of the elements in it. Some of the buttons are still recognized because the mouse icon changes when hovering over them but scrolling or clicking any of them doesn't work and furthermore it doesn't provoke any reaction. The upper menus still work though.

I even managed to trigger this during startup of the client resulting in the upper menus being invisible but still interactable. When switching to views other than "Library", the view seems to work as far as I can see. When switching to "Library" it just shows a steam logo on a dark blue background and nothing else.

#### Steps for reproducing this issue:

1. Start up Steam in small mode.
2. Go to the "Library" view.
3. Switch to another workspace.
4. Come back to the workspace that contains the Steam window.
5. Click on an unselected game in the list.

##### Workaround

After the window is frozen following the above steps:
1. Convert the window to a floating window
2. Issue a small resize.

This refreshes the render and solves the freeze problem entirely as far as I can see.

**Comment by purplebar0** [comment] 2023-07-20 13:38
I can confirm that this started with today's beta, I too use AMD GPU and a WM, Qtile in particular.

Resizing the window does work, I suspect the client cannot detect when it's un-minimised.

**Comment by mackal** [comment] 2023-07-21 23:27
I'm seeing this too, on Gentoo with KDE Plasma. AMD GPU too. Closing the window and reopening it also triggers it. Work around also fixes the issue.

**Comment by TehFreek** [comment] 2023-07-22 03:18
Can confirm, Fedora, MATE/Marco, AMD GPU.

**Comment by mayhem162** [comment] 2023-07-23 05:17
Also, reproducible on my end: i3 WM, AMD GPU, Arch, Steam beta. To add on, launching big picture mode then triggering the bug freezes most of the menus in big picture except the power menu similarly. The OP's workaround works on big picture as well.

**Comment by crumblingstatue** [comment] 2023-07-23 15:25
Using openbox, I don't even have to do any workspace shenaniganry. All I have to do is minimize the Steam window, and try to unminimize, and the view gets frozen.

That comment about the client not responding to unminimize event properly seems spot on.

**Comment by sitedyno** [comment] 2023-07-23 22:01
Toggling the window fullscreen & back seems to be another workaround in i3.

**Comment by Lancer11211** [comment] 2023-07-25 08:59
It also happens when I leave the client minimized for a few minutes(KDE).

**Comment by purplebar0** [comment] 2023-07-29 00:16
Fixed on today's beta! The fix was announced as "Fixed a case where the UI would show the wrong image when switching between small mode and normal mode", which is rather silly, because it's evidently been a much bigger issue than that, but hey, it's gone now.

**Comment by mackal** [comment] 2023-07-29 03:52
This appears to be resolved for me with the latest beta.

**Comment by Saeuissimus** [comment] 2023-07-30 02:22
I no longer experience this issue either.

**Comment by kisak-valve** [comment] 2023-09-16 00:24
Closing per the last several comments.

**Closed by kisak-valve** 2023-09-16 00:24 UTC
Labels: Steam client, Window manager, Need Retest, Web Component

**Comment by KaarelKurik** [comment] 2024-05-20 11:47
I'm experiencing exactly this issue with client build 1715891371 on Arch, with i3 workspace switching.

**Comment by acheronfail** [comment] 2024-05-23 07:51
@KaarelKurik FWIW I've noticed this on the latest updates, too. I've created a new issue for it here: https://github.com/ValveSoftware/steam-for-linux/issues/10917
