### ISSUE TITLE
Numerical keyboard doesn't work when ingame

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4373] opened 2016-03-26 11:24 UTC
Numerical keyboard doesn't work correctly on google search in steam overlay

**Comment by ekaris** [comment] 2016-06-28 07:16
When I click on numbers 4 6 8 and 2, instead of writing Numbers the keys do left write down and up on google search, these keys have arrows.
Keyboard is Logitech K360

**Comment by ekaris** [comment] 2017-08-07 12:49
Actually it doesn't work at all while ingame

**Comment by kisak-valve** [comment] 2019-04-12 14:15
Closing as a duplicate of #4170.

**Closed by kisak-valve** 2019-04-12 14:15 UTC
Labels: reviewed
