### ISSUE TITLE
Steam randomly hangs

### ISSUE THREAD

**Issue by hexum** [ValveSoftware/steam-for-linux#4387] opened 2016-04-05 19:46 UTC
Steam hangs after random amount of time (from 3 sec to 1 min) regardless of my behavior.
Window stops redrawing, all popups and dropdowns freeze and can't be wiped from the screen.
Process can be only stopped with SIGKILL.

Stack trace of main steam process when running with system libxcb.
```
#0  0xf770ab79 in __kernel_vsyscall ()
#1  0xf72a712b in poll () from /lib32/libc.so.6
#2  0xf71a6805 in ?? () from /usr/lib32/libxcb.so.1
#3  0xf71a8b77 in xcb_wait_for_special_event () from /usr/lib32/libxcb.so.1
#4  0xf6a2f6ea in ?? () from /usr/lib32/libGL.so.1
#5  0xf60cb492 in ?? () from /usr/lib32/dri/radeonsi_dri.so
#6  0xf60c7750 in ?? () from /usr/lib32/dri/radeonsi_dri.so
#7  0xf5fe5aa8 in ?? () from /usr/lib32/dri/radeonsi_dri.so
#8  0xf5fe7350 in ?? () from /usr/lib32/dri/radeonsi_dri.so
#9  0xf5f8bd07 in ?? () from /usr/lib32/dri/radeonsi_dri.so
#10 0xf5f968c8 in ?? () from /usr/lib32/dri/radeonsi_dri.so
#11 0xf5d3d2ea in ?? () from /usr/lib32/dri/radeonsi_dri.so
#12 0xf6a32742 in glClear () from /usr/lib32/libGL.so.1
#13 0xeec2a211 in ?? () from /home/hexum/.local/share/Steam/ubuntu12_32/vgui2_s.so
#14 0xeec2cdc5 in ?? () from /home/hexum/.local/share/Steam/ubuntu12_32/vgui2_s.so
#15 0xeec3ca0d in ?? () from /home/hexum/.local/share/Steam/ubuntu12_32/vgui2_s.so
#16 0xf1971340 in ?? () from /home/hexum/.local/share/Steam/ubuntu12_32/steamui.so
#17 0xf1989f2b in ?? () from /home/hexum/.local/share/Steam/ubuntu12_32/steamui.so
#18 0xf1994045 in ?? () from /home/hexum/.local/share/Steam/ubuntu12_32/steamui.so
#19 0x5661a41a in RunSteam(int, char**, bool) ()
#20 0x56602e32 in ?? ()
#21 0xf71dfa07 in __libc_start_main () from /lib32/libc.so.6
#22 0x566056d9 in _start ()
```

Error was the same when steam runtime libxcb was used.
Can we conclude that the problem is in driver? What futher diagnostics should be done?
If I manage to run a game before freeze game works fine (but steam randomly freezes in background though).

**Comment by gdrewb-valve** [comment] 2016-04-05 20:09
That does appear to be an AMD driver issue, you should also check AMD-related forums and such.

**Comment by Tele42** [comment] 2016-04-05 20:39
@hexum are you using DRI3? This may be a duplicate of #4368.

**Comment by hexum** [comment] 2016-04-05 21:10
[Patch](https://bugs.freedesktop.org/attachment.cgi?id=122489) was applied to xorg-server and the problem has gone.
Thank you very much!

**Comment by gdrewb-valve** [comment] 2016-04-05 21:38
Thanks.

**Closed by gdrewb-valve** 2016-04-05 21:38 UTC
Labels: AMD drivers, reviewed
