### ISSUE TITLE
CSGO Launch but no image is displayed

### ISSUE THREAD

**Issue by SkylerBT** [ValveSoftware/steam-for-linux#9361] opened 2023-04-23 03:00 UTC
#### Your system information
https://gist.github.com/SkylerBT/4605246049f443fbcf3f5422f2a58cfa
* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Artix
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Csgo open but its like the display doesnt exist, i can hear the sound but i cannot see the game
![image](https://user-images.githubusercontent.com/131564421/233817252-7120f92e-dfe8-44f7-b8d7-473069d3afdb.png)

  https://gist.github.com/SkylerBT/f79d7221bc794190a779c4aa16f8a096

#### Steps for reproducing this issue:

1. start steam 
2. open csgo

**Comment by kisak-valve** [comment] 2023-04-23 12:45
Closing as a duplicate of https://github.com/ValveSoftware/csgo-osx-linux/issues/3166.

**Closed by kisak-valve** 2023-04-23 12:45 UTC
