### ISSUE TITLE
Severe Texture Corruption Under Fglrx and Team Fortress 2

### ISSUE THREAD

**Issue by egee-irl** [ValveSoftware/steam-for-linux#3894] opened 2015-06-21 04:54 UTC
Certain maps on Team Fortress 2 feature severe texture corruption that render the game unplayable. Sawmill is one such map:

![corruption](https://cloud.githubusercontent.com/assets/6679968/8270525/d69ab8d2-1796-11e5-8b22-d58d005ae55a.jpg)

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x30
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3700 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-21-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon(TM) R7 Graphics  

```
Driver Version:  4.4.13374 Compatibility Profile Context 15.20.1013
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x130f
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.04" x 11.26"  (22.95" diag)
                                        50.9cm x 28.6cm  (58.3cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  14915 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  96984 Mb
    Largest Free Hard Disk Block:  24049 Mb

Installed software:

Recent Failure Reports:

**Comment by nixi-awoo** [comment] 2015-06-21 07:35
This corruption is most likely caused by the fglrx driver. This happened to me as well. Everything worked quite well, if not better, when I tried using the RadeonSI driver.

**Comment by kisak-valve** [comment] 2018-10-26 14:50
Hello @egee-irl, fglrx has been discontinued in favor of mesa and amdgpu-pro. If you're still seeing rendering issues with TF2 and one of these drivers on an up to date system, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker after checking if there isn't a similar issue already open.

Closing as video driver quality from 2015 is no longer relevant.

**Closed by kisak-valve** 2018-10-26 14:50 UTC
Labels: AMD drivers, reviewed
