### ISSUE TITLE
(big picture) Max resolution is 1440×880

### ISSUE THREAD

**Issue by legacychimera247** [ValveSoftware/steam-for-linux#7752] opened 2021-04-15 21:48 UTC
#### Your system information

* Steam client version : latest stable
* Distribution : Fedora workstation 32
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Simply enough my screen resolution is 1440×900 but in big picture i only have 1440×880 maximum, so i'm having black bars. How do i put big picture in a way i don't have black bars anymore?

**Comment by kisak-valve** [comment] 2021-04-15 22:00
Hello @legacychimera247, this reads like the feature request at #7486, which mentions that Big Picture mode is currently locked to a 16:9 aspect ratio and likely the same root cause with your 16:10 display. Feel free to add your experience to that feature request.

Closing as a duplicate.

**Closed by kisak-valve** 2021-04-15 22:00 UTC
