### ISSUE TITLE
Trine 2 crashes Steam when in offline mode and game saves not accessible while offline

### ISSUE THREAD

**Issue by pizzadude** [ValveSoftware/steam-for-linux#2295] opened 2013-04-09 14:49 UTC
The same issue as https://github.com/ValveSoftware/steam-for-linux/issues/701 , which is now closed.
I'm using Linux Mint 13 64-bit, the latest Steam and Trine 2 updates, etc.
When launching Trine 2 in offline mode, the save games appear to be missing. Starting a new game doesn't work because the game complains about no disk space available, although I have 100s of Gigabytes free.
The game eventually crashes.
Starting the game while online fixes the issue, and the saves appear and everything works.

**Comment by kisak-valve** [comment] 2017-04-26 16:44
Hello @pizzadude, @rawcoder, are either of you still experiencing this issue?

**Comment by rawcoder** [comment] 2017-04-26 19:15
Hi @kisak-valve 
It seems the issue has been resolved.

I'm using the latest steam version and unable to reproduce it anymore.

**Comment by kisak-valve** [comment] 2017-05-29 13:43
Thanks for retesting @rawcoder, closing.

**Closed by kisak-valve** 2017-05-29 13:43 UTC
Labels: Need Retest, reviewed, Steam client
