### ISSUE TITLE
steam crashes after exiting aplex legends 

### ISSUE THREAD

**Issue by lowlux** [ValveSoftware/steam-for-linux#9193] opened 2023-02-10 02:47 UTC
[
![Screenshot_20230209_214459](https://user-images.githubusercontent.com/1283196/217987768-77a4a542-0fe8-437e-a4b0-1186fac33533.png)

**Comment by kisak-valve** [comment] 2023-02-10 03:18
Hello @lowlux, if you completely close steam, then run `steam` from a terminal and reproduce the issue, are there any hints? Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by kisak-valve** [comment] 2023-03-10 20:16
Closing due to a lack of actionable information.

**Closed by kisak-valve** 2023-03-10 20:16 UTC
Labels: Need More Information
