### ISSUE TITLE
Swapped Escape and Caps lock causes funny behaviour in source engine games

### ISSUE THREAD

**Issue by mondoman712** [ValveSoftware/steam-for-linux#2788] opened 2013-08-19 23:12 UTC
I have the escape and caps lock keys swapped in X (using setxkbmap -option caps:swapescape in the xinitrc) and it works in everything else (that i've tested).
An easy fix for this would be to allow rebinding of the escape to menu key.

I don't think system info or logs are necessary in this situation, but if they are, please tell me.

**Comment by kisak-valve** [comment] 2017-08-30 22:17
Closing as a duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/304.

**Closed by kisak-valve** 2017-08-30 22:17 UTC
Labels: reviewed
