### ISSUE TITLE
Steam fails to start after running it with Open drivers, then switching to propietary drivers

### ISSUE THREAD

**Issue by LucesEnBabel** [ValveSoftware/steam-for-linux#5516] opened 2018-06-04 18:14 UTC
Steam fails to start after running it with open drivers, then switching to proprietary drivers. Steam successfully installs and runs if you installed proprietary drivers beforehand.

Purging Steam and deleting its directories and then reinstalling had no effect.

#### System Info
Distro: elementaryOS Loki (0.4). Based on Ubuntu 16.04
Video Drivers: nvidia 390.59

#### Steps for reproducing this issue:

1. Install Linux Distro
2. Install Steam
3. Wait for the first time dependency setup
4. Run Steam
5. Install proprietary drivers 

#### What was not tested:

Running the first time setup script again, since I can't find it.

**Comment by LucesEnBabel** [comment] 2018-06-04 18:29
@kisak-valve glxinfo output https://gist.github.com/LucesEnBabel/aa4cde16fdb64f8ca7769d4c04699946

**Comment by kisak-valve** [comment] 2018-06-04 18:35
Since glxinfo is trying to use swrast, which is mesa's slower software renderer, that indicates that mesa's libGL.so.1 is being used and 32 bit opengl is misconfigured or incomplete on your system. Steam needs a working 32 bit opengl stack.

**Comment by LucesEnBabel** [comment] 2018-06-05 13:54
How can I run the first run script?

**Comment by kisak-valve** [comment] 2018-06-05 14:19
First run script of what? The closest thing Steam would have is `steam --reset`, which re-bootstraps the client as if it's the first run or make sure steam is not running, move `~/.steam` and `~/.local/share/Steam` somewhere out of the way and re-run steam.

It should be noted that it's a waste of time to try those until after you've confirmed that the 32 bit OpenGL driver is in a working state.

**Comment by kisak-valve** [comment] 2018-06-05 14:36
For Debian and derivatives, that would be something like `sudo apt purge steam` (and maybe also `steam-launcher`), then re-install with whatever method you used before.

**Comment by LucesEnBabel** [comment] 2018-06-05 15:40
I double checked my installation, and apparently _nvidia-390_ fails to correctly set up a proper 32 bit environment.

Fixed it by running `find -L /etc/ld.so.conf.d -type f | xargs grep -i nvidia`. Steam runs correctly now.

Please mark this issue as invalid.

**Comment by kisak-valve** [comment] 2018-06-05 15:44
Closing per the last comment.

**Closed by kisak-valve** 2018-06-05 15:44 UTC
Labels: Distro Family: Ubuntu, NVIDIA drivers
