### ISSUE TITLE
Steam eating up all my bandwith with unstoppable download while I'm playing.

### ISSUE THREAD

**Issue by rsmantini** [ValveSoftware/steam-for-linux#3681] opened 2015-01-20 01:36 UTC
From time to time steam decides to eat up all the bandwidth of my crappy internet making it impossible to play internet based games. There is nothing else open on the PC. It just happened in middle of a Dota game, and I could do nothing. It's very annoying and frustrating. 
After the episode I got a steam update window, so probably steam was updating the client. It's not the first time that this happens to me.
Steam shouldn't download anything while you are playing. At the very least it should present an easy way to cancel it. 

System Info:

> 3.13.0-43-generic  72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 
> 
> GNU/Linux
> Distributor ID: Ubuntu
> Description:    Ubuntu 14.04.1 LTS
> Release:        14.04
> Codename:       trusty
> 
> kded4 --version
> Qt: 4.8.6
> KDE Development Platform: 4.13.3
> KDE Daemon: 4.13.3
> 
> H/W path        Device      Class          Description
> system         To be filled by O.E.M. (To be filled by O.E.M.)
> /0                          bus            B75M-D3H
> /0/0                        memory         64KiB BIOS
> /0/4                        memory         128KiB L1 cache
> /0/5                        memory         1MiB L2 cache
> /0/6                        memory         8MiB L3 cache
> /0/7                        memory         8GiB System Memory
> /0/7/0                      memory         DIMM [empty]
> /0/7/1                      memory         4GiB DIMM DDR3 Synchronous 1600 MHz (0.6 ns)
> /0/7/2                      memory         DIMM [empty]
> /0/7/3                      memory         4GiB DIMM DDR3 Synchronous 1600 MHz (0.6 ns)
> /0/43                       processor      Intel(R) Xeon(R) CPU E3-1240 V2 @ 3.40GHz
> /0/100                      bridge         Xeon E3-1200 v2/Ivy Bridge DRAM Controller
> /0/100/1                    bridge         Xeon E3-1200 v2/3rd Gen Core processor PCI Express Root Port
> /0/100/1/0                  display        GK106 [GeForce GTX 650 Ti]
> /0/100/1/0.1                multimedia     GK106 HDMI Audio Controller
> /0/100/14                   bus            7 Series/C210 Series Chipset Family USB xHCI Host Controller
> /0/100/16                   communication  7 Series/C210 Series Chipset Family MEI Controller #1
> /0/100/1a                   bus            7 Series/C210 Series Chipset Family USB Enhanced Host Control
> /0/100/1b                   multimedia     7 Series/C210 Series Chipset Family High Definition Audio Con
> /0/100/1c                   bridge         7 Series/C210 Series Chipset Family PCI Express Root Port 1  
> /0/100/1c.4                 bridge         7 Series/C210 Series Chipset Family PCI Express Root Port 5  
> /0/100/1c.4/0   eth1        network        RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller  
> /0/100/1d                   bus            7 Series/C210 Series Chipset Family USB Enhanced Host Control
> /0/100/1e                   bridge         82801 PCI Bridge
> /0/100/1f                   bridge         B75 Express Chipset LPC Controller
> /0/100/1f.2                 storage        7 Series/C210 Series Chipset Family 4-port SATA Controller [I
> /0/100/1f.3                 bus            7 Series/C210 Series Chipset Family SMBus Controller
> /0/100/1f.5                 storage        7 Series/C210 Series Chipset Family 2-port SATA Controller [I
> /0/1            scsi0       storage  
> /0/1/0.0.0      /dev/sda    disk           320GB WDC WD3200AAJS-2
> /0/1/0.0.0/1    /dev/sda1   volume         100MiB Windows NTFS volume
> /0/1/0.0.0/2    /dev/sda2   volume         297GiB Windows NTFS volume
> /0/2            scsi1       storage  
> /0/2/0.0.0      /dev/sdb    disk           1TB WDC WD10EADS-00L
> /0/2/0.0.0/1    /dev/sdb1   volume         927GiB EXT4 volume
> /0/2/0.0.0/2    /dev/sdb2   volume         4094MiB Extended partition
> /0/2/0.0.0/2/5  /dev/sdb5   volume         4094MiB Linux swap / Solaris partition
> /0/2/0.1.0      /dev/cdrom  disk           DVDRAM GH24NS95

![steamdownload](https://cloud.githubusercontent.com/assets/5944832/5810536/1f76bf2c-a02f-11e4-9632-d6bfb5163882.png)

![steamupdate](https://cloud.githubusercontent.com/assets/5944832/5810828/e97297ca-a033-11e4-8b48-06e66c2033ac.png)

**Comment by HeavyHamster** [comment] 2015-01-26 10:58
This is also happening to me. I've reported it on Steam Support and they don't want to help because I'm not running Ubuntu. I think that it's not a distribution problem, it's more like a bug on the Linux Steam Client.

System Info:
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x25
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  1866 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Fedora release 21 (Twenty One)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.17.8-300.fc21.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11602901
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ironlake Mobile 

    Driver Version:  2.1 Mesa 10.4.1
    OpenGL Version: 2.1
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x8086
    DeviceID:  0x46
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 13,54" x 7,60"  (15,51" diag)
                                            34,4cm x 19,3cm  (39,4cm diag)
    Primary VRAM Not Detected
    
Sound card:
    Audio device: Intel IbexPeak HDMI
    
Memory:
    RAM:  3627 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  es_ES.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  65088 Mb
    Largest Free Hard Disk Block:  7615 Mb
    
Installed software:
    
Recent Failure Reports:
    
Also some images from the settings and how Steam client gets all bandwidth while playing:

![instantanea5](https://cloud.githubusercontent.com/assets/10707152/5898697/5387282e-a552-11e4-9c29-bcc659afb78b.png)
![instantanea6](https://cloud.githubusercontent.com/assets/10707152/5898698/538fa832-a552-11e4-9aa3-0924f1cc4f16.png)
![instantanea4](https://cloud.githubusercontent.com/assets/10707152/5898700/56979850-a552-11e4-81f6-9113cf568601.png)

**Comment by Oxalin** [comment] 2015-02-24 20:39
If I understand correctly, the problem happens for Steam client updates, not for game updates, is that it? That would mean Steam only applies the Download Restrictions on games, not to itself, right?

**Comment by HeavyHamster** [comment] 2015-02-24 22:54
Yes, that's right.
Only happens to download new updates of Steam Client while playing, not game updates.

**Comment by Oxalin** [comment] 2015-02-25 00:06
Then I suggest you modify slightly this bug's title for something like "Steam client update aren't affected by Download Restrictions". Valve may choose to see it as a Feature request. Also, I would open a bug in the Steam community since this issue affects steam on all OSes.

**Comment by HeavyHamster** [comment] 2015-02-25 00:17
Maybe the owner's post can do it.
I suspected that it could be in all OS since I have seen people playing with lag when they usually don't have when a new update is released.
Thanks for opening a bug in the Steam community, I tried on Steam Support and they gave me no support :(

**Comment by Oxalin** [comment] 2015-02-25 02:22
It seems someone has already requested this feature: https://steamcommunity.com/groups/SteamClientBeta/discussions/1/666826251168456439/

On the other hand, maybe Steam client should follow the same Download Restrictions as for games instead of having its own settings as suggested in the request. Then that would be more like a bug.

**Comment by Oxalin** [comment] 2015-02-25 02:31
Here it is: http://steamcommunity.com/groups/SteamClientBeta/discussions/0/617328967240812393/
Could rsmantini close the current bug since it is not specific to Steam client for Linux?

**Comment by kisak-valve** [comment] 2018-06-01 14:16
Closing as a duplicate of #2003.

**Closed by kisak-valve** 2018-06-01 14:16 UTC
Labels: Steam client, reviewed
