### ISSUE TITLE
Portal fails to use a xbox360 gamepad

### ISSUE THREAD

**Issue by ribalda** [ValveSoftware/steam-for-linux#4105] opened 2015-11-02 10:03 UTC
I have used with no problem the gamepad on other games: LFD2, big picture, truck simulator...., but it not detected by Portal.

- If I cat /dev/js0 and move the pad I see raw data moving
- going to the game console and execute run 360controller, or 360controller-linux does nothing.

How can I debug this? Why other steam source (LFD2) games work and this doesn't.  What library are you using to handle the js?

**Comment by Tele42** [comment] 2015-11-02 15:15
Duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/1931.

**Comment by gdrewb-valve** [comment] 2015-11-02 19:23
Closing in favor of Portal repo issue.

**Closed by gdrewb-valve** 2015-11-02 19:23 UTC
Labels: duplicate, reviewed
