### ISSUE TITLE
libcef fontconfig - undefined symbol: FcConfigGetSysRoot

### ISSUE THREAD

**Issue by PeterMX** [ValveSoftware/steam-for-linux#6499] opened 2019-09-17 20:15 UTC
#### Your system information

* Steam client version (build number or date): Sept 17th
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Library screen gets freezed when you switch screen(to profile screen for example), then Library screen doesn't respond to mause input, for example you click on a game in the list and it does nothing, but then you switch to other screen(profile for example) then you go back to library and it will be on the game you clicked before you went to profile screen.

#### Steps for reproducing this issue:

1. first this doesn't happens ever but when it does:
2. open steam(in my case it starts in the library section) and everthing works OK
3. switch section(profile for example) then go back to Library section and it gets freezed(just this section, all other still work OK)

**Comment by kisak-valve** [comment] 2019-09-17 20:20
Hello @PeterMX, in Steam -> Settings -> Interface, is `Enable GPU accelerated rendering in web views (requires restart)` checked, and if it is, does unchecking it make a difference?

**Comment by PeterMX** [comment] 2019-09-17 20:40
> Hello @PeterMX, in Steam -> Settings -> Interface, is `Enable GPU accelerated rendering in web views (requires restart)` checked, and if it is, does unchecking it make a difference?

yes, it is checked. So I unchecked it and I was not able to reproduce the issue.

I don't know if this is useful but related to this issue sometimes I get this for long times:
![Captura de pantalla de 2019-09-17 15-30-55](https://user-images.githubusercontent.com/9899682/65077858-6f11bf80-d961-11e9-90ca-48aa94b09471.png)

**Comment by kisak-valve** [comment] 2019-09-17 20:42
What video card and driver version are you using?

**Comment by PeterMX** [comment] 2019-09-17 20:51
Nvidia RTX 2060 with driver: 418.56

just in case it is useful I got those files in /tmp/dumps
[assert_20190917111816_55.dmp.txt](https://github.com/ValveSoftware/steam-for-linux/files/3623402/assert_20190917111816_55.dmp.txt)
[crash_20190917153317_12.dmp.txt](https://github.com/ValveSoftware/steam-for-linux/files/3623403/crash_20190917153317_12.dmp.txt)

**Comment by kisak-valve** [comment] 2019-09-17 20:56
For reference, both attached minidumps are DUMP_REQUESTED in crashhandler.so.

**Comment by eeyrjmr** [comment] 2019-09-17 21:58
Same problem here (Gentoo)

Launching Steam from the command line shows repeated spam of: 

STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: ./libcef.so: undefined symbol: FcConfigGetSysRoot

**Comment by telans** [comment] 2019-09-19 02:21
Same problem on Arch linux after the most recent Beta update. However, after restarting two or three times this issue *might* not appear.

![Screenshot_20190919_141356](https://user-images.githubusercontent.com/45819748/65207974-294d1800-da83-11e9-8399-c82a2b767731.png)

Disabling GPU accelerated rendering fixes the issue but I am left with abysmal performance (not that it's adequate with it enabled, either).

I see this error when lauching through a terminal with acceleration disabled:

```
[*1641.769862:INFO:crash_reporting.cc(245)] Crash reporting enabled for process: gpu-process
[*1641.800316:INFO:crash_reporting.cc(268)] Crash reporting enabled for process: renderer
```

And this with acceleration enabled:
```
[*1750.312126:WARNING:x11_util.cc(1422)] X error received: serial 80, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)
[*1750.312174:WARNING:x11_util.cc(1422)] X error received: serial 82, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)
RegisterForAppOverview: 883
RegisterForAppOverview 1: 8ms
RegisterForAppOverview 2: 10ms
[*1756.435253:WARNING:url_request_job_manager.cc(91)] Failed to map: chrome-extension://invalid/
[*1756.439658:WARNING:url_request_job_manager.cc(91)] Failed to map: chrome-extension://invalid/
```

**Comment by c0r73x** [comment] 2019-09-19 18:58
Setting STEAM_RUNTIME_PREFER_HOST_LIBRARIES to 1 fixed it for me, which is very strange because I don't even have libcef installed on my system. I suspect there is some issue with setting up the library paths in the latest beta.

**Comment by eeyrjmr** [comment] 2019-09-20 16:09
I can confirm that STEAM_RUNTIME_PREFER_HOST_LIBRARIES=1 permits the library to work.

I typically have this set but disabled it to debug a game that didn't work.

**Comment by d-goldin** [comment] 2019-09-21 07:56
While I was unable to make it work with `libcef` yet (on NixOS), I'd like to add a small workaround; It seems to work just fine in "Big Picture Mode" as it seems to not rely on `libcef` for rendering in this mode.

**Comment by Managor** [comment] 2019-09-23 19:16
I'd like to chime in that I probably have the same problem. Changing between the community and library tabs makes those clicks actually do something.
[ASD.webm.zip](https://github.com/ValveSoftware/steam-for-linux/files/3643735/ASD.webm.zip)

**Comment by Kandarihu** [comment] 2019-09-24 12:00
I think that the basis for this problem existed before the New Library was implemented. Ever since the new version of the Friends List came into the game, it would occasionally blank out and I had no idea why. I worried that the problem might affect the New Library and I was right. I think I can assume, then, that the framework that drives the New Friends List and the New Library is one and the same, and is pivotal to the issue that we are having.

**Comment by gnac** [comment] 2019-09-24 16:10
I saw this issue appear yesterday on OpenSuse 15.0. 
About Steam:
Built Sep 23 2019
Steam API: v020
Steam Package Versions: 1569270763

Using STEAM_RUNTIME_PREFER_HOST_LIBRARIES=1 allows the library and other pages to display.

**Comment by echaskaris** [comment] 2019-10-02 12:08
I'm also experiencing this issue.

#### Your system information

* Steam client version (build number or date): Sep 30
* Distribution (e.g. Ubuntu): Ubuntu 19.04
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

System info: [Here](https://gist.github.com/echaskaris/3b86a447cab32359e70b422300987ddb)

**Comment by c0r73x** [comment] 2019-10-02 19:45
Would have been better to let us have some sort of browser-plugin to launch the games directly from the webpage. Or even better create a SDK that we could use to build our own ui's... The client is terrible in every way possible... And with this new beta it's worse than ever... Sorry Valve but it's fact.

**Comment by echaskaris** [comment] 2019-10-03 13:21
Happened after going to Inventory

**Comment by buckybits** [comment] 2019-10-08 16:11
- Steam client version (build number or date): Built: Oct 7 2019, Steam API v020 Steam package versions: 1570492308 
- Distribution (e.g. Ubuntu): Ubuntu 19.04 64-bit, Kernel Version:  5.0.0-31-generic
- Opted into Steam client beta?: Yes
- Have you checked for system updates?: Yes (10/08/2019)

- Processor Information:    CPU Brand:  AMD A8-3850 APU with Radeon(tm) HD 
- Graphics Card: Nvidia GefForce GTX 650 Ti BOOST (Kepler) 
- NVIDIA Driver 435.21

**Please describe your issue in as much detail as possible:**

With enabled "GPU accelerated rendering in web views" mouse clicks within the new UI do not work at all - no response - but ONLY within the web elements. Top bar Steam Client elements (STORE LIBRARY COMMUNITY and top-top drop down menu: Steam View Friends Games ... all work with the mouse. Only the elements INSIDE the 'web view'(?!) trigger no response with mouse clicks.

Turning GPU Acceleration off(!), allows for regular mouse use and all elements in the 'new view' are responsive, again.

**Steps for reproducing this issue:**
1. User New Steam UI. NOT Big Picture Mode - Standard mode.
2. GPU Acceleration active (on)
3. Switch to the user library "Collections" tab.
4. Try to click on anything(!) within the left side list view and/or on anything on the main/right side view elements.
5. GPU Acceleration turned off
6. Try to click on anything(!) within the left side list view and/or on anything on the main/right side view elements.

**Comment by RockyTV** [comment] 2019-10-09 02:14
- Steam client version (build number or date): Oct 7 2019, at 22:46:25, Steam API v020, Steam package versions 1570492308
- Distribution (e.g. Ubuntu): Arch Linux
- Opted into Steam client beta?: Yes
- Have you checked for system updates?: Yes


I'd like to add that the new library is unusable when Steam is down. It happened today when Steam went under maintenance and the library UI wasn't responsive. I could browse the store, my profile, but anything I did in the library tab didn't work, like if the whole client was stuck. I had to restart Steam for it to work again.

**Comment by stephenlake** [comment] 2019-10-10 17:22
Just adding a reference here:
https://steamcommunity.com/groups/SteamClientBeta/discussions/3/1629665087681729148/

**Comment by TECHNOFAB11** [comment] 2019-10-10 17:35
So i at least could fix this issue (tried changing tabs, starting games, seems to be gone now) by unchecking the smooth scrolling in Settings > Interface. I had GPU acceleration turned off before, but i tried with it being on. This resulted in the freeze. 

So my guess is: disabling smooth scroll AND gpu acceleration will probably fix it. But thats just a workaround

**Comment by stephenlake** [comment] 2019-10-16 21:14
I believe one of the recent updates fixed these issues, on my part anyway; Everything seems to be running perfectly on my end right now and we have some cool "Low Performance Mode" options too!

**Comment by gnac** [comment] 2019-10-17 17:44
I just downloaded version 1571182697, buit Oct 15 at 18:19:51.

Unfortunately, I still have the same problem with Blank/Black Library/Store etc.

**Comment by insideone** [comment] 2019-10-31 23:32
@d-goldin I'm new to nixos and haven't figured out how to fix it too, but managed to find out that ~/.steam/steam/ubuntu12_64/libcef.so has FcConfigGetSysRoot marked as "U" i.e. external. On my other machine that uses Mint this function is imported from /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.10.1

Adding fontconfig and libcef packages to steam (pkgs.steam.override) with or without STEAM_RUNTIME_PREFER_HOST_LIBRARIES didn't help and now I'm stuck too.

**Comment by qrilka** [comment] 2019-11-12 07:58
@insideone did you find a proper solution for NixOS?

**Comment by insideone** [comment] 2019-11-13 21:19
@qrilka I found that current stable branch had issue & [PR](https://github.com/NixOS/nixpkgs/pull/73281), however it wasn't relevant to our issue. I ended up with cloning packages repository and updating from release-19.09 branch and it helped. However, I will switch to 19.09 channel when they build it with this fix

**Comment by tex** [comment] 2019-11-15 22:20
I have same issue. Intel integrated graphics card. Switched to full picture mode and it works fine. Even sounds in steam started to work.

**Comment by byte1024** [comment] 2020-02-28 03:08
Just had this happen.

It was the result of a network connection issue upon resuming the computer. Browser also had a problem as well.

The browser recovered but Steam did not.

A reboot fixes the problem. Maybe killing Steam will as well but an exit does not.

You should not need to do anything special to fix this.

**Comment by gnac** [comment] 2020-03-27 04:40
I just installed steam for a account on an existing linux computer and the issue has arisen. A different account, with two computers, (the same computer as the new account, and the second account on a separate computer) do not exhibit the issue. All are running the same Linux distro, OpenSuse 15.1

**Comment by TTimo** [comment] 2020-04-24 15:08
Let's try to move this forward - if you are still experiencing this problem, please provide a complete steam runtime diagnostic, obtained via Help > System Information (wait for the "Steam Linux Runtime Information" to populate and provide that especially!).

Current diagnostic is that on your linux distribution Steam is pinning a newer fontconfig library than the steam runtime which - although newer - is incompatible with CEF (Steam embedded web browser).

**Comment by Anrock** [comment] 2020-09-08 15:34
@TTimo still experiencing this and also having `CClientJobGatherRuntimeInformation: read output failed` in System Information.

**Comment by Anrock** [comment] 2020-09-08 15:46
@TTimo however downgrading fontconfig from 2.13.1 to 2.13.0 fixes the issue.

**Comment by james2432** [comment] 2021-08-03 12:06
Also having CEF issues, currently on my machine I have:

    local/fontconfig 2:2.13.94-1
        Library for configuring and customizing font access
    local/lib32-fontconfig 2:2.13.94-1
        Library for configuring and customizing font access

it seems to be preferring the system libraries over the libraries included in steam

**Comment by kisak-valve** [comment] 2022-01-07 20:22
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by Managor** [comment] 2022-01-08 11:06
Haven't encountered it in ages. It stopped happening some time after reporting it.

**Comment by james2432** [comment] 2022-01-08 13:10
I haven't had it since using: https://archlinux.org/packages/multilib/x86_64/steam-native-runtime/

I uninstalled and ran the steam binary from you. No issues.

I noticed you compare now binary versions and force certain versions or use updated versions. :+1:

**Comment by kisak-valve** [comment] 2022-02-11 20:02
Thanks for retesting, closing as fixed some time ago.

**Closed by kisak-valve** 2022-02-11 20:02 UTC
Labels: Steam client, Need Retest, Web Component
