### ISSUE TITLE
Please add game desktop icons

### ISSUE THREAD

**Issue by ViBENo1** [ValveSoftware/steam-for-linux#4361] opened 2016-03-20 03:50 UTC
Tons of games has no own icons for Linux version and that's very annoying that my desktop filled with default Steam icon's (for example Hotline Miami, Worms Clan Wars, Never Alone, etc).

**Comment by Tele42** [comment] 2016-03-20 03:56
Duplicate of #989, as explained there, each game's developer should be contacted regarding games with a bad configuration.

**Comment by fishxz** [comment] 2016-03-20 11:00
especially valve game. they haver either no icons, bad icons or bad names.

**Comment by gdrewb-valve** [comment] 2016-03-20 16:22
Closing duplicate.

**Closed by gdrewb-valve** 2016-03-20 16:22 UTC
Labels: duplicate, reviewed
