### ISSUE TITLE
[KDE] Taskbar button turning orange at random times

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/steam-for-linux#4829] opened 2017-01-24 00:46 UTC
I recently got back onto my Linux build, updated Steam (big ups to whoever took over the Linux client, by the way; I saw all the fixes in the latest patch notes!), and ran a full system upgrade from 16.04 to 16.10. And I'm noticing some behavior I wasn't seeing before, although maybe I just didn't notice it: The taskbar button for Steam sometimes turns orange for no apparent reason. I thought maybe it was accidentally doing this whenever it generated a toast saying a friend had launched a game, but no. It _might_ be doing it in response to friends quitting games or going offline, which don't generate toasts; I'm having a hard time constantly monitoring the Friends pane without falling asleep.

* Steam client version: 1484790260 (January 19 patch, not beta)
* Distribution: Kubuntu 16.10, running KDE, latest updates

**Comment by DrDoctor13** [comment] 2017-01-28 17:17
Is it starting/ending game downloads when this happens?

**Comment by stevethepocket** [comment] 2017-01-28 21:29
Nope.

**Comment by Baguettedood** [comment] 2017-02-04 13:16
I can reproduce this on KDE 5.8.5 and 5.9.

1. Open Steam.
2. Open the Friends List.
3. Open a chat window.
4. Close the chat window. The Friends list should now be in focus.
5. The friends list is demanding attention even though it is in focus. It does not stop until focusing on another window and then changing focus back to the friends list.

Seems to be sometimes reproducable with other circumstances too, such as opening and closing the friends list making the main window demand attention, or  but the listed steps seems to be the most reliable.

**Comment by kisak-valve** [comment] 2017-02-10 00:00
Today's [steam beta client](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/572357653497317812) has "Fixed Windows taskbar showing pending progress even if there are no more needed updates" which has a small chance of being related to this issue. Can someone test for the quirk behavior with the steam beta client.

**Comment by stevethepocket** [comment] 2017-02-12 04:00
It might have fixed one of multiple causes but definitely not all. So far I haven't had it randomly turn orange while I'm doing other stuff, but when I accidentally closed the Steam client main window, the Friends tab turned orange.

**Comment by hjri** [comment] 2017-03-20 23:07
This issue have been pestering me for quite a time (year or so I think). My workaround it to use KWin's shortcut "Switch to window demanding attention" to switch to steam and "dismiss" the orange highlight.

**Comment by stevethepocket** [comment] 2017-04-15 01:20
Just popping in to let you know this is still happening in 17.04 with the new Plasma.

**Comment by stevethepocket** [comment] 2018-03-23 18:50
I'm starting to wonder if this is related to Steam's habit of focusing other client windows when one is closed. For example, (in Windows) when I get an event notification and then close it, the main client window pops into the foreground even if it was behind something else like Firefox. It's possible that Linux window managers are (understandably) blocking this behavior and using the orange taskbar behavior as a way of saying "Hey, this program wants your attention, but you're going to have to click it yourself."

**Comment by hjri** [comment] 2018-03-24 00:55
Yes, one option is that window simply "asks attention" - _NET_WM_STATE_DEMANDS_ATTENTION which makes orange taskbar entry. Another one is sending _NET_ACTIVE_WINDOW - ask to activate some window, but window manager might deny it and just set _NET_WM_STATE_DEMANDS_ATTENTION instead.

**Comment by stevethepocket** [comment] 2018-04-16 17:03
Yeah, I think this is now only happening when I close one window and another tries to take focus. Arguably that's a different issue than what I was describing, which is that it was happening completely at random. But it's also a cross-platform issue, which means it's not appropriate for this place. Should I close this, or what?

**Comment by Hasshu** [comment] 2020-05-30 11:02
Plasma 5.18.5, and the issue persists.

Oddly enough, it often happens to an already-focused window, and clicking on it again does nothing; to remove the orange highlight, you need to switch focus to another window, then select the "orange" one again. In case of the main client window, hovering the cursor over one of the drop-down menus (Store, Library, Community, etc.) works as well.

**Comment by Hasshu** [comment] 2022-05-20 14:35
Apparently, something has been fixed at some point, as I haven't seen this issue manifesting in a while. (Plasma 5.24.5 here.)

**Comment by kisak-valve** [comment] 2022-06-24 20:26
Closing per the last comment.

**Closed by kisak-valve** 2022-06-24 20:26 UTC
Labels: Steam client, Need Retest
