### ISSUE TITLE
Update screen really pisses me off

### ISSUE THREAD

**Issue by cheery** [ValveSoftware/steam-for-linux#3454] opened 2014-08-26 11:36 UTC
The steam's been on for 3 days on my computer, now I wanted to play something and had to plug a device and restart. The thing's loading every update it can find. Can't skip it.

As the grand finale it messed up the update and doesn't start up anymore. steamui.so failed to load. + jammed and lost the keyboard. Had to reboot my machine.

**Comment by kisak-valve** [comment] 2018-03-16 14:07
I'm going to close this issue as there has been quite a bit of change in the steam client since 2014 and if this is reproducible, it would require a new investigation.

**Closed by kisak-valve** 2018-03-16 14:07 UTC
Labels: reviewed
