### ISSUE TITLE
OpenAL lib too old?

### ISSUE THREAD

**Issue by adolson** [ValveSoftware/steam-for-linux#3970] opened 2015-08-19 05:39 UTC
I have a few games where audio is messed up when running with libopenal.so.1.13.0, which is included in the Steam runtime. When I delete it and games are free to use my system's OpenAL (1.15.1, I'm on Debian Jessie), music volume settings are respected and sound effects work in-game.

Example games: Bard's Gold, Super Star Path, maybe others.

**Comment by Oxalin** [comment] 2015-12-08 06:27
This is a duplicate of issue #18.

Have you tried setting STEAM_RUNTIME=0? That way, the Steam runtime libraries are skipped and your system's provided libraries are used instead.

Since the latest OpenAL is compatible (no ABI changes) with the version provided by Steam, you should have no problem using a more up-to-date version. As an alternative option to disabling Steam's runtime libraries, you could delete the provided files in Steam's runtime folders (thus, Steam and games will look in the system folders) or symlink your system files in those folders if you don't want to override all Steam's runtime libraries.

That said, maybe Steam should modify some aspects of its policy about updating its runtime libraries when nothing can be broken (and even more when they are fixed or improved).

**Comment by adolson** [comment] 2015-12-08 08:58
I don't like the idea of skipping the Steam Runtime entirely, and as I said in the original post, I did delete the the OpenAL lib included in the runtime in order to get it to work.

What I would LIKE to see, is some kind of advanced override mechanism built into Steam for all the libs in the Steam Runtime, to allow advanced users to toggle each on/off on a per-game basis. I dunno how realistic such a feature is, as it'd honestly be better if everything Just Worked(tm).

**Comment by Oxalin** [comment] 2015-12-09 04:06
Maybe Wine could be a model in that way: there are ways to replace some librairies if wanted. Simple and quite efficient. That would need to be done as a power user though or in some advanced settings. Not a bad idea in my opinion. This should be a feature request.

**Comment by kisak-valve** [comment] 2018-11-30 14:37
Since this issue report was opened Steam has changed how it handles the Steam runtime so that it prefers system libraries over the steam runtime variants. If anyone is still experiencing this issue on an up to date system, please open a new issue report.

**Closed by kisak-valve** 2018-11-30 14:37 UTC
Labels: reviewed, runtime
