### ISSUE TITLE
Video playback seems not to stop when Steam Client window is closed (i can hear the audio of the video playback still running)

### ISSUE THREAD

**Issue by mbcraft** [ValveSoftware/steam-for-linux#10792] opened 2024-04-18 19:55 UTC
#### Your system information

* Steam client version (build number or date): 1709846872
* Distribution (e.g. Ubuntu): Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/15029894/steam-logs.tar.gz)`]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:

I was expecting when i closed the Steam Client windows, that any video playback stops. What happens instead is that the video playback still runs since i can hear its audio.

#### Steps for reproducing this issue:

1. Start playback of a video advertising in a videogame page
2. Close the Steam Client window

**Comment by kisak-valve** [comment] 2024-04-18 20:30
Hello @mbcraft, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #5234.

**Closed by kisak-valve** 2024-04-18 20:30 UTC
