### ISSUE TITLE
Upon opening steam, SDL apps (aka everything) no longer see DS4 controllers

### ISSUE THREAD

**Issue by mwales** [ValveSoftware/steam-for-linux#5868] opened 2018-10-31 05:57 UTC
#### Your system information

* Steam client version (build number or date): Oct 31 2018 001647
* Distribution (e.g. Ubuntu): Ubuntu 18.04.1
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam seems to be able to recognize the Dualshock 4, but not working in Rocket League.  During troubleshooting I recognize that the controllers would sometimes appear in sdl2-jstest for a few seconds, and then disappear.  In Dead Cells, the DS4 will work for a second or two after plugging in, then quit.  Most of my DS4 problems started after upgrade to 18.04, I've read about issues with SDL and the DS4, was hoping issues had resolved by now.

#### Steps for reproducing this issue:

1. Have steam closed.
2. Play SDL2 game, controller works fine
3. Open terminal, watch -n 1 "./sdl-jstest --list"
4. Open another terminal, watch -n 1 "sdl2-jstest --list"
5. Plug in DS4 controller.  sd1 shows 1 controller, sdl2 shows 1 controller, and 1 motion controller

```
Every 1.0s: ./sdl-jstest --list 

Found 1 joystick(s)

Joystick Name:     'Sony Computer Entertainment Wireless Controller'
Joystick Number:    0
Number of Axes:     6
Number of Buttons: 13
Number of Hats:     1
Number of Balls:    0
```
```
Every 1.0s: ./sdl2-jstest --list 

Found 2 joystick(s)

Joystick Name:     'Sony Computer Entertainment Wireless Controller'
Joystick GUID:     030000004c050000c405000011810000
Joystick Number:    0
Number of Axes:     6
Number of Buttons: 13
Number of Hats:     1
Number of Balls:    0
GameController:
  Name:    'PS4 Controller'
  Mapping: '030000004c050000c405000011810000,PS4 Controller,a:b0,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b11,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b12,righttr
igger:a5,rightx:a3,righty:a4,start:b9,x:b3,y:b2,'

Joystick Name:     'Sony Computer Entertainment Wireless Controller Motion Sensors'
Joystick GUID:     030000004c050000c405000011810000
Joystick Number:    1
```
6. At this point I can play non-Steam SDL game, run the test, DS4 works
7. Open Steam

After Steam is opened, both the sdl-test terminals show that there are no controllers attached anymore to the system.  DS4 controller works in Big Picture mode.  No DS4 support in Rocket League or Dead Cells.

I've tried disabling gamepad and Playstation controller support in Steam settings, doesn't seem to effect Steam or my issue.

**Comment by kisak-valve** [comment] 2018-10-31 12:36
Hello @mwales, this reads like a duplicate of earlier issue reports. Off hand I'm going to point to #5620 and #5036.

Closing in favor of the existing issue reports.

**Closed by kisak-valve** 2018-10-31 12:36 UTC
