### ISSUE TITLE
Steam not launching on Arch Linux

### ISSUE THREAD

**Issue by wantija** [ValveSoftware/steam-for-linux#9818] opened 2023-07-08 04:46 UTC
#### Your system information

* Steam client version (build number or date): Jul  7 2023
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes 
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11988501/steam-logs.tar.gz)

1. update steam to latest beta
2. launch steam
3. crashes

Happens on both beta and stable channels

**Comment by toshokanneko** [comment] 2023-07-08 07:29
Had the same issue after an update yesterday. Downgrading `libgudev` and `lib32-libgudev` to version `237-2` as mentioned in the following thread fixed it for me => https://github.com/ValveSoftware/steam-for-linux/issues/9805

**Comment by kisak-valve** [comment] 2023-07-08 12:56
Hello @wantija, as @toshokanneko noted, this is most likely a duplicate of #9805. Can you check if installing one of the packages mentioned in https://github.com/ValveSoftware/steam-for-linux/issues/9805#issuecomment-1626486059 gets the Steam client running again for you?

**Comment by wantija** [comment] 2023-07-08 14:40
Hi, yes installing lib32-libudev0-shim fixes the problem for me.
Jul 8, 2023, 08:56 by ***@***.***:

**Comment by kisak-valve** [comment] 2023-07-08 14:43
Thanks for checking. Closing as a duplicate of #9805.

**Closed by kisak-valve** 2023-07-08 14:43 UTC
Labels: duplicate, Need Retest, Distro Family: Arch
