### ISSUE TITLE
Steam crashes at launch (since last update or the one before) on Kubuntu 19.04

### ISSUE THREAD

**Issue by omen23** [ValveSoftware/steam-for-linux#6297] opened 2019-05-31 12:52 UTC
#### Your system information

* Steam client version (build number or date): May 22 2019 21:55:25
* Distribution (e.g. Ubuntu): Kubuntu 
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam UI is expected to launch.
```
$ steam
Running Steam on ubuntu 19.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
[2019-05-31 14:48:38] Startup - updater built May 22 2019 21:55:25
[2019-05-31 14:48:38] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
SteamUpdateUI: An X Error occurred
X Error of failed request:  GLXBadContext
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  42
xerror_handler: X failed, continuing
Major opcode of failed request:  151 (GLX)
Minor opcode of failed request:  6 (X_GLXIsDirect)
Serial number of failed request:  43
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2019-05-31 14:48:38] Checking for update on startup
[2019-05-31 14:48:38] Checking for available updates...
[2019-05-31 14:48:38] Downloading manifest: client-download.steampowered.com/client/steam_client_publicbeta_ubuntu12
[2019-05-31 14:48:38] Download skipped by HTTP 304 Not Modified
[2019-05-31 14:48:38] Nothing to do
[2019-05-31 14:48:38] Verifying installation...
[2019-05-31 14:48:38] Performing checksum verification of executable files
[2019-05-31 14:48:39] Verification complete
```
I ran the script file in the `.steam` folder and got a little more debug output:
```
../.steam/steam.sh
rm: cannot remove '/home/dave/.steam/steam': Is a directory
rm: cannot remove '/home/dave/.steam/bin': Is a directory
Running Steam on ubuntu 19.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
[2019-05-31 14:36:43] Startup - updater built May 22 2019 21:55:25
[2019-05-31 14:36:43] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Installing breakpad exception handler for appid(steam)/version(1558567098)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
SteamUpdateUI: An X Error occurred
X Error of failed request:  GLXBadContext
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  42
xerror_handler: X failed, continuing
Major opcode of failed request:  151 (GLX)
Minor opcode of failed request:  6 (X_GLXIsDirect)
Serial number of failed request:  43
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
Installing breakpad exception handler for appid(steam)/version(1558567098)
[2019-05-31 14:36:43] Checking for update on startup
[2019-05-31 14:36:43] Checking for available updates...
[2019-05-31 14:36:43] Downloading manifest: client-download.steampowered.com/client/steam_client_publicbeta_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1558567098)
[2019-05-31 14:36:43] Download skipped by HTTP 304 Not Modified
[2019-05-31 14:36:43] Nothing to do
[2019-05-31 14:36:43] Verifying installation...
[2019-05-31 14:36:43] Performing checksum verification of executable files
[2019-05-31 14:36:43] Verification complete
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  151
Serial number of failed request:  49
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151
Value in failed request:  0x0
Serial number of failed request:  48
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  151
Serial number of failed request:  50
xerror_handler: X failed, continuing
crash_20190531143643_1.dmp[10342]: Uploading dump (out-of-process)
/tmp/dumps/crash_20190531143643_1.dmp
../.steam/steam.sh: line 712: 10303 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20190531143643_1.dmp[10342]: Finished uploading minidump (out-of-process): success = yes
crash_20190531143643_1.dmp[10342]: response: CrashID=bp-3a800d2d-efa8-448c-ad84-734242190531
crash_20190531143643_1.dmp[10342]: file ''/tmp/dumps/crash_20190531143643_1.dmp'', upload yes: ''CrashID=bp-3a800d2d-efa8-448c-ad84-734242190531'
```
#### Steps for reproducing this issue:
1. Try to launch steam via terminal or startmenu

 installed nvidia driver is 418.67 and everythings in working condition

**Comment by omen23** [comment] 2019-05-31 15:05
deleted all steam folder and uninstalled packages... 

now
```
$ steam
Running Steam on ubuntu 19.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1556574584)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Installing breakpad exception handler for appid(steam)/version(1556574584)
Installing breakpad exception handler for appid(steam)/version(1556574584)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  151
Serial number of failed request:  49
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151
Value in failed request:  0x0
Serial number of failed request:  48
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  151
Serial number of failed request:  50
xerror_handler: X failed, continuing
crash_20190531170345_1.dmp[8454]: Uploading dump (out-of-process)
/tmp/dumps/crash_20190531170345_1.dmp
/home/dave/.local/share/Steam/steam.sh: line 906:  8415 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20190531170345_1.dmp[8454]: Finished uploading minidump (out-of-process): success = yes
crash_20190531170345_1.dmp[8454]: response: CrashID=bp-01a7858f-8078-429e-be77-1bcba2190531
crash_20190531170345_1.dmp[8454]: file ''/tmp/dumps/crash_20190531170345_1.dmp'', upload yes: ''CrashID=bp-01a7858f-8078-429e-be77-1bcba2190531''
```

**Comment by kisak-valve** [comment] 2019-05-31 16:06
Hello @omen23, this is an nVidia driver issue which is being tracked at #5778. The .deb driver package provided by nVidia does not have 32 bit userspace support. If it is available to you, add the `libnvidia-gl-418:i386` package, which may involve adding the [Proprietary GPU Drivers PPA](https://github.com/ValveSoftware/steam-for-linux/issues/5778#issuecomment-478464184).

Closing as a duplicate of #5778.

**Closed by kisak-valve** 2019-05-31 16:06 UTC

**Comment by omen23** [comment] 2019-05-31 17:01
```
sudo apt install libnvidia-gl-418:i386
[sudo] password for dave: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  cuda-command-line-tools-10-0 cuda-compiler-10-0 cuda-cublas-dev-10-0 cuda-cudart-10-0 cuda-cudart-dev-10-0 cuda-cufft-10-0 cuda-cufft-dev-10-0
  cuda-cuobjdump-10-0 cuda-cupti-10-0 cuda-curand-10-0 cuda-curand-dev-10-0 cuda-cusolver-10-0 cuda-cusolver-dev-10-0 cuda-cusparse-10-0
  cuda-cusparse-dev-10-0 cuda-documentation-10-0 cuda-driver-dev-10-0 cuda-gdb-10-0 cuda-gpu-library-advisor-10-0 cuda-libraries-10-0
  cuda-libraries-dev-10-0 cuda-memcheck-10-0 cuda-misc-headers-10-0 cuda-npp-10-0 cuda-npp-dev-10-0 cuda-nsight-10-0 cuda-nsight-compute-10-0 cuda-nvcc-10-0
  cuda-nvdisasm-10-0 cuda-nvgraph-10-0 cuda-nvgraph-dev-10-0 cuda-nvjpeg-10-0 cuda-nvjpeg-dev-10-0 cuda-nvml-dev-10-0 cuda-nvprof-10-0 cuda-nvprune-10-0
  cuda-nvrtc-10-0 cuda-nvrtc-dev-10-0 cuda-nvtx-10-0 cuda-nvvp-10-0 cuda-samples-10-0 cuda-toolkit-10-0 cuda-tools-10-0 cuda-visual-tools-10-0 freeglut3
  freeglut3-dev libnvidia-cfg1-418 libnvidia-decode-418 libnvidia-encode-418 libnvidia-fbc1-418 libxmu-dev libxmu-headers nvidia-compute-utils-418
  nvidia-dkms-418 nvidia-kernel-common-418 nvidia-kernel-source-418 nvidia-modprobe nvidia-prime nvidia-settings nvidia-utils-418 screen-resolution-extra
  xserver-xorg-video-nvidia-418
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  cuda-10-0 cuda-demo-suite-10-0 cuda-drivers cuda-runtime-10-0 libnvidia-gl-418 libnvidia-ifr1-418 nvidia-driver-418
The following NEW packages will be installed:
  libnvidia-gl-418:i386
0 upgraded, 1 newly installed, 7 to remove and 11 not upgraded.
Need to get 17,0 MB of archives.
After this operation, 107 MB disk space will be freed.
Do you want to continue? [Y/n] n
```
any way of installing it without breaking my CUDA 10 + 418.67 installation?

**Comment by omen23** [comment] 2019-05-31 17:10
```
The following packages have unmet dependencies:
 libnvidia-gl-418 : Breaks: libnvidia-gl-418:i386 (!= 418.67-0ubuntu1) but 418.56-0ubuntu1 is installed
 libnvidia-gl-418:i386 : Breaks: libnvidia-gl-418 (!= 418.56-0ubuntu1) but 418.67-0ubuntu1 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
dave@dave-desktop:~/Downloads$ sudo apt --fix-broken install 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  libnvidia-gl-418:i386
0 upgraded, 0 newly installed, 1 to remove and 11 not upgraded.
2 not fully installed or removed.
After this operation, 70,8 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 310163 files and directories currently installed.)
Removing libnvidia-gl-418:i386 (418.56-0ubuntu1) ...
Setting up libnvidia-gl-418:amd64 (418.67-0ubuntu1) ...
Processing triggers for libc-bin (2.29-0ubuntu2) ...
dave@dave-desktop:~/Downloads$ 
```
there seems no way .. around even i can get the 32 bit libary not for 418.67

**Comment by omen23** [comment] 2019-05-31 17:38
I rather use a working cuda 10 with 418.67 .. and wait for valve to fix this .. i mean come on bros ...

**Comment by jblasz** [comment] 2019-10-11 19:06
Any progress?

Cuda is essential to many. So until a fix, steam is unusable forever to us.

**Comment by varishtsg** [comment] 2019-11-01 05:28
Facing the same issue after I upgraded my cuda install for tensorflow last night. Valve really needs to fix this.

**Comment by HackyRoot** [comment] 2019-11-27 11:55
It seems like we all been following the installation guide from the TensorFlow website and it's causing the issue.

**Comment by HaraldKorneliussen** [comment] 2019-11-30 14:00
I just followed the installation guide from Nvidia.
I get that there are steam games which can't handle 64 bit support, but can't the steam client at least do it?

**Comment by mickeyouyou** [comment] 2020-02-12 07:15
fixed issue by reinstall nvidia driver and add 32 bit support .

**Comment by rudylyh** [comment] 2020-05-07 17:27
> Any progress?
> 
> Cuda is essential to many. So until a fix, steam is unusable forever to us.

Tired of trying out all these nvidia fixing things, I choose to use the flatpak version steam.
```
$ sudo apt install flatpak
$ sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
$ sudo flatpak install flathub com.valvesoftware.Steam
$ flatpak run com.valvesoftware.Steam
```
Everything done in 15 mins, easy and smooth.

**Comment by blacar** [comment] 2020-05-17 17:51
NOTE that in my case this was related the CUDA-problem

CUDA repos has alternative versions for Nvidia drivers and these dont offer i386 versions so it created a dependency problem.

The solution is to disable CUDA repos.

Please check here: NVIDIA 440.64 32-bit libraries package breaks 64-bit driver package

Now the problem is when you want to have CUDA and Steam at the same time. Thats a different problem.

**Comment by ohyonghao** [comment] 2020-06-25 02:41
Same issue, and same conclusion, CUDA repos does not support i386, so it will remain broken until the ppa has the 450 32bit libraries if we want to run CUDA-11

**Comment by AlexisTM** [comment] 2020-07-22 18:06
Just 

> > Any progress?
> > Cuda is essential to many. So until a fix, steam is unusable forever to us.
> 
> Tired of trying out all these nvidia fixing things, I choose to use the flatpak version steam.
> 
> ```
> $ sudo apt install flatpak
> $ sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
> $ sudo flatpak install flathub com.valvesoftware.Steam
> $ flatpak run com.valvesoftware.Steam
> ```
> 
> Everything done in 15 mins, easy and smooth.

Thanks!!

**Comment by Jtrei** [comment] 2020-10-10 23:04
> > Any progress?
> > Cuda is essential to many. So until a fix, steam is unusable forever to us.
> 
> Tired of trying out all these nvidia fixing things, I choose to use the flatpak version steam.
> 
> ```
> $ sudo apt install flatpak
> $ sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
> $ sudo flatpak install flathub com.valvesoftware.Steam
> $ flatpak run com.valvesoftware.Steam
> ```
> 
> Everything done in 15 mins, easy and smooth.

This worked for me as well, thanks!

**Comment by LusKrew** [comment] 2020-11-27 13:26
> > Any progress?
> > Cuda is essential to many. So until a fix, steam is unusable forever to us.
> 
> Tired of trying out all these nvidia fixing things, I choose to use the flatpak version steam.
> 
> ```
> $ sudo apt install flatpak
> $ sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
> $ sudo flatpak install flathub com.valvesoftware.Steam
> $ flatpak run com.valvesoftware.Steam
> ```
> 
> Everything done in 15 mins, easy and smooth.

I'm still getting the same error even with flatpak !!! : 


```
flatpak run com.valvesoftware.Steam
https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions
Overriding TZ to Asia/Famagusta
Running Steam on org.freedesktop.platform 20.08.1.2 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/Johnny/.local/share/Steam/ubuntu12_32/steam
[2020-11-27 16:54:15] Startup - updater built Oct 28 2020 23:34:22
Installing breakpad exception handler for appid(steam)/version(1603992987)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
SteamUpdateUI: An X Error occurred
X Error of failed request:  GLXBadContext
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  45
xerror_handler: X failed, continuing
Major opcode of failed request:  151 (GLX)
Minor opcode of failed request:  6 (X_GLXIsDirect)
Serial number of failed request:  46
xerror_handler: X failed, continuing
```

**Comment by CrackerHax** [comment] 2021-09-15 01:45
> > Any progress?
> > Cuda is essential to many. So until a fix, steam is unusable forever to us.
> 
> Tired of trying out all these nvidia fixing things, I choose to use the flatpak version steam.
> 
> ```
> $ sudo apt install flatpak
> $ sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
> $ sudo flatpak install flathub com.valvesoftware.Steam
> $ flatpak run com.valvesoftware.Steam
> ```
> 
> Everything done in 15 mins, easy and smooth.

Still a problem and this fixed it, except took 3 minutes.
