### ISSUE TITLE
[TF2] Extremely high RAM/SWAP usage

### ISSUE THREAD

**Issue by fabledpig** [ValveSoftware/steam-for-linux#3068] opened 2013-12-29 22:24 UTC
TF2 on Windows uses about 680Mb RAM. On Linux it uses about 2.8GB!!! It's a huge memory usage. That's why it's loading so much, it has to swap all the time!

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x17
    CPU Stepping:  0xa
    CPU Type:  0x0
    Speed:  2926 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (32 bit)
    Kernel Name:  Linux
    Kernel Version:  3.12.6-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11405000
    X Window Manager:  bspwm
    Steam Runtime Version:  steam-runtime-release_2013-10-23

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 650 Ti BOOST/PCIe/SSE2

    Driver Version:  4.4.0 NVIDIA 331.20
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x11c2
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 19.21" x 12.01"  (22.64" diag)
                                            48.8cm x 30.5cm  (57.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: VIA VT1708S

Memory:
    RAM:  2019 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  79516 Mb
    Largest Free Hard Disk Block:  13122 Mb

Installed software:

Recent Failure Reports:
    Sun Dec 29 22:02:21 2013 GMT: file ''/tmp/dumps/crash_20131229230201_4.dmp'', upload yes: ''CrashID=bp-8c2830f8-e2af-4fe0-a61a-ca18b2131229''
```

**Comment by RamchandraApte** [comment] 2015-01-14 16:37
I just did a fresh install of (K)ubuntu 14.10 and all these problems have gone away. I can alt-tab easily and TF2 doesn't strain other applications at all. And memory usage has gone to 800 megabytes.
Did some change happen on the driver side or Source engine side?

**Comment by silverhammermba** [comment] 2015-01-17 23:59
Confirmed! Memory usage is way down on my Linux box: 1.2 GB memory usage on very high texture setting.

**Comment by muthaber** [comment] 2017-09-27 21:32
I have same problem exactly with RAM 4GB on Debian Buster 64bit, it's eating all RAM, and the game is laggy because RAM is not enough, swap is slow, I tried to disable swap, but still same problem, this happens with low and high settings, all are same.
Please fix it.
Thanks

**Comment by kisak-valve** [comment] 2017-09-27 22:34
Hello @muthaber, if you're using intel graphics, then this is more or less the current expected behavior. If this is the case, then you may be seeing the issue being tracked at https://github.com/ValveSoftware/Source-1-Games/issues/2212 or https://github.com/ValveSoftware/Source-1-Games/issues/2234, otherwise, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games/) issue tracker.

Closing as the original issue reported here appears to have been resolved some time ago.

**Closed by kisak-valve** 2017-09-27 22:34 UTC
Labels: MOVED: Team Fortress 2, reviewed
