### ISSUE TITLE
Steam crashes on mesa/nouveau 18.0.5 and NV4B

### ISSUE THREAD

**Issue by alex19712207** [ValveSoftware/steam-for-linux#5980] opened 2018-12-23 14:44 UTC
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a 

- steam_client_ubuntu12Gist](https://gist.github.com/)

1. #### Steps for reproducing this issue:steam_client_ubuntu12
2. ubuntu 18.04.01
3. no
4 yes
5 logs  - https://drive.google.com/file/d/1uB3u1Zw4txJrqmBPqtKA-LiqSMFjJ5yL/view?usp=sharing

**Comment by kisak-valve** [comment] 2018-12-23 19:03
Hello @alex19712207, does any 32 bit opengl application like `glxinfo` from `mesa-utils:i386` work?

**Comment by kisak-valve** [comment] 2018-12-25 21:33
What model CPU do you have? Does it support SSE3 (issue #5164)? If you have a `~/.steam/error.log` and a corresponding minidump in `/tmp/dumps/`, please throw them in an archive and drag and drop the archive into the comment box.

**Comment by alex19712207** [comment] 2018-12-26 19:15
Hello, my model of CPU ATLON 5000+ 64bit. I attach the computer data in the file. I attach dump and other errors (logs) I have managed to find. Thanks in advance.
[ALEX.txt](https://github.com/ValveSoftware/steam-for-linux/files/2710740/ALEX.txt)

[alex_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/2710741/alex_log.txt)

[crash_20181226172040_1.zip](https://github.com/ValveSoftware/steam-for-linux/files/2710743/crash_20181226172040_1.zip)
[alex_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/2710747/alex_log.txt)



[error.log](https://github.com/ValveSoftware/steam-for-linux/files/2710748/error.log)

**Comment by kisak-valve** [comment] 2018-12-26 19:36
For reference, the attached minidump is a SIGSEGV in nouveau_dri.so (part of the video driver).

**Comment by alex19712207** [comment] 2018-12-26 19:38
[computer-data.txt](https://github.com/ValveSoftware/steam-for-linux/files/2710765/computer-data.txt)
[crash_20181226172040_1.zip](https://github.com/ValveSoftware/steam-for-linux/files/2710766/crash_20181226172040_1.zip)
[bootstrap_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/2710776/bootstrap_log.txt)
[crash_20181226172040_1.zip](https://github.com/ValveSoftware/steam-for-linux/files/2710778/crash_20181226172040_1.zip)
[alex_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/2710779/alex_log.txt)
[assert_20181226213021_25.zip](https://github.com/ValveSoftware/steam-for-linux/files/2710780/assert_20181226213021_25.zip)

**Comment by alex19712207** [comment] 2018-12-26 19:47
Thank you for your answer. Is it ok that it shuts down after login before the game initializing? There is no pointed driver in the repository Ubuntu 18.04. But I will try the alternative way of installing.Has the video driver got anything to the start of Steam client before game download?

**Comment by kisak-valve** [comment] 2018-12-26 20:00
Steam is a basic 32 bit opengl application and needs about OpenGL 2.0 to run. In theory it should be 
able to work on your system.

The nVidia 304.137 driver is the last of an EoL'd series, and was compatible with kernels up to 4.12. It's very possible that it also won't play nicely with Ubuntu 18.04's 4.15 kernel and was intentionally removed from Ubuntu.

**Comment by imirkin** [comment] 2018-12-27 16:22
[nouveau developer here]

First off, try to get the NVIDIA proprietary driver to work -- it will be MUCH more reliable than nouveau on pre-G80 hardware. Especially for software designed after the cards' heyday.

kisask did bring up this issue in the IRC channel, and I was able to reproduce with a NV34 I had plugged in. This is the same issue as https://bugs.freedesktop.org/show_bug.cgi?id=102349, with the important difference that I was able to reproduce myself.

I have some candidate fixes for this and a handful of other issues I discovered when trying to test these fixes, which I will hopefully be able to push out in the next few days. At least in my setup, with the fixes, steam is able to make it into the main application with the NV34 (but all the graphics are missing due to lack of NPOT support -- NV4x would be able to work with those).

**Comment by imirkin** [comment] 2018-12-31 06:42
I've just pushed some code to mesa master which should make the steam client load now without any obvious issues. This was tested on a Quadro FX 3450 (NV42), which is relatively similar to the NV4B hardware. Not sure how you'd get that onto your system, perhaps there are some package providers that provide up-to-date builds.

Should show up in Mesa 19.0, but if I can get other people to test, I could recommend the patches for inclusion into 18.3.x.

**Comment by kisak-valve** [comment] 2018-12-31 13:41
The next build of mesa in oibaf PPA should be a good test case.

**Comment by kisak-valve** [comment] 2019-01-02 02:34
@alex19712207, [Oibaf PPA](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) should now have the fixes. Please retest with mesa from there.

**Comment by kisak-valve** [comment] 2019-02-08 13:48
Closing as fixed in the driver, thanks @imirkin.

**Closed by kisak-valve** 2019-02-08 13:48 UTC
Labels: Need Retest
