### ISSUE TITLE
Tray icon doesn't do anything anymore.

### ISSUE THREAD

**Issue by Frojin** [ValveSoftware/steam-for-linux#4889] opened 2017-03-09 07:52 UTC
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Ubuntu 16.04 LTS
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
The steam icon on the tray (unity panel) doesn't show options anymore it just shows an empty list.It didn't do these when I just joined the steam beta, it was a bit after  that.
![screenshot from 2017-03-09 09-47-33](https://cloud.githubusercontent.com/assets/17342778/23740800/f5b31588-04ad-11e7-8323-cd8477799487.png)
 [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. join steam beta
2. ???
3. now it's there

**Comment by kisak-valve** [comment] 2017-03-09 14:04
Hello @Frojin, Does the stable client also shot this behavior? Can you please confirm if you are affected by #4795 (there is a summary at https://github.com/ValveSoftware/steam-for-linux/issues/4795#issuecomment-271268063)?

**Comment by Frojin** [comment] 2017-03-09 16:27
I don't know if the stable client also shot this behavior, but that fixes it actually, thanks

**Comment by kisak-valve** [comment] 2017-03-09 16:37
Thanks for testing, closing as a duplicate of #4795.

**Closed by kisak-valve** 2017-03-09 16:37 UTC
Labels: Steam client
