### ISSUE TITLE
Steam Client Tabs are Blank

### ISSUE THREAD

**Issue by miakramer** [ValveSoftware/steam-for-linux#8047] opened 2021-09-08 15:30 UTC
#### Your system information

* Steam client version (build number or date): Built Jul 20 2021, 22:25:57, Api v020, package versions 1626824053
* Distribution (e.g. Ubuntu): Manjaro 21.1.2 64-bit, using Gnome with Wayland
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When starting the Steam client, most windows are black on the interior. This includes Store, Library, Community and my profile, but not Settings or About Steam.

When running Steam from the command line, this is the output:

<details>

```
Running Steam on manjarolinux 21.1.2 64-bit
STEAM_RUNTIME is enabled automatically
Steam runtime environment up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/data/Steam/ubuntu12_32/steam --version
[2021-09-08 08:23:37] Startup - updater built Jul 20 2021 22:25:51
Installing breakpad exception handler for appid(steam)/version(1626824053)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2021-09-08 08:23:37] Loading cached metrics from disk (/data/Steam/package/steam_client_metrics.bin)
[2021-09-08 08:23:37] Using the following download hosts for Public, Realm steamglobal
[2021-09-08 08:23:37] 1. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-09-08 08:23:37] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-09-08 08:23:37] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1626824053)
[2021-09-08 08:23:37] Checking for update on startup
[2021-09-08 08:23:37] Checking for available updates...
[2021-09-08 08:23:37] Downloading manifest: https://cdn.akamai.steamstatic.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1626824053)
[2021-09-08 08:23:38] Download skipped: /client/steam_client_ubuntu12 version 1626824053, installed version 1626824053, existing pending version 0
[2021-09-08 08:23:38] Nothing to do
[2021-09-08 08:23:38] Verifying installation...
[2021-09-08 08:23:38] Performing checksum verification of executable files
[2021-09-08 08:23:39] Verification complete
Loaded SDL version 2.0.15-6655637

(steam:115850): Gtk-WARNING **: 08:23:39.408: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Matcha-dark-sea/gtk-2.0/main.rc:1113: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Matcha-dark-sea/gtk-2.0/apps.rc:91: error: unexpected identifier 'direction', expected character '}'
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  12
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  13
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  14
xerror_handler: X failed, continuing
Installing breakpad exception handler for appid(steam)/version(1626824053)
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language
Installing breakpad exception handler for appid(steam)/version(1626824053)
Installing breakpad exception handler for appid(steam)/version(1626824053)
Installing breakpad exception handler for appid(steam)/version(1626824053)
Installing breakpad exception handler for appid(steam)/version(1626824053)
Installing breakpad exception handler for appid(steam)/version(1626824053)
Installing breakpad exception handler for appid(steam)/version(1626824053)
Installing breakpad exception handler for appid(steam)/version(1626824053)
Installing breakpad exception handler for appid(steam)/version(1626824053)
Installing breakpad exception handler for appid(steam)/version(1626824053)
Installing breakpad exception handler for appid(steam)/version(1626824053)
CAppInfoCacheReadFromDiskThread took 29 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1626824053)
Installing breakpad exception handler for appid(steam)/version(1626824053)
CApplicationManagerPopulateThread took 102 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Installing breakpad exception handler for appid(steam)/version(1626824053)
Installing breakpad exception handler for appid(steam)/version(1626824053)
Proceed to auto login
Installing breakpad exception handler for appid(steam)/version(1626824053)
Installing breakpad exception handler for appid(steam)/version(1626824053)
Opted-in Controller Mask for AppId 0: 4

(steam:115850): Gtk-WARNING **: 08:23:40.111: gtk_disable_setlocale() must be called before gtk_init()
local (potentially out of sync) copy of roaming config loaded - 3476 bytes.
Installing breakpad exception handler for appid(steam)/version(1626824053)
Installing breakpad exception handler for appid(steam)/version(1626824053)
Installing breakpad exception handler for appid(steam)/version(1626824053)
roaming config store loaded successfully - 3476 bytes.
migrating temporary roaming config store
BRefreshApplicationsInLibrary 1: 3ms
Installing breakpad exception handler for appid(steam)/version(1626824053)
Installing breakpad exception handler for appid(steam)/version(1626824053)
Failed to init SteamVR because it isn't installed
ExecCommandLine: "'/data/Steam/ubuntu12_32/steam' '--version'"
System startup time: 1.97 seconds
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language
Installing breakpad exception handler for appid(steam)/version(1626824053)
Installing breakpad exception handler for appid(steam)/version(1626824053)
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language
```

That last error seems to repeat every so often. 

</details>

#### Steps for reproducing this issue:

1. Open Steam for Linux

**Comment by kisak-valve** [comment] 2021-09-08 15:49
Hello @miakramer, `./steamwebhelper: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language` is the key detail in your log, and tells us that you've encountered #7935. The issue should already be resolved in Steam's client beta. Please opt into Steam's beta.

Closing as a duplicate of #7935.

**Closed by kisak-valve** 2021-09-08 15:49 UTC
