### ISSUE TITLE
Linux HIDPI Fix needed. Nearly 3 year old issue.

### ISSUE THREAD

**Issue by DeathKhan** [ValveSoftware/steam-for-linux#4498] opened 2016-06-15 04:22 UTC
#### System information:

* Distribution: Arch (based on latest ubuntu port)
* Opted into Steam client beta?: [Yes] 
* Have you checked for system updates?: [Yes]

#### Description:

Steam is the only package as of 2016 that I have used that does not render for HIDPI screens. Almost all modern laptops and monitors are now HIDPI, as 1080 is being phased out. This needs a fix, its been 3 years. I have attempted to use the themeing system to fix the issue, scaling all UI components, but their size in the program is predefined and thus only portions of the scaled UI components are shown. Themeing does not fix the issue.

#### Steps for reproducing this issue:

1. Get steam on any linux distro
2. Use a HIDPI monitor

**Comment by Tele42** [comment] 2016-06-15 11:12
Duplicate of #3492.

**Comment by gdrewb-valve** [comment] 2016-06-15 15:55
Closing duplicate.

**Closed by gdrewb-valve** 2016-06-15 15:55 UTC
