### ISSUE TITLE
webhelper fails to start with todays build.

### ISSUE THREAD

**Issue by YellowOnion** [ValveSoftware/steam-for-linux#8052] opened 2021-09-10 09:04 UTC
#### Your system information

* Steam client version (build number or date): 
![image](https://user-images.githubusercontent.com/364160/132828655-84f795a2-4f8f-4228-95d6-71dba4dc405f.png)

* Distribution (e.g. Ubuntu): NixOS 21.05
* Opted into Steam client beta?: No
* Have you checked for system updates?:  No

#### Please describe your issue in as much detail as possible:
![image](https://user-images.githubusercontent.com/364160/132828716-254f99c0-cbbd-405b-b412-7a21fab28367.png)

```
<snip>
Runtime for steamwebhelper: defaulting to /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
+ exec /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy.sh --unpack-dir=/home/daniel/.local/share/Steam/ubuntu12_64 --runtime=steam-runtime-heavy -- ./steamwebhelper -lang=en_US -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steampid=1728128 -buildid=1631237534 -steamid=76561197976113747 -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steamuniverse=Public -realm=Global -clientui=/home/daniel/.local/share/Steam/clientui --enable-blink-features=ResizeObserver,Worklet,AudioWorklet --enable-media-stream --enable-smooth-scrolling --password-store=basic --log-file=/home/daniel/.local/share/Steam/logs/cef_log.txt --disable-quick-menu
Runtime for steamwebhelper: defaulting to /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
+ exec /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy.sh --unpack-dir=/home/daniel/.local/share/Steam/ubuntu12_64 --runtime=steam-runtime-heavy -- ./steamwebhelper -lang=en_US -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steampid=1728128 -buildid=1631237534 -steamid=76561197976113747 -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steamuniverse=Public -realm=Global -clientui=/home/daniel/.local/share/Steam/clientui --enable-blink-features=ResizeObserver,Worklet,AudioWorklet --enable-media-stream --enable-smooth-scrolling --password-store=basic --log-file=/home/daniel/.local/share/Steam/logs/cef_log.txt --disable-quick-menu
Runtime for steamwebhelper: defaulting to /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
+ exec /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy.sh --unpack-dir=/home/daniel/.local/share/Steam/ubuntu12_64 --runtime=steam-runtime-heavy -- ./steamwebhelper -lang=en_US -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steampid=1728128 -buildid=1631237534 -steamid=76561197976113747 -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steamuniverse=Public -realm=Global -clientui=/home/daniel/.local/share/Steam/clientui --enable-blink-features=ResizeObserver,Worklet,AudioWorklet --enable-media-stream --enable-smooth-scrolling --password-store=basic --log-file=/home/daniel/.local/share/Steam/logs/cef_log.txt --disable-quick-menu
Runtime for steamwebhelper: defaulting to /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
+ exec /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy.sh --unpack-dir=/home/daniel/.local/share/Steam/ubuntu12_64 --runtime=steam-runtime-heavy -- ./steamwebhelper -lang=en_US -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steampid=1728128 -buildid=1631237534 -steamid=76561197976113747 -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steamuniverse=Public -realm=Global -clientui=/home/daniel/.local/share/Steam/clientui --enable-blink-features=ResizeObserver,Worklet,AudioWorklet --enable-media-stream --enable-smooth-scrolling --password-store=basic --log-file=/home/daniel/.local/share/Steam/logs/cef_log.txt --disable-quick-menu
Runtime for steamwebhelper: defaulting to /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
+ exec /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy.sh --unpack-dir=/home/daniel/.local/share/Steam/ubuntu12_64 --runtime=steam-runtime-heavy -- ./steamwebhelper -lang=en_US -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steampid=1728128 -buildid=1631237534 -steamid=76561197976113747 -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steamuniverse=Public -realm=Global -clientui=/home/daniel/.local/share/Steam/clientui --enable-blink-features=ResizeObserver,Worklet,AudioWorklet --enable-media-stream --enable-smooth-scrolling --password-store=basic --log-file=/home/daniel/.local/share/Steam/logs/cef_log.txt --disable-quick-menu
Runtime for steamwebhelper: defaulting to /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
+ exec /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy.sh --unpack-dir=/home/daniel/.local/share/Steam/ubuntu12_64 --runtime=steam-runtime-heavy -- ./steamwebhelper -lang=en_US -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steampid=1728128 -buildid=1631237534 -steamid=76561197976113747 -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steamuniverse=Public -realm=Global -clientui=/home/daniel/.local/share/Steam/clientui --enable-blink-features=ResizeObserver,Worklet,AudioWorklet --enable-media-stream --enable-smooth-scrolling --password-store=basic --log-file=/home/daniel/.local/share/Steam/logs/cef_log.txt --disable-quick-menu
Runtime for steamwebhelper: defaulting to /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
+ exec /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy.sh --unpack-dir=/home/daniel/.local/share/Steam/ubuntu12_64 --runtime=steam-runtime-heavy -- ./steamwebhelper -lang=en_US -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steampid=1728128 -buildid=1631237534 -steamid=76561197976113747 -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steamuniverse=Public -realm=Global -clientui=/home/daniel/.local/share/Steam/clientui --enable-blink-features=ResizeObserver,Worklet,AudioWorklet --enable-media-stream --enable-smooth-scrolling --password-store=basic --log-file=/home/daniel/.local/share/Steam/logs/cef_log.txt --disable-quick-menu
Runtime for steamwebhelper: defaulting to /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
+ exec /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy.sh --unpack-dir=/home/daniel/.local/share/Steam/ubuntu12_64 --runtime=steam-runtime-heavy -- ./steamwebhelper -lang=en_US -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steampid=1728128 -buildid=1631237534 -steamid=76561197976113747 -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steamuniverse=Public -realm=Global -clientui=/home/daniel/.local/share/Steam/clientui --enable-blink-features=ResizeObserver,Worklet,AudioWorklet --enable-media-stream --enable-smooth-scrolling --password-store=basic --log-file=/home/daniel/.local/share/Steam/logs/cef_log.txt --disable-quick-menu
Runtime for steamwebhelper: defaulting to /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
+ exec /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy.sh --unpack-dir=/home/daniel/.local/share/Steam/ubuntu12_64 --runtime=steam-runtime-heavy -- ./steamwebhelper -lang=en_US -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steampid=1728128 -buildid=1631237534 -steamid=76561197976113747 -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steamuniverse=Public -realm=Global -clientui=/home/daniel/.local/share/Steam/clientui --enable-blink-features=ResizeObserver,Worklet,AudioWorklet --enable-media-stream --enable-smooth-scrolling --password-store=basic --log-file=/home/daniel/.local/share/Steam/logs/cef_log.txt --disable-quick-menu
Runtime for steamwebhelper: defaulting to /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
+ exec /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy.sh --unpack-dir=/home/daniel/.local/share/Steam/ubuntu12_64 --runtime=steam-runtime-heavy -- ./steamwebhelper -lang=en_US -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steampid=1728128 -buildid=1631237534 -steamid=76561197976113747 -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steamuniverse=Public -realm=Global -clientui=/home/daniel/.local/share/Steam/clientui --enable-blink-features=ResizeObserver,Worklet,AudioWorklet --enable-media-stream --enable-smooth-scrolling --password-store=basic --log-file=/home/daniel/.local/share/Steam/logs/cef_log.txt --disable-quick-menu
Runtime for steamwebhelper: defaulting to /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
+ exec /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy.sh --unpack-dir=/home/daniel/.local/share/Steam/ubuntu12_64 --runtime=steam-runtime-heavy -- ./steamwebhelper -lang=en_US -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steampid=1728128 -buildid=1631237534 -steamid=76561197976113747 -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steamuniverse=Public -realm=Global -clientui=/home/daniel/.local/share/Steam/clientui --enable-blink-features=ResizeObserver,Worklet,AudioWorklet --enable-media-stream --enable-smooth-scrolling --password-store=basic --log-file=/home/daniel/.local/share/Steam/logs/cef_log.txt --disable-quick-menu
Runtime for steamwebhelper: defaulting to /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
+ exec /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy.sh --unpack-dir=/home/daniel/.local/share/Steam/ubuntu12_64 --runtime=steam-runtime-heavy -- ./steamwebhelper -lang=en_US -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steampid=1728128 -buildid=1631237534 -steamid=76561197976113747 -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steamuniverse=Public -realm=Global -clientui=/home/daniel/.local/share/Steam/clientui --enable-blink-features=ResizeObserver,Worklet,AudioWorklet --enable-media-stream --enable-smooth-scrolling --password-store=basic --log-file=/home/daniel/.local/share/Steam/logs/cef_log.txt --disable-quick-menu
Runtime for steamwebhelper: defaulting to /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
+ exec /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy.sh --unpack-dir=/home/daniel/.local/share/Steam/ubuntu12_64 --runtime=steam-runtime-heavy -- ./steamwebhelper -lang=en_US -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steampid=1728128 -buildid=1631237534 -steamid=76561197976113747 -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steamuniverse=Public -realm=Global -clientui=/home/daniel/.local/share/Steam/clientui --enable-blink-features=ResizeObserver,Worklet,AudioWorklet --enable-media-stream --enable-smooth-scrolling --password-store=basic --log-file=/home/daniel/.local/share/Steam/logs/cef_log.txt --disable-quick-menu
Runtime for steamwebhelper: defaulting to /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
+ exec /home/daniel/.local/share/Steam/ubuntu12_64/steam-runtime-heavy.sh --unpack-dir=/home/daniel/.local/share/Steam/ubuntu12_64 --runtime=steam-runtime-heavy -- ./steamwebhelper -lang=en_US -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steampid=1728128 -buildid=1631237534 -steamid=76561197976113747 -cachedir=/home/daniel/.local/share/Steam/config/htmlcache -steamuniverse=Public -realm=Global -clientui=/home/daniel/.local/share/Steam/clientui --enable-blink-features=ResizeObserver,Worklet,AudioWorklet --enable-media-stream --enable-smooth-scrolling --password-store=basic --log-file=/home/daniel/.local/share/Steam/logs/cef_log.txt --disable-quick-menu
```

`cef_log.txt` isn't created, `cef_log.previous.txt` is dated before the update.

**Comment by namtsui** [comment] 2021-09-10 10:09
I see the same on guixsd with amdgpu. Small mode works but regular mode doesn't. Friends, messages, downloads and the store do not work as pictured in the OP.

**Comment by pclouds** [comment] 2021-09-10 10:18
Same on Gentoo Linux, nvidia+intel (optimus).

**Comment by kisak-valve** [comment] 2021-09-10 12:43
Hello @YellowOnion, your issue is already being tracked at https://github.com/ValveSoftware/steam-runtime/issues/462 and that is most likely a distro-specific issue.

Hello @namtsui, @pclouds, while the high level symptom of steamwebhelper failing to start may be the same, the cause can be completely different. I doubt that you're seeing the same issue as @YellowOnion. Your issues should be evaluated separately. Blind guess that @pclouds is seeing https://github.com/ValveSoftware/steam-runtime/issues/458.

Closing as a duplicate of https://github.com/ValveSoftware/steam-runtime/issues/462.

**Closed by kisak-valve** 2021-09-10 12:43 UTC

**Comment by pclouds** [comment] 2021-09-10 14:52
Thanks @kisak-valve you guessed right. Installing zenity worked.
