### ISSUE TITLE
steam_latest.deb failing with error

### ISSUE THREAD

**Issue by PgLoLo** [ValveSoftware/steam-for-linux#6365] opened 2019-07-06 09:52 UTC
After installing steam_latest.deb on my Ubuntu 18.04 and running command `steam` from the terminal it fails with this log:

```
Setting up Steam content in /home/george/.local/share/Steam
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins potentially out-of-date, rebuilding...
Installing breakpad exception handler for appid(steam)/version(0)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Installing breakpad exception handler for appid(steam)/version(1.0)
Installing breakpad exception handler for appid(steam)/version(1.0)
[2019-07-06 12:44:59] Startup - updater built Apr  9 2019 22:48:20
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
SteamUpdateUI: An X Error occurred
X Error of failed request:  GLXBadContext
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  155 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  48
xerror_handler: X failed, continuing
Major opcode of failed request:  155 (GLX)
Minor opcode of failed request:  6 (X_GLXIsDirect)
Serial number of failed request:  49
xerror_handler: X failed, continuing
[2019-07-06 12:44:59] Verifying installation...
[2019-07-06 12:44:59] Unable to read and verify install manifest /home/george/.local/share/Steam/package/steam_client_ubuntu12.installed
[2019-07-06 12:44:59] Verification complete
[2019-07-06 12:44:59] Downloading Update...
[2019-07-06 12:44:59] Checking for available update...
[2019-07-06 12:44:59] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
[2019-07-06 12:45:00] Package file tenfoot_misc_all.zip.1ca83d76835b4613170f5cead778b176b11f2b0c missing or incorrect size
[2019-07-06 12:45:00] Package file tenfoot_dicts_all.zip.33245b7d523f68418283e93b0572508fa127ee8f missing or incorrect size
[2019-07-06 12:45:00] Package file tenfoot_fonts_all.zip.vz.7673e4cd32b6752bc621d8bc1a7118a9af19b64a_12077027 missing or incorrect size
[2019-07-06 12:45:00] Package file tenfoot_ambientsounds_all.zip.89b80bcfdd11b2b99257ddbbdc374e2df54e2738 missing or incorrect size
[2019-07-06 12:45:00] Package file tenfoot_sounds_all.zip.vz.ffef2b2fc386819a842ea79484b966a937c2ca7e_1209792 missing or incorrect size
[2019-07-06 12:45:00] Package file tenfoot_images_all.zip.vz.e3fe5d6f7d21ec909bda07de60c9950c54d14402_31320945 missing or incorrect size
[2019-07-06 12:45:00] Package file tenfoot_all.zip.vz.11ff196ae3df752f4c1be0c4869052266062524b_2615321 missing or incorrect size
[2019-07-06 12:45:00] Package file friendsui_all.zip.vz.5cedcf2fb51c708349e106851cd363848a8b29b8_15594965 missing or incorrect size
[2019-07-06 12:45:00] Package file resources_misc_all.zip.vz.4a1fa88d21b005b67a41a9a0fc6044ae1fa46791_2225211 missing or incorrect size
[2019-07-06 12:45:00] Package file resources_music_all.zip.vz.7a62e15083d4a65668f0d1fa58ad8c1b99fb5ace_3708050 missing or incorrect size
[2019-07-06 12:45:00] Package file resources_hidpi_all.zip.vz.66e6d0c4758df08e7a52aeca5d75f7cf2d243268_56612 missing or incorrect size
[2019-07-06 12:45:00] Package file resources_all.zip.vz.96169894093c2f53e32ea35b55d745a31d49c47a_55267206 missing or incorrect size
[2019-07-06 12:45:00] Package file strings_en_all.zip.vz.93ee080847d6289f68b21b9ccdfc45577a8475e7_89640 missing or incorrect size
[2019-07-06 12:45:00] Package file strings_all.zip.vz.69d76c2e903a8cdc6a980151b4207502fc1752ab_2251462 missing or incorrect size
[2019-07-06 12:45:00] Package file public_all.zip.vz.8302631e972135875aaeef18c991194390fcc70c_818451 missing or incorrect size
[2019-07-06 12:45:00] Package file bins_ubuntu12.zip.vz.25ab2ae3b263fb53c3aca5ab1ad02a3bbcfae9b5_19399968 missing or incorrect size
[2019-07-06 12:45:00] Package file bins_pub_ubuntu12.zip.vz.47204fa48348c9fdba7f8fdf5dc1784b35012886_9044146 missing or incorrect size
[2019-07-06 12:45:00] Package file bins_sdk_ubuntu12.zip.vz.c92bdceb34d17ad3f961ca87ddfebb1a73a73214_13417024 missing or incorrect size
[2019-07-06 12:45:00] Package file bins_codecs_ubuntu12.zip.vz.228ce3d6bd2f702a390c63cef6158d21ba57c9e5_2373711 missing or incorrect size
[2019-07-06 12:45:00] Package file bins_misc_ubuntu12.zip.vz.7143e81bc11d2ea075fa68a1efd2eec4db05fc99_4387631 missing or incorrect size
[2019-07-06 12:45:00] Package file webkit_ubuntu12.zip.vz.4f6cd7e40cbf505df58dd2422df4b8781c251da0_53188192 missing or incorrect size
[2019-07-06 12:45:00] Package file miles_ubuntu12.zip.vz.4fd048667c97ef6eb976f4c42ce5c18f8695ac9e_295483 missing or incorrect size
[2019-07-06 12:45:00] Package file sdl2_ubuntu12.zip.vz.0cfd6c622801e59807be2303e5e13f7245d3e2ae_672171 missing or incorrect size
[2019-07-06 12:45:00] Package file steam_ubuntu12.zip.vz.f066893db2e4dc9ff0507220f3dc55c1ce7d4f88_1511404 missing or incorrect size
[2019-07-06 12:45:00] Package file runtime_part0_ubuntu12.zip.b24602650dc8b83de9717f1ff187f8a6a1681c4d missing or incorrect size
[2019-07-06 12:45:00] Package file runtime_part1_ubuntu12.zip.ced39cf4afe570ec7cfe83bfad15e09d1a8ed104 missing or incorrect size
[2019-07-06 12:45:00] Package file runtime_part2_ubuntu12.zip.62fab85050e88af798819dc34c1cd8e7a520db0e missing or incorrect size
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/tenfoot_misc_all.zip.1ca83d76835b4613170f5cead778b176b11f2b0c
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/tenfoot_dicts_all.zip.33245b7d523f68418283e93b0572508fa127ee8f
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/tenfoot_fonts_all.zip.vz.7673e4cd32b6752bc621d8bc1a7118a9af19b64a_12077027
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/tenfoot_ambientsounds_all.zip.89b80bcfdd11b2b99257ddbbdc374e2df54e2738
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/tenfoot_sounds_all.zip.vz.ffef2b2fc386819a842ea79484b966a937c2ca7e_1209792
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/tenfoot_images_all.zip.vz.e3fe5d6f7d21ec909bda07de60c9950c54d14402_31320945
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/tenfoot_all.zip.vz.11ff196ae3df752f4c1be0c4869052266062524b_2615321
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/friendsui_all.zip.vz.5cedcf2fb51c708349e106851cd363848a8b29b8_15594965
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/resources_misc_all.zip.vz.4a1fa88d21b005b67a41a9a0fc6044ae1fa46791_2225211
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/resources_music_all.zip.vz.7a62e15083d4a65668f0d1fa58ad8c1b99fb5ace_3708050
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/resources_hidpi_all.zip.vz.66e6d0c4758df08e7a52aeca5d75f7cf2d243268_56612
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/resources_all.zip.vz.96169894093c2f53e32ea35b55d745a31d49c47a_55267206
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/strings_en_all.zip.vz.93ee080847d6289f68b21b9ccdfc45577a8475e7_89640
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/strings_all.zip.vz.69d76c2e903a8cdc6a980151b4207502fc1752ab_2251462
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/public_all.zip.vz.8302631e972135875aaeef18c991194390fcc70c_818451
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/bins_ubuntu12.zip.vz.25ab2ae3b263fb53c3aca5ab1ad02a3bbcfae9b5_19399968
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/bins_pub_ubuntu12.zip.vz.47204fa48348c9fdba7f8fdf5dc1784b35012886_9044146
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/bins_sdk_ubuntu12.zip.vz.c92bdceb34d17ad3f961ca87ddfebb1a73a73214_13417024
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/bins_codecs_ubuntu12.zip.vz.228ce3d6bd2f702a390c63cef6158d21ba57c9e5_2373711
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/bins_misc_ubuntu12.zip.vz.7143e81bc11d2ea075fa68a1efd2eec4db05fc99_4387631
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/webkit_ubuntu12.zip.vz.4f6cd7e40cbf505df58dd2422df4b8781c251da0_53188192
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/miles_ubuntu12.zip.vz.4fd048667c97ef6eb976f4c42ce5c18f8695ac9e_295483
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/sdl2_ubuntu12.zip.vz.0cfd6c622801e59807be2303e5e13f7245d3e2ae_672171
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/steam_ubuntu12.zip.vz.f066893db2e4dc9ff0507220f3dc55c1ce7d4f88_1511404
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/runtime_part0_ubuntu12.zip.b24602650dc8b83de9717f1ff187f8a6a1681c4d
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/runtime_part1_ubuntu12.zip.ced39cf4afe570ec7cfe83bfad15e09d1a8ed104
[2019-07-06 12:45:00] Add pending download: media4.steampowered.com/client/runtime_part2_ubuntu12.zip.62fab85050e88af798819dc34c1cd8e7a520db0e
[2019-07-06 12:45:00] Downloading update (3,075 of 350,111 KB)...
.......
[2019-07-06 12:45:14] Downloading update (85,429 of 350,111 KB)...
[2019-07-06 12:4Installing breakpad exception handler for appid(steam)/version(1.0)
Installing breakpad exception handler for appid(steam)/version(1.0)
5:14] Downloading update (86,953 of 350,111 KB)...
[2019-07-06 12:45:14] Downloading update (88,531 of 350,111 KB)...
.......
[2019-07-06 12:46:00] Downloading update (350,111 of 350,111 KB)...
[2019Installing breakpad exception handler for appid(steam)/version(1.0)
Installing breakpad exception handler for appid(steam)/version(1.0)
.......
Installing breakpad exception handler for appid(steam)/version(1.0)
-07-06 12:46:00] Download Complete.
[2019-07-06 12:46:00] uninstalled manifest found in /home/george/.local/share/Steam/package/steam_client_ubuntu12 (1).
[2019-07-06 12:46:00] Extracting package...
[2019-07-06 12:46:08] Installing update...
[2019-07-06 12:46:08] Cleaning up...
[2019-07-06 12:46:08] Update complete, launching...
[2019-07-06 12:46:08] Shutdown
Restarting Steam by request...
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME has been set by the user to: /home/george/.local/share/Steam/ubuntu12_32/steam-runtime
Gtk-Message: 12:46:10.359: GtkDialog mapped without a transient parent. This is discouraged.
Forced use of runtime version for 32-bit libdbus-1.so.3. Host: 3.19.4 Runtime: 3.5.8
Found newer runtime version for 32-bit libopus.so.0. Host: 0.5.2 Runtime: 0.7.0
Found newer runtime version for 32-bit libGLU.so.1. Host: 1.3.1 Runtime: 1.3.8004
Found newer runtime version for 64-bit libdbusmenu-glib.so.4. Host: 4.0.12 Runtime: 4.0.13
Found newer runtime version for 64-bit libdbusmenu-gtk.so.4. Host: 4.0.12 Runtime: 4.0.13
Found newer runtime version for 64-bit libpangox-1.0.so.0. Host: 0.0.0 Runtime: 0.3000.0
Found newer runtime version for 64-bit libvulkan.so.1. Host: 1.1.70 Runtime: 1.1.73
Found newer runtime version for 64-bit libSDL2_image-2.0.so.0. Host: 0.2.1 Runtime: 0.2.2
Forced use of runtime version for 64-bit libSDL2-2.0.so.0. Host: 0.8.0 Runtime: 0.9.0
Found newer runtime version for 64-bit libopus.so.0. Host: 0.5.2 Runtime: 0.7.0
Found newer runtime version for 64-bit libGLU.so.1. Host: 1.3.1 Runtime: 1.3.8004
Installing breakpad exception handler for appid(steam)/version(1560817063)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Installing breakpad exception handler for appid(steam)/version(1560817063)
Gtk-Message: 12:46:29.754: Failed to load module "gail"
Gtk-Message: 12:46:29.754: Failed to load module "atk-bridge"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  155
Serial number of failed request:  52
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  155
Value in failed request:  0x0
Serial number of failed request:  51
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  155
Serial number of failed request:  53
xerror_handler: X failed, continuing
crash_20190706124629_1.dmp[24191]: Uploading dump (out-of-process)
/tmp/dumps/crash_20190706124629_1.dmp
/home/george/.local/share/Steam/steam.sh: line 712: 24167 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20190706124629_1.dmp[24191]: Finished uploading minidump (out-of-process): success = yes
crash_20190706124629_1.dmp[24191]: response: CrashID=bp-15445813-176c-4c50-b29e-ac3fb2190706
crash_20190706124629_1.dmp[24191]: file ''/tmp/dumps/crash_20190706124629_1.dmp'', upload yes: ''CrashID=bp-15445813-176c-4c50-b29e-ac3fb2190706''
```

(I've merged some repeating messages e.g. about downloading)

At the beginnig, we can see some libGL errors, but after that, the update process starts correctly. After the update process, the new progress bar about "installing system runtime" appears and finishes correctly (as far as I can tell).

But after that, the final section with a  lot of X errors appears and finally, everything fails with a Segmentation fault. 

How can I fix this problem?

**Comment by kisak-valve** [comment] 2019-07-06 12:55
Hello @PgLoLo, what video card / driver version are you using? Does any 32 bit OpenGL application like `glxinfo` from `mesa-utils:i386` work?

Swrast is mesa's slower software renderer, and the log hints that the system is trying to use it with the nvidia proprietary driver, which is incompatible. Odds are you need to install the 32 bit userspace for the nvidia driver with something like `sudo apt install libnvidia-gl-390:i386` where 390 is the driver series you're using.

**Comment by PgLoLo** [comment] 2019-07-09 10:31
> sudo apt install libnvidia-gl-390:i386

I am using GeForce GTX 1050 Mobile with 418.67 driver

**Comment by PgLoLo** [comment] 2019-07-09 10:32
`glxinfo` works, but I don't know how to guarantee that it is from mesa-utils:i386 though

**Comment by kisak-valve** [comment] 2019-07-09 12:34
In that case, can you check you have `libnvidia-gl-418:i386` with something like `apt policy libnvidia-gl-418:i386`?

**Comment by PgLoLo** [comment] 2019-07-09 16:39
> In that case, can you check if you have `libnvidia-gl-418:i386` with something like `apt policy libnvidia-gl-418:i386`?

No, it says it's not:
```
libnvidia-gl-418:i386:
  Installed: (none)
  Candidate: (none)
  Version table:
```
so I can not apt install it either:
```E: Package 'libnvidia-gl-418:i386' has no installation candidate```

**Comment by ZKing1000** [comment] 2019-07-18 06:31
```
Running Steam on linuxmint 19 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
[2019-07-17 23:28:50] Startup - updater built Jul 17 2019 06:13:47
SteamUpdateUI: An X Error occurred
X Error of failed request:  GLXBadContext
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  155 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  48
xerror_handler: X failed, continuing
Major opcode of failed request:  155 (GLX)
Minor opcode of failed request:  6 (X_GLXIsDirect)
Serial number of failed request:  49
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2019-07-17 23:28:50] Checking for update on startup
[2019-07-17 23:28:50] Checking for available updates...
[2019-07-17 23:28:50] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
[2019-07-17 23:28:51] Download skipped by HTTP 304 Not Modified
[2019-07-17 23:28:51] Nothing to do
[2019-07-17 23:28:51] Verifying installation...
[2019-07-17 23:28:51] Performing checksum verification of executable files
[2019-07-17 23:28:52] Verification complete

```

**Comment by ScaMar** [comment] 2020-01-01 17:48
in order to use steam, it is better to avoid the nvidia repo http://developer.download.nvidia.com/compute/cuda/repos/ubuntu18<xx>/x86_64/ . that may not i386 compliant.
For ubuntu bionic based release the latest available driver with i386 layer is 435 (bionic-updates/restricted repo) and 440 for focal based (restricted repo).
Also with a 64 bit steam client, the issue will persiste with 32bit games.

**Comment by ZKing1000** [comment] 2020-03-12 21:52
When will steam be updated to work properly with Nvidia drivers? I cannot install 32-bit drivers.

**Comment by ZKing1000** [comment] 2020-03-14 21:42
Update: I installed the correct nvidia driver through pacman and lib32-nvidia-390xx-utils and everythings working great now!

**Comment by kisak-valve** [comment] 2021-11-26 22:40
Closing as a duplicate of #5778.

**Closed by kisak-valve** 2021-11-26 22:40 UTC
Labels: NVIDIA drivers, Distro Family: Ubuntu
