### ISSUE TITLE
Steam should change to 64 bits by default and drop 32 bits

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#4465] opened 2016-05-28 16:18 UTC
99% of users out there use 64 bit Linux systems, there should at least be a 64 bit steam client or better, drop 32 bit, that way more devs will put games in 64 bits with better performance.

**Comment by LinuxDonald** [comment] 2016-05-28 16:26
Yeah that would be very cool :)

**Comment by Tele42** [comment] 2016-05-28 19:34
Duplicate of #179.

**Comment by gdrewb-valve** [comment] 2016-05-28 20:03
Closing duplicate.

**Closed by gdrewb-valve** 2016-05-28 20:03 UTC
