### ISSUE TITLE
Chat window does not open when other party initiates chat

### ISSUE THREAD

**Issue by vadi2** [ValveSoftware/steam-for-linux#4280] opened 2016-01-25 21:20 UTC
Whenever someone starts chatting with me, the chat window does not actually open for me. The only way to me to see their messages is if I decide to start a conversation with them - then I'll see the messages I've been missing out on.

**Comment by Tele42** [comment] 2016-01-25 22:45
For me, on Gentoo with KDE4, child windows spawned by steam are spawned minimized, since I have a secondary monitor to the left it appears on the secondary monitor's task-switch selector (or whatever it's called). I am able to alt-tab to that minimized window.

It would be nice if it was not spawned minimized, and not take focus when there is no game running.

**Comment by rmbleeker** [comment] 2016-01-26 10:35
I've actually experienced this bug for a long time, from what I can recall ever since Steam for Linux came out. It's annoying but not terribly important to me since I don't use Steam chat for reliable communication. Good that someone finally reported it though.

I'm using Ubuntu 14.04 LTS with the Unity DE, as vanilla as it gets. Whenever I hear the sound that someone is sending me a message on Steam, I have to click on the Steam icon in the taskbar or double-click a friend in my Friends list to make the chat window appear.

**Comment by vadi2** [comment] 2016-01-26 11:12
I can confirm it's been happening for a long while.

**Comment by sizeofbool** [comment] 2016-01-26 16:57
There is no such issue on GNU\Debian 8 'jessie' x64_86 with the Xfce DE.

**Comment by alextpedro** [comment] 2016-02-05 01:31
I can confirm this happening on Linux Mint 17.3 with Cinnamon, too.

**Comment by kisak-valve** [comment] 2019-03-08 16:51
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment] 2019-04-12 14:05
Closing pending feedback.

**Closed by kisak-valve** 2019-04-12 14:05 UTC
Labels: Need Retest, reviewed
