### ISSUE TITLE
Bad softlink in .steam directory

### ISSUE THREAD

**Issue by FuFikCZ** [ValveSoftware/steam-for-linux#4202] opened 2015-12-25 10:22 UTC
Running steam creates .steam directory with bad softlinks. ~/.steam/root should point to ~/.local/share/Steam, not to itself (root -> /home/fuf/.steam/root)

```
$ cd ~/.steam && ls -l
lrwxrwxrwx 1 fuf fuf   23 25. pro 11.10 bin -> /home/fuf//.steam/bin32
lrwxrwxrwx 1 fuf fuf   33 25. pro 11.10 bin32 -> /home/fuf/.steam/root/ubuntu12_32
lrwxrwxrwx 1 fuf fuf   33 25. pro 11.10 bin64 -> /home/fuf/.steam/root/ubuntu12_64
-rw-r--r-- 1 fuf fuf 2193 25. pro 11.10 registry.vdf
lrwxrwxrwx 1 fuf fuf   21 25. pro 11.10 root -> /home/fuf/.steam/root
lrwxrwxrwx 1 fuf fuf   29 25. pro 11.10 sdk32 -> /home/fuf/.steam/root/linux32
lrwxrwxrwx 1 fuf fuf   29 25. pro 11.10 sdk64 -> /home/fuf/.steam/root/linux64
-rw-r--r-- 1 fuf fuf    0 25. pro 11.10 starting
lrwxrwxrwx 1 fuf fuf   21 25. pro 11.10 steam -> /home/fuf/.steam/root
-rwxr-xr-x 1 fuf fuf 8860 24. pro 16.14 steam_install_agreement.txt
-rw-r--r-- 1 fuf fuf    5 25. pro 11.10 steam.pid
prw------- 1 fuf fuf    0 25. pro 10.39 steam.pipe
```

if I remove root link and create new one, everything works

```
$ rm ~/.steam/root && ln -s ~/.local/share/Steam ~/.steam/root
```

But after restarting steam, link are again bad.

I am running archlinux, sysinfo:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  2900 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.5-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11800000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Mobile x86/MMX/SSE2

    Driver Version:  3.0 Mesa 11.0.7
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x116
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 11,54" x 6,46"  (13,19" diag)
                                            29,3cm x 16,4cm  (33,5cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: 

Memory:
    RAM:  3870 Mb

Miscellaneous:
    UI Language:  English
    LANG:  cs_CZ.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  169897 Mb
    Largest Free Hard Disk Block:  101118 Mb

Installed software:

Recent Failure Reports:
```

**Comment by gdrewb-valve** [comment] 2015-12-25 14:30
Likely duplicate.

**Comment by kisak-valve** [comment] 2018-07-06 13:36
Closing as a duplicate of #3759.

**Closed by kisak-valve** 2018-07-06 13:36 UTC
Labels: reviewed
