### ISSUE TITLE
Can't get steam to run after installing GPU

### ISSUE THREAD

**Issue by tmarkwell16** [ValveSoftware/steam-for-linux#6263] opened 2019-05-09 07:44 UTC
#### Your system information
* Ubuntu 18.04.2 LTS 64 bit
* Intel i5-6600K
* 16GiB Ram
* GeForce GTX 1660TI

* OpenGL version 4.6.0
* GLX version 1.4
* Nvidia driver 418.40.04
* Cuda 10.1

#### Steam outputs:
`
$ steam 
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
[2019-05-09 01:30:01] Startup - updater built Apr 29 2019 20:58:13
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
`
#### glxinfo outputs:
[Output gist](https://gist.github.com/b027d7a8a36c5680ffd4460fd05298e3)
#### glxgears outputs:
`Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
301 frames in 5.0 seconds = 60.066 FPS
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":1"
      after 56 requests (54 known processed) with 0 events remaining.`

I have tried:
* Reinstalling the os
* uninstalling and reinstalling drivers
* uninstalling and reinstalling steam
* 32bit versions of openGL

**Comment by XakepSDK** [comment] 2019-05-09 07:52
Try this: `sudo apt-get install libgl1-nvidia-glx:i386`

**Comment by tmarkwell16** [comment] 2019-05-09 08:07
> Try this: `sudo apt-get install libgl1-nvidia-glx:i386`
That package doesn't seem to be in any repository I have

**Comment by dreamer** [comment] 2019-05-09 10:29
@tmarkwell16 how did you install NVIDIA's proprietary drivers? Using a package or manually by using nvidia-installer?

**Comment by kisak-valve** [comment] 2019-05-09 13:36
Hello @tmarkwell16, you tested with a 64 bit build of glxinfo, but Steam is 32 bit, so a 32 bit build of glxinfo from `mesa-utils:i386` would give you more relevant feedback.

nVidia's 32 bit userspace package in Ubuntu 18.04 has a naming scheme of `libnvidia-gl-<series>`, so in your case, if it exists the 32 bit opengl support would be in `libnvidia-gl-418:i386`.

There's a good chance this is a duplicate of #5778. nVidia's cuda .deb packaging for ubuntu 18.04 and newer is known to be missing 32 bit support.

**Comment by tmarkwell16** [comment] 2019-05-09 14:03
@dreamer I downloaded the .Deb package from https://developer.nvidia.com/cuda-downloads?target_os=Linux and installed from there!

**Comment by kisak-valve** [comment] 2019-05-09 14:39
Closing as a duplicate of #5778.

**Closed by kisak-valve** 2019-05-09 14:39 UTC
Labels: Distro Family: Ubuntu, NVIDIA drivers
