### ISSUE TITLE
Steam on Lubuntu 15.04 don't start

### ISSUE THREAD

**Issue by Clonewayx** [ValveSoftware/steam-for-linux#3801] opened 2015-04-19 14:07 UTC
Steam client dont strat.

********:~$ steam
Running Steam on ubuntu 15.04 32-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1424305157)
libGL error: unable to load driver: r300_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r300
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

ProblemType: Bug
DistroRelease: Ubuntu 15.04
Package: steam 1:1.0.0.48-1ubuntu1 [modified: usr/share/applications/steam.desktop usr/share/icons/hicolor/16x16/apps/steam.png usr/share/icons/hicolor/24x24/apps/steam.png usr/share/icons/hicolor/256x256/apps/steam.png usr/share/icons/hicolor/32x32/apps/steam.png usr/share/icons/hicolor/48x48/apps/steam.png]
ProcVersionSignature: Ubuntu 3.19.0-10.10-generic 3.19.2
Uname: Linux 3.19.0-10-generic i686
ApportVersion: 2.16.2-0ubuntu4
Architecture: i386
CurrentDesktop: LXDE
Date: Fri Mar 27 16:14:50 2015
InstallationDate: Installed on 2013-03-16 (741 days ago)
InstallationMedia: Lubuntu 12.10 "Quantal Quetzal" - Release i386 (20121017.1)
SourcePackage: steam
UpgradeStatus: No upgrade log present (probably fresh install)

https://bugs.launchpad.net/ubuntu/+source/steam/+bug/1437379

**Comment by selfslaughter** [comment] 2015-04-26 10:25
Same issue here, DELL Latitude D810: Fresh install of Lubuntu 15.04 / Linux 4.0.0.
ATI Mobility X600 GPU

self_slaughter@SiC:~$ steam
Running Steam on ubuntu 15.04 32-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0_client)
libGL error: unable to load driver: r300_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r300
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
^C
self_slaughter@SiC:~$ uname -a
Linux SiC 4.0.0-040000-generic #201504121935 SMP Sun Apr 12 23:58:08 UTC 2015 i686 i686 i686 GNU/Linux

**Comment by Tele42** [comment] 2015-04-26 17:55
This is a known issue where the steam runtime bundled libstdc++.so.6 is too old and being used instead of the newer system varient. This is reported at #3273 and https://github.com/ValveSoftware/steam-runtime/issues/13.

**Comment by selfslaughter** [comment] 2015-04-27 04:24
Thanks, I'll try removing it and any other outdated files when I get home 😊

**Comment by likehopper** [comment] 2015-05-02 09:19
This works fine for me under Ubuntu 15.04 64bits with proprietary driver NVIDIA version 346 and the latest steam client :
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib32/nvidia-346/:/usr/lib/nvidia-346/" steam

**Comment by hlorridi** [comment] 2015-06-06 00:25
sudo kill $(pgrep steam)
for f in $(find ~/.steam/ -iname *libstd*); do mv $f $f.bck; done
And that's "fixed"

**Comment by MrSchism** [comment] 2015-06-06 01:48
> edit: removed the libstd files and steam downloaded, then had to force close it and delete the new libstd files it created. Now it's running  Cheers!
> 
> Surprisingly I've got 107 of my games available to linux. Sadly doom isn't one of them lol
> Thank god for chocolate doom

I'm glad it worked, @selfslaughter 

@likehopper it's a mesa (intel integrated graphics) issue.

@hlorridi that's a decent script, but I'd probably have it check a bit more stringent.

**Comment by Ruedii** [comment] 2015-06-27 20:31
This is technically a bug with Steam Runtime.  Sould it be referred over to there?

**Comment by kode-kristoff** [comment] 2015-07-06 21:11
I found this good workaround that doesn't that still works after steam upgrades: https://wirejungle.wordpress.com/2015/01/09/how-to-fix-broken-steam-linux-client-with-radeon-graphics-driver-workaround/

**Comment by monte-fm** [comment] 2015-08-14 11:54
Here is good guide
https://wirejungle.wordpress.com/2015/01/09/how-to-fix-broken-steam-linux-client-with-radeon-graphics-driver-workaround/

**Comment by phgachoud** [comment] 2015-11-05 09:14
Same problem on ubuntu 15.10 Asus and GeForce G102M

**Comment by OwenChia** [comment] 2015-11-14 15:00
Same problem on Gentoo and ATI HD5650m.

**Comment by jhyrman** [comment] 2015-12-02 20:22
FWIW, I installed nvidia-current, restarted, removed steam, purged, updated, installed steam, and now it's working. Ubuntu 15.10 with nVidia.

**Comment by legluondunet** [comment] 2015-12-24 18:57
I obtain the same problem on a computer (Ubuntu 15.10 - AMD/ATI Hawaii XT Radeon R9 290X - drivers free). I found a workaround here:
http://askubuntu.com/questions/614422/problem-with-installing-steam-on-ubuntu-15-04/614458

**Comment by plastilint** [comment] 2016-01-24 18:08
Same problem.

**Comment by tribbloid** [comment] 2016-02-04 06:38
same problem using nvidia-355 & nvidia-prime, WITHOUT bumblebee/primus

**Comment by BitReign** [comment] 2016-02-20 22:36
Same. 7970 - ubuntu 15.10

**Comment by MetzKetz** [comment] 2016-02-21 15:17
Same. Arch - ATI R300

**Comment by menasheh** [comment] 2016-03-06 07:17
@monte-fm Thank you!  Based on your link, easy fix to this problem is:
export LD_PRELOAD='/usr/$LIB/libstdc++.so.6'
export DISPLAY=:0

**Comment by ChrisNZL** [comment] 2016-03-07 06:42
export LD_PRELOAD='/usr/$LIB/libstdc++.so.6'
    export DISPLAY=:0

These two lines got it working for me with Ubuntu 15.10. Thanks.

**Comment by bubbapizza** [comment] 2016-03-19 15:01
yep, those lines worked for me too - ubuntu 15.10, radeon R9 270

**Comment by rskumar** [comment] 2016-04-12 20:13
Shame but same issue. Ubuntu 15.10 :) 

Works with steps as suggested by @monte-fm

**Comment by Enzime** [comment] 2016-04-27 04:57
Just wanted to mention this link, anyone who might be having issues with Steam, this could also be caused by the new version of libgcrypt

https://bugs.archlinux.org/task/48994

**Comment by DeXP** [comment] 2016-05-06 17:23
Thanks, @Enzime, this worked for me!

**Comment by apiraino** [comment] 2016-06-07 20:34
Still present as of Ubuntu 16.04.

In my case the problem was caused by an obsolete version of library `libstdc++.so.6` (dated 2014!) shipped with Steam installer v1.0.0.52. I fixed deleting the culprit library and its symlink (Steam will fall back on the system one):
```
~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/libstdc++.so.6
~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/libstdc++.so.6.0.18
```
In order to diagnose launch with `env LIBGL_DEBUG=verbose steam`; I could spot  this error:

> libGL: dlopen /usr/lib/i386-linux-gnu/dri/r600_dri.so failed (/home/jman/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/i386-linux-gnu/dri/r600_dri.so))


jeez, can't wait for the day we Linux users won't be second-class citizens...

**Comment by OwenChia** [comment] 2016-06-21 06:33
```bash
find ~/.steam/root/ \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" \) -print -delete
```
This worked for me, Gentoo with Radeon.

https://bbs.archlinux.org/viewtopic.php?pid=1590999#p1590999

**Comment by brantje** [comment] 2016-10-13 17:03
Taken from: http://askubuntu.com/questions/614422/problem-with-installing-steam-on-ubuntu-15-04

`find $HOME/.steam/root/ubuntu12_32/steam-runtime/*/usr/lib/ -name "libstdc++.so.6" -exec mv "{}" "{}.bak" \; -print` 

might fix it.

**Comment by pluma** [comment] 2016-10-14 09:34
I'm also getting the swrast error messages and no GUI. I'm not sure what caused it, possibly either a steam update or a regular `apt-get upgrade` of something else.

I'm using Ubuntu 16.04 LTS with a GeForce GTX 870M/PCIe/SSE2 using the official nVidia driver (listed as "proprietary, tested" in the additional drivers selection).

Deleting files like others recommended doesn't fix it. What DOES work around it is switching PRIME to the on-board Intel HD graphics chip in the nVidia settings. But that results in atrocious performance so I'm only using that to install games and then launch them manually without Steam.

I've tried installing steam using the .deb file from the steam website but that refused to launch after the EULA screen, showing the exact same message about swrast in the console (so I had to install using Intel mode).

All of this worked just a few days ago (though I did originally have to hunt down and delete some files like others have suggested here) and ceased working yesterday. Even a clean reinstall after a complete purge didn't fix it -- neither the steam-launcher .deb from the steam website nor the Ubuntu steam:i386 package work when I'm using the nVidia card.

I would be fine if Steam would only work with software rasterisation because it obviously doesn't affect the games and at least I could install and update games without logging out of Ubuntu.

**Comment by dassmann** [comment] 2016-10-14 12:48
Same error here on Ubuntu 16.10 (64bit) and intel graphics (no discrete graphics!). Using the LD_PRELOAD trick I can get steam to update itself. However, the error appears again on the updated version.

**Comment by VictorBjelkholm** [comment] 2016-10-22 11:35
Having similar issues but with a Intel Graphics on MacBookPro11,1

**$ lsb_release -a**
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
```
**$ uname -a**      
```
Linux tonga 4.8.0-26-generic #28-Ubuntu SMP Tue Oct 18 14:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
**$ steam**
```
Running Steam on ubuntu 16.10 64-bit
STEAM_RUNTIME is enabled automatically
/bin/bash: /home/victor/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
Installing breakpad exception handler for appid(steam)/version(1476379980)
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

```

**Comment by IsNoGood** [comment] 2016-10-22 12:03
This happens also for me:  Lenovo Carbon X1 Gen 2 and Ubuntu 16.10

**Comment by higuita** [comment] 2016-10-23 04:44
The logs you send point that libGL mesa drive failed to load the intel driver and then also failed to load the software fallback... probably another lib that needs to be removed from steam-runtime because it breaks recent mesa versions. I still didn't updated ubuntu on test machine, so i can not test it right now.

Please try to start steam from the command line with 
`LIBGL_DEBUG=true steam`

and report the output, it should give a little more info on what is failing now on 16.10.

I also assume that running `glxgears ` works fine in a normal console (not run from inside steam)

**Comment by VictorBjelkholm** [comment] 2016-10-23 13:12
@higuita Thanks a lot for the debugging and the additional steps to get more information. I now get the following output:

```
Running Steam on ubuntu 16.10 64-bit
STEAM_RUNTIME is enabled automatically
/bin/bash: /home/victor/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
Installing breakpad exception handler for appid(steam)/version(1476379980)
libGL: Can't open configuration file /home/victor/.drirc: No such file or directory.
libGL: pci id for fd 7: 8086:0a2e, driver i965
libGL: OpenDriver: trying /usr/lib/i386-linux-gnu/dri/tls/i965_dri.so
libGL: OpenDriver: trying /usr/lib/i386-linux-gnu/dri/i965_dri.so
libGL: dlopen /usr/lib/i386-linux-gnu/dri/i965_dri.so failed (/lib/i386-linux-gnu/libgcrypt.so.20: symbol gpgrt_lock_lock, version GPG_ERROR_1.0 not defined in file libgpg-error.so.0 with link time reference)
libGL: OpenDriver: trying ${ORIGIN}/dri/tls/i965_dri.so
libGL: OpenDriver: trying ${ORIGIN}/dri/i965_dri.so
libGL: dlopen ${ORIGIN}/dri/i965_dri.so failed (${ORIGIN}/dri/i965_dri.so: cannot open shared object file: No such file or directory)
libGL: OpenDriver: trying /usr/lib/dri/tls/i965_dri.so
libGL: OpenDriver: trying /usr/lib/dri/i965_dri.so
libGL: dlopen /usr/lib/dri/i965_dri.so failed (/usr/lib/dri/i965_dri.so: cannot open shared object file: No such file or directory)
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL: pci id for fd 7: 8086:0a2e, driver i965
libGL: OpenDriver: trying /usr/lib/i386-linux-gnu/dri/tls/i965_dri.so
libGL: OpenDriver: trying /usr/lib/i386-linux-gnu/dri/i965_dri.so
libGL: dlopen /usr/lib/i386-linux-gnu/dri/i965_dri.so failed (/lib/i386-linux-gnu/libgcrypt.so.20: symbol gpgrt_lock_lock, version GPG_ERROR_1.0 not defined in file libgpg-error.so.0 with link time reference)
libGL: OpenDriver: trying ${ORIGIN}/dri/tls/i965_dri.so
libGL: OpenDriver: trying ${ORIGIN}/dri/i965_dri.so
libGL: dlopen ${ORIGIN}/dri/i965_dri.so failed (${ORIGIN}/dri/i965_dri.so: cannot open shared object file: No such file or directory)
libGL: OpenDriver: trying /usr/lib/dri/tls/i965_dri.so
libGL: OpenDriver: trying /usr/lib/dri/i965_dri.so
libGL: dlopen /usr/lib/dri/i965_dri.so failed (/usr/lib/dri/i965_dri.so: cannot open shared object file: No such file or directory)
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL: OpenDriver: trying /usr/lib/i386-linux-gnu/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib/i386-linux-gnu/dri/swrast_dri.so
libGL: dlopen /usr/lib/i386-linux-gnu/dri/swrast_dri.so failed (/lib/i386-linux-gnu/libgcrypt.so.20: symbol gpgrt_lock_lock, version GPG_ERROR_1.0 not defined in file libgpg-error.so.0 with link time reference)
libGL: OpenDriver: trying ${ORIGIN}/dri/tls/swrast_dri.so
libGL: OpenDriver: trying ${ORIGIN}/dri/swrast_dri.so
libGL: dlopen ${ORIGIN}/dri/swrast_dri.so failed (${ORIGIN}/dri/swrast_dri.so: cannot open shared object file: No such file or directory)
libGL: OpenDriver: trying /usr/lib/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib/dri/swrast_dri.so
libGL: dlopen /usr/lib/dri/swrast_dri.so failed (/usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory)
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
```

`glxgears` works without any problems.

**Comment by VictorBjelkholm** [comment] 2016-10-23 13:41
I did come across a comment (https://github.com/ValveSoftware/steam-for-linux/issues/4664#issuecomment-253823532) in a different issue that solves the problem if you preload the libraries like this:

```
env LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /$LIB/libgpg-error.so.0' steam
```

With this I'm no longer seeing the errors from LibGL

**Comment by higuita** [comment] 2016-10-23 16:25
correct, that should work, it is the libgpg-error.so.0 that is failing now. Trusting the reddit comment, this is what is needed now (this, or the LD_PRELOAD above)

`find $HOME/.steam/root/ubuntu12_32/steam-runtime/*/usr/lib/ \( -name "libstdc++.so.6" -o -name "libgpg-error.so.0"  -o -name "libxcb.so.1" -o -name "libgcc_s.so.1" \) -exec mv "{}" "{}.bak" \; -print`

**Comment by mr-blobbyyy** [comment] 2016-10-24 03:28
Can someone explain why this is still an issue? Why is steam bundling old mesa libraries?

**Comment by pluma** [comment] 2016-10-24 18:12
Nope, neither of the two are working for me. LD_PRELOAD just gives me a ton of errors, renaming the files still fails with `libGL error: No matching fbConfigs or visuals found` and `libGL error: failed to load driver: swrast`.

**Comment by higuita** [comment] 2016-10-24 22:02
@mr-blobbyyy because steam officially only support steamos and ubuntu 14.04 LTS and this are the lib version include on those systems. Steam have a set of runtime binaries/libs for compatibility, so any game can work for many years without any update... For closed source drivers, this is not usually a problem, but for open source ones (and now too the closed source amdgpu pro) are using the same libs... so trying to load one old lib with a new drive that requires newer lib version creates this problem. This is not easy to solve, but the reality is that very few games require this old compatibility layer, most games can use newer lib versions safely. Long term fix might be isolate system/X/opengl related libs from the game bundled libs

@pluma  if this is failing, please run the find above and then run steam like this and post the result:

`LIBGL_DEBUG=verbose steam`

without this, it is impossible to know what is going wrong on your system.
Also, report what disto/version are you running, if not ubuntu 16.10

**Comment by pluma** [comment] 2016-10-25 08:56
@higuita (mind you, this is after using the rename above)

```
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
/bin/bash: /home/pluma/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
awk: /home/pluma/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.6)
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
Installing breakpad exception handler for appid(steam)/version(1476379980)
libGL: screen 0 does not appear to be DRI2 capable
libGL: OpenDriver: trying /usr/lib/i386-linux-gnu/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib/i386-linux-gnu/dri/swrast_dri.so
libGL: Can't open configuration file /home/pluma/.drirc: No such file or directory.
libGL: Can't open configuration file /home/pluma/.drirc: No such file or directory.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

**Comment by higuita** [comment] 2016-10-26 02:41
@pluma  so intel works, right? 

i would say you have a problem with your nvidia drivers or bumblebee setup...sadly i do not think that nvidia have anything similar to LIBGL_DEBUG=verbose, but i do not use nvidia for about 8 years.
do any other app/game outside steam work with nvidia?

try running with this command (stolen from @likehopper above) :

`LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib32/nvidia-346/:/usr/lib/nvidia-346/" steam`

update the nvidia version for what you have installed

**Comment by pluma** [comment] 2016-10-26 11:30
@higuita Amazing, that seems to do the trick.

I think this explains why Steam was suddenly broken for me. I recall having had problems with Steam the first time I installed it way back and apparently I was using version 361 of the driver (now I'm on 367) because at the bottom of my `.bashrc` I found this line:

`export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib32/nvidia-361:/usr/lib64/nvidia-361"`

So this must have been how I originally got Steam working in the first place and upgrading to 367 broke it.

Now if only there was an easy way to fetch the integer driver version from the output of `nvidia-settings -q NvidiaDriverVersion` and inject it into that path dynamically so this doesn't break on the next update.

**Comment by pluma** [comment] 2016-10-26 11:47
Just as an addendum, this is pretty hacky and someone with better shell skills than me should probably correct this, but this seems to do the trick (just add it to .bashrc and launch steam from the shell):

```sh
NVIDIA_VERSION=`nvidia-settings -q NvidiaDriverVersion | grep -oP "[0-9]{3}" | sed -n 1p`
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib32/nvidia-$NVIDIA_VERSION:/usr/lib/nvidia-$NVIDIA_VERSION"
```

**Comment by rdragonrydr** [comment] 2016-12-25 20:50
I also had this issue on a new Dell Inspiron with AMD graphics. It was running Ubuntu 16.04. I had to use the workaround 
cd $HOME/.steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu
mv libstdc++.so.6 libstdc++.so.6.bak
cd $HOME/.steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu
mv libstdc++.so.6 libstdc++.so.6.bak
to make Steam work. Please fix this problem!
(I also had to install ia32-libs, of course, as I have a 64 bit system)

**Comment by kisak-valve** [comment] 2016-12-25 21:16
Hello, we will be tracking this type of issue at #4768 from now on. Closing.

**Closed by kisak-valve** 2016-12-25 21:16 UTC
Labels: reviewed
