### ISSUE TITLE
Controller not functional in Nov 11th Beta

### ISSUE THREAD

**Issue by brain-anti-freeze** [ValveSoftware/steam-for-linux#8226] opened 2021-11-12 18:55 UTC
#### Your system information

* Steam client version (build number or date): 11th Nov Beta (1636673014)
* Distribution (e.g. Ubuntu): Arch (5.14.16-zen1-1-zen)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When connecting a controller there is a delay of 20 seconds or so before the notification that it is connected, the notification then appears repeatedly for a while.  The controller is shown as detected in settings but does not function in BPM or in game.  Controller_ui.txt (attached) shows constant disconnects and reconnects.  Works fine if I opt back out of the beta and the problem returns when I opt back in.  I've tried with the controller wirelessly (using xow) and wired (using xone) with the same results.

The client also hangs on exit (the UI completely disappears but the process doesn't exit).  The last message in the terminal is `Exiting workitem thread`.

#### Steps for reproducing this issue:

1. Update to beta
2. Connect controller
3. Try to use controller in game or BPM
[controller_ui.txt](https://github.com/ValveSoftware/steam-for-linux/files/7529786/controller_ui.txt)

**Comment by brain-anti-freeze** [comment] 2021-11-12 19:12
A couple of additional observations - if you don't connect a controller at all then there is no hang on shutdown, if you disconnect the controller 30 seconds before exiting there is no hang on shutdown, if you connect the controller before starting the steam client there is no hang on shutdown and BPM can receive input from the controller but it is unusably laggy.

**Comment by tomboland** [comment] 2021-11-12 22:00
I haven't been as thorough as @brain-anti-freeze, but I can confirm my xbox one controller ceased to function today.  I have opted out of the beta client, and it's all working again. 

I'm using Manjaro, with Kernel: 5.10.70-1-MANJARO

**Comment by mscatto** [comment] 2021-11-13 00:04
Same thing here, also under Arch and the latest beta.
Controllers cease to work, proton games take a long time to start, and when running steam on the terminal, it keeps spamming the following indefinitely whenever a controller is connected. Opting out of beta fixes it and everything works again.

`!! Steam controller device opened for index 0.
Steam Controller reserving XInput slot 0
Controller has an Invalid or missing unit serial number, setting to '45e-2a1-462db17'
BYieldingQueryAccountsRegisteredToController
Installing breakpad exception handler for appid(steam)/version(1636673014)
Controller device closed after hid_read failure
BYieldingQueryAccountsRegisteredToController - controller disconnected while waiting.
Local Device Found
  type: 045e 02a1
  path: sdl://0
  serial_number:  - 0
  Manufacturer: 
  Product:      Xbox 360 Wireless Receiver (XBOX)
  Release:      114
  Interface:    -1

!! Steam controller device opened for index 0.
Steam Controller reserving XInput slot 0
Controller has an Invalid or missing unit serial number, setting to '45e-2a1-462db17'
BYieldingQueryAccountsRegisteredToController
Controller device closed after hid_read failure
BYieldingQueryAccountsRegisteredToController - controller disconnected while waiting.
Local Device Found
  type: 045e 02a1
  path: sdl://0
  serial_number:  - 0
  Manufacturer: 
  Product:      Xbox 360 Wireless Receiver (XBOX)
  Release:      114
  Interface:    -1

!! Steam controller device opened for index 0.
Steam Controller reserving XInput slot 0
Controller has an Invalid or missing unit serial number, setting to '45e-2a1-462db17'
BYieldingQueryAccountsRegisteredToController
Controller device closed after hid_read failure
BYieldingQueryAccountsRegisteredToController - controller disconnected while waiting.
Local Device Found
  type: 045e 02a1
  path: sdl://0
  serial_number:  - 0
  Manufacturer: 
  Product:      Xbox 360 Wireless Receiver (XBOX)
  Release:      114
  Interface:    -1
`

**Comment by DonKatsu** [comment] 2021-11-13 03:59
#### Your system information

* Steam client version (build number or date): 11/11/2021
* Distribution (e.g. Ubuntu): Fedora 35 KDE
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

My 8BitDo Pro 2 was working perfectly over bluetooth in Xinput mode until last night, when I accidentally launched Big Picture.
I was using it with "Xbox Configuration Support" enabled since it shows up as an Xbox One Wireless Controller in Xinput mode.
When I launched Big Picture, Steam locked up. I tried to kill the steam and steamwebhelper processes, but they remained until I turned of the controller.
Since then, while in "General Controller Settings" I can see the controller being added and removed and I get spammed with the following in the terminal on loop after enabling "Xbox Configuration Support":
```
Opted-in Controller Mask for AppId 0: a
Controller device closed after hid_read failure
Local Device Found
  type: 045e 02e0
  path: sdl://0
  serial_number:  - 0
  Manufacturer: 
  Product:      Xbox One Wireless Controller
  Release:      903
  Interface:    -1

!! Steam controller device opened for index 0.
Steam Controller reserving XInput slot 0
Controller has an Invalid or missing unit serial number, setting to '45e-2e0-1f77bf8'
BYieldingQueryAccountsRegisteredToController
Controller device closed after hid_read failure
BYieldingQueryAccountsRegisteredToController - controller disconnected while waiting.
Local Device Found
  type: 045e 02e0
  path: sdl://0
  serial_number:  - 0
  Manufacturer: 
  Product:      Xbox One Wireless Controller
  Release:      903
  Interface:    -1

!! Steam controller device opened for index 0.
```
The controller is detected and works as expected over bluetooth as long as "Xbox Configuration Support" is disabled.
However if I use USB, it works with it enabled or disabled.
It also still works as expected in Switch mode, whether over bluetooth or USB.

I opted out of the Steam beta, and "Xbox Configuration Support" worked as expected with bluetooth on Xinput. Switching back to the beta has bluetooth not working again with it enabled.

I tried re-pairing the controller to my bluetooth adapter, but that didn't help. I've restarted my computer twice since this started as well.

**Comment by hasezoey** [comment] 2021-11-13 14:50
#### Your system information

* Steam client version (build number or date):  Nov 11 2021, at 22:49:28, 1636673014
* Distribution (e.g. Ubuntu): Manjaro 21.1.6 - KDE Plasma Wayland
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
i also just noticed that my controller, a xbox controller, stopped working after getting the update yesterday and also other issues

the controller is still detected as "connected" and shown, but no input is received / processed and i also cannot open the controller configuration window. (kde plasma (`Game Controller - System Settings` still detects the controller and its input like before)

other issues:
- sometimes when trying to open Steam Big Picture, it just shows black screen (sound is still played, and input (keyboard & mous) is still processed, guessing from the sound effects), steam needs to be completely restarted for this to work again
- steam does not exit when a controller was ever attached while steam was running (even waiting 30s or 60s before trying to exit steam still does not exit steam)
- when steam does not exit (`Exit Steam` from icon try), it hangs for a while and then acts as if never having clicked the `Exit Steam` button (can even re-open the Library / Store window and start games)
- steam also does not respond to SIGTERM anymore, so i can only kill steam with SIGKILL

**Comment by Brad7173** [comment] 2021-11-13 15:05
Same issue in Kubuntu current version.

**Comment by brain-anti-freeze** [comment] 2021-11-13 16:54
Disabling Xbox Configuration Support appears to allow the controller to work again for me too

**Comment by DanMan** [comment] 2021-11-13 19:35
I also get endless spam by the second in my kernel ring buffer log like:

   input: Microsoft X-Box 360 pad as /devices/virtual/input/input80

With every line, the number at the end keeps incrementing.

**Comment by BillFleming** [comment] 2021-11-14 14:36
I also get this problem on my main gaming rig with an older steam install (2016 or 2017 install date) but not on a PC with a brand new Steam install from last week. Both PCs running Arch Linux from RebornOS install and both using cinnamon. The controllers that work in one PC cause the failure in the other. Switching back to non-beta causes controllers to work again, but then switching back to beta causes them to fail. I haven't yet tried to manually delete files in my steam directory in case anyone wants to examine them.
Note both PCs have different kernels and probably different libusb versions since normal libusb is broken with the 100% cpu bug, but I could retest with them on the same software.

**Comment by apocalyptech** [comment] 2021-11-14 16:11
Just another "me too" for this one.  Either of the workarounds mentioned above fix the issue for me:

1. Disable "Xbox Controller Support" allows the controller to work again, though this has the side-effect that the controller can't be configured -- I'm stuck with unwanted controller vibration, etc.
2. Opt out of Steam client betas and revert back to vanilla

Certainly happy enough on vanilla Steam for now, so at least that workaround exists!

**Comment by DonKatsu** [comment] 2021-11-16 23:45
Got the new beta client. Xbox Controller Support works as intended for me again.

**Comment by shigutso** [comment] 2021-11-17 03:29
Confirming, fixed for me too (PS3 controller)

**Comment by fureloka** [comment] 2021-11-17 04:01
Can confirm my PS3 controller is behaving properly now (with and without config support enabled).

**Comment by BillFleming** [comment] 2021-11-17 04:02
This beta also fixed the problems for me.

**Comment by brain-anti-freeze** [comment] 2021-11-17 09:02
Looks like the new Nov 16th beta fixes it for me too.  The very first time I connected a controller after re-enabling xbox controller support it took 10 seconds to recognise it and then the steam client froze for 5 seconds but subsequent re-connections were fine and controller input is working as expected again.

**Comment by kisak-valve** [comment] 2021-11-17 12:39
Closing as fixed per the last several comments.

**Closed by kisak-valve** 2021-11-17 12:39 UTC
Labels: Big Picture, Need Retest, Distro Family: Arch, General controller / Steam Input

**Comment by hasezoey** [comment] 2021-11-17 13:02
I can also confirm that my Xbox Controller works again on the `Nov 16 2021, at 11:52:43` beta build
