### ISSUE TITLE
Emoticon and Special buttons are oversized and cause misalign in Steam Chat window

### ISSUE THREAD

**Issue by kgorol** [ValveSoftware/steam-for-linux#8363] opened 2022-01-27 06:17 UTC
#### Your system information

* Steam client version (build number or date): Jan 16 2022, at 17:34:49
* Distribution (e.g. Ubuntu): Manjaro KDE
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:

Emoticon and Special buttons are oversized and make the whole Steam Chat window misaligned, as per screenshot below:

<img width="740" alt="Screenshot_20220127_071221" src="https://user-images.githubusercontent.com/34159482/151302469-69869829-f1cb-438c-8580-6be8dfd48477.png">

The top is cut, and there is a black bar at the bottom. It only happened after recent Friends update.

#### Steps for reproducing this issue:

1. Open Chat window.

**Comment by kisak-valve** [comment] 2022-01-27 13:43
Unable to reproduce locally in a quick test.

**Comment by viktor2142** [comment] 2022-02-05 10:29
I also have this exact same issue, interestingly it also affected me on Windows10.

Manjaro KDE
Kernel 5.16.5-1
Problem occurs on XORG and Wayland

Package: steam-manjaro 1.0.0.74-1
Opted into Steam client beta?: [Yes] Issue persists with both versions
Have you checked for system updates?: [Yes]

**Comment by Protonator** [comment] 2022-02-16 20:35
Confirmed under Manjaro Gnome (Wayland, Kernel 5.16.7, latest system updates, Steam-Runtime 1.0.0.74-1) and Windows 10 (21H2). But while under Windows 10 it's still possible to click and use the cropped minimize and close buttons, it's not under Gnome. Resizing the chat window sometimes temporarily fixes both of this – until a client restart.

**Comment by kisak-valve** [comment] 2022-03-01 16:29
Content of chat windows is not in correct position, breaking buttons

Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/8446.
@Zorrototo posted on 2022-03-01T16:26:12:

#### Your system information

* Steam client version (build number or date): steam-runtime_0.20211207.0
* Distribution (e.g. Ubuntu): Manjaro (Windows 10 too)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When receiving a chat message or opening a chat window, the button to minimize, maximize, and close the chat window are not working and are not in their proper position (they are higher). You can also see the issue at the bottom where a black bar appears (the size of the position difference for the buttons in top right corner, as if all the window content is higher), and the emoticon and share file buttons are higher but reach the bottom of the window inside the black bar zone.

Image for reference: https://i.imgur.com/oHu86xp.jpg

Resizing the chat windows sometimes repair the content and moves everything in position.

Problem is similar on the Windows client too after verification a few weeks ago.

#### Steps for reproducing this issue:

1. Open chat window
2. Notice the buttons on top right corner not working and higher than correct position, notice bottom of chat window issues too.

**Comment by kgorol** [comment] 2022-03-24 09:57
Seems to be fixed after latest Friends update.

**Comment by bxkx** [comment] 2022-03-24 11:22
Fixed for me now too!

**Comment by Zorrototo** [comment] 2022-03-24 14:18
Seems like it. :+1:

**Comment by kisak-valve** [comment] 2022-04-29 14:47
Closing as fixer per the last several comments.

**Closed by kisak-valve** 2022-04-29 14:47 UTC
Labels: Steam client, Need Retest
