### ISSUE TITLE
Closing lone Steam window using window manager controls causes Steam to exit completly.

### ISSUE THREAD

**Issue by roge-** [ValveSoftware/steam-for-linux#4934] opened 2017-04-23 01:57 UTC
## System Information
[**Steam system information Gist**](https://gist.github.com/roge-/fd943341f1d61bb12c645e6804b09e96)

* **Steam build date:** Mar 22, 2017 at 23:45:04
* **Steam package version:** 1490228413
* **Distribution**: Arch Linux
* **Opted into Steam client beta?:** No
* **Have you checked for system updates?:** Yes

## The Issue
If you close any lone Steam window using the window manager's close control Steam quits completly. I'm not sure if this functionality is intended or not, if it is that doesn't make much sense becuase if you use the "X" button on Steam's own decorations it doesn't cause Steam to exit.

## Reproduction Steps
1. Open Steam
2. Open a chat window(can be any Steam window, just using chat for example)
3. Close other Steam windows
4. Use window manager's close control on the chat window(IE: Press Alt+F4 with Xfwm, or use the "Close" context menu option in an XFCE window list)

**Comment by kisak-valve** [comment] 2017-04-23 02:19
Hello @roge-, this is the current expected behavior as noted at https://github.com/ValveSoftware/steam-for-linux/issues/2685#issuecomment-21497969. Closing as a duplicate of #2685.

**Closed by kisak-valve** 2017-04-23 02:19 UTC
