### ISSUE TITLE
Can't input CJK in steam.

### ISSUE THREAD

**Issue by queenmedley** [ValveSoftware/steam-for-linux#4239] opened 2016-01-06 08:42 UTC
Input methods for CJK(chines, japan, korea) like fcitx, ibus, scim... are not work in steam.
But I can see CJK font well. 
I think input method doesn't work in steam.
Is there a way to input CJK? or make input method work in steam?

**Comment by Tele42** [comment] 2016-01-06 16:11
This should be a duplicate of #781. You should be able to replace steam-provided libsdl2 with a build of libsdl 2.0.4 with ibus enabled to have a chance of getting this working early.

**Comment by gdrewb-valve** [comment] 2016-01-06 18:43
Closing duplicate.

**Closed by gdrewb-valve** 2016-01-06 18:43 UTC
Labels: duplicate, reviewed
