### ISSUE TITLE
xbox 360 clone controller, no rumble

### ISSUE THREAD

**Issue by biji** [ValveSoftware/steam-for-linux#8601] opened 2022-05-21 12:10 UTC
#### Your system information

* Steam client version (build number or date): 

may 14 2022

* Distribution (e.g. Ubuntu): 

fedora 36 

* Opted into Steam client beta?: [Yes/No]
 no

* Have you checked for system updates?: [Yes/No]
yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I'm using usb xbox 360 clone controller, no rumble in game

#### Steps for reproducing this issue:

1.  open https://gamepad-tester.com/ , test the gamepad vibration works
2.  play steam games
3.  no vibration in game

**Comment by kisak-valve** [comment] 2022-05-21 12:55
Possible duplicate of #8590.

**Comment by biji** [comment] 2022-05-23 02:06
Btw i'm using latest xpad driver from github (dkms)

**Comment by kisak-valve** [comment] 2022-10-28 13:00
Hello @biji, based on the feedback on #8590, this may have improved with the 2022-10-27 Steam client beta. Please opt into Steam's client beta and retest.

**Comment by kisak-valve** [comment] 2022-12-09 19:52
Closing pending feedback.

**Closed by kisak-valve** 2022-12-09 19:52 UTC
Labels: Need Retest, General controller / Steam Input
