### ISSUE TITLE
Steam spawning broken windows and not loading store + library

### ISSUE THREAD

**Issue by nadomodan** [ValveSoftware/steam-for-linux#6771] opened 2019-12-16 00:50 UTC
* Steam client version (build number or date): Dec 6 2019 https://gist.github.com/nadomodan/501f38749e2728c5760e3448585031fe
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

when playing dota 2, after some time steam keeps spawning dead friend list/chat windows
![2019-12-15_23-45](https://user-images.githubusercontent.com/10760147/70870900-6305c000-1f99-11ea-899a-e83a7d67104c.png)
![image](https://user-images.githubusercontent.com/10760147/70870930-cd1e6500-1f99-11ea-8abb-6009c7e36240.png)

they are either full white or black
![image](https://user-images.githubusercontent.com/10760147/70870912-8fb9d780-1f99-11ea-964a-84a4286d3163.png)
can't go to store or library on steam, page is white or rapidly flashes between white and black with steam logo loading icon
also causes dota 2 to run at lower fps and makes it crash after a while
restarting steam makes it work normally, temporarily until problem comes back.
Closing dota2 also makes library and store load and work normally again.
Launch dota 2 again and problems come back soon.
Another weird thing, after I come back to firefox there's a bunch of tabs with http://www.error.com/ open, as if steam is opening those
log: https://gist.github.com/nadomodan/b4f1b0c65a2e73fca8b9e5d16dd17aef

**Comment by kisak-valve** [comment] 2019-12-16 00:58
Hello @nadomodan, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

It looks like you're using RADV/ACO, can you check if completely closing Steam, then running `RADV_PERFTEST=llvm steam-runtime` from a terminal has an effect?

**Comment by nadomodan** [comment] 2019-12-16 01:10
https://gist.github.com/nadomodan/501f38749e2728c5760e3448585031fe
I thought ACO is in mesa 19.3 already? I updated to 19.3 yesterday and enabled ACO but the same problems were happening for few days before that

```
└─▶ RADV_PERFTEST=llvm steam-runtime
Running Steam on arch rolling 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/nadomodan/.local/share/Steam/ubuntu12_32/steam
Installing breakpad exception handler for appid(steam)/version(1575604565)
Installing breakpad exception handler for appid(steam)/version(1575604565)
/usr/share/themes/Adapta-Nokto-Eta/gtk-2.0/common-dark-eta.rc:1425: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Adapta-Nokto-Eta/gtk-2.0/3rd-party-dark-eta.rc:475: error: invalid string constant "toolbar", expected valid string constant
Installing breakpad exception handler for appid(steam)/version(1575604565)
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
[1216/020444.582226:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: browser
[1216/020444.622670:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[1216/020444.622749:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1575603249
[1216/020444.622753:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[1216/020444.622756:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
[1216/020444.658749:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[1216/020444.658816:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1575603249
[1216/020444.658830:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[1216/020444.658834:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
[1216/020444.659557:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: gpu-process
[1216/020444.715861:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[1216/020444.715923:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1575603249
[1216/020444.715937:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[1216/020444.715940:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
[1216/020444.716731:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: utility
Installing breakpad exception handler for appid(steam)/version(1575604565)
Installing breakpad exception handler for appid(steam)/version(1575604565)
Installing breakpad exception handler for appid(steam)/version(1575604565)
Installing breakpad exception handler for appid(steam)/version(1575604565)
Installing breakpad exception handler for appid(steam)/version(1575604565)
Installing breakpad exception handler for appid(steam)/version(1575604565)
CAppInfoCacheReadFromDiskThread took 37 milliseconds to initialize
CApplicationManagerPopulateThread took 47 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Installing breakpad exception handler for appid(steam)/version(1575604565)
Installing breakpad exception handler for appid(steam)/version(1575604565)
Installing breakpad exception handler for appid(steam)/version(1575604565)
Installing breakpad exception handler for appid(steam)/version(1575604565)
Installing breakpad exception handler for appid(steam)/version(1575604565)
Installing breakpad exception handler for appid(steam)/version(1575604565)
Installing breakpad exception handler for appid(steam)/version(1575604565)
Installing breakpad exception handler for appid(steam)/version(1575604565)
Installing breakpad exception handler for appid(steam)/version(1575604565)

** (steam:341696): WARNING **: 02:04:44.944: Could not initialize NMClient /org/freedesktop/NetworkManager: The name org.freedesktop.NetworkManager was not provided by any .service files
Installing breakpad exception handler for appid(steam)/version(1575604565)
Installing breakpad exception handler for appid(steam)/version(1575604565)
Installing breakpad exception handler for appid(steam)/version(1575604565)
Fossilize INFO: Overriding serialization path: "/home/nadomodan/.local/share/Steam/shader_cache_temp_dir_vk_64/fozpipelinesv4/steamapprun_pipeline_cache".
Installing breakpad exception handler for appid(steam)/version(1575604565)
Opted-in Controller Mask for AppId 0: 0

(steam:341696): Gtk-WARNING **: 02:04:55.303: gtk_disable_setlocale() must be called before gtk_init()
Installing breakpad exception handler for appid(steam)/version(1575604565)
roaming config store loaded successfully - 6275 bytes.
migrating temporary roaming config store
BRefreshApplicationsInLibrary 1: 12ms
[1216/020458.031149:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[1216/020458.091949:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[1216/020458.201730:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
Installing breakpad exception handler for appid(steam)/version(1575604565)
Failed to init SteamVR because it isn't installed
ExecCommandLine: "'/home/nadomodan/.local/share/Steam/ubuntu12_32/steam'"
System startup time: 14.67 seconds
[1216/020458.734387:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[1216/020458.738869:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
BuildCompleteAppOverviewChange: 196
RegisterForAppOverview 1: 8ms
RegisterForAppOverview 2: 8ms
Installing breakpad exception handler for appid(steam)/version(1575604565)

```

**Comment by kisak-valve** [comment] 2019-12-16 01:21
Right, my eyes tricked me, RADV/ACO is part of the 19.3.0 release, but it's not enabled by default and I thought I read `WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely` early on in the log, before Dota 2 was started up, but that's not the case. The suggestion was simply to rule it out as a factor since the LLVM backend has been around for much longer.

**Comment by stengun** [comment] 2019-12-20 14:18
I experienced the same problem a while ago but it was relegated to my second screen (wich is rotated 90°). Today after the update I have distorted rendering on all the webpages of steam regardless the screen the application runs on, including library (wich was not touched by this defect before). Steam client is completely unusable.
I'm not running repo's most updated kernel because it breaks entirely my performance with DXVK and related stuff with proton, but the rest of the system is fully updated.

This is my system summary: 
https://gist.github.com/stengun/ef7c16e1085a624c79716124adc5fd8e


This problem appears regardless I run steam with runtime or native libraries and regardless the shader compiler in use.

Having mesa git 20, I tried to enable aco and LLVM. I attach logs
ACO with steam runtime:
https://gist.github.com/stengun/817d04203c7ff3b5811948afc3a0075a
ACO with native runtime:
https://gist.github.com/stengun/693289d4bb558de3cde1ec550f14e320
LLVM with steam runtime
https://gist.github.com/stengun/16ab95086d2514a1d92821c5994bdc58
LLVM with native runtime:
https://gist.github.com/stengun/87877bb6f29485812e548aa40b459838

and this is the error as it appears to me:
![Screenshot_20191220_145723](https://user-images.githubusercontent.com/1102142/71260066-3efc0300-233a-11ea-9fc8-183cf8e05ccc.png)

I'll try new tests after upgrading the kernel, seeing if I can manage to expose this bug more clearly. Thank you.

**Comment by asiantuntija** [comment] 2019-12-21 18:43
I do have this exact view using 5700XT and Mesa-git, reverting back to 19.3.1 and it goes away. It also affects my Spotify, so it's not limited to Steam only. A friend of mine has the same thing using Vega on Manjaro.

Using RADV_PERFTEST=llvm steam-runtime didn't fix it.

**Comment by kode54** [comment] 2019-12-22 11:24
Here, I can't even get it to launch properly, within 5 seconds of the Holiday Sale animation appearing in the store, the whole client crashes.

**Comment by stengun** [comment] 2019-12-23 04:08
I confirm that downgrading mesa to stock mesa in arch linux (19.3.1) fixes my problem too, thanks to @asiantuntija for pointing this. This leads to something related to mesa itself that breaks cef rendering in some way.

**Comment by asiantuntija** [comment] 2019-12-23 09:58
Seems to be fixed now. Updated to kernel to 5.5 RC3 and back to Mesa-git and it's all back to normal.

**Comment by stengun** [comment] 2019-12-23 18:15
5.5 rc3 and mesa git does not solve the issue for me. Probably my installation is kinda borked, because with the kernel release candidate I get a lot of artifacts on the screen (and steam has the same issue as before).

relevant packages:
linux-mainline 5.5rc3-1
mesa-git 1:20.0.0_devel.118691.8e9e94d0843-1

**Comment by Zamundaaa** [comment] 2019-12-24 12:47
Doesn't solve the problem for me either. Exactly the same packages as @stengun. I also tested with kernel 5.4.6, no difference, so it shouldn't be the kernel. A current workaround is simply disabling GPU acceleration for web views in the Steam settings, then the library works again.

As @asiantuntija already said, Spotify has the same behaviour, so it's very likely a fault in Mesa, not Steam. When opening spotify from the command line it prints out
> [1224/132734.173193:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command

**Comment by nadomodan** [comment] 2019-12-24 13:10
It seems you have a bit different problem, stengun and following commenters. I don't have distorted view like on screenshot, it's also not fixed by disabling gpu accel. Do you have this happening immediately from steam start? Because the problem I described initially can take 1-3 hours before it starts happening.

**Comment by stengun** [comment] 2019-12-24 16:43
@nadomodan you are right, it is a different problem. Bt the way, I assume for us the problem is not steam related, since changing the mesa version fixes that (and disabling hw accel too).

Our problem is present since start and there is not way of fixing it by simply "using steam". I apologize to have "invaded" this issue thinking the nature of the problem was the same.

**Comment by Zamundaaa** [comment] 2019-12-24 22:37
@nadomodan it does indeed not sound related after all.
For everyone else, I made a bug report directly on the Mesa project, where the issue should belong: https://gitlab.freedesktop.org/mesa/mesa/issues/2277

**Comment by kisak-valve** [comment] 2022-05-13 23:41
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by kode54** [comment] 2022-05-14 00:10
I can't say I've experienced this recently, but I don't really run either Windows or Linux desktops that often any more, either.

**Comment by kisak-valve** [comment] 2022-06-17 18:58
Closing as outdated.

**Closed by kisak-valve** 2022-06-17 18:58 UTC
Labels: AMD drivers, Need Retest, Distro Family: Arch, Web Component
