### ISSUE TITLE
Steam window takes a long time to appear starting from recent beta, rendering freezes

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [ValveSoftware/steam-for-linux#10595] opened 2024-03-09 03:21 UTC
#### Your system information

* Steam client version (build number or date): 1709920887
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14544753/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Steam in my case is running via flatpak, behavior is the same when launched through a menu entry or command line.
Others have reported also having the issue on other distros and without flatpak.
The observed behavior and symptoms are very similar to #10593, but installing `lsof` didn't solve the issue and I didn't have the "missing `lsof`" warning messages in the first place.
It takes a long time for the main window to appear, but the tray icon appears at a regular time after the line `BRefreshApplicationsInLibrary 1: 0ms` is printed in stdout. After that it takes a long time for the main window to appear.
After launching a game (successfully), the library view breaks and becomes non-interactible. Switching between Store, library, community, etc works but the library itself is broken. But after changing the window size (in my case - going from expanded window to floating) it becomes interactible again.

UPD: the library can be interacted with, but the changes are not reflected in the GUI. I had a window pop up when I pressed a button to select a way to launch a game. But unexpanding the window didn't solve the problem. The whole issue seems a bit flaky.

#### Steps for reproducing this issue:

1. Install steam
2. Start steam
3. Wait for the main window to appear
4. Launch a game and exit
5. Observe effects

**Comment by g572staem** [comment] 2024-03-09 03:41
Not to mention it is a privacy violation.

**Comment by christian-bendiksen** [comment] 2024-03-09 12:59
Yep. Takes a long time to show steam. In terminal it stop at this:

Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 237
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
BRefreshApplicationsInLibrary 1: 0ms

Then when steam window appears it shows:
BuildCompleteAppOverviewChange: 270 apps

**Comment by wescode** [comment] 2024-03-09 15:11
Same issue. Using steam beta, flatpak, fedora 39:

steamwebhelper.sh[138]: === Sat Mar  9 10:09:08 AM EST 2024 ===
steamwebhelper.sh[138]: Starting steamwebhelper under bootstrap sniper steam runtime at /home/nope/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-sniper
CAppInfoCacheReadFromDiskThread took 37 milliseconds to initialize
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 219
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
BRefreshApplicationsInLibrary 1: 57ms
BuildCompleteAppOverviewChange: 367 apps
RegisterForAppOverview 1: 15ms
RegisterForAppOverview 2: 15ms

**Comment by LuNeder** [comment] 2024-03-09 20:38
Same problem here, on openSUSE Tumbleweed

Steam from zypper, so this isn't a flatpak-exclusive problem. On latest beta too.

**Comment by JohnTheCoolingFan** [comment] 2024-03-09 20:43
Updated the issue text to reflect what's known

**Comment by JohnTheCoolingFan** [comment] 2024-03-09 20:46
This issue really degrades my gaming experience, as sometimes games won't launch, but I can't really document the exact behavior from my observations

**Comment by Gamertech** [comment] 2024-03-10 07:06
Fedora 39 KDE. Exact same issue.

Swapped to beta due to Valve breaking Steams windowing in the stable branch, then encountered all the loading and stability issues posted in this and other recent issues.

**Comment by JohnTheCoolingFan** [comment] 2024-03-10 20:30
I think the "flatpak-provided steam package" label should be removed as others have reported having the issue without flatpak

**Comment by af7567** [comment] 2024-03-12 14:42
I seem to have the same problem on slackware64-current with openbox.
The library window will take a long time to show after starting steam.
Sometimes only the tray icon will show and it's impossible to open the library/store/settings without exiting and restarting steam (the friends list will still open though).

Starting and exiting big picture mode using the tray icon also gets the main steam window to appear in the times when it doesn't want to show.

**Comment by TTimo** [comment] 2024-03-12 15:37
We're looking at providing a fallback `lsof` if none is present on the system. But I think overall the analysis is correct, you should make sure it's installed on your distribution. All mainline distros have this by default so that's why this implicit dependency has gone unseen.

**Comment by sitedyno** [comment] 2024-03-13 16:44
I'm having the looong delay after `BRefreshApplicationsInLibrary 1: 0ms`. My system literally boots faster than steam starts. Arch Linux using i3wm. Since the monitors won't sleep while steam is running #5607 that means I'm starting steam a lot :frowning_face: **If there's anything I can do to help move this issue forward please let me know!**

`lsof` is installed:
```
╰─❯ pacman -Ss lsof
extra/lsof 4.99.3-1 [installed]
    Lists open files for running Unix processes
```

`inxi -b` for reference:

```
╰─❯ inxi -b
System:
  Host: cb-d2022 Kernel: 6.7.8-arch1-1 arch: x86_64 bits: 64
  Desktop: i3 v: 4.23 Distro: Arch Linux
Machine:
  Type: Desktop Mobo: ASRock model: X399 Taichi serial: <superuser required>
    UEFI: American Megatrends v: P3.92 date: 01/14/2021
CPU:
  Info: 16-core AMD Ryzen Threadripper 1950X [MT MCP MCM] speed (MHz):
    avg: 2236 min/max: 2200/3400
Graphics:
  Device-1: AMD Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] driver: amdgpu
    v: kernel
  Display: server: X.Org v: 21.1.11 driver: X: loaded: amdgpu dri: radeonsi
    gpu: amdgpu resolution: 1: 2560x1080 2: 1080x1920
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.0.2-arch1.2
    renderer: AMD Radeon RX 6900 XT (radeonsi navi21 LLVM 17.0.6 DRM 3.57
    6.7.8-arch1-1)
Network:
  Device-1: Intel I211 Gigabit Network driver: igb
  Device-2: Intel Dual Band Wireless-AC 3168NGW [Stone Peak] driver: iwlwifi
  Device-3: Intel I211 Gigabit Network driver: igb
Drives:
  Local Storage: total: 2.29 TiB used: 385.58 GiB (16.5%)
Info:
  Memory: total: 64 GiB available: 62.65 GiB used: 12.27 GiB (19.6%)
  Processes: 570 Uptime: 5d 13h 56m Shell: Zsh inxi: 3.3.33
```

**Comment by Gamertech** [comment] 2024-03-13 23:01
lsof is included in the flatpak by default, as well as in most distros as mentioned above.

It may add a delay if the user doesn't have lsof, but it's not the cause for most of the users in this issue. There's something else in the beta.

**Comment by TTimo** [comment] 2024-03-13 23:18
The problem is worse in flatpak than just missing `lsof`. Next beta update will have a fix.

**Comment by JohnTheCoolingFan** [comment] 2024-03-18 04:12
The issue is still present on Steam version 1710281934 for me

**Comment by lostgoat** [comment] 2024-03-18 19:25
Fix for the flatpak case is available in the latest beta.

**Comment by JohnTheCoolingFan** [comment] 2024-03-18 19:34
Fix confirmed for me on version 1710786209

**Comment by Gamertech** [comment] 2024-03-19 00:06
1710786209 flatpak, seems to be working well thanks kisak!

Still got the window size continually resetting issue that's also in stable unfortunately, but loads up quickly again and doesn't freeze up if a Steam sub-window goes behind the main window any more.

**Comment by guihkx** [comment] 2024-03-19 14:02
Thank you very much, the beta branch fixes things for me as well.

**Comment by valgusk** [comment] 2024-03-21 09:41
any idea on the workaround for non-flatpak version?  you seem to know the source of the problem.

**Comment by JohnTheCoolingFan** [comment] 2024-03-21 11:01
Not closing the issue because it seems the non-flatpak version is not fixed. I don't want to test it myself to confirm.

**Comment by kisak-valve** [comment] 2024-05-10 23:55
Closing as fixed in the [2024-05-07](https://store.steampowered.com/news/app/593110/view/4182231197207095612) Steam client update.

If anyone is seeing similar symptoms on an up to date system, please open a new issue report so that it can be tracked properly.

**Closed by kisak-valve** 2024-05-10 23:55 UTC
Labels: Steam client, Need Retest, Web Component
