### ISSUE TITLE
No sound after latest steam beta update (In-home Streaming)

### ISSUE THREAD

**Issue by slis** [ValveSoftware/steam-for-linux#3715] opened 2015-02-14 11:46 UTC
Now no sound ... with nonbeta on HOST is ok, and still window mode on client with vaapi decoding is broken.

Host Win7/8,1 nvfbc

Client Debian Sid vaapi

**Comment by slis** [comment] 2015-02-14 11:52
#3629

**Comment by Gordon01** [comment] 2015-02-17 11:52
I can confirm. Sound playing on host, no sound at client

**Comment by slis** [comment] 2015-02-19 18:18
Switching from 44.1 kHz to 48 kHz (16 Bit, Stereo) on the host's output device solved my problem.

**Comment by slis** [comment] 2015-02-23 07:29
Now sound is cutting in and out every couple of minutes, crackling, and some sounds can't be heard in dota2.

**Comment by IcyTesseract** [comment] 2015-03-21 00:44
I can confirm this issue on Arch Linux x64 as the client. I've tried switching from Normal to Beta on both machines to no avail. Sound works just fine on Mac OS X.

**Comment by karmictoucan** [comment] 2015-03-22 10:14
I have the same issue. I have no sound on client machine when streaming games. If I play games locally(on both client and host) sound is present. 
Host - http://pastebin.com/tezTEbzy
Client - http://pastebin.com/mm0EHyfW
streaming_log.txt - http://pastebin.com/mjAzxbc6

**Comment by karmictoucan** [comment] 2015-03-22 14:47
I opted into steam client beta on both machines and now sound works.

**Comment by rooterkyberian** [comment] 2015-03-30 16:49
Same here. Updated to current beta on both windows an linux and now it works.

**Comment by bjwest** [comment] 2015-03-30 17:37
Latest steam client (built Mar 23 2015, at 20:07:53) fixed the problem for me.

**Comment by bjwest** [comment] 2015-04-09 19:35
Belay my last.  Yesterday sound wasn't working again on my remote client after shutting down my laptop and restarting it.

**Comment by bjwest** [comment] 2015-04-09 20:48
Belay my belay (for now) Just downloaded todays update and sound is working even after a reboot.  That's not to say it won't break again.  It was working after the March update for a while.

**Comment by byteframe** [comment] 2015-06-26 01:55
I've never had audio stream from a linux host, but the windows host does it. Both times with the same linux client. I don't run pulseaudio, does this matter? How exactly does the streaming host transmit the audio? Does it record it with the video or pipe it over the network with pulseaudio or something like that? The small amount of (pulse)audio errors I see in the logs most likely originate from the game (hl2mp). Can't wait to game on the couch, but I can't get a handle on this bug at all, and still presume its my fault or my distro is too old.

**Comment by Daverball** [comment] 2015-11-18 11:38
> I've never had audio stream from a linux host, but the windows host does it. Both times with the same linux client. I don't run pulseaudio, does this matter? How exactly does the streaming host transmit the audio? Does it record it with the video or pipe it over the network with pulseaudio or something like that? The small amount of (pulse)audio errors I see in the logs most likely originate from the game (hl2mp). Can't wait to game on the couch, but I can't get a handle on this bug at all, and still presume its my fault or my distro is too old.

I can confirm that for some reason the audio will only be streamed with pulseaudio running on a linux host, but even then it is a highly volatile matter. Some games, when started, will permanently break audio for the current streaming session until you restart the client and everything.

An example for a game that properly keeps audio going would be Towerfall, and an example for one that does not would be Monaco. Generally it seems to be games where the desktop flashes for a split second instead of seeing a smooth transition from big picture to the game in fullscreen.

My best guess is that the switch to full desktop capturing for that short moment is what breaks it.

**Comment by roemhildtg** [comment] 2016-03-12 07:03
This just started happening to me on Xubuntu 15.10 x64. 
No audio at all from steam interface or streaming. 
The steam Audio settings show "Unable to connect to Audio source".

**Comment by kisak-valve** [comment] 2018-06-15 12:28
Hello, is anyone still experiencing this issue with an up to date system and pulseaudio running?

**Comment by kisak-valve** [comment] 2018-07-25 14:03
Closing pending feedback.

**Closed by kisak-valve** 2018-07-25 14:03 UTC
Labels: Need Retest, Streaming, reviewed
