### ISSUE TITLE
Suspend(?) causes network issues with the steam client

### ISSUE THREAD

**Issue by skeyl** [ValveSoftware/steam-for-linux#4016] opened 2015-09-13 17:50 UTC
I wasn't able to get more information (such as `strace` output or anything like that). But, my games were stuck in "update queued" state and would not get cloud saves. I've experienced this issue a lot and noticed if I restart steam (no updates applied) that the games in update queued state start and they're able to connect to the steam cloud and "play online". I'm *assuming* this is because my desktop sleeps.

**Comment by Tele42** [comment] 2015-09-14 13:23
Duplicate of #474.

**Comment by gdrewb-valve** [comment] 2015-10-12 16:45
Closing duplicate.

**Closed by gdrewb-valve** 2015-10-12 16:45 UTC
