### ISSUE TITLE
Steam client fails to launch for unclear reason, regression

### ISSUE THREAD

**Issue by amonakov** [ValveSoftware/steam-for-linux#7106] opened 2020-05-12 20:29 UTC
#### Your system information

* Steam client version (build number or date): 1588032389
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: No
* Have you checked for system updates?: No

#### Please describe your issue in as much detail as possible:
After an auto-update a few weeks ago Steam client fails to properly launch on my system. It offers the login screen and 2fa window, but after that I see a spew of `
Assertion Failed: !bSharedKVSymbols` messages and it apparently hangs. Normally it would present the client UI next, but that doesn't happen.

I have attempted to wipe and re-download the client, but the issue remains: even with a clean install, it hangs the same way. Even though it worked fine for years on that machine.

Log with `DEBUGGER=gdb STEAM_DEBUG=1`: https://gist.github.com/amonakov/7f8e9cbf29c4f1619cb487dea6317634

What does `Assertion Failed: !bSharedKVSymbols` imply? Can I help debug this further?

**Comment by gedia** [comment] 2020-06-10 02:34
Same here, happened after world update, but steam also updated at the same time so not sure what caused it...

**Comment by tacksetB** [comment] 2020-06-10 09:43
Same here. Problem appears after a world update few days ago. I was not using steam runtime until now, but had to switch to STEAM_RUNTIME=1, in order to make Steam start again.

**Comment by gedia** [comment] 2020-07-22 22:18
This is most probably a duplicate of #5014

**Comment by kisak-valve** [comment] 2022-11-04 15:48
Hello @amonakov, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment] 2022-12-09 19:44
Closing as outdated.

**Closed by kisak-valve** 2022-12-09 19:44 UTC
Labels: Steam client, Need Retest, Distro Family: Gentoo
