### ISSUE TITLE
Rapid flickering on library page

### ISSUE THREAD

**Issue by Jayman2000** [ValveSoftware/steam-for-linux#5805] opened 2018-10-01 22:07 UTC
#### Your system information

* Steam client version (build number or date): Sep 26 2018, at 22:21:27
* Distribution (e.g. Ubuntu): Kubuntu 18.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: No

#### Please describe your issue in as much detail as possible:
I was in my library and everything bellow the words "Locked achievements" began to flicker. The achievement icons would switch between showing 8 and 9 icons. This caused the "LINKS" and "CATEGORIES" sections on the side bar to shift back and forth. The "RECENT NEWS" section also expanded and contracted. Wiggling the mouse made it flicker faster. Here's a video of it happening (https://youtu.be/5IORBmD6Q_c). Switching to another game caused the flickering to stop.

#### Steps for reproducing this issue:
I have not been able to reproduce the issue.

**Comment by kisak-valve** [comment] 2021-02-26 16:13
Hello @Jayman2000, have you seen this issue since the initial report?

**Comment by Jayman2000** [comment] 2021-02-26 16:30
No.

**Comment by kisak-valve** [comment] 2021-02-26 16:39
Thanks, let's treat this as a one off fluke due to a lack of some way to reproduce the issue. Closing.

**Closed by kisak-valve** 2021-02-26 16:39 UTC
Labels: Need Retest, Steam client
