### ISSUE TITLE
libGL.so error with nVidia 435 on Ubuntu 18.04(using Proprietary GPU Drivers PPA)

### ISSUE THREAD

**Issue by DaiQiangReal** [ValveSoftware/steam-for-linux#6517] opened 2019-09-19 17:57 UTC
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1568860339)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Installing breakpad exception handler for appid(steam)/version(1568860339)
Installing breakpad exception handler for appid(steam)/version(1568860339)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  152
Serial number of failed request:  49
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  152
Value in failed request:  0x0
Serial number of failed request:  48
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  152
Serial number of failed request:  50
xerror_handler: X failed, continuing
crash_20190920014229_1.dmp[31084]: Uploading dump (out-of-process)
/tmp/dumps/crash_20190920014229_1.dmp
/home/daiqiang/.local/share/Steam/steam.sh: 行 720: 31069 段错误               (核心已转储) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20190920014229_1.dmp[31084]: Finished uploading minidump (out-of-process): success = yes
crash_20190920014229_1.dmp[31084]: response: CrashID=bp-cc49ed0e-98db-44ee-9867-1e3702190919
crash_20190920014229_1.dmp[31084]: file ''/tmp/dumps/crash_20190920014229_1.dmp'', upload yes: ''CrashID=bp-cc49ed0e-98db-44ee-9867-1e3702190919''

**Comment by kisak-valve** [comment] 2019-09-19 18:01
Hello @DaiQiangReal, can you verify any 32 bit opengl like `glxinfo` from `mesa-utils:i386` works?

Please check if you have the `libnvidia-gl-435:i386` package installed with something like `apt policy libnvidia-gl-435:i386`.

**Comment by emma-goldman** [comment] 2019-11-27 16:31
I have a similar issue but with nvidia-driver-440.

The problem is I can't `sudo apt install nvidia-driver-440:i386` without being told that it would uninstall the 64bit version (alongside cuda 10, and a bunch of other 64bit only nvidia stuff)

If I extract the libnvidia-gl-440:i386 from the driver package could I just copy that over to /appropriate/path/ (usr lib?) and run steam with `env LD_PRELOAD=/appropriate/path` ?

**Comment by gaborpapp** [comment] 2019-12-11 21:34
I'm experiencing the same on Fedora 30 with NVidia 4.40. It's an optimus laptop. Steam runs fine with the Intel card. When switching to the discrete gpu with nvidia-xrun steam crashes.

```
Running Steam on fedora 30 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/gabor/.local/share/Steam/ubuntu12_32/steam
Installing breakpad exception handler for appid(steam)/version(1575604565)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Installing breakpad exception handler for appid(steam)/version(1575604565)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  150
Serial number of failed request:  51
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  150
Value in failed request:  0x0
Serial number of failed request:  50
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  150
Serial number of failed request:  52
xerror_handler: X failed, continuing
assert_20191211222204_1.dmp[19214]: Uploading dump (out-of-process)
/tmp/dumps/assert_20191211222204_1.dmp
/home/gabor/.local/share/Steam/steam.sh: line 722: 19185 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20191211222204_1.dmp[19214]: Finished uploading minidump (out-of-process): success = yes
assert_20191211222204_1.dmp[19214]: response: CrashID=bp-872c1b6a-d325-4255-84cb-d4c142191211
assert_20191211222204_1.dmp[19214]: file ''/tmp/dumps/assert_20191211222204_1.dmp'', upload yes: ''CrashID=bp-872c1b6a-d325-4255-84cb-d4c142191211''
```

**Comment by gaborpapp** [comment] 2019-12-11 21:46
I had to install the 32-bit nVidia libraries. In Fedora this worked for me:
```
sudo dnf install xorg-x11-drv-nvidia-libs.i686
```

**Comment by kisak-valve** [comment] 2022-01-21 22:10
Closing as outdated. It's still possible to install the NVIDIA proprietary driver with the driver's 32 bit userspace libraries missing, but that's a distro packaging issue, not a Steam client issue.

**Closed by kisak-valve** 2022-01-21 22:10 UTC
Labels: NVIDIA drivers, Distro Family: Ubuntu
