### ISSUE TITLE
Username of "catbot" triggers VAC ban

### ISSUE THREAD

**Issue by MrStonedOne** [ValveSoftware/steam-for-linux#5314] opened 2018-01-02 01:58 UTC
So when you have an username on your GNU/Linux machine containing "catbot", you get a VAC ban.

**Comment by kisak-valve** [comment] 2018-01-02 02:06
Hello @MrStonedOne, VAC issues are not handled on these issue trackers in any capacity. Closing as a duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/2475.

**Closed by kisak-valve** 2018-01-02 02:06 UTC
