### ISSUE TITLE
Dealing with binaries of the same game for different OSes

### ISSUE THREAD

**Issue by jack980517** [ValveSoftware/steam-for-linux#4709] opened 2016-11-17 22:30 UTC
#### Your system information

* Steam client version:
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
If the steamapps folder of the Windows Steam is copied or linked to that of the Linux Steam, the Linux Steam should just download the Linux binaries for games that supports Linux and keep the Windows binaries untouched. This was the behavior at some time in 2014 when I attempted it, and this is what I want because this produced a copy of the game directory that could work under both Windows and Linux. But now when I just attempted it again, I found that the Linux Steam is removing the Windows binaries. This is inconvenient for players who dual-boot Windows and Linux, as under this new behavior, players can only download the corresponding binaries every time they switch between OSes (which would decrease the life of the hard disk), or keep two copies of their local library (which is a waste of disk space), both of which are not good. Thus, I suggest reverting to the old behavior, which is keeping binaries for different OSes. I understand that this is not a bug, but a bad design; I also understand that this probably happens for Windows and Mac versions of Steam too, but I don't know where would be more appropriate to report this issue.

#### Steps for reproducing this issue:

1. Link or copy the `steamapps` folder, or just the `appmanifest_xxx.acf` file and the installation folder of the corresponding game (which must support Linux), from the Windows Steam's location to the Linux Steam's location
2. Launch Linux Steam
3. Wait for the "Update" to finish download; or, if the game doesn't start "updating", click "verify integrity of game cache" to start the download
4. Check the game's installation directory to see the Windows binaries gone.

**Comment by gdrewb-valve** [comment] 2016-11-17 22:43
Duplicate of #123.  Nothing has changed on that front as far as I know, sharing game libraries between operating systems is not supported and there aren't any plans to support it.

**Closed by gdrewb-valve** 2016-11-17 22:43 UTC
