### ISSUE TITLE
Free-to-play games don't appear in library after client reinstallation

### ISSUE THREAD

**Issue by smcv** [ValveSoftware/steam-for-linux#6348] opened 2019-06-28 17:23 UTC
#### Your system information

* Steam client version (build number or date): Jun 17 2019, 23:31:27 (1560817063)
* Distribution (e.g. Ubuntu): multiple (reproduced under SteamOS, Debian and unofficial Flatpak)
* Opted into Steam client beta?: No
* Have you checked for system updates?: No

#### Please describe your issue in as much detail as possible:

After installing the Steam client on a new machine, free-to-play games that I already played on another machine don't appear in the Library tab.

I would have expected them to be treated the same as games that I "bought" for zero cost during a free games promotion, meaning they appear in my library alongside games that I have paid for or registered using a key, until/unless I use right-click -> Set Categories -> Hide this game.

#### Steps for reproducing this issue:

* Have a Steam account already
* Install and play some free-to-play games, e.g. Floating Point and Team Fortress 2
* Install the Steam client in a new directory: either install it on a new computer, or as a different Unix user, or switch to or from the unofficial Flatpak
* Go to the Library tab in the newly-installed Steam client

#### Expected result:

* Paid-for games appear in my Library
* Free games that I previously added to my Library also appear

#### Actual result:

* Paid-for games appear in my Library as expected
* Free games that I previously added to my Library *do not* appear
* If I search for one of the free games in the Store tab and visit its Store page, it appears that a record has been kept that I have installed it in the past: there is a green banner reading `[IN LIBRARY] Floating Point is already in your Steam library`, and a light blue `Play now` button. This is not the same as a free game that I have never played, which has a green `Play Game` button in the same style and position as the usual `Add to Cart` button.
* If I click the `Play now` button, the game appears in my Library, but disappears if I uninstall it.

**Comment by kisak-valve** [comment] 2019-06-28 17:39
Hello @smcv, looks like this is the intended behavior from around 2014, and a feature request for the older behavior is already being tracked at #3331. Closing in favor of the existing feature request.

**Closed by kisak-valve** 2019-06-28 17:39 UTC
