### ISSUE TITLE
steamwebhelper crash: trap invalid opcode in steamclient.so on AMD64

### ISSUE THREAD

**Issue by fatalhalt** [ValveSoftware/steam-for-linux#4880] opened 2017-03-02 23:28 UTC
#### Your system information

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Athlon(tm) 64 FX-57 Processor

Operating System Version:
    Linux (64 bit) (ArchLinux)
    Kernel Name:  Linux
    Kernel Version:  4.9.11-2-zen
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11901000
    X Window Manager:  KWin (KDE5)
    Steam Runtime Version:  steam-runtime-beta-release_2016-12-05
    
Video Card:
    Radeon HD6870
    Driver:  X.Org Gallium 0.4 on AMD BARTS (DRM 2.48.0 / 4.9.11-2-zen, LLVM 3.9.1)
    Driver Version:  3.0 Mesa 17.0.0
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 85 Hz
    VendorID:  0x1002
    DeviceID:  0x6738
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1600 x 1200
    Desktop Resolution: 1600 x 1200
    Primary Display Size: 15.59" x 11.69"  (19.49" diag)
                                            39.6cm x 29.7cm  (49.5cm diag)
    Primary VRAM: 1024 MB

Memory:
    RAM:  2003 Mb

#### Please describe your issue in as much detail as possible:

This is happening on a fresh install. Invalid opcode shipped in steamclient.so blob is causing steamwebhelper to crash/respawn endlessly bringing my system down to knees and putting 100% disk load leading to 100% iowait and avg load up to 30.0, 30.0, 30.0

I have seen 'trap invalid opcode' problem before on Linux but that was on very new Intel Haswell CPU that needed microcode update to be loaded with kernel to correct that. K8 CPUs didn't have any:
[    2.187202] microcode: AMD CPU family 0xf not supported

dmesg:
[  210.358959] traps: steamwebhelper[1411] trap invalid opcode ip:7f5f6617bcdd sp:7ffce4c706c0 error:0
[  210.358964]  in steamclient.so[7f5f657ec000+120f000]

The Steam itself is working fine and I can play HL2, but obviously things like browsing Community Hub is not working.

I have attached a coredump of the crash.

#### Steps for reproducing this issue:

1. Launch either Steam-runtime or Steam-native
2. Observe steamwebhelper endlessly crashing and spawning
[core.steamwebhelper.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/815351/core.steamwebhelper.tar.gz)

**Comment by kisak-valve** [comment] 2017-03-02 23:50
This is most likely a lack of CMPXCHG16B support in that processor. Closing as a duplicate of #4196.

**Closed by kisak-valve** 2017-03-02 23:50 UTC
