### ISSUE TITLE
Cannot connect to Friends Network

### ISSUE THREAD

**Issue by SethDusek** [ValveSoftware/steam-for-linux#6042] opened 2019-01-20 11:05 UTC
#### Your system information

* Steam client version (build number or date): 4 Jan 2019 
* Distribution (e.g. Ubuntu): Ubuntu 18.10
* Opted into Steam client beta?: [Yes/No] No 
* Have you checked for system updates?: [Yes/No] Yes

[System info gist](https://gist.github.com/SethDusek/fc88076f4a4bf370aeb832c119d5b0ab)

#### Please describe your issue in as much detail as possible:

Ever since yesterday, I have been unable to connect to the friends network, which means I'm permanently marked offline. I've tried the following things to try and fix this

- Reinstalled Steam
- Opted in to the beta version in hopes of a fix but then opted out
- Installed flatpak version of steam
- Changed DNS settings
- Changed internet connections from my home wifi to a 3g hotspot from my phone
- Reset steam using steam --reset
- Launched steam using -nofriendsui

Here is my [connection_log.txt](https://gist.github.com/SethDusek/4a04080c17b0d1ca937f86e5f805f780)

In big picture I can see which of my friends are online, but I can't message them or see messages from them, but I could strangely enough broadcast their game.
#### Steps for reproducing this issue:

1. I don't know, since I'm not sure this issue affects anyone else
2. 
3. 

edit: I should also mention, the game coordinator works inside of Dota 2, and Dota 2 also doesn't give any error like "Lost connection to steam" so this looks like a friends network only thing. However I can't really party with anyone unless they share their party status in a chat channel, because all my friends see me as offline and vice versa

**Comment by h1z1** [comment] 2019-01-21 11:01
Curious what made you look at timezone?

**Comment by kisak-valve** [comment] 2019-01-21 13:49
Closing as a duplicate of #5612.

**Closed by kisak-valve** 2019-01-21 13:49 UTC
Labels: Steam client

**Comment by Israphel** [comment] 2019-02-10 17:47
> Hi, I seem to have found a solution to my problem. Apparently steam cannot handle binary $TZ formats. Changing the TZ enviroment variable to my timezone and launching steam made it work. I think the following solutions could be added:
> 
>     * Add an error message when this error occurs. Chrome and Firefox also have similar error messages for when your system clock is messed up.
> 
>     * Add support for whatever this binary timezone format is

So what do I have to do to get the chat working? I still don't get it

**Comment by SethDusek** [comment] 2019-03-15 09:15
> > Hi, I seem to have found a solution to my problem. Apparently steam cannot handle binary $TZ formats. Changing the TZ enviroment variable to my timezone and launching steam made it work. I think the following solutions could be added:
> > ```
> > * Add an error message when this error occurs. Chrome and Firefox also have similar error messages for when your system clock is messed up.
> > 
> > * Add support for whatever this binary timezone format is
> > ```
> 
> So what do I have to do to get the chat working? I still don't get it

You can edit your /usr/bin/steam file and change the TZ variable to something else. For example for me I added 

`TZ="Asia/Karachi"` to my /usr/bin/steam file.
