### ISSUE TITLE
Adding a windows-only game to library breaks the library

### ISSUE THREAD

**Issue by bfops** [ValveSoftware/steam-for-linux#4609] opened 2016-08-28 18:52 UTC
#### Your system information
- Steam client version: Aug 23, API v017, package version 1471977975
- Distribution (e.g. Ubuntu): OSX
- Opted into Steam client beta?: [Yes/No] No
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

Be on OSX. Try to install a Windows-only game. Steam servers then think that the game is in the library (removing the "add to library button"), but it will not show up under Windows or OSX. This is particularly annoying because it's very easy to forget about a game you think you've got saved in your library..

**Comment by kisak-valve** [comment] 2019-07-26 14:45
Hello @bfops, trying to install a game on an OS the game doesn't support should give a dialog box with a message like `An error occurred while updating <game name> (invalid platform)` and I can't reproduce this issue on my Mac test box.

Are you still able to reproduce this scenario on an up to date system?

**Comment by kisak-valve** [comment] 2019-08-30 19:55
Closing as out-of-scope for the steam-for-linux issue tracker. Please use [Steam Support](https://help.steampowered.com/en/) for issues with the Mac client.

**Closed by kisak-valve** 2019-08-30 19:55 UTC
Labels: Need Retest, reviewed
