### ISSUE TITLE
[Steam Deck] Setting game resolution for a specific non-steam shortcut sets it for all of them

### ISSUE THREAD

**Issue by popsUlfr** [ValveSoftware/steam-for-linux#8950] opened 2022-11-24 10:31 UTC
#### Your system information

* Steam client version (build number or date): 1669071089 (Sun, Nov 20 01:07 UTC +01:00)
* Distribution (e.g. Ubuntu): SteamOS on the Steam Deck
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Setting a game resolution for a specific non-steam application shortcut sets it for all non-steam shortcuts

#### Steps for reproducing this issue:

1. Add two or more non-steam shortcuts to Steam
2. Change the game resolution in the properties for one of them
3. All non-steam game shortcuts will have the same game resolution set

**Comment by Nonary** [comment] 2022-12-25 18:17
This is caused by the fact that all non steam games have the same AppID. So in order for them to fix this issue they would have to fix that.

https://github.com/ValveSoftware/steam-for-linux/issues/8474

**Comment by popsUlfr** [comment] 2022-12-26 11:33
> This is caused by the fact that all non steam games have the same AppID. So in order for them to fix this issue they would have to fix that.
> 
> #8474

I'm not sure, this worked at one point for me. I could have one non-steam app to output to 1080p while all others were output at the default 800p.

**Comment by Sterophonick** [comment] 2023-02-19 06:49
This appears to have been worked around in Beta `1676680477`. Anyone else confirm this?

**Comment by kisak-valve** [comment] 2023-03-24 23:14
Closing per the last comment.

**Closed by kisak-valve** 2023-03-24 23:14 UTC
Labels: Steam client, Need Retest, Distro Family: SteamOS, non-Steam application
