### ISSUE TITLE
Since latest Steam beta the Overlay does not open up when you click on "Invite Friends" ingame

### ISSUE THREAD

**Issue by NoXPhasma** [ValveSoftware/steam-for-linux#4039] opened 2015-09-24 21:30 UTC
In the Steam Beta client you can't invite friends anymore, because the overlay does not open up. This is not game specific, it happens to all games I tried. For example: Sanctum 2 and Outland.

To reproduce: open up game, start a online lobby, click on the invite friends button. 

Linux Mint 17.2 x64
Steam Packet Version: 1443052401

**Comment by sizeofbool** [comment] 2015-09-25 16:29
I second to this. Features worked a few updates of Beta Steam Client back.
I have same problem with Left 4 Dead 2, when I try to open profile of players while being in lobby. (See screen-shot.)
![ss1](https://cloud.githubusercontent.com/assets/6904856/10106019/a73c340e-63cb-11e5-97af-6d998fb06177.png)

My specs:
*Operating System Version:*
    Debian GNU/Linux 8.2 (jessie) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.16.0-4-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-06-12
*Video Card:*
    Driver:  NVIDIA Corporation GeForce GTX 560 Ti/PCIe/SSE2
    Driver Version:  4.4.0 NVIDIA 340.76
    OpenGL Version: 4.4

**Comment by ramma** [comment] 2015-10-04 08:43
Same problem here. Happens with any game where parts of the interface would normally open the overlay (eg "Sell on Market" buttons in Dota 2 and CSGO).

**Comment by sizeofbool** [comment] 2015-10-22 00:15
Can't reproduce this issue anymore after latest Steam Client Beta update(22.10.2015).

**Comment by NoXPhasma** [comment] 2015-10-25 06:26
[**@sizeofbool**](https://github.com/sizeofbool) commented on [22. Okt. 2015 02:15 MESZ](https://github.com/ValveSoftware/steam-for-linux/issues/4039#issuecomment-150059942 "2015-10-22T00:15:34Z - Replied by Github Comment Enhancer"):
> I can't reproduce this issue anymore after latest Steam Client Beta update(22.10.2015).
Yes, in the current Beta it's fixed. But even we reported it, it landed in the stable branch, typical Valve ;)

**Comment by sizeofbool** [comment] 2015-10-26 11:19
@NoXPhasma i think we reported it when person responsible for bug tracking was on vacation, so this bug got into stable branch.
Anyway, you probably should close this fixed issue.

**Closed** 2015-10-26 11:25 UTC
Labels: reviewed
