### ISSUE TITLE
[Left 4 Dead 2] minimize = game locks up after Steam update today

### ISSUE THREAD

**Issue by undeference** [ValveSoftware/steam-for-linux#4377] opened 2016-03-29 03:41 UTC
Earlier today, I played a game of Left 4 Dead 2 and everything worked as expected. Then I noticed the Steam update thing and clicked the restart Steam button. Now when I try to play Left 4 Dead 2, it stops responding entirely if I switch programs / minimize it and have to manually kill it.

Possible duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/4369

**Comment by steamlinux** [comment] 2016-03-29 04:26
oh my god, I have this trouble in steam beta, and for play in l4d2, i switch steam from beta to stable
after today update on steam stable l4d2 freezed when minimized

**Comment by dbpalan** [comment] 2016-03-29 04:36
I have the same issue but this have been occured for couple of weeks after steam update.  Sorry did not have exact date of update.

Left 4 Dead 2
Ubuntu 14.04 64-bit
nVidia proprietary driver 354 / 362

**Comment by buckwangs** [comment] 2016-03-30 19:00
On Fedora 23 (KDE Spin) 64, Nvidia 361.28 can no longer lose focus since March 29th. I was always able to alt+tab BUT THIS IS IMPORTANT alt+tab isn't the cause of the problem (just a quick way to see the problem).

Whether the game is full screen or windowed does not matter. If you lose focus of L4D2 (windowed or not) the game just hangs. I was always able to alt+tab since L4D2 came to Linux. The game always lost focus gracefully and gained it back without a problem. Starting on March 29th the game can no longer lose its focus.

Please advise on how I can further help resolve this issue.

**Comment by steamlinux** [comment] 2016-03-31 10:41
if I understand correctly, this bug appeared simultaneously with the emergence of steam overlay with vulkan
1st in steam beta, 2nd in stem public

**Comment by jpleau** [comment] 2016-04-11 23:37
Same issue here, I use i3 on Debian unstable

If the game loses focus, I cannot go back to it, either in full screen, windowed mode.

Hopefully this can be fixed!

**Comment by steamlinux** [comment] 2016-04-12 00:25
game normally minimizied when playing intros video
and game normally hide with Super+H

**Comment by buckwangs** [comment] 2016-05-04 06:37
Fellas, here's a quick **temporary** workaround that might work for you. Rename **~/.local/share/Steam/ubuntu12_32/libSDL2-2.0.so.0** to anything you like _(You need to do this while Steam is already running)_ and then launch the game. Good luck.

The reason you need Steam running is because every time Steam starts up, this file is automatically downloaded and put back. This helpful tip was given to me by a friend that got it from a friend. Thank [SteamLUG](https://steamlug.org/) for the tip :)

**Comment by steamlinux** [comment] 2016-05-04 07:30
this bug fixed on Steam Beta, nothing need to remove.

**Comment by undeference** [comment] 2016-05-04 14:05
(In re: @buckwangs)
> Rename ~/.local/share/Steam/ubuntu12_32/libSDL2-2.0.so.0

I was able to reproduce this


(In re: @steamlinux)
> this bug fixed on Steam Beta

I was also able to reproduce this

**Comment by tremby** [comment] 2016-10-18 00:33
This appears to be fixed with the latest update.

**Closed** 2016-10-19 00:10 UTC
Labels: reviewed
