### ISSUE TITLE
Can't see video trailer downlaoded 

### ISSUE THREAD

**Issue by Ruthubuntu** [ValveSoftware/steam-for-linux#904] opened 2013-01-26 12:03 UTC
Steps:
-Choose a game with some trailer and go to Watch all trailer (for exemple i tested Counter-Strike: Global Offensive , Half-Life 2) . 
- Select one trailer and click on Downlaod
- After downlaod, go to library -> Media and click to play
- Error message " Error launching media" with No launch media file spe..." as title
  ![Capture du 2013-01-26 12:02:17](https://f.cloud.github.com/assets/3092262/99708/fd5fb0f6-67af-11e2-9a4b-7cbeabf16d4a.png)
  If i browse, i could find it on ~/.local/share/Steam/SteamApps/common 
  All trailers are on one folder where we can found :
- smp.exe ( an exe on linux o_O )
- an windows media Video (wmv), i can read it with totem ( default mulimedia player on Ubuntu 12.04) or VLC
  ![Capture du 2013-01-26 13:02:09](https://f.cloud.github.com/assets/3092262/99710/4a7cad30-67b0-11e2-894b-0df096322ee1.png)

Expected: 
see the video when i click play:
- use gstreamer for read it
- use an open codec for a native play on Linux: Vorbis/ogg or WebM for exemple

I don't have Flash (Flash is a problem of security)
Steam Built: Jan 24 2013 at 18:37:04
Steam API: v012
Processor Information:
    Vendor:  GenuineIntel
    Speed: 2266 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-37-generic
    X Server vendor:  The X.Org Foundation
    X Server release:  11103000

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ironlake Mobile x86/MMX/SSE2

```
Driver Version:  2.1 Mesa 9.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x8086
DeviceID:  0x46
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13,54" x 7,60"  (15,51" diag)
                                        34,4cm x 19,3cm  (39,4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: 

Memory:
    RAM:  3753 Mb

Miscellaneous:
    UI Language:  English
    LANG:  fr_FR.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  409142 Mb
    Largest Free Hard Disk Block:  69772 Mb

Installed software:

Recent Failure Reports:
    Sat Jan 26 10:54:12 2013 GMT: file ''/tmp/dumps/assert_20130126115405_1.dmp'', upload yes: ''CrashID=bp-91139212-03cc-4d27-9531-cd3e82130126''

**Comment by kisak-valve** [comment] 2017-03-29 22:49
Closing as the mentioned transition occurred a fair while ago and I am unable to reproduce this issue.

**Closed by kisak-valve** 2017-03-29 22:49 UTC
Labels: Feature Request, reviewed, Steam database
