### ISSUE TITLE
Shutting off Dualshock 4 sometimes causes crash

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#5238] opened 2017-11-10 23:29 UTC
Arch Linux & Solus 3

Shutting off my Dualshock 4 controller by holding the center button and pressing triangle causes steam to crash. Reproducible about half of the time. This doesn't happen when the controller is connected with USB, only bluetooth.

**Comment by kisak-valve** [comment] 2017-11-10 23:35
Hello @GitRASQ, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. In particular, if you can find any CrashIDs or minidumps related to this issue, please include them.

**Comment by GitRASQ** [comment] 2017-11-11 02:08
system info:
https://gist.github.com/GitRASQ/5d3b42cc04eb0f47ffc67256a6aa0804

some stuff I found in /tmp/dumps that looks like it may be relevant:
[tmp-dumps.zip](https://github.com/ValveSoftware/steam-for-linux/files/1463186/tmp-dumps.zip)

I have 5 coredumps in /var/lib/systemd/coredump/ but they're 60-90MB. Do you want these?

**Comment by kisak-valve** [comment] 2017-11-11 02:32
For reference, the crash_20171109231219_1.dmp (CrashID=bp-632e5011-21c9-4d3c-957d-820662171110) and crash_20171110152555_1.dmp (CrashID=bp-d646de83-ef9d-4676-95dc-9679b2171110) are a SIGABRT in linux-gate.so, the others are DUMP_REQUESTED in crashhandler.so. 

Let's hold off on core dumps for now. Just a guess, but can you try completely closing steam, then run `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` in a terminal and see if this affects the issue's behavior?

**Comment by GitRASQ** [comment] 2017-11-11 04:26
The crashes still occur, sometimes when I connect the controller as well. I don't remember that happening before.

 I got these messages dozens of times:

    process 28566: arguments to dbus_connection_ref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2656.
    This is normally a bug in some application using the D-Bus library.
    process 28566: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2794.
    This is normally a bug in some application using the D-Bus library.

I also get this whenever I press center button and triangle:

    (steam:29183): GLib-CRITICAL **: g_error_free: assertion 'error != NULL' failed

steam output when crashing:
https://gist.github.com/GitRASQ/736a30475d53fafb8a6a40557ef8f892

**Comment by GargleBlaster259** [comment] 2019-07-13 09:43
I'm experiencing the exact same issue (Kernel: 5.2.0-arch2-1-ARCH) using steam-runtime: shutting off my DS4 v2 with PS + Triangle while connected via Bluetooth crashes Steam with a ~ 50% "success rate". Feel free to ask for additional information and I'll supply what I can.

**Comment by kisak-valve** [comment] 2019-07-19 14:24
Hello @GargleBlaster259, can you check if you're still experiencing this issue on an up to date system?

"Fix crash caused by audio cards with no active port set" in the [2019-07-16](https://store.steampowered.com/news/52467/) Steam client update may have had an effect for Dualshock 4 users.

**Closed** 2020-04-10 13:56 UTC
Labels: Distro Family: Arch, Distro Family: Solus, General controller / Steam Input, Need Retest, Steam client
