### ISSUE TITLE
Steam is entirely just a black window

### ISSUE THREAD

**Issue by Citrom67** [ValveSoftware/steam-for-linux#8359] opened 2022-01-25 19:03 UTC
#### Your system information

* Steam client version (build number or date):  1642451672
* Distribution (e.g. Ubuntu): Manjaro 
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I expected when I open up steam, to you know, look like steam, but it is just black, no UI, no colors, just black...
Though the UI itself works, I just can't see it, even tho zenity is installed as I've read in previous issues that it relies(/relied) on it somewhat.

And interestingly enough, when I press alt+f2 and launch steam via the steam command or from terminal, the UI loads as normal, so it only happens when I open from desktop icon, or the cinnamon menu.

[System Information Gist](https://gist.github.com/Citrom67/70706beecc34666ec73051b1270eb179)

#### Steps for reproducing this issue:

1. Open Steam
2. Wait for it to open up
3. Witness the darkness
![Screenshot from 2022-01-25 20-02-16](https://user-images.githubusercontent.com/54332606/151041983-115fc9f3-f5c5-4b30-ba51-c83e64ff08a7.png)

**Comment by kisak-valve** [comment] 2022-01-25 19:16
Hello @Citrom67, would you happen to be using an Optimus laptop which is configured to run X on the NVIDIA GPU? Please run Steam from a terminal where it renders, then copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

I suspect you're seeing something similar to #8179.

Steam does not depend on zenity, it's only used to show some messages on failure paths.

**Comment by Citrom67** [comment] 2022-01-25 19:22
Hello @kisak-valve, I don't use a laptop, but I do own a GTX 750Ti, I've uploaded the [gist](https://gist.github.com/Citrom67/70706beecc34666ec73051b1270eb179) here. 
Hope you can figure out something from it

**Comment by kisak-valve** [comment] 2022-01-25 19:29
Maybe give #8069 a read and see if something similar has happened on your system? There's not many things that could differ between starting Steam from a desktop shortcut and from a terminal. The question which should be asked is what is the difference in the environment that Steam is run in between the two.

**Comment by Citrom67** [comment] 2022-01-25 20:07
[Desktop icon](https://gist.github.com/Citrom67/1d5437a6314674a29588e7c762edd1ed) log
Interestingly enough I don't get any log out of steam when I launch it in the terminal for some reason

But I tried modifying the command the icon executes, and even tho I execute the same command just from the terminal, it doesn't work, the black screen still stays

**Comment by Citrom67** [comment] 2022-01-25 20:31
A possible workaround I've found is to create a `steam-launcher.sh` file and put it in `/bin/` with the following lines:
```
#!/bin/bash

steam
```
you can ofc put `steam-runtime` too but it works for me with only `steam`

And then make the Steam icon in `/usr/share/applications ` point to that file (`/bin/steam-launcher.sh`)

It pretty much solves it for me, and I can launch it with the icon just like old times :D

**Comment by wtjones** [comment] 2022-01-30 15:26
I encountered this issue when upgrading Manjaro from 5.10.93-1 to 5.15.16-1. I was able to solve it by switching from video-nvidia to video-nvidia-470xx.

**Comment by Citrom67** [comment] 2022-01-31 23:19
Since then I switched back to Linux Mint
I was only trying out distros anyways, but it seems Im gonna stick with ubuntu or debian for a while

If anyone will have a clear solution that works for multiple people, I'll edit it into the post and close the issue tho

**Comment by kisak-valve** [comment] 2022-01-31 23:35
Hello @Citrom67, that's an invitation for this issue report to become a catch all for too many lookalike issues that need to be investigated separately. If someone else comes across a similar issue, it should be evaluated separately.

Closing per the last comment.

**Closed by kisak-valve** 2022-01-31 23:35 UTC
Labels: Steam client, Distro Family: Arch

**Comment by SheMelody** [comment] 2024-04-09 15:31
I'm having the same exact problem, except I'm using Arch Linux, I quadruple checked all dependencies and packages and everything looks great, still Steam just shows a black screen.

**Disabling hardware acceleration fixes it, but I want my GPU to render the UI. The reason why it works from a ALT + Fx terminal is that it doesn't maybe expose the GPU properly, so it falls back to disabled HW acceleration.**

Is there any viable workaround for this, other than disabling hardware acceleration? I don't seem to be able to find this problem easily, but I can still reproduce this on every single system right now, was fine until 4 months ago, I think this should get more visibility.

**Comment by gogromat** [comment] 2025-05-21 03:03
If you still have window settings available you can attempt clicking on "Big Picture".
After it launches I had to close Steam again, but after relaunching Steam once more all windows immediately went back to normal (no longer black boxes).

**Comment by Jcloud67** [comment] 2025-07-17 00:21
I just ran into this bug, Manjaro 25.0 xfce. Not sure if it's connected, but it happened after a reboot and I had changed my desktop resolution from 3840x1080 to 5120x1440 and was the first launching of Steam since resolution change.  I was able to resolve the issue by:
1. Closing Steam client.
2. Opening terminal window
       rm -rf ~/.local/share/Steam/clientui/
3. Restarting Steam client
