### ISSUE TITLE
Limited CJK(Chinese-Japanese-Korean) input solution

### ISSUE THREAD

**Issue by BeyondLimitation** [ValveSoftware/steam-for-linux#4543] opened 2016-07-10 12:52 UTC
#### Your system information

* Steam client version: 1460023329
* Distribution (e.g. Ubuntu): Ubuntu Linux 16.04 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

As you know, we can not type Korean, Japanese and Chinese.
But recently i found the way to type CJK(Chinese-Japanese-Korean)!!

First, you must install the packages listed below.

libsl-ttf-gsf 
libsdl-ttf2.0-0
libsdl-ttf2.0-dev
libsdl1.2-dev
libsdl1.2debian
libsdl2-2.0-0
libsdl2-dev
libsdl2-gfx-1.0-0
libsdl2-ttf-2.0-0

After Installing, Start or restart your steam client.
Finally, Click **Controller** Icon (Right-top side) to enable **Big Picture** mod!
Now chat anyone with your prefer language.

![image](https://cloud.githubusercontent.com/assets/10960326/16713591/08ffc2f0-46e8-11e6-909d-371993f4becf.png)

As you can see. i can type korean!

![image](https://cloud.githubusercontent.com/assets/10960326/16713597/2bda3ac6-46e8-11e6-9c08-046fb05f89ab.png)

Another Picture! You can type **English** and **Korean**.
But I don't know why i must enable Big Picture mod to type CJK..

Because CJK typing only available at Big Picture mod...
I think Valve have to fix some part...

**Comment by gdrewb-valve** [comment] 2016-07-10 16:18
The regular client doesn't have any IME support so this isn't supposed to work, duplicate of #781.

**Closed** 2016-07-10 16:18 UTC
