### ISSUE TITLE
Steam triggering Gnome Remote Desktop on DualSense controller

### ISSUE THREAD

**Issue by alosarjos** [ValveSoftware/steam-for-linux#11197] opened 2024-08-19 17:00 UTC
#### Your system information

* Steam client version (build number or date): 1723685248
* Distribution (e.g. Ubuntu): ArchLinux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16663217/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:

Only when Steam is running, if using a DualSense PS5 Controller (In my case through Bluetooth), if I press the PlayStation button and move the left stick in any direction of Up, Right, Down, Left (Non diagonal), it triggers the remote desktop functionality of Gnome to share the screen

#### Steps for reproducing this issue:

1. Have Steam Running
2. Have a DualSense controller connected through Bluetooth
3. No need to be running a Game, just press PlayStation button and then move the left joystick in horizontal or vertical

If Steam is closed, it doesn't trigger anything, so looks like a Steam issue?

**Comment by kisak-valve** [comment] 2024-08-19 17:04
Hello @alosarjos, this is functionally a duplicate of #10442. Closing as a duplicate.

**Closed by kisak-valve** 2024-08-19 17:04 UTC

**Comment by fedoraBee** [comment] 2026-03-28 16:04
It looks like the Guide Button Chord settings are the culprit here. Adjusting these should prevent the dialog from appearing unexpectedly.

I’ve detailed the fix in this comment:
https://github.com/ValveSoftware/steam-for-linux/issues/10442#issuecomment-4148325257
