### ISSUE TITLE
Steam not opening after latest update

### ISSUE THREAD

**Issue by Meganium97** [ValveSoftware/steam-for-linux#7901] opened 2021-07-04 23:43 UTC
#### Your system information

* Steam client version (build number or date): Presumably latest, installed from "sudo apt-get install steam"
* Distribution (e.g. Ubuntu): 21.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam won't open anymore. It will start updating and download and install the updates but then will immediately close and not reopen.

When running, steam, this is what happens:
`steam
Running Steam on ubuntu 21.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/home/ian/.steam/debian-installation/ubuntu12_32/steam -nominidumps -nobreakpad
[2021-07-04 18:41:23] Startup - updater built Jun  8 2021 22:23:36
Installing breakpad exception handler for appid(steam)/version(1623193086)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  152 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  50
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2021-07-04 18:41:23] Loading cached metrics from disk (/home/ian/.steam/debian-installation/package/steam_client_metrics.bin)
[2021-07-04 18:41:23] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2021-07-04 18:41:23] Using the following download hosts for Public, Realm steamglobal
[2021-07-04 18:41:23] 1. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1623193086)
[2021-07-04 18:41:23] Checking for update on startup
[2021-07-04 18:41:23] Checking for available updates...
[2021-07-04 18:41:23] Downloading manifest: http://media.steampowered.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1623193086)
[2021-07-04 18:41:24] Download skipped: /client/steam_client_ubuntu12 version 1623193086, installed version 1623193086, existing pending version 0
[2021-07-04 18:41:24] Nothing to do
[2021-07-04 18:41:24] Verifying installation...
[2021-07-04 18:41:24] Performing checksum verification of executable files
[2021-07-04 18:41:24] Verification complete
Loaded SDL version 2.0.15-6501165
Gtk-Message: 18:41:25.049: Failed to load module "gail"
Gtk-Message: 18:41:25.050: Failed to load module "atk-bridge"

(steam:16624): Gtk-WARNING **: 18:41:25.058: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru-dark/gtk-2.0/main.rc:775: error: unexpected identifier 'direction', expected character '}'

(steam:16624): Gtk-WARNING **: 18:41:25.062: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru-dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  152
Serial number of failed request:  52
xerror_handler: X failed, continuing
assert_20210704184123_1.dmp[16696]: Uploading dump (out-of-process)
/tmp/dumps/assert_20210704184123_1.dmp
/home/ian/.steam/debian-installation/steam.sh: line 772: 16624 Segmentation fault      (core dumped) $STEAM_DEBUGGER $DEBUGGER_ARGS "$STEAMROOT/$STEAMEXEPATH" "$@"
ian@IansLaptop:~$ assert_20210704184123_1.dmp[16696]: Finished uploading minidump (out-of-process): success = yes
assert_20210704184123_1.dmp[16696]: response: CrashID=bp-9b24d1f3-4749-43c1-9c66-bb0c22210704
assert_20210704184123_1.dmp[16696]: file ''/tmp/dumps/assert_20210704184123_1.dmp'', upload yes: ''CrashID=bp-9b24d1f3-4749-43c1-9c66-bb0c22210704''
`

#### Steps for reproducing this issue:

1.Install steam 
2. Run steam

**Comment by kisak-valve** [comment] 2021-07-04 23:53
Hello @Meganium97, `swrast` is mesa's slower software renderer, and the fact that Steam is trying to use it hints that you're using the nVidia proprietary driver, but don't have the driver's 32 bit userspace libraries installed. The nVidia proprietary driver requires the driver's running kernel module, 32 bit userspace libraries, and 64 bit userspace libraries are installed and have exactly the same version to work properly.

Please check what video driver series you're using, then install the 32 bit libraries with something like `sudo apt install libnvidia-gl-465:i386` (change 465 to match the driver series you're using).

**Comment by Meganium97** [comment] 2021-07-04 23:57
I run the nvidia 470 drivers, and it gives me no such option to install it, instead citing me to install a package already installed.

**Comment by kisak-valve** [comment] 2021-07-05 00:11
Can you elaborate on what package it is asking for and how you've installed that driver series? It's not yet available in Ubuntu's repositories or the commonly used PPA for nvidia driver updates (https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa).

**Comment by Meganium97** [comment] 2021-07-05 00:14
Here is what comes up when I try to install `libnvidia-gl-465:i386`:
`
sudo apt-get install libnvidia-gl-470:i386
[sudo] password for ian: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libnvidia-gl-470:i386 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libnvidia-common-470

E: Package 'libnvidia-gl-470:i386' has no installation candidate
`

**Comment by Meganium97** [comment] 2021-07-05 00:15
However when I try to install `libnvidia-common-470`, here's what happens:
`
sudo apt install libnvidia-common-470
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libnvidia-common-470 is already the newest version (470.42.01-0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
`

**Comment by kisak-valve** [comment] 2021-07-05 00:21
`E: Package 'libnvidia-gl-470:i386' has no installation candidate` is the key detail in apt's feedback, `libnvidia-common-470` is not a replacement for it. Whatever method you used to install the nVidia driver did not give you 32 bit support. Use a different driver series that does support 32 bit OpenGL.

**Comment by Meganium97** [comment] 2021-07-05 17:44
I reinstalled nvidia-465 with `libnvidia-gl-465:i386` and that seems to fix it. So I'm guessing that as of right now, nvidia-470 driver is incompatible with steam linux. Thanks for your help!

**Comment by Meganium97** [comment] 2021-07-05 21:46
So I realized that installing `libnvidia-gl-465:i386` completely uninstalls the rest of the driver, and while steam can run, the games will run off of the iGPU instead of the dGPU.

I believe that it might help to say that I am running off of a Dell XPS 7590 with hybrid graphics.

**Comment by kisak-valve** [comment] 2021-07-05 22:00
If I understand the package layout correctly, `nvidia-driver-465` should be the meta-package that pulls in the majority of nVidia's driver.

**Comment by Meganium97** [comment] 2021-07-05 22:02
Yes, but with only 465 installed, steam will not open, just like with 470. This was my original problem.

**Comment by kisak-valve** [comment] 2021-07-05 22:09
Please share the output of `apt policy nvidia-driver-465 libnvidia-gl-465 libnvidia-gl-465:i386`

**Comment by Meganium97** [comment] 2021-07-05 22:10
ian@IansLaptop:~$ apt policy nvidia-driver-465 libnvidia-gl-465 libnvidia-gl-465:i386
nvidia-driver-465:
  Installed: 465.19.01-0ubuntu1
  Candidate: 465.19.01-0ubuntu1
  Version table:
     465.31-0ubuntu0.21.04.1 500
        500 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu hirsute/main amd64 Packages
     465.27-0ubuntu0.21.04.2 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute-updates/restricted amd64 Packages
        500 http://security.ubuntu.com/ubuntu hirsute-security/restricted amd64 Packages
 *** 465.19.01-0ubuntu1 600
        600 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
        100 /var/lib/dpkg/status
libnvidia-gl-465:
  Installed: 465.19.01-0ubuntu1
  Candidate: 465.19.01-0ubuntu1
  Version table:
     465.31-0ubuntu0.21.04.1 500
        500 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu hirsute/main amd64 Packages
     465.27-0ubuntu0.21.04.2 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute-updates/restricted amd64 Packages
        500 http://security.ubuntu.com/ubuntu hirsute-security/restricted amd64 Packages
 *** 465.19.01-0ubuntu1 600
        600 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
        100 /var/lib/dpkg/status
libnvidia-gl-465:i386:
  Installed: (none)
  Candidate: 465.31-0ubuntu0.21.04.1
  Version table:
     465.31-0ubuntu0.21.04.1 500
        500 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu hirsute/main i386 Packages
     465.27-0ubuntu0.21.04.2 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute-updates/restricted i386 Packages
        500 http://security.ubuntu.com/ubuntu hirsute-security/restricted i386 Packages

**Comment by kisak-valve** [comment] 2021-07-05 22:13
So you've circled back to the start of this issue report...

You're using the nVidia proprietary driver, but don't have the driver's 32 bit userspace libraries installed. The nVidia proprietary driver requires the driver's running kernel module, 32 bit userspace libraries, and 64 bit userspace libraries are installed and have exactly the same version to work properly. Please install the driver's 32 bit userspace with `sudo apt install libnvidia-gl-465:i386`.

**Comment by Meganium97** [comment] 2021-07-05 22:15
When I put this in, it decides to uninstall the 465 driver:
ian@IansLaptop:~$ sudo apt install libnvidia-gl-465:i386
[sudo] password for ian: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  dctrl-tools dkms libnvidia-cfg1-465 libnvidia-decode-465
  libnvidia-encode-465 libnvidia-extra-465 libnvidia-fbc1-465
  nvidia-compute-utils-465 nvidia-dkms-465 nvidia-kernel-common-465
  nvidia-kernel-source-465 nvidia-utils-465 xserver-xorg-video-nvidia-465
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  libnvidia-gl-465 libnvidia-ifr1-465 nvidia-driver-465
The following NEW packages will be installed:
  libnvidia-gl-465:i386
0 upgraded, 1 newly installed, 3 to remove and 0 not upgraded.
Need to get 0 B/19.4 MB of archives.
After this operation, 272 MB disk space will be freed.
Do you want to continue? [Y/n]

**Comment by pyramidenkoenig** [comment] 2021-07-05 22:19
I'm experiencing simmiliar problems to @Meganium97 , since my upgrade to nvidia driver version 470, the 32 bit librarys are gone.
There doesn't seem to be a libnvidia-gl-470:i386 package available anywhere! https://paste.ubuntu.com/p/K5cfhv7Xhf/ .
Running Debian 11 Bullseye on Kernel 5.10.0-5-amd64. Did Nvidia break their own driver once again?

**Comment by kisak-valve** [comment] 2021-07-05 22:41
@Meganium97, thanks. I missed the key detail that you're using a version of the nVidia proprietary driver from their CUDA PPA. nVidia' PPA maintainers do not provide 32 bit userspace packages in their PPA. That issue is being tracked at #5778, and can not be fixed by Valve.

There are some workarounds in that issue report, and the main theme is to remove CUDA's meta package, install the driver series from Ubuntu's main repositories or https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa, then install the individual CUDA components you need without using the CUDA's meta package that pulls in the video driver from the CUDA PPA.

Hello @pyramidenkoenig, looking at your pastebin, there are various `<nvidia-component>/unknown 470.42.01-1 amd64` which hints that you've manually installed the nVidia driver? The general idea is the same in that whatever method you used to install nvidia 470.42.01 did not include 32 bit support, but is the cause is unrelated this issue report.

Regardless, this is a system config issue and all 32 bit OpenGL applications are broken on both your systems. Closing in favor of #5778.

**Closed by kisak-valve** 2021-07-05 22:41 UTC
Labels: Distro Family: Ubuntu, NVIDIA drivers
