### ISSUE TITLE
Steam Client loggs itself out after each restart

### ISSUE THREAD

**Issue by l33tsp3ak** [ValveSoftware/steam-for-linux#5119] opened 2017-08-07 11:04 UTC
#### Your system information

* Steam client version (build number or date): 17th July 2017,  at 23:10:56
* Distribution (e.g. Ubuntu): openSUSE Leap 42.2
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Every time the Steam Client is running and I'm shutting down my computer, my Client is logged off after the next start up

#### Steps for reproducing this issue:

1. Have a running, logged in Steam Client
2. Restart your system
3. Open the Steam Client
4. You're logged out

**Comment by soredake** [comment] 2017-08-11 17:28
https://github.com/ValveSoftware/steam-for-linux/issues/3059
https://github.com/ValveSoftware/steam-for-linux/issues/4567
https://github.com/ValveSoftware/steam-for-linux/issues/5030
https://github.com/ValveSoftware/steam-for-linux/issues/5035
https://github.com/ValveSoftware/steam-for-linux/issues/5060
https://github.com/ValveSoftware/steam-for-linux/issues/5065

**Comment by legluondunet** [comment] 2017-08-14 06:05
Same bugs for me:  I have to specify login/password and language at each start with stable or beta client.

config:
Ubuntu 17.04 Zesty Zapus 64 bits - NVIDIA GeForce GTX 770 - official Ubuntu Nvidia drivers 375.66 - 1920x1080 - Processor Intel i5-3570 3,4 Ghz - 8 Go RAM

**Comment by kisak-valve** [comment] 2017-08-14 15:06
Closing as a duplicate of #5030.

**Closed by kisak-valve** 2017-08-14 15:06 UTC
