### ISSUE TITLE
Installing games with existing data does not take existing files into account during disk size check

### ISSUE THREAD

**Issue by apocalyptech** [ValveSoftware/steam-for-linux#3389] opened 2014-06-30 04:23 UTC
I have a couple machines I'd like to have the same games installed on, and rather than download tens of gigs of data from the internet, I'd like to rsync the data (over my LAN) and then have Steam pick up the local files.

This works fine so long as I rsync the data before choosing "Install," but before Steam checks for the local data, it does a disk space check.  The drive I'm installing to is pretty small, and there wouldn't be room for a second copy of the game, so the install will not proceed (even though I have the game data sitting right in the dir).

It'd be nice if Steam checked for local files _first_, before doing its disk check, so that those conditions would be applied a little more usefully in this case.

Thanks!

**Comment by kisak-valve** [comment] 2018-03-02 16:41
Closing as a duplicate of #3226.

**Closed by kisak-valve** 2018-03-02 16:41 UTC
Labels: Steam client, reviewed
