### ISSUE TITLE
Steam update changelog is black until you click on it

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#6451] opened 2019-08-13 15:12 UTC
#### Your system information

* Steam client version: Aug 12 2019, at 23:59:32. Has happened for at least 5 beta updates.
* Distribution: Xubuntu 19.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* System info: https://gist.github.com/Managor/c1f2c2fe5f1c138dff9efcdac47a29de

#### Please describe your issue in as much detail as possible:
Steam update changelog is black until you click on it. Highlighted on this webm.
[Peek 2019-08-13 18-04.webm.zip](https://github.com/ValveSoftware/steam-for-linux/files/3497625/Peek.2019-08-13.18-04.webm.zip)
I have a hard time knowing if there's something in my system that causes this.

#### Steps for reproducing this issue:

1. Wait for the Self Updater window to pop up

**Comment by byte1024** [comment] 2019-08-14 19:48
> I have a hard time knowing if there's something in my system that causes this.

You were able to use the computer enough to file an issue so probably Steam should also work correctly. If it did something so different that it breaks when all other windows work then I would say Steam is at fault for doing something that different. What extent Valve agrees with that, you will find out.

**Comment by AdamSzopa** [comment] 2019-08-15 17:02
I can confirm this is happening on my system as well. I also use nVidia, but have KDE instead.

**Comment by TriMoon** [comment] 2019-08-17 14:10
Same as @AdamSzopa 

`neofetch --stdout | xclip -selection clipboard`:
```console
OS: Ubuntu 19.04 x86_64 
Model: Manual build Rev:xxx 
Mainboard: X99-PRO/USB 3.1 Rev 1.xx (ASUSTeK COMPUTER INC.) 
Bios: 2017-08-10 AMI Ver:3801 
Kernel: 5.0.0-25-generic 
Uptime: 2 days, 6 hours, 55 mins 
Packages: 2485 (dpkg), 2 (snap) 
Shell: zsh 5.5.1 
Resolution: 1680x1050 @ 59.88Hz 
DE: KDE 
WM: KWin 
Theme: Breeze Dark [KDE] 
Icons: breeze-dark [KDE] 
Terminal: konsole 
Terminal Font: Hack 16 
Font: [KDE] 
Locale: en_US.UTF-8 
Memory: 3880MiB / 32075MiB [37m[-==============[37m] 
CPU: i7-5820K (12) @ 4.0GHz [49.0°C] 
GPU: GeForce GTX 1080 Ti 
GPU: GeForce 210 
GPU Driver: NVIDIA 418.56 
CPU Usage: 3% 
Disk (/): 12G / 146G (9%) 
Disk (home): 50G / 63G (83%) 
Disk (efi): 7.7M / 511M (2%) 
```

**Comment by nightsky30** [comment] 2019-08-18 16:35
I'm also experiencing:  https://gist.github.com/nightsky30/bbf79a56c1b1e87f3a4ed279c0ea3212

**Comment by Termuellinator** [comment] 2019-09-08 10:34
I have the same issue:
https://gist.github.com/Termuellinator/e7a7d27c2ebaad492c0c82ade1035981
had it also on my last system (i5 3550+rx580, also Manjaro KDE), so it's not installation-specific.
I've got the same issue with the Settings-Window in SteamVR (although not always), probably related?

**Comment by jug007** [comment] 2020-01-19 16:11
Same issue here on Linux Mint https://gist.github.com/jug007/fdc8b864e6e7142979c2bcb37889493b

**Comment by wantija** [comment] 2020-02-14 04:55
Happening to me to, EndeavourOS (Arch), KDE 5.18, Mesa 19.3.3, RX 580. Although if I click on it I can't see the update notes. It shows briefly when I update but the windows closes...

**Comment by 3vi1** [comment] 2020-08-19 12:30
As mentioned ^, this has been happening consistently for years on multiple (4+) systems running KDE Plasma + nVidia (plasma-desktop on top of various Ubuntu releases - not Kubuntu) in my house.  I've never paid attention to whether or not it also happens when I'm using Gnome on the systems, as I use Plasma most of the time.  

Oddly, no other program (or even other parts of Steam) exhibits the issue.  So, I suspect something in the way Steam instantiates this particular dialog - especially since clicking in it makes it start redrawing correctly.

**Comment by yaomtc** [comment] 2020-11-27 15:15
Judging by the responses (and the fact that I also have this issue with KDE Plasma) I wonder if this has to do with kwin's compositor? Does anyone have this issue with GNOME or with another window manager/compositor?

**Comment by JulianGro** [comment] 2020-11-27 16:28
I regularly (not always) have the problem on Muffin (Cinnamon) which is a fork of Mutter (Gnome 3)

**Comment by nightsky30** [comment] 2020-11-27 19:42
Same issue with XFCE.

**Comment by nightsky30** [comment] 2020-12-02 13:00
After the 30Nov2020 update it seems the 1Dec2020 update displayed the details pane correctly. This is in the beta client. Not sure if fixed or not.

**Comment by 3vi1** [comment] 2020-12-02 14:08
I've been using the beta client, and the update details I was met with this morning (Dec 2) still displayed all black for me.  (KDE plasma desktop)

**Comment by Managor** [comment] 2020-12-03 23:43
KDE Plasma here and from the latest beta update I can confirm that the changelog no longer stays black.

**Comment by nightsky30** [comment] 2020-12-04 02:02
And now the latest update 3Dec2020 on XFCE is black, and not redrawing again:
![image](https://user-images.githubusercontent.com/6024315/101112184-5dd2c400-35a2-11eb-85b9-577b66a8ca13.png)

**Comment by megatog615** [comment] 2020-12-04 09:20
Used to be able to at least click on the black part to make it render correctly, but now that even doesn't work. Seems to show the contents of the first third of the changelog window for me.

**Comment by Managor** [comment] 2020-12-04 09:40
I retract my statement.

**Comment by nightsky30** [comment] 2020-12-04 12:39
Annnnd it works again...
![image](https://user-images.githubusercontent.com/6024315/101164794-352ae880-35fb-11eb-8061-943a38154751.png)

Maybe this is happening after the client has been running a long while? When it showed the changes this time, I had just started the client.

**Comment by 3vi1** [comment] 2020-12-05 15:10
Still black for me at the start.  Clicking around in the windows, tabbing out, tabbing back in, clicking+dragging more *eventually* gets the text to show up.  It used to be that it was black and a simple click+drag in the window would cause the text to show immediately.

I recreated it this morning.  I edited out about 1-2 minutes of me clicking around trying to get the window to display properly.  Click the image below to see the video.

[![Video - Steam Client Black Window](https://i9.ytimg.com/vi_webp/Q0GHN1XSYpQ/mqdefault.webp?time=1607180700000&sqp=CJzDrv4F&rs=AOn4CLAHLUCFui9ujv_iTUCW_WEKDX9CNA)](https://www.youtube.com/watch?v=Q0GHN1XSYpQ)

**Comment by h1z1** [comment] 2020-12-11 09:58
Latest update tonight still does this.  The weird thing is you can tell elements are in the window by mousing over them but the text and background remain black.  No amount of clicking nor dragging causes it to refresh, it just randomly appears.

**Comment by Termuellinator** [comment] 2020-12-18 10:38
after a new install of my PC, it's back again, too - now clicking into it doesn't help anymore, it is only shown once i click on "restart steam"

**Comment by kattjevfel** [comment] 2021-01-05 13:11
I can't even get it working with clicking, weirdly when clicking "restart steam", it does appear, so I can get glimpse of it if I'm really quick. KDE Plasma 5.20.4

**Comment by AwesamLinux** [comment] 2021-01-05 19:41
**System Information**
- GPU: RX 5700
- GPU Driver: Mesa 21.0.0-devel (git-9ef2c44 2021-01-02 focal-oibaf-ppa)
- Kernel version: 5.8.0-33-generic
- Distro version: Mint 20 (64 bit) (Cinnamon)

[system_info.txt](https://github.com/ValveSoftware/steam-for-linux/files/5772219/system_info.txt)

I can confirm this problem. 

I had the original problem with "Steam update changelog is black until you click on it" issue since around 2019 (back then on Mint 19, but the problem remained with Mint 20 even after full system reinstallation). Now as of recent updates the changelog remains black even when you click on it.

**Comment by almaceleste** [comment] 2021-03-23 11:22
Steam API: v020
Steam package: 1613176728
Steam Runtime:  steam-runtime_0.20201203.1
GPU: nVidia GeForce RTX 2060
nVidia Driver: 450.80.02
Kernel: 5.8.0-26-lowlatency
OS: Ubuntu Studio 20.10
Xfce: 4.14

I have the same problem: after wake up from hibernation the Steam Self Updater window has a black rectangle in place of the changelog information. 

**Workaround** that currently works: 
1. `pkill -f steamwebhelper.*type=gpu-process`
2. after that - open main Steam window from the tray 
3. profit - Changelog becomes readable

This is only the first time I have managed to solve the problem - I will try to check again when the problem reappears.

**Comment by nightsky30** [comment] 2021-03-23 12:01
Similar to @almaceleste if I simply close the window with its close button and open it a 2nd time by having the client check for steam updates the 2nd window renders fine.

**Comment by almaceleste** [comment] 2021-03-23 23:55
Yeah! :tada: 
I got a buggy Updater window again and test [my workaround solution](https://github.com/ValveSoftware/steam-for-linux/issues/6451#issuecomment-804823348) - and it temporarily solves the problem like the first time. Simply `pkill ...` - no visible result - then open main window... and viola :v: - changelog becomes visible. 
I want to try adding a resume script to test workaround - I'll write here if I get any result.

**Comment by kakra** [comment] 2021-04-27 18:10
I can confirm this for KDE Plasma 5.21 with NVIDIA but it only occured to me lately, so I didn't have this issue back in 2019 when the original report was issued.

The behavior changed, tho: First, when this happened, I was still able to click into the webview to make its contents visible, meanwhile this does nothing and the webview stays blank until I click the "Restart" button (it will then reveal the webview, only to close the window one blink of an eye later).

**Comment by hasezoey** [comment] 2021-07-03 16:28
I can also confirm this, System:
```
OS: Linux Mint 20.2 x86_64 
Host: MS-7972 2.0 
Kernel: 5.8.0-59-generic 
Packages: 3208 (dpkg), 13 (flatpak) 
Shell: zsh 5.8 
Resolution: 2560x1440, 1920x1080, 1920x1080 
DE: Cinnamon 
WM: Mutter (Muffin) 
WM Theme: Mint-Y-Dark (Mint-Y-Dark) 
Theme: Mint-Y-Dark [GTK2/3] 
Icons: Mint-Y [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-7700K (8) @ 4.500GHz 
GPU: AMD ATI Radeon RX Vega 56/64 
Memory: 4195MiB / 32060MiB 
```
```
Steam client application
Built: Jul 2 2021, at 18:54:20
Steam API: v020
Steam package versions: 1625258093
```

for me, the behavior is either completely black (clicking it does not change it) or only half black or rarely completely rendering (no black)
Note: this behavior is for the automatically opened "Restart Steam" window

**Comment by JulianGro** [comment] 2021-12-03 01:58
Today I got an update changelog that was actually fully visible. I am on the beta branch.

**Comment by kakra** [comment] 2021-12-03 08:16
Yep, since a few beta versions, it sometimes works, but sometimes doesn't.

**Comment by kisak-valve** [comment] 2022-01-21 20:24
Tentatively closing as fixed.

**Comment by hasezoey** [comment] 2022-03-09 10:29
Since January i didnt have any black changelog window anymore, so it is fixed on my side

**Comment by kakra** [comment] 2022-03-09 10:30
I can confirm, it's working since some time now

**Closed** 2022-03-09 13:35 UTC
Labels: Steam client, Web Component

**Comment by TriMoon** [comment] 2022-03-18 14:57
Always nice to see bugs getting solved without a mention/reference of which MR solved it... :disappointed: 
(Most likely something outside of steam that "fixed" it)

**Comment by L1Q** [comment] 2022-07-21 14:10
Got this today
![image](https://user-images.githubusercontent.com/6942070/180232216-ec528f80-8a60-4c26-b874-ee9e9d8bc6f7.png)
Clicking on the black does not make the content appear.
Manjaro 21.3.3
KDE 5.24.6
Kernel 5.18.11-1-MANJARO
Mesa 22.1.3
![image](https://user-images.githubusercontent.com/6942070/180233614-1bc3999d-ee70-4438-ba43-705c829f1ed9.png)
```pkill -f steamwebhelper.*type=gpu-process``` helped, thanks to @almaceleste

**Comment by kisak-valve** [comment] 2022-07-21 14:19
Hello @L1Q, please open a new issue report so that your issue can be tracked properly.
