### ISSUE TITLE
Steam seems to download client updates while game is running

### ISSUE THREAD

**Issue by dlbeswick** [ValveSoftware/steam-for-linux#2765] opened 2013-08-10 00:39 UTC
I don't have a good connection. Often while playing CS: Source, my ping will suddenly jump up and I can see that my bandwidth is saturated.

Nethogs says that the steam client is downloading something, but no game is updating and no network usage is shown in the client's Library/Downloads page.

Once the bandwidth use has stopped, the problem doesn't recur for the rest of the session.

Game updates do suspend correctly when other games are running. Since nothing else is downloading, I'm just guessing but I think that the steam client might be downloading client updates in the background, to be applied next time the app is started.

**Comment by kisak-valve** [comment] 2017-04-12 19:51
Closing as a duplicate of #2003.

**Closed by kisak-valve** 2017-04-12 19:51 UTC
Labels: reviewed, Steam client
