### ISSUE TITLE
Downloads steam updates in offline mode

### ISSUE THREAD

**Issue by nagisa** [ValveSoftware/steam-for-linux#4599] opened 2016-08-19 21:07 UTC
#### Your system information
- Steam client version: can’t check, must be quite recent;
- Distribution (e.g. Ubuntu): Arch Linux;
- Opted into Steam client beta?: can’t check, probably no;
- Have you checked for system updates?: yes;
#### Please describe your issue in as much detail as possible:

Had steam open in offline mode since I’m on tethered (expensive) connection so steam wouldn’t use network for what’s not critically necessary.

Some time later I came back to console output showing it downloading stuff:

> <snip>
> [2016-08-19 22:00:46] Downloading update (4,381 of 246,368 KB)...
> [2016-08-19 22:00:46] Error: Download of package (tenfoot_misc_all) failed after 0 bytes (200).
> [2016-08-19 22:00:46] Downloading update (1,176 of 246,368 KB)...
> <snip>
> [2016-08-19 22:47:56] Downloading update (188,625 of 246,368 KB)...

The log shows it retrying the download multiple times (i.e. every time the failed after 0 bytes message occured it would restart the download from the beginning).
#### Steps for reproducing this issue:
1. Open steam without network available, pick “Start Steam in Offline mode” when prompted;
2. Connect to a tethered connection;
3. Go play some game/etc until update is dispatched.
4. Notice steam downloading huge files behind the scenes, despite Steam still being in offline mode.

**Comment by Tele42** [comment] 2016-08-19 21:36
Duplicate of #2836.

**Comment by kisak-valve** [comment] 2019-07-26 14:17
Closing as a duplicate of #2836.

**Closed by kisak-valve** 2019-07-26 14:17 UTC
Labels: reviewed
