### ISSUE TITLE
Steam doesn't detects that connection is reestablished

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3628] opened 2014-12-11 20:10 UTC
Sometimes the connection dies due to a bug with NetworkManager and Steam shows "No connection". After the connection is back I need to manually restart Steam so it detects the connection is back.

**Comment by garciabruno** [comment] 2015-01-18 21:12
I can confirm this, it is really annoying that Steam does not restablishes the connection.
Specially if you are on a lousy wireless network.

**Comment by Plaque-fcc** [comment] 2015-01-18 22:49
It doesn't try to go back online when the connection has gone; while it
tries to manage connections (like in #3424). Weird paradigm…

+1, this bug affects me too.

**Comment by kisak-valve** [comment] 2018-05-04 14:49
Hello @garciabruno, @Plaque-fcc, are either of you seeing this issue on an up to date system?

**Comment by kisak-valve** [comment] 2018-06-08 12:19
Closing pending feedback.

**Closed by kisak-valve** 2018-06-08 12:19 UTC
Labels: Need Retest, Steam client, reviewed

**Comment by garciabruno** [comment] 2018-06-10 07:44
@kisak-valve Issue seems to be solved. Appreciated.
