### ISSUE TITLE
can not move a game with a 2.6GB file

### ISSUE THREAD

**Issue by debianxfce** [ValveSoftware/steam-for-linux#5652] opened 2018-08-23 14:58 UTC
#### Your system information

* Steam client version (build number or date):  21.8.2018
* Distribution (e.g. Ubuntu): Debian Sid Xfce
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Copying 2.6GB file fails to i/o error with the Steam Move game to another folder feature.

#### Steps for reproducing this issue:

1. Install Saints Row 2
2. Move it to another drive
3. See the content_log.txt file for this error message:

[2018-08-23 17:37:47] Failed copying file "/media/xfce/10a27c2f-4ccb-47b7-8557-4dce49c89bc8/Steanlibrary/steamapps/common/Saints Row 2/music4.vpp_pc" (2735572992 bytes)
[2018-08-23 17:37:47] Canceled Moving App 9480 : I/O Operation Failed at 11359023133/15977841154 bytes, 43 files (Unknown)

Copying  Saints Row 2 with Thunar works. My computer has 8GB RAM and no swap partition. Verifying game files do not help.

**Comment by kisak-valve** [comment] 2018-08-23 15:04
Hello @debianxfce, what filesystems are being used on the drives?

**Comment by meowmeowfuzzyface** [comment] 2018-08-23 20:27
I can confirm this issue on Ubuntu 18.04.  I was attempting to move several game installations from an NTFS drive to an ext4 drive.  The ones without large files were moved successfully, but the games with large files fail with the I/O Operation Failed message.  Moving through the system file manager and reinstalling through the Steam client served as a successful workaround without having to re-download the games.

Not sure if it matters, but the NTFS drive was mounted with the following options: 
`ntfs-3g defaults,exec,uid=1000,gid=1000,locale=en_US.UTF-8 0 2`

**Comment by kisak-valve** [comment] 2018-08-23 20:51
Possibly related to #4800.

**Comment by Sanaki** [comment] 2018-08-24 07:58
Same issue moving Path of Exile, from ext4 to ext4.

**Comment by kisak-valve** [comment] 2019-05-16 01:09
Closing as a duplicate of #4851.

**Closed by kisak-valve** 2019-05-16 01:09 UTC
