### ISSUE TITLE
Help! Steam on switch

### ISSUE THREAD

**Issue by Impulse706** [ValveSoftware/steam-for-linux#11342] opened 2024-10-12 16:32 UTC
Hi I've got a Nintendo switch which I've jailbroken to run Ubuntu. I've gotten the packages and everything, but it doesn't run. Check out my repository to see what I'm doing about it. Any help would be very much appreciated. Thanks.

**Comment by kisak-valve** [comment] 2024-10-12 16:36
Hello @Impulse706, running Steam for Linux on ARM based hardware is not supported.

Closing as a duplicate of #4061.

**Closed by kisak-valve** 2024-10-12 16:36 UTC

**Comment by Impulse706** [comment] 2024-10-12 22:01
Hi, with all do respect, I believe it is possible. Thank you.
