### ISSUE TITLE
Nintendo Switch Pro controller not functioning correctly in Steam games on Xubuntu 18.04

### ISSUE THREAD

**Issue by pineapplemachine** [ValveSoftware/steam-for-linux#6430] opened 2019-08-05 18:45 UTC
#### Your system information

* Steam client version (build number or date): Jul 17 2019, at 16:14:18
* Distribution (e.g. Ubuntu): Xubuntu 18.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I was able to configure the controller for desktop use without any problems. The issue comes when I check "Switch Pro Configuration Support" in the controller settings window.

What I expected: To be able to use the controller as though it was any gamepad in games run through steam.

What actually happened: Whenever I open a game or other application with controller input support, the application is spammed with a variety of controller inputs extremely quickly. Unfortunately, I can't use the desktop configuration to set up analog controls as far as I can tell, only to simulate button presses.

Addendum: I tried my Xbox controller as well and it seems to be working fine. I would prefer to be using my Switch Pro controller, though...

#### Steps for reproducing this issue:

1. Setup Steam on an Xubuntu 18.04 installation
2. Hook up a Switch Pro controller and check the "Switch Pro Configuration Support" box in Steam's controller settings
3. Download and play a game with controller support - this has happened to me with both Cave Story+ (steam game) and Snes9X (non-steam application, launched through steam). I don't dare to continue testing, since the flurry of random inputs can make it very difficult to exit the application.
4. Do something to make the application accept controller inputs, if it wasn't already - for example, in Cave Story+, it behaves fine until you set controller input instead of the default keyboard input in the settings. After that, things go crazy due to input spam.

**Comment by Myrddin-Wyllt** [comment] 2019-08-06 18:01
Duplicate of issue #6144.
I'm glad this issue is getting more documentation, thank you for the report!
In the future, please search for your issue before posting a duplicate.

**Comment by pineapplemachine** [comment] 2019-08-06 19:21
My apologies. I noticed that issue and how the reporter couldn't get their
controller recognized at all, but I didn't notice the comment further down
where @Myrddin-Wyllt was describing a problem similar to mine.

May I suggest that these might be best considered as two separate, related
issues - input not registering versus inputs unexpectedly and rapidly
registering - and that one issue is not a duplicate of the other?

**Comment by Myrddin-Wyllt** [comment] 2019-08-06 19:30
I changed the wording to **possible duplicate** in my prior comment. You're right in stating these are technically two separate issues. Without knowing either issue's cause, I can't say it is definitively the same problem. Change the title to better reflect the rapid/flickering input. I'm moving my comment here from the other issue.

**Comment by Myrddin-Wyllt** [comment] 2019-08-06 19:30
On Monday during a power outage, I attempted to play Retroarch with my Steam Controller & my brother's Switch Pro controller (both wired directly to my laptop). I was using Steam's "Offline Mode" to play & configuration support for the Switch Controller was tested as enabled & disabled. In Offline Mode, the controller wouldn't send input to Retroarch. I attempted once more without Steam, & while Retroarch did recognize the Switch controller for both attempts, input still wouldn't work. Linux kernel support seems either nonexistent or incomplete.

In Retroarch through Steam with Switch configuration support on, the Switch controller registers as an xinput as well as a Switch Pro Controller. After power was restored, I tested Retroarch again & input worked; but not without issues.

Multiple buttons were constantly registering despite not being pressed making gaming impossible with the Switch Pro controller.

Odd how well the controller works in Big Picture/Desktop versus in-game.

I'm using [Valve's official udev rules](https://github.com/ValveSoftware/steam-devices/blob/master/60-steam-input.rules) for everything.
If Valve wants logs, I'd be happy to oblige.

**Comment by kisak-valve** [comment] 2021-12-10 18:50
Hello @pineapplemachine, are you still experiencing this issue on an up to date system?

**Comment by pineapplemachine** [comment] 2021-12-14 09:30
Hi @kisak-valve, I appreciate you following up. Unfortunately I don't have anything more to contribute here. Back when I reported the issue, I just settled for using an Xbox controller and didn't try to use the Switch Pro controller again. All this time later, I no longer actively use Xubuntu and I can't easily give you an answer there.

**Comment by kisak-valve** [comment] 2022-01-14 18:07
Thanks for the feedback @pineapplemachine. Closing as outdated.

**Closed by kisak-valve** 2022-01-14 18:07 UTC
Labels: Need Retest, General controller / Steam Input
