### ISSUE TITLE
Away detection not functioning on KDE

### ISSUE THREAD

**Issue by Ruedii** [ValveSoftware/steam-for-linux#5923] opened 2018-11-27 14:11 UTC
#### Your system information
Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 5 1500X Quad-Core Processor          
    CPU Family:  0x17
    CPU Model:  0x1
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3500 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 18.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.15.0-39-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-beta-release_2018-11-23

Video Card:
    Driver:  X.Org AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.23.0, 4.15.0-39-generic, LLVM 8.0.0)
    Driver Version:  4.5 (Compatibility Profile) Mesa 19.0.0-devel - padoka PPA
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x1002
    DeviceID:  0x67df
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1600 x 900
    Desktop Resolution: 1600 x 900
    Primary Display Size: 17.44" x 9.80" (20.00" diag)
                                            44.3cm x 24.9cm (50.8cm diag)
    Primary VRAM: 8192 MB

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  16032 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  872869 Mb
    Largest Free Hard Disk Block:  279856 Mb
    VR Headset: None detected

#### Please describe your issue in as much detail as possible:
When away from the system and the screen locks, my system does not go into away mode.

Note: I rely on only the screenlock and monitor power save in KDE, not the screensaver.   I have no need for power-wasting eye candy.

#### Steps for reproducing this issue:

1. Leave system running until the screen locks.
2. Look at account status
3. Account status still reads "online" instead of "away."

The Steam client should use FreeDesktop.org api to detect screen locking and use that to determine auto-away.

It might also be beneficial for the client to self-hide in this state and pause all rendering processes to save on processor usage.

**Comment by Ruedii** [comment] 2018-11-30 23:46
To be more specific, the Steam client should listen for several different FreeDesktop.org events:
Sleep mode (Monitor or system)
Screensaver 
Screen lock

Additionally it should listen for the events that specify inhibitors blocking the screensaver, lock-screen and screen sleep functions to detect when the timer auto-away should be disabled.  This would allow enabling the timer auto-away as well.

I understand that this is a complete rewrite of the auto-away function, but it should create a modern auto-away function that works well on any desktop.

**Comment by kisak-valve** [comment] 2021-04-16 17:23
Closing as a duplicate of #5607.

**Closed by kisak-valve** 2021-04-16 17:23 UTC
Labels: Steam client
