### ISSUE TITLE
CS:GO Nothing works.

### ISSUE THREAD

**Issue by Raidzer1** [ValveSoftware/steam-for-linux#6659] opened 2019-11-07 13:03 UTC
#### Your system information

* Steam client version (build number or date): 1573019481 Nov 6 2019 (Why no one thought to give the opportunity to copy it from the client) It's not flatpak version.
* Distribution (e.g. Ubuntu): PopOS 19.10
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Game wont start at all. Only i can see black screen after this, reboot pc is required beacuse cant do anything on my pc. Sometimes i can see menu but cant click anything if menu is loaded and i quit the game by end of process the game screen is on a wallpaper. For first time runs normal.
Here is a terminal output from steam.
https://gist.github.com/Raidzer1/9ee5fac819eb8225aa9fcedb8329347a
(In logs you can see some information about joystick but it's dosnt matter with not connected joystick or even -nojoy command the result is same.)

Only way to get thsi working is reainstalling steam if i try reinstall only cs go this is not working.

Also knows bugs:

When i press Y to chat games freezes.
When i want to talk on mic games also freezes. (If in background something use microphone like discord etc.  it works normal)

My friend have same issue on fedora 31 with nvidia gpu.

Bad performance on AMD gpu it may be caused of bad implementation of OpenGL in amd drivers because in Dota 2 on OpenGl is too bad performance on Vulkan runs perfectly.

#### Steps for reproducing this issue:

1.Install game 
2.Play Game
3. Quit game
4. Try to play again

**Comment by kisak-valve** [comment] 2019-11-07 14:00
Hello @Raidzer1, you've described the issue being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2187#issuecomment-547176465 which is a mutter 3.34 regression that has been fixed upstream.

You should be able to use the any other desktop environment until https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1845302 makes its way into Ubuntu 19.10 or grab my test build of mutter.

Closing as a duplicate.

**Closed by kisak-valve** 2019-11-07 14:00 UTC

**Comment by Raidzer1** [comment] 2019-11-07 14:10
But what about with another bugs?
When i press Y to chat games freezes.
When i want to talk on mic games also freezes. (If in background something use microphone like discord etc. it works normal)

Bad performance on AMD gpu it may be caused of bad implementation of OpenGL in amd drivers because in Dota 2 on OpenGl is too bad performance on Vulkan runs perfectly.

**Comment by kisak-valve** [comment] 2019-11-07 14:28
Looks like your text chat issue is being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1788 and the voice chat issue is being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1440 (and likely also in other issue reports on [csgo-osx-linux](https://github.com/ValveSoftware/csgo-osx-linux)).

**Comment by Raidzer1** [comment] 2019-11-07 15:26
Yeah nice nothing changeds since 2017 greate.
