### ISSUE TITLE
[Feature Request] Bring the SDKs and Authoring Tools to Linux

### ISSUE THREAD

**Issue by ifohancroft** [ValveSoftware/steam-for-linux#7038] opened 2020-04-16 17:25 UTC
Please bring your games' SDKs and Authoring Tools to Linux.

The feature request is for all of them, I may be missing some in the following list but here it is:

Counter-Strike: Global Offensive - SDK
Half-Life SDK
Left 4 Dead 2 Authoring Tools
Left 4 Dead Authoring Tools
Portal 2 Authoring Tools
Source SDK
Source SDK Base 2006
Source SDK Base 2007

**Comment by kisak-valve** [comment] 2020-04-16 17:34
Hello @ifohancroft, this is a duplicate of https://github.com/ValveSoftware/source-sdk-2013/issues/141, which was effectively answered at https://github.com/ValveSoftware/source-sdk-2013/issues/141#issuecomment-22062601.

**Closed by kisak-valve** 2020-04-16 17:34 UTC

**Comment by ifohancroft** [comment] 2020-04-16 23:34
Sorry, I didn't notice this post and thank you for pointing me to it!

**Comment by Anyeos** [comment] 2022-10-30 03:35
Yes but that is from 2013 so that are very old Windows libraries today. Maybe they must consider updating their tools and porting it to QT as first. There are guides about porting Windows Apps to QT (and that don't look as a heavy work as we can think).
All other tools like the compilers are vanilla C as I know. I used NetRadiant and the bsp compilers are generic C/C++ programs. No need to do much there if they use something like that.
Anyway you can write a wrapper over MFC and other Windows libraries that implements the same functions that use some of the code and only port that to other systems.
The other solution is if they made free under open source license some of the SDK (specially the editor) so the people can port it to other OSes.

For now I need to use Wine or get a stand alone Windows running with OpenGL support and that stop me using a VM. 

But ok, they will do what they want no what I need.
