### ISSUE TITLE
Punctuation / grammar

### ISSUE THREAD

**Issue by maxwell-wagner** [ValveSoftware/steam-for-linux#8176] opened 2021-10-25 00:08 UTC
#### Your system information

* 1634158817 / API-V020 / Oct 13 2021.
* Debian 11 (KDE)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

I'm going to try to create an understandable context, I'm **Brazilian** and normally we use a lot of **punctuation** in letters, eg (áéíóú), **this is important in my language, for better understanding.**

in any area of ​​the system, the scores work, except in steam chat (steam client)

I'm testing here and it's not just limited to scores, there are some other codes that don't work either, it looks like there's an ''invisible English keyboard'' in the steam chat that you can't change (is what goes through my mind)

![Screenshot_20211024_210130](https://user-images.githubusercontent.com/62955221/138618133-8e78471d-230d-423a-b37c-47692e0fb8c9.png)
Browser version seems to work perfectly

#### Steps for reproducing this issue:

1. Open steam chat (steam client version)
2. Try using scores (éxámplé)
3. **Does not work**

**Comment by kisak-valve** [comment] 2021-10-25 00:18
Hello @maxwell-wagner, this reads like #5589. Please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. The detail I'm interested in checking is if the `en_US.UTF-8` locale is available on your system, even if you don't use it.

**Comment by maxwell-wagner** [comment] 2021-10-25 00:51
![Screenshot_20211024_214537](https://user-images.githubusercontent.com/62955221/138619662-121525ee-655c-459e-8967-aca0b0ef9681.png)
pum pum


![Screenshot_20211024_214942](https://user-images.githubusercontent.com/62955221/138619824-6daba572-57a0-4456-8c84-cc19c07a7edf.png)

**Comment by maxwell-wagner** [comment] 2021-10-25 00:52
if I find some more errors, I will report them as soon as possible, I love valve.

**Comment by kisak-valve** [comment] 2021-10-25 00:52
Closing as a duplicate of #5589.

**Closed by kisak-valve** 2021-10-25 00:52 UTC
Labels: Steam client, localization, Need Retest, Distro Family: Debian
