### ISSUE TITLE
Openning Black Mesa (362890) properties crashes Steam

### ISSUE THREAD

**Issue by xDShot** [ValveSoftware/steam-for-linux#6757] opened 2019-12-09 09:22 UTC
#### Your system information

* Steam client version (build number or date): 
![image](https://user-images.githubusercontent.com/4261659/70423349-5f94a500-1a7e-11ea-88a7-f07266f6e577.png)
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When I try opennig Black Mesa properties, Steam crashes

#### Steps for reproducing this issue:

1. Find the game in Steam library
2. Right click on the game
3. Press Properties...

**Comment by kisak-valve** [comment] 2019-12-09 13:31
Hello @xDShot, does `/tmp/dumps/<username>_stdout.txt` have any hints?

**Comment by xDShot** [comment] 2019-12-09 13:40
@kisak-valve https://gist.github.com/xDShot/aefb0284c7117fb84692ac0144f9ffd1

**Comment by Iglu47** [comment] 2019-12-10 21:11
+1 more game - Warframe
#### Your system information

* Steam client version (build number or date): 
![build](https://user-images.githubusercontent.com/25866099/70565102-77fde000-1ba2-11ea-9829-b66dace3f377.png)
* Distribution: Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When I try opennig Warframe properties, Steam crashes
```
Crash reason:  SIGSEGV /0x00000000
Crash address: 0x0
```

#### Steps for reproducing this issue:

1. Find the game in Steam library
2. Right click on the game
3. Press Properties...

**Comment by Iglu47** [comment] 2019-12-11 13:57
works good now for me with same steam build
@xDShot after system update and reboot, are you still have a problem?

**Comment by Myrddin-Wyllt** [comment] 2020-01-02 18:41
Does this occur with compositing disabled? 

The properties, settings, system info, etc. Steam pages don't seem to play nicely with compositing enabled (invisible right-click menus). The newer (likely chromium-based) interfaces don't have this issue. I suspect these could be related problems.

**Comment by tetious** [comment] 2020-01-06 21:04
This is also happening for me with Starcom Nexus (863590). I'm also on an Arch based distro. (Manjaro)

Nothing interesting in the logs. 

If I uninstall the game and delete the download cache, I can open properties again until I reinstall the game and restart steam.

The game doesn't ever properly install, mind. It seems to create a completely empty folder. Verifying the game files reports success, but the folder remains empty. Once I restart Steam, the right click->properties problem returns.

This problem occurs whether I use the latest beta steam client or the stable version.

**Comment by soredake** [comment] 2020-01-24 15:44
It does not crash for me after latest updates.

**Comment by xDShot** [comment] 2020-01-26 01:15
Nope, still crashes

**Comment by xDShot** [comment] 2020-01-26 01:18
latest dump
```
[xdshot@pbody-pc ~]$ coredumpctl debug
           PID: 44888 (steam)
           UID: 1000 (xdshot)
           GID: 1000 (xdshot)
        Signal: 11 (SEGV)
     Timestamp: Sun 2020-01-26 04:15:23 MSK (2min 3s ago)
  Command Line: /home/xdshot/.local/share/Steam/ubuntu12_32/steam
    Executable: /home/xdshot/.local/share/Steam/ubuntu12_32/steam
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
          Unit: user@1000.service
     User Unit: gnome-terminal-server.service
         Slice: user-1000.slice
     Owner UID: 1000 (xdshot)
       Boot ID: 922ed6d611824254983e1a92dae59db3
    Machine ID: 56f9b06945674b5f9d3af22c2426a9f4
      Hostname: pbody-pc
       Storage: /var/lib/systemd/coredump/core.steam.1000.922ed6d611824254983e1a92dae59db3.44888.1580001323000000000000.lz4
       Message: Process 44888 (steam) of user 1000 dumped core.
                
                Stack trace of thread 44888:
                #0  0x00000000f7a88463 __strcmp_sse4_2 (libc.so.6 + 0x170463)
                #1  0x00000000e32da01a n/a (/home/xdshot/.local/share/Steam/ubuntu12_32/steamui.so + 0x85201a)
                #2  0x00000000e32dab30 n/a (/home/xdshot/.local/share/Steam/ubuntu12_32/steamui.so + 0x852b30)
                #3  0x00000000e32bec97 n/a (/home/xdshot/.local/share/Steam/ubuntu12_32/steamui.so + 0x836c97)
                #4  0x00000000e32c1f7e n/a (/home/xdshot/.local/share/Steam/ubuntu12_32/steamui.so + 0x839f7e)
                #5  0x00000000e32bfa49 n/a (/home/xdshot/.local/share/Steam/ubuntu12_32/steamui.so + 0x837a49)
                #6  0x00000000e38cbff2 n/a (/home/xdshot/.local/share/Steam/ubuntu12_32/steamui.so + 0xe43ff2)
                #7  0x00000000e8952c8e n/a (/home/xdshot/.local/share/Steam/ubuntu12_32/chromehtml.so + 0x8fc8e)

GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Registered pretty printers for UE4 classes
Reading symbols from /home/xdshot/.local/share/Steam/ubuntu12_32/steam...
(No debugging symbols found in /home/xdshot/.local/share/Steam/ubuntu12_32/steam)
[New LWP 44888]
[New LWP 45267]
[New LWP 45072]
[New LWP 44978]
[New LWP 45258]
[New LWP 45090]
[New LWP 45259]
[New LWP 45264]
[New LWP 44970]
[New LWP 45268]
[New LWP 45272]
[New LWP 45277]
[New LWP 45273]
[New LWP 45094]
[New LWP 45349]
[New LWP 45076]
[New LWP 44969]
[New LWP 44973]
[New LWP 44968]
[New LWP 45276]
[New LWP 44972]
[New LWP 44971]
[New LWP 44966]
[New LWP 44977]
[New LWP 44974]
[New LWP 44967]
[New LWP 44975]
[New LWP 44985]
[New LWP 44983]
[New LWP 44981]
[New LWP 44984]
[New LWP 45084]
[New LWP 45089]
[New LWP 45129]
[New LWP 44986]
[New LWP 44987]
[New LWP 45125]
[New LWP 45169]
[New LWP 45266]
[New LWP 45260]
[New LWP 45265]
[New LWP 45130]
[New LWP 45261]
[New LWP 44988]
[New LWP 45091]
[New LWP 45122]
[New LWP 44976]
[New LWP 44979]
[New LWP 45123]
[New LWP 45083]
[New LWP 45087]
[New LWP 45262]
[New LWP 45278]
[New LWP 45271]
[New LWP 45270]
[New LWP 45073]
[New LWP 45127]
[New LWP 45343]
[New LWP 44980]
[New LWP 44982]
[New LWP 45275]
[New LWP 45088]
[New LWP 44912]
[New LWP 45211]
[New LWP 45085]
[New LWP 45126]
[New LWP 45274]
[New LWP 45168]
[New LWP 44963]
[New LWP 45269]
[New LWP 45128]
[New LWP 45263]
[New LWP 45093]
[New LWP 45124]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/home/xdshot/.local/share/Steam/ubuntu12_32/steam'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf7a88463 in __strcmp_sse4_2 () from /usr/lib32/libc.so.6
[Current thread is 1 (Thread 0xf78be700 (LWP 44888))]
(gdb) bt
#0  0xf7a88463 in __strcmp_sse4_2 () from /usr/lib32/libc.so.6
#1  0xe32da01a in ?? () from /home/xdshot/.local/share/Steam/ubuntu12_32/steamui.so
#2  0xe32dab30 in ?? () from /home/xdshot/.local/share/Steam/ubuntu12_32/steamui.so
#3  0xe32bec97 in ?? () from /home/xdshot/.local/share/Steam/ubuntu12_32/steamui.so
#4  0xe32c1f7e in ?? () from /home/xdshot/.local/share/Steam/ubuntu12_32/steamui.so
#5  0xe32bfa49 in ?? () from /home/xdshot/.local/share/Steam/ubuntu12_32/steamui.so
#6  0xe38cbff2 in ?? () from /home/xdshot/.local/share/Steam/ubuntu12_32/steamui.so
#7  0xe8952c8e in ?? () from /home/xdshot/.local/share/Steam/ubuntu12_32/chromehtml.so
#8  0xe8c5b6ce in ?? () from /home/xdshot/.local/share/Steam/ubuntu12_32/vgui2_s.so
#9  0xe8c6b25d in ?? () from /home/xdshot/.local/share/Steam/ubuntu12_32/vgui2_s.so
#10 0xe33524d6 in ?? () from /home/xdshot/.local/share/Steam/ubuntu12_32/steamui.so
#11 0xe335434e in ?? () from /home/xdshot/.local/share/Steam/ubuntu12_32/steamui.so
#12 0xe3356483 in ?? () from /home/xdshot/.local/share/Steam/ubuntu12_32/steamui.so
#13 0x565cd4f0 in RunSteam(int, char**, bool) ()
#14 0x565ce473 in ?? ()
#15 0x565b636c in ?? ()
#16 0xf7936ff9 in __libc_start_main () from /usr/lib32/libc.so.6
#17 0x565ba959 in _start ()
(gdb)
```

**Comment by xDShot** [comment] 2020-02-01 16:27
Same happens with Call of Duty: Black Ops II (202970)

**Comment by xDShot** [comment] 2020-02-02 18:09
Deus Ex Mankind Divided is also affected

**Comment by xDShot** [comment] 2020-02-02 18:18
Arma 3 is also affected, which is weird. It wasn't before...

**Comment by xDShot** [comment] 2020-02-02 18:50
So, I switched to alt steam account, opened properties. No crashes.

Switched back to main acc, no crashes as well..

**Comment by ronoverdrive** [comment] 2020-02-02 19:32
Here's the crazy thing for me. Go into Offline Mode and I can open the properties, log back in Online Mode and it crashes.

**Comment by bingusdreggs** [comment] 2020-03-12 10:40
This is happening for me on Grim Dawn. The offline mode trick works. I am using Kubuntu 19.10 though, and not Arch.

**Comment by Sanaki** [comment] 2020-03-24 15:35
Just noticed this is happening to me with Path of Exile (238960), this appears to be due to using a custom proton version that I since removed, and it's crashing when it can't find it. Verified by reproducing the issue with Monster Hunter World (582010) by adding the newest GE custom proton and removing the version MHW had associated. After doing so, it exhibited the exact same behavior. Going offline does not let me get around the issue.

If I knew where the override was stored, I could manually clear it and be done with the issue, but I haven't yet found that. Grepping through everything to attempt to locate it right now.

**Comment by soredake** [comment] 2020-04-04 10:44
Happens again with GTA IV

**Comment by kkleinw** [comment] 2020-04-06 17:51
For me too, though with Warframe. Going offline and online again does not help.

**Comment by xDShot** [comment] 2020-04-06 17:55
Change Account..., relogin, usually works.

**Comment by af7567** [comment] 2020-06-15 23:25
I just got this problem today when trying to open the properties for "Mafia II: Definitive Edition". I assumed it was because I had set Mafia to use a custom Proton version which was installed in compatibilitytools.d and since removed, but after copying it back it still didn't work.

**Comment by alaestor** [comment] 2020-07-09 14:35
> Here's the crazy thing for me. Go into Offline Mode and I can open the properties, log back in Online Mode and it crashes.

I was having the same problem; fixed it by changing properties when in offline mode, then going online.

My thought process was to make it update with the new state to hopefully clear whatever error was causing the problem. In my case: I unticked force compatibility tool, changed steam input and BPM overlay to forced off, removed my launch options, unticked steam overlay... Basically, I changed everything I could just to make sure; seems to have worked.

**Comment by Antares26** [comment] 2020-10-17 00:07
Still having this issue. Solved it too by going into Offline Mode, changing the properties and then going back online

**Comment by popsUlfr** [comment] 2020-10-17 14:59
Just encountered this on **A Plague Tale**. It's definitely something to do with proton versions, or custom proton versions that may have been removed which the game depended on. Offline mode trick worked.

**Comment by kisak-valve** [comment] 2022-05-13 23:37
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by Sanaki** [comment] 2022-05-14 07:54
I haven't experienced this in some time. I believe it's safe to close.

**Comment by kisak-valve** [comment] 2022-06-17 18:57
Thanks for the feedback @Sanaki. Closing as fixed some time ago.

**Closed by kisak-valve** 2022-06-17 18:57 UTC
Labels: Steam client, Need Retest, Distro Family: Arch
