### ISSUE TITLE
Steam Deck gaming mode capturing a screenshot not working

### ISSUE THREAD

**Issue by popsUlfr** [ValveSoftware/steam-for-linux#8985] opened 2022-12-12 16:10 UTC
#### Your system information

* Steam client version (build number or date): 1670661350 Dec 10 2022, at 02:13:15 
* Distribution (e.g. Ubuntu): SteamOS on Steam Deck
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Taking a screenshot with **STEAM + R1** does nothing

#### Steps for reproducing this issue:

1. Capture a screenshot with STEAM + R1 in Steam or in-game
2. It does nothing

**Comment by kisak-valve** [comment] 2022-12-12 16:24
Hello @popsUlfr, this reads like a duplicate of #8871. Until that issue is resolved, we can't really evaluate if there's an additional SteamOS-specific issue going on.

Closing in favor of the older issue report.

**Closed by kisak-valve** 2022-12-12 16:24 UTC

**Comment by popsUlfr** [comment] 2022-12-12 16:46
> Hello @popsUlfr, this reads like a duplicate of #8871. Until that issue is resolved, we can't really evaluate if there's an additional SteamOS-specific issue going on.
> 
> Closing in favor of the older issue report.

@kisak-valve That's fair though I feel like it's a recent problem in gaming mode on the Steam Deck with the Steam Client since I was able to take screenshots a week ago with STEAM + R1. And I'm not seeing anything in the logs that would point to anything crashing.
