### ISSUE TITLE
Disabling the tray icon

### ISSUE THREAD

**Issue by localstyle** [ValveSoftware/steam-for-linux#4843] opened 2017-02-02 12:47 UTC
Hello!
I'd like to have the option to have Steam NOT display an icon in the system bar (top right corner)... In the Settings > Interface > Set Taskbar Preferences, we can choose the online options and destinations to display, but what if we don't want any Steam tray icon to be displayed at all? All Ubuntu apps I know offer that possibility, which I take advantage of to keep my system bar clean. Only Steam remains... :)
Thanks
P

**Comment by kisak-valve** [comment] 2017-02-02 12:50
Closing as a duplicate of #3083.

**Closed by kisak-valve** 2017-02-02 12:50 UTC
