### ISSUE TITLE
Installing CS:GO, "corrupt update files" error

### ISSUE THREAD

**Issue by David-Lor** [ValveSoftware/steam-for-linux#5159] opened 2017-09-05 20:17 UTC
#### Your system information

* Steam client version (build number or date): Aug 28 2017, 11:55:28
* Distribution (e.g. Ubuntu): Ubuntu 14.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I install CS:GO from Steam, and when it reaches the end of the download/installing process, shows the Corrup

The same error is given if I verify data integrity or re-download the game. Tried installing on a NTFS drive, as well as the /home drive (ext4). As I see, the problem was theorically fixed, but I'm still having the same issue (https://github.com/ValveSoftware/steam-for-linux/issues/4800)

I attach a screenshot showing the file that is supposed to raise the error - that alert box is only shown when I press on Play the game, then wait until it finishes re-downloading everything and when it tries to launch it, the dialog is summoned.
![a](https://user-images.githubusercontent.com/17401854/30081586-08fc05c4-9288-11e7-898b-8be9d8680dca.png)

I have previously installed Verdun and Left 4 Dead 2 (on /home) without problems, working well actually.

#### Steps for reproducing this issue:

1. Install the game on NTFS drive
2. Remove the game, install it on EXT4 (/home default steam library folder)
3.

**Comment by kisak-valve** [comment] 2017-09-05 21:07
Hello @EnforcerZhukov, as you say, the issue with corrupt updates on NTFS is being tracked at #4800 It is not fixed, but there is a workaround in that issue report. We'll only track the EXT4 update issue here.

**Comment by devBrouwer** [comment] 2017-09-11 08:32
I have the same issue, installed cs:go on an ext4 partition. But I also have a ntfs steam library, and for some reason steam decided to download updates for cs:go on the ntfs partition.

**Comment by kisak-valve** [comment] 2017-09-11 13:37
How much free space is available on the ext4 steam library? Per "Steam will now use library folders on other drives to download game updates if the primary drive doesn't have enough space left" in the [2017-08-29 stean client update](http://store.steampowered.com/news/32099/), it would not be surprising if steam is picking the NTFS steam library to stage the game update.

**Comment by devBrouwer** [comment] 2017-09-11 14:49
I have over 6GiB available on the steam library partition and the update was only 30MiB so for this update that wasn't the case.

**Comment by EnforcerZhukov** [comment] 2017-09-12 09:07
In my case, 47GiB on /home and 200GiB on the NTFS. I attach a screenshot of the libraries:
![image](https://user-images.githubusercontent.com/17401854/30317472-81be7722-97aa-11e7-9f6c-7c1b2b91b607.png)

**Comment by mercuriete** [comment] 2017-09-13 23:43
same issue...
I have one library folder in NTFS and another in EXT4
probably steam is using the first one to update an application that is in EXT4 partition.

This makes imposible to update csgo and dota2.

You can workaround umounting and mounting again with uid=1000 as said before.

```
sudo umount "/mnt/MEDIA/Juegos Steam"
sudo mount "/mnt/MEDIA/Juegos Steam" -o rw,uid=1000,gid=1000
```
this can allow to workaround temporary if you don't want to use fstab to make it persistent.

be sure that your uid and gid is 1000 with the command
```
id
```

**Comment by EnforcerZhukov** [comment] 2017-10-01 19:19
Just in case tried removing the NTFS library from Steam settings, downloaded the game again, and I'm having the same error. I'll try later unmounting all the NTFS mountpoints.

**Comment by AresiusOfElgard** [comment] 2017-11-19 03:19
This is happening with Counter Strike, Dota 2 and Team Fortress 2 With NTFS and EXT4, every time there is an update.

**Comment by Joechim94** [comment] 2018-10-21 21:33
Having this issue as well.

I have a Secondary NTFS partition (Share Drive) on a drive that I mount in Windows and Linux.

Some games install, other games say _Corrupt Update Files_. For the games that _do_ install on the Share Drive, Proton does not work.

Once a game is installed on the Share Drive, I cannot move the install drive from Steam GUI because it says that the game "already exists" on that drive, even though the Steam Library View says that drive has zero game installs.

**Comment by kisak-valve** [comment] 2020-03-13 14:22
Hello, is anyone still experiencing this issue on an up to date system? It should have been resolved along with https://github.com/ValveSoftware/steam-for-linux/issues/4800#issuecomment-487698302.

**Comment by mercuriete** [comment] 2020-03-13 14:31
@kisak-valve I havent experienced this bug since 2017.
I just put the fix in my fstab and mounted my ntfs partition as I did back then.
I cant retest because I cant reproduce the bug anymore.

**Comment by kisak-valve** [comment] 2020-04-17 13:12
Thanks for the feedback @mercuriete, closing as fixed some time ago.

**Closed by kisak-valve** 2020-04-17 13:12 UTC
Labels: Distro Family: Ubuntu, Need Retest, Steam client
