### ISSUE TITLE
HL2 and Greek characters

### ISSUE THREAD

**Issue by verdegr** [ValveSoftware/steam-for-linux#2908] opened 2013-10-08 21:39 UTC
I recently bought HL2. The Steam application is set to Greek Language. When I open HL2 the in game main menu text  and the in game subtitles are totally messed. If I set Steam to English, HL2 fonts are correct.

Images attached
![2013-10-09_00001](https://f.cloud.github.com/assets/5059984/1293255/1d2c9518-3062-11e3-8f75-8cb84f75f905.jpg)
![2013-10-09_00002](https://f.cloud.github.com/assets/5059984/1293256/1d2c9914-3062-11e3-8be8-0c87d7ff14cc.jpg)
![2013-10-09_00003](https://f.cloud.github.com/assets/5059984/1293257/1d2ed9a4-3062-11e3-8f51-de5e96fbebcc.jpg)
![2013-10-09_00004](https://f.cloud.github.com/assets/5059984/1293258/1d34e56a-3062-11e3-9436-c6baee5944b9.jpg)

**Comment by kisak-valve** [comment] 2017-09-15 14:44
Closing as a duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/1460.

**Closed by kisak-valve** 2017-09-15 14:44 UTC
Labels: reviewed
