### ISSUE TITLE
[Feature Request] Launch Parameters synchronised to STEAM Cloud

### ISSUE THREAD

**Issue by BloodyIron** [ValveSoftware/steam-for-linux#6732] opened 2019-12-02 02:20 UTC
It's really frustrating when I reinstall a game, only to realise I need to set my launch parameters back up (eg. SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 %command%).

Can we please have the launch parameters sync to STEM Cloud? (at least, as an option)

**Comment by Leopard1907** [comment] 2019-12-02 12:52
Well , it does the thing exactly you described as not doing.

For example ; i have been using bunch of Feral Interactive ports with a launch parameter.

When i cleanly installed a new version of my distro of choice , launch parameters that i used were still there.

I don't know if that has to do with i backed up most of my games before doing it tho. If that somehow includes all launch parameters in use etc , sorry for bugging.

**Comment by BloodyIron** [comment] 2019-12-02 15:51
I've reinstalled my games (without reinstalling OS, mind you) multiple times and the launch parameters don't get set back up. I'm not reinstalling from backups, I'm downloading again from STEAM servers each time (I have limited SSD space, and fast internet, so this works for me).

I don't think your scenario is quite the same as mine.

**Comment by kisak-valve** [comment] 2021-07-06 19:07
Closing as a duplicate of #3818.

**Closed by kisak-valve** 2021-07-06 19:07 UTC
Labels: Feature Request
