### ISSUE TITLE
Steam will not run on 18.10 with latest nvidia drivers

### ISSUE THREAD

**Issue by tsalwierz** [ValveSoftware/steam-for-linux#5884] opened 2018-11-07 15:33 UTC
* Steam client version (build number or date): Nov 23 2016 1:05:42
* Distribution (e.g. Ubuntu): Ubuntu 18.10
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

Opening steam after running apt-install steam gives the following error. Note that I have tried directly downloading from the steam website as well with the same problem.

steam --reset && steam
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[2018-11-07 07:25:44] Startup - updater built Nov 23 2016 01:05:42
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)

#### Steps for reproducing this issue:

1. Install 18.10 Ubuntu
2.  Install the latest nvidia driver from their site (410.73) (compiled, because it won't install otherwise on 18.10)
3. Install steam, watch it not work.

**Comment by kisak-valve** [comment] 2018-11-07 15:49
Hello @tsalwierz, does any 32 bit opengl application like `glxinfo` from `mesa-utils:i386` work?

Swrast is mesa's slower software renderer and hints that your nvidia driver install is broken or incomplete. You may need `libc6:i386` installed before running nvidia's manual installer or use an appropriate PPA like https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa.

**Comment by tsalwierz** [comment] 2018-11-07 15:59
I've already moved back to 18.04.

When I was on 18.10, glxgears, vulkaninfo and glxinfo all functioned correctly.

I am now running into glXChooseVisual failed errors on 18.04 after install (when trying to run steam).

https://i.imgur.com/skasLwE.jpg

It looks like I might have to stick with Windows 10, as something is clearly not happy about my 2080 ti.

**Comment by kisak-valve** [comment] 2018-11-07 17:09
Again this hints at a broken or incomplete opengl driver install. I'm going to guess that you tested 64 bit glxgears/glxinfo and if you used the PPA, mostly likely need to run something like `sudo apt install nvidia-driver-410 nvidia-driver-410:i386` or maybe `sudo apt install libnvidia-gl-410:i386`. The nvidia driver needs the running kernel module version to match the userspace version, and the 32 bit userspace and 64 bit userspace libraries are in separate packages on ubuntu.

**Comment by QkiZMR** [comment] 2018-11-10 23:44
Thx @kisak-valve, you make my day. On my 18.10 (64bit, Nvidia) everything worked except Steam client. If I want to install 32bit version of nvidia-driver-410 package manager wants to uninstall 64bit. But when I installed libnvidia-gl-410:i386 Steam client start working again. Thanks.

**Comment by kisak-valve** [comment] 2018-11-11 17:51
Thanks, closing as this was a system config issue.f

**Closed by kisak-valve** 2018-11-11 17:51 UTC
Labels: Distro Family: Ubuntu, NVIDIA drivers

**Comment by tribbloid** [comment] 2018-12-20 03:20
Looks like a lot of version conflicts to me:

```
$ sudo apt install libnvidia-gl-410:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  cuda-command-line-tools-10-0 cuda-compiler-10-0 cuda-cublas-10-0 cuda-cublas-dev-10-0 cuda-cudart-10-0 cuda-cudart-dev-10-0 cuda-cufft-10-0 cuda-cufft-dev-10-0 cuda-cuobjdump-10-0 cuda-cupti-10-0 cuda-curand-10-0 cuda-curand-dev-10-0
  cuda-cusolver-10-0 cuda-cusolver-dev-10-0 cuda-cusparse-10-0 cuda-cusparse-dev-10-0 cuda-documentation-10-0 cuda-driver-dev-10-0 cuda-gdb-10-0 cuda-gpu-library-advisor-10-0 cuda-libraries-10-0 cuda-libraries-dev-10-0
  cuda-license-10-0 cuda-memcheck-10-0 cuda-misc-headers-10-0 cuda-npp-10-0 cuda-npp-dev-10-0 cuda-nsight-10-0 cuda-nsight-compute-10-0 cuda-nvcc-10-0 cuda-nvdisasm-10-0 cuda-nvgraph-10-0 cuda-nvgraph-dev-10-0 cuda-nvjpeg-10-0
  cuda-nvjpeg-dev-10-0 cuda-nvml-dev-10-0 cuda-nvprof-10-0 cuda-nvprune-10-0 cuda-nvrtc-10-0 cuda-nvrtc-dev-10-0 cuda-nvtx-10-0 cuda-nvvp-10-0 cuda-samples-10-0 cuda-toolkit-10-0 cuda-tools-10-0 cuda-visual-tools-10-0
  libnvidia-decode-410 libnvidia-encode-410 libnvidia-fbc1-410 libxnvctrl0 nvidia-compute-utils-410 nvidia-dkms-410 nvidia-kernel-common-410 nvidia-kernel-source-410 nvidia-settings nvidia-utils-410 screen-resolution-extra
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  cuda cuda-10-0 cuda-demo-suite-10-0 cuda-drivers cuda-runtime-10-0 libnvidia-gl-410 libnvidia-ifr1-410 nvidia-driver-410
The following NEW packages will be installed:
  libnvidia-gl-410:i386
0 upgraded, 1 newly installed, 8 to remove and 0 not upgraded.
Need to get 0 B/16.6 MB of archives.
After this operation, 90.9 MB disk space will be freed.
Do you want to continue? [Y/n] n
Abort.
```

**Comment by darthdeus** [comment] 2019-01-26 22:58
@tribbloid Did you manage to figure it out? I'm having the exact same setup/issue with `libnvidia-gl-410:i386` conflicting with cuda 10.

**Comment by CarloWood** [comment] 2020-01-16 16:59
I have the same problem, but...

```
sean:~/Downloads>sudo apt install libnvidia-gl-440:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libnvidia-gl-440:i386 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libnvidia-common-440

E: Package 'libnvidia-gl-440:i386' has no installation candidate
```

**Comment by CarloWood** [comment] 2020-01-16 18:34
After removing all nvidia stuff that is versioned (*440* in my case) and then reinstalling (`sudo apt install nvidia-driver-440`) everything worked again (although, I had also removed steam and reinstalled that after reinstalling nvidia; but I doubt that was necessary). Note that upon reinstalling of nvidia-driver-440 it says:
```sean:~>sudo apt install nvidia-driver-440
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libnvidia-cfg1-440 libnvidia-common-440 libnvidia-compute-440 libnvidia-compute-440:i386 libnvidia-decode-440
  libnvidia-decode-440:i386 libnvidia-encode-440 libnvidia-encode-440:i386 libnvidia-fbc1-440 libnvidia-fbc1-440:i386
  libnvidia-gl-440 libnvidia-gl-440:i386 libnvidia-ifr1-440 libnvidia-ifr1-440:i386 libxnvctrl0 nvidia-compute-utils-440
  nvidia-dkms-440 nvidia-kernel-common-440 nvidia-kernel-source-440 nvidia-settings nvidia-utils-440 screen-resolution-extra
  xserver-xorg-video-nvidia-440
The following NEW packages will be installed:
  libnvidia-cfg1-440 libnvidia-common-440 libnvidia-compute-440:i386 libnvidia-decode-440 libnvidia-decode-440:i386
  libnvidia-encode-440 libnvidia-encode-440:i386 libnvidia-fbc1-440 libnvidia-fbc1-440:i386 libnvidia-gl-440 libnvidia-gl-440:i386
  libnvidia-ifr1-440 libnvidia-ifr1-440:i386 libxnvctrl0 nvidia-compute-utils-440 nvidia-dkms-440 nvidia-driver-440
  nvidia-kernel-common-440 nvidia-kernel-source-440 nvidia-settings nvidia-utils-440 screen-resolution-extra
  xserver-xorg-video-nvidia-440
The following packages will be upgraded:
  libnvidia-compute-440
1 upgraded, 23 newly installed, 0 to remove and 46 not upgraded.
Need to get 142 MB of archives.
After this operation, 416 MB of additional disk space will be used.
Do you want to continue? [Y/n]```

So apparently libnvidia-gl-440:i386 *does* exist. I don't know why it wouldn't install before.

**Comment by leimao** [comment] 2020-02-24 05:12
Mark

**Comment by leimao** [comment] 2020-02-24 05:45
> After removing all nvidia stuff that is versioned (`*440*` in my case) and then reinstalling (`sudo apt install nvidia-driver-440`) everything worked again (although, I had also removed steam and reinstalled that after reinstalling nvidia; but I doubt that was necessary). Note that upon reinstalling of nvidia-driver-440 it says:
> 
> ```
> sean:~>sudo apt install nvidia-driver-440
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following additional packages will be installed:
>   libnvidia-cfg1-440 libnvidia-common-440 libnvidia-compute-440 libnvidia-compute-440:i386 libnvidia-decode-440
>   libnvidia-decode-440:i386 libnvidia-encode-440 libnvidia-encode-440:i386 libnvidia-fbc1-440 libnvidia-fbc1-440:i386
>   libnvidia-gl-440 libnvidia-gl-440:i386 libnvidia-ifr1-440 libnvidia-ifr1-440:i386 libxnvctrl0 nvidia-compute-utils-440
>   nvidia-dkms-440 nvidia-kernel-common-440 nvidia-kernel-source-440 nvidia-settings nvidia-utils-440 screen-resolution-extra
>   xserver-xorg-video-nvidia-440
> The following NEW packages will be installed:
>   libnvidia-cfg1-440 libnvidia-common-440 libnvidia-compute-440:i386 libnvidia-decode-440 libnvidia-decode-440:i386
>   libnvidia-encode-440 libnvidia-encode-440:i386 libnvidia-fbc1-440 libnvidia-fbc1-440:i386 libnvidia-gl-440 libnvidia-gl-440:i386
>   libnvidia-ifr1-440 libnvidia-ifr1-440:i386 libxnvctrl0 nvidia-compute-utils-440 nvidia-dkms-440 nvidia-driver-440
>   nvidia-kernel-common-440 nvidia-kernel-source-440 nvidia-settings nvidia-utils-440 screen-resolution-extra
>   xserver-xorg-video-nvidia-440
> The following packages will be upgraded:
>   libnvidia-compute-440
> 1 upgraded, 23 newly installed, 0 to remove and 46 not upgraded.
> Need to get 142 MB of archives.
> After this operation, 416 MB of additional disk space will be used.
> Do you want to continue? [Y/n]
> ```
> 
> So apparently libnvidia-gl-440:i386 _does_ exist. I don't know why it wouldn't install before.
> 
> Oh, actually I might... because I also installed the ppa. Here is the full list of commands that I ran:
> 
> ```
> sudo add-apt-repository ppa:graphics-drivers/ppa
> sudo apt remove 'nvidia-*-440'
> sudo apt autoremove
> sudo apt install nvidia-driver-440
> sudo reboot
> ```
> 
> This removed cuda in the process without reinstalling it. I haven't reinstalled that yet.
> It is possible that the removal of cuda-10 allowed the i386 packages of nvidia to be installed, so that might be important.

This is almost good. For some users who have conflicting added apt repositories, i386 packages would not be installed. To resolve this, remove the added apt repositories from Ubuntu Software & Updates.

**Comment by rocharhs** [comment] 2020-08-29 03:58
The issue is not that cuda 10 doesn't support 32-bit, but that steam doesn't support 64-bit on linux in the year of 2020!
