### ISSUE TITLE
Special letters don't work in Steam Chat

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#6866] opened 2020-02-05 00:59 UTC
#### Your system information

* Steam client version: 
![image](https://user-images.githubusercontent.com/42655600/73800447-6bbc8a80-47c1-11ea-9bc1-1b945a4cb46d.png)
* Distribution: Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The letters ÅÄÖ don't work in the Steam Chat
Demonstrative video: https://youtu.be/vuuQYe--Q70
System information: https://gist.github.com/Managor/498f5e6fd58a16291a99494005de90be

**Comment by kisak-valve** [comment] 2020-02-05 01:05
Hello @Managor, this looks like #5704, what's does `locale -a` output?

**Comment by Managor** [comment] 2020-02-05 01:12
$ locale -a
C
en_GB.utf8
fi_FI.utf8
POSIX

**Comment by kisak-valve** [comment] 2020-02-05 01:17
Thanks, as noted in that issue report, please add `en_US.UTF-8 UTF-8` to `/etc/locale.gen` and run `locale-gen` as root to regenerate the system localizations, then restart Steam and retest to confirm this is a duplicate of #5704.

**Comment by Managor** [comment] 2020-02-05 03:40
Yes, that got it working.

**Closed** 2020-02-05 04:39 UTC
Labels: Need Retest, Steam client, duplicate, localization
