### ISSUE TITLE
use linux version of dosbox instead of running the windows version through proton

### ISSUE THREAD

**Issue by mtmkls** [ValveSoftware/steam-for-linux#7338] opened 2020-08-28 23:11 UTC
It's silly.

**Comment by kisak-valve** [comment] 2020-08-28 23:14
Duplicate of https://github.com/ValveSoftware/Proton/issues/1566. Also, https://github.com/dreamer/boxtron is out there as an option.

**Closed by kisak-valve** 2020-08-28 23:14 UTC
