### ISSUE TITLE
browse local files not working

### ISSUE THREAD

**Issue by lahtis** [ValveSoftware/steam-for-linux#4560] opened 2016-07-21 10:08 UTC
#### Your system information

* Steam client version: steam-runtime-beta-release_2016-06-15
* Distribution (e.g. Ubuntu): 16.04.1 Ubuntu 
* Opted into Steam client beta?: No 
* Have you checked for system updates?: Yes

#### Steps for reproducing this issue:

1. game browse local files not opened. Game has installed. 
When you go to game properties -> LOCAL FILES -> Browse local files 
2. nothing happened. Files not opened. 
3.

**Comment by Tele42** [comment] 2016-07-21 12:49
Hello @lahtis, this was identified as an issue with steam's usage of xdg-open and has already been fixed in the beta client.
Duplicate of #4528.

**Comment by gdrewb-valve** [comment] 2016-07-21 16:30
Closing duplicate.

**Closed by gdrewb-valve** 2016-07-21 16:30 UTC

**Comment by Inotamira** [comment] 2019-10-01 09:50
Issue is not resolved
