### ISSUE TITLE
Please tell me the answer, don't just write me off (Chromebook running LINUX Steam)

### ISSUE THREAD

**Issue by Kenarik** [ValveSoftware/steam-for-linux#10654] opened 2024-03-22 07:59 UTC
#### Your system information

* Steam client version (build number or date): I don't know, been having issues since late February
* Distribution (e.g. Ubuntu):  Debian 
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] no
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU:  Intel

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

My laptop has the ability to run Linux (yes it's a Chromebook), I have successfully run Steam off of said laptop for 2+ years. This past February (2024) I tried logging in and got a completely black screen. Steam Support is no help telling me I have to use the Chrome OS Beta. I have modified the game I play and can not do that with the Chrome version of Steam. ALL I want is for the Linux version to work properly again so I can play the game I have with the mods (and brand new update to 1.6) I love.

IF I have to go yell at Chrome, please tell me. Don't label it as a ChromeOS issue and not respond. IT is very frustrating not to be able to enjoy the game I got gifted from my eldest kid

#### Steps for reproducing this issue:

1. Have an Linux capable Chromebook
2. Try to install Steam
3. Get a big black screen where the library should be

**Comment by kisak-valve** [comment] 2024-03-22 12:40
Hello @Kenarik, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #10578.

**Closed by kisak-valve** 2024-03-22 12:40 UTC
