### ISSUE TITLE
Update downloads are scheduled in the future

### ISSUE THREAD

**Issue by koraktor** [ValveSoftware/steam-for-linux#3672] opened 2015-01-16 06:22 UTC
Since a few weeks it seems there's a issue with how Steam schedules downloads. In the last days I have been able to verify that this is a problem that occurs when the client is running and new updates become available.

In that case, it seems that the client schedules the download a few hours in the future. The download is marked as "Planned for `time`". I have never seen this before a few weeks ago and there's only one setting that might be related to this: Downloads restrictions, Limit auto-updating schedule. (I don't have this enabled.)
It might be related to time zones – just a wild guess.

This does not happen when the client downloads updates after it has been started.

I'm on OS X 10.10.2.

**Comment by beansmyname** [comment] 2015-01-16 16:21
This feature was added to the beta client on 2014-12-02:
http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/213122562640364629

"When Steam has internally scheduled a game update to be queued some time
in the future, the UI will now display a note to the user indicating that
time"

Sounds like the behaviour of the client remained the same, but the UI was
altered to expose this information. Prior to the update, the UI showed
"Download queued" with no indication of time.

On Thu, Jan 15, 2015 at 10:22 PM, Sebastian Staudt <notifications@github.com
> wrote:

> Since a few weeks it seems there's a issue with how Steam schedules
> downloads. In the last days I have been able to verify that this is a
> problem that occurs when the client is running and new updates become
> available.
>
> In that case, it seems that the client schedules the download a few hours
> in the future. The download is marked as "Planned for time". I have never
> seen this before a few weeks ago and there's only one setting that might be
> related to this: Downloads restrictions, Limit auto-updating schedule.
> It might be related to time zones – just a wild guess.
>
> This does not happen when the client downloads updates after it has been
> started.
>
> I'm on OS X 10.10.2.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ValveSoftware/steam-for-linux/issues/3672>.
>



-- 
The world is full of tough guys.  It doesn't need me to be one, too.

**Comment by koraktor** [comment] 2015-01-16 16:36
OK, sounds like this is expected behavior.

I’d have to rephrase my initial issue then. I don't like that behavior as I see no reason why downloads should be delayed on my end.

If this is some sort of load balancing on Steam’s backend this might be valid, but the UI should state this clearly.

**Comment by kisak-valve** [comment] 2018-06-01 14:01
Closing as this is the intended behavior and not OS specific.

**Closed by kisak-valve** 2018-06-01 14:01 UTC
Labels: reviewed
