### ISSUE TITLE
Keyboard not showing up in desktop mode

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#10851] opened 2024-05-04 13:20 UTC
#### Your system information

* SteamOS version: 3.5.19
* Client build date : 2024.05.04
* Opted into SteamOS beta?: Yes

#### Please describe your issue in as much detail as possible: 
In desktop mode the virtual keyboard isn't showing up with X button or Steam + X, in Gamescope it is.

Also as commented in this post https://steamcommunity.com/groups/SteamClientBeta/discussions/0/4357872384980987794/
*on top of that, all controls are disabled. Buttons, sticks, trackpads, triggers. Only the cursor on the touch screen functions after trying to enable the on-screen keyboard. If you move the cursor to another window in which there was no attempt to enable the on-screen keyboard, the controls work again. However, if you return to the window in which you tried to launch the keyboard, the controls are turned off again.*

#### Steps for reproducing this issue:

1. Go in desktop mode
2. Select a text field
3. Push X or Steam + X

**Comment by kisak-valve** [comment] 2024-05-04 13:47
Hello @ciel-d-automne, this reads like an issue with Steam, not SteamOS as a platform, so I've transferred this issue to the steam-for-linux issue tracker.

Likely a duplicate of #10849.

**Closed as completed** 2024-07-16 17:13 UTC
Labels: duplicate, Distro Family: SteamOS, General controller / Steam Input
