### ISSUE TITLE
[CRASH][DBUS] Steam client crashes regurlaly

### ISSUE THREAD

**Issue by DistantThunder** [ValveSoftware/steam-for-linux#7028] opened 2020-04-13 11:10 UTC
#### Your system information

I understand this issue may be closed or ignored due to not running on an officially supported distribution. I still found the issue relevant to report and hopefully get solved.

* Steam client version (build number or date): `Apr 4 2020, 00:37`
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [No] 
* Have you checked for system updates?: [Yes]

<details><summary>System Information</summary><p>

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 7 3700X 8-Core Processor             
    CPU Family:  0x17
    CPU Model:  0x71
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4050 Mhz
    16 logical processors
    8 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.6.3-zen1-1-zen
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12008000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime_0.20200318.2

Video Card:
    Driver:  X.Org AMD Radeon RX 5700 XT (NAVI10, DRM 3.36.0, 5.6.3-zen1-1-zen, LLVM 9.0.1)
    Driver Version:  4.6 (Compatibility Profile) Mesa 20.0.4
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 143 Hz
    VendorID:  0x1002
    DeviceID:  0x731f
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 2560 x 1440
    Primary Display Size: 23.50" x 13.23" (26.97" diag)
                                            59.7cm x 33.6cm (68.5cm diag)
    Primary VRAM: 8192 MB

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  32047 Mb

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  fr_FR.UTF-8
    Total Hard Disk Space Available:  32125 Mb
    Largest Free Hard Disk Block:  3702 Mb

Steam Linux Runtime Information:
{
  "can-write-uinput" : true,
  "steam-installation" : {
    "path" : "/home/USER/.local/share/Steam",
    "data_path" : "/home/USER/.local/share/Steam",
    "issues" : [
    ]
  },
  "runtime" : {
    "path" : "/home/USER/.local/share/Steam/ubuntu12_32/steam-runtime",
    "version" : "0.20200318.2",
    "issues" : [
    ],
    "pinned_libs_32" : {
      "list" : [
        "   828014      4 drwxr-xr-x   2 USER  USER      4096 mars 27 12:36 pinned_libs_32",
        "   787194      4 -rw-r--r--   1 USER  USER        55 mars 27 12:36 pinned_libs_32/system_libudev.so.0",
        "   786829      4 -rw-r--r--   1 USER  USER        69 mars 27 12:36 pinned_libs_32/system_libdbusmenu-gtk.so.4",
        "   786783      4 lrwxrwxrwx   1 USER  USER       107 mars 27 12:36 pinned_libs_32/libdbusmenu-gtk.so.4 -> /home/USER/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libdbusmenu-gtk.so.4.0.13",
        "   787196      4 -rw-r--r--   1 USER  USER        58 mars 27 12:36 pinned_libs_32/system_libdbus-1.so.3",
        "   786886      4 lrwxrwxrwx   1 USER  USER        98 mars 27 12:36 pinned_libs_32/libjack.so.0 -> /home/USER/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libjack.so.0.1.0",
        "   786948      4 -rw-r--r--   1 USER  USER        53 mars 27 12:36 pinned_libs_32/system_libjack.so.0",
        "   787199      0 lrwxrwxrwx   1 USER  USER        12 mars 27 12:36 pinned_libs_32/libcurl.so.3 -> libcurl.so.4",
        "   787193      4 lrwxrwxrwx   1 USER  USER        95 mars 27 12:36 pinned_libs_32/libudev.so.0 -> /home/USER/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu/libudev.so.0.13.0",
        "   786832      0 -rw-r--r--   1 USER  USER         0 mars 27 12:36 pinned_libs_32/has_pins",
        "   786967      4 lrwxrwxrwx   1 USER  USER       101 mars 27 12:36 pinned_libs_32/libGLU.so.1 -> /home/USER/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libGLU.so.1.3.08004",
        "   786981      4 lrwxrwxrwx   1 USER  USER        98 mars 27 12:36 pinned_libs_32/libcurl.so.4 -> /home/USER/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libcurl.so.4.2.0",
        "   786979      4 -rw-r--r--   1 USER  USER        50 mars 27 12:36 pinned_libs_32/system_libGLU.so.1",
        "   787000      4 lrwxrwxrwx   1 USER  USER       108 mars 27 12:36 pinned_libs_32/libdbusmenu-glib.so.4 -> /home/USER/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libdbusmenu-glib.so.4.0.13",
        "   787005      4 -rw-r--r--   1 USER  USER        71 mars 27 12:36 pinned_libs_32/system_libdbusmenu-glib.so.4",
        "   786999      4 -rw-r--r--   1 USER  USER        52 mars 27 12:36 pinned_libs_32/system_libcurl.so.4",
        "   787098      4 -rw-r--r--   1 USER  USER        70 mars 27 12:36 pinned_libs_32/system_libgtk-x11-2.0.so.0",
        "   787097      4 lrwxrwxrwx   1 USER  USER       109 mars 27 12:36 pinned_libs_32/libgtk-x11-2.0.so.0 -> /home/USER/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0.2400.10",
        "   787195      4 lrwxrwxrwx   1 USER  USER        96 mars 27 12:36 pinned_libs_32/libdbus-1.so.3 -> /home/USER/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu/libdbus-1.so.3.5.8"
      ]
    },
    "pinned_libs_64" : {
      "list" : [
        "   828015      4 drwxr-xr-x   2 USER  USER      4096 mars 27 12:36 pinned_libs_64",
        "   787198      4 -rw-r--r--   1 USER  USER        51 mars 27 12:36 pinned_libs_64/system_libudev.so.0",
        "   787100      4 -rw-r--r--   1 USER  USER        65 mars 27 12:36 pinned_libs_64/system_libdbusmenu-gtk.so.4",
        "   787099      4 lrwxrwxrwx   1 USER  USER       109 mars 27 12:36 pinned_libs_64/libdbusmenu-gtk.so.4 -> /home/USER/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libdbusmenu-gtk.so.4.0.13",
        "   787184      4 lrwxrwxrwx   1 USER  USER       100 mars 27 12:36 pinned_libs_64/libjack.so.0 -> /home/USER/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libjack.so.0.1.0",
        "   787186      4 -rw-r--r--   1 USER  USER        49 mars 27 12:36 pinned_libs_64/system_libjack.so.0",
        "   787200      0 lrwxrwxrwx   1 USER  USER        12 mars 27 12:36 pinned_libs_64/libcurl.so.3 -> libcurl.so.4",
        "   787197      4 lrwxrwxrwx   1 USER  USER        97 mars 27 12:36 pinned_libs_64/libudev.so.0 -> /home/USER/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu/libudev.so.0.13.0",
        "   787174      0 -rw-r--r--   1 USER  USER         0 mars 27 12:36 pinned_libs_64/has_pins",
        "   787187      4 lrwxrwxrwx   1 USER  USER       103 mars 27 12:36 pinned_libs_64/libGLU.so.1 -> /home/USER/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libGLU.so.1.3.08004",
        "   787189      4 lrwxrwxrwx   1 USER  USER       100 mars 27 12:36 pinned_libs_64/libcurl.so.4 -> /home/USER/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libcurl.so.4.2.0",
        "   787188      4 -rw-r--r--   1 USER  USER        46 mars 27 12:36 pinned_libs_64/system_libGLU.so.1",
        "   787191      4 lrwxrwxrwx   1 USER  USER       110 mars 27 12:36 pinned_libs_64/libdbusmenu-glib.so.4 -> /home/USER/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libdbusmenu-glib.so.4.0.13",
        "   787192      4 -rw-r--r--   1 USER  USER        67 mars 27 12:36 pinned_libs_64/system_libdbusmenu-glib.so.4",
        "   787190      4 -rw-r--r--   1 USER  USER        48 mars 27 12:36 pinned_libs_64/system_libcurl.so.4"
      ]
    }
  },
  "os-release" : {
    "id" : "arch",
    "name" : "Arch Linux",
    "pretty_name" : "Arch Linux",
    "build_id" : "rolling"
  },
  "container" : {
    "type" : "none"
  },
  "driver_environment" : [
  ],
  "architectures" : {
    "i386-linux-gnu" : {
      "can-run" : true,
      "library-issues-summary" : [
      ],
      "graphics-details" : {
        "x11/vulkan" : {
          "messages" : "WARNING: [Loader Message] Code 0 : Didn't find required layer object disable_environment in manifest JSON file, skipping this layer\nERROR: [Loader Message] Code 0 : /usr/lib/libvulkan_radeon.so: wrong ELF class: ELFCLASS64\nERROR: [Loader Message] Code 0 : /home/USER/.local/share/Steam/ubuntu12_64/steamoverlayvulkanlayer.so: wrong ELF class: ELFCLASS64\nWARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely\nWARNING: disabling NGG because ACO is used.\nWARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely\nWARNING: disabling NGG because ACO is used.\n",
          "renderer" : "AMD RADV/ACO NAVI10 (LLVM 9.0.1)",
          "version" : "1.2.128 (device 1002:731f) (driver 20.0.4)"
        },
        "glx/gl" : {
          "renderer" : "AMD Radeon RX 5700 XT (NAVI10, DRM 3.36.0, 5.6.3-zen1-1-zen, LLVM 9.0.1)",
          "version" : "4.6 (Compatibility Profile) Mesa 20.0.4",
          "library-vendor" : "glvnd"
        },
        "egl_x11/gl" : {
          "renderer" : "AMD Radeon RX 5700 XT (NAVI10, DRM 3.36.0, 5.6.3-zen1-1-zen, LLVM 9.0.1)",
          "version" : "4.6 (Compatibility Profile) Mesa 20.0.4",
          "library-vendor" : "glvnd"
        },
        "egl_x11/glesv2" : {
          "renderer" : "AMD Radeon RX 5700 XT (NAVI10, DRM 3.36.0, 5.6.3-zen1-1-zen, LLVM 9.0.1)",
          "version" : "OpenGL ES 3.2 Mesa 20.0.4",
          "library-vendor" : "glvnd"
        }
      },
      "dri_drivers" : [
        {
          "library_path" : "/usr/lib32/dri/i915_dri.so"
        },
        {
          "library_path" : "/usr/lib32/dri/i965_dri.so"
        },
        {
          "library_path" : "/usr/lib32/dri/iris_dri.so"
        },
        {
          "library_path" : "/usr/lib32/dri/kms_swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib32/dri/nouveau_dri.so"
        },
        {
          "library_path" : "/usr/lib32/dri/nouveau_vieux_dri.so"
        },
        {
          "library_path" : "/usr/lib32/dri/r200_dri.so"
        },
        {
          "library_path" : "/usr/lib32/dri/r300_dri.so"
        },
        {
          "library_path" : "/usr/lib32/dri/r600_dri.so"
        },
        {
          "library_path" : "/usr/lib32/dri/radeon_dri.so"
        },
        {
          "library_path" : "/usr/lib32/dri/radeonsi_dri.so"
        },
        {
          "library_path" : "/usr/lib32/dri/swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib32/dri/virtio_gpu_dri.so"
        },
        {
          "library_path" : "/usr/lib32/dri/vmwgfx_dri.so"
        }
      ],
      "va-api_drivers" : [
      ],
      "vdpau_drivers" : [
        {
          "library_path" : "/usr/lib32/vdpau/libvdpau_nouveau.so",
          "library_link" : "libvdpau_nouveau.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib32/vdpau/libvdpau_nouveau.so.1",
          "library_link" : "libvdpau_nouveau.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib32/vdpau/libvdpau_nvidia.so",
          "library_link" : "libvdpau_nvidia.so.1"
        },
        {
          "library_path" : "/usr/lib32/vdpau/libvdpau_nvidia.so.1",
          "library_link" : "libvdpau_nvidia.so.440.82"
        },
        {
          "library_path" : "/usr/lib32/vdpau/libvdpau_r300.so",
          "library_link" : "libvdpau_r300.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib32/vdpau/libvdpau_r300.so.1",
          "library_link" : "libvdpau_r300.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib32/vdpau/libvdpau_r600.so",
          "library_link" : "libvdpau_r600.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib32/vdpau/libvdpau_r600.so.1",
          "library_link" : "libvdpau_r600.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib32/vdpau/libvdpau_radeonsi.so",
          "library_link" : "libvdpau_radeonsi.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib32/vdpau/libvdpau_radeonsi.so.1",
          "library_link" : "libvdpau_radeonsi.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib32/vdpau/libvdpau_trace.so",
          "library_link" : "libvdpau_trace.so.1"
        },
        {
          "library_path" : "/usr/lib32/vdpau/libvdpau_trace.so.1",
          "library_link" : "libvdpau_trace.so.1.0.0"
        }
      ],
      "glx_drivers" : [
        {
          "library_soname" : "libGLX_indirect.so.0",
          "library_path" : "/usr/lib32/libGLX_mesa.so.0.0.0"
        },
        {
          "library_soname" : "libGLX_nvidia.so.0",
          "library_path" : "/usr/lib32/libGLX_nvidia.so.440.82"
        },
        {
          "library_soname" : "libGLX_mesa.so.0",
          "library_path" : "/usr/lib32/libGLX_mesa.so.0.0.0"
        }
      ]
    },
    "x86_64-linux-gnu" : {
      "can-run" : true,
      "library-issues-summary" : [
      ],
      "graphics-details" : {
        "x11/vulkan" : {
          "messages" : "WARNING: [Loader Message] Code 0 : Didn't find required layer object disable_environment in manifest JSON file, skipping this layer\nERROR: [Loader Message] Code 0 : /usr/lib32/libvulkan_radeon.so: wrong ELF class: ELFCLASS32\nERROR: [Loader Message] Code 0 : /home/USER/.local/share/Steam/ubuntu12_32/steamoverlayvulkanlayer.so: wrong ELF class: ELFCLASS32\nWARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely\nWARNING: disabling NGG because ACO is used.\nWARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely\nWARNING: disabling NGG because ACO is used.\n",
          "renderer" : "AMD RADV/ACO NAVI10 (LLVM 9.0.1)",
          "version" : "1.2.128 (device 1002:731f) (driver 20.0.4)"
        },
        "glx/gl" : {
          "messages" : "libGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/USER/.drirc: No such file or directory.\nlibGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/USER/.drirc: No such file or directory.\nlibGL: pci id for fd 4: 1002:731f, driver radeonsi\nlibGL: MESA-LOADER: dlopen(/usr/lib/dri/radeonsi_dri.so)\nlibGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/USER/.drirc: No such file or directory.\nlibGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/USER/.drirc: No such file or directory.\nlibGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/USER/.drirc: No such file or directory.\n/usr/share/libdrm/amdgpu.ids version: 1.0.0\nlibGL: Using DRI3 for screen 0\nterminate called after throwing an instance of '__gnu_cxx::recursive_init_error'\n  what():  std::exception\ntimeout: la commande surveillée a renvoyé un core dump\n",
          "renderer" : "AMD Radeon RX 5700 XT (NAVI10, DRM 3.36.0, 5.6.3-zen1-1-zen, LLVM 9.0.1)",
          "version" : "4.6 (Compatibility Profile) Mesa 20.0.4",
          "library-vendor" : "glvnd",
          "issues" : [
            "cannot-draw"
          ],
          "terminating-signal" : 6,
          "terminating-signal-name" : "Aborted"
        },
        "egl_x11/gl" : {
          "renderer" : "AMD Radeon RX 5700 XT (NAVI10, DRM 3.36.0, 5.6.3-zen1-1-zen, LLVM 9.0.1)",
          "version" : "4.6 (Compatibility Profile) Mesa 20.0.4",
          "library-vendor" : "glvnd"
        },
        "egl_x11/glesv2" : {
          "renderer" : "AMD Radeon RX 5700 XT (NAVI10, DRM 3.36.0, 5.6.3-zen1-1-zen, LLVM 9.0.1)",
          "version" : "OpenGL ES 3.2 Mesa 20.0.4",
          "library-vendor" : "glvnd"
        }
      },
      "dri_drivers" : [
        {
          "library_path" : "/usr/lib/dri/i915_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/i965_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/iris_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/kms_swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/nouveau_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/nouveau_vieux_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/r200_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/r300_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/r600_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/radeon_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/radeonsi_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/virtio_gpu_dri.so"
        },
        {
          "library_path" : "/usr/lib/dri/vmwgfx_dri.so"
        }
      ],
      "va-api_drivers" : [
        {
          "library_path" : "/usr/lib/dri/iHD_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/dri/nouveau_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/dri/r600_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/dri/radeonsi_drv_video.so"
        }
      ],
      "vdpau_drivers" : [
        {
          "library_path" : "/usr/lib/vdpau/libvdpau_nvidia.so",
          "library_link" : "libvdpau_nvidia.so.1"
        },
        {
          "library_path" : "/usr/lib/vdpau/libvdpau_nvidia.so.1",
          "library_link" : "libvdpau_nvidia.so.440.82"
        },
        {
          "library_path" : "/usr/lib/vdpau/libvdpau_trace.so",
          "library_link" : "libvdpau_trace.so.1"
        },
        {
          "library_path" : "/usr/lib/vdpau/libvdpau_trace.so.1",
          "library_link" : "libvdpau_trace.so.1.0.0"
        }
      ],
      "glx_drivers" : [
        {
          "library_soname" : "libGLX_indirect.so.0",
          "library_path" : "/usr/lib/libGLX_mesa.so.0.0.0"
        },
        {
          "library_soname" : "libGLX_nvidia.so.0",
          "library_path" : "/usr/lib/libGLX_nvidia.so.440.82"
        },
        {
          "library_soname" : "libGLX_mesa.so.0",
          "library_path" : "/usr/lib/libGLX_mesa.so.0.0.0"
        }
      ]
    }
  },
  "locale-issues" : [
    "c-utf8-missing",
    "i18n-supported-missing"
  ],
  "locales" : {
    "<default>" : {
      "resulting-name" : "fr_FR.UTF-8",
      "charset" : "UTF-8",
      "is_utf8" : true
    },
    "C" : {
      "resulting-name" : "C",
      "charset" : "ANSI_X3.4-1968",
      "is_utf8" : false
    },
    "C.UTF-8" : {
      "error-domain" : "srt-locale-error-quark",
      "error-code" : 0,
      "error" : "No such file or directory"
    },
    "en_US.UTF-8" : {
      "resulting-name" : "en_US.UTF-8",
      "charset" : "UTF-8",
      "is_utf8" : true
    }
  },
  "egl" : {
    "icds" : [
      {
        "json_path" : "/usr/share/glvnd/egl_vendor.d/10_nvidia.json",
        "library_path" : "libEGL_nvidia.so.0"
      },
      {
        "json_path" : "/usr/share/glvnd/egl_vendor.d/50_mesa.json",
        "library_path" : "libEGL_mesa.so.0"
      }
    ]
  },
  "vulkan" : {
    "icds" : [
      {
        "json_path" : "/usr/share/vulkan/icd.d/nvidia_icd.json",
        "library_path" : "libGLX_nvidia.so.0",
        "api_version" : "1.1.119"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/radeon_icd.i686.json",
        "library_path" : "/usr/lib32/libvulkan_radeon.so",
        "api_version" : "1.2.128"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/radeon_icd.x86_64.json",
        "library_path" : "/usr/lib/libvulkan_radeon.so",
        "api_version" : "1.2.128"
      }
    ]
  }
}

The Steam Linux Runtime container tool is not installed.
```

</p></details>

#### Please describe your issue in as much detail as possible:

I was playing native Rise of The Tomb Raider in multiplayer mode when the application crashed along with the Steam Client unexpectedly in the middle of gameplay.

* [Coredumps](http://dl.free.fr/ht7Zd0WRt)
* `local/dbus 1.12.16-5`
#### Steps for reproducing this issue:

1. Play the game in Expedition multiplayer mode

**Comment by DistantThunder** [comment] 2020-04-14 14:58
Hi, 

I'm narrowing this down to the Steam Client itself.
I had another crash today and no game was running. Again, the SIGSEV in klog points to libdbus.

* [Coredumps](http://dl.free.fr/jig8MzLmS)

**Comment by smcv** [comment] 2020-04-15 11:53
There have been other reports of warnings and assertion failures in libdbus with Steam, which point to a bug in either libdbus or code that calls into it. I know SDL has had bugs in the way it interacted with libdbus in the past, so that's one possibility.

Is there anything you can do that causes this to happen more frequently, like interacting with a particular bit of the Steam UI or your desktop environment's UI?

Do you use/have any of these services? ibus, fcitx, rtkit, upower. (Those are the D-Bus services that SDL is known to interact with.)

**Comment by smcv** [comment] 2020-04-15 11:57
Another thing you could try is to run Steam from a terminal (Konsole, xterm or similar), and if it crashes, copy its recent output from that terminal into this bug report.

Perhaps also useful: If you `export DBUS_FATAL_WARNINGS=1`, Steam (and games) will be more likely to crash with a somewhat useful warning if they use libdbus wrong or encounter a libdbus bug, which might help us to understand what's crashing and why.

**Comment by DistantThunder** [comment] 2020-04-15 17:41
The crashes are kind of daily now that I've noticed them.
 
I don't do anything in particular with Steam when they happen. It's usually running foreground or minimized on some other workspace.

I took the habit of opening it in a terminal to try and see if I could catch something.

Last time this was the console output: 
```
(steam:327058): GLib-GObject-CRITICAL **: 18:23:42.714: g_type_instance_get_private: assertion 'instance != NULL && instance->g_class != NULL' failed
Opted-in Controller Mask for AppId 0: 0
Opted-in Controller Mask for AppId 0: 0
Opted-in Controller Mask for AppId 0: 0
[351970]Non-Steam Controller Configs Enabled: 1
Opted-in Controller Mask for AppId 351970: 0
Opted-in Controller Mask for AppId 413080: 0
assert_20200414163841_1.dmp[337539]: Uploading dump (out-of-process)
/tmp/dumps/assert_20200414163841_1.dmp
/home/darkeox/.local/share/Steam/steam.sh : ligne 722 : 327058 Erreur de segmentation  (core dumped)$STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20200414163841_1.dmp[337539]: Finished uploading minidump (out-of-process): success = yes
assert_20200414163841_1.dmp[337539]: response: CrashID=bp-dd6e57da-fd7e-4b95-889d-ace522200414
assert_20200414163841_1.dmp[337539]: file ''/tmp/dumps/assert_20200414163841_1.dmp'', upload yes: ''CrashID=bp-dd6e57da-fd7e-4b95-889d-ace522200414''
```
I've noticed it produces dump files, so here's the one for that crash.

* [assert_20200414163841_1.dmp.zip](https://github.com/ValveSoftware/steam-for-linux/files/4482818/assert_20200414163841_1.dmp.zip)

**Comment by smcv** [comment] 2020-04-15 17:55
I think the LIBDBUSMENU-GLIB-WARNINGs are normal; I'm not sure whether they indicate a bug in libdbusmenu-glib or in Steam or what, but either way they seem harmless.

**Comment by DistantThunder** [comment] 2020-04-16 15:25
Another crash today after 4.92 hour of operation at 14:37 doing essentially nothing (no user interaction that is).

```
(steam:371806): Gtk-WARNING **: 09:47:28.819: gtk_disable_setlocale() must be called before gtk_init()
[0416/102132.807472:WARNING:keyboard_code_conversion_x.cc(1441)] Unknown keycode:108
[500]Non-Steam Controller Configs Enabled: 1
Opted-in Controller Mask for AppId 500: 0
assert_20200416094217_1.dmp[382008]: Uploading dump (out-of-process)
/tmp/dumps/assert_20200416094217_1.dmp
No minidump written, nothing to upload.
No minidump written, nothing to upload.
No minidump written, nothing to upload.
/home/_user_/.local/share/Steam/steam.sh : ligne 722 : 371806 Erreur de segmentation  (core dumped)$STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20200416094217_1.dmp[382008]: Finished uploading minidump (out-of-process): success = yes
assert_20200416094217_1.dmp[382008]: response: CrashID=bp-bd5689fe-11fe-4d84-914b-7fa292200416
assert_20200416094217_1.dmp[382008]: file ''/tmp/dumps/assert_20200416094217_1.dmp'', upload yes: ''CrashID=bp-bd5689fe-11fe-4d84-914b-7fa292200416''
```
The LIBDBUS env var didn't catch anything it seems.

**Comment by TTimo** [comment] 2020-04-16 20:16
Hello @DistantThunder - can you test and reproduce this against the Steam beta client? You indicated you are not using beta - which is consistent with your Apr 4th build date. There is a fix that may affect this problem in Steam beta.

**Comment by TTimo** [comment] 2020-04-16 20:23
Pending confirmation above, will be closing as duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/6911

**Closed by TTimo** 2020-04-16 20:23 UTC
Labels: 3rd party game, Distro Family: Arch, Steam client

**Comment by DistantThunder** [comment] 2020-04-19 16:04
Hi, I'm not very comfortable with the beta since I've heard horror stories about bugs it may introduce, but for this particular issue, I confirm I haven't crashed ever since switching to Beta.
