### ISSUE TITLE
Steam client hangs/freezes every few seconds since upgrading to Ubuntu 21.10

### ISSUE THREAD

**Issue by DomiStyle** [ValveSoftware/steam-for-linux#8150] opened 2021-10-15 21:30 UTC
#### Your system information

* Steam client version (build number or date): Oct 13 2021, at 19:47:24
* Distribution (e.g. Ubuntu): Ubuntu 21.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam hangs every few seconds since updating to Ubuntu 21.10. CPU usage for steamwebhelper spikes while it's stuck. Normal operation will resume after 1-2 seconds.

There isn't really anything going on in the logs while it hangs.

One thing I noticed is that the SteamVR icon on the top right is always visible, even with no VR headset connected. Before upgrading it only appeared when a VR headset is connected.

#### Steps for reproducing this issue:

1. Upgrade Ubuntu 21.04 to 21.10
2. Start Steam
3. Click around the interface, scroll up and down, switch tabs, open chat windows

**Comment by kisak-valve** [comment] 2021-10-15 21:41
Hello @DomiStyle, this reads like #7245. Please give that issue report a read and check if you're seeing the same symptoms as described there. Are you using a X-based or Wayland-based user session?

What video card / driver version are you using? Also, can you check if `Steam` -> `Settings` -> `Interface` -> `Enable GPU accelerated rendering in web views` is unchecked, and if it is, if enabling that setting has an effect.

**Comment by DomiStyle** [comment] 2021-10-15 22:22
@kisak-valve Yes, that does sound similar.

I usually use X11 but it seems the update to 21.10 changed the session to Wayland by default.
The issue only appears in Wayland, with and without accelerated rendering. X11 works flawlessly like before.

I also noticed that the initial load time for the web views takes like 5-10 seconds on Wayland, Steam just hangs and stays black until then.

**Comment by kisak-valve** [comment] 2021-10-15 22:36
Thanks for checking, let's treat this as a duplicate of #7245.

Closing in favor of the older issue report.

**Closed by kisak-valve** 2021-10-15 22:36 UTC
Labels: Steam client, Distro Family: Ubuntu
