### ISSUE TITLE
Unable to run one of my games (Shadowrun Dragonfall) due to game overlay renderer issues (maybe).

### ISSUE THREAD

**Issue by leorodriguesrj** [ValveSoftware/steam-for-linux#7536] opened 2020-12-12 18:33 UTC
#### Your system information

* Steam client version (build number or date): 7 2020, at 18:04:33 (steam package version 1607372145)
* Distribution (e.g. Ubuntu): Debian 10 (buster)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Last week I was running "Shadowrun Dragonfall" just fine. Then a couple of days ago I tried to run it but the execution is aborted short after initialization. Looking into the game's directories I found a file named `output.txt` which contained the following error:

```
ERROR: ld.so: object '/home/myhomedir/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
```

I have another game installed that is running just fine tho.

#### Steps for reproducing this issue:

GIVEN
- You have "Shadowrun Dragonfall" installed

WHEN
- You run the game through any possible shortcut inside Steam

THEN
- The game execution begins and is suddenly aborted.

**Comment by kisak-valve** [comment] 2020-12-12 18:36
Hello @leorodriguesrj, this issue isn't related to the Steam overlay and is already fixed in the Steam client beta release. Please opt into Steam's beta client.

Closing as a duplicate of https://github.com/ValveSoftware/steam-runtime/issues/317.

**Closed by kisak-valve** 2020-12-12 18:36 UTC

**Comment by leorodriguesrj** [comment] 2020-12-12 18:40
Thanks! I'll try it right away!
