### ISSUE TITLE
Steam reports zero disk space

### ISSUE THREAD

**Issue by jmacarthur** [ValveSoftware/steam-for-linux#3945] opened 2015-08-01 12:10 UTC
As of yesterday, when I bought Sportsfriends, Steam will not install any games and says:

    Disk space Available: 0MB

...when I try to install any game, including ones I've previously installed. This problem wasn't occurring last week (25th July) when I bought The Stanley Parable.

    jimm@octode:~$ df -h
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/sda5       196G   82G  104G  45% /
    none            4.0K     0  4.0K   0% /sys/fs/cgroup
    udev            3.9G  4.0K  3.9G   1% /dev
    tmpfs           788M  1.5M  786M   1% /run

    jimm@octode:~$ ls -ld Steam* .steam
    drwxrwxr-x 22 jimm jimm 4096 Aug  1 12:54 .steam
    drwxrwxr-x  3 jimm jimm 4096 Aug  1 00:51 Steam
    drwxrwxr-x  3 jimm jimm 4096 Aug  1 01:10 SteamLibrary

Steam build says Jul 23 2015, at 11:59:29

I spotted this in the output when running steam.sh from the command line: 
    /home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/clientdll/applicationmanager.cpp (3117) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index

**Comment by devcsrj** [comment] 2015-08-01 13:44
+1. For some reason, Dota 2, the only game on my machine was no longer found in the steam library - i.e.: Steam prompts installation. The disk space shows 0MB too.

The build is the same.

![linux-steam-build-july-23](https://cloud.githubusercontent.com/assets/3963900/9022028/337ae688-3896-11e5-91ec-d782f28e43fd.png)

**Comment by gdrewb-valve** [comment] 2015-08-02 15:57
Likely duplicate of #3936, you need to get the kernel update.

**Closed by gdrewb-valve** 2015-08-02 15:57 UTC
Labels: duplicate, reviewed
