### ISSUE TITLE
Taskbar icon doesn't do it's job

### ISSUE THREAD

**Issue by idespisevalvecoders** [ValveSoftware/steam-for-linux#4857] opened 2017-02-10 22:24 UTC
system information: irrelevant
client version: any version since middle of january 2017
distribution: ubuntu
steam client beta: both versions are affected
have you checked for system updates?: lol

issue: taskbar icon in ANY window manager don't show any menu

steps for reproducing this issue:
1. launch steam client

**Comment by kisak-valve** [comment] 2017-02-10 22:44
Closing as a duplicate of #4795. Please see https://github.com/ValveSoftware/steam-for-linux/issues/4795#issuecomment-271268063 for the summary evaluation.

**Closed by kisak-valve** 2017-02-10 22:44 UTC
