### ISSUE TITLE
Some games' desktop shortcuts don't have icons associated with them.

### ISSUE THREAD

**Issue by Benguin** [ValveSoftware/steam-for-linux#4000] opened 2015-09-02 20:41 UTC
Some games use the generic steam icon instead of their own as seen here: http://i.imgur.com/mdqgzF3.png

This is annoying enough on the desktop, but it becomes more of a problem when you're having icons added to the application menu and it's hard to distinguish games from each other.

If some of the games' developers aren't contributing icons for this use, can't steam use the icon it uses for each game in the library view? (as seen here http://i.imgur.com/QIS4jmc.png ) It might look poor depending on how large those icon files are, but it would still help for the menu's where icons are small anyway.

**Comment by MightyCreak** [comment] 2015-09-08 12:21
I have the same problem. I did the `steam --reset` trick, but the problem is still here. I made a list, so maybe you can see a pattern?

Games that show the default icon (https://framapic.org/mkSzwKCwl1f4/V2tnEyrP):
* Dota 2
* Bastion
* Gratuitous Space Battle
* Planetary Annihilation
* Sid Meier's Civilization V
* Ticket to Ride

Games that show the binary icon (https://framapic.org/N3MOpDBmlGqN/WJ87p5ha):
* Block That Matter
* Don't Starve
* FTL
* Metro: Last Light
* Super Meat Boy
* Team Fortress 2
* Tetrobot And Co.
* Ticket to ride

Games that show the right icon:
* And Yet It Moves
* Cities: Skylines
* Sid Meier's Civilization: Beyond Earth
* Small World 2

**Comment by ArnaudAndre** [comment] 2015-10-21 21:50
Dupe of #989. As explained there, this is an issue with the games and should be reported as such to each individual game's developer.

**Comment by MightyCreak** [comment] 2015-10-21 22:08
Ok, I guess we can close this one then

**Comment by kisak-valve** [comment] 2018-06-05 01:39
@Plagman posted at https://github.com/ValveSoftware/steam-for-linux/issues/989#issuecomment-394548865: "Yes, the problem was that we didn't have .pngs to put in there because the developer never specified Linux icon files, only a Windows icon. The next Beta will include a systemic fix for this that will let the Linux client fall back to Windows icons and convert them appropriately; games will have to be reinstalled and the shortcuts recreated for the proper icon to get redownloaded, unfortunately."

**Comment by kisak-valve** [comment] 2018-12-14 16:59
Closing in favor of the current iteration of this issue at #5590.

**Closed by kisak-valve** 2018-12-14 16:59 UTC
Labels: reviewed
