### ISSUE TITLE
Unable to start - Out of memory on account with steam authenticator

### ISSUE THREAD

**Issue by OverlordAlex** [ValveSoftware/steam-for-linux#5069] opened 2017-07-08 09:16 UTC
#### Your system information

* /client/steam_client_ubuntu12 version 1496897923, installed version 1496897923
* Ubuntu 16.04 LTS
* Opted into Steam client beta?: No (see below)
* Have you checked for system updates?: Yes

[System info - from working account on beta client](https://gist.github.com/OverlordAlex/a2118903d33e8b1ec6b9b52ddc7d2e17)

#### Please describe your issue in as much detail as possible:
When attempting to log in, the dialog for entering the steam authenticator code is not shown. Steam appears to hang, before showing the "Connectivity Error" dialog, which also appears to hang (unable to interact) before steam crashes.

This is only for my account using steam authenticator - another account without the authenticator is able to log in as normal. I am able to log into my account on the website using authenticator.

The request for the authenticator token is being sent as the app shows the generated token notification. 

[Full console log of ./steam.sh](https://gist.github.com/OverlordAlex/1197a4b13da70f829aee52d07e1bb387)

The relevant part of the crash:
```
Generating new string page texture 11: 8x256, total string texture memory is 516.10 KB
Generating new string page texture 12: 16x256, total string texture memory is 532.48 KB
Generating new string page texture 13: 24x256, total string texture memory is 557.06 KB
Generating new string page texture 14: 32x256, total string texture memory is 589.82 KB
Installing breakpad exception handler for appid(steam)/version(1496897923)
BYieldingRegisterSteamController - Error querying accounts registered to controller after 1 try.
BYieldingRegisterSteamController - Error querying accounts registered to controller after 2 try.
Installing breakpad exception handler for appid(steam)/version(1496897923)
BYieldingRegisterSteamController - Error querying accounts registered to controller after 3 try.
Generating new string page texture 16: 384x256, total string texture memory is 983.04 KB
***** OUT OF MEMORY! attempted allocation size: 805306368 ****
memstd.cpp (2539) : Fatal Assertion Failed: OUT OF MEMORY
memstd.cpp (2539) : Fatal assert failed: memstd.cpp, line 2539.  Application exiting.

Assert( Fatal Assertion Failed: OUT OF MEMORY ):memstd.cpp:2539
```

From syslog:
```
Jul  8 10:32:45 alex gnome-session[12017]: ../common/pipes.cpp (571) : Assertion Failed: m_pInternalPipe->BRead failed
Jul  8 10:32:45 alex gnome-session[12017]: ../common/processpipe_posix.cpp (492) : Assertion Failed: CCrossProcessPipe::BWrite: 32 
(Broken pipe)
Jul  8 10:32:45 alex gnome-session[12017]: ../common/pipes.cpp (749) : CClientPipe::BWriteAndReadResult: BWrite failed
Jul  8 10:32:45 alex gnome-session[12017]: steamclient.cpp (714) : Assertion Failed: bufRet.TellPut() == sizeof(uint8)
```

Bonus:
```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63433
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63433
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

#### Steps for reproducing this issue:

1. Open steam / switch user from logged-in user
2. Enter username+password for an account using steam authenticator
3. Steam now hangs instead of showing the authenticator dialog to enter the code

#### Steps attempted to fix the problem:

1. `./steam.sh -reset`
2. `./steam.sh -bigpicture`
3. switch user rather than fresh login
4. download latest deb installer, update system packages
5. `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 ./steam.sh` (also tried =1)
6. `strace` fails - didn't feel like digging into the reason
7. Removing authenticator from my account - no change, still crashes. Added it back.
8. beta client - see below

#### Enabling the beta client:

I got further with the beta client - I was able to click "start in offline mode" when the Connection Error appeared. This loaded my games. I was then presented with a little dialog box saying "your steam details have changed - please reauthenticate". After entering my password, it then extended the dialog and asked for my steam authenticator token. Entering the token froze steam, although I could see from my "friends" list that I had changed from offline -> online. Steam then crashed.

Opening steam now doesn't present me with an account log-in page, but attempts to log in as the user with the problem, which just crashes steam before anything happens. The error is the same OOM as above. So now it appears I'm totally stuck, unable to use steam at all on this computer.

EDIT: that last statement isnt quite true: I can still access steam via the bigpicture mode - the account with the authenticator is still crashing through

**Comment by rndmh3ro** [comment] 2017-07-08 10:12
I'm having the same problem on Arch 64bit.

```
basti$ steam
Running Steam on arch rolling 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)

(steam:9922): Gtk-WARNING **: Im Modulpfad »adwaita« konnte keine Themen-Engine gefunden werden,

(steam:9922): Gtk-WARNING **: Im Modulpfad »adwaita« konnte keine Themen-Engine gefunden werden,

(steam:9922): Gtk-WARNING **: Im Modulpfad »murrine« konnte keine Themen-Engine gefunden werden,

(steam:9922): Gtk-WARNING **: Im Modulpfad »murrine« konnte keine Themen-Engine gefunden werden,

(steam:9922): Gtk-WARNING **: Im Modulpfad »murrine« konnte keine Themen-Engine gefunden werden,

(steam:9922): Gtk-WARNING **: Im Modulpfad »murrine« konnte keine Themen-Engine gefunden werden,

(steam:9922): Gtk-WARNING **: Im Modulpfad »murrine« konnte keine Themen-Engine gefunden werden,

(steam:9922): Gtk-WARNING **: Im Modulpfad »murrine« konnte keine Themen-Engine gefunden werden,

(steam:9922): Gtk-WARNING **: Im Modulpfad »murrine« konnte keine Themen-Engine gefunden werden,

(steam:9922): Gtk-WARNING **: Im Modulpfad »murrine« konnte keine Themen-Engine gefunden werden,

(steam:9922): Gtk-WARNING **: Im Modulpfad »murrine« konnte keine Themen-Engine gefunden werden,

(steam:9922): Gtk-WARNING **: Im Modulpfad »murrine« konnte keine Themen-Engine gefunden werden,

(steam:9922): Gtk-WARNING **: Im Modulpfad »murrine« konnte keine Themen-Engine gefunden werden,
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Setting breakpad minidump AppID = 769
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded no]
Steam Controller reserving XInput slot 0
Generating new string page texture 12: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 13: 256x256, total string texture memory is 311,30 KB
Generating new string page texture 14: 128x256, total string texture memory is 442,37 KB
Controller 0 connected, configuring it now...
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
!! Controller 0 attributes:
  ProductID: 654
  Serial: Awaiting_Logon
  Capabilities: 00000003
  Firmware Version: 0
  Firmware Build Time: 2147483647 (Di, 19 Jan 2038 03:14:07 GMT)
  Bootloader Build Time: 2147483647 (Di, 19 Jan 2038 03:14:07 GMT)
Setting VR Path Registry runtime path to /home/basti/.local/share/Steam/SteamApps/common/OpenVR
vr/vrmanager.cpp (190) : Assertion Failed: BFileExists( /home/basti/.local/share/Steam/SteamApps/common/OpenVR/bin/linux64/vrpathreg ) failed
Assert( Assertion Failed: BFileExists( /home/basti/.local/share/Steam/SteamApps/common/OpenVR/bin/linux64/vrpathreg ) failed ):vr/vrmanager.cpp:190

Installing breakpad exception handler for appid(steam)/version(1496897923)
crash_20170708112232_18.dmp[10053]: Uploading dump (out-of-process)
/tmp/dumps/crash_20170708112232_18.dmp
Setting VR Path Registry config path to /home/basti/.local/share/Steam/config
vr/vrmanager.cpp (190) : Assertion Failed: BFileExists( /home/basti/.local/share/Steam/SteamApps/common/OpenVR/bin/linux64/vrpathreg ) failed
Setting VR Path Registry log path to /home/basti/.local/share/Steam/logs
vr/vrmanager.cpp (190) : Assertion Failed: BFileExists( /home/basti/.local/share/Steam/SteamApps/common/OpenVR/bin/linux64/vrpathreg ) failed
Loaded Config for Local Override Path for App ID 413080: /home/basti/.local/share/Steam//controller_base/empty.vdf
Controller 0 mapping uses xinput : false
Generating new string page texture 20: 64x256, total string texture memory is 507,90 KB
Generating new string page texture 21: 8x256, total string texture memory is 516,10 KB
Generating new string page texture 22: 16x256, total string texture memory is 532,48 KB
Generating new string page texture 23: 24x256, total string texture memory is 557,06 KB
Generating new string page texture 24: 32x256, total string texture memory is 589,82 KB
crash_20170708112232_18.dmp[10053]: Finished uploading minidump (out-of-process): success = yes
crash_20170708112232_18.dmp[10053]: response: CrashID=bp-de0ad050-1bf2-4207-8c32-9094a2170708
crash_20170708112232_18.dmp[10053]: file ''/tmp/dumps/crash_20170708112232_18.dmp'', upload yes: ''CrashID=bp-de0ad050-1bf2-4207-8c32-9094a2170708''
Installing breakpad exception handler for appid(steam)/version(1496897923)
BYieldingRegisterSteamController - Error querying accounts registered to controller after 1 try.
BYieldingRegisterSteamController - Error querying accounts registered to controller after 2 try.
Installing breakpad exception handler for appid(steam)/version(1496897923)
BYieldingRegisterSteamController - Error querying accounts registered to controller after 3 try.
Generating new string page texture 29: 384x256, total string texture memory is 983,04 KB
memstd.cpp (2539) : Fatal Assertion Failed: OUT OF MEMORY
memstd.cpp (2539) : Fatal assert failed: memstd.cpp, line 2539.  Application exiting.

Assert( Fatal Assertion Failed: OUT OF MEMORY ):memstd.cpp:2539

Installing breakpad exception handler for appid(steam)/version(1496897923)
assert_20170708112319_22.dmp[10573]: Uploading dump (out-of-process)
/tmp/dumps/assert_20170708112319_22.dmp
_ExitOnFatalAssert
assert_20170708112319_22.dmp[10573]: Finished uploading minidump (out-of-process): success = yes
assert_20170708112319_22.dmp[10573]: response: CrashID=bp-0f878859-efde-433d-870d-780ca2170708
assert_20170708112319_22.dmp[10573]: file ''/tmp/dumps/assert_20170708112319_22.dmp'', upload yes: ''CrashID=bp-0f878859-efde-433d-870d-780ca2170708''
Assert( Assertion Failed: m_pInternalPipe->BRead failed ):../common/pipes.cpp:571

crash_20170708112336_2.dmp[10658]: Uploading dump (out-of-process)
/tmp/dumps/crash_20170708112336_2.dmp
crash_20170708112336_2.dmp[10658]: Finished uploading minidump (out-of-process): success = yes
crash_20170708112336_2.dmp[10658]: response: Discarded=1
crash_20170708112336_2.dmp[10658]: file ''/tmp/dumps/crash_20170708112336_2.dmp'', upload yes: ''Discarded=1''
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
../common/pipes.cpp (571) : Assertion Failed: m_pInternalPipe->BRead failed
../common/processpipe_posix.cpp (492) : Assertion Failed: CCrossProcessPipe::BWrite: 32 (Datenübergabe unterbrochen (broken pipe))
../common/pipes.cpp (749) : CClientPipe::BWriteAndReadResult: BWrite failed
steamclient.cpp (714) : Assertion Failed: bufRet.TellPut() == sizeof(uint8)
../common/processpipe_posix.cpp (492) : Assertion Failed: CCrossProcessPipe::BWrite: 32 (Datenübergabe unterbrochen (broken pipe))
```
Deleting `~/.local/share/Steam` and reinstalling steam solved the issue.

**Comment by OverlordAlex** [comment] 2017-07-08 10:22
Interestingly deleting `~/.local/share/Steam` and reinstalling now gets me to the authenticator dialog, except it crashes immediately afterwards with the same OOM error

**Comment by rndmh3ro** [comment] 2017-07-08 10:29
I'm not using the Authenticator so maybe that makes a difference.

**Comment by OverlordAlex** [comment] 2017-07-08 14:22
> I'm not using the Authenticator so maybe that makes a difference.

Using another account with the same steam installation but no authenticator is fine. Its something about the authenticator code that is causing the crash.

I'm not sure why removing the authenticator from my account isn't working, I'm guessing it's crashing before it can receive the update disabling it

**Comment by hpsu** [comment] 2017-07-09 07:41
I had this exact problem shortly after activating the mobile authenticator, although I don't know if that is related. 

That time I "fixed" it by renaming ```~/.local/share/Steam``` to force steam to create a fresh one.

Now, a couple of weeks later I had the problem again and started looking at recently changed files.

I came across ```userdata/[UID]/config/localconfig.vdf``` which was a suspiciously large text file at 573MiB!
After renaming it, steam started working again. (The newly synced file is now 1MiB.)

A quick look at the broken file shows that each sections repeat itself thousands of times. I saved the previous installation and can confirm that that localconfig.vdf was 987MiB.

**Comment by jsaalfeld** [comment] 2017-07-09 08:11
@hpsu - Dind't work for me, unfortunately. Running on Arch 64Bit, too. Got a compete freeze of the system after I enter my authenticator code. Need to reboot every time.

**Comment by threexone** [comment] 2017-07-10 08:55
Hello,
I had the same problem (though with authenticator) : issue #5041 . I fixed it by deleting the "userdata" folder.
The issue came back this morning and I renamed the "userdata/[UID]/config/localconfig.vdf" as @hpsu suggested and Steam is now working again.

**Comment by leeps** [comment] 2017-07-10 18:13
It seems like I was also affected by this error.

Removing localconfig.vdf worked in my case. The file was ~700MB before and is ~600KB now.

**Comment by Voker57** [comment] 2017-07-12 21:14
Worked for me too.

**Comment by kisak-valve** [comment] 2017-07-14 00:59
Per "Fixed a bug which created excessively large configuration files that could slow down Steam or cause it to appear to hang for several seconds at a time" in the [2017-07-12](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/2318642437901977127) steam beta client update, can anyone reproduce this issue while opted into the steam beta client (and after removing localconfig.vdf if it was oversized before the update)?

**Comment by leeps** [comment] 2017-07-14 05:47
@kisak-valve Opting into beta now.
My localconfig.vdf has gained around 200KB since I reset it 4 days ago, so we should probably see results by monday. I'll let you know.

**Comment by jsaalfeld** [comment] 2017-07-14 09:35
@kisak-valve 
After I noticed there was an update, i exited the client and redirected the output into a [file](http://www.pastefile.com/61vgi2).

Everything seems to work now!

**Comment by leeps** [comment] 2017-07-18 17:13
@kisak-valve It seems like it worked. localconfig.vdf now stays at 600KB.
Thanks for your quick fix!

**Comment by hpsu** [comment] 2017-07-21 09:06
@kisak-valve Seems fixed here, my localconfig.vdf has no duplicate entries for about a week now

**Comment by jsaalfeld** [comment] 2017-07-21 09:40
I just removed Steam from my System and deleted the steam folder in ~./local/share and in ~/. I reinstalled it and tried to start it, but still, my system freezes without any error message.

**Comment by kisak-valve** [comment] 2017-07-21 13:14
Thanks for retesting, closing per the feedback.

@jsaalfeld, the symptoms you've described does not match this issue report. No opengl application should be capable of freezing the entire system, which hints that you may be experiencing a video driver issue.

**Closed by kisak-valve** 2017-07-21 13:14 UTC
Labels: Steam client

**Comment by Ketchup901** [comment] 2017-07-27 18:21
Deleting localconfig.vdf only works once, and only after restarting my computer. Once the client generates a new one, it crashes again.

```
/home/adam/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
/home/adam/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
Running Steam on arch  64-bit
/home/adam/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1501097683)
Installing breakpad exception handler for appid(steam)/version(1501097683)
Installing breakpad exception handler for appid(steam)/version(1501097683)

(steam:2788): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(steam:2788): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/monokai-gtk/gtk-2.0/main.rc:1090: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Breeze-Dark/gtk-2.0/widgets/entry:70: error: unexpected identifier 'direction', expected character '}'

(steam:2788): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Breeze-Dark/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", expected valid string constant
Installing breakpad exception handler for appid(steam)/version(1501097683)
Installing breakpad exception handler for appid(steam)/version(1501097683)
Installing breakpad exception handler for appid(steam)/version(1501097683)
Installing breakpad exception handler for appid(steam)/version(1501097683)
Installing breakpad exception handler for appid(steam)/version(1501097683)
Installing breakpad exception handler for appid(steam)/version(1501097683)
Installing breakpad exception handler for appid(steam)/version(1501097683)
Installing breakpad exception handler for appid(steam)/version(1501097683)
Installing breakpad exception handler for appid(steam)/version(1501097683)
Installing breakpad exception handler for appid(steam)/version(1501097683)
Installing breakpad exception handler for appid(steam)/version(1501097683)
Installing breakpad exception handler for appid(steam)/version(1501097683)
Installing breakpad exception handler for appid(steam)/version(1501097683)

** (steam:2788): WARNING **: Unknown device type 14

** (steam:2788): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/1: unknown object type
Setting breakpad minidump AppID = 769
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198065560768 [API loaded no]

** (steam:2788): WARNING **: Ignoring invalid property 'autoconnect-priority'

** (steam:2788): WARNING **: Unknown setting 'proxy'

** (steam:2788): WARNING **: Ignoring invalid property 'route-data'

** (steam:2788): WARNING **: Ignoring invalid property 'address-data'

** (steam:2788): WARNING **: Ignoring invalid property 'route-data'

** (steam:2788): WARNING **: Ignoring invalid property 'address-data'
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB
Installing breakpad exception handler for appid(steam)/version(1501097683)
Installing breakpad exception handler for appid(steam)/version(1501097683)
Installing breakpad exception handler for appid(steam)/version(1501097683)
Installing breakpad exception handler for appid(steam)/version(1501097683)
Installing breakpad exception handler for appid(steam)/version(1501097683)
roaming config store loaded successfully - 2784 bytes.
migrating temporary roaming config store
Failed to init SteamVR because it isn't installed
process 2788: arguments to dbus_connection_ref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file dbus-connection.c line 2686.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace
[2017-07-27 20:20:23] Startup - updater built Jul 26 2017 18:19:34
[2017-07-27 20:20:23] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2017-07-27 20:20:23] Checking for update on startup
[2017-07-27 20:20:23] Checking for available updates...
[2017-07-27 20:20:23] Download skipped by HTTP 304 Not Modified
[2017-07-27 20:20:23] Nothing to do
[2017-07-27 20:20:23] Verifying installation...
[2017-07-27 20:20:23] Performing checksum verification of executable files
[2017-07-27 20:20:24] Verification complete
assert_20170727202023_1.dmp[2872]: Uploading dump (out-of-process)
/tmp/dumps/assert_20170727202023_1.dmp
/home/adam/.local/share/Steam/steam.sh: line 940:  2788 Aborted                 (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20170727202023_1.dmp[2872]: Finished uploading minidump (out-of-process): success = yes
assert_20170727202023_1.dmp[2872]: response: CrashID=bp-608fc624-2dea-4cd8-8cf2-535622170727
assert_20170727202023_1.dmp[2872]: file ''/tmp/dumps/assert_20170727202023_1.dmp'', upload yes: ''CrashID=bp-608fc624-2dea-4cd8-8cf2-535622170727''
Assert( Assertion Failed: m_pInternalPipe->BRead failed ):../common/pipes.cpp:572

crash_20170727202045_2.dmp[2891]: Uploading dump (out-of-process)
/tmp/dumps/crash_20170727202045_2.dmp
crash_20170727202045_2.dmp[2891]: Finished uploading minidump (out-of-process): success = yes
crash_20170727202045_2.dmp[2891]: response: CrashID=bp-a0286771-2a71-4638-a312-09ce62170727
crash_20170727202045_2.dmp[2891]: file ''/tmp/dumps/crash_20170727202045_2.dmp'', upload yes: ''CrashID=bp-a0286771-2a71-4638-a312-09ce62170727''
../common/pipes.cpp (572) : Assertion Failed: m_pInternalPipe->BRead failed
```
