### ISSUE TITLE
Steam won't start since latest update

### ISSUE THREAD

**Issue by paolorotolo** [ValveSoftware/steam-for-linux#4568] opened 2016-07-25 19:52 UTC
#### Your system information
- Steam client version: latest (updated today, I can't open it to check which version)
- Distribution (e.g. Ubuntu): Ubuntu 16.10
- Opted into Steam client beta?: Tried both with beta and not
- Have you checked for system updates?: Yes
- **Graphic Card:** AMD 7790 HD (Gallium 0.4 on AMD BONAIRE (DRM 2.43.0 / 4.4.0-31-generic, LLVM 3.8.1)
#### Please describe your issue in as much detail as possible:

Steam simply doesn't start. When I run it on a terminal I get:

```
paolo@home:~$ steam
Running Steam on ubuntu 16.10 64-bit
STEAM_RUNTIME is enabled automatically
[2016-07-25 21:51:00] Startup - updater built Jul  8 2016 21:43:51
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
```
#### Steps for reproducing this issue:
1. Open Steam; :)

I've already tried all the fixes and workarounds In the other reports. This seems a new issue, it happens since I did system updates this morning.

**Comment by cwxda** [comment] 2016-07-27 10:03
#### Your system information

* Steam client version: appid(steam)/version(1468023329)
* Distribution (e.g. Ubuntu): Arch rolling amd64
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: AMD HD7950 with latest catalyst(also tested with radeon driver)

#### Please describe your issue in as much detail as possible:
Steam doesn't start since the lastest update

`
ville@Kast ~ % STEAM_RUNTIME=0 steam
Running Steam on arch rolling 64-bit
STEAM_RUNTIME is disabled by the user
[0727/115801:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
[0727/115801:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
assert_20160727115801_1.dmp[2742]: Uploading dump (out-of-process)
/tmp/dumps/assert_20160727115801_1.dmp
/home/ville/.local/share/Steam/steam.sh: line 713:  2686 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20160727115801_1.dmp[2742]: Finished uploading minidump (out-of-process): success = yes
assert_20160727115801_1.dmp[2742]: response: CrashID=bp-6467055f-31d4-4444-b5b7-1be8c2160727
assert_20160727115801_1.dmp[2742]: file ''/tmp/dumps/assert_20160727115801_1.dmp'', upload yes: ''CrashID=bp-6467055f-31d4-4444-b5b7-1be8c2160727''
`

#### Steps for reproducing this issue:

1. Open steam
[assert_20160727115801_1.zip](https://github.com/ValveSoftware/steam-for-linux/files/385791/assert_20160727115801_1.zip)

**Comment by PaoloRotolo** [comment] 2016-07-27 11:53
I can confirm the latest steam client still works on Fedora 24. The problem occurs only on Ubuntu.

![screenshot from 2016-07-27 13-32-46](https://cloud.githubusercontent.com/assets/5623301/17174387/6cd0e108-5401-11e6-9062-f6c2fb6f5c22.png)

**Comment by Entropy0** [comment] 2016-07-27 16:32
**Your system information**

 - Steam client version: appid(steam)/version(1468520696)
 - Distribution (e.g. Ubuntu): Linux Mint 17 Qiana
 - Opted into Steam client beta?: No
 - Have you checked for system updates?: Yes
 - GPU: AMD HD7850 with latest catalyst

**Please describe your issue in as much detail as possible:**

Steam segfaults after trying to login. (Issue also exists with remember password feature checked)
Console log, beginning after pressing login:
```
Installing breakpad exception handler for appid(steam)/version(1468520696)
Installing breakpad exception handler for appid(steam)/version(1468520696)
Installing breakpad exception handler for appid(steam)/version(1468520696)
Installing breakpad exception handler for appid(steam)/version(1468520696)
Installing breakpad exception handler for appid(steam)/version(1468520696)
roaming config store loaded successfully - 2119 bytes.
migrating temporary roaming config store
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Failed to init SteamVR because it isn't installed
ExecCommandLine: ""/media/stuff/Steam/ubuntu12_32/steam" "
Installing breakpad exception handler for appid(steam)/version(1468520696)
System startup time: 15,52 seconds
crash_20160727181929_1.dmp[10733]: Uploading dump (out-of-process)
/tmp/dumps/crash_20160727181929_1.dmp
/home/x2/.steam/steam.sh: line 713: 10677 Segmentation fault  $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20160727181929_1.dmp[10733]: Finished uploading minidump (out-of-process): success = yes
crash_20160727181929_1.dmp[10733]: response: CrashID=bp-6baf0fad-1821-4752-824a-ddffe2160727
crash_20160727181929_1.dmp[10733]: file ''/tmp/dumps/crash_20160727181929_1.dmp'', upload yes: ''CrashID=bp-6baf0fad-1821-4752-824a-ddffe2160727''
```
(The warnings about fonts and exception handlers seem to be unrelated, as I've always got those without any apparent issues)
At this point, the login window comes back up/ the autologin is attempted again.

**Steps for reproducing this issue:**
1. `$ steam`


I've also tried reinstalling steam, `steam --reset`, `STEAM_RUNTIME=0 steam` as suggested in some older threads, all to no avail.

**Comment by watbe** [comment] 2016-07-27 17:33
@Entropy0 I had the same issue as you and solved it by removing a no-longer-existent beta `.acf` file: see #4561 

In my case, `appmanifest_105600.acf` (Terraria) was the culprit for me. You might have one or more of the games affected as well.

**Comment by PaoloRotolo** [comment] 2016-07-27 20:20
I think the original one is another issue.
```X Error of failed request:  BadValue (integer parameter out of range for operation)```

I've already tried removing .acf files anyway.

**Comment by Entropy0** [comment] 2016-07-27 20:31
Yup, removing the .acf files did the trick.
@cwxda you should probably try that, too, since your error looks more like the one I got than OP's.

**Comment by Oxalin** [comment] 2016-07-27 21:32
@PaoloRotolo, by any chance, was the Steam runtime reinstalled during your tests? Was there a system update or upgrade before the error's appearance (you are using a development release of Ubuntu, which could be the culprit)? I may have missed it, but are you using Steam runtime or not? Are you sure the 32bit libraries are also up to date?

My feeling is that Steam is using some libraries that are in conflict with your system's ones. Using mesa drivers tends to show this behaviour (since you ruled out the bug about remaining .acf files) when there is a mix between libstd++, libgcc_s, libxcb and libgpg-error.  Have you tried some of the tricks here (dynamic linker or deleting the files): https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Steam_runtime_issues ? Have also a look here: https://wiki.archlinux.org/index.php/Steam#Using_native_runtime

**Comment by jpleau** [comment] 2016-07-28 18:46
Duplicate of #3820 ?

**Comment by nazar-pc** [comment] 2016-07-29 03:48
Same thing here, following errors appear:
```
/usr/bin/pgrep: /home/nazar-pc/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libgpg-error.so.0: no version information available (required by /lib/x86_64-linux-gnu/libgcrypt.so.20)
/usr/bin/pgrep: relocation error: /lib/x86_64-linux-gnu/libgcrypt.so.20: symbol gpgrt_lock_lock, version GPG_ERROR_1.0 not defined in file libgpg-error.so.0 with link time reference
/usr/bin/pkill: /home/nazar-pc/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libgpg-error.so.0: no version information available (required by /lib/x86_64-linux-gnu/libgcrypt.so.20)
/usr/bin/pkill: relocation error: /lib/x86_64-linux-gnu/libgcrypt.so.20: symbol gpgrt_lock_lock, version GPG_ERROR_1.0 not defined in file libgpg-error.so.0 with link time reference
...
bash: /home/nazar-pc/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by bash)
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
dpkg: symbol lookup error: dpkg: undefined symbol: setexecfilecon
...
/bin/bash: /home/nazar-pc/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
awk: /home/nazar-pc/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.6)
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
/usr/bin/ldd: рядок 119: printf: помилка запису: Канал обірвано
```

**Comment by Oxalin** [comment] 2016-07-29 14:32
@nazar-pc, From what you are showing us, you have at least a problem with libgcrypt/gpg and probably another one with ncurse (from the libtinfo error) (which is obviously not the same as having an X error by the way). As a general note, when reporting a bug, add details about your system (linux distribution, video card, drivers), any updates you did prior to the appearance of the bug, if you are using the Steam runtime or not, since when the bug appeared, etc.

Please, see my previous comment addressed to @PaoloRotolo. You'll have two links where you'll have some clues on what to do: look for missing dependencies first, that will give us a clue about both errors. About libgcrypt/gpg, You'll probably have to rename, move or remove a library from Steam's runtime folder or force the linker to use your system's one (see under "Work around using the dynamic linker").

Now, about your libtinfo error, have you by any chance updated your system recently? Libtinfo is linked to ncurse. Could you do a "ls -lh" on the path to libtinfo.so.5 (which is a symlink to another file) and then do the same on the real file?

You could also try to run Steam with your system's native runtime libraries if you are not already and see what you get from there (have a look in the links for "Using native runtime" first or if you have problem).

Also, @PaoloRotolo,s bug had nothing similar to your log in his original post. Next time, try to find a bug where the description matches. It is better to open a new bug if unsure and to be able to link it as a duplicate to another one than to add noise to a bug.

**Comment by nazar-pc** [comment] 2016-07-29 14:54
@Oxalin, sorry that I didn't provide info in this thread.

* Steam client version: 1468023329
* Distribution (e.g. Ubuntu): Ubuntu 16.10
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* iGPU HD4600, dGPU 780M
* git version of mesa and friends
* Nvidia blob 364.x (all including beta) and 367.x (all including beta)

I've went back to stable Steam, since beta stopped working in single day when I didn't have any major updates besides Steam itself (previous beta version worked fine), so this is Steam's regression.

```
nazar-pc@nazar-pc ~> ls -lh /lib/x86_64-linux-gnu/libtinfo.so.5
lrwxrwxrwx 1 root root 15 лип  7 02:11 /lib/x86_64-linux-gnu/libtinfo.so.5 -> libtinfo.so.5.9
```

Sorry for posting to irrelevant thread, I've just quickly found an issue that matches on the surface problem and distro and decided to comment right here. I'll try to use information from links you've posted and will open new issue, thanks.

**Comment by Harry-R** [comment] 2016-10-27 17:48
This seems not to be an Ubuntu problem, i can confirm it for an up to date Fedora 24 KDE with  steam-1.0.0.52-2 installed via dnf on an Acer Aspire E5-574-59H5. It occurs on the first start after installation. Command line output see: https://gist.github.com/Harry-R/a1b6a400c7880a3259b9a5ae4046dd47

**Comment by LexBarringer** [comment] 2016-11-22 14:25
@paolorotolo 

"SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)"

This is an error you're getting on Ubuntu using open source drivers and that the X-server version files clash with the files that are downloaded and installed in Steam's directories. In order to remedy the situation, you'll delete two symlinked files, then the system with use it's up to date files instead. 

In terminal / console: (cut and paste each line separately, then hit ENTER after each line) 

rm ~/.steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6

rm ~/.steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6

Once you done, type in 'steam' at the prompt and hit ENTER. If it starts to download a new update or starts Steam. Wait for 10 seconds after it's done downloading and installing (if it's doing that) or if it just loads Steam, close Steam normally. Then start it via the icon or the menu system you have it installed as.

**Comment by LexBarringer** [comment] 2016-11-22 14:35
@Harry-R 

Essentially what's happening is that X-org server version 1.18.x is drastically different in it's calls than the previous version of 1.17.4. The files that are symlinked in Steam were designed for the old X-org server. The files you use in your system directory are updated and designed for the new version of the X-org server.

I can't say for certain where you've installed Steam and where it defaults on Fedora 24 because I don't have that distribution as of yet. The problem is still the same, you need to locate the libstdc++.so.6 symlinks in the Steam installation and remove them. After that run Steam from the terminal to make sure everything else is working correctly.

**Comment by kisak-valve** [comment] 2019-07-05 20:02
Hello, since this issue report the way Steam handles the Steam runtime has changed to prefer host libraries before the runtime variants.

Is anyone still experiencing this issue on an up to date system?

**Comment by BrosephJ** [comment] 2019-07-06 00:25
@kisak-valve Yes, using 'native runtime' through LSI only. I get this error:

Failed to load steamui.so - dlerror(): /home/joey/.local/share/Steam/ubuntu12_32/steamui.so: undefined symbol: SDL_RWclose

**Comment by kisak-valve** [comment] 2019-07-06 00:38
Hello @BrosephJ, I don't think your issue is related to the issue that was tracked here. Are you using Solus's Linux Steam Integration?

Running Steam with the Steam runtime disabled is unsupported and any dependency issues should be mentioned to the package maintainer(s) that provide that as an option. SDL_RWclose is from around 2015 and is provided by the Steam runtime.

Related forum thread https://steamcommunity.com/app/221410/discussions/0/1640915206461789705/.

**Comment by kisak-valve** [comment] 2019-08-16 14:53
The followup Solus LSI issue should have been resolved in their project (https://github.com/ValveSoftware/steam-for-linux/issues/6407#issuecomment-513528711) and was discussed at #6396.

Closing.

**Closed by kisak-valve** 2019-08-16 14:53 UTC
Labels: Need Retest, reviewed
