### ISSUE TITLE
[overlay][dota2] in-game voice settings is stuck on pulseaudio on alsa only systems

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#6981] opened 2020-03-25 01:17 UTC
cannot select anything else than pulseaudio. the autodetection does not work.

**Comment by kisak-valve** [comment] 2020-03-25 01:27
Duplicate of https://github.com/ValveSoftware/Dota-2/issues/1724.

**Closed by kisak-valve** 2020-03-25 01:27 UTC
