### ISSUE TITLE
Titlebar buttons are inconsistent with Ubuntu Desktop Environment

### ISSUE THREAD

**Issue by gappleto97** [ValveSoftware/steam-for-linux#3868] opened 2015-06-02 06:44 UTC
When maximized the system titlebar does not take over, and when not, the buttons are on the right, rather than the left.

You really should let the Desktop environment handle these things, or at least go the chrome route and allow layout commands.

**Comment by beansmyname** [comment] 2015-06-02 15:03
Possible duplicate of #1040

**Comment by gdrewb-valve** [comment] 2015-06-15 19:52
Closing duplicate.

**Closed by gdrewb-valve** 2015-06-15 19:52 UTC
Labels: duplicate, reviewed
