### ISSUE TITLE
TF2 KP_ENTER key mapping broken *** ISSUE NOT FIXED - STILL***

### ISSUE THREAD

**Issue by blarf** [ValveSoftware/steam-for-linux#3157] opened 2014-02-16 13:22 UTC
**\* ISSUE NOT FIXED - STILL**\* 
Will someone do this 5 minute bugfix after 2 freakin' years eventually, making TF2 on Linux next to unusable for quite a lot of people!!! 
Does it need a letter to Gabe Newell to get things done? 

We want a working Linux client and now!
Closing unfixed issues or moving bug tickets around does not accomplish anything!
#461 is one heck of a bad example about how NOT to do bug management, so don't make a duplicate of this bug to some dead tickets, but solve this one-liner instead!

You are capable of fixing a simple key mapping issue, aren't you?!

I don't think anyone involved so far has determined the impact on old-school gamers here and I'm not gonna switch to Steam OS to get around this - never ever!

**Comment by kisak-valve** [comment] 2017-11-09 18:16
Closing as a duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/58.

**Closed by kisak-valve** 2017-11-09 18:16 UTC
Labels: reviewed
