### ISSUE TITLE
Portal 2 co-op does not work

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#4886] opened 2017-03-04 20:36 UTC
System info: http://pastebin.com/Nv66CWiq

It tries to connect, shows the other persons name and then both are booted back to the menu.

**Comment by kisak-valve** [comment] 2017-03-05 17:32
Hello @LiamDawe, as far as I can tell this is a duplicate of https://github.com/ValveSoftware/portal2/issues/32. Closing in favor of that issue report.

**Closed by kisak-valve** 2017-03-05 17:32 UTC
