### ISSUE TITLE
[Feature Request] Add a user reporting system for Proton games

### ISSUE THREAD

**Issue by jambonmcyeah** [ValveSoftware/steam-for-linux#5663] opened 2018-08-24 12:50 UTC
#### Your system information

* Steam client version (build number or date): 1535062307
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
It would be good to add a way for users to report how well the game works in Proton and some workarounds that need to be applied. Have the results displayed on each game so other members of the community could see which games work and which do not. The community has already started an effort of collecting user reports of games. (https://docs.google.com/spreadsheets/d/1DcZZQ4HL_Ol969UbXJmFG8TzOHNnHoj8Q1f8DIFe8-8/edit) However it would be better if steam just had a reporting feature.

**Comment by d4rkf4b** [comment] 2018-08-24 19:35
It's look like [#5662](https://github.com/ValveSoftware/steam-for-linux/issues/5662)  ;)

**Comment by kisak-valve** [comment] 2018-08-24 19:57
Closing as a duplicate of #5662.

**Closed by kisak-valve** 2018-08-24 19:57 UTC
Labels: Feature Request, Proton
