### ISSUE TITLE
Arch Linux support for dependencies of games [Request/Feature]

### ISSUE THREAD

**Issue by RevoluPowered** [ValveSoftware/steam-for-linux#6331] opened 2019-06-21 13:01 UTC
#### Your system information

* Steam client version (build number or date):   latest
* Distribution (e.g. Ubuntu): Manjaro (Arch) Deepin
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When I downloaded the game 'ZeroK' steam did not install the required dependency 'mono/.NET' for the game, even though .NET is in the requirements.

At the moment I bet it runs 'apt install mono' after adding the PPA's.

Could you possibly add a check in for if 'mono is not detected./NET' and it's linux and arch distro run 

> 'sudo pacman -S mono'

 instead of the apt equivalent.

#### Steps for reproducing this issue:

1. Install steam on arch linux manjaro - pick whatever desktop environment you want.
2. After installing steam install this package from AUR 'steam-native-pcre-fix'
3. Run steam, install zerok (free game)
4. Try joining a game in MP.
5. Map fails to download due to missing 'mono runtime dll' when you don't have the map and you cannot play game without running 'sudo pacman -S mono'.

I realize you don't officially support arch, but this would help out quite a bit and after using it for a few weeks it seems fairly stable apart from this one issue with the dependencies.

**Comment by XakepSDK** [comment] 2019-06-21 13:14
1.  steam-native is not supported officially.
2. `Steam client version (build number or date): latest` - seriously? Build number or date, nothing else. Help -> About Steam
3. ZeroK is windows game. Go to Proton repository, this repository is for steam for linux only.
https://github.com/ValveSoftware/Proton

**Comment by kisak-valve** [comment] 2019-06-21 13:17
Hello @RevoluPowered, there's a critical detail missing here because you're asking for a Windows dependency to be handled on Linux and this game does not have a native linux version available.

You're most likely using Proton to run the game and we're tracking issues with games run that in the Proton issue tracker. This game is being tracked at https://github.com/ValveSoftware/Proton/issues/2695.

Closing as invalid.

**Closed by kisak-valve** 2019-06-21 13:17 UTC

**Comment by RevoluPowered** [comment] 2019-06-21 13:19
Are you sure of that? the steam library doesn't actually show 'proton' like it does for every other game.

**Comment by RevoluPowered** [comment] 2019-06-21 13:25
Right, so it actually does have a linux executable. 

https://steamdb.info/app/334920/config/

It's running .NET and not using photon.

**Comment by kisak-valve** [comment] 2019-06-21 13:42
There's clearly an bug with the game going on here. Following your steps to reproduce, the game is rejected as an invalid platform on my Linux test boxes and you've framed this issue report as a feature request for the steam client. This issue should be addressed by the game's dev(s) first.

**Comment by RevoluPowered** [comment] 2019-06-21 14:05
Hmm interesting, let me take a look when I get home and I'll chat to them about it.

I appreciate the feedback, as it did help me get closer to getting it resolved. Thank you.

**Comment by GoogleFrog** [comment] 2019-06-21 14:32
@RevoluPowered I expect that you are testing with a linux beta key. Zero-K had not managed to pass a linux build due to issues with SteamOS big picture mode.

**Comment by RevoluPowered** [comment] 2019-06-21 15:22
I may be, since I was given a key pre-release and may still be on it.
