### ISSUE TITLE
Using the SHIFT key in the launch options field causes multi-selection in the game list after closing the dialogs

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4187] opened 2015-12-17 00:24 UTC
Steps to reproduce:
1. Right click a game, select properties, then set launch options.
2. Hold down the SHIFT key and enter some capitalized text. (You can also mix it with normal text.)
3. Close the dialogs to return to Steam.
4. Leftclick on a different game in your list.
5. Steam will multiselect all games in-between, as if SHIFT was being held down.

Applies to: desktop client, both normal and small mode.

**Comment by Unaccounted4** [comment] 2016-05-05 23:13
This seems to be related to this issue: https://github.com/ValveSoftware/steam-for-linux/issues/4187

Which I'm also experiencing on Fedora 23 64bit LXDE.

**Comment by nightsky30** [comment] 2018-08-22 11:47
Also seems like #3451

**Comment by kisak-valve** [comment] 2018-08-22 13:14
Thanks @nightsky30, closing as a duplicate of #3451.

**Closed by kisak-valve** 2018-08-22 13:14 UTC
Labels: reviewed
