### ISSUE TITLE
[Remote Play] No sound when streaming 

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#6606] opened 2019-10-21 20:54 UTC
#### Your system information

* Steam client version: 
![image](https://user-images.githubusercontent.com/42655600/67242230-c245c900-f45d-11e9-8bbc-69bd2298b84b.png)
* Distribution: Ubuntu 19.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Game where this occured: Cuphead 

#### Please describe your issue in as much detail as possible:
When streaming from a Linux PC (host) to a Windows 10 PC (client), the client has no audio. Similar report on the Remote Play forums https://steamcommunity.com/groups/homestream/discussions/1/1608274347734840648/

**Comment by kisak-valve** [comment] 2019-10-21 21:14
Hello @Managor, Steam should use pulseaudio to get the game's audio, is it healthy?

**Comment by Managor** [comment] 2019-10-21 21:17
Oh right, I have Pipewire installed. I don't know if it's active or if it interferes with anything. I'm asking the guy on the steam forums to come here and tell if he has anything similar.

**Comment by Managor** [comment] 2019-10-21 22:01
Uninstalled Pipewire and tried again the problem still persists. Added Cuphead to the OP as the game where I tried this.

**Comment by Newbie13XD** [comment] 2019-10-21 22:18
I have this issue on Fedora 30 Workstation too.

**Comment by Managor** [comment] 2019-10-21 23:42
Judging by the reddit thread, it seems to be a common problem https://www.reddit.com/r/linux_gaming/comments/dl3ppk/steam_remote_play_together_beta_released_with/

**Comment by captn3m0** [comment] 2019-10-22 05:11
Can confirm this. Running Arch with latest beta. Tried multiple games (Linux -> Windows). Using Pulseaudio.

**Comment by ananace** [comment] 2019-10-22 17:58
I seem to be having this same problem as well, on Sabayon Linux (Gentoo-derivate) with a Flatpak install for Steam. Friend/client is using Windows 10.
[System information](https://gist.github.com/ananace/4d255943fd3b3d5c81913401acba4fc8)

The system's got two audio outputs connected, with neither ending up on the stream.

**Comment by Benjuspr** [comment] 2019-10-22 22:59
Confirming this. Running on Solus, tried multiple games using Pulseaudio and the person i invited to play with me couldn't hear any audio on his end.

**Comment by ThaChillera** [comment] 2019-10-24 19:16
Similar issues, Arch Linux with Pulse audio server. Latest updates on everything

**Comment by blastermaster77** [comment] 2019-10-25 19:02
I have the same problem my friend can conect to castle crashers but he has no audio. Im using ubuntu 19.10, if someone has a workarround let me know. thanks

**Comment by kisak-valve** [comment] 2019-10-29 00:54
Hello, per "Enabled audio capture for Remote Play Together on Mac OS X and Linux hosts" in the [2019-10-28](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1656688677577750356) Steam client beta update, please retest this issue.

**Comment by Newbie13XD** [comment] 2019-10-29 19:59
Audio works for me on Fedora 30 as server and Windows 10 as client.

**Comment by captn3m0** [comment] 2019-10-29 20:08
Arch Linux (server) -> Windows 10 Client.

Audio works.

**Comment by ThaChillera** [comment] 2019-10-29 20:46
Fixed for me as well, thanks for the work

**Comment by Benjuspr** [comment] 2019-10-30 01:28
Solus -> Windows 10 , audio works now. 
Also they can hear everything else that's not part of the game, not sure if that's working as intended or not since when speaking to them through discord/teamspeak or any communication app, they can hear themselves talking.

**Comment by Newbie13XD** [comment] 2019-10-30 09:59
> Also they can hear everything else that's not part of the game, not sure if that's working as intended or not since when speaking to them through discord/teamspeak or any communication app, they can hear themselves talking.

Peculiar, person I played with didn't mention anything like that. Might have been because we were using Steam's voice chat though.

**Comment by ThaChillera** [comment] 2019-10-30 10:34
I had a similar experience, person playing with me could hear everything, when using discord or steam voice, it didnt matter

**Comment by ananace** [comment] 2019-10-30 11:26
Might depend on your pulseaudio setup, having separate sinks for communication and other audio for example

**Comment by ananace** [comment] 2019-11-07 06:54
I was able to test this with a friend again, and audio is now coming through fine. We were able to play for a while without any issues.  
Though, the game started on the wrong audio output at first, and I had to move it from my communication sink to my main output sink before it was captured by Remote Play Together.

**Comment by kisak-valve** [comment] 2019-12-13 15:41
Thanks for resting. Closing as fixed.

**Closed by kisak-valve** 2019-12-13 15:41 UTC
Labels: Audio, Need Retest, Streaming

**Comment by albertz** [comment] 2020-05-17 10:34
My host is Ubuntu 20.04, and client MacOSX. Sound does not work. I played around with the settings a bit (not sure if I'm supposed to set "play audio on host"), but so far nothing works.

**Comment by jennasisis** [comment] 2020-07-08 19:57
Hello, +1 to having this issue again

**Comment by marcospampi** [comment] 2020-11-08 10:18
I had the same issue with Android guest and Linux host, I had pavucontrol signaling that Steam is recording, yet no audio on client device... I solved by reinstalling the steam client app tho

**Comment by xz-dev** [comment] 2022-05-30 02:25
I solve it by create a virtual microphone device as [that](https://xzos.net/steam-for-linux-no-sound-when-streaming/) say

**Comment by bjwest** [comment] 2023-05-21 08:35
This issue has been closed for close to a year, but the issue still persists.  Does anyone even care that the Linux client doesn't stream audio?  Neither my Linux laptop nor Steam link gets audio from my Linux desktop (both laptop and desktop are running a fully updated Neon Linux, based on Ubuntu 22.04) but they do on my Windows Desktop.

**Comment by nil123532** [comment] 2023-11-30 05:00
Please fix. 
Reporting same with ubuntu 22.04 as host and windows 11 as client

**Comment by adriancuevas99** [comment] 2024-02-18 18:15
The same here with Fedora 39, no audio output when I am using remote play

**Comment by nil123532** [comment] 2024-02-19 02:54
I restarted both my devices and it worked.

**Comment by adriancuevas99** [comment] 2024-02-19 10:32
I have fixed to, it was the virtual speaker that was disabled in windows audio settings
