### ISSUE TITLE
Steam Client frozen/restarting when using more than one window

### ISSUE THREAD

**Issue by alosarjos** [ValveSoftware/steam-for-linux#10666] opened 2024-03-25 17:04 UTC
#### Your system information

* Steam client version (build number or date): 1711147596
* Distribution (e.g. Ubuntu): Arch Linux (Using Gnome 46 on Wayland)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14747118/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:

If using the HW acceleration for the windows. I've notice than specially when interacting with secondary windows, the main client window can freeze for some time, until it restarts it self

#### Steps for reproducing this issue:

Not happening 100% of the time, but 95% easily

1. Run Steam with HW acceleration
2. Open the friend list and interact, for example, changing the status
3. Close the friends window

[Grabación de pantalla desde 2024-03-25 17-57-56.webm](https://github.com/ValveSoftware/steam-for-linux/assets/29999427/bdc5a0f4-d5a5-4c74-a392-85eb9bfef3ec)

**Comment by alosarjos** [comment] 2024-03-25 17:05
Just to make sure, since it can't seen on the video, after closing the friends window, I'm clicking on any game, trying to go to the game details view

**Comment by nm004** [comment] 2024-04-06 01:12
Same issue here. The bug may be related to switching tabs (Store, Library, Community or "Your profile") since I sometimes see the bug after swithing tabs.

#### Your system information

* Steam client version (build number or date): 1709846872
* Distribution (e.g. Ubuntu): Fedora 39 (Gnome 45.5 on Wayland)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14891880/steam-logs.tar.gz)
* GPU: AMD Radeon RX 6800

#### Please describe your issue in as much detail as possible:
Same as the original post.

#### Steps for reproducing this issue:

Same as the original post.

[Screencast from 2024-04-06 10-06-10.webm](https://github.com/ValveSoftware/steam-for-linux/assets/99280467/a1f98e71-b31e-4c9e-bc4b-e62138f7841b)

**Comment by nm004** [comment] 2024-04-06 01:17
> 2. Open the friend list and interact, for example, changing the status

I saw the bug when just closing the window and not interacting it. The bug also happens when you closes the Steam community screenshot window.

**Comment by McMarius11** [comment] 2024-04-13 10:09
i have this bug only when i close the big notification, it steam freezes for about 10 seconds and then resumes as normal

**Comment by hubertnnn** [comment] 2024-05-16 10:52
I have similar issue with opening store pages in tabs.
It seems that the frozen state is caused specifically by closing of a tab/window and it freezes the main window for exactly 1 minute.
Most likely some kind of race condition during unloading of components causing a deadlock with 60 second timeout when waiting for resources.

**Comment by nm004** [comment] 2024-09-20 04:45
I don't see the bug anymore with the current client (Stable Client, Steam Version 1726604483, Steam Client Build Date:  Wed, Sep 18 5:03 AM UTC -08:00).

**Comment by alosarjos** [comment] 2024-09-23 19:54
I just give it a try re-enabling the hardware acceleration for the client and its working perfectly for me. (I'm on latest beta). I would say this can be closed :D

**Closed** 2024-09-23 19:55 UTC
Labels: Steam client, Need Retest, Distro Family: Arch, Web Component
