### ISSUE TITLE
Resizing the Steam client window by dragging it to the top of the screen when using Cinnamon

### ISSUE THREAD

**Issue by Amanoo** [ValveSoftware/steam-for-linux#1357] opened 2013-02-07 13:40 UTC
Hello. I just discovered a bug with the Steam client on Linux Mint + Cinnamon that occurs when I try to drag my Steam client window to another location in order to demaximize it after maximizing the client window. Maximizing works fine (inluding dragging the screen to the top), and I can demaximize by double clicking the top bar or pressing the maximize/demaximize button, but when I try to drag the screen away the Steam client considers itself demaximized, but doesn't change size and stays stuck. The window manager seems to refuse registering the screen as being demaximized and thus keeps the client maximized. After this, the normal maximizing/demaximizing features of the client stop working. Demaximizing by dragging the screen works fine in other applications, just not in the Steam client window.

**Comment by kisak-valve** [comment] 2017-04-04 15:45
Hello @Amanoo, I am unable to reproduce this issue with Cinnamon 3.0 on Gentoo Linux. Are you still experiencing this issue on an up to date system?

**Comment by Amanoo** [comment] 2017-04-04 20:38
I think it works now. It's a pretty old bug, and I can't reproduce it either. Probably got fixed in the last 4 or so years.

**Comment by kisak-valve** [comment] 2017-04-04 22:25
Thanks for retesting @Amanoo, closing.

**Closed by kisak-valve** 2017-04-04 22:25 UTC
Labels: Need Retest, reviewed, Steam client, Window manager
