### ISSUE TITLE
Window without border mode covered by taskbar

### ISSUE THREAD

**Issue by dbpalan** [ValveSoftware/steam-for-linux#4526] opened 2016-06-30 02:22 UTC
#### Your system information
- Steam client version: Steam client beta (2016-06-29)
- Distribution: lubuntu 14.04
- Opted into Steam client beta?: Yes
- Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:

Run Left 4 Dead 2 in "Window without border" mode, the lowest part is covered by lubuntu taskbar
Expected: Game window is on top of everything created by X window
What happened: Lubuntu taskbar is on top of game window, covered lowest part of the game window
#### Steps for reproducing this issue:
1. Set lubuntu resolution to 1920 x 1080
2. Run Left 4 Dead 2
3. In Left 4 Dead 2 "Video" config page, set resolution to 1920 x 1080 and "Window without border" mode

**Comment by kisak-valve** [comment] 2019-06-07 13:53
Closing as a duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/2678.

**Closed by kisak-valve** 2019-06-07 13:53 UTC
Labels: reviewed
