### ISSUE TITLE
Steam GUI Broken Into Separate Xorg Windows Until Restarted

### ISSUE THREAD

**Issue by MkThUnderwd** [ValveSoftware/steam-for-linux#9786] opened 2023-07-03 23:53 UTC
#### Your system information

* Steam client version (build number or date): 
**Steam Version:  1687386907
Steam Client Build Date:  Wed, Jun 21 16:18 UTC -06:00
Steam Web Build Date:  Wed, Jun 21 17:26 UTC -06:00
Steam API Version:  SteamClient020**

* Distribution (e.g. Ubuntu):  - **Xubuntu 22.04.2 LTS x86_64**
* Opted into Steam client beta?: [Yes/No] - **NO**
* Have you checked for system updates?: [Yes/No] - **YES**

**These packages were not updated at the time:**

> libmm-glib0
> linux-firmware
> modemmanager
> php8.1-cli
> php8.1-common
> php8.1-opcache
> php8.1-readline
> php8.1-xml
> python3-renderpm
> python3-reportlab
> python3-reportlab-accel
> ubuntu-drivers-common

* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
[2023-07-02_mkthunderwd_steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11941892/2023-07-02_mkthunderwd_steam-logs.tar.gz)
* GPU: Nvidia/Intel/AMD - **AMD Radeon RX 6700 XT (navi22, LLVM 15.0.7, DRM 3.51, 5.15.0-75-generic) (0x73df)**

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

**This screenshot says it all. All the popup windows of Steam were broken out into their own generic-icon Xorg windows:**
![STEAM_GLITCH_Screenshot_2023-07-03_18-05-39_1](https://github.com/ValveSoftware/steam-for-linux/assets/5314016/7880f94a-f187-4c36-9fe3-a03fd0827681)

#### Steps for reproducing this issue:

1. **I have not idea how to make it occur. It happened while I was away from my computer.**

**I hope this helps figure out a cause. This is the first time I've seen this kind of error that I can remember.
See Steam request thread here:** [HelpRequest HT-986N-WC65-3Q22](https://help.steampowered.com/en/wizard/HelpRequest/HT-986N-WC65-3Q22)

**Comment by Caffeineix** [comment] 2023-07-05 12:56
This happened to me after waking from suspend, so that might have something to do with it. It looks like the exact same issue, black window and UI in top-left corner.

**Comment by jasuka** [comment] 2023-07-05 14:09
This also happens to me when the PC is idling for a longer period of time (for example overnight) with locked screen.

**Comment by nijave** [comment] 2023-07-07 01:57
Same over here on Fedora 37. They only show up after sitting idle overnight so far

**Comment by bhechinger** [comment] 2023-07-11 12:09
This also happens to me if I leave steam running overnight.

**Comment by dragynbane222** [comment] 2023-07-16 13:58
I have had this happen as well, though it doesn't seem to happen on KDE, just Gnome and GTK-based desktops. hopefully that helps.

**Comment by bhechinger** [comment] 2023-07-16 18:31
Unfortunately I'm on KDE so we've got all bases covered I guess. :-D

**Comment by kisak-valve** [comment] 2023-07-24 12:54
All menu windows become visible if steam started with no monitor

Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/9902.
@tutacat posted on 2023-07-24T11:49:53:

#### Your system information

* Steam client version (build number or date): client 1689034492 (web 1689043680)
* Distribution (e.g. Ubuntu): Fedora (XWayland)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: 
* GPU: AMD
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12145221/steam-logs.tar.gz)

#### Please describe your issue in as much detail as possible:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/16363617/7922a032-79ff-401e-a9ed-788002a84ef1)
* Each menu window (which should be invisible and borderless) becomes visible and bordered, due to an error when starting steam without a monitor connected.

#### Steps for reproducing this issue:

1. Turn off or disconnect your monitor
2. Open Steam
4. Reconnect your monitor
5. See all the menu windows visible with a border, instead of hidden

**Comment by CptCookies12** [comment] 2023-08-08 19:52
I can confirm this also still happening to me on Steam version 1690583737 on a system running Fedora 38 with KDE Plasma and Wayland, and using an AMD Radeon 6700 XT. It only happens if I turn off my two monitors with Steam running overnight and usually makes me have to kill Steam in the System Monitor because it doesn't respond.

**Comment by tutacat** [comment] 2023-08-15 05:08
@CptCookies12 The menu windows still work. It will exit the the Exit Steam menu button, or from the taskbar icon.

**Comment by MkThUnderwd** [comment] 2023-09-04 14:41
I'm not sure it's related but have a feeling it is. When I have my displayport monitor powered off and try to Streamlink stream from my PC to my Android phone, Steam crashes.

`steam.sh: line 798: 2187492 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20230903195904_74.dmp[2194280]: Finished uploading minidump (out-of-process): success = yes
crash_20230903195904_74.dmp[2194280]: response: CrashID=bp-83b701de-5cdc-4f3d-a081-2ecfb2230903
crash_20230903195904_74.dmp[2194280]: file ''/tmp/dumps/crash_20230903195904_74.dmp'', upload yes: ''CrashID=bp-83b701de-5cdc-4f3d-a081-2ecfb2230903''`
[crash_20230903195904_74.dmp.zip](https://github.com/ValveSoftware/steam-for-linux/files/12514686/crash_20230903195904_74.dmp.zip)

**Comment by Foxmanx7** [comment] 2023-09-07 11:27
I am also having exactly the same issue. With the steam installed through flatpak I don´t have this issue but with the package installed from pacman I do.

**Comment by caphene** [comment] 2023-09-21 00:53
Oddly, I haven't had this happen in a few days. Anyone else experiencing that as well? Nothing's really changed on my end except for maybe a few updates.

**Comment by bhechinger** [comment] 2023-09-21 09:05
> Oddly, I haven't had this happen in a few days. Anyone else experiencing that as well? Nothing's really changed on my end except for maybe a few updates.

I've not had this issue or the VRAM leak issue since the latest update. I think they fixed it.

**Comment by Cookies77777** [comment] 2023-10-05 18:54
> Oddly, I haven't had this happen in a few days. Anyone else experiencing that as well? Nothing's really changed on my end except for maybe a few updates.

Same here, around 13 days uptime and no issues anymore so I think it's fixed.

**Comment by MkThUnderwd** [comment] 2023-10-11 04:27
I have not noticed it happening lately and I just tried it again: started Steam, turned off montior, waited a few seconds, turned monitor back on, no glitch.

Steam Version:  1696019606
Steam Client Build Date:  Fri, Sep 29 12:38 UTC -06:00
Steam Web Build Date:  Fri, Sep 29 15:25 UTC -06:00
Steam API Version:  SteamClient020

**Comment by kisak-valve** [comment] 2023-11-24 23:23
Closing per the last couple comments.

**Closed by kisak-valve** 2023-11-24 23:23 UTC
Labels: Steam client, Need Retest

**Comment by Sn0uu** [comment] 2024-03-08 17:23
I'm having this issue on Windows, has been happening the last few days.

**Comment by joshdee** [comment] 2024-03-25 06:25
> I'm having this issue on Windows, has been happening the last few days. Commenting here so it isn't closed as duplicate.

Same here!

**Comment by DHager** [comment] 2024-03-25 07:13
Just chiming in that I observed this (for the first time) just now on Windows 10, so it's still happening on some platforms.

In case it offers a clue:

1. Computer unattended to install new game (Talos Principle 2) 
2. Switched to another local Windows user account
3. Possible sleep/resume
4. Continued on that other account, then switched back
5. Saw ~10 of those black windows with partial menu dropdowns

**Comment by dragynbane222** [comment] 2024-03-25 07:19
To all the Windows users commenting on a bug you're encountering:

1. This is not the place for you to report that, a Valve employee has Said to go to customer support for your bugs.
2. This is a completely unrelated but for an operating system you do not use (Linux) that works completely differently. Any similarities are only skin deep 
3. You have not found a regression, see point 2.
4. This project that you're reporting a bug on is specifically for Linux, as such any input you put here is useless to Valve.

**Comment by eranekao** [comment] 2024-05-10 19:08
This happens to me and I'm on Windows. I know this is for Steam Linux but it's the only thread I could find about the issue, so I'm hoping that help narrowing down the causes.

Steam Version: 1709846872

It happens when I lock my Windows session or when I log into another local Windows user on my PC for a while and then re-open the Windows user session I didn't log out of.

**Comment by DavidPyke** [comment] 2024-06-14 17:46
I have this issue too.  Running Wayland on Kubuntu with a KVM switch.  When I switch to the other system for more than a couple hours, I get 12 windows, one for each menu.

**Comment by ASCI-Blue** [comment] 2024-08-18 18:40
Wife has the same issue Garuda linux, dual monitor setup, Wayland, no auto logout. I also run Garuda, no problem, single monitor, power settings to always on and no auto logout.

**Comment by DeviceLimit** [comment] 2024-08-23 15:30
I have been having this issue for a while now. On EndeavorOS  KDE Wayland with an AMD RX6700XT graphics card.  I use a KVM to switch between this computer and another though Ive had it happen even when I didn't switch and just let the screen look and monitors standby by themselves.

**Comment by XOmniverse** [comment] 2024-08-26 21:06
Same issue, very similar setup to DeviceLimit (NVidia 4090 GPU, but exact same OS/desktop environment). Problem began after I started using Wayland.

**Comment by caphene** [comment] 2024-09-24 06:39
Oddly it stopped for a bit for me, but then came back. Still the same system as previously posted in #9934
