### ISSUE TITLE
Remember password does not work most of the time, steam asks for password every login.

### ISSUE THREAD

**Issue by calexil** [ValveSoftware/steam-for-linux#4567] opened 2016-07-25 00:36 UTC
#### Your system information

Motherboard : MSI 970A-G46  
Processor : AMD FX-8350 4Ghz Octocore  
Cooling : Cooler Master Hyper 212 Evo  
Memory : 16GB PNY-XLR8 DDR3 1600Mhz 9-9-9-27  
Operating System : Linux Mint 18 Sarah  
Display : Asus 24in Lcd 1920x1080  
Video Card : XFX Radeon R9 380X  
Graphics Driver : amdgpu+Mesa 11.2  
HDD : WD Blue 1TB  
SSD : OCZ-VERTEX3  
PSU : Rosewill Photon 750  
- Steam client version: latest non beta in xenial repo whichever that is steam:i386 1:1.0.0.48-1ubuntu3
- Distribution (e.g. Ubuntu): Linux mint 18
- Opted into Steam client beta?: [No] 
- Have you checked for system updates?: [Yes]
#### Please describe your issue in as much detail as possible:

steam does not remember my password, mint 18 MATE, The default keyring is unlocked. remember password box checked, and 'do not store login cred..." unchecked...

randomly and seemingly without cause the login will fail, and steam will require me to reenter my password

insanely annoying to have to enter my encrypted password over and over again.

I think this is keyring/auto login related
#### Steps for reproducing this issue:
1. start steam after login
2. enter password, make sure remember pwd is checked
3. go to settings after login, make sure "do not remember login cred..." is unchecked
4. logout/restart computer
5. try to start steam.... asks for password :/   almost every damn time :/

**Comment by Tele42** [comment] 2016-07-25 03:14
Possible duplicate of #3059.

**Comment by calexil** [comment] 2016-07-25 17:56
@Tele42 might be related, but certainly not a duplicate. I don't dualboot one distro on all affected systems

**Comment by OscarOrSomething** [comment] 2016-07-26 20:54
Having this problem. I assume the two are related, Steam support are refusing to help cos i'm not using ubuntu (an outdated version as well)

**Comment by OscarOrSomething** [comment] 2016-08-09 16:25
After reinstalling my computer it worked for 3 days and now my skin and password are not being saved. Any fix?

**Comment by OscarOrSomething** [comment] 2016-09-06 16:07
@calexil Are you still having this problem? Broken for me, Very annoying.

**Comment by calexil** [comment] 2016-09-06 17:32
Still happening. Almost certain it has to do with signing in on two machines on the same network now...
On Sep 6, 2016 12:07 PM, Oscar <notifications@github.com> wrote:@calexil Are you still having this problem? Broken for me, Very annoying.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ValveSoftware/steam-for-linux","title":"ValveSoftware/steam-for-linux","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ValveSoftware/steam-for-linux"}},"updates":{"snippets":[{"icon":"PERSON","message":"@OscarOrSomething in #4567: @calexil Are you still having this problem? Broken for me, Very annoying."}],"action":{"name":"View Issue","url":"https://github.com/ValveSoftware/steam-for-linux/issues/4567#issuecomment-245001655"}}}

**Comment by Tele42** [comment] 2016-09-06 17:46
@calexil, something has gone wrong with your last comment. Please hop on github and edit out the potentially sensitive information.

**Comment by calexil** [comment] 2016-09-06 18:13
@Tele42 thx, stupid email replies

**Comment by xhsdf** [comment] 2016-09-14 16:44
Still not fixed. Very annoying. I have to login via SSH on my Steam Machine using this script on it:
`DISPLAY=:0 xdotool getactivewindow key KP_Enter
read -s -p "Password: " spw
echo
DISPLAY=:0 xdotool getactivewindow type --delay 100 "$spw"
sleep 0.2s
DISPLAY=:0 xdotool getactivewindow key KP_Enter`

**Closed** 2017-07-05 17:45 UTC
Labels: reviewed

**Comment by Gfurst** [comment] 2017-07-20 18:50
Any news on the issue? its been closed without answer, but lately Steam has been like that, always asking for password.

**Comment by kisak-valve** [comment] 2017-07-20 18:55
Hello @Gfurst, you're most likely looking for the issue currently being tracked at #5030.
