### ISSUE TITLE
Steam auto-launching last run game on update

### ISSUE THREAD

**Issue by petteyg** [ValveSoftware/steam-for-linux#8094] opened 2021-09-22 22:52 UTC
#### Your system information

* Steam client version (build number or date): sep 16 2021 4:30:38, 1631912732
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

For the past several Steam client updates (i.e. Steam pops up a dialog with a list of changes and a button to "restart now"), when I restart Steam, it will restart and apply its update appropriately, and then proceed to launch whatever game I last ran. This can be very annoying with the last game I ran is buggy Proton stuff and takes forever to launch to a point that I can actually tell it to quit.

Aside, the text area with the changelog on the updates is always blank, or the text is the same color as the background, or something, until I click restart and then the text appears and I have all of a few milliseconds to try to glimpse any of it before the client exits to update.

**Comment by kisak-valve** [comment] 2021-09-22 22:59
Hello @petteyg, this reads like a duplicate of #1414. When you started Steam before the update, did you start it via a game's desktop shortcut that started Steam along with the game?

The second part is being tracked at #6451.

**Closed** 2021-09-22 23:47 UTC
Labels: duplicate, Steam client, Distro Family: Gentoo
