### ISSUE TITLE
Some Steam windows have invisible right-click menus

### ISSUE THREAD

**Issue by Tynach** [ValveSoftware/steam-for-linux#4531] opened 2016-07-02 23:55 UTC
## My system information
- Steam client version: Jun 14 2016, at 23:24:07 (1465948400)
- Distribution: Ubuntu 16.04 64-bit, using KDE
- Opted into Steam client beta?: No.
- Have you checked for system updates?: Yes.
### Detailed description of the issue:

Context menus within many windows - but not all of them - are transparent and cannot be clicked while using a compositing window manager.

I know this is the case because sometimes you can right-click in an area that changes the mouse cursor to the 'I-Beam' text-selection cursor, and there is an invisible box in which the cursor will _not_ change to said I-Beam cursor. This means that the menu does pop up, but it's invisible for some reason.

I recorded the behavior, and in the recording I compare the invisible menu of one window with a visible menu of another menu - both menus being from different windows, but both from Steam. The working one is from the 'web browser' part, viewing my Steam profile. The non-working one is from the 'System Information' window. Take a look:

![bug](https://cloud.githubusercontent.com/assets/224197/16542969/bf7e47d0-4072-11e6-94a9-3b5a32b7c5ac.gif)
### Steps for reproducing this issue:
1. If Steam is already running, open it. Else, start Steam.
2. Go to the **Help** > **System Information** menu item.
3. Right-click anywhere in the text box. Doesn't matter if text is selected or not.
### About My Issue

System Information is not the only part of Steam that is affected. This is most often encountered within Steam Chat, as I cannot right-click to copy or paste text while chatting with people. However, for privacy reasons, I opted to capture an affected window that does not have information about other people than myself.
#### Troubleshooting Steps Taken

I've tried all possible combinations of OpenGL versions, EGL vs. GLX, and with DRI2 vs. DRI3. None of the aforementioned options change the behavior of the invisible menus. However, disabling compositing allows the menus to be seen and work perfectly.
#### Other Issue Reports

Someone in #606 has mentioned this bug, but I figured it deserved its own bug report (as it has nothing to do with the menus' positions, instead their visibility).
#### Other Software

OBS had run into [an issue](https://github.com/jp9000/obs-studio/commit/3967c6354a2f5ce9a08f416c7241d5563e28feb9) where Mesa did not support something dealing with alpha channels. I don't know if this is related at all to Steam's issue, but since transparency and Mesa drivers seem to be in common, I figured I'd mention it.
### About My System

I have a factory overclocked AMD Radeon R9 290X, and I use the open source Mesa drivers. I currently have DRI3 enabled and my window compositor, KWin, is set to use EGL and OpenGL 3.1. As mentioned, however, this doesn't really matter (except the fact I have compositing enabled).

**Comment by Tele42** [comment] 2016-07-03 00:38
Hello @Tynach, this should also be reported to the mesa devs.

**Comment by Tynach** [comment] 2016-07-03 03:17
@Tele42, I don't know for sure if it's specific to Mesa or not. It could also be that Steam's code tries to use an OpenGL or X11 extension (or something) that is non-standard. Or it could be an X11 bug that has nothing to do with Mesa. Heck, it could be a KWin bug.

I could probably install the fglrx drivers and see if it still occurs, but I've generally had a lot better stability using the open source drivers. And the AMDGPU Pro driver does not currently support my card.

On top of all of that, it could still end up being a Steam bug. No other program has invisible menus, just Steam. The OBS bug I mentioned in my bug report was related to capturing/recording windows - not anything to do with making something visible on the screen or not. I just figured I'd mention it in case it had any relation to the issue (perhaps dealing with GPU-side pixel formats for texture data, but I don't know).

**Comment by kisak-valve** [comment] 2017-05-24 16:11
Also occurs on Arch with KDE 5.

**Comment by Commander-Zal** [comment] 2018-05-06 04:25
I can confirm the issue still exists on Fedora with KDE Plasma 5.14.4

Disabling all compositing 'fixes' the issue, but this is a stopgap solution at best. Rather surprised that nothing has been done about this in just under 2 years...

**Comment by kode54** [comment] 2018-08-26 00:41
Also happens on Kubuntu 18.04.1 with KDE Plasma 5.12.6.

**Comment by Commander-Zal** [comment] 2018-08-31 07:55
I no longer encounter this issue in the new chat client, but right click menus continue to not function within the Steam client itself (Settings, address bar, etc).

Currently encountering this issue with:

- Antergos with kernel 4.18.5 
- Mesa 18.1-7
- KDE 5.13.4
- Intel i5-3320M / HD 4000 Graphics

**Comment by Tynach** [comment] 2018-09-01 08:41
@Commander-Zal, that's because the new chat client implements its own right-click menus that are not actual menus. The new interface is implemented using HTML/CSS/Javascript/etc., and the menus are generated by custom event handlers that make actual web page elements that act as menus.

Ironically, I used the 'System Information' window in the gif I made when submitting this bug report, and that particular window still exhibits the problem - so the developers certainly can't claim the bug is 'fixed' by simply pointing to their workaround in the new chat client.

**Comment by hochl** [comment] 2018-10-13 22:42
I have this exact same problem, an invisible window on the top left of my desktop. It is not there initially, but appears after using steam for some time. It moves with the virtual desktop. i.e. it appears to hang there in the top left, which is one of the worst places on a desktop since it makes most programs unusable.

**Comment by kode54** [comment] 2018-10-13 23:19
I had an invisible window pop up on top of the middle of my primary monitor, and clicks onto what appeared to be overlapping windows instead went through to the Steam main window underneath. The only way to make the invisible window go away was to quit Steam altogether.

**Comment by Tynach** [comment] 2018-10-24 01:35
I have had the 'invisible window in the top left' bug for a long time, and I believe it is a separate bug from *this* bug. I've never had it appear in the middle, only the top-left corner. I believe there's likely a separate bug report already for this issue, @kode54 and @hochl, though I admit I'm not sure. I'd have to go looking.

**Comment by kisak-valve** [comment] 2018-10-24 01:38
Convenience link: #5584

**Comment by atomic-penguin** [comment] 2019-03-29 20:55
If you're using KDE 5, you can block compositing for the Steam application, so that it will unhide objects like the Copy All Text to Clipboard menu on the System Information page.

Click on the Steam window so it is in-focus. Hit `Alt-F3` -> More Actions -> Special Application Settings -> Appearances & Fixes -> Check Block Compositing -> Force -> Yes.

Then restart Steam.

**Comment by Tynach** [comment] 2019-08-02 08:34
Sure, and you can also toggle compositing manually with Alt+Shift+F12... But you can't disable compositing for individual applications while allowing compositing for all other applications. It just blocks compositing while that application is running, period.

*That said*, this issue appears to *almost* be fixed!

Steam just updated to 'steam-runtime_0.20190711.3', and now the menus actually pop up for a few frames before turning invisible! At least, sometimes.

I can occasionally get them to stay open and I can actually click 'copy' in the System Information dialog window!

However, it's not perfect. They still largely disappear almost immediately, or never show up in the first place. So there's still a ways to go.

**Comment by guihkx** [comment] 2020-02-15 15:51
Just tested this on Plasma 5.18 and I don't think this is an issue anymore...

@Tynach can you confirm?

**Comment by Tynach** [comment] 2020-02-21 17:58
@guihkx I can confirm that the issue no longer occurs on my system, but since I use KDE Neon I'm unsure if this is actually a fix on KDE's side or on Valve's side. Can anyone confirm if the problem occurs in Gnome, Xfce, LXQt, etc.?

**Comment by kisak-valve** [comment] 2020-03-27 15:48
Closing as fixed.

**Closed by kisak-valve** 2020-03-27 15:48 UTC
Labels: Need Retest, Window manager, reviewed
