### ISSUE TITLE
The ubuntu steam package does not use $XDG_DATA_HOME

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#5272] opened 2017-12-05 07:44 UTC
inxi -F here: https://imgur.com/iH3XH3H
Steam version: https://i.imgur.com/YGzjzFK.png

* Steam client version: Dec 1 2017, at 15:05:56
* Distribution: Xubuntu 17.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

When installing the steam package from ubuntu repository, the program creates all the data files under ~/.steam. ~/Steam contains crash logs and bootstrap.log.txt and ~/.local/share does not contain any folder related to steam. It doesn't adhere to the XDG specifications at all. 
The .deb file you download from the steam website seems to work a bit more intended but it still litters the $HOME folder with .steam, .steampath and .steampid. What I've talked with Plagman, there isn't going to be a solution to this. 
A lot of other distros seem to create a symlink ~/.steam that links to ./local/share/Steam to fool steam into using the $XDG_DATA_HOME for everything it does.

#### Steps for reproducing this issue:

1. Download the Steam package from the ubuntu repository
2. Use steam

**Comment by Managor** [comment] 2017-12-05 07:47
Did some searching an this might be a duplicate of #1890

**Comment by kisak-valve** [comment] 2017-12-05 13:56
Hello @Managor, you'll need to reach out to the Debian package maintainer(s) for steam (as Ubuntu inherits this package from Debian) for this issue as your issue is with the distro-provided package, the Valve-provided deb has been using ~/.local/share/Steam for years.

The rest is a couple of legacy bits, which I agree is a duplicate of #1890. Closing in favor of the existing issue report.

**Closed by kisak-valve** 2017-12-05 13:56 UTC
