### ISSUE TITLE
Steam overlay crashes when trying to remove friend

### ISSUE THREAD

**Issue by DrDoctor13** [ValveSoftware/steam-for-linux#4356] opened 2016-03-16 01:32 UTC
On Linux, the Steam overlay will crash when trying to remove a friend from the friends list.

**Comment by Tele42** [comment] 2016-03-16 01:44
happen to be using nvidia 358.16?

**Comment by DrDoctor13** [comment] 2016-03-16 01:46
This was on Nvidia 361.28-4

**Comment by Tele42** [comment] 2016-03-16 01:51
nvidia drivers 361.28 has a known defective version of libglvnd bundled with it, if you close steam, then run ```__GLVND_DISALLOW_PATCHING=1 steam``` from a terminal, can you reproduce the problem?

**Comment by DrDoctor13** [comment] 2016-03-16 13:21
Yes, that did not fix it.


-Buck

**Comment by steamlinux** [comment] 2016-03-22 14:58
this fix doesn't help me
now I use 364.12

**Comment by DrDoctor13** [comment] 2016-03-22 15:01
I will post system information in the PM (I'm in EDT)

**Comment by DrDoctor13** [comment] 2016-03-25 13:37
Tried to add a friend, too. Crashed as well.

> System info:
> 
> Processor Information:
>     Vendor:  GenuineIntel
>     CPU Family:  0x6
>     CPU Model:  0x3c
>     CPU Stepping:  0x3
>     CPU Type:  0x0
>     Speed:  3700 Mhz
>     4 logical processors
>     4 physical processors
>     HyperThreading:  Unsupported
>     FCMOV:  Supported
>     SSE2:  Supported
>     SSE3:  Supported
>     SSSE3:  Supported
>     SSE4a:  Unsupported
>     SSE41:  Supported
>     SSE42:  Supported
>     
> Network Information:
>     Network Speed:  
>     
> Operating System Version:
>     "Arch Linux" (64 bit)
>     Kernel Name:  Linux
>     Kernel Version:  4.4.5-1-ARCH
>     X Server Vendor:  The X.Org Foundation
>     X Server Release:  11801000
>     X Window Manager:  GNOME Shell
>     Steam Runtime Version:  steam-runtime-release_2016-02-23
>     
> Video Card:
>     Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2
> 
>     Driver Version:  4.5.0 NVIDIA 361.28
>     OpenGL Version: 4.5
>     Desktop Color Depth: 24 bits per pixel
>     Monitor Refresh Rate: 60 Hz
>     VendorID:  0x10de
>     DeviceID:  0x13c2
>     Number of Monitors:  2
>     Number of Logical Video Cards:  1
>     Primary Display Resolution:  1920 x 1080
>     Desktop Resolution: 3520 x 1080
>     Primary Display Size: 18.74" x 10.55"  (21.50" diag)
>                                             47.6cm x 26.8cm  (54.6cm diag)
>     Primary Bus: PCI Express 16x
>     Primary VRAM: 4096 MB
>     Supported MSAA Modes:  2x 4x 8x 16x 
>     
> Sound card:
>     Audio device: Realtek ALC887-VD
>     
> Memory:
>     RAM:  16003 Mb
>     
> Miscellaneous:
>     UI Language:  English
>     LANG:  en_US.UTF-8
>     Microphone:  Not set
>     Total Hard Disk Space Available:  234098 Mb
>     Largest Free Hard Disk Block:  108831 Mb
>     VR Headset: None detected
>     
> Installed software:
>     
> Recent Failure Reports:
>     Fri Mar 25 13:36:01 2016 GMT: file ''/tmp/dumps/crash_20160325092943_2.dmp'', upload yes: ''Discarded=1''
>     
>

**Comment by steamlinux** [comment] 2016-04-13 20:43
https://github.com/ValveSoftware/steam-runtime/issues/39

**Comment by not83** [comment] 2016-04-13 21:04
Does this issue happen only on Debain with Nidia?

ValveSoftware/steam-runtime#39
<https://github.com/ValveSoftware/steam-runtime/issues/39>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/ValveSoftware/steam-for-linux/issues/4356#issuecomment-209639790>

**Comment by steamlinux** [comment] 2016-04-13 21:44
I don't know where this issue happen, because I use only debian and only nvidia

**Comment by DrDoctor13** [comment] 2016-06-23 01:37
This still happens with the latest Nvidia drivers.

**Comment by Plagman** [comment] 2016-08-15 22:22
Hi,

Is this the desktop client overlay, or Big Picture?

**Comment by DrDoctor13** [comment] 2016-08-15 22:29
This is the desktop client overlay. I have not tested it with big picture...

**Comment by Kurolox** [comment] 2016-08-17 18:21
Same here. Using Arch and Nvidia 367.35.
```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3800 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.7.0-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  i3
    Steam Runtime Version:  steam-runtime-beta-release_2016-06-15
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 770/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 367.35
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1184
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3200 x 1080
    Primary Display Size: 20.08" x 11.30"  (23.03" diag)
                                            51.0cm x 28.7cm  (58.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: VIA VT2020
    
Memory:
    RAM:  16010 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  110522 Mb
    Largest Free Hard Disk Block:  30519 Mb
    VR Headset: None detected
    
Recent Failure Reports:
    Wed Aug 17 18:03:25 2016 GMT: file ''/tmp/dumps/crash_20160817181857_2.dmp'', upload yes: ''Discarded=1''
    
```

**Comment by Plagman** [comment] 2016-08-23 02:32
This will be fixed in the next Beta cycle, thanks for the report.

**Comment by kisak-valve** [comment] 2019-04-05 15:50
Closing per the last comment.

**Closed by kisak-valve** 2019-04-05 15:50 UTC
Labels: reviewed
