### ISSUE TITLE
When a game beta ends, the beta name is stuck at the end of the game name

### ISSUE THREAD

**Issue by eydee** [ValveSoftware/steam-for-linux#3859] opened 2015-05-27 09:06 UTC
If you enter a game beta, the name of the beta is added to the end of the game name in your list. When the beta is ended by the developer, the game name in stuck in that state. As there is no longer a betas tab on the property sheet of the game, there is no way to "opt out" from the beta, that doesn't even exist anymore, and the name is not corrected automatically.

**Comment by MrSchism** [comment] 2015-05-27 09:16
This is a duplicate of #3456.  Closing as such.

**Closed by MrSchism** 2015-05-27 09:16 UTC
