### ISSUE TITLE
Mouse input delay after using the Steam Overlay

### ISSUE THREAD

**Issue by Liemaeu** [ValveSoftware/steam-for-linux#10265] opened 2023-11-30 15:50 UTC
#### Your system information

* Steam client version (build number or date): both regular Steam version and Beta
* Distribution (e.g. Ubuntu): openSUSE Tumbleweed 64-bit, KDE Plasma 5.27.9, X (not Wayland)
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]
* GPU: Nvidia RTX 3070, 545.29.06 driver

#### Please describe your issue in as much detail as possible:
When I open the Steam Overlay in-game and navigate through it (e.g. opening the achievement list or a chat window to accept an invitation); after closing the Overlay I have an extreme delay to mouse inputs in-game (e.g. when turning the camera with the mouse, I turn around delayed).

From what I can tell it's only the mouse, neither my keyboard nor my controller (if I plug one in).

It happens with both regular Steam Overlay and Big-Picture-Mode Overlay.
I only observed this issue in Proton games (e.g. Phasmophobia and Shadow Warrior 2) yet, but I haven't played any native games lately.

#### Steps for reproducing this issue:

1. Open the Steam Overlay (Shift + Tab)
2. Do something with it (e.g. open a chat)
3. Close the Steam Overlay

**Comment by kisak-valve** [comment] 2023-11-30 16:07
Hello @Liemaeu, this reads like a duplicate of #8591. Closing in favor of the older issue report.

**Closed by kisak-valve** 2023-11-30 16:07 UTC
