### ISSUE TITLE
Half-Life 2: Update Crashes missing libtcmalloc_minimal.so.4 with pressure-vessel

### ISSUE THREAD

**Issue by Vash63** [ValveSoftware/steam-for-linux#6722] opened 2019-11-26 23:29 UTC
To be honest I can't get this working natively either, but that's for wholly different reasons as it seems there's something broken between my system and the libtcmalloc provided by this game. With the Steam Linux Runtime enabled when launching the game I get:

```
 /mnt/steam/steamapps/common/Half-Life 2 Update/hl2_linux: error while loading shared libraries: libtcmalloc_minimal.so.4: cannot open shared object file: No such file or directory
```

Without the pressure vessel enabled it crashes with:
```
/mnt/steam/steamapps/common/Half-Life 2 Update/hl2_linux: symbol lookup error: /usr/lib32/libtcmalloc_minimal.so.4: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEj, version GLIBCXX_3.4.21
```

I've confirmed also that the game ships its own libtcmalloc_minimal.so.4 in the `bin` subdirectory so I'm not sure why this was referencing my system location. Forcing `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0` gives a similar 'no such file' error (also this breaks the Steam library so I had to launch it with steam://launch/appid which is another problem when testing)

These secondary issues are probably Arch related, but I was hoping the pressure vessel would get around them.

[System info](https://gist.github.com/Vash63/de8cfef4e4abcbfe884d1163fdb3c2bb)

**Comment by kisak-valve** [comment] 2019-11-26 23:50
Closing as a duplicate of #5425.

**Closed by kisak-valve** 2019-11-26 23:50 UTC
Labels: 3rd party game, Steam database

**Comment by teihome** [comment] 2025-08-12 03:38
for flatpak, I found this workaround to be successful: https://github.com/flathub/com.valvesoftware.Steam/issues/1361#issuecomment-2699483277
