### ISSUE TITLE
Mouse pointer changes when moving over the sale graph when selling item

### ISSUE THREAD

**Issue by HenAlm** [ValveSoftware/steam-for-linux#3058] opened 2013-12-26 07:51 UTC
I noticed that when I move the mouse over the graph in check prices, it changes the mouse pointer. Is this intentional? It seems I can't take a screenshot where the mouse would be, but it becomes the X with circle around it.

I'm using Kubuntu.

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x17
    CPU Stepping:  0x6
    CPU Type:  0x0
    Speed:  2501 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 13.04 (32 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-33-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2013-10-23

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD RV630

    Driver Version:  3.0 Mesa 9.1.7
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x9581
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 1680 x 1050
    Primary Display Size: 13.03" x 8.15"  (15.35" diag)
                                            33.1cm x 20.7cm  (39.0cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Analog Devices AD1981

Memory:
    RAM:  3970 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  140161 Mb
    Largest Free Hard Disk Block:  12360 Mb

Installed software:

Recent Failure Reports:

```

**Comment by kisak-valve** [comment] 2017-10-20 14:46
Closing as a duplicate of #2616.

**Closed by kisak-valve** 2017-10-20 14:46 UTC
Labels: reviewed, Steam client
