### ISSUE TITLE
Steam stuck at login with websocket error

### ISSUE THREAD

**Issue by ryuukk** [ValveSoftware/steam-for-linux#11216] opened 2024-08-29 16:03 UTC
vvvvvvvvvvvvvvvvvvvv
📣 **WORKAROUND FOUND**: start steam with `steam -tcp` https://github.com/ValveSoftware/steam-for-linux/issues/11216#issuecomment-2318253260
^^^^^^^^^^^^^^^^^^

#### Your system information

* Steam client version (build number or date): steam 1.0.0.81-2
* Distribution (e.g. Ubuntu): arch linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16801866/steam-logs.tar.gz)

* GPU: AMD RX 6600 XT

#### Please describe your issue in as much detail as possible:

Doesn't start, nothing show up

If i start with the command -v, it's stuck on the sign-in menu

#### Steps for reproducing this issue:

```
$ steam -nofriendsui -v
```
```
steam.sh[74695]: Running Steam on arch rolling 64-bit
steam.sh[74695]: STEAM_RUNTIME is enabled automatically
setup.sh[74770]: Steam runtime environment up-to-date!
steam.sh[74695]: Steam client's requirements are satisfied
[2024-08-29 18:02:04] Startup - updater built Jul 16 2024 23:21:18
[2024-08-29 18:02:04] Startup - Steam Client launched with: '/home/ryuukk/.local/share/Steam/ubuntu12_32/steam' '-srt-logger-opened' '-nofriendsui' '-v'
08/29 18:02:04 minidumps folder is set to /tmp/dumps
08/29 18:02:04 Init: Installing breakpad exception handler for appid(steam)/version(1721173382)/tid(74823)
[2024-08-29 18:02:04] Loading cached metrics from disk (/home/ryuukk/.local/share/Steam/package/steam_client_metrics.bin)
[2024-08-29 18:02:04] Using the following download hosts for Public, Realm steamglobal
[2024-08-29 18:02:04] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2024-08-29 18:02:04] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2024-08-29 18:02:04] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2024-08-29 18:02:04] Verifying installation...
[2024-08-29 18:02:04] Verification complete
UpdateUI: skip show logo
Steam logging initialized: directory: /home/ryuukk/.local/share/Steam/logs

/usr/share/themes/Arc-Dark/gtk-2.0/main.rc:1090: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Arc-Dark/gtk-2.0/apps.rc:91: error: unexpected identifier 'direction', expected character '}'
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xd8660dc0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xd865f500
CAppInfoCacheReadFromDiskThread took 72 milliseconds to initialize
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 75054
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
src/clientdll/cminterface.cpp (3556) : m_VecAddressWebSocketCMs.Count()
src/clientdll/cminterface.cpp (3556) : m_VecAddressWebSocketCMs.Count()
assert_20240829180206_28.dmp[75157]: Uploading dump (out-of-process)
/tmp/dumps/assert_20240829180206_28.dmp
assert_20240829180206_28.dmp[75157]: Finished uploading minidump (out-of-process): success = yes
assert_20240829180206_28.dmp[75157]: response: CrashID=bp-734ef9e5-430e-4a03-9b64-69cbe2240829
assert_20240829180206_28.dmp[75157]: file ''/tmp/dumps/assert_20240829180206_28.dmp'', upload yes: ''CrashID=bp-734ef9e5-430e-4a03-9b64-69cbe2240829''

```

**Comment by mahlersand** [comment] 2024-08-29 16:06
I have the same issue. Resetting the steam runtime using `steam-runtime --reset` does NOT help. The client is stuck at the login screen (Post sign-in).

**Comment by Rosentti** [comment] 2024-08-29 16:07
Oops. Filed a duplicate issue :D
I'll copy my findings here.

#### Your system information

* Steam client version (build number or date): 1724878532
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?:  Families Beta
* Have you checked for system updates?: No
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16801888/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Steam does not get past logging in.
Websocket CMs are gone, and the linux client seemingly does not support anything else.
This can be confirmed by visiting https://api.steampowered.com/ISteamDirectory/GetCMListForConnect/v1/?cellid=5&cmtype=websockets, which results in "Internal Server Error", or not specifying a filter results in only netfilter CMs. 
The cell does not seem to matter, they are gone globally. 

#### Steps for reproducing this issue:

1. Try to launch steam.
2. Permanently stuck here
![image](https://github.com/user-attachments/assets/2cc0c546-47e2-4520-82bf-ab2213488cfc)

**Comment by kisak-valve** [comment] 2024-08-29 16:09
Until this gets looked at closer, starting Steam with `-tcp` might workaround the issue.

**Comment by kattjevfel** [comment] 2024-08-29 16:10
`steam -tcp` workaround works for me, hope this gets fixed for real soon

**Comment by JStrategic** [comment] 2024-08-29 16:14
having the same issue!

**Comment by Tannenfels** [comment] 2024-08-29 16:16
> `steam -tcp` workaround works for me, hope this gets fixed for real soon

It starts, true, but now my Steam Clowd is unavailable.

**Comment by prplwtf** [comment] 2024-08-29 16:17
Same issue over here as well! Tried multiple devices, happening on both my laptop and desktop. (both running Arch Linux and Hyprland, different configurations)

**Comment by sketchbuch** [comment] 2024-08-29 16:18
Same. Ubuntu 24.04 Steam Flatpak 1.0.0.79

**Comment by midnightcatwalk** [comment] 2024-08-29 16:19
Seems to be a Linux-wide issue. Affecting Decks as well.

**Comment by Rosentti** [comment] 2024-08-29 16:31
Websocket servers seem to be back.

**Comment by Foxreef** [comment] 2024-08-29 16:38
Had the same issue, also on arch. Found some old [community post](https://steamcommunity.com/discussions/forum/1/611696927927659240/) where someone said flushing the DNS cache could help and it worked for me

**Comment by etojuice** [comment] 2024-08-29 16:43
Steamcmd was also affected. Seems to be working now.

**Comment by blazux** [comment] 2024-08-29 16:46
Got the same problem, steam -tcp did work.

**Comment by LiamDawe** [comment] 2024-08-29 16:52
Seems it was a wider Steam server outage, should be fine now?

**Comment by kisak-valve** [comment] 2024-09-02 13:25
Closing as fixed server side.

**Closed by kisak-valve** 2024-09-02 13:25 UTC
Labels: Need Retest
