### ISSUE TITLE
[GPU Acceleration] Steam Client Black/Gray Windows After Enabling GPU Acceleration

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/steam-for-linux#6549] opened 2019-10-01 03:23 UTC
#### Your system information

* Steam client version (build number or date): 
![Screenshot_2019-09-30_22-13-56](https://user-images.githubusercontent.com/6024315/65931521-a5beef80-e3cf-11e9-98ad-c41a1929406e.png)
System Info:  https://gist.github.com/nightsky30/1d4d2c90396bf186ebf7cde7770422b6
* Distribution (e.g. Ubuntu): Xubuntu 19.10
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Enable GPU Acceleration voluntarily or be forced to use it after the most recent Steam Client Beta update, and within minutes I'm experiencing black/gray screens and instances where the library fails to load items properly.

With the black screens the entire client window is blacked out including child windows such as the friends list window.

![Screenshot_2019-09-30_21-59-41](https://user-images.githubusercontent.com/6024315/65931552-c5eeae80-e3cf-11e9-91ac-ddd538295b61.png)

I closed these windows and reopened them using the taskbar icon and that seemed to fix the black screen temporarily.

Then I got a gray, unpopulated window in the client where the steam web browser normally displays the store, library, etc.  The library should have been displayed.

![Screenshot_2019-09-30_22-00-27](https://user-images.githubusercontent.com/6024315/65931568-dbfc6f00-e3cf-11e9-8704-f9bebfc8af04.png)

Then I clicked on something in the gray Library window.  It did something but didn't render the click or anything in the library.

Then I clicked the Store.  The store rendered properly.

Then I clicked Library again.  And it showed the news feed for one of my games (from when i clicked in the gray box).  But I cannot close the feed or interact with it.  It then disappeared while I wasn't looking, and now the library is not responsive.  Every time I open the library I get a random feed from a game that doesn't seem to respond to clicks.  It is really broken.

![Screenshot_2019-09-30_22-27-36](https://user-images.githubusercontent.com/6024315/65932014-95a80f80-e3d1-11e9-8687-cec4b9f1a33b.png)

**GPU Acceleration still seems very glitchy...though admittedly this is an opt-in Beta**

#### Steps for reproducing this issue:

1. Update to latest Steam Beta with GPU Acceleration enabled.
2. View the Library.
3. Open the Friends List window.
4. Mouse over friends' status.
5. Experience black windows
6. Close black windows
7. Reopen steam windows through taskbar icon.
8. Attempt to view library.
9. Get gray screens.
10. Click in gray screens.
11. Notice no rendering, but mouse indicating stuff was clicked.
12. Load store.
13. Attempt to load library.
14. Notice library loads with feeds pre-rendered and non-interactable.

**Comment by LiamDawe** [comment] 2019-10-01 08:42
I also had a very similar issue. Clicking Home for the Library made Steam quite unresponsive. Collections could be seen although quite unresponsive too and yet the Store page worked fine.

Reloading Steam seems to have fixed it though.

**Comment by KibaGasteiz** [comment] 2019-10-01 11:47
The same is happening to me, but instead of grey screens i get frozen views of what i was seeing last time, closing the window and reopening library through the tray icon like OP said moves the view to whatever i've clicked while frozen, but then again it's frozen and can't do anything.
So, frozen, i click on a game, nothing happens, close the window, reopen it, the game info is opened now, i click in another game, nothing happens, it's frozen again.

**Comment by adojck** [comment] 2019-10-02 10:55
I have same problem like @KibaGasteiz described. I also have same GPU drivers version: NVIDIA **435.21**

Maybe it is something related to NVIDIA drivers?

**Comment by af7567** [comment] 2019-10-02 11:03
Same problem also with nvidia 435.21 drivers. The main steam window and the friends list are going grey for me and the only way to fix it is to close the windows and re-open them. Resizing does show the window contents but then it goes back to grey after resizing.
I can still close the steam windows by clicking the X in the top right corner even though I can't see it.

**Comment by Myrddin-Wyllt** [comment] 2019-10-03 17:39
I don't have this issue on my AMD machines:
- RX 480
- Ryzen 7 2700U

**Comment by peon501** [comment] 2019-10-07 00:30
I closed my issue, cuz its the same problem.

**Comment by psymin** [comment] 2019-10-08 20:42
Same issue here.

https://gist.github.com/psymin/6035bebe694974e85352648d1a3414fe

![steam-beta-friends](https://user-images.githubusercontent.com/326578/66431690-b5df5c00-e9d9-11e9-9d28-d3b8549466a2.png)

Launch client, right click a friend, view profile.  Grey friend's list.

Gentoo, x86_64, nVidia (435.21), KDE, Steam Client beta (1570492308)

Restarting client resolves issue temporarily.

**Comment by GuzTech** [comment] 2019-10-12 17:57
I have the same issue as @KibaGasteiz. Before running a game, the library works just fine. After I have run a game and quit, then the library screen just displays the last contents of the window. For example, when I scroll through my list of games, the UI doesn't update. But if I the go to Store and back to Library, then it renders the "updated" screen as if it did process my mouse wheel scroll event.

System information:
https://gist.github.com/GuzTech/fc9ada8531cb5ed6ef1f108340c0be4f

**Comment by anohren** [comment] 2019-11-04 15:35
> Disabling gpu acceleration for web views resolves the issue.

That didn't work for me. It's still all black. Except the Manage Downloads screen.

**Comment by nightsky30** [comment] 2019-12-22 19:18
After re-enabling GPU Acceleration for web views I cannot seem to reproduce the issue with the latest Steam Beta client and NVIDIA 440.44 drivers.

Can anyone else confirm?

**Comment by af7567** [comment] 2019-12-22 21:02
It seems to be OK for me now too. I also have the 440.44 nvidia drivers. I didn't realise but I already had GPU acceleration enabled again so it must have auto enabled in a previous steam update?

**Comment by KibaGasteiz** [comment] 2019-12-23 02:41
The client runs fine for me now too.

**Comment by LiamDawe** [comment] 2019-12-23 10:55
I'm on the Steam beta, with NVIDIA 440.36 and can also confirm when turning back GPU acceleration on and restarting Steam the issue is gone.

**Comment by anohren** [comment] 2019-12-28 21:02
I enabled Beta updates, relaunched and updated. I enabled GPU accelerated rendering and relaunched.

Still blackness. No improvement with or without GPU acceleration.

**Comment by KibaGasteiz** [comment] 2019-12-29 15:59
> I enabled Beta updates, relaunched and updated. I enabled GPU accelerated rendering and relaunched.
> 
> Still blackness. No improvement with or without GPU acceleration.

I had no issues in the last week, what's your specs, distro and driver?

**Comment by anohren** [comment] 2019-12-30 00:44
> what's your specs, distro and driver?

I have a Geforce GTX 550 Ti with 390 drivers on Ubuntu 19.10 64 bit

**Comment by KibaGasteiz** [comment] 2019-12-30 02:33
> > what's your specs, distro and driver?
> 
> I have a Geforce GTX 550 Ti with 390 drivers on Ubuntu 19.10 64 bit

You should update to 440.44 drivers:
`sudo add-apt-repository ppa:graphics-drivers/ppa
sudo apt-get update`
Then search and install "nvidia-graphics-drivers-440"

**Comment by kisak-valve** [comment] 2019-12-30 02:47
Hello @KibaGasteiz, @anohren should not update to the 440 series driver because the nVidia 550 Ti is a Fermi generation card and that generation is currently in legacy support by the 390 series. Newer driver series do not support that card.

**Comment by anohren** [comment] 2019-12-30 02:59
Is the problem mainly with the drivers? If so I guess I can't expect it to be fixed if nvidia doesn't update them anymore.

**Comment by KibaGasteiz** [comment] 2019-12-30 10:34
> Hello @KibaGasteiz, @anohren should not update to the 440 series driver because the nVidia 550 Ti is a Fermi generation card and that generation is currently in legacy support by the 390 series. Newer driver series do not support that card.

Oh sorry, and shouldn't he use the 440.108? https://www.gamingonlinux.com/articles/if-you-have-an-old-nvidia-8-or-9-series-gpu-theres-a-new-linux-driver-update-out-for-you.15674

**Comment by anohren** [comment] 2019-12-30 13:57
> Oh sorry, and shouldn't he use the 440.108?

Well, I'm a bit confused. Did you mean 340?

All I know is that the Steam client is unusable with or without GPU acceleration, with 390 and with Nouveau. Ubuntu offered me a lower numbered driver though, perhaps that's the one you're referring to. I'll give it a try.

**Comment by KibaGasteiz** [comment] 2019-12-30 13:59
> > Oh sorry, and shouldn't he use the 440.108?
> 
> Well, I'm a bit confused. Did you mean 340?
> 
> All I know is that the Steam client is unusable with or without GPU acceleration, with 390 and with Nouveau. Ubuntu offered me a lower numbered driver though, perhaps that's the one you're referring to. I'll give it a try.

Yes, 340.108, i'm very confused with all this branches from nvidia, sorry.

**Comment by anohren** [comment] 2019-12-30 16:25
Ubuntu offered 340.107. Steam is still broken with that one. I'll see if I can install the linked one, but it looks like a lot of work.

**Comment by anohren** [comment] 2019-12-31 15:32
The install instructions for the linked driver were not clear enough for me to install them, sorry. I wish you good luck unbreaking the steam client.

**Comment by kisak-valve** [comment] 2022-02-04 19:53
Hello, is anyone still experiencing this issue on an up to date system? It sounds like this issue was due to driver defects in legacy series of the NVIDIA driver.

**Comment by LiamDawe** [comment] 2022-02-04 21:06
Nah never have an issue anymore.

**Comment by anohren** [comment] 2022-02-04 22:50
My issue turned out to be missing CMPXCHG128B, so not relevant to this issue.

**Comment by peon501** [comment] 2022-02-07 09:55
That was not only on nvidia, I had this problem on old intel integrated graphics (on old ProBook 6560b)
disabling gpu acceleration fixed that for me.
Didnt used it in a while, so I dont know if thats fixed or not.

**Comment by kisak-valve** [comment] 2022-03-12 01:22
Thanks for retesting. @peon501, if you manage to reproduce a similar issue with an up to date system, please open an new issue report to ponder that particular system further.

Closing as outdated.

**Closed by kisak-valve** 2022-03-12 01:22 UTC
Labels: Steam client, Need Retest, Web Component
