### ISSUE TITLE
Csgo wont start: error while loading shared libraries

### ISSUE THREAD

**Issue by 0ttoman** [ValveSoftware/steam-for-linux#4748] opened 2016-12-13 11:52 UTC
Hello guys,
I run csgo under Fedora 25 on an t460 with intel graphics and got the following errors after the new csgo update..

I opened steam in the console and these was the output after I started the game
```
Game update: AppID 730 "Counter-Strike: Global Offensive", ProcID 17456, IP 0.0.0.0:0
ERROR: ld.so: object '/home/name/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/name/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 17458 != 17457, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/name/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 17456 for game ID 730

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:17262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
ERROR: ld.so: object '/home/name/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 17457 for game ID 730
>>> Adding process 17459 for game ID 730
>>> Adding process 17460 for game ID 730
Installing breakpad exception handler for appid(gameoverlayui)/version(20161013004725)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
/home/name/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/csgo.sh: Zeile 64: 17460 Segmentation fault      (Speicherabzug geschrieben) ${DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 730 "Counter-Strike: Global Offensive", ProcID 17460 
No cached sticky mapping in ActivateActionSet.Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/65-0-lohit-bengali.conf", line 32: unknown element "langset"
Fontconfig warning: "/etc/fonts/conf.d/69-gnu-free-sans.conf", line 24: unknown element "langset"
Fontconfig warning: "/etc/fonts/conf.d/69-gnu-free-serif.conf", line 24: unknown element "langset"
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
```

I tried to start the game directly..
```
$ ~/.steam/steam/steamapps/common/Counter-Strike\ Global\ Offensive/csgo.sh 
SDL video target is 'x11'
SDL failed to create GL compatibility profile (whichProfile=0!
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system DOES NOT support the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GL_ARB_buffer_storage.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
 failed to dlopen /home/name/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/bin/engine_client.so error=/home/name/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/bin/engine_client.so: wrong ELF class: ELFCLASS32
/home/name/.steam/steam/steamapps/common/Counter-Strike Global Offensive/csgo.sh: Zeile 64: 17715 Segmentation fault      (Speicherabzug geschrieben) ${DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
```
and when I then ran 
`$ DEBUGGER=gdb ./.steam/steam/steamapps/common/Counter-Strike\ Global\ Offensive/csgo.sh `
I got:
```
Reading symbols from /home/name/.steam/steam/steamapps/common/Counter-Strike Global Offensive/csgo_linux64...Missing separate debuginfo for /home/name/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/csgo_linux64
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/48/5f0266bbd4745ba01c29ed890b2b195fa38639.debug
(no debugging symbols found)...done.
Breakpoint 1 at 0x400654
Missing separate debuginfo for /home/name/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/linux64/libtcmalloc_minimal.so.0
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/ca/916378ae7ccebea645b2fbc5512c9ed37571ab.debug
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Breakpoint 1, 0x0000000000400654 in main ()
Argument list to give program being debugged when it is started is "-game csgo".
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.24-3.fc25.x86_64 libgcc-6.2.1-2.fc25.x86_64 libstdc++-6.2.1-2.fc25.x86_64
```
'csgo_linux64' itselft says:
```
./.steam/steam/steamapps/common/Counter-Strike Global Offensive/csgo_linux64: error while loading shared libraries: libtcmalloc_minimal.so.0: cannot open shared object file: No such file or directory
```

Note that csgo ran on this system some days ago, between that I had a kernel update, installed some programs and the new sound update in csgo came in.
I already verified the caches and tried a reinstall. I'm not opt-in into any beta and am on the latest stable fedora version.

the missing libraries are in the bin ordner as expected.
the steam ui itself doesn't show an error at all

what can I try next / what can I test for so this 'maybe bug' can be fixed?

my system Information:
```

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    CPU Family:  0x6
    CPU Model:  0x4e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  2800 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Fedora release 25 (Twenty Five)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.8.12-300.fc25.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11900000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2016-09-02
    
Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 

    Driver Version:  3.0 Mesa 13.0.2
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x1916
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 12,13" x 6,81"  (13,90" diag)
                                            30,8cm x 17,3cm  (35,3cm diag)
    Primary VRAM Not Detected
    
Sound card:
    Audio device: Realtek ALC293
    
Memory:
    RAM:  15481 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  239984 Mb
    Largest Free Hard Disk Block:  117457 Mb
    VR Headset: None detected
    
Recent Failure Reports:
    
```

**Comment by Tele42** [comment] 2016-12-13 13:54
Duplicate of https://github.com/ValveSoftware/csgo-osx-linux/issues/1249.

**Comment by gdrewb-valve** [comment] 2016-12-13 17:13
Closing duplicate.

**Closed by gdrewb-valve** 2016-12-13 17:13 UTC
Labels: MOVED: Counter‐Strike, reviewed
