### ISSUE TITLE
occasional Steam crash while playing Dota

### ISSUE THREAD

**Issue by mbenlioglu** [ValveSoftware/steam-for-linux#8253] opened 2021-11-23 02:57 UTC
#### Your system information

* Steam client version (build number or date):  
  * Built: Nov 19, 2021 at 20:59:59; Steam Package Version: 1637358733
* Distribution (e.g. Ubuntu): Ubuntu 21.10 (was also present in LTS)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

**Other:**

* CPU/GPU: AMD Ryzen 9 4900HS / NVIDIA RTX 2060 Max-Q
* Driver versions:
  * Nvidia: 495.44
  * Mesa: 21.2.2
  * X.org: 2:1.20.13-1ubuntu1
  * DE: GNOME Shell 40.5

#### Please describe your issue in as much detail as possible:

Steam client crashes in the background while playing games. I mainly play Dota 2, so this happened during matches. Steam crashes, with SEGV and subsequently Dota 2 freezes and has to be killed (since it cannot communicate with steam).

The issue is not frequent, but I've encountered it about 5-10 times since the beginning of this year.

I cannot pinpoint if there's a specific sequence of actions to trigger this crash, as it seems to happen randomly. Unfortunately, there are no debug symbols with the client, so backtrace output is useless. You can find the coredumps of the most recent crash (today) [here](https://drive.google.com/file/d/1XdTGejoq_Z7ga-4yOTGx_bY7rObLZM0R/view?usp=sharing). (too big to directly attach ~130 MB)

<details>
  <summary>Sha256 checksum</summary>

```
f71689c5b86ad3836b9f35f3b42591d62d9ea32963a6696c0790f9725482b6be  coredumps.tar.gz
```
</details>

#### Steps for reproducing this issue:

Happens randomly, while playing games.

**Comment by kisak-valve** [comment] 2021-11-23 13:37
Possible duplicate of #6318.

**Comment by TTimo** [comment] 2021-11-29 22:44
I couldn't extract anything useful out of that crash dump unfortunately. If the Steam client is writing minidumps (to /tmp/dumps), considering uploading those (or passing the crash ids for the ones that get uploaded)

**Comment by FagSoft** [comment] 2021-11-30 01:44
I recommend checking out issue #8214. The debugging steps I did could help shed some light on the issue you have.

**Comment by TTimo** [comment] 2021-11-30 03:32
very little useful info in the crash dump, but enough that it doesn't look like a runaway memory allocation problem - eg not #8214

**Comment by mbenlioglu** [comment] 2021-11-30 03:54
I've rebooted since the last crash, so `/tmp/dumps` is currently empty. I'll make sure to check it after the next one. Other than that, not sure how to gather more useful information. Raw coredumps out of `coredumpctl` are not too helpful since all the symbols are n/a

**Comment by drogeek** [comment] 2021-12-04 16:21
> Possible duplicate of #6318.

it's actually a duplicate of [#8071](https://github.com/ValveSoftware/steam-for-linux/issues/8071) which was closed although still happening to me (which is why I'm here commenting).
It happens both on my laptop running Ubuntu 21.10 with nvidia proprietary drivers and on my desktop running Ubuntu 20.04 LTS with latest mesa (AMD GPU).
Same behavior as described by @mbenlioglu

**Comment by ex0z3** [comment] 2021-12-04 19:20
Same problem here, random crashes while playing Dota 2, dmp attached
Arch, prop NVidia drivers (495.44)
[crash_20211204203706_62.zip](https://github.com/ValveSoftware/steam-for-linux/files/7654518/crash_20211204203706_62.zip)

**Comment by drogeek** [comment] 2021-12-04 22:31
I got this at some point

```
src/public/tier1/utlsymbol.h (457) : Symbol table grew beyond unsigned short.  Time to upgrade UtlSymId_t for the symbol type or look for unnecessary spam in the tables.
src/public/tier1/utlsymbol.h (457) : Symbol table grew beyond unsigned short.  Time to upgrade UtlSymId_t for the symbol type or look for unnecessary spam in the tables.
src/public/tier1/utlsymbol.h (457) : Fatal assert; application exiting
src/public/tier1/utlsymbol.h (457) : Fatal assert; application exiting
Installing breakpad exception handler for appid(steam)/version(1638464786)
assert_20211204192831_59.dmp[27594]: Uploading dump (out-of-process)
/tmp/dumps/assert_20211204192831_59.dmp
_ExitOnFatalAssert
```
/tmp/dumps/assert_20211204192831_59.dmp

**Comment by mbenlioglu** [comment] 2021-12-11 15:02
> If the Steam client is writing minidumps (to /tmp/dumps), considering uploading those (or passing the crash ids for the ones that get uploaded)

@TTimo is there a name convention for steam logs? Crash happened again today and `/tmp/dumps` only has a couple of `assert_<timestamp>_<number>.dmp` and  a `crash_<timestamp>_<number>.dmp` files along with
[this](https://github.com/ValveSoftware/steam-for-linux/files/7697249/bruce_log.txt) file, which appears to be the index of those files.

**Comment by drogeek** [comment] 2021-12-11 16:49
> > If the Steam client is writing minidumps (to /tmp/dumps), considering uploading those (or passing the crash ids for the ones that get uploaded)
> 
> I've confirmed they are Steam dumps. This part is no longer relevant
> 
> Edit: Those are indeed mindump files belonging to steam. I've briefly inspected them with lldb, the issue could be caused by the game overlay. @TTimo [minidumps.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/7697375/minidumps.tar.gz)

I've disabled the game overlay, still happening though

**Comment by mbenlioglu** [comment] 2021-12-11 18:20
Yeah, could be something else. Can't tell with the release version. Internal builds may use the dumps to pinpoint exact place, hopefully. 

Also,  this crash belongs to the latest version of the steam.
![Screenshot from 2021-12-11 21-19-39](https://user-images.githubusercontent.com/18167175/145687354-61a59aa4-160e-4b74-abc0-a67840c4fb59.png)

**Comment by mbenlioglu** [comment] 2021-12-13 13:59
Another crash today, this time no games open. After I've recently closed Dota 2. (Although closing dota is not graceful, and I have to `killall -9 dota2` every time. Described in this issue: https://github.com/ValveSoftware/Dota-2/issues/1992 ) 

[minidumps.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/7704329/minidumps.tar.gz)

**Comment by TTimo** [comment] 2021-12-13 18:06
@mbenlioglu thanks, the latest minidumps confirm this is the symbol table crash also reported at https://github.com/ValveSoftware/steam-for-linux/issues/8290

**Comment by mbenlioglu** [comment] 2021-12-13 20:19
Glad to help! I wanted to add that, today, it's been crashing consistently every time I close off Dota 2 (fresh installation + `-gl` launch option to bypass https://github.com/ValveSoftware/Dota-2/issues/1992). So it made me suspect that the latest crash dumps I provided versus this one: https://github.com/ValveSoftware/steam-for-linux/issues/8253#issuecomment-991674132 might have different causes.

**Comment by danginsburg** [comment] 2021-12-14 00:42
A fix for this will be in the next Steam Beta update.

**Comment by webaake** [comment] 2021-12-14 04:13
Nice with a fix! Thanks guys! I've sort of narrowed it down to if I go to "Discussion" in Steam it then crashes almost immediately. But the fix is coming, so...

Thanks again!

**Comment by Mario156090** [comment] 2021-12-20 02:35
This is happening me. When I play DOTA2 this is freezing randomly and I should to kill the Game and re Open.

I use cinnamon DE and Nvidia Rtx 3060 Mobile with the last drivers 495.X.

**Comment by drogeek** [comment] 2021-12-20 09:13
Well I definitely got a Steam update after this message came up, and yet still happening

**Comment by Mario156090** [comment] 2021-12-20 13:01
> Well I definitely got a Steam update after this message came up, and yet still happening

Beta version?

**Comment by drogeek** [comment] 2021-12-20 14:24
Yes, when I got to settings/account I see `Steam Beta Update`

**Comment by Mario156090** [comment] 2021-12-21 15:02
¿Aún no hay solución?

**Comment by Mario156090** [comment] 2021-12-22 20:23
I friends, test flatpak steam version. Dota can plays correctly.

**Comment by webaake** [comment] 2021-12-24 09:50
Working okay now, since 16 december update. ( I think it is 16 dec).

**Comment by mbenlioglu** [comment] 2021-12-25 00:52
Issue still present on non-beta branch, waiting for beta to merge the main version.

**Comment by Mario156090** [comment] 2021-12-25 01:03
I don't understand, who is notice us if the bug will be fixed or no?

**Comment by drogeek** [comment] 2022-01-01 10:45
still happens every day for me on `steam beta update`, I just got banned because of it on dota2…
why is the steam program such a strong dependency for the game in the first place anyway? It's weird that the games freeze when steam crashes, it shouldn't be the case. Wouldn't that make sense to have a background service, independent from the Steam app itself that handles things that are necessary for the games? I mean, I don't see why Steam is necessary there, it should be simply a launcher or something.

**Comment by TTimo** [comment] 2022-01-01 19:02
Hello @drogeek, do you have updated crash ids and minidumps you can provide against current steam beta? You may be experiencing additional crashes than the fix made in #8290

**Comment by Mario156090** [comment] 2022-01-01 19:57
> Hello @drogeek, do you have updated crash ids and minidumps you can provide against current steam beta? You may be experiencing additional crashes than the fix made in #8290 

Is this problem fixed?

**Comment by mbenlioglu** [comment] 2022-01-02 01:05
I've updated to beta version today. I'll provide further info if a crash occurs again.

**Comment by Mario156090** [comment] 2022-01-11 16:10
Inside arch and arch distribution based I found a workaround:

install steam-native-runtime package and steam package and this is fixed, DOTA 2 does not close nevermore.
![image](https://user-images.githubusercontent.com/47507975/148979035-327f1ee2-ae35-408d-83bf-b737dcf297f5.png)

**Comment by mbenlioglu** [comment] 2022-01-12 22:48
Crash still happens in the latest beta version of the steam. I'm attaching the latest minidumps. @TTimo

[minidumps.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/7858458/minidumps.tar.gz)

**Comment by Mario156090** [comment] 2022-01-12 22:51
> Crash still happens in the latest beta version of the steam. I'm attaching the latest minidumps. @TTimo
> 
> [minidumps.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/7858458/minidumps.tar.gz)
>  

No, it's we're fixed for me.

What steamd build number have You?

**Comment by mbenlioglu** [comment] 2022-01-12 22:55
> No, it's we're fixed for me.

Crash happens randomly, how exactly did you verify that it's fixed?

> What steamd build number have You?

![image](https://user-images.githubusercontent.com/18167175/149236068-ddc0c81d-603e-44aa-ad4c-70390387c3fd.png)

**Comment by Mario156090** [comment] 2022-01-12 23:00
> > No, it's we're fixed for me.
> 
> Crash happens randomly, how exactly did you verify that it's fixed?
> 
> > What steamd build number have You?
> 
> ![image](https://user-images.githubusercontent.com/18167175/149236068-ddc0c81d-603e-44aa-ad4c-70390387c3fd.png)
> 

I'm using Arch Linux, so I disable beta version and crashed appears newly, bur when I rentable beta crash does not appears nevermore.

**Comment by mbenlioglu** [comment] 2022-01-12 23:06
Well this is the latest beta version and the crash happened less than an hour ago

**Comment by Mario156090** [comment] 2022-01-13 00:21
> Well this is the latest beta version and the crash happened less than an hour ago

That's so bad, can You test with nvidia 4.70 driver?

**Comment by mbenlioglu** [comment] 2022-01-13 12:37
I'm using the latest nvidia drivers for development purposes, so rolling back driver versions is impractical for me. Yesterday's crash happened with 4.95, but I've upgraded it to 5.10 today, so I'll see if that improves the situation. In the meantime, it's confirmed that the issue still persists with the latest beta version & nvidia 4.95 drivers.

**Comment by Mario156090** [comment] 2022-01-13 12:44
> I'm using the latest nvidia drivers for development purposes, so rolling back driver versions is impractical for me. Yesterday's crash happened with 4.95, but I've upgraded it to 5.10 today, so I'll see if that improves the situation. In the meantime, it's confirmed that the issue still persists with the latest beta version & nvidia 4.95 drivers. 

Oh ok, well for me works with this combination:

Steam beta
Nvidia 470 drivers

**Comment by mbenlioglu** [comment] 2022-02-05 00:11
Thanks @TTimo glad to help. I got another crash today. With Nvidia 510.47.03 and Steam built on Feb 3, 2022 at 00:45:52 & package versions: 1643850988

[minidumps.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/8006150/minidumps.tar.gz)

**Comment by kisak-valve** [comment] 2022-02-05 00:16
For reference, the asserts are DUMP_REQUESTED in crashhandler.so, and the crash marked minidump is a SIGSEGV coming from steamservice.so.

**Comment by mbenlioglu** [comment] 2022-04-17 23:38
Since the last update, number of crashes decreased significantly. I've had 2 crashes since February. One of the causes definitely resolved, but it seems there's still one more. This one happened today, attaching dumps.

![Screenshot from 2022-04-18 02-35-17](https://user-images.githubusercontent.com/18167175/163736237-2b5cc0dd-7bf2-454c-857a-8b2fce672d0d.png)

[minidumps.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/8502634/minidumps.tar.gz)

**Comment by mbenlioglu** [comment] 2022-08-20 16:06
I haven't encountered this issue again for a long time. I'm closing the issue as fixed.

**Comment by mbenlioglu** [comment] 2022-10-29 14:33
This issue is back again after recent patches

**Closed** 2022-10-31 20:30 UTC
Labels: Steam client

**Comment by TTimo** [comment] 2022-10-31 20:32
Please open a new issue, providing up to date logs, crash dump IDs etc. - you have not provided clear indication that we are looking at the same problem (other than "occasional crash").
