### ISSUE TITLE
Steam big picture keeps focus over games with steamcompmgr on Ubuntu

### ISSUE THREAD

**Issue by frioux** [ValveSoftware/steam-for-linux#8055] opened 2021-09-10 15:34 UTC
#### Your system information

* Steam client version (build number or date): Sept 10 2021, at 01:01:56
* Distribution (e.g. Ubuntu):  Ubuntu
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When I try to run a game (at least Outer Wilds but I have only tried a few games) instead of flashing a colored square then starting the game, it's like the game fights with big picture for focus.  The game is running in the background, but I can't play it!

#### Steps for reproducing this issue:

1. Start Big Picture Mode
2. Start Outer Wilds
3. Note that the game is running (with ps or top or whatever) but not in the foreground.

Note: This *doesn't* happen when I start big picture mode from xfce4.  Only when I start big picture (automatically) from steamcompmgr.

**Comment by alkazar** [comment] 2021-09-11 00:48
This issue is essentially a duplicate of #7966

See my comment about a fix/workaround: https://github.com/ValveSoftware/steam-for-linux/issues/7966

**Comment by frioux** [comment] 2021-09-12 15:31
I installed steamcompmgr-plus from source and it resolved the issue for me

**Comment by Plagman** [comment] 2021-09-13 16:08
Let's track this in the other bug since it has the more complete context:

https://github.com/ValveSoftware/steam-for-linux/issues/8055

**Closed by Plagman** 2021-09-13 16:08 UTC
Labels: Big Picture, Window manager, Distro Family: Ubuntu

**Comment by alkazar** [comment] 2021-09-13 16:20
To avoid any confusion I think @Plagman means to say #7966
