### ISSUE TITLE
Fatal Error: Failed to load steamui.so — Apparently without (obvious) reasons

### ISSUE THREAD

**Issue by DDzwiedziu** [ValveSoftware/steam-for-linux#5398] opened 2018-03-01 21:52 UTC
#### Your system information

* Steam client version (build number or date): 1513371133
* Distribution (e.g. Ubuntu): Ubuntu 17.10
* Opted into Steam client beta?: [Yes/No] No [1]
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

_Classical_ expected to run got nothing.
```$ steam               
Running Steam on ubuntu 17.10 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
[2018-03-01 22:37:23] Startup - updater built Dec 15 2017 11:47:44
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2018-03-01 22:37:23] Checking for update on startup
[2018-03-01 22:37:23] Checking for available updates...
[2018-03-01 22:37:24] Download skipped: /client/steam_client_ubuntu12 version 1513371133, installed version 1513371133
[2018-03-01 22:37:24] Nothing to do
[2018-03-01 22:37:24] Verifying installation...
[2018-03-01 22:37:24] Performing checksum verification of executable files
[2018-03-01 22:37:24] Verification complete
```
At this point I see a popup: Fatal Error: Failed to load steamui.so

Tried to install additional libraries: libvdpau1:i386, libva-x11-1:i386, libva1:i386, libdrm2:i386 (not exactly sure about this one). Tried reinstalling the Steam package. Tried removing `~/.steam`, or pinned libraries. No change.

#### Steps for reproducing this issue:

1. ?
2. Update packages on 2018-03-01 [2][3]
3. Launch steam

[1] Tried beta by making a steam.cfg file, did not download the beta citing connection problems.
[2] Current day upgrades
```2018-03-01 19:42:38 upgrade google-chrome-beta:amd64 65.0.3325.88-1 65.0.3325.106-1
2018-03-01 19:42:41 upgrade grub-efi-amd64-signed:amd64 1.85.1+2.02~beta3-4ubuntu7.1 1.85.2+2.02~beta3-4ubuntu7.2
2018-03-01 19:42:42 upgrade grub-efi-amd64:amd64 2.02~beta3-4ubuntu7.1 2.02~beta3-4ubuntu7.2
2018-03-01 19:42:42 upgrade grub-efi-amd64-bin:amd64 2.02~beta3-4ubuntu7.1 2.02~beta3-4ubuntu7.2
2018-03-01 19:42:42 upgrade grub2-common:amd64 2.02~beta3-4ubuntu7.1 2.02~beta3-4ubuntu7.2
2018-03-01 19:42:42 upgrade grub-common:amd64 2.02~beta3-4ubuntu7.1 2.02~beta3-4ubuntu7.2
```
[3] Day earlier upgrades:
```egrep '2018-02-28.*upgrade'  /var/log/dpkg.log.1 
2018-02-28 19:24:26 upgrade ubuntu-drivers-common:amd64 1:0.4.23.1 1:0.4.23.3
2018-02-28 19:24:38 upgrade ubuntu-drivers-common:amd64 1:0.4.23.3 1:0.4.23.3
2018-02-28 19:24:38 upgrade fonts-opensymbol:all 2:102.10+LibO5.4.5-0ubuntu0.17.10.1 2:102.10+LibO5.4.5-0ubuntu0.17.10.4
2018-02-28 19:24:50 upgrade ure:amd64 5.4.5-0ubuntu0.17.10.1 5.4.5-0ubuntu0.17.10.4
2018-02-28 19:24:50 upgrade uno-libs3:amd64 5.4.5-0ubuntu0.17.10.1 5.4.5-0ubuntu0.17.10.4
(...skipped libreoffice upgrades...)
2018-02-28 19:25:17 upgrade python3-uno:amd64 1:5.4.5-0ubuntu0.17.10.1 1:5.4.5-0ubuntu0.17.10.4
(...skipped libreoffice upgrades...)
2018-02-28 22:00:37 upgrade vivaldi-stable:amd64 1.14.1077.50-1 1.14.1077.55-1
```

**Comment by DDzwiedziu** [comment] 2018-03-01 21:58
Not that it was expected but downgrading ubuntu-drivers-common did not help.

**Comment by kisak-valve** [comment] 2018-03-01 22:21
Hello @DDzwiedziu, does `cd ~/.steam/ubuntu12_32/ && ~/.steam/ubuntu12_32/steam-runtime/run.sh ldd steamui.so | grep "not found"` in a terminal output anything?

**Comment by DDzwiedziu** [comment] 2018-03-01 22:39
```
$ cd ~/.steam/ubuntu12_32/ && ~/.steam/ubuntu12_32/steam-runtime/run.sh ldd steamui.so | grep "not found"
./steamui.so: /usr/lib/i386-linux-gnu/libpng12.so.0: version `PNG12_0' not found (required by /home/dzwiedziu/.steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libgdk_pixbuf-2.0.so.0)
./steamui.so: /usr/lib/i386-linux-gnu/libpng12.so.0: version `PNG12_0' not found (required by /home/dzwiedziu/.steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libcairo.so.2)
```
Which I've made myself, because of some wine games testing yesterday...
```
ll /usr/lib/i386-linux-gnu/libpng12.so.0 
lrwxrwxrwx 1 root root 38 lut 28 22:48 /usr/lib/i386-linux-gnu/libpng12.so.0 -> /usr/lib/i386-linux-gnu/libpng16.so.16
```

Still, shouldn't the version in `steam-runtime` directory be used first?

**Comment by kisak-valve** [comment] 2018-03-01 22:57
By default, the steam runtime is supposed to use system libraries if they are newer than the steam runtime.

Libpng12.so.0 and libpng16.so.16 are ABI-incompatible and you should not symlink one to the other. If you really need to have that library mangled, you can try manually pinning the steam runtime variant with: `ln -s ~/.steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libpng12.so.0 ~/.steam/ubuntu12_32/steam-runtime/pinned_libs_32/libpng12.so.0`

**Comment by Sworddragon** [comment] 2018-03-24 20:05
The crash/steamui.so claim appears if at least libdrm2:i386 is missing (which is usually a default on a 64 bit Linux with an upstream Steam). Normally I would expect upstream Steam to have all needed libraries statically shipped with but maybe this is not possible for some libraries due to license issues or maybe this is just a regression.

**Comment by prime-evil** [comment] 2018-04-26 09:53
It may indeed be a problem with lack of 32-bit DRM support. If I run LIBGL_DEBUG=verbose steam on a system with similar issues, I get the following response: 
 
Running Steam on linuxmint 18.3 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
[2018-04-26 19:05:34] Startup - updater built Apr  2 2018 15:23:43
[2018-04-26 19:05:34] Verifying installation...
[2018-04-26 19:06:32] Verification complete
Refresh rate: 0
Refresh rate: 0
html_chrome.cpp (3238) : Assertion Failed: WideVine CDN download failure 0

WideVine is Google's digital rights management platform.

**Comment by kisak-valve** [comment] 2020-06-12 18:33
Closing because the original issue was resolved. Symlinking between ABI incompatible libraries will give most software a bad day.

**Closed by kisak-valve** 2020-06-12 18:33 UTC
Labels: Distro Family: Ubuntu
