### ISSUE TITLE
Character display bug for players' name

### ISSUE THREAD

**Issue by MightyCreak** [ValveSoftware/steam-for-linux#4123] opened 2015-11-08 19:02 UTC
_Disclaimer: Running Fedora 23 and using the [libgcc hack](https://wiki.archlinux.org/index.php/Steam#Steam_runtime_issues) to have full graphics performances._

Here is the glitches (look at the texts on top of the heroes):
![dota_text_bug_playing](https://cloud.githubusercontent.com/assets/6382548/11021993/19612266-8621-11e5-9f29-d07c32d008af.png)
![dota_text_bug_spectating](https://cloud.githubusercontent.com/assets/6382548/11021995/1f4442bc-8621-11e5-86fa-a2a6687fde1a.png)

I just upgraded from Fedora 22 to Fedora 23.
On F22, it was working without any problem, not on F23 anymore.

If you need any other information, please ask.

**Comment by Tele42** [comment] 2015-11-08 20:20
Duplicate of https://github.com/ValveSoftware/Dota-2/issues/488.

**Comment by gdrewb-valve** [comment] 2015-11-09 17:43
Closing duplicate.

**Closed by gdrewb-valve** 2015-11-09 17:43 UTC
Labels: duplicate, reviewed
