### ISSUE TITLE
Unable to start in Ubuntu 16.04

### ISSUE THREAD

**Issue by bpearson** [ValveSoftware/steam-for-linux#4433] opened 2016-05-01 00:54 UTC
I tried to install the steam client on Ubuntu 16.04 but it always returns with "free(): invalid pointer: 0xffbd36d0". I have tried what workarounds (like prefixing Steam with environment variables etc) I could find here but with no change. Unable to start or play on Steam at all. Any advice?

**Comment by gdrewb-valve** [comment] 2016-05-01 06:31
Likely duplicate of the other 16.04 startup issues here.

**Comment by bpearson** [comment] 2016-05-15 01:13
Any movement with this?

**Comment by TruboXL** [comment] 2016-05-21 04:17
@bpearson `Exec=env LC_ALL=C steam $@`?

Can you tell me where you get the idea of `LC_ALL=C`?

**Comment by bpearson** [comment] 2016-05-21 04:51
I found it here... https://wiki.ubuntu.com/Valve ... apparently it is from a missing locale?

**Comment by gowthamsadasivam** [comment] 2016-05-21 13:49
@bpearson Thanks for the workaround. Just saved me lot of time :+1: 

**I was getting the following error:**

`Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
awk: /home/USERNAME/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.6)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "unity-gtk-module"
Installing breakpad exception handler for appid(steam)/version(1461972496)
[0521/190602:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
[0521/190602:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20160429221814)
Installing breakpad exception handler for appid(steamwebhelper)/version(1461968294)
[0521/190602:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
Installing breakpad exception handler for appid(steamwebhelper)/version(20160429221814)
Installing breakpad exception handler for appid(steamwebhelper)/version(1461972496)
Installing breakpad exception handler for appid(steamwebhelper)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Created shared memory when not owner SteamController_Shared_mem
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
assert_20160521190600_1.dmp[12105]: Uploading dump (out-of-process)
/tmp/dumps/assert_20160521190600_1.dmp
/home/USERNAME/.local/share/Steam/steam.sh: line 756: 12050 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
assert_20160521190600_1.dmp[12105]: Finished uploading minidump (out-of-process): success = yes`

## **Now, as from your comment above,**
Running `Exec=env LC_ALL=C steam $@` Makes it work now.. :)

**Comment by murateca** [comment] 2017-02-07 22:55
@bpearson `Exec=env LC_ALL=C steam $@` solves the problem. Strange that i've been searching for 2 days yet couldnt find that simple solution. Thanks a lot.

**Comment by kisak-valve** [comment] 2019-05-10 17:08
Hello, does anyone still need this workaround to start Steam? If you are, what does `locale -a` give you?

**Comment by kisak-valve** [comment] 2019-06-15 22:19
Closing pending feedback.

**Closed by kisak-valve** 2019-06-15 22:19 UTC
Labels: Need Retest, reviewed
