### ISSUE TITLE
Magicka 2 Linux x86-64 crashes on start with error messages involving libssl_conf.so

### ISSUE THREAD

**Issue by nipsy** [ValveSoftware/steam-for-linux#6014] opened 2019-01-08 00:53 UTC
#### Your system information

* Steam client version (build number or date): Dec 14 2018, at 22:19:08
* Distribution (e.g. Ubuntu): Debian buster x86-64
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Trying to start Magicka 2 for Linux (64-bit version on a 64-bit distribution) fails.  While most of the necessary files/symlinks are present in ~/.steam/ubuntu12_32/steam-runtime/amd64/... there seems to be a critical one missing.  I expected a natively available Linux game to start without needing to do anything extra.

I've also included a run from the CLI using the necessary Steam runtime wrapper showing the actual reason for the crash (missing libssl_conf.so) at:
https://gist.github.com/nipsy/b3b4e2d315e3300445410919ff800080

#### Steps for reproducing this issue:

1. Install Magicka 2 under Steam on my 64-bit Linux distribution.
2. Click Play button.
3. Screen goes dark like the game is trying to start.
4. Application crashes and returns to Steam window.

#### Steps for fixing
A temporary solution if Valve cannot fix this is:

```
ln -s ~/.steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libssl.so.1.0.0 ~/.steam/steam/steamapps/common/Magicka\ 2/engine/libssl_conf.so
```

which will create a link in a location that will fix the problem at least.  Running from the CLI or using the Play button via the Steam UI both work correctly after doing this.

Ideally, an additional symlink would be created in ~/.steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu, but I'm unsure if this would negatively impact other games.

**Comment by nipsy** [comment] 2019-01-08 00:57
Humorously enough, I found the solution to this via another Paradox Interactive Linux game at failing to start correctly at:
https://forum.paradoxplaza.com/forum/index.php?threads/surviving-mars-linux-crash-on-startup-solved.1125237/

**Comment by nipsy** [comment] 2019-01-08 00:58
Humorously enough, I found the solution to this via another Paradox Interactive Linux game failing to start correctly at:
https://forum.paradoxplaza.com/forum/index.php?threads/surviving-mars-linux-crash-on-startup-solved.1125237/

**Comment by nipsy** [comment] 2019-01-08 01:03
#4837 contains a comment about this very problem also.  I'm linking from that bug report to this one also.

**Comment by kisak-valve** [comment] 2019-01-08 01:19
Hello @nipsy, for sanity sake, please also try `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 ~/.steam/ubuntu12_32/steam-runtime/run.sh ./Magicka2_x64`.

**Comment by nipsy** [comment] 2019-01-08 03:46
@kisak-valve I've added that CLI output to the original gist above.  Seems to fail in exactly the same way.  I also had looked previously to see if Debian even provides a libssl_conf.so still, but I didn't find any reference to it via `apt-file search` (using the standard main, contrib and non-free APT sources for Debian).

**Comment by TTimo** [comment] 2019-01-08 15:48
I don't think this is a problem with the steam client or the steam runtime unfortunately, but an issue with Magicka 2.

libssl_conf.so appears to be a module that was part of older libssl distributions, that is no longer available in more recent libssl versions. It was probably never meant to be used directly by client programs. A quick google search seems to support this.

steam runtime never distributed it, and when Magicka 2 worked it must have been by implicitly relying on it being present on the host OS.

This needs to be taken up with the Magicka 2 developers to properly addressed. I realize compiling updated binaries isn't necessarily practical in a released title, but this may be a simple matter of recompiling using the docker runtime environment from https://github.com/ValveSoftware/steam-runtime/

If there is something else we can do please comment on this issue and we will re-open it.

**Comment by TTimo** [comment] 2019-01-08 15:58
Afterthought - I suppose wrapping the legacy binary in a shell script with the adequate workaround could be a cheap way to fix this.

**Comment by TTimo** [comment] 2019-01-08 17:09
After further investigation, we think this is happening because the libssl library in the runtime is picking up configuration items from the host's `/etc/ssl/openssl.cnf` that it can't adequately interpret. So it is indeed a problem on our end .. reopening!

**Comment by smcv** [comment] 2019-01-08 17:46
@nipsy: If you remove any other workarounds, and run the game with `OPENSSL_CONF=/dev/null` in the environment, does that also work?

**Comment by smcv** [comment] 2019-01-08 18:35
Thanks, that's very useful feedback (and probably a better short term workaround too).

**Comment by smcv** [comment] 2019-01-08 19:10
Please could someone with appropriate privileges retitle this?

```
Magicka 2 Linux x86-64 crashes on start with error messages involving libssl_conf.so
```

The root cause isn't a missing library symlink - it's valid and correct that libssl_conf.so doesn't exist. The problem is that /etc/ssl/openssl.cnf in Debian buster was written for OpenSSL >= 1.1.0, and is incompatible with the OpenSSL 1.0.0 in the Steam Runtime. I think the solution is to patch the Steam Runtime's libssl so it doesn't load /etc/ssl/openssl.cnf by default.

**Comment by smcv** [comment] 2019-01-16 10:19
> I think the solution is to patch the Steam Runtime's libssl so it doesn't load /etc/ssl/openssl.cnf by default.

This works, and the updated packages should go out in the next Steam Runtime update.

**Comment by TTimo** [comment] 2019-01-16 19:53
This is fixed in the latest steam beta runtime.

**Closed by TTimo** 2019-01-16 19:53 UTC
Labels: 3rd party game, runtime
