### ISSUE TITLE
[Cinnamon] Steam notifications block panel and hot corners

### ISSUE THREAD

**Issue by javermot** [ValveSoftware/steam-for-linux#3668] opened 2015-01-11 18:09 UTC
If the panel is set to automatically hide, Steam notifications (e.g. new inventory item) keep the panel from appearing when hovering over the panel with the mouse. They also block any hot corners, for example to switch between windows/workspaces.

Result: you have to wait 5 seconds until the notification disappears before using the panel. Only tested on the Cinnamon desktop so far.

Tested on:
Linux Mint 17.1 Cinnamon 64-bit
Cinnamon version: 2.4.5
Kernel: Linux 3.18.0-031800-generic (Ubuntu)
Steam client: Built Nov 21 2014, package versions 1416617579
Using Intel graphics

**Comment by MrSchism** [comment] 2015-01-11 18:59
Seems to work fine with XFCE.  This is possibly related to #184

**Comment by javermot** [comment] 2015-01-11 19:38
Seems related. When the panel is not set to autohide, the notification now goes in front, but the panel becomes unresponsive while it's there.

**Comment by MrSchism** [comment] 2015-01-11 22:59
It's likely because the solution they used (in my opinion*) was kinda kludgy.  I'll be opening a bug over on the Cinnamon tracker about this... unless you want to do it, that is.

* This was the case because their solution didn't take into account that -other- notifications were coming up behind the bar as well.  An example could be seen by hovering over VLC or the battery notification.

**Comment by hypershadsy** [comment] 2015-03-31 23:42
Any update on this?

**Comment by MrSchism** [comment] 2015-04-01 03:13
linuxmint/Cinnamon#2357 is the most recent update.  Supposedly it's fixed.  I'm going to install Mint 17.1 and see if Cinnamon 2.4 fixes the issue(s).

The issue is still open on multi-monitor setups.  As I mentioned above, I doubt they fixed the cause of the problem, but our specific symptom may have resolved.

**Comment by kisak-valve** [comment] 2018-05-25 14:08
Hello @javermot, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment] 2018-07-03 00:35
Closing pending feedback.

**Closed by kisak-valve** 2018-07-03 00:35 UTC
Labels: Need Retest, Window manager, reviewed
