### ISSUE TITLE
Steam spamming message of Xlib: sequence lost on terminal

### ISSUE THREAD

**Issue by Danielhlw** [ValveSoftware/steam-for-linux#9087] opened 2023-01-10 22:06 UTC
#### Your system information

* Steam client version (build number or date):  steam 1.0.0.75-1
* Distribution (e.g. Ubuntu): Arch-Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

![image](https://user-images.githubusercontent.com/64915907/211671918-980d62ab-e776-4313-8cd0-0dc86004586e.png)

The only way to resolve this is to downgrade lib32-libx11 to version 1.8.2-2.
In my case, this resulted in a good performance in waiting time to start my games.

**Comment by Patola** [comment] 2023-01-10 22:07
Duplicate of #9086

**Comment by kisak-valve** [comment] 2023-01-10 23:26
Hello @Danielhlw, this is an upstream regression in libX11 and needs to be resolved upstream.

Closing as a duplicate of #9083.

**Closed by kisak-valve** 2023-01-10 23:26 UTC
