### ISSUE TITLE
Steam crashes after selecting new drive for apps

### ISSUE THREAD

**Issue by prufaraSS** [ValveSoftware/steam-for-linux#11164] opened 2024-08-06 18:54 UTC
#### Your system information

* Steam client version (build number or date): 1722380543
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes (Steam Family Beta)
* Have you checked for system updates?: No (Fresh system install)
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16514558/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
i'm trying to add new directory for installed games above /home/ folder (/steamdata/ to be precise) and when I press SELECT in popup it crashes steam after a short delay. i've tried to chmod both /steamdata directory and directories where steam is installed (recursively), nothing helped.
Just to mention - /home/ directory is located in HDD while other part of the system located in SSD

#### Steps for reproducing this issue:

1. Open Steam settings
2. Locate to Storage category
3. Open dropdown list located at the top of the window and select "Add Drive"
4. In popup select any path not located at /home/ directory
5. Press select and wait for crash

**Comment by prufaraSS** [comment] 2024-08-07 11:15
Update: tried to do some things mentioned in [official Arch wiki](https://wiki.archlinux.org/title/Steam/Troubleshooting#Cannot_add_library_folder_because_of_missing_execute_permissions)
such as: modify /etc/fstab file to make required filesystem contain 'exec' parameter, add 'steamapps' folder to new library directory. Still nothing changed.

**Comment by TTimo** [comment] 2024-08-13 17:19
Hello,

Unfortunately we are not able to reproduce. I looked at the crash report information from your logs but it doesn't carry much information as to what is happening. It is unlikely we will make much progress on this until we have a reproduction or other users come forward with more information.

**Comment by TTimo** [comment] 2024-09-03 16:07
You are crashing with the Steam builtin file dialog though, you may want to install https://wiki.archlinux.org/title/XDG_Desktop_Portal and use your OS file dialogs instead.

**Comment by TTimo** [comment] 2024-09-03 20:47
I was able to reproduce. This will be fixed in an upcoming beta client update.

**Comment by prufaraSS** [comment] 2024-09-04 16:05
wait it was actually fixed? i've just made some changes and thought it really worked (i've got really surprised)
here's all things i've done:
1. add "exec" parameter for drive for /home directory
2. chown /steamdata/ (folder that being used for new place for apps) to have user group instead of root (group: root -> max)

**Comment by TTimo** [comment] 2024-09-04 16:10
The crash was due to a race condition in the Steam client. Not something you could have fixed, other than by using `xdg-desktop-portal` which uses a different path not affected by the bug.

Most folks (including me) do have `xdg-desktop-portal` as it's a standard piece of a kde or gnome desktop environment.

**Comment by prufaraSS** [comment] 2024-09-04 16:15
> The crash was due to a race condition in the Steam client. Not something you could have fixed, other than by using `xdg-desktop-portal` which uses a different path not affected by the bug.
> 
> Most folks (including me) do have `xdg-desktop-portal` as it's a standard piece of a kde or gnome desktop environment.

that must be the case then, since i'm using Hyprland which invents it's own version of desktop integration portals, if i'm correct

**Closed** 2024-09-04 16:16 UTC
Labels: Steam client, Need Retest
