### ISSUE TITLE
Big Picture Mode Doesn't Render / Open Properly

### ISSUE THREAD

**Issue by ThisNekoGuy** [ValveSoftware/steam-for-linux#8916] opened 2022-11-15 11:07 UTC
#### Your system information

* Steam client version (build number or date): Nov 15 2022, at 03:57:54 (1668486879)
* Distribution: Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* GPU: RTX 2080 Ti
* GPU Driver: 520.56.06 (Open-GPU Kernel Module)

#### Please describe your issue in as much detail as possible:
Big picture mode no longer opens properly; it loops in trying to render the window but does so as a transparent window then closes, repeatedly.

#### Steps for reproducing this issue:

1. Run Steam with: `steam -newbigpicture`
2. Click on the big picture mode icon in the top right of desktop mode

**Comment by LiamDawe** [comment] 2022-11-15 16:50
This seems to be from the Beta update that introduced the new intro video, I can confirm I am seeing the same here with "-gamepadui".

I hear the intro video playing, but it doesn't actually render anything and my screen ends up looking like this (notice the split across it): 
![1](https://user-images.githubusercontent.com/83223/201978539-70403999-4c51-4359-b40a-0ed32059dc7b.png)

**Comment by cybik** [comment] 2022-11-15 17:06
Can't post screenshots because stuff is offline, but I can confirm that `-gamepadui` and `-newgamepadui` break the 10-foot interface on nVidia since this morning. Using a 3060 Ti and latest drivers.

**Comment by agentwolf88** [comment] 2022-11-15 19:39
Same!

**Comment by TheTee82** [comment] 2022-11-16 08:51
Same here.
I also tried downgrading Nvidia drivers to 4.70 which didn't work either.


I also noticed when trying to run steams new ui with `-steamos3 -steampal -steamdeck -gamepadui` steam will download a (probably stable) version of steamos and it works fine.
However when installing the update (which happens shortly after the first launch) it's again back to being 'broken'.


Also note the `-gamepadui` version in beta was working fine on the exact same system up until the update last week which (coincidentally) introduced the new parameter `-newbigpicture`.

**Comment by papamikey** [comment] 2022-11-16 11:11
hopefully this has to do with them trying to fix the lack of hardware acceleration on linux that caused it to be laggy. Happens to me as well.

**Comment by LiamDawe** [comment] 2022-11-17 13:47
This has now rolled out into the Stable release, still broken on NVIDIA.

**Comment by groybe** [comment] 2022-11-18 02:53
This also affects Controller Configurator in stable.

**Comment by guymanley** [comment] 2022-11-19 12:57
Adding myself to the list of affected users. Nvidia GTX 1080, 520.56.06 proprietary drivers, Manjaro linux. Beta and stable steam clients. New steam deck big picture UI doesn't work. Same behavior.

**Comment by Sqaaakoi** [comment] 2022-11-20 12:22
Also affected in the exact same way as everyone else here, running NVIDIA 520.61.05, KDE Plasma 5.26.3, Xorg, also tried both stable and beta, Also, screwing around with some command line arguments put my steam client into Danish, somehow?

**Comment by msmafra** [comment] 2022-11-20 16:55
Same here in Fedora 37 (kernel 6.0.8), Intel + Nvidia, Gnome X11, Flatpak Steam, 22.2.3. Tried with 520.61.05 and Beta 525.53, BUT only when I start my laptop in Discreet GPU mode, via Hybrid graphics it works OK because it seems to start in the iGPU instead.

Steam version 1668842190

**Comment by toastal** [comment] 2022-11-21 08:55
It doesn't work at all with 10-bit color.

**Comment by o-kotb** [comment] 2022-11-27 19:58
No issues here with nVidia 2070 on F37 wayland. I'm using the freedom respecting free/libre nouveau drivers. We can close this now.

**Comment by ThisNekoGuy** [comment] 2022-11-27 21:20
> We can close this now.

Very funny; sorry to burstbyour bubble, but most people don't use the janky Nouveau driver and for good reason. That's not an excuse to close this issue.

**Comment by TheBurnDoc** [comment] 2022-11-30 17:51
Same issue, Ubuntu 22.04, RTX 3070

**Comment by alexhowell2a** [comment] 2022-11-30 21:27
Same issue on my GTX 1650, Ubuntu 22.04.

**Comment by reedlove** [comment] 2022-12-03 10:03
Also having the same problem along with the controller configurator on Linux Mint 21. Nvidia 1060 and 3060m. Being unable to assign controller profiles along with the recent changes has broken controller support with Xone unless I disable steam configuration support. Honestly can't believe that it's been over half a month and it's radio silence from Valve. Can't get the controller configuration screen to pop up under classic big picture mode now either.

**Comment by guymanley** [comment] 2022-12-03 14:28
> Also having the same problem along with the controller configurator on Linux Mint 21. Nvidia 1060 and 3060m. Being unable to assign controller profiles along with the recent changes has broken controller support with Xone unless I disable steam configuration support. Honestly can't believe that it's been over half a month and it's radio silence from Valve. Can't get the controller configuration screen to pop up under classic big picture mode now either.

Yes confirmed, normal steam controller input from the desktop client will not render the window. Which makes sense as this is now the Steam OS input configurator. So as of the latest update (that added the intro video) nothing steamOS / game mode / new big picture etc. will render on a Nvidia GPU.

**Comment by TheTee82** [comment] 2022-12-09 16:39
With the latest update even the old "-bigpicture" does not work anymore since it launches the new UI which doesn't work!
This renders my couch setup completely useless!

Does anyone know if the old big picture mode can still be launched somehow?

**Comment by agentwolf88** [comment] 2022-12-09 17:12
Why does Valve dont fix this bug???

**Comment by EthanArmbrust** [comment] 2022-12-09 22:42
> With the latest update even the old "-bigpicture" does not work anymore since it launches the new UI which doesn't work! This renders my couch setup completely useless!
> 
> Does anyone know if the old big picture mode can still be launched somehow?

You'll have to opt out of the Steam Beta program for now

**Comment by m0ngr31** [comment] 2022-12-09 23:21
I have Steam launching into Big Picture mode automatically, but as of today I can't get back to regular mode to opt-out of the beta and disable Big Picture mode :-1:

**Comment by TheTee82** [comment] 2022-12-09 23:45
> I have Steam launching into Big Picture mode automatically, but as of today I can't get back to regular mode to opt-out of the beta and disable Big Picture mode 👎

You could try '-nobigpicture' as a launch parameter to opt out of beta.


However, I fear they will push this broken state into release as well soon, just like with the controller settings interface.

**Comment by m0ngr31** [comment] 2022-12-10 00:03
> > I have Steam launching into Big Picture mode automatically, but as of today I can't get back to regular mode to opt-out of the beta and disable Big Picture mode 👎
> 
> You could try '-nobigpicture' as a launch parameter to opt out of beta.
> 
> However, I fear they will push this broken state into release as well soon, just like with the controller settings interface.

Unfortunately that didn't work

**Comment by patrick-g-p** [comment] 2022-12-10 00:36
Having the same problem with big picture

- Distro: Kubuntu 22.04.1 LTS (64 bit)
- CPU:  AMD Ryzen 7 3700X 8-Core Processor       
- GPU:  NVIDIA GeForce RTX 2070 SUPER
- Drivers:  4.6.0 NVIDIA 525.60.11

**Comment by piffall** [comment] 2022-12-10 09:47
Same!

**Comment by Zeitwaechter** [comment] 2022-12-10 11:34
It works for me via Wayland, but Wayland is still broken, especially when I use only one monitor or the amount of monitors changes on the way.. anyway:

![image](https://user-images.githubusercontent.com/1764348/206852510-901459d3-f7de-4c2d-8c8b-af16433dfcd4.png)

I have installed the proprietary NVIDIA drivers v525.60.11-2.
KDE Plasma v5.26.4-1.

I also just tested it with an Intel i9 9900KF, same behaviour, so clearly GPU bound.

Steam beta is active and up2date (also this shows that the new BPM does "run" for me):

![image](https://user-images.githubusercontent.com/1764348/206852731-12284538-f65e-4851-804a-873017ae1844.png)

My [base software stack](https://gist.github.com/Zeitwaechter/c2de35b21b826d0f261a55bad8b9ece4)  is documented - feel free to compare (and comes without warranty).

Hope it helps somebody, in some kind of way :+1:

**Comment by armadillu** [comment] 2022-12-10 13:54
Same here, on a default install of popOs, fully updated and latest Nvidia drivers, using an Nvidia GTX 960

**Comment by Soulsuke** [comment] 2022-12-10 14:01
Chiming in as well...

Steam client version: 1670661475
Opted into Steam client beta?: Yes
Have you checked for system updates?: Yes
Distribution: Arch Linux (6.0.11-arch1-1)
CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
GPU: NVIDIA GeForce GTX 1060
Drivers: 525.60.11 (closed source ones)

With the latest update big picture is completely broken on X11, while it seems to work on Wayland sessions (tested on KDE Plasma 5.26.4).

Just a friendly reminder: KDE isn't really viable for anyone who isn't using KDE or Gnome, as many X11 workflows still don't have a valid (read: "really working") Wayland replacement.

Please don't let the new Big Picture go live unfixed, it'd break so many setups relying on Remote Play...

**Comment by TLATER** [comment] 2022-12-10 19:43
Can we please stop it with the #metoos, the issue is obviously there and trivial to reproduce. It will affect just about everybody with the proprietary nvidia driver on X11. Just leave a :+1: on the original post.

Every ping here is just another round of emails to anyone subscribing to this issue waiting for a fix, and doesn't contribute much useful additional information beyond driver versions which anyone triaging this can easily find themselves.

Alternatively go complain to nvidia on your favorite social media platform. Get them to write a real mesa driver instead of [outsourcing that to the open source community](https://www.collabora.com/news-and-blog/news-and-events/introducing-nvk.html) and fix issues like this for good. That's where #metoos actually help a bit.

**Comment by reedlove** [comment] 2022-12-10 19:45
> Can we please stop it with the #metoos, the issue is obviously there and trivial to reproduce. It will affect just about everybody with the proprietary nvidia driver on X11. Just leave a 👍 on the original post.
> 
> Every ping here is just another round of emails to anyone subscribing to this issue waiting for a fix, and doesn't contribute much useful additional information beyond driver versions which anyone triaging this can easily find themselves.
> 
> Alternatively go complain to nvidia on your favorite social media platform. Get them to write a real mesa driver instead of [outsourcing that to the open source community](https://www.collabora.com/news-and-blog/news-and-events/introducing-nvk.html) and fix issues like this for good. That's where #metoos actually help a bit.

You're more than welcome to unsubscribe from the thread.

**Comment by avtavt** [comment] 2022-12-11 01:46
I have this issue too on Manjaro. It basically perma-bricks steam, since you can't opt out of the beta any more

================== CONFIRMED WORKAROUND ====================
If you can't launch steam, to opt out, make sure that all steam processes are closed, then run `steam -nobigpicture`. It'll launch in desktop mode, where you can opt out.

If it launches in the new UI anyways, and locks up, or, shows just a few lines of debug on the terminal, then returns to your shell prompt, or both, then that probably means you have a steam process still running. Make sure ALL steam processes are dead (`ps -eaf | grep -i steam`) and try again. If you're successfully starting steam from scratch, your terminal should stay "inside" the steam command, without returning to the shell, and you should see pages and pages and pages of debug info

**Comment by TheTee82** [comment] 2022-12-12 15:05
Apparently they introduced a new parameter without posting it in release notes ( see https://steamcommunity.com/groups/SteamClientBeta/discussions/3/3710433479209600654/#c3710433479212649928 ):


`-oldbigpicture` - this will use the old ugly (but at least working) big picture mode


Note that this will not immediately launch bpm. If you want to immediately start Steam in old BPM, it would look something like this:
`steam -oldbigpicture -bigpicture`


I only tested this on my desktop PC which uses an AMD GPU - will check if it works later with latest beta on the affected Nvidia Couch PC.

**Comment by hardpenguin** [comment] 2022-12-13 09:11
I tried the most recent beta and this still is a problem.

Then I used `-oldbigpicture` workaround but it causes the legacy Big Picture to just crash the Steam client altogether.

**Comment by HereInPlainSight** [comment] 2022-12-13 14:18
Oddly enough, using `-oldbigpicture` briefly worked for me yesterday morning... but by evening, after updating to do the same test from the other thread, it now crashes Steam to desktop when I try to open BPM.  Using Steam outside of BPM seems to work just fine with the flag.  I don't _know_ that the update itself is directly related as I can't roll back the client, but the error when run from command line for me is:

`/home/tom/.local/share/Steam/steam.sh: line 798: 24566 Aborted                 "$STEAMROOT/$STEAMEXEPATH" "$@"`

**Comment by ri0t** [comment] 2022-12-13 17:10
Yeah, same here. Debian Sid/Experimental, i can hear the bigpicturemode, but not see it. Oldbigpicturemode gives me either "Illegal Instruction"+crash (if started with cmd argument) or immediate crash on starting it in classic view.

**Comment by smcv** [comment] 2022-12-13 17:38
> It basically perma-bricks steam, since you can't opt out of the beta any more

Even in situations with no direct workaround, there is a failsafe for this: if you `rm ~/.steam/root/package/beta` and start Steam again, it will opt you out of the beta and download the general-availability version of Steam instead.

**Comment by hardpenguin** [comment] 2022-12-13 17:54
> It basically perma-bricks steam, since you can't opt out of the beta any more

What? No? Why? I was able to opt out of beta without any problem.

**Comment by avtavt** [comment] 2022-12-13 18:10
> > It basically perma-bricks steam, since you can't opt out of the beta any more
> 
> What? No? Why? I was able to opt out of beta without any problem.

If you're unfortunate enough to have told steam to auto-start in the broken BPM, then you're perma-bricked.

If your steam still starts in desktop mode, then yeah you can easily opt out

**Comment by nonno-cicala** [comment] 2022-12-14 00:36
I have this problem too with Nvidia RTX 2060 v.515.86.01 X11 on Gentoo

**Comment by HereInPlainSight** [comment] 2022-12-14 04:39
After installing tonight's update, I'm able to launch the new BPM on an Nvidia 2080 on Gentoo, albeit extremely laggy.  `-oldbigpicture` seems to be working again as well.

**Comment by toastyfen** [comment] 2022-12-14 05:51
Also working after tonight's beta on my 3080 Ti w/ arch. Laggy, though that's how it was on Linux before it broke

**Comment by hardpenguin** [comment] 2022-12-14 10:18
Same here, works but laggy on 3060 Ti on Debian Sid.

I wonder is it possible for it to be rendered in software mode and also not be laggy.

**Comment by agentwolf88** [comment] 2022-12-14 10:21
How does work the software mode?

**Comment by hardpenguin** [comment] 2022-12-14 10:23
> How does work the software mode?

Well um not sure if there is one actually. There is a GPU blacklist but that's it. I would suspect that a blacklisted GPU will launch New Big Picture in software mode. That is just pure speculation on my side.

**Comment by nonno-cicala** [comment] 2022-12-14 12:27
After today's update BPM works for me, thanks!
I only tested the new interface

**Comment by guymanley** [comment] 2022-12-14 12:55
hmm, I opted back into the beta and tried again. Still the same non rendering transparent window. I don't know what proprietary Nvidia drivers I'm on currently at the moment. This is my couch PC so I don't boot it often. I'll check when I can again. Did anyone need to do anything to trigger a beta update? Steam just restarted when opting in and didn't install anything, so I think I might be on an older beta then the recent reports here.

**Comment by alexhowell2a** [comment] 2022-12-14 13:24
After the update, NBP works for me too on the GTX 1650, latest NVIDIA drivers. Laggy, but it works.

**Comment by TheTee82** [comment] 2022-12-14 13:45
Yeah, can confirm.
New BPM now works on latest beta for me just like before - with bad performance and all but at least it launches.
- GTX 1080 - nvidia 525.60.11

---

**Steam Version:** `1671007697`
**Built:** `Dec 14 2022, at 08:27:42`

**Comment by TheTee82** [comment] 2022-12-14 14:02
@guymanley 

> Steam just restarted when opting in and didn't install anything, so I think I might be on an older beta then the recent reports here.

Maybe this here helps to make sure no old beta is present: https://github.com/ValveSoftware/steam-for-linux/issues/8916#issuecomment-1349228881

**Comment by ri0t** [comment] 2022-12-14 14:40
Yeah, works now @kisak-valve :-)

Hella confusing though, i need to change the css on the deck, as it is now indistinguishable from my PC when connected to the same display.

Good job!

**Comment by cybik** [comment] 2022-12-14 14:53
Confirming it works again here as well. Still slow as all hel though.

**Comment by HereInPlainSight** [comment] 2022-12-14 15:16
> Did anyone need to do anything to trigger a beta update?

You can trigger an update outside of BPM by clicking `Steam` from the top-bar, `Check for Steam Client Updates`.

![Screenshot_20221214_101356](https://user-images.githubusercontent.com/766446/207633933-ff734542-d10b-455a-825b-eeba74d9fdcf.png)

**Comment by guymanley** [comment] 2022-12-14 18:40
Yes! 525.60.11 X11 New big Picture mode isn't completely borked after all this time. Now that regression is done. I'm looking forward to progress again.

**Comment by guymanley** [comment] 2022-12-20 15:15
> Still new BP mode are laggy and slow. Also Elden Ring cannot see my controller with it. Old BP mode is ok, and with no BP mode also is ok. When we will stop with that madness? I'm glad i can still play my game without any BP mode. So do not mess up more than that! Valve... i mean you.

Wow an actual threat from death. Time to unsub from this thread.

**Comment by kisak-valve** [comment] 2023-01-27 23:32
Closing as fixed. Any followup issues should be tracked separately.

**Closed by kisak-valve** 2023-01-27 23:32 UTC
Labels: NVIDIA drivers, Big Picture, Need Retest

**Comment by Kalidibus** [comment] 2023-02-09 19:38
On latest steam client beta - fully up to date Manjaro with nvidia GTX 3060 - this issue is still occurring

**Comment by rcarmo** [comment] 2023-02-11 13:28
Also having this issue in Fedora, Nvidia 3060.

**Comment by rcbevans** [comment] 2023-02-13 05:28
Big Picture performance is very very poor, eyeball 15-20fps and input lag on fresh Pop_OS 22.04 install with official nvidia drivers.

**Comment by papamikey** [comment] 2023-02-15 00:10
not only is the performance completely unusable, when I try to edit a controller config while not in big picture mode it just opens a black box. To get around this you used to have to open Steam in small mode then try, and it would open old BPM. Now when you try that it crashes the entire client.

**Comment by kisak-valve** [comment] 2023-02-15 00:18
To re-emphasize, the issue originally reported in this issue report was resolved. There are remaining issues, but they should be tracked separately.

Some related issue reports: #8918 #8949 #9160 #9190
