### ISSUE TITLE
Feature Request: Allowing user to download games for any operating system

### ISSUE THREAD

**Issue by Sarkie** [ValveSoftware/steam-for-linux#3714] opened 2015-02-13 16:14 UTC
Is it possible to allow me to download games, "Right click 'Download only'" for other operating systems, as for instance I have some old games that will run from DosBox or Wine, I just need to download the correct files instead of logging into Windows and such.

**Comment by Tele42** [comment] 2015-02-13 16:51
The steam for windows client can be run in wine.

Duplicate of #74.

**Comment by slobo42** [comment] 2015-02-13 17:19
Like @Tele42 said, you can use PlayOnLinux if you want 
https://www.playonlinux.com/en/

**Comment by gdrewb-valve** [comment] 2015-02-13 20:20
Closing duplicate.

**Closed by gdrewb-valve** 2015-02-13 20:20 UTC
Labels: duplicate, reviewed
