### ISSUE TITLE
[KDE] Window becomes semi-transparent and drag pointer appears when I click the "titlebar" area

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/steam-for-linux#1935] opened 2013-02-21 03:56 UTC
In KDE 4.x, windows become semi-transparent when dragged or resized. In order to keep this from being annoying in cases where the user is merely clicking the titlebar to focus it, there's a delay of about half a second of the mouse button being held down. Except in the Steam client's windows, where it happens immediately. This is especially annoying for the main window, because its draggable area is much larger than the actual titlebar.

I know KDE isn't officially supported yet, but I'm seeing other KDE-specific issues staying open on here, so I figured I'd throw this one on the pile.

**Comment by esromneb** [comment] 2015-04-15 01:14
How do you disable this "Transparent when drag" feature? It's messing up my seamless desktop under VirtualBox.

**Comment by kisak-valve** [comment] 2017-04-12 13:02
Closing as a duplicate of #86.

**Closed by kisak-valve** 2017-04-12 13:02 UTC
Labels: reviewed, Window manager
