### ISSUE TITLE
не запускается программа на linux 16.04

### ISSUE THREAD

**Issue by devweb99** [ValveSoftware/steam-for-linux#5416] opened 2018-03-22 14:28 UTC
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment] 2018-03-22 15:02
Hello @devweb99, you're going to need to give more information than a one-liner saying steam won't start.

Can you try to run steam from a terminal and copy the spew to a [gist](https://gist.github.com/)? Additionally, please describe your system, in particular, what video driver version are you using and check if any 32 bit opengl application works as intended. A 32 bit variant of glxinfo should be sufficient for testing.

**Comment by devweb99** [comment] 2018-03-22 16:39
ubuntu 16.04   64

console 

Refresh rate: 1
Refresh rate: 1
Refresh rate: 60
Refresh rate: 60
Refresh rate: 15
Refresh rate: 15




>Четверг, 22 марта 2018, 22:02 +07:00 от kisak-valve <notifications@github.com>:
>
>Hello  @devweb99 , you're going to need to give more information than a one-liner saying steam won't start.
>Can you try to run steam from a terminal and copy the spew to a  gist ? Additionally, please describe your system, in particular, what video driver version are you using and check if any 32 bit opengl application works as intended. A 32 bit variant of glxinfo should be sufficient for testing.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Кирилл Белов

**Comment by kisak-valve** [comment] 2018-04-27 13:05
Closing due to insufficient information to troubleshoot.

**Closed by kisak-valve** 2018-04-27 13:05 UTC
Labels: Distro Family: Ubuntu, Need System Info
