### ISSUE TITLE
Steam client doesnt remember password

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [ValveSoftware/steam-for-linux#5491] opened 2018-05-19 19:41 UTC
#### Your system information

* Steam client version (build number or date): May 18 2018 14:50:44
* Distribution (e.g. Ubuntu):  Debian stretch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam client doesn`t remember password even if checked option to rememeber it. Look like such option doesn`t work on linux at all. 
#### Steps for reproducing this issue:
1. Trivial

**Comment by kisak-valve** [comment] 2018-05-19 21:53
Hello @jpVm5jYYRE1VIKL, is the username also not remembered? If that's the case, then this is most likely a duplicate of #5030.

**Comment by kisak-valve** [comment] 2018-05-21 12:28
Closing as a duplicate of #5030.

**Closed by kisak-valve** 2018-05-21 12:28 UTC
Labels: Distro Family: Debian, Steam client, duplicate
