### ISSUE TITLE
steam-runtime/run.sh missing on fresh install

### ISSUE THREAD

**Issue by avalonv** [ValveSoftware/steam-for-linux#6129] opened 2019-03-07 22:38 UTC
#### Your system information

* Steam client version (build number or date):  07 Mar 2019
* Distribution (e.g. Ubuntu): Void Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Steam segfaults on fresh install, looks like #5991
```/home/satsu/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
/home/satsu/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
Running Steam on void  64-bit
/home/satsu/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/satsu/.local/share/Steam/steam.sh: line 828: /home/satsu/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: No such file or directory
Installing breakpad exception handler for appid(steam)/version(0)
crash_20190307193011_1.dmp[15736]: Uploading dump (out-of-process)
/tmp/dumps/crash_20190307193011_1.dmp
crash_20190307193011_1.dmp[15736]: Finished uploading minidump (out-of-process): success = no
crash_20190307193011_1.dmp[15736]: error: libcurl.so: cannot open shared object file: No such file or directory
crash_20190307193011_1.dmp[15736]: file ''/tmp/dumps/crash_20190307193011_1.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
/home/satsu/.local/share/Steam/steam.sh: line 889: 15720 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
```

#### Steps for reproducing this issue:

1. Install steam on Void Linux
2. Run `steam`

**Comment by kisak-valve** [comment] 2019-03-07 22:48
Possible duplicate of #6077.

**Comment by kisak-valve** [comment] 2021-07-23 16:57
Hello @avalonv, steam-runtime/run.sh was added to Steam's 1.0.0.61 package, and this issue report is now outdated. If you're still experiencing this issue on an up to date system, please open a new issue report.

**Closed by kisak-valve** 2021-07-23 16:57 UTC
Labels: Steam client
