### ISSUE TITLE
Steam games crashing at launch

### ISSUE THREAD

**Issue by Jp5243** [ValveSoftware/steam-for-linux#4147] opened 2015-11-20 20:13 UTC
So, I have Steam on Linux Ubuntu 15.04 64-bit. Whenever I launch a game, it briefly appears as a blank, black window and then crashes. None of my games on Steam (Crusader Kings II, Mount and Blade: Warband and Terraria) will run. My non-Steam games (Minecraft, Triplea, Astromenace and Battle for Wesnoth) all work. I have tried to "Verify Integrity of Game Cache" at least a half dozen times, following the exact instructions given by Steam. Even after running it, it always says that I am missing some 9000+ files (for CK2, don't remember the exact number for Mount and Blade: Warband or Terraria.), it then downloads them and still won't run. If you verify the files again, the same files are missing. I was in contact with Steam Support for over a month and they were still unable to resolve the issue. Any help would be greatly appreciated. Thanks!

**Comment by sizeofbool** [comment] 2015-11-21 13:59
Post more information about your PC and configuration.
Install Steam client from *http://repo.steampowered.com/steam/* instead of ubuntu's package.
Make sure you use compatible filesystem for Steam Library such as *ext4*.

**Comment by Tele42** [comment] 2015-11-21 18:20
@Jp5243 if you have an encrypted home folder, that would explain why verifying games always downloads files.

**Comment by Jp5243** [comment] 2015-11-21 22:41
@Tele42 Would this be the cause of all of my problems or just the issue with file verification? IMy files are encrypted, would changing that help?

**Comment by Tele42** [comment] 2015-11-21 22:54
@Jp5243 I can't speculatively guess without <a href="https://github.com/ValveSoftware/steam-for-linux#reporting-issues">system information</a>. Home folder encryption should only confuse steam, not prevent games from launching.

**Comment by Jp5243** [comment] 2015-11-21 22:59
There you go, sorry for not including it in the first place.

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0xf
    CPU Stepping:  0x6
    CPU Type:  0x0
    Speed:  2000 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-21-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) 945GM x86/MMX/SSE2

    Driver Version:  1.4 Mesa 10.5.9
    OpenGL Version: 1.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x27a2
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1280 x 800
    Desktop Resolution: 1280 x 800
    Primary Display Size: 11.97" x 7.48"  (14.09" diag)
                                            30.4cm x 19.0cm  (35.8cm diag)
    Primary VRAM Not Detected
    
Sound card:
    Audio device: SigmaTel STAC9200
    
Memory:
    RAM:  1991 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  232352 Mb
    Largest Free Hard Disk Block:  192926 Mb
    
Installed software:
    
Recent Failure Reports:

**Comment by Tele42** [comment] 2015-11-21 23:02
Some libraries in the steam runtime are too old for your version of mesa, please take a look at the <a href="https://wiki.archlinux.org/index.php/Steam#Steam_runtime_issues">Arch workaround</a>.

**Comment by Jp5243** [comment] 2015-11-22 01:31
Didn't work. Still has the same error.

**Comment by Tele42** [comment] 2015-11-22 02:31
This is where I step aside and leave this riddle to a valve dev. Since that did not help, I'm going to assume that individual games are assuming the availability of at least OpenGL 2.1, and mesa is only exposing OpenGL 1.4 on your intel gen 3 chip.

**Comment by Jp5243** [comment] 2015-11-22 02:43
@sizeofbool Why would I need to install Steam from where you linked rather than Ubuntu? Does the Ubuntu package have issues?

**Comment by sizeofbool** [comment] 2015-11-23 02:57
@Jp5243 I can't tell if there is an issues with Ubuntu's Steam Client package, but official Valve repo recently got an update and I never had any problems with official Steam Client package.

There are known problems with Steam games if they are installed on uncommon filesystems like *btrfs* for an example. "Dead Island" had black screen and crashes on start up. Installing the game on *ext4* partition solves all problems and the game works perfectly.
You can test if this is your problem without repartitioning your disk, just create ext4 filesystem in a file and mount it like loop device.

**Comment by Undeterminant** [comment] 2015-11-26 05:26
I have the same issue under Arch Linux. The cause seems to be a crash in steam overlay-- some games will just continue regardless, whereas many will crash if overlay fails to start.

**Comment by cheebsco** [comment] 2015-11-27 10:19
@Jp5243 I would double check file permissions.  Ensure the Steam Games are allowed to be executed.  Is this an issue that just appeared, or is this the first time you are running them on this OS?  There are many roads to travel in troubleshooting, so its definately worth the effort.  Like Undeterminant mentioned, it could be as simple as turning the steam overlay off in Steam Settings.  It looks like you have an integrated graphics card, could be that simple.

**Comment by Jp5243** [comment] 2015-11-28 00:17
@cheebsco Where can I check file permissions? I have had the issue for over six months. I went to Github because Steam Support gave up on me and sent me here. I have already tried turning off Steam Overlay, doesn't fix the issue.

**Comment by Jp5243** [comment] 2015-11-28 00:35
@cheebsco How do I check file permissions? I have had the issue for around seven months. I came to Github after Steam Support gave up and sent me here. I have tried turning Steam Overlay off, it did not work.

**Comment by cheebsco** [comment] 2015-11-28 00:44
@Jp5243 While you are inside steam, Browse for the area where you would normally validate content.  Instead, "Browse Local Files On Disc. This should show you where your game data is.  First thing to do, is check the properties of the executables.  Under permissions, ensure it is " Allow Executing File As A Program" is checked.  You may need to do this for 3 game files.  There may be a "*.x86", "*.x86_64", and "*.sh" file.  
If you are not allowed to change permissions of the files:
open terminal:
sudo nautilus
<enter password> 
then navigate to the same directory that you found the files in through steam, and change permissions.

**Comment by Jp5243** [comment] 2015-11-28 03:34
The only executable I could find was the ck2 executable. Not sure what the file type itself was. In any case, it is/already was allowed to execute as a program.

**Comment by cheebsco** [comment] 2015-11-28 15:57
Do you know if these programs are 32bit or 64bit?

**Comment by cheebsco** [comment] 2015-11-28 16:04
@Jp5243 to add 32bit support for your os
sudo dpkg --add-architecture i386
sudo apt-get update

**Comment by Jp5243** [comment] 2015-11-28 17:41
@cheebsco I executed the commands you posted, still does not work. I do not know if they are 32 or 64 bit.

**Comment by cheebsco** [comment] 2015-11-28 18:31
Do you have any logs, like output_log.txt files from these games? if so, use pastebin.com and send me the link.

**Comment by Jp5243** [comment] 2015-11-28 19:07
The only log I could find was in the folder for Mount and Blade: Warband. http://pastebin.com/EZUbkQWL

**Comment by Jp5243** [comment] 2015-11-28 19:08
Well, the only log that might be related to the issue. There are other logs, but they are mostly changelogs.

**Comment by cheebsco** [comment] 2015-11-28 20:45
@Jp5243 sudo apt-get install libxrandr2:i386 libglu1-mesa:i386 libxcursor1:i386

**Comment by Jp5243** [comment] 2015-11-28 23:37
Didn't work.

**Comment by cheebsco** [comment] 2015-11-30 14:23
@Jp5243 Ensure you have a recovery disc. Take the time to have a backup.  have you tried going through the control panel in settings,  and check for any proprietary drivers. After which, update the system.

**Comment by Jp5243** [comment] 2015-11-30 14:58
@cheebsco  I'm sorry, but I'm not very knowledgeable about the inner workings of these things. Could you explain that in a little more detail? How much do I need to backup, where exactly do I check for proprietary drivers and what exactly do you mean by updating the system?

**Comment by cheebsco** [comment] 2015-11-30 15:18
@Jp5243 https://launchpad.net/systemback
Read about this software and understand before doing anything major with your drivers. I recommend this, because fiddling with drivers can work magic or break stuff. It is easy to restore a system from disc, than starting terminal and fixing from command line. 

To understand the nature of the issue.
GLEW initialization failed.
This is related to OpenGL. As mentioned by Tele42, you have an issue with Drivers not communicating properly.

**Comment by Jp5243** [comment] 2015-11-30 19:43
@cheebsco OpenGL straight up does not work. Is this the reason it's not working?

**Comment by cheebsco** [comment] 2015-12-02 17:38
It appears to be the main issue.

**Comment by kisak-valve** [comment] 2019-02-08 14:30
Hello @Jp5243, your issues were from poor hardware support. There's a chance you could get more things running with `LIBGL_ALWAYS_SOFTWARE=1 %command%` in the game's launch options, but regardless, anything that runs would have underwhelming performance.

Closing as this is a hardware issue.

**Closed by kisak-valve** 2019-02-08 14:30 UTC
Labels: reviewed

**Comment by olgsh** [comment] 2020-12-19 19:05
Run steam from terminal, try to launch the game that crashes, and read the terminal output.
For me it was "Failed to load libSDL2_ttf-2.0 (run "sudo apt install libsdl2-ttf-2.0-0" on Ubuntu)" and it solved my problem
