### ISSUE TITLE
Steam client full redownloads shader pre-cache content of games on an SD card when cards are swapped

### ISSUE THREAD

**Issue by nex86** [ValveSoftware/steam-for-linux#8823] opened 2022-10-02 09:27 UTC
I'm getting very annoyed by having to download Shader Cache for my games every single day. 
Some games even have several gigabytes of shader cache to download on a daily basis.
It's especially annoying when I'm on the go and don't always have good internet.

So isn't there a way to just disable shader cache updates and use the locally stored cache that is already downloaded?

I know there is a setting to "set updates on hold until the game is launched" but thats not the solution as it tries to update the shaders when I launch the game.
I just want to completely stop shader cache updates until I want it to.

I know there also is a setting in steam settings to disable shader pre-caching. but wouldn't that also delete the cache that is already stored on disk?

**Comment by kisak-valve** [comment] 2022-10-02 12:40
Hello @nex86, this issue is already being tracked at #6486 / #7519. Closing as a duplicate.

Yes, the checkbox which disables the shader pre-caching subsystem also frees the storage used by the shader cache.

**Comment by kisak-valve** [comment] 2022-10-02 12:48
Out of mild curiosity, which games are you seeing repeated gigabytes of downloads to Steam's shader pre-cache? When looking at Steam's download queue, under the progress bar, the left number is the download progress (interesting), and the right number is Steam's progress of delta patching the files on disk (not particularly interesting).

**Comment by nex86** [comment] 2022-10-02 14:08
well almost all of my games, with Devil May Cry being the largest with downloading 6GB..

**Comment by kisak-valve** [comment] 2022-10-02 14:11
Can you share a log of that next time you see it? Should be found at `~/.steam/root/logs/shader_log.txt`.

**Comment by nex86** [comment] 2022-10-02 14:14
sure can do, but now it already downloaded most of it.

**Comment by nex86** [comment] 2022-10-03 16:55
> Can you share a log of that next time you see it? Should be found at `~/.steam/root/logs/shader_log.txt`.

this is from today when I turned my Steamdeck on.

**Comment by kisak-valve** [comment] 2022-10-03 17:32
Thanks, just to confirm, did you toggle the shader pre-caching setting shortly before gathering this log?

To my eyes, this looks like a full download of all shader pre-cache content, including transcoded videos as if there was nothing there to incrementally update.

**Comment by nex86** [comment] 2022-10-03 17:41
> Thanks, just to confirm, did you toggle the shader pre-caching setting shortly before gathering this log?
> 
No I did not.
But I played games from my other sd card yesterday before switching back to my 1TB card.

**Comment by kisak-valve** [comment] 2022-10-03 18:36
Let's re-open this issue report and focus on the Steam client losing track of shader pre-cache content related to swapping SD cards.

**Comment by nex86** [comment] 2022-10-04 06:55
what I suspect is it only does it when you swap sd cards when its powered off.
when you hot swap them, it doesn't seem to do it.

**Comment by Walaryne** [comment] 2022-10-26 12:56
Hi, wanted to add my bit from the closed issue. I feel like this might be down to the Steam client's hardware detection for invalidating the shader cache. Restarting the Steam client after swapping two SD cards seems to yield the same results. It is also not limited to the shader cache, and does the same for the Steamworks Common Redistributables (when they're on internal storage).
Only other idea I have is that it may not be the hardware detection, but rather Steam detecting these games are missing from the drive, and clearing the shader cache/invalidating it so that the space is not wasted. Since I have limited internet access I'd love to help in any way to see the resolved.

**Comment by do-kevin** [comment] 2023-01-11 00:02
I am also hotswapping microSDs as well. I like to keep the SSD reserved only for shaders and put my games on the microSDs. Everytime I swap, the games have to download the shader cache again.

Can't the Steam Deck just keep and re-use the shader cache everytime the user hotswaps?

**Comment by EverydayGamer30** [comment] 2023-01-26 10:07
I just noticed this the other day and it's pissing me off. My steam deck keeps deleting and re-downloading the Steamworks Common Redistributables which is 400MBs for one SD card and 900MBs for the other. I have looked all over the internet for a solution and these forums seem to be the only ones that even talk about it, and they seem the be dead ends. It would seem simple enough for the Steamworks Common Redistributables to stay on the main drive and not delete themselves. The only current solution is upgrading the internal drive to the biggest nvme 2230 and biggest SD card so you don't have files being deleted between SD card swaps. I am hoping a solution can be found as it currently makes this device similar to a trash cloud gaming handheld. I made this account just to comment on this forum and will try to respond if any replies ever come.

**Comment by perroboc** [comment] 2023-07-13 22:25
This is partially fixed in the latest (beta) release. Steam doesn't redownload shaders when hotswapping SD cards, but it does download the Steamworks Common Redistributables.

Since it seems to be a different issue, I've since created it in #9847

**Comment by kisak-valve** [comment] 2023-08-25 17:36
Closing per the last comment.

**Closed by kisak-valve** 2023-08-25 17:36 UTC
Labels: Steam client, Need Retest, Distro Family: SteamOS

**Comment by Gooby135** [comment] 2023-10-09 03:20
I'm having this same issue.  I've formatted the sd card, tried ejecting from the Storage menu, swapping when off.  Every time it seems to trigger a redownload of all the shader precache of games installed on the SD card .  I'm on the latest beta release and the issue is not fixed.

**Comment by gotgenes** [comment] 2023-11-26 16:15
There seems to be a regression and reemergence of this bug in the latest stable release, 3.5.7. Swapping the micro SD card, then restarting the Steam Deck, will cause the Deck to re-download the pre-cached shaders for the games on the micro SD card that was inserted.
