### ISSUE TITLE
Steam does not tell system not to sleep if using Xbox 360 controller in games

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4229] opened 2016-01-03 08:44 UTC
I was racing in GRID Autosport and then my system shuts off my screens; I had to push a key on my keyboard to turn the screens back on. This is normal for an idle system; except, my system was not idle.

I'm guessing a few things could be occurring here:
- Steam client isn't telling my system not to sleep/standby/turnoff screen.
- The game is not telling my system not to sleep/standby/turnoff screen.
- XFCE does not detect the controller and tell the system not to sleep.

Using Mint 17.2 with XFCE.

**Comment by kisak-valve** [comment] 2019-02-22 21:40
Duplicate of #1693.

**Closed by kisak-valve** 2019-02-22 21:40 UTC
Labels: reviewed
