### ISSUE TITLE
Dualshock4 + Rocket League -> crash

### ISSUE THREAD

**Issue by pshem** [ValveSoftware/steam-for-linux#6266] opened 2019-05-11 20:13 UTC
#### Your system information

* Steam client version (build number or date): 1556574584
* Distribution (e.g. Ubuntu): Peppermint 8 (Xubuntu 16.04 with a different layout)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I have Rocket League installed. It works fine, but controllers seem to cause it trouble. I usually play with a Steam Controller, and it works. It also works fine with a mouse and a keyboard. Immediately before and after the crash described below, I was fully able to play with a keyboard and a mouse.

When visiting relatives, I tried to use a Dualshock 4 controller(from a PS4). However, when a DS4 controller was plugged in(via USB), RL immediately crashed, taking Steam with it. Below is the key part of the terminal output for the crash(full stdout in a [gist](https://gist.github.com/pshem/f3b9284f41e27a2ab2d7a9e8f85ecca0)):

```bash
../common/pipes.cpp (766) : CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected
../common/pipes.cpp (766) : Fatal assert failed: ../common/pipes.cpp, line 766.  Application exiting.
```
I am also including the crash and assert files from /tmp/dumps: [rocket_league_crash.zip](https://github.com/ValveSoftware/steam-for-linux/files/3169435/rocket_league_crash.zip). If there is anything more I could provide, let me know

#### Steps for reproducing this issue:

1. Plug in a Dualshock4 Controller (from a PS4) 
2. Launch Rocket League (`steam steam://rungameid/252950` from the terminal)
3. Rocket League & Steam both crash

**Comment by pshem** [comment] 2019-05-13 16:58
Steam Input was "forced on". After setting it to "forced off" in the launch options(`right click on the game` > `properties` > `Steam Input per game setting`, the game works fine. Does that still make it a bug, or should I close it?

**Comment by kisak-valve** [comment] 2019-07-19 14:20
Hello @pshem, can you check if you're still experiencing this issue on an up to date system?

"Fix crash caused by audio cards with no active port set" in the [2019-07-16](https://store.steampowered.com/news/52467/) may have had an effect for Dualshock 4 users.

**Comment by pshem** [comment] 2019-07-25 18:40
I'm afraid I won't have access to a Dualshock 4 controller until Christmas. Should I set a calendar event, or should we just close it?

**Comment by kisak-valve** [comment] 2019-08-30 19:53
Thanks for the feedback. I'm going to close this as fixed and if you find this is not the case, let me know and I can re-open.

**Closed by kisak-valve** 2019-08-30 19:53 UTC
Labels: 3rd party game, General controller / Steam Input, Need Retest
