### ISSUE TITLE
Shift key remains pressed after losing focus

### ISSUE THREAD

**Issue by tkerber** [ValveSoftware/steam-for-linux#3451] opened 2014-08-25 12:54 UTC
If the shift key is pressed when steam loses focus, and released before it regains focus (e.g. a key combination including shift which moves windows around), steam behaves as though the key was never released.

The result is that clicking on games in the library results in multiple games being selected instead of the desired game, and clicking on links opens them in a new window.

Problem also occurs to a lesser extent with the control key.

**Comment by sizeofbool** [comment] 2015-02-18 18:02
This bug is affecting me as well.
OS: Debian 8 GNU\Linux (jessie) x86_64
Desktop Environment: xfce4
Display Manager: LightDM

**Comment by wayzhc** [comment] 2015-12-09 16:57
Is there any kind of workaround for this? Ctrl and Shift gets constantly "stuck" when using steam overlay. It's really annoying bug.

**Comment by sizeofbool** [comment] 2015-12-10 08:46
I've changed Steam In-Game Overlay key to "F4" to workaround this issue. I got used to it and found it more convenient to use.

**Comment by duck57** [comment] 2016-01-01 03:23
I'm pretty sure this is the same bug I run into when using Steam under Mac OS.  Very annoying.  There is absolutely no excuse for this to have been an issue in the first place.

**Comment by LeonardKoenig** [comment] 2016-03-31 13:51
It's still there but you can basically just press shift again and exit the focus and everything is ok again.

**Comment by Unaccounted4** [comment] 2016-05-05 23:15
Chalk me up, as well.

Running Fedora 23 64bit with LXDE.

For me pressing right shift then left shift seems to "release" it.

**Comment by Cynerd** [comment] 2016-05-20 22:55
Happens to me all the time, when I move steam window to other virtual desktop by shortcut with shift in i3. This is really annoying. Pressing shift again fixes it, but I hate seconds when my mind doesn't known what is happening.

Anyway I think that steam client is storing key for shift and other modifier keys in some internal variable. They should reset all states when they get FocusOut event. Or better check state in X of these keys on every key press. I don't know what library they use to communicate with X, but don't tell me that it is too hard to fix this.

**Comment by errclman** [comment] 2016-05-26 18:12
Still happens when i using Shift button. Fedora 24 64-bit, Gnome Shell.

**Comment by MikkyX** [comment] 2017-06-13 08:40
I get this issue on macOS as well. If I open Steam, go away and do something else, every game I click on is added to selection as if I have Ctrl / Cmd held down. I have to roll my fingers across Ctrl / Cmd / Option to make it behave properly.

**Comment by kaadmy** [comment] 2017-08-15 17:42
Getting this issue on Arch Linux with i3wm, it's annoying but I can deal with it. Is any fix going to happen any time soon?

**Comment by nightsky30** [comment] 2018-08-22 00:27
Seeing this as well with the latest Steam Client Beta.

**Comment by Rabcor** [comment] 2018-09-25 06:44
4 years and we still have this issue.

**Comment by AlexTwo** [comment] 2019-02-28 21:29
Hmm, Still happening.
Arch Linux 4.20.12 
I3-gaps
Pressing shift again temporarily solved this issue

**Comment by Rabcor** [comment] 2019-03-01 15:22
I managed to connect this issue to the keyboard shortcut I was using to change workspaces, I can't remember exactly, but I think I was using Ctrl+Shift+F1-F6, I changed it to Ctrl+Alt+1-6 and the issue never happens anymore.

**Comment by chutchatut** [comment] 2019-04-15 07:05
Still happening
Ubuntu 18.10

**Comment by Rabcor** [comment] 2019-05-01 05:09
I noticed that in my case this was happening because of a macro/key combination I used to switch desktops, e.g. if  I switched to/from the desktop steam is on with my keybinds I got this issue, but if I used the mouse I didn't.

Digging a little deeper I found that it was the key combination, I can't remember exactly what combination it was (something like ctrl+shift+f1-f6 or alt+shift+f1-f6) but after changing it to not use shift in the combination for switching desktops, I no longer have this issue.

**Comment by Spass1966** [comment] 2019-05-08 08:31
Also getting this on NixOS

**Comment by h1z1** [comment] 2019-06-27 09:09
Weird,, though this ticket goes back quite a long time I've only noticed it after the last update-ish.  Shift most certainly is not being held down, the only "fix" I've found is restarting steam.   Doesn't happen all the time either.

**Comment by gburgwardt** [comment] 2019-11-12 01:56
Getting this on ubuntu 18.04, nvidia drivers

**Comment by szmarczak** [comment] 2019-11-16 19:44
The issue is easy to reproduce:

![Peek 2019-11-16 20-43](https://user-images.githubusercontent.com/36894700/68998389-d987a300-08b1-11ea-9a2a-479fa32a64b2.gif)

**Comment by szmarczak** [comment] 2019-11-16 20:46
It also happens when switching from CS:GO to Steam Chat (through shift tab).

**Comment by winny-** [comment] 2019-12-21 23:04
Happening on Gentoo, easy to highlight entire web pages in the steam browser on accident.

[System information](https://gist.github.com/winny-/34f51cb4a7572176feb439192c8f700e)

**Comment by arrowgent** [comment] 2020-03-29 11:09
long time issue?

wanted to report and/or find a fix for this

this did not always happen, now it seems to be a common problem.

**Comment by sizeofbool** [comment] 2020-03-29 13:00
I suspect this is a problem with (some?) X server\window managers, because I get similar "Shift key" and scrolling problems with other GUI apps like Firefox and text editors, so Steam Client is not the root cause for this behavior.
Probably, this is why this issue is taking so long to be fixed.

**Comment by szmarczak** [comment] 2020-03-29 14:40
> I suspect this is a problem with (some?) X server\window managers, because I get similar "Shift key" and scrolling problems with other GUI apps like Firefox and text editors, so Steam Client is not the root cause for this behavior.

I strongly disagree. I'm using Solus 4.1. It works everywhere else but the Steam app.

**Comment by Cynerd** [comment] 2020-03-29 15:52
> I suspect this is a problem with (some?) X server\window managers, because I get similar "Shift key" and scrolling problems with other GUI apps like Firefox and text editors, so Steam Client is not the root cause for this behavior.

In this case it is Steam Client's fault or fault of some library it uses for sure. I even wrote my suspicion here four years ago. X server sends key press and release events. That is how application knows what you are typing. The problem is that if you use key shortcut to change focus such as win+cursor key then application receives win key press event and with press of cursor key the focus is changed so it receives FocusOut event. It won't receive win key release event.
How X input should be handled in this case is that application should use key modifiers sent with key press/release event that contains info about shift key. Application should not track key press and release on its own because modifying key can be pressed when window is not focused and such event is not propagated to that specific application. It is invalid usage of X API.

This issue is present and reliably reproducible on Linux client from beginning. I was able to reproduce it with Gnome, KDE, awesome and i3. You just have to use shortcut that includes shift key to change focus and then return to Steam client with shift not pressed and that is it.

**Comment by ashtonx** [comment] 2021-01-24 22:31
7 years later still an issue ;/ any workarounds ?

**Comment by jimmy-print** [comment] 2021-02-24 10:13
> 7 years later still an issue ;/ any workarounds ?

I just shift-clicked again on one of the games and it fixed the problem.

**Comment by prismz** [comment] 2021-07-10 16:08
Still a problem on Debian 11. My dwm keybind to move windows to another monitor includes the shift key, and as others have mentioned Steam doesn't seem to properly handle X events.

**Comment by h1z1** [comment] 2021-07-26 06:38
Not to bump an old thread but just realized no one reported what keyboards were in use nor if using ps/2  / console (not the sony kind) or USB.  There are keyboards out there that do not work well or at all with multiple key combinations.  Simple two key combinations work (ctrl-c/v for example), but anything more like requiring the hand of Spock, will not, especially gaming keyboards.   You can use something like the X event spy (xev) to see exactly what X is at least telling Steam.  xwinfo -events will show what steam is listening for.

Fun fact - such keyboards are not usable in several Valve games I've tried.   The hardware lacks it's own auto repeat (technically it's the dumb ps2->USB dongle) - so you're able to move for example but any modifier stops it.  ie Strife jumping is impossible.  Setting repeat in X is pointless as Valve does their own thing.

**Comment by laNuez** [comment] 2021-08-16 04:10
> ![Peek 2019-11-16 20-43](https://user-images.githubusercontent.com/36894700/68998389-d987a300-08b1-11ea-9a2a-479fa32a64b2.gif)

This was driving me nuts i thought my keyboard was malfunctioning. 
Please look into it

**Comment by AmberABit** [comment] 2022-01-13 05:13
This problem has been badly exasperated with the ability to shift-click to select multiple games. Half the time when I go into steam now to play a game, I spend double the time that I used just because I need to fix this before I can even hit the play button.

**Comment by efield6568** [comment] 2022-03-08 01:44
As a quick fix, I noticed that as the issue is caused by having pressed the Shift key and left focus, if you are out of focus and press shift, then focus steam and release the issue goes away.

**Comment by rupansh** [comment] 2022-03-19 16:33
its been 8 years

**Comment by krompus** [comment] 2022-11-06 21:40
Issue persists, and the Steam Overlay affected by a similar issue: I have it bound to Alt+Home (I have both of these keys on my mouse, I swear it's comfy lol), and when I open the Steam Overlay with Alt+Home and then close it with Escape, the game still acts like Alt is being held, so I am unable to jump (Space bar). Seen in Mordhau and Borderlands 3 for example. No problem when I close it with a repeated Alt+Home. Should I create a new issue for that?

**Comment by r3k2** [comment] 2022-11-06 21:59
yeah this still happens on GNU/Linux

**Comment by MacTavishAO** [comment] 2022-12-21 00:29
Any kid born on the day this issue was created goes to second grade.

**Comment by Splarkszter** [comment] 2023-01-20 15:58
No way this is not even solved. @valve do you want me to stop spending money on your crap platform? do you really want that?

**Comment by Splarkszter** [comment] 2023-01-20 16:00
No way this hasn't been fixed in 8 damm years. Ok then i'll stop spending my money here and start migrating to GoG faster than i thought.

**Comment by ashtonx** [comment] 2023-01-20 16:14
> No way this hasn't been fixed in 8 damm years. Ok then i'll stop spending my money here and start migrating to GoG faster than i thought.

As sad as it is, steam is still one digital store with best support on linux. I'm guessing you didn't play much with gog on linux.

**Comment by namtabmai** [comment] 2023-01-21 13:35
> No way this hasn't been fixed in 8 damm years. Ok then i'll stop spending my money here and start migrating to GoG faster than i thought.

That's odd, because Linux users have been asking GOG to bring out a Linux supported Galaxy client for almost as long as this bug has been around.

**Comment by Newbytee** [comment] 2023-04-28 20:24
I can't seem to reproduce this any more with the new beta client. Can anyone else confirm? My old reproducer no longer exists (used to do it with the GNOME screenshot shortcut, but that's been reworked since), so I had to try to come up with a new one but I can't reproduce it any more.

**Comment by MacTavishAO** [comment] 2023-04-29 00:31
> I can't seem to reproduce this any more with the new beta client. Can anyone else confirm? My old reproducer no longer exists (used to do it with the GNOME screenshot shortcut, but that's been reworked since), so I had to try to come up with a new one but I can't reproduce it any more.

I can confirm it's fixed here with the beta client.

**Comment by Soapsuds** [comment] 2023-04-30 07:55
With the beta client I haven't had this happen, but have triggered it inside the overlay. Not sure if overlay issues are in scope for this issue though.

**Comment by comminux** [comment] 2023-05-29 10:45
This problem does not happen on Sway (Wayland) with the beta version of Steam Sneak Peek

**Comment by dsalt** [comment] 2023-05-29 11:07
Not happening here (Xfce4/X, Steam beta). Looks fixed as a consequence of the UI now being essentially all browser windows.

As for whether it happens with the overlay – seen things happen here, usually the game thinking that the overlay hot-keys are still pressed. Could be the overlay ‘eating’ the key-up events, could be due to how the game handles keypresses…

**Comment by Splarkszter** [comment] 2023-06-09 00:07
> Could be the overlay ‘eating’ the key-up events, could be due to how the game handles keypresses

Yes, highly possible, I saw that some games are specially sensitive to this, probably to fight against dumb auto-clickers that only send `KEY{DOWN}` and no `KEY{UP}` like the one that Razer utilizes on their mice.

**Comment by kisak-valve** [comment] 2023-07-22 01:34
Closing per the last several comments.

**Closed by kisak-valve** 2023-07-22 01:34 UTC
Labels: reviewed, Steam client, Need Retest
