### ISSUE TITLE
Incorrect scolling behavior in Linux client.

### ISSUE THREAD

**Issue by Aimela** [ValveSoftware/steam-for-linux#4644] opened 2016-10-02 15:05 UTC
#### Your system information
- Steam client version: Current Beta client
- Distribution (e.g. Ubuntu): Arch Linux with Cinnamon DE(however, issue was also observed on Linux Mint)
- Opted into Steam client beta?: [Yes/No] Yes
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

After and update a few month ago which mentioned a change to scroll behavior, scrolling in the Linux client has been instant, instead of smooth scrolling behavior. The Windows client does not show this issue, only the Linux client.
#### Steps for reproducing this issue:

Just scroll anywhere in the desktop interface of the Steam Linux client.

**Comment by squatch04** [comment] 2016-11-13 14:19
I have the same issue. Only difference is i'm running Elementary OS Loki.

**Comment by parkerlreed** [comment] 2016-12-22 01:55
Same here. It's really jerky. Latest client beta on Arch Linux with Gnome.

https://my.mixtape.moe/jbhxmq.mp4

**Comment by mlms13** [comment] 2017-01-01 16:37
Same on Ubuntu 16.04. There was a time when scrolling was fine, but something changed (maybe early-to-mid-2016?) and now scrolling is really choppy. It's bad enough that I've almost completely stopped browsing the store.

**Comment by xFoxBox** [comment] 2017-01-10 23:40
I am also having this problem. I even tested: synclient VertScrollSpeed=-1000 to slow the speed of scrolling wayyyyy down... and all it does it make me have to scroll my mouse a lot until the page magically JUMPS a huge step down.

**Comment by DougTy** [comment] 2017-02-25 02:16
I'm also getting this with Arch on Xfce. Scrolling is **waaaaaay** too fast.

**Comment by Ragmaanir** [comment] 2017-02-25 03:14
I have the same problem. When moving the scroll-wheel by one unit the screen jumps about 120 pixel. This makes scrolling in lists really confusing because you cannot see easily where your previous focus was. I am on Linux Mint 18 Cinnamon(3.0.7) 64 bit. Steam API v017, built Jan 19 2017.

**Comment by aidenmdcurtis** [comment] 2017-06-23 17:38
On ElementaryOS Loki 0.4 - I'm using imwheel for my mouse's scrolling configuration and I noticed that every time I move the scroll wheel enough for one movement on any other app, it moves for two movements on Steam. This makes scrolling on the Friends List unusable as you'll scroll once and it'll move past names that weren't even on the window in the first place.

**Comment by thecosmicfrog** [comment] 2017-07-23 22:22
+1 on this. Scrolling behavior on Linux is... uncomfortable? Pretty much the best way I can describe it. Jumps are far too big and scrolling through the store is very difficult.

**Comment by Chiitoo** [comment] 2017-12-07 11:39
@thecosmicfrog,

While it might be related, what you're speaking of, seems to be more like this one:

Scrolling the store window with mouse wheel flips too much #4722

And indeed, it would be very nice if Steam could respect the settings of the OS it's running on, and at least optionally, do it smooth-like.  :]

**Comment by Ragmaanir** [comment] 2017-12-08 07:32
@Chiitoo,

for me this scrolling behavior is everywhere (store, community, library/tools, friends list). The store is just the most annoying and important part. I dont know, but i guess the issue is more general than the store-page issue and that there is/might be a general solution.

**Comment by dpanter** [comment] 2018-01-08 13:37
It's been this way as long as I can remember, did it ever work properly?

Anyway. Scrolling in the game Library list is about 5 lines (i.e. 5 game titles) per mouse wheel tick and anywhere else is scrolling double that (or even a bit more) per mouse wheel tick.
Tested Store/Featured, Store/News, Community/Home, Community/Workshop, Community/Discussions, any Profile page and any products own store page. Only the Library seems to work reasonably correct.

Stuff: Debian sid, KDE 5 Plasma, AMD RX580 Mesa, non-beta Steam client.

**Comment by LukaPrebil** [comment] 2018-02-04 12:04
Same here, on Elementary 0.4

**Comment by h1z1** [comment] 2018-02-10 02:22
165Hz monitors yet, always thought this was due to the mouse but I've since gone through 3 different mice with the same problem.  Scrolling is pretty horrid coupled with zoom because the fonts lack HDPI.  I know it's in beta, that has other problems though.

**Comment by parkerlreed** [comment] 2018-06-13 18:07
Still experiencing this too https://my.mixtape.moe/xprjgm.mp4

**Comment by scorninpc** [comment] 2018-06-22 16:45
The same on Deepin and Debian 9/Gnome 3

**Comment by TomokoK** [comment] 2018-08-26 16:20
Same issue on Void/Openbox

**Comment by Granddave** [comment] 2018-11-18 11:32
Same in Debian 9 KDE Plasma 5.8.6.

**Comment by Plagman** [comment] 2018-11-29 01:14
Incorrect scroll offset will be fixed in the next major client Beta. However, this doesn't mean 1:1 smooth scrolling when using touchpads/etc as of yet.

**Comment by bradleypariah** [comment] 2019-01-02 19:42
Good to know there is a fix incoming for trackpads.  I'm using Kubuntu 18.04 on an HTPC, and I control desktop apps with a Logitech wireless K400.  Scrolling in Steam is still a nightmare.

**Comment by kisak-valve** [comment] 2019-02-07 21:54
Closing per "Fixed incorrect mouse wheel scrolling offsets" in the [2019-02-01](https://store.steampowered.com/news/48091/) Steam client update.

**Closed by kisak-valve** 2019-02-07 21:54 UTC
Labels: Steam client, reviewed

**Comment by morfyum** [comment] 2022-02-12 18:32
Same isssue in 2022, on Fedora Workstation 35  :/
Btw SteamDeck is coming, but Steam is ...

**Comment by litLizard69** [comment] 2022-07-15 22:41
This issue is still not fixed..

**Comment by kisak-valve** [comment] 2022-07-15 23:16
Hello @morfyum, @litLizard69, the investigation on this issue report concluded in 2019 and in a quick test, there isn't a regression. Please open a new issue report with exactly what behavior you're seeing and your system information.
