### ISSUE TITLE
Portal 1 's font could not display properly on Linux

### ISSUE THREAD

**Issue by imsuwj** [ValveSoftware/steam-for-linux#4162] opened 2015-11-29 05:04 UTC
OS: ArchLinux
I have installed ttf-liberation,wqy-microhei and wqy-zenhei.
No matter what language I set , the problem still.
Even English display as a square symbol.
![Language](https://cloud.githubusercontent.com/assets/2463831/11455419/8ea4494e-9699-11e5-8910-f1a402aab383.png)

![Snapshot screen](https://cloud.githubusercontent.com/assets/2463831/11455406/ea83452c-9698-11e5-9d92-dc2cf834423f.png)

Dota2 Reborn and TF2 do not have any problems with font on my system.

Do I need any other font ?

**Comment by imsuwj** [comment] 2015-11-29 05:07
Even English display as a square symbol.

**Comment by Tele42** [comment] 2015-11-29 13:41
I know valve assumes all systems have mscorefonts, but I don't think that will help with your native language.

**Comment by imsuwj** [comment] 2015-12-01 13:33
Then I change the Steam 's language to English and start Portal.The text display correctly  But whatever language I set(Portal,not Steam) , the text still show as English.

**Comment by Oxalin** [comment] 2015-12-20 18:12
@imsuwj , if I understand correctly, your first screenshot is from the game's language settings, which causes problem in the game (squares are shown). However, if you set the global Steam's language, then it is properly displayed. And Portal will stick to Steam's language whatever you set for Portal's language. In other words, Portal uses Steam's language setting instead of its own language setting.

There are two problems then:
- The first one, Portal is not using its own language setting. This one is a bug.
- The second, Portal is looking for a missing font in your native language (Chinese or Japanese?): if it was found, the squares would be replaced by characters. If we can provide the missing font to Portal, this should fix it.

On Arch, there is a package in AUR called steam-fonts. Could you install it?

Also, if you launch steam from a terminal, is there any ouput error related to fonts?

**Comment by imsuwj** [comment] 2015-12-21 13:58
@Oxalin When the Steam 's language was setted to Chinese(Non English) and the Portal 's language was setted to English , text still displayed as squares .
I installed steam-fonts (AUR).Then changed the steam 's language to Chinese and started portal . Here is the terminal log.
```
Using breakpad crash handler
Setting breakpad minidump AppID = 400
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198160822291 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198160822291
Did not detect any valid joysticks.
 failed to dlopen /home/userxxx/.local/share/Steam/steamapps/common/Portal/bin/stdshader_dbg.so error=/home/userxxx/.local/share/Steam/steamapps/common/Portal/bin/stdshader_dbg.so: cannot open shared object file: No such file or directory
 failed to dlopen /home/userxxx/.local/share/Steam/steamapps/common/Portal/bin/stdshader_dbg.so error=/home/userxxx/.local/share/Steam/steamapps/common/Portal/bin/stdshader_dbg.so: cannot open shared object file: No such file or directory
 failed to dlopen stdshader_dbg.so error=stdshader_dbg.so: cannot open shared object file: No such file or directory
 failed to dlopen /home/userxxx/.local/share/Steam/steamapps/common/Portal/bin/stdshader_dx6.so error=/home/userxxx/.local/share/Steam/steamapps/common/Portal/bin/stdshader_dx6.so: cannot open shared object file: No such file or directory
 failed to dlopen /home/userxxx/.local/share/Steam/steamapps/common/Portal/bin/stdshader_dx6.so error=/home/userxxx/.local/share/Steam/steamapps/common/Portal/bin/stdshader_dx6.so: cannot open shared object file: No such file or directory
 failed to dlopen stdshader_dx6.so error=stdshader_dx6.so: cannot open shared object file: No such file or directory
 failed to dlopen /home/userxxx/.local/share/Steam/steamapps/common/Portal/bin/stdshader_dx7.so error=/home/userxxx/.local/share/Steam/steamapps/common/Portal/bin/stdshader_dx7.so: cannot open shared object file: No such file or directory
 failed to dlopen /home/userxxx/.local/share/Steam/steamapps/common/Portal/bin/stdshader_dx7.so error=/home/userxxx/.local/share/Steam/steamapps/common/Portal/bin/stdshader_dx7.so: cannot open shared object file: No such file or directory
 failed to dlopen stdshader_dx7.so error=stdshader_dx7.so: cannot open shared object file: No such file or directory
 failed to dlopen /home/userxxx/.local/share/Steam/steamapps/common/Portal/bin/stdshader_dx8.so error=/home/userxxx/.local/share/Steam/steamapps/common/Portal/bin/stdshader_dx8.so: cannot open shared object file: No such file or directory
 failed to dlopen /home/userxxx/.local/share/Steam/steamapps/common/Portal/bin/stdshader_dx8.so error=/home/userxxx/.local/share/Steam/steamapps/common/Portal/bin/stdshader_dx8.so: cannot open shared object file: No such file or directory
 failed to dlopen stdshader_dx8.so error=stdshader_dx8.so: cannot open shared object file: No such file or directory
[1221/214237:ERROR:resource_bundle.cc(411)] Failed to load /home/userxxx/.local/share/Steam/steamapps/common/Portal/cef_gtk.pak
Some features may not be available.
[1221/214237:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system DOES NOT support the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_EXT_texture_sRGB_decode: AVAILABLE
GL_NVX_gpu_memory_info: UNAVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_MAX_SAMPLES_EXT: 8
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 3400 MHz, Processor: GenuineIntel
GlobalMemoryStatus: 4294967295
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 3400 MHz, Processor: GenuineIntel
GlobalMemoryStatus: 4294967295
IDirect3DDevice9::Create: BackBufWidth: 1920, BackBufHeight: 1080, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
GL sampler object usage: ENABLED
GL prefer MapBufferRange: YES

 ##### swap interval = 0     swap limit = 1 #####
Could not load program cache file glbaseshaders.cfg
Could not find base GL shader cache file                                                                                                                                                     
CGLMShaderPair::SetProgramPair: Centroid masks differ at link time of vertex shader lightmappedgeneric_vs20 and pixel shader decalbasetimeslightmapalphablendselfillum2_ps20b!               
Loaded program cache file "glshaders.cfg", total keyvalues: 172, total successfully linked: 172                                                                                              
Precache: Took 6621 ms, Vertex 914, Pixel 682                                                                                                                                                
ConVarRef mat_dxlevel doesn't point to an existing ConVar                                                                                                                                    
Game.so loaded for "Half-Life 2"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000004) differs from mask derived from shader name (0x0000000C) for shader ps-file shatteredglass_ps20b ps-index 40 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000004) differs from mask derived from shader name (0x0000000C) for shader ps-file shatteredglass_ps20b ps-index 40 ps-combo 2
Unable to remove /home/userxxx/.local/share/Steam/steamapps/common/Portal/portal/gamestats.log!
Unable to remove /home/userxxx/.local/share/Steam/steamapps/common/Portal/portal/gamestats.log!
maxplayers set to 1
Error: Material "debug/debugluxels" uses unknown shader "DebugLuxels"
Error: Material "___fillrate_0" uses unknown shader "FillRate"
Error: Material "___debugnormalmap_1" uses unknown shader "DebugNormalMap"
Error: Material "___debugdrawenvmapmask_2" uses unknown shader "DebugDrawEnvmapMask"
Error: Material "___debugdepth_3" uses unknown shader "DebugDepth"
Error: Material "___debugdepth_4" uses unknown shader "DebugDepth"
Steam config directory: /home/userxxx/.local/share/Steam/steamapps/common/Portal/platform/config
CClientSteamContext logged on = 1
Hud element 'CMapOverview' doesn't have an entry 'overview' in scripts/HudLayout.res
JOY_AXIS_X:  mapped to Turn (absolute)
JOY_AXIS_Y:  mapped to Look (absolute)
JOY_AXIS_Z:  unmapped
JOY_AXIS_R:  mapped to Forward (absolute)
JOY_AXIS_U:  mapped to Side (absolute)
JOY_AXIS_V:  unmapped
Advanced Joystick settings initialized
Can't use cheat cvar cam_snapto in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_ideallag in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealdelta in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealyaw in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealpitch in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealdist in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealdistright in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_idealdistup in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar cam_collision in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_maxpitch in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_minpitch in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_maxyaw in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_minyaw in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_maxdistance in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_mindistance in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_orthowidth in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar c_orthoheight in multiplayer, unless the server has sv_cheats set to 1.
Unknown command "cl_thirdperson"
Unknown command "sv_backspeed"
Not playing a local game.

Console initialized.
--- Missing Vgui material vgui/servers/icon_replay
--- Missing Vgui material vgui/servers/icon_replay_column
Can't use cheat cvar fog_start in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar fog_end in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar fog_startskybox in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar fog_endskybox in multiplayer, unless the server has sv_cheats set to 1.
Can't use cheat cvar r_farz in multiplayer, unless the server has sv_cheats set to 1.

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/weapons/v_models/v_hands/v_hands.vtf
'cfg/motd.txt' not found; not loaded
'cfg/motd_text.txt' not found; not loaded
Requesting texture value from var "$basetexture" which is not a texture value (material: dev/bloomadd)
Requesting texture value from var "$basetexture" which is not a texture value (ma

```

**Comment by Sinihopea** [comment] 2016-01-23 03:26
This is an issue on Fedora too. Portal doesn't show Japanese characters no matter what I do. I can guarantee that I have all the proper fonts installed since e.g. Counter-Strike Source displays the Japanese characters just fine.

**Comment by wgjak47** [comment] 2016-02-26 15:56
I have the same problem, It show noting but Portal

**Comment by wangling12** [comment] 2017-12-26 05:04
Portal 2 also has this problem.The problem is that when the font is called, the English font is preceded by the Chinese font, even if the game language is set in Chinese. Dota2 had the problem before, but then they solved it. Before the official solution of this problem, users can disguise wqy fonts as Helvetica fonts for a temporary solution. But this may cause unforeseen consequences.

**Comment by kisak-valve** [comment] 2019-02-15 18:06
Closing as a duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/153 and https://github.com/ValveSoftware/Source-1-Games/issues/1939#issuecomment-269807338.

**Closed by kisak-valve** 2019-02-15 18:06 UTC
Labels: reviewed
