### ISSUE TITLE
steam client ignoring SIGINT signal

### ISSUE THREAD

**Issue by alemansec** [ValveSoftware/steam-for-linux#4771] opened 2016-12-21 20:22 UTC
#### Your system information

* Steam client version:1482214037
* Distribution (e.g. Ubuntu): Debian GNU/Linux Jessie x86_64 up-to-date
* Opted into Steam client beta?: [Yes/No] Yes & No (both afected)
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
steam client ignoring SIGINT signal

#### Steps for reproducing this issue:

start steam and send it the SIGINT signal (Ctrl C when started foreground, or kill -2 % jobid or kill -2 pid)

#### expected result :
proper steam client shutdown

#### obtained result:
nothing .. trapped and ignored signal ?!?!?!

**Comment by kisak-valve** [comment] 2016-12-21 21:10
This is effectively a duplicate of #3005.

**Closed by kisak-valve** 2016-12-21 21:10 UTC

**Comment by alemansec** [comment] 2016-12-21 21:25
SIGTERM and SIGINT are two different signals, hopefully devs won't forget to properly handle all signals instead of just fixing the SIGTERM signal handling (as suggested by your duplicate mark)
