### ISSUE TITLE
Steam crash on startup

### ISSUE THREAD

**Issue by Nuzgart** [ValveSoftware/steam-for-linux#5557] opened 2018-07-07 00:28 UTC
#### Your system information

* Steam client version (build number or date): 1.0.0.54 (installed from Mageia repositories)
* Distribution (e.g. Ubuntu): Mageia 6 (32 bit)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

When attempting to run Steam, it tries to update the client... And then, just crashes. Running it on a terminal gives off the following output:

```
Running Steam on mageia 6 32-bit
STEAM_RUNTIME is enabled automatically
Pins potentially out-of-date, rebuilding...
Found newer runtime version for 32-bit libdbus-1.so.3. Host: 3.14.10 Runtime: 3.5.8
Found newer runtime version for 32-bit libdbusmenu-glib.so.4. Host: 4.0.12 Runtime: 4.0.13
Found newer runtime version for 32-bit libpangox-1.0.so.0. Host: 0.0.0 Runtime: 0.3000.0
Found newer runtime version for 32-bit libGLU.so.1. Host: 1.3.1 Runtime: 1.3.8004
Found newer runtime version for 32-bit libgtk-x11-2.0.so.0. Host: 0.2400.31 Runtime: 0.2400.10
Found newer runtime version for 32-bit libSDL2-2.0.so.0. Host: 0.4.1 Runtime: 0.5.0
Installing breakpad exception handler for appid(steam)/version(1528497815)
Installing breakpad exception handler for appid(steam)/version(1528497815)
Installing breakpad exception handler for appid(steam)/version(1528497815)

(steam:18006): Gtk-WARNING **: Imposible encontrar el motor de temas en la ruta al _modulo: «adwaita»,
/usr/share/themes/Adwaita/gtk-2.0/main.rc:733: error: unexpected identifier 'direction', expected character '}'

(steam:18006): Gtk-WARNING **: Imposible encontrar el motor de temas en la ruta al _modulo: «adwaita»,
/usr/share/themes/Adwaita/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant

(steam:18006): Gtk-WARNING **: Imposible encontrar el motor de temas en la ruta al _modulo: «adwaita»,
/usr/share/themes/Adwaita/gtk-2.0/main.rc:733: error: unexpected identifier 'direction', expected character '}'

(steam:18006): Gtk-WARNING **: Imposible encontrar el motor de temas en la ruta al _modulo: «adwaita»,
/usr/share/themes/Adwaita/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
assert_20180707022026_1.dmp[18017]: Uploading dump (out-of-process)
/tmp/dumps/assert_20180707022026_1.dmp
/home/soser/.local/share/Steam/steam.sh: línea 876: 18006 Instrucción ilegal     (`core' generado) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20180707022026_1.dmp[18017]: Finished uploading minidump (out-of-process): success = yes
assert_20180707022026_1.dmp[18017]: response: CrashID=bp-93a6592a-7e3d-4e05-b2e1-5d9a02180706
assert_20180707022026_1.dmp[18017]: file ''/tmp/dumps/assert_20180707022026_1.dmp'', upload yes: ''CrashID=bp-93a6592a-7e3d-4e05-b2e1-5d9a02180706''

```
I've managed to workaround by running the Windows version of Steam through Wine, but when I try to do that, it fails to download any game- Message: "Steam content servers unreachable" 

#### Steps for reproducing this issue:

1. Install Mageia 6 (32 bit)
2. Install Nvidia drivers (420 or later)
3. Install Steam
4. Run Steam on a terminal

**Comment by kisak-valve** [comment] 2018-07-07 00:34
Hello @Nuzgart, what cpu does your system have?

**Comment by Nuzgart** [comment] 2018-07-07 00:43
Pentium IV, 3 Ghz

**Comment by kisak-valve** [comment] 2018-07-07 00:53
I suspect the issue is that SDL bundled with Steam currently requires SSE3 and this is already being tracked at #5164.

If `cat /proc/cpuinfo` has `pni` in the flags section for you cpu, we can investigate further, otherwise closing in favor of the existing issue report.

**Closed by kisak-valve** 2018-07-07 00:53 UTC
Labels: Distro Family: Mageia
