### ISSUE TITLE
queue customization ignores OS/machine filters

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#4552] opened 2016-07-16 02:06 UTC
#### Your system information

* Steam client version:as of today
* Distribution (e.g. Ubuntu): debian jessie x86
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
the queue customization select windows (ERK!) games, even if I'm on a linux box.

**Comment by Tele42** [comment] 2016-07-16 03:45
Duplicate of #4500.

**Comment by gdrewb-valve** [comment] 2016-07-16 04:01
Closing duplicate.

**Closed by gdrewb-valve** 2016-07-16 04:01 UTC
