### ISSUE TITLE
Chat window does not have tab on taskbar.

### ISSUE THREAD

**Issue by Kosyne** [ValveSoftware/steam-for-linux#4163] opened 2015-12-01 23:50 UTC
As the title says, chat does not have a tab on the taskbar. I can manually open a chat, click a notification, any of that, and a tab on the taskbar does not appear. Otherwise, chat works fine.
Steam, friends, and other windows to appear on the taskbar just fine, however. I have tried setting each chat to open in a new window, though that did nothing as well.

After googling, I found a few similar bugs, though they weren't quite the same. 

Screenshot of the issue. I have the main steam window minimized, and a chat window open, so there should be two tabs on the taskbar.
![Screenshot](https://cloud.githubusercontent.com/assets/356616/11518002/6ede5e22-9853-11e5-81ee-1ec2780339bb.png)

Fresh install of Linux Mint 18.3 beta - x64
Default WM (Cinnamon 2.8.6)

---

Ok, some more info.
I restarted steam, and was messaged by someone. The chat window popped up, and as did a tab.
 I then closed the tab and tried to open the chat window manually, no luck.
I received another message, and the tab still didn't appear.

So, it seems that it works for the first message you receive upon opening steam. If I close that window, however, there is no way to get the tab back.

**Comment by kajzersoze** [comment] 2015-12-16 12:58
Same problem here.

**Comment by Oxalin** [comment] 2015-12-20 18:19
@Kosyne , have you tried another window manager?

Gnome 3 doesn't have tabs in a taskbar, however each Steam windows appears individually when using Alt-Tab or Alt-# (depends of the behaviour). I could try under XFCE or KDE to see if the same problem appears. I'm trying to figure out if this is related to some window managers only.

**Comment by ExplosiveSilo** [comment] 2015-12-21 07:24
Okay guys, I had the same problem myself, turns out it's only cinnamon doing it, it works fine with XFCE and MATE (Which I am currently using).

**Comment by itzexor** [comment] 2015-12-23 00:40
I believe this problem is a combination of Steam initially generating the window with a null title and Cinnamon not handling a null value for this field since 2.8 when the thumbnail previews were added. 

I have opened an issue on the Cinnamon bug tracker with a patch that fixes it (may not be a good fix, but it does work). I have not experienced this bug with any other application or even any other type of Steam window. It only happens with chat windows. 

Here is the bug I opened on Cinnamon's bug tracker: https://github.com/linuxmint/Cinnamon/issues/4950

**Comment by itzexor** [comment] 2016-01-19 16:19
This is now fixed in the git version of Cinnamon, so it should work properly in the version.

**Comment by Oxalin** [comment] 2016-01-19 19:15
Once confirmed as fixed, could you close the issue?

**Comment by kajzersoze** [comment] 2016-01-19 19:29
Replacing applet,js from git isn't enough, are there changes in other files beside applet.js ?

**Comment by kisak-valve** [comment] 2019-02-15 18:08
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment] 2019-03-15 12:48
Closing pending feedback.

**Closed by kisak-valve** 2019-03-15 12:48 UTC
Labels: Need Retest, Window manager, reviewed
