### ISSUE TITLE
steam. while downloading games high disk activity

### ISSUE THREAD

**Issue by steamlinux** [ValveSoftware/steam-for-linux#3843] opened 2015-05-13 11:31 UTC
because of this problem with a download speed
![2015-05-13 14 26 22](https://cloud.githubusercontent.com/assets/11569159/7609560/8a403134-f97c-11e4-93c4-25c76cf0e7ba.png)
![2015-05-13 14 26 56](https://cloud.githubusercontent.com/assets/11569159/7609562/8d15d6a2-f97c-11e4-89c5-314aade3f304.png)

**Comment by MrSchism** [comment] 2015-05-13 11:55
Closing as dupe of #3450

**Closed by MrSchism** 2015-05-13 11:55 UTC
Labels: duplicate, Steam client
