### ISSUE TITLE
Trouble starting steam after update

### ISSUE THREAD

**Issue by bbarker** [ValveSoftware/steam-for-linux#5197] opened 2017-10-05 22:28 UTC
#### Your system information

* Steam client version (build number or date): 
Not sure, can't launch it! Based on output i think  it is 1507158695

* Distribution (e.g. Ubuntu): 
Ubuntu 17.04
* Opted into Steam client beta?: [Yes/No]
I don't think so, but again, how can I tell if I can't launch it? 

* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam won't launch. Seems to be an IPC issue. What is steam doing IPC with?

#### Steps for reproducing this issue:

```
brandon@brandon-750-170se:~/workspace/ProjectGists$ steam
Running Steam on ubuntu 17.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1507158695)
Installing breakpad exception handler for appid(steam)/version(1507158695)
Installing breakpad exception handler for appid(steam)/version(1507158695)
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
IPC error: LockMgrMutex failed to acquire SysMgrMutex
IPC error: LockMgrMutex failed to acquire SysMgrMutex
IPC error: LockMgrMutex failed to acquire SysMgrMutex
IPC error: LockMgrMutex failed to acquire SysMgrMutex
IPC error: LockMgrMutex failed to acquire SysMgrMutex
chrome_ipc_client.cpp (580) : Assertion Failed: !"Collided with existing master response stream"
Assert( Assertion Failed: !"Collided with existing master response stream" ):chrome_ipc_client.cpp:580

Installing breakpad exception handler for appid(steam)/version(1507158695)
assert_20171005182111_5.dmp[16387]: Uploading dump (out-of-process)
/tmp/dumps/assert_20171005182111_5.dmp
Installing breakpad exception handler for appid(steam)/version(1507158695)
Installing breakpad exception handler for appid(steam)/version(1507158695)
Installing breakpad exception handler for appid(steam)/version(1507158695)
Installing breakpad exception handler for appid(steam)/version(1507158695)
Installing breakpad exception handler for appid(steam)/version(1507158695)
Installing breakpad exception handler for appid(steam)/version(1507158695)
Installing breakpad exception handler for appid(steam)/version(1507158695)
assert_20171005182111_5.dmp[16387]: Finished uploading minidump (out-of-process): success = yes
assert_20171005182111_5.dmp[16387]: response: CrashID=bp-f8f9d0f5-12a3-4d24-a450-a63b92171005
assert_20171005182111_5.dmp[16387]: file ''/tmp/dumps/assert_20171005182111_5.dmp'', upload yes: ''CrashID=bp-f8f9d0f5-12a3-4d24-a450-a63b92171005''
IPC error: LockMgrMutex failed to acquire SysMgrMutex
IPC error: LockMgrMutex failed to acquire SysMgrMutex
IPC error: LockMgrMutex failed to acquire SysMgrMutex
Failed creating file mapping SteamController_Master_mem
IPC error: LockMgrMutex failed to acquire SysMgrMutex
IPC error: LockMgrMutex failed to acquire SysMgrMutex
Installing breakpad exception handler for appid(steam)/version(1507158695)
Installing breakpad exception handler for appid(steam)/version(1507158695)
Installing breakpad exception handler for appid(steam)/version(1507158695)
Installing breakpad exception handler for appid(steam)/version(1507158695)
Installing breakpad exception handler for appid(steam)/version(1507158695)
Installing breakpad exception handler for appid(steam)/version(1507158695)
Setting breakpad minidump AppID = 769
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded no]
Installing breakpad exception handler for appid(steam)/version(1507158695)
[1005/182137.080826:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
Installing breakpad exception handler for appid(steam)/version(1507158695)
IPC error: LockMgrMutex failed to acquire SysMgrMutex
IPC error: LockMgrMutex failed to acquire SysMgrMutex
IPC error: LockMgrMutex failed to acquire SysMgrMutex
Failed creating file mapping SteamController_Master_mem
IPC error: LockMgrMutex failed to acquire SysMgrMutex
IPC error: LockMgrMutex failed to acquire SysMgrMutex
IPC error: LockMgrMutex failed to acquire SysMgrMutex
^C
```

**Comment by kisak-valve** [comment] 2017-10-05 22:43
Duplicate of #5089.

**Comment by bbarker** [comment] 2017-10-06 11:51
Sorry, I was tired when I posted, should have checked for duplicates, will follow up in the original - feel free to close this duplicate.

**Closed** 2017-10-06 11:59 UTC
Labels: Distro Family: Ubuntu, Steam client
