### ISSUE TITLE
Left 4 Dead 2 won't start

### ISSUE THREAD

**Issue by l29ah** [ValveSoftware/steam-for-linux#4532] opened 2016-07-03 11:34 UTC
- Steam client version: 1465948400
- Distribution (e.g. Ubuntu): Gentoo
- Opted into Steam client beta?: No
- Have you checked for system updates?: Yes

When i try to launch Left 4 Dead 2, after the launch preparations nothing happens. Steam writes this to the console:

```
Game update: AppID 550 "Left 4 Dead 2", ProcID 3266, IP 0.0.0.0:0
ERROR: ld.so: object '/home/steam/.config/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/steam/.config/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 3268 != 3267, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/steam/.config/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/steam/.config/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
libGL error: MESA-LOADER: could not create udev device for fd 15
libGL error: MESA-LOADER: could not create udev device for fd 15
MESA-LOADER: could not create udev device for fd 28
MESA-LOADER: could not create udev device for fd 28
SDL video target is 'x11'
Game removed: AppID 550 "Left 4 Dead 2", ProcID 3266 
No cached sticky mapping in ActivateActionSet.
```

If i try to launch `hl2_linux` directly, it just runs and quits without showing anything or printing to the terminal. `strace` of the run doesn't show anything useful as i see, but there it is: https://bpaste.net/show/06ade4a92270

**Comment by Tele42** [comment] 2016-07-03 12:27
Hello @l29ah, this is probably the long standing steam runtime compatibility issue with mesa 10.5 and newer. You can either try the [arch workaround](https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Steam_runtime_issues) or disable the steam runtime with ```USE="-steamruntime"```. NOTE: Disabling the steam runtime makes it your responsibility to manage library dependencies and dependency issues should be reported to the package maintainer.

Alternatively, this may be specific to how you got libudev.so.0 to be resolved. Your best bet is to use ```sys-libs/libudev-compat```, which shims your system libudev.so.1.

**Comment by l29ah** [comment] 2016-07-03 14:29
Removing the libraries didn't help to run l4d, although i have already removed some of these to be able to run the steam client.
Installing `sys-libs/libudev-compat` didn't change anything.
Building the 32bit libs now to try running it w/o the bundled libs.

**Comment by LinuxDonald** [comment] 2016-07-03 15:04
The log is not complete. You should delete the libstdc lib as it stand in the arch linux wiki. The problem is that the bundled lib is too old for the mesa driver.

**Comment by l29ah** [comment] 2016-07-03 15:05
This is the portion of the log that occurs when i press "play".
The library is already removed.

**Comment by LinuxDonald** [comment] 2016-07-03 15:08
With the complete log I mean from the start of steam.

**Comment by l29ah** [comment] 2016-07-03 15:11
https://bpaste.net/show/cc33b9dde90d

**Comment by l29ah** [comment] 2016-07-03 16:40
Okay, same problem with STEAM_RUNTIME=0.

**Comment by l29ah** [comment] 2016-07-03 17:16
Installed `Transmissions: Element 120`, observing the same behaviour.

**Comment by l29ah** [comment] 2016-07-03 18:51
Okay, it seems like installing a proper libsdl2 and s3tc made l4d2 work.

**Comment by sandikata** [comment] 2018-01-07 10:14
And which is a proper libsdl2 version and s3tc ? which solve your problem?
Why you didn't mention them, to help us with same problem?

**Comment by l29ah** [comment] 2018-01-07 12:25
AFAIR i just installed it w/ my package manager (w/ the corresponding 32bit USE).

**Comment by lbaldim** [comment] 2018-09-08 16:33
Can someone help me?
My doesn't start too and i couldn't find any other threads sorry for necroing.

**Comment by kisak-valve** [comment] 2019-06-07 14:09
Hello @lbaldim, @sandikata, if you're still having trouble running Left 4 Dead 2 on an up to date system, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.

Closing per https://github.com/ValveSoftware/steam-for-linux/issues/4532#issuecomment-230168919.

**Closed by kisak-valve** 2019-06-07 14:09 UTC
Labels: reviewed
