### ISSUE TITLE
Error:' glXChooseVisual failed'

### ISSUE THREAD

**Issue by jumpspacejunkie** [ValveSoftware/steam-for-linux#4430] opened 2016-04-28 04:02 UTC
ran the install, seemed to work. get this error on launch. couldn't find the error in search. thanks..

**Comment by gdrewb-valve** [comment] 2016-04-28 10:18
Please post your system information, but this is likely a duplicate of the other startup issues here.

**Comment by jumpspacejunkie** [comment] 2016-04-28 16:37
[DxDiag1.14.16.txt](https://github.com/ValveSoftware/steam-for-linux/files/240985/DxDiag1.14.16.txt)
this is from my windows install

**Comment by jumpspacejunkie** [comment] 2016-04-28 16:38
if this has been reported please leave a link

**Comment by gdrewb-valve** [comment] 2016-04-28 19:43
We need your Linux system information.  You can get it from the Steam client if necessary.

There are many startup issues of all kinds here.  #3542 fails with the same glx call although that routine can have many failure reasons so they aren't necessarily the same thing.

**Comment by Tele42** [comment] 2016-04-28 21:15
It's hard to get the system information via steam when steam is failing to start. The particular information requested is what distro / release you are running, and what video driver is in use. Additionally, steam needs 32bit OpenGL support do be working with your driver.

**Comment by gdrewb-valve** [comment] 2016-04-28 22:45
Sorry, force of habit.

**Comment by jumpspacejunkie** [comment] 2016-04-30 03:15
thanks for the help. after a restart it started working. was able to log on and the 17 linux games have installed. now to try them and see if they work.
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x1e
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  2926 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Unsupported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 16.04 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-21-lowlatency
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2016-02-23
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 980/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 361.42
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x13c0
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1600 x 900
    Desktop Resolution: 1600 x 900
    Primary Display Size: 17.44" x 9.84"  (20.00" diag)
                                            44.3cm x 25.0cm  (50.8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC887
    
Memory:
    RAM:  7978 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  292997 Mb
    Largest Free Hard Disk Block:  259587 Mb
    VR Headset: None detected

**Comment by epe007** [comment] 2017-04-21 12:21
Isn't fixed. I updated all packages and the same happens.
Thank you NVIDIA for ruining the weekend.

**Comment by trite2k3** [comment] 2017-10-13 19:39
I have the same problem on slackware64-current with latest stable kernel from kernel.org installed fresh today, got multilib from alien slackware repo.

If I start "glxgears" and drag around the window like crazy the fps is constant and seems ok, GSYNC is working I got 144hz and 1440p on two screens (one 60hz).

steam is not launching



root@bifrost:~# nvidia-smi -a

==============NVSMI LOG==============

Timestamp                           : Fri Oct 13 19:31:02 2017
Driver Version                      : 384.90

Attached GPUs                       : 1
GPU 00000000:01:00.0
    Product Name                    : GeForce GTX 980
    Product Brand                   : GeForce
    Display Mode                    : Enabled
    Display Active                  : Enabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 1920
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : 0323614114278
    GPU UUID                        : GPU-5b953fca-b3dc-b086-25c3-7f246f4cd127
    Minor Number                    : 0
    VBIOS Version                   : 84.04.1F.00.02
    MultiGPU Board                  : No
    Board ID                        : 0x100
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : G001.0000.01.03
        OEM Object                  : 1.1
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : None
    PCI
        Bus                         : 0x01
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x13C010DE
        Bus Id                      : 00000000:01:00.0
        Sub System Id               : 0x85041043
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 3
            Link Width
                Max                 : 16x
                Current             : 16x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : 0 KB/s
        Rx Throughput               : 8000 KB/s
    Fan Speed                       : 30 %
    Performance State               : P0
    Clocks Throttle Reasons
        Idle                        : Not Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
    FB Memory Usage
        Total                       : 4035 MiB
        Used                        : 193 MiB
        Free                        : 3842 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 4 MiB
        Free                        : 252 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 2 %
        Memory                      : 2 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 49 C
        GPU Shutdown Temp           : 96 C
        GPU Slowdown Temp           : 91 C
        GPU Max Operating Temp      : N/A
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : Supported
        Power Draw                  : 45.13 W
        Power Limit                 : 180.00 W
        Default Power Limit         : 180.00 W
        Enforced Power Limit        : 180.00 W
        Min Power Limit             : 120.00 W
        Max Power Limit             : 225.00 W
    Clocks
        Graphics                    : 911 MHz
        SM                          : 911 MHz
        Memory                      : 3505 MHz
        Video                       : 838 MHz
    Applications Clocks
        Graphics                    : 1126 MHz
        Memory                      : 3505 MHz
    Default Applications Clocks
        Graphics                    : 1126 MHz
        Memory                      : 3505 MHz
    Max Clocks
        Graphics                    : 1392 MHz
        SM                          : 1392 MHz
        Memory                      : 3505 MHz
        Video                       : 1281 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes
        Process ID                  : 1334
            Type                    : G
            Name                    : /usr/libexec/Xorg
            Used GPU Memory         : 190 MiB

root@bifrost:~# lspci -vnnn | perl -lne 'print if /^\d+\:.+(\[\S+\:\S+\])/' | grep VGA
00:02.0 VGA compatible controller [0300]: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller [8086:0412] (rev 06) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GM204 [GeForce GTX 980] [10de:13c0] (rev a1) (prog-if 00 [VGA controller])
root@bifrost:~# nvidia-settings &
[1] 2496
root@bifrost:~# glxgears
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
719 frames in 5.0 seconds = 143.759 FPS
720 frames in 5.0 seconds = 143.808 FPS
720 frames in 5.0 seconds = 143.803 FPS
720 frames in 5.0 seconds = 143.810 FPS
720 frames in 5.0 seconds = 143.806 FPS
720 frames in 5.0 seconds = 143.807 FPS
719 frames in 5.0 seconds = 143.606 FPS
720 frames in 5.0 seconds = 143.806 FPS
720 frames in 5.0 seconds = 143.807 FPS
720 frames in 5.0 seconds = 143.806 FPS
720 frames in 5.0 seconds = 143.807 FPS
720 frames in 5.0 seconds = 143.806 FPS
720 frames in 5.0 seconds = 143.806 FPS
720 frames in 5.0 seconds = 143.808 FPS
720 frames in 5.0 seconds = 143.805 FPS
720 frames in 5.0 seconds = 143.809 FPS
720 frames in 5.0 seconds = 143.807 FPS
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0.0"
      after 60 requests (60 known processed) with 0 events remaining.
root@bifrost:~# uname -a
Linux bifrost 4.13.6 #1 SMP Fri Oct 13 18:27:00 CEST 2017 x86_64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz GenuineIntel GNU/Linux
[1]+  Done                    nvidia-settings

**Comment by kisak-valve** [comment] 2019-05-03 14:32
Hello @jumpspacejunkie, @trite2k3, in general this issue can happen when 32 bit opengl provided by the nvidia driver is not working. A 32 bit variant of glxinfo would have been a more insightful test to use.

The nvidia driver requires the loaded kernel module version to match the userspace version, and depending on distro packaging, the 32 bit and 64 bit userspace half of the driver may be packaged separately.

If either of you are still experiencing this issue on an up to date system, please open a new issue report.

**Closed by kisak-valve** 2019-05-03 14:32 UTC
Labels: reviewed
