### ISSUE TITLE
Issues on 4.18.9-gentoo kernel

### ISSUE THREAD

**Issue by Kreyren** [ValveSoftware/steam-for-linux#5782] opened 2018-09-24 10:03 UTC
#### Your system information
* **Steam client version (build number or date):** Unknown, downloaded using https://wiki.gentoo.org/wiki/Steam#Installation first *manual* then *Manual with alternative installer script*.
* **Distribution (e.g. Ubuntu):** 4.18.9-gentoo
* **Opted into Steam client beta?:** Yes
* **Have you checked for system updates?:** Yes

#### Please describe your issue in as much detail as possible:
1. Compiled xpad in kernel which works out of the box on 4.18.4-gentoo, but does NOT on 4.18.9-gentoo.
1.1 Xbox360 Controller was detected by gentoo based on indicator on the controller, but coudn't be used in steam and steamapps. Tried to fix it installing https://packages.gentoo.org/packages/games-util/xboxdrv. Coudn't verify due fatal issue.
2. Minor issues (crashes) with steam client which lead to fatal issue (crash on startup).

#### Steps for reproducing this issue:
**Log of actions:**
https://wiki.gentoo.org/wiki/User:Kreyren/ULTIMATE_BREAKER/Steam

#### Additional info:
**dmesg && cat /var/log/Xorg.0.log && cat /usr/src/linux/.config && uname -r && uname -a && eselect kernel list && emerge --info && cat /etc/portage/make.conf && cat /etc/portage/package.*/steam**:
https://bpaste.net/show/2e82dd9b43d4

**.tmp files**
https://drive.google.com/drive/folders/1D_dls-5NItCHVC8FFCbBDTDhyLuswMnp?usp=sharing

**Comment by kisak-valve** [comment] 2018-09-24 12:44
Hello @Kreyren, your minidump indicates a crash in libdbus-1.so.3.5.8. Can you move ~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs* somewhere out of the way, then start steam to regenerate those folders? If that helps, please list the difference between the old and new variants of the pinned_libs folders.

**Comment by Kreyren** [comment] 2018-09-24 14:32
Invoked **~/.local/share/Steam/ubuntu12_32/steam-runtime $ mv pinned_libs_32 pinned_libs_32.old && mv pinned_libs_64 pinned_libs_64.old && steam**

resulted in same issue.

**Comment by Kreyren** [comment] 2018-09-24 14:49
@kisak-valve 

Note that if steam --reset it invoked steam is able to start again and play games without Xbox360 support (even when it's compiled in kernel and using xboxdvr):

https://bpaste.net/show/58bbbd014034

Previous issue occur later again on restart.

http://bpaste.net/show/317e140d66cc

**Comment by chewi** [comment] 2018-09-24 15:08
I'm using xboxdrv (admittedly my own custom patched version with stability fixes) with 4.18.9 and it worked for me just yesterday. Note that xboxdrv doesn't need the xpad driver because it talks directly via USB, the driver may even make more temperamental. You should also test with something simpler like jstest rather than Steam.

**Comment by chewi** [comment] 2018-09-24 15:39
I also highly recommend installing steam-overlay rather than the other methods. We apply patches such as [this one](https://github.com/anyc/steam-overlay/blob/master/games-util/steam-launcher/files/steam-fix-joystick-detection.patch), which I have found can make a difference.

**Comment by Kreyren** [comment] 2018-09-24 16:12
@chewi Thanks for info, trying steam-overlay based on instructions from gentoo wiki.

**Comment by Kreyren** [comment] 2018-09-24 17:38
@chewi Encounter different issue(?) on the overlay: http://bpaste.net/show/33fce7a30c99

**Comment by kisak-valve** [comment] 2018-09-24 17:51
For what it's worth, the majority of the steam client is in ~/.local/share/Steam.

**Comment by Kreyren** [comment] 2018-09-24 18:08
@kisak-valve thanks for info.

Invoked `rm -rf /home/kreyren/steam* && rm -rf /home/kreyren/.local/share/Steam && emerge -C steam && emerge steam-meta`

Was prompted with a `It seems that you moved..` or simmilar options Reinstall/Cancel, chosed reinstall.
http://bpaste.net/show/a071c065a9e3

Won't open again: 
http://bpaste.net/show/ce37d8c89bd8

Trying https://wiki.gentoo.org/wiki/Steam/Client_troubleshooting#Segfault_when_remember_my_password_is_selected

Invoked `rm -fr ~/.local/share/Steam/config`

Steam opens
 http://bpaste.net/show/f2862c44b111

Exit steam, openning again.
http://bpaste.net/show/eb946bbe7399

Won't open again.

**Conclusion:** 
possibly old steam was removed from  ~/.local/share/Steam and overlay version replaced it solving the previous issue? 
Using steam without the saved password is acceptable for the time beeing, but steam won't detect Xbox360 nor steam controller even with xboxdvr and compiled XPAD in kernel: https://bpaste.net/show/679f717a7350.

It may also be possible that previous issue was resolved by removing ~/.local/share/Steam and i'm still running manually installed steam.. Trying to reverse-engineer the installer script.

**Comment by chewi** [comment] 2018-09-24 18:52
Sorry, I thought jstest was part of SDL or libevdev or something but it's actually part of games-util/joystick. No overlays required.

Regarding the error from xboxdrv, I wonder if this is simply a permissions issue. You're normally supposed to run it as root, perhaps you're not? Beyond that, distributions annoyingly still use permissions that don't work out of the box. I added myself to the plugdev group and created /etc/udev/rules.d/99-joysticks.rules with this:

```
SUBSYSTEM=="input", ENV{ID_INPUT_JOYSTICK}=="1", MODE="0664", GROUP="plugdev"
```

As for Steam, I'm sorry you're having so much trouble there. I haven't seen an issue quite like that. I normally suggest that people disable the Steam runtime. You can make this default with `USE="-steamruntime"` or try it as a one-off with `STEAM_RUNTIME=0` but you'll need to have the necessary dependencies installed for the latter. I have a feeling it's not that though. Most users to give `LIBGL_DRI3_DISABLE=1` when starting Steam for the first time but I don't think it's that either.

**Comment by Kreyren** [comment] 2018-09-24 19:03
New result: i believe that i'm now on steam-overlay and the controller is detected and working, but on restart it won't open again.
http://bpaste.net/show/737f0a74f6e3

Can be resolved by removing config file again:
http://bpaste.net/show/be0a33125dca

**Comment by chewi** [comment] 2018-09-24 19:03
Looking through your system info, I've noticed one big oddity. You've enabled the new AMDGPU stuff for your Southern Islands card in the kernel but you're still using the radeon X.Org driver. Your `VIDEO_CARDS` variable has a typo where you've put `amgpu` rather than `amdgpu`. I wonder if mixing these drivers has screwed things up.

**Comment by Kreyren** [comment] 2018-09-24 19:06
> Looking through your system info, I've noticed one big oddity. You've enabled the new AMDGPU stuff for your Southern Islands card in the kernel but you're still using the radeon X.Org driver. Your VIDEO_CARDS variable has a typo where you've put amgpu rather than amdgpu. I wonder if mixing these drivers has screwed things up.

@chewi using `amdgpu radeonsi` is recommended on gentoo wiki: https://wiki.gentoo.org/wiki/AMDGPU

> Regarding the error from xboxdrv, I wonder if this is simply a permissions issue. You're normally supposed to run it as root, perhaps you're not? Beyond that, distributions annoyingly still use permissions that don't work out of the box. I added myself to the plugdev group and created /etc/udev/rules.d/99-joysticks.rules with this:
> 
> SUBSYSTEM=="input", ENV{ID_INPUT_JOYSTICK}=="1", MODE="0664", GROUP="plugdev"
> ...

Seems to work out of the box on steam-overlay. So i didn't tried it.

**Comment by chewi** [comment] 2018-09-24 19:08
Yes, but look again, you've got a typo there. It's am**d**gpu.

What desktop are you using? Is openbox your window manager by any chance?

**Comment by Kreyren** [comment] 2018-09-24 19:10
> Yes, but look again, you've got a typo there. It's amdgpu.
> 
> What desktop are you using? Is openbox your window manager by any chance?

Thanks for letting me know, you probably solved the issue with DXVK for me now :+1:  :D 

I'm using x11-wm/i3 atm which has openbox included afaik.

**Comment by chewi** [comment] 2018-09-24 19:19
I saw the `Major opcode of failed request:  40 (X_TranslateCoords)` error and found lots of reports tying that to openbox, although that doesn't seem to be the error that prevents it from starting.

The segmentation fault may well be caused by the Steam runtime, particularly libstdc++.so.6. Other than disabling it, you can quickly test that theory with:

`LD_PRELOAD=/usr/lib64/gcc/x86_64-pc-linux-gnu/8.2.0/libstdc++.so.6 steam`

**Comment by Kreyren** [comment] 2018-09-24 19:51
@chewi testing it now
http://bpaste.net/show/3b26f972cb9f

http://bpaste.net/show/cbd8d2330b32

**Comment by chewi** [comment] 2018-09-24 19:55
My bad, I'm forgetting Steam is 32-bit.

```
LD_PRELOAD=/usr/lib32/gcc/x86_64-pc-linux-gnu/8.2.0/libstdc++.so.6 steam
```

But you also need to do this every time, I don't see it in your second paste.

**Comment by Kreyren** [comment] 2018-09-24 19:57
Noted, testing again:
http://bpaste.net/show/f24f6509ad9b

**Comment by chewi** [comment] 2018-09-24 20:38
Gah, I still got the path wrong, gcc isn't installed like other 32-bit libraries. Blame the fact that I'm currently doing out-of-hours remote server upgrades. :tired_face: 

```
LD_PRELOAD=/usr/lib64/gcc/x86_64-pc-linux-gnu/8.2.0/32/libstdc++.so.6 steam
```

**Comment by Kreyren** [comment] 2018-09-24 20:59
@chewi It's okay i'm happy that your helping me. ^^

http://bpaste.net/show/2447b903563d

Same issue tho

**Comment by chewi** [comment] 2018-09-24 21:03
Feel like I'm clutching at straws here. Maybe that dump file needs a closer look but I don't know about them. libstdc++.so.6 isn't the only library that can cause issues, which is why I recommend disabling the Steam runtime entirely but it could just as easily be something else entirely.

**Comment by Kreyren** [comment] 2018-09-24 21:08
@chewi Sent me the instructions to disable steamruntime i will try it tommorow and sent you the result if it's relevant for you.

**Comment by kisak-valve** [comment] 2018-09-24 21:09
To briefly chase a different hint, do you have a dbus session running? Maybe check #4444 if the workarounds there have any effect.

**Comment by Kreyren** [comment] 2018-09-25 07:49
@kisak-valve i'm not aware of using dbus, but it seems to be part of /desktop profile on gentoo. Check line 5982 in https://bpaste.net/show/2e82dd9b43d4.

Checking #4444

**Comment by kakra** [comment] 2018-09-27 21:11
@Kreyren A very dumb question but did you `emerge -1a @module-rebuild` after compiling the new kernel? It's easy to forget that for 3rd-party drivers.

Here's a quick fix to automate this:

```bash
# cat /etc/kernel/postinst.d/70-emerge-module-rebuild
#!/bin/bash
exec env -i PATH=$PATH /usr/bin/emerge -1v --usepkg=n --selective=n @module-rebuild
```

**Comment by Kreyren** [comment] 2018-09-28 09:14
@kakra I'm compiling kernel using:

`eselect list kernel` and selecting kernel to use, followed by `make && make modules_install && make install && shutdown -r now`.

Is `emerge -la @module-rebuild` required? it's not mentioned anywhere afaik.

**Comment by kakra** [comment] 2018-09-28 10:04
@Kreyren @chewi `emerge -1a @module-rebuild` is a no-op if there are no out-of-tree modules. It's worth a try to see if it shows something. I think `xpad` may provide out-of-tree drivers (but I'm not sure, I'm using `xpadneo`).

If `@module-rebuild` shows up modules for you, and you want to continue using `make modules_install` etc the way you're used to be, I recommend to place the postinst hook I've mentioned. It's the same way I do it: `make -j9 && make modules_install install && reboot`. :-) Hooks are in place here to rebuild emerged modules, rebuild the initramfs, and update the boot loader.

BTW: It's "minus one A", not "minus L A" (`-1a`), or with long options: `emerge --one-shot --ask @module-rebuild`.

**Comment by Kreyren** [comment] 2018-09-28 10:13
@chewi `games-util/steam-meta steamruntime` is now present in `package.use/custom` and emerged. It's possible that it was applied before since it seems to not change much. 
Added just to decrease the amount of variables.

@kakra 
> I think xpad may provide out-of-tree drivers (but I'm not sure, I'm using xpadneo).

x11-misc/xpad is now unmerged and i'm using just kernel configuration which is sufficient on steam-overlay, invoking `emerge -la @modules-rebuild` which did not detect anything to pull == http://bpaste.net/show/086bc2a2d5e9.

> if @module-rebuild shows up modules for you, and you want to continue using make modules_install etc the way you're used to be, I recommend to place the postinst hook I've mentioned. It's the same way I do it: make -j9 && make modules_install install && reboot. :-)

`make -j9` results in `No rule to make target` on my system http://bpaste.net/show/6e5812ae36a0 (invoked from /usr/src/linux). So i was using `make` instead. 

> Hooks are in place here to rebuild emerged modules, rebuild the initramfs, and update the boot loader.

Noted.

>  It's "minus one A", not "minus L A" (-1a),

Noted, copy-pasted your command to terminal.

**Comment by chewi** [comment] 2018-09-28 10:16
> @chewi games-util/steam-meta steamruntime is now present in package.use/custom and emerged. It's possible that it was applied before since it seems to not change much. Added just to decrease the amount of variables.

To be clear, I want you to disable it, not enable it. :grin:

**Comment by Kreyren** [comment] 2018-09-28 10:17
@chewi i missunderstood then :D Disabling it now.

**Comment by kisak-valve** [comment] 2018-09-28 11:58
@Kreyren, can you `rc-status -a | grep dbus` and start the service if it is not already. The saved password quirk reads #3415.

If that doesn't make a difference, please check that sys-apps/dbus has ABI_X86="32 64" and regenerate the pinned library folders again.

**Comment by Kreyren** [comment] 2018-09-28 13:35
@kisak-valve 

 wgetpaste -c "rc-status -a | grep dbus"
http://bpaste.net/show/4e07a5c4d3cb

_WIll update the post with the rest_

**Comment by Kreyren** [comment] 2018-12-14 21:34
I'm having the same issue on `default/linux/amd64/17.0/desktop (stable)` profile using xpad (https://paste.pound-python.org/show/zl0oMVjvxFSXjC9GrHfc/) and steam-laucher from [steam-overlay](https://github.com/anyc/steam-overlay).

Installed packages = https://paste.pound-python.org/show/uTER1LkBdMENzOyyIE1n/

emerge --info = https://paste.pound-python.org/show/Xksc1WNHzBUXOTLUQoDW/

rc-status -a | grep dbus = https://paste.pound-python.org/show/d2lEceglWB9Xuivmzw4E/


## Symptoms
Xbox360 Controller is not recognized in steam-games. 

## Steps to reproduce
On gentoo install xpad on desktop profile and emerge `steam-laucher` or `steam-meta` from [steam-overlay](https://github.com/anyc/steam-overlay).

**Comment by kakra** [comment] 2018-12-15 02:48
Is this about the original Xbox360 controller or the current model Xbox One S?

**Comment by Kreyren** [comment] 2018-12-15 03:19
@kakra As mensioned Xbox360 controller (https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Xbox-360-S-Controller.png/800px-Xbox-360-S-Controller.png)

Not sure if it's original it says "model 1403" under battery. None serial number that i can see.

**Comment by kakra** [comment] 2018-12-15 04:39
@Kreyren That's the original... The One S has a different logo button. For the "One S" I can recommend using the xpadneo driver but it won't support the original 360 variant.

**Comment by Kreyren** [comment] 2018-12-15 20:15
Tried `xboxdrv` results updated in [post above](https://github.com/ValveSoftware/steam-for-linux/issues/5782#issuecomment-447485904).

**Comment by Kreyren** [comment] 2018-12-16 00:12
Find solution(?):

Updating udev seems to solved the issue https://paste.pound-python.org/show/644FZoV1Z8JfzksMLwGM/

**Comment by kisak-valve** [comment] 2021-02-12 16:28
Hello @Kreyren, are you still experiencing this issue on an up to date system?

**Comment by Kreyren** [comment] 2021-02-12 16:31
@kisak-valve I am not aware of any issues with it atm.

**Comment by kisak-valve** [comment] 2021-02-12 16:37
Thanks, closing.

**Closed by kisak-valve** 2021-02-12 16:37 UTC
Labels: Distro Family: Gentoo, Need Retest, Steam client
