### ISSUE TITLE
Updated Ubuntu 14.04 to 16.04 now STEAM wont run anymore

### ISSUE THREAD

**Issue by vbdeman** [ValveSoftware/steam-for-linux#4429] opened 2016-04-27 14:57 UTC
You guys have any clue?

steam did notthing after upgrade to ubuntu 16.04
uninstalled steam wtih synaptic from 16.04 and reinstalled.
first time run - it did do a update and then notting.
i rebootted then this

terminal:

ben@lpt-001:~$ steam
Running Steam on ubuntu 16.04 32-bit
STEAM_RUNTIME is enabled automatically
[2016-04-27 16:45:12] Startup - updater built Mar 31 2016 19:10:48
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)

any ideas? 

running a laptop with intel integrated graphics.

**Comment by gdrewb-valve** [comment] 2016-04-28 10:18
Likely duplicate of other issues here, look at the ones referencing 16.04 and specifically #4417.

**Comment by kisak-valve** [comment] 2019-05-03 14:25
Hello @vbdeman, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment] 2019-06-07 13:19
Closing pending feedback.

**Closed by kisak-valve** 2019-06-07 13:19 UTC
Labels: Need Retest, reviewed
