### ISSUE TITLE
[Fedora 36] Steam virtual gamepad replaces Xbox Elite 2 when it shouldnt

### ISSUE THREAD

**Issue by MNS26** [ValveSoftware/steam-for-linux#8793] opened 2022-09-12 09:30 UTC
#### Your system information

* Steam client version (build number or date): Sep 9 2022, at 23:46:16
* Distribution (e.g. Ubuntu): Fedora 36
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

What i expected:
When connecting my Xbox Elite 2 controller wireless for steam to not make a virtual game pad when "Generic Gamepad" is unchecked

What did happen:
Steam generating a "Steam Virtual Gamepad" and replacing the actual controller
![image](https://user-images.githubusercontent.com/53867268/189619009-ed02dc9a-e0dc-4122-8a50-e372f8ee3962.png)

#### Steps for reproducing this issue:

1. connect Xbox Elite 2 controller via bluetooth
2. start steam
3. open Controller settings (or any program to check controllers)

Steam system info
[https://gist.github.com/MNS26/019ef7d9bd2c9ca2fbfe21563ac05bbf](url)

**Comment by MNS26** [comment] 2022-09-12 09:32
When i was using arch linux it didnt have this issue, ever since i switched (2 days ago) it happened

**Comment by kisak-valve** [comment] 2022-09-12 12:23
Hello @MNS26, this is consistent with the intended behavior of the Steam Input subcomponent of Steam. You have an Xbox controller plugged in and that should toggled with the `Xbox Configuration Support` option, not `Generic Gamepad Configuration Support`.

Closing as not a bug.

**Closed by kisak-valve** 2022-09-12 12:23 UTC

**Comment by MNS26** [comment] 2022-09-12 14:15
@kisak-valve yes im aware but even that on it doesnt change
