### ISSUE TITLE
Steam crash: Segmentation Fault

### ISSUE THREAD

**Issue by gchapyzh** [ValveSoftware/steam-for-linux#4583] opened 2016-08-10 05:14 UTC
All details here:

http://steamcommunity.com/app/221410/discussions/0/365172547941678152/

**Comment by gdrewb-valve** [comment] 2016-08-10 07:45
Likely a Steam runtime compatibility issue.  There are many similar issues open here with possible workarounds.

**Comment by GreatBigWhiteWorld** [comment] 2016-08-10 11:49
@gdrewb-valve It's been a month with this error and there is no workarounds for this.

https://github.com/ValveSoftware/steam-for-linux/issues/4554

Check how this has not been solved at all.

**Comment by gdrewb-valve** [comment] 2016-08-10 16:27
It depends on the problem.  There are threads like #4504 and #4534 that do have workarounds, so @gchapyzh may find one that works.

**Comment by gchapyzh** [comment] 2016-08-10 16:34
#4534 has no workaround, #4504 did nothing for me.

**Comment by gdrewb-valve** [comment] 2016-08-10 16:37
Sorry, #4537.

**Comment by madrang** [comment] 2016-08-10 20:43
There are many ticket open for this already.
https://github.com/ValveSoftware/steam-for-linux/issues/4504
https://github.com/ValveSoftware/steam-for-linux/issues/4537
https://github.com/ValveSoftware/steam-for-linux/issues/4554

**Comment by xtonousou** [comment] 2016-08-17 02:25
I solved this with:

  find ~/.steam/root/ -name "libstdc++.so*" -print -delete
  find ~/.steam/root/ -name "libxcb.so*" -print -delete
  find ~/.steam/root/ -name "libgpg-error.so*" -print -delete

**Comment by gchapyzh** [comment] 2016-08-18 00:31
@xtonousou sorry, I tired doing exactly that before and just now - no effect.

**Comment by xtonousou** [comment] 2016-08-18 02:49
It's probably caused by missing libraries. There is an AUR called steam-libs, `https://aur.archlinux.org/packages/steam-libs/` , you can go check the dependencies. And don't forget to open steam by `STEAM_RUNTIME=0 /usr/bin/steam`.

**Comment by GreatBigWhiteWorld** [comment] 2016-08-23 06:11
I think if everything is open source, people can actually find what's causing the problem very fast, but I'm no programmer so I may be wrong.

**Comment by kisak-valve** [comment] 2019-07-12 16:20
Hello @gchapyzh, Steam's handling of the Steam runtime has changed since the last time this issue was commented on. It now prefers host libraries before the runtime variants which avoids several common snafus from this time period.

Are you still experiencing this issue on an up to date system?

**Comment by gchapyzh** [comment] 2019-07-12 16:24
@kisak-valve It has been a while, but I run steam on a platform of lies and slander, supported by a construct of duct tape and scripts that even I have no memory of putting up.

In short, I avoided the issue a long time ago. Later, I started dual booting between Windows and SUSE on a new machine, so I can't honestly comment of if it works or not.

**Comment by kisak-valve** [comment] 2019-07-12 16:29
Thanks for the feedback, closing per the last comment. This should have been fixed some time ago.

**Closed by kisak-valve** 2019-07-12 16:29 UTC
Labels: Distro Family: openSUSE, Need Retest, reviewed
