### ISSUE TITLE
Steam Doesn't Minimize to System Tray

### ISSUE THREAD

**Issue by dbass81** [ValveSoftware/steam-for-linux#4232] opened 2016-01-03 19:53 UTC
![screenshot from 2016-01-03 12 53 29](https://cloud.githubusercontent.com/assets/5233000/12080488/0736a8bc-b219-11e5-8c1e-317df28992f6.png)

Steam doesn't minimize to system tray when running lxpanel.  It stays on the taskbar.  I don't know if this is the default behavior on Linux, but on Windows if you minimize or click 'X' Steam minimizes to the system tray.

**Comment by beansmyname** [comment] 2016-01-03 19:56
This may be a duplicate of #1025

**Comment by dbass81** [comment] 2016-01-03 20:01
Running 'steam -silent' starts Steam in the system tray without opening the main window, but once it opens, it still doesn't minimize to the system tray.

**Comment by dbass81** [comment] 2016-01-03 20:08
'STEAM_FRAME_FORCE_CLOSE=1 steam' seems to work for now if you click on the 'X' to minimize it.  Thanks.

**Closed** 2016-01-03 20:09 UTC
