### ISSUE TITLE
Linux client controller not working on Windows Remote Play Together host

### ISSUE THREAD

**Issue by Zorrototo** [ValveSoftware/steam-for-linux#7715] opened 2021-03-24 02:59 UTC
#### Your system information

* Steam client version (build number or date): 03.23.2021 20:11:07
* Distribution (e.g. Ubuntu): Manjaro KDE [System information](https://gist.github.com/Zorrototo/533bb4f3b9d8d5abc137cd8cf5c00f02)
* Opted into Steam client beta?: [Yes/No] No for client and host 1616532526
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When I join a remote play together invitation my X-box 360 controller does not work in the remote game hosted on a Windows 10 machine.
Keyboard and Mouse can work if host enable them.
We (client and host) tried probably all combination of settings for the Controller and Remote Play Together in Steam Settings but result is the same: no working controller for the Linux client.
With same hardware, it works correctly from Windows 7 to Windows 10 and controller has no issue. It also all works properly from the Windows 10 client to the Manjaro Linux host.
The Windows 10 computer in these tests has an Xbox One controller.

I found this other issue but I'm not sure it is the same problem https://github.com/ValveSoftware/steam-for-linux/issues/6951 as the Windows host here can see and can assign the controller.

#### Steps for reproducing this issue:

1. From a Linux client join a Remote Play Together invitation from a Windows 10 host
2. Host can assign the second controller to you (and the Linux client controller can rumble when the host assign it so it seems to work there)
3. Controller does not work at all in remote game, you can not hold the back button to open controller menu, it just doesn't work

**Comment by kisak-valve** [comment] 2021-03-24 12:45
Possible duplicate of #7052.

**Comment by ripper81** [comment] 2021-03-28 20:02
Same here. I tried to join a game and pressing the backbutton resulted in nothing. I tried with controlleroverlay on and off to no avail.

**Comment by syrofoam** [comment] 2021-04-01 11:40
Same problem here, if you bring up the assign controller picture. There is no active controller input in that screen even if you can use it on the game.

The problem is not present in Remote Play on Windows on same PC.

**Comment by ripper81** [comment] 2021-04-01 13:36
It is also clearly related to the linux steamclient itself. The problem occurs regardless on which platform (Windows or Linux) the game is hosted. It is also not present when the linux steam link app is used for connecting to steam remote play.

**Comment by hcwinsemius** [comment] 2021-04-17 20:26
Exactly the same problem here with Ubuntu 20.04 (host) to Ubuntu 20.04 (client). We both use 8bitdo sn30 pro plus controllers.

**Comment by VortexAcherontic** [comment] 2021-07-03 10:54
Can confirm the same issue with Windows as Host and Linux as guest as well as Linux as host and another Linux as guest.

The controllers are visible for both the host and the guest in the overlay and can be pinged individually (rumble) and are even shown as two separate input devices in-game.
But it seems the Linux guest just don't want to transmit any controller inputs to the host.

This also seems to be independent of the display server. I am facing the same issue with a X11 and Wayland guest.

Tested scenarios:

Host: Windows 10
Guest: openSUSE Tumbleweed (X11)

Host: openSUSE Tumbleweed (X11)
Guest: openSUSE Tumbleweed (Wayland)

Host: openSUSE Tumbleweed (X11)
Guest: openSUSE Tumbleweed (X11)

**Comment by ripper81** [comment] 2021-08-17 16:35
Any news about that issue? I am still facing the problem. I wonder if this is solved until the steam deck is out. However all steam games relying on steam remoteplay for online multiplayer are not playable on linux.

**Comment by Zorrototo** [comment] 2021-08-17 17:36
Yep that's a deal breaker to me. I tried multiple time but if in the end I have to switch back to Windows to Remote Play... this is annoying to say the least..

**Comment by slouken** [comment] 2021-09-16 23:45
Is this still active with the latest Steam client on Windows and Linux?

I tried and wasn't able to reproduce:

Linux system:
1. Install openSUSE Tumbleweed KDE/Plasma
2. Install openSUSE Steam package
3. Launch steam
4. Connect Xbox 360 wired controller

Windows 10 system:
1. Install D-Corp
2. Launch D-Corp
3. At the title screen, use Shift-Tab to open the overlay
4. Click "Invite Anyone" and copy the invitation link
5. Send invitation link via e-mail to the Linux system

Linux system:
1. Click on invitation link, allowing Steam to open it
2. Streaming client launches and connects, showing an intro dialog and a toast saying to hold the Back button for the controller overlay

Windows 10 system:
1. Use Shift-Tab to close the overlay

Linux system:
1. Use the controller to navigate the menu and quit

**Comment by slouken** [comment] 2021-09-23 15:13
We identified the problem and it's fixed for the latest Steam client beta, dated Sep 23.

Thanks!

**Closed by slouken** 2021-09-23 15:13 UTC
Labels: Streaming, Need Retest, General controller / Steam Input
