### ISSUE TITLE
"More discussions" section makes Steam Client unresponsive

### ISSUE THREAD

**Issue by sizeofbool** [ValveSoftware/steam-for-linux#3994] opened 2015-08-29 10:51 UTC
Steps to reproduce:
1. Open Steam community discussions inside Steam client.
2. Open any thread and move mouse cursor to "More discussions" section.
3. Moving mouse cursor over buttons displays tooltips with huge delay and makes Steam Client unresponsive for a few seconds.

Screenshots have comments in them.

![steamcommunity2](https://cloud.githubusercontent.com/assets/6904856/9561559/b40cbc9e-4e63-11e5-8efc-a8e106fa4345.png)
![steamcommunity1](https://cloud.githubusercontent.com/assets/6904856/9561558/b40c7db0-4e63-11e5-8ae8-ed45da21681d.png)
![steamcommunity3](https://cloud.githubusercontent.com/assets/6904856/9561560/b40dd494-4e63-11e5-9c06-27caeee586fc.png)
![steamcommunity4](https://cloud.githubusercontent.com/assets/6904856/9561561/b40f0986-4e63-11e5-9db8-19a16a691a4b.png)

My Specs:
GNU\Linux Debian 8 "jessie" x86_64 with Xfce
Steam Client Beta

Operating System Version:
    Debian GNU/Linux 8.1 (jessie) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.16.0-4-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-06-12

**Comment by ivazqueznet** [comment] 2016-02-26 18:11
Confirmed still exists with the Feb 4 build of steam.

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.3.5-300.fc23.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11800000
    X Window Manager:  Metacity (Marco)
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  X.Org Gallium 0.4 on AMD OLAND (DRM 2.43.0, LLVM 3.7.0)

    Driver Version:  3.0 Mesa 11.1.0 (git-525f3c2)
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel

**Comment by predr** [comment] 2017-01-26 03:07
![steam-high-cpu-usage](https://cloud.githubusercontent.com/assets/17696117/22318370/3fc30c78-e37a-11e6-9f2f-54324d1047d4.gif)

**Comment by BloodyIron** [comment] 2022-04-25 14:40
So has this been fixed yet? :/ Still happens to me at times.

**Comment by Elandig** [comment] 2022-05-02 11:08
I'm still having this issue as well, Arch + i3wm.
It is very annoying because it gets permanently stuck on the screen even if I change workspaces and their outputs.

Wish there was a flag or something to completely disable those tooltip prompts, because the issue seems to be quite old.

**Comment by N-Prime** [comment] 2022-05-16 15:28
This has been an issue since I started using Linux in 2019. Currently on openSUSE Leap 15.3, KDE Plasma.

**Comment by BloodyIron** [comment] 2022-05-17 00:39
This has been an issue for me for like 8 years. I can't fathom why this hasn't been fixed.

**Comment by BloodyIron** [comment] 2022-05-17 16:26
I agree it's better to just disable this considering how this completely freezes my Steam application and I have to force kill it when it happens. It's not only literally un-usable, it is so problematic it breaks my entire application session. That alone should be a big enough deal for it to be disabled/equivalent. But... ZERO action from VALVe on this...

**Comment by BloodyIron** [comment] 2022-05-17 16:26
@kisak-valve any chance we can get someone to look at this... this decade? Last decade has come and gone already.

**Comment by KibaGasteiz** [comment] 2023-04-29 11:39
This is fixed on Steam beta, please close this issue.

**Comment by DanMan** [comment] 2023-04-29 16:25
Well, they've removed them. Wouldn't call that "fixed", but I take it.

**Comment by KibaGasteiz** [comment] 2023-04-29 17:00
> Well, they've removed them. Wouldn't call that "fixed", but I take it.

No, they didn't remove anything wtf, look again please.

**Comment by Elandig** [comment] 2023-04-30 02:45
> > Well, they've removed them. Wouldn't call that "fixed", but I take it.
> 
> No, they didn't remove anything wtf, look again please.

Perhaps that person is talking about the current Steam Beta client. I don't have it anymore either.

**Comment by Elandig** [comment] 2023-04-30 02:49
> Well, they've removed them. Wouldn't call that "fixed", but I take it.

Try hovering on them for longer, they now appear with a slight delay and seem to be working fine.

**Comment by kisak-valve** [comment] 2023-06-09 23:19
Closing per the last several comments.

**Closed by kisak-valve** 2023-06-09 23:19 UTC
Labels: reviewed, Steam client, Need Retest, Web

**Comment by BloodyIron** [comment] 2023-06-12 20:55
I was generally able to reproduce this issue by hovering my mouse over the discussion thing back and forth and back and forth for a few seconds, and yeah it is still a problem : 

![image](https://github.com/ValveSoftware/steam-for-linux/assets/12439391/82775720-9271-4def-9b51-3ffc02d4f94b)

That overlay EVENTUALLY went away after like a few minutes...

**Comment by kisak-valve** [comment] 2023-06-12 20:59
Hello @BloodyIron, please verify that you saw this issue with the current Steam client beta (should be 1686453716 from June 10th).
