### ISSUE TITLE
[beta][xserver] client crash due to xserver commit 601fd0fd8446a4377180d9695b469a48aa352d71

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#11069] opened 2024-07-06 14:05 UTC
Updated my gfx stack today, the beta steam client was not starting anymore with a x11 error. After bisecting the xserver (I run xorg git), the xserver commit 601fd0fd8446a4377180d9695b469a48aa352d71  breaks x11 beta steam client support on my system.

I tried to contact the author, his/her SMTP server does block my SMTP server and there is no grey listing.

Anybody can reproduce contact the author?

**Comment by kisak-valve** [comment] 2024-07-06 14:24
Hello @sylware, looks like it should be fixed with https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/1574. In general, regressions in other projects should be evaluated and fixed in those projects.

Closing as not a Steam client issue.

**Closed by kisak-valve** 2024-07-06 14:24 UTC

**Comment by sylware** [comment] 2024-07-06 15:08
Ok, I cannot interact with their gitlab as it is hostile to noscript/basic (x)html, and his/her smtp admin does not know about grey listing.

After further reading: this is "why wayland 101": x11 is a really shabily defined protocol. The Devil hides in the details.

Hopefully, the fixes of his/her breakages will be merged soon in xserver main.
