### ISSUE TITLE
Steam GUI freeze few seconds after login

### ISSUE THREAD

**Issue by PierfrancescoArdino** [ValveSoftware/steam-for-linux#5488] opened 2018-05-18 08:46 UTC
#### Your system information

* Steam client version (build number or date): 1526499729
* Distribution (e.g. Ubuntu):  Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

The app freezes after log in, I can not execute any command nor click on any button. This seems to happen both with Runtime and Native version of Steam. 

Here's the CLI output

https://gist.github.com/PierfrancescoArdino/ead22fa3874c2556962b2c0f600e208b

**Comment by kisak-valve** [comment] 2018-05-18 13:06
Hello @PierfrancescoArdino, what video card are you using?

This is most likely a duplicate of #5480.

**Comment by PierfrancescoArdino** [comment] 2018-05-18 13:07
Well, the problem seems to be disappeared after a mesa update 2 hours ago

**Comment by kisak-valve** [comment] 2018-05-18 13:12
Closing as a duplicate of #5480.

**Closed by kisak-valve** 2018-05-18 13:12 UTC
Labels: Distro Family: Arch, Steam client, duplicate
