### ISSUE TITLE
Stop button does not work for proton games

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#6689] opened 2019-11-13 12:25 UTC
#### Your system information

* Steam client version (build number or date): Nov 11 2019, at 22:23:52
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Stop button does not work for proton games

#### Steps for reproducing this issue:

1. Start game with Proton
2. Press `stop` button

**Comment by underlineGalaxy** [comment] 2020-01-02 04:09
I can confirm this is **still** an issue.

Especially annoying since when I open a proton game and it doesn't work I got no other choice than to restart my system

**Comment by fallenguru** [comment] 2020-01-07 23:26
> when I open a proton game and it doesn't work I got no other choice than to restart my system

Alt-tabbing out and killing it usually works for me, in these cases?

**Comment by TriMoon** [comment] 2020-01-08 09:23
I can confirm this is also the case on Kubuntu 19.10

**Comment by krompus** [comment] 2020-03-30 14:40
It would be great if the button worked, but for now I have a script bound to a keybind (Alt+Shift+F4), to kill all `.exe`s:

`#!/bin/bash`
`kill -9 `ps -ef | egrep '\.exe'|awk '{print $2}'``

**Comment by kisak-valve** [comment] 2021-02-26 21:41
Hello, is anyone still experiencing this issue on an up to date system? Most likely fixed by "Fix games not getting stopped via the 'Stop' button in the client UI (steam-for-linux#7435)" in the [2020-12-07](https://store.steampowered.com/oldnews/78652) Steam client update.

**Comment by XakepSDK** [comment] 2021-03-02 18:40
Working for me

**Comment by kisak-valve** [comment] 2021-04-02 16:29
Thanks for retesting, closing as fixed.

**Closed by kisak-valve** 2021-04-02 16:29 UTC
Labels: Need Retest, Proton, Steam client
