### ISSUE TITLE
CS2 is broken for most Linux users with newer graphics cards after 7/11 update

### ISSUE THREAD

**Issue by ageisen2000** [ValveSoftware/steam-for-linux#11179] opened 2024-08-10 16:28 UTC
#### Your system information

* Steam client version (build number or date): na
* Distribution (e.g. Ubuntu): bazzite Nvidia (fedora)
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD: nvidia

#### Please describe your issue in as much detail as possible:
Many Linux users are experiencing issues with CS2 freezing randomly when opening menus. I tried creating a support ticket and they sent me here to create an issue. 

For additional details, please see the comments here: https://github.com/ValveSoftware/csgo-osx-linux/issues/3803

#### Steps for reproducing this issue:

1. Be on bazzite distro (others are effected too) with a newer graphics card (and and Nvidia are both effected)
2. Go into a game 
3. Press escape, the game will freeze for a long time

**Comment by kisak-valve** [comment] 2024-08-10 17:13
Hello @ageisen2000, please do not intentionally open duplicate issue reports.

Closing as a duplicate of https://github.com/ValveSoftware/csgo-osx-linux/issues/3803.

**Closed by kisak-valve** 2024-08-10 17:13 UTC

**Comment by ageisen2000** [comment] 2024-08-10 17:31
> Hello @ageisen2000, please do not intentionally open duplicate issue reports.
> 
> Closing as a duplicate of [ValveSoftware/csgo-osx-linux#3803](https://github.com/ValveSoftware/csgo-osx-linux/issues/3803).

I was advised by steam support to open the issue in this repo, sorry.
