### ISSUE TITLE
Steam doesn't start

### ISSUE THREAD

**Issue by FrancoAndres** [ValveSoftware/steam-for-linux#4736] opened 2016-12-04 22:23 UTC
#### Your system information

* Steam client version: 

$ sudo aptitude show steam-launcher 
Package: steam-launcher                  
New: yes
State: installed
Automatically installed: no
Multi-Arch: foreign
Version: 1.0.0.54

* Distribution (e.g. Ubuntu): 

Debian

* Opted into Steam client beta?: [Yes/No] 

?

* Have you checked for system updates?: [Yes/No]

yes.

#### Please describe your issue in as much detail as possible:

Steam doesn't start.

```
$ steam
Running Steam on debian 8 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1476379980)
Installing breakpad exception handler for appid(steam)/version(1476379980)
Installing breakpad exception handler for appid(steam)/version(1476379980)

(steam:4781): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(steam:4781): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Adwaita/gtk-2.0/gtkrc:1163: error: unexpected identifier `direction', expected character `}'
Installing breakpad exception handler for appid(steam)/version(1476379980)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[1204/182034:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
[1204/182034:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20161013004706)
Installing breakpad exception handler for appid(steamwebhelper)/version(1476319626)
[1204/182034:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
Installing breakpad exception handler for appid(steamwebhelper)/version(20161013004706)
Installing breakpad exception handler for appid(steamwebhelper)/version(1476379980)
Installing breakpad exception handler for appid(steamwebhelper)/version(1476379980)
ICE default IO error handler doing an exit(), pid = 4781, errno = 2
[2016-12-04 18:20:33] Startup - updater built Oct 13 2016 00:47:16
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2016-12-04 18:20:33] Checking for update on startup
[2016-12-04 18:20:33] Checking for available updates...
[2016-12-04 18:20:34] Download skipped: /client/steam_client_ubuntu12 version 1476379980, installed version 1476379980
[2016-12-04 18:20:34] Nothing to do
[2016-12-04 18:20:34] Verifying installation...
[2016-12-04 18:20:34] Performing checksum verification of executable files
[2016-12-04 18:20:34] Verification complete
Assert( Assertion Failed: CFrameFunctionMgr::~CFrameFunctionMgr: non static FrameFunction[CHTTPClient::BFrameFuncHandleCompletedWorkItems] still registered ):framefunction.cpp:120

Installing breakpad exception handler for appid(steam)/version(1476379980)
crash_20161204182040_2.dmp[4810]: Uploading dump (out-of-process)
/tmp/dumps/crash_20161204182040_2.dmp
framefunction.cpp (120) : Assertion Failed: CFrameFunctionMgr::~CFrameFunctionMgr: non static FrameFunction[CHTTPClient::BFrameFuncHandleCompletedWorkItems] still registered
crash_20161204182040_2.dmp[4810]: Finished uploading minidump (out-of-process): success = yes
crash_20161204182040_2.dmp[4810]: response: CrashID=bp-d7fb8949-720f-4218-adcb-944b12161204
crash_20161204182040_2.dmp[4810]: file ''/tmp/dumps/crash_20161204182040_2.dmp'', upload yes: ''CrashID=bp-d7fb8949-720f-4218-adcb-944b12161204''

```

**Comment by Tele42** [comment] 2016-12-04 22:33
Duplicate of #4335.

The distro-provided steam package appears to be [1.0.0.49](https://packages.debian.org/jessie/steam). Does this issue occur if you use the package from Debian?

**Comment by gdrewb-valve** [comment] 2016-12-05 05:52
Closing duplicate.

**Closed by gdrewb-valve** 2016-12-05 05:52 UTC

**Comment by FrancoAndres** [comment] 2016-12-05 18:36
hello??

**Comment by FrancoAndres** [comment] 2016-12-05 18:37
Thenks guis, I didt seen it
