### ISSUE TITLE
Taking more than one screenshot in a short amount of time makes the game crash/unresponsive

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#5120] opened 2017-08-07 12:22 UTC
#### Your system information

* Steam client version (build number or date): 17/7/17
* Distribution (e.g. Ubuntu): Ubuntu gnome 17.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Taking more than one screenshot in a short amount of time makes the game crash/unresponsive

#### Steps for reproducing this issue:

1. Launch a game
2. Click F12 more than one time
3. Game needs to be killed by terminal, it will no longer respond

**Comment by kisak-valve** [comment] 2017-08-14 17:35
Related to #4928.

**Comment by af7567** [comment] 2017-09-08 10:13
I have been having this problem with Unity games for a while now on stable and beta steamclients.  I first noticed it in Rust a few months ago and it is now happening in Golf with your friends, Armello, Layers of fear and Human: fall flat. 

In rust, layers of fear and human: fall flat I can take 1 screenshot per session and then no more until restarting the game.
In Golf with your friends taking a screenshot causes the games graphics to freeze.
In Armello screenshots don't work at all, but the overlay in general doesn't seem to work right in Armello.

**Comment by kisak-valve** [comment] 2018-06-04 13:07
Closing as a duplicate of #4928.

**Closed by kisak-valve** 2018-06-04 13:07 UTC
Labels: overlay
