### ISSUE TITLE
Steam Remote Play freezing into "Remote computer is performing first time setup"

### ISSUE THREAD

**Issue by fabiancabau** [ValveSoftware/steam-for-linux#6275] opened 2019-05-17 14:54 UTC
#### Your system information

* Steam client version: May 15, 2019, 21:17:00 - 1557957375
* Distribution: Deepin OS 15.9 and Zorin OS 12
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Enabled Steam Beta on Windows 10 PC, enabled Steam Beta in both Deepin OS 15.9 and Zorin OS 12. Tried to stream games from Windows 10 PC using the newest Remote Play, not on the same network as the Win10 PC. The game opens up in the Remote PC, but the Linux Steam client freezes on the "Remote computer is performing first time setup" screen.

#### Steps for reproducing this issue:

1. Enable Steam Beta on Windows 10 PC
2. Enable Steam Beta on Linux
3. Enable Remote Play on Both
4. Try to Stream a game from the Windows 10 PC in the Linux machine (not on the same network)
5. Game should open in the Windows 10 PC, Linux Steam will freeze into "Remote computer is performing first time setup"
![DeepinScreenshot_select-area_20190517115354](https://user-images.githubusercontent.com/6144269/57936493-7da87700-789a-11e9-94cf-359f03f5d890.png)

**Comment by joeknock90** [comment] 2019-05-17 15:12
I am getting the same issue streaming from Linux to Linux:

#### Your system information

* Steam client version (build number or date): May 15 2019, at 21:17:00
* Distribution (e.g. Ubuntu): Arch Linux (Host and Client)
* Opted into Steam client beta?: Yes (Host and Client)
* Have you checked for system updates?: Yes (Both host and client packages up to date)

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Same steps as above EXCEPT

It seems that even games that do not require first time setup are also not working. Steam client on client PC will either freeze or crash completely. Steam on host continues to run fine and usually even starts the game.

I have tried both Steam (Runtime and Steam-Native provided by Arch Linux packages

I can create a new issue if needed.

**Comment by parkerlreed** [comment] 2019-05-21 23:10
Same here. Linux host/Linux client. It freezes and after a while crashes out. Seems to segfault at the driver level. Tried both Intel and AMD.

Client https://gist.github.com/parkerlreed/43f7a5ee2b3588cbba12274564daae67

Host https://gist.github.com/parkerlreed/cb146f2b3f0e83af12f529e6130c12c3

The game continues to run on the host.

```
[parker@stealth ~]$ coredumpctl info 9326
           PID: 9326 (steam)
           UID: 1000 (parker)
           GID: 1000 (parker)
        Signal: 11 (SEGV)
     Timestamp: Tue 2019-05-21 18:48:17 EDT (7min ago)
  Command Line: /home/parker/.local/share/Steam/ubuntu12_32/steam
    Executable: /home/parker/.local/share/Steam/ubuntu12_32/steam
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (parker)
       Boot ID: d14cb38cebf34c9383bd59b719178540
    Machine ID: 175eb21d26bc4b75a833309c038d32c8
      Hostname: stealth
       Storage: /var/lib/systemd/coredump/core.steam.1000.d14cb38cebf34c9383bd59b719178540.9326.1558478897000000.lz4
       Message: Process 9326 (steam) of user 1000 dumped core.
                
                Stack trace of thread 9400:
                #0  0x00000000f7000000 n/a (radeonsi_dri.so)
                #1  0x00000000ecf9d5ae n/a (/home/parker/.local/share/Steam/ubuntu12_32/libvstdlib_s.so)
                #2  0x00000000ecf9d655 n/a (/home/parker/.local/share/Steam/ubuntu12_32/libvstdlib_s.so)
                #3  0x00000000ecf9dcc7 n/a (/home/parker/.local/share/Steam/ubuntu12_32/libvstdlib_s.so)
                #4  0x00000000ecf9dfcf n/a (/home/parker/.local/share/Steam/ubuntu12_32/libvstdlib_s.so)
[parker@stealth ~]$ coredumpctl info 2219
           PID: 2219 (steam)
           UID: 1000 (parker)
           GID: 1000 (parker)
        Signal: 11 (SEGV)
     Timestamp: Tue 2019-05-21 18:59:30 EDT (4min 44s ago)
  Command Line: /home/parker/.local/share/Steam/ubuntu12_32/steam
    Executable: /home/parker/.local/share/Steam/ubuntu12_32/steam
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (parker)
       Boot ID: 33b9b34f5f9a4a30ae86235ab0d97ce5
    Machine ID: 175eb21d26bc4b75a833309c038d32c8
      Hostname: stealth
       Storage: /var/lib/systemd/coredump/core.steam.1000.33b9b34f5f9a4a30ae86235ab0d97ce5.2219.1558479570000000.lz4
       Message: Process 2219 (steam) of user 1000 dumped core.
                
                Stack trace of thread 2255:
                #0  0x00000000f7000000 n/a (i965_dri.so)
                #1  0x00000000f4ad95ae n/a (/home/parker/.local/share/Steam/ubuntu12_32/libvstdlib_s.so)
                #2  0x00000000f4ad9655 n/a (/home/parker/.local/share/Steam/ubuntu12_32/libvstdlib_s.so)
                #3  0x00000000f4ad9cc7 n/a (/home/parker/.local/share/Steam/ubuntu12_32/libvstdlib_s.so)
                #4  0x00000000f4ad9fcf n/a (/home/parker/.local/share/Steam/ubuntu12_32/libvstdlib_s.so)
```

**Comment by parkerlreed** [comment] 2019-05-21 23:55
Would the dump created by Steam help? Let me know if that's good to share here.

**Comment by parkerlreed** [comment] 2019-05-22 22:31
I tried again today with steam-native and actually saw streaming_client itself bail

```
[parker@stealth ~]$ coredumpctl info 27568
           PID: 27568 (streaming_clien)
           UID: 1000 (parker)
           GID: 1000 (parker)
        Signal: 3 (QUIT)
     Timestamp: Wed 2019-05-22 18:26:10 EDT (3min 59s ago)
  Command Line: /home/parker/.local/share/Steam/ubuntu12_32/streaming_client --gameid 233470 --server 0.0.0.0:27031 --transport k_EStreamTransportUDPRelay --relay 162.254.192.84:28381 --quality 2 072e5d6e9525f0cb22c5ee3efb9126235bcf6df2d0>
    Executable: /home/parker/.local/share/Steam/ubuntu12_32/streaming_client
 Control Group: /user.slice/user-1000.slice/session-5.scope
          Unit: session-5.scope
         Slice: user-1000.slice
       Session: 5
     Owner UID: 1000 (parker)
       Boot ID: 581a7076524b4fdea41dcb88b87f418a
    Machine ID: 175eb21d26bc4b75a833309c038d32c8
      Hostname: stealth
       Storage: /var/lib/systemd/coredump/core.streaming_clien.1000.581a7076524b4fdea41dcb88b87f418a.27568.1558563970000000.lz4
       Message: Process 27568 (streaming_clien) of user 1000 dumped core.
                
                Stack trace of thread 27568:
                #0  0x00000000f7f4d929 __kernel_vsyscall (linux-gate.so.1)
                #1  0x00000000f71fbf07 __poll (libc.so.6)
                #2  0x00000000f580ec04 n/a (/home/parker/.local/share/Steam/ubuntu12_32/steamclient.so)
                #3  0x00000000f580cbcd n/a (/home/parker/.local/share/Steam/ubuntu12_32/steamclient.so)
                #4  0x00000000f580cde0 n/a (/home/parker/.local/share/Steam/ubuntu12_32/steamclient.so)
                #5  0x00000000f57fdde4 n/a (/home/parker/.local/share/Steam/ubuntu12_32/steamclient.so)
                #6  0x00000000f60fd28f n/a (/home/parker/.local/share/Steam/ubuntu12_32/steamclient.so)
                #7  0x00000000f60fd937 n/a (/home/parker/.local/share/Steam/ubuntu12_32/steamclient.so)
                #8  0x000000005665295f n/a (/home/parker/.local/share/Steam/ubuntu12_32/streaming_client)
```

**Comment by enthalpie** [comment] 2019-05-25 12:00
I am having issues with in-home streaming as well. It all worked fine, then I got several updates. Steam updated, the kernel and the padoka-devel ppa for AMD. After that my host machine freezes now when I try to start in home streaming from the steam link. It seems to be a GPU hang since all 7 LEDs on the Vega 64 are lit and the system is frozen, can still ssh into it but the gpu hang even prohibits a soft reboot.

I have tried reverting back to an older kernel and tried opting out of steam beta no luck. So it seems to be GPU driver related.

I am on Ubuntu 18.04.2, 5.0.0-18.1-liquorix-amd64 with padoka-devel ppa

**Comment by lovemoebius** [comment] 2019-05-25 20:03
I am also experiencing this issue.
Running Ubuntu 18.10.

I tried a Windows laptop to see if it was a problem with the Host but that works flawlessly so it's definitely a problem with the Linux Steam Client.

**Comment by enthalpie** [comment] 2019-05-25 21:56
In my case it could be Vega gpu related. When the host dies, kernel error gives a VMA page fault error.

**Comment by BalanarAHN** [comment] 2019-05-27 07:18
Same issue after last beta update. 

**Your system information**
Steam client version: May 22 2019 21:55:25 - 1558567098
Distribution:  Ubuntu 18.04 
Opted into Steam client beta?: Yes
Have you checked for system updates?: Yes

**Please describe your issue in as much detail as possible:**
Update and enabled Steam Beta on Windows 10 PC, enabled Steam Beta in Ubuntu 18.04. Tried to stream games from Windows 10 PC using the newest Remote Play, using hamachi and own VPN connection (brefore last beta update all works fine). The game opens up in the Remote PC, but the Linux Steam client stucked on the "Remote computer is performing first time setup" screen, BUT on host game launch anyway. The problem is that the client does not start the window with the stream.

Steps for reproducing this issue:
Enable Steam Beta on Windows 10 PC
Enable Steam Beta on Linux
Enable Remote Play on Both
Try to Stream a game from the Windows 10 PC in the Ubuntu machine (via hamachi and other own VPN)
Game launched and opened in the Windows 10 PC, but  on Ubuntu Steam will freeze into "Remote computer is performing first time setup" and didnt opening stream window.

**Comment by joeknock90** [comment] 2019-05-30 18:41
It seems to be entirely the streaming client. Streaming from Linux to Windows works fine.

**Comment by michealharrington** [comment] 2019-06-06 18:06
I also have the same issue. It hangs when trying to stream from my Windows PC to my Fedora PC.

**Comment by creativiii** [comment] 2019-06-08 09:42
Eventually got fed up waiting for a fix and moved my Windows Desktop on the same network.
Seems like the problem, at least for me, has now also extended to In-Home streaming.

Steam doesn't crash, but the game starts and Steam on Ubuntu tells me it couldn't connect to the remote desktop.

This used to work flawlessly a few weeks ago so I don't even know where to start with this.

**Comment by joeknock90** [comment] 2019-06-08 12:16
Yep. My in home streaming setup has been broken for over 2 weeks now. It's definitely a problem with the Linux streaming client.

**Comment by creativiii** [comment] 2019-06-10 07:28
After some testing, removing beta participation from both clients seems to at least fix in-home streaming. 

I still had some temporary issues where Linux wasn't able to connect to the remote desktop, but I managed to fix that with a restart of both clients. It has worked fine for the past two days.

**Comment by bandmask** [comment] 2019-06-14 22:09
Having the same problem still going with Windows host and Linux client. Is the problem still there for you with Linux hosts?

**Comment by joeknock90** [comment] 2019-06-16 23:48
Doesn't seem to matter what the host is. It's the Linux streaming client in the beta update that's causing the problem.

**Comment by ronlaws86** [comment] 2019-06-17 13:09
Confirmed here too, Steam client hangs while reporting "Remote computer is performing first time setup" (Even though it's actually launching the game, no setup process is running) then it eventually exits.

**Comment by nalquas** [comment] 2019-06-17 14:45
Same thing is happening here, tried it from multiple networks.

**Comment by justinbarnett** [comment] 2019-06-19 04:16
The Beta client is now the live client. So it's broken for live and beta now.

**Comment by creativiii** [comment] 2019-06-19 07:22
> The Beta client is now the live client. So it's broken for live and beta now.

Thank you Valve, very cool

**Comment by joeknock90** [comment] 2019-06-19 12:41
Ok, NOW my streaming setup is completely broken.

**Comment by hardpenguin** [comment] 2019-06-21 05:49
I am also affected by this issue.

**Comment by JaredBanyard** [comment] 2019-06-21 18:04
Same here. Win 10 -> Ubuntu 18.04. Non-Beta Clients. Linux Client Crashes.

**Comment by bostrot** [comment] 2019-06-22 05:55
Works the other way around (Windows 10 - > Ubuntu 18.04) so it definetely is not a host issue.

**Comment by randomei** [comment] 2019-06-25 07:44
Same here. Linux client crashes.

**Comment by bandmask** [comment] 2019-06-25 09:36
Is there anyone from steam looking at this? 
Over a month old and no feedback.

**Comment by joeknock90** [comment] 2019-06-25 10:40
It does feel a little silly that they brought a broken feature from beta to stable, breaking the stable client as well.

**Comment by creativiii** [comment] 2019-06-25 20:04
I wrote a support ticket in the hope of making someone at Valve aware of the bug. Maybe that will help?

**Comment by joeknock90** [comment] 2019-06-25 21:58
@creativiii 

Honestly, it's probably more like 90% now. I don't know why but it's basically just working now.

**Comment by creativiii** [comment] 2019-06-25 22:03
> @creativiii
> 
> Honestly, it's probably more like 90% now. I don't know why but it's basically just working now.

I wish I could say the same. I go from crashes to "could not connect". I've managed to connect once for about 5 seconds, that was about it.

**Comment by orbsthetics** [comment] 2019-06-26 03:06
I run into this issue as well from Ubuntu 18.04 -> Windows 10 however what "fixes" it for me is to login to the Windows machine locally, not remotely. Once past the login screen I go back to my Ubuntu laptop and can stream anything just fine.

I have run into weird login issues like this before where if I remote into the Windows desktop using like Remmina, then stream, I will get the login screen for Windows but no sound once logged in. However if I quit the game then re-stream, I don't get the login screen but will now have sound.

**Comment by atm0915** [comment] 2019-06-27 21:10
Getting the same issue here. Linux --> Linux.

**Comment by parkerlreed** [comment] 2019-06-27 21:40
I can now remote stream as of the latest update

**Comment by parkerlreed** [comment] 2019-06-27 21:43
https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1602634609613937361

**Comment by parkerlreed** [comment] 2019-06-27 21:47
Limited to software decode but I expected that by now... 

![image](https://user-images.githubusercontent.com/841440/60303102-92e5dc00-9903-11e9-9feb-62ca9bf7f4f8.png)

**Comment by BalanarAHN** [comment] 2019-06-28 00:39
After today's update of Windows Steam client In-Home Streaming Works correctly. Will continue to observe

**Comment by joeknock90** [comment] 2019-06-28 01:07
I am working consistently as well now. Thanks volvo.

**Comment by fabiancabau** [comment] 2019-07-01 22:52
Working fine for me too. Great job!

**Comment by bandmask** [comment] 2019-07-03 12:09
I still can not stream in home from host (Windows 10) to client (Ubuntu 18.04)

**Comment by creativiii** [comment] 2019-07-03 12:14
I'll be honest if I try to start a game steam will tell me it can't connect to remote desktop about 90% of times. Sometimes I can just click on the game that's already been started and it will connect, but most times I need to restart both Steam clients. 

This is still pretty far from being fixed knowing that a month ago this worked flawlessly

**Comment by parkerlreed** [comment] 2019-07-03 12:24
@bandmask Are you on the beta client in Ubuntu? I don't think the fix has hit stable yet.

**Comment by howels** [comment] 2019-07-04 11:18
Same issue here. Plus, if the streaming continues after this then it will grab the first frame of host video output and freeze on the client, whilst the host continues.

**Comment by SamsonCoder** [comment] 2019-07-09 14:00
Even without the Steam Beta thing, it freezes. Something is wrong with the Host, then.... I'm assuming.
For now I'm just using Parsec. Until then I'll just use Parsec. When there will be an update that patches it, I may use the Steam Remote Play thing or maybe Parsec.

**Comment by LaurentDumont** [comment] 2019-07-10 01:38
With the non-beta client, I was unable to stream to a Ubuntu 19.04 laptop from a Windows 10 machine. Everything seems to work okay with the new beta client.

**Comment by mlassnig** [comment] 2019-07-14 18:15
I am on beta on both host and client Linux machines over the internet. Steam on both host and client find each other automatically, and I can click on "Stream from <other host>", then client screen goes black, game starts on host, and after a few seconds "Couldn't connect to remote computer", and game on host has to be kill -9 via ssh. Not entirely sure what to do now, host machine is unlocked (no screensaver, etc..), but I do not have any ports forwarded.

**Comment by LaurentDumont** [comment] 2019-07-15 02:21
> I am on beta on both host and client Linux machines over the internet. Steam on both host and client find each other automatically, and I can click on "Stream from ", then client screen goes black, game starts on host, and after a few seconds "Couldn't connect to remote computer", and game on host has to be kill -9 via ssh. Not entirely sure what to do now, host machine is unlocked (no screensaver, etc..), but I do not have any ports forwarded.

How are you discovering the other PC? As far as I know, the steam stream uses multicast packets to discover other endpoints. By default, it's designed to work on the same L2 broadcast domain. You usually have to use a Multicast daemon on your "router" to allow the multicasts packets to reach beyond the subnet of the Steam host.

**Comment by mlassnig** [comment] 2019-07-15 05:53
> > I am on beta on both host and client Linux machines over the internet. Steam on both host and client find each other automatically, and I can click on "Stream from ", then client screen goes black, game starts on host, and after a few seconds "Couldn't connect to remote computer", and game on host has to be kill -9 via ssh. Not entirely sure what to do now, host machine is unlocked (no screensaver, etc..), but I do not have any ports forwarded.
> 
> How are you discovering the other PC? As far as I know, the steam stream uses multicast packets to discover other endpoints. By default, it's designed to work on the same L2 broadcast domain. You usually have to use a Multicast daemon on your "router" to allow the multicasts packets to reach beyond the subnet of the Steam host.

I just have the Steam linux application running on both host and client. The client finds the host automatically (I have paired them previously through Settings->Remote Play), even though I'm in a different country right now. But starting a game results in the client black screen and the error message.

**Comment by LaurentDumont** [comment] 2019-07-15 20:10
> > > I am on beta on both host and client Linux machines over the internet. Steam on both host and client find each other automatically, and I can click on "Stream from ", then client screen goes black, game starts on host, and after a few seconds "Couldn't connect to remote computer", and game on host has to be kill -9 via ssh. Not entirely sure what to do now, host machine is unlocked (no screensaver, etc..), but I do not have any ports forwarded.
> > 
> > 
> > How are you discovering the other PC? As far as I know, the steam stream uses multicast packets to discover other endpoints. By default, it's designed to work on the same L2 broadcast domain. You usually have to use a Multicast daemon on your "router" to allow the multicasts packets to reach beyond the subnet of the Steam host.
> 
> I just have the Steam linux application running on both host and client. The client finds the host automatically (I have paired them previously through Settings->Remote Play), even though I'm in a different country right now. But starting a game results in the client black screen and the error message.

I'm a bit puzzled by this. Most of the doc I find reference streaming from a PC to an Android device/Steam link device, not from a PC to a PC over the internet. I feel like this requires a VPN/l2 tunneling.

**Comment by kisak-valve** [comment] 2019-08-16 15:01
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by SamsonCoder** [comment] 2019-08-16 15:03
I don't know... have not tried.

**Comment by creativiii** [comment] 2019-08-16 15:08
> Hello, is anyone still experiencing this issue on an up to date system?

It is far from perfect. It still does not perform as well as it used to before the update that broke it.
Previously I was able to immediately connect to a game without many problems, while now I usually have to do this:

- Click Stream
- Wait for it to time out
- Try to connect while the game is running

I usually have to do this 2 or three times before it actually connects.

But I suppose the original issue is resolved.

**Comment by howels** [comment] 2019-08-23 22:01
Remote Play working but only when not using Steam Play (Proton). Which is a shame given the huge number of proton-based games which became playable under Linux.

**Comment by kisak-valve** [comment] 2019-09-27 19:22
Closing as it appears the original issue has been resolved.

@howels, there's a some Proton + streaming issues being tracked at #5770, #5831, #6200, #6516 which may be worth comparing to your experience.

**Closed by kisak-valve** 2019-09-27 19:22 UTC
Labels: Need Retest, Steam client, Streaming

**Comment by LoganPaulFanSIKE** [comment] 2019-11-23 11:10
Guys if Steam Remote Play isn't working, try and turn of your Windows Firewall (Search up how to do that) and hopefully that should work

**Comment by howels** [comment] 2019-11-25 11:25
> Guys if Steam Remote Play isn't working, try and turn of your Windows Firewall (Search up how to do that) and hopefully that should work

This is a Linux issue, Windows is irrelevant.
