### ISSUE TITLE
.local/share/Steam/steam.sh: líne 798: 16744 Aborted

### ISSUE THREAD

**Issue by Izaise** [ValveSoftware/steam-for-linux#10011] opened 2023-08-24 23:36 UTC
Recently updated linux and steam stopped opening

Console Log:

steam.sh[16600]: Running Steam on arch rolling 64-bit
steam.sh[16600]: STEAM_RUNTIME is enabled automatically
setup.sh[16674]: Steam runtime environment up-to-date!
steam.sh[16600]: Steam client's requirements are satisfied
Startup - updater built Jul 28 2023 18:44:09
Startup - Steam Client launched with: '(user).local/share/Steam/ubuntu12_32/steam'
08/24 20:16:00 Init: Installing breakpad exception handler for appid(steam)/version(1690583737)/tid(16744)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
 Loading cached metrics from disk ((user).local/share/Steam/package/steam_client_metrics.bin)
 Using the following download hosts for Public, Realm steamglobal
 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
 Checking for update on startup
 Checking for available updates...
 Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12
 Manifest download: send request
 Manifest download: waiting for download to finish
 Manifest download: finished
 Download skipped: /steam_client_ubuntu12 version 1690583737, installed version 1690583737, existing pending version 0
 Nothing to do
 Verifying installation...
 Performing checksum verification of executable files
 Verification complete
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xe8890db0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xe888f500
GetWin32Stats: display was not open yet, good
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[16776]: Runtime for steamwebhelper: defaulting to (user).local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[16776]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
CAppInfoCacheReadFromDiskThread took 632 milliseconds to initialize
vkEnumeratePhysicalDevices failed, unable to init and enumerate GPUs with Vulkan.
BInit - Unable to initialize Vulkan!
vkEnumeratePhysicalDevices failed, unable to init and enumerate GPUs with Vulkan.
BInit - Unable to initialize Vulkan!
sh: líne 1: xdg-user-dir: order not found
sh: líne 1: xdg-user-dir: order not found
Assertion 'device' failed at src/libsystemd/sd-device/device-private.c:103, function device_get_tags_generation(). Aborting.
crash_20230824201610_25.dmp[16974]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230824201610_25.dmp
crash_20230824201610_25.dmp[16974]: Finished uploading minidump (out-of-process): success = yes
crash_20230824201610_25.dmp[16974]: response: CrashID=bp-209fdebd-6750-4ac0-a3c1-77c5d2230824
crash_20230824201610_25.dmp[16974]: file ''/tmp/dumps/crash_20230824201610_25.dmp'', upload yes: ''CrashID=bp-209fdebd-6750-4ac0-a3c1-77c5d2230824''
(user).local/share/Steam/steam.sh: líne 798: 16744 Aborted                (`core' generated) "$STEAMROOT/$STEAMEXEPATH" "$@"

**Comment by kisak-valve** [comment] 2023-08-24 23:43
Hello @Izaise, `Assertion 'device' failed at src/libsystemd/sd-device/device-private.c:103, function device_get_tags_generation(). Aborting.` is the key detail here and makes this issue a duplicate of #9805.

Closing as a duplicate.

**Closed by kisak-valve** 2023-08-24 23:43 UTC

**Comment by Izaise** [comment] 2023-08-25 00:29
Sorry!
