### ISSUE TITLE
 Watching videos in full screen disables compositor

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#6258] opened 2019-05-05 05:53 UTC
#### Your system information

* Steam client version (build number or date): May 2 2019, at 00:33:37
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Desktop Environment: KDE with KWin

Watching videos in full screen disables compositor and because of this going full screen is slow until compositor disables. Turning off full screen is also slow because steam waits until compositor enabled.

**Comment by kisak-valve** [comment] 2019-05-05 12:37
Hello @XakepSDK, this reads like https://userbase.kde.org/Desktop_Effects_Performance#Suspend_desktop_effects_for_fullscreen_windows behaving as intended and not a Steam-specific issue. A slow transition sounds like a window manager issue and should be mentioned to the kwin devs.

**Comment by kisak-valve** [comment] 2021-10-01 20:34
Closing because this does not appear to be a Steam issue.

**Closed by kisak-valve** 2021-10-01 20:34 UTC
Labels: Window manager, Web Component
