### ISSUE TITLE
"see more: Upcoming releases" filter is broken for Linux and Mac but works for Windows

### ISSUE THREAD

**Issue by Swiftpaw** [ValveSoftware/steam-for-linux#3806] opened 2015-04-21 19:10 UTC
At the bottom of the main Steam Featured page is a list section with some tabs.  One of those is "Upcoming".  If you click on that, then click on the "Upcoming releases" button at the bottom, even when there are Linux games showing in that list in that tab before clicking it, the page it takes you to with the filters along the right side is always blank for Linux.  If you change the selection to Mac, that is blank as well.  But, if you change it to Windows, suddenly you get all the upcoming games results including the Linux and Mac games.

**Comment by Swiftpaw** [comment] 2015-04-23 17:16
Sorry, I meant the upcoming releases filter is broken for both Linux and Mac, but works for Windows.

**Comment by gdrewb-valve** [comment] 2015-04-27 19:31
Duplicate of #3753.

**Closed by gdrewb-valve** 2015-04-27 19:31 UTC
Labels: duplicate, reviewed
