### ISSUE TITLE
Steamwebhelper Out of Memory, Inhibits GUI Launch

### ISSUE THREAD

**Issue by LRitzdorf** [ValveSoftware/steam-for-linux#9764] opened 2023-06-30 07:36 UTC
#### System Information

* Steam client version (build number or date): Jun 21, 2023
* Distribution (e.g. Ubuntu): Arch Linux (fully up to date as of posting)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia

#### Issue Description
When launching Steam with the new GUI, the Steam Web Helper crash-loops with an "out of memory" error, despite total memory utilization not exceeding ~22% of my system's 16GB.

Following suggestions from related issues, I tested with the `-vgui` flag, which prevents looping, but not the initial crash. As a result, the old GUI *kind of* works, but lacks chat features. Also, in this mode, certain Settings items are apparently not saved, and the Storage Settings area (where extra library locations are configured) is completely inaccessible. (In fact, attempting to access it causes the web helper to start and crash again, reopening the chat window in the process.)

#### Issue Reproduction
1. Install the `steam` package on Arch Linux
2. Launch Steam with no CLI options (ideally from terminal, to observe stdout)
3. Observe logs and standard output

[steamwebhelper.log](https://github.com/ValveSoftware/steam-for-linux/files/11913876/steamwebhelper.log) (rewritten every ~10 seconds with identical content, as the Web Helper repeatedly crashes)

Happy to facilitate troubleshooting — please let me know if you'd like me to test anything!

### Apparent Solution
Removing `~/.cache/nvidia/GLCache` seems to resolve this issue. (At the time of writing this, only two users have tested this, so YMMV.)

**Comment by fontivan** [comment] 2023-06-30 14:05
+1 same issue on Fedora 38 using rpm package from rpmfusion.

Adding `-vgui` as suggested by LRitzdorf does allow steam to launch in the old ui but as noted there is various features unavailable.

**Comment by LRitzdorf** [comment] 2023-06-30 16:44
...okay, I hate to be this guy, but the issue has resolved itself for me. It seems to have been helped by removing `~/.cache/nvidia/GLCache`` and `~/.local/share/vulkan/implicit_layer.d/steam*.json`, though I have no idea why either of those would affect the web helper.

Also, @fontivan and @vityafx: note that there are several other issues with the Steam Web Helper, so unless you can see it crashing with the same out-of-memory error, don't assume that this specifically is your issue — try looking at some of the other Web Helper posts here, and maybe try their suggested solutions (if any).

**Comment by fontivan** [comment] 2023-06-30 16:50
@LRitzdorf I had exactly the same steamwebhelper.log crashes with the constant loop.
However I can confirm that deleting `~/.cache/nvidia/GLCache` immediately fixes my client.

I did recently update my nvidia driver to 535 which could be related? Though client has been a bit troublesome since the new UI update so I am not sure.

**Comment by LRitzdorf** [comment] 2023-06-30 17:04
Okay, good, just wanted to make sure you hadn't been drawn here by the fact that this was a recently-created issue.

The weird thing about this issue for me is that it appeared when I wiped and remade the disk partition containing my home directory. Nothing outside of `/home/me` was touched, and system packages stayed the same. This makes it even stranger that clearing the GL cache would help — those files had to have been very recently created by Steam anyway. (Then again, I know very little about the inner workings of the Steam client, so I'm just glad to have found a solution).

**Comment by pixelat3d** [comment] 2023-07-14 03:55
Nvidia Driver version: 535.54.03    CUDA Version: 12.2

Confirming that removing ~/.cache/nvidia/GLCache also fixed the issue for me on fedora 38. Also confirm that -vgui launched, but that way there be dragons, lol

**Comment by GeoMarkou** [comment] 2023-07-17 22:42
I had this issue after a fresh install. I reinstalled Linux Mint and all my apps (including Steam), before realising I was still using the Nouveau graphics drivers instead of the proprietary NVIDIA ones. I switched to the latest (v535) and restarted my machine; upon reboot Steam stopped working as above. It would appear as an icon in the tray, but clicking any menu items like Library or Store didn't work. I uninstalled Steam completely and reinstalled it to no avail. Running `steam` via command line printed strange messages over and over in an infinite loop:

```
partially disabling sandbox until CEF supports clone3()
Runtime for steamwebhelper: defaulting to [PATH]
```

Following advice, I went to `~/.cache/nvidia/GLCache` and renamed all the GUID folders to have an underscore `_` (just in case). As soon as I renamed the last folder, suddenly all the folders disappeared, and Steam appeared out of nowhere. Another thing to note is I was previously using this exact configuration and drivers before reinstalling Linux, which might give credit to the "changing drivers broke something" theory.

Hopefully this helps debug the issue - I can provide logs if requested.

**Comment by deabru** [comment] 2023-07-18 12:04
Wild, removing `~/.cache/nvidia/GLCache` works. Reboot... and still works.

Nvidia rtx2060; openSUSE Leap 15.5; drivers version: 535.54.03.

**Comment by mdruby** [comment] 2023-07-19 17:11
Nvidia driver version 535.86.05 that was just released fixes the issue for me.

**Comment by kisak-valve** [comment] 2023-08-25 17:40
Closing per the last comment.

**Closed by kisak-valve** 2023-08-25 17:40 UTC
Labels: Need Retest, Distro Family: Arch, Web Component
