### ISSUE TITLE
Steam segfaults entering BPM

### ISSUE THREAD

**Issue by phantom-voltage** [ValveSoftware/steam-for-linux#4530] opened 2016-07-02 17:11 UTC
#### Your system information
- Steam client version: 1465948400
- Distribution (e.g. Ubuntu): Ubuntu 16.04
- Opted into Steam client beta?: No
- Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:

Launching Big Picture Mode crashes Steam. 

Output from command line when launching Steam and then clicking the BPM icon.

```
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME has been set by the user to: /home/mcp/.steam/ubuntu12_32/steam-runtime
Refresh rate: 15
Refresh rate: 15
Refresh rate: 15
Refresh rate: 15
Refresh rate: 15
Refresh rate: 15
Refresh rate: 15
Refresh rate: 15
Refresh rate: 60
Refresh rate: 60
Refresh rate: 60
```

Launching Steam with -tenfoot:

```
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
```

As you can see, nothing shows up in the command line, however, using journactl -xe, I found:

`Jul 01 22:10:37 htpc kernel: steam[4214]: segfault at 0 ip 00000000f72ba561 sp 00000000ffb6281c error 4 in libc-2.23.so[f7245000+1af000]`

Extended log from journactl -xe is found [here](https://gist.github.com/phantom-voltage/21e75840bf9e5a55d9eaf25326a10878).

This is on a fresh install of Ubuntu 16.04. I was previously running 15.10, where Steam BPM was working until I received a Steam update a few days ago. After the update I got the same error in libc. It was suggested to me to move to a supported release in the Steam forums, however I am encountering the same problem.

I followed instructions from other users to delete the Steam runtime libs, and using LD_PRELOAD. None of these suggestions produced different results.
#### Steps for reproducing this issue:

I am using:
Ubuntu 16.04 on an Intel Nuc DC3217IYE. Intel drivers page notes that drivers are included in the Ubuntu repositories.

Graphics information:

```
lshw -c video
  *-display               
       description: VGA compatible controller
       product: 3rd Gen Core processor Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:26 memory:f7800000-f7bfffff memory:e0000000-efffffff ioport:f000(size=64)
```

**Comment by gdrewb-valve** [comment] 2016-07-03 02:22
Probably a duplicate of #4494.

**Comment by phantom-voltage** [comment] 2016-07-03 03:11
I probably should have done this earlier. I was looking through the .steam folder to see if I could find anything. Here's the [error.log](https://gist.github.com/phantom-voltage/0c81e9cdab7d19e27b138b74ed99df7a) file.

The most important bits are here:
```
...
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
rm: cannot remove '/home/mcp/.steam/bin': Is a directory
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
/usr/bin/ldd: line 119: printf: write error: Broken pipe
Opening joystick XInput Controller
Generating new string page texture 74: 128x256, total string texture memory is 442.37 KB
Generating new string page texture 75: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 76: 64x256, total string texture memory is 507.90 KB
Generating new string page texture 77: 32x256, total string texture memory is 540.67 KB
ExecCommandLine: "/home/mcp/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 84: 24x256, total string texture memory is 565.25 KB
CAPIJobRequestUserStats - Server response failed 2
Installing breakpad exception handler for appid(steam)/version(1465948400)
Fontconfig warning: "/home/mcp/.steam/bin/panorama/etc/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/mcp/.steam/bin/panorama/etc/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
assert_20160702195226_1.dmp[19523]: Uploading dump (out-of-process)
/tmp/dumps/assert_20160702195226_1.dmp
/home/mcp/.steam/steam.sh: line 753: 19360 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20160702195226_1.dmp[19523]: Finished uploading minidump (out-of-process): success = yes
assert_20160702195226_1.dmp[19523]: response: CrashID=bp-f0ce7f7c-cc4a-437e-b287-0e2bb2160702
assert_20160702195226_1.dmp[19523]: file ''/tmp/dumps/assert_20160702195226_1.dmp'', upload yes: ''CrashID=bp-f0ce7f7c-cc4a-437e-b287-0e2bb2160702''
```

**Comment by kisak-valve** [comment] 2019-06-07 13:59
Hello @phantom-voltage, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment] 2019-07-12 15:03
Closing pending feedback.

**Closed by kisak-valve** 2019-07-12 15:03 UTC
Labels: Big Picture, Distro Family: Ubuntu, Need Retest, reviewed
