### ISSUE TITLE
Steam won't launch after recent update, ending with Segmentation Fault

### ISSUE THREAD

**Issue by monoai** [ValveSoftware/steam-for-linux#8940] opened 2022-11-21 08:50 UTC
#### Your system information

* Steam client version (build number or date): 1668654564 
* Distribution (e.g. Ubuntu): Ubuntu 22.04.1
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Steam launched once before prompting for an update that was released around Nov 17, afterwards it wouldn't launch again.
Launching steam via `steam` or the app icon does not launch steam. Only tries to verify installation, seemingly succeeds, and stops immediately.

I've launched steam through the terminal to see its results, also tried to debug its backtracing as was detailed from [Arch's documentation on debugging steam](https://wiki.archlinux.org/title/Steam/Troubleshooting#Debugging_Steam), and opened up the coredump result to see if anything pops up. All the results from my findings can be found in the link below:
[Terminal Output, gdb result, coredump result](https://gist.github.com/monoai/86a96520afc96a014b86f68a81895b63)

#### Diagnostics done before doing this report:

1. Renamed files from `~/.steam` and `~/.local/share/Steam` in hopes of reinstalling will do something.
2. Uninstalled steam and installed the latest deb file from [Steam's repo.](https://repo.steampowered.com/steam/)
3. Reverted mesa drivers to the ones supplied by Ubuntu instead of using the one from the kisak-mesa repo.
4. Used Wayland instead of Xorg

#### Steps for reproducing this issue:

1. Launch steam through the terminal and/or app icon
2. Verifies installation
3. Segmentation Fault

**Comment by kisak-valve** [comment] 2022-11-21 13:43
Possible duplicate of #8926.

**Comment by monoai** [comment] 2022-11-21 14:32
I don't use Telegram messenger but I find it strange that the log for the other issue does seem pretty similar with mine, even ending the segfault on the same line.
I tried rebooting my PC and launching steam without hopefully any programs interfering but it doesn't seem to be changing anything.

**Comment by monoai** [comment] 2022-11-21 15:25
I would like to apologize for the double post and for this particular issue, but it seems like I've pinpointed the problem and have fixed my issue, it **does** seem related to the other issue where something audio-related was interfering albeit I was using a different program called `OpenRGB` where I had a plugin that listens to my audio output and converts it to my RGB lights (though this is unused for my case, I assume the program still loads my audio somewhat).

Exiting the program before launching Steam finally successfully launches Steam, while keeping the program open while opening Steam would lead to SegFault again. Keeping it open while Steam is already open seems to not affect Steam until it's closed, and playing games seems to be alright.

I would like to add though that I haven't had this issue of my program conflicting with Steam until the recent update, and might still push that the recent update might've caused this particular bug.

**Comment by aep** [comment] 2022-11-21 18:56
same issue. how did you find the conflicting program? There's literally nothing with audio in my xinitrc

**Comment by slonopotamus** [comment] 2022-11-22 15:46
Observing the same crash. I'm on Gentoo Linux.

**Comment by slonopotamus** [comment] 2022-11-22 20:09
Is there any workaround? Like, can I somehow temporarily downgrade Steam to an older version?

**Comment by monoai** [comment] 2022-11-23 04:35
As far as I'm aware, and looked, that isn't possible. Even if you probably downloaded an outdated launcher it would still download the latest build of steam. Your only best bet (assumingly you do have the same problem and using Pulseaudio and could use Pavucontrol or something similar) is probably to observe your recording streams and see if any open ones are interfering.

**Comment by S4NDW1CH** [comment] 2022-11-26 12:47
Had the same issue today. Comments here talked about OpenRGB which I also use. Tested it out and the issue went away after shutting down OpenRGB.

If OpenRGB is launched before Steam, then steam crashes on startup. Other way around and everything seems to work fine.

Also both native and built-in runtimes are crashing.

OpenRGB might not be the only cause of the issue, but for me it was.

Some details:
- Kernel 6.0.9-arch1-1
- OpenRGB ([specifically this fork](https://gitlab.com/thombo/OpenRGB)) together with these plugins:
  - [Effects](https://gitlab.com/OpenRGBDevelopers/OpenRGBEffectsPlugin) (seeing as audio is suspected issue, this plugin might be involved as it uses audio)
  - [VisualMap](https://gitlab.com/OpenRGBDevelopers/OpenRGBVisualMapPlugin)
  - [Hardware Sync](https://gitlab.com/OpenRGBDevelopers/OpenRGBHardwareSyncPlugin)

**Comment by FF-AntiK** [comment] 2022-11-26 14:30
> Some details:
> 
> * Kernel 6.0.9-arch1-1
> * Wayland 1.21.0-1
> * KDE Plasma 5.26.3
> * Pipewire 1:0.3.60-3 and pipewire-pulse 1:0.3.60-3, pipewire-alsa 1:0.3.60-3
> * OpenRGB ([specifically this fork](https://gitlab.com/thombo/OpenRGB)) together with these plugins:
>   
>   * [Effects](https://gitlab.com/OpenRGBDevelopers/OpenRGBEffectsPlugin) (seeing as audio is suspected issue, this plugin might be involved as it uses audio)
>   * [VisualMap](https://gitlab.com/OpenRGBDevelopers/OpenRGBVisualMapPlugin)
>   * [Hardware Sync](https://gitlab.com/OpenRGBDevelopers/OpenRGBHardwareSyncPlugin)

It's the nearly the same for me, but I have only the Effects plugin running on OpenRGB without the other ones.

**Comment by AndrewAmmerlaan** [comment] 2022-11-28 13:28
> my issue went away after completely removing /usr/lib32/alsa-lib/*

Please do not manually remove system libraries. When the package manager thinks a library is installed but it actually isn't you will encounter problems later on in software that depends on those libraries.

**Comment by Y0shioSato** [comment] 2022-12-04 19:31
openSUSE Tumbleweed. Have same problem even with Flatpak.

**Comment by TTimo** [comment] 2022-12-05 16:57
Please provide uploaded Crash IDs if you are encountering this. Pasting a gdb trace isn't very useful to us.

**Comment by AndrewAmmerlaan** [comment] 2022-12-05 17:09
> Please provide uploaded Crash IDs if you are encountering this. Pasting a gdb trace isn't very useful to us.

```
steam.sh[5504]: Running Steam on gentoo 1.0.0.74-r1 64-bit
steam.sh[5504]: STEAM_RUNTIME is disabled by the user
steam.sh[5504]: Can't find 'steam-runtime-check-requirements', continuing anyway
[2022-12-05 18:06:29] Startup - updater built Dec  1 2022 22:37:35
[2022-12-05 18:06:29] Startup - Steam Client launched with: '/home/andrew/.local/share/Steam/ubuntu12_32/steam'
[2022-12-05 18:06:29] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Installing breakpad exception handler for appid(steam)/version(1669935987)
[2022-12-05 18:06:29] Loading cached metrics from disk (/home/andrew/.local/share/Steam/package/steam_client_metrics.bin)
[2022-12-05 18:06:29] Using the following download hosts for Public, Realm steamglobal
[2022-12-05 18:06:29] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2022-12-05 18:06:29] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2022-12-05 18:06:29] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1669935987)
[2022-12-05 18:06:29] Verifying installation...
[2022-12-05 18:06:29] Verification complete
Loaded SDL version 2.27.0-p7692409
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xec01b5a0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xec019f00
ComputeStartupMode: found registry default startup mode: 0steamwebhelper.sh[5629]: Runtime for steamwebhelper:disabled by environment (this is unsupported)
steamwebhelper.sh[5629]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
Installing breakpad exception handler for appid(steam)/version(1669935987)
Installing breakpad exception handler for appid(steam)/version(1669935987)
Installing breakpad exception handler for appid(steam)/version(1669935987)
Installing breakpad exception handler for appid(steam)/version(1669935987)
Installing breakpad exception handler for appid(steam)/version(1669935987)
Installing breakpad exception handler for appid(steam)/version(1669935987)
Installing breakpad exception handler for appid(steam)/version(1669935987)
Installing breakpad exception handler for appid(steam)/version(1669935987)
Installing breakpad exception handler for appid(steam)/version(1669935987)
Installing breakpad exception handler for appid(steam)/version(1669935987)
Installing breakpad exception handler for appid(steam)/version(1669935987)
Installing breakpad exception handler for appid(steam)/version(1669935987)
Installing breakpad exception handler for appid(steam)/version(1669935987)
Installing breakpad exception handler for appid(steam)/version(1669935987)
Installing breakpad exception handler for appid(steam)/version(1669935987)
Installing breakpad exception handler for appid(steam)/version(1669935987)
Installing breakpad exception handler for appid(steam)/version(1669935987)
Installing breakpad exception handler for appid(steam)/version(1669935987)
src/vstdlib/strtools.cpp (252) : n == 0 || s1 != NULL
src/vstdlib/strtools.cpp (252) : n == 0 || s1 != NULL
Installing breakpad exception handler for appid(steam)/version(1669935987)
assert_20221205180630_23.dmp[5743]: Uploading dump (out-of-process)
/tmp/dumps/assert_20221205180630_23.dmp
/home/andrew/.local/share/Steam/steam.sh: line 798:  5586 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20221205180630_23.dmp[5743]: Finished uploading minidump (out-of-process): success = yes
assert_20221205180630_23.dmp[5743]: response: CrashID=bp-8f817662-f8d6-49fc-8c08-be8e82221205
assert_20221205180630_23.dmp[5743]: file ''/tmp/dumps/assert_20221205180630_23.dmp'', upload yes: ''CrashID=bp-8f817662-f8d6-49fc-8c08-be8e82221205''
```

CrashID of this one is `bp-8f817662-f8d6-49fc-8c08-be8e82221205`

Created dump file attached here: [assert_20221205180630_23.zip](https://github.com/ValveSoftware/steam-for-linux/files/10156329/assert_20221205180630_23.zip)

**Comment by TTimo** [comment] 2022-12-05 18:46
Thank you. Possible fix will ship in next beta update. This is the same issue as https://github.com/ValveSoftware/steam-for-linux/issues/8926

**Comment by AndrewAmmerlaan** [comment] 2022-12-09 15:49
> Thank you. Possible fix will ship in next beta update. This is the same issue as #8926

:partying_face: After updating it is fixed on my side, Thanks @TTimo

**Closed** 2022-12-09 21:47 UTC
Labels: Steam client, Audio, Need Retest, Distro Family: Ubuntu
