### ISSUE TITLE
Storage Manager not showing mounted drive

### ISSUE THREAD

**Issue by kepa4** [ValveSoftware/steam-for-linux#8090] opened 2021-09-21 00:28 UTC
#### Your system information

* Steam client version (build number or date): 1631912732
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I am trying to add an existing steam library that is located on a different Drive. The drive is mounted to a /media directory. But when I try to search for it in the "Create or select new Steam library folder:" window it does not show up.

![image](https://user-images.githubusercontent.com/30184742/134093251-13538dcd-9cad-48c5-a60d-174032dd373b.png)

storage properties:
![image](https://user-images.githubusercontent.com/30184742/134093472-a707b921-b1e1-4ae8-9990-a14f298628bd.png) 

#### Steps for reproducing this issue:

1. settings -> downloads
2. Click on Steam Library Folders
3. Click on the plus symbol

**Comment by TTimo** [comment] 2021-09-27 16:46
CNR - I have /opt (ext4) mounted on my local system and it shows up (Steam beta client). I checked the directory enumeration code and there's nothing suspicious. The path may be getting skipped due to permissions? Anyone else able to reproduce something similar?

**Comment by kalambet** [comment] 2021-09-28 09:28
So as it turns out this is the issue for `flatpack` version, I installed one from the the `multiverse` and was able to add `/media` mount just fine.

**Comment by kisak-valve** [comment] 2021-09-28 12:29
@kepa4, are you using the Steam package from Arch's software repository or the Flathub distributed Steam package? Software in Flatpak is not expected to have unlimited access to the host system.

**Comment by kepa4** [comment] 2021-10-01 01:22
It was indeed the version in Flathub, installed using pacman and it works

**Comment by kisak-valve** [comment] 2021-10-01 01:23
Closing as not a Steam issue. See also: https://github.com/flathub/com.valvesoftware.Steam/wiki#I_want_to_add_external_disk_for_Steam_libraries

**Closed by kisak-valve** 2021-10-01 01:23 UTC
Labels: Steam client, Need More Information
