### ISSUE TITLE
Steam tries to install already installed packages on Ubuntu 16.10

### ISSUE THREAD

**Issue by nazar-pc** [ValveSoftware/steam-for-linux#4572] opened 2016-07-29 03:47 UTC
#### Your system information
- Steam client version: 1468023329
- Distribution (e.g. Ubuntu): Ubuntu 16.10
- Opted into Steam client beta?: [Yes/No] Yes, No
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

I have similar issue to # 3702 on Ubuntu 16.10. Everything works, but shows terminal with:

> Steam needs to install these additional packages:
> curl, python-apt, xterm, xz-utils, zenity, libgl1-mesa-dri:i386, libgl1-mesa-glx:i386, libc6:i386
> [sudo] password for %user:

This annoying modal is actually opened in xterm, which it suggests to install. And yes, I have all those packages installed, so that apt-get results with 0 additional packages installed, it just causes those packages to be marked as installed manually, which is even more annoying.

I suggest to add check whether those packages are actually installed.
### With latest Steam beta update, this happens before Steam UI appears, and thus doesn't start at all, it loops over and over again.

Probably, related to #4568 as well
#### Steps for reproducing this issue:
1. Have Ubuntu 16.10 (likely, 16.04 might be the same)
2. Launch steam

**Comment by nazar-pc** [comment] 2016-08-09 19:18
Doesn't happen anymore with latest stable and beta versions.

**Comment by Spitfire1900** [comment] 2016-10-23 00:03
This is reoccurring on 16.10

Build: 10/13/2016 @ 00:49:25
Steam-launcher version: 1.0.0.53
OS: Ubuntu 16.10 x64

This is after following https://bugs.archlinux.org/task/48994 and running the command
`find ~/.local/share/Steam/ubuntu12_32/steam-runtime/ -name libgpg-error.so* -delete`
to resolve the error
`libGL: dlopen /usr/lib/xorg/modules/dri/radeonsi_dri.so failed (/usr/lib/libgcrypt.so.20: symbol gpgrt_lock_lock, version GPG_ERROR_1.0 `

Startup script:
`D_PRELOAD='/usr/$LIB/libstdc++.so.6' DISPLAY=:0 steam`

Script output:
```
Steam needs to install these additional packages: 
        curl, python-apt, xterm, xz-utils, zenity, libgl1-mesa-dri:i386, libgl1-mesa-glx:i386, libc6:i386
dpkg: symbol lookup error: dpkg: undefined symbol: setexecfilecon
[sudo] password for kyle: 
............
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.50.1-1ubuntu1).
python-apt is already the newest version (1.1.0~beta5).
xterm is already the newest version (324-2ubuntu1).
xz-utils is already the newest version (5.1.1alpha+20120614-2.1ubuntu1).
zenity is already the newest version (3.22.0-1).
libc6:i386 is already the newest version (2.24-3ubuntu1).
libgl1-mesa-dri:i386 is already the newest version (12.0.3-1ubuntu2).
libgl1-mesa-glx:i386 is already the newest version (12.0.3-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Press return to continue: 
\
```

**Comment by nazar-pc** [comment] 2016-10-23 00:06
For me it is trying to install packages silently (no terminal showing up anymore, probably, because of pam_usb or something else). I know this because packages it is trying to install are constantly marked as installed manually in package manager (this happens when you try to install explicitly already automatically installed package).

**Comment by Spitfire1900** [comment] 2016-10-23 00:14
Yes, the error I experience is after the Steam UI appears so closing the window allows normal operation.

**Comment by kisak-valve** [comment] 2019-07-05 20:09
Closing because Ubuntu 16.10 has been EOL'd for quite a while. If anyone can reproduce this issue with a distro release that has upstream support, please open a new issue report.

**Closed by kisak-valve** 2019-07-05 20:09 UTC
Labels: reviewed
