### ISSUE TITLE
[Arch Linux] Steam doesn't launch, no errors. 

### ISSUE THREAD

**Issue by gunnar** [ValveSoftware/steam-for-linux#3960] opened 2015-08-12 08:42 UTC
I have just installed again arch linux, and after installing the nvidia drivers (both 32 and 64 bit) and steam, I find that steam doesn't launch!

When I launch steam from a terminal, it simply opens up the license agreement, which I accept, and then... nothing. According to htop there was no steam process created at any point. The terminal only outputs one line: ***/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable. This for which I have found a fix involving editing steam.sh to something I can't remember, however it still changed nothing, except that line did not appear. 

[Here is a video showing what happens.](https://www.youtube.com/watch?v=knZtbZ_FZpQ)

I have tried running in xfce4 and moving the steam folder and letting steam redownload itself (which it does just fine), but the problem persists.

**Comment by gdrewb-valve** [comment] 2015-08-12 16:55
This sounds like a duplicate of #3954, do you believe you have a separate problem?

**Comment by bgiv** [comment] 2015-08-12 17:31
I believe so, that post describes steam as hanging, however mine never starts and returns me directly to the prompt. I have solved the unbound variable error by adding an entry for VERSION_ID in /etc/os-release, so now their is no text outputted at all. 

I tried running the steam binary in the ubuntu12_32 folder, and it ran the update however after trying to launch it immediately shutdown. Now whenever I try the binary again it gives me a steam popup with "Fatal Error: Failed to load steamui.so". I've also moved the installation folder and let it redownload, with no change.

https://gist.githubusercontent.com/bgiv/aa2ed1106359ff58d127/raw/d8806f8cead8fae67bf03cccb6846398831a7413/gistfile1.txt

**Comment by gdrewb-valve** [comment] 2015-08-12 17:34
We'll leave this open separately just in case.

**Comment by TheBatman** [comment] 2015-08-13 03:17
do you followed this? https://wiki.archlinux.org/index.php/Steam, are you using the native enviroment? i'm a noob in Arch btw :wink:

**Comment by d3rrial** [comment] 2015-11-07 15:01
Maybe try this:
LD_PRELOAD='/usr/lib32/libstdc++.so.6 /usr/lib32/libgcc_s.so.1 /usr/lib32/libxcb.so.1' LIBGL_DRIVERS_PATH=/usr/lib32/xorg/modules/dri steam

**Comment by Tele42** [comment] 2015-11-07 16:09
@d3rrial your workaround is specific to newer mesa, which should not apply to nvidia proprietary users.

**Comment by d3rrial** [comment] 2015-11-07 20:20
True. I should've mentioned that.

**Comment by kisak-valve** [comment] 2018-11-30 14:19
Hello @gunnar, are you still experiencing this issue on an up to date system?

**Comment by dearlygparted** [comment] 2018-12-17 06:36
@kisak-valve I'm not the OP but I am running Arch Linux and can confirm that Steam launches fine for me. Here are my [System specs](https://gist.github.com/d970f00749734326bc332cdebfb90085.git).

**Comment by gunnar** [comment] 2018-12-18 13:13
The issue seems to have been fixed quite a while ago (currently using `steam` in `multilib`. Apologies for not keeping up with the thread.

**Closed** 2018-12-18 13:14 UTC
Labels: Distro Family: Arch, Need Retest, reviewed

**Comment by NGStaph** [comment] 2022-07-11 12:20
I've noticed that the error happens due to nvidia driver updates after changing your default GPU (envycontrol/optimus). if primary gpu = NVIDIA, change the steam.desktop file to `PrefersNonDefaultGPU=false`
