### ISSUE TITLE
Shader pre-caching update: SEVERELY BROKEN on Linux and Mac

### ISSUE THREAD

**Issue by g572staem** [ValveSoftware/steam-for-linux#8292] opened 2021-12-11 07:33 UTC
CS:GO is broken for all Linux and Mac users with the very recent "Shader pre-caching update".  I don't think it is related to this project but this needs to be seen by someone who can contact the appropriate people at Valve.

Thanks.

https://steamcommunity.com/app/730/discussions/0/3196990234721043288/https://steamcommunity.com/app/730/discussions/0/3196990234721043288/

**Comment by g572staem** [comment] 2021-12-11 08:13
https://github.com/ValveSoftware/csgo-osx-linux/issues/2868

**Comment by g572staem** [comment] 2021-12-11 08:22
I should close this but I can't play so...

**Comment by kisak-valve** [comment] 2021-12-11 12:54
Closing as a duplicate of https://github.com/ValveSoftware/csgo-osx-linux/issues/2871.

**Closed by kisak-valve** 2021-12-11 12:54 UTC

**Comment by FinnVincible** [comment] 2021-12-13 17:39
my thing is glitched still how do we fix where is all previous comments
