### ISSUE TITLE
Steam client home page shows new Windows-only releases

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4448] opened 2016-05-11 15:01 UTC
Since today the home page of the Steam Linux client is showing me Windows-only games in the "new releases" area.

**Comment by Tele42** [comment] 2016-05-11 16:14
Duplicate of #4038.

**Comment by stqn1** [comment] 2016-05-11 16:49
I don’t think it’s a duplicate since it’s new as of today and not about the featured slider. But whatever.

**Comment by stqn1** [comment] 2016-05-11 17:34
It also shows me videos even though I have unchecked "videos" in the customization menu.

**Comment by stqn1** [comment] 2016-05-26 18:13
The filter seems to be working correctly again now.

**Comment by Swiftpaw** [comment] 2016-07-09 15:49
This is now happening for me in the tabbed section at the bottom.  All tabs include games that aren't on Linux yet, and the "Popular New Releases" and "All New Releases" buttons both take me to a search page with Linux unchecked, and both Mac and Windows checked, the exact opposite of what it should be.

**Comment by adolson** [comment] 2016-07-12 17:50
Yep, same exact behavior here. Linux is purposely unselected, while Mac and Windows are selected.

Is a secret message being communicated to us? Did meraco get hired at Valve??

**Comment by xpris** [comment] 2016-07-15 14:52
I have also this issue on both pc - laptop with Ubuntu 16.04 and desktop with Linux Mageia 5.
I see in Steam client on Linux only Windows (maybe also mac) games in store and If i trying listing game, I see two selected checkbox - listing windows, mac osx games but Linux+SteamOS is not selected.

Also the same issues is in steam store when I browse it in web browser from Linux. I try Firefox, Chromium, Chrome, Opera developer and Vivaldi snapshot - always shows only Windows content, but not Linux why?

**Comment by rkfg** [comment] 2016-10-25 15:55
This is solved for me, I read somewhere about the store preferences, you can find it in your account details (not the community page settings but in account's ones). [Here](https://store.steampowered.com/account/preferences/) you can check your OS and uncheck the others. For whatever reason the change isn't applied immediately, I had to wait for **weeks** but eventually it worked. Only the "Upcoming" tab isn't filtered for me, all the other tabs are good. I have no idea why I have to change this by hand when it's pretty trivial to detect the user's OS just by user agent if all other fails.

However, my actions may have nothing to do with it as it could have been fixed on the Valve's side.

**Comment by Swiftpaw** [comment] 2016-10-25 20:33
I found SteamOS + Linux already set for me in that web interface preferences section, and indeed this problem seems to have resolved itself for me a few weeks ago.

https://www.reddit.com/r/linux_gaming/comments/56bvhk/

I've made a new post so other Reddit gamers can try out this setting tweak to see if it helps them.

https://www.reddit.com/r/linux_gaming/comments/59dd2i/

**Comment by kisak-valve** [comment] 2019-10-04 17:25
Hello, is anyone still experiencing this issue on an up to date system? Please check your platform preferences set in Steam -> Settings -> View Account Details -> Preferences and scroll down to the platform preferences.

**Closed** 2021-06-04 17:43 UTC
Labels: Need Retest, Web, reviewed
