### ISSUE TITLE
SteamOS / Linux Game Filter Does Not Work When Steam Play Is Enabled For All Games

### ISSUE THREAD

**Issue by mdeguzis** [ValveSoftware/steam-for-linux#6127] opened 2019-03-07 03:06 UTC
#### Your system information

* Steam client version (build number or date): 1551915103, Mar 6 2019
* Distribution (e.g. Ubuntu):  SteamOS
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
SteamOS / Linux Game Filter Does Not Work When Steam Play Is Enabled For All Games. The filter option in your Library will not filter out Windows games as it seems to only rely on if they are installable or not. This makes identifying SteamOS/Linux vs Windows-only games from a library perspective difficult (unless someday icon/badging is introduced to make this distinction on the Steam grid icon like the controller icon for "ready").

A workaround is to leave  "Enable Steam Play for all other titles" off in the Steam Play options globally under settings, and enable Steam Play within the game title itself. However, this negates any central management of the feature. 

#### Steps for reproducing this issue:

1. Turn on "Enable Steam Play for all other titles"
2. Try to filter only by SteamOS / Linux in your library to observe failure.
3. Turn off "Enabled Steam Play for all other titlles"
4. Observe SteamOS / Linux filter is again working.

**Comment by dearlygparted** [comment] 2019-03-07 06:53
Duplicate of [#5679](https://github.com/ValveSoftware/steam-for-linux/issues/5679)

**Comment by kisak-valve** [comment] 2019-03-07 13:31
Hello @mdeguzis, as noted by @dearlygparted this issue is already being tracked at #5679. Closing as a duplicate.

**Closed by kisak-valve** 2019-03-07 13:31 UTC
