### ISSUE TITLE
Interacting with Friends List window and "rich features" makes opened windows blank.

### ISSUE THREAD

**Issue by sizeofbool** [ValveSoftware/steam-for-linux#6314] opened 2019-06-13 10:46 UTC
#### Your system information

* Steam client version (build number or date): ![steam2](https://user-images.githubusercontent.com/6904856/59426936-e24fe680-8df2-11e9-9165-df9ecd755f4b.png)
* Distribution (e.g. Ubuntu): Debian 9 'stretch' x86_64
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Interacting with Friends List window and "rich features" makes any opened chat windows, configuration windows and Friends List window itself blank. (see attached screenshot)
Same windows inside In-Game Overlay and web client window are also affected by this issue.

Even if those windows became blank they still could be interacted with, eg. closed or minimized if you blindly click at the place where close button ( "X" ) is located.

If I close all blanked windows and open Friends List again, it will be restored to a normal state, without need to restart Steam client itself.

![steam1_m](https://user-images.githubusercontent.com/6904856/59425956-69e82600-8df0-11e9-8807-64df0a43aef2.png)

[My System Specs](https://gist.github.com/sizeofbool/e5ac9fa9c115b43760b0b75d5fd6abed)

#### Steps for reproducing this issue:

1. Start Steam Client and open Friends List.
2. RMB-click on any friend and simply move mouse cursor over opened menus.
3. If that didn't triggered the issue, repeat the same procedure with another friend from the list.
4. While doing this you can also occasionally click on menu options like "View Game info", "Manage > Categorize", "Manage > Notifications", etc, to simulate casual user interactions.
5. Even if this issue happen sporadically, I can reliably reproduce it within a few minutes, simply using described actions.

**Comment by Newbie13XD** [comment] 2019-07-28 19:32
I can confirm this also occurs on my system. 

Fedora 30, nvidia 430.26, Linux 5.1.18, Steam beta.

**Comment by Newbie13XD** [comment] 2019-09-15 16:45
In my case, it seems that disabling hardware acceleration in Steam's settings has mitigated this issue. It's a bit difficult to verify as the issue occurs rather randomly, but I haven't had it occur since disabling hardware acceleration a few days ago.

**Comment by kisak-valve** [comment] 2021-11-05 17:18
Hello @sizeofbool, @Newbytee, are either of you still experiencing this issue on an up to date system?

**Comment by Newbytee** [comment] 2021-11-05 17:42
I haven't used hardware acceleration in Steam since writing those messages (which was necessary to reproduce it), but I can try enabling it again and see if it reproduces.

**Comment by sizeofbool** [comment] 2021-11-05 18:42
@kisak-valve this issue is fixed for me. Doesn't require any workarounds, like disabling hardware acceleration, etc.
My current system was updated to current stable GNU/Debian 11 'bullseye'. Hardware-wise it is the same system.

**Comment by Newbytee** [comment] 2021-11-10 13:12
I can't reproduce this any more either.

**Comment by kisak-valve** [comment] 2021-11-10 13:17
Thanks for retesting, closing.

**Closed by kisak-valve** 2021-11-10 13:17 UTC
Labels: NVIDIA drivers, Need Retest, Distro Family: Debian, Web Component
