### ISSUE TITLE
Steam Cannot Start on Ubuntu 18.04, Nvidia Driver 418

### ISSUE THREAD

**Issue by LyqSpace** [ValveSoftware/steam-for-linux#6116] opened 2019-03-01 05:46 UTC
#### Your system information

* Steam client version (build number or date): 
    Latest download from website.
* Distribution (e.g. Ubuntu): 
    Ubuntu 18.04 64bit
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Nvidia-Information:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 00000000:03:00.0  On |                  N/A |
| 23%   54C    P0    64W / 250W |    499MiB / 11170MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+

yq@Tiger01:~$ ldconfig -p | grep libGL.so
	libGL.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGL.so.1
	libGL.so.1 (libc6) => /usr/lib/i386-linux-gnu/libGL.so.1
	libGL.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGL.so
	libGL.so (libc6) => /usr/lib/i386-linux-gnu/libGL.so

Follow someone in the steam, I have installed so many packages: 
sudo apt-get install libegl1-mesa:i386  libgl1-mesa-dri:i386 libgl1-mesa-glx:i386  libglapi-mesa:i386 libglib2.0-0:i386 libglu1-mesa:i386 libwayland-egl1-mesa:i386 libxcb-glx0:i386 libpangoxft-1.0-0:i386 libgtk2.0-0:i386 libidn11:i386 libglu1-mesa:i386 libxmu6:i386

glxinfo, glxgears are normal.

I've tried mv libGL.so.1 to libGL.so.1.backup

But it raises another problem:

You are missing the following 32-bit libraries, and Steam may not run: libGL.so.1

This system can run in Nvidia Driver 410, but when I upgrade my cuda from 10.0 to 10.1. The steam fails.

#### Steps for reproducing this issue:

1. Type steam in terminal:

Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1550534751)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

Thank you for your help!

**Comment by kisak-valve** [comment] 2019-03-01 13:32
Hello @LyqSpace, mesa's libGL.so.1 is not compatible with nVidia's proprietary driver. This driver issue is a continuation of #5778 and needs to be fixed by nVidia.

You may have better luck with the .run installer instead of the .deb.

Closing in favor of the existing issue report.

**Closed by kisak-valve** 2019-03-01 13:32 UTC

**Comment by LyqSpace** [comment] 2019-03-01 15:23
> Hello @LyqSpace, mesa's libGL.so.1 is not compatible with nVidia's proprietary driver. This driver issue is a continuation of #5778 and needs to be fixed by nVidia.
> 
> You may have better luck with the .run installer instead of the .deb.
> 
> Closing in favor of the existing issue report.

Thank you for your reply.  I guess you are right.
Where can I download the steam.run file? The official website only provide .deb file.
Thank you!

**Comment by kisak-valve** [comment] 2019-03-01 15:27
https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804

**Comment by LyqSpace** [comment] 2019-03-01 18:37
> https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804

Thank you so much. I understand that only Cuda10 .run file  contains the 32bit runtime libraries. I am using Cuda10.1 deb currently. As Nvidia official report says, they will no longer support 32bit libraries in Cuda10. Maybe it's time for Steam to upgrade their program in 64bit environment. 
Thanks again for your help.

**Comment by iHad169** [comment] 2019-03-07 04:28
me too

**Comment by MartinX3** [comment] 2019-03-19 10:42
@kisak-valve 
Nvidia dropped the deprecated x86 binaries and only provides now x64 binaries.
That's not a bug, that's a normal progress in the IT world.

The bug is von valve's site not providing an x64 steam version.
x64 CPU's exist since April 2003 with the AMD Opteron as the worlds first x64 CPU.
x64 exists since Windows XP x64 edition (Kind of windows server 2003).
Linux supports x64 since Kernel 2.4 in 2001.
MacOS supports x64 since 10.4.11(2007).

Now the hardware driver vendors start deprecating their x86 drivers.
That's completely fine, since MacOS is x64 by default, Windows is shipped with x64 by default on devices with more than 4GB RAM and Linux suggested running the x64 version (while some distributions already dropped x86 support.)

The x86 steam binary should be seen as a backward compatibility to old systems, not as the primary steam application distribution.

Just my opinion as a IT DevOps working since years in the business.

**Comment by nastys** [comment] 2019-04-02 15:13
@MartinX3 The 32-bit library has not been deprecated, it's just not installed. Should they get rid of it, all 32-bit games wouldn't be playable anymore.

Just install libnvidia-gl-418:i386 and everything will work again.

**Comment by MartinX3** [comment] 2019-04-02 15:22
@nastys 
nvidia's x86 (32-bit) deprecation plans
https://www.ghacks.net/2017/12/22/nvidia-ends-support-for-32-bit-operating-system-drivers/

**Comment by nastys** [comment] 2019-04-02 15:24
@MartinX3 It says NVIDIA won't release new drivers for 32-bit operating systems. It doesn't say anything about 32-bit libraries on 64-bit OSes.

**Comment by MartinX3** [comment] 2019-04-02 15:26
@nastys 
that's just the beginning.

**Comment by kisak-valve** [comment] 2019-04-02 15:32
Hello @MartinX3, nVidia dropped 32 bit kernel support, not 32 bit userspace support.

"Support for 32-bit x86 kernels
The Linux-x86 and FreeBSD-x86 release packages, as well as support for 32-bit kernels in the Solaris package, are no longer provided starting with release 396.

Support for 32-bit applications running on x86_64 kernels will continue."
(from https://devtalk.nvidia.com/default/topic/1032650/linux/unix-graphics-feature-deprecation-schedule/)

There is no indication this is going to change in the near future.

**Comment by MartinX3** [comment] 2019-04-02 15:41
Hello @kisak-valve 

thank you for the link to the official nvidia website.
Then it's only matter of time until they start to drop the userspace support, too.
Maybe in a few years.

How is the roadmap for the x64 steam application support?

**Comment by nastys** [comment] 2019-04-02 17:01
@MartinX3 That's not going to happen anytime soon. They just got rid of the 32-bit kernel code because nobody uses 32-bit operating systems anymore (on new computers anyway). If they removed the userspace libraries as well, A LOT of software (including games) wouldn't be able to run and too many people would complain and switch to AMD or even Intel graphics. There are just too many games, including fairly recent ones, that won't ever get ported to x86_64.
