### ISSUE TITLE
Can't type some special characters in Steam Overlay

### ISSUE THREAD

**Issue by gr0ebi** [ValveSoftware/steam-for-linux#4267] opened 2016-01-17 17:33 UTC
I'm on Debian 8 x64, using XFCE with German Keyboard and got Steam working yesterday.
Today I noticed, when playing Dota 2 and opening the Steam Overlay, I can't write some special characters (like Shift+3 for '§') and also some language specific mutations like "ä,ö,ü".
My `/etc/default/locale` looks like this:

```
LANG="de_AT.UTF-8"
LANGUAGE="de_AT:de"
```

If I chat over Steam without the Steam overlay, I can write all of this characters.
Edit:
Shift+2 for "
Shift+4 for $
Shift+5 for %
are all working btw

**Comment by steffenWi** [comment] 2016-11-09 19:17
This is still an issue. For me it's äöüß and @ that aren't working.

**Comment by kisak-valve** [comment] 2017-04-18 17:59
Closing as a duplicate of #2122.

**Closed by kisak-valve** 2017-04-18 17:59 UTC
Labels: reviewed

**Comment by kattmat3** [comment] 2021-12-09 01:23
Still an issue latest version of Steam while playing ARK on Fedora WS 35.

**Comment by retlok** [comment] 2022-08-23 21:52
Still a problem in latest version of steam while playing any game on Windows 11 with an Azerty keyboard.
