### ISSUE TITLE
Steam Controller Keyboard Gets Stuck Consistently

### ISSUE THREAD

**Issue by noammor** [ValveSoftware/steam-for-linux#4922] opened 2017-04-04 19:45 UTC
#### Your system information

* Steam client version (build number or date): March 30, 2017
* Distribution (e.g. Ubuntu): Ubuntu 16.10
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam Controller Keyboard gets stuck consistently at the second character input. 

In general, it works very strangely. Example: I open gedit, I alt-tab to the keyboard screen. I input the characters "a" and then "b". The keyboard application gets stuck; it completely stops responding to the Steam Controller buttons. The input is not yet sent to gedit (not even the "a") but I assume this is intended. I minimize the keyboard, and gedit now has "ab". 

I do the same thing, entering the letters "o" followed by "k". It gets stuck, I minimize it. Now gedit has the string "ko". I tested several times and it's always "ko" as far as I can see. 

When gedit is in focus and the keyboard window is next to it, I can successfully enter several characters and gedit gets them as they are typed.

This was tested on beta and on non-beta.

#### Steps for reproducing this issue:

1. Start Steam
2. Start some program that takes input, e.g gedit
3. Press joystick to start the keyboard
4. Enter two characters. Observe stuck keyboard.
5. Advanced: enter two characters. Check whether they're in the correct order.

**Comment by noammor** [comment] 2017-04-20 07:33
Also tested on Ubuntu 17.04 and on my laptop. Problem persists. Ordering of the two characters input before the keyboard application gets stuck seems completely random. Naturally this prevents me from using desktop mode for anything that requires typing of any sort.

**Comment by noammor** [comment] 2017-05-09 15:56
As of May 8, 2017, the controller window gets stuck in a different manner. Now it happens after the first input character.

**Comment by noammor** [comment] 2017-06-08 18:13
If anyone is listening, June 8 build, Keyboard window still unusable in desktop mode on Ubuntu 17.04.

**Comment by Corben78** [comment] 2017-07-16 07:51
I'm experiencing a similar problem.
Looks like the onscreen keyboard window kinda loses focus.
When using the onscreen keyboard in desktop mode, I can click somewhere else with the mouse and then back into the onscreen keyboard window and the controller is responsive again and I can hover over letters with the touchpads. As soon as I try to enter any character it's stuck again.
This does not happen on Windows.

**Comment by noammor** [comment] 2017-10-12 09:15
Bug still present. 

Controlling the desktop using a Steam Controller works perfectly, the only exception being the on-screen keyboard, which is unusable.

**Comment by noammor** [comment] 2017-10-29 14:23
Issue still present on Ubuntu 17.10.

**Comment by whitemarvin** [comment] 2017-11-12 18:11
I think this is a duplicate of #4353

**Comment by noammor** [comment] 2017-11-14 19:50
It seems to be! Thanks for the heads up, I installed devilspie as suggested in the Steam Community thread and it worked well.

**Comment by kisak-valve** [comment] 2017-11-14 20:01
Let's track this issue with the older issue report. Closing as a duplicate of #4353.

**Closed by kisak-valve** 2017-11-14 20:01 UTC
Labels: Distro Family: Ubuntu, Steam controller
