### ISSUE TITLE
Dota 2 always update after switching OS

### ISSUE THREAD

**Issue by yeknava** [ValveSoftware/steam-for-linux#5880] opened 2018-11-06 15:48 UTC
#### system information
* Steam client version: latest
* Distribution (e.g. Ubuntu): ubuntu/windows
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:
Dota 2 redownload files each time i change my OS.
it happend to other people also as someone asked it [here](https://gaming.stackexchange.com/questions/330802/why-my-dota-2-always-update-after-switch-the-os)
Needs to tell Dota 2 is stored on a NTFS partition and both steam clients redirect to same Steam Library folder to avoid downloading games multiple times.
Also keep in mind it wasn't a case before. I was playing before without any issue.
#### Steps for reproducing this issue:
1. Download Latest dota 2 update in windows or linux. then everything is fine
2. Switch OS to play on windows (if i were on linux or vice versa)
3. Dota 2 needs to (re)download about 800 mb each time.
4. Going to step 1 again.

**Comment by kisak-valve** [comment] 2018-11-06 16:13
Hello @yeknava, sharing a steam library between multiple OSes is unsupported and can give undefined behavior. Closing as a duplicate of #546 / #700 / https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation

**Closed by kisak-valve** 2018-11-06 16:13 UTC
