### ISSUE TITLE
Your steam package is out of date.  It's not though.

### ISSUE THREAD

**Issue by BryanQuigley** [ValveSoftware/steam-for-linux#4321] opened 2016-02-16 18:52 UTC
Your steam package is out of date. Please get an updated version from your package provider or directly from http://repo.steampowered.com/steam for supported distributions.
Press enter to continue: 

dpkg -l | grep steam
ii  steam-launcher                                     1.0.0.51

I'm on Ubuntu 16.04 (dev) with latest updates and the nvidia 361.xx series driver.

**Comment by bp0** [comment] 2016-02-19 05:46
Also with Ubuntu 16.04 and nvidia-358, steam-launcher 1.0.0.51. 
When Steam is launched an xterm is opened with that message about the package being out of date. If you quit Steam before closing the xterm window, Steam will restart after the xterm window is closed.

**Comment by hackedbellini** [comment] 2016-02-19 13:17
I'm experiencing the same on Debian Testing.

```
apt-cache policy steam-launcher                      hackedbellini@slayer
steam-launcher:
  Installed: 1.0.0.51
  Candidate: 1.0.0.51
  Version table:
 *** 1.0.0.51 500
        500 http://repo.steampowered.com/steam precise/steam amd64 Packages
        500 http://repo.steampowered.com/steam precise/steam i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by NaughtySquid** [comment] 2016-02-19 15:56
Yeah, same on Ubuntu 16.04 thought I was going mad :P

**Comment by cephyr** [comment] 2016-02-25 01:11
Hey guys,

same message for me on Ubuntu 16.04 but on stable Ubuntu the message went away after update

**Comment by leinardi** [comment] 2016-02-27 11:13
Same here. Ubuntu 16.04 and nvidia-358, steam-launcher 1.0.0.51.

**Comment by luisalvarado** [comment] 2016-03-01 17:27
Same here. Ubuntu 16.04. Nvidia 358.16. steam-launcher 1.0.0.51

**Comment by glesima** [comment] 2016-03-02 00:49
Same here.

steam-launcher 1.0.0.51 
Ubuntu 16.04
Kernel: 4.4.0-8-generic
Nvidia 361.28

**Comment by soee** [comment] 2016-03-11 17:06
Confirmed on Kubuntu 16.04
Plasma 5.5.5
Frameworks 5.18
QT 5.5.1
Kernel 4.4.0-11
64bit

**Comment by der-eismann** [comment] 2016-03-11 17:38
So I guess it is somehow related to the "new-ness" of Ubuntu 16.04. I have the same problem with Xubuntu 16.04 and kernel 4.4.0-11. 

Could a developer look into this?

**Comment by dietrmat** [comment] 2016-03-15 19:45
Also affected on 16.04: http://paste.ubuntu.com/15394943/

**Comment by drohm** [comment] 2016-03-27 18:02
Seeing same issue - Xubuntu 16.04 Final Beta.

**Comment by rkarolak** [comment] 2016-03-29 18:29
Likewise on my machine, which I recently installed the latest build of 16.04. I'm assuming that it's due to the new release of Ubuntu. Being that it's not officially released / stable maybe Steam doesn't recognize the distribution which prompts this error? It seems to work find otherwise.

$ uname -a
Linux link-lxub1604 4.4.0-15-generic #31-Ubuntu SMP Fri Mar 18 19:08:31 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -r
Release:	16.04

**Comment by Erazor84** [comment] 2016-03-31 04:53
Same error, even after the Steam Package Update last night.

Ubuntu Mate 16.04 Beta 2
Lastest Nvidia 361.42 Driver

**Comment by elbuglione** [comment] 2016-04-01 21:25
Same here.
Ubuntu 16.04 Beta2
Nvidia 361.42

**Comment by drohm** [comment] 2016-04-01 21:49
Following the instructions in #747 I was able to get the dialog to stop saying it was out of date.

**Comment by admshao** [comment] 2016-04-08 01:31
Just upgrade to 16.04. Same for me with nvidia-364

**Comment by swetoast** [comment] 2016-04-12 07:49
Same here
xubuntu 16.04 (amd64)
Intel Graphics Drivers

**Comment by erichoglander** [comment] 2016-04-12 10:17
Confirming
Kubuntu 16.04
Nvidia 361.42

**Comment by helicida** [comment] 2016-04-13 10:46
Same here, Ubuntu 16.04 Beta 2 - GTX 950 with nvidia 361.42 drivers.

**Comment by Recydywa** [comment] 2016-04-14 18:53
I'm also affected by this issue and at least two other people reported it on Ubuntu Forums.

http://ubuntuforums.org/showthread.php?t=2313587

**Comment by rgiyf** [comment] 2016-04-21 14:27
Ubuntu 16.04 64-bit Final release still same issue

**Comment by rhsolive** [comment] 2016-04-21 18:07
Same here with 16.04 final.

**Comment by cyberwitch** [comment] 2016-04-22 01:30
I installed the latest steam from steam's repo (1.0.0.52).  However, Ubuntu thinks that it's repo has a newer version (1:1.0.0.48-1ubuntu3) and keeps trying to get me to "upgrade."  Steam itself is still showing the popup, too.

**Comment by Tschrock** [comment] 2016-04-22 03:12
I was able to 'fix' this by uninstalling steam and removing the steampowered.com repo and then reinstalling from ubuntu's multiverse repo (deb http://us.archive.ubuntu.com/ubuntu/ xenial multiverse)

**Comment by cyberwitch** [comment] 2016-04-22 07:04
Thanks a bunch!  That worked for me.

**Comment by dnlbaines** [comment] 2016-04-22 11:42
Just upgraded, seems like this is going to be an issue for anyone who upgrades to 16.04. Hope there will be an easy fix that doesn't involve reinstalling Steam.

**Comment by ridowan007** [comment] 2016-04-22 12:03
Kubuntu 16.04, updated from 14.04, seeing this problem. Each time at startup, steam warns about 
"Your steam package is out of date. Please get an updated version from your package provider or directly from http://repo.steampowered.com/steam for supported distributions."

Already removed and reinstalled from main steam site.

**Comment by cyberwitch** [comment] 2016-04-22 16:35
@ridowan007 Like @Tschrock suggested, the fix seems to be to uninstall Steam's steam and steam-launcher, remove Steam's repo, and finally install just steam from Ubuntu's multiverse repository.  For whatever reason, the version in Steam's repo is actually borked on 16.04, but Ubuntu's official package works.

**Comment by ghephardo** [comment] 2016-04-22 21:31
I just updated from 14.04 to 16.04 and there are no steam packages in my multiverse repo. Anyone have a clue about this?!

**Comment by cyberwitch** [comment] 2016-04-22 21:33
I couldn't see the steam package in synaptic for some reason, but if I ran
"sudo apt-get install steam" it would install steam.

**Comment by BryanQuigley** [comment] 2016-04-22 21:34
It's a steam:i386 package, so if you do
apt install steam it will install.   If you look in Software or Synaptic it won't show up :/

This is (AFAICT) an older version of the steam-launcher in multiverse.  Somewhat funny, but it did work for me, although have to redownload games...

**Comment by cyberwitch** [comment] 2016-04-22 21:36
Yes, you might want to backup save files from ~/.steam since not all games
save to the cloud.

**Comment by rgiyf** [comment] 2016-04-22 21:41
You could just move your games from ~/.local/share/Steam/steamapps to ~/.steam/steamapps

**Comment by cyberwitch** [comment] 2016-04-22 21:52
Oh, and you can move any local folders at ~/.local/share/Steam/userdata/*/*/local to ~/.steam/userdata/*/*/local to restore your local saves!  Guess they weren't lost either ^^

**Comment by inadril** [comment] 2016-04-23 11:59
I had the same issue, and solved as follows:
1. Got to Ubuntu Software and find steam.
2. Uninstall it.
3. Install it again from the same location.
4. Run steam to update (not there may be no steam in the application list, so just type in terminal "steam")
5. Copy games and configuration of Your profile:
5a. games:
~/.local/share/Steam/steamapps to ~/.steam/steamapps
5b. profile settings:
~/.local/share/Steam/userdata to ~/.steam/userdata

**Comment by terzag** [comment] 2016-04-23 16:52
Given that Steam updates itself and shouldn't care about the original installation version/method, it's a bit weird that this shows up. I wonder what it checks to decide that it's out of date. Is the term window with the message displayed by the Steam client itself or from outside (e.g. a shell script that launches the client, checks some version number and displays the term window)?

**Comment by pgn674** [comment] 2016-04-24 05:39
I traced through to where the message is coming from.

In `~/.steam/root/steam.sh`, find `MINIMUM_VERSION`
In `/usr/bin/steam`, find `STEAMSCRIPT_VERSION`
`MINIMUM_VERSION` must be less than `STEAMSCRIPT_VERSION` (uses Bash's "`if [[ A -lt B ]]`" )
If it is not, then the message in steam.sh is displayed in that xterm window:
`Warning: Your steam package is out of date. Please get an updated version from your package provider or directly from http://repo.steampowered.com/steam for supported distributions.`

Strangely, for me, MINIMUM_VERSION is 100020, and STEAMSCRIPT_VERSION is 100052. And in my testing, the versions are compared successfully. I've tried altering steam.sh, but it gets repaired every time Steam is run. I don't know how the version comparison is failing when I run Steam.

**Comment by lahtis** [comment] 2016-04-24 10:49
Same here.
Ubuntu 16.04 LTS (64 bit)
kernel 4.4.0-21-generic
steam-runtime-release_2016-02-23
nvidia  361.42
steam-launcher 1.0.0.51

**Comment by cyberwitch** [comment] 2016-04-24 17:32
See Tyler Schrock's comment previously in this thread.  You should not have
steam-launcher installed *at all*, you should remove the steam repository,
and make sure the version of steam you have installed is steam:i386 from
Ububntu's multiverse repository.

**Comment by peterLaurence** [comment] 2016-04-24 18:49
I can confirm that doing what @cyberwitch explained in the previous post worked for me.

**Comment by lahtis** [comment] 2016-04-24 20:43
this help 
sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ xenial multiverse"
sudo apt-get update && sudo apt-get install steam

**Comment by NosajDraw** [comment] 2016-04-29 10:04
I need a lot of convincing before I mess with my steam install... I'd rather this was just fixed.

as for "I was able to 'fix' this by uninstalling steam and removing the steampowered.com repo and then reinstalling from ubuntu's multiverse repo (deb http://us.archive.ubuntu.com/ubuntu/ xenial multiverse)" I'm not even sure what that means.

**Comment by terzag** [comment] 2016-04-29 10:27
Linux distributions usually install software through repositories ("repos"), i.e. places where packages are stored and installed/updated on demand. Each distribution has its own repositories organization; on Ubuntu, the principal repos are named main, universe, multiverse and restricted, depending on the type of packages you find in them (e.g. free vs proprietary software, or software managed by Canonical vs by the community).

When you install Steam through the deb package downloaded on its official website, it adds a repo from Valve to your system, so it can update the package easily if needed. But Steam is also available on Ubuntu through the multiverse repo, withouth having to install it from the official deb package. There's a small issue, though: both version seem to install Steam files in different places; the one from Valve's deb uses ~/.local/share/Steam while the one from the Ubuntu repo uses ~/.steam.

So, if you installed Steam from Valve's deb, you have the issue mentioned in this bug report (window with version mismatch error message); if you installed it from the Ubuntu's repo, you dont. Thus, the solution is simple:
1) remove the Steam package that was installed by the deb (it's called "steam-launcher"); you can do it from the terminal with **sudo apt-get remove steam-launcher**

2) remove the Steam repository that was added by the deb; you can do it through the "Software & Updates" (not sure of the proper english name, my system is in french) option in the system prefs. There, you'll have a first tab that lists the Ubuntu repos, multiverse should be checked. Then, you'll have a tab for other software: find the two lines that begin with "http://repo.steampowered.com" and uncheck/delete them. When you close Software and Updates after this, it'll ask you if you want to reload the sources; do it.

3) now that Valve's repo and Steam have been removed, you can reinstall it from the Ubuntu multiverse repo. In a terminal: **sudo apt-get install steam**

4) I said above that the two versions of Steam don't use the same places for the files, so don't launch Steam now or it won't find you installed games because it doesn't search for them in the right place. Instead, open a Nautilus (file manager) window and show hidden files (ctrl + H), you'll see (among others) two folders that begin with a dot: ".steam" and ".local". Go into ".local", then "share", then "Steam". You'll see two folders of interest: "steamapps" (your games) and "userdata" (your personal data, like games config files or screenshots and such). Move these two folders into the ".steam" one you saw previously in your home folder.

5) launch Steam and you should have your installed games as before and you should get rid of the annoying terminal windows that appeared previously.

**Comment by lahtis** [comment] 2016-04-29 13:20
Why steam has its own repository or why steam pages has a steam.deb package? If it does not work. Why then the site is not updated.

**Comment by RPiAwesomeness** [comment] 2016-05-03 17:39
Confirmed on Ubuntu 16.04

i7-2760QM, Intel HD3000/Quadro 1000M

Seems to be resolved by @terzag's solution

**Comment by Angsereg** [comment] 2016-05-04 00:12
$HOME/.steam/steam/steam.sh or $HOME/.local/share/Steam/steam.sh is getting run twice. The first time around, check_scriptversion() and detect_scriptversion() return the correct Steam version, 100052, and STEAMSCRIPT_OUTOFDATE gets set to 0. However, steam.sh gets run a second time, and this time, for whatever reason, detect_scriptversion() returns a 0, which is obviously less than the 100020 that it's checking against.

In steam.sh, line 576 reads:
`if [ "$INITIAL_LAUNCH" ]; then`

Just before that, INITIAL_LAUNCH is set to either true or false (the strings, not the values).

Unless $INITIAL_LAUNCH is empty, the `[ "$INITIAL_LAUNCH" ]` will always return true. `[ "" ]` will always return false. I'd suggest the if statement on line 576 be changed to `if $INITIAL_LAUNCH; then`, so it will actually run the `true` and `false` commands in the path, get their respective returns, and skip that buggy second version evaluation.

I'd test this directly in the steam.sh, myself, but whenever I make any changes there, it fails the hash check, and is replaced.

**Comment by elbuglione** [comment] 2016-05-04 14:25
@Angsereg 
Nice work, man!

@johndrinkwater @johnv-valve 
VALVe plz... FIX IT

**Comment by cpw** [comment] 2016-05-09 03:30
The problem is actually that the "libpcre" library used by debian's grep is no longer 100% compatible with the version shipping inside the steam "mini-distro".

````
rm ~/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libpcre.so.3
rm ~/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libpcre.so.3.12.1
````

Will fix the problem, by forcing the steam mini-distro to use the libpcre from the system (3.13.1). The annoying popup will no longer happen (but if you re-install steam because of an update, you'll have to do this again)

**Comment by CreamyCookie** [comment] 2016-05-13 12:57
@cpw 

Would it be possible to create a symlink (owned by root) to system version of libpcre, so Steam can't recreate these outdated versions?

**Comment by Tele42** [comment] 2016-05-13 13:41
@CreamyCookie, no, steam moves the entire steam runtime folder out of the way and unpacks a new steam runtime on any change to the steam runtime.

**Comment by CreamyCookie** [comment] 2016-05-13 13:51
@Tele42 But when Steam is doing normal updates it isn't running as root, so it can't overwrite files / symlinks created by root, or do I misunderstand how Linux file access rights work?

**Comment by Tele42** [comment] 2016-05-13 14:07
@CreamyCookie you can test the claim yourself:
1) create a folder with your regular non-root user
2) in that folder, as root, create a symlink to something
3) as your regular user rename the folder
4) create the folder again as your regular user

There should be no permission violations in that sequence.

**Comment by mhalano** [comment] 2016-05-13 14:09
May be just update libpcre?

Em sex, 13 de mai de 2016 10:51, CreamyCookie <notifications@github.com>
escreveu:

> @Tele42 <https://github.com/Tele42> But when Steam is doing normal
> updates it isn't running as root, so it can't overwrite files / symlinks
> created by root, or do I misunderstand how Linux file access rights work?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ValveSoftware/steam-for-linux/issues/4321#issuecomment-219048666>
>
-- 

Sent from my Android

**Comment by CreamyCookie** [comment] 2016-05-13 15:49
@Tele42 Oops. Well, I probably should have RTFM.

@mhalano That would get overwritten by Steam as well though.

**Comment by mhalano** [comment] 2016-05-13 15:58
@CreamyCookie I'm thinking for ways to fix the bug. Not just to do a
workaround. You got it?

Em sex, 13 de mai de 2016 às 12:49, CreamyCookie <notifications@github.com>
escreveu:

> @Tele42 <https://github.com/Tele42> Oops. Well, I probably should have
> RTFM.
>
> @mhalano <https://github.com/mhalano> That would get overwritten by Steam
> as well though.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/ValveSoftware/steam-for-linux/issues/4321#issuecomment-219082749>
>
-- 

Sent from my Android

**Comment by CreamyCookie** [comment] 2016-05-13 17:10
@mhalano I didn't know you work at Valve.

Of course the package should be updated if it's causing the issue.

**Comment by mhalano** [comment] 2016-05-13 18:06
@CreamCookie I don't work at Valve (I wish :), but I think we should help
who works there to fix this bug fastest as possible. Probably all the
workarounds we can think will become useless after a Steam update because
the integrity checks.

Em sex, 13 de mai de 2016 às 14:10, CreamyCookie <notifications@github.com>
escreveu:

> @mhalano <https://github.com/mhalano> I didn't know you work at Valve.
>
> Of course the package should be updated if it's causing the issue.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ValveSoftware/steam-for-linux/issues/4321#issuecomment-219103035>
>
-- 

Sent from my Android

**Comment by PhoneixS** [comment] 2016-05-15 12:23
@terzag I used your commet and it work but you said "Move these two folders into the ".steam" one you saw previously in your home folder." when for me I needed to move the folders to `.steam/steam/`.

**Comment by terzag** [comment] 2016-05-15 12:47
That's possible, I haven't checked (I use the package from Valve, not the one from the Ubuntu repos). I only detailed what people explained above. That's a bit odd, though, as @rgiyf, @cyberwitch and @inadril all talked about putting them directly in .steam...

**Comment by rgiyf** [comment] 2016-05-15 12:58
@terzag because package from Ubuntu repo installs steam to ~/.steam and from valve to ~/.local/share/Steam

**Comment by terzag** [comment] 2016-05-15 13:10
That's what I thought but @PhoenixS seems to say that it's ~/.steam/steam on his/her system instead.

**Comment by PhoneixS** [comment] 2016-05-15 13:26
Yes, it's what I said. First I copied them to `~/.steam` but weren't detected, moved it to `~/.steam/steam` and steam recognizes them. So if other people have the same problem can try it.

I have Ubuntu 16.04.

**Comment by Xavron** [comment] 2016-05-20 12:05
Its funny, the entire time from the daily's till today, I didn't think of just removing xterm which is popping up the message. If your not using xterm:

sudo apt-get remove --purge xterm

...and goodbye silly popup :-)

**Comment by terzag** [comment] 2016-05-20 12:07
Sure, but it's only hiding the problem rather than fixing it...

**Comment by Xavron** [comment] 2016-05-20 12:11
Nothing here fixes it. Only Valve can do that, but at least I won't ever see it again and I don't use xterm anyway. So don't care if its just hidden - its better and that was the problem imo.

**Comment by terzag** [comment] 2016-05-20 12:15
Removing libpcre from the Steam Runtime fixes the problem. See @cpw message above (11 days ago).

The Steam Runtime is a mess anyway, you already have to remove libs in some cases (like when using the Mesa graphic driver). It's only one more lib to remove than usual until Valve fixes the issue properly.

**Comment by Xavron** [comment] 2016-05-20 12:16
Yet, you have to keep doing it after every update. Give me a break man.

**Comment by riking** [comment] 2016-05-26 03:57
https://github.com/ValveSoftware/steam-for-linux/issues/4321#issuecomment-215679452 was the only solution here that actually resulted in the Steam client's update installing.

**Comment by suprovsky** [comment] 2016-05-28 18:12
Removing libpcre is not working for me.
I'm Using Gentoo x64.

**Comment by samrocketman** [comment] 2016-05-28 18:29
@cpw how did you figure out to remove libpcre?  Did you use strace, ldd, grep and other wizardry?  I'm curious what your process was.

**Comment by falbani** [comment] 2016-05-30 03:25
@cpw What kind of magic you used to figure that out? Genius!

**Comment by natanprog** [comment] 2016-06-08 15:18
@cpw 

It works in Ubuntu Gnome 16.04 LTS 64-bit
but does not work in Lubuntu 16.04 LTS 32-bit

**Comment by magicmyth** [comment] 2016-06-09 09:10
@cpw Thanks for discovering that the issue was with libpcre. I never would have realised that.

Another more elegant (because it will be unaffected by steam updates) method to workaround the libpcre issue is to use:
`export LD_PRELOAD="$LD_PRELOAD /lib/x86_64-linux-gnu/libpcre.so.3 /lib/x86_64-linux-gnu/libpcre.so.3.13.2"`

You can add that in a couple of places. The simplest is to make a copy of steam.desktop into the /usr/local area so it overrides the package version:

`cp /usr/share/applications/steam.desktop /usr/local/share/applications/
sudo editor /usr/local/share/applications/steam.desktop`

And under [Desktop Entry] change:
`Exec=/usr/bin/steam %U` 
to
`Exec=LD_PRELOAD='/lib/x86_64-linux-gnu/libpcre.so.3 /lib/x86_64-linux-gnu/libpcre.so.3.13.2 '${LD_PRELOAD} /usr/bin/steam %U` 

You may need to log out then back in for your desktop to start using your own steam.desktop.

Another method which I myself actual use now is to create a shell script at:
`/usr/local/bin/steam`

With contents like:
```
#!/bin/bash

# This is a custom steam wrapper to prevent library conflicts

if [[ $EUID -eq 0 ]]; then
   echo "This script must not be run as root" 1>&2
   exit 1
fi

# If you find LD_PRELOAD is not enough to get all games working uncomment below:
#find ~/.steam/root/ \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" \) -print -delete
export LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /lib/x86_64-linux-gnu/libgcc_s.so.1 /lib/i386-linux-gnu/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so /usr/$LIB/libasound.so.2 '
# This fixes the "Your system is out of date" message which is caused by
# grep using the library provided by Steam.
# @see https://github.com/ValveSoftware/steam-for-linux/issues/4321#issuecomment-217769283
export LD_PRELOAD="$LD_PRELOAD /lib/x86_64-linux-gnu/libpcre.so.3 /lib/x86_64-linux-gnu/libpcre.so.3.13.2"

exec /usr/bin/steam "$@"
```

You will still need to make the /usr/local/share/applications/steam.desktop copy and edit its line:
`Exec=/usr/bin/steam %U` 
to
`Exec=/usr/local/bin/steam %U`
But from that point on any command calls to "steam" will use the custom wrapper.

NOTE: If you are on 32bit you will need to change the libpcre path from `/lib/x86_64-linux-gnu/libpcre` to `/lib/i386-linux-gnu/libpcre`

**Comment by dennisheitmann** [comment] 2016-06-12 10:27
Thank you for the custom steam wrapper script!

**Comment by BeyondLimitation** [comment] 2016-06-23 02:57
@cpw 
Thanks man! I owe u one.

**Comment by DoNotSpamPls** [comment] 2016-06-28 16:13
I have found an easier way that doesn't require you to do any hard work.
It's very simple - just switch to the Steam Beta release channel. After that the messages will stop.
After that you can simply revert to the normal builds to get the latest non-beta build.

**Comment by ViBE-HU** [comment] 2016-06-28 17:29
@DoNotSpamPls lol not.

**Comment by DoNotSpamPls** [comment] 2016-06-29 17:52
Edited my comment after a test

**Comment by pickledMind** [comment] 2016-07-05 23:33
I really liked @DoNotSpamPls  solution. It was really quick and easy.

**Comment by holtrop** [comment] 2016-07-09 15:53
I got a Steam update this morning that finally seems to have fixed this issue with Ubuntu 16.04.

**Comment by DoNotSpamPls** [comment] 2016-07-11 07:31
After testing, it's confirmed that this issue is fixed. You can fix it for yourself by updating your Steam client.
Please close the issue.

**Closed** 2016-07-11 08:04 UTC
Labels: reviewed

**Comment by xpris** [comment] 2016-07-15 14:42
Yes is fixing now. Thanks.

**Comment by NicoHood** [comment] 2016-08-02 08:41
I just tried to install steam on an ubuntu 14.04 based system. I tried the software center version and the deb package of the website but both do not work. It searches for updates, tries to download but it will not download a single byte from the server. Any ideas how to solve this?

**Comment by samrocketman** [comment] 2016-08-02 17:15
@NicoHood your question seems completely unrelated to this issue.  I recommend finding a relevant open issue or opening a new issue.
