### ISSUE TITLE
Broken symlink from ~/.steam/root

### ISSUE THREAD

**Issue by cdkrot** [ValveSoftware/steam-for-linux#4148] opened 2015-11-21 20:37 UTC
Under ~/.steam there is a dir called "sdk32" it is symbolic link to ~/.steam/root/linux32,

And the ~/.steam/root is a symlink itself, and, magically, it is symlink to itself!

So when a game tries to load a lib from ~/.steam/sdk32 it fails, due to broken symlink.

This problem is probably not specific to my installation, because i deleted the whole ~/.steam directory and it was recreated in the same state again by launcher. Moreover, after each relaunch of steam client the link become broken again, so you have to fix it each time. 

Steam launcher is the latest available from debian testing, the download link from the site was broken when i was writing it.

**Comment by cdkrot** [comment] 2015-11-21 21:41
![a](https://cloud.githubusercontent.com/assets/5040764/11320660/c220cc90-90b1-11e5-9b3f-f002f5edab57.png)

**Comment by Tele42** [comment] 2015-11-21 22:59
Duplicate of #3696.

**Comment by gdrewb-valve** [comment] 2015-11-22 05:51
Closing duplicate.

**Closed by gdrewb-valve** 2015-11-22 05:51 UTC
Labels: duplicate, reviewed
