### ISSUE TITLE
steam beta - unresponsive links

### ISSUE THREAD

**Issue by cjwijtmans** [ValveSoftware/steam-for-linux#3413] opened 2014-07-25 22:20 UTC
when  i go to unread messages for forums i try to click the links but they dont anything, not even the loading animation icon appears. It seems in several other places clicking links doesnt work.

**Comment by kisak-valve** [comment] 2018-03-09 15:52
Closing as a duplicate of #3451.

**Closed by kisak-valve** 2018-03-09 15:52 UTC
Labels: Steam client, reviewed
