### ISSUE TITLE
Steam grabs focus three times while loading...

### ISSUE THREAD

**Issue by PhoenixRiver** [ValveSoftware/steam-for-linux#4241] opened 2016-01-07 19:44 UTC
uname:
3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

While loading steam grabs focus three times despite needing no user interaction, this very annoying (and very rude) when trying to do something else waiting for Steam to load... if it didn't take so long to load this would be less of an issue.

The one thing it hasn't (I presume because it can't) grab focus from is a request from the system for root password... given it's rudeness that actually slightly surprised me! Please make it stop (especially as I swaer it only used to do it twice...)

**Comment by PhoenixRiver** [comment] 2016-01-07 19:46
Forgot:

Steam client application
Built: Jan 1 2016 at 15:10:16
Steam API: v017
Steam package version: 1451695168

P.S. And apparently selecting text in Steam client is also not possible in the about box... not so helpful!

**Comment by rpdelaney** [comment] 2016-02-05 20:19
+1. This is pretty frustrating; Windows users might be more used to this, but in linux development it's quite rude to grab focus without any reason or even asking the user for input on something.

**Comment by kisak-valve** [comment] 2017-03-30 13:53
Closing as a duplicate of #3783.

**Closed by kisak-valve** 2017-03-30 13:53 UTC
Labels: reviewed
