### ISSUE TITLE
Steam doesn't automatically set status to "Away" when no user input for specified time is present

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#2805] opened 2013-08-26 09:31 UTC

**Comment by dsibenik** [comment] 2015-01-02 00:20
@Rocik Nice, thanks. Is there a way I can make steam run the script every time i launch it ?

**Comment by Tele42** [comment] 2015-01-02 03:35
should be a simple launcher script like
```
#!/use/bin/env bash
/usr/local/bin/awaychecker.sh &
/usr/bin/steam
pkill awaychecker.sh
```
The & backgrounds the first command, and proceeds to next command, when you close steam, then pkill should run and clean up the script.

**Comment by Rocik** [comment] 2015-01-02 11:24
@dsibenik Script itself works only if steam is running, but in case you don't want additional process @Tele42 launcher should work.

**Comment by litt89** [comment] 2015-04-05 13:17
@Rocik @Tele42 thanks! works like a charm ;)

**Comment by emnoor** [comment] 2015-10-21 15:45
This is quite a shame that this issue was reported more than 2 years age and yet it is not fixed!

@Rocik I have added these lines to the beginning of the loop so that it ends when steam exits. pkill doesn't work for me from @Tele42's launcher script.

    if [[ ! $(ps aux | grep "/usr/bin/stea[m]") ]]; then
        exit
    fi

**Comment by JamesTheAwesomeDude** [comment] 2016-01-04 01:10
This bug is still in existence. Mint XFCE 17.3.

**Comment by saward** [comment] 2016-03-08 01:00
I think people are used to just seeing me as permanently marked 'online' now after a couple of years of this bug, but would be nice to have fixed.

**Comment by Arcaena** [comment] 2016-08-07 18:01
Can confirm this still happens. I had someone ask me today if I ever slept since they never saw me marked aw away or snooze, which explains some of the weird messages I've gotten at like 4am.

This doesn't happen on any other platform, and other messengers can detect this status just fine, so a fix would be appreciated.

**Comment by SuperJavaDude** [comment] 2016-09-15 04:55
I have this issue as well, unfortunately valve doesn't really care about the linux user base much anymore.

**Comment by Alexander-Walker** [comment] 2016-11-09 22:56
Come on Valve, please fix this.

**Comment by Plagman** [comment] 2016-11-29 04:19
Is xprintidle actually working reliably for you guys? The XScreenSaver extension's idle time is periodically resetting every few minutes in our testing, even on an idle system.

**Comment by Lihis** [comment] 2016-11-29 05:52
@Plagman Is xprintidle still maintained? Anyway, I have thought it is unmaintained so that's why I wrote small C program where I used `XScreenSaverInfo`'s  `idle` to retrieve the idle time and set away/online status based on that. https://linux.die.net/man/3/xscreensaverqueryinfo.

**Comment by Plagman** [comment] 2016-11-29 18:15
We have some test code in Steam that does that now, I was asking how xprintidle was working for people because it also uses it and got linked above, but it just doesn't work. It goes back to 0s idle by itself every few minutes, so it's not reliable to track auto-away.

**Comment by Rocik** [comment] 2016-11-29 19:27
@Plagman I have added logs to my script:
```
[Tue Nov 29 20:03:31 CET 2016] status changed to away
[Tue Nov 29 20:15:46 CET 2016] status changed to online
```
I have been using xprintidle for quite a long time and never noticed timer reset. It would change my state to online for 5 minutes.
I'll try to test it for longer periods of time.

I'm running on fresh packages. Maybe that is the case?

**Comment by Plagman** [comment] 2016-11-30 02:30
I was also running new versions of everything on a Ubuntu 16.10 install. I tested it across several desktop environments and hardware configs and it's reliable on some, but not others, so we just opted to use an alternate method to detect idle time. The next major Steam client beta cycle will have support for changing your status when idle like other platforms.

**Comment by kisak-valve** [comment] 2017-01-05 22:33
Per the [2017-01-05 steam beta update](http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/586991182161672256), does this issue still occur with the beta client?

**Comment by chrjguill** [comment] 2017-01-06 01:11
I'll get someone to check my status overnight and see if it's away/snooze. Is there any way for us to test (should it output something to a terminal if we don't detach it from a terminal?)

Thanks!

**Comment by saward** [comment] 2017-01-21 00:22
I can confirm that this is now working correctly for me with stable client, thanks!  I had twitch running, but walked away from my computer for a while, which seemed to prevent screen from turning away so I was able to see that I'm marked as away.

**Comment by kisak-valve** [comment] 2017-01-21 00:50
Thanks, closing.

**Closed by kisak-valve** 2017-01-21 00:50 UTC
Labels: Need Retest, reviewed, Steam client
