### ISSUE TITLE
Library time played on a cart blurred when mouse hovers

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#7287] opened 2020-07-24 06:49 UTC
#### Your system information

* Steam client version (build number or date): Jul 23 2020, at 11:01:27
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* System information: https://gist.github.com/XakepSDK/f944da51cb4e691280742b6cf7f9908a

#### Please describe your issue in as much detail as possible:
Without hover:
![Screenshot_20200724_123951](https://user-images.githubusercontent.com/4938483/88366807-a919d200-cd79-11ea-9d08-1593388e8f3e.png)

With hover:
![Screenshot_20200724_124908](https://user-images.githubusercontent.com/4938483/88366866-cc448180-cd79-11ea-97cc-42cd87412be4.png)

#### Steps for reproducing this issue:
1. Hover mouse over game cart

**Comment by kisak-valve** [comment] 2020-07-24 13:00
Duplicate of #6596.

**Closed by kisak-valve** 2020-07-24 13:00 UTC
