### ISSUE TITLE
My login window is now blank. Can't login.

### ISSUE THREAD

**Issue by prominentdetail** [ValveSoftware/steam-for-linux#9171] opened 2023-02-03 20:17 UTC
#### Your system information

* Steam client version (feb 2): 
* Distribution ( Ubuntu): 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [No]

#### Please describe your issue in as much detail as possible:
when opening steam, it gives a blank login window

#### Steps for reproducing this issue:
opening steam

![linuxsteam](https://user-images.githubusercontent.com/10412778/216702374-601215a5-1566-436f-a4f2-4dfafbf26707.png)

**Comment by kisak-valve** [comment] 2023-02-03 20:22
Hello @prominentdetail, can you be more clear as to what Ubuntu distro release you are using?

This looks like libcef failed to initialize. If you completely close Steam, then run `steam` from a terminal, are there any hints in the terminal spew? It would also be interesting to check `cef_log.txt` `steamwebhelper.log`, and `webhelper.txt` in ~/.steam/root/logs for any libcef-specific hints.

**Comment by prominentdetail** [comment] 2023-02-03 20:44
I checked and it is ubuntu 16.04 lts
I tried running steam from terminal and this is what I got (it kept repeating same stuff, so I closed it after a while):
```
$ steam
steam.sh[2136]: Running Steam on ubuntu 16.04 64-bit
steam.sh[2136]: STEAM_RUNTIME is enabled automatically
setup.sh[2269]: Steam runtime environment up-to-date!
steam.sh[2136]: Steam client's requirements are satisfied
[2023-02-03 14:32:05] Startup - updater built Jan 31 2023 19:05:55
[2023-02-03 14:32:05] Startup - Steam Client launched with: '/home/alex/.local/share/Steam/ubuntu12_32/steam'
[2023-02-03 14:32:05] Loading cached metrics from disk (/home/alex/.local/share/Steam/package/steam_client_metrics.bin)
[2023-02-03 14:32:05] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2023-02-03 14:32:05] Using the following download hosts for Public, Realm steamglobal
[2023-02-03 14:32:05] 1. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-02-03 14:32:05] Verifying installation...
[2023-02-03 14:32:06] Verification complete
Loaded SDL version 3.0.0-765-gc4db0725e
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "unity-gtk-module"
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf6b1a370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf6b18cc0
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[2377]: Runtime for steamwebhelper: defaulting to /home/alex/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[2377]: Using CEF sandbox (try with -no-cef-sandbox if this fails)
/home/alex/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 115: in_container[@]: unbound variable
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Failed to init SteamVR because it isn't installed
vkEnumeratePhysicalDevices failed, unable to init and enumerate GPUs with Vulkan.
BInit - Unable to initialize Vulkan!
vkEnumeratePhysicalDevices failed, unable to init and enumerate GPUs with Vulkan.
BInit - Unable to initialize Vulkan!
steamwebhelper.sh[2458]: Runtime for steamwebhelper: defaulting to /home/alex/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[2458]: Using CEF sandbox (try with -no-cef-sandbox if this fails)
/home/alex/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 115: in_container[@]: unbound variable
src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 2458 -- steamwebhelper.

src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 2458 -- steamwebhelper.

assert_20230203143227_26.dmp[2466]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230203143227_26.dmp
steamwebhelper.sh[2467]: Runtime for steamwebhelper: defaulting to /home/alex/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[2467]: Using CEF sandbox (try with -no-cef-sandbox if this fails)
/home/alex/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 115: in_container[@]: unbound variable
assert_20230203143227_26.dmp[2466]: Finished uploading minidump (out-of-process): success = yes
assert_20230203143227_26.dmp[2466]: response: CrashID=bp-6efd0c54-35df-41c3-bb37-db6562230203
assert_20230203143227_26.dmp[2466]: file ''/tmp/dumps/assert_20230203143227_26.dmp'', upload yes: ''CrashID=bp-6efd0c54-35df-41c3-bb37-db6562230203''
src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 2467 -- steamwebhelper.

src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 2467 -- steamwebhelper.

steamwebhelper.sh[2475]: Runtime for steamwebhelper: defaulting to /home/alex/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[2475]: Using CEF sandbox (try with -no-cef-sandbox if this fails)
/home/alex/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 115: in_container[@]: unbound variable
src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 2475 -- steamwebhelper.

src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 2475 -- steamwebhelper.

steamwebhelper.sh[2481]: Runtime for steamwebhelper: defaulting to /home/alex/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[2481]: Using CEF sandbox (try with -no-cef-sandbox if this fails)
/home/alex/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 115: in_container[@]: unbound variable
src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 2481 -- steamwebhelper.

src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 2481 -- steamwebhelper.

steamwebhelper.sh[2487]: Runtime for steamwebhelper: defaulting to /home/alex/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[2487]: Using CEF sandbox (try with -no-cef-sandbox if this fails)
/home/alex/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 115: in_container[@]: unbound variable
src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 2487 -- steamwebhelper.

src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 2487 -- steamwebhelper.

steamwebhelper.sh[2493]: Runtime for steamwebhelper: defaulting to /home/alex/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[2493]: Using CEF sandbox (try with -no-cef-sandbox if this fails)
/home/alex/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 115: in_container[@]: unbound variable
src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 2493 -- steamwebhelper.

src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 2493 -- steamwebhelper.

steamwebhelper.sh[2501]: Runtime for steamwebhelper: defaulting to /home/alex/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[2501]: Using CEF sandbox (try with -no-cef-sandbox if this fails)
/home/alex/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 115: in_container[@]: unbound variable
src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 2501 -- steamwebhelper.

src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 2501 -- steamwebhelper.

steamwebhelper.sh[2507]: Runtime for steamwebhelper: defaulting to /home/alex/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[2507]: Using CEF sandbox (try with -no-cef-sandbox if this fails)
/home/alex/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 115: in_container[@]: unbound variable

(steam:2366): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(steam:2366): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[2023-02-03 14:33:38] Shutdown

```

I looked for those log files, but I don't see any listed in that location:
![steamlogslinux](https://user-images.githubusercontent.com/10412778/216706994-f3923681-25d4-4bba-8139-1da355cf556f.png)

**Comment by kisak-valve** [comment] 2023-02-03 20:59
Thanks, `/home/alex/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 115: in_container[@]: unbound variable` is the line of interest from the log.

Distro support for Ubuntu 16.04 ended in 2021, which makes this issue a non-starter. That said, https://github.com/ValveSoftware/steam-for-linux/issues/9158#issuecomment-1413793129 has a plausible explanation that this issue is from bash being older than 4.4.

Closing as a duplicate of #9158.

**Closed by kisak-valve** 2023-02-03 20:59 UTC
Labels: Distro Family: Ubuntu, Web Component
