### ISSUE TITLE
Every Game is running with low fps, unresponsive

### ISSUE THREAD

**Issue by nano3k0a** [ValveSoftware/steam-for-linux#4517] opened 2016-06-26 03:53 UTC
#### Your system information
- Steam client version: 
- steam-runtime-release_2016-02-23
- Steam API: v017
- Steam package version: 1465948400
- Distribution (e.g. Ubuntu):  Arch Linux x64
- Opted into Steam client beta?: No 
- Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:

Steam installation is running without issues, download and starting games is also not an issue.
But when I start any Game (tested with Soma, Alien Isolation and Dota 2). The game runs with 1fps and everything is unresponsive, mouse and keyboard actions are executed after > 30sec. When I then somehow manage to close the game, Steam also crashes. I have attached the dump file. Every library that is needed (yes the 32 libs) are installed, otherwise whether steam or any game should not even start (which is not the case). 

I then tried to start the game outside of steam to see if this has something to do with only steams runtime and yes it does, because outside of steam the games are running fine. Steam worked always without any issues but after several steam updates and arch updates now it doesn't work anymore. 

I tried every solution of the steam troubleshooting page on the arch wiki and still I am stuck with the same problem. 

[crash.zip](https://github.com/ValveSoftware/steam-for-linux/files/333413/crash.zip)
#### Steps for reproducing this issue:
1. Start a Game

**Comment by fiszts** [comment] 2016-06-27 13:42
Having the same problem, 1-10 fps with artifacts on GTX 980, I even thought that my videocard are going to die, tried to reinstall prop NVIDIA drivers with different versions, to swith to nouveau with same result...

Are you serious? No ads\updates\notes about this issue, I can't imagine what's going on within steam client to couse the perfomance leakage like this (looks like infinite loop of furmark and cpuburn), rofl.

So is the any solution?

**Comment by Trodis** [comment] 2016-06-27 14:15
I really did try everything I could, I solve it at the end by reinstalling my arch system. Now Steam works perfectly without issues. Without proper linux debug knowledge the problem is hard to pinpoint.

**Comment by fiszts** [comment] 2016-06-27 15:34
Very radical method, lol, but you gave me a hint, if everything works after just reinstalling...
Solution:

Run dota2 or some different games from .steam folder, "/home/$USER/.steam/steam/steamapps/common/dota 2 beta/game/dota.2" it will throw some warning, mine was about the next libs:

"ibpng12" — updated in many linux distros, now it's "libpng16-16"
"libudev" — updated too, it was "libudev.so.0" and now it's "libgudev-1.0"

Anyway, steam still requiring em, so just create symlinks in "/usr/lib/x86_64-linux-gnu/":
ln -s libpng16.so.16.23.0 libpng12.so
ln -s libudev.so.1.6.4 libudev.so

Steam — adventure-game with presence effect, rofl.

**Comment by kisak-valve** [comment] 2019-05-31 17:06
Hello @nano3k0a, @fiszts, are either of you still experiencing this issue on an up to date system?

In general, you're asking for a bad day by symlinking libpng12 to libpng16 because they are not ABI compatible.

**Comment by kisak-valve** [comment] 2019-07-05 19:25
Closing pending feedback.

**Closed by kisak-valve** 2019-07-05 19:25 UTC
Labels: Need Retest, reviewed
