### ISSUE TITLE
[CS 1.6] Missing arrows in spectator menu

### ISSUE THREAD

**Issue by healthycs16** [ValveSoftware/steam-for-linux#3051] opened 2013-12-19 03:37 UTC
Arrows don't show up in spectator menu so I can't see if a option like PiP is enabled or not.

**Comment by kisak-valve** [comment] 2017-10-20 14:23
Closing as a duplicate of https://github.com/ValveSoftware/halflife/issues/214.

**Closed by kisak-valve** 2017-10-20 14:23 UTC
Labels: MOVED: Counter‐Strike, reviewed
