### ISSUE TITLE
Steam client - "Removing ..." window issue

### ISSUE THREAD

**Issue by UAVXP** [ValveSoftware/steam-for-linux#2607] opened 2013-06-20 07:53 UTC
I can make so many "removing" windows, when Steam is still removing things
Screenshot: http://img15.imageshack.us/img15/9965/ev3q.png - there's only one window when the game has been deleted, but when game is so big and deleting time is quite long, I can make 20 or more windows, I didn't notice. And those windows are still on the screen until exiting Steam client.

**Comment by eiglow** [comment] 2021-01-12 01:38
Looks like that screenshot link is dead, so I can't really tell what the issue is.

**Comment by kisak-valve** [comment] 2021-01-12 01:42
Hello @UAVXP, @eiglow, the UI for game removal has been overhauled since this issue was reported, and if you're still seeing something similar, then it would need to be re-evaluated from scratch.

Closing as outdated.

**Closed by kisak-valve** 2021-01-12 01:42 UTC
Labels: Steam client, reviewed
