### ISSUE TITLE
Requesting CD key doesn't deliver it

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4557] opened 2016-07-20 07:31 UTC
#### Your system information
- Steam client version: Latest stable as of today
- Distribution (e.g. Ubuntu): Ubuntu
- Opted into Steam client beta?: [Yes/No] No
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

Clicking on the right menu to request CD key for available games
doesn't work. it just opens a window saying requesting key and it never finishes.

**Comment by ekaris** [comment] 2016-07-20 18:53
Turns out it's only with some games like Mount & Blade: With Fire & Sword

**Comment by gammelinke** [comment] 2018-06-27 02:00
Hi guys,

The answser from [arenanet/guild wars support](https://imgur.com/a/Koceqmb)
I can't get the support on steam [and the "bug" is still there](https://imgur.com/a/HeOP71i)
Where can I talk to someone?
At least, can anyone answer?

**Comment by kisak-valve** [comment] 2019-07-05 19:38
Closing as a duplicate of #212.

**Closed by kisak-valve** 2019-07-05 19:38 UTC
Labels: reviewed
