### ISSUE TITLE
[beta] libcef fontconfig - undefined symbol: FcConfigGetSysRoot 

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#7059] opened 2020-04-24 00:44 UTC
with an up-to-date beta client, using the steam-runtinem fontconfig library will break the client, which will periodically output:
"STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: ./libcef.so: undefined symbol: FcConfigGetSysRoot"

**Comment by TTimo** [comment] 2020-04-24 15:03
This is a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/6845 and https://github.com/ValveSoftware/steam-for-linux/issues/6499.

Based on https://github.com/ValveSoftware/steam-runtime/issues/253 you are forcing an incompatible fontconfig to libcef, which causes the problem.

**Closed by TTimo** 2020-04-24 15:03 UTC
Labels: Web Component, runtime

**Comment by sylware** [comment] 2020-04-25 01:14
On Fri, Apr 24, 2020 at 08:03:28AM -0700, TTimo wrote:
> Closed #7059.

What do you mean? The breaking fontconfig is the verbatim one from the steam-runtime.
I don't understand.

**Comment by sylware** [comment] 2020-04-25 13:50
Wow.

Yesterday, I could not check the issues you were refering to because github
would send me a blunt "not found" error code... Today it worked and I could verify
that my issue was actually a duplicate of 6845. Something web/internet is
significantly "laggy".
