### ISSUE TITLE
"OpenGL GLX context is not using direct rendering" popping up again

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3907] opened 2015-06-25 03:52 UTC
Hi, I'm getting the eponymous issue again whenever I start up Steam on Linux. Can't run 3D games like Borderlands 2 or Civilization V. While I know it's not officially supported, I'm using Chakra Linux, 64-bit. I started getting the error again after a large update, bringing me to kernel 4.0.5 and fglrx 15.5.

Tried removing some libraries from the .local/share directories, didn't work this time around. What I'm getting from running Steam from a terminal emulator displays this.

"libGL error: open uki failed (Operation not permitted)
libGL error: reverting to (slow) indirect rendering"

Any help with this one? Thanks for your time.

**Comment by agame-chakra** [comment] 2015-07-04 09:47
I have the same problem with the same setup, I just opened a topic on chakraos forums. By the first explorations I have done, it seems to be a driver related problem. I will test more to narrow the causes but I am no linux guru so any help is welcome.

**Comment by Zomtir** [comment] 2015-11-21 14:10
You might try to add /usr/lib32/fglrx to the LD_LIBRARY_PATH in ~/.steam/steam.sh

Lines 709-710 should look like this afterwards:

    # Need to add /usr/lib32 to the library path to pick up libvdpau_nvidia.so on Ubuntu 12.04
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH-}:/usr/lib32:/usr/lib32/fglrx"

The underlying issue seems to be libGL.so.1, which is not taken up from /usr/lib32/fglrx but /usr/lib/i386-linux-gnu/mesa instead. Therefor steam fails to use direct rendering when using the proprietary ATI drivers.

 @Plagman Could this be taken into upstream as well?

**Comment by Zomtir** [comment] 2015-11-25 08:52
The file steam.sh resets itself before execution, it worked the first time I tried though. As a workaround put this line into ~/.profile

    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH-}:/usr/lib32/fglrx"

**Comment by kisak-valve** [comment] 2018-11-02 18:16
Hello @agame-chakra, @Zomtir, are either of you still experiencing this issue with an up to date system?

**Comment by Zomtir** [comment] 2018-11-02 22:07
This specific issue is resolved. Fglrx is no longer supported by AMD and Ubuntu. The default radeon drivers now work out of the box on my setup. Back then fglrx was almost mandatory.

I did not test the AMDGPU-PRO drivers, but if it failed, it would probably belong into a new bug report.

**Comment by kisak-valve** [comment] 2018-12-07 13:51
Thanks for the feedback @Zomtir, closing.

**Closed by kisak-valve** 2018-12-07 13:51 UTC
Labels: Need Retest, reviewed
