### ISSUE TITLE
Download speed is much slower than windows

### ISSUE THREAD

**Issue by zoobporsor** [ValveSoftware/steam-for-linux#11089] opened 2024-07-13 18:54 UTC
#### Your system information

* Steam client version (build number or date):  Steam Version:  1718904662 Steam Client Build Date:  Thu, Jun 20 2:44 PM UTC -08:00
* Distribution (e.g. Ubuntu):  Arch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* 
[connection_log_27015.txt](https://github.com/user-attachments/files/16203359/connection_log_27015.txt)
[connection_log_0.txt](https://github.com/user-attachments/files/16203360/connection_log_0.txt)
[console_log.previous.txt](https://github.com/user-attachments/files/16203361/console_log.previous.txt)
[cloud_log.previous.txt](https://github.com/user-attachments/files/16203362/cloud_log.previous.txt)
[timedtrial_log.txt](https://github.com/user-attachments/files/16203363/timedtrial_log.txt)
[systemdisplaymanager.txt](https://github.com/user-attachments/files/16203364/systemdisplaymanager.txt)
[systemaudiomanager.txt](https://github.com/user-attachments/files/16203365/systemaudiomanager.txt)
[systemdockmanager.txt](https://github.com/user-attachments/files/16203366/systemdockmanager.txt)
[client_networkmanager.txt](https://github.com/user-attachments/files/16203367/client_networkmanager.txt)
[steamui_update.txt](https://github.com/user-attachments/files/16203368/steamui_update.txt)
[workshop_log.txt](https://github.com/user-attachments/files/16203369/workshop_log.txt)
[steamui_audio.txt](https://github.com/user-attachments/files/16203370/steamui_audio.txt)
[steamui_system.txt](https://github.com/user-attachments/files/16203371/steamui_system.txt)
[appinfo_log.txt](https://github.com/user-attachments/files/16203372/appinfo_log.txt)
[parental_log.txt](https://github.com/user-attachments/files/16203373/parental_log.txt)
[connection_log.txt](https://github.com/user-attachments/files/16203374/connection_log.txt)
[compat_log.previous.txt](https://github.com/user-attachments/files/16203375/compat_log.previous.txt)
[cef_log.previous.txt](https://github.com/user-attachments/files/16203376/cef_log.previous.txt)
[transport_client.txt](https://github.com/user-attachments/files/16203377/transport_client.txt)
[transport_steamui.txt](https://github.com/user-attachments/files/16203378/transport_steamui.txt)
[text_filter_log.txt](https://github.com/user-attachments/files/16203379/text_filter_log.txt)
[steamui_html.txt](https://github.com/user-attachments/files/16203380/steamui_html.txt)
[stats_log.txt](https://github.com/user-attachments/files/16203381/stats_log.txt)
[cef_log.txt](https://github.com/user-attachments/files/16203382/cef_log.txt)
[webhelper-linux.txt](https://github.com/user-attachments/files/16203383/webhelper-linux.txt)
[remote_connections.txt](https://github.com/user-attachments/files/16203384/remote_connections.txt)
[cloud_log.txt](https://github.com/user-attachments/files/16203385/cloud_log.txt)
[sitelicense_log.txt](https://github.com/user-attachments/files/16203386/sitelicense_log.txt)
[shader_log.txt](https://github.com/user-attachments/files/16203387/shader_log.txt)
[systemperfmanager.txt](https://github.com/user-attachments/files/16203388/systemperfmanager.txt)
[compat_log.txt](https://github.com/user-attachments/files/16203389/compat_log.txt)
[streaming_log.txt](https://github.com/user-attachments/files/16203390/streaming_log.txt)

* GPU: Nvidia

#### Please describe your issue in as much detail as possible:

 My max download speed is something like 35mb
On windows 11, I can reach that no problem
On Linux, specifically Arch Linux right now, by default I was only able to get 3-4MB

I made a steam_dev.cfg file and put:
@nClientDownloadEnableHTTP2PlatformLinux 0
@fDownloadRateImprovementToAddAnotherConnection 1.0

This helped, now my download speed goes up to 14.5MB, still its only half as fast as it was on Windows
What is causing this?

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Use Arch Linux (any linux?)
2. Try to download anything
3.  Download speeds are much slower than Windows or other places
4. Using steam_dev.cfg   @nClientDownloadEnableHTTP2PlatformLinux 0
@fDownloadRateImprovementToAddAnotherConnection 1.0
6. improved it a bit, but still half as slow as it should be. 
7.

**Comment by kisak-valve** [comment] 2024-07-13 19:01
Hello @zoobporsor, there's no value in fragmenting the discussion of this issue across anther issue report.

Closing as a duplicate of #9715 / #10248.

**Closed by kisak-valve** 2024-07-13 19:01 UTC
