### ISSUE TITLE
Steam menu not opening on Cinnamon taskbar, after gtk3 update.

### ISSUE THREAD

**Issue by Zerophase** [ValveSoftware/steam-for-linux#4893] opened 2017-03-14 23:34 UTC
#### Your system information
1
* Steam client version: 1489442219 
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Clicking on the steam icon on the system tray area doesn't open Steam's menu. I just upgraded gtk3, along with dependencies, and the menu won't come up. Every other app works in there, so I believe this is a steam issue, and not a Cinnamon issue. After a restart this behaviour persisted, so I'm fairly certain it is a bug.

#### Steps for reproducing this issue:

1. Install Cinnamon on Arch
2. Install Steam.
3.  Try opening Steam from the System tray.

**Comment by kisak-valve** [comment] 2017-03-14 23:52
Hello @Zerophase, I just confirmed the steam tray icon works as expected with Cinnamon on my Arch test box.

Steam uses libappindicator built against gtk2 for the steam tray icon and you are most likely encountering #4795.

Can you confirm that lib32-libappindicator-gtk2, lib32-libindicator-gtk2, lib32-libdbusmenu-glib and lib32-libdbusmenu-gtk2 are installed on your system?

**Comment by Zerophase** [comment] 2017-03-15 00:06
Yeah, it works fine after installing those packages. Previously, I didn't have those packages installed, and the Steam tray icon was working as expected.

**Comment by kisak-valve** [comment] 2017-03-15 00:11
Right, so that had to have been before the 2017-01-19 steam client update, which changed the behavior to prefer system libraries.

As a side note, these packages are pulled in by the steam-native-runtime package among other things. You may want to follow up with Arch's package maintainer for steam to have these dependencies moved to the steam package.

Closing as a duplicate of #4795.

**Closed by kisak-valve** 2017-03-15 00:11 UTC
Labels: Distro Family: Arch
