### ISSUE TITLE
steamwebhelper invalid opcode with Arch NVIDIA 535.54.03-1 driver

### ISSUE THREAD

**Issue by steckhelena** [ValveSoftware/steam-for-linux#9634] opened 2023-06-16 16:48 UTC
#### Your system information

* Steam client version (build number or date): 1686880776
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes and No - none works
* Have you checked for system updates?: Yes

[system_information.txt](https://gist.github.com/steckhelena/015c8301f4effdd127370aa3aedb1edd)

#### Please describe your issue in as much detail as possible:

The new Steam client UI does not open, even though Steam is running. There are no crashes, you can see the logs [here](https://gist.github.com/steckhelena/87c3fa38ef4b05957b595d1cef1f2d73), but the UI won't open.

I can see the UI by running Steam with `steam -vgui`, but then 'friends' won't go online.

#### Steps for reproducing this issue:

1. Install steam on arch + latest Nvidia drivers (`535.54.03-1`)
2. ???
3. UI does not open

**Comment by kisak-valve** [comment] 2023-06-16 16:55
Hello @steckhelena, this issue is already being tracked at #9630. Closing as a duplicate.

**Comment by steckhelena** [comment] 2023-06-16 17:01
I don't think it is a duplicate, as even without beta and with GPU acceleration disabled (disabling it in the `-vgui`), it is not working. Or maybe you should update that report to include that non-beta clients and clients with the `GPU accelerated rendering` disabled are also affected by it.

**Comment by kisak-valve** [comment] 2023-06-16 17:07
As a quick test, are you able to downgrade to NVIDIA driver to the 530.xx series (including nvidia-dkms, nvidia-utils, and lib32-nvidia-utils) and see if that has an effect?

**Comment by Cephi-sui** [comment] 2023-06-16 17:40
@kisak-valve I was running into this issue. `sudo dmesg` showed errors regarding invalid opcodes. I was able to downgrade nvidia-utils lib32-nvidia-utils and nvidia to 530.xx (as well as downgrading linux and linux-headers to 6.3.7.arch1-1, because I was not able to boot into a GUI with 535.xx and 6.3.8) and get Steam to launch properly.

**Comment by kisak-valve** [comment] 2023-06-16 17:42
Hello @Cephi-sui, that should be mentioned to your video driver vendor and/or your distro's package maintainer for the video driver.

**Comment by Cephi-sui** [comment] 2023-06-16 17:46
@kisak-valve Apologies. I am on Arch Linux using the Extra repo through pacman. To downgrade my linux and nvidia packages, I used `downgrade` from the AUR, which in turn obtains its packages through the Arch Linux Archive repository here: https://archive.archlinux.org/

**Comment by kisak-valve** [comment] 2023-06-16 18:58
Thanks, that's enough details that we can consider this a distinctly different issue from the older issue report.

**Comment by ln4r3n** [comment] 2023-06-16 19:43
I have this line in dmesg with AMDGPU as well:
```traps: steamwebhelper[6337] trap invalid opcode ip:7f92e2cc013b sp:7ffd9c0c9220 error:0 in libcef.so[7f92deaef000+7770000]```

ArchLinux (currently up to date)
Linux `6.3.8-arch1-1`
Mesa `23.1.2-1`
Radeon RX6950XT
Beta: No

**Comment by steckhelena** [comment] 2023-06-17 00:40
If it helps, I've got a stacktrace from journalctl when running `steam` with the nvidia 535.54.03-1drivers:

```
Jun 16 21:27:07 fenrir kernel: traps: steamwebhelper[2836] trap invalid opcode ip:7f13029db794 sp:7ffc7be2aaf0 error:0 in libcef.so[7f13000ef000+7770000]
Jun 16 21:27:08 fenrir systemd[1]: Started Process Core Dump (PID 3023/UID 0).
Jun 16 21:27:08 fenrir systemd-coredump[3024]: [🡕] Process 2836 (steamwebhelper) of user 1000 dumped core.
                                               
                                               Stack trace of thread 2836:
                                               #0  0x00007f13029db794 n/a (/home/steckhelena/.local/share/Steam/ubuntu12_64/libcef.so + 0x43db794)
                                               #1  0x00007f1302a67522 n/a (/home/steckhelena/.local/share/Steam/ubuntu12_64/libcef.so + 0x4467522)
                                               #2  0x00007f1302a6a764 n/a (/home/steckhelena/.local/share/Steam/ubuntu12_64/libcef.so + 0x446a764)
                                               #3  0x00007f12eaef77f2 n/a (libnvidia-glcore.so.535.54.03 + 0x14f77f2)
                                               #4  0x00007f12ea9fcf45 n/a (libnvidia-glcore.so.535.54.03 + 0xffcf45)
                                               #5  0x00007f12eaa0844a n/a (libnvidia-glcore.so.535.54.03 + 0x100844a)
                                               #6  0x00007f12eb4e9992 n/a (libnvidia-glcore.so.535.54.03 + 0x1ae9992)
                                               #7  0x00007f12ead7a868 n/a (libnvidia-glcore.so.535.54.03 + 0x137a868)
                                               #8  0x00007f12ead4827e n/a (libnvidia-glcore.so.535.54.03 + 0x134827e)
                                               #9  0x00007f12fe4baffa n/a (/home/steckhelena/.local/share/Steam/ubuntu12_64/libSDL3.so.0 + 0x9affa)
                                               ELF object binary architecture: AMD x86-64
Jun 16 21:27:08 fenrir systemd[1]: systemd-coredump@1-3023-0.service: Deactivated successfully.
Jun 16 21:27:17 fenrir kernel: traps: Composite Threa[3149] trap invalid opcode ip:7fbe32fdb794 sp:7fbe205c38f0 error:0 in libcef.so[7fbe306ef000+7770000]
Jun 16 21:27:17 fenrir systemd[1]: Started Process Core Dump (PID 3185/UID 0).
Jun 16 21:27:18 fenrir systemd-coredump[3186]: [🡕] Process 3043 (steamwebhelper) of user 1000 dumped core.
                                               
                                               Stack trace of thread 3149:
                                               #0  0x00007fbe32fdb794 n/a (/home/steckhelena/.local/share/Steam/ubuntu12_64/libcef.so + 0x43db794)
                                               #1  0x00007fbe33067522 n/a (/home/steckhelena/.local/share/Steam/ubuntu12_64/libcef.so + 0x4467522)
                                               #2  0x00007fbe3306a764 n/a (/home/steckhelena/.local/share/Steam/ubuntu12_64/libcef.so + 0x446a764)
                                               #3  0x00007fbe1b2f77f2 n/a (libnvidia-glcore.so.535.54.03 + 0x14f77f2)
                                               #4  0x00007fbe1adfcf45 n/a (libnvidia-glcore.so.535.54.03 + 0xffcf45)
                                               #5  0x00007fbe1ae0844a n/a (libnvidia-glcore.so.535.54.03 + 0x100844a)
                                               #6  0x00007fbe1b146182 n/a (libnvidia-glcore.so.535.54.03 + 0x1346182)
                                               #7  0x00007fbe1b149cb5 n/a (libnvidia-glcore.so.535.54.03 + 0x1349cb5)
                                               #8  0x00000000004a9c2f n/a (/home/steckhelena/.local/share/Steam/ubuntu12_64/steamwebhelper + 0xa9c2f)
                                               ELF object binary architecture: AMD x86-64
Jun 16 21:27:18 fenrir systemd[1]: systemd-coredump@2-3185-0.service: Deactivated successfully.
```

Steam never fully crashes, and I can still launch games via the applet. The second stacktrace seems to keep repeating while Steam is open.

I've reported that I saw this with the `-vgui` option, but I think I may have confused the timestamps, as when running with it, I don't see the invalid opcode error.

Also, this issue seems similar to https://github.com/ValveSoftware/steam-for-linux/issues/9577

**Comment by jrgiacone** [comment] 2023-06-20 01:13
any update on this?

**Comment by ahuillet** [comment] 2023-06-22 09:40
I've looked at this briefly - the stack trace in the NVIDIA driver stack is simply a call to malloc.
The libcef.so part appears to be the malloc reimplementation provided by libcef, which seems to end on an INT 3 instruction.
This seems to be a CEF bug.

**Comment by Wesselinator** [comment] 2023-06-22 21:15
>
> The opcode message does not appear with the downgraded drivers (`530.41.03-1`).

Can confirm after downgrading from `535.54.03-1` to `530.41.03-1`  everything is working fine again.

more info :  
* Beta would not launch any window (tray icon still functioned in a limited fashion)
* Got it open with `steam -vgui` but the friends panel did not work and trying to open any "new" panels like the `settings -> downloads -> library folders` would force reload every open steam window and did not function.

**Comment by ajuniper** [comment] 2023-06-23 18:29
Same problem on Ubuntu 20.04 with latest AMD drivers 5.18.13.
System was working fine prior to installation of AMD graphics card over the weekend.
```
[ 4557.679922] traps: Composite Threa[279821] trap invalid opcode ip:7f3a8af2a794 sp:7f3a75ac5920 error:0 in libcef.so[7f3a8863e000+7770000]
[ 4567.387682] traps: Composite Threa[280691] trap invalid opcode ip:7f8ecd3f4794 sp:7f8eb4cd1920 error:0 in libcef.so[7f8ecab08000+7770000]
[ 4577.214636] traps: Composite Threa[281576] trap invalid opcode ip:7fd812fa4794 sp:7fd7fa881920 error:0
[ 4587.449842] traps: Composite Threa[282600] trap invalid opcode ip:7f76dfbb7794 sp:7f76ca723920 error:0 in libcef.so[7f76dd2cb000+7770000]
```
Works ok using `steam -vgui`

**Comment by joethefox** [comment] 2023-06-24 09:21
@Wesselinator adding also -no-cef-sandbox worked for me, at least now I can open also the game properties again...

so starting steam:
`$ steam -vgui -no-cef-sandbox` 
seems a robust workaround with my environment.

Maybe, and underlining maybe, looking for a workaround by adding automatically this options until that the libcef.so and the "it's not me, it's your fault!" incidend is solved, could be a good workround for people that don't wan't to go crazy and search the internet for esotic solutions just for start playing again with their games.

**Comment by jrgiacone** [comment] 2023-06-25 17:14
> @Wesselinator adding also -no-cef-sandbox worked for me, at least now I can open also the game properties again...
> 
> so starting steam: `$ steam -vgui -no-cef-sandbox` seems a robust workaround with my environment.
> 
> Maybe, and underlining maybe, looking for a workaround by adding automatically this options until that the libcef.so and the "it's not me, it's your fault!" incidend is solved, could be a good workround for people that don't wan't to go crazy and search the internet for esotic solutions just for start playing again with their games.

does your friends list work?

**Comment by LuckyMcBeast** [comment] 2023-06-29 03:28
https://forums.developer.nvidia.com/t/535-54-03-driver-regression-with-steams-new-web-gui-530-works/258225/2

A thread was started earlier today on the Nvidia forums. I commented on it because I'm having the same issue. Shared this issue in my post.

**Comment by twoxa** [comment] 2023-07-01 09:08
I got it to work by launching steam with the `-vgui` option and then in the settings enabling GPU accelerated rendering in web views. After restarting steam without the -vgui option the new UI shows up and works normally. The invalid opcode  errors are still there and the UI feels a bit choppier and glitchier than before but it works.

**Comment by achurch** [comment] 2023-07-03 22:29
I encountered what looked like this same issue (including the INT 3) after upgrading to the 535 driver, but it turned out to be #9233 instead - I wonder if the INT 3 is an intentional abort in an OOM handler?

**Comment by ahuillet** [comment] 2023-07-05 08:51
Yes, the INT 3 is an intentional abort in an OOM handler in CEF. CEF is failing to allocate memory for some reason. That should be debugged in Steam/CEF.

**Comment by Draco-Omega** [comment] 2023-07-05 18:54
Hello. I have a very similar issue. I am able to start steam using the work around $ steam -vgui, however, I try to run games with a bit of sofistication in the graphics (such as frostpunk) and they crash.
Games that could run on the snes as the messenger or infernax, run ok.

**Comment by RustyReich** [comment] 2023-07-05 19:23
[This](https://github.com/ValveSoftware/steam-for-linux/issues/9780#issuecomment-1622073358) comment seemingly got Steam working consistently again for me.

**Comment by Fell-x27** [comment] 2023-08-01 06:49
535.54.03 - the issue appears randomly.

**Comment by Wesselinator** [comment] 2023-08-06 18:45
Note for anyone still running on the reverted drivers:
`535.86.05` has been working for me so far, but YMMV.
Unsure if new steam version or new nvidia drivers but its working so not complaining.

**Comment by kisak-valve** [comment] 2023-09-08 22:55
Closing as this appears to have been a video driver issue.

**Closed by kisak-valve** 2023-09-08 22:55 UTC
Labels: NVIDIA drivers, Need Retest, Distro Family: Arch, Web Component
