### ISSUE TITLE
[Fix]Issue with Steam active on Taskbar on close

### ISSUE THREAD

**Issue by Yupy** [ValveSoftware/steam-for-linux#4307] opened 2016-02-09 15:26 UTC
Location: usr/bin/steam

Under:

`export STEAMSCRIPT="$(cd "${0%/*}" && echo "$PWD")/${0##*/}"`

Needs to be added:

`export STEAM_FRAME_FORCE_CLOSE=1`

**Comment by Tele42** [comment] 2016-02-09 15:34
This is effectively a duplicate of #1025 and is the current intended behavior picked by valve.

**Comment by gdrewb-valve** [comment] 2016-02-09 16:49
Closing duplicate.

**Closed by gdrewb-valve** 2016-02-09 16:49 UTC
Labels: duplicate, reviewed
