### ISSUE TITLE
Regression in Remote Play: Certain games now have bleached/washed out colors in stream after Mar 4 update

### ISSUE THREAD

**Issue by Lyusternik** [ValveSoftware/steam-for-linux#8458] opened 2022-03-06 17:40 UTC
#### Your system information

* Steam client version (build number or date): Mar 6, 2022, 00:19:25
* Distribution (e.g. Ubuntu): Manjaro, but problems reported across multiple platforms
* Opted into Steam client beta?: [Yes/No] Yes, but issue also exists in non-beta version.
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
After recent update (probably March 4, as the earliest comment about the issue recently I can find is March 5), certain games when streamed will have a highly saturated/bleached appearance when streamed, to the point where the screen is almost entirely white and UI elements can barely be made out. The game appearance on the host device remains unchanged. This issue did not occur prior to the update.

I personally have this issue with Star Wars: Empire at War: Gold Pack but other users have reported issues with different games.
[report 1](https://www.reddit.com/r/Steam/comments/t7zemc/steam_update_has_broken_remote_play/)
[report 2](https://steamcommunity.com/app/32470/discussions/0/3187990555108560744/)
[report 3](https://steamcommunity.com/app/21130/discussions/0/3177854919328078252/)
[report 4](https://steamcommunity.com/app/32440/discussions/0/3185736218669832240/)
[report 5](https://steamcommunity.com/app/32440/discussions/0/3191368254807827760/)
One can find many more reports by searching 'remote play white' across steam discussions.
[image from report 1 illustrating the problem](https://i.imgur.com/oSKhdpj.png)

https://github.com/ValveSoftware/steam-for-linux/issues/6066 had similar effects, but their workaround of enabling performance metrics does not work.

#### Steps for reproducing this issue:
Attempt to stream an affected game (Star Wars: Empire at War: Gold Pack, Lego Harry Potter etc.)
Other users note that it is also possible for certain games to work initially, but the color effect occurs for certain menus/interfaces only e.g. dialogue in Fallout New Vegas.
I do not yet know whether this is tied to particular hardware, but I suspect it isn't.

**Comment by skavenger6666** [comment] 2022-03-09 23:22
Tried here too, both with stable and beta, and I confirm the same also happens to me on Windows (saint seiya SS, guilty geat xrd sign, skullgirls), so the regression looks like it's crossplatform. Most games are bleached, one is blacked.

**Comment by hughbirky** [comment] 2022-03-10 02:15
This same thing happened to me tonight when streaming Lego Star Wars the Complete Saga. Friend's screen was completely washed out.

**Comment by Lyusternik** [comment] 2022-03-10 02:37
I've read speculation on other threads/bug reports that it might be related to games that still use DirectX 9, but I'm not sure if that holds water.

**Comment by chi18000** [comment] 2022-03-11 00:52
Same situation in game: Don't Starve Together.
My host and client are both Windows 10.
The remote playing screenshot: https://imgur.com/YZvsu0c
If I use MS remote desktop, the color is correct (but more latency with control)
I tried different game like [Styx: Master of Shadows], the color is correct.

**Comment by slouken** [comment] 2022-03-11 20:10
Fixed in the latest beta update, thanks!

**Closed by slouken** 2022-03-11 20:10 UTC
Labels: Streaming

**Comment by TTimo** [comment] 2022-03-11 21:56
this is fixed in Steam beta client released on March 10th. Please retest.

**Comment by Lyusternik** [comment] 2022-03-11 22:37
Confirming that the issue is no longer present with Star Wars: Empire at War: Gold Pack after the host machine had Steam updated to the latest beta.

**Comment by DooMMasteR** [comment] 2022-03-22 23:10
For me colors are still weirdly washed out with the latest beta client and Ubuntu 21.10
