### ISSUE TITLE
Steam "-newbigpicture" does not display custom artwork

### ISSUE THREAD

**Issue by Goggo66** [ValveSoftware/steam-for-linux#8908] opened 2022-11-10 10:47 UTC
#### Your system information

* Steam client version (build number or date): 1667965227
* Distribution (e.g. Ubuntu): Kubuntu 22.04
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I have added custom artwork to several non-Steam games in my library. When starting Steam with the "-newbigpicture" option and switching to the new big picture mode, the custom artwork is not displayed.
![Screenshot_20221110_102853](https://user-images.githubusercontent.com/79007900/201069551-4a1d20bc-76f0-4d7b-a4d7-6421e5107447.jpg)
When starting Steam with the "-gamepadui" option, custom artwork is displayed.
![Screenshot_20221110_103137](https://user-images.githubusercontent.com/79007900/201069681-2d4ebd2a-6059-4c2b-9dab-fd8ef3b27c29.jpg)

#### Steps for reproducing this issue:

1. Start Steam with "-newbigpicture" option.
2. If no non-Steam game exists: add a non-Steam game, and add some custom artwork for a better presentation (e.g. header, library, or logo images).
3. Switch to the new big picture mode.
4. Observe that the custom artwork is missing.
5. Restart Steam with "-gamepadui" option.
6. Observe that the custom artwork is displayed.

**Comment by kisak-valve** [comment] 2022-11-11 16:13
Hello @Goggo66, per "Fixed issue where custom artwork and local screenshots were not found when running with -newbigpicture" in the [2022-10-10](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/5040118834414844880) Steam client beta, please retest this issue.

**Comment by Goggo66** [comment] 2022-11-12 11:58
Yes, I can confirm, the issue is fixed. My Steam client beta version is 1668138960.

**Comment by kisak-valve** [comment] 2022-11-12 13:45
Thanks for retesting. Closing as fixed.

**Closed by kisak-valve** 2022-11-12 13:45 UTC
Labels: Big Picture, Need Retest

**Comment by Denyerec** [comment] 2023-03-05 12:10
Unsure if this is related, but I do not see, and cannot add/edit custom artwork for non steam games when viewing in Bigpicturemode (No commandline flags) via SteamLink.

**Comment by PigDan20** [comment] 2023-05-14 22:01
> Unsure if this is related, but I do not see, and cannot add/edit custom artwork for non steam games when viewing in Bigpicturemode (No commandline flags) via SteamLink. Windows 10 Client Ver 1676336721 (Feb 13)

May 2023 -- I'm having the same exact problem. Not sure how to fix it!

**Comment by ShizCalev** [comment] 2023-06-26 12:55
There appears to have been a regression, this issue is occuring again.

**Comment by shanjii** [comment] 2023-07-19 23:54
Can confirm there seems to be a regression, same issue happening with me again.

**Comment by kisak-valve** [comment] 2023-07-19 23:56
Hello @ShizCalev, @shanjii, can one of you please open a new issue report so that this more recent regression can be tracked properly?
