### ISSUE TITLE
just follow xdg, thats all we ask

### ISSUE THREAD

**Issue by digitalwtf** [ValveSoftware/steam-for-linux#8634] opened 2022-06-16 21:30 UTC
#### Your system information

* Steam client version (build number or date): Jun 7. 2022 at 03:18:43
* Distribution (e.g. Ubuntu): Arch Linux x86_64
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

We dont need more junk in our $HOME.
We should have the option of disabling the ~/.steam folder as some of us can run games without it.

Please.

#### Steps for reproducing this issue:

bruh just something like this (copy of #1890)

if (set(XDG_DATA_HOME)) {
 dir=$XDG_DATA_HOME/Valve/Steam
} else {
 dir=$HOME/.local/share/Valve/Steam
}

1. Valve
2. Please
3. Fix

**Comment by kisak-valve** [comment] 2022-06-16 21:34
Hello @digitalwtf, please do not intentionally open duplicate issue reports. Closing as a duplicate of #1890.

**Closed by kisak-valve** 2022-06-16 21:34 UTC

**Comment by digitalwtf** [comment] 2022-06-16 21:35
@kisak-valve this issue is approaching 10 years of age, there is nothing done about it at all.

**Comment by wael444** [comment] 2022-06-30 00:22
so steam devs are aware of this being an issue it sems

**Comment by PureTryOut** [comment] 2022-07-03 12:44
@wael444 don't be confused like I was, @kisak-valve is not a Steam dev and them knowing about the issue doesn't mean Valve knows about it. But seeing the age of the original issue, they probably _do_ know about it and just don't care about it.
