### ISSUE TITLE
Steam fails to log in after a force reboot of PC

### ISSUE THREAD

**Issue by Tannenfels** [ValveSoftware/steam-for-linux#11218] opened 2024-08-29 16:07 UTC
#### Your system information

* Steam client version (build number or date): latest from apt-get
* Distribution (e.g. Ubuntu): Ubuntu 22.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16801941/steam-logs.tar.gz)

* GPU: Nvidia GTX 3070

#### Please describe your issue in as much detail as possible:
I was playing a game and then it stuck, so I had to manually reboot my PC. After rebooting, Steam log in stucks in endless loop. Reinstalling steam did not help

#### Steps for reproducing this issue:

1. Force reboot PC
2. Steam is unable to log in

P.S. Is there a way to remove my steam user data from my system, so the next time it will try clean log in?

**Comment by Rosentti** [comment] 2024-08-29 16:11
Duplicate of #11216. You also have `m_VecAddressWebSocketCMs.Count()` present in the console-llinux file.

**Comment by kisak-valve** [comment] 2024-08-29 16:16
Hello @Tannenfels, as @Rosentti noted, this issue is already being tracked at #11216. Closing as a duplicate.

**Closed by kisak-valve** 2024-08-29 16:16 UTC

**Comment by mahlersand** [comment] 2024-08-29 16:20
@Tannenfels regarding your P.S., you can reset the entire steam runtime using `steam-runtime --reset` / `steam --reset`, depending on how you start it. That also resets the downloaded runtime libraries too, though. If you have fast internet, that is usually not a problem.
