### ISSUE TITLE
Steam instacrash when I click on PLAY on any supported or unsupported "Steam Play" games

### ISSUE THREAD

**Issue by DestroyFX** [ValveSoftware/steam-for-linux#5669] opened 2018-08-24 18:35 UTC
**#### Your system information**

* Steam client version 1535062307
* Distribution (e.g. Ubuntu): Gentoo, Kernel 4.18, AMDGPU Video stack from yesterday Git, LLVM 8
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
**What should append:**
When I click on a game, a popup should open asking me if I want to run it.

**What did append:**
When I click on supported "Windows" games for Steam Play, I see a windows popup but it instacrash and I can't read the popup. The crash is from Steam before I have the chance to try to run the game.

Running Steam on gentoo 1.0.0.54-r4 64-bit
STEAM_RUNTIME is enabled by the user
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
[0824/095235.248091:WARNING:crash_reporting.cc(254)] Failed to set crash key: UserID with value: 0
[0824/095235.248133:WARNING:crash_reporting.cc(254)] Failed to set crash key: BuildID with value: 1535053639
[0824/095235.248137:WARNING:crash_reporting.cc(254)] Failed to set crash key: SteamUniverse with value: Public
[0824/095235.248140:WARNING:crash_reporting.cc(254)] Failed to set crash key: Version with value: 1535053639
[0824/095235.248142:WARNING:crash_reporting.cc(254)] Failed to set crash key: ProductName with value: cefwebhelper
[0824/095235.248145:WARNING:crash_reporting.cc(254)] Failed to set crash key: Vendor with value: Valve
[0824/095235.305959:ERROR:gpu_process_transport_factory.cc(1029)] Lost UI shared context.
html_chrome.cpp (394) : Assertion Failed: CefCrashReportingEnabled()
[0824/095235.347877:WARNING:crash_reporting.cc(254)] Failed to set crash key: SteamUniverse with value: Dev
[0824/095235.348237:WARNING:crash_reporting.cc(254)] Failed to set crash key: UserID with value: 0
[0824/095235.348246:WARNING:crash_reporting.cc(254)] Failed to set crash key: BuildID with value: 1535062307
[0824/095235.348249:WARNING:crash_reporting.cc(254)] Failed to set crash key: SteamUniverse with value: Public
[0824/095235.348253:WARNING:crash_reporting.cc(254)] Failed to set crash key: Version with value: 1535062307
[0824/095235.348257:WARNING:crash_reporting.cc(254)] Failed to set crash key: ProductName with value: cefwebhelper
[0824/095235.348261:WARNING:crash_reporting.cc(254)] Failed to set crash key: Vendor with value: Valve
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
CAppInfoCacheReadFromDiskThread took 76 milliseconds to initialize
CApplicationManagerPopulateThread took 210 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Found unsupported CDM version 1.4.9.1088, using last known good version 1.4.8.1008
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB
Installing breakpad exception handler for appid(steam)/version(1535062307)

(steam:14356): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
roaming config store loaded successfully - 2231 bytes.
migrating temporary roaming config store
Installing breakpad exception handler for appid(steam)/version(1535062307)
[0824/095253.546987:WARNING:crash_reporting.cc(254)] Failed to set crash key: UserID with value: 0
[0824/095253.547067:WARNING:crash_reporting.cc(254)] Failed to set crash key: BuildID with value: 1535053639
[0824/095253.547072:WARNING:crash_reporting.cc(254)] Failed to set crash key: SteamUniverse with value: Public
[0824/095253.547077:WARNING:crash_reporting.cc(254)] Failed to set crash key: Version with value: 1535053639
[0824/095253.547082:WARNING:crash_reporting.cc(254)] Failed to set crash key: ProductName with value: cefwebhelper
[0824/095253.547087:WARNING:crash_reporting.cc(254)] Failed to set crash key: Vendor with value: Valve
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Failed to init SteamVR because it isn't installed
ExecCommandLine: "'/mnt/extend/destroyfx/Steam/ubuntu12_32/steam'"
System startup time: 19.66 seconds
Generating new string page texture 81: 1024x256, total string texture memory is 1.36 MB
Generating new string page texture 82: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 83: 128x256, total string texture memory is 1.49 MB
Generating new string page texture 84: 64x256, total string texture memory is 1.56 MB
Generating new string page texture 85: 32x256, total string texture memory is 1.59 MB
Generating new string page texture 90: 128x256, total string texture memory is 1.72 MB
Generating new string page texture 91: 256x256, total string texture memory is 1.98 MB
Generating new string page texture 93: 128x256, total string texture memory is 2.11 MB
Generating new string page texture 94: 384x256, total string texture memory is 2.51 MB
Generating new string page texture 97: 256x256, total string texture memory is 2.77 MB
JS method call WebChat.GetWebChatLanguage with 1 arguments
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call WebChat.GetSignIntoFriendsOnStart with 1 arguments
JS method call WebChat.GetCurrentUserAccountID with 1 arguments
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call WebChat.GetWebChatURL with 1 arguments
Generating new string page texture 102: 8x256, total string texture memory is 2.78 MB
Generating new string page texture 136: 48x256, total string texture memory is 2.83 MB
JS method call FriendSettings.RegisterForSettingsChanges with 1 arguments
JS method call WebChat.RegisterForPushToTalkStateChange with 1 arguments
JS method call WebChat.GetPushToTalkEnabled with 1 arguments
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call WebChat.RegisterForComputerActiveStateChange with 1 arguments
JS method call SharedConnection.AllocateSharedConnection with 1 arguments
JS method call WebChat.RegisterOverlayChatBrowserInfoChanged with 1 arguments
JS method call FriendSettings.GetEnabledFeatures with 1 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.RegisterOnLogonInfoChanged with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
JS method call Parental.RegisterForParentalSettingsChanges with 1 arguments
JS method call Broadcast.RegisterForBroadcastStatus with 1 arguments
JS method call Broadcast.RegisterForViewerRequests with 1 arguments
JS method call SharedConnection.RegisterOnMessageReceived with 2 arguments
JS method call SharedConnection.SendMsg with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsg with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsg with 2 arguments
JS method call WebChat.BSuppressPopupsInRestore with 1 arguments
JS method call SharedConnection.SendMsg with 2 arguments
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Generating new string page texture 143: 64x256, total string texture memory is 2.89 MB
Generating new string page texture 157: 128x256, total string texture memory is 3.02 MB
[0824/095325.497964:WARNING:spdy_session.cc(2921)] Received HEADERS for invalid stream 155
[0824/095325.764587:WARNING:spdy_session.cc(2921)] Received HEADERS for invalid stream 163
[0824/095325.832743:WARNING:spdy_session.cc(2921)] Received HEADERS for invalid stream 159
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
[0824/100013.495023:WARNING:render_frame_host_impl.cc(2751)] OnDidStopLoading was called twice.
ExecuteSteamURL: "steam://subscriptioninstall/97032"
Generating new string page texture 170: 512x256, total string texture memory is 3.55 MB
GameAction [AppID 275850, ActionID 1] : InstallApps waiting for user response to ShowEula "http://store.steampowered.com//eula/275850_eula_0"
GameAction [AppID 275850, ActionID 1] : InstallApps continues with user response "ShowEula"
GameAction [AppID 275850, ActionID 1] : InstallApps changed task to CreateNextApp with ""
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
Generating new string page texture 173: 256x256, total string texture memory is 393.22 KB
Generating new string page texture 176: 256x256, total string texture memory is 3.81 MB
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
GameAction [AppID 275850, ActionID 1] : InstallApps changed task to RemoveGameDemos with ""
GameAction [AppID 275850, ActionID 1] : InstallApps changed task to CreateSystemEntries with ""
GameAction [AppID 275850, ActionID 1] : InstallApps changed task to AutoLaunch with ""
GameAction [AppID 275850, ActionID 1] : InstallApps changed task to Complete with ""
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
ExecuteSteamURL: "steam://open/downloads"
Generating new string page texture 253: 128x256, total string texture memory is 3.94 MB
Generating new string page texture 254: 64x256, total string texture memory is 4.01 MB
Generating new string page texture 257: 128x256, total string texture memory is 4.14 MB
Installing breakpad exception handler for appid(steam)/version(1535062307)
JS method call SharedConnection.SendMsg with 2 arguments
JS method call SharedConnection.SendMsg with 2 arguments
Installing breakpad exception handler for appid(steam)/version(1535062307)
Installing breakpad exception handler for appid(steam)/version(1535062307)
JS method call SharedConnection.SendMsg with 2 arguments
JS method call SharedConnection.SendMsg with 2 arguments
JS method call SharedConnection.SendMsg with 2 arguments
JS method call SharedConnection.SendMsg with 2 arguments
JS method call SharedConnection.SendMsg with 2 arguments
JS method call SharedConnection.SendMsg with 2 arguments
Generating new string page texture 264: 128x256, total string texture memory is 4.27 MB
GameAction [AppID 275850, ActionID 2] : LaunchApp changed task to ShowSteamPlayWarning with ""
GameAction [AppID 275850, ActionID 2] : LaunchApp waiting for user response to ShowSteamPlayWarning ""
**Failed to open digital audio driver No mixer services exist.** _<-could it be that?_
crash_20180824095231_1.dmp[20973]: Uploading dump (out-of-process)
/tmp/dumps/crash_20180824095231_1.dmp
/mnt/extend/destroyfx/Steam/steam.sh: line 876: 14356 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
html_chrome.cpp (394) : Assertion Failed: CefCrashReportingEnabled()
crash_20180824095231_1.dmp[20973]: Finished uploading minidump (out-of-process): success = yes
crash_20180824095231_1.dmp[20973]: response: CrashID=bp-c649dbe6-eefe-47f6-b643-c66f42180824
crash_20180824095231_1.dmp[20973]: file ''/tmp/dumps/crash_20180824095231_1.dmp'', upload yes: ''CrashID=bp-c649dbe6-eefe-47f6-b643-c66f42180824''

#### Steps for reproducing this issue:

1. run steam
2. click on a Steam Play game like No man sky or Stalker
3. click play

**Comment by DestroyFX** [comment] 2018-08-24 18:38
Google drive link for the crash dump
https://drive.google.com/open?id=1HdXgUAlZ-6vVQ39SqmFF-Z1slCzfkBZp

**Comment by DestroyFX** [comment] 2018-08-24 18:56
I did notice that in the dmesg:

steam[14356]: segfault at 0 ip 00000000ee8f7bd9 sp 00000000ffd64ea0 error 4 in vgui2_s.so[ee85a000+299000]
[833016.416549] Code: 74 03 00 00 00 00 00 00 c7 44 24 08 02 00 00 00 c7 44 24 04 10 00 00 00 c7 04 24 44 ac 00 00 e8 ad 3f fb ff 89 86 74 03 00 00 <8b> 00 8b 78 10 e8 8d 18 fb ff 8b 86 74 03 00 00 dd 5c 24 04 89 04 
[833190.039743] CApplicationMan[21495]: segfault at 1 ip 00000000f79b450a sp 00000000df1fe2c0 error 4 in libc-2.27.so[f792f000+1ec000]

**Comment by kisak-valve** [comment] 2018-08-24 19:09
For reference, the attached minidump is a DUMP_REQUESTED in crashhandler.so.

**Comment by pcfreak30** [comment] 2018-08-26 09:56
#5634 same issue

**Comment by digulla** [comment] 2018-09-20 08:00
Same happens on openSUSE Leap 15.0. Can someone update the tags?

**Comment by DestroyFX** [comment] 2018-09-20 15:05
@kisak-valve It's not openSuse related. it's related to Linux in General. Steam have some 32Bit parts and 32Bits code can't properly handle **inode64**. The proper fix would be to get rig of all 32bits parts. More time will pass, more filesystem will use 64 bits inodes (at lease new one). Even ext4 can do it sometime.

@digulla Let me guess, You have some XFS partitions? I did posted a "possibly data-eating" workaround in #5634. If your games and steam are in a section of the hdd that is accessible by a 32bit then yes, it should work fine but if your disk is quite full, I would advice again trying that.

**Comment by DestroyFX** [comment] 2018-09-20 15:09
@kisak-valve Description of the problem : https://www.tcm.phy.cam.ac.uk/sw/inodes64.html

@digulla Workaround to use at your own risk, also : https://www.tcm.phy.cam.ac.uk/sw/inodes64.html

You get the inode64.so and you run steam from a sh script with :
LD_PRELOAD=${LD_PRELOAD:+${LD_PRELOAD}:}/usr/lib32/inode64.so steam

**Comment by digulla** [comment] 2018-09-20 18:40
@DestroyFX Thanks for the info. I'll try to create a small test partition to see if that works.

**Comment by tomaszg7** [comment] 2018-09-20 19:01
Generally this issue can have many causes. In my case it turn out it was due to the lack of access to ALSA devices. User was not a member of `audio` group and adding it solved the problem. Weird that such an issue would crash Steam.

**Comment by kisak-valve** [comment] 2020-11-13 14:00
Closing as a duplicate of #5634.

**Closed by kisak-valve** 2020-11-13 14:00 UTC
Labels: Proton, Steam client
