### ISSUE TITLE
Steam linux client becomes unresponsive after some time

### ISSUE THREAD

**Issue by Hrafnsmerki** [ValveSoftware/steam-for-linux#3637] opened 2014-12-19 11:59 UTC
Steam linux client becomes unresponsive after some time. It may be after watching video on the client or now, when the main store windows has animated title.

**Comment by rbrs** [comment] 2015-01-01 11:08
I am experiencing the same problem.

System details:
```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3201 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    elementary OS Freya (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-40-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Mutter(Gala)
    Steam Runtime Version:  steam-runtime-release_2014-08-20
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 770/PCIe/SSE2

    Driver Version:  4.4.0 NVIDIA 340.65
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1184
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1200
    Desktop Resolution: 1920 x 1200
    Primary Display Size: 20,39" x 12,76"  (24,02" diag)
                                            51,8cm x 32,4cm  (61,0cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Intel PantherPoint HDMI
    
Memory:
    RAM:  7880 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  104588 Mb
    Largest Free Hard Disk Block:  22081 Mb
    
Installed software:
    
Recent Failure Reports:
    
```

This is how it looks in action: http://i.imgur.com/v3PzFrX.gifv

**Comment by who-me** [comment] 2015-02-21 14:20
Does this happen with the 346.35 driver?

**Comment by kamjau** [comment] 2015-02-25 01:52
I upgraded to that a few weeks ago and haven't seen it happen since then, but i haven't used Steam much since then either. I'll post if it happens again.

**Comment by kisak-valve** [comment] 2018-05-18 14:06
Hello, is anyone still experiencing this issue on an up to date system?

Note: Xorg-server 1.20 users may be seeing #5480.

**Comment by kisak-valve** [comment] 2018-05-20 13:41
Hello @Silur, if your issue is a very recent regression, then it's unlikely to be related to this issue from 2014 / 2015.

**Comment by kisak-valve** [comment] 2018-06-22 13:50
Closing as the original issue appears to have been resolved some time ago. The newer regression mentioned was a poor interaction between xorg server 1.20 and mesa which was resolved by https://patchwork.freedesktop.org/patch/223324/.

**Closed by kisak-valve** 2018-06-22 13:50 UTC
Labels: Need Retest, Steam client, reviewed
