### ISSUE TITLE
SELinux blocks sounds for TF2

### ISSUE THREAD

**Issue by acerspyro** [ValveSoftware/steam-for-linux#4185] opened 2015-12-15 22:37 UTC
A lot of voices are blocked by SELinux in TF2 on Fedora 23.

**Comment by Tele42** [comment] 2015-12-16 00:17
This is a duplicate of #43, the miles audio middleware uses execheap.

**Comment by gdrewb-valve** [comment] 2015-12-16 04:57
Closing duplicate.

**Closed by gdrewb-valve** 2015-12-16 04:57 UTC
Labels: duplicate, reviewed
