### ISSUE TITLE
High cpu usage on idle

### ISSUE THREAD

**Issue by zany130** [ValveSoftware/steam-for-linux#7673] opened 2021-02-24 22:17 UTC
#### Your system information
* Steam client version (build number or date): https://gist.github.com/zany130/1578d604dbc8267a5419b32e90d3967f
* Distribution (e.g. Ubuntu): Fedora 33
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Very High CPU usage just having steam open doing nothing
Expect little to no CPU usage on steam idle
#### Steps for reproducing this issue:

1. open steam
2. ensure no downloads or shaders are being cached by disabling it
3. observe high CPU usage

**Comment by kisak-valve** [comment] 2021-02-24 22:27
Hello @zany130, can you identify what threads are using more resources than you expected? See https://github.com/ValveSoftware/steam-for-linux/issues/7372#issuecomment-696193644 for some instructions on collecting that kind of info.

**Comment by zany130** [comment] 2021-02-24 22:39
![steam](https://user-images.githubusercontent.com/25832539/109075098-aba12900-76c6-11eb-8712-a4b8af21acff.png)
 it just says its ```/home/zany130/.local/share/Steam/ubuntu12_32/steam```
 however, remove all music folders and disabling music scanning on startup fixed the issue so maybe it's a duplicate of that?

**Comment by kisak-valve** [comment] 2021-02-24 22:59
Gnome's system monitor doesn't give thread names, but yes, from the symptoms you've described, this is a duplicate of #7372. Closing in favor of the older issue report.

**Closed by kisak-valve** 2021-02-24 22:59 UTC
Labels: Need More Information, Steam client
