### ISSUE TITLE
TF2 "Server list" dialog doesn't remember its size

### ISSUE THREAD

**Issue by epitron** [ValveSoftware/steam-for-linux#2739] opened 2013-07-26 05:36 UTC
The TF2 server list is always in its default "way too small" state when I first launch the game; its size and position are forgotten between loads.

**Comment by kisak-valve** [comment] 2017-08-25 22:09
Closing as a duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/75.

**Closed by kisak-valve** 2017-08-25 22:09 UTC
Labels: MOVED: Team Fortress 2, reviewed
