### ISSUE TITLE
Steam Store displays and recommends non-Linux games while on Linux

### ISSUE THREAD

**Issue by aaronfranke** [ValveSoftware/steam-for-linux#4631] opened 2016-09-21 22:15 UTC
#### Your system information

* Steam client version: 1473798563 (however, this affects all versions of the Steam client, as well as the website viewed through any web browser)
* Distribution (e.g. Ubuntu): Xubuntu (Ubuntu with XFCE) 16.04 LTS 64-bit
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Imgur album describing the problem: https://imgur.com/a/2f1iQ

Reddit thread: https://www.reddit.com/r/linux_gaming/comments/53pk9u/the_biggest_problem_imo_with_steam_and_linux/

The Steam Store displays and recommends non-Linux games while on Linux, regardless of whether or not you have SteamOS + Linux checked on [this page](https://store.steampowered.com/account/preferences).

The point is that it's completely unacceptable to display games on a store when the user cannot play them. All you're going to do is anger Linux users who purchase a Windows-only game by accident. The solution is to stop displaying these unrunnable games to people who don't have the required OS, by checking for the Steam client's reported OS or the browser's user agent string.

#### Steps for reproducing this issue:

1. Open Steam on Linux or the Steam website
2. Go to the Store
3. See Windows-only titles on the Store
4. See Windows-only titles in the Discovery queue

**Comment by gdrewb-valve** [comment] 2016-09-21 22:59
Duplicate of several issues, such as #3999.

**Closed by gdrewb-valve** 2016-09-21 22:59 UTC
