### ISSUE TITLE
Steam Crashes When Clicking on Specific Game's "Properties" Option 

### ISSUE THREAD

**Issue by nutta-git** [ValveSoftware/steam-for-linux#6940] opened 2020-03-02 01:17 UTC
#### Your system information

* Steam client version (build number or date): 02/21/2020
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When using Steam Properties on Steam Client for Warframe (https://store.steampowered.com/app/230410/Warframe/), Steam crashes. 
Journalctl: 
```
Mar 01 20:23:21 nutta.butta assert_20200301202251_1.dmp[7616]: Uploading dump (out-of-process)
                                                               /tmp/dumps/assert_20200301202251_1.dmp
Mar 01 20:23:21 nutta.butta kernel: steam[7149]: segfault at 0 ip 00000000f7a1be3e sp 00000000ff88634c error 4 in libc-2.30.so[f79ad000+128000]
Mar 01 20:23:21 nutta.butta kernel: Code: 38 d5 74 e2 40 c1 e9 10 84 c9 74 05 38 d1 74 d6 40 5f c3 66 90 66 90 66 90 66 90 90 f3 0f 1e fb 8b 4c 24 04 8b 54 24 08 8a 01 <3a> 02 75 09 41 42 84 c0 75 f4 31 c0 c3 b8 01 00 00 00 b9 ff ff ff
Mar 01 20:23:21 nutta.butta systemd[1]: Started Process Core Dump (PID 7617/UID 0).
Mar 01 20:23:21 nutta.butta audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@5-7617-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal>
Mar 01 20:23:22 nutta.butta kwin_x11[2015]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 5199, resource id: 52428843, major code: 15 (QueryTree), minor code: 0
Mar 01 20:23:22 nutta.butta systemd-coredump[7618]: Process 7149 (steam) of user 1000 dumped core.
                                                    
                                                    Stack trace of thread 7149:
                                                    #0  0x00000000f7a1be3e strcmp (libc.so.6)
                                                    #1  0x00000000e0bd4e7a n/a (/home/nutta/.local/share/Steam/ubuntu12_32/steamui.so)
                                                    #2  0x00000000e0bd5983 n/a (/home/nutta/.local/share/Steam/ubuntu12_32/steamui.so)
                                                    #3  0x00000000e0bb9a67 n/a (/home/nutta/.local/share/Steam/ubuntu12_32/steamui.so)
                                                    #4  0x00000000e0bbd33e n/a (/home/nutta/.local/share/Steam/ubuntu12_32/steamui.so)
                                                    #5  0x00000000e0bba819 n/a (/home/nutta/.local/share/Steam/ubuntu12_32/steamui.so)
                                                    #6  0x00000000e11cca50 n/a (/home/nutta/.local/share/Steam/ubuntu12_32/steamui.so)
                                                    #7  0x00000000ea788db8 n/a (/home/nutta/.local/share/Steam/ubuntu12_32/chromehtml.so)
Mar 01 20:23:23 nutta.butta systemd[1]: systemd-coredump@5-7617-0.service: Succeeded.
Mar 01 20:23:23 nutta.butta audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@5-7617-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=>
Mar 01 20:23:23 nutta.butta systemd[1]: systemd-coredump@5-7617-0.service: Consumed 1.091s CPU time.
Mar 01 20:23:24 nutta.butta assert_20200301202251_1.dmp[7616]: Finished uploading minidump (out-of-process): success = yes
Mar 01 20:23:24 nutta.butta assert_20200301202251_1.dmp[7616]: response: CrashID=bp-41ccc5ef-7230-4df4-af51-5b8602200301
Mar 01 20:23:24 nutta.butta kwin_x11[2015]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 5867, resource id: 35651843, major code: 18 (ChangeProperty), minor code: 0

```
dmesg: 
```
[   57.334458] steam[2462]: segfault at 0 ip 00000000f7a36e3e sp 00000000ffdcd93c error 4 in libc-2.30.so[f79c8000+128000]
[   57.334462] Code: 38 d5 74 e2 40 c1 e9 10 84 c9 74 05 38 d1 74 d6 40 5f c3 66 90 66 90 66 90 66 90 90 f3 0f 1e fb 8b 4c 24 04 8b 54 24 08 8a 01 <3a> 02 75 09 41 42 84 c0 75 f4 31 c0 c3 b8 01 00 00 00 b9 ff ff ff
[  243.987877] steam[3468]: segfault at 0 ip 00000000f79c5e3e sp 00000000ff9b9dbc error 4 in libc-2.30.so[f7957000+128000]
[  243.987881] Code: 38 d5 74 e2 40 c1 e9 10 84 c9 74 05 38 d1 74 d6 40 5f c3 66 90 66 90 66 90 66 90 90 f3 0f 1e fb 8b 4c 24 04 8b 54 24 08 8a 01 <3a> 02 75 09 41 42 84 c0 75 f4 31 c0 c3 b8 01 00 00 00 b9 ff ff ff
[  659.448520] steam[4936]: segfault at 0 ip 00000000f7a26e3e sp 00000000ff93035c error 4 in libc-2.30.so[f79b8000+128000]
[  659.448524] Code: 38 d5 74 e2 40 c1 e9 10 84 c9 74 05 38 d1 74 d6 40 5f c3 66 90 66 90 66 90 66 90 90 f3 0f 1e fb 8b 4c 24 04 8b 54 24 08 8a 01 <3a> 02 75 09 41 42 84 c0 75 f4 31 c0 c3 b8 01 00 00 00 b9 ff ff ff
[  768.319069] steam[5697]: segfault at 0 ip 00000000f7972e3e sp 00000000fff3892c error 4 in libc-2.30.so[f7904000+128000]
[  768.319074] Code: 38 d5 74 e2 40 c1 e9 10 84 c9 74 05 38 d1 74 d6 40 5f c3 66 90 66 90 66 90 66 90 90 f3 0f 1e fb 8b 4c 24 04 8b 54 24 08 8a 01 <3a> 02 75 09 41 42 84 c0 75 f4 31 c0 c3 b8 01 00 00 00 b9 ff ff ff
[  808.394482] steam[6326]: segfault at 0 ip 00000000f7a48e3e sp 00000000ffcdffbc error 4 in libc-2.30.so[f79da000+128000]
[  808.394486] Code: 38 d5 74 e2 40 c1 e9 10 84 c9 74 05 38 d1 74 d6 40 5f c3 66 90 66 90 66 90 66 90 90 f3 0f 1e fb 8b 4c 24 04 8b 54 24 08 8a 01 <3a> 02 75 09 41 42 84 c0 75 f4 31 c0 c3 b8 01 00 00 00 b9 ff ff ff
[ 1102.917531] steam[7149]: segfault at 0 ip 00000000f7a1be3e sp 00000000ff88634c error 4 in libc-2.30.so[f79ad000+128000]
[ 1102.917536] Code: 38 d5 74 e2 40 c1 e9 10 84 c9 74 05 38 d1 74 d6 40 5f c3 66 90 66 90 66 90 66 90 90 f3 0f 1e fb 8b 4c 24 04 8b 54 24 08 8a 01 <3a> 02 75 09 41 42 84 c0 75 f4 31 c0 c3 b8 01 00 00 00 b9 ff ff ff

```

#### Steps for reproducing this issue:

1. Open Steam Beta Client 
2. Right Click Warframe
3. Select Properties 

This ONLY happens with Warframe, Clicking on properties on other games works fine.

**Comment by kisak-valve** [comment] 2020-03-02 01:41
Hello @nutta-git, this is most likely a duplicate of #6757. Can you check if putting the Steam client into offline mode avoids the crash?

**Comment by nutta-git** [comment] 2020-03-02 01:44
Starting In off-line mode does fix the issue

**Comment by kisak-valve** [comment] 2020-03-02 01:51
Thanks, closing as a duplicate of #6757.

**Closed by kisak-valve** 2020-03-02 01:51 UTC
Labels: Distro Family: Fedora, Steam client
