### ISSUE TITLE
[Dungeons of Dredmor] Sound issues for a short period after launching game.

### ISSUE THREAD

**Issue by IanWitham** [ValveSoftware/steam-for-linux#1829] opened 2013-02-16 06:24 UTC
Music has a kind of crackly distorted static in the background for about a minute after launching the game. After that the sound seems to come right again.

That seems to be unrelated to what I'm doing in the game, or even whether I've started playing a level yet. The sound just comes right again regardless.

[System Information](https://gist.github.com/IanWitham/1ea44b2009b38fff07b0)

**Comment by kparal** [comment] 2015-09-24 22:14
Seems to be solved by renaming/deleting `Dungeons of Dredmor/x86/libopenal.so.1`. I wonder why they bundle that library when it is bundled in Steam SDK (and apparently a better working version).

**Comment by Managor** [comment] 2024-04-01 02:55
@kisak-valve I left Dungeons of Dreadmor running for 30 minutes and was not able to reproduce the issue. It has probably been fixed along the years so this can be closed.

**Comment by kisak-valve** [comment] 2024-05-03 22:33
Closing per the last comment.

**Closed by kisak-valve** 2024-05-03 22:33 UTC
Labels: reviewed, 3rd party game, Need Retest
