### ISSUE TITLE
Windows other than the main client window are now grouped under separate "steamwebhelper" window

### ISSUE THREAD

**Issue by tearoww** [ValveSoftware/steam-for-linux#9235] opened 2023-02-24 09:05 UTC
#### Your system information

* Steam client version (build number or date): package versions: 1677204767
* Distribution (e.g. Ubuntu): Manjaro KDE
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Before a Steam client beta update this month, Steam has had all of its windows under the same "Steam (Runtime)" window in KDE's Task Manager (taskbar).
After the update windows other than the main client window are grouped under a separate "steamwebhelper" window.

The problem does not occur if I opt out of the Steam client beta, but reappears if I opt in again.

[System Information](https://gist.github.com/tearoww/efbec82f43fc84c56b06925ee9418137)

#### Steps for reproducing this issue:

1. Open the Steam Beta Client
2. Open a separate window, e.g. Friends List

**Comment by NoXPhasma** [comment] 2023-03-02 14:11
Same happens on Cinnamon Desktop.

**Comment by tearoww** [comment] 2023-03-15 07:53
This is now fixed on my system after update 1678845529.

**Comment by NoXPhasma** [comment] 2023-03-15 07:57
I can confirm, latest beta fixed it.

**Comment by NoXPhasma** [comment] 2023-03-20 10:47
While it's fixed for the chat/friendlist/settings windows, other windows still are separated. Some of the windows which are still separated are game properties, single screenshot viewer, DLC manager, Storage Manager and probably a few more which I didn't encounter yet.

Could you open this issue again @tearoww

**Comment by tearoww** [comment] 2023-03-20 11:16
> While it's fixed for the chat/friendlist/settings windows, other windows still are separated. Some of the windows which are still separated are game properties, single screenshot viewer, DLC manager, Storage Manager and probably a few more which I didn't encounter yet.
> 
> Could you open this issue again @tearoww

This appears to also be the case on my system.

**Comment by OhaDerErste** [comment] 2023-04-10 23:05
Still happens on my system on stable and beta 1680827821

**Comment by Munoida** [comment] 2023-05-03 17:48
Seems to be fixed for me now.
![image](https://user-images.githubusercontent.com/84733553/236001688-761f8196-5a07-4752-93e7-664b38d672be.png)

**Comment by NoXPhasma** [comment] 2023-05-03 18:51
I can confirm, with Steam beta all windows are grouped under one icon.

**Comment by Visne** [comment] 2023-06-09 12:43
This was broken again since the last comment but has been fixed since this morning (see #9551 and [this beta update](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3651903168569436963))

**Comment by kisak-valve** [comment] 2023-07-22 01:06
Closing as fixed in the [2023-06-14](https://store.steampowered.com/oldnews/195171) Steam client update.

**Closed by kisak-valve** 2023-07-22 01:06 UTC
Labels: Steam client, Window manager
