### ISSUE TITLE
Double ‘B’ Button press required to exit game on gaming mode (Steam Deck)

### ISSUE THREAD

**Issue by anyoneyun** [ValveSoftware/steam-for-linux#10183] opened 2023-10-31 22:30 UTC
Hi, as the title says, when exiting a game and returning to the game page on game mode, Steam requires pressing two times the B button to return to the home screen (the first is registered with a sound but does nothing).
This was also shared on reddit, here:
https://www.reddit.com/r/SteamDeck/comments/17i9mle/need_to_press_b_twice_after_closing_game/

I’m on the latest SteamOS version, latest stable Steam version.

Update: this also happens on my desktop computer in Big Picture mode (Manjaro Linux, latest stable Steam client)

**Comment by anyoneyun** [comment] 2024-01-11 23:16
Any news about this? I get it's a small issue but I thought it would also be easy to solve! Let me know if you need some other info!

**Comment by Managor** [comment] 2024-04-27 05:34
This has been fixed in the latest beta

**Comment by Managor** [comment] 2024-04-27 14:03
Also this is a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/10253

**Comment by anyoneyun** [comment] 2024-05-23 08:55
Closed as it has been fixed

**Closed** 2024-05-23 08:54 UTC
Labels: Steam client, Need Retest, Distro Family: SteamOS
