### ISSUE TITLE
Limit number of recent games in tray icon

### ISSUE THREAD

**Issue by rgiyf** [ValveSoftware/steam-for-linux#4295] opened 2016-02-03 15:47 UTC
Please limit number of recent games in tray like maybe to 5 games. For example how it looks like now:
![menu_001](https://cloud.githubusercontent.com/assets/9195693/12787307/edcd7dc4-caa5-11e5-985c-dc37788242bc.jpg)
And I didn't play all of this games recently.
On windowst:
![2016-02-03_18-37-14](https://cloud.githubusercontent.com/assets/9195693/12787383/401a48aa-caa6-11e5-8773-aac9eb6c9faf.png)

**Comment by malysps** [comment] 2016-09-11 22:25
+1

I have 20 games in my Steam indicator menu. It's ridiculously long. Most of them isn't even installed any more. Please add an option to disable that list, clear it or at least limit it to 5 games.

Maybe it's stored somewhere in the _~/.steam_ folder? In that case please tell me where so I could brake it... I mean fix it by myself.

**Comment by Tyrsen** [comment] 2016-09-11 22:40
+1
if it didn't show uninstalled games i wouldn't care how long it was, but seriously, that's incredibly annoying

**Comment by kisak-valve** [comment] 2017-10-13 17:07
Closing as a duplicate of #3037

**Closed by kisak-valve** 2017-10-13 17:07 UTC
Labels: reviewed
