### ISSUE TITLE
Steam now tries to access kwallet at startup

### ISSUE THREAD

**Issue by moozaad** [ValveSoftware/steam-for-linux#6588] opened 2019-10-16 09:53 UTC
#### Your system information

* Steam client version (build number or date): 1571182697
* Distribution (e.g. Ubuntu): opensuse-tumbleweed 20191007 64-bit
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
At startup Steam now tries to access the kwallet.

![image](https://user-images.githubusercontent.com/7650192/66908232-a0ce8280-f002-11e9-8a5f-1e6ac72eca1f.png)

I can't think of a reason for Steam to need access to kwallet as no relevant credentials are stored there unless Valve is planning to "remember" creds there.

#### Steps for reproducing this issue:

1. start steam

**Comment by Leopard1907** [comment] 2019-10-16 10:17
https://github.com/ValveSoftware/steam-for-linux/issues/6585

I think root cause of those issues is the same.

**Comment by kisak-valve** [comment] 2019-10-16 12:32
Hello @moozaad, as @Leopard1907 noted this issue is already being tracked at #6585. Closing as a duplicate.

**Closed by kisak-valve** 2019-10-16 12:32 UTC
