### ISSUE TITLE
Steam unresponsive, steamwebhelper using 100% CPU

### ISSUE THREAD

**Issue by klarkc** [ValveSoftware/steam-for-linux#3514] opened 2014-09-26 14:39 UTC
Steps to reproduce:

1 - Open Steam Client (BP or Normal mode) in a user session
2 - Open another Steam Client in any other user session

What Happens:

The second client turns extremely slow, the steamwebhelper process was using 100% CPU all the time.

Observations:

1 - Even if you close the first client, the problem remains
2 - All the time the first client run flawless, even if you close everything and open user session again.

System Information:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3801 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-36-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2014-08-20

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 660 Ti/PCIe/SSE2

    Driver Version:  4.4.0 NVIDIA 331.38
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1183
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1600 x 900
    Desktop Resolution: 1600 x 900
    Primary Display Size: 17,44" x 9,80"  (20,00" diag)
                                            44,3cm x 24,9cm  (50,8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  7932 Mb

Miscellaneous:
    UI Language:  English
    LANG:  pt_BR.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  78616 Mb
    Largest Free Hard Disk Block:  56723 Mb

Installed software:

Recent Failure Reports:

```

Steam Log: https://gist.github.com/klarkc/6a139209f36aa3d2da56

**Comment by OlliC** [comment] 2015-02-06 18:22
Had the same problem just now. 

Steps to reproduce:
1. Create a new user
2. Logout the current user
3. Login as the new user
4. Start steam

It downloads and installs the runtime, etc. After that 100% CPU and a unresponsive Login GUI.

What helped: 

1. Delete /tmp/steam_chrome_shmem
2. Reboot

Just deleting steam_chrome_shmem was not enough. Got the same problem. Only a reboot helped. Maybe because of some other files in /tmp that got deleted on reboot.

**Comment by Plagman** [comment] 2015-02-06 19:18
Are you opted in the Beta?

**Comment by OlliC** [comment] 2015-02-06 20:30
Nope. No Beta.

**Comment by Plagman** [comment] 2015-02-06 20:46
Can you try opting into the beta? This should have the filename change and a fix for the hangs.

**Comment by OlliC** [comment] 2015-02-06 20:59
Ok. Its in Beta now and this seems to be fixed there.

Regular steam client: steam_chrome_shmem
Beta steam client: steam_chrome_shmem_gaming_spid2314

**Comment by kisak-valve** [comment] 2018-04-06 13:58
Closing as fixed some time ago.

**Closed by kisak-valve** 2018-04-06 13:58 UTC
Labels: reviewed

**Comment by olefasting** [comment] 2022-01-04 18:12
I'm still having this issue today, on Ubuntu.
It makes cpu-intensive games unplayable on my system, unless I use cputool to set the load allowance to something low, like 1%, for the steamwebhelper pid group.

As I found this issue while googling a different issue with the steam client, I just figured I'd post the above fix, for anyone else stumbling over this through google etc.

**Comment by sbrl** [comment] 2022-05-22 13:48
This is still a problem with the latest version of steam on Ubuntu 22.04 Jammy Jellyfish.
