### ISSUE TITLE
[minor issue][ubuntu 13.10][linux] menus disappear when the mouse is moving

### ISSUE THREAD

**Issue by Wabuo** [ValveSoftware/steam-for-linux#3253] opened 2014-04-14 20:44 UTC
platform: ubuntu 13.10 64bit
steam for linux latest ver.

how to reproduce the issue:
-start steam client 
-use any menu like "games"
-the menu will disappears before you are able to click on any entry

**Comment by kisak-valve** [comment] 2017-12-01 14:40
Closing as a duplicate of #6.

**Closed by kisak-valve** 2017-12-01 14:40 UTC
Labels: reviewed, Steam client
