### ISSUE TITLE
cannot install on external hard disk (no exec permission even if I have them)

### ISSUE THREAD

**Issue by portaloffreedom** [ValveSoftware/steam-for-linux#3812] opened 2015-04-25 09:42 UTC
The issue is that I cannot install my games on the external hard drive any more. The hard drive is NTFS formatted, and mounted with executable permissions. Still, all of a sudden all the games installed there disappeard (they are uninstalled now) and I cannot install anything any more on that disk. I receive this error message (more or less this, it's translated from Italian): "The new folder of the steam library must be on a filesystem mounted with executable permissions".

Now, the disk is INDEED mounted with executable permissions. I even tried to create a stupid executable there and execute it, and it's working.

This is the mount output for that disk:
```
/dev/sdb1 on /run/media/matteo/Pointer Poing type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,group_id=0,allow_other,blksize=4096,uhelper=udisks2)
```

NB:
- The drive is mounted on a path where there is a space, so that could be an issue.
- The drive is mounted with ntfs-3g on fuse, and is using a usermapping file to have personalized permission for any file/folder.

**Comment by htto** [comment] 2015-04-25 12:18
I have a similar problem (steam client beta), if I want to add a folder "X", that was previously already a steam library folder and thus has the directory "SteamApps" in there. Trying to add "X" also fails with the execute permission message and the console detail:
`sh: /X/steamapps/.steam_exec_test.sh: No such file or directory`

If I rename the contained folder "SteamApps" to "steamapps", the client recognizes the folder and the installed games.

So I guess this is some sort of case-sensitivity issue, where "SteamApps" is accepted for a known steam folder (because it doesn't trigger the folder must be empty message), but not used for the executable test?

@portaloffreedom: Does renaming the "SteamApp" folder to the lowercase version restore things?

**Comment by portaloffreedom** [comment] 2015-04-25 13:24
@htto OMG yes! Renaming the "SteamApp" folder to the lowercase version does indeed fix the issue for me! Thanks! :D

Still, I wouln't say this issue is solved

**Comment by Plaque-fcc** [comment] 2015-04-25 14:55
This issue ain't resolved. It's a duplicate of those like #3777 and
#3679, at least.

**Comment by gdrewb-valve** [comment] 2015-04-27 19:27
Duplicate of #3649.

**Closed by gdrewb-valve** 2015-04-27 19:27 UTC
Labels: duplicate, reviewed

**Comment by JamesHealdUK** [comment] 2018-11-18 21:29
This issue is still (unfortunately) alive and well.
