### ISSUE TITLE
Offline mode breaks Aperture Desk Job and other titles on Steam Deck after a reboot

### ISSUE THREAD

**Issue by psymin** [ValveSoftware/steam-for-linux#8721] opened 2022-08-04 20:24 UTC
#### Your system information

* Steam client version (build number or date): Built: Jul 30 2022, at 04:09:05  Steam package versions: 1659369000
* Distribution (e.g. Ubuntu): SteamOS Holo (64 bit)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Many games, including Aperture Desk Job, fail to launch properly on the Steam Deck in offline mode after the most recent update, v3.3.

They will work properly in Online mode.  They will continue to work in offline mode until the device is rebooted, then they will fail.

In desktop mode and offline mode after a reboot, Aperture Desk Job returns this error:

"An error occurred while updating Aperture Desk Job (compatibility tool configuration failed)"

It provides the following link in the error window:
https://help.steampowered.com/en/faqs/view/21F5-8D5D-0141-7A5E

In gaming mode it just returns immediately to the Steam Deck UI to launch the game.

#### Steps for reproducing this issue:

1. Update the Steam Deck to the latest stable OS (3.3)
2. Install Aperture Desk Job.
3. Launch Aperture Desk Job once.
4. Enable Offline mode.
5. Reboot the Steam Deck
6. Attempt to launch Aperture Desk Job

**Comment by ZereoX** [comment] 2024-07-15 13:08
Hi @psymin,

I have been unable to reproduce the issue you reported above on the latest Stable SteamOS release (3.5.19) with both the Native and Windows versions of Aperture Desk Job (1902490). In all instances the title launched without issue after the device was rebooted in Offline mode (and no internet).

Would you be able to confirm if this is still an issue that is affecting you with Aperture Desk Job or any other titles?

Thanks.

**Comment by kisak-valve** [comment] 2024-08-16 20:34
Closing pending feedback.

**Closed by kisak-valve** 2024-08-16 20:34 UTC
Labels: Steam client, Need Retest, Distro Family: SteamOS
