### ISSUE TITLE
Notification rendering issue

### ISSUE THREAD

**Issue by muvor** [ValveSoftware/steam-for-linux#6267] opened 2019-05-12 20:47 UTC
#### Your system information

* Steam client version (build number or date): May 2 2019
* Distribution (e.g. Ubuntu): Manjaro Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
The pop-up notifications don't render correctly anymore since the steam friends UI update, they became unreadably dark.
In je first half a second the notification fades in it has the correct brightness, but when it stops sliding it becomes very dark and not readable anymore.

#### Steps for reproducing this issue:

1. Receive notification (either that someone launched a game or that someone maessaged you)
2. The notification slides in and is readable, when it stops sliding it becomes very dark
3. The notification slides out again (still dark)

**Comment by kisak-valve** [comment] 2019-05-12 21:13
Hello @muvor, this reads like #4735. Can you check if the example in that issue report matches your experience and does mousing over the notification have an effect?

**Comment by muvor** [comment] 2019-05-12 21:23
I seem to have glossed over this issue in the issue list. The issues match mostly, the only difference is that when I hover over the notification, nothing happens, but only when I click it, it returns to normal (but slides back down again).

**Comment by kisak-valve** [comment] 2019-05-12 22:02
Thanks for checking, it wasn't particularly easy for me to find either. Let's track this issue with the existing report. Feel free to add your experience to it.

Closing as a duplicate of #4735.

**Closed by kisak-valve** 2019-05-12 22:02 UTC
Labels: Steam client
