### ISSUE TITLE
Feral Gamemode awareness

### ISSUE THREAD

**Issue by X6205** [ValveSoftware/steam-for-linux#7126] opened 2020-05-23 14:29 UTC
Hi,

I have this idea/suggestion for Steam client on linux..

Since some linux distros are shipping pre-installed Feral Gamemode (like Ubuntu 20.04) my suggestion is to make Steam linux client aware of installed Gamemode and enable it automatically when user have launched a game. It could be done by appending silently launch option "gamemoderun %command%" to game when is launched. After exiting a game it should also disable gamemode. This is propably not something dificult to implement, since Steam client is already tracking if game is running or not what is visible also in library.

If you think this is bad place to write here such feature requests, i am sorry and please delete this ticket.

**Comment by kisak-valve** [comment] 2020-05-23 14:38
Hello @X6205, silently adding gamemoderun is a bad idea because there's a minor chance of complications preventing games from starting. Manually adding it would make this request a duplicate of #3453, which is the main part of this feature request.

Closing as a duplicate of #3453.

**Closed by kisak-valve** 2020-05-23 14:38 UTC
