### ISSUE TITLE
Steam refuses to exit

### ISSUE THREAD

**Issue by stevenroose** [ValveSoftware/steam-for-linux#5926] opened 2018-11-28 23:03 UTC
#### Your system information

* Steam client version (build number or date): (can't copy this)
![screenshot-2018-11-28-22-36-30](https://user-images.githubusercontent.com/853468/49186913-c9537c80-f35d-11e8-9e42-844d867b22ec.png)
Arch package `steam-1.0.0.56-1`
System Information: https://gist.github.com/stevenroose/1fb78734c34f3a5cb8ee6296b0e38270#file-system-information-txt

* Distribution: Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam refuses to shut down. I have to sigkill it (2 different processes) to have it stop. Could be related to https://github.com/ValveSoftware/steam-for-linux/issues/5925.

stderr and stdout log while running and exiting:
https://gist.github.com/stevenroose/1fb78734c34f3a5cb8ee6296b0e38270#file-steam-log

#### Steps for reproducing this issue:

1. Install Steam on Arch.
2. Launch Steam.
3. Try to use the File > Exit option.

Steam window disappears, but processes stay running. Tray icon also stays.

**Comment by dearlygparted** [comment] 2019-01-24 00:20
I am unable to reproduce the issue. Has it been solved?

**Comment by kisak-valve** [comment] 2021-04-16 17:25
Hello @stevenroose, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment] 2021-05-28 17:21
Closing pending feedback.

**Closed by kisak-valve** 2021-05-28 17:21 UTC
Labels: Distro Family: Arch, Need Retest, Steam client
