### ISSUE TITLE
Alt+F4 does not behave as expected when using STEAM_FRAME_FORCE_CLOSE=1

### ISSUE THREAD

**Issue by gracicot** [ValveSoftware/steam-for-linux#3056] opened 2013-12-23 05:28 UTC
Hi. I use steam On KDE 4.11. I tried the option STEAM_FRAME_FORCE_CLOSE=1 to make steam minimize to tray when closing. When clicking on the close button on steam, it work like a charm. And then I tried to close it by Alt + F4 or by the window Manager (example: expo) it shutdown steam. It should minimize to tray, like any other applications do or when you press the close button.

**Comment by cmeeren** [comment] 2016-07-25 21:41
Second this. I expected Alt-F4 to minimize the window, same as clicking the close button (which I absolutely never do anyway; I always use Alt-F4). I wondered why Steam was closing on me all the time until I suspected that Alt-F4 might not behave the same way as the close button. Please implement this! :)

**Comment by Narthorn** [comment] 2016-10-15 08:37
Thirded. Killing the window should have the same behavior as clicking the close button.

**Comment by mpottage** [comment] 2017-08-27 17:30
Me too. In Windows Alt-F4 behaves the same as the close button. Should the shell icon fail using the Windows task-manager is required. Why the special behaviour for Linux? There are equivalents to the task manager on Linux.

**Comment by mvrozanti** [comment] 2017-10-14 16:21
Just moved over to Linux and things are great except these small things really bug me though.

**Comment by Thermi** [comment] 2018-12-08 16:55
Quinted. It's annoying when I accidently quit steam because I hit alt+f4 like with all my other windows.

**Comment by Rodancoci** [comment] 2020-06-18 03:40
I am also experiencing this behavior in GNOME 3.36. Many other apps that have a tray icon (i.e. Discord, Telegram Desktop) close the window keep running in the background the tray icon.
Closing the Steam window by clicking on the close button works as expected and leaves an icon in the tray.

Alt+F4 fully closes Steam, however.

**Comment by LeSnake04** [comment] 2020-11-22 16:48
I also would expect Alt f4 to minimize steam to tray, just like in windows....

**Comment by codeman101** [comment] 2020-11-22 23:03
Why is the kotkey to exit steam Alt+F4 instead of Ctrl+q? It doesn't seem like Ctrl+q is bound to anything else in client as far as I can tell.

**Comment by Rodancoci** [comment] 2020-11-23 01:33
Seems to me the standard is for alt+f4 to close windows (and where applicable leave the app running with a tray icon) whereas ctrl+q outright quits the application.

I often accidentally quit Steam by pressing alt+f4 because I keep expecting it to close to the tray instead of quitting entirely

**Comment by poison64** [comment] 2021-03-09 14:07
over 7 years later this error still bugs me :( I'm on Ubuntu 20.04...

**Comment by Jimi-James** [comment] 2021-12-26 20:02
Why is this still not fixed, anyway???

**Comment by InvisibleRain** [comment] 2022-09-11 13:57
@ValveSoftware, please fix

**Comment by JaneSmith** [comment] 2022-09-12 20:50
Still an issue nine years later. I find this very frustrating, as I often do it by accident when I Alt+F4 with the wrong window focused. For example, I mean to Alt+F4 my authenticator app after logging into something, but Steam was actually focused (difficult to tell as Steam doesn't seem to change appearance at all to indicate whether it's focused or unfocused). As a result, Steam then closes out entirely, and I have to waste time waiting for it to fully exit, then launch it again and get set back up.

**Comment by metov** [comment] 2023-04-19 04:22
This problem also happens with i3. I have a key bound to `kill`, and when I use that on the Steam window, it terminates all Steam processes. I would have expected it to do the same thing as when I press the `X` button: Only close the window, but leave the tray running, as well as any Steam games.

This can be reproduced by running `i3-msg '[title="Steam"]' kill` in a terminal, which should close all windows with the title `Steam`. Don't do this if you have another program running, also called Steam, which is doing something important like controlling the steam flow of your nuclear reactor.

I looked at https://i3wm.org/docs/userguide.html and found this:

>If an application does not provide a mechanism for closing (most applications provide a menu, the escape key or a shortcut like Control+w to close), you can press $mod+Shift+q to kill a window. For applications which support the WM_DELETE protocol, this will correctly close the application (saving any modifications or doing other cleanup). If the application doesn’t support the WM_DELETE protocol your X server will kill the window and the behaviour depends on the application.

So it looks like this `WM_DELETE` is the key thing here. I'm guessing other WM/DE also send `WM_DELETE` on Alt+F4. The last bit about X killing the window sounds about right.

Perhaps the solution is to implement this `WM_DELETE` on Linux?

I've been using i3 for quite some time, and Steam is the first program I've seen that has this behavior. For everything else, i3 `kill` does the same thing as the `X` button. For example:

* If I open a new window of Firefox, `kill` will only close that window, not the entire Firefox.
* If I open ckb-next, `kill` will only close the main window, but leave it running as tray.

In i3 at least, it is possible to define special commands for specific windows. Is there any command or signal at all that can be used to close the main Steam window, without exiting Steam itself (the tray)? I could configure i3 to send this command, instead of `kill`, when I use the regular close key on a Steam window. This doesn't help people on other WM/DE though.

**Comment by metov** [comment] 2023-04-19 04:25
Also, @gdrewb-valve above, many years ago (lol), said:

>This is expected behavior as STEAM_FRAME_FORCE_CLOSE only affects the close box. We deliberately exit steam on Alt+F4 of the last window to handle cases where the tray doesn't work. We could add a new environment variable to control Alt+F4 behavior so leaving this open as a feature request.

Sounds like he's saying they could add an envar, and when I set this, Alt+F4 on Steam's window will no longer exit Steam. That sounds like a reasonable solution, but there's a bunch of :-1: on it. :shrug:

**Comment by KotoWhiskas** [comment] 2023-04-28 14:02
I can no longer reproduce it on the latest steam beta update.

@kisak-valve I think it's finally a time to close this issue!

**Comment by Narthorn** [comment] 2023-04-28 14:49
Indeed, it seems fixed in the new beta client.

**Comment by DrymarchonShaun** [comment] 2023-05-21 08:20
I also can no longer reproduce on the newest beta update. 

Does this UI update mean we're heading in the direction of native Wayland support as well?

**Comment by kisak-valve** [comment] 2023-06-30 23:53
Closing per the last several comment.

**Closed by kisak-valve** 2023-06-30 23:53 UTC
Labels: Feature Request, reviewed, Steam client, Need Retest
