### ISSUE TITLE
steam remote play shows black screen but has audio

### ISSUE THREAD

**Issue by greenalden** [ValveSoftware/steam-for-linux#7153] opened 2020-05-31 23:15 UTC
AMD a6 laptop 8gb ddr3 ram

* Steam client version don't know but most recent version as of posting this
* Distribution Ubuntu 20.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. just installed steam and tried to do remote play with a friend (I was not the host)
2. 
3.

**Comment by TomokoK** [comment] 2020-06-01 22:22
Can you enable stream details and check if you are using VAAPI? I'm wondering if this is a duplicate of #7150

**Comment by kisak-valve** [comment] 2022-12-09 20:16
Closing due to a lack of feedback.

**Closed by kisak-valve** 2022-12-09 20:16 UTC
Labels: Streaming
