### ISSUE TITLE
steam.sh: line 710: LD_LIBRARY_PATH: unbound variable | the return of the unbound LD_LIBRARY_PATH usage

### ISSUE THREAD

**Issue by Oxalin** [ValveSoftware/steam-for-linux#4447] opened 2016-05-11 06:19 UTC
Using Archlinux 64 bit.

With today's beta client, when launching steam.sh, it fails with:
steam.sh: line 710: LD_LIBRARY_PATH: unbound variable

Line 710 reads as follow:
export LD_LIBRARY_PATH="$STEAMROOT/$PLATFORM:$STEAMROOT/$PLATFORM/panorama:$LD_LIBRARY_PATH"

As uncountered before, $LD_LIBRARY_PATH should be replaced by ${LD_LIBRARY_PATH-} as used elsewhere in case LD_LIBRARY_PATH is indeed undefined. Line 710 should then be:
LD_LIBRARY_PATH="$STEAMROOT/$PLATFORM:$STEAMROOT/$PLATFORM/panorama:${LD_LIBRARY_PATH-}"

**Comment by RyuzakiKK** [comment] 2016-05-11 17:45
I use arch linux and had the same problem. Solved with ${LD_LIBRARY_PATH-}

**Comment by Plagman** [comment] 2016-05-11 18:08
This'll be fixed in the next Beta update. Looks like this might be specific to running without the Steam Runtime enabled, as otherwise LD_LIBRARY_PATH gets set earlier in the script.

**Comment by RyuzakiKK** [comment] 2016-05-11 19:05
Yes, I forgot to say that I run steam with the runtime disabled.

**Comment by mralext20** [comment] 2016-05-11 19:21
> This'll be fixed in the next Beta update. Looks like this might be specific to running without the Steam Runtime enabled, as otherwise LD_LIBRARY_PATH gets set earlier in the script.

when do you say the next beta will be released?

**Comment by Plagman** [comment] 2016-05-12 01:21
This is released now.

**Closed by Plagman** 2016-05-12 01:21 UTC
Labels: reviewed

**Comment by John-Gee** [comment] 2016-05-12 03:22
I can confirm that the new client worked, though I had to set LD_LIBRARY_PATH first to load the previous to upgrade itself.. and then it works setting the variable.
