### ISSUE TITLE
Dualshock 4 controllers disconnect and reconnect after roughly 5 minutes of gameplay

### ISSUE THREAD

**Issue by CygnusTerminal** [ValveSoftware/steam-for-linux#7608] opened 2021-01-16 12:59 UTC
#### Your system information

* Steam client version (build number or date): Jan 14, 2021, at 00:10:17
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Since 1/2 months ago, i am having issues with Steam and my DS4 controllers. The issue is only affecting Steam, and only Proton games as far as i can tell. Native games and other clients/emulators do not have this issue, and it is also affecting my Kubuntu installation. USB ports/controllers are not at fault, the have been thoroughly tested. This issue would occur after roughly 5 minutes into the game, the controller light would change from white to blue, as if it was disabled, and then go back white, usually leaving the game with no controller functionality. This also happens to my new DS4 controller i bought a few days ago.

#### Steps for reproducing this issue:

1. Connect the controller.
2. Start a Proton game.
3. Play with the controller.
4. The controller shows the issue.

**Comment by kisak-valve** [comment] 2021-01-16 13:08
Hello @CygnusTerminal, please do no intentionally open duplicate issue reports. Closing as a duplicate of #7405.

**Closed by kisak-valve** 2021-01-16 13:08 UTC
