### ISSUE TITLE
Export clip menu uses wrong kind of save dialog

### ISSUE THREAD

**Issue by iodream** [ValveSoftware/steam-for-linux#11027] opened 2024-06-26 21:54 UTC
#### Your system information

* Steam client version (build number or date): 1719420706
* Distribution (e.g. Ubuntu): Arch linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/15996319/steam-logs.tar.gz)
* GPU: intel hd 3000
* Desktop environment: Kde Plasma 6.1
* Session: X11

#### Please describe your issue in as much detail as possible:
On Kde Plasma X11, in the new gameplay clip recording beta, if you try to export the clip to an MP4 Steam will try to launch a Qt open dialog but this doesn't make sense as we are saving a file and entering a path and name where to save it. Instead, Steam wants us to open something and we can't export the clip.

#### Steps for reproducing this issue:

1. Record a short gameplay clip
2. Go to View -> Recording & Screenshots
3. Open the recording
4. Click Share -> Export video file

Observed result: Steam opens a Qt open file dialog. Errors pop up with any file name that's entered.
Expected result: Steam opens a save file dialog where a proper path and name can be entered.

![Screenshot_20240627_004446](https://github.com/ValveSoftware/steam-for-linux/assets/42720874/04ea6119-3066-42bb-8392-019bfdc198fd)

**Comment by tlneondo** [comment] 2024-06-26 22:19
Same here, tried to "touch example.mp4" and it caused things to just fail

**Comment by kisak-valve** [comment] 2024-06-26 22:23
Possible duplicate of #6698.

**Comment by iodream** [comment] 2024-06-27 00:15
> Same here, tried to "touch example.mp4" and it caused things to just fail

This workaround actually worked for me, thanks. I've found there's a small delay before the file's contents will be fully written to disk so maybe you opened it a bit prematurely.

**Comment by kisak-valve** [comment] 2024-06-27 00:27
That's a fairly strong hint that this is the same issue as the older issue report.

Closing in favor of #6698.

**Closed by kisak-valve** 2024-06-27 00:27 UTC
Labels: Steam client
