### ISSUE TITLE
Steam fails to validate integrity if home folder is encrypted

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4761] opened 2016-12-17 20:53 UTC
#### Your system information

* Steam client version: 
Built: Dec 9 2016, at 20:41:34
Steam API: v017
Steam package versions: 1481318740
* Distribution (e.g. Ubuntu): Linux Mint 17.3 64-bit and Linux Mint 18 64-bit
* Opted into Steam client beta?: Tried both, latest normal and beta client
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
First i was using Linux Mint 17.3 64-bit and i noticed that everytime i did a fresh installation of the game Verdun, and then i verified the integrity, steam always fails and put in download a tons of data multiple times. Sometimes after even 10 downloads it managed to not fail, except that after first crash or any issue the loop started again, and again. This happened after the game released updates too.
I tried with beta version of steam but had the same issue. 
Same issue happened to Chivalry: Medieval Warfare. 
I tried couple of others videogames that are little size and they gave me no problems (don't know why).
I tried then to move my steam library to a non-encrypted folder, verified integrity, it may failed once and downloaded less than 50mb of data, but after that it worked perfectly.

I moved from Mint 17.3 to 18 (always 64 bit), this time i didn't put any encryption. Installed steam (not beta), downloaded the game, verified integrity, all fine.

My specs while using mint 17.3: http://pastebin.com/ApzZ9KF8
Mint 18: http://pastebin.com/YaZRpdF1

#### Steps for reproducing this issue:

1. Install Linux Mint with encrypted home folder.
2. Download games from steam.
3. After fresh installation and/or any game's update verify integrity of game cache.

**Comment by kisak-valve** [comment] 2016-12-18 02:19
Most likely a duplicate of #4752.

**Comment by kisak-valve** [comment] 2019-10-25 12:59
Closing because the reporting user has turned into a ghost and it appears similar issues from around this time were resolved.

**Closed by kisak-valve** 2019-10-25 12:59 UTC
Labels: reviewed
