### ISSUE TITLE
Hiding all non-essential popups (cards, achievements, friends, etc) WITHOUT disabling Steam Overlay

### ISSUE THREAD

**Issue by ItsRogueRen** [ValveSoftware/steam-for-linux#9477] opened 2023-05-08 15:26 UTC
The Steam Deck has an option to hide all non-essential popups, which is a feature that has been requested on the desktop for almost a decade with 0 response. I'm making a new issue in hopes someone will see this since the existing issue seems to be buried and completely ignored.

You can hide all popups by disabling the Steam Overlay, but this has the drawback of also disabling all controller support for some bizarre reason. We need to have one of the following:

A) the same feature as Deck UI for hiding all popups in the regular desktop client, or

B) controller input to not be tied to the Steam Overlay, so users who don't want any interruptions while playing can disable to overlay but still use a controller.

Using the Deck UI is not a solution, AFAIK Deck UI is still broken on Nvidia GPUs.

**Comment by kisak-valve** [comment] 2023-05-08 15:40
Hello @ItsRogueRen, please do not intentionally open duplicate issue reports. Closing as a duplicate of #3239.

**Closed by kisak-valve** 2023-05-08 15:40 UTC

**Comment by ItsRogueRen** [comment] 2023-05-08 17:01
This is not a duplicate of the original issue as that was a bug in the overlay with Unity games, but more so what the comments of that issue evolved into that never got around to ever making an actual issue for it.
