### ISSUE TITLE
Steam attempting to write an executable script into non-library directories

### ISSUE THREAD

**Issue by davidebeatrici** [ValveSoftware/steam-for-linux#8666] opened 2022-07-03 01:50 UTC
#### Your system information

* Steam client version (build number or date): Jun 7 2022, at 03:18:43
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

```
statvfs64: ret -1 errno 13
  f_bsize : 0
  f_frsize: 0
  f_blocks: 0
  f_bfree : 0
  f_bavail: 0
src/tier1/fileio.cpp (3855) : Assertion Failed: statvfs64 failed for /boot/efi, errno 13
src/tier1/fileio.cpp (3855) : Assertion Failed: statvfs64 failed for /boot/efi, errno 13
Execute: /home/user/.steam/debian-installation/ubuntu12_64/disk-free /boot/efi >/tmp/disk-free.LDY4Sc
realpath errno 13
src/tier1/fileio.cpp (3886) : disk-free command failed

src/tier1/fileio.cpp (3886) : disk-free command failed

Couldn't write /boot/efi/.steam_exec_test.sh: Permission denied
Couldn't write /media/games_2/.steam_exec_test.sh: Permission denied
statvfs64: ret -1 errno 2
  f_bsize : 0
  f_frsize: 0
  f_blocks: 0
  f_bfree : 0
  f_bavail: 0
src/tier1/fileio.cpp (3855) : Assertion Failed: statvfs64 failed for /media/data, errno 2
src/tier1/fileio.cpp (3855) : Assertion Failed: statvfs64 failed for /media/data, errno 2
Execute: /home/user/.steam/debian-installation/ubuntu12_64/disk-free /media/data >/tmp/disk-free.UZii6g
realpath errno 2
src/tier1/fileio.cpp (3886) : disk-free command failed

src/tier1/fileio.cpp (3886) : disk-free command failed

Couldn't write /media/data/.steam_exec_test.sh: No such file or directory
Couldn't write /media/games_1/.steam_exec_test.sh: Permission denied
Couldn't write /etc/.steam_exec_test.sh: Permission denied
Couldn't write /etc/.steam_exec_test.sh: Permission denied
Couldn't write /var/.steam_exec_test.sh: Permission denied
Couldn't write /var/.steam_exec_test.sh: Permission denied
sh: 1: /home/user/.steam_exec_test.sh: Permission denied
Failed system("/home/user/.steam_exec_test.sh") in execute test: 32256
```

I have a Steam library at `/media/games_1/SteamLibrary` and `/media/games_2/SteamLibrary`.

#### Steps for reproducing this issue:

I noticed the console output after [Independence War 2: Edge of Chaos](https://store.steampowered.com/app/359630/Independence_War_2_Edge_of_Chaos) crashed.

Steam was running through firejail.

**Comment by kisak-valve** [comment] 2022-07-03 01:57
Hello @davidebeatrici, this is functionally a duplicate of #8026. Closing in favor of the older issue report.

**Closed by kisak-valve** 2022-07-03 01:57 UTC
Labels: Steam client

**Comment by davidebeatrici** [comment] 2022-07-03 02:23
Oh, sorry, I just realized it's trying to access all mount points.
