### ISSUE TITLE
Eternal Return fails negotiating with Valve servers

### ISSUE THREAD

**Issue by errorforever** [ValveSoftware/steam-for-linux#7675] opened 2021-02-26 02:41 UTC
#### Your system information

* Steam client version (build number or date): Feb 24 2021
* Distribution (e.g. Ubuntu): Arch (Fresh install. Linux and linux-zen kernels tried.)
* Opted into Steam client beta?: [Yes/No] Yes (Tried non beta also.)
* Have you checked for system updates?: [Yes/No] Yes

Protons tried: Experimental (as of Feb 24), 5.13-6, 5.13-5, 5.0-10, 4.11-13, 6.1-GE-2

#### Please describe your issue in as much detail as possible:
Eternal Return: Black Survival connects to _Valve_ hosting or routing servers. Fails.
Cannot connect to game servers. Go to server menu, see "Unable to confirm" next to each server, "Cannot find a server. Please check your internet connection." No other networking or multiplayer issues on machine. After title screen, tcpdump shows the game connecting via udp to Valve machines, mostly in Europe (I am on US East Coast), before always settling at the same site near Wichita Kansas, with an unknown ownership, 143.131.179.64. For the final 4.5-5.0 seconds of udp activity, my machine sends 100 byte packets to this site, the site sends 39 byte responses, every time. No further udp activity. UPnP, TCPv6, firewalls, port forwarding, NAT assignment, DNS choice do not effect failure of connection to Valve / Eternal Return servers.

#### Steps for reproducing this issue:

1. Start game
2. Monitor udp connections
3. Check server menu for connection, or play first tutorial until completion (fails upon final task completion, syncing to servers)
4. No connection, no ping, for any server

**Comment by kisak-valve** [comment] 2021-02-26 03:01
Hello @errorforever, please do not intentionally open duplicate issue reports. Closing as a duplicate of https://github.com/ValveSoftware/Proton/issues/4653.

**Closed by kisak-valve** 2021-02-26 03:01 UTC
