### ISSUE TITLE
steamwebhelper crashes with symbol lookup error

### ISSUE THREAD

**Issue by SergeiFranco** [ValveSoftware/steam-for-linux#4965] opened 2017-05-12 04:42 UTC
* Steam client version (build number or date):  
    `Built: May 11 2017, at 00:07:39`
    `Steam API: v017`
    `Steam package versions: 1494464423`

* Distribution (e.g. Ubuntu):  kUbuntu 14.04 LTS 64bit
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

The symptom:
   All steamwebhelper areas are blank, eg: Store, Community, Profile, News pop-up etc.

The troubleshooting:
  When launching from command line the following is spat out when trying to visit Store:
`chrome_ipc_client.cpp (112) : Assertion Failed: GenerateCEFLogFileName in unknown process
./steamwebhelper: symbol lookup error: ./steamwebhelper: undefined symbol: SDL_SetWindowHitTest`

Running `steam --reset` does not resolve the issue.

System information:
distro: `kUbuntu 14.04 LTS 64bit`
kernel: `3.13.0-117-generic #164-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux`
video card: `GeForce GTX 1080 (nvidia driver version: 375.66)`

#### Steps for reproducing this issue:

1.  Launch steam in Ubuntu 14.04 LTS 64bit
2.  Click on Store
3.  See a blank page

**Comment by brendemar** [comment] 2017-05-12 11:10
hello. i have same exact problem on same ubuntu version.
./steamwebhelper: symbol lookup error: ./steamwebhelper: undefined symbol: SDL_SetWindowHitTest
chrome_ipc_client.cpp (112) : Assertion Failed: GenerateCEFLogFileName in unknown process

**Comment by kisak-valve** [comment] 2017-05-12 13:21
Hello @SergeiFranco, this issue is already being tracked at #4951. Closing as a duplicate.

**Comment by kisak-valve** [comment] 2017-05-19 23:14
@pclose commented on 2017-05-11T18:36:04

I have the same behavior occuring, with a different error message. [steam.sh.log.zip](https://github.com/ValveSoftware/steam-for-linux/files/994081/steam.sh.log.zip). Just started since a build this weekend.

    chrome_ipc_client.cpp (112) : Assertion Failed: GenerateCEFLogFileName in unknown process
    ./steamwebhelper: symbol lookup error: ./steamwebhelper: undefined symbol: SDL_SetWindowHitTest
***
@SergeiFranco commented on 2017-05-13T00:32:52

Just got new update and problem is still there with Build date `May 12 2017, at 23:46:20`...
***
@ardje commented on 2017-05-19T08:34:11

Since 19 may I got the SDL_SetWindowHitTest lookup error on steamos stable. I think I can leverage my problem by not using the steamos libs:
steam@steamos:~$ strings -a /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.2.0|grep SDL_SetWindowHit
steam@steamos:~$ strings -a .local/share/Steam/ubuntu12_32/libSDL2-2.0.so.0|grep SDL_SetWindowHit
SDL_SetWindowHitTest
SDL_SetWindowHitTest
steam@steamos:~$ dpkg -l libsdl2-2.0-0|tail -1
ii  libsdl2-2.0-0:amd64 2.0.2+dfsg1-6+bsos1 amd64        Simple DirectMedia Layer

I must confess that I upgraded my system with 381.09 nvidia drivers using normal debian methods, but that should not break this.

EDIT: I meant steamos testing.
***
@kisak-valve commented on 2017-05-19T23:00:09

@NotMrFlibble posted on 2017-05-19T22:43:14 at #4983:

Steam client build no.: 1495155850
Running on SteamOS brewmaster + jessie-backports (for use with current Mesa)

This pair of messages is repeatedly being output on the terminal:
```
chrome_ipc_client.cpp (112) : Assertion Failed: GenerateCEFLogFileName in unknown process
./steamwebhelper: symbol lookup error: ./steamwebhelper: undefined symbol: SDL_SetWindowHitTest
```
Running with STEAM_RUNTIME=1 does not help. Moving the system libSDL2-2.0.so.0 out of the way works around the issue. Upgrading should fix it, but that would require pulling in packages from Debian stretch (which may be problematic regarding pulling in other packages) or locally recompiling.

***

From this hint, running steam from a terminal with `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` may workaround this issue

**Comment by kisak-valve** [comment] 2017-05-19 23:19
This issue is steam using the system variant of SDL2 and that variant being older than 2.0.4.

It should be noted that the system variant of SDL is not installed on a stock install of SteamOS, and thus not affected.

**Comment by NotMrFlibble** [comment] 2017-05-19 23:22
Confirming that `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` works.

**Comment by ardje** [comment] 2017-05-22 12:11
Hi Kisak,
Good to hear it's not a problem with a default install on steamos. But be aware that this version is the version from steamos:
 *** 2.0.2+dfsg1-6+bsos1 0
        900 http://repo.steampowered.com/steamos/ brewmaster/main amd64 Packages
(also for brewmaster beta). So anything an advanced user or a tinkering user installs using apt-get will pull in that version.

**Comment by kisak-valve** [comment] 2017-05-24 00:24
Closing per "Fixed web component not working on certain distributions if host libraries were preferred" in the [2017-05-23] steam beta client update.

Also confirmed fixed with testing @ardje's scenario.

**Closed by kisak-valve** 2017-05-24 00:24 UTC
Labels: Distro Family: Debian, Distro Family: SteamOS, Distro Family: Ubuntu, runtime, Steam client
