### ISSUE TITLE
Proton / compatibility tools UI could be improved

### ISSUE THREAD

**Issue by fallenguru** [ValveSoftware/steam-for-linux#7619] opened 2021-01-23 14:05 UTC
#### Your system information

* Steam client version (build number or date): Jan 22, 2021
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
*This has some overlap with other feature requests, apologies if it's an outright dupe.*

I recently noticed that I had a bunch of old Proton versions installed which I wasn't (consciously) using any more. For some, this worked, others just threw a generic error. Google revealed that that was probably due to a game still using them. Fair enough.
So now I went through all my installed games to check whether I'd set a custom Proton version somewhere and forgotten about it. I had not. It turns out that "whitelisted" games will use a different default Proton version from the one configured globally. Again, makes sense. Only now I was reduced to selecting each game manually, clicking the info button, and checking the Proton version manually ... that's terrible UI/UX.

A side effect is that from the game configuration dialogue's compatibility tab(!), you can't even tell if a compatibility tool is in use, which one, and why (unless manually overridden).

I won't presume to tell you *how* to make it better, but amending the uninstallation error message to say: "<compatibility tool> is still in use by <...>" would be a good start.
In the long run I'd also like more information about the used compatibility tool and version prominently shown, e.g. in the game configuration dialogue under compatibility it should show, for instance "using Proton x-yy-z …[Valve default]" (meaning whitelisted), "... [user default]", or "... [manually configured for this game by you]". Ideally, I'd like to have this info on the library view, too, and not buried behind an info button.

**Comment by kisak-valve** [comment] 2021-01-23 14:16
Hello @fallenguru, this issue is already being tracked at #7407.

Closing as a duplicate of #7407 / #7618.

**Closed by kisak-valve** 2021-01-23 14:16 UTC
