### ISSUE TITLE
Overlay features are not functional in Steam Client Beta:  Web pages, Profiles, Friends Tab, etc

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/steam-for-linux#5541] opened 2018-06-24 03:49 UTC
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Xubuntu 18.04
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

https://gist.github.com/nightsky30/4c7eeb46844357cdb90c13f350e7c36e

#### Please describe your issue in as much detail as possible:
I cannot open other players' profiles from within the Borderlands 2 game client using the Steam Client Overlay.  The overlay's web browser fails to load anything.

Seems similar to #4957, #5026, #5045, ValveSoftware/csgo-osx-linux#1432, ValveSoftware/csgo-osx-linux#1433, ValveSoftware/csgo-osx-linux#1434, ValveSoftware/Dota-2#1247, ValveSoftware/csgo-osx-linux#1441, 

#### Steps for reproducing this issue:

1. Start Borderlands 2
2. Have ppl join your game
3. Attempt to view their profile by using esc to get to the menu
4. Select the player
5. Select view profile
6. Overlay web browser fails to load profile page

**Comment by conrev** [comment] 2018-06-26 10:38
I can also confirm this issue, on my case, none of the overlay features work for the current beta. This includes loading web pages, opening friends tab (new steam chat) etc. It also applies for every game i opened, not just borderlands 2.

**Comment by conrev** [comment] 2018-06-28 03:21
I have retested this with the 27th June build, which has this on the changelog:
"Fixed some more cases where the friends list and chat windows would not appear in the in-game overlay for some games"

unfortunately, on my case it's still not functional.

**Comment by LDD19** [comment] 2018-06-28 14:08
My friends tab is straight up not showing up when clicking on it and the web browser just shows a black box, even after clearing the cache and cookies. If you're low on funds, there's no way to make in-game purchases because you can't add funds in-game.

**Comment by sizeofbool** [comment] 2018-06-29 05:22
Same issue. Friends List doesn't open in Steam In-Game Overlay. "Friends&Chat" button does nothing.
Also Web browser, Steam Community Forums, Storefront pages are show up as empty windows with black background.

Everything mentioned above is working fine outside Steam In-Game Overlay.
This issue showed up after a couple Steam Client updates. Everything worked fine around two days ago.

CPU: i5-6600
RAM: 16Gb
VGA: nVidia GTX1060 6Gb (Proprietary driver 384.130)
OS: GNU\Linux Debian 9 'stretch' x86_64 (Kernel 4.15.11-1~bpo9+1 (2018-04-07))
DE: Xfce 4.12 (lightdm + xfwm4 with Compositor enabled)
Latest up-to-date Steam Client Beta installed.

**Comment by kisak-valve** [comment] 2018-06-29 22:59
Per "Fixed Friends and Chat windows not displaying in the in-game overlay on Linux and macOS" in the [2018-06-29](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1689296019097021490) Steam client beta update, please confirm your steam client is up to date and retest this issue.

**Comment by conrev** [comment] 2018-06-30 02:40
I can confirm that the overlay features are fixed in the latest beta.

**Comment by kisak-valve** [comment] 2018-06-30 17:37
Thanks for retesting, closing as fixed.

**Closed by kisak-valve** 2018-06-30 17:37 UTC
Labels: 3rd party game, Need Retest, overlay
