### ISSUE TITLE
Linux steam client beta causes pak errors in csgo

### ISSUE THREAD

**Issue by af7567** [ValveSoftware/steam-for-linux#3810] opened 2015-04-24 04:01 UTC
This is not a csgo problem like I thought, it is a steam client beta problem.  I have been using the beta for a long time and since getting csgo I had pak file errors at least once a week.  Today I couldn't fix it by deleteing/redownloading and ended up with a 2 hour ban and decided to play around a bit.  Completely reinstalling to a different disk didn't help and I still had the error on the same pak file.  Turning off steam client beta participation (and restarting steam) seems to have fixed it though.  I also did a file verification after disabling beta to be sure.

**Comment by evil-genius9000** [comment] 2015-04-24 15:13
Confirmed. ValveSoftware/Counter-Strike-Global-Offensive#328 refers.

**Comment by martino-valve** [comment] 2015-04-24 17:03
Did you try to "verify integrity of game cache" before switching back to the regular client ?

**Comment by Rika-chan** [comment] 2015-04-24 18:34
@martino-valve I had tried verification of game cache multiple times, and it would find nothing wrong with the files.

Switching back to the regular client seemed to have fixed it for some reason

**Comment by SoftwareSchlosser** [comment] 2015-04-25 13:11
I can confirm that switching back to non-beta steam client solves that issue.

**Comment by xypiie** [comment] 2015-04-25 18:07
I had the same problem on two computers, after switching out of beta, it's running fine again.

**Comment by donovan** [comment] 2015-04-26 04:07
I have been having this issue on SteamOS where I am a beta participant. This issue was not occurring about 2 weeks ago on on the same system.

I was getting: "Pure server: file [GAME]\pak01_040.vpk does not match the server's file." after a min of playing csgo. I verified game files and the issue persisted. Checked the md5sum of the file:

36814b3628d83d1134b82e23252b5920   /home/steam/.local/share/Steam/SteamApps/common/Counter-Strike Global Offensive/csgo/pak01_040.vpk

Also the file had a mtime of 11 Dec which matches quite a few other csgo vpk files, I had none older than that but quite a few newer than 11Dec. The file contend had not changed in ages.

I then deleted the file and re-verified which caused a new pak01_040.vpk to be downloaded. Checked the checksum of the new file ... it is the same as the old one ( 36814b3628d83d1134b82e23252b5920 ).

Started playing csgo ...  played 1 round an then:

"Pure server: file [GAME]\pak01_039.vpk does not match the server's file."

Will opt out of beta and try again.

**Comment by Plagman** [comment] 2015-04-26 06:00
Confirmed with Linux Steam Beta client.

**Comment by Plagman** [comment] 2015-04-27 00:19
Looks like this is also a problem on Mac:

http://www.reddit.com/r/GlobalOffensive/comments/33vy7f/i_tried_reinstalling_i_tried_verifying_and_i/

I saw a few other similar reports as well.

**Comment by nahtnam** [comment] 2015-04-28 04:22
Same issue with Ubuntu 14.04 but with `[GAME]\pak01_008.vpk`. Tried reinstalling game, and verifying game files. No luck. Plz fix.

**Comment by maurition** [comment] 2015-05-01 16:56
Confirm Issue on ubuntu 15.04 with steam beta. Will try without beta.

**Comment by martino-valve** [comment] 2015-05-01 17:04
Can you confirm that the SHA of the pak file acutually doesn't change when switching back to release Steam client ?

**Comment by idk** [comment] 2015-05-01 19:02
.pak files look unchanged. Checked the .pak files with sha256sum within Beta and Regular Steam client: https://www.diffchecker.com/1sy95j48

Using the Beta client one can play the local (Offline) maps just fine but when connect to remote (Valves) servers the 1st thing I notice is the motd is missing the image, it is just greyed out instead, then once game starts sometimes it's missing textures showing ERROR textures or it will play for a while but then get kicked out of game with the pak error.

Let us know if we can help further.

**Comment by donovan** [comment] 2015-05-02 01:02
Checked pak file hashes on my SteamOS and Trusty installs:

Trusty Not Beta:
user@trusty:~$ find ~/.steam/steam/SteamApps/common/Counter-Strike\ Global\ Offensive/csgo -maxdepth 1 -type f -name '*.vpk' -exec sha1sum {} \; | awk '{print $4 " " $1}' | sort | sha1sum 
50c551632377f96fda04b5112746fde4b1a8ad96  -

SteamOS Not Beta:
desktop@steamos:~$ find /home/steam/.local/share/Steam/SteamApps/common/Counter-Strike\ Global\ Offensive/csgo -maxdepth 1 -type f -name '*.vpk' -exec sha1sum {} \; | awk '{print $4 " " $1}' | sort | sha1sum
50c551632377f96fda04b5112746fde4b1a8ad96  -

SteamOS Beta*:
desktop@steamos:~$ find /home/steam/.local/share/Steam/SteamApps/common/Counter-Strike\ Global\ Offensive/csgo -maxdepth 1 -type f -name '*.vpk' -exec sha1sum {} \; | awk '{print $4 " " $1}' | sort | sha1sum
50c551632377f96fda04b5112746fde4b1a8ad96  -

Rebooted after opting in to beta.

Can confirm I also get the grey motd reported by idk, do not get this when not signed up to beta.

**Comment by idk** [comment] 2015-05-02 06:50
Confirming that this issue appears to have been fixed with the May 01 Beta Client update.

**Comment by donovan** [comment] 2015-05-02 08:03
Fixed for me.

**Closed** 2016-06-05 19:24 UTC
Labels: reviewed, Steam client
