### ISSUE TITLE
libGL error: failed to load driver: i965

### ISSUE THREAD

**Issue by orschiro** [ValveSoftware/steam-for-linux#4694] opened 2016-11-06 13:59 UTC
#### Your system information

* Steam client version: steam-launcher 1.0.0.53
* Distribution (e.g. Ubuntu): 16.10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes 
* Machine: Thinkpad X230 with i965 graphics card

#### Please describe your issue in as much detail as possible:
```
orschiro@x230:~$ steam
Running Steam on ubuntu 16.10 64-bit
STEAM_RUNTIME is enabled automatically
/bin/bash: /home/orschiro/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
awk: /home/orschiro/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.7)
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
Installing breakpad exception handler for appid(steam)/version(1476379980)
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
```

#### Steps for reproducing this issue:

1. Install steam on Ubuntu 16.10
2. Run `steam` in the terminal

**Comment by gdrewb-valve** [comment] 2016-11-06 17:43
Duplicate of Steam runtime issues, check out #4664 and others for workarounds.

**Closed by gdrewb-valve** 2016-11-06 17:43 UTC

**Comment by jsroyal** [comment] 2017-02-26 05:19
jsroyal@Hp:~$ chmod +x genymotion-2.8.1_x64.bin
jsroyal@Hp:~$ ./genymotion-2.8.1_x64.bin
Installing for current user only. To install for all users, restart this installer as root.

Installing to folder [/home/jsroyal/genymotion]. Are you sure [y/n] ? y


- Trying to find VirtualBox toolset .................... OK (Valid version of VirtualBox found: 5.0.32_Ubuntur112930)
- Extracting files ..................................... OK (Extract into: [/home/jsroyal/genymotion])
- Installing launcher icon ............................. OK

Installation done successfully.

You can now use these tools from [/home/jsroyal/genymotion]:
 - genymotion
 - genymotion-shell
 - gmtool

jsroyal@Hp:~$ cd genymotion/
jsroyal@Hp:~/genymotion$ ./genymotion
Logging activities to file: /home/jsroyal/.Genymobile/genymotion.log
libGL error: unable to load driver: r600_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r600
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
