### ISSUE TITLE
Please make a 64-bit linux steam client ?

### ISSUE THREAD

**Issue by linuxcbon** [ValveSoftware/steam-for-linux#4235] opened 2016-01-04 06:15 UTC
Many people use a 64-bit linux now.
Please make a 64-bit linux steam client ?

**Comment by gdrewb-valve** [comment] 2016-01-04 06:40
Duplicate of #179.

**Closed by gdrewb-valve** 2016-01-04 06:40 UTC
Labels: duplicate, reviewed

**Comment by baryluk** [comment] 2019-10-15 18:45
Could we please reopen this instead, at least for tracking?

The explanation given on #179 is not satisfactory or sound at all. The bug wasn't about dropping 32-bit runtime or support for 32-bit game, but about the Steam Client itself.

Almost all games I own are 64-bit only, and I do consciously refuse to buy 32-bit games. So, it would be really nice for me to be able to install Steam and games I know are 64-bit only, with zero 32-bit dependencies on my distro, system, if possible, or even with no 32-bit support in kernel. Steam Client is still free to download 32-bit runtimes, I don't care about that much.

It would be very beneficial to everybody for the Steam Client itself to be 64-bit. It is fine for the 64-bit Steam Client to provide 32-bit runtime for 32-bit games, but the Steam Client should be native arch if possible.

I of course don't know exact figures of Linux (not Windows) users running Steam Client on 32-bit hardware and 32-bit kernel. But I would be surprised if it is more than 0.2%. Sure, they need to be cared for, but some transitional period with both versions could be provided too. I would also guess, Steam Client is pretty robust in terms of code portability, considering existence of macOS version, which I am guessing is 64-bit only?

```
user@debian:~$ uname -a
Linux debian 5.2.0-3-amd64 #1 SMP Debian 5.2.17-1 (2019-09-26) x86_64 GNU/Linux
user@debian:~$ for pid in $(pidof steam); do file -L /proc/$pid/exe; done
/proc/32400/exe: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=2ee25e952921cb672d1d18abcb24505e5b805432, not stripped
/proc/32279/exe: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=2ee25e952921cb672d1d18abcb24505e5b805432, not stripped
user@debian:~$ 
```

Not good. "Valve please fix".

**Comment by baryluk** [comment] 2019-10-15 18:48
The last statement of the #179, even says:

> Whether the Steam client graphical interface component itself gets ported to 64-bit is a different question altogether, and is largely irrelevant as the need for the 32-bit execution environment would still be there because of the many 32-bit games to support.

And THAT WAS exactly what the original bug was about. Some other people than original reported hijacked the bug issue for other purposes, unrelated to original bug report.

**Comment by kisak-valve** [comment] 2019-10-15 18:49
Hello @baryluk, you're looking for #3518.

**Comment by baryluk** [comment] 2019-10-15 18:50
Also AFAIK steam client is 32-bit, but actually it requires 64-bit support in user space and kernel. It will not run on 32-bit only OS. So my "0.2%" doesn't even apply. It is 0.0%.

**Comment by baryluk** [comment] 2019-10-15 18:50
@kisak-valve Thank you. I will check that.
