### ISSUE TITLE
[Remote Play Together] Black screen when games run via Proton and use Vulkan

### ISSUE THREAD

**Issue by Henning0** [ValveSoftware/steam-for-linux#6656] opened 2019-11-06 14:01 UTC
#### Your system information

* Steam client version (build number or date): Nov 6 2019 03:10:37
* Distribution (e.g. Ubuntu): Manjaro Linux ([System Info](https://gist.github.com/Henning0/fe5f6452d8e1652fe3eb6bef71d79390))
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I wanted to play Degrees of Separation with a friend via Remote Play Together, but my friend only gets a black screen or a waiting screen with the game banner all over it. Before that I successfully tested The Cave and Rocket League with my friend.

I started testing other games and I think any game running through Proton and Vulkan has this problem. It doesn't matter if its via DXVK/D9VK or a native Vulkan renderer. On the other hand, native Linux games with a Vulkan renderer should be fine.

I ended up with this list of working or not working combinations:

##### Working:
- The Cave (Native / OpenGL)
- The Cave (Proton / WineD3D)
- Rocket League (Native / OpenGL)
- Shift Happens (Proton / WineD3D)
- Serious Sam Fusion 2017 (Native / Vulkan)
- Jamestown (Proton / OpenGL)

##### Not working:
- The Cave (Proton / D9VK)
- Degrees of Separation (Proton / DXVK)
- Shift Happens (Proton / D9VK)
- Serious Sam Fusion 2017 (Proton / Vulkan)

#### Steps for reproducing this issue:

1. Start a game via Proton which runs via the Vulkan-API, including games via DXVK/D9VK
2. Invite a friend to Remote Play Together
3. The friend gets a black screen or a waiting screen with the game banner, but can hear the game sound

**Comment by kisak-valve** [comment] 2019-11-06 14:20
Hello @Henning0, this is most likely a duplicate of #5770. Closing in favor of the existing issue report.

**Comment by kisak-valve** [comment] 2019-11-06 16:37
Re-opening per https://github.com/ValveSoftware/steam-for-linux/issues/5770#issuecomment-550392656.

**Comment by fallenguru** [comment] 2019-11-08 19:51
Have you tried pinning one the non-working games to a lower Proton version?

**Comment by Henning0** [comment] 2019-11-09 15:59
Hello @fallenguru. That was a good hint. I didn't think of this option while testing.

And actually an older version helps. With Proton 4.2-9 or lower my friend receives a image. Tested with Degrees of Separation and Serious Sam Fusion 2017.

**Comment by fallenguru** [comment] 2019-11-09 17:06
You're welcome. Proton 4.11 doesn't like Remote Play all that much for me, either, see #6516.

I just noticed I actually own The Cave and can reproduce: Native it streams fine [regular Remote Play All Alone], with 4.11 it stays at the new loading screen with the blue "progress wheel" at the bottom right, though I do have audio. 4.2 and 4.19 are fine. So, really similar to #6516, only with Prey I get the host's desktop instead of the loading screen.

(BTW, for some reason, The Cave seems to be capped at 30 FPS for me, native and Proton.)

**Comment by kisak-valve** [comment] 2019-11-09 20:39
Glad to hear you found a working setup @Henning0. I think that this issue is covered between #5770 and #6516. 

Closing in favor of the older issue reports.

**Closed by kisak-valve** 2019-11-09 20:39 UTC
Labels: Streaming
