### ISSUE TITLE
Print button doesn't work

### ISSUE THREAD

**Issue by Yanpas** [ValveSoftware/steam-for-linux#4355] opened 2016-03-15 09:47 UTC
I've just activated game via key. Print button doesn't do anything. I'm using Linux Mint 17.3 (based on ubuntu 14.04) system-config-printer is installed. Sysinfo: https://gist.github.com/Yanpas/99842e1885b36b20d2c8
Screenshot 
![_2016-03-15_12-44-59](https://cloud.githubusercontent.com/assets/7345761/13773760/19ab4266-eaac-11e5-8ecb-2ce4314f6d14.png)

**Comment by Tele42** [comment] 2016-03-15 14:41
As a basic check, do you have 32 bit cups libraries? Can you print (or at least detect the printer) from any 32 bit appliction?

**Comment by Yanpas** [comment] 2016-03-15 15:13
libcups2:i386 was already installed. I have also installed leafpad:i386 and I am able to print. Can you suggest any place in steam where I can test print dialog? (I've closed those windows of promocode)

**Comment by HileV** [comment] 2016-03-15 15:56
О русский )

**Comment by ViBENo1** [comment] 2016-03-15 16:11
same here. i thought it's an already reported and known bug, lol.

**Comment by gdrewb-valve** [comment] 2016-03-15 19:01
Duplicate of #252.

**Closed by gdrewb-valve** 2016-03-15 19:01 UTC
Labels: duplicate, reviewed
