### ISSUE TITLE
aimtux detected

### ISSUE THREAD

**Issue by awesomememe** [ValveSoftware/steam-for-linux#5110] opened 2017-07-31 13:55 UTC
Your system information

Steam client version (build number or date): latest
Distribution (e.g. Ubuntu): SteamOS because novac on linux
Opted into Steam client beta?: [Yes/No] no beta is for fags
Have you checked for system updates?: [Yes/No] no how to do it
Please describe your issue in as much detail as possible:

Describe what you expected should happen and what did happen. Please link any large code pastes as a Github Gist
1 vac ban on record

Steps for reproducing this issue:

install csgo, go to GE, get $$ and skins
install aimtux
1 VAC-Ban on record https://steamcommunity.com/profiles/76561198173426483/

**Comment by GreenByteSoftware** [comment] 2017-07-31 13:58
VAC-Ban is a special status and you should be proud of it.

**Comment by GreenByteSoftware** [comment] 2017-07-31 13:59
Other than that, this seems like a duplicate.

**Comment by kisak-valve** [comment] 2017-07-31 14:01
Duplicate of #5109.

**Closed by kisak-valve** 2017-07-31 14:01 UTC
