### ISSUE TITLE
Plans for broadcasting in Linux?

### ISSUE THREAD

**Issue by CrackedCrafterz** [ValveSoftware/steam-for-linux#5844] opened 2018-10-16 10:51 UTC
Hello,

there are news about the broadcasting in steam on Linux?

on the FAQ page (https://support.steampowered.com/kb_article.php?ref=6730-TOAK-6497#17)
is written that will come in the future but when?

We are waiting since 2014 or longer :(

**Comment by kisak-valve** [comment] 2018-10-16 12:44
Closing as a duplicate of #5275.

**Closed by kisak-valve** 2018-10-16 12:44 UTC
