### ISSUE TITLE
friends window not in focus when clicking "view friends" button

### ISSUE THREAD

**Issue by kaesekrokette** [ValveSoftware/steam-for-linux#374] opened 2012-12-24 23:37 UTC
steps to reproduce:
-open steam
-open friends list
-change focus to main steam window so that the friends list is in background (make sure the friends list window is actually <i>behind</i> the main window, not next to it)
-click on "view friends" button to bring it to the fore again

result: friends list is in foreground, but not in focus

If friends list is closed initially and you open it the first time or if you change to the friends list window by clicking on the tab in taskbar, it's working fine.

tested both with Linux Mint 13 64bit and Ubuntu 12.04 32bit

**Comment by kisak-valve** [comment] 2017-03-28 22:21
Closing as the main issue appears to have been fixed. Additionally, for the follow up issue with KDE 4, KDE 4 has been retired by upstream, and I am unable to reproduce the quirk behavior with KDE 5. It is highly unlikely that there will be a fix coming for KDE 4 if this still applies.

**Closed by kisak-valve** 2017-03-28 22:21 UTC
Labels: reviewed, Steam client
