### ISSUE TITLE
Can't move 'Total War: Warhammer' to another Steam folder.

### ISSUE THREAD

**Issue by YevPo** [ValveSoftware/steam-for-linux#4851] opened 2017-02-07 19:10 UTC
#### Your system information

* Steam client version (build number or date): Feb 3 2017
* Distribution (e.g. Ubuntu): Ubuntu 16.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Next error appears when I try to move 'Total War : Warhammer' to another Steam folder:

> 'Failed to move all files to new library folder (I/O Operation Failed).'

#### Steps for reproducing this issue:

1. Install Total War: Warhammer on first disk drive.
2. Create Steam content folder on second disk drive.
3. Try to move the game to that folder via 'Properties -> Local Files -> Move Install Folder...'.

Here is an excerpt from content_log.txt:

>[2017-02-07 21:04:36] AppID 364360 moving from "/media/Files/eugene/Steam/steamapps/common/Total War WARHAMMER" to "/home/eugene/SteamGames/steamapps/common/Total War WARHAMMER"
[2017-02-07 21:04:36] Finished uninstall script before moving folders
[2017-02-07 21:04:36] AppID 364360 state changed : Fully Installed,Moving Folder,
[2017-02-07 21:04:50] HTTP (CS,510) - valve510.steampipe.steamcontent.com (valve510.steamcontent.com): Closing connection
[2017-02-07 21:04:50] HTTP (CS,507) - valve507.steampipe.steamcontent.com (valve507.steamcontent.com): Closing connection
[2017-02-07 21:04:52] HTTP (CS,511) - valve511.steampipe.steamcontent.com (valve511.steamcontent.com): Closing connection
[2017-02-07 21:04:56] Failed copying file "/home/eugene/SteamGames/steamapps/common/Total War WARHAMMER/share/data/data/data.pack" (3913104960 bytes)
[2017-02-07 21:04:56] Canceled Moving App 364360 : I/O Operation Failed at 672027385/35036905426 bytes, 85 files (Unknown)
[2017-02-07 21:04:56] AppID 364360 state changed : Fully Installed,

Additional info:
- It always fails at the same position - 672027385
- I successfully moved other games(Mad Max and Super Meat Boy) to that new folder.
- Both drives have ext4 file system.
- First drive(source) is HDD, second - SSD.

**Comment by sysms** [comment] 2017-02-10 22:48
I can confirm this problem for some more titles, not only "TW: WH".

Affected games are e. g.:

- The Witcher 2 (trying to move from HDD to SSD)
- This is the Police (trying to move from SSD to HDD)

I've fscked my drives, they have no errors.

**Comment by sysms** [comment] 2017-03-25 12:49
Any progress here? This problem still exists in the latest beta client (1490314264)...

**Comment by Poil** [comment] 2017-06-04 15:27
I have the same problem when installing this mod 552761829

**Comment by saward** [comment] 2017-08-28 11:43
Having the same issue.

**Comment by saward** [comment] 2017-09-02 04:45
I was able to successfully move the folder by going into the Total War installed folder, and moving the 'share' folder temporarily somewhere else on the hard drive.  With that out of the way, steam happily moved the remaining files/folders.  I then moved the missing 'share' folder into the new location where it should be.

I've also previously had issues with patches not installing when using a symlink to put these files on this drive, so will need to wait to see if it patches while on this hard drive.

**Comment by saward** [comment] 2017-09-17 06:18
I have tried a new SSD, and the same problem persists.

**Comment by thackel** [comment] 2017-12-23 20:12
I can confirm the same problem with "HITMAN" on Kubuntu 17.10, Steam Beta Client 2017-12-20.
After 33% i get the IO Error, no other output in the console.

I could move other games of different sizes from/to SSD/HDD.

**Comment by timcarr89** [comment] 2018-10-03 10:27
Just checked a game that I was having trouble moving and it had a file bigger than 2GB. Moved several other games that did not have files larger than 2GB and they were fine. Ran your command on my steamapps/common folder and attempted to move the games with 2GB+ files and every one I tried failed.

**Comment by kakra** [comment] 2018-10-03 11:30
Can you amend the title then to take note of this being the issue? Thanks.

**Comment by paimoe** [comment] 2018-10-19 09:28
Can't move RUINER (464060) which includes a 4.9GB file

Might just have to reinstall on the SSD instead of moving

**Comment by rdrey** [comment] 2018-10-30 02:38
This also works for GTA5

**Comment by hlarsen** [comment] 2018-11-24 20:52
Same issue with Deus Ex: Mankind Divided, which has a few > 2GB files.

**Comment by noobaldrin** [comment] 2018-12-25 15:46
Was able to successfully move a game with this issue.

Just move (mv) the large files temporarily to a new directory outside of steam installation, use find command to filter or large files larger than 2G or whatever command you see fit.
Then execute the move steam games on steam client, it'll ignore the missing files but once it completed it will still say the move has been successful.

Then manually place the large files to the appropriate directory in the new installation location.

**Comment by ThunderMikey** [comment] 2019-01-11 13:59
In addition to the comment by @noobaldrin , it is a good idea to turn off auto-update temporarily so that Steam does not start downloading missing files (the files to be moved manually).

**Comment by daxcore** [comment] 2019-03-10 11:08
Yeah same issue here. Deus Ex, Himan, HITMAN2, ... all games with files large than 2G.

**Comment by Managor** [comment] 2019-03-31 20:29
Bumping the thread as I just just experienced this by trying to move Quake champions from an NVME to a HDD but not when I tried to move Crash Bandicoot from a HDD to an NVME or when moving Dota 2 from NVME to HDD.

**Comment by okaestne** [comment] 2019-04-02 19:01
Having the issue as well with GTA 5. BTRFS -> ext4 partition.
Maybe this is a limitation of the 32-bitness of the steam client?

**Comment by TFoxxy** [comment] 2019-04-03 01:37
I attempted the fix posted by @noobaldrin with GTA V but Steam gave me a new error "Failed to move all files to new library (invalid state)".

**Comment by TFoxxy** [comment] 2019-04-03 17:34
Oops, I renamed the GTA V directory in order to find the 2GB+ files. Naming it back to the original and running the game once fixed it right up. After that, I can confirm that the above solution works with GTA V.

**Comment by dshoreman** [comment] 2019-04-26 00:09
One more "me too" for the collection - this time affecting Saints Row 2.

Moving files breaks with I/O failure, but after moving the 2.7GB `music4.vpp_pc` manually to a different folder it works fine.

**Comment by Vash63** [comment] 2019-04-26 16:02
I'm having this issue attempting to install the latest DLC for Assassin's Creed: Odyssey. For some reason Steam is storing the temporary download cache in a different library than the game install itself, so it has to migrate the data. 

This in itself wouldn't be an issue, but one library is btrfs and the other is f2fs - triggering this bug. It's failing on a 6.3GiB '.forge' file.

**Comment by tinfoil-hacks** [comment] 2019-04-27 03:48
Confirmed here too. Moving Wolfenstein: The Old Blood fails on a 2.1G file (~/.local/share/Steam/steamapps/common/Wolfenstein The Old Blood/virtualtextures/dlc1_c01_04_s1.pages). 

This is an old bug...

**Comment by phoe** [comment] 2019-04-27 13:32
Related discussion on /r/linux_gaming: https://www.reddit.com/r/linux_gaming/comments/bhyo8g/

**Comment by KibaGasteiz** [comment] 2019-04-27 14:17
Now i know why i can't move some games, at least now i know that i should copy the games by myself.

**Comment by qarmin** [comment] 2019-04-27 19:10
This reminds me bug in Godot Engine https://github.com/godotengine/godot/issues/21677 which limitation was caused by using int 32bit (-2,1 GB to 2,1 GB) instead int 64bit

**Comment by tinfoil-hacks** [comment] 2019-04-28 18:27
https://github.com/tinfoil-hacks/steam-mv

I wrote a quick Python script that handles moving games/apps between Steam folders.

**Comment by kisak-valve** [comment] 2019-05-15 23:19
Hello, per "Fixed a bug where copying/moving files bigger than 2GB would fail with an I/O error" in the [2019-05-15](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1611638091301723544) Steam client beta update, please opt into Steam's beta client and retest this issue.

**Comment by tinfoil-hacks** [comment] 2019-05-16 01:03
Works, though the window with Library selection menu/progress bar doesn't close until you close the window underneath it (Properties menu).

**Comment by kisak-valve** [comment] 2019-05-16 01:06
Thanks for testing @tinfoil-hacks. Can you open a new issue report for the followup issue so it can be tracked properly?

**Comment by tinfoil-hacks** [comment] 2019-05-16 01:14
Yes. Thanks for your hard work, @kisak-valve. Your reputation precedes you.

**Comment by Vash63** [comment] 2019-05-16 01:19
My issue relating to this was fixed also.

**Comment by tinfoil-hacks** [comment] 2019-05-16 01:22
@kisak-valve https://github.com/ValveSoftware/steam-for-linux/issues/5466

This is my issue. I can add more detail there.

**Comment by kisak-valve** [comment] 2019-06-21 15:08
Closing as fixed.

**Closed by kisak-valve** 2019-06-21 15:08 UTC
Labels: Need Retest, Steam client
