### ISSUE TITLE
Closing any Steam window via WM shuts steam down [i3]

### ISSUE THREAD

**Issue by mist** [ValveSoftware/steam-for-linux#5503] opened 2018-05-27 15:16 UTC
#### Your system information

* Steam client version (build number or date): May 18, 14:50:44 / 1526683293
* Distribution (e.g. Ubuntu): Debian testing
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* `i3 version 4.15`

Operating System Version:
    Debian GNU/Linux testing (buster) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.16.0-1-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  i3
    Steam Runtime Version:  steam-runtime-beta-release_2017-10-05

#### Please describe your issue in as much detail as possible:
When closing any steam window via Win+Shift+q I get the "Steam is shutting down" window and steam quits. This happens always, even when there are plenty other steam windows open.
From `man i3`: `Kills the current window. This is equivalent to "clicking on the close button", meaning a polite request to the application to close this window. For example, Firefox will save its session upon such a request. If the application does not support that, the window will be killed and it depends on the application what happens.`

I'd expect the window to close like when pressing the X in the top right corner.

This is probably related to: #53 #5157 #5433 #2685

#### Steps for reproducing this issue:

1. Open Steam
2. Open any window from steam (friendlist, messages, main window, ...)
3. Use WM to close the window (here: i3)

**Comment by kisak-valve** [comment] 2018-05-27 17:30
Hello @mist, this is functionally a duplicate of the issue reports you've mentioned. I'm going to arbitrarily pick #2685 as the direct match for Steam completely closing on the WM asking for the window to be closed. Feel free to add your experience to that issue report.

Closing in favor of #2685.

**Closed by kisak-valve** 2018-05-27 17:30 UTC

**Comment by mist** [comment] 2018-05-27 17:35
Well, I read #2685 as the main window only („Press alt+f4 when focused on the main steam window.“), so  #5157 („but when middle clicking on the main window the issue still exists.“).
Sorry for opening a duplicate though.
